### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by mobilegmYT** [Botspot/pi-apps#10]
Hello. For the GUI that displays if a program is installed or not, I think it would be better to display the icons based on if the programs folder or whatever existed, instead of tracking it in the app store.

**Comment by Botspot** [comment]
So do you mean if the Arduino app is not installed, we shouldn't display the Arduino icon in the app list? But just the Arduino text only?

**Comment by Botspot** [comment]
Oh, I see what you mean, a more direct way to check if something is installed.
Like if /home/pi/Arduino exists, then Pi-Apps assumes the Arduino app is installed.
I thought long and hard about this, but eventually decided not to do it for one reason:

- Confusion.

You might notice there are 2 similarly-named apps: 'FreeCAD' and 'FreeCAD (Precompiled)'.
One is more portable but takes hours to compile, the other is already compiled. Both install the exact same App.
So how would Pi-Apps know which one had been installed?
Back to the first example Arduino. Pi-Apps' version is newer, but ultimately installs the same files as the repository's Arduino. Also, a user may decide to compile Arduino outside of the realms of Pi-Apps.
And they would be rightfully confused if Pi-Apps suddenly showed Arduino as being installed.

**Comment by mobilegmYT** [comment]
Ooh that makes more sense.
