### ISSUE TITLE
Zoom is not in any category from my Raspberry Pi menu after installing it.

### ISSUE THREAD

**Issue by fabianmendes** [Botspot/pi-apps#100]
> Sorry, excuse me. Where should I see Zoom after installing it? There is not in any category from my Raspberry Pi menu :$

Maybe it didn't install correctly. Please open a new issue for that.

_Originally posted by @Botspot in https://github.com/Botspot/pi-apps/issues/52#issuecomment-734325524_

**Comment by Botspot** [comment]
Thank you.

Let's check if the menu button file exists by running this command:
```
file /home/pi/.local/share/applications/zoom.desktop
```
If it exists, it will tell you what type of file it is. If it does not exist, it will say "no such file or directory".

**Comment by fabianmendes** [comment]
That's right, "no such file or directory"

**Comment by fabianmendes** [comment]
Take a look:
![2020-11-26-172043_800x480_scrot](https://user-images.githubusercontent.com/31230743/100392076-c8688a80-300b-11eb-9458-d96c5b7f0138.png)
![2020-11-26-172026_800x480_scrot](https://user-images.githubusercontent.com/31230743/100392080-cacae480-300b-11eb-9690-c9c2defef791.png)

**Comment by Botspot** [comment]
That's the problem. "/root/zoom already exists on your system."

Why are you launching Pi-Apps with `sudo`?

**Comment by fabianmendes** [comment]
> That's the problem. "/root/zoom already exists on your system."
> 
> Why are you launching Pi-Apps with `sudo`?

Oh, so what can I do then? 
Because installing packages it said to me that it hasn't permission (I don't remember which of the apps did)

**Comment by Botspot** [comment]
> Oh, so what can I do then?

Run Pi-Apps the way it was intended - from the menu.

If you find the permission denied error again, I can help you more with that in a new issue.
