### ISSUE TITLE
General Discussion on binary based installs and automatic updating

### ISSUE THREAD

**Issue by theofficialgman** [Botspot/pi-apps#1019]
install becomes as simple as this
```
echo "Removing previous legacy Discord installs..."
sudo dpkg -r electron-discord-webapp

wget -qO- http://download.tuxfamily.org/webcordapt/add-repo.sh | sudo bash
sudo apt install webcord -y
```

alternatively, if you want to keep the manual download deb process,  how about automate the version and grab the latest?

the l4t-megascript used to do this before we moved to the apt repo (https://github.com/cobalt2727/L4T-Megascript/blob/master/scripts/discord.sh) its commented out incase we ever want to go back to it

```
echo "Downloading the most recent .deb from SpacingBat3's repository..."
curl -s https://api.github.com/repos/SpacingBat3/WebCord/releases/latest \
  | grep "browser_download_url.*arm64.deb" \
  | cut -d : -f 2,3 \
  | tr -d \" \
  | wget -qi -

echo "Done! Installing the package (and maybe fixing dependencies)..."
sudo dpkg -i *arm64.deb
sudo apt --fix-broken install -y

cd ..
rm -rf discord-tmp/
```
(you could modify to use the pkg-install of course)

**Comment by Botspot** [comment]
> alternatively, if you want to keep the manual download deb process, how about automate the version and grab the latest?
> ```
> echo "Downloading the most recent .deb from SpacingBat3's repository..."
> ```

Many people ask us the same question: "Why don't the installation scripts in Pi-Apps always grab the latest release from Github?" "Why is the url hardcoded?" "This is not future-proof."
The answer: **updates.** The next time SpacingBat3 uploads a new version, we will change the URL in the script to point to the new version. That change to the installation script will trigger an update for all of our Pi-Apps users. During that update, because the install script was modified, everyone's Discord app will be **reinstalled**, thereby updating everyone to the new version.

Suppose we changed the script to always point to SpacingBat3's latest release. Then there would be no update. People who had Discord installed prior to this will never be notified and will never receive the new version.

Ironically, by creating a way to keep Discord up-to-date without editing the script each time, **it would actually keep everybody out-of-date.**

Concerning your apt repository, yes that may be workable - a way to update the Discord app outside of Pi-Apps. But I hesitate to do that for three reasons:

- More complication.
  - Suppose SpacingBat3 releases a new version of WebCord that **crashes**. It malfunctions in some way. With our current setup we could simply roll-back the URL to SpacingBat's older release.
  - But if Pi-Apps was using a repository for webcord, I would not be able to do that. I'd have to ask the repository's maintainers to fix the problem.
  - This actually happened recently with the Box86 app. For that app we use Itai's Box86 apt-repository. Box86 broke Zoom, due to a recent bug in the source code. Box86 was quickly fixed, but Itai was away and couldn't trigger another deb build. So all of our Zoom users had to **wait** until Itai's Pi automatically rebuilt Box86. And this whole time there was nothing I could do to fix the situation.
- APT issues.
  - I don't know how it happens, but some people just mess up their systems so that an added repository causes errors or fails to be signed.
  - Right now WebCord very rarely triggers an error-report because of its simplicity. Other, more problematic apps have to download multiple things, while WebCord is a single deb package.
- If it already works, don't fix it! :)

**Comment by theofficialgman** [comment]
I'll show an example of what I have in mind once I get some more time

**Comment by Botspot** [comment]
Yes, it will certainly need to be decided on a case-by-case basis.

**Comment by Crilum** [comment]
This is an example of a script that would reside in an app folder and get run by the `updater` script:

```
#!/bin/bash

# Pi-Apps update script example for Github Release based updating -- this script will update btop
# -- by Crilum, exept for the `get_release` code that was by someone else on GitHub..
# Note: requires the `jq` package to be installed: `sudo apt install jq`

# Source Pi-Apps api script, so Pi-Apps functions can be used
DIRECTORY=/home/pi/pi-apps
source $HOME/pi-apps/api
# Code for getting latest release version -- This would be added to the api script.. 
get_release() {
curl --silent "https://api.github.com/repos/$1/tags" | jq -r '.[0].name'
}
webVer=$(get_release aristocratos/btop)
localAppVer=v$(btop -v | sed 's/..............//')
# echo the versions
status "The latest online version is:  $webVer"
status "The current local version is:  $localAppVer"
echo
#Test to see if version is current:
if [ "$localAppVer" = "$webVer" ]; then
#If version is current do:
status_green 'Your version is current!'
else
#If version is not current do:
status 'The local version is not the same as the online version! Updating now.'
# Make dir for install files, and cd into it
mkdir $HOME/btop && cd $HOME/btop
# Download and install latest release
wget https://github.com/aristocratos/btop/releases/download/$webVer/btop-armv7l-linux-musleabihf.tbz
tar -xjf btop-armv7l-linux-musleabihf.tbz || error 'Failed to decompress "btop-1.0.24-armv7l-linux-musleabihf.tbz"!'
sudo make -B install || error 'Failed to install btop with "sudo make install"!'
echo
status_green 'Your new Version: '$localAppVer
# Clean up after install
rm -rf $HOME/btop || sudo rm -rf $HOME/btop || error 'Failed to remove install directory!'
fi
#!/bin/bash

# Pi-Apps update script example for Github Release based updating -- this script will update btop
# -- by Crilum, exept for the `get_release` code that was by someone else on GitHub..
# Note: requires the `jq` package to be installed: `sudo apt install jq`

# Source Pi-Apps api script, so Pi-Apps functions can be used
DIRECTORY=/home/pi/pi-apps
source $HOME/pi-apps/api
# Code for getting latest release version -- This would be added to the api script.. 
get_release() {
curl --silent "https://api.github.com/repos/$1/tags" | jq -r '.[0].name'
}
webVer=$(get_release aristocratos/btop)
localAppVer=v$(btop -v | sed 's/..............//')
# echo the versions
status "The latest online version is:  $webVer"
status "The current local version is:  $localAppVer"
echo
#Test to see if version is current:
if [ "$localAppVer" = "$webVer" ]; then
#If version is current do:
status_green 'Your version is current!'
else
#If version is not current do:
status 'The local version is not the same as the online version! Updating now.'
# Make dir for install files, and cd into it
mkdir $HOME/btop && cd $HOME/btop
# Download and install latest release
wget https://github.com/aristocratos/btop/releases/download/$webVer/btop-armv7l-linux-musleabihf.tbz
tar -xjf btop-armv7l-linux-musleabihf.tbz || error 'Failed to decompress "btop-armv7l-linux-musleabihf.tbz"!'
sudo make -B install || error 'Failed to install btop with "sudo make install"!'
echo
status_green 'Your new Version: '$localAppVer
# Clean up after install
rm -rf $HOME/btop || sudo rm -rf $HOME/btop || error 'Failed to remove install directory!'
fi
```
This should actually work, if you have btop installed.

@Botspot @theofficialgman  What do you think? It isn't as fast as the current method, it takes about one second to check for an update, so with roughly 50 apps in Pi-Apps that use Github to download the app (that's a guess), the update process would get pretty long, however, this makes Pi-Apps much more future-proof.

A script like this could be added for every app that installs from GitHub, and probably a lot of other apps too..

**Comment by theofficialgman** [comment]
yeah this looks about right for what I had in my for this type of github based install.
the only really unstable part of this has to do with the local btop version...

this might be a bit safer
`btop -v | sed 's/[^0-9.]*//g'`

**Comment by theofficialgman** [comment]
the only "slow" part of the script for me is when you call the github api
and there isn't anything you can do about that
only takes 0.25 seconds to run for me though

for some apps, I think this is a reasonable sacrifice to save the maintainers of pi-apps from having to update install script every time there is an update to a binary

**Comment by theofficialgman** [comment]
also btw, your script isn't good for apps that have pre-releases/betas because it grabs those too
an example is webcord https://github.com/SpacingBat3/WebCord/releases which has betas

you will have to do something closer to what I had above for that https://github.com/Botspot/pi-apps/issues/1019#issuecomment-938285267

**Comment by theofficialgman** [comment]
modify your get_release to this and you should be good
```
get_release() {
curl --silent "https://api.github.com/repos/$1/releases/latest" | jq -r '.name'
}
```

**Comment by theofficialgman** [comment]
here is my example for webcord
```
#!/bin/bash

# Pi-Apps update script example for Github Release based updating -- this script will update webcord
# -- by theofficialgman
# Note: requires the `jq` package to be installed: `sudo apt install jq`

# Source Pi-Apps api script, so Pi-Apps functions can be used
DIRECTORY=/home/pi/pi-apps
source $HOME/pi-apps/api
# Code for getting latest release version -- This would be added to the api script.. 
get_release() {
	curl --silent "https://api.github.com/repos/$1/releases/latest" | jq -r '.tag_name'
}
webVer=$(get_release SpacingBat3/WebCord)
localAppVer=v"$(dpkg -s webcord | grep "Version" 2>/dev/null | awk '{print $2}' | grep .)"
# echo the versions
status "The latest online version is:  $webVer"
status "The current local version is:  $localAppVer"
echo
#Test to see if version is current:
if [ "$localAppVer" = "$webVer" ]; then
	#If version is current do:
	status_green 'Your version is current!'
else
	#If version is not current do:
	status 'The local version is not the same as the online version! Updating now.'
	# Make dir for install files, and cd into it
	mkdir /tmp/webcord && cd /tmp/webcord
	# Download and install latest release
	case "$arch" in
		"64") arch-name="arm64";;
		"32") arch-name="armhf";;
		*) error "arch variable is not set, something is very wrong!"
	esac
	wget https://github.com/SpacingBat3/WebCord/releases/download/$webVer/webcord_2.2.0_$arch-name.deb
	sudo apt install ./webcord_2.2.0_$arch-name.deb || error 'Failed to install webcord with "sudo apt install"!'
	status_green 'Your new Version: '$localAppVer
	# Clean up after install
	rm -rf /tmp/webcord || sudo rm -rf /tmp/webcord || error 'Failed to remove install directory!'
fi
```

**Comment by cycool29** [comment]
Edited version of gman one.

```bash
#!/bin/bash

# Pi-Apps update script example for Github Release based updating -- this script will update webcord
# -- by cycool29
# Note: requires the `jq` package to be installed: `sudo apt install jq`

# Source Pi-Apps api script, so Pi-Apps functions can be used
DIRECTORY=/home/pi/pi-apps
source $DIRECTORY/api
# Code for getting latest release version -- This would be added to the api script.. 
get_release() {
	curl --silent "https://api.github.com/repos/$1/releases/latest" | jq -r '.tag_name' | sed s/v//g
}
webVer=$(get_release SpacingBat3/WebCord)
localAppVer=v"$(dpkg -s webcord | grep "Version" 2>/dev/null | awk '{print $2}' | grep .)"
# echo the versions
status "The latest online version is:  $webVer"
status "The current local version is:  $localAppVer"
echo
#Test to see if version is current:
if [ "$localAppVer" = "$webVer" ]; then
	#If the version is current do:
	status_green 'Your version is current!'
else
	#If version is not current do:
	status 'The local version is not the same as the online version! Updating now.'
	# Make dir for install files, and cd into it
	mkdir /tmp/webcord && cd /tmp/webcord
	# Download and install latest release
	case "$arch" in
		"64") arch_name="arm64";;
		"32") arch_name="armhf";;
		*) error "arch variable is not set, something is very wrong!";;
	esac
	wget https://github.com/SpacingBat3/WebCord/releases/download/v$webVer/webcord_${webVer}_${arch_name}.deb
	sudo apt install ./webcord_${webVer}_${arch_name}.deb || error 'Failed to install webcord with "sudo apt install"!'
	status_green "Your new Version: $webVer"
	# Clean up after install
	rm -rf /tmp/webcord || sudo rm -rf /tmp/webcord || error 'Failed to remove install directory!'
fi
```

**Comment by cycool29** [comment]
Now I think I can understand the concept. A conclusion here:

- What pi-apps implements now: Developers keep track of app updates, and when there are any updates, the install script is modified and triggered an update notification to users.
  - Advantages - Easy concept, developers controlling everything
  - Disadvantages - Huge workload to developers to check updates of each app

- Gman's proposal: Check and install updates on the client-side with a script.
  - Advantages - Fewer works on developers
  - Disadvantages - Out of developers' control

- Botspot's proposal: Check updates (and maybe testing) using GitHub Actions or automated scripts, update the install script on GitHub, and trigger updates to users.
  - Advantages - Fewer works on developers, developers controlling everything, easy to roll back updates
  - Disadvantages - (Currently I don't see any)

So I would prefer Botspot's proposal, it solves the disadvantages of the current pi-apps update process and includes the advantages of both Gman's proposal and the current pi-apps solution. 

@theofficialgman @Botspot Am I right?

**Comment by Crilum** [comment]
@cycool29 Yeah, that seems good. I could create a workflow doing what the above script does (mostly, we wouldn't need the update part), but I don't know how to make it change the Pi-Apps scripts if it detects an update...

**Comment by theofficialgman** [comment]
@cycool29 yes you have everything right

@Crilum the workflow for github actions using botspots idea would basically just run the update checks daily, then if an update was detected, the workflow itself would edit the version variable we currrently set in our install scripts, commit that change, and push to pi-apps

for users, it looks like we have manually edited the variable and everything works normally without needing to make any actual changes to pi-apps

**Comment by Crilum** [comment]
How would one edit a script without completely replacing it?
In this case the btop install script..

**Comment by theofficialgman** [comment]
@Crilum 
change the btop script so this uses a variable `wget https://github.com/aristocratos/btop/releases/download/v1.1.3/btop-aarch64-linux-musl.tbz `

```
version="v1.1.3"
wget https://github.com/aristocratos/btop/releases/download/${version}/btop-aarch64-linux-musl.tbz
```

then all you have to do is sed the script to replace the version= string
```
sed -i "s/version=.*/version=${webVer}/g" apps/btop++/install-64
```

**Comment by Crilum** [comment]
How's [this](https://github.com/Crilum/pi-apps/blob/AutoUpdate/.github/workflows/update-btop.yml)?

**Comment by theofficialgman** [comment]
@Crilum no thats not right
github actions runs within the github repo already, do not clone another one into it.
I'll take what you have started and make a PR with the changes integrated

**Comment by Crilum** [comment]
I can just change it real quick, if you want..

**Comment by Crilum** [comment]
I'm making a PR to update btop to 1.1.4, and add the version var.

**Comment by theofficialgman** [comment]
> I can just change it real quick, if you want..

nah I don't really like how you are laying out the actions
I was already working on my own before you sent something anyway

I think you will like what I have got once its done

> I'm making a PR to update btop to 1.1.4, and add the version var.

this needs to happen no matter what so go ahead

**Comment by Itai-Nelken** [comment]
Maybe the action should open a pr with the changes, just in case something goes wrong.

**Comment by theofficialgman** [comment]
> Maybe the action should open a pr with the changes, just in case something goes wrong.

yup I thought about that... that should be possible

**Comment by theofficialgman** [comment]
@Itai-Nelken @Crilum see my PR in progress https://github.com/Botspot/pi-apps/pull/1330

**Comment by Crilum** [comment]
@theofficialgman It looks good, the loop is a little confusing, I couldn't understand it, but I'm sure it works.

**Comment by theofficialgman** [comment]
I'll explain it (I do a very similar loop in the megascript)

> apps=( .github/workflows/updates/*.sh )

this creates an array containing the filepaths to all update script files (currently there is only btop++.sh)

> for app_directory in ${apps[@]}; do

this is start of the loop where only one of the scripts is operated on at once

> app_name=$(echo ${app_directory%.*} | sed 's:.*/::')

this just gets me the name of the app (btop++) instead of the whole filepath
