### ISSUE TITLE
Can't install anything it says Permission denied

### ISSUE THREAD

**Issue by fabianmendes** [Botspot/pi-apps#102]
Hi, I've tried to install again both apps: TBOplayer and Zoom, after uninstalling them.

![2020-11-26-183231_800x480_scrot](https://user-images.githubusercontent.com/31230743/100395334-e4255e00-3016-11eb-87b4-ebd4b272d7b1.png)
![2020-11-26-183248_800x480_scrot](https://user-images.githubusercontent.com/31230743/100395329-e1c30400-3016-11eb-96f9-c34f3bf18f53.png)
![2020-11-26-183546_800x480_scrot](https://user-images.githubusercontent.com/31230743/100395328-e091d700-3016-11eb-972f-8abb76311cd8.png)

**Comment by Botspot** [comment]
Why are you in `/home/pi/Downloads/git`?

Please use the official install instructions:
```
cd
git clone https://github.com/Botspot/pi-apps
~/pi-apps/install
```

**Comment by fabianmendes** [comment]
same, man 
![2020-11-26-190636_800x480_scrot](https://user-images.githubusercontent.com/31230743/100396209-ade9dd80-301a-11eb-908d-8884377abc7f.png)
![2020-11-26-190659_800x480_scrot](https://user-images.githubusercontent.com/31230743/100396214-b510eb80-301a-11eb-97b2-1d4d042c3bf7.png)
j;

**Comment by Botspot** [comment]
@fabianmendes Have you been copying over any files from the old install?

**Comment by fabianmendes** [comment]
No, I've unistalled zoom and tboplayer first. How can I remove pi-apps ans installing it over again from the start?

**Comment by Botspot** [comment]
Delete the whole `/home/pi/pi-apps` folder.

Then run the official install instructions:
```
cd
git clone https://github.com/Botspot/pi-apps
~/pi-apps/install
```

**Comment by fabianmendes** [comment]
OK, thanks. Let me see

**Comment by fabianmendes** [comment]
Done, thanks!

**Comment by Botspot** [comment]
Yay! I'm glad you've gotten it working.

**Comment by fabianmendes** [comment]
Yes, thanks to you twice. Also, I'm installing Steam (#36 ) to take a look on it. Great job, later OR tomorrow I'll try to make an app for Blender 2.7 (the only Last versión realease that works on raspberry pi). I'm glad you've creaste this thing.

I Wonder if it's possible to maje an app for WPS Office, many People are needing it. I'll open a New issue for that! (I have the ".deb" File bit I Just can't install it.. I hope you can instead, it need a couple of lib files.. But anyways I don't know too much abou it) #105
