### ISSUE TITLE
Purge Installed removes packages which were set to manually installed before running pi-apps

### ISSUE THREAD

**Issue by theofficialgman** [Botspot/pi-apps#1020]
how to replicate:
```sudo apt install cmake``` which sets cmake to manually installed

run a pi-apps script which does a pkg-install which overwrittes cmake to automatically installed instead of manually installed (VERY BAD)

run the uninstall script for a pi-apps script with purge-installed and cmake gets REMOVED even though it was manually installed before using pi-apps

this is very dangerous and could cause applications to not function, cmake was just the example used here

**Comment by Botspot** [comment]
Great question. I've explained this change on the commit summary page.
https://github.com/Botspot/pi-apps/commit/a2d7ef55f92c0cea384abb6d1fa48acc43d79e51#commitcomment-57623470
