### ISSUE TITLE
[FIX] Lunar Client on 64bit fixed for version 1.7 - 1.18 (all versions)

### ISSUE THREAD

**Issue by Chaosdave34** [Botspot/pi-apps#1030]
I found a way to get Minecraft 1.16 + 1.17 running with Lunar on 64bit Raspberry Pi OS:

1. rename `/opt/jdk/jdk-16.0.1+9-jre` to `/opt/jdk/jdk-16.0.1+9-jre64`
2. In this commit (https://github.com/Botspot/pi-apps/commit/8adba9a73b95755f43cd4f4ef50736a6c6af59fb) you removed libwebp-imageio64.so but it is needed for lunar on 64bit os
-> `wget -O ~/lwjgl3arm64/libwebp-imageio64.so 'https://github.com/gl91306/lunar/raw/master/libwebp-imageio64.so'`

Now Minecraft starts, BUT logging in to Microsoft Accounts is not working. It tells, that I need to update the launcher to the lates version.

**Comment by timof121** [comment]
gonna test if happens with pi-ware

**Comment by Chaosdave34** [comment]
EDIT: Fix for Minecraft 1.7 - 1.12.

Problem: lwjgl2arm64 folder is empty AND Lunar client always looks for lwjgl3arm64 folder even when starting 1.7-1.12
(Note: jdk folder name needs to be changed: `/opt/jdk/jdk-16.0.1+9-jre` to `/opt/jdk/jdk-16.0.1+9-jre64`)

1. Compile lwjgl2 (for this your default java MUST BE version 8
* `sudo apt install ant`
* `git clone https://github.com/lwjgl/lwjgl`
* `cd lwjgl`
* In platform_build/linux_ant/build.xml change `amd64` and `x86_64` to `aarch64`
* `ant generate-all`
* `ant compile`
* `ant compile_native`
2. Copy the needed files to lwjgl2arm64
* libs/linux/libopenal.so
* libs/linux/libopenal.so
* libs/linux/liblwjgl.so (copy this to lwjgl2arm64 folder as liblwjgl.so and liblwjgl64.so)
3. Download libwebp
* `wget -O ~/lwjgl2arm64/libwebp-imageio64.so 'https://github.com/gl91306/lunar/raw/master/libwebp-imageio64.so'`

 When starting 1.7 - 1.12 rename the lwjgl2arm64 folder to lwjgl3arm64. (Do not delete the real lwjgl3arm64 folder, just rename it to something like lwjgl3arm64_old).
 When starting 1.16-1.18 just  undo the above step.

**Comment by Chaosdave34** [comment]
> > 2. In this commit ([8adba9a](https://github.com/Botspot/pi-apps/commit/8adba9a73b95755f43cd4f4ef50736a6c6af59fb)) you removed libwebp-imageio64.so but it is needed for lunar on 64bit os
> >    -> `wget -O ~/lwjgl3arm64/libwebp-imageio64.so 'https://github.com/gl91306/lunar/raw/master/libwebp-imageio64.so'`
> 
> why tf would libwebp-imageio64.so be needed
> 

Try starting Lunar without libwebp. It will crash and the crash report in .minecraft folder tells you, that libwebp is needed.

**Comment by theofficialgman** [comment]
closing because I "think" it works right now
