### ISSUE TITLE
Ipscan not working in Bullseye

### ISSUE THREAD

**Issue by feadog1** [Botspot/pi-apps#1045]
Angry ip scanner not running under bullseye rpi-os rpi4. 
Error message " failed to load native code. Cannot load 64bit swt libraries on 32 bit JVM"

While I know bullseye is not fully supported, it would be nice to see this working as in Buster.
Thanks

**Comment by norambna** [comment]
Hi! I got the same problem on a freshly installed Raspberry Pi OS Bullseye 32-bit.

**Comment by Itai-Nelken** [comment]
maybe this helps: https://stackoverflow.com/questions/11022600/cannot-load-64-bit-swt-libraries-on-32-bit-jvm-replacing-swt-file

**Comment by PabloI75** [comment]
Hello, same here, I have a fresh install and an update from Buster both same result as the first comment here. Any updates / solution? thanks!!

**Comment by cycool29** [comment]
I got it working, see https://github.com/angryip/ipscan/issues/322#issuecomment-1014144836.

For anyone who urges to use Angry IP Scanner on Bullseye, enter this command for a temporary fix:

```bash
cd "$(mktemp -d)"
wget http://ftp.us.debian.org/debian/pool/main/s/swt4-gtk/libswt-gtk-4-java_4.10.0-3_$(dpkg --print-architecture).deb http://ftp.us.debian.org/debian/pool/main/s/swt4-gtk/libswt-gtk-4-jni_4.10.0-3_$(dpkg --print-architecture).deb http://ftp.us.debian.org/debian/pool/main/s/swt4-gtk/libswt-cairo-gtk-4-jni_4.10.0-3_$(dpkg --print-architecture).deb
sudo apt install ./*.deb
sudo apt-mark hold libswt-cairo-gtk-4-jni libswt-gtk-4-java libswt-gtk-4-jni
cd -
```

@theofficialgman Do you know where we can report the broken SWT packages to Raspbian?

**Comment by theofficialgman** [comment]
the launchpad is the official place to report it https://bugs.launchpad.net/raspbian

you can see what process they want you to use here: https://www.raspbian.org/RaspbianBugs

I guess if the debian buster ones work then its actually a bug with raspbian packages for it. the version for those packages is the same in the raspbian repo as the debian buster repo http://archive.raspbian.org/raspbian/pool/main/s/swt4-gtk/ , so its not that they are out of date or anything

**Comment by theofficialgman** [comment]
edit: oh I see you are referring to an issue only occurring on bullseye, the debian bullseye packages for swt are at version 4.17 while the raspbian bullseye packages are still at 4.13, so they are out of date, it might just be a matter of updating those in the repo and then everything might work

**Comment by feadog1** [comment]
Great work and thanks for the temporary fix.

**Comment by cycool29** [comment]
> edit: oh I see you are referring to an issue only occurring on bullseye, the debian bullseye packages for swt are at version 4.17 while the raspbian bullseye packages are still at 4.13, so they are out of date, it might just be a matter of updating those in the repo and then everything might work

Maybe SWT on 4.17 is not supported on armhf, since there doesn't even have armhf packages on https://packages.debian.org.

**Comment by PabloI75** [comment]
Thanks for the temp fix cycool29!! it worked for me when I apply the fix on a system where Angry ip scanner was previously installed, but now I have applied the fix before installing it and it doesn't let me install it, stating:
Failed to install file: A package could not be found that allows the action to complete...

**Comment by theofficialgman** [comment]
> Maybe SWT on 4.17 is not supported on armhf, since there doesn't even have armhf packages on https://packages.debian.org.

I checked the ubuntu launchpad to see if armhf was still in their buildscript and it is, but its failing on anything newer than 4.18 (no ubuntu release uses 4.17). you can see the buildlog from the 4.18 and the errors it is encountering on armhf here: https://launchpadlibrarian.net/557787289/buildlog_ubuntu-hirsute-armhf.swt4-gtk_4.18.0-2_BUILDING.txt.gz

in both cases, on ubuntu and debian, the Debian Java Maintainers are the ones responsible for this package
https://launchpad.net/~pkg-java-maintainers
their email for contacting is here: pkg-java-maintainers@lists.alioth.debian.org

**Comment by theofficialgman** [comment]
did more searching and it looks like they are already aware:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=962915

the issue is because upstream stopped supporting 32bit alltogether. 4.13 is the last supported version on all 32bit architectures

**Comment by theofficialgman** [comment]
raspbian bullseye is basically supplying 4.13 on armhf even when its unsupported upstream. they should either revert to 4.10.0-3 on bullseye, or make sure to apply this patch to their 4.13 build: https://sources.debian.org/patches/swt4-gtk/4.10.0-3/0004-Use-is64-defined-for-build.patch/

**Comment by Anouomgharbivsseagjdzzvz** [comment]
Qweqwe4844

**Comment by theofficialgman** [comment]
checking in on old issues. unfortunatly raspbian maintainers have been entirely unresponsive (as is normal with them). a bug report was created 8 months ago with no responses https://bugs.launchpad.net/raspbian/+bug/1962099

for anyone that forgot, this is because this https://github.com/Botspot/pi-apps/issues/1045#issuecomment-1014856414

**Comment by theofficialgman** [comment]
32bit support removed in pi-apps since this is going nowhere and will not get better
https://github.com/Botspot/pi-apps/commit/65dc9e276abfbdb1acfabbdf6d9c35e59f91869f

**Comment by Abdullaalali** [comment]
> I got it working, see https://github.com/angryip/ipscan/issues/322#issuecomment-1014144836.
> 
> 
> 
> For anyone who urges to use Angry IP Scanner on Bullseye ARM32, enter this command for a temporary fix:
> 
> 
> 
> ```bash
> 
> cd "$(mktemp -d)"
> 
> wget http://ftp.us.debian.org/debian/pool/main/s/swt4-gtk/libswt-gtk-4-java_4.10.0-3_$(dpkg --print-architecture).deb http://ftp.us.debian.org/debian/pool/main/s/swt4-gtk/libswt-gtk-4-jni_4.10.0-3_$(dpkg --print-architecture).deb http://ftp.us.debian.org/debian/pool/main/s/swt4-gtk/libswt-cairo-gtk-4-jni_4.10.0-3_$(dpkg --print-architecture).deb
> 
> sudo apt install ./*.deb
> 
> sudo apt-mark hold libswt-cairo-gtk-4-jni libswt-gtk-4-java libswt-gtk-4-jni
> 
> cd -
> 
> ```
> 
> 
> 
> @theofficialgman Do you know where we can report the broken SWT packages to Raspbian?
> 
>
