### ISSUE TITLE
Deltarune Chapter 1/2 (through BOX64)

### ISSUE THREAD

**Issue by theofficialgman** [Botspot/pi-apps#1048]
Can this app run on RPi? If so, please provide a link to a tutorial if applicable.

https://www.reddit.com/r/Undertale/comments/prg9n1/how_to_get_deltarune_chapter_2_running_on_linux/
https://www.reddit.com/r/linux_gaming/comments/9wj080/deltarune_running_on_linux_natively/

The runner ( YoYo Games Linux Runner V1.3) is only easy available on linux x86_64. There might be an armv7l specific running build out there but someone needs to find a game with it included

Is this app something many GUI users would find useful?

Its a great game.

Is this app installable with `sudo apt install`?

No

If you've created a zip file for this app, upload it here.

I haven't created a PR yet but just want to see if people want it. I have tried through BOX64 and it works well.

**Comment by theofficialgman** [comment]
update on this!
the creator of "Mailroom Mayhem" has created an armv7l game maker studio runner for their game at my request
this allows almost any GMS2 game to be played on armv7l devices!

below you will find my deltarune 1/2 conversion for armv7l. if you want to play on arm64/aarch64, then you can use box64 with an x86_64 runner as done in the tutorial links above
have fun!
https://ufile.io/qpzrsyw5 (edited)

**Comment by faizu396** [comment]
Can this be re-uploaded? when i try to go to the website, it says i need premium access to download the file.

**Comment by theofficialgman** [comment]
> Can this be re-uploaded? when i try to go to the website, it says i need premium access to download the file.
@faizu396 
oh sorry about that, nobody expressed interest before so I assumed it wasn't wanted.
I believe this is the correct backup of the armv7l (32bit) folder that I uploaded
https://ufile.io/n7t8rmcf
