### ISSUE TITLE
ExaGear App request

### ISSUE THREAD

**Issue by Crilum** [Botspot/pi-apps#1051]
ExaGear for Raspberry Pi
----------
I've made a Pi-Apps app install/uninstall script (with the Pi-Apps settings New App button) to install ExaGear.

There is one problem I know is in there and it's that when the Pi-Apps install script updates and re-installs ExaGear, is will delete the user's data in the ExaGear image. If anyone has an idea about how to fix that, I would be greatful for help or a suggestion.

Also, the website doesn't work, because Eltechs (the dev) shut down and took the website down too.

I have ExaGear running on my Pi 4 with spotify installed, and it runs pretty well.

Any advice or comments would be greatly appreciated.

[ExaGear.zip](https://github.com/Botspot/pi-apps/files/7350870/ExaGear.zip)

P.S. I'm new to github, so I don't know how to add the app-request label...

**Comment by cycool29** [comment]
With this app added, I think we can have lots of Linux i386 apps to be added to pi-apps !

**Comment by cycool29** [comment]
> This app seems to have great potential. However, ExaGear is/was a **paid software**. Once ExaGear was discontinued, their licensing servers went down too, so as far as I understand the only way to use ExaGear now is by downloading a cracked version of the deb. Is that the case here? Or, are the debs non-modified but these weird-looking lines of code do it?
> 
> ```shell
> #Credit to toasteh on pyra-handheld.com for this patch:
> echo "Patching exagear..."
> sudo rm -rf '/opt/exagear/lic' || error 'Failed to remove "/opt/exagear/lic"!'
> sudo rm -f '/opt/exagear/bin/actool' || error 'Failed to remove "/opt/exagear/bin/actool"!'
> sudo printf '\x00\xf0\x20\xe3\x01\x00\xa0\xe3' | sudo dd of='/opt/exagear/bin/ubt_x32a32_al_mem2g' bs=1 seek=866740 count=8 conv=notrunc 2> /dev/null || error 'Failed to run printf!'
> sudo printf '\x00\xf0\x20\xe3\x01\x00\xa0\xe3' | sudo dd of='/opt/exagear/bin/ubt_x32a32_al_mem3g' bs=1 seek=996256 count=8 conv=notrunc 2> /dev/null || error 'Failed to run printf!'
> ```

Yes, those lines are the patch script for the license. And ya, since ExaGear is not open source, I think you are worry about the license / copyright issue of the cracked app. (I have heard some news about it is sold to Huawei).

For that, ExaGear may not be added to pi-apps, but it still very useful to me.

**Comment by Botspot** [comment]
ExaGear seems to be interfering with Box86 binfmt.

**Comment by Crilum** [comment]
This is in the postinst file on box86 repo:
```
#!/bin/sh
systemctl restart systemd-binfmt
```

Don't know if it helps, but I thought I'd mention it..

**Comment by Itai-Nelken** [comment]
> ExaGear seems to be interfering with Box86 binfmt.

I think ExaGear is basically qemu-user which is known to interfere with box86.

**Comment by Crilum** [comment]
With this it's probably a small chance that Huawei will let us use ExaGear.

https://threedots.ovh/blog/2021/01/huawei-exagear-x86_64-apps-on-arm64/
> Note: This post is only kept up for historical reasons. The current ExaGear EULA doesn’t allow using ExaGear outside of Huawei Kunpeng processors.

The blog post also has a download link which leads to [https://mirrors.huaweicloud.com/kunpeng/archive/ExaGear/](this).
I think Huawei also developed ExaGear more.

There are also [installation instructions](https://support.huaweicloud.com/intl/en-us/ug-exagear-kunpengdevps/kunpengexagear_06_0011.html) on the Huawei support page, but they only support aarch64.

**Comment by Crilum** [comment]
Another thought: Huawei distributes ExaGear for free, no license.
But, as I said above, you can only use it on Huawei Kunpeng processors...

**Comment by Crilum** [comment]
Well, I just tried to run Zoom with box86, and it exited with the error from #1038, but it looked like box86 started..
```
Launching Zoom.
Box86 with Dynarec v0.2.3 1955c225 built on Oct 10 2021 00:04:24
zoom started.
Client: Breakpad is using Single Client Mode! client fd = -1
free(): invalid pointer
/home/pi/zoom/runzoom.sh: line 13: 26028 Aborted                 box86 zoom "$1"
Zoom exited. Close this terminal to exit

```
Wine still has the same problem...

**Comment by Crilum** [comment]
Sublime Text starts:
![Screenshot-Sublime-Text-box86](https://user-images.githubusercontent.com/91354257/137597613-ec33c24d-0915-421b-9518-3efba18c0fa5.png)
That uses box86 dosen't it?

**Comment by Crilum** [comment]
@Botspot 
> - When installing Ubuntu, you have a choice to install some DRM packages. If you check the box, those DRM packages are downloaded from an offshore server. Basically, Ubuntu is offloading the legal risk to a 3rd party. (Pi-Apps could do the same by running a 3rd-party script)
 -When installing ExaGear, the script may display a warning that requires the user to hit the Enter key. It could say "Proceed at your own risk" or something like that.

Back to the legality part of this:

The debs and patch script are already downloaded from a third-party mirror, and we could use user input to warn them that they are using ExaGear at their own risk, like you suggested.

Just some more of my thoughts...

**Comment by Crilum** [comment]
Well, now that I actually try to do something in ExaGear, I get this, which has to do with binfmt again:
```
$ sudo apt install snapd
ExaGear itself does not support running SUID or SGID binaries,
they must be started using the binfmt_misc wrapper.
Please see the user manual for the details.
```
It was the `sudo` part that triggered it.
So it looks like box86 has binfmt right now...
Other commands work... Just no `sudo`.
If I run ExaGear as root in the host, it works..

**Comment by open-sorcerer64** [comment]
What apps can be run by using ExaGear (I mean apps that the Pi can handle)

**Comment by Crilum** [comment]
I have my Pi 4 4G overclocked to 2 gigahertzs, just so you know..
- I have Spotify running, and it's not super fast, but it plays just fine unless the CPU is stressed past like 80%.
- Wine can be run (I haven't tried it because I use box86/Wine).

I haven't really tried a lot of apps besides Spotify, because I have most of what I need, just on RPiOS or Wine, but in theory, it should be able to handle most apps.

**Comment by Crilum** [comment]
Sublime Text 3 runs alright.

**Comment by Crilum** [comment]
After a reboot if you start box86 before ExaGear, you can run box86, but if you start ExaGear first you get the `Segmentation Fault` error with wine.

**Comment by Crilum** [comment]
Just so everyone interested knows, the ExaGear guest images, at least the `debian-9` one, comes with wine preinstalled, and it is the default wine for the system, so if you double-click on a .exe, it opens in ExaGear, instead of box86 wine..

**Comment by woachk** [comment]
Reminder that the new ExaGear EULA that was added this summer doesn’t allow ExaGear use on non-Huawei Kunpeng hardware anymore.

**Comment by Crilum** [comment]
> Reminder that the new ExaGear EULA that was added this summer doesn’t allow ExaGear use on non-Huawei Kunpeng hardware anymore.

Yeah, we do know that. Thanks though. :smile:

**Comment by theofficialgman** [comment]
closing due to already stated licensing issues. I think box86 and box64 already fill this role very well as it is anyway.

and at some point FEX-emu will mature enough to be usefull

**Comment by Crilum** [comment]
@theofficialgman I agree with closing this. However, box86/46 does not have libcef support, so you can't run Spotify..
