### ISSUE TITLE
[App Request] 3D pinball space cadet linux port

### ISSUE THREAD

**Issue by iAmInActions** [Botspot/pi-apps#1057]
Can this app run on RPi? If so, please provide a link to a tutorial if applicable.
It can run on the pi and is found here: https://github.com/k4zmu2a/SpaceCadetPinball

Is this app something many GUI users would find useful?
Probably yes as its a fun game to get rid of boredom.

Is this app installable with `sudo apt install`?
No. You have to compile it using cmake.

If you've created a zip file for this app, upload it here:
Not yet, will do so soon.

**Comment by Itai-Nelken** [comment]
I compiled it succesfully (on arm64 rpiOS upgraded to bullseye), but I had to install `libsdl2-dev` and `libsdl2-mixer-dev` before.
It launches, but I haven't tested if it actually runs the game yet though.
