### ISSUE TITLE
failed to install

### ISSUE THREAD

**Issue by EarlierPlane034** [Botspot/pi-apps#106]
i keep on getting this error i think the main problem is at the end
Installing Steam with install-32 script
Running pkg-install...
Waiting until APT locks are released... Done
Failed to run sudo apt update!
APT reported these errors:
E: The repository 'https://ppa.launchpad.net/polychromatic/stable/ubuntu xenial Release' does not have a Release file.
E: The repository 'http://download.opensuse.org/repositories/hardware:/razer/Debian_Sid  Release' does not have a Release file.
W: GPG error: http://ppa.launchpad.net/polychromatic/stable/ubuntu bionic InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 96B9CD7C22E2C8C5
E: The repository 'http://ppa.launchpad.net/polychromatic/stable/ubuntu bionic InRelease' is not signed.
W: Target Packages (main/binary-armhf/Packages) is configured multiple times in /etc/apt/sources.list.d/polychromatic.list:1 and /etc/apt/sources.list.d/polychromatic.list:2
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/polychromatic.list:1 and /etc/apt/sources.list.d/polychromatic.list:2
W: Target Translations (main/i18n/Translation-en_US) is configured multiple times in /etc/apt/sources.list.d/polychromatic.list:1 and /etc/apt/sources.list.d/polychromatic.list:2
W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list.d/polychromatic.list:1 and /etc/apt/sources.list.d/polychromatic.list:2
W: Target Translations (main/i18n/Translation-en_US.UTF-8) is configured multiple times in /etc/apt/sources.list.d/polychromatic.list:1 and /etc/apt/sources.list.d/polychromatic.list:2
W: Target Packages (main/binary-armhf/Packages) is configured multiple times in /etc/apt/sources.list.d/polychromatic.list:1 and /etc/apt/sources.list.d/polychromatic.list:3
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/polychromatic.list:1 and /etc/apt/sources.list.d/polychromatic.list:3
W: Target Translations (main/i18n/Translation-en_US) is configured multiple times in /etc/apt/sources.list.d/polychromatic.list:1 and /etc/apt/sources.list.d/polychromatic.list:3
W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list.d/polychromatic.list:1 and /etc/apt/sources.list.d/polychromatic.list:3
W: Target Translations (main/i18n/Translation-en_US.UTF-8) is configured multiple times in /etc/apt/sources.list.d/polychromatic.list:1 and /etc/apt/sources.list.d/polychromatic.list:3
W: Target Packages (main/binary-armhf/Packages) is configured multiple times in /etc/apt/sources.list.d/polychromatic.list:1 and /etc/apt/sources.list.d/polychromatic.list:4
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/polychromatic.list:1 and /etc/apt/sources.list.d/polychromatic.list:4
W: Target Translations (main/i18n/Translation-en_US) is configured multiple times in /etc/apt/sources.list.d/polychromatic.list:1 and /etc/apt/sources.list.d/polychromatic.list:4
W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list.d/polychromatic.list:1 and /etc/apt/sources.list.d/polychromatic.list:4
W: Target Translations (main/i18n/Translation-en_US.UTF-8) is configured multiple times in /etc/apt/sources.list.d/polychromatic.list:1 and /etc/apt/sources.list.d/polychromatic.list:4
W: Target Packages (main/binary-armhf/Packages) is configured multiple times in /etc/apt/sources.list.d/polychromatic.list:1 and /etc/apt/sources.list.d/polychromatic.list:5
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/polychromatic.list:1 and /etc/apt/sources.list.d/polychromatic.list:5
W: Target Translations (main/i18n/Translation-en_US) is configured multiple times in /etc/apt/sources.list.d/polychromatic.list:1 and /etc/apt/sources.list.d/polychromatic.list:5
W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list.d/polychromatic.list:1 and /etc/apt/sources.list.d/polychromatic.list:5
W: Target Translations (main/i18n/Translation-en_US.UTF-8) is configured multiple times in /etc/apt/sources.list.d/polychromatic.list:1 and /etc/apt/sources.list.d/polychromatic.list:5
W: Target Packages (main/binary-armhf/Packages) is configured multiple times in /etc/apt/sources.list.d/polychromatic.list:1 and /etc/apt/sources.list.d/polychromatic.list:6
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/polychromatic.list:1 and /etc/apt/sources.list.d/polychromatic.list:6
W: Target Translations (main/i18n/Translation-en_US) is configured multiple times in /etc/apt/sources.list.d/polychromatic.list:1 and /etc/apt/sources.list.d/polychromatic.list:6
W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list.d/polychromatic.list:1 and /etc/apt/sources.list.d/polychromatic.list:6
W: Target Translations (main/i18n/Translation-en_US.UTF-8) is configured multiple times in /etc/apt/sources.list.d/polychromatic.list:1 and /etc/apt/sources.list.d/polychromatic.list:6
W: Target Packages (main/binary-armhf/Packages) is configured multiple times in /etc/apt/sources.list.d/polychromatic.list:1 and /etc/apt/sources.list.d/polychromatic.list:7
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/polychromatic.list:1 and /etc/apt/sources.list.d/polychromatic.list:7
W: Target Translations (main/i18n/Translation-en_US) is configured multiple times in /etc/apt/sources.list.d/polychromatic.list:1 and /etc/apt/sources.list.d/polychromatic.list:7
W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list.d/polychromatic.list:1 and /etc/apt/sources.list.d/polychromatic.list:7
W: Target Translations (main/i18n/Translation-en_US.UTF-8) is configured multiple times in /etc/apt/sources.list.d/polychromatic.list:1 and /etc/apt/sources.list.d/polychromatic.list:7
W: Target Packages (main/binary-armhf/Packages) is configured multiple times in /etc/apt/sources.list.d/polychromatic.list:1 and /etc/apt/sources.list.d/polychromatic.list:8
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/polychromatic.list:1 and /etc/apt/sources.list.d/polychromatic.list:8
W: Target Translations (main/i18n/Translation-en_US) is configured multiple times in /etc/apt/sources.list.d/polychromatic.list:1 and /etc/apt/sources.list.d/polychromatic.list:8
W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list.d/polychromatic.list:1 and /etc/apt/sources.list.d/polychromatic.list:8
W: Target Translations (main/i18n/Translation-en_US.UTF-8) is configured multiple times in /etc/apt/sources.list.d/polychromatic.list:1 and /etc/apt/sources.list.d/polychromatic.list:8
W: Target Packages (main/binary-armhf/Packages) is configured multiple times in /etc/apt/sources.list.d/polychromatic.list:1 and /etc/apt/sources.list.d/polychromatic.list:9
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/polychromatic.list:1 and /etc/apt/sources.list.d/polychromatic.list:9
W: Target Translations (main/i18n/Translation-en_US) is configured multiple times in /etc/apt/sources.list.d/polychromatic.list:1 and /etc/apt/sources.list.d/polychromatic.list:9
W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list.d/polychromatic.list:1 and /etc/apt/sources.list.d/polychromatic.list:9
W: Target Translations (main/i18n/Translation-en_US.UTF-8) is configured multiple times in /etc/apt/sources.list.d/polychromatic.list:1 and /etc/apt/sources.list.d/polychromatic.list:9
W: Target Packages (main/binary-armhf/Packages) is configured multiple times in /etc/apt/sources.list.d/polychromatic.list:1 and /etc/apt/sources.list.d/polychromatic.list:13
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/polychromatic.list:1 and /etc/apt/sources.list.d/polychromatic.list:13
W: Target Translations (main/i18n/Translation-en_US) is configured multiple times in /etc/apt/sources.list.d/polychromatic.list:1 and /etc/apt/sources.list.d/polychromatic.list:13
W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list.d/polychromatic.list:1 and /etc/apt/sources.list.d/polychromatic.list:13
W: Target Translations (main/i18n/Translation-en_US.UTF-8) is configured multiple times in /etc/apt/sources.list.d/polychromatic.list:1 and /etc/apt/sources.list.d/polychromatic.list:13
W: Target Packages (main/binary-armhf/Packages) is configured multiple times in /etc/apt/sources.list.d/polychromatic.list:10 and /etc/apt/sources.list.d/polychromatic.list:11
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/polychromatic.list:10 and /etc/apt/sources.list.d/polychromatic.list:11
W: Target Translations (main/i18n/Translation-en_US) is configured multiple times in /etc/apt/sources.list.d/polychromatic.list:10 and /etc/apt/sources.list.d/polychromatic.list:11
W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list.d/polychromatic.list:10 and /etc/apt/sources.list.d/polychromatic.list:11
W: Target Translations (main/i18n/Translation-en_US.UTF-8) is configured multiple times in /etc/apt/sources.list.d/polychromatic.list:10 and /etc/apt/sources.list.d/polychromatic.list:11
W: Target Packages (main/binary-armhf/Packages) is configured multiple times in /etc/apt/sources.list.d/polychromatic.list:10 and /etc/apt/sources.list.d/polychromatic.list:12
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/polychromatic.list:10 and /etc/apt/sources.list.d/polychromatic.list:12
W: Target Translations (main/i18n/Translation-en_US) is configured multiple times in /etc/apt/sources.list.d/polychromatic.list:10 and /etc/apt/sources.list.d/polychromatic.list:12
W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list.d/polychromatic.list:10 and /etc/apt/sources.list.d/polychromatic.list:12
W: Target Translations (main/i18n/Translation-en_US.UTF-8) is configured multiple times in /etc/apt/sources.list.d/polychromatic.list:10 and /etc/apt/sources.list.d/polychromatic.list:12
W: Target Packages (main/binary-armhf/Packages) is configured multiple times in /etc/apt/sources.list.d/polychromatic.list:10 and /etc/apt/sources.list.d/polychromatic.list:14
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/polychromatic.list:10 and /etc/apt/sources.list.d/polychromatic.list:14
W: Target Translations (main/i18n/Translation-en_US) is configured multiple times in /etc/apt/sources.list.d/polychromatic.list:10 and /etc/apt/sources.list.d/polychromatic.list:14
W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list.d/polychromatic.list:10 and /etc/apt/sources.list.d/polychromatic.list:14
W: Target Translations (main/i18n/Translation-en_US.UTF-8) is configured multiple times in /etc/apt/sources.list.d/polychromatic.list:10 and /etc/apt/sources.list.d/polychromatic.list:14

Failed to install Steam with install-32 script!

**Comment by Botspot** [comment]
Looks like you messed up your repository settings before you installed Steam.

I can't help you much there. Try googling the errors, consider re-flashing, and this command may come in handy:
```
sudo apt update 2>&1 1>/dev/null | sed -ne 's/.*NO_PUBKEY //p' | while read key; do if ! [[ ${keys[*]} =~ "$key" ]]; then sudo apt-key adv --keyserver hkp://pool.sks-keyservers.net:80 --recv-keys "$key"; keys+=("$key"); fi; done
```
That above command detects any unsigned repositories and signs them for you. IDK if that would solve your whole problem or not, though.
