### ISSUE TITLE
Steam Browser disabled (Steam is now working at all)

### ISSUE THREAD

**Issue by MTCK123** [Botspot/pi-apps#107]
Ok so I would of thought someone would of catched this before me but Steam completely does not work AT ALL on linux 32-bit. Basicly this is what Steam says on there website "32-bit Linux distributions are also no longer supported. Please install a 64-bit Linux distribution to make use of the Steam browser." (support.steampowered.com/kb_article.php?ref=4090-RTKZ-4347). So you will proably want to remove steam for now. P.S im not eniterly sure with this stuff so tell me if its just my problem.

**Comment by Botspot** [comment]
Known issue.

All you have to do is enable small mode in Steam. See: https://www.reddit.com/r/SBCGaming/comments/k1sx2v/fix_downloaded_steam_on_rpi_but_cant_see_your/

So we have two options here: either putting that link in the description, or I'm hoping we can use Pi-Apps to create a config file that tells Steam to use Small Mode by default.

In any case, this is a known issue, there is a known easy fix, so I'm closing this issue.
