### ISSUE TITLE
Pi-Apps cli updater script with no input

### ISSUE THREAD

**Issue by Crilum** [Botspot/pi-apps#1071]
Suggestion:
Make the cli updater script have a flag like the -y flag in Apt.
I'm making an [update script](https://github.com/Crilum/update-app-script) that can update from Apt, Pi-Apps, Flatpak, and snap, and I want to have it be completely input free after the initial command, but the Pi-Apps updater script asks `Update now? [Y/n]`.

**Comment by Botspot** [comment]
The `updater` script has an automatic-yes mode.
See: https://github.com/Botspot/pi-apps/blob/master/DOCUMENTATION.md#the-updater-script
