### ISSUE TITLE
LinuxCNC

### ISSUE THREAD

**Issue by Crilum** [Botspot/pi-apps#1074]
Can this app run on RPi? If so, please provide a link to a tutorial if applicable.
Yes.
Is this app something many GUI users would find useful?
I think so.
Is this app installable with `sudo apt install`?
No...
If you've created a zip file for this app, upload it here.
[LinuxCNC.zip](https://github.com/Botspot/pi-apps/files/7399910/LinuxCNC.zip)

**Comment by Botspot** [comment]
This app is failing to install on Bullseye due to missing python2 dependencies.
```
 linuxcnc-uspace : Depends: libboost-python1.67.0 but it is not installable
                   Depends: python2.7-glade2 but it is not installable or
                            python-glade2 but it is not installable
                   Depends: python2.7-numpy but it is not installable or
                            python-numpy but it is not installable
                   Depends: python2.7-imaging but it is not installable or
                            python-imaging but it is not installable or
                            python-pil but it is not installable
                   Depends: python2.7-imaging-tk but it is not installable or
                            python-imaging-tk but it is not installable or
                            python-pil.imagetk but it is not installable
                   Depends: python-gtksourceview2 but it is not installable
                   Depends: python-gst-1.0 but it is not installable
                   Depends: python-xlib but it is not installable
                   Depends: python-gtkglext1 but it is not installable
                   Depends: python-configobj but it is not installable
```
If this problem is not fixable, we will have to remove this app from Pi-Apps. :(

**Comment by Crilum** [comment]
I'll look into it.

**Comment by Crilum** [comment]
Well, I tried to install all the dependencies manually, but there is a long dependency tree, that will all have to be installed manually from the debian repos.

I'll create an issue in the LinuxCNC repo, to see if they'll build another arm deb for bullseye.
If they can't/won't, then I guess we'll have to take it off Pi-Apps.

This is my progress:
[LinuxCNC.zip](https://github.com/Botspot/pi-apps/files/7531586/LinuxCNC.zip)
