### ISSUE TITLE
2 thing's about  wine

### ISSUE THREAD

**Issue by neofeo** [Botspot/pi-apps#1075]
Hi buddy, salva here.

Okay, the first one is about winetricks, it needs BOX86_NOBANNER=1 to work, so, copy winetricks to /home/pi/wine/ folder instead and create a symlink on /urs/local/winetricks to export that env var and target the winetricks script. Thats how we do on twister

Second, add another shortcut to kill any wine app with the command wineserver -k . It's  very handy bc many times we suffer process not crossing and running  on the background. 

Br ,salvador

**Comment by Itai-Nelken** [comment]
Thanks for the suggestions and sorry for the delay in answering.
I'll look at them when I have time.

**Comment by Itai-Nelken** [comment]
Can this issue be closed (see commit d05eac9578fb2d3cbaa3072e1088f8b64bb3253b)?

**Comment by Botspot** [comment]
> Can this issue be closed (see commit [d05eac9](https://github.com/Botspot/pi-apps/commit/d05eac9578fb2d3cbaa3072e1088f8b64bb3253b))?

Yes, because I've completed both objectives.

**Comment by Itai-Nelken** [comment]
thanks @neofeo!
