### ISSUE TITLE
timeshift

### ISSUE THREAD

**Issue by Itai-Nelken** [Botspot/pi-apps#109]
[Timeshift.zip](https://github.com/Botspot/pi-apps/files/5608049/Timeshift.zip)

**Comment by Botspot** [comment]
timeshift is already in the apt repositories.

Now, it's v19.01 and yours is v20.11. Do you think most Pi-Apps users would prefer using v20.11?

**Comment by Itai-Nelken** [comment]
I don't really know, but v20.11.1 has a lot of fixes.

**Comment by Itai-Nelken** [comment]
Fix #631: Escape single quote in LUKS password when unlocking device

Fix #626: Filters: Save filter order changes when clicking OK

Fix #643: Filters: Save changes after Include/Exclude radio is toggled

Fix #668: Filters: Save changes immediately after a pattern is added or edited

Fix #666: Filters: Save changes before showing Summary

Fix #497, #467: Fix missing hourly backups

Move config file to /etc/timeshift/timeshift.json

Move default config to /etc/timeshift/default.json

AppStream: Install only under /usr/share/metainfo. Don't install under /usr/share/appdata/

Option to unmark snapshots that are marked for deletion

Launcher: No need to pass DISPLAY and AUTHORITY to pkexec

Remove unused functions and code

Update translations

**Comment by Botspot** [comment]
Okay, I've decided to add this.

**Comment by Botspot** [comment]
Added with commit a80a5ae17d8c76077080ce2de6cc3734ae545d1d.
