### ISSUE TITLE
DDnet

### ISSUE THREAD

**Issue by KolpixTV** [Botspot/pi-apps#1093]
Is this app installable with `sudo apt install`?

Yes but the apt Version is outdated.

If you've created a zip file for this app, upload it here
[DDnet.zip](https://github.com/Botspot/pi-apps/files/7434212/DDnet.zip)

I did not tested it on x64 but im shure it will also work there. I will try it later today or tomorrow. And when it works i will send a ZIP File with the install script for x64 (i think it's the same as for 32x xD)

Here is the newest Version:

https://github.com/Botspot/pi-apps/issues/1093#issuecomment-955682513

**Comment by Crilum** [comment]
Are you on twisterOS? I'm using RPiOS.
I don't know if it makes a difference..

**Comment by KolpixTV** [comment]
Im using RPiOs as well and it worked perfectly before as i said but i reinstalled it to test some stuff.

And i also don't want to like reinstall RPiOS.

**Comment by Crilum** [comment]
You can try [vdesktop]() (also available in Pi Power Tools under `boot` in IMG Mode), it lets you run a RPiOS image inside your real OS.

**Comment by KolpixTV** [comment]
I already tried it with Pi Power Tools but it's also doesn't work there, but vdesktop is also a little bit buggy for me i have 1 sd card left i try it there later.

**Comment by Crilum** [comment]
Ok. That is really weird. It works for me.

**Comment by Crilum** [comment]
[This](https://stackoverflow.com/questions/62374298/ffmpeg-installation-on-raspberry-pi-zero-w-undefined-references-to-atomic#62501876) might help you.

**Comment by Crilum** [comment]
We might need to fork DDNet, and change the `cmakelists.txt`, or make an issue in their repository.. [Look at this](https://github.com/PurpleI2P/i2pd/issues/897).

**Comment by KolpixTV** [comment]
what we have to change in the cmakelist.txt file?

**Comment by Crilum** [comment]
The [issue](https://github.com/PurpleI2P/i2pd/issues/897) in my last comment has a fix to add to the `cmakelists.txt`.

**Comment by Crilum** [comment]
That is @v2e's comment from [PurpleI2p/i2pd](https://github.com/PurpleI2P/i2pd). The above fix is just an example, so for DDNet, we would need something like:
```
target_link_libraries(${TARGET_CLIENT} ${LIBS_CLIENT} -latomic)
```

**Comment by Crilum** [comment]
In uninstall, we should probably tell the user that `/home/pi/.teeworlds` still exists after uninstall..

**Comment by KolpixTV** [comment]
[DDnet.4.zip](https://github.com/Botspot/pi-apps/files/7448436/DDnet.4.zip)
The uninstall script here also deletes .teeworlds.

![image](https://user-images.githubusercontent.com/68741965/139577912-89c86782-69c4-4099-9f40-7f756181bbae.png)
i will fork that (i never did it but i try it)

**Comment by KolpixTV** [comment]
i forked it and updated the CMakelist i will update the Install Script now

**Comment by KolpixTV** [comment]
![image](https://user-images.githubusercontent.com/68741965/139579569-140e4ecd-8442-4293-a241-5c6a431e0089.png)
also $HOME works but this dirname "§0" does not work.

Here is the new File
[ddnet.zip](https://github.com/Botspot/pi-apps/files/7448651/ddnet.zip)
.

**Comment by Crilum** [comment]
Ok, well, it should work in the desktop files.

**Comment by Crilum** [comment]
@KolpixTV By the way, does the install script work?

**Comment by KolpixTV** [comment]
The install script file does work for me now. Idk if `§(dirname "$0")` works **in** the Desktop Entry but it does not work where i marked it and also every other.
Are you using x64? Maybe `$HOME` only works on 32bit and we can make an Install script for x64 where `$HOME` is replaced with `$(dirname "$0")`. If `$(dirname "$0")` works for you fine.

**Comment by Itai-Nelken** [comment]
If `$HOME` doesn't work, something is very wrong.

**Comment by KolpixTV** [comment]
> If `$HOME` doesn't work, something is very wrong.

It works for me but Not for you

**Comment by KolpixTV** [comment]
> If `$HOME` doesn't work, something is very wrong.

For me its working but Not for him

**Comment by cycool29** [comment]
`$HOME` and `$(dirname "$0")` won't work if you **exactly** put it in the desktop file because desktop file can only read absolute path.

Use `$HOME` and `$(dirname "$0")` in script to create desktop file should be fine, since when you execute the script the `$HOME` or `$(dirname "$0")` will be translated to absolute path.

> Are you using x64? Maybe `$HOME` only works on 32bit and we can make an Install script for x64 where `$HOME` is replaced with `$(dirname "$0")`. If `$(dirname "$0")` works for you fine.

It doesn't matter what architechture.

**Comment by KolpixTV** [comment]
So If i put $HOME in my Install Script Script its fine right?

**Comment by cycool29** [comment]
> So If i put $HOME in my Install Script Script its fine right?

Yes

**Comment by KolpixTV** [comment]
ok nice. I think the Zip File is now done.

**Comment by Crilum** [comment]
> If `$HOME` doesn't work, something is very wrong.

`$HOME` works for me, but not in .desktop files. @cycool29 suggested `$(dirname "$0")` for making .desktop files, because `$HOME` didn't work.

**Comment by cycool29** [comment]
`$HOME` and `$(dirname "$0")` is **totally** different thing.

 `$HOME` points to the home folder (e.g. `/home/pi`) and `$(dirname "$0")` point to the path of the script (e.g. `/home/pi/pi-apps/apps/DDnet`). 

As @Itai-Nelken said, if $HOME doesn't work, something is **very wrong**.

**Comment by cycool29** [comment]
I have simplified the script and add `purge-installed`, here is the improved zip:
[DDnet.zip](https://github.com/Botspot/pi-apps/files/7457255/DDnet.zip)

**Comment by Crilum** [comment]
I should clarify, $HOME works for stuff like this:
```
xdg-open $HOME/Pictures/Picture.png
```

But not something like this:
```
echo "[Desktop Entry]
Name=Temps
Comment=Temps is a modern and minimal menubar application based on Electron with actual weather information and forecast.
GenericName=Weather App
Exec=temps
Icon=$HOME/pi-apps/apps/temps/icon-64.png
StartupNotify=true
Terminal=false
Type=Application
Categories=Utility;" > $HOME/.local/share/applications/Temps.desktop
```

Sorry for the slightly off topic comment.. :man_shrugging:

**Comment by cycool29** [comment]
> But not something like this:
> 
> ```
> echo "[Desktop Entry]
> Name=Temps
> Comment=Temps is a modern and minimal menubar application based on Electron with actual weather information and forecast.
> GenericName=Weather App
> Exec=temps
> Icon=$HOME/pi-apps/apps/temps/icon-64.png
> StartupNotify=true
> Terminal=false
> Type=Application
> Categories=Utility;" > $HOME/.local/share/applications/Temps.desktop
> ```
> 
> Sorry for the slightly off topic comment.. 🤷‍♂️

Why not? It works for me.

**Comment by Crilum** [comment]
> > But not something like this:
> > ```
> > echo "[Desktop Entry]
> > Name=Temps
> > Comment=Temps is a modern and minimal menubar application based on Electron with actual weather information and forecast.
> > GenericName=Weather App
> > Exec=temps
> > Icon=$HOME/pi-apps/apps/temps/icon-64.png
> > StartupNotify=true
> > Terminal=false
> > Type=Application
> > Categories=Utility;" > $HOME/.local/share/applications/Temps.desktop
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Sorry for the slightly off topic comment.. man_shrugging
> 
> Why not? It works for me.

Directly calling `$HOME`, doesn't work, but this does:
```
 echo "[Desktop Entry]
Name=Temps
Comment=Temps is a beautiful weather app that resides in your system tray.
GenericName=Weather App
Exec=temps
Icon=$(echo $HOME)/pi-apps/apps/Temps/icon-64.png
StartupNotify=true
Terminal=false
Type=Application
Categories=Utility;
" | sudo tee /usr/share/applications/Temps.desktop

```

**Comment by Itai-Nelken** [comment]
Soory, I accidentally edited @Crilum comments instead of replying to them...

**Comment by Crilum** [comment]
Ah, it's ok, haha. :rofl:

**Comment by cycool29** [comment]
> This will work in a script as bash will replace $HOME
with the path. It won't work if you put that straight in the desktop file.

Who wrote this lol.
This is right.

> Directly calling $HOME, doesn't work, but this does:
> 
> ```
> echo "[Desktop Entry]
> Name=Temps
> Comment=Temps is a beautiful weather app that resides in your system tray.
> GenericName=Weather App
> Exec=temps
> Icon=$(echo $HOME)/pi-apps/apps/Temps/icon-64.png
> StartupNotify=true
> Terminal=false
> Type=Application
> Categories=Utility;
> " | sudo tee /usr/share/applications/Temps.desktop
> ```


Uhh, `echo $HOME` should work same with `$HOME`.

**Comment by Crilum** [comment]
Well, :man_shrugging:. I don't know.

**Comment by Itai-Nelken** [comment]
I edited them back.

Anyway what I wanted to say is that referencing `$HOME` will work as long as it's in the install script and not straight in the desktop file.
For example putting
```
path=$HOME/folder/binary
```
Straight in the desktop file won't work, but doing this will work:
```
echo "Path=$HOME/folder/binary" > /path/to/applications/app.desktop
```

**Comment by Crilum** [comment]
@KolpixTV Sorry for starting a discussion in your app request.. :smiley: 

@Botspot Could you enable Discussions for things like this?

**Comment by KolpixTV** [comment]
No Problem.

So is there a ZIP File with the Final script that works? If not what do i have to change?

**Comment by cycool29** [comment]
> No Problem.
> 
> So is there a ZIP File with the Final script that works? If not what do i have to change?

I am not familiar with this game, you may try with my latest zip [here](https://github.com/Botspot/pi-apps/issues/1093#issuecomment-957031637). If that works well, that should be the final one.

**Comment by KolpixTV** [comment]
Ok Thanks i'll try it :D

**Comment by KolpixTV** [comment]
it works fine

**Comment by Botspot** [comment]
Should we mention in the description that DDnet launches in fullscreen and ignores the Esc and F11 keys?

**Comment by Itai-Nelken** [comment]
> Should we mention in the description that DDnet launches in fullscreen and ignores the Esc and F11 keys?

Certainly. maybe we should handle a way to exit ourselves (if it's possible)?

**Comment by Botspot** [comment]
> Certainly. maybe we should handle a way to exit ourselves (if it's possible)?

Alt+F4 appears to work. Honestly, I'm tempted to install `xephyr` along with this app to run it in a window. :)

**Comment by Botspot** [comment]
Well that was easy.
![ddnet in xephyr](https://user-images.githubusercontent.com/54716352/139893811-639b6e98-1e73-474c-b0ba-d117561dc20f.png)
Unfortunately the built-in mouse pointer does not work, but it was worth a shot.

**Comment by KolpixTV** [comment]
You can Go in the graphic settings and Turn Off fullscreen there

**Comment by Itai-Nelken** [comment]
> You can Go in the graphic settings and Turn Off fullscreen there

Can we maybe do that automatically (by changing a config file) like stuntrally does?

**Comment by cycool29** [comment]
> > You can Go in the graphic settings and Turn Off fullscreen there
> 
> Can we maybe do that automatically (by changing a config file) like stuntrally does?

Just edit `~/.teeworlds/settings_ddnet.cfg` and change `gfx_fullscreen 1` to `gfx_fullscreen 0`.
One-liner to do so:
```
sed -i s+"gfx_fullscreen 1"+"gfx_fullscreen 0"+g $HOME/.teeworlds/settings_ddnet.cfg
```

I think this can be added at the last of the install script.

**Comment by Itai-Nelken** [comment]
> That's easy. Just edit `~/.teeworlds/settings_ddnet.cfg` and change `gfx_fullscreen 1` to `gfx_fullscreen 0`.
> One-liner to do so:
> ```
> sed -i s+"gfx_fullscreen 1"+"gfx_fullscreen 0"+g $HOME/.teeworlds/settings_ddnet.cfg
> ```
> 
> I think this can be added at the last of the install script.

Does that file exist before running the program?

**Comment by cycool29** [comment]
> > That's easy. Just edit `~/.teeworlds/settings_ddnet.cfg` and change `gfx_fullscreen 1` to `gfx_fullscreen 0`.
> > One-liner to do so:
> > ```
> > sed -i s+"gfx_fullscreen 1"+"gfx_fullscreen 0"+g $HOME/.teeworlds/settings_ddnet.cfg
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I think this can be added at the last of the install script.
> 
> Does that file exist before running the program?

The file doesn't exist before first run. But we can simply create it:
```
mkdir $HOME/.teeworlds && echo "gfx_fullscreen 0" > $HOME/.teeworlds/settings_ddnet.cfg
```
