### ISSUE TITLE
Small bug

### ISSUE THREAD

**Issue by mobilegmYT** [Botspot/pi-apps#11]
Love it how when I run shell check, it says there's a problem with the code in the template:
`In /home/pi/pi-apps/apps/Retropie/uninstall line 5:
  echo -e "\e[31m$1\e[39m"
           ^-- SC1117: Backslash is literal in "\e". Prefer explicit escaping: "\\e".
                   ^-- SC1117: Backslash is literal in "\e". Prefer explicit escaping: "\\e".
`
It's not a big bug, but it triggers my OCD so hard.

**Comment by Botspot** [comment]
Yeah as long as shellcheck prints only green stuff, you're good. A syntax error, like a missing `"`,  would result in several yellow messages, and maybe a red one as well.
For a longer script, `shellcheck` spits out lots of slight complaints, and I've grown used to ignoring them.
But for your sake, I've added double backslashes like `shellckeck` asked for with commit 
9f5cf5eb9233c4ded856ab0edc53abb2f5cb4ad.
