### ISSUE TITLE
typo in 'app list style' tooltip in settings

### ISSUE THREAD

**Issue by Itai-Nelken** [Botspot/pi-apps#110]
![pi-apps-typo](https://user-images.githubusercontent.com/70802936/100488363-63e62200-3116-11eb-92c8-8a3077a66bcc.png)

**Comment by Itai-Nelken** [comment]
can be fixed in next big update, it's nothing really bad.

**Comment by Botspot** [comment]
Well, sure enough.

That's an easy fix. Thanks for noticing.
