### ISSUE TITLE
Submitting Godot update

### ISSUE THREAD

**Issue by irtexo** [Botspot/pi-apps#1101]
Updated install.txt to Godot 3.3.4 and Godot rpi support version to 1.7.0

[install.txt](https://github.com/Botspot/pi-apps/files/7448809/install.txt)

**Comment by Botspot** [comment]
Thank you for your submission. I've gone ahead and [uploaded](https://github.com/Botspot/pi-apps/commit/7c0ee8bb08fdfb3e554fb709a2eb5f25a8fec3ab) the changes to github. Next time, feel free to open a pull request. This will save you time, and it will save us time. To open a pull request:
- Find the file you want to edit on github.
- Click the little pencil icon. This will fork the repository and allow you to make changes yo your copy.
- After making changes, you will have the option to create a **pull request**.
- Pi-Apps maintainers will be able to review the changes you made and decide if we want to merge them.
- For us, merging takes only one click.
