### ISSUE TITLE
Add an new Minecraft Launcher with Microsoft account support

### ISSUE THREAD

**Issue by ALEGAMER20068** [Botspot/pi-apps#1106]
Thx :D

**Comment by Botspot** [comment]
You're right - we don't have **a** Minecraft launcher that supports Microsoft accounts... We have _two_!!

Pi-Apps has both Lunar launcher and Multimc5. Both of these launchers fully support Microsoft logins. If you don't see these apps in Pi-Apps, be sure it's up to date.

**Comment by shioyama** [comment]
I installed pi-apps to a fresh install of bullseye and Minecraft MultiMC5 worked like a charm. Then I migrated to Microsoft login, and everything works up until login, but after entering creds the launcher seems to just hang.

Any idea what's going on?

**Comment by Botspot** [comment]
> I installed pi-apps to a fresh install of bullseye and Minecraft MultiMC5 worked like a charm. Then I migrated to Microsoft login, and everything works up until login, but after entering creds the launcher seems to just hang.
> 
> Any idea what might be going on?

That is very strange. We have a [report](https://github.com/Botspot/pi-apps/issues/1336) that Lunar Client is doing the same thing.

**Comment by KolpixTV** [comment]
https://github.com/gl91306/launcherpi

does Microsoft Login works for you in this launcher @shioyama ? (btw. it's still in progress)

Steps to install the Launcher:

**1. Clone it**
**2. cd into the folder**
**3. do "npm i"**
**4. do "npm start"**

**Comment by gl91306** [comment]
> > I installed pi-apps to a fresh install of bullseye and Minecraft MultiMC5 worked like a charm. Then I migrated to Microsoft login, and everything works up until login, but after entering creds the launcher seems to just hang.
> > Any idea what might be going on?
> 
> That is very strange. We have a [report](https://github.com/Botspot/pi-apps/issues/1336) that Lunar Client is also doing the same thing.

well the thing is that this issue was created by the same person, so it might not be the launchers fault. It just might be that their proxy filters microsofts login page

**Comment by gl91306** [comment]
because if specifically microsoft accounts dont work for this person, then the issue is most likley client side

**Comment by gl91306** [comment]
this will be confirmed when logs are sent
