### ISSUE TITLE
Add import app to Wiki page

### ISSUE THREAD

**Issue by Crilum** [Botspot/pi-apps#1107]
I just looked at the Pi-Apps [wiki page about all the files in the `~/pi-apps` folder](https://github.com/Botspot/pi-apps/wiki/Directory-tree#below-is-an-explanation-for-every-single-file-in-the-pi-apps-folder), and noticed it didn't have `import-app` on it, under `etc`. 

Maybe we could add that?

**Comment by Botspot** [comment]
Should be good now. I found a few other missing entries, and [made those changes](https://github.com/Botspot/pi-apps/wiki/Directory-tree/_compare/890ba78338703539c153da0fa5fb0695c04200e1...3a7387c4a2c88c8f98e3fc2d38058a06c2c8973f) too.

Thanks for reaching out and letting us (me) know. :)
