### ISSUE TITLE
Spotify

### ISSUE THREAD

**Issue by Pythonic456** [Botspot/pi-apps#1108]
Spotify Web Player on Chromium or Min has issues (even when using Widevine):

- Skips songs after playing for 0 seconds
- Repeats ^ until it hits an ad, which it plays
- Repeat both of above until your frustration is too much and you defenestrate your Raspberry Pi

Jokes aside, this is very annoying. So maybe a way to run the Ubuntu version of Spotify, or some way of using wine?

**Comment by cycool29** [comment]
It's possible with Exagear (#1051), but Exagear is not yet up on Pi Apps as of its legal issue. You can import Exagear via the import-app tool, and start Exagear, and you can [install Spotify](https://www.spotify.com/us/download/linux/#:~:text=the%20command%20above.-,Debian%20/%20Ubuntu,-Spotify%20for%20Linux) like how you do in i686 Linux machines.

If Exagear is merged to pi-apps, I think Spotify will be the first app based on Exagear to be added to pi-apps.

**Comment by Crilum** [comment]
I use the linux Spotify desktop client every day, with the help of ExaGear. It works pretty well, unless your Pi is really being pushed (over 85-90% on all cores, Raspberry Pi 4 4G). It runs admirably well, for being a heavy music streamer/player on an emulated i686 (Intel 32-bit) system, on a Raspberry Pi 4 4G. That means that it's not very fast.. It works though:

[!https://user-images.githubusercontent.com/91354257/140267369-5fcf5921-46b7-48d1-9586-22d186ccb078.mp4](https://user-images.githubusercontent.com/91354257/140267369-5fcf5921-46b7-48d1-9586-22d186ccb078.mp4)

When I say it works, it does, but the account menu doesn't work, as well as the Filter bar in playlists.
If you are wondering, the yellow rectangle in covering my username.. :+1: 
If the install scripts aren't working for you, you can try this [tutorial](https://insrt.uk/post/exagear-install).

**Comment by Pythonic456** [comment]
ExaGear works with that tutorial, but how do I install Spotify in it? It seems to be using my host systems file system, and not a container? I would much appreciate any help on containerising this. Thanks!

**Comment by cycool29** [comment]
Start Exagear, and enter these commands:
```
wget -O spotify.deb https://repository-origin.spotify.com/pool/non-free/s/spotify-client/spotify-client_1.0.72.117.g6bd7cc73-35_i386.deb
sudo apt install ./spotify.deb
```

**Comment by Pythonic456** [comment]
I got Spotify running. I couldn't login with Facebook (which my primary account is on), so I had to use my email sign in, which is inconvenient. And the Spotify app fails when trying to use GPU acceleration.

**Comment by cycool29** [comment]
> I got Spotify running. I couldn't login with Facebook (which my primary account is on), so I had to use my email sign in, which is inconvenient. 

Can't test this since I use email as my primary login way.

> And when playing a song, no sound comes out of the speakers, and it doesn't initialize any kind of audio connection to pulse.

Weird. I can play music on my pi flawlessly.

**Comment by Crilum** [comment]
> And when playing a song, no sound comes out of the speakers, and it doesn't initialize any kind of audio connection to pulse.

I have no idea why yours doesn't output any sound. Mine did automatically, on multiple SD cards running RPiOS.
What OS and audio output do you use?
I have no idea if this will work, but ExaGear doesn't have pulseaudio installed, so you could try installing pulseaudio inside ExaGear.

>I got Spotify running. I couldn't login with Facebook (which my primary account is on), so I had to use my email sign in, which is inconvenient.

ExaGear does not have a web browser installed in the guest image as far as I can tell, and Facebook login requires a browser to open the little Facebook login website window, right? 
Try installing a light but Facebook capable browser.

>And the Spotify app fails when trying to use GPU acceleration.

Yes, it does fail to use GPU acceleration. Like I said, it's a Raspberry Pi running the Spotify desktop cilent though an emulated container. Give it some slack. 
You also can't use multiple Spotify windows because of this (I think. It just hangs after GPU acceleration errors).

**Comment by Pythonic456** [comment]
> I have no idea why yours doesn't output any sound. Mine did automatically, on multiple SD cards running RPiOS. What OS and audio output do you use?

Raspberry Pi 32-bit OS, BT audio.
> I have no idea if this will work, but ExaGear doesn't have pulseaudio installed, so you could try installing pulseaudio inside ExaGear.

Will try this. 
> ExaGear does not have a web browser installed in the guest image as far as I can tell, and Facebook login requires a browser to open the little Facebook login website window, right? Try installing a light but Facebook capable browser.

I installed Chromium but nothing happens when I click "Login with FaceBook".
> Yes, it does fail to use GPU acceleration. Like I said, it's a Raspberry Pi running the Spotify desktop cilent though an emulated container. Give it some slack. :) You also can't use multiple Spotify windows because of this (I think. It just hangs after GPU acceleration errors - What you were saying?).

Doesn't hang -  it just fails to use GPU acceleration. It works, but slow because of this.

**Comment by Crilum** [comment]
> Doesn't hang - it just fails to use GPU acceleration. It works, but slow because of this.

Yeah, but for me, if you try to open two simultaneous Spotify windows, it just hangs after the GPU acceleration errors.

**Comment by Pythonic456** [comment]
I installed Pulseaudio and it works fine now. I'm trying to find a way to get GPU acceleration working.

**Comment by cycool29** [comment]
There is a tutorial on how to enable hardware acceleration (I don't know if GPU acceleration is same with hardware acceleration) in `/opt/exagear/share/doc/user-guide.pdf`. You can try it out.

**Comment by Crilum** [comment]
Cool, thanks. I'll try it!

**Comment by Crilum** [comment]
I think this is kind of weird...

![no-full-kms](https://user-images.githubusercontent.com/91354257/140561391-2784c7fe-e6f5-40e0-b3dc-99a17f2a8f2c.png)

The ExaGear Hardware acceleration page in teh user guide says to use full kms, and to set it via `raspi-config`, but my `raspi-config` doesn't  have an option for Full KMS. I have seen it before in raspi-config, so I don't know why it's not there now.. 

I tried to set it by just changing the `config.txt` file GL driver line to 
```
[pi4]
# Enable DRM VC4 V3D driver on top of the dispmanx display stack
dtoverlay=vc4-kms-v3d
max_framebuffers=2
```

But everything appears to be the same...

**Comment by cycool29** [comment]
I can't see Full KMS in`raspi-config` too.
After some googling I found the full KMS for Pi 4 is still beta, but for Pi 2 and 3 is already live, as see in [this forum post](https://forums.raspberrypi.com/viewtopic.php?t=273202#p1657087).

Also, I found the user guide said:
> On Raspberry Pi 2 and Raspberry Pi 3 ExaGear supports hardware graphics acceleration. This
feature significantly increases performance of x86 applications that use OpenGL up to version
2.1.

So maybe that's only support Pi 2 and Pi 3...

**Comment by Crilum** [comment]
Yeah, that makes sense. 

@Pythonic456 @cycool29 Do either of you have a Pi 3 you could try it on? Mine is lacking a power supply at the moment.

**Comment by cycool29** [comment]
> Yeah, that makes sense.
> 
> @Pythonic456 @cycool29 Do either of you have a Pi 3 you could try it on? Mine is lacking a power supply at the moment.

No, I don't have a Pi 3.

**Comment by Pythonic456** [comment]
I have a 2B, although it is very slow compared to my 4.

**Comment by Crilum** [comment]
@Pythonic456 Well, I think you could still try it.

**Comment by ryanfortner** [comment]
Open-source spotify clients are also an option...

I've been using this application called Spot for a while: https://github.com/xou816/spot

It has almost all the functions of Spotify, except for downloading songs

**Comment by Crilum** [comment]
I wish it had an armhf build...

**Comment by cycool29** [comment]
> Open-source spotify clients are also an option...
> 
> I've been using this application called Spot for a while: https://github.com/xou816/spot
> 
> It has almost all the functions of Spotify, except for downloading songs

It only works with premium accounts.

**Comment by Crilum** [comment]
Yeah, and I really use offline mode...

**Comment by Pythonic456** [comment]
https://github.com/dtcooper/raspotify What about using this?

**Comment by cycool29** [comment]
> https://github.com/dtcooper/raspotify What about using this?

That is Spotify Connect, not Spotify client.

**Comment by Crilum** [comment]
I've used that, and it's good, as a Spotify Connect client. ***But***, it's not a GUI, and you can't control it from your Raspberry.

**Comment by leha-code** [comment]
Pi-ware has a working spotify app, maybe adapt its script?

**Comment by Pythonic456** [comment]
I just looked at Pi-Ware's github repo, and couldn't find a Spotify/anything that might be a Spotify client. Could you please link to the install script you mean?

**Comment by Pythonic456** [comment]
@leha-code I assume that this is the repository you mentioned: https://github.com/piware14/pi-ware
So where is the "Spotify" app?

**Comment by Crilum** [comment]
I have Pi-Ware installed, and I don't see any `Spotify`..

**Comment by Botspot** [comment]
Looks like they *used* to have Spotify?
I searched the repository and found [this commit](https://github.com/piware14/pi-ware/commit/56d6d4763d84f40b1c98141d8560a50e37401ba1) deleting Spotify.

**Comment by Crilum** [comment]
Ah, thanks @Botspot. I guess it didn't work?

**Comment by Crilum** [comment]
For anyone interested: RPiOS Bullseye comes with Full KMS enabled, and Spotify with ExaGear has hardware acceleration. It's still not fast, but is really not awful. @Pythonic456 Try signing in with facebook again.. I think the hardware acceleration might fix that.. All the menus and search bars work now.

**Comment by Pythonic456** [comment]
I will have to flash a MicroSD with Bullseye and try this. :)

**Comment by Crilum** [comment]
@Pythonic456 Just curious, have you tried it yet?

**Comment by Pythonic456** [comment]
@Crilum Not yet, will try to do it today and let you know how it goes.

**Comment by Pythonic456** [comment]
I have flashed a SD card with rpios bullseye, and have installed exagear with debian 8. I encountered a annoying thing: You don't seem to be able to become root in the exagear image. Fortunately, if you are root when you run exagear, you are root in the exagear image. Spotify has installed, but when running, it has no hardware acceleration. Here is the output:
```pi@raspberrypi:~ $ spotify 
libGL error: MESA-LOADER: malformed or no PCI ID
libGL error: unable to load driver: vc4_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: vc4
libGL error: MESA-LOADER: malformed or no PCI ID
libGL error: unable to load driver: vc4_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: vc4
[0130/132218.238110:ERROR:sandbox_linux.cc(344)] InitializeSandbox() called with multiple threads in process gpu-process.
pi@raspberrypi:~ $
```
(Btw, it doesn't crash - I just closed it.) Seems to want vc4_dri, but I can't find anything in the APT repos or online on how to go about setting it up/installing it. Any help would be appreciated.

**Comment by Pythonic456** [comment]
And you can't login with Facebook still. I installed Firefox in Exagear and can launch it, I then set it as the default browser. When I click "Login with Facebook" in Spotify, the `firefox-esr` process doesn't appear on the top list at all. Seems Spotify might fail somehow when trying to find a browser, am using `strace` to figure out what exactly is happening. I logged in with my email Spotify account, which works, and can play music just fine. Unfortunately, no graphics acceleration.

**Comment by Pythonic456** [comment]
@Crilum any ideas?

**Comment by Pythonic456** [comment]
> For anyone interested: RPiOS Bullseye comes with Full KMS enabled, and Spotify with ExaGear has hardware acceleration. It's still not fast, but is really not awful. @Pythonic456 Try signing in with facebook again.. I think the hardware acceleration might fix that.. All the menus and search bars work now.

I have installed it on Bullseye however no hardware acceleration still.

**Comment by Pythonic456** [comment]
@Crilum so did you manage to get hardware accel working?

**Comment by Crilum** [comment]
No, I didn't.. :cry: But, Spotify is definitely faster and more usable on Bullseye...

**Comment by Crilum** [comment]
Anyone that's interested might take a look at @MCRaspRBX's [Spotify Webapp](https://github.com/MCRaspRBX/Spotify).
It works for me! 

![image](https://user-images.githubusercontent.com/91354257/157755904-94ebccd8-4a7d-496f-b9e1-f61de50be2d1.png)

**Comment by ryanfortner** [comment]
> Anyone that's interested might take a look at @MCRaspRBX's Spotify Web app

It looks like it's just a Chromium desktop shortcut that goes to open.spotify.com...

**Comment by Crilum** [comment]
Yeah, it is.. But it's slightly different, It doesn't have the Spotify logo in the corner, and it doesn't have a `Download the App` button.. 

I guess it really is just the web player, but it feels a lot better to have it on the desktop.

**Comment by Botspot** [comment]
> But it's slightly different, It doesn't have the Spotify logo in the corner, and it doesn't have a `Download the App` button.

That could be due to the custom user-agent.

**Comment by Pythonic456** [comment]
I tried installing that repo, but unfortunately I still have the problem where I play a song, it skips after ~1 second, then continues to do that song after song until it manages to play the first ten seconds of a song, at which point the audio stops playing, then the whole Spotify UI becomes unresponsive.
I tried uninstalling Chromium and Chromium Widevine, then reinstalling both from Pi-Apps, still doesn't work.
Oh and by the way, when you click play for the first song since opening Spotify, it doesn't do anything for about 5 seconds.

https://user-images.githubusercontent.com/56113118/158015259-aebbf205-ba4f-4e7e-b671-7988b9cf3beb.mp4

Any ideas?

**Comment by Crilum** [comment]
What RPiOS/Debian version are you running? I'm on Bullseye, that might have something to do with it...

**Comment by Pythonic456** [comment]
Buster 32bit userspace, 64bit kernel.

**Comment by Crilum** [comment]
Yeah, in Buster, DRM is still broken I think, but it works in Bullseye!

**Comment by Crilum** [comment]
So I tried to make a qemu-powered x86 chroot, with [this tutorial](https://danct12.github.io/x86-chroot-on-ARM/), and the chroot worked, and the Spotify window opened, but then it just seg-faulted...

```
$ spotify

(process:3337): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.
Gtk-Message: Failed to load module "canberra-gtk-module"
qemu: unknown option 'type=gpu-process'
qemu: unknown option 'type=gpu-process'
qemu: unknown option 'type=gpu-process'
qemu: unknown option 'type=gpu-process'
qemu: unknown option 'type=gpu-process'
qemu: unknown option 'type=gpu-process'
qemu: unknown option 'type=gpu-process'
qemu: unknown option 'type=gpu-process'
[0412/222343.730152:ERROR:browser_gpu_channel_host_factory.cc(103)] Failed to launch GPU process.
qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped
[0412/222411.416909:ERROR:service_manager_context.cc(171)] Attempting to run unsupported native service: /usr/share/spotify/content_renderer.service
qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped
qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
Segmentation fault
```

**Comment by Crilum** [comment]
@Pythonic456 So, I just saw this, maybe it would work for you? https://community.spotify.com/t5/Accounts/Can-t-Login-via-Facebook-anymore/td-p/1210679

**Comment by Crilum** [comment]
It might be possible to use qemu-user with flatpak (only on 64 bit systems, though, cause the Spotify flatpak is x86_64 only).. https://www.reddit.com/r/linux/comments/n6x63p/til_that_flatpak_apps_can_emulate_nonnative_apps/

**Comment by Painadath** [comment]
well i am using spotify on my arm64 raspbain using chromium:arm32

**Comment by Crilum** [comment]
> well i am using spotify on my arm64 raspbain using chromium:arm32

Yes, Spotify Web Player works with Chromium and Bullseye.. I assume you're using Bullseye?

Also, you shouldn't need to use `chromium:armhf`, the arm64 version should work fine..

**Comment by theofficialgman** [comment]
many old widvine versions were disabled late last year. I doubt that any of the suggestions here still work

**Comment by Botspot** [comment]
Widevine is still alive and well. See the libwidevinecdm0:armhf package on the Raspberry Pi repositories.

**Comment by theofficialgman** [comment]
that isn't what I said
old widevine releases were blocked by google from working
only widevine versions from december 2022 onwards still work
many of the projects linked in the comments above are from before that time and haven't been updated since so they probably no longer work (except the webapp which at that point just use the web browser)

**Comment by Botspot** [comment]
Well for that matter it looks like the entire webapp is gone.
https://github.com/MCRaspRBX/Spotify

Enough people can simply use Chromium Widevine and use Spotify in the browser, with all the Pi tweaks out of the box.
However if someone reads this and wants a Spotify web app, feel free to make it and comment below.
