### ISSUE TITLE
TBOplayer doesn't open

### ISSUE THREAD

**Issue by fabianmendes** [Botspot/pi-apps#111]
I was trying a lot and it seems to be a problem from the script:
Only a missing "," before the "}". Expected: ",}"
![2020-11-27-222315_800x480_scrot](https://user-images.githubusercontent.com/31230743/100492428-4909b280-3102-11eb-86a1-bfee2b2f6614.png)

**I've fixed it but then it got me this next:**
![2020-11-27-223438_800x480_scrot](https://user-images.githubusercontent.com/31230743/100492445-69397180-3102-11eb-8747-bb4277355304.png)

**Comment by Botspot** [comment]
I've opened [an issue](https://github.com/KenT2/tboplayer/issues/190) for you on the TBOPlayer repository.

**Comment by fabianmendes** [comment]
Thaanks!

**Comment by heniotierra** [comment]
HI, @fabianmendes , tboplayer dev here. Seems like the error occurs in a dependency lib. Which python version are you using to run tboplayer?

**Comment by fabianmendes** [comment]
> HI, @fabianmendes , tboplayer dev here. Seems like the error occurs in a dependency lib. Which python version are you using to run tboplayer?

```

pi@basiliscus:~/ $ python /opt/tboplayer/tboplayer.py
Traceback (most recent call last):
  File "/opt/tboplayer/tboplayer.py", line 75, in <module>
    from youtubesearchpython import SearchVideos
  File "/home/pi/.local/lib/python2.7/site-packages/youtubesearchpython/__init__.py", line 1, in <module>
    from youtubesearchpython.videos__search import SearchVideos
  File "/home/pi/.local/lib/python2.7/site-packages/youtubesearchpython/videos__search.py", line 3, in <module>
    from youtubesearchpython.__requesthandler import RequestHandler
  File "/home/pi/.local/lib/python2.7/site-packages/youtubesearchpython/__requesthandler.py", line 4, in <module>
    from urllib import urlencode, urlopen, Request
ImportError: cannot import name Request
pi@basiliscus:~/ $ python3 /opt/tboplayer/tboplayer.py
  File "/opt/tboplayer/tboplayer.py", line 1078
    except KeyError, er:
                   ^
SyntaxError: invalid syntax


```
At first python (2.7) but I've tried then with python3 and got me another syntax error. Also, consider my first correction (missing ","). All these I was after fixing that (now, it' says there is another syntax error) @heniotierra

**Comment by fabianmendes** [comment]
After _fixing_ all Exception **as** e: instead ","
It got me this: (**dismiss** the _.local/share/applications_ $ )
```
pi@basiliscus:~/.local/share/applications $ python3 /opt/tboplayer/tboplayer.py
Traceback (most recent call last):
  File "/opt/tboplayer/tboplayer.py", line 59, in <module>
    from options import *
  File "/opt/tboplayer/options.py", line 3, in <module>
    import ConfigParser
ModuleNotFoundError: No module named 'ConfigParser'
```
![2020-11-28-001830_800x480_scrot](https://user-images.githubusercontent.com/31230743/100493643-5a0cf080-310f-11eb-95b0-a014997ea5c4.png)

**Comment by heniotierra** [comment]
@Botspot can you please update the branch you wget the program from? It should be installed from master branch.

**Comment by heniotierra** [comment]
@fabianmendes try to install with

```
    cd ~ && wget https://github.com/KenT2/tboplayer/tarball/master -O - | tar xz &&
    cd KenT2-tboplayer-* && chmod +x setup.sh && ./setup.sh
```

**Comment by fabianmendes** [comment]
I don't know because I did it using Pi-Apps

On Nov 28, 2020 12:42 AM, "heniotierra" <notifications@github.com> wrote:

@Botspot <https://github.com/Botspot> can you please update the branch you
wget the program from? It should be installed from master branch.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Botspot/pi-apps/issues/111#issuecomment-735039163>, or
unsubscribe

**Comment by fabianmendes** [comment]
@heniotierra same. I think that these **Exception, e:** should be **Exception as e:** instead, you know
```

pi@basiliscus:~ $ python /opt/tboplayer/tboplayer.py
  File "/opt/tboplayer/tboplayer.py", line 1279
    except Exception e:
                     ^
SyntaxError: invalid syntax
pi@basiliscus:~ $ python3 /opt/tboplayer/tboplayer.py
  File "/opt/tboplayer/tboplayer.py", line 1078
    except KeyError, er:
                   ^
SyntaxError: invalid syntax

```

**Comment by fabianmendes** [comment]
> @heniotierra same. I think that these **Exception, e:** should be **Exception as e:** instead, you know
> 
> ```
> 
> pi@basiliscus:~ $ python /opt/tboplayer/tboplayer.py
>   File "/opt/tboplayer/tboplayer.py", line 1279
>     except Exception e:
>                      ^
> SyntaxError: invalid syntax
> pi@basiliscus:~ $ python3 /opt/tboplayer/tboplayer.py
>   File "/opt/tboplayer/tboplayer.py", line 1078
>     except KeyError, er:
>                    ^
> SyntaxError: invalid syntax
> ```

```
pi@basiliscus:~ $ python3 /opt/tboplayer/tboplayer.py
Traceback (most recent call last):
  File "/opt/tboplayer/tboplayer.py", line 59, in <module>
    from options import *
  File "/opt/tboplayer/options.py", line 3, in <module>
    import ConfigParser
ModuleNotFoundError: No module named 'ConfigParser'
pi@basiliscus:~ $ python /opt/tboplayer/tboplayer.py
Traceback (most recent call last):
  File "/opt/tboplayer/tboplayer.py", line 75, in <module>
    from youtubesearchpython import SearchVideos
  File "/home/pi/.local/lib/python2.7/site-packages/youtubesearchpython/__init__.py", line 1, in <module>
    from youtubesearchpython.videos__search import SearchVideos
  File "/home/pi/.local/lib/python2.7/site-packages/youtubesearchpython/videos__search.py", line 3, in <module>
    from youtubesearchpython.__requesthandler import RequestHandler
  File "/home/pi/.local/lib/python2.7/site-packages/youtubesearchpython/__requesthandler.py", line 4, in <module>
    from urllib import urlencode, urlopen, Request
ImportError: cannot import name Request

```
(all this after doing this )

**Comment by heniotierra** [comment]
This version of tboplayer is not really meant for python3. I injected those bugs there. :( But you fixed it. :) Thank you.

**Comment by fabianmendes** [comment]
> This version of tboplayer is not really meant for python3. But we did have another version that kinda worked for python3. Anyway, I injected those bugs there. :( But you fixed them. :) Thank you.

That's good to know haha. Anyway, I was only trying with both. Anyways there are still some problems, I would like to open an issue about it, or flag it at #KenT2/tboplayer/issues/190 

I'm glad to be helpful. I wonder your app come to work soon, I want to give it a try for sure!!

**Comment by heniotierra** [comment]
>  I would like to open an issue about it
Please, go ahead!

**Comment by Botspot** [comment]
> @Botspot can you please update the branch you wget the program from? It should be installed from master branch.

Sure.

**Comment by Botspot** [comment]
I did not mean to close this issue.

**Comment by Botspot** [comment]
@fabianmendes Has this issue been solved for you yet?

**Comment by fabianmendes** [comment]
Not at all

On Nov 29, 2020 9:35 PM, "Botspot" <notifications@github.com> wrote:

@fabianmendes <https://github.com/fabianmendes> Has this issue been solved
for you yet?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Botspot/pi-apps/issues/111#issuecomment-735497903>, or
unsubscribe

**Comment by Botspot** [comment]
@fabianmendes Hmm. Strange. I just reinstalled tboplayer and it still works fine for me.

Perhaps it would work for you if you reinstalled it? (and made sure pi-apps is up to date?)

**Comment by fabianmendes** [comment]
Ok, ill try again

**Comment by fabianmendes** [comment]
Could you open it? I'm still not able to run the app, also seems to _pip3_ does nothing, I've tried out to run the app with _python3_ instead, then I got an error:

![2020-11-29-230034_800x480_scrot](https://user-images.githubusercontent.com/31230743/100564215-c403d200-3296-11eb-971f-fbb8322b8be5.png)

**Comment by Botspot** [comment]
Yes, it launches fine for me.

IDK what's going on for you, but hopefully @heniotierra can figure it out.

**Comment by heniotierra** [comment]
@fabianmendes @Botspot  As I said before, this seems like a problem in the lastest version of a dependency, breaking python2 compatibility.

Try to downgrade the lib version running:

> pip uninstall youtube-search-python
pip install youtube-search-python==1.3.1

**Comment by fabianmendes** [comment]
![2020-11-30-100337_800x480_scrot](https://user-images.githubusercontent.com/31230743/100621092-9a2dc800-32f5-11eb-967e-3bbea3c76121.png)

Yes, It works now! (now I'm testing it..) Otherwise, you should put on the pi-apps install youtube-search-pythom==1.3.1 only. Also, it creates a shortcut on the menu that runs "pip3 ..." instead of "python ..." you may see:  | or create a _requirements.txt_ file, @heniotierra  I don't know.
![2020-11-30-100644_800x480_scrot](https://user-images.githubusercontent.com/31230743/100620708-196ecc00-32f5-11eb-9679-b0991fcf6444.png)

Also, @heniotierra, this gives an error about _duration_ after typing an URL. Should I create an issue on TBOplayer's Github? 
![2020-11-30-101336_800x480_scrot](https://user-images.githubusercontent.com/31230743/100621032-7ff3ea00-32f5-11eb-95ac-e128a10946fa.png)

Even with playlist URL. Please, help. @Botspot could you ver listen or play any video? Because it says 'duration' error. So, I don't think that it's still my raspberry pi failure :(
```
python /opt/tboplayer/tboplayer.py 
2020-11-30 10:09:27,067 - /opt/tboplayer/debugging.pyc - ERROR - Traceback (most recent call last):
  File "/opt/tboplayer/tboplayer.py", line 1102, in set_progress_bar
    self.progress_bar_step_rate = self.omx.timenf['duration']/self.progress_bar_total_steps
KeyError: 'duration'

```

**Comment by Botspot** [comment]
@heniotierra I just tried it - TBOPlayer played a youtube video perfectly. (Though clicking Stop did nothing. I had to close tboplayer to stop the video. Weird.)

But it played, and that's what you asked.

**Comment by heniotierra** [comment]
>  it creates a shortcut on the menu that runs "pip3 ..." instead of "python ..." 

That's weird, I should look into it.

> Even with playlist URL. Please, help. @Botspot could you ver listen or play any video? Because it says 'duration' error. So, I don't think that it's still my raspberry pi failure :(

Does that happen to you with any file? With streams too, like youtube?

**Comment by fabianmendes** [comment]
Ok, they were just downloading it. Anyway, I play it, but it didn't make any sound. So, I went to Options> I saw that Audio Output was set to HDMI only, then click > ALSA, but I can't click on Apply/Accept/Ok. I don't know because my display doesn't allow me, and resizing the windows can't help because it doesn't scroll it (may you please create a release with a scroll feature? @heniotierra. Any help to switch it from another way meanwhile?)
![2020-11-30-102958_800x480_scrot](https://user-images.githubusercontent.com/31230743/100622790-a87ce380-32f7-11eb-94f7-529aa5435851.png)

**Comment by Botspot** [comment]
> I can't click on Apply/Accept/Ok. I don't know because my display doesn't allow me, and resizing the windows can't help because it doesn't scroll it

Press and hold Alt, then click and drag the window around.

**Comment by fabianmendes** [comment]
> > I can't click on Apply/Accept/Ok. I don't know because my display doesn't allow me, and resizing the windows can't help because it doesn't scroll it
> 
> Press and hold Alt, then click and drag the window around.

Thaaanks. Now I can listen to youtube! Amazing app, of course, thanks. @heniotierra shout-out to you and your team, anyways, please consider my observations. And @Botspot, please change the _pip3_ for _python_ run command on the desktop file, when you have time. And I don't know if you can specify on the _install-pkg **youtube-search-python=1.3.1**_



> > it creates a shortcut on the menu that runs "pip3 ..." instead of "python ..."
> 
> That's weird, I should look into it.
> 
> > Even with playlist URL. Please, help. @Botspot could you ver listen or play any video? Because it says 'duration' error. So, I don't think that it's still my raspberry pi failure :(
> 
> Does that happen to you with any file? With streams too, like youtube?

It was downloading, would be nice if it show up a message notifying abou internet network connection problem or something (I just had to wait a bit, not worries about that _duration_ issue).

**I don't click Close with comment, because it is necessary to change the run command from desktop** pip3 > python.

**Comment by Botspot** [comment]
> **I don't click Close with comment, because it is necessary to change the run command from desktop** pip3 > python.

That's out of my control. TBOPlayer's [setup.sh](https://github.com/KenT2/tboplayer/blob/master/setup.sh#L202) is what creates the menu button.

I took a look in there and it's [using python](https://github.com/KenT2/tboplayer/blob/master/setup.sh#L202) as it should. IDK how you saw pip3 in there. Best guess: you changed it?

Try uninstalling tboplayer one last time, make sure the menu button disappeared, then install it again and see if it's still trying to run tboplayer with `pip3`.

**Comment by fabianmendes** [comment]
No, I didn't. I hace changed it Just now after running it properly on my
terminal. Let me do that, uninstalling making sure that and the installing
again. Also, remember to maje terminal downloads only YouTube será Python
== 1.3.1 please

**Comment by fabianmendes** [comment]
Done. Thanks a lot!

![2020-11-30-111956_800x480_scrot](https://user-images.githubusercontent.com/31230743/100628045-2ba13800-32fe-11eb-9f0a-a316acf21841.png)
Haha, sorry if  I'm bothering you too much. Also, remember the restriction to install only the y.s.p. == 1.3.1 hehe @heniotierra @Botspot

**Comment by Botspot** [comment]
> Also, remember the restriction to install only the y.s.p. == 1.3.1

That's @heniotierra 's department. Pi-Apps install script doesn't install ysp, it runs tboplayer's setup.sh script.

> Done. Thanks a lot!

Glad you have it working!

**Comment by heniotierra** [comment]
> may you please create a release with a scroll feature? @heniotierra. Any help to switch it from another way meanwhile?

I guess I can find the time for that, but it may take a while.

>  Also, remember the restriction to install only the y.s.p. == 1.3.1

This I can do later on today.

**Comment by fabianmendes** [comment]
Dont worry It's okay, about scrolling - take your time; @Botstop helped a
lot with hold ALT. Thank you, wish you the best and keep doing it right!!

**Comment by Botspot** [comment]
> Dont worry It's okay, about scrolling - take your time; @BotStop helped a lot with hold ALT. Thank you, wish you the best and keep doing it right!!

Whoa - who is @BotStop? Looks like that's another github account! Funny typo. ;)

**Comment by fabianmendes** [comment]
Hahhahah its my smartphone (such smart huh) keyboard dictionary..

On Nov 30, 2020 2:00 PM, "Botspot" <notifications@github.com> wrote:

Dont worry It's okay, about scrolling - take your time; @BotStop
<https://github.com/BotStop> helped a lot with hold ALT. Thank you, wish
you the best and keep doing it right!!

Whoa - who is @BotStop <https://github.com/BotStop>? Looks like that's
another github account! Funny typo. ;)

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/Botspot/pi-apps/issues/111#issuecomment-735946105>, or
unsubscribe

**Comment by Botspot** [comment]
Three more people on Discord just reported this same problem is still occurring.

**Comment by fabianmendes** [comment]
It's for youtube-search-version for sure, did they say what log (terminal)
says?

**Comment by heniotierra** [comment]
@Botspot May you can tell them to try again now. I think something went wrong during the push for the fix yesterday. I just pushed it again now.

**Comment by Botspot** [comment]
Everyone on Discord says it's working for them now. Thanks @heniotierra!

**Comment by fabianmendes** [comment]
@Botspot TBOplayer doesn't work (does not reproduce/play anything) because omxplayer is not installable on arm64 architecture for a large couple of dependences, in the case of install-64 we will need to install all dependences:armhf @heniotierra

**Comment by fabianmendes** [comment]
ok, for installing **omxplayer**, here are the dependences. To install **omxplayer** and being able to use TBOplayer @heniotierra 
`sudo apt-get install libavcodec58:armhf libavformat58:armhf libraspberrypi0:armhf libssh-gcrypt-4:armhf libgssapi-krb5-2:armhf libkrb5-3:armhf libssl1.1:armhf`

**Comment by fabianmendes** [comment]
> ok, for installing **omxplayer**, here are the dependences. To install **omxplayer** and being able to use TBOplayer @heniotierra
> `sudo apt-get install libavcodec58:armhf libavformat58:armhf libraspberrypi0:armhf libssh-gcrypt-4:armhf libgssapi-krb5-2:armhf libkrb5-3:armhf libssl1.1:armhf`
> 
> EDIT: after adding armhf, of course. `sudo --add-architecture armhf`

WARNING: an unexpected behavior (I didn't know): installing them or running that command line will delete almost everything on your raspberry pi (libs)

**Comment by Itai-Nelken** [comment]
>EDIT: after adding armhf, of course. sudo --add-architecture armhf

its `sudo dpkg --add-architecture armhf`

**Comment by 492citizen** [comment]
I am experiencing the same issue on my Pi 3B+:

`ImportError: No module named youtubesearchpython`

I am using python 2.7

**Comment by Botspot** [comment]
> I am experiencing the same issue on my Pi 3B+:
> 
> `ImportError: No module named youtubesearchpython`
> 
> I am using python 2.7
> 
> Installation process:
> Cloned the repository to my desktop and ran setup.sh. Also manually installed the dependencies to be sure.
> 
> Just typing "tboplayer" in my terminal gives me the error.

@heniotierra ^
