### ISSUE TITLE
Alacritty - OpenGL terminal emulator

### ISSUE THREAD

**Issue by ryanfortner** [Botspot/pi-apps#1115]
Project homepage: https://github.com/alacritty/alacritty

Can this app run on RPi? If so, please provide a link to a tutorial if applicable.

- Yes. I was only able to compile it for armhf though.

Is this app something many GUI users would find useful?

- Yes, it's a terminal emulator which uses the GPU for rendering.

Is this app installable with `sudo apt install`?

- No, it's not available in the rpi repositories.

If you've created a zip file for this app, upload it here.

- No zip file at the moment, but it's on my list.
- I have a .deb file in my repository, can be downloaded here: https://apt.raspbian-addons.org/debian/pool/alacritty_0.6.0_armhf.deb

**Comment by Crilum** [comment]
Works for me. I'll make the scripts.

**Comment by Crilum** [comment]
@ryanfortner Question. Did you make the .deb? Just want to know so I can thank you properly in the credits. :)

**Comment by ryanfortner** [comment]
> @ryanfortner Question. Did you make the .deb? Just want to know so I can thank you properly in the credits. :)

Yes, I made the deb.

**Comment by ryanfortner** [comment]
@Crilum please also credit the creator of piKiss, @jmcerrejon, for creating compile scripts

**Comment by Crilum** [comment]
Here is the .zip:
[Alacritty.zip](https://github.com/Botspot/pi-apps/files/7488742/Alacritty.zip)

**Comment by Crilum** [comment]
Here is another version which uses `install_packages` and `purge_packages`:
[Alacritty.zip](https://github.com/Botspot/pi-apps/files/7489275/Alacritty.zip)

**Comment by Crilum** [comment]
Somehow this happens:

![howdidthishappen](https://user-images.githubusercontent.com/91354257/140588725-e23d69bb-4119-4d16-9a9d-f951edc27639.png)

@Botspot Do you have any idea what could have caused this?

**Comment by cycool29** [comment]
> Somehow this happens:
> 
> ![howdidthishappen](https://user-images.githubusercontent.com/91354257/140588725-e23d69bb-4119-4d16-9a9d-f951edc27639.png)
> 
> @Botspot Do you have any idea what could have caused this?

Not for me, it shows properly on pi-apps. Did you put the folder in the right place?

**Comment by Crilum** [comment]
@cycool29 Yeah... If I rename the app folder to `wut` it works.. :D

**Comment by cycool29** [comment]
![image](https://user-images.githubusercontent.com/88134003/140602163-dba9fdc3-0338-44a3-9458-c95738535e05.png)

Uhh..

**Comment by Crilum** [comment]
Yes, I agree. The `InternetAlacritty` category is quite odd. This happens when I import the `Alacritty` folder, or just copy it...

**Comment by ryanfortner** [comment]
@Crilum i've opened a pr with the changes, and also updated the .desktop file in the deb so that the terminal launches from the user's current directory, not /opt/alacritty.

**Comment by Botspot** [comment]
The `InternetAlacritty` category issue has been solved with commit https://github.com/Botspot/pi-apps/commit/cc9fbe1b4210275256563449a8b30b70e09956c6.

**Comment by Crilum** [comment]
Thank you @Botspot!
