### ISSUE TITLE
Selecting Multiple Apps and then Pressing Info Garbage Details

### ISSUE THREAD

**Issue by theofficialgman** [Botspot/pi-apps#1117]
If you select multiple apps with ctrl or shift, then press the info button, the info screen still loads but you get useless info about the apps

maybe rotate through the multiple apps info? or just show the last app selected in the lists info (picture attached in next post)

**Comment by theofficialgman** [comment]
![Screenshot from 2021-11-05 16-35-17](https://user-images.githubusercontent.com/28281419/140575432-1752155d-8e88-49ca-be0e-c856707b3c2d.png)

**Comment by theofficialgman** [comment]
I'm willing to help code something for this, just let me know what functionality you would like

**Comment by Botspot** [comment]
With commit https://github.com/Botspot/pi-apps/commit/722851e1eb1095480921a2004522b5cf14e590a4, if multiple items are selected, only the first item is honored.

**Comment by theofficialgman** [comment]
alright, good enough
