### ISSUE TITLE
Pulseaudio & Discord

### ISSUE THREAD

**Issue by Crazily** [Botspot/pi-apps#112]
Set the discord install script to install pulseaudio & pavucontrol if it is not installed already. In Raspberry PI OS the microphone cannot be used until pulseaudio is installed.

**Comment by fabianmendes** [comment]
And it dos work with ALSA player? (I don't know, The other opposite output
audio service)

**Comment by Botspot** [comment]
@Crazily This would anger many, many Raspberry Pi users.

On Raspbian, Pulseaudio is notorious for causing problems, including outputting to the wrong output device, audio cracking up, not playing back at all, ignoring volume settings, and completely breaking Sonic Pi.

I'll ask the Discord dev, @spacingbat3 , to see what's going on.

**Comment by mobilegmYT** [comment]
I use PulseAudio myself, but even there, the mic is still broken

**Comment by Botspot** [comment]
Yeah, there's nothing I can do about it. @spacingbat3 says he can't do anything about it either.

Try getting your mic to work in chromium, and once that works, @spacingbat3 says it should work in Electron too.
