### ISSUE TITLE
Installing cronky  in bullseye ends  with  30 secs sh: 1: /opt/vc/bin/vcgencmd: not found

### ISSUE THREAD

**Issue by tom-eilers-nl** [Botspot/pi-apps#1124]
At the end of installing cronky  the terminal display during 30 secs 
sh: 1: /opt/vc/bin/vcgencmd: not found
sh: 1: /opt/vc/bin/vcgencmd: not found
sh: 1: /opt/vc/bin/vcgencmd: not found
etc.
Tested installing cronky manual this doesn't happen.
Also tested flamshot no problem.

**Comment by Itai-Nelken** [comment]
What isnyour OS?

**Comment by ryanfortner** [comment]
Seems like `vcgencmd` has been moved out of /opt/vc/bin/ and into /usr/bin in bullseye. I've opened a pr on botspot's conky repo for the changes: https://github.com/Botspot/rpi_conky/pull/1

**Comment by Botspot** [comment]
> Seems like `vcgencmd` has been moved out of /opt/vc/bin/ and into /usr/bin in bullseye. I've opened a pr on botspot's conky repo for the changes: [Botspot/rpi_conky#1](https://github.com/Botspot/rpi_conky/pull/1)

Pull request merged. I've [bumped](https://github.com/Botspot/pi-apps/commit/aa17e8a4c35a3c53c7cc8a8f59bf4654af88599f) the Conky app so everyone sees it as an update.

@tom-eilers-nl, the problem should be solved now. (after updating the Conky app)

**Comment by ryanfortner** [comment]
Can this issue be closed now?

**Comment by tom-eilers-nl** [comment]
Yes thank you.
Every thing works.
