### ISSUE TITLE
The Uninstall Script of Vivaldi does not work correctly

### ISSUE THREAD

**Issue by KolpixTV** [Botspot/pi-apps#1125]
It's not deleting Vivaldi. I just edit the uninstall script so it's working.
[Vivaldi.zip](https://github.com/Botspot/pi-apps/files/7499331/Vivaldi.zip)

**Comment by cycool29** [comment]
`purge-installed` should already purge `vivaldi-stable`, unless you marked it as manual-installed in APT.

**Comment by KolpixTV** [comment]
Oh ok
