### ISSUE TITLE
App editor fails to use install_packages and purge_packages

### ISSUE THREAD

**Issue by Crilum** [Botspot/pi-apps#1127]
When I click the `Run install-32` or `Run install-64` button, if my install script uses `install_packages` or `purge_packages`, it fails with the error:
```
/home/pi/pi-apps/apps/Electron Fiddle/install-32: line 11: install_packages: command not found
Closing in 10 seconds.

```

If you just use the install/uninstall button, it works, but not with the App Editor..

**Comment by cycool29** [comment]
All the functions in `api` are not working.

**Comment by Botspot** [comment]
Fixed with commit https://github.com/Botspot/pi-apps/commit/12ff3d61c214ddaed345f4496234a7c4f389c7ca.
