### ISSUE TITLE
 Add Roblox wine kali, ubunntu and mamjo

### ISSUE THREAD

**Issue by Abdullah22-rgb** [Botspot/pi-apps#1136]
Is this app installable with `sudo apt install`?

If you've created a zip file for this app, upload it here.

it got to run on box64

**Comment by cycool29** [comment]
Not really understand what you mean. Do you mean you want to add Roblox?
How it works? You said it worked with box64, where do you download the binary?

Also, what is mamjo? 

Please provide a **clear** description about what you want. This will help others to understand what you mean easier.

**Comment by cycool29** [comment]
I don't think Roblox will work well on a pi, as it **don't even have a Linux client**. To make it work we need Wine + Box86 emulation which is **extremely** slow and user won't get a smooth game experience.

See [this forum answer](https://beta.raspberrypi.org/forums/viewtopic.php?t=307434#p1896339).

**Comment by Abdullah22-rgb** [comment]
ya that will work hopeful
