### ISSUE TITLE
Try to make pi-app onto manjo

### ISSUE THREAD

**Issue by Abdullah22-rgb** [Botspot/pi-apps#1137]
Can this app run on RPi? If so, please provide a link to a tutorial if applicable.

Is this app something many GUI users would find useful?

Is this app installable with `sudo apt install`?

If you've created a zip file for this app, upload it here.

**Comment by cycool29** [comment]
When you say 'manjo', I assume you mean Manjaro Linux. 

Pi-apps is not gonna to be in Manjaro, as it is a Arch-based distro, and pi-apps only supports debian-like distros.

![image](https://user-images.githubusercontent.com/88134003/141243630-f1031098-5d08-4199-b31f-c21f55e5caa2.png)

**Comment by Abdullah22-rgb** [comment]
ok

**Comment by Crilum** [comment]
@Abdullah22-rgb If you really want to install Pi-Apps on Manjaro, I edited the install script so it can be used on Manjaro, or probably any arch-based distro, which can be found in #1090. You can also find a little more in-depth explanation of why Pi-Apps can't be used on Manjaro.

WARNING: If you install Pi-Apps with the edited script, you probably won't be able to install any of the apps or do anything besides open the GUI and look at app's descriptions.
