### ISSUE TITLE
Steam with Wine

### ISSUE THREAD

**Issue by PGSCOM** [Botspot/pi-apps#1138]
Can this app run on RPi? If so, please provide a link to a tutorial if applicable.
I think it will, because it can run and install Steam for Linux.
Is this app something many GUI users would find useful?
Yes, you can use it for download exclusive Windows Steam games/programs in Raspbian

[Steam client](https://store.steampowered.com/about/)

**Comment by Abdullah22-rgb** [comment]
I like your idea

**Comment by Abdullah22-rgb** [comment]
what about ubnutu, kali

**Comment by Abdullah22-rgb** [comment]
and it got to run on box64

**Comment by PGSCOM** [comment]
Umm... I´ll try it
