### ISSUE TITLE
Future - App Request

### ISSUE THREAD

**Issue by necro-nemesis** [Botspot/pi-apps#114]
Love this project. Just a heads up I've written and tested an installer but the fully working deployed application is just on the verge of being rebranded.  Similar to TOR (I see the browser is now here) but with 1300+ rapidly growing globally distributed nodes, exit nodes and broader capabilities as UDP is also supported. Not in any other Raspberry repo anywhere atm this would likely be it's introduction to the pi. All code is open source. I've been working on parts of the ARM end of development for a couple years now and would be very honored to be added here. Current repo below but as I say this is a heads up for when I will put in a formal request when rebranded and the code is updated accordingly. 

https://github.com/necro-nemesis/pi-apps/tree/master/apps/Lokinet

Keep up the awesome work and keep growing! Impressive.

**Comment by Botspot** [comment]
Wow this is really impressive.

Does it include its own, dedicated browser? (Like how Tor uses modified Firefox)  
Or is it like a proxy server that pre-existing browsers connect to?

In any case, this looks like a good addition to Pi-Apps. Let me know when it's ready and I'll re-open the issue.

**Comment by necro-nemesis** [comment]
Use existing browsers. No specific one for it yet. I believe the intent is to focus on the network presently but provide guidance on how to configure an existing browser better for privacy. At least that's where the current discussions on browser are focused. Sits as a definite future consideration once there's time to not only produce but maintain it. Yes forking an existing open source browser would be the most viable option on that front.
