### ISSUE TITLE
`apt_update` ignoring release files when processing local repository

### ISSUE THREAD

**Issue by cycool29** [Botspot/pi-apps#1141]
From the output of `install_packages` shows these messages:
```
Running sudo apt update...
Ign:1 file:/tmp/pi-apps-local-packages ./ InRelease
Ign:2 file:/tmp/pi-apps-local-packages ./ Release
Ign:3 file:/tmp/pi-apps-local-packages ./ Packages
Ign:4 file:/tmp/pi-apps-local-packages ./ Translation-en_US
Ign:5 file:/tmp/pi-apps-local-packages ./ Translation-en
Ign:6 file:/tmp/pi-apps-local-packages ./ Translation-en_US.UTF-8
Ign:3 file:/tmp/pi-apps-local-packages ./ Packages
Ign:4 file:/tmp/pi-apps-local-packages ./ Translation-en_US
Ign:5 file:/tmp/pi-apps-local-packages ./ Translation-en
Ign:6 file:/tmp/pi-apps-local-packages ./ Translation-en_US.UTF-8
Ign:3 file:/tmp/pi-apps-local-packages ./ Packages
Ign:4 file:/tmp/pi-apps-local-packages ./ Translation-en_US
Ign:5 file:/tmp/pi-apps-local-packages ./ Translation-en
Ign:6 file:/tmp/pi-apps-local-packages ./ Translation-en_US.UTF-8
Ign:3 file:/tmp/pi-apps-local-packages ./ Packages
Ign:4 file:/tmp/pi-apps-local-packages ./ Translation-en_US
Ign:5 file:/tmp/pi-apps-local-packages ./ Translation-en
Ign:6 file:/tmp/pi-apps-local-packages ./ Translation-en_US.UTF-8
Ign:3 file:/tmp/pi-apps-local-packages ./ Packages
Ign:4 file:/tmp/pi-apps-local-packages ./ Translation-en_US
Ign:5 file:/tmp/pi-apps-local-packages ./ Translation-en
Ign:6 file:/tmp/pi-apps-local-packages ./ Translation-en_US.UTF-8
Ign:3 file:/tmp/pi-apps-local-packages ./ Packages
Ign:4 file:/tmp/pi-apps-local-packages ./ Translation-en_US
Ign:5 file:/tmp/pi-apps-local-packages ./ Translation-en
Ign:6 file:/tmp/pi-apps-local-packages ./ Translation-en_US.UTF-8
Ign:4 file:/tmp/pi-apps-local-packages ./ Translation-en_US
Ign:5 file:/tmp/pi-apps-local-packages ./ Translation-en
Ign:6 file:/tmp/pi-apps-local-packages ./ Translation-en_US.UTF-8
Hit:7 https://itai-nelken.github.io/weekly-box86-debs/debian  InRelease
Hit:8 http://archive.raspberrypi.org/debian bullseye InRelease
All packages are up to date.
```

But the deb still installed successfully. 

**EDIT**: I found a APT config string `::Ignore-Files-Silently`, it will remove the `Ign` message. Tested working.

**Comment by theofficialgman** [comment]
thats the output from this function isn't it? not install_packages itself
(cut off the end for shortness)
```
apt_update() { #run an apt update with error-checking and minimal output
  apt_lock_wait
  
  status "Running \e[7msudo apt update\e[27m..."
  output="$(sudo -E apt update --allow-releaseinfo-change "$@" 2>&1 | less_apt | tee /dev/stderr)"
  exitcode=$?
  status "apt update complete."
  ```

**Comment by theofficialgman** [comment]
the real question is... whey are those ignores getting reported multiple times duplicated?

**Comment by cycool29** [comment]
> thats the output from this function isn't it? not `install_packages` itself (cut off the end for shortness) called here:
> 
> ```
>   packages="$(tr '\n' ' ' <<<"$packages")"
>   
>   if [ "$using_local_packages" == 1 ];then
>     #Initialize the pi-apps-local-packages repository
>     repo_refresh
>     #add this repository to flags to add to apt
>     apt_flags+=(-o 'Dir::Etc::SourceList=/tmp/pi-apps-local-packages/source.list')
>   fi
>   #run an apt update
>   apt_update "${apt_flags[@]}" || exit 1
> ```
> 
> ```
> apt_update() { #run an apt update with error-checking and minimal output
>   apt_lock_wait
>   
>   status "Running \e[7msudo apt update\e[27m..."
>   output="$(sudo -E apt update --allow-releaseinfo-change "$@" 2>&1 | less_apt | tee /dev/stderr)"
>   exitcode=$?
>   status "apt update complete."
> ```

Not really. This is caused by `add_repo` local repository. Nothing wrong with `apt_update`.


 


> the real question is... whey are those ignores getting reported multiple times duplicated?

Ya, that is weird too.

**Comment by theofficialgman** [comment]
are you sure? pretty sure it comes from the `apt_flags+=(-o 'Dir::Etc::SourceList=/tmp/pi-apps-local-packages/source.list')` getting added and then `  apt_update "${apt_flags[@]}"` getting called

**Comment by theofficialgman** [comment]
yeah thats it... because repo_refresh is what adds the specific files to the source.list
  `echo "deb [trusted=yes] file:/tmp/pi-apps-local-packages/ ./" > /tmp/pi-apps-local-packages/source.list`

**Comment by cycool29** [comment]
> are you sure? pretty sure it comes from the `apt_flags+=(-o 'Dir::Etc::SourceList=/tmp/pi-apps-local-packages/source.list')` getting added and then ` apt_update "${apt_flags[@]}"` getting called

Yes, that is the problem of `SourceList=/tmp/pi-apps-local-packages/source.list`, which points to the pi-apps local repository. And the repository don't have those `Release` `InRelease` files, so apt ignored it.

**Comment by theofficialgman** [comment]
this is also concerning... `Ign:3 file:/tmp/pi-apps-local-packages ./ Packages`
the Packages file should have been added here: https://github.com/Botspot/pi-apps/blob/26f5e9a372b83afd107f698a6f66ab6111cec9ab/api#L186
