### ISSUE TITLE
Chromium don't work with netflix, spotify ecc

### ISSUE THREAD

**Issue by chourmoge** [Botspot/pi-apps#1144]
Thanks for sharing this important app
It is a necessary app for those who are not as good as me in computer science.
Unfortunately the chromiun app doesn't allow me to view amazon prime video, netflix, spotify and raiplay.
Is there a solution?
Thank you very much

**Comment by cycool29** [comment]
I got the same issue in Spotify, in Raspbian bullseye.

![image](https://user-images.githubusercontent.com/88134003/141303122-e9eca126-5074-4b30-87c7-01b7c2c9245a.png)

**Comment by Itai-Nelken** [comment]
DRM broke recently, rpf said it will be fixed in bullseye.

**Comment by chourmoge** [comment]
thank you for notice

**Comment by PGSCOM** [comment]
You try to install Chromium widevine? You can install it in pi apps

**Comment by chourmoge** [comment]
> You try to install Chromium widevine? You can install it in pi apps

Yes, i did, but do not work for DRM's problems.

**Comment by chourmoge** [comment]
hello, with installation of Raspberry Pi OS (Legacy) and subsequent installation of pi-apps, and consequent installation of Chromium widevine I get error: File.
invalid desktop entry: "/home/pi/.local/share/applications/widevine-chromium.desktop". There is a solution, the goal is to be able to take advantage of Netflix, Amazon video, Raiplay.
Thanks in advance for any solutions

**Comment by Itai-Nelken** [comment]
Can you send the output of
```shell
cat /home/pi/.local/share/applications/widevine-chromium.desktop
```
please?

**Comment by chourmoge** [comment]
hello and thanks in advance for your interest.
The following output is required.
Greetings

`pi@raspberrypi:~ $ cat /home/pi/.local/share/applications/widevine-chromium.desktop
[Desktop Entry]
Version=1.0
Name=Chromium Widevine
GenericName=Web Browser
Comment=The last several versions of RPi Chromium already use the Chromebook user-agent, so this menu button isn't necessary. But the icon looks too awesome to get rid of! And if you're using a pre-v84 Chromium version, this menu button may still be necessary.
Exec=chromium-browser %U --user-agent="Mozilla/5.0 (X11; CrOS armv7l 12371.89.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36" %U
Terminal=false
X-MultipleArgs=false
Type=Application
Icon=/home/pi/pi-apps/apps/Chromium Widevine/icon-64.png
Categories=Network;WebBrowser;
StartupNotify=true
pi@raspberrypi:~ $ 
`

**Comment by cycool29** [comment]
Try to reinstalling it.

**Comment by chourmoge** [comment]
I uninstalled, rebooted, installed from Pi-apps again Chromium widevine, reboot, but when opening Chromium widevine a window opens with the following content:
Invalid desktop entry file: "/home/pi/.local/share/applications/widevine-chromium.desktop". The command suggested by Itai-Nelken gives the following result:

`pi@raspberrypi:~ $ cat /home/pi/.local/share/applications/widevine-chromium.desktop
[Desktop Entry]
Version=1.0
Name=Chromium Widevine
GenericName=Web Browser
Comment=The last several versions of RPi Chromium already use the Chromebook user-agent, so this menu button isn't necessary. But the icon looks too awesome to get rid of! And if you're using a pre-v84 Chromium version, this menu button may still be necessary.
Exec=chromium-browser %U --user-agent="Mozilla/5.0 (X11; CrOS armv7l 12371.89.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36" %U
Terminal=false
X-MultipleArgs=false
Type=Application
Icon=/home/pi/pi-apps/apps/Chromium Widevine/icon-64.png
Categories=Network;WebBrowser;
StartupNotify=true
pi@raspberrypi:~ $ `
thanks for your interest

**Comment by Itai-Nelken** [comment]
try running `chromium-browser %U --user-agent="Mozilla/5.0 (X11; CrOS armv7l 12371.89.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36"`

**Comment by chourmoge** [comment]
> try running `chromium-browser %U --user-agent="Mozilla/5.0 (X11; CrOS armv7l 12371.89.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36"`

Here is the result

pi@raspberrypi:~ $ chromium-browser %U --user-agent="Mozilla/5.0 (X11; CrOS armv7l 12371.89.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36"
bash: chromium-browser: comando non trovato
pi@raspberrypi:~ $

**Comment by cycool29** [comment]
You don't have chromium installed. Run `sudo apt install chromium-browser` and try again.

**Comment by chourmoge** [comment]
@cycool29 
But I use chromium browser and it works, and it is present in the menu. The Chromium widevine icon is also present, but upon opening it presents the window that I indicated in the thread above. So it is possible that although I will try to reinstall the browser shortly as you indicated, the problem is something else. Thanks for the directions

**Comment by cycool29** [comment]
What is the output of `dpkg -s chromium-browser | grep Status`

**Comment by chourmoge** [comment]
here is the result
pi@raspberrypi:~ $ dpkg -s chromium-browser | grep Status
dpkg-query: il pacchetto "chromium-browser" non è installato e non è disponibile alcuna informazione
Usare "dpkg --info" (= "dpkg-deb --info") per esaminare gli archivi.

pi@raspberrypi:~ $

**Comment by Botspot** [comment]
@chourmoge Perhaps you have `chromium` installed instead of `chromium-browser`?

**Comment by chourmoge** [comment]
Hi, I tried to install via: sudo apt install chromium-browser and spotify free, Netflix and Raiplay seem to work, but Amazon video doesn't.
Sorry, but Chromium browser is not installed standard on the S.o. Raspberry? However, I am grateful to you for your availability.
Below is the result of the installation

`pi@raspberrypi:~ $ sudo apt install chromium-browser
Lettura elenco dei pacchetti... Fatto
Generazione albero delle dipendenze       
Lettura informazioni sullo stato... Fatto
I seguenti pacchetti sono stati installati automaticamente e non sono più richiesti:
  chromium-common chromium-sandbox libjsoncpp1 libminizip1 libre2-5
  libu2f-udev
Usare "sudo apt autoremove" per rimuoverli.
I seguenti pacchetti aggiuntivi saranno inoltre installati:
  chromium-browser-l10n chromium-codecs-ffmpeg-extra
Pacchetti suggeriti:
  webaccounts-chromium-extension unity-chromium-extension adobe-flashplugin
I seguenti pacchetti saranno RIMOSSI:
  chromium
I seguenti pacchetti NUOVI saranno installati:
  chromium-browser chromium-browser-l10n chromium-codecs-ffmpeg-extra
0 aggiornati, 3 installati, 1 da rimuovere e 0 non aggiornati.
È necessario scaricare 124 MB di archivi.
Dopo quest'operazione, verranno occupati 275 MB di spazio su disco.
Continuare? [S/n] s
Scaricamento di:1 http://archive.raspberrypi.org/debian buster/main armhf chromium-codecs-ffmpeg-extra armhf 92.0.4515.98~buster-rpt2 [1.589 kB]
Scaricamento di:2 http://archive.raspberrypi.org/debian buster/main armhf chromium-browser armhf 92.0.4515.98~buster-rpt2 [118 MB]
Scaricamento di:3 http://archive.raspberrypi.org/debian buster/main armhf chromium-browser-l10n all 92.0.4515.98~buster-rpt2 [4.073 kB]
Recuperati 124 MB in 19s (6.586 kB/s)                                          
(Lettura del database... 101810 file e directory attualmente installati.)
Rimozione di chromium (90.0.4430.212-1~deb10u1)...
update-alternatives: viene usato /usr/bin/dillo per fornire /usr/bin/x-www-browser (x-www-browser) in modalità automatica
Selezionato il pacchetto chromium-codecs-ffmpeg-extra non precedentemente selezionato.
(Lettura del database... 101779 file e directory attualmente installati.)
Preparativi per estrarre .../chromium-codecs-ffmpeg-extra_92.0.4515.98~buster-rpt2_armhf.deb...
Estrazione di chromium-codecs-ffmpeg-extra (92.0.4515.98~buster-rpt2)...
Selezionato il pacchetto chromium-browser non precedentemente selezionato.
Preparativi per estrarre .../chromium-browser_92.0.4515.98~buster-rpt2_armhf.deb...
Estrazione di chromium-browser (92.0.4515.98~buster-rpt2)...
Selezionato il pacchetto chromium-browser-l10n non precedentemente selezionato.
Preparativi per estrarre .../chromium-browser-l10n_92.0.4515.98~buster-rpt2_all.deb...
Estrazione di chromium-browser-l10n (92.0.4515.98~buster-rpt2)...
Configurazione di chromium-codecs-ffmpeg-extra (92.0.4515.98~buster-rpt2)...
Configurazione di chromium-browser (92.0.4515.98~buster-rpt2)...
update-alternatives: viene usato /usr/bin/chromium-browser per fornire /usr/bin/x-www-browser (x-www-browser) in modalità automatica
update-alternatives: viene usato /usr/bin/chromium-browser per fornire /usr/bin/gnome-www-browser (gnome-www-browser) in modalità automatica
Configurazione di chromium-browser-l10n (92.0.4515.98~buster-rpt2)...
Elaborazione dei trigger per mime-support (3.62)...
Elaborazione dei trigger per hicolor-icon-theme (0.17-2)...
Elaborazione dei trigger per gnome-menus (3.31.4-3)...
Elaborazione dei trigger per libc-bin (2.28-10+rpt2+rpi1)...
Elaborazione dei trigger per man-db (2.8.5-2)...
Elaborazione dei trigger per desktop-file-utils (0.23-4)...
`
Grazie ancora, manca ancora Amazon video, ma forse si troverà la soluzione

**Comment by cycool29** [comment]
> Sorry, but Chromium browser is not installed standard on the S.o. Raspberry? 

There are two chromium packages in APT - `chromium` is built for Debian and `chromium-browser` is built specifically for Raspbian. `chromium-browser` should be installed by default in all Raspbian releases.

> Hi, I tried to install via: sudo apt install chromium-browser and spotify free, Netflix and Raiplay seem to work, but Amazon video doesn't.

Are there any error messages? (Sorry, I am not an Amazon Video user and I don't know how it will look like.)
I just search for a 'test video', and I found [this](https://www.amazon.com/vdp/cad21520a9f649499e558fe848872488) it played smoothly for me.

Can you try to play [this video](https://www.amazon.com/vdp/cad21520a9f649499e558fe848872488) and send a screenshot here if there are any error messages?

Also, can you go to https://bitmovin.com/demos/drm and send a screenshot? Just want to make sure your widevine is working.

**Comment by chourmoge** [comment]
hi,
below what is required.
I specify that Spotify is opened by Chromium widevine, but the songs stop after 10 seconds, the video test on Amazon works without problems, and that https://bitmovin.com/demos/drm produces what in the following image
![Schermata del 2021-12-31 17-15-56](https://user-images.githubusercontent.com/94105181/147832112-cf475ce6-ee43-422e-ac56-bba997c624bf.png)

Thank you for your interest, and I wish you a happy new year

**Comment by chourmoge** [comment]
@Botspot There is not a solution?

**Comment by chourmoge** [comment]
Good morning everyone. It seems to me that the lack of answers indicates that the problem is complex. I ask for my knowledge if this situation occurs for all those who use Chromium widevine on raspberry pi4 with o.s. Buster legacy. Thanks and greetings

**Comment by cycool29** [comment]
What is the problem now? Does the menu entry works?

**Comment by chourmoge** [comment]
> 

From the menu Chromium widevine open the windows of browser, but do not works the follow sites: amazon music, amazon video, netflix. All problem of permit, i suppose drm that chromium widevine browser  does not manage

**Comment by KolpixTV** [comment]
I also had the same issue here is how i fixed it:

**1. Uninstall Chromium Widevine if you have it installed.**

**Comment by chourmoge** [comment]
hello and thanks for the availability. 
I followed your instructions, more precisely: 
"Uninstall Chromium Widevine if you have it installed. "Unistalled from Pi-apps "sudo apt install chromium-browser" executed, currently installed v. 92.0.4515
 "Install Chromium Widevine" installed by Pi-apps 
"Close all Chrome instances and Open Chromium Widevine (the normal chrome menu entry also works for me)" Done and rebooted. Opening Chromium widevine, netflix, amazon video, amazon music does not work. Youtube seems to work instead.
 I do not understand if it is a widespread problem and in case why Chromium Widevine does not work for me. 
Thanks for any explanation

**Comment by chourmoge** [comment]
sorry, i use raspberry o. s. Legacy buster! I have a hard time understanding what you mean

**Comment by KolpixTV** [comment]
> sorry, i use raspberry o. s. Legacy buster! I have a hard time understanding what you mean

But Debian 11 is bullseye

chromium version:
Version 95.0.4638.78 (Official Build) Built on Raspbian , running on Raspbian 11 (32-bit)
(not the media edition)...

**Comment by chourmoge** [comment]
This is a post of:

- [ ] [https://forums.raspberrypi.com/viewtopic.php?p=1954915&hilit=widevine#p1954915] 
- [ ] : Re: Cannot watch Amazon Prime video on Bullseye (Raspberry Pi4)

Sat Jan 01, 2022 11:29 pm
Prime video, Disney+, PBS, and Netflix work fine on my PI4-8G with bullseye.
(on a wired connection)
note: this was a clean start with Bullseye, NOT an upgraded buster.

chromium version:
Version 95.0.4638.78 (Official Build) Built on Raspbian , running on Raspbian 11 (32-bit)
(not the media edition)...

i do have the widevine library loaded with:
sudo apt install libwidevinecdm0

**Comment by KolpixTV** [comment]
sudo apt install libwidevinecdm0 actually fixed that issue (https://github.com/Botspot/pi-apps/issues/1108) for me. And amazon Music and Videos also works perfectly with this command.

**Comment by chourmoge** [comment]
Good Morning. 
For me works : amazon video, spotify, netflix and Raiplay (italian tv), but don't works amazon music.

**Comment by theofficialgman** [comment]
@Botspot can this issue be closed? I think this is just users misunderstanding that chromium-browser does NOT come with widevineDRM libraries installed by default.

I don't have a pi so can't say, but does the `libwidevinecdm0` package from the archive.raspberrypi.org repo work by default with the latest version of chromium-browser?

**Comment by ryanfortner** [comment]
> I don't have a pi so can't say, but does the `libwidevinecdm0` package from the archive.raspberrypi.org https://archive.raspberrypi.org/debian/pool/main/w/widevine/ (last updated in september) repo work by default with the latest version of chromium-browser?

For me, it works with Spotify drm content on RPiOS bullseye, haven't tested buster.
