### ISSUE TITLE
Arduino install doesn't have enough rights to install

### ISSUE THREAD

**Issue by tom-eilers-nl** [Botspot/pi-apps#1145]
Arduino will not install (bullseye= pi4B) ,because the install rights are not elevated.
My login is default pi-raspberry.

**Comment by Botspot** [comment]
What errors did you see?

**Comment by tom-eilers-nl** [comment]
I am sorry for the version number:
If I install arduino from the arduino cc site it copy’s a arduino-1.8.9 file but installs 1.8.16  the same as Pi=apps does.
Sorry or my mistake.

**Comment by cycool29** [comment]
[This PR](https://github.com/Botspot/pi-apps/pull/1149) should fix `ln: failed to create symbolic link '/usr/local/bin/arduino': Permission denied`.

> Also the Arduino version Pi-apps installs is 1.8.6
The lastest version is 1.8.9

Are you sure? The version I saw it the offcial website is 1.8.**16**, pi-apps is installing that version.

**Comment by tom-eilers-nl** [comment]
I seem to be mad yesterday I downloaded arduino from arduino cc site and extracted it on my pi
It created directory arduino-1.8.9.
That’s why I was thinking it was arduino 1.8.9 version.
Sorry again.
