### ISSUE TITLE
FF Multi Converter

### ISSUE THREAD

**Issue by Crilum** [Botspot/pi-apps#1146]
- Can this app run on RPi? If so, please provide a link to a tutorial if applicable.

Yes.

- Is this app something many GUI users would find useful?

I think so. FF Multi Converter allows users to convert **many** Image, Video/Audio, and Document files to different formats with the 
help of `imagemagick`, `FFmpeg`, and `unoconv`. 

- Is this app installable with `sudo apt install`?

No.

- If you've created a zip file for this app, upload it here.

[FF Multi Converter.zip](https://github.com/Botspot/pi-apps/files/7522881/FF.Multi.Converter.zip)

**Comment by ryanfortner** [comment]
Wow, that's a long credits file... might want to shorten it.

**Comment by Crilum** [comment]
Yeah, I just copied the credits from the website.. I'll just say "Thanks to ilstad and all contributors.". Is that good?

**Comment by ryanfortner** [comment]
> Yeah, I just copied the credits from the website.. I'll just say "Thanks to ilstad and all contributors.". Is that good?

Yeah that should be good.

**Comment by Crilum** [comment]
Ok, here is the new .zip:
[FF Multi Converter.zip](https://github.com/Botspot/pi-apps/files/7529756/FF.Multi.Converter.zip)

**Comment by Crilum** [comment]
Anyone?

**Comment by Crilum** [comment]
Ok, I found an error, which might be in some other apps that I have made/contributed to:

```
cp: cannot create regular file '/home/pi/.local/share/icons/hicolor/64x64/apps/ffmulticonverter.png': No such file or directory
Failed to copy icon to system icons directory!

Failed to install FF Multi Converter!

```

The error is caused by my new install of bullseye, in which there are no apps which have 64x64 icons, so the `~/.local/share/icons/hicolor/64x64` folder does not exist.

Here is the fix:
[FF Multi Converter.zip](https://github.com/Botspot/pi-apps/files/7532859/FF.Multi.Converter.zip)

**Comment by Crilum** [comment]
@Botspot I think this is ready. Anyone have suggestions?

**Comment by Botspot** [comment]
App has been added now. I made some changes to your scripts:

- Added some `|| exit 1` for commands that should exit the script if they fail. (install_packages and git_clone)
- Removed the unnecessary stuff from the top of the scripts (the code to set the DIRECTORY variable and create the error function. That's no longer necessary)
- Changed the approach for creating the desktop file (removing an unnecessary usage of the `tee` command)
- If python3 fails to install the app, the errors are displayed. (originally, you simply had sent the output to `/dev/null`, which would leave us without answers if failures occur)App has been added now. I made some changes to your scripts:

- Added some `|| exit 1` for commands that should exit the script if they fail. (install_packages and git_clone)
- Removed the unnecessary stuff from the top of the scripts (the code to set the DIRECTORY variable and create the error function. That's no longer necessary)
- Changed the approach for creating the desktop file (removing an unnecessary usage of the `tee` command)
- If python3 fails to install the app, the errors are displayed. (originally, you simply had sent the output to `/dev/null`, which would leave us without answers if failures occur)

**Comment by Crilum** [comment]
Thanks!

**Comment by Crilum** [comment]
@Botspot Now that we've put that in, I've realised something. This is going to happen every time someone gets an update for FF Multi Converter:
```
Downloading FF-Multi-Converter repository... 
rm: cannot remove 'FF-Multi-Converter/build/scripts-3.9/ffmulticonverter': Permission denied
rm: cannot remove 'FF-Multi-Converter/build/lib/ffmulticonverter/preferences_dlg.py': Permission denied
rm: cannot remove 'FF-Multi-Converter/build/lib/ffmulticonverter/progress.py': Permission denied
rm: cannot remove 'FF-Multi-Converter/build/lib/ffmulticonverter/audiovideotab.py': Permission denied
rm: cannot remove 'FF-Multi-Converter/build/lib/ffmulticonverter/imagetab.py': Permission denied
rm: cannot remove 'FF-Multi-Converter/build/lib/ffmulticonverter/config.py': Permission denied
rm: cannot remove 'FF-Multi-Converter/build/lib/ffmulticonverter/utils.py': Permission denied
rm: cannot remove 'FF-Multi-Converter/build/lib/ffmulticonverter/presets_dlgs.py': Permission denied
rm: cannot remove 'FF-Multi-Converter/build/lib/ffmulticonverter/documenttab.py': Permission denied
rm: cannot remove 'FF-Multi-Converter/build/lib/ffmulticonverter/__init__.py': Permission denied
rm: cannot remove 'FF-Multi-Converter/build/lib/ffmulticonverter/ffmulticonverter.py': Permission denied
rm: cannot remove 'FF-Multi-Converter/build/lib/ffmulticonverter/qrc_resources.py': Permission denied
rm: cannot remove 'FF-Multi-Converter/build/lib/ffmulticonverter/about_dlg.py': Permission denied
rm: cannot remove 'FF-Multi-Converter/ffmulticonverter/__pycache__/__init__.cpython-39.pyc': Permission denied

Failed to download FF-Multi-Converter repository.
Errors: fatal: destination path 'FF-Multi-Converter' already exists and is not an empty directory.

Failed to install FF Multi Converter!
🔺Need help? Copy the ENTIRE terminal output or take a screenshot.
Please ask on Github: https://github.com/Botspot/pi-apps/issues/new/choose
Or on Discord: https://discord.gg/RXSTvaUvuu

Close this window to exit.
```

So we either need to change the install script to delete `FF-Multi-Converter` before cloning the repo, or you need to change the `git_clone` function to use `sudo` if `rm` fails.

**Comment by Botspot** [comment]
> So we either need to change the install script to delete `FF-Multi-Converter` before cloning the repo, or you need to change the `git_clone` function to use `sudo` if `rm` fails.

An `api` update is in the works to fix this.
