### ISSUE TITLE
Boxy SVG won't install on Ubuntu 20.10

### ISSUE THREAD

**Issue by Itai-Nelken** [Botspot/pi-apps#115]
because chromium-browser isn't installed, i'ts only available as a snap and not installable (or blocked probably) from `apt`

**Comment by Botspot** [comment]
Well you need some form of chromium installed first.

Does Ubuntu come with Chromium out-of-the-box?

**Comment by Itai-Nelken** [comment]
the command to start the chromium snap is `chromium` and not `chromium-browser`, is it possible for the install script to detect if you are on ubuntu and generate the desktop shortcut/launcher differently?

**Comment by Botspot** [comment]
I already tried to add that detection to the script.  
https://github.com/Botspot/pi-apps/blob/master/apps/Boxy%20SVG/install#L16

Please run: `whereis chromium`

**Comment by Itai-Nelken** [comment]
no, but I installed it with `sudo snap install chromium`

**Comment by Itai-Nelken** [comment]
> I already tried to add that detection to the script.
> https://github.com/Botspot/pi-apps/blob/master/apps/Boxy%20SVG/install#L16
> 
> Please run: `whereis chromium`

itai@UbuntuPi4-ultra-4gb:~$ whereis chromium
chromium: /snap/bin/chromium /snap/bin/chromium.chromedriver
itai@UbuntuPi4-ultra-4gb:~$

**Comment by Botspot** [comment]
Now please run:
```
command -v chromium && echo "chromium found"
```

**Comment by Itai-Nelken** [comment]
itai@UbuntuPi4-ultra-4gb:~$ command -v chromium && echo "chromium found"
/snap/bin/chromium
chromium found

**Comment by Botspot** [comment]
Good. I'll change the chromium detection to use `command -v chromium`.

**Comment by Botspot** [comment]
There. Hopefully it will work now as of commit 853e7fe4d14eab1b2bcbcfb5e1c5f0b5958512b9.

**Comment by Itai-Nelken** [comment]
great! it works, but there is no menu  button

**Comment by Botspot** [comment]
Did Boxy SVG launch when you installed it? (Chromium should have launched boxy svg during install)

**Comment by Itai-Nelken** [comment]
yes, it launched

**Comment by Botspot** [comment]
Creating the menu button is Chromium's domain. There's nothing much I can do about it.

Try running this:
```
find ~/.local/share/applications | grep gaoogdonmngmdlbinmiclicjpbjhgomg
```

**Comment by Itai-Nelken** [comment]
it doesn't show anything

itai@UbuntuPi4-ultra-4gb:~$ find ~/.local/share/applications | grep gaoogdonmngmdlbinmiclicjpbjhgomg
itai@UbuntuPi4-ultra-4gb:~$

**Comment by Itai-Nelken** [comment]
but it isn't there
```
itai@UbuntuPi4-ultra-4gb:~$ cd ~/.local/share/applications/
itai@UbuntuPi4-ultra-4gb:~/.local/share/applications$ ls
aiw.desktop                                wine-extension-htm.desktop
menulibre-chromium-media-edition-.desktop  wine-extension-ini.desktop
menulibre-discord1.desktop                 wine-extension-jfif.desktop
menulibre-discord.desktop                  wine-extension-jpe.desktop
menulibre-new-launcher.desktop             wine-extension-msp.desktop
menulibre-speedtest-cli.desktop            wine-extension-pdf.desktop
menulibre-zoom.desktop                     wine-extension-png.desktop
mimeinfo.cache                             wine-extension-rtf.desktop
pi-apps.desktop                            wine-extension-txt.desktop
pi-apps-settings.desktop                   wine-extension-url.desktop
wine-extension-chm.desktop                 wine-extension-vbs.desktop
wine-extension-gif.desktop                 wine-extension-wri.desktop
wine-extension-hlp.desktop                 wine-extension-xml.desktop
itai@UbuntuPi4-ultra-4gb:~/.local/share/applications$ 
```

**Comment by Botspot** [comment]
Well try going to chrome://apps in your browser.

Maybe you can launch boxy svg from there.

**Comment by Itai-Nelken** [comment]
it isn't there

**Comment by Botspot** [comment]
Okay try running this: 
```
chromium --app-id=gaoogdonmngmdlbinmiclicjpbjhgomg
```

**Comment by Botspot** [comment]
Okay I was able to reproduce the issue.

It involved developer mode in chrome://extensions.

**Comment by Itai-Nelken** [comment]
it opens a new chromium window.
```
itai@UbuntuPi4-ultra-4gb:~$ chromium --app-id=gaoogdonmngmdlbinmiclicjpbjhgomg

(chrome:19125): Gtk-WARNING **: 18:29:51.659: Theme parsing error: gtk.css:1566:23: 'font-feature-settings' is not a valid property name

(chrome:19125): Gtk-WARNING **: 18:29:51.695: Theme parsing error: gtk.css:3616:25: 'font-feature-settings' is not a valid property name

(chrome:19125): Gtk-WARNING **: 18:29:51.709: Theme parsing error: gtk.css:4078:23: 'font-feature-settings' is not a valid property name
Gtk-Message: 18:29:52.118: Failed to load module "canberra-gtk-module"
Gtk-Message: 18:29:52.153: Failed to load module "canberra-gtk-module"
Opening in existing browser session.
itai@UbuntuPi4-ultra-4gb:~$ 
```

**Comment by Botspot** [comment]
@Itai-Nelken Could you find where your snap chromium install stores its config?

Is it at `~/.config/chromium`?

**Comment by Itai-Nelken** [comment]
I think it is `~snap/chromium/common/chromium`

![image](https://user-images.githubusercontent.com/70802936/100643184-64630080-3342-11eb-94a9-11206baab36b.png)

**Comment by Itai-Nelken** [comment]
I reinstalled (Boxy SVG) and now it appears in `chrome://apps`

**Comment by Botspot** [comment]
> I reinstalled (Boxy SVG) and now it appears in `chrome://apps`

Did you ever enable Developer Mode in chrome://extensions?

**Comment by Itai-Nelken** [comment]
> PS. You might not want to post a screenshot containing your email address. ;)
yes, I forgot it is there thanks, I removed it

**Comment by Itai-Nelken** [comment]
> Did you ever enable Developer Mode in chrome://extensions?

No, but for some reason after reinstalling it appears there, so I guess it's something to do with Ubuntu becuse I never had this type of bug with rpiOS

**Comment by Botspot** [comment]
Okay could you run `file /snap/chromium/common/chromium/Default/Preferences`?

**Comment by Itai-Nelken** [comment]
when I right click on the app in `chrome://apps` and select create shortcut>on desktop and menu
a shortcut with no icon appears on the desktop, but not in the "menu"

**Comment by Botspot** [comment]
> > Did you ever enable Developer Mode in chrome://extensions?
> 
> No, but for some reason after reinstalling it appears there, so I guess it's something to do with Ubuntu becuse I never had this type of bug with rpiOS

No, this is a bit different, and I am encountering it on RPiOS. Boxy SVG is a local unpackaged app. It's not from the Chrome Web Store. So the process of installing it can be a bit tricky.

**Comment by Botspot** [comment]
> when I right click on the app in `chrome://apps` and select create shortcut>on desktop and menu
> a shortcut with no icon appears on the desktop, but not in the "menu"

Okay that... sounds like an incompatibility between snap and chromium.

**Comment by Botspot** [comment]
Please run `file /snap/chromium/common/chromium/Default/Preferences`.

**Comment by Itai-Nelken** [comment]
```
itai@UbuntuPi4-ultra-4gb:~$ file /snap/chromium/common/chromium/Default/Preferences
/snap/chromium/common/chromium/Default/Preferences: cannot open `/snap/chromium/common/chromium/Default/Preferences' (No such file or directory)
itai@UbuntuPi4-ultra-4gb:~$ 
```

**Comment by Botspot** [comment]
Okay where did you say your chromium preferences were?

Maybe `file ~/snap/chromium/common/chromium/Default/Preferences`?

**Comment by Itai-Nelken** [comment]
```
itai@UbuntuPi4-ultra-4gb:~$ file ~/snap/chromium/common/chromium/Default/Preferences
/home/itai/snap/chromium/common/chromium/Default/Preferences: UTF-8 Unicode text, with very long lines, with no line terminators
itai@UbuntuPi4-ultra-4gb:~$ 
```

that file is there, I checked

**Comment by Botspot** [comment]
Okay I will push an update to boxy svg soon to enable developer mode automatically.

**Comment by Itai-Nelken** [comment]
I uninstalled it, updated pi-apps, and reinstalled but it still doesn't work. the menu shortcut did appear, but it has no icon and opens a new chromium window. 

I found that if go to `chrome://extensions`, turn on developer mode, and click on `load unpacked` then select `~/Boxy-SVG-RPi/boxysvgrpi` it appears in `chrome://apps`

**Comment by Botspot** [comment]
@Itai-Nelken

**Comment by Itai-Nelken** [comment]
No, but it did say that chromium didn't create a menu shortcut.

**Comment by Itai-Nelken** [comment]
I tried installing with the install script without and I got this error:
![Screenshot from 2020-12-01 17-45-07](https://user-images.githubusercontent.com/70802936/100763172-7ce42100-33fd-11eb-8a88-9b46e2fc7c04.png)

**Comment by Botspot** [comment]
I have an idea. Check your discord, @Itai-Nelken.

**Comment by Itai-Nelken** [comment]
it seems the install script doesn't turn on developer settings for me, because when I had them turned on before the installation, the app appeared in `chrome://apps` and `chrome://extensions`.
but the menu shortcyt still has no icon and only opens a new chromium window (not always either)

**Comment by Botspot** [comment]
> it seems the install script doesn't turn on developer settings for me

Yes. I have an idea. Please check your discord.

**Comment by Itai-Nelken** [comment]
sorry, the tab didn't refresh so I didn't see you repiled

**Comment by Itai-Nelken** [comment]
when installing on TwisterOS (1.9.3) the menu button appears, but when you click on it it opens a new chromium window only.

**Comment by Botspot** [comment]
@Itai-Nelken I've completely redone the script a few days ago.

Do your problems still occur on TwisterOS?

**Comment by Itai-Nelken** [comment]
> @Itai-Nelken I've completely redone the script a few days ago.
> 
> Do your problems still occur on TwisterOS?

@Botspot No, boxy SVG works like a charm. 
something to add to the description (in pi-apps) is that it uses a new user (chromium user) profile, so if chromium was closed when running boxy sag, next time you open it you have to switch back to your account.

thanks for all your hard work!

**Comment by Botspot** [comment]
> something to add to the description (in pi-apps) is that it uses a new user (chromium user) profile, so if chromium was closed when running boxy svg, next time you open it you have to switch back to your account.

Interesting. I think there's an alternative which can avoid this annoyance... :)

> thanks for all your hard work!

And you're welcome! Thank you too.

**Comment by Botspot** [comment]
> Interesting. I think there's an alternative which can avoid this annoyance... :)

Nope. Couldn't get it working. :(
