### ISSUE TITLE
filezilla

### ISSUE THREAD

**Issue by PGSCOM** [Botspot/pi-apps#1153]
Can this app run on RPi? If so, please provide a link to a tutorial if applicable.
Yes, it can
Is this app something many GUI users would find useful?
Yes, you can connect to a ftp server
Is this app installable with `sudo apt install`?
Yes, the comand is sudo apt-get install filezilla

**Comment by Crilum** [comment]
@PGSCOM You maight want to take a look at #185.

It says:

>Add up the points and see what you get. Below are some special cases where points don't matter - the app is disqualified:
>- The app is already available on APT.
>- ~~The app requires paying for something.~~ Edit: What was I thinking? MC Java and MC Bedrock are already on here, and KSP is on the waiting list. I think they belong in Pi-Apps, despite costing money. This point is no longer valid.
>- The app is illegal to distribute.

**Comment by Botspot** [comment]
@Crilum is correct - Pi-Apps is solely for software that you *can't* install with a simple `apt-get` command.

This will change in the future though, and the infrastructure is ready-to-go. (it's just waiting for my signal... 😆)

**Comment by PGSCOM** [comment]
> @Crilum is correct - Pi-Apps is solely for software that you _can't_ install with a simple `apt-get` command.
> 
> This will change in the future though, and the infrastructure is ready-to-go. (it's just waiting for my signal... laughing)

👌

**Comment by Crilum** [comment]
So, I actually just tried to install Filezilla, but `sudo apt install filezilla` has the normal package not found error, @PGSCOM are you able to/did you install just like that?

If it isn't in the Raspberry Pi repos, maybe we can make a Pi-Apps script for it.

**Comment by PGSCOM** [comment]
Yes, install it with `sudo apt-get install filezilla`

**Comment by Crilum** [comment]
```
$ sudo apt-get install filezilla
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package filezilla

```

**Comment by PGSCOM** [comment]
Also after all this happened I installed gimp in that way too and there was no problem, pi-apps worked perfectly

**Comment by PGSCOM** [comment]
I don’t think the filezilla installation was the cause of the problem

**Comment by Crilum** [comment]
Me neither, but now I'm curious why I can't install Filezilla.

**Comment by PGSCOM** [comment]
What is the error when you installing it?

**Comment by Crilum** [comment]
Like I said above:
```
$ sudo apt-get install filezilla
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package filezilla
```

**Comment by PGSCOM** [comment]
How many RAM do you have in your rpi4?

**Comment by Crilum** [comment]
4G, but that is not the problem. Could you send the output of `cat /etc/apt/sources.list`?

**Comment by PGSCOM** [comment]
![imagen](https://user-images.githubusercontent.com/69808296/141662745-a640b980-d1cb-4442-8ca1-496c4179e16b.png)

**Comment by Crilum** [comment]
I think I know what my problem is.. You have RPiOS buster, and I have RPiOS Bullseye. I'll look and see if the Bullseye repos have Filezilla.

**Comment by Crilum** [comment]
Does anyone here have/use 64-bit Bullseye? I'm trying to figure out if filezilla is in the default repos in Bullseye 64-bit.

**Comment by PGSCOM** [comment]
It exsist `sudo apt-get install filezilla-common`?

**Comment by PGSCOM** [comment]
Also I found this: [https://packages.debian.org/source/bullseye/filezilla](https://packages.debian.org/source/bullseye/filezilla)

**Comment by PGSCOM** [comment]
Another option would be to install Filezilla with Wine.

**Comment by PGSCOM** [comment]
> Does anyone here have/use 64-bit Bullseye? I'm trying to figure out if filezilla is in the default repos in Bullseye 64-bit. 

I may try to make a virtual machine on my computer and try to install it.

**Comment by Crilum** [comment]
> It exsist `sudo apt-get install filezilla-common`?

No, apperently not:
```
$ sudo apt-get install filezilla-common
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package filezilla-common
```



> Also I found this: https://packages.debian.org/source/bullseye/filezilla

Yes, Debian has it in their repos, as well as the Raspberry Pi repos, but, it is not available for RPiOS Bullseye 32-bit. The 64-bit Buster version has the debian repos available automatically, so I was wondering whether 64-bit bullseye had it.



> > Does anyone here have/use 64-bit Bullseye? I'm trying to figure out if filezilla is in the default repos in Bullseye 64-bit.
> 
> I may try to make a virtual machine on my computer and try to install it.

If you do, I recommend using vdesktop, which is available via the `boot` button in Pi Power Tools, which is available though Pi-Apps :smile:. If you do use vdesktop, you'll have to add `arm-64bit=1` in `config.txt` and reboot if you are using a 32-bit host.. 
If you already know all this, sorry! :laughing:

**Comment by PGSCOM** [comment]
Okay, I’ll do it tomorrow. My time zone is Spain, Madrid.

**Comment by PGSCOM** [comment]
@Crilum Have you tried installing FileZilla with wine?

**Comment by Botspot** [comment]
Weird. It's missing on my Bullseye system too.

**Comment by Botspot** [comment]
I figured it out: turns out that our `install_packages` function had a bug: if it was last used to install a local package for an app, it will ignore the repositories located in `/etc/apt/sources.list`. This bug triggered many error reports and is what made the `filezilla` package appear to be missing.

After running `sudo apt update`, the `filezilla` package should be installable. BTW this bug in `install_packages` has been [fixed](https://github.com/Botspot/pi-apps/commit/12f479cd7fb2652603f2ad791421e4697a59f9b1).

**Comment by Botspot** [comment]
> @Crilum is correct - Pi-Apps is solely for software that you _can't_ install with a simple `apt-get` command.
> 
> This will change in the future though, and the infrastructure is ready-to-go. (it's just waiting for my signal... 😆)

I've [rolled out](https://github.com/Botspot/pi-apps/commit/2ef8be885c463de17d13dfc8fa5033eb3d83526e) package-app support and have [added](https://github.com/Botspot/pi-apps/commit/258b6d2515701776e08ce0b20b7de362989f01a4) Filezilla now.
