### ISSUE TITLE
doesnt instal

### ISSUE THREAD

**Issue by velesbh** [Botspot/pi-apps#1154]
┏━━━┓
┏━━┻━━━┻━━┓
┃  ⬛⬛⬛ ┃  ▕ᑐ • ▁  ʌ
┃  ⬛⬛⬛ ┃  ▕  │   ╱‾╲▕ᑐ ▕ᑐ Ｓ
┃  ⬛⬛⬛ ┃            ▕  ▕
╰━━━━━━━━━╯

🔺 WARNING: YOUR SYSTEM IS UNSUPPORTED:
Your system drive has less than 500MB of free space. Watch out for "disk full" errors.
The ability to send error reports has been disabled.
Waiting 10 seconds... (To cancel, press Ctrl+C or close this terminal)
Installing Cura...

Downloading Cura-mb-master-armhf-20210908.AppImage to /home/pi/Cura.AppImage... 
Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
8d23aa|OK  |   1.9MiB/s|/home/pi/Cura.AppImage

Status Legend:
(OK):download completed.
Done
Making executable: /home/pi/Cura.AppImage
Downloading stl-thumb_0.4.0_armhf.deb... 
Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
e75333|OK  |   2.7MiB/s|/home/pi/stl-thumb_0.4.0_armhf.deb

Status Legend:
(OK):download completed.
Done
Running pkg-install...
Running sudo apt update...

Hit:2 http://repository.spotify.com stable InRelease
Hit:5 https://itai-nelken.github.io/weekly-box86-debs/debian  InRelease
Hit:7 https://adoptopenjdk.jfrog.io/adoptopenjdk/deb buster InRelease
Ign:11 http://ports.ubuntu.com/ubuntu-ports bionic-updates/main i386 Packages
Ign:11 http://ports.ubuntu.com/ubuntu-ports bionic-updates/main i386 Packages
Ign:11 http://ports.ubuntu.com/ubuntu-ports bionic-updates/main i386 Packages
Ign:11 http://ports.ubuntu.com/ubuntu-ports bionic-updates/main i386 Packages
Ign:11 http://ports.ubuntu.com/ubuntu-ports bionic-updates/main i386 Packages
Err:11 http://ports.ubuntu.com/ubuntu-ports bionic-updates/main i386 Packages
  404  Not Found [IP: 91.189.88.152 80]
E: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/bionic-updates/main/binary-i386/Packages  404  Not Found [IP: 91.189.88.152 80]
E: Some index files failed to download. They have been ignored, or old ones used instead.
pkg-install failed to run sudo apt update!
APT reported these errors:
E: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/bionic-updates/main/binary-i386/Packages  404  Not Found [IP: 91.189.88.152 80]
E: Some index files failed to download. They have been ignored, or old ones used instead.

▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼
APT reported an unresolvable repository.

Please check your Internet connection and try again.
▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲

Failed to install Cura!
🔺Need help? Copy the ENTIRE terminal output or take a screenshot.
Please ask on Github: https://github.com/Botspot/pi-apps/issues/new/choose
Or on Discord: https://discord.gg/RXSTvaUvuu

Close this window to exit.

**Comment by Botspot** [comment]
This problem was not caused by Pi-Apps. It appears you've added an Ubuntu repository to your system.

**Comment by Botspot** [comment]
Removing the repository should solve the problem.
