### ISSUE TITLE
Remove Falkon

### ISSUE THREAD

**Issue by theofficialgman** [Botspot/pi-apps#1155]
falkon is already available in the debian repos for buster, bullseye, etc

the current version of this script will break on debian bullseye and it dangerous (as it tries to manually download out of date packages from buster)
this script should be removed or changed into a simple

`install_packages falkon`

**Comment by Botspot** [comment]
```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package falkon
```

**Comment by theofficialgman** [comment]
https://packages.debian.org/bullseye/falkon
what debian repos do you have in bullsye (like your sources lists)

**Comment by Botspot** [comment]
```
Hit:1 https://itai-nelken.github.io/weekly-box86-debs/debian  InRelease
Hit:2 http://archive.raspberrypi.org/debian bullseye InRelease                                                                                                                                                                                                    
Hit:4 http://raspbian.raspberrypi.org/raspbian bullseye InRelease                  
```

**Comment by theofficialgman** [comment]
oh dear... is that the official bullseye image?
the debian repo is entirely missing

**Comment by Botspot** [comment]
> oh dear... is that the official bullseye image?

Yes it is.
Maybe you were thinking of the 64-bit PiOS which includes a debian repository?

**Comment by theofficialgman** [comment]
I wasn't aware that 32bit piOS was missing the debian repos....

how the crap do you install much of anything with those missing (well I guess you don't as shown here)

**Comment by Botspot** [comment]
> how the crap do you install much of anything with those missing

I guess that's where Pi-Apps comes in! 🤷‍♂️

**Comment by theofficialgman** [comment]
hmm... well this makes my job a lot harder....
raspbian and archive.raspberrypi.org don't have search engines like the great debian and ubuntu ones

what are the repos (the sources list) included in rpiOS 64bit beta?

**Comment by Botspot** [comment]
> what are the repos (the sources list) included in rpiOS 64bit beta?

I don't know - I don't use RPiOS 64-bit. Maybe you can ask someone on discord who does use it?

**Comment by theofficialgman** [comment]
well regardless this issue needs to be re-opened
the script has to be changed for bullseye
and the dependencies should be directly downloaded from raspbian, I checked, they are there

**Comment by Crilum** [comment]
If you still want the 64-bit `sources.list`:

```
deb http://deb.debian.org/debian buster main contrib non-free
deb http://deb.debian.org/debian-security/ buster/updates main contrib non-free
deb http://deb.debian.org/debian buster-updates main contrib non-free
# Uncomment deb-src lines below then 'apt-get update' to enable 'apt-get source'
# deb-src http://deb.debian.org/debian buster main contrib non-free
# deb-src http://deb.debian.org/debian-security/ buster/updates main contrib non-free
# deb-src http://deb.debian.org/debian buster-updates main contrib non-free
```

**Comment by theofficialgman** [comment]
oh I got it from a user in the discord. same as what you posted though, so thanks for confirming!
