### ISSUE TITLE
Gimp in pi apps

### ISSUE THREAD

**Issue by PGSCOM** [Botspot/pi-apps#1156]
Is this app something many GUI users would find useful?
It´s an alternative for Adobe photoshop

If you've created a zip file for this app, upload it here.
https://www.gimp.org/downloads/

It can install it with [Flatpak](https://flatpak.org/)

**Comment by PGSCOM** [comment]
I think it´s correct #185

**Comment by Botspot** [comment]
Can't gimp be installed with `apt`?
```
sudo apt install gimp
```

**Comment by PGSCOM** [comment]
I did not know that it could be installed with sudo. Thanks!

**Comment by Botspot** [comment]
> I did not know that it could be installed with sudo. Thanks!

Pro tip: You can search for apt-installable applications using the `pi-packages` program.

**Comment by Botspot** [comment]
Pi-Apps now supports package-apps and gimp has been added.
See: https://github.com/Botspot/pi-apps/issues/1229
