### ISSUE TITLE
Pi-apps not responding

### ISSUE THREAD

**Issue by PGSCOM** [Botspot/pi-apps#1158]
Hi, when i run pi-apps it show the logo but it doesn´t open. But when i go to the install folder and i run the update program, it update normaly. I reinstall it but it doesn´t work.

Any solution?

https://user-images.githubusercontent.com/69808296/141656397-18d3d6b1-d983-4a74-8e09-a6c9ab2c401e.mov

**Comment by Botspot** [comment]
Run this command and post the output:
```bash
~/pi-apps/gui
```

**Comment by PGSCOM** [comment]
┏━━━┓
┏━━┻━━━┻━━┓
┃  ⬛⬛⬛ ┃  ▕ᑐ • ▁  ʌ
┃  ⬛⬛⬛ ┃  ▕  │   ╱‾╲▕ᑐ ▕ᑐ Ｓ
┃  ⬛⬛⬛ ┃            ▕  ▕
╰━━━━━━━━━╯

App: 
Action: main-window
Prevaction: 
Unrecognized app list style 'Always'!

**Comment by Botspot** [comment]
> Unrecognized app list style 'Always'!

Go to Pi-Apps settings and change the app list style to 'yad-default'.

**Comment by PGSCOM** [comment]
It has worked. Thanks a lot! It is rare that all the boxes were blank...

**Comment by Itai-Nelken** [comment]
all the options shouldn't be blank, I don;t know why that happened.

**Comment by Crilum** [comment]
@PGSCOM Did Pi-Apps do that on a brand new install? (of Pi-Apps)

**Comment by PGSCOM** [comment]
No, before I didn’t start so I decided to reinstall it, but I don’t know if the same thing happened before reinstallation.

**Comment by Crilum** [comment]
But after installing it happened, correct?

**Comment by PGSCOM** [comment]
Yes, but it may not be because the configuration is empty.

**Comment by Crilum** [comment]
Do you have any idea other than that?

**Comment by PGSCOM** [comment]
But I really don’t know how that could have happened, it may be because of an application I have installed. I recently installed Filezilla

**Comment by Crilum** [comment]
I'll try it to see.. But I really don't think that would do that.
