### ISSUE TITLE
Thomas' Multiplayer Arena

### ISSUE THREAD

**Issue by MegaTKC** [Botspot/pi-apps#1160]
Can this app run on RPi? If so, please provide a link to a tutorial if applicable.
There are no tutorials on how to install this game, this is just a browser game that I turned into an app.
Is this app something many GUI users would find useful?
I would say that this app is not an essential to pi users. This is just a game.
Is this app installable with `sudo apt install`?
No.
If you've created a zip file for this app, upload it here.
[Multiplayer-Arena.zip](https://github.com/Botspot/pi-apps/files/7532974/Multiplayer-Arena.zip)

EDIT: This application code was based on WebCord.

**Comment by Botspot** [comment]
The zip file you sent me is not in proper Pi-Apps format. I have no installation script, no description, no `icon-24.png` or `icon-64.png`, and it's missing the `website` file.

Please read [the app creation wiki](https://github.com/Botspot/pi-apps/wiki/Creating-an-app).
