### ISSUE TITLE
Blockbench install Error

### ISSUE THREAD

**Issue by KolpixTV** [Botspot/pi-apps#1165]
I just tried to install Blockbench. It didn't work. I checked the Log and the Problem was that libappindicator-3-1 does not exist for the new Raspberry Pi OS with Bullseye. The fix was that i had to add buster to my sources.list and installed it with the .deb file from the Debian Package Site. Then i installed it again and it worked fine

**Comment by cycool29** [comment]
`libappindicator-3-1` is deprecated in bullseye. Blockbench still launched well without it.

@ryanfortner I've updated the debs to 4.0.4 and removed `libappindicator-3-1` in dependency list. 

armhf: 
arm64: https://transfer.sh/UtwmNp/blockbench_4.0.4_arm64.deb
