### ISSUE TITLE
Failed to install OBS Studio.

### ISSUE THREAD

**Issue by Rak1ta** [Botspot/pi-apps#1169]
Installation error (Debian 10).
file > [install-fail-OBS Studio.log](https://github.com/Botspot/pi-apps/files/7540598/install-fail-OBS.Studio.log)

**Comment by cycool29** [comment]
That should be fixed in e1c08ee3fbe586b0421cd55f76d4265f4025685b.

Please update your pi-apps.

**Comment by Rak1ta** [comment]
Fixed!
