### ISSUE TITLE
[PI Apps] Installing conky failed.

### ISSUE THREAD

**Issue by pasman1** [Botspot/pi-apps#117]
When one selects installing conky , only config is installed.

Raspos 32bit, kernel 5.10rc3

**Comment by Botspot** [comment]
You can view the whole conky install script [here](https://github.com/Botspot/pi-apps/blob/master/apps/Conky/install).

**Comment by pasman1** [comment]
Looks like
`sudo install conky -y`
fix the issue. Maybe add it ?

**Comment by Botspot** [comment]
`sudo install`?

**Comment by Botspot** [comment]
@pasman1 What locale is your system using?

[This line](https://github.com/Botspot/pi-apps/blob/master/apps/Conky/install#L17) is supposed to install conky, but I've seen reports that it doesn't work properly on non-english locales.

**Comment by pasman1** [comment]
Hi.

I found a bug. In file pkg-install(80) , 
parameter `--dry-run` blocks installing conky.

**Comment by Botspot** [comment]
Thank you for your debugging effort, but that --dry-run is supposed to be there.

Basically, the script has to determine the list of packages to install.

- It tells apt to do a dry run.
- Then the script parses apt's output, to determine which packages are going to be installed.
- If that list-of-packages-that-are-going-to-be-installed [is not empty](https://github.com/Botspot/pi-apps/blob/master/pkg-install#L89), then the script actually [tells apt to install the packages](https://github.com/Botspot/pi-apps/blob/master/pkg-install#L97).

So, if the script fails to parse your apt's output, then it won't actually run the `apt install` command.

**Comment by pasman1** [comment]
Yes, I have locale pl_PL an parsing it probably fails. 
I check differences.

**Comment by Botspot** [comment]
Try this:
```
sudo apt purge -y conky
sudo LANG=C LC_ALL=C apt-get install --no-install-recommends --dry-run conky
```
(report back the full output of the second command please)

**Comment by pasman1** [comment]
Looks better:

> $ sudo LANG=C LC_ALL=C apt-get install --no-install-recommends --dry-run conky
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  conky-std libncurses5
Suggested packages:
  apcupsd moc mpd
The following NEW packages will be installed:
  conky conky-std libncurses5
0 upgraded, 3 newly installed, 0 to remove and 1 not upgraded.
Inst libncurses5 (6.1+20181013-2+deb10u2 Raspbian:stable [armhf])
Inst conky-std (1.10.8-1 Raspbian:stable [armhf])
Inst conky (1.10.8-1 Raspbian:stable [all])
Conf libncurses5 (6.1+20181013-2+deb10u2 Raspbian:stable [armhf])
Conf conky-std (1.10.8-1 Raspbian:stable [armhf])
Conf conky (1.10.8-1 Raspbian:stable [all])

**Comment by Botspot** [comment]
Now let's see if my script could **parse** that output:
```
sudo apt purge -y conky
sudo LANG=C LC_ALL=C apt-get install --no-install-recommends --dry-run conky | sed -n '/The following packages/,/to remove/p' | sed -e '2,$!d' -e '$d' | tr -d '*' | tr '\n' ' ' | sed 's/The following.*//'
```

**Comment by pasman1** [comment]
Result is empty.

**Comment by Botspot** [comment]
Let's try removing the --dry-run then.
```
sudo LANG=C LC_ALL=C apt-get install --no-install-recommends --dry-run conky | sed -n '/The following packages/,/to remove/p' | sed -e '2,$!d' -e '$d' | tr -d '*' | tr '\n' ' ' | sed 's/The following.*//'
```
And also try:
```
sudo apt purge -y conky
sudo LANG=C LC_ALL=C apt-get install --no-install-recommends --dry-run conky | sed -n '/The following/,/to remove/p' | sed -e '2,$!d' -e '$d' | tr -d '*' | tr '\n' ' ' | sed 's/The following.*//'
```

**Comment by pasman1** [comment]
Last method works:

>$ sudo LANG=C LC_ALL=C apt-get install --no-install-recommends --dry-run conky | sed -n '/The following/,/to remove/p' | sed -e '2,$!d' -e '$d' | tr -d '*' | tr '\n' ' ' | sed 's/The following.*//'
  conky
$

**Comment by Botspot** [comment]
> Last method partially works:
> 
> > $ sudo LANG=C LC_ALL=C apt-get install --no-install-recommends --dry-run conky | sed -n '/The following/,/to remove/p' | sed -e '2,$!d' -e '$d' | tr -d '_' | tr '\n' ' ' | sed 's/The following._//'
> > conky
> > $

No, that's not "partially", that worked perfectly!

**Comment by pasman1** [comment]
Yes, this works

**Comment by Botspot** [comment]
I'll update `pkg-install` soon.

**Comment by Botspot** [comment]
One more thing. Try this:
```
sudo apt purge -y conky-std conky
sudo LANG=C LC_ALL=C apt-get install --no-install-recommends conky | sed -n '/The following NEW packages/,/to remove/p' | sed -e '2,$!d' -e '$d' | tr -d '*' | tr '\n' ' ' | sed 's/The following.*//'
```

**Comment by pasman1** [comment]
Your patch works, after update  conky installs.

**Comment by Botspot** [comment]
Not what I meant.  
I was wondering if the second command would report back the packages successfully.
```
sudo apt purge -y conky-std conky
sudo LANG=C LC_ALL=C apt-get install --no-install-recommends --dry-run conky | sed -n '/The following NEW packages/,/to remove/p' | sed -e '2,$!d' -e '$d' | tr -d '*' | tr '\n' ' ' | sed 's/The following.*//'
```

**Comment by pasman1** [comment]
This version works too.
>$ sudo LANG=C LC_ALL=C apt-get install --no-install-recommends --dry-run conky | sed -n '/The following NEW packages/,/to remove/p' | sed -e '2,$!d' -e '$d' | tr -d '*' | tr '\n' ' ' | sed 's/The following.*//'
  conky conky-std

**Comment by Botspot** [comment]
Well that's already what pkg-install did. So we're back to not knowing what happened. :(

**Comment by Botspot** [comment]
@pasman1 I have an idea. Perhaps I would understand the error if I could get the full output from the `pkg-install` script on your system.

Please run:
```
sudo apt purge conky conky-std
~/pi-apps/pkg-install "conky" ~/pi-apps/apps/Conky
```
Please send me the full output of the `pkg-install` line.

**Comment by Botspot** [comment]
@pasman1 Have you seen this yet?

**Comment by Botspot** [comment]
@pasman1 Unfortunately I've had to close this issue due to your inactivity. :(

Reply back and I can re-open it.
