### ISSUE TITLE
Add an optional reload button

### ISSUE THREAD

**Issue by Crilum** [Botspot/pi-apps#1170]
I'm working on something, and I have to check if an app shows as installed.
I'm already in `Installed`, so I have to go `Home`, wait for it to load, click on `Installed` again, wait for it to load, and then I can see if the app in question is installed.
I think it would be very useful to add a reload button in the Pi-Apps GUI, so you don't have to go through the process described above. It could also have a button or switch/dropdown selection that could turn it on/off.

Any input is welcomed.

**Comment by Botspot** [comment]
Adding a fifth button to the Pi-Apps GUI would widen the window even more. :(
![2021-11-15-141026_1920x1080_scrot](https://user-images.githubusercontent.com/54716352/141847199-048e78e8-48d5-48ee-9723-f07e1a20be37.png)

**Comment by Botspot** [comment]
HOWEVER, you can run this command to forcibly re-preload the app-list:
```
~/pi-apps/api refresh_app_list
```

**Comment by Crilum** [comment]
I don't know how hard it would be (also maybe not user friendly...), but you could try making a drag-down type of thing, like Google/Android stuff?
Again, it could be off by default.

**Comment by Botspot** [comment]
> I don't know how hard it would be (also maybe not user friendly...), but you could try making a drag-down type of thing, like Google/Android stuff? Again, it could be off by default.

This may be possible if Pi-Apps was using a more flexible GTK library. Currently it uses the `yad` dialog system. No such option exists.

If the GUI was written in C, we could add a button anywhere. But it's not in C, and we don't have the resources to write it in C.

**Comment by Crilum** [comment]
:bulb: 
:man: 
You could make a Developer Mode, which might not be beginner friendly, but is more functional for advanced users (App Devs, Pi-Apps Devs..).

**Comment by Botspot** [comment]
> * Could a sidebar be added, potentially? Maybe only for the (proposed) dev mode..
> * Or another row, instead of making it longer, like Pi-Apps Settings.

Yad doesn't have those options. In list mode, all you can add is a text label (message of the day), a window icon, and buttons.

**Comment by Crilum** [comment]
Again, maybe make an optional Developer Mode, which would make the GUI uglier, but more functional.

**Comment by theofficialgman** [comment]
closed by: https://github.com/Botspot/pi-apps/pull/1580

reload will not be necessary with the new GUI since it refresh's automatically
