### ISSUE TITLE
CommanderPi: permission denied removing files in `~/CommanderPi/src/__pycache__/`

### ISSUE THREAD

**Issue by Itai-Nelken** [Botspot/pi-apps#1176]
```
rm: cannot remove '/home/pi/CommanderPi/src/__pycache__/bootloader.cpython-39.pyc': Permission denied
rm: cannot remove '/home/pi/CommanderPi/src/__pycache__/resources.cpython-39.pyc': Permission denied
rm: cannot remove '/home/pi/CommanderPi/src/__pycache__/theme.cpython-39.pyc': Permission denied
rm: cannot remove '/home/pi/CommanderPi/src/__pycache__/update.cpython-39.pyc': Permission denied
rm: cannot remove '/home/pi/CommanderPi/src/__pycache__/gui.cpython-39.pyc': Permission denied
```
The fix is easy, but I don't have time to do it.

**Comment by Crilum** [comment]
Yeah, `git_clone` just needs to use `sudo` on the `rm` part.

**Comment by Botspot** [comment]
I don't understand - the `git_clone` command now uses sudo to remove the destination folder.

**Comment by Crilum** [comment]
I think the errors are from the first part:
```
--> rm -rf $repo_name <-- || sudo rm -rf $repo_name
```

The first one doesn't have enough permissions, so it outputs errors. It runs the second one (because the first one failed), and that one works.
I think this could be fixed by changing the line to this:

```
rm -rf $repo_name &>/dev/null || sudo rm -rf $repo_name
```

**Comment by Crilum** [comment]
I guess you could have just looked at @cycool29's PR.. :man_shrugging:
