### ISSUE TITLE
`date` not receiving an argument for `-d` option

### ISSUE THREAD

**Issue by Itai-Nelken** [Botspot/pi-apps#1177]
```
date: option requires an argument -- 'd'
Try 'date --help' for more information.
Falling back to local system time
```

**Comment by theofficialgman** [comment]
for reference, thats exactly why I implemented the fallback
if for whatever reason that git upstream curl/grep/date command did not work
its not a fatal error

```
upstream_git_date="$(curl https://api.github.com/repos/Botspot/pi-apps/commits/master 2>&1 | grep '"date":' | tail -n 1 | sed 's/"date"://g' | xargs date +%s -d)"
if ! [[ "$upstream_git_date" =~ ^[0-9]+$ ]]; then
  # if upstream master git date can't be found, then fallback to local time server
  # the above checks for an empty variable or a variable containing non-numerical values
  echo "Falling back to local system time" 1>&2
  upstream_git_date="$(date +%s)"
fi
```
can you tell me what exactly fails in this command for you?
```
curl https://api.github.com/repos/Botspot/pi-apps/commits/master 2>&1 | grep '"date":' | tail -n 1 | sed 's/"date"://g' | xargs date +%s -d
```

**Comment by cycool29** [comment]
> can you tell me what exactly fails in this command for you?
> 
> ```
> curl https://api.github.com/repos/Botspot/pi-apps/commits/master 2>&1 | grep '"date":' | tail -n 1 | sed 's/"date"://g' | xargs date +%s -d
> ```

`1637112679`

**Comment by theofficialgman** [comment]
@cycool29 not you... it works fine for you (as it does for me)
I want to know why @Itai-Nelken is reporting this and what is failing for them

**Comment by cycool29** [comment]
> @cycool29 not you... it works fine for you (as it does for me) I want to know why @Itai-Nelken is reporting this and what is failing for them

That occurs on my side too when updating and installing some apps.

**Comment by theofficialgman** [comment]
@cycool29 just to confirm, you have seen this warning as well?:
```
date: option requires an argument -- 'd'
Try 'date --help' for more information.
Falling back to local system time
```
I don't see how that is possible because you just verified to me that its working...

**Comment by theofficialgman** [comment]
the only way for that function to error is if `https://api.github.com/repos/Botspot/pi-apps/commits/master` the contents here miss the "date" value or the curl fails
in which case the fallback is supposed to take over

**Comment by theofficialgman** [comment]
this isn't causing the update to fail is it?

**Comment by theofficialgman** [comment]
the only thing I can gather is that your internet temporarily died/had trouble connecting to `api.github.com`
in which case the fallback takes over...

**Comment by cycool29** [comment]
> @cycool29 just to confirm, you have seen this warning as well?:
> 
> ```
> date: option requires an argument -- 'd'
> Try 'date --help' for more information.
> Falling back to local system time
> ```

Yes.

> the only way for that function to error is if https://api.github.com/repos/Botspot/pi-apps/commits/master the contents here miss the "date" value or the curl fails
in which case the fallback is supposed to take over

Maybe we make a check like this:
```bash
upstream_api=$(curl https://api.github.com/repos/Botspot/pi-apps/commits/master 2>&1)

if [ "$?" == 0 ] && (echo "$upstream_api" | grep -q date); then #if curl returns 0 and `date` is found in upstream_api
  upstream_git_date="$(echo "$upstream_api" | grep '"date":' | tail -n 1 | sed 's/"date"://g' | xargs date +%s -d)"
else
  echo "Falling back to local system time" 1>&2
  upstream_git_date="$(date +%s)"
fi
```

> this isn't causing the update to fail is it? Because from what I can tell, it definitely should not cause that

Nope, it shows `Falling back to local system time` and continues the update.

**Comment by theofficialgman** [comment]
no there is no reason for that
the fallback still needs to happen if you can't download from this address `https://api.github.com/repos/Botspot/pi-apps/commits/master`
and in my opinion, that is a bigger problem with your internet that should be solved

the fallback works fine... the error in the log is good to see, I think it should stay

**Comment by theofficialgman** [comment]
oh hold on.... I see a potential problem
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current

                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0{
```
I forgot to turn off curl logging
maybe an early "date" gets printed somehow or something

**Comment by theofficialgman** [comment]
> Maybe we make a check like this:

if you really want to hide the error... just redirect it to /dev/null `xargs date +%s -d 2>/dev/null`

**Comment by Itai-Nelken** [comment]
This isn't happening anymore, and I haven't been able to reproduce it. I guess it was a script being called while being updated maybe?

**Comment by Botspot** [comment]
> This isn't happening anymore, and I haven't been able to reproduce it. I guess it was a script being called while being updated maybe?

I routinely got that error whenever I ran the `pi-apps` command. This was with the "Pi-Apps Terminal Plugin (bash)" app being installed.

**Comment by Itai-Nelken** [comment]
> > This isn't happening anymore, and I haven't been able to reproduce it. I guess it was a script being called while being updated maybe?
> 
> I still routinely get that error whenever I run the `pi-apps` command. I think it's related to the "Pi-Apps Terminal Plugin (bash)".

I have it installed and I don't get the error.

**Comment by Botspot** [comment]
Does this error still happen? I haven't seen it in a while.

**Comment by theofficialgman** [comment]
I honestly have no clue... I never saw it myself

**Comment by cycool29** [comment]
Finally, I know why the error occurs... It is because it reached the GitHub API rate limit. Thus no argument was sent to `date`.

**Comment by cycool29** [comment]
I found another way to check the latest commit date:

```bash
git -C "$DIRECTORY" log -1 --format=%ct origin
```

**Comment by Botspot** [comment]
> I found another way to check the latest commit date:
> 
> ```shell
> git -C "$DIRECTORY" log -1 --format=%ct origin
> ```

Would that check the local repository's latest commit date, or the online version?

**Comment by Itai-Nelken** [comment]
I'm not sure, but I think it's the online version from the `origin` part.

**Comment by Botspot** [comment]
> I'm not sure, but I think it's the online version from the `origin` part.

There's just one problem: if the .git folder gets corrupted, using `git` to check the latest online version will fail, while using github's api, as we currently do, would still succeed.
A few percent of 3-month-reinstalls had an empty local version number, indicating that the .git folder must have been corrupted or missing.

**Comment by Itai-Nelken** [comment]
Then we can check of the version returned by the github api is empty. if yes, use this new version, if not, use the gh api one.

**Comment by Botspot** [comment]
> > Finally, I know why the error occurs... It is because it reached the GitHub API rate limit. Thus no argument was sent to `date`.
> 
> yup just confirmed, this is the reason. I threw the commands into a for loop to spam the github api and was blocked after 50 times in a row.... I don't expect any normal user to ever run into this though

the 3-month-updater runs every time the `manage` script runs. So, I suppose if somebody updates 50 apps that it could happen.

**Comment by Botspot** [comment]
> I wonder.. can you add authentication for this?

I see little reason to, as it's pointless to check more than a few times each day. Perhaps it would be best to hide errors.

**Comment by theofficialgman** [comment]
alternatively, we can just check our ratelimit status and if we are ratelimited, skip the 3-month-update check (since we probably already did it)
```
curl -I https://api.github.com
```
run this and among other things it returns the ratelimit status
```
x-ratelimit-limit: 60
x-ratelimit-remaining: 0
x-ratelimit-reset: 1644946787
x-ratelimit-resource: core
x-ratelimit-used: 60
```

**Comment by theofficialgman** [comment]
as a reminder, the whole purpose of this getting the online date from the repo was because multiple users have installs with incorrect date which could falsely trigger the 3-month-update (raspberry pis don't have any battery backup system clock).

we could instead get the current actual date with something like this
```
rdate -n -4 -p time.nist.gov
```
I tested this for 500 times and was not ratelimited

so the command becomes this and no longer is the git date, but the actual world epoch time
```
upstream_git_date="$(date +%s -d "$(rdate -4 -n -p time.nist.gov)")"
```
you will need to add rdate as a dependency, it may or may not be installed

**Comment by Botspot** [comment]
Another reason for checking the git date is to avoid a hypothetical situation in the future where pi-apps receives no changes for 3 months.
