### ISSUE TITLE
Sublime Text

### ISSUE THREAD

**Issue by Botspot** [Botspot/pi-apps#118]
This has been successfully emulated with Box86 on the RPi platform. It may be a good app to add in the future.

**Comment by Itai-Nelken** [comment]
commands to download and extract the x86 version:
```
wget https://download.sublimetext.com/sublime_text_3_build_3211_x32.tar.bz2
tar xvjf sublime_text_3_build_3211_x32.tar.bz2
rm sublime_text_3_build_3211_x32.tar.bz2
```

**Comment by Itai-Nelken** [comment]
then double clicking on the `sublime_text` executable inside the `sublime_text_3` folder (extracted in last step) opens the app.
but the text color is the same as the background along with some more graphical gliches.
when running from terminal, box86 errors and fails.

**Comment by Itai-Nelken** [comment]
[sublime-text-test.mp4.zip](https://github.com/Botspot/pi-apps/files/5661437/sublime-text-test.mp4.zip)
screen recording showing what I wrote above.
(TwisterOS win7 theme)

**Comment by Botspot** [comment]
Well that was the easy-ish part.

To become an app:

- The install script needs to take care of box86 installation - like how the Steam app does it. Remember that Pi-Apps was originally intended for Raspberry Pi OS.
- The install script needs to make a desktop file. (menu button)
- The uninstall script needs to undo everything the install script did.
- We need some icons, description, website, credits, etc.

**Comment by Itai-Nelken** [comment]
I know, but I won't do it until it works, and it still doesn't, it's completely useless if you can't see the text.

**Comment by Botspot** [comment]
Strange - I can see the text just fine.  
![2020-12-11-101916_1920x1080_scrot](https://user-images.githubusercontent.com/54716352/101927654-57dc7480-3b9a-11eb-8567-c2642a8f43c4.png)

**Comment by Itai-Nelken** [comment]
I think box86 and wine are completley broken on my system, I'll try again on a clean rpiOS install with vdesktop

**Comment by Botspot** [comment]
> I think box86 and wine are completley broken on my system, I'll try again on a clean rpiOS install with vdesktop

Try running this:
```
wget -qO- https://raw.githubusercontent.com/Botspot/box86-updater/main/update-box86 | bash
```

**Comment by Itai-Nelken** [comment]
I think I found the issue, I was trying to use v3, but once I downloaded v2 (from [here](https://www.sublimetext.com/2) it worked, I'll write the scripts now.

**Comment by Itai-Nelken** [comment]
here: [Sublime Text 2.zip](https://github.com/Botspot/pi-apps/files/5680584/Sublime.Text.2.zip)
can someone test/fix the menu button please? it doesn't work for me when I put this as the executable: `$HOME/Sublime\ Text\ 2/sublime_text`

**Comment by Botspot** [comment]
A bit of bash syntax:

- Either you encase a string with quotes, like `"word1 word2"`, and `bash` will consider all of that one single string.
- Or, you can avoid using quotation marks by *escaping* the space characters, like`word1\ word2`.  `Bash` will consider all of that one single string.
- You use one or the other. Not both.

You did `"word1\ word2"`, so bash will literally put those `\` characters in the .desktop file.

**Comment by Botspot** [comment]
Desktop files can be a bit quirky.

I think I got it working now:
```
echo "[Desktop Entry]
Name=Sublime Text 2
Comment=nice text editor that has native support for most programming languages.
Exec='$HOME/Sublime Text 2/sublime_text'
Icon=$(dirname "$0")/icon-64.png
Terminal=false
StartupNotify=false
Type=Application
Categories=Utility;" > ~/.local/share/applications/sublime-text.desktop || error "Failed to create menu button!"
```
Looks like the `Exec=` line must be quoted with single quotes, but the `Icon=` line cannot be single-quoted.

**Comment by Botspot** [comment]
Oh and let's change `StartupNotify=false` to `StartupNotify=true` in the desktop file.

What's StartupNotify? It controls whether your mouse pointer should appear as an hourglass when launching Sublime Text.

**Comment by Itai-Nelken** [comment]
ok, I never really got what startup notify was, thanks for explaining.

**Comment by Itai-Nelken** [comment]
[Sublime Text 2.zip](https://github.com/Botspot/pi-apps/files/5681247/Sublime.Text.2.zip)

**Comment by Itai-Nelken** [comment]
> A bit of bash syntax:
> 
> * Either you encase a string with quotes, like `"word1 word2"`, and `bash` will consider all of that one single string.
> * Or, you can avoid using quotation marks by _escaping_ the space characters, like`word1\ word2`.  `Bash` will consider all of that one single string.
> * You use one or the other. Not both.
> 
> You did `"word1\ word2"`, so bash will literally put those `\` characters in the .desktop file.

thanks for explaining, when it comes to bash, I'm a complete noob but I'm really good at copying and pasting from google.

**Comment by Botspot** [comment]
Added with commit a110e624722e805224a2f0f4ecb61f45006574f8.
