### ISSUE TITLE
MindustryPi

### ISSUE THREAD

**Issue by smithmule** [Botspot/pi-apps#1186]
sorry i am not sure how to do this but i will try :D
i followed the guide here https://github.com/azureblue/MindustryPi

#steps to install
#wget the file from 
https://github.com/azureblue/MindustryPi/releases/download/v110/MindustryPi.jar 
#its in the assets here 
https://github.com/azureblue/MindustryPi/releases

#make sure some stuff is installed
sudo apt install libsdl2-2.0-0
sudo apt install libopenal1
sudo apt install openjdk-11-jre

#the jar file can then be run with 
java -jar MindustryPi.jar

i googled how to make an alias so i can just type mindustry from anywhere.
i will be trying to figure out how to add it to the games folder in my start button tomorrow :D

works on pi400 running bullseye

**Comment by theofficialgman** [comment]
the assets link you sent is a very out of date version of Mindistry
you should be looking at the upstream repo and installing from there

an important thing of note:
```
If you'd rather compile on your own, follow these instructions. First, make sure you have JDK 16-17 installed. Other JDK versions will not work. Open a terminal in the Mindustry directory and run the following commands:
```
