### ISSUE TITLE
Suda-Music (v1.01)

### ISSUE THREAD

**Issue by Raspberry-Pi-Reviews** [Botspot/pi-apps#1191]
This app works on the rpi4 and the rpi400, I have not tested it on all the other pi's.

yes many GUI users will find a use with this app

no this app is not installable with `sudo apt install`.

[Suda-Music-main.zip](https://github.com/Botspot/pi-apps/files/7570888/Suda-Music-main.zip)

**Comment by Crilum** [comment]
@Raspberry-Pi-Reviews Did you use the New App wizard in Pi-Apps settings? The zip is missing icons, the `description`, `credits`, `website`, and `uninstall` files.

The music player also does not have any sound.

**Comment by Crilum** [comment]
The install script should also use `git_clone` instead of `git clone`.

**Comment by theofficialgman** [comment]
closing as this is a poor music player compared to other alternatives. looks like you had some fun writing python code though.

also the user hasn't been active since this was posted

**Comment by Crilum** [comment]
>also the user hasn't been active since this was posted

Yes, they have. They invited me to be a contributor on this app, and I helped them solve some of the problems.
