### ISSUE TITLE
Windows Theme is Glitchy

### ISSUE THREAD

**Issue by 2-bithacker** [Botspot/pi-apps#1192]
On pi-apps, there is an app that converts raspberry pi os to look like windows.  At the end of the install, botspot asked me to let him know what needs improvement; well, I found that the taskbar only is half displayed. Reboots don't fix it.   The ends of it are only visible sometimes.  It is very frustrating when I try to launch stuff;  I'm runing raspbian bullseye.

**Comment by Botspot** [comment]
I am aware of the issue and am making progress to fix the theme. For the time being, I suggest you uninstall the Windows 10 theme to restore the original appearance/

**Comment by 2-bithacker** [comment]
I did that. Thanks!
