### ISSUE TITLE
It needs flightgear.

### ISSUE THREAD

**Issue by 2-bithacker** [Botspot/pi-apps#1193]
Can this app run on RPi? If so, please provide a link to a tutorial if applicable.
flightgear can be installed with `sudo apt update` and `sudo apt install flightgear flightgear-data-ai flightgear-data-all flightgear-data-base flightgear-data-models flightgear-phi`
Is this app something many GUI users would find useful?
It is a high-end free flight simulator.
Is this app installable with `sudo apt install`?
YES

**Comment by Crilum** [comment]
@2-bithacker I think you should read #185. Apps are disqualified if they can be installed with one apt command.

I've also tried using Flightgear, and it ran at like 2fps before crashing 10 seconds later. It also takes like 16 minutes to load..

**Comment by 2-bithacker** [comment]
I get about 30 fps on a pi 4b 8gb running raspbian bullseye; It is very smooth.  Also, I forgot that `sudo apt update` goes before the rest.

**Comment by Crilum** [comment]
> I get about 30 fps on a pi 4b 8gb running raspbian bullseye; It is very smooth. It takes abou 3 to 5 minutes to load with me. It never crashes. Also, I forgot that `sudo apt update` goes before the rest.

Well, that's good. 

Did you read #185? Like I said above, apps are disqualified if they can be installed with one apt command.

**Comment by 2-bithacker** [comment]
Programs are on pi-apps that can be installed with apt;  I didn't notice anything saying 1 command or less.

**Comment by 2-bithacker** [comment]
Why is sonic-pi on there?  It can be installed with, of course, `sudo apt update`, but then, just `sudo apt install sonic-pi` !  1 command.

**Comment by Crilum** [comment]
I'm just stating what the app requirements say:

>- The app is already available on APT.
>- ~~The app requires paying for something.~~ Edit: What was I thinking? MC Java and MC Bedrock are already on here, and KSP is on the waiting list. I think they belong in Pi-Apps, despite costing money. This point is no longer valid.
>- The app is illegal to distribute.

I think Sonic Pi was put on because the current version available in the apt repos at the time was outdated.
Sonic Pi also does not just run `sudo apt install sonic-pi`. It downloads the latest deb from the website, and installs it, like this:

```
wget -O ~/sonic-pi.deb https://sonic-pi.net/files/releases/v3.3.1/sonic-pi_3.3.1_1_armhf.deb || error "Failed to download deb file!"

"${DIRECTORY}/pkg-install" "$HOME/sonic-pi.deb libconfig9 xcompmgr" "$(dirname "$0")" || exit 1
```

@Botspot, what are your thoughts?

**Comment by 2-bithacker** [comment]
oooooohhh!!! I get it now. Thanks.

**Comment by 2-bithacker** [comment]
Shall I close this?

**Comment by Crilum** [comment]
Yeah, unless you can find a later version of Flightgear that install available in the apt repos.

**Comment by Botspot** [comment]
> I think Sonic Pi was put on because the current version available in the apt repos at the time was outdated.

Correct. We don't want Pi-Apps to replace the Raspberry Pi repositories. If something can be installed from there, there is little reason to add it here too.

HOWEVER, I can see a time soon when this will change. Pi-Apps will soon accept package-apps. In fact, the code is already in place and functional. But I think it's best to sort out all of our Bullseye-compatibility issues before dumping hundreds of new apps into Pi-Apps. (our resources are limited)

**Comment by 2-bithacker** [comment]
I see.  I'll wait till then.  Thanks!

**Comment by Crilum** [comment]
@Botspot This can be added now.. :+1:

**Comment by 2-bithacker** [comment]
Excellent!

**Comment by Crilum** [comment]
@Botspot, do you want a zip?

**Comment by Botspot** [comment]
> @Botspot, do you want a zip?

A zip or a PR, that would be great.

**Comment by 2-bithacker** [comment]
I tried to send you a zip, but my pc wasn't compressing it.  What is a PR?

**Comment by Botspot** [comment]
> I tried to send you a zip, but my pc wasn't compressing it. What is a PR?

Are you using the pi-apps app creator? After creation, you should be able to go into your pi-apps folder, find the app-folder, right-click it, and click "Compress". (This is assuming you're using a raspberry pi)

A pull request (PR) is a bit more complicated way to send me an app. It involves using terminal-commands.

**Comment by 2-bithacker** [comment]
I never knew there was a app creator.  I'll try it.  Here is the link to it on github.  https://github.com/FlightGear/flightgear

**Comment by 2-bithacker** [comment]
New pc can make zips.  I added a tarball to the original question.

**Comment by Botspot** [comment]
> I can't add a .zip or tarball sucessfully to the original question.

Try replying to this message and drag-n-drop the zip file to the text entry box.

**Comment by 2-bithacker** [comment]
I tried that.  No success at all.  Look at the github page.  (not the terminal)
![2021-12-02-144851_1920x1080_scrot](https://user-images.githubusercontent.com/90713990/144500659-8e527153-58ae-4c40-91e2-3b8bf302f527.png)
It says "It is not included in the list."  Is there another way I could send you the file?

**Comment by Itai-Nelken** [comment]
FlightGear can be compiled natively, and an older version is either in the debian or ubuntu repos (I don't remember which).

**Comment by 2-bithacker** [comment]
The newest are on both my debian and ubuntu repositories (I am using debian bullseye as debian buster does not run flightgear nearly as well.)

**Comment by Crilum** [comment]
Here:
[Flightgear.zip](https://github.com/Botspot/pi-apps/files/7665664/Flightgear.zip)

**Comment by Crilum** [comment]
@2-bithacker I used p7zip desktop, which can be installed through snapd, like this:
```
sudo snap install p7zip-desktop
```
After you install it, just open it, click on the folder/item/items you want to compress, click add, choose the compression settings you want (somewhere in there, there is a drop down with compression type settings, so you can select `.zip` there.), and click `Ok`. You now have a .zip. :+1:

**Comment by 2-bithacker** [comment]
I tried it in a .zip format, a tarball, and a 7zip.  NONE of them work.

**Comment by Crilum** [comment]
Really? What OS and system are you using? I'm using RPiOS Bullseye, with a Pi 4, 4G..

**Comment by 2-bithacker** [comment]
An old Dell Optiplex 780 running ubuntu 21.10; it's faster at compressing than my pi.  Should I try my pi 4b 8g with bullseye?

**Comment by Crilum** [comment]
Yeah, if it's not too hard.. If you're just compressing a Pi-Apps folder, it's pretty much instant..

**Comment by 2-bithacker** [comment]
I don't have it on my pi-apps.  I just have it installed.  It is pretty hard to switch computers, as I only have one monitor and one mouse and keyboard.  I'll get back to you when I get the pi set up headless or something.

**Comment by 2-bithacker** [comment]
I just tried to do it with a raspberry pi, but the same problem of it not being included in the list.  What is the pi-apps app creator called?

**Comment by Itai-Nelken** [comment]
> I just tried to do it with a raspberry pi, but the same problem of it not being included in the list.  What is the pi-apps app creator called?

Pi-apps settings -> create app

**Comment by Crilum** [comment]
My zip works, I think..

**Comment by 2-bithacker** [comment]
I was making the app install script, when I thought of a problem.  I have to install flightgear on the pi with a build.  That takes over 3 hours, and upwards of 12 gigabytes, but  with full functionality.  When installing it with apt, it installs, but you can only use the default cessna.  What command would I use in the install script to include box86 in the command string so it will just run the x84 appimage and data file that I would make it download  (Assuming that I am using the terminal style installation, and I am having it get the files from flightgear.org)  Doing it this way seems to be the only way, possible for me, to get it to work.  The command language I know much about for installing is the debian-based terminal.

**Comment by Botspot** [comment]
> What command would I use in the install script to include box86 in the command string so it will just run the x84 appimage and data file that I would make it download

Have you verified that box86 can run flightgear? And if it does run, does it run _well_?
In any case, you can look at an existing pi-app that depends on box86 to run. I don't have any on the top of my head, so I used the Search tool in Pi-apps:
![2021-12-20-194608_1920x1080_scrot](https://user-images.githubusercontent.com/54716352/147157513-13bfb024-f714-482d-bb6b-68a2d343f2f5.png) (in this case I'm searching all app-scripts for the word "box86".

Based on the results, I would recommend you look at either Eagle, Sublime Text, or Zoom to see how they did it.

**Comment by Botspot** [comment]
> What command would I use in the install script to include box86 in the command string so it will just run the x84 appimage and data file that I would make it download

Have you verified that box86 can run flightgear? And if it does run, does it run _well_?
In any case, you can look at an existing pi-app that depends on box86 to run. I don't have any on the top of my head, so I used the Search tool in Pi-apps:
![2021-12-22-153056_1920x1080_scrot](https://user-images.githubusercontent.com/54716352/147157721-bd7a3f7c-4573-4816-9795-4e1b1253de9c.png) (in this case I'm searching all app-scripts for the word "box86".

Based on the results, I would recommend you look at either Eagle, Sublime Text, or Zoom to see how they did it.

**Comment by 2-bithacker** [comment]
I know very little bash.  My install script works perfectly,  but, I'm embarassed to ask this, I don't know how to make it create a launch icon.

**Comment by 2-bithacker** [comment]
Have you run a AppImage with box86 before?  If you have, why isn't this working?  It reports no errors or problems of anykind at the end of the install.

`#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"


rm ~/pi-apps/apps/FlightGear/download || error 'This file was not present, so not removed. Dont worry about it:)'
rm ~/pi-apps/apps/FlightGear/download.1 || error 'This file was not present, so not removed. Dont worry about it:)'
rm -rf ~/pi-apps/apps/FlightGear/fgdata || error 'This directory was not present, so not removed. Dont worry about it:)'


#install box86
"${DIRECTORY}/manage" install-if-not-installed Box86 || error "Box86 failed to install somehow!"
if ! command -v box86 >/dev/null ;then
  error "User error: Pi-Apps thinks Box86 is installed, however no command named 'box86' exists. Please install Box86 manually."
fi

wget https://sourceforge.net/projects/flightgear/files/release-2020.3/FlightGear-2020.3.11-x86_64.AppImage/download || error 'Failed to download app from sourceforge.net!'
wget https://sourceforge.net/projects/flightgear/files/release-2020.3/FlightGear-2020.3.11-data.txz/download || error 'Failed to download FlightGear data!'

chmod +x ~/pi-apps/apps/FlightGear/download || error 'chmod of Flightgear.AppImage failed!'
tar -xf ~/pi-apps/apps/FlightGear/download.1 || error 'extract of Fightgear-data.txz fialed!'

#Be sure to use the "error" function - it will display a message if a command fails to run. Example below:
rm ~/pi-apps/apps/FlightGear/download.1 || error 'This file was not present, so not removed. Dont worry about it:)'

echo "[Desktop Entry]
Name=Flight Gear
Comment=Open source, feature-rich, and highly sophisticated flight simulator.
Exec=box86 '$HOME/FlightGear'
Icon=$(dirname "$0")/icon-64.png
Terminal=false
StartupNotify=true
Type=Application
Categories=Development;" > ~/.local/share/applications/FlightGear.desktop || error "Failed to create menu button!"`

**Comment by 2-bithacker** [comment]
I just learned it needs box64 to run the .AppImage I'm going to make the script install it as well.  (This script is getting very long here)

**Comment by 2-bithacker** [comment]
Latest update:  Box64 is what I need to run the AppImage.  I hears pi-apps has box64, but when I search for it, no results are found.  I looked in /home/pi/pi-apps/apps and there is a file called box64 there.  I ran the install script there, but it did not successfully install.

**Comment by Crilum** [comment]
> Latest update: Box64 is what I need to run the AppImage. I heard pi-apps has box64, but when I search for it, no results are found. I looked in /home/pi/pi-apps/apps and there is a file called box64 there. I ran the install script titled install-64 that I found there, but it did not successfully install.

That's because you can only install Box64 (or any 64-bit app) on 64-bit RPiOS, or at least 64-bit kernel. 

If you still have these lines:

```
rm ~/pi-apps/apps/FlightGear/download || error 'This file was not present, so not removed. Dont worry about it:)'
rm ~/pi-apps/apps/FlightGear/download.1 || error 'This file was not present, so not removed. Dont worry about it:)'
rm -rf ~/pi-apps/apps/FlightGear/fgdata || error 'This directory was not present, so not removed. Dont worry about it:)'
```
You'll have to change the `error` part to `warning`, or else the script will fail if those files aren't there to be removed.
I'd recommend no message at all for those lines, and to redirect them to `/dev/null`, so it doesn't have ugly error messages:

```
rm ~/pi-apps/apps/FlightGear/download &>/dev/null
rm ~/pi-apps/apps/FlightGear/download.1 &>/dev/null
rm -rf ~/pi-apps/apps/FlightGear/fgdata &>/dev/null
```

**Comment by 2-bithacker** [comment]
I am using bullseye 64 bit.

**Comment by Crilum** [comment]
Well, then you should be able to install it, what error did you have?

**Comment by 2-bithacker** [comment]
When I ran the script, I got a bunch of unreadable foreign fonts.

**Comment by Crilum** [comment]
Ohh, you have to have sourced the Pi-Apps `api` script.

Try this:
```
$ DIRECTORY=$HOME/pi-apps
$ source $HOME/pi-apps/api
$ .$HOME/pi-apps/apps/Box64/install-64
```

**Comment by 2-bithacker** [comment]
I got it to work, but it is way to slow on the rpi4b 8gb.  The emulation part makes it about 3-15 fps.  It used to be very playable, but running the other binary knocks it out. Sorry.
