### ISSUE TITLE
GOG Games Installer(App Request)

### ISSUE THREAD

**Issue by gl91306** [Botspot/pi-apps#120]
Can you please add the GOG Installer App to PiApps? Also, great work on this project! :))))

**Comment by Botspot** [comment]
@gl91306 Are you aware of GOG running on RPi?

**Comment by Botspot** [comment]
@gl91306 Pi-Apps isn't magical. Each app has to be able to run on RPi **first**, then if I think that many people would like to use it, I can add it to the Pi-Apps app store.

So for the first step: do you know how to make GOG Installer run on the RPi?

**Comment by Botspot** [comment]
Unfortunately, I've had to close this issue due to your inactivity.

@gl91306, feel free to reply back and I can re-open it.
