### ISSUE TITLE
Deskreen not installing on Bullseye 64bit

### ISSUE THREAD

**Issue by radarcorr** [Botspot/pi-apps#1203]
The other form is not working for me so I am using this blank issue form.

The app is not installing on Raspberry Pi OS arm64

Yes I have updated pi apps

Here are the logs

OS: Debian GNU/Linux 11 (bullseye)
OS architecture: 64-bit
Pi-Apps local commit ID: ce96a6ed31888715ec4bb38ae50d05af4415f6f3
Github latest commit ID: ce96a6ed31888715ec4bb38ae50d05af4415f6f3	
Kernel: aarch64 5.10.63-v8+
Device model: Raspberry Pi 4 Model B Rev 1.4
Ram size:  GB
Raspberry Pi OS image version: 2021-10-30
Language: en_US.UTF-8

BEGINNING OF LOG FILE:
-----------------------

Will install these packages: https://osdn.mirror.constant.com/storage/g/r/ra/raspbian-addons/debian/pool/deskreen_1.0.11_arm64.deb 
Downloading deskreen_1.0.11_arm64.deb... 
Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
3adae1|OK  |   5.3MiB/s|/home/pi/deskreen_1.0.11_arm64.deb

Status Legend:
(OK):download completed.
Done
Running sudo apt update...
Ign:1 file:/tmp/pi-apps-local-packages ./ InRelease
Ign:2 file:/tmp/pi-apps-local-packages ./ Release
Ign:3 file:/tmp/pi-apps-local-packages ./ Packages
Ign:4 file:/tmp/pi-apps-local-packages ./ Translation-en_US
Ign:5 file:/tmp/pi-apps-local-packages ./ Translation-en
Ign:6 file:/tmp/pi-apps-local-packages ./ Translation-en_US.UTF-8
Ign:3 file:/tmp/pi-apps-local-packages ./ Packages
Ign:4 file:/tmp/pi-apps-local-packages ./ Translation-en_US
Ign:5 file:/tmp/pi-apps-local-packages ./ Translation-en
Ign:6 file:/tmp/pi-apps-local-packages ./ Translation-en_US.UTF-8
Ign:3 file:/tmp/pi-apps-local-packages ./ Packages
Ign:4 file:/tmp/pi-apps-local-packages ./ Translation-en_US
Ign:5 file:/tmp/pi-apps-local-packages ./ Translation-en
Ign:6 file:/tmp/pi-apps-local-packages ./ Translation-en_US.UTF-8
Ign:3 file:/tmp/pi-apps-local-packages ./ Packages
Ign:4 file:/tmp/pi-apps-local-packages ./ Translation-en_US
Ign:5 file:/tmp/pi-apps-local-packages ./ Translation-en
Ign:6 file:/tmp/pi-apps-local-packages ./ Translation-en_US.UTF-8
Ign:3 file:/tmp/pi-apps-local-packages ./ Packages
Ign:4 file:/tmp/pi-apps-local-packages ./ Translation-en_US
Ign:5 file:/tmp/pi-apps-local-packages ./ Translation-en
Ign:6 file:/tmp/pi-apps-local-packages ./ Translation-en_US.UTF-8
Ign:3 file:/tmp/pi-apps-local-packages ./ Packages
Ign:4 file:/tmp/pi-apps-local-packages ./ Translation-en_US
Ign:5 file:/tmp/pi-apps-local-packages ./ Translation-en
Ign:6 file:/tmp/pi-apps-local-packages ./ Translation-en_US.UTF-8
Ign:4 file:/tmp/pi-apps-local-packages ./ Translation-en_US
Ign:5 file:/tmp/pi-apps-local-packages ./ Translation-en
Ign:6 file:/tmp/pi-apps-local-packages ./ Translation-en_US.UTF-8
Hit:7 http://security.debian.org/debian-security bullseye-security InRelease
Hit:8 http://archive.raspberrypi.org/debian bullseye InRelease
Hit:10 http://deb.debian.org/debian bullseye InRelease
Hit:11 http://deb.debian.org/debian bullseye-updates InRelease
All packages are up to date.
apt update complete.
Creating an empty apt-package to install the necessary apt packages...
It will be named: pi-apps-0c3404b5
Depends: deskreen
Installing the pi-apps-0c3404b5 package...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:
The following packages have unmet dependencies:
 deskreen : Depends: libappindicator3-1 but it is not installable
E: Unable to correct problems, you have held broken packages.
Apt finished.
Failed to install the packages!
APT reported these errors:
E: Unable to correct problems, you have held broken packages.
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:
The following packages have unmet dependencies:
 deskreen : Depends: libappindicator3-1 but it is not installable
E: Unable to correct problems, you have held broken packages.

[91mFailed to install Deskreen![39m
[40m[93m[5m🔺[25m[39m[49m[93mNeed help? Copy the [1mENTIRE[0m[49m[93m terminal output or take a screenshot.
Please ask on Github: [94m[4mhttps://github.com/Botspot/pi-apps/issues/new/choose[24m[93m
Or on Discord: [94m[4mhttps://discord.gg/RXSTvaUvuu[0m

**Comment by cycool29** [comment]
`libappindicator3-1` is deprecated in bullseye, and many apps will not work. 

I will test if Deskreen works well without ` libappindicator3-1` (or with its alternative, `libayatana-appindicator3-1`). If so, I will make another deb to remove ` libappindicator3-1` as dependency.

**Comment by radarcorr** [comment]
Thanks

**Comment by radarcorr** [comment]
Also I found that you could download the package from this link http://ftp.us.debian.org/debian/pool/main/liba/libappindicator/libappindicator3-1_0.4.92-7_arm64.deb
Hope it helps

**Comment by cycool29** [comment]
I just installed deskreen without `libappindicator3-1`, and I don't see any significant issue. 

Here is the modified deb:  https://transfer.sh/dyn3Xl/deskreen_1.0.11_arm64.deb @ryanfortner

**Comment by cycool29** [comment]
Opened a PR [here](https://github.com/Pi-Apps-Coders/files/pull/7).
