### ISSUE TITLE
cool-retro-term already in apt

### ISSUE THREAD

**Issue by ryanfortner** [Botspot/pi-apps#1205]
`cool-retro-term` can be installed via the apt repositories on rpios bullseye. Maybe it should be removed from pi-apps now?

I can open a pr with changes if needed.

**Comment by cycool29** [comment]
We still have buster users, so that is not a good idea.

That's why we need `check_codename` function, or something similar to that.

**Comment by Botspot** [comment]
Closing, as APT packages are now allowed on pi-apps.
