### ISSUE TITLE
Change Pi-Apps Settings icon

### ISSUE THREAD

**Issue by Crilum** [Botspot/pi-apps#1206]
### Cool ideas?

I would like to put the Pi-Apps Settings shortcut on my Launch Bar, but the icon is the same as Pi-Apps, so I won't be able to tell them apart. Could we change the Pi-Apps Settings icon to have, like, a gear in it or something?

**Comment by cycool29** [comment]
![settings](https://user-images.githubusercontent.com/88134003/146889537-8111ae81-b439-47e2-bfc3-fc2899f349a7.png)

![image](https://user-images.githubusercontent.com/88134003/146889650-ca05202f-d157-4f9e-bccd-3cadf0cb6436.png)


@Botspot

**Comment by Crilum** [comment]
Cool!
