### ISSUE TITLE
Adding a website

### ISSUE THREAD

**Issue by ryanfortner** [Botspot/pi-apps#1218]
### Cool ideas?

I've been working on a pi-apps website, live at https://pi-apps.io/ , with source code available [here](https://github.com/Pi-Apps-Coders/website). I think it might be a good idea to add it to the repository details, or some sort of reference in the readme, as some users may prefer using it?

What do you think @Botspot ?

**Comment by cycool29** [comment]
I would not recommend a website for pi-apps, for these two reasons:
- Almost all links in the website point to GitHub, there is nothing informational there.
- GitHub pages SEO is weak. GitHub.com will be more 'famous' than GitHub pages in Google searches.

However, since you have applied for a domain and the site is ready now, I see no reason to don't put it on the README!

**Comment by ryanfortner** [comment]
> Almost all links in the website point to GitHub, there is nothing informational there.

I will create an install/uninstall instruction page in a bit, so it doesn't just redirect to GitHub. Thank you for the feedback!

**Comment by cycool29** [comment]
> I will create an install/uninstall instruction page in a bit, so it doesn't just redirect to GitHub. 

I think you can put the install command on the home page, like how the Pi-Ware website does.

**Comment by ryanfortner** [comment]
> I think you can put the install command on the home page, like how the Pi-Ware website does.

I've added it to the main page.

**Comment by Crilum** [comment]
@ryanfortner 
Looks great. I think it would help to add a couple `hr`'s in the install/uninstall part.
I'll make a PR soon(ish).

**Comment by Crilum** [comment]
I think it might be a little repetitive to have install instructions on main page, and an install link in the header..

**Comment by Crilum** [comment]
@ryanfortner I'm getting this error from your JS:
```
Uncaught TypeError: Cannot set properties of null (setting 'innerHTML')
    at copyToClipboard (index.html:119)
    at HTMLButtonElement.onclick (index.html:89)
```
also, both copied buttons show `Copied!` when you click on one.

**Comment by ryanfortner** [comment]
> @ryanfortner I'm getting this error from your JS:
> 
> ```
> 
> Uncaught TypeError: Cannot set properties of null (setting 'innerHTML')
> 
>     at copyToClipboard (index.html:119)
> 
>     at HTMLButtonElement.onclick (index.html:89)
> 
> ```
> 
> also, both copied buttons show `Copied!` when you click on one.

Is it any different when using a different web browser?

**Comment by leha-code** [comment]
Anyways if you want to have a website for it, I have a domain, pi-apps.tk, currently it redirects to the github page

**Comment by ryanfortner** [comment]
> Anyways if you want to have a website for it, I have a domain, pi-apps.tk, currently it redirects to the github page

@leha-code I already have a domain set up: https://pi-apps.io.

**Comment by leha-code** [comment]
Whatever

**Comment by oxmc** [comment]
> 

i belive that was an error in my js before, not sure.

**Comment by oxmc** [comment]
@ryanfortner I fixed the copy.js script, I'll make a pr with the working script soon.

**Comment by oxmc** [comment]
@ryanfortner https://oxmc.github.io/website/ here is the working example site.

**Comment by ryanfortner** [comment]
@Botspot quite a few improvements to the website have been made over the last couple days, what do you think? https://pi-apps.io 

https://github.com/Pi-Apps-Coders/website

**Comment by Botspot** [comment]
> @Botspot quite a few improvements to the website have been made over the last couple days, what do you think? https://pi-apps.io

Amazing!
1. Who paid for the domain?
2. Why is the dark mode not very dark?
3. Could the app websites in the app list be made clickable?
4. Do the documentation pages automatically synchronize with DOCUMENTATION.md?

**Comment by ryanfortner** [comment]
> 1. Who paid for the domain?

The domain was generously provided by the [Fosshost project](https://fosshost.org/)  

> 2. Why is the dark mode not very dark?

Do you mean the dark mode for the docs site? The main site (https://pi-apps.io) doesn’t have a dark mode (yet). 

> 3. Could the app websites in the app list be made clickable?

Sure! I’ll add it to my to-do list. 

> 4. Do the documentation pages automatically synchronize with DOCUMENTATION.md?

No. However, the apps list page synchronizes with the apps list on the wiki.

**Comment by Crilum** [comment]
@ryanfortner Looks Awesome! 
However, the screenshots on the home page look kind of smushed:
![2022-01-06-172535_1024x768_scrot](https://user-images.githubusercontent.com/91354257/148471391-05d787c4-4d7d-480b-8193-2d3649c7cbc5.png)

**Comment by theofficialgman** [comment]
@ryanfortner the website needs updating with new pictures from the new GUI update

**Comment by ryanfortner** [comment]
> @ryanfortner the website needs updating with new pictures from the new GUI update

Done, thanks for reminding me (I know the image appears a bit large, I am working on scaling it down).
