### ISSUE TITLE
Test AntiMicroX DEB

### ISSUE THREAD

**Issue by cycool29** [Botspot/pi-apps#1219]
I have built DEB packages for AntiMicroX to avoid compile errors in installation.

armhf: https://transfer.sh/zNWLCt/antimicrox_3.2.0_armhf.deb
arm64: https://transfer.sh/JXFL8O/antimicrox_3.2.0_aarch64.deb

Can anyone test them? @Crilum

**Comment by Crilum** [comment]
armhf works, as far as I can tell.

**Comment by cycool29** [comment]
I just tested them on vdesktop and both of them launched well.
