### ISSUE TITLE
Wont execute after latest Dec Pi OS Update

### ISSUE THREAD

**Issue by yeoldalchemist** [Botspot/pi-apps#122]
Since i have updated to the latest PI OS pi apps GUI does not execute, I get update notifications which appear to be installed but as soon as i try opening Pi apps from icon or terminal i get egg timer for 5 seconds then nothing. I have tried to uninstall pi apps and reinstall but still not able to execute. Not sure if its an issue specifically to me or the update has corrupted the App. Hope this is informative

**Comment by Itai-Nelken** [comment]
Run `~/pi-apps/gui` in terminal and post the terminal output. the command starts pi-apps regularly, but you can see any errors.

**Comment by yeoldalchemist** [comment]
im not great at terminal copying, and the code seems to be repeating last line which is OUTPUT : E00  there is a lot of script prior to that but cant seem to catch it. I have paused it and seems to count to 100% verifying that the apps are no different to the online version and then it sticks on the OUTPUT : E00 referenced above

**Comment by Itai-Nelken** [comment]
I'm no expert at this, better wait for @Botspot.
btw to copy from terminal, select the text by clicking and dragging, than right click and copy or shift+control+c

**Comment by Botspot** [comment]
@yeoldalchemist Yes, first try sending me the full output.

Also, did Pi-Apps work in the past for you? How did you install Pi-Apps?

**Comment by yeoldalchemist** [comment]
I can't send the full output as mentioned in my earlier post it doesn't stop it constantly is running and leaving the output : message. Installed pi apps from terminal copy and pasting from the github. Have been enjoying the app up until the update with no issues


kind regards


Tim

Yate Computing


07749382602


sent via outlook for mobile devices

**Comment by Itai-Nelken** [comment]
@yeoldalchemist maybe Start pi-apps from terminal, and when you start seeing any errors, stop it with control+c, and than post the output.

**Comment by Botspot** [comment]
> I can't send the full output as mentioned in my earlier post it doesn't stop it constantly is running and leaving the output : message. Installed pi apps from terminal copy and pasting from the github. Have been enjoying the app up until the update with no issues

Try creating a log file to send me:
```
~/pi-apps/gui &>/home/pi/Desktop/pi-apps-log.txt
```

**Comment by Botspot** [comment]
@yeoldalchemist Have you seen this yet?

**Comment by yeoldalchemist** [comment]
[pi-apps-log.txt](https://github.com/Botspot/pi-apps/files/5660498/pi-apps-log.txt)

**Comment by yeoldalchemist** [comment]
coincidentally although the GUI does not appear the cores are very active until i shut the pi down. I also had an update reminder tpday which ran fine.

**Comment by Botspot** [comment]
Whoa.

Is yad installed?

Are you running that command in a graphical environment, or from the console?

**Comment by yeoldalchemist** [comment]
Its run from the standard pi os  terminal, not sure about yad.


But as said before all was working well for last month or so until i updated pi is to latest version then bam all went wrong.


kind regards


Tim

Yate Computing


07749382602


sent via outlook for mobile devices

**Comment by Botspot** [comment]
That is very strange. Try running these commands:
```
sudo apt install yad
~/pi-apps/updater
```

**Comment by yeoldalchemist** [comment]
@Botspot Hi Yad was at its newest version and i then had a thought on something i hadnt checked. Using the uninstall command for Piapps still left the coatining folder and some files so i deleted the folder restarted and then reinstalled using the full process and voila all now working. Apologies if this is a known fact when uninstalling an app from Pi OS but i would have hoped that uninstall would have removed all redundant files.

Any way i much appreciate the assistance given and really like the app and what it is doing.

case closed
