### ISSUE TITLE
Issue forms aren't working (github issue)

### ISSUE THREAD

**Issue by Itai-Nelken** [Botspot/pi-apps#1222]
we should revert to the old markdown ones for now.

**Comment by cycool29** [comment]
Why?

**Comment by ryanfortner** [comment]
They seem to be working fine for me…

**Comment by cycool29** [comment]
Oh, I just saw that on githubstatus.com

![image](https://user-images.githubusercontent.com/88134003/143725848-d64f1f66-5fc3-486a-956f-d91ac2cb8f41.png)

**Comment by Itai-Nelken** [comment]
They still aren't working, see #1230.

**Comment by cycool29** [comment]
There is a blank issue template on the choose template page. We can disable it: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#configuring-the-template-chooser.

![image](https://user-images.githubusercontent.com/88134003/144196696-0b93e799-e8cd-4246-ad9b-94a0489e6cb3.png)

**Comment by Itai-Nelken** [comment]
But why disable it?
The main ones aren't working, and disabling the blank template will make it impossible to open issues!
I think we should revert to the old markdown ones until the forms start working again.
what do you think @Botspot?

**Comment by cycool29** [comment]
> They still aren't working, see #1230.

What do you mean by `they still aren't working`? They are working though.

**Comment by Botspot** [comment]
> I think we should revert to the old markdown ones until the forms start working again. what do you think @Botspot?

They are working fine for me. 🤷‍♂️

**Comment by Itai-Nelken** [comment]
They are working again for me.

**Comment by Botspot** [comment]
We can re-open if this becomes an issue again.

**Comment by Crilum** [comment]
The Bug Report template isn't showing up on the Issues Page:
![pi-apps-no-bug-report](https://user-images.githubusercontent.com/91354257/147127804-d7d4f34c-9e09-437b-877f-bcae0fb4e153.png)

**Comment by Botspot** [comment]
@Crilum, I can confirm your observation, and when I went to edit templates there was this error.
![2021-12-22-150703_1920x1080_scrot](https://user-images.githubusercontent.com/54716352/147155278-fd90260a-c6e2-4800-89d8-2bd188dbf612.png)
Does anyone know what it means?

**Comment by cycool29** [comment]
> @Crilum, I can confirm your observation, and when I went to edit templates there was this error. ![2021-12-22-150703_1920x1080_scrot](https://user-images.githubusercontent.com/54716352/147155278-fd90260a-c6e2-4800-89d8-2bd188dbf612.png) Does anyone know what it means?

It means the `label` attribute is missing in the [second `body` section](https://github.com/Botspot/pi-apps/blob/0806d60409c0f39395c1f4d547b0f8abfbed12eb/.github/ISSUE_TEMPLATE/bug-report.yml#L9-L15).

When I add the `label` attribute, it works on my testing repo.

But I think this is an error of GitHub, as the `label` attribute is not required in `checkboxes`.

![image](https://user-images.githubusercontent.com/88134003/147171482-e50eecc2-2e6c-41e1-af6b-bfc48d8ab901.png)


I opened a PR [here](https://github.com/Botspot/pi-apps/pull/1297) to add the `label` attribute.
