### ISSUE TITLE
Adding a documentation site

### ISSUE THREAD

**Issue by ryanfortner** [Botspot/pi-apps#1223]
### Cool ideas?

I’ve been experimenting with [MKDocs](https://www.mkdocs.org/), a site generator for documentation websites. It’s super easy to use and simple to set up. 

Since there is only one long page for documentation now, I was thinking maybe we could create a formal site for it.

I created a site here: https://github.com/Pi-Apps-Coders/docs, if there are any improvements to be made or if you think this isn’t a good idea please let me know!

**Comment by Crilum** [comment]
This is great! I think some of the titles need to be updated, such as `The main pi apps folder`. I think it might be better to just have the folder docs be titled something simpler like this: `Folders: Pi-Apps` (or if you can't get a dash in there: `Folders: Pi Apps`).

**Comment by ryanfortner** [comment]
> I think this is great! I think some of the titles need to be updated, such as `The main pi apps folder`. I think it might be better to just have the folder docs be titled something simpler like this: `Folders: Pi-Apps` (or if you can't get a dash in there: `Folders: Pi Apps`). 

Feel free to open a PR if you want. I'm wide open to any improvements :)

**Comment by cycool29** [comment]
I think this is unnecessary... But since you've already set up the site (and it looks beautiful too), we can just add the website link in the README.

@Botspot What do you think?

**Comment by leha-code** [comment]
Guys, make a docs folder in the repo and put markdown docs there. Then turn on github pages and connect the domain

**Comment by leha-code** [comment]
Select the folder to be docs in github pages instead of root

**Comment by ryanfortner** [comment]
> Guys, make a docs folder in the repo and put markdown docs there. Then turn on github pages and connect the domain

@leha-code this isn't necessary. Mkdocs is a static website generator, and so it generates html and css files for the site. There is another branch of the repository for the static site: gh-pages. This is where GitHub pages is served from. 

If you'd like to see how it works, take a look at the '.github/workflows/publish.yml' file in the master branch.

**Comment by leha-code** [comment]
I know what is mkdocs, but, if you host github pages on the main branch and you have a docs folder there, it will host the docs folder

**Comment by ryanfortner** [comment]
> I know what is mkdocs, but, if you host github pages on the main branch and you have a docs folder there, it will host the docs folder

Hosting the docs folder will only show markdown files. Hosting the gh-pages branch will show the entire website.

**Comment by ryanfortner** [comment]
@Botspot any thoughts?

**Comment by theofficialgman** [comment]
We made this years ago on our wiki https://pi-apps.io/wiki/development/DOCUMENTATION/
Closing
