### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by ryanfortner** [Botspot/pi-apps#1225]
### What is the name of the app?

Update

### (Optional) Where is the app hosted?

Update is hosted on GitHub: https://github.com/Crilum/update

### About the app

`update` is a small but mighty script that updates apps/packages/dependencies from Apt, Pi-Apps, Flatpak, the Snap Store, Homebrew, and NPM.

### Upload file

I don't have a zip right now., but there are deb files available on the [latest release](https://github.com/Crilum/update/releases/latest)

### Confirmations

- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.
- [X] I have confirmed that this app is not installable with `apt`, or the app is the updated version of APT one.

**Comment by Crilum** [comment]
I'll make a zip.

**Comment by Crilum** [comment]
Um, should I just call it `update`? That doesn't sound very good.. I could call it `Crilum's update script`, how's that?

**Comment by ryanfortner** [comment]
something like `Package Updater` or `CLI Package Updater` maybe?

**Comment by Crilum** [comment]
That seems kind of boring...

**Comment by Crilum** [comment]
What about `Crilum's CLI Update Tool`? If you don't want my username on there then maybe just `CLI Update Tool`?

**Comment by Crilum** [comment]
Here's a zip, the name can be changed, if need be:
[Crilum's CLI Update Tool.zip](https://github.com/Botspot/pi-apps/files/7620883/Crilum.s.CLI.Update.Tool.zip)

**Comment by ryanfortner** [comment]
I think it'll look more appealing to users with the name as just 'CLI Update Tool'. Just my opinion though.

**Comment by Crilum** [comment]
[CLI Update Tool.zip](https://github.com/Botspot/pi-apps/files/7623362/CLI.Update.Tool.zip)

**Comment by Botspot** [comment]
I think the smartest approach would be to improve our existing "All is Well" app. This app already does what we want, for apt at least, and has a good number of users.

**Comment by Botspot** [comment]
Or we could improve Update Buddy. 🤷‍♂️

**Comment by Crilum** [comment]
> I think the smartest approach would be to improve our existing "All is Well" app. This app already does what we want, for apt at least, and has a good number of users.

Do you mean to replace All is Well with update?

**Comment by Botspot** [comment]
> > I think the smartest approach would be to improve our existing "All is Well" app. This app already does what we want, for apt at least, and has a good number of users.
> 
> Do you mean to replace All is Well with update?

I mean that rather than _adding_ a third updating tool to pi-apps, it would be better to add this tool's functionality to one of our two *existing* update tools. (After all, it doesn't really make sense to have multiple updaters installed)

**Comment by Crilum** [comment]
I like to try to update stuff all the time, and update just saves me from typing `sudo apt update && sudo apt upgrade` or `~/pi-apps/updater cli-yes` over and over again.

**Comment by Crilum** [comment]
If we added update to All is Well, what would All is Well do? update kind of replaces it..

**Comment by Botspot** [comment]
> Yes, but I think update is different. It's a command that you can run to just update apps from Pi-Apps, or apt, or snap, or you can update everything. All is Well doesn't have arguments that you can choose from, as far as I know, and Update Buddy only checks on boot. We don't have an update tool that can update from multiple package managers, which I think would be very useful to lots of people.

Oh I know. I'm suggesting that all of that functionality be *added* to All is Well. (Forget about Update Buddy)
For all I care, you could replace AiW with Update, but still call it AiW and use the same terminal-command.

Basically, thousands of people already use All is Well. Adding new features and flags to it, like the ability to update pi-apps and snap, seems smarter than adding a new app to compete with it.

Besides, shouldn't "**All** is Well" update **all** package-managers? ;)

**Comment by Crilum** [comment]
I think that would work, but do you think the creator of All is Well would be okay with that?

**Comment by Botspot** [comment]
> I think that would work, but do you think the creator of All is Well would be okay with that? Replacing his script with a different one, but still calling it All is Well?

Maybe you could fork the [repo](https://github.com/spectrumgamer75/All-is-well) and work from there.

But if that doesn't work, we don't have much to worry about as @spectrumgamer75 has been inactive for nearly a year.
![2021-11-30-114717_1920x1080_scrot](https://user-images.githubusercontent.com/54716352/144100498-44e0b551-586a-4430-a5ae-5215f365aede.png)

**Comment by theofficialgman** [comment]
any intention to finish this or fork/rework all is well? you are allowed to fork all is well and keep the name according to its license and I think its fine to do so.

**Comment by Crilum** [comment]
> any intention to finish this or fork/rework all is well? you are allowed to fork all is well and keep the name according to its license and I think its fine to do so.

I still work on update, and it is fully maintained, if that's what you're asking. I don't really want to change the name to All is Well, but I have been thinking of renaming it to `up` (I added alias in my `.bashrc`, and it's so much easier than typing `update`..), would that be a better name?

**Comment by Botspot** [comment]
@Crilum, This might sound a little convoluted, but hear me out.
Right now Pi-Apps has two updating tools: "All Is Well" and "Update Buddy".
Rather than potentially adding a third option, I was thinking of combining all three. All Is Well would be removed, and users who have it installed will be transitioned to Update Buddy.
Update Buddy itself would be a combination of your "update" tool with my Update Buddy gui stuff.

So at the end of the day, there would be one updating program with both a gui and cli interface for updating all package-managers, with the option to autostart, and All Is Well users would not be dropped in the process.

**Comment by Crilum** [comment]
@Botspot FYI, RPiOS now has it's own on-boot updater:
![image](https://user-images.githubusercontent.com/91354257/170363214-84386f00-54af-45cc-9e82-2c49c8c709d0.png)


![image](https://user-images.githubusercontent.com/91354257/170364057-298585f5-9dfd-49a7-9d83-e564a657eb25.png)

It isn't very complex, though. 

@Botspot I don't want to combine `update` and Update Buddy in the sense that there wouldn't be any `update` anymore, but what we could do is make `update` the backend for Update Buddy (which I think is what you were saying?), so you have Update, the CLI part and backend, and Update Buddy, the GUI part and frontend. 

I could also try to create a new GUI for update, with PyQt5 (Qt5 and Python), which I am learning.

**Comment by Botspot** [comment]
> @Botspot I don't want to combine `update` and Update Buddy in the sense that there wouldn't be any `update` anymore, but what we could do is make `update` the backend for Update Buddy (which I think is what you were saying?), so you have Update, the CLI part and backend, and Update Buddy, the GUI part and frontend.

That's what I was thinking - transplanting the Update Buddy GUI and autostart code to your project, while retaining your name for it.
Then within Pi-Apps, all existing users of Update Buddy would be migrated to your repo, but the app within Pi-Apps would be named the same.

**Comment by Crilum** [comment]
Ok, I'll take a look at Update Buddy's code, and see if I can change it to use `update`.

**Comment by Crilum** [comment]
> Ok, I'll take a look at Update Buddy's code, and see if I can change it to use `update`.

Actually, why do I need to change the code? It works well as it is. Nevermind.

What if I made a GUI with PyQt5, that has tabs, so you could update each app store/package manager?
maybe something that looks like this:

https://user-images.githubusercontent.com/91354257/170557112-199dfc67-ba91-4808-8c84-7316eb5c0498.mp4

With more package managers, and an `Install all updates output` tab.

**Comment by theofficialgman** [comment]
closing as stale
if developent and interest picks up in the future this can be re-opened

also just an fyi this is no good: https://github.com/Crilum/update/blob/main/update#L245
calling that will still upgrade other packages in addition to the ones listed. use `sudo apt install --only-upgrade packagename`
