### ISSUE TITLE
GIMP

### ISSUE THREAD

**Issue by rileydavies** [Botspot/pi-apps#1229]
apt package gimp

[GIMP.zip](https://github.com/Botspot/pi-apps/files/7629626/GIMP.zip)

**Comment by Botspot** [comment]
Thanks!

**Comment by Crilum** [comment]
> Thanks!

@Botspot Has the policy on apt duplicates changed? GIMP is already available from apt...

**Comment by Botspot** [comment]
> @Botspot Has the policy on apt duplicates changed? GIMP is already available from apt...

Oh I guess you aren't in our [Discord server](https://discord.gg/RXSTvaUvuu) so you haven't been seeing the announcements lately.
Today I've [rolled out](https://github.com/Botspot/pi-apps/commit/2ef8be885c463de17d13dfc8fa5033eb3d83526e) package-apps: a new type of app that will simply install an apt package. So from now on, some packages will be allowed on pi-apps - they have to be something a desktop user would want.

**Comment by Crilum** [comment]
Thanks. Yeah, I don't have Discord, so I didn't see that. Maybe we could make a new App Eligibility Rubric?

**Comment by Botspot** [comment]
> Maybe we could make a new App Eligibility Rubric?

Done.
