### ISSUE TITLE
UsbImager characters not displaying in non-english (russian)

### ISSUE THREAD

**Issue by Rak1ta** [Botspot/pi-apps#1230]
Tried running some applications on my Pi and got some errors in the process.
RaspiOS 32bit Debian 10, tested on a clean, updated system.
a) When installing LibrePCB, a program shortcut is created, but there Type = LibrePCB instead of Application and the shortcut is not displayed in the application menu.
b) UsbImager does not display characters when Russian is selected, but my system language is Russian UTF8. Other languages are displayed normally.
в) OpenSCAD doesn't work after installation
```
pi@raspberrypi:~ $ OpenSCAD.AppImage
bash: OpenSCAD.AppImage: команда не найдена
(command not found)
pi@raspberrypi:~ $ bash -c 'sudo modprobe fuse; ~/OpenSCAD.AppImage'
bash: строка 1: 17189 Ошибка сегментирования ~/OpenSCAD.AppImage
(Segmentation error)
pi@raspberrypi:~ $
```
г) Eagle CAD won't launch.
```
pi@raspberrypi:~ $ eagle
Box86 with Dynarec v0.2.3 b5623128 built on Nov  7 2021 00:05:16
Error: PltReolver: Symbol CRYPTO_num_locks(ver 0: CRYPTO_num_locks) not found, cannot apply R_386_JMP_SLOT 0x9ab3aa8 (0x807ccb6) in /usr/local/bin/eagle
pi@raspberrypi:~ $ 
```
д) BleachBit installs and works, but an error occurs with the shortcut.
```
Package installation complete.
sed: can't read /usr/share/applications/bleachbit-root.desktop: No such file or directory
Failed to move BleachBit to Accessories category.
```
[Fix bleachbit desktop shortcut path (#1213)](https://github.com/Botspot/pi-apps/commit/5be2b40463380fb28ecef07c5625db9be8f2fb20#diff-18b9d1e5f84794a077631cb82867ad93305ecb0a47ea65ed28cac95974876112)
There is one in the folder with shortcuts, but with a different name. - "org.bleachbit.BleachBit-root.desktop"

*I wanted to submit it through a bug-form, but when creating it, an error 400 occurs.

**Comment by Rak1ta** [comment]
Tried running some applications on my Pi and got some errors in the process
a) When installing LibrePCB, a program shortcut is created, but there Type = LibrePCB instead of Application and the shortcut is not displayed in the application menu.
b) UsbImager does not display characters when Russian is selected, but my system language is Russian UTF8. Other languages are displayed normally.
в) OpenSCAD doesn't work after installation
```
pi@raspberrypi:~ $ OpenSCAD.AppImage
bash: OpenSCAD.AppImage: команда не найдена
(command not found)
pi@raspberrypi:~ $ bash -c 'sudo modprobe fuse; ~/OpenSCAD.AppImage'
bash: строка 1: 17189 Ошибка сегментирования ~/OpenSCAD.AppImage
(Segmentation error)
pi@raspberrypi:~ $
```

**Comment by Botspot** [comment]
> Tried running some applications on my Pi and got some errors in the process. RaspiOS 32bit Debian 10, tested on a clean, updated system.

Thank you for letting us know.

> a) When installing LibrePCB, a program shortcut is created, but there Type = LibrePCB instead of Application and the shortcut is not displayed in the application menu.

That's strange. I'll upload the fixed program shortcut soon.

> b) UsbImager does not display characters when Russian is selected, but my system language is Russian UTF8. Other languages are displayed normally.

Try opening an issue on [the usbimager repository](https://bztsrc.gitlab.io/usbimager/).

> в) OpenSCAD doesn't work after installation
> ```
> pi@raspberrypi:~ $ OpenSCAD.AppImage
> bash: OpenSCAD.AppImage: команда не найдена
> (command not found)
> pi@raspberrypi:~ $ bash -c 'sudo modprobe fuse; ~/OpenSCAD.AppImage'
> bash: строка 1: 17189 Ошибка сегментирования ~/OpenSCAD.AppImage
> (Segmentation error)
> pi@raspberrypi:~ $
> ```

That's strange, because it used to work. I was able to repeat the error, and found that using the [latest release](https://github.com/koendv/openscad-raspberrypi/releases/tag/v1.7) solved the problem. I will upload the changes soon.

> г) Eagle CAD won't launch.
> 
> ```
> pi@raspberrypi:~ $ eagle
> Box86 with Dynarec v0.2.3 b5623128 built on Nov  7 2021 00:05:16
> Error: PltReolver: Symbol CRYPTO_num_locks(ver 0: CRYPTO_num_locks) not found, cannot apply R_386_JMP_SLOT 0x9ab3aa8 (0x807ccb6) in /usr/local/bin/eagle
> pi@raspberrypi:~ $ 
> ```

Try installing the `libssl1.0-dev` package.

> д) BleachBit installs and works, but an error occurs with the shortcut.
> 
> ```
> Package installation complete.
> sed: can't read /usr/share/applications/bleachbit-root.desktop: No such file or directory
> Failed to move BleachBit to Accessories category.
> ```

Updating pi-apps should solve this issue - we [solved](https://github.com/Botspot/pi-apps/commit/5be2b40463380fb28ecef07c5625db9be8f2fb20) this issue yesterday.

> *I wanted to submit it through a bug-form, but when creating it, an error 400 occurs.

Yes, we are currently re-writing the issue forms. This should be solved soon.

**Comment by Rak1ta** [comment]
@Botspot 
> Try installing the libssl1.0-dev package.

Then many packages will be removed, including programs from Pi-Apps (OBS, PrusaSlicer)
**upd.** Installed this package libssl1.0-dev. Eagle is up and running. Installed another app from Pi-Apps that has packages conflicting with libssl1.0-dev.

**Comment by Rak1ta** [comment]
@Botspot [gitlab-issue](https://gitlab.com/bztsrc/usbimager/-/issues/68) The GTK version renders the font correctly. Is it possible to add the ability to choose which version to install when installing from Pi-Apps?

**Comment by theofficialgman** [comment]
> @Botspot click ->[gitlab-issue](https://gitlab.com/bztsrc/usbimager/-/issues/68) The GTK version renders the font correctly. Is it possible to add the ability to choose which version to install when installing from Pi-Apps?

this is not an option currently as the GTK+ version is only available on armhf through a deb format and not provided for arm64

**Comment by theofficialgman** [comment]
GTK3 version is now used for armhf and arm64

**Comment by theofficialgman** [comment]
I already built the GTK3 version in june and put it on pi-apps. The X11 version is no longer used.
It has been fixed since then, no need for rebuilds from upstream
