### ISSUE TITLE
APT App PHP

### ISSUE THREAD

**Issue by 1Spinne** [Botspot/pi-apps#1232]
### What is the name of the app?

PHP

### About the app

It`s PHP as we all know it

### Upload file

[PHP.zip](https://github.com/Botspot/pi-apps/files/7639429/PHP.zip)

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by Botspot** [comment]
I'm not sure if this app is something many desktop users would use.
See: https://github.com/Botspot/pi-apps/issues/185

**Comment by 1Spinne** [comment]
Yeah ok

**Comment by 1Spinne** [comment]
I didnt think of it
