### ISSUE TITLE
Minecraft Java (aka Lunar Client) not working

### ISSUE THREAD

**Issue by Pythonic456** [Botspot/pi-apps#1236]
Error from Launcher:
```
Lunar Client Launch Error
Short: Java invoke error
Description: Failed to invoke Java: Error: spawn /opt/jdk/jdk1.8.0_251/jre/bin/java ENOENT
Launcher ID: 307f7b0a96b4ce344133b35120a6c57d71bc83b05d2a3711a9a8e313bb3d7c43
Launcher Version: 2.8.0
OS: linux arm
Game Version: 1.8/master
Launch Type: OFFLINE
```
Not sure since when this has started happening, haven't been using LC that much.

**Comment by Pythonic456** [comment]
Ah. The file doesn't seem to exist. Not sure why though.

**Comment by Pythonic456** [comment]
I manually copied the java file there, it was only up one directory level, and still doesn't work unfortunately. 
Logs below:
[main.log](https://github.com/Botspot/pi-apps/files/7641343/main.log)
[renderer.log](https://github.com/Botspot/pi-apps/files/7641344/renderer.log)
[renderer.old.log](https://github.com/Botspot/pi-apps/files/7641345/renderer.old.log)

**Comment by xFxre** [comment]
I have been having the same issue. @Botspot does the launcher need an update?

**Comment by Botspot** [comment]
This seems to fix it:
```bash
wget https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.1%2B12/OpenJDK17U-jdk_arm_linux_hotspot_17.0.1_12.tar.gz
sudo tar -zxf OpenJDK17U-jdk_arm_linux_hotspot_17.0.1_12.tar.gz -C /opt/jdk
```
We originally had those commands in the script - not sure why they got removed.
