### ISSUE TITLE
Add a changelog

### ISSUE THREAD

**Issue by 1Spinne** [Botspot/pi-apps#1240]
### Cool ideas?

Can you add a changelogs, so that an app update must have a changelog?

**Comment by ryanfortner** [comment]
@1Spinne there is already a change log here: https://github.com/Botspot/pi-apps/blob/master/CHANGELOG.md, did you mean a change log for each specific app?

**Comment by 1Spinne** [comment]
Yes, i mean for every app

**Comment by mobilegmYT** [comment]
> Yes, i mean for every app

A changelog for every app? I feel like you could just read the commits for each app update, having to also write to the app itself's changelog everytime someone updates it would be a insane amount of extra effort that barely anyone would read.

**Comment by 1Spinne** [comment]
not botspot must write the changelog but the app creators.
And it could be voluntary

**Comment by mobilegmYT** [comment]
> not botspot must write the changelog but the app creators. And it could be voluntary

Still feels like lots of extra effort for not much in return, why don't you just read the commit messages? They describe the change and also you could peek inside if you don't understand the message.

**Comment by 1Spinne** [comment]
ok
