### ISSUE TITLE
Mineshaft Preview

### ISSUE THREAD

**Issue by leha-code** [Botspot/pi-apps#1242]
### What is the name of the app?

Mineshaft

### (Optional) Where is the app hosted?

https://sourceforge.net/project/mineshaft2d

### About the app

Attempt to recreate Minecraft in 2D

### Upload file

[z.zip](https://github.com/Botspot/pi-apps/files/7655068/z.zip)

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by mobilegmYT** [comment]
> ### What is the name of the app?
> Mineshaft
> 
> ### (Optional) Where is the app hosted?
> https://sourceforge.net/project/mineshaft2d
> 
> ### About the app
> Attempt to recreate Minecraft in 2D
> 
> ### Upload file
> [z.zip](https://github.com/Botspot/pi-apps/files/7655068/z.zip)
> 
> ### Confirmations
> * [x]  I have confirmed that this app is legal and not piracy.
> * [x]  I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
> * [x]  I have confirmed that this app can run on Raspberry Pi.

The game doesn't even run for me:
```
Traceback (most recent call last):
  File "C:\Users\Mike\Downloads\ms-041221\Mineshaft-game-Mineshaft-eeb2fae\main.py", line 163, in <module>
    from render import Engine
ImportError: cannot import name 'Engine' from 'render' (unknown location)
```

The render folder is empty

**Comment by leha-code** [comment]
Hey, the script does not use the source forge version, and you did not initialize sub modules, run `git submodule init && git submodule update`

**Comment by leha-code** [comment]
I will fix the source forge version later

**Comment by leha-code** [comment]
The title of this issue clearly states that this is a preview version of Mineshaft, it is cloned from github,  not the releases page of sourceforge

**Comment by leha-code** [comment]
[mspreview.zip](https://github.com/Botspot/pi-apps/files/7656813/mspreview.zip)



Fixed, the previous zip was cursed

**Comment by mobilegmYT** [comment]
Well at least it works now.. but also the game doesn't appear to be finished, it crashes when I try to start the game because libmineshaft is missing.

**Comment by leha-code** [comment]
> Well at least it works now.. but also the game doesn't appear to be finished, it crashes when I try to start the game because libmineshaft is missing.

This is because you did not install the requirements.

**Comment by mobilegmYT** [comment]
> > Well at least it works now.. but also the game doesn't appear to be finished, it crashes when I try to start the game because libmineshaft is missing.
> 
> This is because you did not install the requirements.

I have libmineshaft installed from pip

```
RenderMite v[unknown]
  File "/home/mike/Mineshaft/main.py", line 410, in <module>
    game = Mineshaft()  # create an instance of the game
  File "/home/mike/Mineshaft/main.py", line 230, in __init__
    self._menu_init(WIDTH, HEIGHT)  # initialize the menu
  File "/home/mike/Mineshaft/main.py", line 276, in _menu_init
    self.menu = pygame_menu.Menu(  # set up the menu
  File "/home/mike/.local/lib/python3.9/site-packages/pygame_menu/menu.py", line 357, in __init__
    self._sound = Sound()
  File "/home/mike/.local/lib/python3.9/site-packages/pygame_menu/sound.py", line 203, in __init__
    warn('sound error: ' + str(e))
/home/mike/.local/lib/python3.9/site-packages/pygame_menu/sound.py:203: UserWarning: sound error: No such device.
  warn('sound error: ' + str(e))
Traceback (most recent call last):
  File "/home/mike/Mineshaft/main.py", line 415, in <module>
    game.update_game()  # update the game
  File "/home/mike/Mineshaft/main.py", line 384, in update_game
    self.menu.update(
  File "/home/mike/.local/lib/python3.9/site-packages/pygame_menu/menu.py", line 2439, in update
    selected_widget.update(events):
  File "/home/mike/.local/lib/python3.9/site-packages/pygame_menu/widgets/widget/button.py", line 231, in update
    self.apply()
  File "/home/mike/.local/lib/python3.9/site-packages/pygame_menu/widgets/core/widget.py", line 1260, in apply
    return self._onreturn(*args, **self._kwargs)
  File "/home/mike/Mineshaft/main.py", line 359, in _menu_singleplayer
    self.world = gen.generateWorld()
  File "/home/mike/Mineshaft/gen/__init__.py", line 61, in generateWorld
    world = generateBlankWorld()
  File "/home/mike/Mineshaft/gen/__init__.py", line 56, in generateBlankWorld
    world = libmineshaft.world.World(world=world_list)
NameError: name 'libmineshaft' is not defined
```

**Comment by leha-code** [comment]
> The

You should use the install script. It works with the install script.

**Comment by mobilegmYT** [comment]
> > The
> 
> You should use the install script. It works with the install script.

I did use the install script.

**Comment by theofficialgman** [comment]
https://github.com/Mineshaft-game/Mineshaft
posting the link to the github here since I find sourceforge unintuitive

**Comment by theofficialgman** [comment]
I think this should wait till the game is more finalized
at which point a 
```
pip install mineshaft2d
```
will be all thats necessary

**Comment by leha-code** [comment]
> I think this should wait till the game is more finalized/stable/free of bugs at which point a
> 
> ```
> pip install mineshaft2d
> ```
> 
> will be all thats necessary

This package is a dummy package actually. Mineshaft will not be distributed through pip.

**Comment by leha-code** [comment]
> > > The
> > 
> > 
> > You should use the install script. It works with the install script.
> 
> I did use the install script.

If you click "Start game" it's currently supposed to crash. I would make it a basic game already if it did not reqire a lot of stuff I don't want to rewrite later for. You won't understand this since you're no real coder.

**Comment by leha-code** [comment]
Anyways, closing temporarily, until I have a basic game

**Comment by mobilegmYT** [comment]
> You won't understand this since you're no real coder.

This is the kind of passive-aggressive behavior that got you banned from MCPI Revival and could get you banned from Botspot Software.
