### ISSUE TITLE
Droidbuddy

### ISSUE THREAD

**Issue by Botspot** [Botspot/pi-apps#125]
An easy way to control your Android device from a Linux PC.
https://github.com/gaz-github/droidbuddy

**Comment by Botspot** [comment]
```git clone https://gitlab.com/gazlene/droidbuddy
git clone https://github.com/Genymobile/scrcpy
sudo apt install python3-pip python3-tk ffmpeg libsdl2-2.0-0 gcc git pkg-config meson ninja-build libavcodec-dev libavformat-dev libavutil-dev libsdl2-dev openjdk-8-jdk
sudo pip3 install Pillow
cd scrcpy
meson x --buildtype release --strip -Db_lto=true
ninja -Cx
sudo ninja -Cx install
cd ../droidbuddy
python3 main.py```

**Comment by Itai-Nelken** [comment]
@Botspot is someone already working on the script or can I create it?

**Comment by Botspot** [comment]
> @Botspot is someone already working on the script or can I create it?

I think @gazlene may be working on it. IDK.

**Comment by Botspot** [comment]
Raspberry Pi News and I are working on this.

**Comment by Botspot** [comment]
Any volunteers for testing? :)  
[AndroidBuddy.zip](https://github.com/Botspot/pi-apps/files/5752133/AndroidBuddy.zip)

**Comment by Botspot** [comment]
Added with commit 65e098770a0a6964b88b16d0dce273583365b4b3.
