### ISSUE TITLE
Minecraft server app

### ISSUE THREAD

**Issue by GYKgamer** [Botspot/pi-apps#1250]
Using the RPI you could create a Minecraft server which would be very easy and I will try to create an app to automate it.
The only problem I'll get is the server port and the port forwarding which they will have to do manually.

**Comment by GYKgamer** [comment]
also I forgot how to add a app request so sorry

**Comment by Crilum** [comment]
Wouldn't this be in the same category as XMRig? Servers are mostly Term based, right?

**Comment by GYKgamer** [comment]
Yep probably

**Comment by Crilum** [comment]
@Botspot It would be cool if you made make a category, or another app store like Pi-Apps for Power User apps such as this or XMRig.. I think a lot of users would find this helpful..

**Comment by GYKgamer** [comment]
Aren't categories already added?

**Comment by GYKgamer** [comment]
![Screenshot_20211207-234356_VNC Viewer](https://user-images.githubusercontent.com/41442793/145123141-79f374ae-1fa1-41c3-82cf-38ce7358bc35.jpg)

**Comment by GYKgamer** [comment]
[MinecraftServer.zip](https://github.com/Botspot/pi-apps/files/7672281/MinecraftServer.zip)
I've created something except Pi-apps doesn't want it to 1. install 2. show up

**Comment by Crilum** [comment]
@GYKgamer Yes, there are categories, but I was talking about creating another category for CLI apps.

**Comment by GYKgamer** [comment]
ah that makes sense but technically the minecraft server can be with gui (although there is no point in that so ig it would stay terminal only)

**Comment by GYKgamer** [comment]
> [MinecraftServer.zip](https://github.com/Botspot/pi-apps/files/7672281/MinecraftServer.zip) I've created something except Pi-apps doesn't want it to 1. install 2. show up

It shows up except as null

**Comment by Crilum** [comment]
@GYKgamer It probably would be easier for you to use `Create App`, `install64.sh` should be `install-64`, `Uninstall.sh` should be `uninstall`, and all the text files should have lower-case file-names. The `Create App` script in Pi-Apps Settings does all of this for you.

**Comment by GYKgamer** [comment]
Alright ill check it out

**Comment by GYKgamer** [comment]
The create app was pretty glitched to me so I just the changes you said

**Comment by Crilum** [comment]
Yeah, @Botspot there were some weird bugs in the `create-app` script, like the entire description became the app name.. (sort of)

**Comment by GYKgamer** [comment]
Yea that and text editor and opening for me (except for uninstall script)

**Comment by Crilum** [comment]
I have this, it still might not work.. But I made some changes to the script, and description:
[Minecraft Server.zip](https://github.com/Botspot/pi-apps/files/7672393/Minecraft.Server.zip)

**Comment by Crilum** [comment]
> Yea that and text editor not opening for me (except for uninstall script)

Yeah that happened too..

**Comment by GYKgamer** [comment]
> I have this, it still might not work.. But I made some changes to the script, and description: [Minecraft Server.zip](https://github.com/Botspot/pi-apps/files/7672393/Minecraft.Server.zip)

will check

**Comment by Crilum** [comment]
Thanks!

**Comment by GYKgamer** [comment]
Hmmm got an error. Ill check it

**Comment by GYKgamer** [comment]
Found the reason

**Comment by GYKgamer** [comment]
It installed into the /home/pi folder but my dumb head made one of the commands to /home/pi/Desktop

**Comment by GYKgamer** [comment]
Wait I found more errors.
It's not cd to desktop which is why it doesnt work

**Comment by Crilum** [comment]
oh, well, I think files should be put in a folder in the home folder, not on the Desktop :)

**Comment by GYKgamer** [comment]
well i broke it a second after buttttt
![image](https://user-images.githubusercontent.com/41442793/145142516-4073359e-52a7-48e7-8fbd-c13bce331480.png)
I did get it working

**Comment by GYKgamer** [comment]
Only problem left are that it's stuck on "Installing Minecraft Server" and also we would probably have to add a button so that the server would open (or the start.sh file I made)

**Comment by Crilum** [comment]
Yeah, I wouldn't run the Server right after installation, I'd echo something about testing the server first.. As for adding a menu button, that's easy:

Just add:
```
echo "[Desktop Entry]
Name=Minecraft Server
Comment=Run a Minecraft 1.17 Server over your local network
Exec=wherever start.sh is
Icon=$HOME/pi-apps/apps/"Minecraft Server"/icon-64.png
Terminal=false
StartupNotify=true
Type=Application
Categories=Games;"
```
to the end of the script.

**Comment by GYKgamer** [comment]
> 

should the "wherever start.sh is" be changes to home/pi/blablabla

**Comment by Crilum** [comment]
Yeah, if the Server folder which contains the `start.sh` file is `/home/pi/MinecraftServer/` then you would write `exec=$HOME/MinecraftServer/start.sh`

**Comment by theofficialgman** [comment]
I know this is still a work in progress and I see you have copied some of the code from my MultiMC5 install script.

Having the java-17 not work should not just be a warning for this script, it should be a fatal error (its a warning for multimc5 because multimc itself does not need java 17 to run).

I think the idea for this script is helpful but its not very useable as is. I'm thinking something better would be directing users to this site: https://mcversions.net/ to download a server jar file easily, that the script can pick up on.

Do you care if I make a draft PR for this with changes?

**Comment by theofficialgman** [comment]
Ok its not done but I wanted to push my changes just so you can see what I'm going for.
here is the draft PR: https://github.com/Botspot/pi-apps/pull/1259

**Comment by GYKgamer** [comment]
> I know this is still a work in progress and I see you have copied some of the code from my MultiMC5 install script.
> 
> Having the java-17 not work should not just be a warning for this script, it should be a fatal error (its a warning for multimc5 because multimc itself does not need java 17 to run).
> 
> I think the idea for this script is helpful but its not very useable as is. I'm thinking something better would be directing users to this site: https://mcversions.net/ to download a server jar file easily, that the script can pick up on.
> 
> Do you care if I make a draft PR for thi

> I know this is still a work in progress and I see you have copied some of the code from my MultiMC5 install script.
> 
> Having the java-17 not work should not just be a warning for this script, it should be a fatal error (its a warning for multimc5 because multimc itself does not need java 17 to run).
> 
> I think the idea for this script is helpful but its not very useable as is. I'm thinking something better would be directing users to this site: https://mcversions.net/ to download a server jar file easily, that the script can pick up on.
> 
> Do you care if I make a draft PR for this with changes?

Nope not at all, This would be better also since 1.18 is out and people might want early versions

**Comment by GYKgamer** [comment]
> Ok its not done but I wanted to push my changes just so you can see what I'm going for. here is the draft PR: #1259
> 
> some of the comments, website, etc need updating but I just wanted to get this pushed

I seen that and you've done a good job so far
