### ISSUE TITLE
eDEX-UI arm64

### ISSUE THREAD

**Issue by Itai-Nelken** [Botspot/pi-apps#126]
[install-64.zip](https://github.com/Botspot/pi-apps/files/5651306/install-64.zip)

**Comment by Itai-Nelken** [comment]
Downloads arm64 AppImage from official repo.
I don't have my pi with me, so someone with a 64bit OS needs to test it first.

**Comment by Itai-Nelken** [comment]
[install-64.zip](https://github.com/Botspot/pi-apps/files/5652739/install-64.zip)

a few fixes

**Comment by Itai-Nelken** [comment]
installs OK, but doesn't run (or takes longer than 5 minutes)

**Comment by Itai-Nelken** [comment]
I gave up waiting...

**Comment by Botspot** [comment]
> I gave up waiting...

What became of this? As Novaspirit Tech compiled the armhf appimages, maybe he could help with an arm64 build.

**Comment by Itai-Nelken** [comment]
> As Novaspirit Tech compiled the armhf appimages, maybe he could help with an arm64 build.

he could help, yes.
but there is a official arm64 build. I opened a issue in [the official repo](https://github.com/GitSquared/edex-ui/issues/944)

**Comment by Botspot** [comment]
We can re-open this issue when/if a build for arm64 is ever successfully released.
