### ISSUE TITLE
Add Inkscape

### ISSUE THREAD

**Issue by 1Spinne** [Botspot/pi-apps#1262]
### What is the name of the app?

Inkscape

### About the app

Inkscape is one of the best free vector graphics editor available for the Raspi

### Upload file

[Inkscape.zip](https://github.com/Botspot/pi-apps/files/7697409/Inkscape.zip)

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [x] I have confirmed that this app can run on Raspberry Pi.

**Comment by Botspot** [comment]
Inkscape has been added to pi-apps now.
