### ISSUE TITLE
Using deb packages for java 17

### ISSUE THREAD

**Issue by ryanfortner** [Botspot/pi-apps#1269]
### Cool ideas?

I saw that the [MultiMC script](https://github.com/Botspot/pi-apps/blob/master/apps/Minecraft%20Java%20MultiMC5/install) now uses temurin-17. Maybe we should use deb packages for it so that it's easily installable/uninstallable.

I have compiled deb files for both armhf and arm64 here: https://apt.raspbian-addons.org/debian/pool/main/t/temurin-17-hotspot/

What do you think @theofficialgman @Botspot ?

**Comment by theofficialgman** [comment]
I do not want that. I was personally told by a temurin developer that they are working on making a debian repo available for their packages. It is not released yet so I waiting on that.

**Comment by ryanfortner** [comment]
Good to know, thanks @theofficialgman.

**Comment by theofficialgman** [comment]
just to provide the proof for my claim: https://github.com/adoptium/adoptium-support/issues/368
the chairman of adoptium himself was the one who stated this
