### ISSUE TITLE
Timeshift fix (typo in description)

### ISSUE THREAD

**Issue by Itai-Nelken** [Botspot/pi-apps#127]
[Timeshift.zip](https://github.com/Botspot/pi-apps/files/5659053/Timeshift.zip)

**Comment by Botspot** [comment]
In this case, a zip will work, but if you only want to change the description, a PR would have worked too. ;)

**Comment by Itai-Nelken** [comment]
Well, I always forget they exist (pr's)

**Comment by Botspot** [comment]
Or you simply could have sent me the description directly in the body text of this issue.

Any of these options will work fine. Thanks for noticing the typo.

**Comment by Botspot** [comment]
Fixed with commit 5bfd15cc7aa324807c0b9eb1820ea97326778cba.
