### ISSUE TITLE
Zoom not starting on RPi 4

### ISSUE THREAD

**Issue by anantmishra** [Botspot/pi-apps#1271]
Zoom fails to start with the following error:

> Box86 with Dynarec v0.2.5 a1aac43a built on Dec 12 2021 00:07:09
zoom started.
Client: Breakpad is using Single Client Mode! client fd = -1
/home/pi/zoom/runzoom.sh: line 13: 31885 Segmentation fault      box86 zoom "$1"
Zoom exited. Close this terminal to exit

Hardware: RPi 4 B+ 2Gb
OS: Raspberry Pi OS (bullseye)

**Comment by Botspot** [comment]
I've been able to reproduce the problem on my end.
@Itai-Nelken, would removing the latest build from your repository force a downgrade on everybody's systems?

**Comment by Itai-Nelken** [comment]
> I've been able to reproduce the problem on my end.
> @Itai-Nelken, would removing the latest box86 build from your repository force a downgrade on everybody's systems?

Unfortunately no. But we can force apt to do that by holding the `box86` package and then installing box86 with the `package=version` syntax.

**Comment by Botspot** [comment]
> > I've been able to reproduce the problem on my end.
> > @Itai-Nelken, would removing the latest box86 build from your repository force a downgrade on everybody's systems?
> 
> Unfortunately no. But we can force apt to do that by holding the `box86` package and then installing box86 with the `package=version` syntax.

Could you copy last week's debfile and give it a higher version number so everyone will upgrade to a working box86 version?

**Comment by temporarium** [comment]
I've got the same issue with `Box86 with Dynarec v0.2.5 a1aac43a built on Dec 12 2021 00:07:09`

Downgraded to `Box86 with Dynarec v0.2.3 b5623128 built on Nov  7 2021 00:05:16`

Zoom works again.

**Comment by cycool29** [comment]
Was this issue reported to the box86 repository?

**Comment by temporarium** [comment]
> Was this issue reported to the box86 repository?

See above... https://github.com/ptitSeb/box86/issues/522

**Comment by temporarium** [comment]
Confirm that on the latest version of `Box86 with Dynarec v0.2.5 66332ae9 built on Dec 26 2021 00:07:16` Zoom is working OK.

**Comment by cycool29** [comment]
Yes, it works for me too.

**Comment by Itai-Nelken** [comment]
Good! I'll trigger a new build as soon as I'm home.

**Comment by Itai-Nelken** [comment]
A new build was uploaded a few hours ago. could someone test if it works with zoom?
if yes I'll force an update to zoom.

**Comment by temporarium** [comment]
`Box86 with Dynarec v0.2.5 430b24c0 built on Dec 28 2021 18:07:43` works for me.

**Comment by Itai-Nelken** [comment]
Good, that's the latest build I pushed.
I'll force a zoom update.

**Comment by anantmishra** [comment]
Thanks guys! I can confirm that its working for me.
