### ISSUE TITLE
Anydesk does not start

### ISSUE THREAD

**Issue by Rak1ta** [Botspot/pi-apps#1275]
RaspiOS 32bit Debian 10
It does not start for me, although one of the older versions **anydesk_2.9.4-1_armhf.deb** works correctly. 
sample > [Reddit](https://www.reddit.com/r/AnyDesk/comments/qw71e1/anydesk_on_raspberry_pi_4_b_not_loading_gui/) 
```
* failed to add service - already in use?
Gtk-Message: 20:35:18.485: Failed to load module "atk-bridge"
```

Tried a clean install of Raspbian, everything works.  If anyone knows how to fix this, thanks from me.

**Comment by Botspot** [comment]
> ```
> * failed to add service - already in use?
> ```

Perhaps that's because there's an anydesk process already running? To find out, run this command:
```
killall anydesk
```
If the output is silent, then anydesk was running (and you just killed it), but if the output says "no process found", then anydesk was not already running and that error message must mean something else.

I'm not a frequent AnyDesk user, so there's a limit to what I can help with. Perhaps try disabling the OpenGL driver? Or enabling it?

**Comment by Rak1ta** [comment]
> Perhaps try disabling the OpenGL driver? Or enabling it?

Recovered a copy of the raspbian disk image, recovered everything that was installed and anydesk was working.  I still did not understand why it did not work for me earlier.

**Comment by Crilum** [comment]
I think it has something to do with bullseye (AnyDesk), I get library errors:
```
$ anydesk
anydesk: error while loading shared libraries: libbrcmGLESv2.so: cannot open shared object file: No such file or directory
```

**Comment by Botspot** [comment]
> And it looks like `libbrcmGLESv2.so` is having trouble finding another library...

Solved with commit https://github.com/Botspot/pi-apps/commit/b4ddb959ec5f5a391f0c4d1c96bcc8bd86382965. AnyDesk now launches on Bullseye.

@Rak1ta, I'm confused: I thought this issue was about AnyDesk problems but now it looks like you've changed everything to talk about Geekbench?

**Comment by Rak1ta** [comment]
@Botspot Geekbench has created a separate topic so as not to get confused. Thanks!  On Debian 11, I can’t test the functionality, since I don’t use it.
