### ISSUE TITLE
Different update mechanism for Apps that relies on Github Releases?

### ISSUE THREAD

**Issue by touhidurrr** [Botspot/pi-apps#1284]
For Apps that relies on Github Releases the existing update mechanism in Pi-Apps feels inefficient in many ways. Using the Github API's directly is an Option. For example to update **Unciv** I use this script written by me, [gist link.](https://gist.github.com/touhidurrr/c36b978d6ac7f7a2dec0b94276834fc2)

What do you guys think, @theofficialgman @cycool29 @Itai-Nelken @Botspot ?

My suggestion is if some app has an `update` script than `Pi-Apps` will use it check for updates and update the app instead of running the install script again. We can do something like this.

Return Codes:

`-1` -> error
`0` -> no error, no update
`1` -> app updated

**Comment by Crilum** [comment]
>Return Codes:
`-1` -> error
`0` -> no error, no update
`1` -> app updated

I don't think that would work... `0` Is supposed to be success, or at least nothing went wrong, and `1` is an error..

**Comment by touhidurrr** [comment]
> > Return Codes:
> > `-1` -> error
> > `0` -> no error, no update
> > `1` -> app updated
> 
> I don't think that would work... `0` Is supposed to be success, or at least nothing went wrong, and `1` is an error..

Its an example attempt of explaining how an `update` script would work. Obviously, open to suggestions. You can suggest a better behaviour if you want. I chose these status codes thinking the following ...
`-1` => `Negative Integer` => `Something went wrong.`
` 0` => `Neither Poistive nor Negative`  => `Nothing happend. No error, no update.`
` 1` => `Positive Integer` => `Process Successful. The app was updated properly.`
This way it is easy to remember.

If you don't like that, than it would be better if you make a draft of `update` script behaviour and possible `status` codes the update script should return and post it here. That way we can take a better look at your thoughts.

**Comment by Crilum** [comment]
See #1019 for my script.. The script would just exit with normal exit codes, `0` for success, `1` for failure, but it's pretty informative, so it would let you know what was happening...

**Comment by touhidurrr** [comment]
Thats what everyone is doing already, though.

**Comment by Crilum** [comment]
> Thats what everyone is doing already, though.

Yeah, but I don't want to confuse people who are used to normal exit codes..

**Comment by touhidurrr** [comment]
> > Thats what everyone is doing already, though.
> 
> Yeah, but I don't want to confuse people who are used to normal exit codes.. But, feel free to take it and change it however you like!

That would be the Job of @Botspot I think. Who haven't showed up in this convo yet.

**Comment by theofficialgman** [comment]
closed with github actions update script PR https://github.com/Botspot/pi-apps/pull/1330

**Comment by touhidurrr** [comment]
> closed with github actions update script PR https://github.com/Botspot/pi-apps/pull/1330

I don't think that’s what the issue was about.
It was about custom update scripts on client side not server side.
Writing this for documentation.

**Comment by theofficialgman** [comment]
I will note: a similar discussion was already had in https://github.com/Botspot/pi-apps/issues/1019 which lead to PR #1330
in particular "It was about custom update scripts on client side not server side." was ruled out in the above issue and can be read about there.

any future discussion about topics similar to this should be had in https://github.com/Botspot/pi-apps/issues/1019 which will be kept open
