### ISSUE TITLE
Pi-Apps take lag in Kali arm64

### ISSUE THREAD

**Issue by KhanhNguyen9872** [Botspot/pi-apps#1288]
![Screenshot_20211221-130438](https://user-images.githubusercontent.com/88880309/146879823-3b8cb7b0-a7d3-49bb-b6ba-9f34cd699bff.png)

after i turned it on, about 10 seconds later my computer gradually lagged, and then my computer froze, forced to turn it off and on again
Please fix it! Thanks!

**Comment by Itai-Nelken** [comment]
Probably a slow sd card.
Pi-apps does a lot of file I/O (input/output), so using it on slow sd cards will slow the whole system down.

**Comment by KhanhNguyen9872** [comment]
> Probably a slow sd card. Pi-apps does a lot of file I/O (input/output), so using it on slow sd cards will slow the whole system down.

my storage is UFS 2.1

**Comment by theofficialgman** [comment]
I suggest looking at your system for corruption.
this is not a pi-apps issue.
Closing
