### ISSUE TITLE
Lunar Client (Failed to invoke Java)

### ISSUE THREAD

**Issue by AwesomeAurick** [Botspot/pi-apps#1290]
Lunar Client Launch Error
Short: Java launch fail
Description: Lunar Client has failed to launch. A report has been automatically submitted.
Launcher ID: 2e015aea6237cb06ce180db88e0e4d3ba3a570e5847e763cec5fa67e99e2c8cd
Launcher Version: 2.8.0
OS: linux arm64
Game Version: 1.8/master
Launch Type: OFFLINE

I get this error launching minecraft java 1.8.9 on lunar client raspian 64bit

I found this simular issue but it did not work: https://github.com/Botspot/pi-apps/issues/1236

I tried allocating 2gb and 4gb both does not work
I tried reinstalling java 8 and java 11.
I tried Updating pi-apps and reinstall Minecraft Launcher

Please help

**Comment by TheSimonLam** [comment]
I'm also getting the same issue:

Failed to launch Lunar Client
Java invoke error
Failed to invoke Java: Error: spawn /opt/jdk/jdk-17.0.1+12/bin/java ENOENT

I suspect Lunar Client must have been updated along with the required Java version and may need updating in PiApps config files too?

**Comment by AwesomeAurick** [comment]
Hi I just installed Lunar Client on a fresh install of raspian 32 bit it works for 1.8.9 but after reboot it stuck on loading screen

**Comment by mobilegmYT** [comment]
try multimc

**Comment by Botspot** [comment]
I'm currently investigating the problem in a virtual machine.

**Comment by Botspot** [comment]
> Failed to launch Lunar Client Java invoke error Failed to invoke Java: Error: spawn /opt/jdk/jdk-17.0.1+12/bin/java ENOENT

Can someone try running this command?
```
file /opt/jdk/jdk-17.0.1+12/bin/java
```
In my VM, that file exists, but the ENOENT error indicates a missing file.

**Comment by DaFFiK320** [comment]
Does not work for me

**Comment by AwesomeAurick** [comment]
Hi just an update, multimc works on raspian 64bit for 1.8.9.

**Comment by gl91306** [comment]
> try multimc

lmao

**Comment by Botspot** [comment]
MultiMC5 has received a few script improvements in the past two weeks and should not run fine.
Please open a new issue if the issue still persists after updating Pi-Apps.
