### ISSUE TITLE
Themes / Light and Dark Mode

### ISSUE THREAD

**Issue by TurquoiseTNT** [Botspot/pi-apps#1295]
### Cool ideas?

Hey Botspot and Devs!
I know you guys are most probably busy but I was wondering if you might add a dark mode or even a theming system to Pi-Apps?
If You Do Choose a Theming system then I would be more then happy to get a dark mode theme running (as long as it's not to hard to code).
Thanks,  - Seb from TurquoiseTNT

**Comment by cycool29** [comment]
You can change pi-apps theme from Pi-Apps Settings (App List Style). Access it from Menu -> Preference -> Pi Apps Settings.

![image](https://user-images.githubusercontent.com/88134003/147052849-905b8bbb-f48d-4c58-87de-e15aa5a817c4.png)


The dark theme looks like this:

![image](https://user-images.githubusercontent.com/88134003/147052945-119ba5d1-c9ce-4512-8eaf-c18029324182.png)

**Comment by TurquoiseTNT** [comment]
Sorry, I did not realise that the setting was accessible as a separate app
not from the pi apps GUI. Sorry about that.

**Comment by Botspot** [comment]
> Sorry, I did not realise that the setting was accessible as a separate app not from the pi apps GUI. Sorry about that.

No worries. Future users will find this issue and be helped by it.

**Comment by TurquoiseTNT** [comment]
Good to Hear!
Have a Merry Christmas @Botspot @cycool29!
