### ISSUE TITLE
PrusaSlicer update

### ISSUE THREAD

**Issue by Crilum** [Botspot/pi-apps#1296]
### Cool ideas?

So, PrusaSlicer has just had their `2.4.0` release, and so I went to make a PR to update the download link, but then I saw that the install script uses different builds. 
Why do we use 3rd party builds, when Prusa already provides `armv7l` and `aarch64` AppImages? 

Also, @davidk has released a `2.4.0-rc2` build, so if we're sticking to those builds, then PrusaSlicer still needs to be updated.. :+1:

I can make a PR if I know which build to use..

**Comment by Crilum** [comment]
Also, in his releases, @davidk said:
>Prusa Research has officially begun releasing their own AppImages for ARM. It is advisable to switch to these official builds going forward.

So, I think we should switch to those..

**Comment by Botspot** [comment]
> > _Prusa Research has officially begun releasing their own AppImages for ARM. It is advisable to switch to these official builds going forward._
> 
> So, I think we should switch to those..

I looked at the official PrusaSlicer [release](https://github.com/prusa3d/PrusaSlicer/releases/tag/version_2.4.0-rc2) and while it has an armv7l release, it is missing aarch64 releases.

@Crilum, perhaps it's best to wait until official 32-bit and 64-bit ARM appimages are released, before switching to them? This would reduce confusion.

**Comment by davidk** [comment]
Hello,
PrusaSlicer has released a final [2.4.0](https://github.com/prusa3d/PrusaSlicer/releases/tag/version_2.4.0) which includes both [aarch64](https://github.com/prusa3d/PrusaSlicer/releases/download/version_2.4.0/PrusaSlicer-2.4.0+linux-aarch64-202112211915.AppImage) and [arm7l](https://github.com/prusa3d/PrusaSlicer/releases/download/version_2.4.0/PrusaSlicer-2.4.0+linux-armv7l-202112220001.AppImage) AppImages.

aarch64 was dropped from the subsequent release candidates after being introduced in beta4, but they are back in the final release now.

**Comment by Botspot** [comment]
@davidk, thank you for clarifying.

PrusaSlicer has now [been updated](https://github.com/Botspot/pi-apps/commit/48dfb0f0ecdb8c21e4e5513e1e77dcc54c1285f4) to use the official releases.
