### ISSUE TITLE
Icons Upload

### ISSUE THREAD

**Issue by TurquoiseTNT** [Botspot/pi-apps#1299]
### Cool ideas?

Use This Post to Give Ideas of Icons / Images for Use In Pi-Apps

**Comment by TurquoiseTNT** [comment]
![splashscreen](https://user-images.githubusercontent.com/69688534/147338726-4f23a32a-0eb1-41d9-9baf-df0e4d76ad5c.png)
Here is My Version of the Splashscreen!

**Comment by Crilum** [comment]
> ![splashscreen](https://user-images.githubusercontent.com/69688534/147338726-4f23a32a-0eb1-41d9-9baf-df0e4d76ad5c.png) Here is My Version of the Splashscreen!

Yeah, that's awesome! Maybe we could have a different theme for it though, cause I like the current one, too..

**Comment by TurquoiseTNT** [comment]
A way to make it work would be to set a variable in the app and then set it
so when it tries to load the splash screen the variable is actually a
folder at the same time and therefore loads it like this:
pi-apps/{variable/theme}/icons/splashscreen.png

**Comment by theofficialgman** [comment]
honestly you know what would be actually really cool
if the logo was dynamic and changed each time based on the icons supplied in pi-apps already, so a random selection of 6-10 apps made up the logo background on each launch. the next launch logo could be made asynchronously for the next launch so this feature wouldn't add extra launch time even if it takes a few seconds to run this generation

**Comment by TurquoiseTNT** [comment]
Its a Good Idea but what if someone wanted only 1 or 2 Splashscreens on their instance < Sent via Mail > From: theofficialgmanSent: 27 December 2021 02:24To: Botspot/pi-appsCc: TurquoiseTNT; AuthorSubject: Re: [Botspot/pi-apps] Icons Upload (Issue #1299) honestly you know what would be actually really coolif the logo was dynamic and changed each time based on the icons supplied in pi-apps already, so a random selection of 6-10 apps made up the logo background on each launch. the next launch logo could be made asynchronously for the next launch so this feature wouldn't add extra launch time even if it takes a few seconds to run this generation—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by Botspot** [comment]
> honestly you know what would be actually really cool if the logo was dynamic and changed each time based on the icons supplied in pi-apps already, so a random selection of 6-10 apps made up the logo background on each launch. the next launch logo could be made asynchronously for the next launch so this feature wouldn't add extra launch time even if it takes a few seconds to run this generation

Fascinating idea. My first thought would be to generate a svg image based on a template.
I just created a simple svg file. (using Boxy SVG) It's a text box and an embedded image. When you open it in a text editor, the embedded image is encoded in base64. Using `sed`, I was able to replace the base64 data with the encoded data of another image. Basically, I replaced one image with another from the terminal.
Before:
![before-base64](https://user-images.githubusercontent.com/54716352/147501577-6b867e4d-13e1-49db-bcd0-cf3435ed9c07.png)
After:
![after-base64](https://user-images.githubusercontent.com/54716352/147501575-5e85ebb6-5e94-48a3-8a4d-f35f4b77518a.png)
Command I used to do the replacement:
sed -i 's_xlink:href="data:image/png;base64,.*"_xlink:href="data:image/png;base64,'"$(base64 /home/pi/pi-apps/icons/in-progress.png -w 0)"'"_' /home/pi/pi-apps/splash.svg

**Comment by TurquoiseTNT** [comment]
Cool! Nice work. An Easy Implication As well! Loving it!

**Comment by Crilum** [comment]
@theofficialgman That would be so cool!

@Botspot To rotate some App Icons like in @TurquoiseTNT's splash, ImageMagick could definitly be used as well.

**Comment by Botspot** [comment]
Dynamically-generated splash screen has been added.

To see the changes, update Pi-Apps, then launch the gui. You will still see the old splash screen one last time. Wait 10 seconds before closing the gui, then launch Pi-Apps again. Now the splash screen should look something like:
![splashscreen 2](https://user-images.githubusercontent.com/54716352/147864430-8d128616-7bfd-41f9-92fd-845788495c3f.png)
(Of course, it will look different on your system, each time you launch Pi-Apps.)
