### ISSUE TITLE
[App] RPI Imager

### ISSUE THREAD

**Issue by mobilegmYT** [Botspot/pi-apps#13]
[RPI Imager.zip](https://github.com/Botspot/pi-apps/files/5322182/RPI.Imager.zip)

**Comment by Botspot** [comment]
This is probably ineligible, as RPI Imager is already in the repositories:

    sudo apt install -y rpi-imager

**Comment by mobilegmYT** [comment]
Oop

**Comment by Botspot** [comment]
PS if you want TwisterOS added to a flash utility, then maybe you'd like to add it to Pi-Power-Tools' `mirrors` file?
https://github.com/Botspot/Pi-Power-Tools/blob/master/data/mirrors
