### ISSUE TITLE
Autostart any app

### ISSUE THREAD

**Issue by actraiser30** [Botspot/pi-apps#1307]
### Cool ideas?

Hello.is it possible to add the option after an installation of an app/game to give you the option to autostart it?
and give you the possibility to select yes or no
To start it on boot i mean for example the minecraft server after the installation is finished the piapps installer to ask if you want to start it on boot

thank you

**Comment by Botspot** [comment]
For autostarting any app, see my Autostar app.
For the Minecraft Server app in particular, perhaps the install script can ask the user if they want an autostart entry created.

**Comment by actraiser30** [comment]
I tried a while ago your autostart app, didn't work.thats why im asking,if
its possible for everything to get an autostart configuration.

Στις Δευ, 27 Δεκ 2021, 21:08 ο χρήστης Botspot ***@***.***>
έγραψε:

**Comment by theofficialgman** [comment]
@actraiser30 the `minecraft-server` app has been reworked and was merged yesterday. It now natively supports autostarting and safe shutdown (if the service is enabled). Please install the latest release and read the app description for instructions

**Comment by theofficialgman** [comment]
and more in general, many DEs have a "Startup Applications Preferences" app that simply adds any app to startup that the user chooses. the one gnome/budgie can be installed with `sudo apt install gnome-startup-applications` and you run it startup applications in the menu or from `gnome-session-properties` in terminal
