### ISSUE TITLE
App Request for mi unlock tool

### ISSUE THREAD

**Issue by JeromTWinL** [Botspot/pi-apps#1310]
### What is the name of the app?

Mi Unlock Tool

### (Optional) Where is the app hosted?

https://github.com/JeromTWinL/MiUnlockTool

### About the app

MI Unlock tool helps to unlock a mi phone without root.

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by Itai-Nelken** [comment]
Sorry for being suspicious, but the install script looks slightly weird.
It downloads a .jar file and extracts it to a shell script.
Could someone take a look please @Botspot @theofficialgman @cycool29

**Comment by Botspot** [comment]
I looked at the script and saw that it's downloading a zip file from Google Drive.
Using Google Drive for file-hosting is frowned upon due to lack of transparency. It's not exactly private either, and to illustrate that, @JeromTWinL I now know your email address.
![Screenshot from 2021-12-27 14-59-23](https://user-images.githubusercontent.com/54716352/147506836-7f154054-b47e-4141-b331-4ae4a3c5bb47.png)

**Comment by cycool29** [comment]
The JAR file is not working.

![image](https://user-images.githubusercontent.com/88134003/147519366-6b5336fd-d00f-4838-b207-4d5410d46272.png)

I found [something similar](https://www.xiaomitool.com/MiUnlockTool), not working too:

![image](https://user-images.githubusercontent.com/88134003/147519619-03fcefe5-e568-4f9a-bc84-1314fd93c9be.png)


Also, @Botspot I think you need to update the pi-apps wiki, especially the `Creating an app for pi-apps` section. It is *very* outdated.

**Comment by JeromTWinL** [comment]
@cycool29 fid you installed correctly?

**Comment by JeromTWinL** [comment]
Sorry, i need to fix that.

**Comment by cycool29** [comment]
I just download the JAR file and execute with `java -jar ./[the jar file}`.

**Comment by JeromTWinL** [comment]
No, it requires `sudo` to execute fastboot (mentioned in the Official Website).

**Comment by JeromTWinL** [comment]
@cycool29 your comment:


> The JAR file is not working.
> 
> ![image](https://user-images.githubusercontent.com/88134003/147519366-6b5336fd-d00f-4838-b207-4d5410d46272.png)
> 
> I found [something similar](https://www.xiaomitool.com/MiUnlockTool), not working too:
> 
> ![image](https://user-images.githubusercontent.com/88134003/147519619-03fcefe5-e568-4f9a-bc84-1314fd93c9be.png)
> 
> Also, @Botspot I think you need to update the pi-apps wiki, especially the `Creating an app for pi-apps` section. It is _very_ outdated.

That's why I am gonna test it again.

**Comment by cycool29** [comment]
Can I know where is the official website?

**Comment by JeromTWinL** [comment]
https://www.xiaomitool.com/V2/

**Comment by cycool29** [comment]
I just compile it from [source](https://github.com/francescotescari/XiaoMiToolV2) and it worked!

**Comment by JeromTWinL** [comment]
What are the commands did u execute?

**Comment by cycool29** [comment]
> What are the commands did u execute?

```bash
git clone https://github.com/francescotescari/XiaoMiToolV2 -b linux
cd XiaoMiToolV2
./gradlew build
./gradlew run
```

**Comment by JeromTWinL** [comment]
I saw your comment after 2 hours and i started building before 15 minutes, and it failed now

**Comment by cycool29** [comment]
Can you post the error output?

**Comment by JeromTWinL** [comment]
Wait

**Comment by JeromTWinL** [comment]
Sorry, i closed it

**Comment by cycool29** [comment]
Just build it again.

**Comment by JeromTWinL** [comment]
Ok
But it will take noo long time (15 min)

**Comment by JeromTWinL** [comment]
here, the error report (it just failed in 21s, cuz now it did'nt downloaded):

Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* What went wrong:
java.lang.UnsupportedClassVersionError: org/openjfx/gradle/JavaFXPlugin has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
> org/openjfx/gradle/JavaFXPlugin has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 21s

**Comment by cycool29** [comment]
Seems like your Java is outdated.

Try `sudo apt install openjdk-11-jdk` and build again.

**Comment by JeromTWinL** [comment]
Build Done and execution also

**Comment by JeromTWinL** [comment]
Now, can you add this app to pi-apps (Updated Build Scripts in Git repo)

https://github.com/JeromTWinL/MiUnlockTool

**Comment by cycool29** [comment]
You don't need to host the install and uninstall script. Just make a PR on pi-apps repo.

**Comment by theofficialgman** [comment]
```
sudo apt update && sudo apt install openjfx nautilus android-tools-adb android-tools-fastboot openjdk-11-jdk -y || exit 1

echo "Downloading MiUnlockTool..."
git clone https://github.com/francescotescari/XiaoMiToolV2 -b linux || error "Failed to clone git repository!"
cd XiaoMiToolV2
echo "Build Unlock Tool..."
./gradlew build || error "Failed to build XiaoMiToolV2!"
```
there will be problems with this if the user already has openjdk-11 installed
its possible for java 8 or some other lower version to be the default java, which gradle will then use and will fail (as seen before when it tried to build on java 8)

since you install the openjdk-11-jdk, you should set the JAVA_HOME variable to that version before running gradle to guarantee using that openjdk-11-jdk, to be save and avoid errors

**Comment by theofficialgman** [comment]
> > you should just be able to run gradle like JAVA_HOME=/usr/lib/jvm/java-11-openjdk-arm* ./gradlew build
> 
> No, it won't work. You need to set the `PATH` variable, and move the link in `/usr/bin` to anywhere not in `PATH` temporarily.
> 
> ```shell
> sudo mv /usr/bin/java /tmp 
> JAVA_HOME="$(dirname $(dirname $(update-alternatives --list java | grep "openjdk" | grep 11 --color=none)))"
> ORIGINAL_PATH="$PATH"
> PATH="$(echo $PATH | tr ':' '\n' | grep -v openjdk | tr '\n' ':')$JAVA_HOME/bin"
> ./gradlew build
> sudo mv /tmp/java /usr/bin
> PATH="$ORIGINAL_PATH"
> ```
@cycool29 
umm, WHAT? no no no, why would you ever do that. its just using the JAVA_HOME variable for building, thats it
gradlew has functionality builtin for reading the JAVA_HOME variable, see right here https://github.com/francescotescari/XiaoMiToolV2/blob/a335da6bb812272d68d6842ff88c4b7552465cc4/gradlew#L86
what I said has always worked for me
