### ISSUE TITLE
Spotify Compatibility

### ISSUE THREAD

**Issue by Arohan-Senroy** [Botspot/pi-apps#1311]
It will be really cool if you could make an app somewhat similar to Spotify.
Thanks

**Comment by Crilum** [comment]
See #1108, Spotify clients as well as the official Spotify Desktop app are talked about.

**Comment by Arohan-Senroy** [comment]
Yeah ok thanks a lot

**Comment by TheLastViper01** [comment]
what do you mean ur gonna copy spotify?
