### ISSUE TITLE
Wine 7.0

### ISSUE THREAD

**Issue by derryktutt** [Botspot/pi-apps#1316]
### What is the name of the app?

Wine 7.0

### (Optional) Where is the app hosted?

[https://www.winehq.org/announce/7.0-rc3](url)

### About the app

This would be an update from wine 5.13, so people can play Roblox on the Raspberry Pi!

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by Painadath** [comment]
What do u mean did u found a way to add wine 7.0 to raspberry Pi or do you wish to get it running?

**Comment by derryktutt** [comment]
I want to get it on there. I already messed up 2 installs trying.

**Comment by baldbuffalo** [comment]
is it there now?

**Comment by Crilum** [comment]
@baldbuffalo On Pi-Apps? No.

**Comment by Botspot** [comment]
I just talked with Salve from Pi Labs and he says that later wine versions are not suitable for raspberry pi.
He says:

> Further versions are only regressions and they fix very modern games
> Games we can't run on rpi4

**Comment by open-sorcerer64** [comment]
But newer is better, right??

**Comment by derryktutt** [comment]
Yes
