### ISSUE TITLE
New Apps

### ISSUE THREAD

**Issue by everypizza1** [Botspot/pi-apps#1327]
I made apps for issue #1326.
[Pacman.zip](https://github.com/Botspot/pi-apps/files/7794017/Pacman.zip)
[Pacman-cli.zip](https://github.com/Botspot/pi-apps/files/7794018/Pacman-cli.zip)

**Comment by Crilum** [comment]
@IKittyCode

**Comment by cycool29** [comment]
Pacman won't work on Raspberry Pi OS, you will probably get this error:

```
X Error of failed request:  BadName (named color or font does not exist)
  Major opcode of failed request:  45 (X_OpenFont)
  Serial number of failed request:  27
  Current serial number in output stream:  31
```

It is a known issue in:
https://forums.raspberrypi.com/viewtopic.php?t=243070
https://forums.raspberrypi.com/viewtopic.php?t=27253
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=248496

I am finding a good alternative of pacman.

pacman4console works well.

**Comment by Crilum** [comment]
This might work:
```
sudo apt install xfonts-75dpi xfonts-100dpi xfonts-cyrillic xfonts-base
```
From: https://askubuntu.com/questions/72122/how-to-install-xorg-x11-fonts

**Comment by cycool29** [comment]
> 

IT WORKED!

**Comment by cycool29** [comment]
@ryanfortner I made DEB packages for this, can you host them on your raspbian-addons repo?

armhf: https://transfer.sh/eaTr5B/pacman_11_armhf.deb
arm64: https://transfer.sh/bTjzdl/pacman_11_arm64.deb

**Comment by ryanfortner** [comment]
> @ryanfortner I made DEB packages for this, can you host them on your raspbian-addons repo?
> 
> armhf: https://transfer.sh/eaTr5B/pacman_11_armhf.deb arm64: https://transfer.sh/bTjzdl/pacman_11_arm64.deb

Added. https://apt.raspbian-addons.org/debian/pool/main/p/pacman/
