### ISSUE TITLE
The previous version of minecraft

### ISSUE THREAD

**Issue by skuxkid123** [Botspot/pi-apps#1329]
### What is the name of the app?

Minecraft java

### About the app

The current Minecraft java launchers we have right now on pi apps is Minecraft java (lunar client) which takes a over an hour to install the version and then for me just crashes, and also Minecarft java (MultiMC5) which also crashes. There used to be another launcher which worked perfectly fine and fast for me but had to reset my system and when i went back to pi apps it was gone but some how i found some one who had all the links and instructions to setup but its kind of a pain to open because you have to type commands everytime  you want to open it. Please add this amazing version of Minecraft java back to pi apps.

Link to how I setup Minecraft java on my Raspberry pi: https://forums.raspberrypi.com/viewtopic.php?t=243946

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by Botspot** [comment]
First, be sure your Pi-Apps is up to date. Both Lunar Client and MultiMC5 launch fine on my system. What system are you using?

Concerning the old launcher, we had to phase it out when all Minecraft accounts were transitioned to Microsoft accounts. The old launcher did not support Microsoft accounts, so it was fairly useless. Both of these new launchers have more features and do support Microsoft Account authentication.

**Comment by skuxkid123** [comment]
Raspberry pi OS

**Comment by skuxkid123** [comment]
Ok I’ll try them again. Thanks!

**Comment by shioyama** [comment]
I also have problems on Bullseye using either install of Minecraft. Lunar 1.12 (which seems to be the current version on pi-apps) doesn't work for me, see https://github.com/gl91306/lunar/issues/29

I tried MultiMC5 and it complained about not having Java 18.

I haven't done anything special with the raspberry pi install and the os itself is up-to-date.

**Comment by shioyama** [comment]
Update: I got MultiMC5 working by updating the Java to the path to java 17. Lunar doesn't work for me even after updating to the latest (1.18).

**Comment by theofficialgman** [comment]
@shioyama 
> I tried MultiMC5 and it complained about not having Java 17.

user error, please read the app description before commenting on an issue

> How to choose the correct java version: https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java#setting-up-java-in-multimc

java-17 is installed for you, its up to you to choose it correctly on setup

**Comment by theofficialgman** [comment]
>Please add this amazing version of Minecraft java back to pi apps.

closing as this request can not be fulfilled as microsoft accounts are the predominant and soon to be only login method.
If a fork comes in the future for the original java launcher to support microsoft accounts this will be looked into again.
