### ISSUE TITLE
DollarSkip

### ISSUE THREAD

**Issue by derryktutt** [Botspot/pi-apps#1333]
### What is the name of the app?

DollarSkip

### (Optional) Where is the app hosted?

https://github.com/CleanMachine1/DollarSkip

### About the app

DollarSkip will remove the $ when pasting commands from the internet.
To test, just paste this: `$ echo 1`. The command prompt should say: `1`. If it does, it works.

### Upload file

[DollarSkip.zip](https://github.com/Botspot/pi-apps/files/7796442/DollarSkip.zip)

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by Botspot** [comment]
It's not a dealbreaker, but I find it highly ironic that Pi-Apps provides an alternative to online tutorials, and then here's an app on Pi-Apps to simplify online tutorials! 😆

There are some other issues to deal with:
- This script directly uses `apt`, which is a no-no.
- The icon is very hard to read. How about a red **Ø** symbol around the dollar sign? That would be much more clearer @CleanMachine1.
- Why is anything being compiled at all? It seems like a small bash script would prevent the 8000 character count limitation and avoid having to use apt or git.

**Comment by CleanMachine1** [comment]
I don't think dollarskip fits pi-apps goals.
Maybe at another time however currently the code doesn't fit the goals and aims of this repo.

Maybe when dollarskip is more complete **I** will add this. However thank you @derryktutt for attempting to add this.
