### ISSUE TITLE
App showing unistalled

### ISSUE THREAD

**Issue by derryktutt** [Botspot/pi-apps#1334]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)

### What happened?

App showing as uninstalled

### Description

I had to reinstall pi-apps, and Zoom was showing as uninstalled, even though it is in my menu.

### What is your operating system?

Raspberry Pi OS

**Comment by Botspot** [comment]
This is normal and expected, because the Pi-apps application is designed to be portable. Pi-Apps keeps lists of apps inside the `~/pi-apps/data/status` folder. So if you deleted that, then Pi-Apps has forgotten the status of apps that you've installed.

Sorry. :/
