### ISSUE TITLE
Lunar Client hangs after Microsoft Login (Raspberry Pi Bullseye)

### ISSUE THREAD

**Issue by shioyama** [Botspot/pi-apps#1336]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)

### What happened?

Minecraft via the Lunar Launcher worked previously with the Mojang login, but after migrating to Microsoft it seems to hang.

### Description

I've been using Minecraft Java edition with the Lunar launcher successfully on Bullseye with Mojang login, but after migrating to Microsoft login the launcher seems to hang after entering login details.

I'd include more details but I'm not really sure where I can find the appopriate logs, etc.

I've updated to the latest version of pi-apps and tried uinstalling/re-installing Minecraft but the same thing happens.

### What is your operating system?

Raspberry Pi Bullseye

**Comment by Botspot** [comment]
@gl91306

**Comment by KolpixTV** [comment]
renderer.log?

**Comment by KolpixTV** [comment]
![image](https://user-images.githubusercontent.com/68741965/148098944-ee7faf9a-c878-4fc7-96fc-af4ed59c8ecc.png)

**Comment by gl91306** [comment]
yeah, and also next time please open an issue on my repo, because the issue template walks you though sending logs

**Comment by gl91306** [comment]
@shioyama

**Comment by gl91306** [comment]
also id like to mention to botspot to please make it clear that any issue related to lunar client should be added as an issue in either my repo or pi-ware's repo

**Comment by gl91306** [comment]
because those will be the only places i will be giving app support

**Comment by Botspot** [comment]
> also id like to mention to botspot to please make it clear that any issue related to lunar client should be added as an issue in either my repo or pi-ware's repo

No problem. I've made the requested changes in commit https://github.com/Botspot/pi-apps/commit/dff30338f1feef25439875b80c9fbca543b708f6. If someone still opens an issue here, I guess we'll close it and direct them to your repo?

**Comment by gl91306** [comment]
yeah

**Comment by gl91306** [comment]
but if its a pi-ware related issue ill direct them back

**Comment by gl91306** [comment]
carp missspel

**Comment by gl91306** [comment]
fixed

**Comment by shioyama** [comment]
Now it seems to be stuck at "Extracting Natives", created an issue: https://github.com/gl91306/lunar/issues/27

**Comment by theofficialgman** [comment]
I'm assuming this bug does not exist anymore, since we have gotten no reports of issues via the discord or github.
closing.
