### ISSUE TITLE
minecraft not install please tell me how to upgrade raspberry pi

### ISSUE THREAD

**Issue by premkubade** [Botspot/pi-apps#1337]
OS: Raspbian GNU/Linux 9 (stretch)
OS architecture: 32-bit
Pi-Apps local commit ID: 67dfacc2d3deff9a4a2cf44533ba6d35f3dd9558
Github latest commit ID: 08f4be92a5153ade59b3250889d90bef66edc6e2	
Kernel: armv7l 4.19.66-v7+
Device model: Raspberry Pi 3 Model B Plus Rev 1.3
Ram size:  GB
Raspberry Pi OS image version: 2019-04-08
Language: en_US.UTF-8

BEGINNING OF LOG FILE:
-----------------------

User error: The suite 'stretch' is not supported, consider upgrading to Raspbian Buster or higher.(B
Failed to install APT repo!

[91mFailed to install Minecraft Pi (Modded)![39m
[40m[93m[5m🔺[25m[39m[49m[93mNeed help? Copy the [1mENTIRE[0m[49m[93m terminal output or take a screenshot.
Please ask on Github: [94m[4mhttps://github.com/Botspot/pi-apps/issues/new/choose[24m[93m
Or on Discord: [94m[4mhttps://discord.gg/RXSTvaUvuu[0m

**Comment by chourmoge** [comment]
see
https://www.raspberrypi.com/software/

**Comment by derryktutt** [comment]
sudo apt update && sudo apt full-upgrade

**Comment by Botspot** [comment]
> sudo apt update && sudo apt full-upgrade

Incorrect. Upgrading packages will not upgrade from Raspbian Stretch to Raspbian Bullseye.

@premkubade, I ***highly*** recommend you re-flash your SD card with a fresh installation of Raspberry Pi OS from [the official download page](https://www.raspberrypi.com/software/). You can use the official [Imager application](https://www.raspberrypi.com/software/) on another computer to write the latest version of operating system to your SD card.
