### ISSUE TITLE
Steam Games not running

### ISSUE THREAD

**Issue by GlacierPark19** [Botspot/pi-apps#134]
Hello,

Huge fan of Pi-Apps, it makes life SO much easier, and I love the ability to use steam. However, when I download and Install a steamOS+Linux game, (Adventure Communist for example), the app appears in taskmgr, but never launches. Help!

Using a Rasberry Pi4B 4gb, Overclocked to 2Ghz

**Comment by Botspot** [comment]
Try running `steam` directly in a terminal.  
By running it in a terminal, you will be able to see any errors.

Reply back with the errors you see, and I'll try to help.

Also, keep in mind that Steam is *still in beta*. I've had it crash often, and had other random issues with running games on it.
