### ISSUE TITLE
VMWare Horizon Client

### ISSUE THREAD

**Issue by DaveDischord** [Botspot/pi-apps#1341]
### Cool ideas?

Would it be possible to add VMWare Horizon Client?  You can find the v2111 tar here: [https://customerconnect.vmware.com/en/downloads/details?downloadGroup=CART22FH2_LIN_2111_TARBALL&productId=1027&rPId=62297#product_downloads](https://customerconnect.vmware.com/en/downloads/details?downloadGroup=CART22FH2_LIN_2111_TARBALL&productId=1027&rPId=62297#product_downloads)

and the Doc here: [https://docs.vmware.com/en/VMware-Horizon-Client-for-Linux/2111/rn/vmware-horizon-client-for-linux-2111-release-notes/index.html#whats-new](https://docs.vmware.com/en/VMware-Horizon-Client-for-Linux/2111/rn/vmware-horizon-client-for-linux-2111-release-notes/index.html#whats-new)

**Comment by Botspot** [comment]
Do you know if it runs on Raspberry Pi?

**Comment by DaveDischord** [comment]
Yes.  I have got it installed and tested to an extent on a pi 4.

**Comment by cycool29** [comment]
After a huge work of extracting tarball and copying binaries, I got it launched:

![](https://i.imgur.com/Gyau5gt.jpg)

**Comment by Crilum** [comment]
@cycool29 would it be possible to put it in a deb?

**Comment by cycool29** [comment]
> @cycool29 would it be possible to put it in a deb?

Yes, but I need someone to test the app. I am not a VMWare user.

I will put the deb here later.

**Comment by DaveDischord** [comment]
I have a few Pis I've wanted to install it on, so I'll happily test it out.

**Comment by Botspot** [comment]
@cycool29?

**Comment by cycool29** [comment]
Sorry, I've forgotten about this.

Here is the deb: https://transfer.sh/L1MSGG/vmware-horizon-client_2111-8.4.0-18957622_armhf.deb

**Comment by DaveDischord** [comment]
OK.  So I had Horizon Client 2106 installed.  Using your package, it
successfully updated to 2111 and the application worked fine.  I also
installed on a fresh rPi OS and it seems to be working as well.  I will try
with different scenarios.

**Comment by DaveDischord** [comment]
OK, so I just attempted an install on Raspberry Pi OS 64-bit and got this error: **Errors were encountered while processing: vmware-horizon-client:armhf**

Could it be an issue with the 64-bit architecture?

**Comment by DaveDischord** [comment]
OK, so after an attempt to install on rpiOS 64-bit, I got the following:
`sudo dpkg -i vmware-horizon-client_2111-8.4.0-18957622_armhf.deb
Selecting previously unselected package vmware-horizon-client:armhf.
(Reading database ... 89487 files and directories currently installed.)
Preparing to unpack vmware-horizon-client_2111-8.4.0-18957622_armhf.deb ...
Unpacking vmware-horizon-client:armhf (2111-8.4.0-18957622) ...
dpkg: dependency problems prevent configuration of vmware-horizon-client:armhf:
 vmware-horizon-client:armhf depends on libudev1.

dpkg: error processing package vmware-horizon-client:armhf (--install):
 dependency problems - leaving unconfigured
Processing triggers for systemd (241-7~deb10u8) ...
Processing triggers for gnome-menus (3.31.4-3) ...
Processing triggers for desktop-file-utils (0.23-4) ...
Processing triggers for mime-support (3.62) ...
Errors were encountered while processing:
 vmware-horizon-client:armhf
`
I'll see if there are more dependencies that need to be included.

**Comment by Botspot** [comment]
You don't generally want to be installing armhf applications in an arm64 OS.
Someone will have to make a deb for arm64.

**Comment by DaveDischord** [comment]
I found the install.sh file for my manual installation of 2106 [here](https://gist.github.com/AliMD/1510c1fea685add923eec662e10f80c3)
I manually ran these lines:
`apt-get install libudev1 libxss1`
`ln -s /lib/arm-linux-gnueabihf/libudev.so.1 /lib/arm-linux-gnueabihf/libudev.so.0`
but I'm still getting the same message.

**Comment by Crilum** [comment]
@DaveDischord Maybe try installing with apt:
```
sudo apt install vmware-horizon-client_2111-8.4.0-18957622_armhf.deb
```

Apt will try to install all the dependencies.

**Comment by Botspot** [comment]
> @DaveDischord Maybe try installing with apt:
> 
> ```
> sudo apt install vmware-horizon-client_2111-8.4.0-18957622_armhf.deb
> ```
> 
> Apt will try to install all the dependencies.

Unless you enabled multiarch and added an armhf repository, that won't work. And it's not a good idea unless you know exactly what you're doing. Someone will simply have to build an arm64 deb.

**Comment by cycool29** [comment]
> OK, so after an attempt to install on rpiOS 64-bit, I got the following:

It is not gonna work, as the DEB is for 32-bit.

> Someone will have to make a deb for arm64.

No, it is only available on armhf.

**Comment by DaveDischord** [comment]
Gotcha.  I'll keep the testing to 32-bit.

**Comment by cycool29** [comment]
The transfer-sh link has expired and I deleted the DEB package...

@DaveDischord Do you have the DEB package?

**Comment by cycool29** [comment]
https://transfer.sh/Sd9W2d/vmware-horizon-client_1.0_armhf.deb

@DaveDischord Can you test again this DEB?

**Comment by DaveDischord** [comment]
I've installed it.  Once on top of an existing install, once after
uninstalling the previous install, then installing, and once on a fresh
OS.  All installed and worked as far as functionality.  The only thing
I noticed was, with installing on top of the existing install, it claimed
to be 'downgrading to 1.0', however, as far as the version listed in-app,
it's the same/latest available.  If you did this for a separate pi-app
version control, then it worked as intended.
I'm sorry.  I must have missed this notification or I would have gotten to
it sooner.

**Comment by cycool29** [comment]
> The only thing I noticed was, with installing on top of the existing install, it claimed to be 'downgrading to 1.0', however, as far as the version listed in-app, it's the same/latest available.

Yes, I use `1.0` instead of `2111-8.4.0-18957622`. That is normal. 

I opened a PR to upload the file on `files` repo: https://github.com/Pi-Apps-Coders/files/pull/26.
