### ISSUE TITLE
Simplescreenrecorder (apt App)

### ISSUE THREAD

**Issue by KolpixTV** [Botspot/pi-apps#1346]
### What is the name of the app?

simplescreenrecorder

### (Optional) Where is the app hosted?

https://github.com/MaartenBaert/ssr

### About the app

_I know it was already requested but it was denied because you didn't accepted apt apps. But now there are many apt apps (like Audacity, Chromium etc.) and it would be nice if you could add simplescreenrecoder aswell._ 

Simplescreenrecorder is a Simple Screen Recorder (the name already say's it lol). It's much faster than OBS.

### Upload file

`sudo apt install simplescreenrecoder`

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [ ] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by KolpixTV** [comment]
I'll do that

**Comment by KolpixTV** [comment]
If you find errors in the description, it would be nice if you could fix them. I'm from Germany so my English is not that good.
[SimpleScreenRecorder.zip](https://github.com/Botspot/pi-apps/files/7809664/SimpleScreenRecorder.zip)

**Comment by Botspot** [comment]
I've gone ahead and copied the official description from `apt info simplscreenrecorder`.
```
Feature-rich screen recorder for X11 and OpenGL
Simple Screen Recorder is, despite its name, an actually feature-rich screen recorder. The name reflects the fact that it is simple to use unlike many other free screen recording applications available. It can be easily configured to start recording from an intuitive wizard-like interface.

It can record the entire screen or part of it directly.  The recording can be paused and resumed at any time. Many different file formats and codecs are supported. To perform an X11 recording, all it takes is selecting an area on the root window with the mouse, choosing an output file and pressing record, either by using the mouse or using a hotkey.

It has a Qt-based graphical user interface.

Its complexity becomes apparent in its powerful features. It allows one to record X11 screen areas and fullscreen OpenGL applications including sound supporting both ALSA, PulseAudio, JACK and OSS. It uses libavformat to encode the recorded material into a variety of video formats. Scaling the recorded video is possible as well as configuring the encoding quality for the codec chosen directly from the user interface.
```

**Comment by Botspot** [comment]
This app has been added.
