### ISSUE TITLE
Jetbrains IntelliJ IDEA

### ISSUE THREAD

**Issue by GlacierPark19** [Botspot/pi-apps#135]
Can we add IntelliJ IDEA Community to Pi-Apps? I don't think it would be difficult. Thanks!

**Comment by Botspot** [comment]
Does it run on Raspberry Pi already?

**Comment by Botspot** [comment]
Okay so it looks like you can run it. https://geektechstuff.com/2019/06/08/installing-intellij-ide-on-raspberry-pi-java-raspberry-pi/

Now, how is it different from Pycharm? It looks like some people were using IntelliJ IDEA and Pycharm interchangeably on the website. Is Pycharm just another name for IntelliJ IDEA?

**Comment by GlacierPark19** [comment]
JetBrains IDEA is nicer for Minecraft forge/java development. It is very similar to eclipse (code completion, run client in IDE ,etc.), but actually works on the pi. I was just hoping we could get the app added to Pi-apps for easier install.

**Comment by Botspot** [comment]
Okay I've made progress on it.

Currently I'm here:
```
pi@raspberrypi:~/Downloads/idea-IC-203.5981.155/bin $ ./idea.sh

Unsupported Java Version
Cannot start under Java 1.8.0_251-b08: Java 11 or later is required.
```
So it looks like a later version of java is required. Interesting.

**Comment by Botspot** [comment]
It's almost done!

**Comment by Botspot** [comment]
Would anyone like to try it?
[Intellij IDEA.zip](https://github.com/Botspot/pi-apps/files/5718067/Intellij.IDEA.zip)

**Comment by fabianmendes** [comment]
> Would anyone like to try it?
> [Intellij IDEA.zip](https://github.com/Botspot/pi-apps/files/5718067/Intellij.IDEA.zip)

Sure

**Comment by Botspot** [comment]
This later version of the zip has cosmetic improvements.  
[Intellij IDEA.zip](https://github.com/Botspot/pi-apps/files/5722190/Intellij.IDEA.zip)

**Comment by fabianmendes** [comment]
I'm on it. I couldn't test the older .zip (too busy this afternoon)

![2020-12-21-000425_800x480_scrot](https://user-images.githubusercontent.com/31230743/102738331-25601380-4320-11eb-8dbd-03abc9dbfd99.png)

**Comment by fabianmendes** [comment]
Ok, I have not free space on my disk, installation failed for now to me.

I must clean up. Hope someone else can test it too

**Comment by Itai-Nelken** [comment]
> Ok, I have not free space on my disk, installation failed for now to me.
> 
> I must clean up. Hope someone else can test it too

use bleachbit (`sudo apt install bleachbit`) in some cases it cleans several GB's.

**Comment by fabianmendes** [comment]
Amazing, I will try it out!

On Dec 21, 2020 2:14 AM, "Itai Nelken" <notifications@github.com> wrote:

Ok, I have not free space on my disk, installation failed for now to me.

I must clean up. Hope someone else can test it too

use bleachbit (sudo apt install bleachbit) in some cases it cleans several
GB's.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/Botspot/pi-apps/issues/135#issuecomment-748783058>, or
unsubscribe

**Comment by Botspot** [comment]
Added. Commit https://github.com/Botspot/pi-apps/tree/master/apps
