### ISSUE TITLE
OBS can't stream or record

### ISSUE THREAD

**Issue by epicmario7133** [Botspot/pi-apps#1353]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)

### What happened?

OBS can't stream or record

### Description

Full error;
warning: Stream output type 'rtmp_output' failed to start!
QObject::connect: No such signal QLineEdit::editingFinished(const QString &)
QObject::connect:  (sender name:   'customServer')
QObject::connect:  (receiver name: 'OBSBasicSettings')
Attempted path: share/obs/obs-studio/locale.ini
Attempted path: /usr/share/obs/obs-studio/locale.ini
Attempted path: share/obs/obs-studio/themes/
Attempted path: /usr/share/obs/obs-studio/themes/
error: Encoder ID 'obs_x264' not found
info: Settings changed (outputs)

### What is your operating system?

Raspberry pi os  blueeyes

**Comment by frogro** [comment]
So obs can be installed again but no screen / webcam streaming and recording?

**Comment by epicmario7133** [comment]
> So obs can be open after installation again but no screen / webcam streaming and recording?

yep

**Comment by frogro** [comment]
Whst does  it mram? What is to do?

**Comment by theofficialgman** [comment]
https://github.com/Botspot/pi-apps/pull/1362#issuecomment-1008174396
other users believe this is unfixable. use the workaround referenced in this message ^

**Comment by theofficialgman** [comment]
@frogro @epicmario7133 please send your obs logfile

open obs -> help ->logfiles -> upload current logfile

copy the URL and send it here. this is necessary for debugging, for some reason your obs_x264 binary is not loading

**Comment by Crilum** [comment]
Here you go, @theofficialgman:
```
$ obs
debug: Found portal inhibitor
Attempted path: share/obs/obs-studio/locale/en-US.ini
Attempted path: /usr/share/obs/obs-studio/locale/en-US.ini
Attempted path: share/obs/obs-studio/locale.ini
Attempted path: /usr/share/obs/obs-studio/locale.ini
Attempted path: share/obs/obs-studio/themes/Dark.qss
Attempted path: /usr/share/obs/obs-studio/themes/Dark.qss
info: Physical Cores: 4, Logical Cores: 4
info: Physical Memory: 3794MB Total, 716MB Free
info: Kernel Version: Linux 5.15.32-v8+
info: Distribution: "Raspbian GNU/Linux" "11"
info: Session Type: x11
info: Window System: X11.0, Vendor: The X.Org Foundation, Version: 1.20.11
info: Qt Version: 5.15.2 (runtime), 5.15.2 (compiled)
info: Portable mode: false
Attempted path: share/obs/obs-studio/themes/Dark/no_sources.svg
Attempted path: /usr/share/obs/obs-studio/themes/Dark/no_sources.svg
QMetaObject::connectSlotsByName: No matching signal for on_tbar_position_valueChanged(int)
QMetaObject::connectSlotsByName: No matching signal for on_actionShowTransitionProperties_triggered()
QMetaObject::connectSlotsByName: No matching signal for on_actionHideTransitionProperties_triggered()
info: OBS 27.2.0-286-gac674e413 (linux)
info: ---------------------------------
info: ---------------------------------
info: audio settings reset:
	samples per sec: 48000
	speakers:        2
info: ---------------------------------
info: Initializing OpenGL...
/usr/bin/obs: line 2: 10419 Segmentation fault      MESA_GL_VERSION_OVERRIDE=3.3 /usr/bin/obs-exec "$@"
``

**Comment by theofficialgman** [comment]
> Here you go, @theofficialgman:
> 
> ```
> $ obs
> debug: Found portal inhibitor
> Attempted path: share/obs/obs-studio/locale/en-US.ini
> Attempted path: /usr/share/obs/obs-studio/locale/en-US.ini
> Attempted path: share/obs/obs-studio/locale.ini
> Attempted path: /usr/share/obs/obs-studio/locale.ini
> Attempted path: share/obs/obs-studio/themes/Dark.qss
> Attempted path: /usr/share/obs/obs-studio/themes/Dark.qss
> info: Physical Cores: 4, Logical Cores: 4
> info: Physical Memory: 3794MB Total, 716MB Free
> info: Kernel Version: Linux 5.15.32-v8+
> info: Distribution: "Raspbian GNU/Linux" "11"
> info: Session Type: x11
> info: Window System: X11.0, Vendor: The X.Org Foundation, Version: 1.20.11
> info: Qt Version: 5.15.2 (runtime), 5.15.2 (compiled)
> info: Portable mode: false
> Attempted path: share/obs/obs-studio/themes/Dark/no_sources.svg
> Attempted path: /usr/share/obs/obs-studio/themes/Dark/no_sources.svg
> QMetaObject::connectSlotsByName: No matching signal for on_tbar_position_valueChanged(int)
> QMetaObject::connectSlotsByName: No matching signal for on_actionShowTransitionProperties_triggered()
> QMetaObject::connectSlotsByName: No matching signal for on_actionHideTransitionProperties_triggered()
> info: OBS 27.2.0-286-gac674e413 (linux)
> info: ---------------------------------
> info: ---------------------------------
> info: audio settings reset:
> 	samples per sec: 48000
> 	speakers:        2
> info: ---------------------------------
> info: Initializing OpenGL...
> /usr/bin/obs: line 2: 10419 Segmentation fault      MESA_GL_VERSION_OVERRIDE=3.3 /usr/bin/obs-exec "$@"
> ``
> ```

that isn't a logfile.... but this is different from what other users have reported since you segfault before even opening OBS
verify that you are on the latest version from pi-apps

if you are on the latest version then this is something else. I will let you know that on nintendo switch, I also get a segfault when initializing OBS on opengl when I build myself. OBS said it was a bug with nvidia drivers but that seems to not be the case if the pi has it as well

try preloading opengl, it works for me on switch
```
bash -c "MESA_GL_VERSION_OVERRIDE=3.3 LD_PRELOAD=/usr/lib/aarch64-linux-gnu/libGL.so obs"
```
(change aarch64 to the appropriate armhf location, I don't know what is is off the top of my head)

**Comment by Crilum** [comment]
With your command, it opens:
```
10:58:41.571: Physical Cores: 4, Logical Cores: 4
10:58:41.571: Physical Memory: 3794MB Total, 594MB Free
10:58:41.571: Kernel Version: Linux 5.15.32-v8+
10:58:41.571: Distribution: "Raspbian GNU/Linux" "11"
10:58:41.571: Session Type: x11
10:58:41.571: Window System: X11.0, Vendor: The X.Org Foundation, Version: 1.20.11
10:58:41.573: Qt Version: 5.15.2 (runtime), 5.15.2 (compiled)
10:58:41.573: Portable mode: false
10:58:41.860: OBS 27.2.0-286-gac674e413 (linux)
10:58:41.860: ---------------------------------
10:58:41.862: ---------------------------------
10:58:41.862: audio settings reset:
10:58:41.862: 	samples per sec: 48000
10:58:41.862: 	speakers:        2
10:58:41.902: ---------------------------------
10:58:41.902: Initializing OpenGL...
10:58:42.921: Loading up OpenGL on adapter Broadcom V3D 4.2
10:58:42.922: glEnable failed, glGetError returned GL_INVALID_ENUM(0x500)
10:58:42.930: OpenGL loaded successfully, version 3.3 (Core Profile) Mesa 20.3.5, shading language 3.30
10:58:43.613: ---------------------------------
10:58:43.614: video settings reset:
10:58:43.614: 	base resolution:   1920x1080
10:58:43.614: 	output resolution: 1280x720
10:58:43.614: 	downscale filter:  Bicubic
10:58:43.614: 	fps:               30/1
10:58:43.614: 	format:            NV12
10:58:43.614: 	YUV mode:          Rec. 709/Partial
10:58:43.615: NV12 texture support not available
10:58:43.615: P010 texture support not available
10:58:43.651: Audio monitoring device:
10:58:43.651: 	name: Default
10:58:43.651: 	id: default
10:58:43.651: ---------------------------------
10:58:43.662: Failed to load 'en-US' text for module: 'decklink-captions.so'
10:58:43.682: Failed to load 'en-US' text for module: 'decklink-output-ui.so'
10:58:43.695: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
10:58:43.696: Failed to initialize module 'decklink.so'
10:58:44.726: v4l2loopback not installed, virtual camera disabled
10:58:44.770: [obs-browser]: Version 2.17.14
10:58:44.774: [obs-browser]: CEF Version 95.0.4638.69 (runtime), 95.7.18+g0d6005e+chromium-95.0.4638.69 (compiled)
10:58:45.349: FFMPEG VAAPI supported
10:58:45.508: [vlc-video]: VLC 3.0.16 Vetinari found, VLC video source enabled
10:58:45.509: ---------------------------------
10:58:45.509:   Loaded Modules:
10:58:45.509:     vlc-video.so
10:58:45.509:     text-freetype2.so
10:58:45.509:     rtmp-services.so
10:58:45.509:     obs-x264.so
10:58:45.509:     obs-vst.so
10:58:45.509:     obs-transitions.so
10:58:45.509:     obs-outputs.so
10:58:45.509:     obs-filters.so
10:58:45.509:     obs-ffmpeg.so
10:58:45.509:     obs-browser.so
10:58:45.509:     linux-v4l2.so
10:58:45.509:     linux-pulseaudio.so
10:58:45.509:     linux-capture.so
10:58:45.509:     linux-alsa.so
10:58:45.509:     image-source.so
10:58:45.510:     frontend-tools.so
10:58:45.510:     decklink-output-ui.so
10:58:45.510:     decklink-captions.so
10:58:45.510: ---------------------------------
10:58:45.515: ==== Startup complete ===============================================
10:58:45.553: No scene file found, creating default scene
10:58:45.763: All scene data cleared
10:58:45.764: ------------------------------------------------
10:58:45.848: pulse-input: Server name: 'pulseaudio 14.2'
10:58:45.850: pulse-input: Audio format: s16le, 44100 Hz, 2 channels
10:58:45.851: pulse-input: Started recording from 'bluez_sink.30_C0_1B_48_8B_69.a2dp_sink.monitor'
10:58:45.851: Switched to scene 'Scene'
10:58:45.851: Failed to glob scene collections
10:58:46.422: adding 42 milliseconds of audio buffering, total audio buffering is now 42 milliseconds (source: Desktop Audio)
10:58:46.422: 
```

That's the log, from Help -> log files -> view current log
I don't have a webcam, but OBS records my desktop just fine:

https://user-images.githubusercontent.com/91354257/173885210-f3f748bc-42f8-44f3-b913-20f6c547c73b.mp4

**Comment by theofficialgman** [comment]
@Crilum ok so your issue is not the same as the ones in these thread: https://github.com/Botspot/pi-apps/issues/1353#issue-1094829789
see above they are failing to load the encoder ^. for you it loads just fine

this was probably fixed in an update to OBS many months ago but the original poster never came back

I will add the GL preload to the obs command for pi-apps

**Comment by theofficialgman** [comment]
added: https://github.com/Botspot/pi-apps/commit/67c67f4900dbf5af13b60b05785b764bab212c29

**Comment by theofficialgman** [comment]
also not to self, this commit can be reverted once we build a new version of OBS on master or the next release (whenever they make one) https://github.com/Botspot/pi-apps/commit/67c67f4900dbf5af13b60b05785b764bab212c29

obs removed the gl-x11-glx renderer and now exclusively uses the EGL render on linux https://github.com/obsproject/obs-studio/commit/ca2d02c2ce5278e7403e0d343ca743cb91fd068f
