### ISSUE TITLE
webcord won't launch

### ISSUE THREAD

**Issue by wet-wert** [Botspot/pi-apps#1357]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)

### What happened?

App installs but as soon has I try and open it it throws a syntax error

### Description

the exact error page is as follows
Uncaught Exception: WebCord threw 'SyntaxError'

Unexpected end of JSON input
at WinKeeperState.get (sources/code/main/modules/config.ts:151:35)
at new WinKeeperstate.get (sources/code/main/modules/config.ts:214:47)
at createMainWindow (sources/code/main/windows/main.ts:23:29)
at App.main (sources/code/main.ts23:39)

### What is your operating system?

Raspberry Pi OS ARM 32-bit

**Comment by cycool29** [comment]
Try reinstalling it.

If that doesn't work, you need to remove WebCord config files: `rm -rf ~/.config/WebCord`.
