### ISSUE TITLE
Celeste

### ISSUE THREAD

**Issue by ghost** [Botspot/pi-apps#136]
Hey it would be awesome to play Minecraft Dungeons on my Pi, as it is possible with Minecraft Java and Bedrock Edition.

**Comment by Botspot** [comment]
Pi-Apps isn't magic. An app has to already be runnable on the Pi.  
Then Pi-Apps makes it a piece of cake to install.

So @zachdwilliams, are you aware of MC Dungeons running on RPi? If not, Pi-Apps really can't be of much help.

**Comment by zachdwilliams** [comment]
I haven’t found anything so far. If not Minecraft then maybe Celeste? I know it is runnable on the Pi so it would be an amazing addition to Pi-Apps.

**Comment by zachdwilliams** [comment]
@Botspot I haven’t found anything so far. If not Minecraft then maybe Celeste? I know it is runnable on the Pi so it would be an amazing addition to Pi-Apps.

**Comment by zachdwilliams** [comment]
So yeah, Celeste is runnable but I don’t know how to run it

**Comment by mobilegmYT** [comment]
If you want something, then get it running and come back to here and make a new issue. For now, please close this ticket.

**Comment by Botspot** [comment]
This issue can remain open until somebody makes a Celeste app for Pi-Apps..

**Comment by moocow1452** [comment]
[These instructions worked fine for me.](https://hackmd.io/@djazz/Sysdqjva8) Whoever would want to build the installer could probably use it as a base.

**Comment by Botspot** [comment]
Is there a free (legal) version of Celeste anywhere?  

If not, it's not eligible for Pi-Apps.

**Comment by irishgreencitrus** [comment]
> Is there a free (legal) version of Celeste anywhere?
> 
> If not, it's not eligible for Pi-Apps.

Nope. It's a paid game. The only version that's (legally) free is the PICO-8 version, but that requires PICO-8 which is a paid software and already has a raspberry pi version.
