### ISSUE TITLE
Cura fails to slice

### ISSUE THREAD

**Issue by poolboy97** [Botspot/pi-apps#1375]
Pi-apps updated my cura version to latest 4.13. Since there have been a few issues with plugins which isnt a huge deal for me, but it will not slice any model. Is there a way to force revert back to 4.12.1 or other versions until this is worked out? Im not savy with github and cant find direct instructions on how to do so.

**Comment by poolboy97** [comment]
![image](https://user-images.githubusercontent.com/82302746/149416158-45131130-9469-4be0-942c-0aef3228d4c0.png)

**Comment by poolboy97** [comment]
I get this same error on every and anything i try to slice. Rather auto or manually slice. I have uninstalled and reinstalled a few times. Same issue.

**Comment by poolboy97** [comment]
![image](https://user-images.githubusercontent.com/82302746/149416518-64e91c18-d206-447f-8b90-0191a5d28d0a.jpeg)

**Comment by poolboy97** [comment]
I was going to try to report a bug but not sure where to find logs to send copy of.

**Comment by poolboy97** [comment]
Awesome. Thank you very much for your reply and all your work.

**Comment by Botspot** [comment]
I've downgraded Cura with commit https://github.com/Botspot/pi-apps/commit/4d598e1b0bab951a19997110c5ebb209f75d1195.
Update Pi-Apps, and Cura should work again.

Thanks for reporting! Together, we all make Pi-Apps better.

**Comment by theofficialgman** [comment]
> It appears many other people have also encountered this error on Cura 4.13. Cura fixed it on their end, but the [repository](https://github.com/smartavionics/Cura) hosting RPi-compatible builds has not been updated yet.

I don't see this as being true
smartavionics release is up to date with upstream cura 4.13
not sure what the issue is though since the full error needs to be posted here

**Comment by smartavionics** [comment]
Hi. Please provide a Cura project (.3mf) file that shows the problem. Thanks.

**Comment by poolboy97** [comment]
I’m not sure the 3mf is where the issue is. I tried with multiple files which i’ve printed many times and same error with all of them.

 To be honest im not really up to speed on finding/sending logs to help much. If you could help walk me through would be appreciated. I have gone into config folder and found cura logs there. Is this the logs that would be needed? If so only a portion or entire log as it has a couple days worth? I really want to help/learn so hope im not asking to much. 
Since the app downgraded it is working ok without errors now. Only thing I notice now is preview only shows greyed model and not actual layer lines nor can i cycle through each layer as i could before the initial update. 


Larry Shirley

**Comment by Crilum** [comment]
> I’m not sure the 3mf is where the issue is. I tried with multiple files which i’ve printed many times and same error with all of them. To be honest im not really up to speed on finding/sending logs to help much. If you could help walk me through would be appreciated. I have gone into config folder and found cura logs there. Is this the logs that would be needed? If so only a portion or entire log as it has a couple days worth? I really want to help/learn so hope im not asking to much. Since the app downgraded it is working ok without errors now. Only thing I notice now is preview only shows greyed model and not actual layer lines nor can i cycle through each layer as i could before the initial update. Larry Shirley

Yes, I have also noticed that cura doesn't actually show the layer lines, which is kind of annoying..

Any Cura logs you find that would be relevant might be helpful.

**Comment by smartavionics** [comment]
Without any sample project files or cura.log files to look at I can't really find out what's going wrong here.

The project files are simply created by doing File->Save and then either zipping up the resulting .3mf file or changing the extension to .zip so that it can be attached to this thread.

You will find the cura.log file in ~/.local/share/cura/master and also the stderr.log file from ~/.local/share/cura could be useful.

**Comment by poolboy97** [comment]
Ok.  I am away right now. It may take me a day or so be back to access. 


Larry Shirley

**Comment by poolboy97** [comment]
[cura.log.zip](https://github.com/Botspot/pi-apps/files/7876431/cura.log.zip)

**Comment by poolboy97** [comment]
i believe this is the actual file where issue was  the first one i sent was after system downgraded.
[Uploading cura.log.1.zip…]()

**Comment by smartavionics** [comment]
Thanks for the log files. Could you please also provide a project file that had failed to slice. Thanks.

**Comment by poolboy97** [comment]
[CCR10_XYZ_Calibration_v3.3mf.zip](https://github.com/Botspot/pi-apps/files/7877675/CCR10_XYZ_Calibration_v3.3mf.zip)

**Comment by poolboy97** [comment]
[CCR10_barrel retainer test 1.2.3mf.zip](https://github.com/Botspot/pi-apps/files/7877696/CCR10_barrel.retainer.test.1.2.3mf.zip)

**Comment by smartavionics** [comment]
Thanks for the files. I managed to slice those OK using a 64 bit Pi4 with 8G of memory. With the tree support enabled, the slicing took quite a long time but it did complete. BTW, the UM 4.13 release is attracting some bug reports with regard to the tree support being newly broken. e.g. https://community.ultimaker.com/topic/39214-cura-413-tree-support-is-being-placed-through-model/

What Pi are you using?

Is it 32 or 64 bit?

How much memory does it have?

As for the problem with the preview mode not displaying the sliced model, I have identified the issue and will fix that although the problem is not specific to the 20220111 release, earlier releases will also behave the same on systems that have Open GL libraries based on Mesa 20 or later. A workaround is to install the mesa files available with my builds. See https://github.com/smartavionics/Cura/releases for more info.

**Comment by poolboy97** [comment]
Pi 4b 8g 32bit with a 128gb card. With literally not much more than OS on it as this is a fresh card. Maybe the 32bit is an issue? Is there something different with this version, i have been using this pi for a year now with cura without any issues really. 


Larry Shirley

**Comment by smartavionics** [comment]
I've just tried slicing the XYZ calibration thing on a 32 bit Pi4 and it does indeed have a problem. I will investigate but won't get a chance to look until tomorrow (Tuesday). I'll be back...

**Comment by poolboy97** [comment]
Thanks. 


Larry Shirley

**Comment by poolboy97** [comment]
Sounds good. Thanks much


Larry Shirley
