### ISSUE TITLE
zoom not installing

### ISSUE THREAD

**Issue by rbcoder117** [Botspot/pi-apps#1377]
### Confirmations

- [x] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [x] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)

### What happened?

app won't install

### Description

zoom is failing to install
already reinstalled box 86

### What is your operating system?

Rapsberry pi os 32-bit

### (Optional) Error log? Terminal output? Debug messages?

```bash
OS: Raspbian GNU/Linux 10 (buster)
OS architecture: 32-bit
Pi-Apps local commit ID: e31fe3d8a105b7bdfb125ca04a59d78f2b5845b2
Github latest commit ID: d95a25047f18e2a15228565e72262d5bb898acfe	
Kernel: armv7l 5.10.63-v7l+
Device model: Raspberry Pi 4 Model B Rev 1.2
Ram size: 3.83 GB
Raspberry Pi OS image version: 2021-05-07
Language: en_US.UTF-8

BEGINNING OF LOG FILE:
-----------------------

Installing box86...
Box86 failed to install somehow!
/usr/local/bin/box86 does not exist

[91mFailed to install Zoom![39m
[40m[93m[5m🔺[25m[39m[49m[93mNeed help? Copy the [1mENTIRE[0m[49m[93m terminal output or take a screenshot.
Please ask on Github: [94m[4mhttps://github.com/Botspot/pi-apps/issues/new/choose[24m[93m
Or on Discord: [94m[4mhttps://discord.gg/RXSTvaUvuu[0m
```

**Comment by Botspot** [comment]
Looks like Pi-Apps thinks Box86 is installed, but it really isn't.
Try uninstalling Box86, then install Zoom again.

**Comment by rbcoder117** [comment]
I tried that twice but I it still won't install.
the error log is this
Installing Box86...

Adding box86 repo...
--2022-01-15 08:20:22--  https://itai-nelken.github.io/weekly-box86-debs/debian/box86.list
Resolving itai-nelken.github.io (itai-nelken.github.io)... 2606:50c0:8001::153, 2606:50c0:8002::153, 2606:50c0:8000::153, ...
Connecting to itai-nelken.github.io (itai-nelken.github.io)|2606:50c0:8001::153|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 62 [text/plain]
Saving to: ‘/etc/apt/sources.list.d/box86.list’

     0K                                                       100% 1.63M=0s

2022-01-15 08:20:23 (1.63 MB/s) - ‘/etc/apt/sources.list.d/box86.list’ saved [62/62]

Adding key...
Warning: apt-key output should not be parsed (stdout is not a terminal)
OK
Installing box86...
Running pkg-install...
Running sudo apt update...


Hit:1 http://raspbian.raspberrypi.org/raspbian buster InRelease
Hit:3 http://archive.raspberrypi.org/debian buster InRelease
All packages are up to date.

Creating dummy deb...

Installing dummy deb...


The following additional packages will be installed:
  box86-no-binfmt-restart
The following NEW packages will be installed:
  box86-no-binfmt-restart pi-apps-5f3374a7
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 99145 files and directories currently installed.)


Apt finished.

Installed Box86 successfully.
Box86 failed to install somehow!
/usr/local/bin/box86 does not exist

[91mFailed to install Zoom![39m
[40m[93m[5m🔺[25m[39m[49m[93mNeed help? Copy the [1mENTIRE[0m[49m[93m terminal output or take a screenshot.
Please ask on Github: [94m[4mhttps://github.com/Botspot/pi-apps/issues/new/choose[24m[93m
Or on Discord: [94m[4mhttps://discord.gg/RXSTvaUvuu[0m

**Comment by Botspot** [comment]
Your installation of Pi-Apps must be out of date because it's trying to install the `box86-no-binfmt-restart` package. We rewrote that months ago.

**Comment by rbcoder117** [comment]
how do i update I tried to force update but it didn't work

**Comment by Botspot** [comment]
> how do i update I tried to force update but it didn't work

Please run this command in a terminal and tell me what it says.
```
~/pi-apps/updater
```

**Comment by rbcoder117** [comment]
it says
 pi@raspberrypi:~ $ ~/pi-apps/updater

Updater mode: gui

app_type: no app specified!
Scanning files... Done
Nothing is updatable.
pi@raspberrypi:~ $

**Comment by Botspot** [comment]
> it says
> 
> ```
>  pi@raspberrypi:~ $ ~/pi-apps/updater
> 
> Updater mode: gui
> 
> app_type: no app specified!
> Scanning files... Done
> Nothing is updatable.
> pi@raspberrypi:~ $ 
> ```

That's not good.
Okay try this:
```
~/pi-apps/manage check-all
```

**Comment by rbcoder117** [comment]
got error message
~/pi-apps/manage check-all
app_type: no app specified!

**Comment by Botspot** [comment]
> got error message
> 
> ```
> ~/pi-apps/manage check-all
> app_type: no app specified!
> ```

Weird. Let's see what apps you have.
```
~/pi-apps/api list_apps local
```

**Comment by rbcoder117** [comment]
~/pi-apps/api list_apps local
'All Is Well'		 'Mission Planner'
 AndroidBuddy		  Node.js
'Angry IP scanner'	 'Notepad ++'
 AnyDesk		 'OBS Studio'
 Arduino		  OpenSCAD
 AstroMenace		 'Pi-Apps Terminal Plugin (bash)'
 Autostar		 'Pi-Apps Terminal Plugin (python)'
 BalenaEtcher		  PiGro
 BlockPi		  piKiss
'Bongo Cam'		 'Pi Power Tools'
 Box64			  PiSafe
 Box86			  Powerline-Shell
'Boxy SVG'		 'PPSSPP (PSP emulator)'
 Browsh			 'Processing IDE'
 Chiaki			  PrusaSlicer
'Chromium Widevine'	 'Pycharm CE'
'Clam Antivirus'	  QEMU
 CloudBuddy		  Raspi2png
'Color Emoji font'	  Remarkable
 CommanderPi		 'Scratch 2'
 Conky			  Scrcpy
'Conky Rings'		  Snapdrop
'Cool Retro Term'	 'Snap Store'
 Cura			  SpeedTest-CLI
'Descent 1'		  StackEdit
'Descent 2'		  Steam
 Discord		 'Stunt Rally'
'Doom 3'		 'Sublime Text'
'Downgrade Chromium'	  TBOPlayer
 Drawing		 'TeamViewer Host'
'Eagle CAD'		  template
 eDEX-UI		  Timeshift
'Email Checker'		  tldr
'Firefox Rapid Release'   Turbowarp
 Flameshot		  Ulauncher
 FreeCAD		 'Update Buddy'
 FreeTube		  USBImager
'Geany Dark Mode'	  VeraCrypt
 Github-CLI		 'Visual Studio Code'
 Godot			  Vivaldi
'Heroes 2'		  VSCodium
'Https File Server'	 'WACUP (new WinAmp)'
'Intellij IDEA'		 'Web Apps'
'jGRASP IDE'		  Wechat
'Lego Digital Designer'  'Windows 10 Theme'
'Libreoffice MS theme'	 'Windows Flasher'
 LibrePCB		 'Windows Screensavers'
 Lightpad		 'Wine (x86)'
 Lokinet		 'WPS Office'
'Mac OS Theme'		  YouTubuddy
'Minecraft Bedrock'	  Zoom
'Minecraft Java'	 'Zoom PWA'
'Minecraft Pi (Modded)'

**Comment by Botspot** [comment]
Okay, this output will be long, so we'll redirect the output to a file.
```
bash -x ~/pi-apps/manage check-all >> ~/Desktop/test-output.txt
```
Once finished please send me that file.

**Comment by rbcoder117** [comment]
where is it stored?

**Comment by Botspot** [comment]
> where is it stored?

The file is `~/Desktop/test-output.txt`. You should be able to find it with file manager in your Desktop folder. The file is named `test-output.txt`.

**Comment by rbcoder117** [comment]
its empty

**Comment by Botspot** [comment]
> its empty

Okay, try running it again: (originally I forgot to put the & character)
```
bash -x ~/pi-apps/manage check-all &>> ~/Desktop/test-output.txt
```
The terminal should not output ANYTHING.

**Comment by rbcoder117** [comment]
[test-output.txt](https://github.com/Botspot/pi-apps/files/7875660/test-output.txt)

**Comment by Botspot** [comment]
Okay, give me some time to review it.

Please, whatever you do, don't reinstall pi-apps! Even though that would probably solve your issue, it would prevent me from finding and solving the issue.

**Comment by rbcoder117** [comment]
ok

**Comment by Botspot** [comment]
> ok

Hey, could you send me the `manage` script you have installed on your system?
To do that, we'll have to copy the file and rename it to end with txt.
This should work:
```
cp ~/pi-apps/manage ~/Desktop/manage.txt
```

**Comment by rbcoder117** [comment]
[manage.txt](https://github.com/Botspot/pi-apps/files/7875738/manage.txt)

**Comment by Botspot** [comment]
Okay I found the problem.
Turns out your manage script contained a syntax error. This particular one went unnoticed for 2 days back in November, because it's not like a usual, easily catchable syntax error.
The syntax error was introduced with commit https://github.com/Botspot/pi-apps/commit/a53271dd59a1946cc1eac0acdcefc3405f672f39#diff-181229424893bb65d94a74c2132b8b9e5adfe851464fdb5cb9f49e8a8204be7b, and was fixed with commit https://github.com/Botspot/pi-apps/commit/d21575094bc10ad00eed46ed7cb65ef12110a3be#diff-181229424893bb65d94a74c2132b8b9e5adfe851464fdb5cb9f49e8a8204be7b.

Basically, you must have received an update in November which broke future update-checking. Things like this really shouldn't happen, and we've taken measures to prevent it in the future.
Fortunately there is a backup updater, which forcibly updates Pi-Apps after 3 months of inactivity. This backup updater has saved us more than once! :)

To fix your Pi-Apps installation, overwrite your `manage` script with the latest version:
```
wget -O ~/pi-apps/manage https://raw.githubusercontent.com/Botspot/pi-apps/master/manage
```
After running this, `~/pi-apps/updater` will run correctly and you will receive a bunch of updates.
