### ISSUE TITLE
android buddy not starting

### ISSUE THREAD

**Issue by rbcoder117** [Botspot/pi-apps#1386]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)

### What happened?

Won't launch

### Description

It will just load and never open.

### What is your operating system?

Rapsberry pi os 32-bit

**Comment by cycool29** [comment]
Can you post the output of `python3 ~/droidbuddy/main.py`?

**Comment by rbcoder117** [comment]
it is
Traceback (most recent call last):
  File "/home/pi/droidbuddy/main.py", line 4, in <module>
    from PIL import ImageTk, Image
ImportError: cannot import name 'ImageTk' from 'PIL' (/usr/lib/python3/dist-packages/PIL/__init__.py)

**Comment by theofficialgman** [comment]
> it is Traceback (most recent call last): File "/home/pi/droidbuddy/main.py", line 4, in from PIL import ImageTk, Image ImportError: cannot import name 'ImageTk' from 'PIL' (/usr/lib/python3/dist-packages/PIL/**init**.py)

ImageTK comes from a fork of PIL called Pillow and is not available in the default install
the android buddy script does an install of Pillow but does not check for errors:
https://github.com/Botspot/pi-apps/blob/ddb616b869160abdde7f7e85b7ffcc08c9d21266/apps/AndroidBuddy/install#L18

most likely this package failed to install from pip3, or even better, pip3 is not an available command (its not on may installs)

@rbcoder117 try this first and past the output here:
`sudo pip3 install Pillow`

and if that returns an error, then try this:
`sudo python3 -m pip install Pillow`

**Comment by rbcoder117** [comment]
doesn't help same error

**Comment by cycool29** [comment]
Try `sudo apt-get install python3-pil.imagetk`.

**Comment by theofficialgman** [comment]
> doesn't help same error

You didn't report back what the output of those commands were

**Comment by rbcoder117** [comment]
both of them were
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: Pillow in /usr/lib/python3/dist-packages (5.4.1)

**Comment by cycool29** [comment]
> 

@rbcoder117

**Comment by cycool29** [comment]
> Try `sudo apt-get install python3-pil.imagetk`.

@rbcoder117

**Comment by rbcoder117** [comment]
didn't work

**Comment by cycool29** [comment]
Output?

**Comment by rbcoder117** [comment]
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3-pil.imagetk is already the newest version (5.4.1-2+deb10u2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by cycool29** [comment]
Try `sudo apt-get install python3-pil python3-pil.imagetk`.

**Comment by rbcoder117** [comment]
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3-pil is already the newest version (5.4.1-2+deb10u2).
python3-pil set to manually installed.
python3-pil.imagetk is already the newest version (5.4.1-2+deb10u2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by cycool29** [comment]
It might conflict with the pip one, try `sudo apt purge python3-pil python3-pil.imagetk` and reinstall AndroidBuddy.

**Comment by rbcoder117** [comment]
thank you
