### ISSUE TITLE
Adding DietPi support

### ISSUE THREAD

**Issue by pklion** [Botspot/pi-apps#1387]
### Cool ideas?

It looks like there is no official support for DietPi, so it's better if there is a name of DietPi on the supported OS list.

**Comment by cycool29** [comment]
Since DietPi is Debian-based, pi-apps should be compatible with it.

Instead of specifying every compatible Debian-based distro on README, I think we can simply say `Debian-based ARM OS`.

**Comment by pklion** [comment]
I think it's good idea.
