### ISSUE TITLE
Lego digital designer not starter after Wine update

### ISSUE THREAD

**Issue by Rak1ta** [Botspot/pi-apps#1391]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)

### What happened?

Lego digital designer not starter after Wine update

### Description

After updating Wine (didn't update it for a long time, but eventually completely reinstalled it), LDD does not start with the error "OpenGL was not found". Something breaks after the update. Wine has been installed installed in November, ~14. (installation script is below)
Something changed during installation.

I am attaching the installation script dated November 14 (I have the installation date) on which LDD is running.
![Безымянный1](https://user-images.githubusercontent.com/88277343/149824703-bb15abba-33a2-4d9a-8567-e2def85bc798.png)
[install-32.zip](https://github.com/Botspot/pi-apps/files/7884181/install-32.zip)
(del .zip)

### What is your operating system?

RaspiOS 32bit Debian10

**Comment by cycool29** [comment]
Try `sudo apt install libgl1` and install Lego digital designer again.

**Comment by Rak1ta** [comment]
@cycool29 libgl1 is already installed, reinstalled. LDD reinstalled, didn't help.

**Comment by cycool29** [comment]
Try `sudo apt install libgl1-*`.

Also post the output of `sudo find / -iname "libgl.so.1"`.

**Comment by Rak1ta** [comment]
@cycool29 
```
pi@raspberrypi:~ $ sudo find / -iname "libgl.so.1"
/snap/gnome-3-38-2004/89/usr/lib/arm-linux-gnueabihf/libGL.so.1
find: Обнаружено зацикливание в файловой системе; ‘/media/usb0’ является частью той же петли файловой системы что и ‘/’.
(find: File system loop detected; ‘/media/usb0’ is part of the same filesystem loop as ‘/’.)
/usr/lib/arm-linux-gnueabihf/libGL.so.1
find: ‘/run/user/1000/gvfs’: Отказано в доступе
(Access denied)
/var/lib/flatpak/runtime/org.kde.Platform/arm/5.14/fdc141efef6de9ed5020dc22b26f566015f617333dfbc706146d08c3488ea563/files/lib/arm-linux-gnueabihf/libGL.so.1
/home/pi/games/openmw/lib/arm-linux-gnueabihf/libGL.so.1
/home/pi/mesa/gl4es/libGL.so.1
/home/pi/mesa/lib/arm-linux-gnueabihf/libGL.so.1
/opt/wine/mesa/lib/arm-linux-gnueabihf/libGL.so.1
find: ‘/proc/671/task/671/net’: Недопустимый аргумент
(Invalid argument)
find: ‘/proc/671/net’: Недопустимый аргумент
(Invalid argument)
pi@raspberrypi:~ $ sudo apt install libgl1-*
Чтение списков пакетов… Готово
Построение дерева зависимостей       
Чтение информации о состоянии… Готово
Заметьте, выбирается «libgl1-mesa-swx11» для шаблона «libgl1-*»
Заметьте, выбирается «libgl1-nvidia-glx» для шаблона «libgl1-*»
Заметьте, выбирается «libgl1-mesa-swx11-dev» для шаблона «libgl1-*»
Заметьте, выбирается «libgl1-mesa-dev» для шаблона «libgl1-*»
Заметьте, выбирается «libgl1-mesa-dri» для шаблона «libgl1-*»
Заметьте, выбирается «libgl1-mesa-glx» для шаблона «libgl1-*»
Заметьте, выбирается «libgl1-mesa-dri-dbgsym» для шаблона «libgl1-*»
Заметьте, выбирается «libgl1-dbgsym» для шаблона «libgl1-*»
Уже установлен пакет libgl1-mesa-dev самой новой версии (19.3.2-1~bpo10+1~rpt4).
libgl1-mesa-dev помечен как установленный вручную.
Уже установлен пакет libgl1-mesa-dri самой новой версии (19.3.2-1~bpo10+1~rpt4).
Следующие НОВЫЕ пакеты будут установлены:
  libgl1-dbgsym libgl1-mesa-dri-dbgsym libgl1-mesa-glx
Обновлено 0 пакетов, установлено 3 новых пакетов, для удаления отмечено 0 пакетов, и 18 пакетов не обновлено.
Необходимо скачать 66,0 MB архивов.
После данной операции объём занятого дискового пространства возрастёт на 70,1 MB.
Хотите продолжить? [Д/н] y
Пол:1 http://archive.raspberrypi.org/debian buster/main armhf libgl1-dbgsym armhf 1.3.0-7~bpo10+1 [446 kB]
Пол:2 http://archive.raspberrypi.org/debian buster/main armhf libgl1-mesa-dri-dbgsym armhf 19.3.2-1~bpo10+1~rpt4 [65,5 MB]
Пол:3 http://archive.raspberrypi.org/debian buster/main armhf libgl1-mesa-glx armhf 19.3.2-1~bpo10+1~rpt4 [49,4 kB]
Получено 66,0 MB за 29с (2 306 kB/s)                                           
Выбор ранее не выбранного пакета libgl1-dbgsym:armhf.
(Чтение базы данных … на данный момент установлено 378433 файла и каталога.)
Подготовка к распаковке …/libgl1-dbgsym_1.3.0-7~bpo10+1_armhf.deb …
Распаковывается libgl1-dbgsym:armhf (1.3.0-7~bpo10+1) …
Выбор ранее не выбранного пакета libgl1-mesa-dri-dbgsym:armhf.
Подготовка к распаковке …/libgl1-mesa-dri-dbgsym_19.3.2-1~bpo10+1~rpt4_armhf.deb …
Распаковывается libgl1-mesa-dri-dbgsym:armhf (19.3.2-1~bpo10+1~rpt4) …
Выбор ранее не выбранного пакета libgl1-mesa-glx:armhf.
Подготовка к распаковке …/libgl1-mesa-glx_19.3.2-1~bpo10+1~rpt4_armhf.deb …
Распаковывается libgl1-mesa-glx:armhf (19.3.2-1~bpo10+1~rpt4) …
Настраивается пакет libgl1-mesa-dri-dbgsym:armhf (19.3.2-1~bpo10+1~rpt4) …
Настраивается пакет libgl1-dbgsym:armhf (1.3.0-7~bpo10+1) …
Настраивается пакет libgl1-mesa-glx:armhf (19.3.2-1~bpo10+1~rpt4) …
pi@raspberrypi:~ $ sudo find / -iname "libgl.so.1"
/snap/gnome-3-38-2004/89/usr/lib/arm-linux-gnueabihf/libGL.so.1
find: Обнаружено зацикливание в файловой системе; ‘/media/usb0’ является частью той же петли файловой системы что и ‘/’.
(find: File system loop detected; ‘/media/usb0’ is part of the same filesystem loop as ‘/’.)
/usr/lib/arm-linux-gnueabihf/libGL.so.1
find: ‘/run/user/1000/gvfs’: Отказано в доступе
(Access denied)
/var/lib/flatpak/runtime/org.kde.Platform/arm/5.14/fdc141efef6de9ed5020dc22b26f566015f617333dfbc706146d08c3488ea563/files/lib/arm-linux-gnueabihf/libGL.so.1
/home/pi/games/openmw/lib/arm-linux-gnueabihf/libGL.so.1
/home/pi/mesa/gl4es/libGL.so.1
/home/pi/mesa/lib/arm-linux-gnueabihf/libGL.so.1
/opt/wine/mesa/lib/arm-linux-gnueabihf/libGL.so.1
find: ‘/proc/671/task/671/net’: Недопустимый аргумент
(Invalid argument)
find: ‘/proc/671/net’: Недопустимый аргумент
(Invalid argument)
pi@raspberrypi:~ $ 


```

**Comment by Rak1ta** [comment]
@cycool29 On a clean install of RaspiOS tried installing LDD. Won't run, OpenGL error. When I installed Wine with the old script (attached above), even without uninstalling, everything works.  OpenGL output is similar. Games with OpenGL work correctly.

**Comment by cycool29** [comment]
What is the output of `cat /proc/cpuinfo`?

**Comment by Rak1ta** [comment]
@cycool29 
```
pi@raspberrypi:~ $ cat /proc/cpuinfo
processor	: 0
model name	: ARMv7 Processor rev 3 (v7l)
BogoMIPS	: 144.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 3

processor	: 1
model name	: ARMv7 Processor rev 3 (v7l)
BogoMIPS	: 144.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 3

processor	: 2
model name	: ARMv7 Processor rev 3 (v7l)
BogoMIPS	: 144.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 3

processor	: 3
model name	: ARMv7 Processor rev 3 (v7l)
BogoMIPS	: 144.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 3

Hardware	: BCM2711
Revision	: c03112
Serial		: 1000000091e8965b
Model		: Raspberry Pi 4 Model B Rev 1.2

```

**Comment by Botspot** [comment]
I can't seem to reproduce this. LDD installs and runs flawlessly.

@Rak1ta, what kernel are you using?
To find out, run: `~/pi-apps/api get_device_info`

**Comment by Botspot** [comment]
OK, I think I know what happened. The recent upgrade to Wine included a new build of Mesa, to enable better graphics and compatibility. However, it appears to not be compatible with the Raspberry Pi 3.
So, with commit https://github.com/Botspot/pi-apps/commit/306c785f4509ae9e512fe347fe7f468e3b54577f, I've configured the script to skip downloading Mesa if the platform is not a Pi4.

**Comment by Botspot** [comment]
@Rak1ta, please update Pi-Apps, then let me know if the problem continues to occur.

**Comment by cycool29** [comment]
> OK, I think I know what happened. The recent upgrade to Wine included a new build of Mesa, to enable better graphics and compatibility. However, it appears to not be compatible with the Raspberry Pi 3. So, with commit [306c785](https://github.com/Botspot/pi-apps/commit/306c785f4509ae9e512fe347fe7f468e3b54577f), I've configured the script to skip downloading Mesa if the platform is not a Pi4.

He is using Raspberry Pi 4, see the `Model` field [here](https://github.com/Botspot/pi-apps/issues/1391#issuecomment-1015175842).

**Comment by Rak1ta** [comment]
@Botspot works with your update, the previous version does not. 
And tried the same thing with a clean install of Debian 10, the old version doesn't work.
 ```
~/pi-apps/api get_device_info
OS: Raspbian GNU/Linux 10 (buster)
OS architecture: 32-bit
Pi-Apps local commit ID: 95c1eec68f61105428c063a98b6f45668b73b47f
Github latest commit ID: 306c785f4509ae9e512fe347fe7f468e3b54577f	
Kernel: armv7l 5.10.63-v7l+
Device model: Raspberry Pi 4 Model B Rev 1.2
Ram size: 3.65 GB
Raspberry Pi OS image version: 2021-05-07
Language: en_US.UTF-8

```

**Comment by Rak1ta** [comment]
But there are no icons in the application menu **sudo mv "$PWD/wine-stuff/icons" /opt/wine**

**Comment by Rak1ta** [comment]
@Botspot If the folder **opt/wine/mesa** is in place, then LDD will not start.  Everything else is ok. Thanks!

**Comment by Botspot** [comment]
> @Botspot If the folder **opt/wine/mesa** is in place, then LDD will not start. Everything else is ok on my system. Thanks!

Thank you for figuring out what is causing the issue. I've forwarded your message to the guy who gave me the Mesa build. We'll see what he recommends.

**Comment by neofeo** [comment]
HI! @Rak1ta is your rpi os bullseye up to date? 

can you do on terminal : "LD_LIBRARY_PATH=/opt/wine/mesa/lib/arm-linux-gnueabihf/ LIBGL_DRIVERS_PATH=/opt/wine/mesa/lib/arm-linux-gnueabihf/dri/ glxinfo -B" you need mesa-utils to use glxinfo (sudo apt install mesa-utils)

post the result

**Comment by Rak1ta** [comment]
@neofeo i have Debian 10 Buster
"no such file or directory"
![Безымянный](https://user-images.githubusercontent.com/88277343/151119768-9968a052-0e46-4b45-9f23-61a344146380.png)

**Comment by Rak1ta** [comment]
@neofeo i use Debian 10 **_Buster_**
glibc (2.28-10) - this is the latest version on _**Buster**_
Put Bullseye to check and everything works there.
![Безымянный](https://user-images.githubusercontent.com/88277343/151134549-4fbd92b2-fd52-4fa8-9eec-b4cfbbd62022.png)

**Comment by neofeo** [comment]
Okay @Botspot then the script should check if it's running on rpi os bullseye and only use the extra env vars if it's on rpi os bullseye. Quick workaround.

**Comment by Botspot** [comment]
The Wine script now checks glibc version and avoids installing Mesa if it's below 2.30.

This issue should now be solved. @Rak1ta, please update Pi-Apps, which should reinstall Wine, then let me know if LDD is working for you.

**Comment by Rak1ta** [comment]
@Botspot 👌 working
