### ISSUE TITLE
pi apps wont start

### ISSUE THREAD

**Issue by rbcoder117** [Botspot/pi-apps#1394]
pi apps was fine then it just randomly stopped working!

**Comment by Itai-Nelken** [comment]
can you send the output when running `pi-apps` in terminal please?

**Comment by rbcoder117** [comment]
pi@raspberrypi:~ $ pi-apps
    🭊▅▅▅▅🬿
 🭈▂▂█▂▂▂▂█▂▂🬽
 ▌  ▗▖▗▖▗▖  ▐   █▀▀🭍 ▄
 ▌  ▗▖▗▖▗▖  ▐   █▄▄🭞 ▄ ▄▄ 🭂▀▀█ █▀▀🭍 █▀▀🭍 🭂🬰🬰🬰
 ▌  ▗▖▗▖▗▖  ▐   █    █    🭓▄▄█ █▄▄🭞 █▄▄🭞 ▄▄▄🭞
 🭓🬭🬭🬰🬰🬰🬰🬰🬰🬭🬭🭞                  █    █

App: 
Action: main-window
Prevaction: 
Unrecognized app list style 'Daily'!

**Comment by rbcoder117** [comment]
got it to work

**Comment by olaxe** [comment]
I just have this issue and to solve it you need to perform this command:
`rm "~/pi-apps/data/settings/App List Style"`
