### ISSUE TITLE
zoom crashes when I join meeting

### ISSUE THREAD

**Issue by rbcoder117** [Botspot/pi-apps#1404]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)

### What happened?

App will crash when I join zoom meeting

### Description

it crashes and says zoom exited.

### What is your operating system?

raspberry pi os 32bit

**Comment by Botspot** [comment]
When you launched zoom, a terminal should have appeared. In that terminal, there is valuable information about why Zoom crashed. Could you copy everything out of that terminal and post it here?

**Comment by rbcoder117** [comment]
ok

**Comment by rbcoder117** [comment]
it says 
Launching Zoom.
Box86 with Dynarec v0.2.5 b903e57e built on Jan 16 2022 00:07:22
zoom started.
Client: Breakpad is using Single Client Mode! client fd = -1
[CZPClientLogMgr::LogClientEnvironment] [MacAddr: DC:A6:32:8F:4E:3B][client: Linux][OS: Raspbian GNU/Linux 10 (buster)][Hardware: CPU Core:4 Frenquency:1.5 G Memory size:3787MB CPU Brand:              Intel(R) Pentium(R) 4 CPU 1500MHz GPU Brand:][Req ID: ]
Linux Client Version is 5.4.2 (53391.1108)
QSG_RENDER_LOOP is 
XDG_CURRENT_DESKTOP = LXDE;   GDMSESSION = lightdm-xsession
Graphics Card Info:: 
Zoom package arch is 32bit, runing OS arch is i386
AppIconMgr::systemDesktopName log Desktop Name: LXDE-pi 
link image0 hasn't been detected!
Could not resolve property : pattern0
Error: Send error, 22 Invalid argument
Error: Send error, 22 Invalid argument
Error: Send error, 22 Invalid argument
CSBConfUI::OnConfStatusChanged  UI_CMD_SHARE_READYZoom exited. Close this terminal to exit

**Comment by rbcoder117** [comment]
@Botspot what happend?
