### ISSUE TITLE
minecraft server app broken

### ISSUE THREAD

**Issue by rbcoder117** [Botspot/pi-apps#1405]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)

### What happened?

App will crash when I add a mod

### Description

when I launch my server it just will open the terminal then just close the terminal. I am using fabric with fabric api 1.17 with java 16

### What is your operating system?

raspberry pi os 32bit

### (Optional) Error log? Terminal output? Debug messages?

```bash
N/A
```

**Comment by theofficialgman** [comment]
@Botspot this issue should have also been closed with PR: https://github.com/Botspot/pi-apps/pull/1416

please do not spam the issue tracker unless you are using an unmodified install and have verified this is not a user error
mods work perfectly fine
