### ISSUE TITLE
New Server sofware's for the App "Minecraft Java Server"

### ISSUE THREAD

**Issue by KolpixTV** [Botspot/pi-apps#1410]
### Cool ideas?

Ideas for Software's:

- [Spigot](https://getbukkit.org/download/spigot) (very slow but some People still use it)
- [Paper](https://papermc.io/) (Fast Spigot Fork) 
- [Airplane](https://airplane.gg/) (Fast Paper Fork for new Versions)
- [Purpur](https://purpurmc.org/) (Fast Paper Fork for new Versions)

Paper, Airplane and Purpur doesn't put download links for older versions like 1.8.8 1.12.2 etc. on their website so here are all Files even from older Versions:

https://minecraftversion.net/

**Comment by KolpixTV** [comment]
This actually looks better than minecraftversion.net and has more Server Software's

https://serverjars.com/

**Comment by rbcoder117** [comment]
see pull #1406

**Comment by rbcoder117** [comment]
@KolpixTV
