### ISSUE TITLE
mc server wont open

### ISSUE THREAD

**Issue by rbcoder117** [Botspot/pi-apps#1415]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)

### What happened?

when i open it just crashes

### Description

when clicking the application it will open a terminal named bash then just close.

### What is your operating system?

raspberry pi os 32bit

**Comment by Botspot** [comment]
Please find what command the menu launcher is running. To do that:

- Right-click on the menu button -> Properties -> Desktop Launcher tab -> Command
- Copy that command out and close the window.

@rbcoder117, Try running that command in a terminal to see what is going wrong.
@theofficialgman, maybe it's a good idea to switch to `terminal-run` so that we could configure it to stay open after the minecraft server stops.

**Comment by rbcoder117** [comment]
how do i do that it is not showing properties

**Comment by rbcoder117** [comment]
@Botspot @theofficialgman

**Comment by theofficialgman** [comment]
this is probably a user error to due with rbcoder117 working on their own changes
refer to the description for how to run the server:
```
To run: Menu -> Games -> Minecraft Java Server
Attach to a server in the background with: screen -r Minecraft_Server
Detach from a running server session with: CTRL+A then D
To start from a terminal: sudo systemctl start minecraft-server
To stop the server: sudo systemctl stop minecraft-server
To start on automatically on boot and stop on shutdown: sudo systemctl enable minecraft-server
```
I suggest attaching to the currently running server with `screen -r Minecraft_Server`. if that doesn't exist, then it means you are not running your server. in which case you should check that you haven't messed up the systemd script by runing `sudo systemctl status minecraft-server`

running the server from the menu will automatically start server with systemd and then connect to it with `screen -r Minecraft_Server`

**Comment by rbcoder117** [comment]
@theofficialgman how do i revert my changes.

**Comment by theofficialgman** [comment]
> @theofficialgman how do i revert my changes.

I can't tell you that since I don't know your setup. if you had an unchanged pi-apps, I would just run the uninstall of the minecraft server from that and then install again

**Comment by rbcoder117** [comment]
no i changed the installation

**Comment by rbcoder117** [comment]
@theofficialgman

**Comment by theofficialgman** [comment]
please stop @ing me and other users. pi-apps can be installed to any folder, if you believe you have messed up your current install, just install to another folder and try running it from there

**Comment by rbcoder117** [comment]
OK sorry
