### ISSUE TITLE
App Addons

### ISSUE THREAD

**Issue by derryktutt** [Botspot/pi-apps#1418]
### Cool ideas?

If there were app addons, then people would be able to use apps to their full extent. E.X. Wine could have PlayOnLinux.

**Comment by Itai-Nelken** [comment]
The app addons could simply be other apps, for example: currently there are 2 pi-apps terminal addons.
(Also PlayOnLinux doesn't work very well with box86+wine (according to Pi-Labs)).

**Comment by theofficialgman** [comment]
closing, see Itai-Nelken's answer, I think that is how we want to handle apps
