### ISSUE TITLE
Installation Delays should be reduced

### ISSUE THREAD

**Issue by touhidurrr** [Botspot/pi-apps#1421]
### Cool ideas?

So, Here is the log...
```bash
Installing Vivaldi...

Will install these packages: vivaldi-stable 
Running sudo apt update...
Hit:1 http://archive.raspberrypi.org/debian bullseye InRelease
Hit:2 http://ports.ubuntu.com/ubuntu-ports bionic-updates InRelease
Ign:3 https://download.puffinbrowser.com/repo stable InRelease
Ign:4 https://repo.vivaldi.com/archive/deb stable InRelease
Hit:5 https://repo.vivaldi.com/archive/deb stable Release
Hit:7 https://download.puffinbrowser.com/repo stable Release
Hit:9 http://raspbian.raspberrypi.org/raspbian bullseye InRelease
Hit:11 https://itai-nelken.github.io/weekly-box86-debs/debian  InRelease
Hit:12 https://adoptium.jfrog.io/artifactory/deb bullseye InRelease
Hit:13 https://deb.nodesource.com/node_17.x bullseye InRelease
All packages are up to date.
apt update complete.
Creating an empty apt-package to install the necessary apt packages...
It will be named: pi-apps-bc9e1974
Depends: vivaldi-stable
Installing the pi-apps-bc9e1974 package...
The following additional packages will be installed:
  vivaldi-stable
The following NEW packages will be installed:
  pi-apps-bc9e1974 vivaldi-stable
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
(Reading database ... 193857 files and directories currently installed.)
update-alternatives: using /usr/bin/vivaldi-stable to provide /usr/bin/x-www-browser (x-www-browser) in auto mode
update-alternatives: using /usr/bin/vivaldi-stable to provide /usr/bin/gnome-www-browser (gnome-www-browser) in auto mode
update-alternatives: using /usr/bin/vivaldi-stable to provide /usr/bin/vivaldi (vivaldi) in auto mode
Apt finished.
Package installation complete.
```
Now you might wonder, where is the problem? The problem is from these lines..
```bash
The following NEW packages will be installed:
  pi-apps-bc9e1974 vivaldi-stable
```
to these line...
```bash
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
(Reading database ... 193857 files and directories currently installed.)
```
There was a delay of like **5 minutes**, which is very irritating.

Now I don't know why is this happening, but the delays should be fixed / reduced.

**Comment by Botspot** [comment]
This is normal and not fixable. Pi-Apps reduces apt's output to only show the necessary stuff. The delay you observed is when Vivaldi's package is actually being extracted and installed to the system. Vivaldi consumes over 200MB of space, so extraction will take a while on a slow SD card. Usually, apt would spit out a lot of output during this stage, but it has been hidden for the sake of brevity, as most other packages take just a few seconds to install.

**Comment by theofficialgman** [comment]
@Botspot  I have always not liked `less_apt`, the only potential thing I would hide would be the `apt does not have a stable CLI interface.`, everything else deserves to be printed out to terminal and logged. User can watch packages download, configure, and install. Hiding this hurts apt's transparency

Do you have a reason for wanting to do so?

**Comment by Botspot** [comment]
> @Botspot I have always not liked `less_apt`, the only potential thing I would hide would be the `apt does not have a stable CLI interface.`, everything else deserves to be printed out to terminal and logged. User can watch packages download, configure, and install. Hiding this hurts apt's transparency
> 
> Do you have a reason for wanting to do so?

For larger installations, apt seems to display too much output. "Preparing to configure", "selecting previously unselected package", not to mention all of the progress lines.
Also, in a logfile, lines that would usually display on top of each other in a terminal will now consume one line each. And it doesn't take too many of those before log_diagnose stops working.

By reducing apt's output, we actually made Pi-Apps _more reliable_, because it was far more likely to successfully diagnose an error.

**Comment by theofficialgman** [comment]
> Also, in a logfile, lines that would usually display on top of each other in a terminal will now consume one line each.

hmm... yeah the `(Reading database ...` will do that. But I "think" thats all apt has percentages for, I can see wanting to drop those.

and there definitely is some redundant output in apt, I will give you that. maybe you can let through `Fetched 28.7 MB in 9s (3,324 kB/s)`(which indicates to the user that packages are downloaded) and potentially some of the others... `Unpacking` `Setting up` and `Processing triggers for`

right now the experience is not great because you go from "these packages will be installed" to "packages are done installing"

even a dummy scrolling bar across the screen would be enough (to show the process didn't hang), and I know that is possible without consuming one line each update in the logfile because this magic command for wget `--progress=bar:force:noscroll` does that for wget downloads

**Comment by Botspot** [comment]
Looks like there is a built-in way to reduce apt's output.
`-qq -o=Dpkg::Use-Pty=0`
[source](https://askubuntu.com/a/668859)

**Comment by theofficialgman** [comment]
> @theofficialgman, I don't see the point of showing "`Processing triggers for`", or having three lines of output per package: "`selecting previous unselected package`", "`preparing to unpack`", and "`unpacking`". Do you?

yeah those three are redundant, I would just show `unpacking` and hide the others. I don't think the first two outputs can even fail

**Comment by Botspot** [comment]
Currently, these lines are hidden by the `less_apt` function:

- Reading package lists...
- Building dependency tree
- Reading state information...
- Need to get
- After this operation,
- Get:
- Fetched
- Selecting previously unselected package
- Preparing to unpack
- Unpacking 
- Setting up 
- Processing triggers for 
- ^$

@theofficialgman, would you recommend removing anything else in addition to "Unpacking"?

**Comment by theofficialgman** [comment]
`Get:` and `Fetched` should be show, since `Get:` will output immediately for each downloaded package (so user can see that downloads are happening), and `Fetched` only outputs once at the end showing the average download speed

**Comment by touhidurrr** [comment]
> Currently, these lines are hidden by the `less_apt` function:
> 
> - Reading package lists...
> - Building dependency tree
> - Reading state information...
> - Need to get
> - After this operation,
> - Get:
> - Fetched
> - Selecting previously unselected package
> - Preparing to unpack
> - Unpacking 
> - Setting up 
> - Processing triggers for 
> - ^$
> 
> @theofficialgman, would you recommend removing anything else in addition to "Unpacking"?

Seems to complicated to me. Why not just implement it like this: if not `Error:` and not `Warning:` and not things we want like `Get:` and `Fetched:` then hide.

**Comment by Botspot** [comment]
Changes have been made with commit https://github.com/Botspot/pi-apps/commit/a4b63c2b3d3e744927d4aeb05316c0df746d2dcf.
