### ISSUE TITLE
Split `Editors` and `Tools` Categories

### ISSUE THREAD

**Issue by theofficialgman** [Botspot/pi-apps#1446]
### Cool ideas?

The number of apps in the editors category is getting quite large. Maybe we should consider splitting the category into multiple different categories. Examples below:

```
Code Editors
Office Suites
CAD/Manufacturing
Creative Arts Editors
```

My main issue with the current setup is I don't really think the CAD/Manufacturing programs fall into the Editors category at all:
LinuxCNC LibrePCB Eagle CAD FreeCAD Cura OpenSCAD PrusaSlicer

Similarly, the `Tools` category is massive as well but the variety there is so large I can't think of good ways to split it.

**Comment by open-sorcerer64** [comment]
Yeah, I totally agree. But imo 
```
Programming (Apps like codex aren't a code editor) 
Office (Libreoffice themes and AbiWord aren't office "suites")
Graphics (can accommodate both of them)
```

**Comment by open-sorcerer64** [comment]
@Botspot

**Comment by Botspot** [comment]
The other day, I was thinking of a new and totally different category solution: based on the human-level action.

Categories would include "create", "connect", "listen", "watch", "write", "play", etc.
It would certainly be unique, and arguably more precise and intuitive.

**Comment by Botspot** [comment]
> Maybe there could be category themes, that can be changed from Pi-Apps Settings..

Category names can be changed, so what do you mean by "Category themes"? Are you referring to the category icons found in `icons/categories`?

**Comment by theofficialgman** [comment]
> The other day, I was thinking of a new and totally different category solution: based on the human-level action.
> 
> Categories would include "create", "connect", "listen", "watch", "write", "play", etc. It would certainly be unique, and arguably more precise and intuitive.

I don't like this at all...
Way too many apps would fall into multiple categories and it would be confusing for users.
For instance, in YouTube buddy you connect, listen, and watch. The Minecraft scripts, you create and play. For the editors, you create, write, etc.
It just doesn't make any sense, not intuitive at all

**Comment by Crilum** [comment]
@Botspot No, like multiple `categories` files,  the categories you suggested could be one theme, and the current categories would be another theme, and you could switch them out in Settings.
