### ISSUE TITLE
Cant install steam, fails on Box86

### ISSUE THREAD

**Issue by VinMannie** [Botspot/pi-apps#145]
When I attempt a steam install i get this:
```
Extracting box86...
Installing files...
cp: cannot stat '/home/pi/box86.download/etc/*': No such file or directory
cp: cannot stat '/home/pi/box86.download/usr/*': No such file or directory

Done!
Box86 failed to install somehow!

Failed to install Steam with install-32 script!

Close this window to exit.
```

**Comment by VinMannie** [comment]
Workaround: Install box86 first instead of installing it with steam, then it installs just fine

**Comment by Botspot** [comment]
This appears to be an issue with Pale's automated build.

I've let him know.

**Comment by pjh64** [comment]
The issue you have is a result of a faulty build (probably a timing issue) that was uploaded by my script. Should work again now.

Sry for the inconvenience.
