### ISSUE TITLE
Pi-Apps download failed! git clone output was: bash: line 43: git: command not found : rpi4 8gb 2019 ubuntu mate

### ISSUE THREAD

**Issue by Abdullah22-rgb** [Botspot/pi-apps#1453]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)

### What happened?

app won't install

### Description

pls help me

### What is your operating system?

Ubuntu mate 64bit arm64

### (Optional) Error log? Terminal output? Debug messages?

```bash
Pi-Apps download failed!
git clone output was: bash: line 43: git: command not found
```

**Comment by Botspot** [comment]
I wonder how you managed to download Pi-Apps without `git` installed.
In any case, you can install git with this command:
```
sudo apt install -y git
```

**Comment by Abdullah22-rgb** [comment]
let me see

**Comment by Abdullah22-rgb** [comment]
it work
