### ISSUE TITLE
Linuxcnc

### ISSUE THREAD

**Issue by kowlioje** [Botspot/pi-apps#1458]
### What is the name of the app?

Linuxcnc

### (Optional) Where is the app hosted?

Pi apps

### About the app

CNC software

### Upload file

Failed to install LinuxCNC!
◢◣Need help? Copy the ENTIRE terminal output or take a screenshot.
Please ask on Github: https://github.com/Botspot/pi-apps/issues/new/choose
Or on Discord: https://discord.gg/RXSTvaUvuu

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by theofficialgman** [comment]
this is not an "App Request", LinuxCNC is currently in pi-apps
it does not support bullseye (due to the linuxCNC developers) and will likely be removed from pi-apps as a result very soon

**Comment by Crilum** [comment]
@theofficialgman Yeah, if the devs release a bullseye deb, then we can add it back, but for now it should be removed.

**Comment by Crilum** [comment]
I might try to build LinuxCNC, so we might have a fix relatively soon.

**Comment by Botspot** [comment]
> I might try to build LinuxCNC, so we might have a fix relatively soon.

@Crilum, how is progress going?

**Comment by Crilum** [comment]
@Botspot, seeing your comment from #1504 gave me an idea.. Linuxcnc could be run inside a buster chroot.. Kinda inefficient, but if we really wanted to keep Linuxcnc, that could be done..

**Comment by theofficialgman** [comment]
closing as linuxcnc was removed from pi-apps
(users of linuxCNC still know where to get it from the official website for buster only)
