### ISSUE TITLE
Wine is missing on 64bit

### ISSUE THREAD

**Issue by schroedaa** [Botspot/pi-apps#1465]
Hi guys,

can someone confirm that wine isnt included anymore?
Cant find it after a fresh install.

[https://gyazo.com/1c9a4045e432613963f6794c47240294](url)

**Comment by Botspot** [comment]
You appear to be using a 64-bit operating system. While we're planning on making Wine work for 64-bit operating systems, it's not ready and there are other, more pressing issues we need to look into.

To fix:

- You can switch to a 32-bit operating system.
- You can try to help us make Wine available for 64-bit operating systems.

**Comment by arturi** [comment]
According to https://github.com/ptitSeb/box86/issues/565#issuecomment-1031519917, it might be possible to install box86 on Raspberry Pi OS 64. And so Wine should then work too?

**Comment by Botspot** [comment]
> According to [ptitSeb/box86#565 (comment)](https://github.com/ptitSeb/box86/issues/565#issuecomment-1031519917), it might be possible to install box86 on Raspberry Pi OS 64. And so Wine should then work too?

Recently I made an arm64 chroot and did manage to setup multiarch and then installed the box86 apt package. So I can confirm it's possible.
But the bigger question is: would anyone really want 32-bit Wine support on a 64-bit OS? I'm hoping somebody will get 64-bit Wine working, as that would be more ideal.

**Comment by arturi** [comment]
But does 64 bit Wine run 32 bit apps? I just want to play GTA 1, Worms Armaggedon and run Word 2003 + Winamp 😂

**Comment by Crilum** [comment]
> > According to [ptitSeb/box86#565 (comment)](https://github.com/ptitSeb/box86/issues/565#issuecomment-1031519917), it might be possible to install box86 on Raspberry Pi OS 64. And so Wine should then work too?
> 
> Recently I made an arm64 chroot and did manage to setup multiarch and then installed the box86 apt package. So I can confirm it's possible. But the bigger question is: would anyone really want 32-bit Wine support on a 64-bit OS? I'm hoping somebody will get 64-bit Wine working, as that would be more ideal.

@Botspot Most Windows installers are 32-bit, and Wine64 can't run 32-bit programs, it calls Wine32, so I think that users would find Wine32 very helpful on 64-bit.
