### ISSUE TITLE
Cant install firefox

### ISSUE THREAD

**Issue by derryktutt** [Botspot/pi-apps#1468]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)

### What happened?

app not installing latest version

### Description

I think that Ubuntu just deleted the Bionic repository (or stopped updating it).
![2022-02-06-091058_1440x900_scrot](https://user-images.githubusercontent.com/82726593/152687429-33c41328-c013-4db9-8271-7366e034416e.png)

### What is your operating system?

Raspbian GNU/Linux 11 (bullseye), 32 bit

**Comment by Botspot** [comment]
Why did you hide the error? In your original post, you had a screenshot of the error.

Anyway, you should NOT have **amd64** repositories on your system. They won't do any good on your system, and as you've seen, they just cause problems. Please remove the repository file from the `/etc/apt/cources.list.d` folder and try again.

**Comment by theofficialgman** [comment]
ubuntu-ports actually doesn't have amd64 packages at all (its used for armhf, arm64, ppc64 and other architectures)

the user got ubunu-ports added from `Firefox Rapid Release` but they must have added amd64 themselves at some other point
we can force only arm64/armhf packages to be checked from ubuntu-ports to avoid this in the future `[arch=arm64]`, etc
I will fix this in a sec
