### ISSUE TITLE
Soundnode app (SoundCloud client)

### ISSUE THREAD

**Issue by fabianmendes** [Botspot/pi-apps#147]
[App request]

Hi, I want to see it working on RaspberryPi, I don't know how to install it, also, there are two versions for Linux (32-bit and 64-bit). Links:
https://soundnode.github.io/soundnode-website/
https://github.com/Soundnode/soundnode-app
EDIT: 
another helpful link, https://sourcedigit.com/21989-install-soundnode-soundcloud-desktop-app-for-ubuntu-linux/

**Comment by Itai-Nelken** [comment]
the 32bit and 64bit are x86 not arm, so not possible to install on the pi.

**Comment by fabianmendes** [comment]
OMSC (for raspberry pi 3) has an Soundcloud add-on, I think it should be posible to implementa it here as well. The thing is that I don't know!

**Comment by Botspot** [comment]
The Soundnode App looks promising, but I'm concerned that not enough beginner users would understand how to retrieve theyr API key as instructed here: https://github.com/Soundnode/soundnode-app#configuration

**Comment by fabianmendes** [comment]
So good to know!!
