### ISSUE TITLE
LineRider app request

### ISSUE THREAD

**Issue by Sussy-OS** [Botspot/pi-apps#1472]
### What is the name of the app?

Linerider

### (Optional) Where is the app hosted?

https://github.com/jealouscloud/linerider-advanced/releases/tag/v1.04

### About the app

An Open Source spiritual successor to the flash game Line Rider

Fast:
Built with performance in mind

 
Cross Platform:
Line Rider Advanced runs on Windows, Mac OSX, and Linux

 
Open Source:
Line Rider Advanced is open source, and hosted on Github. Anybody can make edits to or view the code

To run: Open the games menu, then click 'linerider'

### Upload file

Note: there is a glitch when recording the track, it tries to open an .exe but it does not use wine to do so. (I hope you can help fix it, Botspot)

[Linerider.zip](https://github.com/Botspot/pi-apps/files/8016909/Linerider.zip)

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by cycool29** [comment]
This app can be run natively on Raspberry Pi with [mono](https://www.mono-project.com/download/stable/#download-lin-raspbian) with all functions working and the startup time is faster than wine. 




To do so:
```bash
sudo apt install apt-transport-https dirmngr gnupg ca-certificates ffmpeg
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
echo "deb https://download.mono-project.com/repo/debian stable-raspbianbuster main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
sudo apt update
sudo apt install mono-devel
wget -O ~/linerider.zip https://github.com/jealouscloud/linerider-advanced/releases/download/v1.04/linerider104.zip
unzip ~/linerider.zip
rm ~/linerider.zip
mkdir -p ~/Documents/LRA/ffmpeg/linux
cp $(command -v ffmpeg) ~/Documents/LRA/ffmpeg/linux/ffmpeg
```

And launch the game with:
```bash
mono ~/linerider/linerider.exe
```

**Comment by cycool29** [comment]
I made a zip: https://transfer.sh/0DSgGb/LineRider.zip

**Comment by Botspot** [comment]
> I made a zip: [LineRider.zip](https://github.com/Botspot/pi-apps/files/8020214/LineRider.zip)

Your uninstall script includes these lines:
```
remove_repofile_if_unused /etc/apt/sources.list.d/mono-official-stable.list

purge_packages || exit 1
```
In no circumstances will the repofile actually be removed, because at the time of running that function, the `mono-devel` package will be installed. It's important to purge packages first, before running `remove_repofile_if_unused`.

**Comment by cycool29** [comment]
> In no circumstances will the repofile actually be removed, because at the time of running that function, the `mono-devel` package will be installed. It's important to purge packages first, before running `remove_repofile_if_unused`.

I've edited the zip. Thanks for noticing.

**Comment by theofficialgman** [comment]
I wouldn't suggest using the `stable-raspbianbuster` repo without actually checking what OS the script is running on, especially since there is a normal bullseye repo, as well as many other ubuntu repos supported at `https://download.mono-project.com/repo/debian`

this would be a good time to implement a decent OS detection function, you can start with what I included in the MultiMC script which seems to have been doing a good job of identifying raspbian vs debian as well as ubuntu and their individual versions
```
if [ -f /etc/upstream-release/lsb-release ]; then
  # this is a ubuntu derivative release, get the upstream info
  mapfile -t os < <(lsb_release -u -s -i -d -r -c)
  __os_id="${os[0]}"
  __os_desc="${os[1]}"
  __os_release="${os[2]}"
  __os_codename="${os[3]}"
else
  mapfile -t os < <(lsb_release -s -i -d -r -c)
  __os_id="${os[0]}"
  __os_desc="${os[1]}"
  __os_release="${os[2]}"
  __os_codename="${os[3]}"
fi
# __os_id contains Raspbian, Debian, or Ubuntu (even for derivatives like ElementaryOS)
# __os_release contains codename, so this is stuff like "bionic" "focal" "buster" or "bullseye"
case "$__os_id" in
    Raspbian)
      dosomething ;;
    Debian)
      dosomething ;;
    Ubuntu)
      dosomething ;;
esac
```

**Comment by theofficialgman** [comment]
to further backup my claim, mono actually has individual packages for each of those OS versions, they don't all just point to the same place. so we should definitely attempt OS detection and install the correct one
and example of the path to the bionic one (note the 1804 in the filename) `pool/main/m/mono/mono-devel_6.12.0.122-0xamarin1+ubuntu1804b1_all.deb`

**Comment by theofficialgman** [comment]
also, consider using this fork https://github.com/Tran-Foxxo/LRTran which is kept up to date and had many more bugfixes and updates
(the original repo has not been updated since 2018, the recent commit was just a readme update)

**Comment by Botspot** [comment]
Installing this app ended up breaking my apt. Before installing LineRider, I did have Pinta installed.

Relevant output:
```
Unpacking libmono-corlib4.5-cil (6.12.0.122-0xamarin1+raspbian10b1) over (6.8.0.105+dfsg-3.2) ...
dpkg: error processing archive /tmp/apt-dpkg-install-yryvcj/00-libmono-corlib4.5-cil_6.12.0.122-0xamarin1+raspbian10b1_all.deb (--unpack):
 trying to overwrite '/usr/lib/mono/4.5/mscorlib.dll', which is also in package libmono-corlib4.5-dll 6.8.0.105+dfsg-3.2
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
```
This managed to lock apt up completely, and I had to resort to forcibly purging all mono-related packages with dpkg.

**Comment by theofficialgman** [comment]
> Installing this app ended up breaking my apt. Before installing LineRider, I did have Pinta installed.
> 
> Relevant output:
> 
> ```
> Unpacking libmono-corlib4.5-cil (6.12.0.122-0xamarin1+raspbian10b1) over (6.8.0.105+dfsg-3.2) ...
> dpkg: error processing archive /tmp/apt-dpkg-install-yryvcj/00-libmono-corlib4.5-cil_6.12.0.122-0xamarin1+raspbian10b1_all.deb (--unpack):
>  trying to overwrite '/usr/lib/mono/4.5/mscorlib.dll', which is also in package libmono-corlib4.5-dll 6.8.0.105+dfsg-3.2
> dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
> ```
> 
> This managed to lock apt up completely, and I had to resort to forcibly purging all mono-related packages with dpkg.

Using the `stable-raspbianbuster` repo on bullseye (which I can tell you are using) is probably just a bad idea...

I doubt that bullseye needs a newer version of mono at all. try instead just using mono 6.8 (the version included with buster by default).

**Comment by Sussy-OS** [comment]
Okay, thanks for the sugjustion of using mono! I have not tested it yet, but this seems like a great idea! Do you have an updated edition of the LineRider.zip?

**Comment by cycool29** [comment]
I just copied how Mission Planner does to LineRider install script.

https://github.com/Botspot/pi-apps/blob/458a55335ce7c58ead39bbdd4889a43346af2111/apps/Mission%20Planner/install#L12-L16

**Comment by cycool29** [comment]
I just found Raspbian already has mono in its apt repo http://raspbian.raspberrypi.org/raspbian/pool/main/m/mono/. 
Ubuntu has it too: http://ports.ubuntu.com/pool/main/m/mono/

So we won't need to add the mono repo, just `install_packages mono-devel` should be enough.

**Comment by cycool29** [comment]
> Does the mono packages fix the recording error?

Yes, as I said, everything works.

**Comment by cycool29** [comment]
> also, consider using this fork https://github.com/Tran-Foxxo/LRTran (which has builds) or this fork which is more up to date but does not have builds https://github.com/RatherBeLunar/LRA-Community-Edition
(the original repo has not been updated since 2018, the recent commit was just a readme update)

I would prefer https://github.com/Tran-Foxxo/LRTran since I can't build https://github.com/RatherBeLunar/LRA-Community-Edition.

**Comment by theofficialgman** [comment]
> I just found Raspbian already has mono in its apt repo http://raspbian.raspberrypi.org/raspbian/pool/main/m/mono/. Ubuntu has it too: http://ports.ubuntu.com/pool/main/m/mono/
> 
> So we won't need to add the mono repo, just `install_packages mono-devel` should be enough.

@cycool29 can you verify that the buster repo version of mono is new enough to support this app?
I think buster has version 5.18 which might be too old

**Comment by theofficialgman** [comment]
LRTran has a different zip format (no linerider folder itself in the zip) so I slightly edited the script to use it
```
install_packages apt-transport-https dirmngr gnupg ffmpeg mono-complete
mkdir -p ~/linerider
wget -O ~/linerider/linerider.zip https://github.com/Tran-Foxxo/LRTran/releases/download/6%2F16%2F20-1/LRTran.6-16-20.-.Build.1.zip
cd ~/linerider
unzip linerider.zip
rm ~/linerider.zip
mkdir -p ~/Documents/LRA/ffmpeg/linux
cp $(command -v ffmpeg) ~/Documents/LRA/ffmpeg/linux/ffmpeg
```

**Comment by Sussy-OS** [comment]
CLOSING: CONtINUEING HERE: https://github.com/Botspot/pi-apps/pull/1476
