### ISSUE TITLE
Raspberry Pi not able to run Pikiss

### ISSUE THREAD

**Issue by NoHumans1** [Botspot/pi-apps#148]
When I installed PiApps, everything went according to plan but as I installed PiKiss it went through the terminal commands and prompted that it did install. but it wont load and brings up an error message about not having an internet connection.

Internet connection required. Causes:

 · Check your network.
 · Weak WiFi signal?.
 · Try no check internet connection parameter (-ni): cd ~/piKiss && ./piKiss.sh -ni

Any help would be appreciated

**Comment by Itai-Nelken** [comment]
this is nothing to do with pi-apps, and is what happens when you have a slow internet connection.

**Comment by NoHumans1** [comment]
Thanks, but my internet speeds are quite fast. I just didn't know why that message was coming up.

**Comment by Botspot** [comment]
Pi-Apps did not cause this issue, and neither can it fix it. Please open an issue on the PiKISS github repository.

https://github.com/jmcerrejon/PiKISS
