### ISSUE TITLE
Install steam client (64 bit)

### ISSUE THREAD

**Issue by GYKgamer** [Botspot/pi-apps#1481]
### What is the name of the app?

Steam Client

### (Optional) Where is the app hosted?

App is hosted from valve inc

### About the app

You can play steam games (supported with linux / arm64) on the raspberry pi 4 instead of using an existing pc to play.

https://pimylifeup.com/raspberry-pi-steam-client/

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by Botspot** [comment]
> ### Confirmations
> * [x]  I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.

Are you sure about that? Steam is already on Pi-Apps and has been for a long time.

**Comment by GYKgamer** [comment]
I've only found steam link, I'm guessing that means it's only in the 32bit version

**Comment by Botspot** [comment]
> I've only found steam link, I'm guessing that means it's only in the 32bit version

You must be running a 64-bit OS then.

**Comment by Botspot** [comment]
> I've only found steam link, I'm guessing that means it's only in the 32bit version

If you would like a challenge, then maybe you would consider trying to get Steam running for 64-bit operating systems? It would help you, and would help many others as well.

**Comment by GYKgamer** [comment]
coding skills = almost 0
wanna try and code this = absolutely

**Comment by Botspot** [comment]
> coding skills = almost 0 wanna try and code this = absolutely

You can start by reviewing the Steam app's install-32 script. I think the hardest part would be to install box86 on a 64-bit OS, but it has been done before. (There are tutorials for it)

**Comment by GYKgamer** [comment]
alright
I will

**Comment by GYKgamer** [comment]
@Botspot I did infact get a script working (it's terrible as hell but does install steam)
But found 2 problems
1. is that it changes your architecture which might give problems installing other apps.
2. I got an error when trying to load into steam "fatal error: Failed to load steamui.so"

**Comment by Botspot** [comment]
Your zip file seems to be corrupted. :(

Could you simply reply with the script in code tags: ```

**Comment by Botspot** [comment]
I've tried downloading your file around 6 times now.
Error output:
```
pi@raspberrypi:~ $ unzip /home/pi/Downloads/install-64.zip
Archive:  /home/pi/Downloads/install-64.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /home/pi/Downloads/install-64.zip or
        /home/pi/Downloads/install-64.zip.zip, and cannot find /home/pi/Downloads/install-64.zip.ZIP, period.
```

**Comment by GYKgamer** [comment]
Oh now I understand, try unzipping using windows and transfer the file over, that's what I di since im using a headless pi

**Comment by Botspot** [comment]
> Oh now I understand, try unzipping using windows and transfer the file over, that's what I di since im using a headless pi

I'm not going to install Windows on a Pi just to extract your script. That would take several hours. Please just send me the script through this reply box.

**Comment by GYKgamer** [comment]
you don't have windows on anything, alright

sudo apt update && sudo apt full-upgrade 
sudo apt install git build-essential cmake
git clone https://github.com/ptitSeb/box86
sudo dpkg --add-architecture armhf
sudo apt update
sudo apt install gcc-arm-linux-gnueabihf libc6:armhf libncurses5:armhf libstdc++6:armhf
cd ~/box86
mkdir build
cd build
cmake .. -DRPI4ARM64=1 -DCMAKE_BUILD_TYPE=RelWithDebInfo
make -j$(nproc)
sudo make install
sudo systemctl restart systemd-binfmt
echo "Downloading steam.deb"
cd ..
cd ..
wget https://steamcdn-a.akamaihd.net/client/installer/steam.deb || error "Failed to download steam.deb!"
"${DIRECTORY}/api" apt_lock_wait
sudo dpkg -i ~/steam.deb || error "dpkg failed to install steam.deb!"
rm ~/steam.deb

echo "Editing steam script to run on Raspberry Pi..."
sudo sed -i 's/set -e/set -e\nexport STEAMOS=1\nexport STEAM_RUNTIME=1/' /usr/lib/steam/bin_steam.sh
echo "Creating a Steam config file so it will launch in Small Mode..."
mkdir -p ~/.local/share/Steam/config
wget https://raw.githubusercontent.com/Botspot/Steam-RPi/main/DialogConfig.vdf -O ~/.local/share/Steam/config/DialogConfig.vdf

**Comment by Botspot** [comment]
@GYKgamer, what did you use to install box86 on it? I don't seem to see that covered in your script.

**Comment by GYKgamer** [comment]
as in what link or what source?

**Comment by GYKgamer** [comment]
Uhh why did you delete my comment?

**Comment by Botspot** [comment]
> Uhh why did you delete my comment?

You were replying to something I deleted, that's all. I found the answer to my own question. ;)

**Comment by GYKgamer** [comment]
How's the code?

**Comment by GYKgamer** [comment]
@Botspot any updates needed to the code (other then all the obvious stuff)

**Comment by theofficialgman** [comment]
out of date PR related to this isssue: https://github.com/Botspot/pi-apps/pull/653

if a true "64bit steam" install is to be done, the user should have both box86 (for steam 32bit client) and box64 (for playing x86_64 games through steam) installed
