### ISSUE TITLE
Need a deb for nala

### ISSUE THREAD

**Issue by Botspot** [Botspot/pi-apps#1487]
### What is the name of the app?

Nala apt package manager

### (Optional) Where is the app hosted?

Run these commands to get started:
```
git clone https://gitlab.com/volian/nala
cd nala
python3 ./setup.py build
sudo python3 ./setup.py install
```

### About the app

I need somebody to make a debfile for this, so that it can be uninstalled.

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by theofficialgman** [comment]
fyi, the repo itself has all the info needed to make a proper deb
```
https://gitlab.com/volian/nala/-/tree/main/debian
```

**Comment by derryktutt** [comment]
Some things I have found:
https://stackoverflow.com/questions/13323107/how-to-make-a-deb-file-from-python
https://wiki.debian.org/Python/LibraryStyleGuide?action=show&redirect=Python%2FPackaging
https://askubuntu.com/questions/399552/how-to-create-a-deb-package-for-a-python3-script

**Comment by theofficialgman** [comment]
see gitlab issue for necessary changes upstream: https://gitlab.com/volian/nala/-/issues/19
