### ISSUE TITLE
NEW APP: Quartz Browser

### ISSUE THREAD

**Issue by atwoyearold14** [Botspot/pi-apps#1490]
What is the name of the app?

Quartz Browser

About the app
A fairly simple browser which has many cool features!

Upload file
[Quartz Browser.zip](https://github.com/Botspot/pi-apps/files/8056128/Quartz.Browser.zip)

zip file above ^^^

Confirmations
I have confirmed that this app is legal and not piracy.
I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
I have confirmed that this app can run on Raspberry Pi.

**Comment by ryanfortner** [comment]
Quartz Browser is already in Pi-Apps: https://github.com/Botspot/pi-apps/tree/master/apps/Quartz

**Comment by atwoyearold14** [comment]
Got it! Sorry, I looked through pi-apps on my rpi and I couldn't find it...

Will look more carefully in the future! :)

**Comment by atwoyearold14** [comment]
Issue closed
