### ISSUE TITLE
Is it possible to add Fritzing app?

### ISSUE THREAD

**Issue by ThaPg** [Botspot/pi-apps#1495]
### What is the name of the app?

Fritzing

### (Optional) Where is the app hosted?

https://github.com/fritzing/fritzing-app

https://github.com/fritzing/fritzing-parts

### About the app

The Fritzing application is an Electronic Design Automation software with a low entry barrier, suited for the needs of makers and hobbyists. It offers a unique real-life "breadboard" view, and a parts library with many commonly used high-level components. Fritzing makes it very easy to communicate about circuits, as well as to turn them into PCB layouts ready for production. It is particularly popular among Arduino and Raspberry Pi users, and is widely used in education and creative tinkering.

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by ThaPg** [comment]
I have seen that you can intall the program using `sudo apt-get install fritzing` but it is in version 0.9.3. Now it is 0.9.9. 

Version 0.9.3 is from July 2016
Version 0.9.9 is from September 2021.

**Comment by ThaPg** [comment]
I saw them. Unfortunately it is confused and difficult for me to understand them. Is it possible to create installation script?

Also i found that: https://github.com/fritzing/fritzing-app/wiki/1.3-Linux-notes

Thanks.

**Comment by theofficialgman** [comment]
I'll look into this soon. I really like Fritzing and have used it plenty on Windows 10. I honestly forgot it was FOSS.

I just checked their build check, and they are building on ubuntu xenial, so there shouldn't be any issues building on bionic/buster or newer

**Comment by ThaPg** [comment]
@theofficialgman thanks for the answer. Unfortunately I don't have the knowledge to understand all the commands and coding tips to create a build. 

I'll wait for your .zip archive to try the installation.

I love this program and I'm using in Windows 10, but in version 0.9.3b. 
Also what means FOSS and CI?

**Comment by theofficialgman** [comment]
update on this
builds perfectly on ubuntu bionic without any changes
```
cd $HOME
mkdir Fritzing
cd Fritzing
git clone https://github.com/fritzing/fritzing-parts.git parts
cd /tmp
git clone https://github.com/fritzing/fritzing-app.git
cd fritzing-app
git checkout 0.9.6
sudo apt-get install build-essential git cmake libssl-dev libudev-dev qt5-default libqt5serialport5-dev libqt5svg5-dev libgit2-dev libboost-all-dev -y
sed -i 's/LIBGIT_STATIC = true/LIBGIT_STATIC = false/g' phoenix.pro
qmake
lupdate -noobsolete phoenix.pro
lrelease -removeidentical phoenix.pro
make -j$(nproc)
sudo make install
```
system installs of the parts library is totally broken on fritzing in general, every package manager (debian, ubuntu, arch, etc) fixes it in their own fork in different ways... so this is the below is the best we can do reasonably

run from cli:
```
Fritzing --parts $HOME/Fritzing/parts
```

modify the .desktop file to also use this parts path
```
sudo sed -i "s:Exec=Fritzing %F:Exec=Fritzing --parts $HOME/Fritzing/parts %F:g" /usr/share/applications/org.fritzing.Fritzing.desktop
```

**Comment by theofficialgman** [comment]
and fyi, 0.9.9, 0.9.8, and 0.9.7 don't have official release tags
which is why I chose 0.9.6 in the above example (also what latest debian testing a ubuntu use)
