### ISSUE TITLE
Minecraft Bedrock not signing into google

### ISSUE THREAD

**Issue by CreeperCrafter979** [Botspot/pi-apps#1498]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)

### What happened?

Minecraft Bedrock is not loading the Google Login Page

### Description

After installing the Minecraft Bedrock Linux Launcher on a fresh (~2 or so minutes of theme changes and downloading performance monitors) install of Raspberry Pi OS on my Raspberry Pi 400, it fails to load the Google Play sign in prompt, instead displaying the text "Failed to load the [Google login Page](https://accounts.google.com/embedded/setup/v2/android?source=com.android.settings&xoauth_display_name=Android%20Phone&canFrp=1&canSk=1&lang=en&langCountry=en_us&hl=en-US&cc=us), please check your Internet connection." and a button to try again. Clicking on the link will open a separate sign in prompt on a chromium tab, but it won't do anything upon completion. I tried running the AppImage in the terminal and it outputs the text shown in the error log section. After this, I tried it on a micro SD card containing an older version of Raspberry Pi OS (5.10.17-v7l+ compared to 5.10.92-v7l+) I installed somewhere in 2021, and it worked flawlessly (other than needing to install 1.13 before getting 1.18.10 to make it not crash)! I know I should just be happy with that, but the older version of the OS doesn't mix well with my new monitor so I want it working on the latest OS. I saw in the terminal output mentioned previously that something was crashing in the chromium files, so I tried a few things to either fix or redirect it like using the downgrade chromium app (did nothing), installing Firefox as well (also nothing), and then also uninstalling chromium (green spinning wheel of death replaced the entire sign in window, yay). 
![2022-02-15-220741_2944x1080_scrot](https://user-images.githubusercontent.com/61715966/154188648-f42847b4-e639-4540-a58a-15aa87e3e88f.png)
 

### What is your operating system?

Raspberry Pi OS

### (Optional) Error log? Terminal output? Debug messages?

```bash
/tmp/.mount_MCBedrPWWt6J/usr/bin/mcpelauncher-ui-qt: /tmp/.mount_MCBedrPWWt6J/usr/lib/libselinux.so.1: no version information available (required by /lib/arm-linux-gnueabihf/libgio-2.0.so.0)
/tmp/.mount_MCBedrPWWt6J/usr/bin/msa-ui-qt: /tmp/.mount_MCBedrPWWt6J/usr/lib/libselinux.so.1: no version information available (required by /lib/arm-linux-gnueabihf/libgio-2.0.so.0)
/tmp/.mount_MCBedrPWWt6J/usr/libexec/QtWebEngineProcess: /tmp/.mount_MCBedrPWWt6J/usr/lib/libselinux.so.1: no version information available (required by /lib/arm-linux-gnueabihf/libgio-2.0.so.0)
../../3rdparty/chromium/sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0403
Received signal 11 SEGV_MAPERR 000009801193
#0 ../../3rdparty/chromium/sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0403
../../3rdparty/chromium/sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0403
Received signal 11 SEGV_MAPERR 000009801193
../../3rdparty/chromium/sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0403
[4169:4272:0215/213736.533878:ERROR:service_manager_context.cc(252)] Attempting to run unsupported native service: /tmp/.mount_MCBedrPWWt6J/usr/bin/content_renderer.service
[4169:4272:0215/213736.534424:ERROR:service_manager_context.cc(252)] Attempting to run unsupported native service: /tmp/.mount_MCBedrPWWt6J/usr/bin/content_renderer.service
[4169:4272:0215/213736.534613:ERROR:service_manager_context.cc(252)] Attempting to run unsupported native service: /tmp/.mount_MCBedrPWWt6J/usr/bin/content_renderer.service
```

**Comment by theofficialgman** [comment]
something looks to be going wrong with chome sandboxing on your OS
try launching the appimage without is
```
QTWEBENGINE_CHROMIUM_FLAGS="--enable-logging --log-level=0 --v=3 --single-process --no-sandbox" $HOME/.local/bin/MCBedrock.AppImage
```

**Comment by CreeperCrafter979** [comment]
Thanks, that ended up working!

**Comment by Botspot** [comment]
> something looks to be going wrong with chome sandboxing on your OS try launching the appimage without it
> 
> ```
> QTWEBENGINE_CHROMIUM_FLAGS="--enable-logging --log-level=0 --v=3 --single-process --no-sandbox" $HOME/.local/bin/MCBedrock.AppImage
> ```

@theofficialgman, would it be a good idea to add those flags to the app to prevent this error from happening to other people? I recall that on Bullseye, all electron apps needed the `--disable-seccomp-filter-sandbox` flag to run successfully.

**Comment by theofficialgman** [comment]
> @theofficialgman, would it be a good idea to add those flags to the app to prevent this error from happening to other people? I recall that on Bullseye, all electron apps needed the `--disable-seccomp-filter-sandbox` flag to run successfully.

including the flags shouldn't cause any issues.... There are a few distros I'm aware of that seem to have broken sandboxing across the board. Some of the latest RPM based distros also have this problem. It would be nice if whatever needs to be changed (whether that be kernel or some library) would just be fixed so we don't have to do this.

I've noted these docs which I think are relevant that describe how the sandboxing is implemented and what support is needed from userspace/kernel depending on which is used:

https://chromium.googlesource.com/chromium/src/+/main/docs/linux/sandboxing.md
https://chromium.googlesource.com/chromium/src/+/main/docs/linux/suid_sandbox.md
https://chromium.googlesource.com/chromium/src/+/main/docs/linux/suid_sandbox_development.md
