### ISSUE TITLE
Installed Category and Updates

### ISSUE THREAD

**Issue by ThaPg** [Botspot/pi-apps#1499]
### Cool ideas?

I have installed some apps. Some of them are outdated. And I want to update it. Is it possible to add update button in "Installed" folder and not only in general "Update" folder? 

Or in "Update" folder create separate table for already installed apps.

Thanks!!!

**Comment by Botspot** [comment]
The "Updates" category is visible in all categories, so I'm a bit confused as to what you are requesting.
Are you asking for a way to limit updatable apps to only the ones you have installed?

**Comment by ThaPg** [comment]
Yes. That is what I want. 

Thanks.

**Comment by Botspot** [comment]
> Yes. That is what I want.
> 
> Thanks.

This is a tough call to make. On the one hand, it does make sense for users to not care about updates for apps that are not installed. On the other hand, the Updater is our primary way of notifying most users of improvements being made!
One thing I like about Pi-Apps is how the Updater will tell you when a new app is added. This helps existing users find new stuff.

There is one more thing to consider: if someone is having trouble with an app and it fails to install, they will want to be notified when it is fixed. Did you catch that? There is a legitimate reason for users to be interested in updated apps that are not currently installed.

I'm not sure there is a perfect one-size-fits all solution here. @ThaPg, given the information I've listed above, what is your opinion on this?
