### ISSUE TITLE
[App] Minecraft Bedrock

### ISSUE THREAD

**Issue by mobilegmYT** [Botspot/pi-apps#15]
[Minecraft Bedrock.zip](https://github.com/Botspot/pi-apps/files/5325149/Minecraft.Bedrock.zip)

**Comment by Botspot** [comment]
Pardon my dumb question, but what's the difference between Minecraft Java and Minecraft Bedrock?

**Comment by mobilegmYT** [comment]
Basically, the same, but bedrock has some features live moveable chests and stuff, and a lot of skin packs/worlds are only available through bedrock.

**Comment by mobilegmYT** [comment]
Also, some people like bedrock because since you log in with a google account to prove you have the licence and Minecraft on the app store is only like $6, its much cheaper.

**Comment by mobilegmYT** [comment]
Also technically if your tech savvy enough, you _could_ also play bedrock for free.

**Comment by Botspot** [comment]
Do you think most users would care to have one over the other? I don't want several Minecraft apps in the app store, if there isn't a good reason for it.

**Comment by Botspot** [comment]
But if anybody would prefer one over the other, then no problem! We can distribute both.

**Comment by Botspot** [comment]
> Also technically if your tech savvy enough, you _could_ also play bedrock for free.

Yeah, speaking of that, what will I need to do to test this app?

**Comment by mobilegmYT** [comment]
Well if you bought MC on a google play account, then you can use that. Else, you can use this apk my friend @boomerangos made:

**Comment by Botspot** [comment]
OK. Will try that soon.
After clicking Install, I got this error:
```
/home/pi/pi-apps/apps/Minecraft Bedrock/install: line 10: flatpak: command not found
Failed to download and install!

Command failed!
Close this window to exit.
```

**Comment by mobilegmYT** [comment]
Hmm. It was supposed to install flatpak through apk first.

**Comment by mobilegmYT** [comment]
[Minecraft-Bedrock.zip](https://github.com/Botspot/pi-apps/files/5328693/Minecraft-Bedrock.zip)
Try dis.

**Comment by Botspot** [comment]
Failed again.
```
Running pkg-install...
Some packages can be upgraded. Please consider running sudo apt full-upgrade -y.
These packages will be installed:   flatpak libappstream-glib8 libostree-1-1 libpipewire-0.2-1   xdg-desktop-portal 
Output was: Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  xdg-desktop-portal-gtk
Suggested packages:
  accountsservice
The following NEW packages will be installed:
  flatpak libappstream-glib8 libostree-1-1 libpipewire-0.2-1
  xdg-desktop-portal xdg-desktop-portal-gtk
0 upgraded, 6 newly installed, 0 to remove and 15 not upgraded.
Need to get 1,404 kB of archives.
After this operation, 5,841 kB of additional disk space will be used.
Get:1 http://mirror.pit.teraswitch.com/raspbian/raspbian buster/main armhf libpipewire-0.2-1 armhf 0.2.5-1 [70.5 kB]
Get:2 http://mirror.us.leaseweb.net/raspbian/raspbian buster/main armhf xdg-desktop-portal armhf 1.2.0-1 [154 kB]
Get:3 http://mirror.pit.teraswitch.com/raspbian/raspbian buster/main armhf libappstream-glib8 armhf 0.7.14-1+deb10u1 [113 kB]
Get:4 http://mirror.pit.teraswitch.com/raspbian/raspbian buster/main armhf libostree-1-1 armhf 2019.1-1+rpi1 [236 kB]
Get:5 http://mirror.pit.teraswitch.com/raspbian/raspbian buster/main armhf flatpak armhf 1.2.4-1 [731 kB]
Get:6 http://mirror.pit.teraswitch.com/raspbian/raspbian buster/main armhf xdg-desktop-portal-gtk armhf 1.2.0-1 [99.3 kB]
Fetched 1,404 kB in 2s (612 kB/s)
Selecting previously unselected package libpipewire-0.2-1:armhf.
(Reading database ... 231596 files and directories currently installed.)
Preparing to unpack .../0-libpipewire-0.2-1_0.2.5-1_armhf.deb ...
Unpacking libpipewire-0.2-1:armhf (0.2.5-1) ...
Selecting previously unselected package xdg-desktop-portal.
Preparing to unpack .../1-xdg-desktop-portal_1.2.0-1_armhf.deb ...
Unpacking xdg-desktop-portal (1.2.0-1) ...
Selecting previously unselected package libappstream-glib8:armhf.
Preparing to unpack .../2-libappstream-glib8_0.7.14-1+deb10u1_armhf.deb ...
Unpacking libappstream-glib8:armhf (0.7.14-1+deb10u1) ...
Selecting previously unselected package libostree-1-1:armhf.
Preparing to unpack .../3-libostree-1-1_2019.1-1+rpi1_armhf.deb ...
Unpacking libostree-1-1:armhf (2019.1-1+rpi1) ...
Selecting previously unselected package flatpak.
Preparing to unpack .../4-flatpak_1.2.4-1_armhf.deb ...
Unpacking flatpak (1.2.4-1) ...
Selecting previously unselected package xdg-desktop-portal-gtk.
Preparing to unpack .../5-xdg-desktop-portal-gtk_1.2.0-1_armhf.deb ...
Unpacking xdg-desktop-portal-gtk (1.2.0-1) ...
Setting up libappstream-glib8:armhf (0.7.14-1+deb10u1) ...
Setting up libostree-1-1:armhf (2019.1-1+rpi1) ...
Setting up libpipewire-0.2-1:armhf (0.2.5-1) ...
Setting up xdg-desktop-portal (1.2.0-1) ...
Setting up flatpak (1.2.4-1) ...
Setting up xdg-desktop-portal-gtk (1.2.0-1) ...
Processing triggers for mime-support (3.62) ...
Processing triggers for gnome-menus (3.31.4-3) ...
Processing triggers for libc-bin (2.28-10+rpi1) ...
Processing triggers for man-db (2.8.5-2) ...
Processing triggers for dbus (1.12.20-0+deb10u1) ...
EOOcessing triggers for desktop-file-utils (0.23-4) ...
All packages were installed succesfully.

Note that the directories 

'/var/lib/flatpak/exports/share'
'/home/pi/.local/share/flatpak/exports/share'

are not in the search path set by the XDG_DATA_DIRS environment variable, so
applications installed by Flatpak may not appear on your desktop until the
session is restarted.

Looking for matches…
error: No remote refs found similar to ‘flathub’
Failed to download and install!

Command failed!
Close this window to exit.^A

```

**Comment by mobilegmYT** [comment]
[Minecraft-Bedrock.zip](https://github.com/Botspot/pi-apps/files/5328720/Minecraft-Bedrock.zip)

**Comment by Botspot** [comment]
```
Running pkg-install...
Some packages can be upgraded. Please consider running sudo apt full-upgrade -y.
These packages will be installed:   flatpak 
Output was: Reading package lists...
Building dependency tree...
Reading state information...
The following NEW packages will be installed:
  flatpak
0 upgraded, 1 newly installed, 0 to remove and 15 not upgraded.
Need to get 0 B/731 kB of archives.
After this operation, 3,239 kB of additional disk space will be used.
Selecting previously unselected package flatpak.
(Reading database ... 231676 files and directories currently installed.)
Preparing to unpack .../flatpak_1.2.4-1_armhf.deb ...
Unpacking flatpak (1.2.4-1) ...
Setting up flatpak (1.2.4-1) ...
Processing triggers for dbus (1.12.20-0+deb10u1) ...
EOOcessing triggers for man-db (2.8.5-2) ...
All packages were installed succesfully.

Note that the directories 

'/var/lib/flatpak/exports/share'
'/home/pi/.local/share/flatpak/exports/share'

are not in the search path set by the XDG_DATA_DIRS environment variable, so
applications installed by Flatpak may not appear on your desktop until the
session is restarted.

Looking for matches…
error: No remote refs found similar to ‘io.mrarm.mcpelauncher’
Failed to download and install!

Command failed!
Close this window to exit.

```

**Comment by mobilegmYT** [comment]
Try just runnning `flatpak install io.mrarm.mcpelauncher`

**Comment by Botspot** [comment]
```
pi@raspberrypi:~ $ flatpak install io.mrarm.mcpelauncher

Note that the directories 

'/var/lib/flatpak/exports/share'
'/home/pi/.local/share/flatpak/exports/share'

are not in the search path set by the XDG_DATA_DIRS environment variable, so
applications installed by Flatpak may not appear on your desktop until the
session is restarted.

Looking for matches…
error: No remote refs found similar to ‘io.mrarm.mcpelauncher’
```

**Comment by mobilegmYT** [comment]
If it still doesnt work, download https://dl.flathub.org/repo/appstream/io.mrarm.mcpelauncher.flatpakref and then run `flatpak install /download/location`

**Comment by Botspot** [comment]
That worked. I entered 'Y' to every question flatpak asked me.
Now running `flatpak run io.mrarm.mcpelauncher` launched 'linux minecraft launcher'.
But no menu button showed up.

**Comment by mobilegmYT** [comment]
Try opening from the menu shortcut

**Comment by Botspot** [comment]
That's what I mean. It's not there. Only thing in Menu -> Games is Minecraft Launcher (java version)

**Comment by mobilegmYT** [comment]
1 sec

**Comment by mobilegmYT** [comment]
So nothing like this showed up? 
![Screenshot_2020-10-05_11-37-45](https://user-images.githubusercontent.com/44128563/95113142-37f28580-06ff-11eb-8d11-6631bc665fad.png)

**Comment by Botspot** [comment]
That window does open when I run `flatpak run io.mrarm.mcpelauncher`, but I just wanted to point out that there's no way to launch it apart from the terminal.
So one of the things that needs to be fixed is a start menu button to launch "Linux Minecraft Launcher.
Make sense?

**Comment by mobilegmYT** [comment]
Yes. I found though that after a reboot, the menu bar shortcut does show.

**Comment by mobilegmYT** [comment]
Ask for reboot upon install.
[Minecraft Bedrock .zip](https://github.com/Botspot/pi-apps/files/5337954/Minecraft.Bedrock.zip)

**Comment by Botspot** [comment]
Something isn't right here.
On a stock Raspbian, I get the same error:
```
/home/pi/pi-apps/apps/Minecraft Bedrock /install: line 15: flatpak: command not found
Please press [Enter] to reboot and finish installation.
```
So it looks like your script needs to install flatpak, while currently it does not.

**Comment by mobilegmYT** [comment]
Oops. I think you just need to move the mc install line below the apt install flat oak line.

**Comment by Botspot** [comment]
Oh OK. So now the install script is:
```
# Get dependencies
"${DIRECTORY}/pkg-install" "flatpak" "$(dirname "$0")" || exit 1

#Install program from flatpak
flatpak install flathub io.mrarm.mcpelauncher

read -p 'Please press [Enter] to reboot and finish installation.'
```
Now this error occurs during installation:
```
Looking for matches…
error: No remote refs found similar to ‘flathub’
```

**Comment by mobilegmYT** [comment]
Ok. In that case, lets just make it wget https://dl.flathub.org/repo/appstream/io.mrarm.mcpelauncher.flatpakref

**Comment by Botspot** [comment]
I will not be able to add this app until it actually works on Raspberry Pi OS.
Please fix your install script.

Also, I was not able to get good performance out of it, even after tweaking all the settings. Any way to improve it, or is 10fps unavoidable?

**Comment by Botspot** [comment]
Closing this issue due to your inactivity

**Comment by mobilegmYT** [comment]
[Minecraft-Bedrock.zip](https://github.com/Botspot/pi-apps/files/5366223/Minecraft-Bedrock.zip)

**Comment by mobilegmYT** [comment]
New update: the install script needs to include `sudo apt install gnome-software-plugin-flatpak` as well as `flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo`. This way, we don't need to whet the file and we can use the original install command.

**Comment by Botspot** [comment]
I get:
```
The following packages have unmet dependencies:
 gnome-software-plugin-flatpak : Depends: gnome-software (= 3.30.6-5) but it is not going to be installed
```

**Comment by mobilegmYT** [comment]
Try 
[Minecraft-Bedrock.zip](https://github.com/Botspot/pi-apps/files/5368185/Minecraft-Bedrock.zip)

**Comment by Botspot** [comment]
Even worse, apt says that `pi-package` (Add/Remove Software) will be removed in order to install gnome-software-plugin-flatpak.
```
The following packages will be REMOVED:
  pi-package pi-package-data pi-package-session
The following NEW packages will be installed:
  appstream apt-config-icons gnome-desktop3-data gnome-software
  gnome-software-common gnome-software-plugin-flatpak libcairo-gobject-perl
  libflatpak0 libfwupd2 libglib-object-introspection-perl
  libgnome-desktop-3-17 libgtk3-perl python3-pycurl
  python3-software-properties software-properties-common
  software-properties-gtk
0 upgraded, 16 newly installed, 3 to remove and 0 not upgraded.
```

**Comment by Botspot** [comment]
\o/ It worked!  
By default, Flatpak will ask permission to install io.mrarm.mcpelauncher. I've made it automatically install by adding the `-y` flag to it.  
Also, I appended `sudo` to the beginning of the `flatpak remote-add` command.

You cannot have an install script perform a reboot, and here's why: when you install an app, Pi-Apps (specifically, the `manage` script) marks the app as 'corrupted' before running the App's install script. After the install script finishes successfully, `manage` will change that App's status to 'installed'.  
So if the install script shuts down the system, what will happen? The app's status will still be 'corrupted', since `manage` never exited cleanly.
I've changed it to **ask the user to reboot** to finish the install.

**Comment by mobilegmYT** [comment]
Ayyyy

**Comment by Botspot** [comment]
One problem: Minecraft launcher still does not display in the menu after a reboot.

**Comment by mobilegmYT** [comment]
Hmm. Is the file in .local/applications or /usr/share/applications ?

**Comment by Botspot** [comment]
Neither.

**Comment by Botspot** [comment]
But it does open successfully when I run `flatpak run io.mrarm.mcpelauncher`.

**Comment by mobilegmYT** [comment]
1 sec. I will upload the desktop file to pi-apps-resources.

**Comment by Botspot** [comment]
> 1 sec.

It's been 32 minutes :P

**Comment by mobilegmYT** [comment]
Lol. Here ya go. 
[Minecraft Bedrock.zip](https://github.com/Botspot/pi-apps/files/5368613/Minecraft.Bedrock.zip)

**Comment by Botspot** [comment]
Added.

**Comment by mobilegmYT** [comment]
[Uploading Minecraft Bedrock.zip…]()

**Comment by Botspot** [comment]
I'm assuming running `flatpak uninstall` with a `-y` flag would be good, right?

**Comment by mobilegmYT** [comment]
I believe so
