### ISSUE TITLE
To Botspot, Pi apps

### ISSUE THREAD

**Issue by Ihavetoomanyerrors** [Botspot/pi-apps#150]
I cant install Minecraft Java on my Pi 4. When I try to install it, this message showns: "Failed to install Minecraft Java with install-32 script!" What should I do? Please help me!

**Comment by Ihavetoomanyerrors** [comment]
![2020-12-21-141511_1920x1080_scrot](https://user-images.githubusercontent.com/76432287/102771984-d655c500-4397-11eb-9c40-69b00053d5b9.png)

**Comment by mobilegmYT** [comment]
What does the text above it say? I don't know what language it is so I cant translate it.

**Comment by UntalentedAmateur** [comment]
The Raspberry 4 is a 64-bit system, so it won't like the install-32 option  -- You should be looking to install the 64-bit version.

**Comment by Itai-Nelken** [comment]
> The Raspberry 4 is a 64-bit system, so it won't like the install-32 option -- You should be looking to install the 64-bit version.

@UntalentedAmateur while the RPi is 64bit, the OS he is running should be 32bit if pi-apps tried to install with `install-32`

**Comment by Itai-Nelken** [comment]
@mobilegmYT

Here is a Translation with google translat:

```
cat: / home / pi / pi - apps / data / status / Minecraft Java ': No such file or directory  Installing Minecraft Java with install - 32 script 2020-12-21 14:12:26 - https://github.com/mikehooper/Minecraft/raw/main/setupM c.sh github.com (github.com) resolving.  .. 140.82.121.3 github.com (github.com) [140.82.121.3]: 443 connecting ... connection established.  HTTP request sent, waiting for response ... 302 Found Location: https://raw.githubusercontent.com/mikehooper/Minecraft/main/setupc.sh [track track] - - 2020-12-21 14:12:26 -  Resolving https://raw.githubusercontent.com/mikehooper/Minecraft remain / setupc.sh raw.githubusercontent.com (raw.githubusercontent.com) ... 151.101.11 raw.githubusercontent.com (raw.githubusercontent.com) (  151.101.112.133): 443 connecting ... connection established. HTTP request sent, waiting for panit ... 200 OK length: 3152 (3, 1K) (text / plain) Save location: 'setupmc.sh' setupMc.sh 0  % [.  ...- KB / s home / pi / pi - apps / apps / Minecraft Java / install - 32: line 16: 15569 Shredding arizas wget https://github.com/mikehooper/Minecraft/raw/main/setupc.sh  failed to install the launcher! 
```

Looks like it's Turkish

**Comment by UntalentedAmateur** [comment]
Ok, but how about trying the install-64 option.  It's possible that he's got a 64-bit OS running and just grabbed the wrong install script by mistake.  It's worth a try.

**Comment by Itai-Nelken** [comment]
> Ok, but how about trying the install-64 option. It's possible that he's got a 64-bit OS running and just grabbed the wrong install script by mistake. It's worth a try.

@UntalentedAmateur better to run `uname -m` (I think) it's supposed to show the arch of the OS.
so @Ihavetoomanyerrors run this in terminal and send the output:
```
uname -m
``` 
it should be `armhf` or `armv7l` (32bit) or `arm64` or `aarch64` (64bit)

**Comment by mobilegmYT** [comment]
> Ok, but how about trying the install-64 option.  It's possible that he's got a 64-bit OS running and just grabbed the wrong install script by mistake.  It's worth a try

Pi-apps has OS auto detection. If he was running a 64-bit os, it would have switched to it

**Comment by Botspot** [comment]
> Looks like it's Turkish

Yes it does. The phrase that we're interested in is `parçalama arızası`. Google says that means `shredding failure`. I have no idea what to make of that.

@Ihavetoomanyerrors, please translate your error messages to English so we can help you.

**Comment by mobilegmYT** [comment]
> > Looks like it's Turkish
> 
> Yes it does. The phrase that we're interested in is `parçalama arızası`. Google says that means `shredding failure`. I have no idea what to make of that.
> 
> @Ihavetoomanyerrors, please translate your error messages to English so we can help you.

Itai already translated it to english. See the messages above.

**Comment by Botspot** [comment]
> > @Ihavetoomanyerrors, please translate your error messages to English so we can help you.
> 
> Itai already translated it to english. See the messages above.

Itai's translation translated `parçalama arızası` to `Shredding arizas`. Not helpful. :(

**Comment by Itai-Nelken** [comment]
@Botspot I translated it again (with google) and it came up as this now: `shredding failure`

**Comment by Botspot** [comment]
I'm not sure what shredding meansin this context. Perhaps @Ihavetoomanyerrors can translate it better?

**Comment by Itai-Nelken** [comment]
> Perhaps @Ihavetoomanyerrors can translate it better?

yes, that would be best.
>I'm not sure what shredding means in this context.

maybe it means something like `ignoring error`?

**Comment by Botspot** [comment]
Unfortunately I've had to close this issue due to @Ihavetoomanyerrors's inactivity.

**Comment by Ihavetoomanyerrors** [comment]
Ok

Botspot <notifications@github.com>, 28 Ara 2020 Pzt, 02:18 tarihinde şunu
yazdı:
