### ISSUE TITLE
Add ledcontrol

### ISSUE THREAD

**Issue by Juliandev02** [Botspot/pi-apps#1502]
### What is the name of the app?

ledcontrol

### (Optional) Where is the app hosted?

GitHub.
See https://github.com/Strawberry-Software-Industries/ledcontrol

### About the app

This is a simple program to control the status LEDs of your Raspberry Pi.
Just install this App, and type `ledcontrol` into the Terminal. To change the Behavior of any led, you need root perms. 
Example: `sudo ledcontrol dr` - This will deactivate the red led
###
![image](https://user-images.githubusercontent.com/81520713/154499526-5086b402-4f4e-4392-882d-928c133f029a.png)
:)
Soon i will build armhf Executeables!
If the app should come in, I will also design an icon for it later. 

### Upload file or Add PR Link

[ledcontrol.zip](https://github.com/Botspot/pi-apps/files/8089205/ledcontrol.zip)

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by Botspot** [comment]
This looks interesting and I'm fine with it being added to Pi-Apps.

I vaguely recall that various Raspberry Pi models treated the LEDs differently. I remember being able to control both built-in LEDS on the Pi3, but the method I used would not work for the Pi4.
Also the Pi zero uses its LED differently.
How are these exceptions handled by the program?

**Comment by Juliandev02** [comment]
Currently (as far as I know) the program only works on the Raspberry Pi 4, because I don't know what the LED map looks like on the Pi 3. The same is true for the Pi Zero. I would have to look more closely at how the LED map is on the Pi 3 and the Zero.
I know that led1 is the red power LED and led0 is the green one.

**Comment by Juliandev02** [comment]
I'm sure I'll get it right. I just need to identify which model you have (via Bash Command is possible), and then find the appropriate LED map. 
And yes, the Pi 4 is extremely hard to find. I was extremely lucky that I still got my Pi 4 with 8GB RAM ...

**Comment by theofficialgman** [comment]
closing as prone to breakage (new hardware) and not really useful for desktop users. these are status LEDs and not intended to be utilized by the user (other kernel drivers and hardware interact with them).
