### ISSUE TITLE
FireDM

### ISSUE THREAD

**Issue by Le0X8** [Botspot/pi-apps#1514]
### What is the name of the app?

FireDM

### (Optional) Where is the app hosted?

https://github.com/firedm/FireDM

### About the app

A small tool to download YouTube-videos fast with FireDM based on Python.

### Upload file

[FireDM.zip](https://github.com/Botspot/pi-apps/files/8111130/FireDM.zip)

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by ryanfortner** [comment]
@Le0X8 the zip you provided doesn't have a `description` file (you can also include `credits` if you want)

**Comment by theofficialgman** [comment]
closing since https://github.com/firedm/FireDM 404s since the user has deleted/privated their repo. the script is non-functional because of this
