### ISSUE TITLE
request for eve

### ISSUE THREAD

**Issue by n0mzn0mz** [Botspot/pi-apps#1521]
### What is the name of the app?

eve online

### About the app

its a mmorpg 
you would need the mac version, which runs armv8 i believe

### Upload file

https://www.google.com/search?q=download+eve&ei=OnoVYvKEH9upptQPp-6gsAk&ved=0ahUKEwjyib3Cw5T2AhXblIkEHSc3CJYQ4dUDCA4&uact=5&oq=download+eve&gs_lcp=Cgdnd3Mtd2l6EAMyBwgAELEDEEMyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQ6BwgAEEcQsAM6BwgAELADEEM6CAgAEIAEELEDOgQIABBDSgQIQRgASgQIRhgAUMkIWOoKYMIWaAJwAXgAgAH8AYgB8gSSAQUwLjIuMZgBAKABAcgBCsABAQ&sclient=gws-wiz

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by theofficialgman** [comment]
@n0mzn0mz please confirm:  "I have confirmed that this app can run on Raspberry Pi."
this application does not have a linux version at all, let alone a armhf/arm64 linux version

having a mac version does not help here
