### ISSUE TITLE
"Debian version (bookworm) is too old, update to debian Jessie or newer"

### ISSUE THREAD

**Issue by snek100** [Botspot/pi-apps#1529]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)

### What happened?

I am using a Debian version newer than Jessie.

### Description

I am using a Debian version newer than Jessie, but it seems to not recognize bookworm and assume it is too old. This occurs when trying to install MultiMC5.

### What is your operating system?

OS: Debian GNU/Linux bookworm/sid

### (Optional) Error log? Terminal output? Debug messages?

```bash
OS: Debian GNU/Linux bookworm/sid
OS architecture: 64-bit
Pi-Apps local commit ID: 20bd835902537a03b56e531c48c3106677aa033e
Github latest commit ID: 20bd835902537a03b56e531c48c3106677aa033e	
Kernel: aarch64 5.16.0-1-arm64
Device model: Pine64 RockPro64 v2.1
Ram size: 3.86 GB
Language: en_US.UTF-8

BEGINNING OF LOG FILE:
-----------------------
Installing Necessary Dependencies
Debian version (bookworm) is too old, update to debian Jessie or newer

Failed to install Minecraft Java MultiMC5!
```

**Comment by Botspot** [comment]
@theofficialgman can you take a look at this?

**Comment by theofficialgman** [comment]
Bookworm is an unstable repo. Adding support for it is a feature request, not a bug. The temurin java repo is not available on bookworm since it's an unstable repo. So while we CAN build multimc on bookworm, we can't easily install all the necessary java versions on it.

**Comment by theofficialgman** [comment]
@snek100 oh sorry not sure how my syntax editor missed that
fixed with: https://github.com/Botspot/pi-apps/commit/35f81145f9d546136996973b81d70f869565a4ee

you can try again

**Comment by snek100** [comment]
ok its compiling the launcher. nothing after this went wrong before, so i think the issue is fixed.
