### ISSUE TITLE
Minecraft Bedrock on Raspberry pi os 64bit

### ISSUE THREAD

**Issue by ilobilo** [Botspot/pi-apps#153]
Is it possible to install Minecraft BE on raspberry pi os 64bit?

**Comment by CactiChameleon9** [comment]
Yes have a look here: https://flathub.org/apps/details/io.mrarm.mcpelauncher or https://github.com/ChristopherHX/linux-packaging-scripts/releases (for app image version)
It should, in theory be quite easy to make scripts, however I don't know loads about pi-apps yet

**Comment by ilobilo** [comment]
Thanks!

**Comment by CactiChameleon9** [comment]
I have just made a pull request to add 64 bit installation - however I am unable to test #155

**Comment by CactiChameleon9** [comment]
Now (I think) available in pi apps - feel free to test (and close this issue if you want)

**Comment by Botspot** [comment]
Yes, testers wanted.

**Comment by ilobilo** [comment]
Install-64 script doesn't work:
./install-64: line 11: ./pkg-install: No such file or directory
