### ISSUE TITLE
All contribtours in readme

### ISSUE THREAD

**Issue by iKittyCode** [Botspot/pi-apps#1530]
### Cool ideas?

In the readme you should add a all contributors with people who gave you ideas and also link to the key to follow the github all contributors.

**Comment by Botspot** [comment]
This is a hard one. Pi-Apps has certainly been a group effort in many ways, and many people have helped. But I can't list everybody - the list would drown out everything else.

So if I can't list every single person and website that has helped this project in any way, then where do I draw the line? No matter where I draw the line, those below it will feel unimportant, while those above it will come to expect it. Also I don't want to turn the README into an advertising billboard, where there is a hall of fame for those who would only contribute *if* I agreed to advertise them.

The way I see it, manually advocating for contributors is a slippery slope and would be prone to causing problems.

**Comment by ryanfortner** [comment]
I agree with @Botspot : there are many contributors to this project and it doesn't really make sense to me to list them all on the readme, since you can already view contributors [here](https://github.com/Botspot/pi-apps/graphs/contributors).

**Comment by iKittyCode** [comment]
That's fine but maybe you should try the all contributors bot from
know don't add previous people but only use the bot to add the new people
who give you ideas and bug reports

**Comment by theofficialgman** [comment]
> know don't add previous people but only use the bot to add the new people
who give you ideas

users who give ideas for apps are already rewarded when their app is added to pi-apps
I don't think it would really make sense to maintain a list of people who suggested apps and its really not necessary.

bug reports are always welcome and the credit for them is recorded in the closed issue (and usually in the commit message) on the github already.

I agree with botspot, everything is best left as is.

**Comment by Botspot** [comment]
To boil everything down, I see no way to fairly elevate some contributors over others. Those on the list will all be seen as equals, while those not on the list won't be regarded at all.
Even worse, there is no single metric to rank any user's particular involvement in a given project. After all, there are numerous ways to help: submitting new apps, suggesting an improvement, improving the code, making the pi-apps website, advertising on youtube, helping other users on github or discord, spreading the word to friends, encouraging the devs, etc.

None of the above factors can be measured quantitatively in isolation, much less collectively. Any attempt to do so would inevitably result in the algorithm favoring one type of contribution over another. The solution: don't rank contributors with an algorithm.

And there's no way a bot could do it. 🤣
