### ISSUE TITLE
Can't install WPS Office 64bit (buster)

### ISSUE THREAD

**Issue by fabianmendes** [Botspot/pi-apps#1538]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [x] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)

### What happened?

Unavailable to install, even after downloaded it completely

### Description

After updating pi-apps and also trying to reinstall it from pi-apps

### What is your operating system?

Raspberry Pi 4 4gb, RaspiOS 

### (Optional) Error log? Terminal output? Debug messages?

```bash
I couldn't copy the log..
```

**Comment by Botspot** [comment]
Did WPS *fail* to install, or are you having trouble *finding* it in Pi-Apps?

**Comment by theofficialgman** [comment]
closing due to lack of response
