### ISSUE TITLE
Difficulty installing across profiles.

### ISSUE THREAD

**Issue by UntalentedAmateur** [Botspot/pi-apps#154]
Hi,

I've successfully installed Pi-Apps as the pi user and since added a restricted rights user.  I initially tried to move across the pi-apps install folder, but found it would only run with sudo permissions.  Once I had it running, I went to install Minecraft Java, only to find that it was telling me it was already installed.

I tried a variety of uninstalling and reinstalling options, only to find that once I finally got logged into Minecraft from the limited user account, it crashed repeatedly.

The only way I found to successfully log into Minecraft as the restricted user was to manually copy across the hidden directories from the pi home folder to my restricted user and go from there.

Is there any way to support installing pi-apps into restricted user profiles, or across multiple profiles?  It seems that some of the data is linked to the user profile, and other data is system-wide.

Ta.

**Comment by Itai-Nelken** [comment]
I'm not sure, but I think pi-apps is made to run on administrator user accounts. 

>It seems that some of the data is linked to the user profile, and other data is system-wide.

yes, pi-apps creates some menu shortcuts in `~/.local/share/applications/` which means they are local to the user that installed the app (I think because it doesn't need `sudo` to write files to it). other menu shortcuts go to `/usr/share/applications` that require sudo, but the menu shortcut will appear to all users.

**Comment by Itai-Nelken** [comment]
If I understood you correctly you installed pi-apps using the pi user, then moved the `pi-apps` folder to your other user (that has restricted rights).
if that is correct, than install pi-apps in your other user.

**Comment by UntalentedAmateur** [comment]
>If I understood you correctly you installed pi-apps using the pi user, then moved the pi-apps folder to your other user (that has restricted rights).
if that is correct?

Yes.  That was based off the description in the Github project where it described the install as being self-contained for everything.  I immediately found that I couldn't even get pi-apps to launch.  After some trying of different options, I found that I had to sudo in order to install pi-apps under the limited account, and run it effectively.  The only problem is that I didn't give my restricted user sudo permissions.

I was able to work out in the end where everything was hiding that I needed, but I did find that there were a couple of folders that weren't as cleanly identified and located as I thought they might have been.

My new problem with my restricted user is getting the raspbian desktop to properly retain configuration settings, as there's something hiding deep in the system somewhere and I can't quite find it as yet.  As far as they are concerned, they're happy because Minecraft is installed and working properly with their account, so that's a victory.

For my technical peace of mind I'm going to dig around a bit more.  At least the next restricted user install is going to be much quicker.

Thanks for clearing up some of those details for me.

**Comment by Botspot** [comment]
@UntalentedAmateur Pi-Apps _itself_ is as contained as possible.

Now there's a couple menu buttons and an autostart file outside of the Pi-Apps folder, but those are a necessary evil.

As for the apps you install, those are not contained inside Pi-Apps by any means. Minecraft Java, for example, stores files in `~/.local`, `~/Minecraft`, `~/lwjgl2arm32`, `~/lwjgl3arm32`, `~/lwjgl3arm64`, `~/lwjgl2arm64`, `/usr/share/minecraftjava`.

As far as installing stuff on a restricted account, maybe this approach would be easier:

- Temporarily lift the user restrictions.
- Install the stuff.
- Reinstate the user restrictions.

**Comment by UntalentedAmateur** [comment]
Thank you for your input Botspot, and for the wonderful pi-apps installer.  After digging, I was able to find all of those folders and ensure the restricted user had their own copies of them, and the ~/.minecraft folder.

The only other issue I forgot to fix was ensuring proper chown / chgrp permission setting, but that's a basic Linux admin error of my own fault rather than a pi-apps problem.

It is wonderful to see a set of apps install cleanly into individual userspace like that, it made it feel very OS X-like.  There are a couple of very happy younger Pi users who are starting to cut their teeth on the system who now have Minecraft, thanks to you.
