### ISSUE TITLE
pi-apps Games

### ISSUE THREAD

**Issue by derryktutt** [Botspot/pi-apps#1547]
### Cool ideas?

Could there be a "Online Games" category? I am currently working on a Web Demo.

**Comment by ryanfortner** [comment]
Do you mean something like Twister Web Apps? https://github.com/phoenixbyrd/webapps

**Comment by derryktutt** [comment]
i made a small demo
https://pi-apps-games.glitch.me/

**Comment by jonahXD** [comment]
looks cool

**Comment by derryktutt** [comment]
Maybe we could reuse twister os web apps code

**Comment by theofficialgman** [comment]
we discussed webapps here: https://github.com/Botspot/pi-apps/issues/1791

the general consensus was that they do not fit in with pi-apps
