### ISSUE TITLE
PiKISS GUI cannot be installed

### ISSUE THREAD

**Issue by Rak1ta** [Botspot/pi-apps#1551]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)

### What happened?

PiKISS GUI cannot be installed on Debian Buster (?)

### Description

https://github.com/Jai-JAP/pikiss-gui
```
You'll need the following dependencies:

meson >= 0.57
```
Not [available](https://packages.debian.org/buster-backports/meson) for Debian 10 Buster?

### What is your operating system?

RaspiOS 32bit Debian10

**Comment by Jai-JAP** [comment]
Can you post the error log as meson is installed from pip and not from apt?
