### ISSUE TITLE
SDK for Sphero RVR (Zip included)

### ISSUE THREAD

**Issue by zShqdows** [Botspot/pi-apps#1552]
### What is the name of the app?

Sphero RVR SDK

### (Optional) Where is the app hosted?

https://github.com/sphero-inc/sphero-sdk-raspberrypi-python.git

### About the app

Allows you to interface with the Sphero RVR robot through the Raspberry Pi's UART, This app allows you to use servos, IR sensors, LED's and more. The possibilities are endless.

### Upload file

[Sphero SDK Rev.2.zip](https://github.com/Botspot/pi-apps/files/8165483/Sphero.SDK.Rev.2.zip)

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by zShqdows** [comment]
@Botspot Thoughts?

**Comment by zShqdows** [comment]
@ryanfortner Do you have any interest in this?

**Comment by ryanfortner** [comment]
> @ryanfortner Do you have any interest in this?

I used to mess with sphero stuff, but I don't anymore really.

**Comment by zShqdows** [comment]
> > @ryanfortner Do you have any interest in this?
> 
> I used to mess with sphero stuff, but I don't anymore really.

Ah ok, just wanted to know, hoping that this can be on Pi-Apps someday.
