### ISSUE TITLE
Hello Botspot i install pi apps and i liked to install XSnow i tried it 2 times but it not work for me it still says APT reported an unsigned repository. Try signing it yourself, asking for help as needed. APT reported an unresolvable repository.  Check your Internet connection and try again.

### ISSUE THREAD

**Issue by Jan13295** [Botspot/pi-apps#1556]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [ ] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)

### What happened?

The app wont install

### Description

i dont know what i do here :(

### What is your operating system?

Raspberry Pi OS

### (Optional) Error log? Terminal output? Debug messages?

```bash
APT reported an unsigned repository. Try signing it yourself, asking for help as needed.
APT reported an unresolvable repository.

Check your Internet connection and try again.
```

**Comment by Jai-JAP** [comment]
This is probably not an issue with pi-apps but the cause is your apt sources are misconfigured and also your internet connection is down.

You can google the error output from the command `sudo apt update` for the solution.

**Comment by theofficialgman** [comment]
closing due to lack of response. comment and this can be re-opened if your issue is not fixed @Jan13295
