### ISSUE TITLE
New Website and further website information

### ISSUE THREAD

**Issue by qroft** [Botspot/pi-apps#1559]
### Cool ideas?

Hi there,
i am having trouble with the app as - nearly whenever i start pi-apps there is the information of new apps available.
But it shows me apps that i have not installed - so i always have to uncheck most apps and only have thos checked that i have.
So here are my suggestions, ideas and questions.

1. With every update the last files are some kind of txt/data files. I suggest that these are the info files including the program updates information. If this is so, are those last files like "mandatory" to install? If yes, it would be awesome to mention this somewhere for newbies like me.
3. How can i help in creating a better website? Something with a better filter option, a versioning etc. It could gather the information from the file that you already use and import it into for example a flat file CMS.

I really would love to help out here to push the project forward.
My Pi400 arrived about 2 months ago and i absolutely love it.

**Comment by Botspot** [comment]
> Hi there, i am having trouble with the app as - nearly whenever i start pi-apps there is the information of new apps available. But it shows me apps that i have not installed - so i always have to uncheck most apps and only have those checked that i have. So here are my suggestions, ideas and questions.
> 
> 1. With every update the last files are some kind of txt/data files. I suggest that these are the info files including the program updates information. If this is so, are those last files like "mandatory" to install? If yes, it would be awesome to mention this somewhere for newbies like me.

You seem to be misunderstanding how updates work. Under normal circumstances, you want to leave **all checkboxes checked**. Advanced users who want to avoid updating a particular app or file can uncheck something. But everything else should remain in its default state.
Pi-Apps keeps a local copy of each app-s installation-scripts. When we update an app, you will be asked if you want that particular app to be updated, even if you don't have it installed. I chose this route for transparency reasons, though if you have another idea then please let me know.

> 2. How can i help in creating a better website? Something with a better filter option, a versioning etc. It could gather the information from the file that you already use and import it into for example a flat file CMS.

The pi-apps.io website is maintained by some other contributors, though they have a taken a few of my suggestions. You can find the website repo here: https://github.com/Pi-Apps-Coders/website

> I really would love to help out here to push the project forward. My Pi400 arrived about 2 months ago and i absolutely love it.

Thanks! People like you are who keep this project going. :)

**Comment by theofficialgman** [comment]
> > 1. With every update the last files are some kind of txt/data files. I suggest that these are the info files including the program updates information. If this is so, are those last files like "mandatory" to install? If yes, it would be awesome to mention this somewhere for newbies like me.
> 
> You seem to be misunderstanding how updates work. Under normal circumstances, you want to leave **all checkboxes checked**. Advanced users who want to avoid updating a particular app or file can uncheck something. But everything else should remain in its default state. Pi-Apps keeps a local copy of each app-s installation-scripts. When we update an app, you will be asked if you want that particular app to be updated, even if you don't have it installed. I chose this route for transparency reasons, though if you have another idea then please let me know.

when I first used pi-apps I was also somewhat confused by this. Why do we even need to tell the user we are updating local apps scripts from apps not even installed? I feel like that should just always happen regardless. Just have one tickbox with something like "Update pi-apps app repository" or something like this instead of all the individual apps

**Comment by qroft** [comment]
Thanks so much you both for your answers! To be honest, if this update procedure is mentioned somewhere, i have not read it and thus i feel ashamed. Sorry for not RTFM once gain - my fault!
But now, as @Botspot explained it to me, it is absolutely understandable and seems perfect for me how you do it.
Will immediately update pi-apps now! :)

I also think like @theofficialgman idea, as noobs like me certainly will be confused and a sentence like "Update pi-apps repository" is super easy to understand.

One love and greetings from this corner of the planet!
