### ISSUE TITLE
VMware Horizon Client installaton error.

### ISSUE THREAD

**Issue by Rak1ta** [Botspot/pi-apps#1560]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)

### What happened?

Error during installation. It is also not completely deleted if an error occurs.

### Description

[install-fail-VMware Horizon Client.log](https://github.com/Botspot/pi-apps/files/8188488/install-fail-VMware.Horizon.Client.log)

### What is your operating system?

RaspiOS 32bit Debian10

### (Optional) Error log? Terminal output? Debug messages?

Installed ->
![Безымянный](https://user-images.githubusercontent.com/88277343/156834814-1f7e8089-b44d-4d7f-89b6-21bf9d470b94.png)

**Comment by Botspot** [comment]
Looks like there is a bug in @cycool29's deb.
```
Unpacking vmware-horizon-client (1.0) ...

Unpacking pi-apps-c8854f57 (1.0) ...

sed: -e expression #1, char 5: unterminated `s' command

ln: failed to create symbolic link '/usr/lib/libudev.so.0' -> '': No such file or directory

dpkg: error processing package vmware-horizon-client (--configure):

 installed vmware-horizon-client package post-installation script subprocess returned error exit status 1

dpkg: dependency problems prevent configuration of pi-apps-c8854f57:

 pi-apps-c8854f57 depends on vmware-horizon-client; however:

  Package vmware-horizon-client is not configured yet.
```

**Comment by cycool29** [comment]
What is your output of `dpkg -S libudev.so.1 | grep ​'​libudev.so.1​$'​ | sed ​'​s/.​*​: //g​'​`?

**Comment by Rak1ta** [comment]
@cycool29 
```
pi@raspberrypi:~ $ dpkg -S libudev.so.1 | grep ​'​libudev.so.1​$'​ | sed ​'​s/.​*​: //g​'
sed: -e выражение #1, символ 1: неизвестная команда: `�'
```
sed: -e expression #1, character 1: unknown command: `�'

**Comment by Botspot** [comment]
@Rak1ta This should be fixed now.

**Comment by Rak1ta** [comment]
@Botspot working 👌
