### ISSUE TITLE
Scrcpy won't launch from shortcut

### ISSUE THREAD

**Issue by Rak1ta** [Botspot/pi-apps#1561]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)

### What happened?

Scrcpy won't launch from shortcut

### Description

Scrcpy won't run with shortcut because android.sh is missing. But it starts with the **_scrcpy_** command, as stated in the readme of the [program](https://github.com/Genymobile/scrcpy)
Is this command wrong? `bash -c 'cd /home/pi/scrcpy ; /home/pi/scrcpy/android.sh'`
Thanks!
![Безымянный](https://user-images.githubusercontent.com/88277343/156840113-573f8bf9-1eb7-41e6-a1e6-46fec6cb6e7f.png)

### What is your operating system?

RaspiOS 32bit Debian10

**Comment by Botspot** [comment]
I just tested this and encountered the same problem.

**Comment by Botspot** [comment]
> Scrcpy won't run with shortcut because android.sh is missing. But it starts with the **_scrcpy_** command, as stated in the readme of the [program](https://github.com/Genymobile/scrcpy)

My only guess is that someone on Scrcpy's end changed `install_release.sh` to no longer allow portable execution.

**Comment by Botspot** [comment]
Should be fixed in commit https://github.com/Botspot/pi-apps/commit/a6a528cc4c6240fb98f7c8fb16a3206c68582bc0.
