### ISSUE TITLE
 The link to the Tor file has an error.

### ISSUE THREAD

**Issue by Rak1ta** [Botspot/pi-apps#1563]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)

### What happened?

Download link error.

### Description
An extra character before the version number.
![Безымянный](https://user-images.githubusercontent.com/88277343/156850688-d4602dc6-48fb-492a-a09a-e4edc9e93e06.png)

### What is your operating system?

RaspiOS 32bit Debian10

**Comment by Itai-Nelken** [comment]
Thanks!
this has already been fixed in commit 2ce7b031dbda50d1d37543b6f6a14bf9700779e3

**Comment by Itai-Nelken** [comment]
Thanks!

**Comment by Botspot** [comment]
> Thanks! this has already been fixed in commit [2ce7b03](https://github.com/Botspot/pi-apps/commit/2ce7b031dbda50d1d37543b6f6a14bf9700779e3)

No, that was for the Github Actions update script.

Looks like the same typo made its way into both the GitHub update script and into the install-32. I just fixed it in commit https://github.com/Botspot/pi-apps/commit/0b24c9ad44370709e3574d38ba29b7877b741380.

@Rak1ta, thank you for reporting.
