### ISSUE TITLE
Minecraft Dungeons

### ISSUE THREAD

**Issue by rbcoder117** [Botspot/pi-apps#1567]
### What is the name of the app?

Minecraft Dungeons

### (Optional) Where is the app hosted?

https://www.minecraft.net/en-us/about-dungeons

### About the app

It is minecraft rpg. Official by mojang. We already have so much other mc LoLL

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [] I have confirmed that this app can run on Raspberry Pi.

**Comment by Botspot** [comment]
Does this run on Raspberry Pi?

**Comment by rbcoder117** [comment]
sry for late reply but works with wine

**Comment by nolan-the-dev** [comment]
the rpi does not have the enough power to run that
