### ISSUE TITLE
shellcheck does not have -S option (leading to false redownloads)

### ISSUE THREAD

**Issue by theofficialgman** [Botspot/pi-apps#1573]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)

### What happened?

executed the update script which causes unnecessary api script redownloads

### Description

the -S option (severity) was added in shellcheck v0.6.0

ubuntu bionic has version v0.4.6 so it does not include this option and causes shellcheck itself to error
debian buster (without the backports repo) also it too old and only includes v0.5.0

### What is your operating system?

L4T Ubuntu Bionic

### (Optional) Error log? Terminal output? Debug messages?

```bash
Updater mode: gui


Checking for online changes... Done
Scanning apps... Done
Scanning files... Done

unrecognized option `-S'

Usage: shellcheck [OPTIONS...] FILES...
  -e CODE1,CODE2..  --exclude=CODE1,CODE2..  exclude types of warnings
  -f FORMAT         --format=FORMAT          output format
  -C[WHEN]          --color[=WHEN]           Use color (auto, always, never)
  -s SHELLNAME      --shell=SHELLNAME        Specify dialect (sh,bash,dash,ksh)
  -x                --external-sources       Allow 'source' outside of FILES.
  -V                --version                Print version information

Downloading updater script to repair syntax error
unrecognized option `-S'

Usage: shellcheck [OPTIONS...] FILES...
  -e CODE1,CODE2..  --exclude=CODE1,CODE2..  exclude types of warnings
  -f FORMAT         --format=FORMAT          output format
  -C[WHEN]          --color[=WHEN]           Use color (auto, always, never)
  -s SHELLNAME      --shell=SHELLNAME        Specify dialect (sh,bash,dash,ksh)
  -x                --external-sources       Allow 'source' outside of FILES.
  -V                --version                Print version information

Downloading api script to repair syntax error
```

**Comment by theofficialgman** [comment]
also fyi, the gui script has an error output (you can tell because shellcheck returns red which is only used for error)

<pre><b>In gui line 514:</b>

      if [ ! -f &quot;${DIRECTORY}/apps/$app/icon-64.png&quot; ] &amp;&amp; [ ! -f &quot;${DIRECTORY}/apps/$app/icon-24.png&quot; ] &amp;&amp; [ -f &quot;${DIRECTORY}/apps/$app/&quot;*.png ] &amp;&amp; command -v convert &gt;/dev/null ;then

<font color="#CC0000">                                                                                                                ^-- SC2144: -f doesn&apos;t work with globs. Use a for loop.</font></pre>

**Comment by theofficialgman** [comment]
so I guess one way to fix this would be to instead grep the output for `[31m` which is bold red
`shellcheck --color gui | grep '\[31m'` (add in -q for 0 or 1 output as normal)

**Comment by Botspot** [comment]
@theofficialgman, Should be fixed now. Thanks for the grep idea.
