### ISSUE TITLE
Wrong link from jGRASP IDE. 

### ISSUE THREAD

**Issue by Rak1ta** [Botspot/pi-apps#1577]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)

### What happened?

jGRASP IDE won't load

### Description

`wget 'https://www.jgrasp.org/dl4g/jgrasp/jgrasp206_07.zip'`
Only version _**206_08**_ or _**206_09**_ (latest) is available for download. Thanks! 
I do not use the program, I did not check the performance / differences between versions.

### What is your operating system?

RaspiOS 32bit Debian10

**Comment by Botspot** [comment]
Thank you for reporting. This should be fixed now.
