### ISSUE TITLE
Glorious model o and gmmk software

### ISSUE THREAD

**Issue by FlashFire900** [Botspot/pi-apps#158]
I would like to be able to edit my settings on my keyboard and mouse without having to switch to my laptop. Both the keyboard and mouse are pretty popular so I thought it would be a great

**Comment by Botspot** [comment]
I'm afraid this is not possible.

Both applications are distributed as x86 Windows EXEs. And Raspberry Pi OS is ARM Linux.  
So not only would we have to emulate the binaries on the RPi's ARM processor, we'd also have to spoof a Windows filesystem, kernel, and device tree.

That may be possible using emulation and WINE, but I wouldn't hold your breath - especially considering that both applications are meant to communicate with the mouse/keyboard using USB. (and USB communication through two virtualization layers can be hit-or-miss.)
