### ISSUE TITLE
GNURadio and CubicSDR

### ISSUE THREAD

**Issue by DTTNWO** [Botspot/pi-apps#1581]
### What is the name of the app?

GNURadio, CubicSDR

### (Optional) Where is the app hosted?

GNURadio can be found in the default Add / Remove Software repository for the latest release of Raspberry Pi OS 64 bit. 

CubicSDR can be installed with apt install cubicsdr 

### About the app

Both of the apps are Software Defined Radio applications, along side of several extra code block packages which can be added for increase feature functionality. One is an easy to use SDR waterfall visualiser and the other is a SDR block IDE. Both, I assume, would be relatively simple to add to this app and it might bring further eyes to the project. I saw another post about SDR apps from Windoze and thought this was a clean suggestion. Thanks.

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by theofficialgman** [comment]
no SDR radio projects exist in pi-apps, see package app requirements: https://github.com/Botspot/pi-apps/issues/185
