### ISSUE TITLE
my app request 

### ISSUE THREAD

**Issue by jonahXD** [Botspot/pi-apps#1586]
### What is the name of the app?

jojobears cool PYTHON GAMES AND HAX

### (Optional) Where is the app hosted?

https://github.com/jonahXD/python-cool-stuff

### About the app

you can play a game and hack

### Upload file or Add PR Link

[python-cool-stuff-cool.zip](https://github.com/Botspot/pi-apps/files/8225191/python-cool-stuff-cool.zip)

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by zShqdows** [comment]
As of now, I don't think there is enough information on your app, maybe try adding more information to your request.

**Comment by theofficialgman** [comment]
I will need to edit the issue template but I thought it was clear enough. 
if you have the app hosted on github please put the link to it, not just tell us its hosted on github 😆

**Comment by zShqdows** [comment]
> I thought it was clear enough. 
> 
> if you have the app hosted on github please put the link to it, not just tell us its hosted on github 😆 
> 
> ```
> 
>       label: (Optional) Where is the app hosted?
> 
>       placeholder: Ex - Github link, Gitlab link, Sourceforge link
> 
> ```

Agreed

**Comment by jonahXD** [comment]
Done

**Comment by jonahXD** [comment]
Also added the button for pi apps in readme.md

**Comment by Crilum** [comment]
@jonahXD Can you create a Pi-App with The `New App` button in Pi-Apps Settings?

![image](https://user-images.githubusercontent.com/91354257/158263674-658a7413-f1ca-4999-ad76-f5c2c2ff8801.png)

**Comment by jonahXD** [comment]
@Crilum I've done that just need to do it again and sign in on pi to get it (I reimage my pi )

**Comment by theofficialgman** [comment]
for now, I'm going to close this, as I think [python-cool-stuff](https://github.com/jonahXD/python-cool-stuff) doesn't have enough substance, structure, or direction to include in pi-apps

jonahXD, if you eventually add something significant to your repo, feel free to comment here again and it can be re-considered
