### ISSUE TITLE
Dot Matrix drawing app

### ISSUE THREAD

**Issue by Crilum** [Botspot/pi-apps#1589]
### What is the name of the app?

Dot Matrix

### (Optional) Where is the app hosted?

https://github.com/lainsce/dot-matrix

### About the app

This would be a way cool app to have in Pi-Apps, but Bullseye doesn't have GTK4 packages, to be able to build it..

![screenshot](https://github.com/lainsce/dot-matrix/blob/main/data/shot-dark.png?raw=true)

This would be able to run on the Raspberry Pi if gtk4 were available.

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [x] I have confirmed that this app can run on Raspberry Pi.

**Comment by Sussy-OS** [comment]
awesome request! I'll see what I can do to try to get this to work. :)

**Comment by derryktutt** [comment]
https://discourse.gnome.org/t/installing-libgtk-4-0-on-raspberry-debian-os/6216

**Comment by Crilum** [comment]
@derryktutt Thanks for linking that, but it doesn't work:
```
sudo apt install -t experimental libgtk-4-1 libgtk-4-dev
Hit:1 https://apt.mopidy.com buster InRelease
Hit:2 https://itai-nelken.github.io/weekly-box86-debs/debian  InRelease        
Hit:3 http://ppa.launchpad.net/spocon/lovspotify/ubuntu bionic InRelease       
Hit:4 http://deb.debian.org/debian experimental InRelease                      
Ign:5 https://download.puffinbrowser.com/repo stable InRelease                 
Hit:6 http://archive.raspberrypi.org/debian bullseye InRelease      
Hit:7 https://download.puffinbrowser.com/repo stable Release
Hit:8 http://raspbian.raspberrypi.org/raspbian bullseye InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package libgtk-4-1 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libgtk-4-1' has no installation candidate
E: Unable to locate package libgtk-4-dev

```

**Comment by leha-code** [comment]
That's because it is not in the official repos yet

**Comment by Crilum** [comment]
Well yes, but I added the experimental repo which supposedly has gtk4, but it didn't work.

**Comment by cycool29** [comment]
> Well yes, but I added the experimental repo which supposedly has gtk4, but it didn't work.

[`libgtk-4-dev`](https://packages.debian.org/experimental/libgtk-4-dev) doesn't have armhf build, so it won't install.
But it does have armhf build in [bookworm](https://packages.debian.org/bookworm/libgtk-4-dev).

`libgtk-4-1` is in [bookworm](https://packages.debian.org/bookworm/libgtk-4-1) and [sid](https://packages.debian.org/sid/libgtk-4-1), but not experimental.

Anyway, all of them are not possible to install on Raspbian, you will get into dependencies hell.

```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libgtk-4-1 : Depends: libc6 (>= 2.33) but 2.31-13+rpt2+rpi1+deb11u2 is to be installed
              Depends: libcloudproviders0 (>= 0.3.1) but it is not going to be installed
              Depends: libglib2.0-0 (>= 2.70.0) but 2.66.8-1 is to be installed
              Depends: libpango-1.0-0 (>= 1.50.3) but 1.46.2-3 is to be installed
              Depends: libpangocairo-1.0-0 (>= 1.50.0) but 1.46.2-3 is to be installed
              Depends: libpangoft2-1.0-0 (>= 1.50.0) but 1.46.2-3 is to be installed
              Depends: libwayland-client0 (>= 1.20.0) but 1.18.0-2~exp1.1 is to be installed
              Depends: libwayland-egl1 (>= 1.20.0) but 1.18.0-2~exp1.1 is to be installed
              Depends: libgtk-4-common (>= 4.6.1+ds-1) but it is not installable
              Recommends: libgtk-4-bin but it is not installable
              Recommends: librsvg2-common (>= 2.52.0) but 2.50.3+dfsg-1 is to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by Crilum** [comment]
I got `libgtk-4-dev` and `libgtk-4-1` installed, with only two dependencies that gave me trouble, but now I think I can build dot-matrix.

**Comment by Crilum** [comment]
So, if you run arm64, you can actually just install Dot Matrix with Flatpak. I asked the main dev if he could enable armhf Flatpaks, but he didn't know how.

**Comment by Crilum** [comment]
Here is a Pi-App for 64-bit: 
[Dot Matrix.zip](https://github.com/Botspot/pi-apps/files/8483524/Dot.Matrix.zip)

It just uses Flatpak (with `flatpak_install()`) to install `io.github.lainsce.DotMatrix`.

**Comment by Crilum** [comment]
Hey, @Botspot (or @theofficialgman), this is ready to be added (if you're ok with it), it's 64 bit only, and 32-bit won't be available (Flatpak is phasing out support for 32-bit arm apps), but it's a really cool app!
