### ISSUE TITLE
psutil and pip is missing

### ISSUE THREAD

**Issue by TheHeroCraft1579** [Botspot/pi-apps#159]
CommanderPi won't start because it doesn't check if pip and psutil is installed

**Comment by Botspot** [comment]
Would running `sudo apt install pip psutil` solve the problem?

If so I can add those packages to the install script.

**Comment by TheHeroCraft1579** [comment]
Yeah i fixed it with
`sudo apt-get install python3-pip`
`sudo pip install psutil`

**Comment by Botspot** [comment]
The author of CommanderPi has fixed this for you in his install script.

See: https://github.com/Jack477/CommanderPi/issues/43
