### ISSUE TITLE
OBS Studio Unable to run on Bullseye 32/64bit

### ISSUE THREAD

**Issue by theofficialgman** [Botspot/pi-apps#1592]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)

### What happened?

OBS deb is built on buster and requires libpython3.7m.so.1.0 when executing `obs`. This is not available in bullseye as it uses python3.9. The deb itself installs (which is why there have been no error messages) but the software does not run.

### Description

<img width="548" alt="Screenshot 2022-03-12 180708" src="https://user-images.githubusercontent.com/28281419/158038109-9ac68c15-d996-460c-90b3-60fc94e78518.png">

@ryanfortner A deb for OBS studio will need to be built directly on bullseye for 32/64bit in addition to the current buster 32/64bit deb.

### What is your operating system?

Bullseye 32bit and 64bit Raspberry PIOS Releases

**Comment by ryanfortner** [comment]
Ill add this to my to-do list, should be able to compile soon.

**Comment by ryanfortner** [comment]
Here is an arm64 bullseye deb I just compiled, I tested it and it works. https://github.com/ryanfortner/ryanfortner/releases/download/1002/obs-studio_27.2.0-101-g358ef281c_arm64.deb

**Comment by theofficialgman** [comment]
@ryanfortner were you able to compile the armhf bullseye deb as well?
I've got confirmation from a user that the `libxcb-util.so.0` library hack is also no longer necessary since you compiled on native bullseye, so I will be removing that as well

**Comment by ryanfortner** [comment]
> @ryanfortner were you able to compile the armhf bullseye deb as well? I've got confirmation from a user that the `libxcb-util.so.0` library hack is also no longer necessary since you compiled on native bullseye, so I will be removing that as well

Yep, just compiled armhf version and updated the install-32 script. Also, I changed the scripts so that the library hack is only run on bullseye installs.

**Comment by theofficialgman** [comment]
no its not necessary at all, I went ahead and added my own commit and pushed
your PR had multiple issues (incorrect links, etc) but you did upload the debs to your github so all is fine now
https://github.com/Botspot/pi-apps/commit/0112d125eea852cfe751034cbbe48050f4ca3cca

**Comment by ryanfortner** [comment]
Thanks!

**Comment by Crilum** [comment]
My OBS install is still broken:
```
$ obs
Attempted path: share/obs/obs-studio/locale/en-US.ini
Attempted path: /usr/share/obs/obs-studio/locale/en-US.ini
Attempted path: share/obs/obs-studio/locale.ini
Attempted path: /usr/share/obs/obs-studio/locale.ini
Attempted path: share/obs/obs-studio/themes/Dark.qss
Attempted path: /usr/share/obs/obs-studio/themes/Dark.qss
info: Physical Cores: 4, Logical Cores: 4
info: Physical Memory: 3795MB Total, 156MB Free
info: Kernel Version: Linux 5.10.103-v8+
info: Distribution: "Raspbian GNU/Linux" "11"
info: Session Type: x11
info: Window System: X11.0, Vendor: The X.Org Foundation, Version: 1.20.11
info: Qt Version: 5.15.2 (runtime), 5.15.2 (compiled)
info: Portable mode: false
Attempted path: share/obs/obs-studio/themes/Dark/no_sources.svg
Attempted path: /usr/share/obs/obs-studio/themes/Dark/no_sources.svg
QMetaObject::connectSlotsByName: No matching signal for on_tbar_position_valueChanged(int)
QMetaObject::connectSlotsByName: No matching signal for on_actionShowTransitionProperties_triggered()
QMetaObject::connectSlotsByName: No matching signal for on_actionHideTransitionProperties_triggered()
info: OBS 27.2.0-103-g02e541038 (linux)
info: ---------------------------------
info: ---------------------------------
info: audio settings reset:
	samples per sec: 48000
	speakers:        2
info: ---------------------------------
info: Initializing OpenGL...
/usr/bin/obs: line 2: 29774 Segmentation fault      MESA_GL_VERSION_OVERRIDE=3.3 /usr/bin/obs-exec "$@"
```

**Comment by ryanfortner** [comment]
Hmm.. that's weird because it was working on my install just 24 hours ago.

Have you tried an `apt update/upgrade`?

**Comment by Crilum** [comment]
did one right before I updated Pi-Apps, which updated OBS.

**Comment by Crilum** [comment]
I guess @cycool29 already posted this problem in #1479
