### ISSUE TITLE
Planet Launcher

### ISSUE THREAD

**Issue by leha-code** [Botspot/pi-apps#1599]
### What is the name of the app?

Planet Launcher

### (Optional) Where is the app hosted?

https://github.com/mcpiscript/planet

### About the app

It's a launcher that actually saves stuff and etc for mcpi. 

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [x] I have confirmed that this app can run on Raspberry Pi.

**Comment by leha-code** [comment]
It could be added as an option in the mcpi install script

**Comment by ryanfortner** [comment]
Link is incorrect, should be https://github.com/mcpiscript/planet
