### ISSUE TITLE
Unable to find update-status during update

### ISSUE THREAD

**Issue by mobilegmYT** [Botspot/pi-apps#16]
Got these errors every time during a update:
`/home/pi/pi-apps/manage: line 170: /home/pi/pi-apps/data/update-status/Arduino: No such file or directory
/home/pi/pi-apps/manage: line 170: /home/pi/pi-apps/data/update-status/BalenaEtcher: No such file or directory
/home/pi/pi-apps/manage: line 170: /home/pi/pi-apps/data/update-status/Chromium Media Edition: No such file or directory
/home/pi/pi-apps/manage: line 170: /home/pi/pi-apps/data/update-status/CommanderPi: No such file or directory
/home/pi/pi-apps/manage: line 170: /home/pi/pi-apps/data/update-status/Conky: No such file or directory
/home/pi/pi-apps/manage: line 170: /home/pi/pi-apps/data/update-status/Cool Retro Term: No such file or directory
/home/pi/pi-apps/manage: line 170: /home/pi/pi-apps/data/update-status/Cura: No such file or directory
/home/pi/pi-apps/manage: line 170: /home/pi/pi-apps/data/update-status/Discord: No such file or directory
/home/pi/pi-apps/manage: line 170: /home/pi/pi-apps/data/update-status/FreeCAD: No such file or directory
/home/pi/pi-apps/manage: line 170: /home/pi/pi-apps/data/update-status/FreeCAD (precompiled): No such file or directory
/home/pi/pi-apps/manage: line 170: /home/pi/pi-apps/data/update-status/Minecraft: No such file or directory
/home/pi/pi-apps/manage: line 179: /home/pi/pi-apps/data/update-status/Minecraft-Bedrock: No such file or directory
/home/pi/pi-apps/manage: line 170: /home/pi/pi-apps/data/update-status/piKiss: No such file or directory
/home/pi/pi-apps/manage: line 170: /home/pi/pi-apps/data/update-status/Pi Power Tools: No such file or directory
/home/pi/pi-apps/manage: line 170: /home/pi/pi-apps/data/update-status/Raspi2png: No such file or directory
/home/pi/pi-apps/manage: line 170: /home/pi/pi-apps/data/update-status/TBOPlayer: No such file or directory
/home/pi/pi-apps/manage: line 170: /home/pi/pi-apps/data/update-status/template: No such file or directory
/home/pi/pi-apps/manage: line 170: /home/pi/pi-apps/data/update-status/Windows 10 Theme: No such file or directory
`

**Comment by Botspot** [comment]
Run this:

    mkdir ~/pi-apps/data/update-status

**Comment by Botspot** [comment]
Will add that same line to the `manage` script soon.

**Comment by mobilegmYT** [comment]
Also, there are these errors running `createapp`
cat: /home/pi/pi-apps/apps//website: No such file or directory
cat: /home/pi/pi-apps/apps//description: No such file or directory

**Comment by Botspot** [comment]
> Also, there are these errors running `createapp`
> cat: /home/pi/pi-apps/apps//website: No such file or directory
> cat: /home/pi/pi-apps/apps//description: No such file or directory

You can ignore those. They're harmless. I can suppress them when I get around to it.

**Comment by Botspot** [comment]
Unfortunately for you, any apps you installed while the `update-status` directory was missing, Pi-Apps has not stored status info for them. So you can't really know if an App is currently installed or not.

**Comment by Botspot** [comment]
I'm going to leave this open until I fix both of your issues.

**Comment by Botspot** [comment]
Fixed both now with commit 8b7a2d0fc0eb8c45615eb1dd75d11af11314258e and f796b45d89144124d3b01b8c54d27486003d3985.
