### ISSUE TITLE
SysMonTask not showing CPU temperature

### ISSUE THREAD

**Issue by Pythonic456** [Botspot/pi-apps#1611]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)

### What happened?

SysMonTask won't show CPU temp

### Description

![Screenshot from 2022-03-18 21-19-20](https://user-images.githubusercontent.com/56113118/159084465-4150df85-c411-4129-a861-8e9a4dffa71d.png)
```pi@raspberrypi4b:~ $ python3
Python 3.9.2 (default, Mar 12 2021, 04:06:34) 
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import psutil
>>> psutil.sensors_temperatures()
{'cpu_thermal': [shwtemp(label='', current=55.504, high=None, critical=None)]}
>>> 
```
If you need any extra info please let me know :)

### What is your operating system?

Raspberry Pi OS Bullseye 32-bit

**Comment by ryanfortner** [comment]
You might want to open an issue on sysmontask's repo: https://github.com/KrispyCamel4u/SysMonTask
