### ISSUE TITLE
luteris

### ISSUE THREAD

**Issue by rbcoder117** [Botspot/pi-apps#1613]
### What is the name of the app?

luteris

### About the app

to run games

### Confirmations

- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.
- [X] I have confirmed that this app is legal and not piracy.

**Comment by open-sorcerer64** [comment]
To be closed as we're trying to get `LUTRIS` running on Raspberry Pi OS in #545 

@Botspot

**Comment by rbcoder117** [comment]
ok
