### ISSUE TITLE
syntax error in updater

### ISSUE THREAD

**Issue by TechDudie** [Botspot/pi-apps#1615]
![2022-03-19-182133_1680x1050_scrot](https://user-images.githubusercontent.com/73961295/159141784-aeadba72-c720-460f-85f9-10108f98551e.png)
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)

### What happened?

./updater spits out a syntax error

### Description

updater gave me a syntax error, if the update was meant to fix this, you can close this, and how ironic

### What is your operating system?

rpi buster

### (Optional) Error log? Terminal output? Debug messages?

```bash
icons/vector/background-3d-dark.svg was updated successfully.
icons/vector/badge-dark.svg was updated successfully.
icons/vector/badge-light.svg was updated successfully.
icons/vector/error.svg was updated successfully.
icons/vector/logo-3d-dark.svg was updated successfully.
icons/vector/logo-glow.svg was updated successfully.
icons/vector/logo-simple.svg was updated successfully.
icons/vector/logo.svg was updated successfully.
icons/vector/logo-text.svg was updated successfully.
icons/vector/splashscreen-original.svg was updated successfully.
install was updated successfully.
manage was updated successfully.
preload was updated successfully.
README.md was updated successfully.
settings was updated successfully.
updater was updated successfully.
./updater: line 205: ast: command not found
cat: /home/pi/pi-apps/data/update-status/updatable-apps: No such file or directory
cat: /home/pi/pi-apps/data/update-status/updatable-files: No such file or directory
./updater: line 241: syntax error near unexpected token `}'
./updater: line 241: `}'
pi@raspberrypi:~/pi-apps $
```

**Comment by open-sorcerer64** [comment]
![UMM](https://user-images.githubusercontent.com/78641958/159151382-3a1cc5cf-6fb6-4c3a-8c62-4c31c79eadc5.png)


I don't get the same problem on the latest pi-apps version

**Comment by Itai-Nelken** [comment]
This happens sometimes when the updater updates itself while running. If you run the updater again, does it still error?

**Comment by TechDudie** [comment]
no, it works now
