### ISSUE TITLE
KeePassXC dependencies missing

### ISSUE THREAD

**Issue by milada-horakova** [Botspot/pi-apps#1618]
application installed via pi-apps doesn't start because of unmet dependencies.
Running twister os 2.1.2 on raspberry pi 4.

```
$ keepassxc
keepassxc: /lib/arm-linux-gnueabihf/libykpers-1.so.1: version `LIBYKPERS_1.20' not found (required by keepassxc)
keepassxc: /lib/arm-linux-gnueabihf/libm.so.6: version `GLIBC_2.29' not found (required by keepassxc)
```

**Comment by ryanfortner** [comment]
I must have compiles using bullseye, I’ll recompile it later today.

**Comment by ryanfortner** [comment]
ok @theofficialgman I've compiled new debs and uploaded them to the repository. Can you run your github action manually so the scripts can update please?

**Comment by theofficialgman** [comment]
the github actions ran automatically. I've merged so this should be fixed now @milada-horakova 

going to close this, please send a message if it still doesn't work

**Comment by theofficialgman** [comment]
@ryanfortner reopening. now `libreadline7` is a dependency and thats not available on bullseye. `libreadline8` is now used in bullseye with different .so versions to go with it.
looks like we will need separate debs for buster and bullseye again.

**Comment by ryanfortner** [comment]
I'll compile buster debs and push the changes later today.

**Comment by theofficialgman** [comment]
> I'll compile buster debs and push the changes later today.

the debs you compiled are buster, we need bullseye debs again 😆 . we need separate debs
so I suggest keeping whichever version you want in your apt repo and putting the other in pi-apps-coders or somewhere similar

**Comment by ryanfortner** [comment]
I meant Bullseye, sorry :)

**Comment by ryanfortner** [comment]
closing since https://github.com/Botspot/pi-apps/pull/1638 was merged.
