### ISSUE TITLE
Stremio

### ISSUE THREAD

**Issue by fabianmendes** [Botspot/pi-apps#162]
May you please make it available for pi-apps? 
https://github.com/Stremio/stremio-addon-sdk

**Comment by Botspot** [comment]
Your link is to Stremio's addon sdk repository. Did you do that on purpose, or are you hoping Pi-Apps can include an entire media center?

**Comment by fabianmendes** [comment]
> Your link is to Stremio's addon SDK repository. Did you do that on purpose, or are you hoping Pi-Apps can include an entire media center?

I've attached the link hoping that it could help for a Stremio app on pi-apps. Seems to be possible to incorporate it into Raspberry pi

**Comment by mobilegmYT** [comment]
@fabianmendes Could you try getting this to work on your Raspberry Pi first?

**Comment by fabianmendes** [comment]
Ok, yeah I will do my research. Thanks for your question/asking RPI News!
 ~V. Fabian T· Mendes C.
