### ISSUE TITLE
App Submission: Syncthing

### ISSUE THREAD

**Issue by edbernard** [Botspot/pi-apps#1620]
Hi there, I found an app called syncthing a while back and found it to be super useful, I was wondering if you could put it on pi-apps.
[Syncthing.zip](https://github.com/Botspot/pi-apps/files/8317909/Syncthing.zip)

**Comment by theofficialgman** [comment]
going to add some context here for other people:
website: https://syncthing.net/
github: https://github.com/syncthing/syncthing
Description:
> Syncthing is a continuous file synchronization program. It synchronizes files between two or more computers in real time, safely protected from prying eyes. Your data is your data alone and you deserve to choose where it is stored, whether it is shared with some third party, and how it's transmitted over the internet.


the user above submitted a package app but I don't think that is what we should use.

syncthing has updated binary builds for many systems (armhf and arm64 linux included) on their website https://syncthing.net/downloads/ and directly from the github releases https://github.com/syncthing/syncthing/releases/tag/v1.19.1. the debian buster and bullseye official packages of syncthing are quite old, hence why I wouldn't suggest them. Assuming these builds work on both buster and bullseye, this would be a perfect application for the auto update github actions.

**Comment by theofficialgman** [comment]
there is also an official apt repo, but because it doesn't have an index file, its not really useable in our case unless we want to install the apt repo and not handle version management `https://apt.syncthing.net/`

**Comment by cycool29** [comment]
> there is also an official apt repo, but because it doesn't have an index file, its not really useable in our case unless we want to install the apt repo and not handle version management `https://apt.syncthing.net/`

We can manually grep its `Packages` file.
```bash
wget -qO- wget -qO- https://apt.syncthing.net/dists/syncthing/stable/binary-armhf/Packages | sed -z 's/Package: syncthing-discosrv.*//g' | grep 'Version:' | tail -n 1 | sed 's/.*: //g'
```

**Comment by theofficialgman** [comment]
relying on the order of the pacakges file sounds like a bad idea, so is relying on the placement of the syncthing inside the packages file relative to the other packages....

it would be nice if there was some tool that could read the Packages file directly and output the highest version number of a specified package within it

**Comment by theofficialgman** [comment]
```
wget -qO- https://apt.syncthing.net/dists/syncthing/stable/binary-armhf/Packages | awk '/Package: syncthing\n/' RS= | grep "Version:" | awk '{print $2}' | sort -V | tail -n1
```
and here is that script
it gets the `syncthing` packages only, gets their versions in a list, then sorts them and grabs the highest number

**Comment by edbernard** [comment]
OK thanks

**Comment by theofficialgman** [comment]
@edbernard syncthing is now in pi-apps
sorry for the long wait, it was waiting for action on my debian updater script PR, which syncthing is the first app to utilize for automated updates
