### ISSUE TITLE
App Suggestion - Signal App

### ISSUE THREAD

**Issue by jimmodo** [Botspot/pi-apps#1621]
### What is the name of the app?

Signal

### (Optional) Where is the app hosted?

The app is listed on the Signal.org website, as a Intel 64 binary, hence it would work on 64 bit Pi oses with Box64.  

### About the app

Replacement for Telegram with better security

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by Botspot** [comment]
> ### Confirmations
> * [x]  I have confirmed that this app is legal and not piracy.
> * [x]  I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
> * [x]  I have confirmed that this app can run on Raspberry Pi.

Actually this already has been discussed in https://github.com/Botspot/pi-apps/issues/1621. Naive arm64 works, and armhf should also work but I encountered some issues then. Perhaps you could find a solution?
In any case, let's continue the discussion in #1621.
