### ISSUE TITLE
Pi-Hole

### ISSUE THREAD

**Issue by ilobilo** [Botspot/pi-apps#163]
It would be awesome if you will add pi-hole installer.

**Comment by Itai-Nelken** [comment]
pikiss has a pi-hole installer under the server category, and you can install pikiss from pi-apps. 
I'm not sure how pi-hole works, but if I understand correctly, it's usually used in a headless pi without a desktop, and in that case using pikiss will be better than using pi-apps.

**Comment by Botspot** [comment]
We already had an issue on this. #58 

Basically:

- Pi-Hold is useless on a desktop GUI system.
- Pi-Hole is already well-known.

So I decided that PiHole does not belong on Pi-Apps.
