### ISSUE TITLE
Wine_x86 Not Found in Tools Category

### ISSUE THREAD

**Issue by ShortsKing** [Botspot/pi-apps#1633]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)

### What happened?

Wine_x86 was missing from the "Tools" category where is should be according to settings.

### Description

I just reinstalled my operating system and was using pi apps to install a whole bunch of programs, but i couldn't find Wine_x86. On the top of the main window (where you choose the category to look in) it gave me a promo message for Wine_x86, as if it were in the apps list. i also looked in settings > categories and saw that Wine_x86 was in that list as well and should be in the "Tools" category. a Pi -Apps search yields no results.

### What is your operating system?

Raspberry Pi OS Bullseye 64-Bit

**Comment by theofficialgman** [comment]
this is a feature request. wine x86 is not supported on arm64 in pi-apps.

There is current work being done to add this but it will require box86 on 64bit first: https://github.com/Botspot/pi-apps/pull/1625

if you need to use wine x86 right now, use the 32bit PiOS images

**Comment by theofficialgman** [comment]
> i also looked in settings > categories and saw that Wine_x86 was in that list as well and should be in the "Tools" category. a Pi -Apps search yields no results.

use the [wiki page](https://github.com/Botspot/pi-apps/tree/master/apps/Wine%20(x86)) or https://pi-apps.io/ to search for supported apps in the future


if you had, you would have seen wine_x86 is not supported on 64bit

<img width="355" alt="image" src="https://user-images.githubusercontent.com/28281419/159611605-c74f7d88-2686-4921-89bf-93ad357baee2.png">

**Comment by theofficialgman** [comment]
@Botspot  the only thing of concern here is maybe consider removing the wine promo from the pi-apps-announcements repo.
since it brings confusion when arm64 users see it in the banner https://github.com/Botspot/pi-apps-announcements/blob/main/message
