### ISSUE TITLE
Zoom not starting: Error loading needed lib libcef.so

### ISSUE THREAD

**Issue by sean-was-taken** [Botspot/pi-apps#1634]
The installation process went smoothly without any errors. However, when running it via `box64 ./zoom`  it gives me
```sean@raspi:~/zoom$ box64 ./zoom  
Dynarec for ARM64, with extension: ASIMD CRC32 PageSize:4096
Box64 with Dynarec v0.1.7 44a2034 built on Mar 23 2022 05:08:37
Using default BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/
Using default BOX64_PATH: ./:bin/
Counted 27 Env var
Looking for ./zoom
Zoom detected, trying to use system libturbojpeg if possible
Error loading needed lib libcef.so
Error loading one of needed lib
Error: loading needed libs in elf /home/sean/zoom/zoom
```
There is indeed no `libcef.so` in `/home/sean/zoom/` . 
This behavior didn't happen before. Maybe this has something to do with the new `Version 5.10.0 (2450)`?

**Comment by sean-was-taken** [comment]
I can confirm that this error does not occur on version 5.9.6 (2225). It seems that the error is caused by the new version requiring `libcef.so` which `zoom_x64_libs.zip` does not provide.

**Comment by Botspot** [comment]
Pinging @ryanfortner as he is the maintainer of [zoom_x64_libs.zip](https://github.com/ryanfortner/rpi-zoom/raw/master/zoom_x64_libs.zip)

**Comment by ryanfortner** [comment]
Seems like Zoom changed a bunch of things with their program dependencies. It's not just `libcef.so`

**Comment by ryanfortner** [comment]
@Botspot @sean-was-taken fixed the dependency issues with [this commit](https://github.com/ryanfortner/rpi-zoom/commit/6e8725d311f43655eb300b8fcd432e84b1621af5). we just need to trigger an update: #1636

**Comment by theofficialgman** [comment]
triggered, I'm going to add a script to keep track of the zoom .deb hash as well so we find out every time the github actions script runs if the package has changed. That way we at least we know when to test zoom for issues.

maybe we should also consider caching the zoom and saving it somewhere else, so pi-apps users install from a stable location. And just have the github actions script prompt for updating it when it detects a difference in the upstream deb, and the cached one

**Comment by sean-was-taken** [comment]
The error has been fixed. Thanks!
