### ISSUE TITLE
Parts of the Installation Command not found

### ISSUE THREAD

**Issue by DaRealMinecraftexpert** [Botspot/pi-apps#1635]
The Beginning part of the Command `\E[200~wget `and the End `(bash~)` Are described as not found by the Terminal. When removing the parts described (Keeping the wget), I get a Function Error instead.

**Comment by Botspot** [comment]
Could you attach a screenshot of what you see?

**Comment by DaRealMinecraftexpert** [comment]
![2022-03-24-105628_1920x1080_scrot](https://user-images.githubusercontent.com/55472940/159980089-7c096b84-a3cd-4874-aa3d-035db0d2aa30.png)

**Comment by Botspot** [comment]
I've noticed that Raspberry Pi OS Bullseye sometimes adds some weird characters to the beginning and the end of a command copied copied to the terminal. It is very annoying.

Try copying the original command again.
```bash
wget -qO- https://raw.githubusercontent.com/Botspot/pi-apps/master/install | bash
```

**Comment by DaRealMinecraftexpert** [comment]
That works, Thank you :)
