### ISSUE TITLE
Brave browser App request 

### ISSUE THREAD

**Issue by FlashFire900** [Botspot/pi-apps#164]
Brave is overall superior to all web browsers

**Comment by Itai-Nelken** [comment]
Do you know if brave can run on the pi?

**Comment by FlashFire900** [comment]
There is a linux version but im not sure

**Comment by Botspot** [comment]
No RPi release, and the linux version ix x86 64-bit. Not looking good, but I'm going to try emulating the 32-bit Windows version with WINE.

**Comment by Botspot** [comment]
Nope, didn't work. :(

**Comment by ralf1307** [comment]
A way would be to get the [brave-browser](https://github.com/brave/brave-browser) packaged in the raspberry pi (or better debian) repositories (for arm64).

**Comment by Botspot** [comment]
> A way would be to get the [brave-browser](https://github.com/brave/brave-browser) packaged in the raspberry pi (or better debian) repositories (for arm64).

Interesting!
If someone can make a build for armhf or arm64, I'd be happy to include it.

**Comment by ralf1307** [comment]
well, theres an issue for linux arm64 https://github.com/brave/brave-browser/issues/11836
and i cant build linux arm32.
@Botspot Please close this issue.

**Comment by Botspot** [comment]
Okay. Standing by.

**Comment by ralf1307** [comment]
My god this is a long download.

**Comment by ralf1307** [comment]
Ok, giving up.

**Comment by Itai-Nelken** [comment]
> Ok, giving up.

@ralf1307 could you send the commands you tried please?

**Comment by ralf1307** [comment]
I followed the build instructions in the [README.md](https://github.com/brave/brave-browser)
target_os linux; target_arch arm;

With different Chroots / OSs:
1. Alpine arm64
2. Alpine amd64
3. Manjaro amd64

Im going to attempt an armhf run with Debian and then Im going to give up completely.

The last error I got: 
```ERROR at //build/config/linux/atk/BUILD.gn:13:1 (//build/toolchain/linux:clang_x86_v8_arm): Assertion failed.
assert(current_toolchain == default_toolchain)
```
Im afraid if im going to comment this line out Im going to hit some roadblocks somewhere else.

**Comment by Itai-Nelken** [comment]
[compile-brave-rpi.txt](https://github.com/Botspot/pi-apps/files/5757467/compile-brave-rpi.txt)
I tried to compile it as well, I included the commands I ran. but `nom run init` fails.
as far as I understand from you comments @ralf1307 you got farther. can you post all the commands you did please?

**Comment by ralf1307** [comment]
```
npm install
npm run init --target_os=linux --target_arch=arm
npm run build
```

**Comment by Itai-Nelken** [comment]
> I had to wait a long time for npm run init to download everything and changed a lot of program's versions.
> 
> ```
> git clone https://github.com/brave/brave-browser
> npm install
> npm run init --target_os=linux --target_arch=arm
> npm run build
> ```

@ralf1307 thanks, any dependencies you had to install?

**Comment by Itai-Nelken** [comment]
maybe try `npm build --linux --arch=armv7l`

**Comment by ralf1307** [comment]
> maybe try `npm build --linux --arch=armv7l`

didnt work, trying to setup a ci

**Comment by slashtechno** [comment]
@Botspot It seems that Brave has published an ARM build
https://github.com/brave/brave-browser/issues/11836
I would test it, but currently, I don't have access to my Raspberry Pi 4

**Comment by Botspot** [comment]
It works for me!

It ran fine in an arm64 PiOS Bullseye vdesktop.
![2022-10-23-023617_1920x1080_scrot](https://user-images.githubusercontent.com/54716352/197380199-bad2f25d-0d82-476e-bffa-fb991e6ee45d.png)
The PiOS Bullseye desktop is glitchy in vdesktop, so I ran Brave in my outer X session like this:
```shell
DISPLAY=:0 brave-browser
```
Vdesktop is only necessary if you use 32-bit PiOS. If you have 64-bit PiOS, then Brave's new ARM64 DEB release could be installed straight into your system.

I think it is best to wait until this makes its way into the stable release. That way the Pi-Apps script can install Brave from its APT repository. [source](https://brave.com/linux/#debian-ubuntu-mint)

**Comment by theofficialgman** [comment]
likely blocked by: https://github.com/brave/brave-browser/issues/26189

**Comment by theofficialgman** [comment]
brave 1.49 with chromium 111 is in the pre-release channel. once released it can be added.

**Comment by everypizza1** [comment]
Try using `aria2` to download faster.

**Comment by theofficialgman** [comment]
oh oops I meant to close this. brave has been in pi-apps for a month now

**Comment by everypizza1** [comment]
Sorry
