### ISSUE TITLE
Minecraft Bedrock requires FUSE to be installed

### ISSUE THREAD

**Issue by Tyty395** [Botspot/pi-apps#1642]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)

### What happened?

Minecraft Bedrock will not launch without FUSE installed

### Description

Just as a heads up, the Minecraft Bedrock app won't launch without running `sudo apt-get install fuse`. I believe this is a limitation of the `.AppImage` file format. I tested this on Raspbian Bullseye 64 bit OS.

### What is your operating system?

Raspbian Bullseye 64 bit

**Comment by Botspot** [comment]
With the `fuse` package uninstalled, what is the output of `sudo modprobe fuse`?

**Comment by theofficialgman** [comment]
I don't see how `enable_module` could possible have not errored if this user is reporting this on a new install. modprobe will error if the `fuse` module is not available (aka, if the `fuse` package is not installed or if `fuse` is not built into the kernel)

**Comment by theofficialgman** [comment]
actually wait... @Botspot fuse is a two part component, its a kernel driver, and a userspace binary.

you can have the fuse kernel driver (what you load with modprobe) load successfully without installing the fuse package, but it the userspace components still need the fuse package to be installed (like appimages)

`fuse` (the package) needs to be added as a dependency to all appimages (or just to pi-apps itself) because clearly its not installed by default on all systems

**Comment by Botspot** [comment]
> `fuse` (the package) needs to be added as a dependency to all appimages (or just to pi-apps itself) because clearly its not installed by default on all systems

Something is not adding up. My system runs appimages fine and the `fuse` package has never been installed.

**Comment by theofficialgman** [comment]
> Something is not adding up. My system runs appimages fine and the `fuse` package has never been installed.

is it installed already?

**Comment by Botspot** [comment]
> is it installed already?

Nope. It is not currently installed, and I have never installed it either.

**Comment by theofficialgman** [comment]
how about `libfuse2`?

**Comment by Botspot** [comment]
Oh wait.
```
$ apt list fuse*
#partial output
fuse3/stable,now 3.10.3-2 armhf [installed,automatic]
fuse/stable 2.9.9-5 armhf
```
I checked the `info` of `fuse3`, and it said it "Provides: fuse", "Breaks: fuse", and "Replaces: fuse".
This still doesn't mean anything - it could have been automatically installed for something else and is not used for appimages.

**Comment by theofficialgman** [comment]
ah yup thats it, fuse3 works
I wasn't aware that existed till now though. its a newer package but yeah its just a newer version of fuse

**Comment by Botspot** [comment]
> ah yup thats it, fuse3 works I wasn't aware that existed till now though. its a newer package but yeah its just a newer version of fuse

I wonder if `apt install fuse` would have automatically redirected to fuse3, as it says it replaces the original fuse package.

**Comment by theofficialgman** [comment]
> > ah yup thats it, fuse3 works I wasn't aware that existed till now though. its a newer package but yeah its just a newer version of fuse
> 
> I wonder if `apt install fuse` would have automatically redirected to fuse3, as it says it replaces the original fuse package.

try it
`apt-get install --dry-run fuse`

**Comment by Botspot** [comment]
> how about `libfuse2`?

That sounds more familiar. I wasn't aware of the `fuse` package until I read this issue. I think the best way to handle this would be to add a conditional to the `enable_module` function.

**Comment by Botspot** [comment]
> try it and see `apt-get install --dry-run fuse`

interesting `The following packages will be REMOVED: fuse3 gvfs-fuse`

**Comment by theofficialgman** [comment]
alright so we definitely don't want that they
you should probably do an "if available" fuse3, install fuse3
and if not, install fuse

**Comment by Botspot** [comment]
> alright so we definitely don't want that then.... you should probably do an "if available" fuse3, install fuse3 and if not, install fuse

I was thinking of installing libfuse2, as long as that's the most futureproof way to do it.

**Comment by theofficialgman** [comment]
honestly maybe not even that... because some users might have fuse and some might have fuse3 already installed
no need to install again or change versions if one is already installed

**Comment by theofficialgman** [comment]
> I was thinking of installing libfuse2, as long as that's the most futureproof way to do it.

its not, thats the library for fuse. fuse3 uses libfuse3-3

**Comment by theofficialgman** [comment]
so basically... this should be good
if neither libfuse2 or libfuse3-3 are installed
install fuse3 if available, otherwise install fuse2

**Comment by Botspot** [comment]
@theofficialgman, does this look good? (within the `enable_module` function)

```bash
if [ "$module" == 'fuse' ];then
    if package_installed libfuse2 ;then
      true #nothing to do
    elif package_installed libfuse3-3 ;then
      true #nothing to do
    else
      #install fuse
      apt_update
      if package_available fuse3 ;then
        apt_lock_wait
        sudo apt install -y fuse3
      elif package_available fuse ;then
        apt_lock_wait
        sudo apt install -y fuse
      fi
    fi
  fi
```

**Comment by theofficialgman** [comment]
@Botspot yeah that looks good, though you could have squashed both package_installed together with an or || if you wanted
