### ISSUE TITLE
Intellij IDEA does not work

### ISSUE THREAD

**Issue by Rak1ta** [Botspot/pi-apps#1656]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)

### What happened?

Intellij IDEA does not turn on

### Description

```
Cannot load a JDK class: com.sun.jdi.Field
Please ensure you run the IDE on JDK rather than JRE.
```
![Безымянный](https://user-images.githubusercontent.com/88277343/161161105-35f3bce3-1700-492d-ab33-e95b095e09b6.png)

Are the properties in the application icon correct and specified? If you substitute the launch command* as in PyCharm CE, then it starts. If left unchanged _**/home/pi/idea_ic/bin/idea.sh**_ then an error occurs.

### What is your operating system?

RaspiOS 32bit Debian10

**Comment by Botspot** [comment]
Thank you for reporting. I've been able to reproduce this. Looking into solutions now...

**Comment by Botspot** [comment]
This issue should be solved now.
