### ISSUE TITLE
Minecraft in Q2 2021

### ISSUE THREAD

**Issue by GlacierPark19** [Botspot/pi-apps#167]
Greetings all!

I don't know how often you guys play Minecraft Java on the pi, but in Q2 2021, support will be ending for the legacy launcher. My question is, has the Pi-apps team started looking for a way to use the new launcher with pi-apps? I use my Pi to make Minecraft content, so having it available is helpful.

Thanks~
GlacierPark19

**Comment by beiop** [comment]
I think it's just try and run the launcher with wine or something or just hope they make a launcher for arm

**Comment by Botspot** [comment]
Pretty much the only thing we can do it to sign the petition for Microsoft to make an ARM launcher build.

https://feedback.minecraft.net/hc/en-us/community/posts/360075486052-Port-the-latest-Java-Minecraft-Launcher-to-the-Raspberry-Pi

**Comment by ralf1307** [comment]
_There is still [Multimc5](https://multimc.org/)_

**Comment by GlacierPark19** [comment]
Can Pi-Apps add MultiMC? I have struggled to get it to compile in the past, and Mojang intends to support 3rd party launchers, killing all the birds with one stone

**Comment by ralf1307** [comment]
I dont have any experience using this fork, but it should have the needed fixes inside MultiMC5 (https://github.com/JJTech0130/MultiMC5/tree/develop)

**Comment by mobilegmYT** [comment]
This certainly seems to be promising, but it only works with 64-bit. https://nicholasbering.ca/raspberry-pi/2020/10/18/minecraft-64bit-rpi4/

**Comment by Botspot** [comment]
What's the current status of this issue?

I think that it would be best to wait until Microsoft's transition is over. After that happens, there's a good chance the community will develop a workaround. Let's especially keep an eye on this [Raspberry Pi Forum topic](https://www.raspberrypi.org/forums/viewtopic.php?f=78&t=284448). Those guys won't give up easily.

**Comment by chunky-milk** [comment]
@Botspot [ATLauncher](https://atlauncher.com/) works with Microsoft accounts. Works on 32/64 bit, as long as you follow all the other steps with the JVM arguments and such.
![screenshot](https://user-images.githubusercontent.com/71036629/104139016-73dc5d00-5376-11eb-924e-a715fae680d5.png)

**Comment by pi-dev500** [comment]
> @Botspot [ATLauncher](https://atlauncher.com/) works with Microsoft accounts. Works on 32/64 bit, as long as you follow all the other steps with the JVM arguments and such.
> ![screenshot](https://user-images.githubusercontent.com/71036629/104139016-73dc5d00-5376-11eb-924e-a715fae680d5.png)

And the adapted installer is availlable here:
[MinecraftMicrosoftPILauncher](https://github.com/pi-dev500/MinecraftMicrosoftPILauncher)

**Comment by mobilegmYT** [comment]
ATLauncher seems to be our best bet here. Problem is, we'd still need to write some code to link the lwjgl libraries. I've contacted the dev about potentially having this function be added to the source code.

**Comment by pi-dev500** [comment]
I have a script that configure and install atlauncher. It works perfectly : https://github.com/pi-dev500/MinecraftMicrosoftPILauncher
[ATlauncherPI.zip](https://github.com/Botspot/pi-apps/files/5916879/ATlauncherPI.zip)

**Comment by Botspot** [comment]
https://github.com/Botspot/pi-apps/issues/483
