### ISSUE TITLE
Cannot download IntelliJ Idea

### ISSUE THREAD

**Issue by XSS6-2b2t** [Botspot/pi-apps#1676]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)

### What happened?

App won’t install

### Description

It just says must require JDK but I cannot change the Java version. Please help

### What is your operating system?

PI OS armhf

### (Optional) Error log? Terminal output? Debug messages?

```bash
No terminal output
```

**Comment by Botspot** [comment]
This issue was recently fixed in commit https://github.com/Botspot/pi-apps/commit/b4b24b4ad8054261d9ece8301478f7c137a56a88. Can you check if Pi-Apps is fully up to date?

**Comment by theofficialgman** [comment]
closing due to lack of response. there have been many installs since this date and the issues as botspot reported is probably fixed already
