### ISSUE TITLE
Install Pozyx

### ISSUE THREAD

**Issue by hafidz141200** [Botspot/pi-apps#1677]
### What is the name of the app?

Pozyx

### (Optional) Where is the app hosted?

https://pozyx.io/files/creator-controller/2.0.0/pozyx-creator-controller-2.0.0.appimage

### About the app

Can connect to anchor pozyx for coodinate AGV

### Upload file or Add PR Link

[Pozyx#.zip](https://github.com/Botspot/pi-apps/files/8469197/Pozyx.zip)

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by cycool29** [comment]
The appimage is for x86-64, do you mean to run it with box64?

**Comment by theofficialgman** [comment]
> * [x]  I have confirmed that this app can run on Raspberry Pi.

Please don't tick this box unless you have actually managed to run this on a raspberry pi. as was already said, the appimage is x86_64, and its actually not possible to even extract it on a pi (armhf or arm64)
