### ISSUE TITLE
[APP SUBMISSION]- Neofetch (.ZIP included)

### ISSUE THREAD

**Issue by nikoloiz** [Botspot/pi-apps#1690]
### What is the name of the app?

Neofetch

### About the app

An aesthetically pleasing bash script to show system information.

### Upload file or Add PR Link

[Neofetch.zip](https://github.com/Botspot/pi-apps/files/8494862/Neofetch.zip)

### Confirmations

- [x] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by CleanMachine1** [comment]
`sudo apt install neofetch` 

Have I missed something in the Pi-Apps rules, can you add packages from APT to pi-apps

**Comment by Crilum** [comment]
> `sudo apt install neofetch`
> 
> Have I missed something in the Pi-Apps rules, can you add packages from APT to pi-apps

Yeah, you can add apt packages now.. They're called package apps. If the repo version is higher though, it might be a good idea to use a script instead of apt.

**Comment by Crilum** [comment]
The current apt version is `7.1.0`, which is up to date with the repo. This looks good!

**Comment by Crilum** [comment]
@Botspot I think this can be added.

**Comment by Crilum** [comment]
@Botspot is this any better?  
[Neofetch.zip](https://github.com/Botspot/pi-apps/files/8664965/Neofetch.zip)

**Comment by Botspot** [comment]
> @Botspot is this any better? [Neofetch.zip](https://github.com/Botspot/pi-apps/files/8664965/Neofetch.zip)

It is better, but `icon-24.png` is still incomprehensible.
![icon-24](https://user-images.githubusercontent.com/54716352/167762733-dae2a520-009f-4599-a832-820125beabd5.png)
![icon-64](https://user-images.githubusercontent.com/54716352/167762735-23e08b80-19e6-4a5a-ad94-7de2791442eb.png)

**Comment by Botspot** [comment]
I cropped and resized a screenshot of neofetch. It's not great. Looking for better ideas for an icon.
![2022-05-17-234540_1920x1080_scrot](https://user-images.githubusercontent.com/54716352/168959362-d60cc2ce-239e-49a6-812d-fe8bda473900.png)

**Comment by nikoloiz** [comment]
Not quite sure what to add tbh.. I'll think abt it and come back later

**Comment by ryanfortner** [comment]
Personally I think an “info” icon would work nicely. I like this one from icons8: 
![icons8-info-500](https://user-images.githubusercontent.com/71036629/169591431-f31e917e-9536-48ad-8de9-e3f889beffca.png)

**Comment by Crilum** [comment]
I've made another edited version of the Neofetch icon:
![Neofetch-24v2](https://user-images.githubusercontent.com/91354257/169630297-88e3932c-ed89-4cd1-b553-c47e3f14f9be.png)
![Neofetch-64v2](https://user-images.githubusercontent.com/91354257/169630298-17e0f702-ecd5-4550-ab81-17e1f7ef12ff.png)

**Comment by Botspot** [comment]
This app has been added.
https://github.com/Botspot/pi-apps/commit/ae23a49621fb131c240f6b8680936c46eb8b9fd6
