### ISSUE TITLE
Add GIMPS (Great Internet Mersenne Prime Search)

### ISSUE THREAD

**Issue by MrBrain295** [Botspot/pi-apps#1691]
### What is the name of the app?

GIMPS (Great Internet Mersenne Prime Search)

### (Optional) Where is the app hosted?

https://www.mersenne.org/

### About the app

It searches for large prime numbers. At one point I got it to run on the PI4, it was slow but it worked.

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by Crilum** [comment]
Their `Linux (32)` works for me on armhf.. This would probably be pretty easy to make a script for.

**Comment by Crilum** [comment]
Here's some output:

```

[Comm thread Apr 15 19:41] == Info: Connection #0 to host v5.mersenne.org left intact
[Comm thread Apr 15 19:41] RESPONSE:
[Comm thread Apr 15 19:41] pnErrorResult=0
[Comm thread Apr 15 19:41] pnErrorDetail=SUCCESS
[Comm thread Apr 15 19:41] ==END==
[Comm thread Apr 15 19:41] 
[Comm thread Apr 15 19:41] Done communicating with server.
[Work thread Apr 15 19:41] M664597 curve 1 stage 1 at prime 337 [0.13%]. Time: 16.267 sec.
[Work thread Apr 15 19:41] M664597 curve 1 stage 1 at prime 877 [0.35%]. Time: 14.393 sec.
[Work thread Apr 15 19:41] M664597 curve 1 stage 1 at prime 1571 [0.62%]. Time: 16.484 sec.
[Work thread Apr 15 19:42] M664597 curve 1 stage 1 at prime 2281 [0.91%]. Time: 29.011 sec.
[Work thread Apr 15 19:42] M664597 curve 1 stage 1 at prime 2957 [1.18%]. Time: 16.613 sec.
[Work thread Apr 15 19:43] M664597 curve 1 stage 1 at prime 3659 [1.46%]. Time: 17.600 sec.
[Work thread Apr 15 19:43] M664597 curve 1 stage 1 at prime 4349 [1.73%]. Time: 16.411 sec.
[Work thread Apr 15 19:43] M664597 curve 1 stage 1 at prime 5039 [2.01%]. Time: 19.643 sec.
[Work thread Apr 15 19:43] M664597 curve 1 stage 1 at prime 5737 [2.29%]. Time: 14.547 sec.
[Work thread Apr 15 19:44] M664597 curve 1 stage 1 at prime 6389 [2.55%]. Time: 20.730 sec.
[Work thread Apr 15 19:44] M664597 curve 1 stage 1 at prime 7109 [2.84%]. Time: 17.938 sec.
[Work thread Apr 15 19:44] M664597 curve 1 stage 1 at prime 7817 [3.12%]. Time: 13.713 sec.
[Work thread Apr 15 19:45] M664597 curve 1 stage 1 at prime 8537 [3.41%]. Time: 15.510 sec.
```

**Comment by MrBrain295** [comment]
@Crilum are you working on the script or should I try to make a script for it?

**Comment by Crilum** [comment]
@MrBrain295 Here you go:

[GIMPS.zip](https://github.com/Botspot/pi-apps/files/8507509/GIMPS.zip)

**Comment by MrBrain295** [comment]
@Crilum I tried to run both `install-64` and `install-32` but the both gave me this error `install-32: 7: status: not found
install-32: 11: status_green: not found
install-32: 15: status: not found
install-32: 18: status_green: not found
`.

**Comment by MrBrain295** [comment]
It says when I go to `/usr/local/bin` and run `sudo ./mprime` it says that `/root/gimps/mprime` dosen't exist.

**Comment by MrBrain295** [comment]
@Crilum I got it to work but now it says `./mprime` was marked as an executable but cannot be ran by the OS.

**Comment by Crilum** [comment]
>@Crilum I tried to run both install-64 and install-32 but the both gave me this error
install-32: 11: status_green: not found
install-32: 15: status: not found
install-32: 18: status_green: not found
. Edit: replacing status_green and status with echo works.

Did you import the app into Pi-Apps and install from there?
`status` and `status_green` are Pi-Apps' functions.

> It says when I go to `/usr/local/bin` and run `sudo ./mprime` it says that `/root/gimps/mprime` dosen't exist.

Don't run `mprime` as root. You should also just be able to run `mprime` without going into `/usr/local/bin`.
`/usr/local/bin/mprime` is a symbolic link to `$HOME/gimps/mprime` with `$HOME` being your home dir, in my case `/home/pi/`. If you run it as root, I guess it thinks your home dir is `/root/`..

When I run as sudo, it works:
```
$ sudo mprime

Welcome to GIMPS, the hunt for huge prime numbers.  You will be asked a
few simple questions and then the program will contact the primenet server
to get some work for your computer.  Good luck!

Attention OVERCLOCKERS!!  Mprime has gained a reputation as a useful
stress testing tool for people that enjoy pushing their hardware to the
limit.  You are more than welcome to use this software for that purpose. 
Please select the stress testing choice below to avoid interfering with
the PrimeNet server.  Use the Options/Torture Test menu choice for your
stress tests.  Also, read the stress.txt file.

If you want to both join GIMPS and run stress tests, then Join GIMPS and
answer the questions.  After the server gets some work for you, stop
mprime, then run mprime -m and choose Options/Torture Test.

Join Gimps? (Y=Yes, N=Just stress testing) (Y):
```

**Comment by Crilum** [comment]
> @Crilum I got it to work but now it says `./mprime` was marked as an executable but cannot be ran by the OS.

Which install script did you use? (It sounds like you just ran one) `install-32` is for 32 bit systems, `install-64` is for 64 bit systems.
If you use the App Importer in Pi-Apps Settings, you can import the app into Pi-Apps, and install from Pi-Apps, which should fix installing the wrong program arch, as well as the `bash: status: command not found` problem.

**Comment by MrBrain295** [comment]
@Crilum I followed your instructions but when I run `sudo mprime` it says 
```
sh: 0: getcwd() failed: No such file or directory
/usr/local/bin/mprime: 1: Syntax error: "(" unexpected
```

**Comment by Crilum** [comment]
What arch are you using? You can get it with this: `arch`

**Comment by MrBrain295** [comment]
I am new to shell so I’m confused what an “arch” is. Is it the cpu architecture?

**Comment by Crilum** [comment]
Yeah, sorry. `arch` is short for `architecture`.

**Comment by Crilum** [comment]
Ok, so if you've imported the app into Pi-Apps like this (or manually with the GUI (**G**raphical **U**ser **I**nterface)):
```bash
~/pi-apps/etc/import-app https://github.com/Botspot/pi-apps/files/8507509/GIMPS.zip
```
Uninstall it (from Pi-Apps) and then install it again.
Pi-Apps should install the right program architecture for you.

Can you also send the output of `dpkg --print-architecture`? (I assume you're on Debian, or a derivative,  since you're using Pi-Apps..)

**Comment by MrBrain295** [comment]
I have installed it through pi apps and removed it through pi apps a few times already without success.

**Comment by Crilum** [comment]
Same error that you posted above?

**Comment by MrBrain295** [comment]
yes

**Comment by Crilum** [comment]
Can you post the output of `dpkg --print-architecture`?

**Comment by MrBrain295** [comment]
That command outputted `arm64`.

**Comment by Crilum** [comment]
sorry for asking for so many commands, but can you also post the output of `file $HOME/gimps/mprime`?
This gives us the type and arch of the exectable.

**Comment by MrBrain295** [comment]
`ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=6d053e3f9b870f31508045b9f0af5a4c6c9d9a55, with debug_info, not stripped
`

**Comment by Crilum** [comment]
Oh, I think I know what the problem is!! I have exagear installed, and I think it was just taking over, emulating an x86 system..

If you have box64 installed, try running it with that.

**Comment by MrBrain295** [comment]
It looks as though the program that's being downloaded is for `x86`.

**Comment by Crilum** [comment]
Yep, it is.. See my above comment

**Comment by Crilum** [comment]
Someone will have to build it..

**Comment by MrBrain295** [comment]
Yeah sorry I commented but my internet was too slow and your comment appeared first.

**Comment by MrBrain295** [comment]
With `box64` installed it works perfectly!!!

**Comment by Crilum** [comment]
We can try building `gimps`, or we can just make the install scripts use box86 or box64 for running it. We should at least try building `gimps` first though...

**Comment by MrBrain295** [comment]
How should we go about building gimps?

**Comment by Crilum** [comment]
They have building instructions on their website.

**Comment by MrBrain295** [comment]
Oh

**Comment by Crilum** [comment]
This might be worth taking a look at...

**Comment by MrBrain295** [comment]
I think it would be better to add box64/box86 as a dependency so it doesn’t need to be recompiled whenever an update comes out and recompiling for 64 and 32 bit.

**Comment by Crilum** [comment]
Ok, but:

- Using Box86/64 will make the efficiency lower, because box86/64 is translating the x86/x64 program into arm code
- We don't need to build it every time (unless we need it to be up to date all the time), we just need to build a couple debs, and then we can install the debs.

**Comment by Crilum** [comment]
Here is a version that uses box86/64:
[GIMPSv2.zip](https://github.com/Botspot/pi-apps/files/8542699/GIMPS.zip)

**Comment by Crilum** [comment]
I probably won't be able to try building GIMPS today or tomorrow, so if you want to try it, go ahead!

**Comment by theofficialgman** [comment]
> [This](https://www.mersenneforum.org/mayer/README.html) might be worth taking a look at...

I suggested this before in the discord, yes this should be used. Prime95 (GIMPS) through box86/64 is the wrong way to go. You should be using the open source multiplatform version from that link.
Unfortunately this isn't the same as prime95, there is no GUI to see progress and select settings, and the test takes hours to run by default

**Comment by Botspot** [comment]
What is the current status of this issue?

**Comment by MrBrain295** [comment]
I haven’t had the time to work on this but I will in about 2 weeks.
