### ISSUE TITLE
PiKiss GUI: ./build.sh: line 5: unexpected EOF while looking for matching `"'

### ISSUE THREAD

**Issue by Kcam6708** [Botspot/pi-apps#1692]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)

### What happened?

App won't install

### Description

I was installing PiKiss GUI and when it tried to install PiKiss the Terminal returned an error.

### What is your operating system?

Raspberry Pi OS (32bit) KDE Plasma Desktop

### (Optional) Error log? Terminal output? Debug messages?

```bash
PiKISS
======

Installing at /home/pi/piKiss. Please wait...


WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Reading package lists...
Building dependency tree...
Reading state information...
dialog is already the newest version (1.3-20201126-1).
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
Cloning into 'piKiss'...

PiKISS installed!
=================

cd /home/pi/piKiss, type or click ./piKiss.sh. You have an Menu shortcut, too!. Go to:

 · Raspberry Pi OS: Menu > System Tools > PiKISS
 · Twister OS: Menu > Accesories > PiKISS


Installed piKiss successfully.
./build.sh: line 5: unexpected EOF while looking for matching `"'
./build.sh: line 10: unexpected argument to conditional unary operator
./build.sh: line 10: syntax error: unexpected end of file
Failed to build PiKISS GUI
Allowing packages required by the PiKISS GUI app to be uninstalled
These packages were: gobject-introspection, libgee-0.8-dev, libgirepository1.0-dev, libgnome-menu-3-dev, libgtk-3-dev, ninja-build, valac
Purging the pi-apps-51b4a14d package...
The following packages will be REMOVED:
  gir1.2-gee-0.8* libgee-0.8-2* libgee-0.8-dev* libgnome-menu-3-dev*
  libvala-0.48-0* libvalacodegen-0.48-0* pi-apps-51b4a14d* valac*
  valac-0.48-vapi* valac-bin*
0 upgraded, 0 newly installed, 10 to remove and 3 not upgraded.
                                                               (Reading database(Reading database ... 270613 files and directories currently installed.)
Removing pi-apps-51b4a14d (1.0) ...
Removing libgee-0.8-dev:armhf (0.20.4-1) ...
Removing gir1.2-gee-0.8:armhf (0.20.4-1) ...
Removing libgee-0.8-2:armhf (0.20.4-1) ...
Removing libgnome-menu-3-dev:armhf (3.36.0-1) ...
Removing valac (0.48.17-1) ...
Removing valac-bin (0.48.17-1) ...
Removing libvalacodegen-0.48-0:armhf (0.48.17-1) ...
Removing libvala-0.48-0:armhf (0.48.17-1) ...
Removing valac-0.48-vapi (0.48.17-1) ...
Apt finished.
All packages have been purged succesfully.

Failed to install PiKISS GUI!
◢◣Need help? Copy the ENTIRE terminal output or take a screenshot.
Please ask on Github: https://github.com/Botspot/pi-apps/issues/new/choose
Or on Discord: https://discord.gg/RXSTvaUvuu

Close this window to exit.
```

**Comment by Kcam6708** [comment]
I tried installing it again and got a different error. The following is from the Terminal

    🭊▅▅▅▅🬿
 🭈▂▂█▂▂▂▂█▂▂🬽
 ▌  ▗▖▗▖▗▖  ▐   █▀▀🭍 ▄
 ▌  ▗▖▗▖▗▖  ▐   █▄▄🭞 ▄ ▄▄ 🭂▀▀█ █▀▀🭍 █▀▀🭍 🭂🬰🬰🬰
 ▌  ▗▖▗▖▗▖  ▐   █    █    🭓▄▄█ █▄▄🭞 █▄▄🭞 ▄▄▄🭞
 🭓🬭🬭🬰🬰🬰🬰🬰🬰🬭🬭🭞                  █    █

Installing PiKISS GUI...

Downloading pikiss-gui repository... Done
Will install these packages: ninja-build gobject-introspection libgee-0.8-dev libgirepository1.0-dev libgtk-3-dev valac libgnome-menu-3-dev 
Running sudo apt update...
Hit:1 http://raspbian.raspberrypi.org/raspbian bullseye InRelease
Hit:2 http://ports.ubuntu.com/ubuntu-ports bionic-updates InRelease
Hit:3 https://itai-nelken.github.io/weekly-box86-debs/debian  InRelease
Hit:4 http://archive.raspberrypi.org/debian bullseye InRelease
Hit:5 https://repo.steampowered.com/steam stable InRelease
Hit:6 https://osdn.mirror.constant.com/storage/g/r/ra/raspbian-addons/debian precise InRelease
Ign:7 https://download.puffinbrowser.com/repo stable InRelease
Ign:8 https://repo.vivaldi.com/stable/deb stable InRelease
Hit:9 https://repo.vivaldi.com/stable/deb stable Release
Hit:10 https://download.puffinbrowser.com/repo stable Release
3 packages can be upgraded. Run 'apt list --upgradable' to see them.
apt update complete.
Some packages can be upgraded. Please consider running sudo apt full-upgrade.
Creating an empty apt-package to install the necessary apt packages...
It will be named: pi-apps-51b4a14d
Depends: gobject-introspection, libgee-0.8-dev, libgirepository1.0-dev, libgnome-menu-3-dev, libgtk-3-dev, ninja-build, valac
Installing the pi-apps-51b4a14d package...
The following additional packages will be installed:
  gir1.2-gee-0.8 libgee-0.8-2 libgee-0.8-dev libgnome-menu-3-dev libvala-0.48-0
  libvalacodegen-0.48-0 valac valac-0.48-vapi valac-bin
The following NEW packages will be installed:
  gir1.2-gee-0.8 libgee-0.8-2 libgee-0.8-dev libgnome-menu-3-dev libvala-0.48-0
  libvalacodegen-0.48-0 pi-apps-51b4a14d valac valac-0.48-vapi valac-bin
0 upgraded, 10 newly installed, 0 to remove and 3 not upgraded.
Get:1 /home/pi/pi-apps-51b4a14d.deb pi-apps-51b4a14d all 1.0 [808 B]
Get:2 http://mirrors.syringanetworks.net/raspbian/raspbian bullseye/main armhf gir1.2-gee-0.8 armhf 0.20.4-1 [36.0 kB]
Get:3 http://raspbian.mirror.constant.com/raspbian bullseye/main armhf libgee-0.8-2 armhf 0.20.4-1 [187 kB]
Get:4 http://mirror.pit.teraswitch.com/raspbian/raspbian bullseye/main armhf libgee-0.8-dev armhf 0.20.4-1 [67.1 kB]
Get:5 http://mirrors.syringanetworks.net/raspbian/raspbian bullseye/main armhf libgnome-menu-3-dev armhf 3.36.0-1 [108 kB]
Get:6 http://mirror.pit.teraswitch.com/raspbian/raspbian bullseye/main armhf libvala-0.48-0 armhf 0.48.17-1 [721 kB]
Get:7 http://mirror.us.leaseweb.net/raspbian/raspbian bullseye/main armhf libvalacodegen-0.48-0 armhf 0.48.17-1 [606 kB]
Get:8 http://mirrors.syringanetworks.net/raspbian/raspbian bullseye/main armhf valac-0.48-vapi all 0.48.17-1 [1,003 kB]
Get:9 http://mirrors.syringanetworks.net/raspbian/raspbian bullseye/main armhf valac-bin armhf 0.48.17-1 [302 kB]
Get:10 http://mirrors.syringanetworks.net/raspbian/raspbian bullseye/main armhf valac armhf 0.48.17-1 [379 kB]
Fetched 3,409 kB in 6s (620 kB/s)
(Reading database ... 270232 files and directories currently installed.)
Unpacking gir1.2-gee-0.8:armhf (0.20.4-1) ...
Unpacking libgee-0.8-2:armhf (0.20.4-1) ...
Unpacking libgee-0.8-dev:armhf (0.20.4-1) ...
Unpacking libgnome-menu-3-dev:armhf (3.36.0-1) ...
Unpacking libvala-0.48-0:armhf (0.48.17-1) ...
Unpacking libvalacodegen-0.48-0:armhf (0.48.17-1) ...
Unpacking valac-0.48-vapi (0.48.17-1) ...
Unpacking valac-bin (0.48.17-1) ...
Unpacking valac (0.48.17-1) ...
Unpacking pi-apps-51b4a14d (1.0) ...
Apt finished.
Package installation complete.
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: meson in /usr/local/lib/python3.9/dist-packages (0.62.0)
Collecting meson
  Using cached https://www.piwheels.org/simple/meson/meson-0.62.0-py3-none-any.whl (862 kB)
  Using cached https://www.piwheels.org/simple/meson/meson-0.61.4-py3-none-any.whl (848 kB)
./build.sh: line 5: unexpected EOF while looking for matching `"'
./build.sh: line 10: unexpected argument to conditional unary operator
./build.sh: line 10: syntax error: unexpected end of file
Failed to build PiKISS GUI
Allowing packages required by the PiKISS GUI app to be uninstalled
These packages were: gobject-introspection, libgee-0.8-dev, libgirepository1.0-dev, libgnome-menu-3-dev, libgtk-3-dev, ninja-build, valac
Purging the pi-apps-51b4a14d package...
The following packages will be REMOVED:
  gir1.2-gee-0.8* libgee-0.8-2* libgee-0.8-dev* libgnome-menu-3-dev*
  libvala-0.48-0* libvalacodegen-0.48-0* pi-apps-51b4a14d* valac*
  valac-0.48-vapi* valac-bin*
0 upgraded, 0 newly installed, 10 to remove and 3 not upgraded.
                                                               (Reading database(Reading database ... 270613 files and directories currently installed.)
Removing pi-apps-51b4a14d (1.0) ...
Removing libgee-0.8-dev:armhf (0.20.4-1) ...
Removing gir1.2-gee-0.8:armhf (0.20.4-1) ...
Removing libgee-0.8-2:armhf (0.20.4-1) ...
Removing libgnome-menu-3-dev:armhf (3.36.0-1) ...
Removing valac (0.48.17-1) ...
Removing valac-bin (0.48.17-1) ...
Removing libvalacodegen-0.48-0:armhf (0.48.17-1) ...
Removing libvala-0.48-0:armhf (0.48.17-1) ...
Removing valac-0.48-vapi (0.48.17-1) ...
Apt finished.
All packages have been purged succesfully.

Failed to install PiKISS GUI!
◢◣Need help? Copy the ENTIRE terminal output or take a screenshot.
Please ask on Github: https://github.com/Botspot/pi-apps/issues/new/choose
Or on Discord: https://discord.gg/RXSTvaUvuu

Close this window to exit.

**Comment by CleanMachine1** [comment]
See #1693 

There is a random underscore, making the command git_clone which doesn't exist since the correct command is git clone

**Comment by Jai-JAP** [comment]
> See #1693
> 
> There is a random underscore, making the command git_clone which doesn't exist since the correct command is git clone

git_clone is intended it is a finction defined in api
https://github.com/Botspot/pi-apps/blob/ff65f94f6735b6604fd23ee9f094d43ed92605ab/api#L1927

**Comment by Jai-JAP** [comment]
should be fixed now @Kcam6708 can you try again

**Comment by Kcam6708** [comment]
I don't know what you did but it worked, thanks.

**Comment by Jai-JAP** [comment]
It was an typo in my [pikiss-gui](https://github.com/Jai-JAP/pikiss-gui) repo

**Comment by Botspot** [comment]
> I don't know what you did but it worked, thanks.

Closing issue, as it has been solved.
