### ISSUE TITLE
Add the ability to download ANY app

### ISSUE THREAD

**Issue by TechDudie** [Botspot/pi-apps#1694]
### Cool ideas?

So the user searches in a cool interface for a github repo or puts in a link
and then the script gets the git repo
and then it's analyzed, its language detected
and based on the language, the code is scanned for the file to run and shortcuts are created
if its like python, it runs files like main, \_\_init__, \_\_main__ or the python file in the root git directory
it its like c or c++ it builds it with gcc or something, if theres a makefile, it does some make stuff

i know this sounds really hard but i feel like it would make pi-apps even better because then it could download and install almost any app, even if its not on the list which means that almost any github or gitlab or whatever program can be installed, so basic neophytes have no trouble at all :)

pi-apps would be even better

Edit:
maybe have like a .pi_config file with a link to a bash script to run so the developer can make the app pi-apps compatible
a lot of devs want to have their app on pi-apps even if it's not well known

**Comment by Crilum** [comment]
I don't think this would work very well. If a dev wants to have their app on Pi-Apps, they can just submit an app request. If the app doesn't make it on to Pi-Apps, they can still provide a 3rd-party Pi-App for their app, that can be imported with Pi-Apps' `import-app` script.

It would be *insanely* hard to create a script that could scan a git repository, and be able to find the main script/source code, build it (lots of programs have different build procedures, not to mention multiple programming languages), and make menu entries for it.

If the script could be provided with building/setup instructions, this would be more feasible, but then why not just make an install script?

A `.pi_config` sort of thing might work, if the dev can't get their app onto Pi-Apps, but that is basically just a 3rd-party Pi-App, and without importing it, how would Pi-Apps know to look for it?

@TechDudie I'm not trying to just veto your idea, it would be way cool, but I don't think it's really feasible for Pi-Apps. Maybe if someone made a script that could do this, it could be adapted to become a Pi-Apps Addon.

**Comment by TechDudie** [comment]
then what if i made it

**Comment by Botspot** [comment]
This task requires not only computer language detection, but also human language detection. This task requires a human level of intelligence - a task that is very hard to achieve with conventional programming.

Your best bet is to somehow create and train a neural network with a GPU rack. No matter how you do it, this would take a lot of time and a lot of money.

> then what if i made it

I wish you the best. This reminds me of the computer science students in 1966 who were assigned a summer project to make a computer label objects in a scene. They failed, and over half a century later we still struggle to do it.

On a more practical side, I do understand the problem this is trying to address. Pi-Apps right now is personally moderated and vetted by a handful of maintainers. Quality has been favored over quantity. There are drawbacks to this technique. Ideally, anyone could publish their app to pi-apps without having to ask us, but that has its own risks and there would be a lot of spam and possibly viruses.

Closing this issue, as I'm not exactly holding my breath for this proposed feature to become a reality.
