### ISSUE TITLE
Package Installer Broken 

### ISSUE THREAD

**Issue by cogfilms-3D** [Botspot/pi-apps#1695]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)

### What happened?

installed Box64 by pi-apps and now broken update from Ubuntu Mate

### Description

I installed box64 and at some point a dependency was corrupted or failed to load. This has now broken any updates including Ubuntu mate on my raspberry pi. I have tried all the commands using apt.
Any help greatly appreciated.

### What is your operating system?

Raspberry pi 400  Ubuntu 21.10 OS architecture: 64-bit

### (Optional) Error log? Terminal output? Debug messages?

```
OS: Ubuntu 21.10
OS architecture: 64-bit
Installed Pi-Apps version: 04/14/2022
Most recent Pi-Apps version: 04/15/2022
Kernel: aarch64 5.13.0-1024-raspi
Device model: Raspberry Pi 400 Rev 1.0
Ram size: 3.74 GB
Language: en_US.UTF-8

BEGINNING OF LOG FILE:
-----------------------

Waiting until APT locks are released... Done
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 pi-apps-5f3374a7 : Depends: libraspberrypi0:armhf
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).

Failed to uninstall HTTrack Website Copier!
◢◣Need help? Copy the ENTIRE terminal output or take a screenshot.
Please ask on Github: https://github.com/Botspot/pi-apps/issues/new/choose
Or on Discord: https://discord.gg/RXSTvaUvuu
```
As you can see I tried to use pi-apps to install another program HHTrack which failed.

-----------------------------------------------
I have tried uninstalling and re-installing p-apps but the dependency and error persists.
I may have installed Box64 followed by Box86 which may have corrupted the dependencies. However, I can no longer update my system which might mean a total re-install which I'm not looking forward to.
here is another error message from terminal when I attempted to clear the apt cache.
```
pi-400@pi-400:~$ sudo apt-get install -f
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Correcting dependencies... Done
The following additional packages will be installed:
  libraspberrypi0:armhf
The following NEW packages will be installed:
  libraspberrypi0:armhf
0 upgraded, 1 newly installed, 0 to remove and 48 not upgraded.
1 not fully installed or removed.
Need to get 426 kB of archives.
After this operation, 1,200 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://ports.ubuntu.com/ubuntu-ports impish-updates/main armhf libraspberrypi0 armhf 0~20200520+git2fe4ca3-0ubuntu5~21.10.1 [426 kB]
Fetched 426 kB in 0s (2,537 kB/s)             
(Reading database ... 304641 files and directories currently installed.)
Preparing to unpack .../libraspberrypi0_0~20200520+git2fe4ca3-0ubuntu5~21.10.1_armhf.deb ...
Unpacking libraspberrypi0:armhf (0~20200520+git2fe4ca3-0ubuntu5~21.10.1) ...
dpkg: error processing archive /var/cache/apt/archives/libraspberrypi0_0~20200520+git2fe4ca3-0ubuntu5~21.10.1_armhf.deb (--unpack):
 trying to overwrite shared '/usr/share/lintian/overrides/libraspberrypi0', which is different from other instances of package libraspberrypi0:armhf
Errors were encountered while processing:
 /var/cache/apt/archives/libraspberrypi0_0~20200520+git2fe4ca3-0ubuntu5~21.10.1_armhf.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

```
pi-400@pi-400:~$ sudo apt-get install -f
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Correcting dependencies... Done
The following additional packages will be installed:
  libraspberrypi0:armhf
The following NEW packages will be installed:
  libraspberrypi0:armhf
0 upgraded, 1 newly installed, 0 to remove and 48 not upgraded.
1 not fully installed or removed.
Need to get 426 kB of archives.
After this operation, 1,200 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://ports.ubuntu.com/ubuntu-ports impish-updates/main armhf libraspberrypi0 armhf 0~20200520+git2fe4ca3-0ubuntu5~21.10.1 [426 kB]
Fetched 426 kB in 0s (2,537 kB/s)             
(Reading database ... 304641 files and directories currently installed.)
Preparing to unpack .../libraspberrypi0_0~20200520+git2fe4ca3-0ubuntu5~21.10.1_armhf.deb ...
Unpacking libraspberrypi0:armhf (0~20200520+git2fe4ca3-0ubuntu5~21.10.1) ...
dpkg: error processing archive /var/cache/apt/archives/libraspberrypi0_0~20200520+git2fe4ca3-0ubuntu5~21.10.1_armhf.deb (--unpack):
 trying to overwrite shared '/usr/share/lintian/overrides/libraspberrypi0', which is different from other instances of package libraspberrypi0:armhf
Errors were encountered while processing:
 /var/cache/apt/archives/libraspberrypi0_0~20200520+git2fe4ca3-0ubuntu5~21.10.1_armhf.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by theofficialgman** [comment]
> ### What happened?
> installed Box64 by pi-apps and now broken update from Ubuntu Mate

first off, Ubuntu 21.10 is an unsupported system.
Secondly, installing box64 did NOT cause this error. Box64 does not depend on  `libraspberrypi0:armhf`

>  pi-apps-5f3374a7 : Depends: libraspberrypi0:armhf

running the pi-apps naming function, we can see that `5f3374a7` is Box86
`echo Box86 | md5sum | cut -c1-8 | awk '{print $1}'` produces `5f3374a7` 

Impish is out of date and not supported, I suggest using 22.04 (ubuntu jammy the LTS) and seeing if the issue goes away.

In the meantime, you can uninstall box68 through pi-apps and the error will go away

**Comment by theofficialgman** [comment]
if 22.04, jammy still has the issue, I suggest filing a bug at https://bugs.launchpad.net/ubuntu/+source/raspberrypi-userland
describe that you are running a multiarch armhf and arm64 system and encounter errors when installing libraspberrypi0:armhf with libraspberrypi0:arm64 already installed due to conflicting files

**Comment by theofficialgman** [comment]
I'm going to close this as I've fully described the problem for the user and have gotten no response.

If you open a bug at the launchpad for the armhf/arm64 incompatibility, link it here
