### ISSUE TITLE
git clone erro 43

### ISSUE THREAD

**Issue by Abdullah22-rgb** [Botspot/pi-apps#1699]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)

### What happened?

app wont install

### Description

help me pls i need pro

### What is your operating system?

ubuntu 21.10

### (Optional) Error log? Terminal output? Debug messages?

```bash
git clone output was: bash: line 43: git: command not found
```

**Comment by theofficialgman** [comment]
@Abdullah22-rgb git is a requirement to install pi-apps. you have to install it before running the install script

@Botspot this is a bit of an oversight, `git` could be added to the dependencies list and this would be avoided. I will got ahead and do that

**Comment by theofficialgman** [comment]
@Abdullah22-rgb if you run the install command again, it will succeed
