### ISSUE TITLE
ClamAV (antivirus)

### ISSUE THREAD

**Issue by mobilegmYT** [Botspot/pi-apps#17]
I recently realized that no one has antivirus on their pi, and with hackers targeting Linux now, I found a old guide and made a small app. Still need to work out how to ask the user for when the antivirus runs and convert that to cron. 
[Clam Antivirus.zip](https://github.com/Botspot/pi-apps/files/5330633/Clam.Antivirus.zip)

**Comment by Botspot** [comment]
Cool!
A couple questions:

- I see you have it scanning /home. Would ClamAV ever notice if a virus was located outside of /home? I guess it would be harder for an attacker to place a virus outside of /home?
- Would it be simpler to have ClamAV scan upon every boot, or would that waste too much resources? (I can imagine some pi users wouldn't ever have theirs turned on at 11AM Monday)

**Comment by mobilegmYT** [comment]
1) You can totally edit the small script it makes to scan whatever
directories you want. We could change it to root directory

2) Starting on boot would lag insanely. I guess you could do some bash
wizardry to ask the user for when they want clamscan to run.
-- 
Cheers,
Mike
CEO of The Useless Companies Corp.

**Comment by mobilegmYT** [comment]
I really need to remove my email signatures

**Comment by Botspot** [comment]
> 1) You can totally edit the small script it makes to scan whatever directories you want. We could change it to root directory

But is that necessary? I have no idea - I'm a kid myself.

> 2) Starting on boot would lag insanely. I guess you could do some bash wizardry to ask the user for when they want it to run.

OK, so it consumes 100% of the CPU? Is that what you mean by 'lags insanely'? If that's the case, then I'd have it do a scan during [periods of inactivity](https://askubuntu.com/questions/202136/how-can-a-script-detect-a-users-idle-time). <- (click the link if you want to learn something)
I once did this with a Bitcoin miner on my Pi. If it detected no mouse/keyboard movement for 10 mins, it would start mining. If I wiggled the mouse it would stop.

**Comment by mobilegmYT** [comment]
Maybe i exaggerated a little, but there's noticeable lag, especially if your scanning the whole rootfs. I just looked through my clamscan logs and found that clam Mac can't even scan the whole of rootfs...so yea. It only scan up to 27262976 bytes.

**Comment by Botspot** [comment]
> It only scan up to 27262976 bytes.

...What? That's 27 megabytes! That's nothing! My /home directory contains over 75 **giga**bytes of files.

**Comment by mobilegmYT** [comment]
Wha- WHY. Ok so I did some googling, and it turns out that the error I got in logs was because it couldn't scan individual files that were too large to prevent DOS attacks. It can scan larger files if you use the flag `--max-filesize 100M` along with the command.

**Comment by mobilegmYT** [comment]
also you can use `--max-scansize=250M` for compressed files

**Comment by Botspot** [comment]
> Wha- WHY. Ok so I did some googling, and it turns out that the error I got in logs was because it couldn't scan individual files that were too large to prevent DOS attacks. It can scan larger files if you use the flag `--max-filesize 100M` along with the command.

That makes much more sense - a per-file size limit, not a total limit for your whole scan directory.

**Comment by mobilegmYT** [comment]
Ok. Can you write a script or something to ask for what the user wants for the crontab? Like something that asks for the hour, minute, and what day of the week and set them to variables?

**Comment by Botspot** [comment]
Currently I'm thinking of just doing a weekly schedule, but without using crontab.
The script I envision would write down which day it last scanned.
On every boot, it would check to see if it's been 7 days since that day.
Once it's been 7 days since then, run another scan.
In this way, the schedule is completely flexible, not relying on reboots or a certain time.

Let me know what you think.

**Comment by mobilegmYT** [comment]
Hmm. I do think it would work

**Comment by Botspot** [comment]
It's about time: Pi-Apps [has been released](https://www.raspberrypi.org/forums/viewtopic.php?f=63&t=287680) on the forums.
Feel free to tell everyone about it.

**Comment by Botspot** [comment]
I see your script adds `0 11 * * 1  bash /root/scanvirus.sh` to crontab. But /root/scanvirus.sh isn't mentioned anywhere else in any of your scripts, or on my filesystem. What happened?

**Comment by mobilegmYT** [comment]
Line 22 in the install script:
`#Make scan script
sudo echo '#!/bin/bash

#Location of log file
LOGNAME="/var/log/clamav/clamav-log-$(date +'%Y-%m-%d').log";

#Folder(s) to be scanned
DIRTOSCAN="/home";

#Scan to make logs and again to move sus files to quaratine
clamscan -ri "$DIRTOSCAN" &>"$LOGNAME";
clamscan -r --move=/home/pi/antivirus/quaratine/ "$DIRTOSCAN"' >> /root/scanvirus.sh`

**Comment by Botspot** [comment]
![2020-10-14-124310_1920x1080_scrot](https://user-images.githubusercontent.com/54716352/96025561-e93d9d80-0e1a-11eb-803f-29811b43d549.png)

**Comment by Botspot** [comment]
Oh I see why it didn't successfully actually create the file. For some reason, you can't `sudo echo`. It doesn't work.
I'll fix it to `sudo bash -c "echo 'stuff' > /root/scanvirus.sh"`

**Comment by mobilegmYT** [comment]
[Uploading Clam Antivirus.zip…]()

**Comment by Botspot** [comment]
Doesn't work. Remember: 

> Oh I see why it didn't successfully actually create the file. For some reason, you can't `sudo echo`. It doesn't work.
> I'll fix it to `sudo bash -c "echo 'stuff' > /root/scanvirus.sh"`

**Comment by Botspot** [comment]
Okay I made a bunch of changes for you.  
[Clam Antivirus.zip](https://github.com/Botspot/pi-apps/files/5482516/Clam.Antivirus.zip)  
Untested.

**Comment by mobilegmYT** [comment]
[Clam Antivirus.zip](https://github.com/Botspot/pi-apps/files/5490926/Clam.Antivirus.zip)
Here is the GUI version

**Comment by Botspot** [comment]
Added. Commit 3e98312e27ad0807ece973627227600fbc38c0eb
