### ISSUE TITLE
Error on uninstalling pacakge app

### ISSUE THREAD

**Issue by theofficialgman** [Botspot/pi-apps#1701]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)

### What happened?

Terminal error output (this did not stop the uninstall)

### Description

```
Uninstalling Kodi...

E: Command line option 'f' [from -yf] is not understood in combination with the other options.
```
I believe this was on uninstalling the package app. I haven't upgraded my system in a while, so the currently installed version of kodi was still a package app.
Looks like `-yf` is not a valid set of commands when doing `apt purge`
https://github.com/Botspot/pi-apps/blob/44414a35ff60db404df8809605a254a819d7ea2d/manage#L290

I'm not sure if the package actually purged successfully or not

### What is your operating system?

L4T Ubuntu Bionic

**Comment by Botspot** [comment]
I've seen that error appear when a package is broken. Otherwise, it works.
I just ran this command and it works:
`sudo apt purge --autoremove -yf yad`

**Comment by theofficialgman** [comment]
yeah this must be the case. since I can't reproduce on a working package or even `kodi` again.... not sure why this happened since kodi was perfectly working already even
