### ISSUE TITLE
Add Electric Sheep

### ISSUE THREAD

**Issue by MrBrain295** [Botspot/pi-apps#1703]
### What is the name of the app?

Electric Sheep

### (Optional) Where is the app hosted?

https://electricsheep.org/linux/

### About the app

It’s a distributed screen saver.

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [x] I have confirmed that this app can run on Raspberry Pi.

**Comment by Botspot** [comment]
> * [x]  I have confirmed that this app can run on Raspberry Pi.

Thank you for the app submission. You checked the box that says "I have confirmed that this app can run on Raspberry Pi." If that is really true, then could you share the build commands? Also, how smoothly does it run?

**Comment by MrBrain295** [comment]
I haven’t ran it myself but I saw [this](https://github.com/guysoft/ElectricSheepPi) and assumed it could run.

**Comment by Botspot** [comment]
> I haven’t ran it myself but I saw [this](https://github.com/guysoft/ElectricSheepPi) and assumed it could run.

While this looks interesting, we don't have very much manpower to try getting new apps working. Pi-Apps is maintained by only a handful of part-time volunteers. Would you be able to help us out by finding what commands are necessary to make this install/uninstall?

**Comment by MrBrain295** [comment]
I’ll give it a shot!

**Comment by derryktutt** [comment]
Found this
```
#!/usr/bin/env bash
# ElectrcSheepPi generation script
# Helper script that runs in a Raspbian chroot to create the ElectrcSheepPi distro
# Written by Guy Sheffer <guysoft at gmail dot com>
# GPL V3
########
set -x
set -e

source /common.sh
install_cleanup_trap

sudo apt-get update
sudo apt-get install -y subversion autoconf libtool libgtk2.0-dev libgl1-mesa-dev libavcodec-dev libavformat-dev libswscale-dev liblua5.1-0-dev libcurl4-openssl-dev libxml2-dev libjpeg9-dev libgtop2-dev libboost-dev libboost-filesystem-dev libboost-thread-dev libtinyxml-dev freeglut3-dev glee-dev libwxgtk3.0-gtk3-dev git checkinstall

pushd /home/pi
    git clone https://github.com/scottdraves/flam3.git
    pushd flam3
        autoreconf -f -i
        ./configure --build=arm-unknown-linux-gnueabihf
        export LDFLAGS="-Wl,--copy-dt-needed-entries"
        make
        sudo checkinstall -y
    popd
    
    git clone https://github.com/scottdraves/electricsheep.git
    pushd electricsheep/client_generic
        wget https://raw.githubusercontent.com/stefantalpalaru/gentoo-overlay/master/x11-misc/electricsheep/files/electricsheep-glext-prototypes.patch
        patch -p1 < electricsheep-glext-prototypes.patch
        ./autogen.sh
        ./configure --build=arm-unknown-linux-gnueabihf
        make
	sudo checkinstall --fstrans=no -y
    popd
pushd

```

**Comment by theofficialgman** [comment]
project electricsheep is very unmaintained, does not compile on many newer distros, and has almost 100 open bugs
closing
