### ISSUE TITLE
add MAME

### ISSUE THREAD

**Issue by frankmilliron** [Botspot/pi-apps#1707]
### What is the name of the app?

MAME

### About the app

MAME (Multiple Arcade Machine Emulator) can be installed with 'sudo apt-get install mame'. I did a clean install today and MAME was the only item I had to go into 'Add/Remove Software' to add. Repos have both 32-bit and 64-bit versions. I usually install 'mame-data' and 'mame-tools' as well, but I don't think they are necessary.

Cool and easy-to-use app! Thank you. Frank

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by derryktutt** [comment]
[MAME.zip](https://github.com/Botspot/pi-apps/files/8598931/MAME.zip)

**Comment by theofficialgman** [comment]
https://github.com/Botspot/pi-apps/issues/185
