### ISSUE TITLE
Snap Store

### ISSUE THREAD

**Issue by Botspot** [Botspot/pi-apps#171]
I've heard mention of there being a GUI app store for `snap`. It would be cool to install this on RPi, and then add it to Pi-Apps.

**Comment by techcoder20** [comment]
It is possible to install it on RPi but it might be a little hard as you need to reboot after installing snap so once we install snap with apt we need to reboot then only we can install snap store with snap.

**Comment by Itai-Nelken** [comment]
I always installed snap this way:
`sudo apt install snap`
sudo snap install snap-store`
reboot
 
never had any issues doing it like that.
but it seems canonical have changed the way to install it:
https://snapcraft.io/docs/installing-snap-on-raspbian
https://snapcraft.io/docs/installing-snap-store-app

as @techcoder20 said, you have to reboot after installing snap (I'm not sure it's necessary after installing `snap`, maybe make the installer to ask at the end of installation if user wants to reboot) and now you have to install `core` snap package.

here are the instructions from the 2 links above:
```
sudo apt update
sudo apt install snapd
```
reboot here
```
sudo snap install core

# install snap-store
sudo snap install snap-store
```
**A VERY IMPORTANT NOTE!**
don't install `gnome-software`, it conflicts with add/remove software (`pi-package`) and anyway isn't as useful for a lot of people (I think?).
if you want to install flatpak apps with a gui app store, than try to use this: https://gitlab.gnome.org/haecker-felix/souk (never worked for me though).

**Comment by Itai-Nelken** [comment]
I'll try installing it and see if a reboot is really needed after installing `snapd`

**Comment by chunky-milk** [comment]
Just FYI, in order to get the Snap applications to appear in the menu, you may have to use this command: 
`ln -st ~/.local/share/applications /var/lib/snapd/desktop/applications/*.desktop `
due to the desktop files being misplaced.

**Comment by Itai-Nelken** [comment]
@chunky-milk I never had any problem with menu shortcuts not appearing, and when it did happen a reboot fixed it.

**Comment by chunky-milk** [comment]
Awesome! That must mean they fixed the bug then!

**Comment by Itai-Nelken** [comment]
I just installed snap-store:
```sh
sudo apt update
sudo apt install snapd
sudo snap install core
sudo snap install snap-store
```
here I rebooted.

I can confirm that until you reboot, the menu shortcut for snap-store doesn't appear.
![snap-store](https://user-images.githubusercontent.com/70802936/103537857-cfea4180-4e9d-11eb-8b4e-31876a0bafde.png)

**Comment by Itai-Nelken** [comment]
[Snap-Store.zip](https://github.com/Botspot/pi-apps/files/5792344/Snap-Store.zip)
@Botspot I didn't find any way to make the menu shortcuts appear properly without rebooting after installing snap-store,
so I added a yad window that stays on top with a countdown indicator that waits 15seconds before rebooting, therealso is a cancel button.
that's the best way to install I know of.

I asked a question in askubuntu: https://askubuntu.com/questions/1306650/is-it-possible-to-complete-snap-installation-without-rebooting

**Comment by techcoder20** [comment]
I was able to figure out how to install snap store without rebooting and I am manually copying the desktop entry as in twister the desktop entry might come after rebooting but in rpi os it won't come even after rebooting

**Comment by Itai-Nelken** [comment]
> I was able to figure out how to install snap store without rebooting and I am manually copying the desktop entry as in twister the desktop entry might come after rebooting but in rpi os it won't come even after rebooting

weird it always showed up for me on RPiOS after rebooting.

**Comment by techcoder20** [comment]
Oh maybe its just for me 😭

**Comment by Botspot** [comment]
> > I was able to figure out how to install snap store without rebooting and I am manually copying the desktop entry as in twister the desktop entry might come after rebooting but in rpi os it won't come even after rebooting
> 
> weird it always showed up for me on RPiOS after rebooting.

Same here. I was never able to get anything snap-related working, simply because the desktop files weren't there.

**Comment by Itai-Nelken** [comment]
> > > I was able to figure out how to install snap store without rebooting and I am manually copying the desktop entry as in twister the desktop entry might come after rebooting but in rpi os it won't come even after rebooting
> > 
> > 
> > weird it always showed up for me on RPiOS after rebooting.
> 
> Same here. I was never able to get anything snap-related working, simply because the desktop files weren't there.

that's really weird!
I used snaps on my RPi on RPiOS for around a year before I got comfortable with the command line, and the menu shortcuts always appeared after a reboot.

**Comment by Botspot** [comment]
Added Snap Store to Pi-Apps with commit 67624edaa842edc7a15b939799f9bc876e4935f5.

Sent @techcoder20 a 5 dollar gift card for his efforts in making this app. (The reward was stated in advance and anyone had a chance to complete it)
