### ISSUE TITLE
Add to apt library

### ISSUE THREAD

**Issue by rbcoder117** [Botspot/pi-apps#1713]
### Cool ideas?

We should add this to the apt library so people only have sudo apt install pi-apps

**Comment by theofficialgman** [comment]
unfortunately this is not feasible.
for one, there is no such thing at "the apt library".
there are debian repos, each distro has their own with the main upstream source of packages being the debian repositories and ubuntu repositories. projects such as raspbian create their own distros based on these repositories and host their own packages.

pi-apps can be installed currently in any debian based system with a simple install command. 

instead, what you are asking is for us to first create a debian package which is unchanging to install pi-apps, then go to each repo maintainer and request our deb to be added to it. it would of course be a armhf and arm64 only debian package which repo maintainers do not like (they like for a package to be for all architectures). Now if our deb package has an issue and breaks at some point, then now we have to go to each of these maintainers again and make sure the package gets updated, an process that takes weeks, months, or even never depending on the distro release model.
