### ISSUE TITLE
Not installing. 

### ISSUE THREAD

**Issue by skeleton-mcpi** [Botspot/pi-apps#1716]
Error:

APT reported a typo in the sources.list file.

You must look around in /etc/apt/sources.list and /etc/apt/sources.list.d and fix the typo.

This appears when I try to install  gMCPIL or jMCPIL through Pi-Apps.
This started today. I've had no trouble doing it before in Pi-Apps.

**Comment by Itai-Nelken** [comment]
The error clearly states the problem: there is a typo in your sources.listbir a list file in sources.list.d.
This isn't a problem with pi-apps, so I'll close this issue.
However I'll try to help. 
Can you send the output of `sudo apt update` please?

**Comment by skeleton-mcpi** [comment]
I knew it said that, but I have no idea how to do it. It says failed to run sudo apt update. I'll get back to you when I find out more.

**Comment by Itai-Nelken** [comment]
Could you send the full output, every line?

**Comment by skeleton-mcpi** [comment]
Yep, just loading it. Sorry for the delay, I've had a busy week.

**Comment by skeleton-mcpi** [comment]
Oh, nevermind. It has fixed. Seems like it was updated and has fixed. Thanks.
