### ISSUE TITLE
Pi4 Dual Screen Update Window Placement

### ISSUE THREAD

**Issue by Joshy-2010** [Botspot/pi-apps#172]
I am using both HDMI Ports of my Pi4, one for my primary PC Display and one for a small Touchscreen with Displays some sort of Smart Home GUI (which is always on the highest? layer / meaning the second display isn't meant to use programs.) 
Sadly every time the Pi Apps update window appears, it does so just BARELY on the bottom right corner of my main screen so I cant press the "OK" button. So firstly i have to close my custom GUI and then also move the screen's position relative to another (--> "Screen Settings" because second screen is much smaller) to apply the update. I'm really not into this stuff but maybe there's a way to just spawn the update window in the middle of one Display rather than halt way between them. 
Apart from that, really great tool, thanks man!

**Comment by Botspot** [comment]
This is probably due to how [Pi-Apps's updater calculates the screen's width and height](https://github.com/Botspot/pi-apps/blob/master/updater#L161).

Try running this and let's see what it says:
```
xdpyinfo
```

**Comment by Joshy-2010** [comment]
The command returns the following:
dimensions:    2944x1200 pixels (778x317 millimeters)
My first, main display has an resolution of 1920x1200 and the second one has a resolution if 1024x600. Since they are placed horizontally to another this output makes total sense (just both widths added together X biggest height), the command just assumes one big display. And after looking at the line of code you linked the programs behaviour make sense, too. pi-apps just puts the update window "roughly" in the middle of this supposed big singular screen. 
Problem is, since the second screen is (Y) much smaller and pi-apps tries to position the update window in the lower (Y) left (X) half of the big display (at least for me)  there isn't actually any physical display there, if you understand that I mean (Can try to add a picture if you want). Plus, as I said, the second display isn't actually supposed to display anything but my GUI.
I mean this isn't a super important issue, but maybe there's any easy way to get the width and height of just one display, which the user can choose.

**Comment by Botspot** [comment]
I would like for the `xdpyinfo` command to return correct results on dual-display systems.

Okay let's try [this](https://askubuntu.com/questions/584688/how-can-i-get-the-monitor-resolution-using-the-command-line) and have you run:
```
xrandr
```

**Comment by Joshy-2010** [comment]
Seems much better:
Screen 0: minimum 320 x 200, current 2944 x 1200, maximum 7680 x 7680
HDMI-1 connected primary 1920x1200+0+0 (normal left inverted right x axis y axis) 518mm x 324mm
   1920x1200     59.95*+  74.92  
   1920x1080     60.00    50.00    59.94  
   1600x1200     60.00  
   1680x1050     59.88  
   1600x900      60.00  
   1280x1024     75.02    60.02  
   1440x900      59.90  
   1280x800      59.91  
   1280x720      60.00    50.00    59.94  
   1024x768      75.03    60.00  
   800x600       75.00    60.32  
   720x576       50.00  
   720x480       60.00    59.94  
   640x480       75.00    60.00    59.94  
   720x400       70.08  
HDMI-2 connected 1024x600+1920+0 (normal left inverted right x axis y axis) 0mm x 0mm
   FIXED_MODE    59.85*+

**Comment by Botspot** [comment]
Okay @Joshy-2010, I think I got it working for you.

- Please open the `/home/pi/pi-apps/updater` file in a text editor.
If you're using Mousepad (the default text editor), enable line numbers by going to View -> Line numbers.  
- Replace lines 161-162 with:
```
screen_width="$(xrandr | grep "HDMI-1" | awk '{print $4}' | tr 'x+' ' ' | awk '{print $1}')"
screen_height="$(xrandr | grep "HDMI-1" | awk '{print $4}' | tr 'x+' ' ' | awk '{print $2}')"
```
- Afterwards, make sure Pi-Apps is set to update "always".  
- Launch Pi-Apps.  
- See if the pop-up appears in the right place now.

**Comment by Joshy-2010** [comment]
It does work now, thanks! 
Though it still appears right at the right edge of my display. You surely have a reason for that, but for me i just changed [Code](https://github.com/Botspot/pi-apps/blob/master/updater#L166) to  
--geometry=260+$((screen_width-500))+$((screen_height-150)) \    (instead of 262 500)
so that the window appears more centered and overall make it look a bit prettier.
Thx for the quick update, i suppose i can close this now, right?

**Comment by Botspot** [comment]
> It does work now, thanks!
> Though it still appears right at the right edge of my display. You surely have a reason for that, but for me i just changed [Line 166](https://github.com/Botspot/pi-apps/blob/master/updater#L166)

It's supposed to be in about the same spot as a Windows notification.  
![windows notification screenshot](https://www.howtogeek.com/wp-content/uploads/2015/08/00_lead_image_email_notification.png)  
 Is that what you saw? Was it fully on the screen, or partially hidden?

**Comment by Joshy-2010** [comment]
Ah, now i get it! 
Yes, that's basically what I saw. At first, i thought some bits are missing (maybe because it looked a bit strange with my wallpaper), but after editing the code, rebooting and seeing the window more centered I can assure you that the whole window was indeed visible after your fix.
Thx again

**Comment by Botspot** [comment]
Awesome. I will push those changes to Pi-Apps then. Thanks for running that test for me!

**Comment by Joshy-2010** [comment]
Just wanted to come back and say that everything is working great now.
