### ISSUE TITLE
Question about Minecraft Java Server

### ISSUE THREAD

**Issue by Pythonic456** [Botspot/pi-apps#1724]
Just a quick question, feel free to close this issue if you answer it :)

Can you have multiple instances of Minecraft Java Server? Is multiple servers a feature?

Thanks 👍

**Comment by theofficialgman** [comment]
right now, no. the script is written to support only one server which it makes in `$HOME/Minecraft-Java-Server`

it would require a more complicated install and uninstall script to support multiple servers. If you wanted multiple, each server would need its own install path, and its own systemd service.

In general, I wouldn't recommend hosting multiple servers on a pi anyway... they aren't powerful enough for that if you have actual active users on them.

**Comment by Botspot** [comment]
> Just a quick question, feel free to close this issue if you answer it :)

Done. :)
