### ISSUE TITLE
minecraft java install error

### ISSUE THREAD

**Issue by premkubade** [Botspot/pi-apps#173]
when i try to install minecraft java it gives me a error that it failed to install minecraft java launcher

**Comment by Itai-Nelken** [comment]
could you send the terminal output or a screenshot of the error?

**Comment by Botspot** [comment]
> when i try to install minecraft java it gives me a error that it failed to install minecraft java launcher

What version of Minecraft Java were you trying to install?

**Comment by mobilegmYT** [comment]
@Botspot I guess close this issue due to inactivity???

**Comment by premkubade** [comment]
Installing Minecraft Java with install-64 script
mkdir: cannot create directory ‘/home/pi/Minecraft’: File exists
Failed to install the launcher!

Failed to install Minecraft Java with install-64 script!

Close this window to exit.

**Comment by premkubade** [comment]
this error i found while installing

**Comment by Botspot** [comment]
> this error i found while installing

It looks like it was partially installed prior to you installing it this time. Please try uninstalling it, then install it again.

**Comment by premkubade** [comment]
i tried it 3 times uninstalling and installing but the result is same

**Comment by Botspot** [comment]
> i tried it 3 times uninstalling and installing but the result is same

Well then try manually deleting `/home/pi/Minecraft`.

**Comment by premkubade** [comment]
ok i will try it

**Comment by premkubade** [comment]
Setup 6/9
Setup 7/9
Extracting java ...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package openjdk-11-jdk is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'openjdk-11-jdk' has no installation candidate
Failed to install the launcher!

Failed to install Minecraft Java with install-64 script!

Close this window to exit.

**Comment by Botspot** [comment]
> ```
> Setup 6/9
> Setup 7/9
> Extracting java ...
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> Package openjdk-11-jdk is not available, but is referred to by another package.
> This may mean that the package is missing, has been obsoleted, or
> is only available from another source
> 
> E: Package 'openjdk-11-jdk' has no installation candidate
> Failed to install the launcher!
> 
> Failed to install Minecraft Java with install-64 script!
> 
> Close this window to exit.
> ```

Okay that is quite weird. Try searching for the java JDK yourself:
```
apt search openjdk
```
(no need for `sudo` for `apt search`)

**Comment by Botspot** [comment]
How is progress coming, @premkubade?
