### ISSUE TITLE
app is having me update apps I do not have installed

### ISSUE THREAD

**Issue by Daggerfellar** [Botspot/pi-apps#1742]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)

### What happened?

updates are trying to get me to install apps I do not have installed

### Description

app is showing updates for applications I do not have installed such as Tabby, VeraCrypt, Zoom, Xtreme mod manager, OBS studio, microsoft powershell, notepad ++, and several others. 

I do not have these installed and its a pain to unselect them just to update the apps I have installed and want on my Raspberry Pi4b

### What is your operating system?

Raspian Bullseye 64bit, Pi4b

**Comment by theofficialgman** [comment]
closing as duplicate and user misinterpretation. pi-apps is not updating the apps you do not have install. it is updating the local pi-apps scripts for those apps so you always have the most up to date version for when you do go to install these apps.

see here for explanation:
https://github.com/Botspot/pi-apps/issues/1559#issuecomment-1059226002
in the future this may be chosen to be hidden from the user

**Comment by Jai-JAP** [comment]
This is often misunderstood as an issue. I had a plan to make pi-apps not download a single script and just an index of apps as a json and then download scripts as the user demands install or uninstalling an app. That sounds kinda weird and i also think that would be even more pain to implement it with all the features pi-apps has

**Comment by Jai-JAP** [comment]
I never tried implementing the concept but that should be possible if i get enough time from studies and exams :\

**Comment by rbcoder117** [comment]
@Jai-JAP Lol
