### ISSUE TITLE
Cura 5 Beta Raspberry Pi4 install error

### ISSUE THREAD

**Issue by ThaPg** [Botspot/pi-apps#1749]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [ ] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)

### What happened?

I tried to install the new Cura 5 Beta but I took error.

### Description

I found interesting to try new Cura 5 Beta but I can't install it. If I can understand right, there are problem with installing script.

### What is your operating system?

OS: Debian GNU/Linux 11 (bullseye) OS architecture: 64-bit

### (Optional) Error log? Terminal output? Debug messages?

```bash
Error log:

OS: Debian GNU/Linux 11 (bullseye)
OS architecture: 64-bit
Installed Pi-Apps version: 05/01/2022
Most recent Pi-Apps version: 05/01/2022
Kernel: aarch64 5.15.32-v8+
Device model: Raspberry Pi 4 Model B Rev 1.1
Ram size: 3.79 GB
Raspberry Pi OS image version: 2022-01-28
Language: en_US.UTF-8

BEGINNING OF LOG FILE:
-----------------------

Downloading example.com repository... 
Failed to download example.com repository.
Errors: Cloning into 'example.com'...
fatal: repository 'https://example.com/' not found

Failed to install Cura 5 Beta!
◢◣Need help? Copy the ENTIRE terminal output or take a screenshot.
Please ask on Github: https://github.com/Botspot/pi-apps/issues/new/choose
Or on Discord: https://discord.gg/RXSTvaUvuu
```

**Comment by Botspot** [comment]
It appears that you launched the Pi-Apps App Creator, created a new app called "Cura 5 Beta", and immediately tried to install it. **This will not work.**

It takes more than a name to make an app install. You'd have to first find out how to install Cura 5 Beta, then convert that knowledge into a scripted form. This is a form of computer programming, and Pi-Apps is not a magic shortcut in this regard.

Cura builds suitable for the Raspberry Pi are located at https://github.com/smartavionics/Cura. Unless you have good programming knowledge and a healthy dose of determination, I suggest you wait until @smartavionics releases Cura v5.

You're not alone BTW - I'm eagerly waiting to try Cura 5 as well. 😁

**Comment by smartavionics** [comment]
Sorry to say that I am not intending to produce builds based on Cura 5 any time soon (if ever). This is for a few reasons:

1 - my source code has diverged greatly from the UM source code and so combining the two would be a large amount of work.

2 - UM have changed how Cura is built and I suspect that it will not work for the Pi releases. Again, this could probably be worked around but would involve some work.

3 - I am expecting Cura 5 to be pretty buggy for at least the first few releases so it is best avoided until UM sort out the worst problems.

**Comment by Botspot** [comment]
@smartavionics, have you decided to perpetually stay behind with Cura v4, or are there plans to get v5 working?

**Comment by smartavionics** [comment]
For the reasons I give above,  I won't be doing it but I have no issue with others taking any of my code and incorporating it into Cura 5.
