### ISSUE TITLE
Steam will not run on Pi 400

### ISSUE THREAD

**Issue by moocow1452** [Botspot/pi-apps#175]
When I'm trying to install Steam on a fresh Pi 400 installation, I can install Box86 and Steam, and when I click the menu launcher, it updates the pin. But clicking on the Desktop icon just makes the cursor have the hourglass for about 10 seconds, and nothing else happens. Executing via terminal doesn't open a terminal and gives the same behavior, and trying to open terminal with "box86 steam"  gives me this error.

https://paste.ubuntu.com/p/P7VtsyQXY2

I'm probably missing something obvious, but I'm kinda dead in the water otherwise.

**Comment by Botspot** [comment]
First, let's make sure nothing is still running in the background:
```
killall -9 steam box86
```
Now let's try running Steam:
```
box86 steam
```
Still didn't work?  
Okay let's reinstall box86. Find Box86 in Pi-Apps, click Uninstall, then click Install. Then try running the above command again and see if anything's different.

**Comment by moocow1452** [comment]
Neither Steam or Box86 were running, and when trying to uninstall Box86, I
got this error.

https://paste.ubuntu.com/p/RjQhqjkDrG

Compiling from the web worked okay following the compile instructions from
GitHub, and using the Steam iteration from Pi Apps worked fine, so I dunno
what the deal was with the original build was. Maybe because it was
different silicon?

**Comment by Botspot** [comment]
> Neither Steam or Box86 were running, and when trying to uninstall Box86, I got this error. https://paste.ubuntu.com/p/RjQhqjkDrG Compiling from the web worked okay following the compile instructions from GitHub, and using the Steam iteration from Pi Apps worked fine, so I dunno what the deal was with the original build was. Maybe because it was different silicon?

Okay so compiling worked for you. Good. I guess you must have installed Box86 prior to this and it was out of date.

Try installing this week's precompiled version of box86.
```
wget -qO- https://raw.githubusercontent.com/Botspot/box86-updater/main/update-box86 | bash
```

**Comment by Botspot** [comment]
Well did it work?

**Comment by moocow1452** [comment]
Yeah, I think what happened is that I tried uninstalling Retropie, (which removed all of its dependencies even though I didn't want it to,) and that borked my installation for Box86 so that I had to compile it manually to reinstall.
