### ISSUE TITLE
Electron 18.0.0 - 18.2.3 broken on buster/bionic and older linux distros

### ISSUE THREAD

**Issue by hyppyp** [Botspot/pi-apps#1752]
Running list of apps broken by electron 18 in pi-apps (manually downgraded to older versions):

edit: everything currently in pi-apps has been fixed

**Comment by Rak1ta** [comment]
I have RaspiOS Buster 32bit - update works.

**Comment by hyppyp** [comment]
Deleted, booted and reinstalled it. Nada! :(

**Comment by ryanfortner** [comment]
Can you please run ‘whatsapp’ in a terminal window, and post the full output here?

These are @cycool29 ’s builds, they may also be able to help.

**Comment by cycool29** [comment]
The latest DEB works for me on both 32 and 64 bit.

**Comment by hyppyp** [comment]
/opt/WhatsApp/WhatsApp: /usr/lib/aarch64-linux-gnu/libxkbcommon.so.0: version `V_1.0.0' not found (required by /opt/WhatsApp/WhatsApp)

**Comment by ryanfortner** [comment]
@hyppyp try running `sudo apt install libxkbcommon0` in a terminal, then try running whatsapp again.

**Comment by hyppyp** [comment]
libxkbcommon0 is reeds de nieuwste versie (0.8.2-1). 
libxkbcommon0 staat ingesteld op handmatig geïnstalleerd.
(is Dutch, sorry - already latest version (0.8.2-1), set to manual install

**Comment by ryanfortner** [comment]
> libxkbcommon0 is reeds de nieuwste versie (0.8.2-1). libxkbcommon0 staat ingesteld op handmatig geïnstalleerd. (is Dutch, sorry - already latest version (0.8.2-1), set to manual install

Try `sudo apt install libxkbcommon` (without the 0)

**Comment by hyppyp** [comment]
E: Kan pakket libxkbcommon niet vinden
(can't find package)

**Comment by ryanfortner** [comment]
@cycool29 it looks like your debs work on debian Bullseye, but not Buster due to the availability of a newer libxkbcommon version in the bullseye repos. 

Can you configure your [workflow](https://github.com/cycool29/whatsapp-for-linux/blob/main/.github/workflows/build-whatsapp.yml) to build for Buster, or at least a lower version of Ubuntu, for broader compatilbility?

**Comment by cycool29** [comment]
@hyppyp Try:

```bash
wget https://github.com/cycool29/testing-repo/raw/master/whatsapp_7.0_arm64.deb
sudo apt install ./whatsapp_7.0_arm64.deb
```

**Comment by hyppyp** [comment]
/opt/WhatsApp/WhatsApp: /usr/lib/aarch64-linux-gnu/libxkbcommon.so.0: version `V_1.0.0' not found (required by /opt/WhatsApp/WhatsApp)

:(

**Comment by theofficialgman** [comment]
I can also confirm this issue on bionic
`/opt/WhatsApp/WhatsApp: /usr/lib/aarch64-linux-gnu/libxkbcommon.so.0: version `V_1.0.0' not found (required by /opt/WhatsApp/WhatsApp)`

either this is a nativefier bug (aka, they are building their binaries for electron/chromium on something newer than buster/bionic) or has to do with upstream whatsapp. neither bionic or buster have libxkbcommon version greater or equal to 1.X (they are on version 0.8)

**Comment by theofficialgman** [comment]
@cycool29 its an upstream electron bug https://github.com/electron/electron/issues/33533

**Comment by cycool29** [comment]
I just fallback the release to 5.0. The next auto-update version PR should fix this issue.

**Comment by Itai-Nelken** [comment]
@hyppyp try again, it should work.

**Comment by hyppyp** [comment]
Yep, version 5.0 works! :)

**Comment by theofficialgman** [comment]
alright good, I've renamed this bug and we will keep it open. any further apps like https://github.com/SpacingBat3/WebCord which are now being built on electron 18 will be tracked here either until electron 19 goes stable or the fix is backported to electron 18

**Comment by Rak1ta** [comment]
@cycool29 Hello. Can you advise me? I have **Buster 32bit** but WhatsApp 6.0, Discord 3.1.4, Turbowarp 1.3.0 work and install correctly, but here they write that there should be an error. That is, in the future, what kind of software updates will work normally? I rarely use raspberry pi, I don't want to waste time updating (reinstalling).

**Comment by theofficialgman** [comment]
the fix was just pulled into 18.x.y electron branch today. it did not make it into v18.2.3, but will be in v18.2.4
https://github.com/electron/electron/pull/34155

someone keep track of electron releases and watch out for 18.2.4 in the next coming days

**Comment by theofficialgman** [comment]
electron 18.2.4 has been released. it is time for these apps to update.

electron fiddle PR can be merged now https://github.com/Botspot/pi-apps/pull/1128

notifications need to be made to these upstream projects:
tabby
turbowarp
whatsapp
electron fiddle
webcord
