### ISSUE TITLE
Flutter

### ISSUE THREAD

**Issue by virat2010** [Botspot/pi-apps#1753]
### What is the name of the app?

Flutter

### (Optional) Where is the app hosted?

https://docs.flutter.dev/get-started/install/linux

this doesn't work:
cd ~/development
tar xf ~/Downloads/flutter_linux_2.10.5-stable.tar.xz

this does:
git clone https://github.com/flutter/flutter.git
or
git clone https://github.com/flutter/flutter.git -b stable

then:
export PATH="$PATH:`pwd`/flutter/bin"

flutter precache

and then:
flutter doctor
the line above starts the service

### About the app

This app is a web developement platform that allows you create applications for all kinds of platforms, sorry for my bad english

there was one similar suggestion:
flutter pub get #1459

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by virat2010** [comment]
hello?

**Comment by theofficialgman** [comment]
Pi-Apps currently has over 70 app requested (including some open PRs for apps to be added).
We can't always get to every request in a timely fashion. In general, we like to have a pi-apps maintainer or contributor be somewhat responsible or knowledgeable for every app contained in pi-apps.

From my understanding, flutter is a google software development kit/library. I would assume any developers which want to use this library already understand how to follow the install flutter instructions.

I'll let botspot comment on this if he wants, but to me this seems like it would not be very helpful for everyday GUI users (based on our guidelines): https://github.com/Botspot/pi-apps/issues/185

> Apps that are not designed for everyday GUI users won't be accepted. (command-line file servers, webservers, etc)

**Comment by Painadath** [comment]
Actually there is a project called flutter-pi but the problem is android sdk. i have tried a lot of ways to install it but no sucess

**Comment by virat2010** [comment]
Thank you!
