### ISSUE TITLE
add Android Studio

### ISSUE THREAD

**Issue by virat2010** [Botspot/pi-apps#1754]
### Cool ideas?

What about android studio?
Could guys make an installation script for android studio
I couldn't get it working.
this is quite a challenge, I don't expect you guys to get it done either
I am a noob but I got couple of steps on most things

**Comment by Crilum** [comment]
I don't think Android Studio on the Pi would work very well (if you could even get it to install.).
Android Studio is proprietary (you can't see the source code), and Google doesn't release arm linux builds, so short of using an emulator (like box86), which would be *really* slow, it's not possible.

Sidenote: Could you use the `App Request` issue type for app requests, in the future?

**Comment by ryanfortner** [comment]
Google provides a precompiled x86-64 binary. Visit this page, and scroll down to Linux (64-bit): https://developer.android.com/studio#downloads. You'll need to use something like box64 or qemu to run it though. 

Keep in mind that there really is no point running the software on a pi because of hardware requirements. The minimum RAM requirement is 8GB, and even then, it's said to run quite slowly. https://raspberrypi.stackexchange.com/questions/106140/android-studio-on-rpi4

**Comment by theofficialgman** [comment]
you may also be able to build directly from source https://android.googlesource.com/platform/tools/base/+/studio-master-dev/studio.md
my guess is this will take a while and maybe you will run into issues getting all the dependencies but it should be possible

**Comment by theofficialgman** [comment]
> Android Studio is proprietary (you can't see the source code)
🤔 don't think so... see above, its FOSS
```
Like the Android operating system, Android Studio is open source and free of charge to all. Android releases source code to the Android Open Source Project (AOSP) after each stable release, described in detail here.
```

**Comment by Crilum** [comment]
@theofficialgman Thanks for correcting me.. I didn't realize it was open source...

**Comment by theofficialgman** [comment]
in traditional google fashion... it takes up a lot of space to build
currently at 10GB during the sync of the repos

if someone has more space, it should be pretty simple to follow the instructions at that link

**Comment by Crilum** [comment]
I'm going to build on a TB Hard Drive.. :rofl:

**Comment by Crilum** [comment]
Google's `repo` command is kind of broken on my system.. Having to fix Python indentation errors and so forth..

**Comment by theofficialgman** [comment]
I used python3.8 and so it worked for me.. granted I am using the old version of `repo` from bionic.. so its old

**Comment by Crilum** [comment]
Well, the licenses say it's copywrited from 2008, so...

**Comment by Crilum** [comment]
Using 3.8 I still have errors

**Comment by Crilum** [comment]
I'm not getting anywhere with building Android Studio.. Bazel fails with:
```
$ sudo ./build_studio.sh
## Building android-studio ##
## Dist dir : /media/pi/GSource/studio-master-dev/tools/idea/out/studio/dist
## Qualifier: 
## Build Num: SNAPSHOT
## Out dir  : /media/pi/GSource/studio-master-dev/tools/idea/out/studio
## Prog dir : .
## ASWB?    : 
## UITESTS? : false

## JAVA_HOME: /usr/bin/
## BAZEL: /media/pi/GSource/studio-master-dev/prebuilts/tools/linux-armv7l/bazel/bazel-4.2.2
Extracting Bazel installation...
WARNING: Ignoring JAVA_HOME, because it must point to a JDK, not a JRE.
WARNING: Ignoring JAVA_HOME, because it must point to a JDK, not a JRE.
Starting local Bazel server and connecting to it...
ERROR: Error fetching repository: java.io.IOException: The repository's path is "tools/vendor/google3/blaze" (absolute: "/media/pi/GSource/studio-master-dev/tools/vendor/google3/blaze") but this directory does not exist.
ERROR: no such package '@blaze//': The repository's path is "tools/vendor/google3/blaze" (absolute: "/media/pi/GSource/studio-master-dev/tools/vendor/google3/blaze") but this directory does not exist.
## BAZEL_BIN: 
Buildfile: /media/pi/GSource/studio-master-dev/tools/idea/build.xml

init:

bazel-dependencies:
     [exec] Traceback (most recent call last):
     [exec]   File "/media/pi/GSource/studio-master-dev/tools/base/bazel/bazel", line 154, in <module>
     [exec]     main()
     [exec]   File "/media/pi/GSource/studio-master-dev/tools/base/bazel/bazel", line 84, in main
     [exec]     sys.exit(subprocess.call([bazel, bazelrc_arg] + args, env=env))
     [exec]   File "/usr/lib/python3.9/subprocess.py", line 349, in call
     [exec]     with Popen(*popenargs, **kwargs) as p:
     [exec]   File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
     [exec]     self._execute_child(args, executable, preexec_fn, close_fds,
     [exec]   File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child
     [exec]     raise child_exception_type(errno_num, err_msg, err_filename)
     [exec] OSError: [Errno 8] Exec format error: '/media/pi/GSource/studio-master-dev/prebuilts/tools/linux-x86_64/bazel/bazel-real'

BUILD FAILED
/media/pi/GSource/studio-master-dev/tools/idea/build.xml:47: The following error occurred while executing this line:
/media/pi/GSource/studio-master-dev/tools/adt/idea/android/build.xml:33: exec returned: 1

Total time: 1 second
```

**Comment by Crilum** [comment]
If anybody needs a bazel build, here it is: https://github.com/koenvervloesem/bazel-on-arm/releases/tag/v4.2.2

**Comment by Itai-Nelken** [comment]
> I'm not getting anywhere with building Android Studio.. Bazel fails with:
> ```
> $ sudo ./build_studio.sh
> ## Building android-studio ##
> ## Dist dir : /media/pi/GSource/studio-master-dev/tools/idea/out/studio/dist
> ## Qualifier: 
> ## Build Num: SNAPSHOT
> ## Out dir  : /media/pi/GSource/studio-master-dev/tools/idea/out/studio
> ## Prog dir : .
> ## ASWB?    : 
> ## UITESTS? : false
> 
> ## JAVA_HOME: /usr/bin/
> ## BAZEL: /media/pi/GSource/studio-master-dev/prebuilts/tools/linux-armv7l/bazel/bazel-4.2.2
> Extracting Bazel installation...
> WARNING: Ignoring JAVA_HOME, because it must point to a JDK, not a JRE.
> WARNING: Ignoring JAVA_HOME, because it must point to a JDK, not a JRE.
> Starting local Bazel server and connecting to it...
> ERROR: Error fetching repository: java.io.IOException: The repository's path is "tools/vendor/google3/blaze" (absolute: "/media/pi/GSource/studio-master-dev/tools/vendor/google3/blaze") but this directory does not exist.
> ERROR: no such package '@blaze//': The repository's path is "tools/vendor/google3/blaze" (absolute: "/media/pi/GSource/studio-master-dev/tools/vendor/google3/blaze") but this directory does not exist.
> ## BAZEL_BIN: 
> Buildfile: /media/pi/GSource/studio-master-dev/tools/idea/build.xml
> 
> init:
> 
> bazel-dependencies:
>      [exec] Traceback (most recent call last):
>      [exec]   File "/media/pi/GSource/studio-master-dev/tools/base/bazel/bazel", line 154, in <module>
>      [exec]     main()
>      [exec]   File "/media/pi/GSource/studio-master-dev/tools/base/bazel/bazel", line 84, in main
>      [exec]     sys.exit(subprocess.call([bazel, bazelrc_arg] + args, env=env))
>      [exec]   File "/usr/lib/python3.9/subprocess.py", line 349, in call
>      [exec]     with Popen(*popenargs, **kwargs) as p:
>      [exec]   File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
>      [exec]     self._execute_child(args, executable, preexec_fn, close_fds,
>      [exec]   File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child
>      [exec]     raise child_exception_type(errno_num, err_msg, err_filename)
>      [exec] OSError: [Errno 8] Exec format error: '/media/pi/GSource/studio-master-dev/prebuilts/tools/linux-x86_64/bazel/bazel-real'
> 
> BUILD FAILED
> /media/pi/GSource/studio-master-dev/tools/idea/build.xml:47: The following error occurred while executing this line:
> /media/pi/GSource/studio-master-dev/tools/adt/idea/android/build.xml:33: exec returned: 1
> 
> Total time: 1 second
> ```

It's executing the x64 version of bazel. I hacky fix would be to copy an arm version to `GSource/studio-master-dev/prebuilts/tools/linux-x86_64/bazel/` named `bazel-real`

**Comment by ryanfortner** [comment]
> in traditional google fashion... it takes up a lot of space to build currently at 10GB during the sync of the repos
> 
> if someone has more space, it should be pretty simple to follow the instructions at that link

I’ll try to build on my Equinix Metal machine later today

**Comment by Crilum** [comment]
I'm getting this now:
```
$ ./build_studio.sh 
## Building android-studio ##
## Dist dir : /media/pi/GSource/studio-master-dev/tools/idea/out/studio/dist
## Qualifier: 
## Build Num: SNAPSHOT
## Out dir  : /media/pi/GSource/studio-master-dev/tools/idea/out/studio
## Prog dir : .
## ASWB?    : 
## UITESTS? : false

## JAVA_HOME: /usr/bin/
## BAZEL: /media/pi/GSource/studio-master-dev/prebuilts/tools/linux-armv7l/bazel/bazel-4.2.2
WARNING: Ignoring JAVA_HOME, because it must point to a JDK, not a JRE.
WARNING: Ignoring JAVA_HOME, because it must point to a JDK, not a JRE.
WARNING: Running Bazel server needs to be killed, because the startup options are different.
Starting local Bazel server and connecting to it...
ERROR: Error fetching repository: java.io.IOException: The repository's path is "tools/vendor/google3/blaze" (absolute: "/media/pi/GSource/studio-master-dev/tools/vendor/google3/blaze") but this directory does not exist.
ERROR: no such package '@blaze//': The repository's path is "tools/vendor/google3/blaze" (absolute: "/media/pi/GSource/studio-master-dev/tools/vendor/google3/blaze") but this directory does not exist.
## BAZEL_BIN: 
Buildfile: /media/pi/GSource/studio-master-dev/tools/idea/build.xml

init:

bazel-dependencies:
     [exec] WARNING: Running Bazel server needs to be killed, because the startup options are different.
     [exec] Starting local Bazel server and connecting to it...
     [exec] Loading: 
     [exec] Loading: 0 packages loaded
     [exec] ERROR: Error fetching repository: java.io.IOException: The repository's path is "tools/vendor/google3/blaze" (absolute: "/media/pi/GSource/studio-master-dev/tools/vendor/google3/blaze") but this directory does not exist.
     [exec] ERROR: no such package '@blaze//': The repository's path is "tools/vendor/google3/blaze" (absolute: "/media/pi/GSource/studio-master-dev/tools/vendor/google3/blaze") but this directory does not exist.
     [exec] INFO: Elapsed time: 8.798s
     [exec] Loading: 0 packages loaded
     [exec] INFO: 0 processes.
     [exec] FAILED: Build did NOT complete successfully (0 packages loaded)
     [exec] FAILED: Build did NOT complete successfully (0 packages loaded)

BUILD FAILED
/media/pi/GSource/studio-master-dev/tools/idea/build.xml:47: The following error occurred while executing this line:
/media/pi/GSource/studio-master-dev/tools/adt/idea/android/build.xml:33: exec returned: 1

Total time: 11 seconds
```

**Comment by virat2010** [comment]
Thank you for all the support and hardwork guys, @Crilum and @ryanfortner and @theofficialgman and @Itai-Nelken I don't really need it anyways, it's better I use a dedicated system or phone. see ya later
