### ISSUE TITLE
Auto start

### ISSUE THREAD

**Issue by virat2010** [Botspot/pi-apps#1755]
### Cool ideas?

add option to auto start pi apps on login

**Comment by Botspot** [comment]
I'm not sure how many people would find this useful. Could you explain how this feature would help you?

**Comment by theofficialgman** [comment]
@virat2010  you can always do this manually by adding pi-apps as an autostart program either manually or with software like autostar

**Comment by virat2010** [comment]
ok, thanks!

**Comment by virat2010** [comment]
also @Botspot it could help since I use it so much as a curios rpi4 dev
