### ISSUE TITLE
Another App

### ISSUE THREAD

**Issue by virat2010** [Botspot/pi-apps#1756]
### Cool ideas?

An app that is simple and straight forward to use that automatically isntalls apps from tar files?
I kinda spammed some issues, srry for that

**Comment by Botspot** [comment]
This would require human-level intelligence. It would be very difficult to do with conventional programming, and would require extensive training with AI.

For now, it's probably better to ask a human how to install something rather than to ask your computer to figure it out. :)

**Comment by virat2010** [comment]
It techinally doesn't. All it needs is to extract it and create a shortcut of it on desktop and finally run it's executable. That would be hard though considering the structure is different for every linux application.
