### ISSUE TITLE
pi apps

### ISSUE THREAD

**Issue by gronenbest** [Botspot/pi-apps#1759]
### What is the name of the app?

Minecarft java MultiMc 5

### (Optional) Where is the app hosted?

https://github.com/Botspot/pi-apps/issues/new/choose

### About the app

https://github.com/Botspot/pi-apps/issues/new/choose

### Upload file or Add PR Link

https://github.com/Botspot/pi-apps/issues/new/choose

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by gronenbest** [comment]
u

**Comment by gronenbest** [comment]
u

**Comment by ryanfortner** [comment]
This looks like a spam issue to me. MultiMC is already in pi-apps.

**Comment by Cigarglue5777** [comment]
Need help sign in to my Microsoft account

**Comment by Botspot** [comment]
> Need help sign in to my Microsoft account

@Cigarglue5777, please open a new issue so we can help you sign into your Microsoft account.
