### ISSUE TITLE
Folding@Home (64 bit)

### ISSUE THREAD

**Issue by moocow1452** [Botspot/pi-apps#176]
Folding@Home has a client for Raspberry Pi but it's a 64bit client and I'm not sure that Pi Apps will work in 64bit Raspbian.

https://foldingathome.org/start-folding/

**Comment by Botspot** [comment]
Each app in Pi-Apps can have separate install scripts for CPU architecture.  
Apps with only an `install-32` script will only appear in the list if your OS is 32bit. Apps with only an `install-64` script will only appear in the list if your OS is 64bit.

Folding@Home is an interesting app request. I'll have to decide if it's a good fit for Pi-Apps.

**Comment by Botspot** [comment]
Meh. I don't think enough Pi-Apps users would appreciate this.

For those who do, it's already super simple to install, has many forum threads about it, and a large user-base already.
