### ISSUE TITLE
Split Sublime Text into Sublime Text 2 & Sublime Text 4

### ISSUE THREAD

**Issue by touhidurrr** [Botspot/pi-apps#1768]
### Cool ideas?

Sublime Text advertises it major version it releases like a separate product.
For Pi-Apps, the installation scripts for Sublime Text installs Sublime Text 2 on armhf and Sublime Text 4 on arm64 based Operating Systems. This is because there is no arm package provided by it's developers for Sublime Text 4.
So, should we split into two Sublime Text for clarity?

**Comment by virat2010** [comment]
seems like a great idea, hmm I can't do anything about it, I am very novice :(, then again great idea!

**Comment by theofficialgman** [comment]
@Botspot this isn't directly related, but if I might ask, is there a reason you didn't use sublime text 3 for the armhf install? does it not work?
there are x86 32bit linux builds of it https://download.sublimetext.com/sublime_text_3_build_3211_x32.tar.bz2
https://www.sublimetext.com/3

**Comment by theofficialgman** [comment]
oh my bad @Itai-Nelken you are credited for this app. can you answer the above?

**Comment by Itai-Nelken** [comment]
> @Botspot this isn't directly related, but if I might ask, is there a reason you didn't use sublime text 3 for the armhf install? does it not work?
> there are x86 32bit linux builds of it https://download.sublimetext.com/sublime_text_3_build_3211_x32.tar.bz2
> https://www.sublimetext.com/3

It didn't work with box86. I haven't tested it since though, it might work now.

**Comment by Botspot** [comment]
Closing, as the description of Sublime Text now clears any confusion up, thanks to @touhidurrr's PR #1767
