### ISSUE TITLE
well mine in mostly a non app but it count as one right?

### ISSUE THREAD

**Issue by srini-pro** [Botspot/pi-apps#177]
git clone https://github.com/srini-pro/ensripy.git

**Comment by ilobilo** [comment]
It's a password encryptor, right?

**Comment by srini-pro** [comment]
yup
not only password encryptor also like note encrypter a yup

**Comment by ilobilo** [comment]
It would be cool if you make GUI with yad like pi-apps.

**Comment by Itai-Nelken** [comment]
> You should make GUI with yad like pi-apps, Because they don't add apps that are CLI only. (I think)

its preferred to have a gui, but I don't think its required.
for example box86, raspi2png, and wine (coming soon) don't have a gui (but box86 is used to run gui apps like sublime text and steam, same for wine).
I'm not sure, best to wait for Botspot.

**Comment by ilobilo** [comment]
Ok

**Comment by Botspot** [comment]
This seems more like a utility than an app. Even if a GUI was made for it, I don't think it would be a good fit for Pi-Apps.

**Comment by srini-pro** [comment]
OK
