### ISSUE TITLE
E: Unable to locate package yad

### ISSUE THREAD

**Issue by Pap76** [Botspot/pi-apps#178]
the installation finished with this error; E: Unable to locate package yad

anyone can help me?
thanks

**Comment by ilobilo** [comment]
Try "apt update"

**Comment by Itai-Nelken** [comment]
run `sudo apt update` and `sudo apt install yad` as @ilobilo said

**Comment by Botspot** [comment]
Did that work? The install script should have already done a `sudo apt update`. Look at commit 813d687cb8c86ddb18d7b65547c170c0ed20bb1e.

@Pap76: You ran the Pi-Apps install script, right?
