### ISSUE TITLE
Google Earth (Pro)

### ISSUE THREAD

**Issue by Crilum** [Botspot/pi-apps#1789]
### What is the name of the app?

Google Earth Pro

### (Optional) Where is the app hosted?

https://www.google.com/earth/about/versions/
https://dl.google.com/dl/earth/client/GE7/release_7_3_0/google-earth-pro-stable_7.3.0.3832-r0_i386.deb

### About the app

You know.. Google Earth. It has a 32-bit deb, so in theory it should be able to be installed with box86.

It also works with wine, but only the first use, then it has problems...

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.
^ I haven't tested the deb (though I've tried), but box86 should be able to run it.

**Comment by theofficialgman** [comment]
looks like its written in QT5, which is nice. I'm sure you know, but thats an older version and they are not making 32bit releases anymore
https://support.google.com/earth/answer/168344#zippy=%2Cdownload-a-google-earth-pro-direct-installer

**Comment by Crilum** [comment]
>I'm sure you know, but thats an older version and they are not making 32bit releases anymore

Yeah, I do know. :+1:

**Comment by ryanfortner** [comment]
There is an open issue on the box86 repo for google earth: https://github.com/ptitSeb/box86/issues/332

**Comment by Crilum** [comment]
Oh, ok. I didn't realize @Botspot had already tried with box86. I guess we're waiting on @ptitSeb then? Could `libIGUtils` be added as a dependency and not use the wrapped version (I'm assuming it's using a wrapped version)?

**Comment by Itai-Nelken** [comment]
I doubt it will run well especially with emulation as it stutters on a much more powerful computer than the rpi.

**Comment by Crilum** [comment]
> I doubt it will run well especially with emulation as it stutters on a much more powerful computer than the rpi.

I used it with wine, and it worked pretty well, a little stutter, but not much considering it's running through both box86 and wine. I expect with box86 alone, it would be pretty usable.

**Comment by ryanfortner** [comment]
just curious, is the web-based version of Google Earth, earth.google.com, usable on your pi?

**Comment by Crilum** [comment]
Well, it never loads... I haven't left the tab open for more than ten minutes, but it load faster than that...

**Comment by theofficialgman** [comment]
> Well, it never loads... I haven't left the tab open for more than ten minutes, but it load faster than that...

loaded in about 30 seconds on nintendo switch with it stuck at 100% cpu usage for an additional 30 seconds... gpu usage is very high as well.
its probably just too much for the pi cpu and gpu to handle in a timely manner.

**Comment by Crilum** [comment]
>its very useable here, but the web version doesn't nearly have the features of the pro desktop app if I remember correctly.

The web version looks better, but the desktop app does have some unique features.

**Comment by theofficialgman** [comment]
Deprecated by upstream for years and no guarantee it does not stop working (ie: required google backends get removed) if it hasn't already.
