### ISSUE TITLE
octoprint

### ISSUE THREAD

**Issue by Grisu1970** [Botspot/pi-apps#1795]
### Confirmations

- [] I have confirmed that this app is legal and not piracy.
- [] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [] I have confirmed that this app can run on Raspberry Pi.

**Comment by theofficialgman** [comment]
@Grisu1970 please use the issues format for app suggestions. I have edited your post and will require you to fill it out before receiving further responses

**Comment by theofficialgman** [comment]
stale issue, closing due to lack of necessary response
