### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by ilobilo** [Botspot/pi-apps#180]
I tried running Pi-Apps on Ubuntu with IceWM, but when I clicked Minecraft BE install button it didn't do anything.

**Comment by Itai-Nelken** [comment]
run `~/pi-apps/gui`, that will run pi-apps regularly but you will be able to see any errors.

**Comment by Botspot** [comment]
> I tried running Pi-Apps on Ubuntu with IceWM, but when I clicked Minecraft BE install button it didn't do anything.

Yes, do what @Itai-Nelken recommended, but also please tell me which terminals you have installed.

**Comment by ilobilo** [comment]
I was using Xterm, running on:
Redmi Note 9s >> Termux >> Ubuntu 20.04 arm64 >> TightVNC >> IceWM

![Screenshot_2020-12-29-21-56-02-453_com.realvnc.viewer.android.jpg](https://user-images.githubusercontent.com/68286835/103303930-ab671300-4a20-11eb-8f4f-c5a750c39352.jpg)

**Comment by Botspot** [comment]
Now try installing something and see if any more output shows up in your first terminal.

**Comment by ilobilo** [comment]
This is when installing browsh:
![Screenshot_2020-12-29-22-01-21-007_com.realvnc.viewer.android.jpg](https://user-images.githubusercontent.com/68286835/103304195-6becf680-4a21-11eb-8d53-2a81968c17b8.jpg)
Nothing is happening when clicking install button, errors are appearing when entering details page.

**Comment by Botspot** [comment]
Why aren't you using Raspberry Pi OS?

**Comment by ilobilo** [comment]
I don't have rpi, I just like it and your project so wanted to test if it would work on Ubuntu.
I thought it supposed to.

**Comment by ilobilo** [comment]
Sorry for bad English.

**Comment by Botspot** [comment]
> I don't have rpi, I just like it and your project so wanted to test if it would work on Ubuntu,

99% of the apps will only run on RPi anyway. In theory, the Pi-Apps GUI should work on any Linux PC, but as none of the apps work, there really isn't any point.
