### ISSUE TITLE
Pi-Apps update.sh file

### ISSUE THREAD

**Issue by Sussy-OS** [Botspot/pi-apps#1808]
### Cool ideas?

Every time I update an app that, when uninstalled, deletes data for space (Eg. Minecraft Java Server) I have to go through the whole process, adding a new world, setting up the .jar config or preferences. My suggestion is to add an update.sh so that apps that uninstall everything can update the correct way.

**Comment by Itai-Nelken** [comment]
Apps shouldn't remove user data at all.

**Comment by theofficialgman** [comment]
minecraft java server does not uninstall anything on update. the uninstall process is skipped. even on uninstall, worlds, mods, and versions folders are skipped.

we also do not intend to update the install file for it either as it does not need updates to work on later versions. even if the install file was to be updated, you would only go through the prompts to re-download (or chose a new) version of the server jar
