### ISSUE TITLE
WhatsApp

### ISSUE THREAD

**Issue by ghost** [Botspot/pi-apps#181]
Hey, there. This is an app request.
So I started getting WhatsApp Web on the Pi but never got it to work. @Botspot could you maybe look at the folder that I uploaded to this issue?

[WhatsApp.zip](https://github.com/Botspot/pi-apps/files/5752049/WhatsApp.zip)

**Comment by Botspot** [comment]
There isn't much to see in the folder. :(

Your install script and uninstall scripts are completely stock! (they don't do anything at all)

**Comment by Itai-Nelken** [comment]
I compiled a nativefier web app of WhatsApp web, we could use it.

**Comment by zachdwilliams** [comment]
> There isn't much to see in the folder. :(
> 
> Your install script and uninstall scripts are completely stock! (they don't do anything at all)

Oh. So there isn’t any way to fix it?

**Comment by zachdwilliams** [comment]
> I compiled a nativefier web app of WhatsApp web, we could use it.

Cool. Can you send screenshots/a video to me on Discord?

**Comment by Botspot** [comment]
> > There isn't much to see in the folder. :(
> > Your install script and uninstall scripts are completely stock! (they don't do anything at all)
> 
> Oh. So there isn’t any way to fix it?

No, they are a clean slate. Like a blank piece of paper. They don't do anything yet.

**Comment by Itai-Nelken** [comment]
@zachdwilliams 
## Downloads to the WhatsApp web nativefier web apps I compiled:

* **no** tray nativefier webapp: https://app.box.com/s/pnoozkvf393cvojv2hbiq1j9efogpmil

* tray nativefier webapp: https://app.box.com/s/eqm597lbcgvzlrgmtukt8uekt6ctuab1

**Comment by Itai-Nelken** [comment]
@zachdwilliams 
## Downloads to the WhatsApp web nativefier web apps I compiled:

* **no** tray icon (armv7l):<br> https://app.box.com/s/35q4lybmqzyzhcsbzx80e9h7ppm9nc8o
* **with** tray icon (armv7l):<br>https://app.box.com/s/eqm597lbcgvzlrgmtukt8uekt6ctuab1
### to run

1) download and extract the archive
2) enter the extracted folder and open terminal in it
3) run `./WhatsAppWeb`

**Comment by Itai-Nelken** [comment]
@Botspot are those apps ok with you?
@zachdwilliams and Botspot decide if you prefer the tray version or the regular version and thans I'll write the scripts.

**Comment by Botspot** [comment]
@Itai-Nelken Yes it's working okay for me. But, how is it better than simply going to the Whatsapp website in Chromium?

**Comment by Itai-Nelken** [comment]
@Botspot It is the same as using the discord webapp. Its separated from chromium data.

I don't really know.

**Comment by zachdwilliams** [comment]
> @Itai-Nelken Yes it's working okay for me. But, how is it better than simply going to the Whatsapp website in Chromium?

Well there’s an app version of the Discord website on pi apps...

**Comment by zachdwilliams** [comment]
> @Botspot are those apps ok with you?
> @zachdwilliams and Botspot decide if you prefer the tray version or the regular version and thans I'll write the scripts.

I like it! Tell me, what is a tray icon?

**Comment by Itai-Nelken** [comment]
@zachdwilliams a icon in the top bar
![2020-12-30_11-04](https://user-images.githubusercontent.com/70802936/103341178-db4cff80-4a8e-11eb-8ba8-cf68acdd50db.png)
it stays there even if you close the main window, so you can keep the app without taking space on the taskbar.

**Comment by zachdwilliams** [comment]
> @zachdwilliams a icon in the top bar

Ok in that case let’s do it without the tray icon. I tried downloading the 32 ARM install without tray but I have no idea how to run it...

**Comment by zachdwilliams** [comment]
Never mind, I got it.

**Comment by Itai-Nelken** [comment]
@Botspot do you agree to add this app to pi-apps?
if yes @zachdwilliams what version do you prefer?

**Comment by Botspot** [comment]
> @Botspot do you agree to add this app to pi-apps?

Yeah I guess.

> if yes @zachdwilliams what version do you prefer?

I think we'll go with the tray version. @zachdwilliams please upload your files to Github to simplify the app creation process.

**Comment by Itai-Nelken** [comment]
> > @Botspot do you agree to add this app to pi-apps?
> 
> Yeah I guess.
> 
> > if yes @zachdwilliams what version do you prefer?
> 
> I think we'll go with the tray version. @zachdwilliams please upload your files to Github to simplify the app creation process.

@Botspot (they are my files). I'll create the scripts.

**Comment by Botspot** [comment]
> @Botspot (they are my files).

Oh yeah whoops.

**Comment by Itai-Nelken** [comment]
here is the repo: https://github.com/Itai-Nelken/Nativefier-Whatsapp-Web

**Comment by Itai-Nelken** [comment]
[Whatsapp Web.zip](https://github.com/Botspot/pi-apps/files/5755132/Whatsapp.Web.zip)
here, I tested it on 32bit and it works. 64bit should work as it is the same script with a different download link.
just need someone to test in case there are any dependencies.

**Comment by Itai-Nelken** [comment]
@Botspot can you add the `Testers needed` label please?

**Comment by Itai-Nelken** [comment]
@Botspot do you know how to fix this? when installing in TwisterOS the script works perfectly, but when testing on a new rpiOS 32bit image (with vdesktop) I get this error:
![menu-shortcut-error](https://user-images.githubusercontent.com/70802936/103400071-70fa9480-4b4c-11eb-8a25-6b8b6d56b20a.png)
any idea why that happens? I tried lauching it straight from `~/.local/share/applications` and I still get the same error.

**Comment by Itai-Nelken** [comment]
I tried renaming the .desktop file to use only lower case letters, but it still didn't work.
so I searched a bit and found this command, so I ran it: `desktop-file-validate ~/.local/share/applications/whatsappweb.desktop` and it told me that the categories weren't correct, so I let `Network` only and it still doesn't work.

**Comment by Itai-Nelken** [comment]
[Whatsapp Web.zip](https://github.com/Botspot/pi-apps/files/5757169/Whatsapp.Web.zip)
works great on TwisterOS, menu shortcut is broken on RPiOS for some reason.

**Comment by Botspot** [comment]
> so I ran it: `desktop-file-validate ~/.local/share/applications/whatsappweb.desktop` and it told me that the categories weren't correct

Whoa what?! Thanks for the tip. That will save me a lot of time.

**Comment by Botspot** [comment]
Okay I found it. The `Exec=` patch has to be a full path.  
Like this:
```
[Desktop Entry]
Name=Whatsapp Web
Comment=Nativefier Whatsapp Web webapp.
Exec=/home/pi/WhatsAppWeb/WhatsAppWeb
Path=/home/pi/WhatsAppWeb
Icon=/home/pi/pi-apps/apps/Whatsapp Web/icon-64.png
Terminal=false
StartupNotify=true
Type=Application
Categories=Network;
```
I've made a few changes to the `install-32` script. [Whatsapp Web.zip](https://github.com/Botspot/pi-apps/files/5757545/Whatsapp.Web.zip)

**Comment by Itai-Nelken** [comment]
should I do the same changes to the install-64 script?

**Comment by Itai-Nelken** [comment]
[Whatsapp Web.zip](https://github.com/Botspot/pi-apps/files/5757593/Whatsapp.Web.zip)
install-64 is now the same as install-32 (other than the download links.
Thanks for finding out how to fix the menu shortcut!

**Comment by Botspot** [comment]
Added to Pi-Apps with commit 69150fbfa75fa73f7671b0d432291b442212d356.
