### ISSUE TITLE
Brackets

### ISSUE THREAD

**Issue by Botspot** [Botspot/pi-apps#182]
Robloxboy on Discord is working on this.

https://brackets.io/

**Comment by robloxboy24** [comment]
Yep! And its _SO_ close to being done! :D

**Comment by mobilegmYT** [comment]
Nice!

**Comment by Botspot** [comment]
> Yep! And its _SO_ close to being done! :D

...As of 24 days ago. :(

I'm closing this issue for now. It's been "so close!" for too long. I will re-open it when/if robloxboy24 (or anyone else) makes this app and replies to this issue with a zip file.
