### ISSUE TITLE
Python Icon Installer

### ISSUE THREAD

**Issue by Red-exe-Engineer** [Botspot/pi-apps#1830]
Hey Botspot! (Or whoever is reading this)

Here is that icon installer I made for Python files :p

BTW the app maker is **SUPAH** easy to use/understand so thanks

[Python Icon Installer.zip](https://github.com/Botspot/pi-apps/files/8704539/Python.Icon.Installer.zip)

**Comment by theofficialgman** [comment]
Please use appropriate issues template next time. https://github.com/Botspot/pi-apps/issues/new/choose
(this would be an App Submission)

**Comment by theofficialgman** [comment]
```
#!/bin/bash

# Print some info
echo 'Created by Wallee#8314/Red-exe-Engineer' || error ''
echo || error ''

# Download the icon
wget https://upload.wikimedia.org/wikipedia/commons/c/c3/Python-logo-notext.svg || error 'Failed to download the icon'

# Move the icon to /usr/share/icons/gnome/scalable/mimetypes
sudo mv Python-logo-notext.svg /usr/share/icons/gnome/scalable/mimetypes/text-x-python.svg || error 'Could not move the icon to /usr/share/icons/gnome/scalable/mimetypes'

# Update Mimetypes or something
sudo gtk-update-icon-cache /usr/share/icons/gnome/ -f || error 'Failed to update Mimetypes icon cashe (try a reboot?)'
```

is this really necessary to have as an app? you are just adding one icon to the list of icons that many themes and DEs already include

**Comment by Red-exe-Engineer** [comment]
> ```
> #!/bin/bash
> 
> # Print some info
> echo 'Created by Wallee#8314/Red-exe-Engineer' || error ''
> echo || error ''
> 
> # Download the icon
> wget https://upload.wikimedia.org/wikipedia/commons/c/c3/Python-logo-notext.svg || error 'Failed to download the icon'
> 
> # Move the icon to /usr/share/icons/gnome/scalable/mimetypes
> sudo mv Python-logo-notext.svg /usr/share/icons/gnome/scalable/mimetypes/text-x-python.svg || error 'Could not move the icon to /usr/share/icons/gnome/scalable/mimetypes'
> 
> # Update Mimetypes or something
> sudo gtk-update-icon-cache /usr/share/icons/gnome/ -f || error 'Failed to update Mimetypes icon cashe (try a reboot?)'
> ```
> 
> is this really necessary to have as an app (also there are a lot of typos and bugs in this)? you are just adding one icon to the list of icons that many themes and DEs already include

Eh, every system I have used didn't come with a Python icon and it gets annoying trying to find them.

Though it is simple I feel as though a lot of people do not know how to do it (I didn't until today)

 It is less an app and more an updater to what *should* be included.

BTW sorry I didn't use pins or whatever, new to this 👀

**Comment by theofficialgman** [comment]
> Eh, every system I have used didn't come with a Python icon and it gets annoying trying to find them.

strange, literally every theme I have installed has python as an icon. I think this is more of an issue for PiOS (assuming you are using that) and there default theme, you should open an issue there to get them to add one if there isn't one

**Comment by theofficialgman** [comment]
going to close this, I suggest you create an issue here: https://github.com/raspberrypi/Raspberry-Pi-OS-64bit/issues
or at the pi forum, or with whatever theme you are using. your app wil only add it to the gnome theme and overwriting users themes is not a good idea
