### ISSUE TITLE
Installing Conky spams the terminal (the daemon mode)

### ISSUE THREAD

**Issue by theofficialgman** [Botspot/pi-apps#1832]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)

### What happened?

conky installs, builds and compiles, then launches something the background and kills the terminal running all installs/uninstalls

### Description

https://github.com/Botspot/pi-apps/blob/0b452db2ce1003af8dbd5265d7d825c3ec87d420/apps/Conky/install#L17

starting conkey as part of the script is bad since it continues to run and spam the terminal as long as its running. conkey finishes installing, but the spam stating that the vcgencmd (only found on pis) continues to spam the terminal for other programs. this is not captured in saved logs, only in the running terminal.

conky does otherwise work fine besides this spam

### What is your operating system?

L4T Ubuntu Bionic

### (Optional) Error log? Terminal output? Debug messages?

```bash
s can be upgraded. Run 'apt list --upgradable' to see them.
apt update complete.
Some packages can be upgraded. Please consider running sudo apt full-upgrade.
Creating an empty apt-package to install the necessary apt packages...
It will be named: pi-apps-81d52d4a
Depends: conky
Installing the pi-apps-81d52d4a package...
The following additional packages will be installed:
  conky conky-std liblua5.1-0
Suggested packages:
  apcupsd audacious moc mpd xmms2
The following NEW packages will be installed:
  conky conky-std liblua5.1-0 pi-apps-81d52d4a
0 upgraded, 4 newly installed, 0 to remove and 17 not upgraded.
Get:1 /home/garrett/pi-apps-81d52d4a.deb pi-apps-81d52d4a all 1.0 [740 B]
Get:2 http://ports.ubuntu.com bionic/universe arm64 liblua5.1-0 arm64 5.1.5-8.1build2 [90.8 kB]
Get:3 http://ports.ubuntu.com bionic/universe arm64 conky-std arm64 1.10.8-1 [301 kB]
Get:4 http://ports.ubuntu.com bionic/universe arm64 conky all 1.10.8-1 [3,396 B]
Fetched 395 kB in 1s (420 kB/s)
(Reading database ... 434676 files and directories currently installed.)
Unpacking liblua5.1-0:arm64 (5.1.5-8.1build2) ...
Unpacking conky-std (1.10.8-1) ...
Unpacking conky (1.10.8-1) ...
Unpacking pi-apps-81d52d4a (1.0) ...
environment: line 1:  8798 Terminated              ( sleep 3; echo -n "Waiting until APT locks are released... " )
Apt finished.
Package installation complete.
conky: desktop window (1a0002f) is subwindow of root window (1a6)

Installed Conky successfully.
conky: window type - normal
conky: drawing to created window (0x3e00001)
conky: drawing to double buffer
conky: forked to background, pid is 9893

sh: 1: /usr/bin/vcgencmd: not found
queue is 'install;Conky;0
install;Cool Retro Term'
Received 'install;Cool Retro Term'
Action is install, app is Cool Retro Term
sh: 1: /usr/bin/vcgencmd: not found
Installing Cool Retro Term...

Will install these packages: build-essential qmlscene qt5-qmake qtbase5-dev qtchooser qtdeclarative5-dev qtquickcontrols2-5-dev qml-module-qtquick-controls qml-module-qtgraphicaleffects qml-module-qtquick-dialogs qml-module-qtquick-localstorage qml-module-qtquick-window2 qml-module-qt-labs-settings qml-module-qt-labs-folderlistmodel 
sh: 1: /usr/bin/vcgencmd: not found
sh: 1: /usr/bin/vcgencmd: not found
sh: 1: /usr/bin/vcgencmd: not found
sh: 1: /usr/bin/vcgencmd: not found
environment: line 1: 10096 Terminated              ( sleep 3; echo -n "Waiting until APT locks are released... " )
sh: 1: /usr/bin/vcgencmd: not found
sh: 1: /usr/bin/vcgencmd: not found
sh: 1: /usr/bin/vcgencmd: not found
Running sudo apt update...
environment: line 3: 10157 Terminated              ( sleep 3; echo -n "Waiting until APT locks are released... " )
sh: 1: /usr/bin/vcgencmd: not found
sh: 1: /usr/bin/vcgencmd: not found
Hit:3 https://download.mono-project.com/repo/ubuntu stable-bionic InRelease
Hit:4 http://packages.microsoft.com/repos/code stable InRelease
Hit:5 http://ports.ubuntu.com bionic InRelease
Get:6 https://repo.download.nvidia.com/jetson/common r32 InRelease [2,541 B]
Get:7 http://download.tuxfamily.org/webcordapt/debian buster InRelease [4,005 B]
Get:8 https://repo.download.nvidia.com/jetson/t210 r32 InRelease [2,555 B]
Hit:9 https://deb.nodesource.com/node_17.x bionic InRelease
Hit:10 http://ports.ubuntu.com bionic-updates InRelease
Hit:11 https://adoptopenjdk.jfrog.io/adoptopenjdk/deb bionic InRelease
sh: 1: /usr/bin/vcgencmd: not found
Hit:12 https://newrepo.switchroot.org switchroot InRelease
Hit:13 http://ppa.launchpad.net/alexlarsson/flatpak/ubuntu bionic InRelease
Hit:15 https://mcpiscript.github.io/PPA ./ InRelease
Hit:16 http://ports.ubuntu.com bionic-backports InRelease
Get:17 https://dl.cloudsmith.io/public/moonlight-game-streaming/moonlight-l4t/deb/ubuntu bionic InRelease [5,073 B]
Hit:18 https://apt.syncthing.net syncthing InRelease
Hit:19 http://ports.ubuntu.com bionic-security InRelease
Hit:20 http://ppa.launchpad.net/camel-neeraj/sysmontask/ubuntu bionic InRelease
Hit:21 https://adoptium.jfrog.io/artifactory/deb bionic InRelease
Hit:22 https://dl.yarnpkg.com/debian stable InRelease
Ign:23 https://repo.azka.li/ubuntu bionic InRelease
Hit:24 http://ppa.launchpad.net/cartes/drawing/ubuntu bionic InRelease
sh: 1: /usr/bin/vcgencmd: not found
Hit:25 https://repo.azka.li/ubuntu bionic Release
Hit:26 http://ppa.launchpad.net/cwchien/gradle/ubuntu bionic InRelease
Ign:27 https://repo.azka.li/ubuntu bionic Release.gpg
Hit:1 https://repo.switchroot.org unstable/ InRelease
Hit:2 https://apt.llvm.org/bionic llvm-toolchain-bionic-14 InRelease
Hit:28 http://ppa.launchpad.net/jonmagon/kdiskmark/ubuntu bionic InRelease
sh: 1: /usr/bin/vcgencmd: not found
Hit:29 http://ppa.launchpad.net/libretro/stable/ubuntu bionic InRelease
Hit:30 http://ppa.launchpad.net/openjdk-r/ppa/ubuntu bionic InRelease
sh: 1: /usr/bin/vcgencmd: not found
Hit:14 https://packagecloud.io/ookla/speedtest-cli/ubuntu bionic InRelease
Hit:31 http://ppa.launchpad.net/ricotz/docky/ubuntu bionic InRelease
Hit:32 http://ppa.launchpad.net/theofficialgman/boost1.67-bionic/ubuntu bionic InRelease
sh: 1: /usr/bin/vcgencmd: not found
Hit:33 http://ppa.launchpad.net/theofficialgman/cmake-bionic/ubuntu bionic InRelease
Hit:34 http://ppa.launchpad.net/theofficialgman/git-backport-bionic/ubuntu bionic InRelease
sh: 1: /usr/bin/vcgencmd: not found
Hit:35 http://ppa.launchpad.net/theofficialgman/melonds-depends/ubuntu bionic InRelease
Hit:36 http://ppa.launchpad.net/theofficialgman/opt-qt-5.12.0-bionic-arm/ubuntu bionic InRelease
sh: 1: /usr/bin/vcgencmd: not found
Hit:37 http://ppa.launchpad.net/theofficialgman/opt-qt-5.15.2-bionic-arm/ubuntu bionic InRelease
Hit:38 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu bionic InRelease
sh: 1: /usr/bin/vcgencmd: not found
Hit:39 http://ppa.launchpad.net/ubuntubudgie/backports/ubuntu bionic InRelease
sh: 1: /usr/bin/vcgencmd: not found
sh: 1: /usr/bin/vcgencmd: not found
sh: 1: /usr/bin/vcgencmd: not found
sh: 1: /usr/bin/vcgencmd: not found
sh: 1: /usr/bin/vcgencmd: not found
sh: 1: /usr/bin/vcgencmd: not found
sh: 1: /usr/bin/vcgencmd: not found
sh: 1: /usr/bin/vcgencmd: not found
sh: 1: /usr/bin/vcgencmd: not found
sh: 1: /usr/bin/vcgencmd: not found
sh: 1: /usr/bin/vcgencmd: not found
sh: 1: /usr/bin/vcgencmd: not found
sh: 1: /usr/bin/vcgencmd: not found
sh: 1: /usr/bin/vcgencmd: not found
sh: 1: /usr/bin/vcgencmd: not found

```
```

**Comment by Botspot** [comment]
The default conkyrc uses `vcgencmd` to obtain CPU temperature information.

https://github.com/Botspot/rpi_conky/blob/3eeb8ebc62170bd379d9993c1b1205fc4b54f9bd/conkyrc#L50

Is there a more cross-platform way of detecting this? Also it's possible to include an `if` statement, or to hide errors.
Running Conky from the script seems to be necessary - it's best to avoid making the user reboot unnecessarily.

**Comment by theofficialgman** [comment]
the problem is you don't detach conky. the spam would be fine if it didn't happen in the terminal
something like 
```
disown $!
```
on the next line after & should work

or maybe launch with nohup
```
nohup conky &
```

**Comment by Botspot** [comment]
Conky forks itself to another process anyway, so closing the terminal should not close conky.

**Comment by Botspot** [comment]
The simplest solution would be to change the script to run conky with &>/dev/null.
But I'd prefer to use a universal temperature-checking utility, if such a thing exists.

@theofficialgman, do you know of a way to check temperature on your switch?

**Comment by theofficialgman** [comment]
thats not the problem. the problem is you send conky to the background but don't detach it

**Comment by theofficialgman** [comment]
> @theofficialgman, do you know of a way to check temperature on your switch?

there are multiple thermal zones
`/sys/devices/virtual/thermal/thermal_zone*/`
0,1,2,etc

each of those folders has a `type` file in it. one of them is CPU-therm, which is the cpu folder. in that thermal zone folder you read the `temp` file and its its in millicelcius

**Comment by theofficialgman** [comment]
oh, and lol, conky closed after pi-apps finished installing it btw

**Comment by theofficialgman** [comment]
also, are you writing directly to the framebuffer here? or is this nvjank. because thats my framebuffer image in the background before the nvgpu driver starts.

![Screenshot from 2022-05-17 19-02-05](https://user-images.githubusercontent.com/28281419/168926141-00ebaf1e-26fc-4af8-96ad-a3bac01bbff0.png)

**Comment by Botspot** [comment]
> oh, and lol, conky closed after pi-apps finished installing it and the daemon disappeared btw

That is unexpected. Could you kill conky and then run it manually?
On my system it specifically mentions the process is being forked to the background.
```
pi@raspberrypi:~ $ conky
conky: desktop window (1000010) is subwindow of root window (3b9)
conky: window type - normal
conky: drawing to created window (0x3600001)
conky: drawing to double buffer
conky: forked to background, pid is 12149
```

> > @theofficialgman, do you know of a way to check temperature on your switch?
> 
> there are multiple thermal zones `/sys/devices/virtual/thermal/thermal_zone*/` 0,1,2,etc
> 
> each of those folders has a `type` file in it. one of them is `CPU-therm`, which is the cpu folder. in that thermal zone folder you read the `temp` file and its its in millicelcius

Fortunately, `thermal_zone0` exists on my RPi, so I'll probably replace vcgencmd with this:
`echo $(($(< /sys/devices/virtual/thermal/thermal_zone0/temp) / 1000))`
Does that look good?

**Comment by theofficialgman** [comment]
thermal_zone0 is not CPU-therm on switch, and it is not guaranteed to be the same on any system.
you will have to search each matching folder for the correct contents containing CPU-therm

**Comment by Botspot** [comment]
Either I can use thermal_zone0 for lower overhead, no dependence on vcgencmd, and slightly better compatibility with other SBCs, or I can leave it as-is and mask errors.
I think the first option, while still flawed, is better than the second option.

**Comment by theofficialgman** [comment]
thermal_zone0 will literally almost never be cpu temp. It happens to be for you but that is just chance. In the case of the switch I think it happens to be the battery temperature (don't have it on rn so can't say).
Providing no information is better than false information. Keep it as is and hide errors

**Comment by Botspot** [comment]
[Done.](https://github.com/Botspot/rpi_conky/commit/36e2b5696b4d4e7f45b629a186450af6511ec613)
I won't push a reinstall, because this problem only occurs during installation and is otherwise harmless.

**Comment by Crilum** [comment]
@Botspot If you want to use Python, you could use `psutil`.

**Comment by Botspot** [comment]
> @Botspot If you want to use Python, you could use `psutil`.

The only way to integrate that with Conky would be to open a Python shell twice every second. That may cause a performance hit. You're welcome to edit ~/.conkyrc and try it though.

**Comment by Itai-Nelken** [comment]
It might be possible to make a "server" in python - a program that is always running in the background that checks the temperature every X minutes and puts it somwhere, and then concky can get the temperature from there without having to start the python interpreter every 2 seconds.
I don't think this is a good idea and I don't know if it is even possible to do.
