### ISSUE TITLE
insufficient permissions for androidbuddy

### ISSUE THREAD

**Issue by theofficialgman** [Botspot/pi-apps#1834]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)

### What happened?

using android buddy results in no control of the android device connected

### Description

launching via terminal I can see: `error: insufficient permissions for device: user in plugdev group; are your udev rules wrong?`

I had to run
```
sudo usermod -aG plugdev $LOGNAME
apt-get install android-sdk-platform-tools-common
```
then reboot and after this it worked fine

### What is your operating system?

L4T Ubuntu Bionic

**Comment by Botspot** [comment]
Good catch - I think RPiOS automatically adds users to the plugdev group.
What is the difference between $USER and $LOGNAME?

**Comment by Botspot** [comment]
> I had to run
> ```
> apt-get install android-sdk-platform-tools-common
> ```

On my system, android-sdk-platform-tools-common was automatically installed because it's a dependency of `adb`, which is a dependency of the Pi-Apps dummy deb.

**Comment by theofficialgman** [comment]
@Botspot on buster and bionic it is only a recommends, not a depends. that has changed on bullseye and newer ubuntu.
so this needs to be added to the install_packages

**Comment by theofficialgman** [comment]
> Good catch - I think RPiOS automatically adds users to the plugdev group. What is the difference between $USER and $LOGNAME?

its the same on my system, but from google's docs on adb they recommend you use $LOGNAME

**Comment by Botspot** [comment]
I found multiple other scripting problems with Scrcpy, including unnecessary file-copying and incomplete uninstall.
I fixed it all and added a GUI error-catcher, in addition to making Scrcpy install globally and solve the problems you encountered.

Thanks for the bug report, @theofficialgman.
