### ISSUE TITLE
Lokinet crashes on launch

### ISSUE THREAD

**Issue by theofficialgman** [Botspot/pi-apps#1835]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)

### What happened?

lokinet crashes on launch

### Description

lokinet apt repo has official bionic binaries. these appear to be broken currently. need testing for other users to see if lokinet is functional on arm64 buster or bullseye or if its broken on everything

### What is your operating system?

L4T Ubuntu Bionic

### (Optional) Error log? Terminal output? Debug messages?

```bash
/usr/bin/lokinet-gui --notray
------ Lokinet Control Panel ------
Compile-time Qt Version: 5.9.5
Run-time Qt Version: 5.9.5
nohide:  T
notray:  T
Gtk-Message: 17:20:18.852: Failed to load module "canberra-gtk-module"
lokinet-gui: /drone/src/oxenmq/jobs.cpp:114: void oxenmq::OxenMQ::_queue_timer_job(int): Assertion `b->size() == std::make_pair(size_t{1}, thread > 0)' failed.
Aborted (core dumped
```

**Comment by theofficialgman** [comment]
I can't seem to find any reference to the lokinet GUI for linux in the upstream github repo, only on macos and windows.
maybe it was removed or added by the debian/ubuntu maintainer?

**Comment by Botspot** [comment]
@necro-nemesis

**Comment by theofficialgman** [comment]
@necro-nemesis I've looked at the lokinet electron repo. unfortunatly, due to electron 11.X used there, this can not be included on modern linux distros https://github.com/oxen-io/lokinet-gui/blob/569f90ad88fd820aa47825bbac4b34795425c6ce/package.json#L85 . you need to upgrade to a minimum of electron 13 https://github.com/electron/electron/pull/31091 as well as stay below electron 19, and not use electron 18.0.0-18.2.3

gmans electron blacklist:
electron 18.0.0-18.2.3
electron 19.0.0+
electron < 13.0.0

**Comment by Botspot** [comment]
@necro-nemesis, I have pinged you several times over the past few months whenever I spot a Lokinet installation failure in the Botspot Software Discord server.

Have you checked Discord recently and are you still reviewing these logs?

**Comment by theofficialgman** [comment]
currently hidden in the GUI of pi-apps since it quite literally has near 0 successful installs over the past many months

I see that the new electron GUI has just released 5 days ago... however I'm in favor of removing this from pi-apps as I have no interest in maintaining or testing it, unless another maintainer would like to do so.

**Comment by necro-nemesis** [comment]
The latest version of Lokinet including the new GUI just dropped into the repo as of Friday where Pi-Apps acquires it from. It will require some testing on various platforms including pi that are reliant on the repo hosting Lokinet to test it's installation from there. Although tagged 5 days ago it took that additional amount time for it to be added to the repo.

**Comment by theofficialgman** [comment]
I took a look at the repo yesterday and found lokinet-gui to only be available for amd64. no arm64 or armhf releases
<https://deb.oxen.io/pool/main/l/lokinet-gui/>. the releases for the GUI in the `pool/main/l/loki-network-control-panel` are only the old GUI.

in addition 18.04 support appears to not be there for all packages and all architectures

**Comment by majestrate** [comment]
the issues with the arm build is related to some idiosyncrasies in node/electron. there is/was an old abandoned npm module or two that are holding version back a bit. we are planning on addressing these in the next up coming tag.

**Comment by Botspot** [comment]
For now Lokinet is hidden in Pi-Apps. Existing users (assuming there are any) will receive no change, but new users will not be able to find it.

**Comment by necro-nemesis** [comment]
I'm waiting on the electron dev to build 64 bit ARM version of the gui for addition to the repo before reworking the installer. I see where the app is hidden and appreciate how to gain access to it within my own fresh installation of Pi-Apps when I am able to proceed with required changes.  From my testing and discussions it appears this is the last step required before Pi-Apps can be reworked to support both Lokinet ARM 32 and 64 bit.  Currently lokinet and lokinet-bin 32 and 64 bit are the latest versions (v0.9.11) in the repo but the repo currently lacks the final 64 bit electron gui build to fully support Pi-Apps as a desktop application.

**Comment by Botspot** [comment]
Was there ever any outcome on this? If not, I want to remove this app completely from Pi-Apps, as it has been hidden for two years.

**Comment by theofficialgman** [comment]
> Was there ever any outcome on this? If not, I want to remove this app completely from Pi-Apps, as it has been hidden for two years.

@Botspot Never resolved. lokinet-gui (the "new" gui) was never built for arm linux (only the very old, pre-1.0 release exists on older distros while newer ones actually just have no lokinet-gui package at all). The isn't the case on amd64. Seems reasonable to remove it given the lack of upstream support for 2 years.

Just for reference, I checked for this info from the packages files

arm64:
https://deb.oxen.io/dists/noble/main/binary-arm64/Packages
https://deb.oxen.io/dists/jammy/main/binary-arm64/Packages

**Comment by necro-nemesis** [comment]
Lokinet went through a complete and lengthy refactor to use quic. I can contact the lead dev to see if now would be the time to reintroduce it within Pi-Apps if there's interest still in the community.

**Comment by Botspot** [comment]
That's fine.

**Comment by jagerman** [comment]
Speaking as upstream project dev: our development focus currently is on getting the refactored version up and running with bugs ironed out working on our internal testnet before the end of this year, and then polishing and pushing the required server-side upgrade out to the network (with an ideal release target for February).  There's a lot of promising changes for reliability and performance, but at the moment our focus is on the core; as we get closer to a public-ready release we'll definitely come back to getting the new electron GUI working on ARM with an aim to re-enter pi-apps.
