### ISSUE TITLE
Blank list - No Categories

### ISSUE THREAD

**Issue by DaveDischord** [Botspot/pi-apps#1842]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)

### What happened?

App does not display list of categories after launch.

### Description

It started after an Pi-Apps update.  I went ahead and uninstalled Pi-apps and removed the ~/pi-apps folder before doing a fresh install with the same results.  I've even changed themes between light and dark and went to Settings -> Categories -> All and Saved with no change
![Screen Shot 05-19-22 at 09 19 AM](https://user-images.githubusercontent.com/14235646/169318890-fb20a0c2-1168-49e7-881b-51c087a55656.PNG)
.

### What is your operating system?

TwisterOS on Pi4

**Comment by DaveDischord** [comment]
The only thing out of the ordinary from the looks of it is the **#00AA00** on Line 28
[output.txt](https://github.com/Botspot/pi-apps/files/8730377/output.txt)
2

**Comment by Crilum** [comment]
This has happened to me a couple of times too..

**Comment by Crilum** [comment]
I did, when I had the issue, it looked like `preload` issues..

**Comment by DaveDischord** [comment]
Just looks like its hanging on 'Reading list file...' unless that's normal.
![Screen Shot 05-19-22 at 12 48 PM](https://user-images.githubusercontent.com/14235646/169365055-8e7ac51d-b51f-472b-be96-d022437ad764.PNG)

**Comment by Botspot** [comment]
> Just looks like its hanging on 'Reading list file...' unless that's normal. ![Screen Shot 05-19-22 at 12 48 PM](https://user-images.githubusercontent.com/14235646/169365055-8e7ac51d-b51f-472b-be96-d022437ad764.PNG)

Do you have a discord account? I'd like to test some things myself on your system through AnyDesk, and we need a private place to share credentials.

**Comment by DaveDischord** [comment]
Yes, but I can't seem to be able to install AnyDesk. Using `sudo pi-apps/apps/AnyDesk/install-32` returns `pi-apps/apps/AnyDesk/install-32: line 5: install_packages: command not found`

**Comment by Botspot** [comment]
> Yes, but I can't seem to be able to install AnyDesk. Using `sudo pi-apps/apps/AnyDesk/install-32` returns `pi-apps/apps/AnyDesk/install-32: line 5: install_packages: command not found`

Pi-Apps is not designed to be used with `sudo`, and the `install_packages` function is a local function.
The poper way to install apps from the command-line is: `~/pi-apps/manage install AnyDesk`

Once you get it installed, please go to Discord and message Botspot#6825

**Comment by DaveDischord** [comment]
I'm sorry. I got caught up at work and couldn't get to having a session.

**Comment by theofficialgman** [comment]
> The only thing out of the ordinary from the looks of it is the **#00AA00** on Line 282 [output.txt](https://github.com/Botspot/pi-apps/files/8730377/output.txt)

thats color data for the app being installs, thats perfectly normal.

there are MANY problems with your output though, following botspots command should give you the main page output ONLY. there are MANY apps in the output and NONE should be on the main page

this is very strange... my guess would be a faulty SD card where data is not getting writter correctly, resulting in random data corruption, since you say you have tried on a clean install.

**Comment by Botspot** [comment]
> I'm sorry. I got caught up at work and couldn't get to having a session.

Maybe today then?

**Comment by astremler** [comment]
I am having exact the same problems described as above on 2 different raspberry Pi's (Pi 400 and Pi 4) both using Ubuntu 20. The problems started after updating (sudo apt upgrade). First on my Pi 400 the issue started with blank window. Uninstalling/Removing pi-apps folder and re-installing didn't help. While on my Pi 4 it still works fine and I decided to do the same: just updating by 'sudo apt upgrade' and then the problem started there as well. Any idea?

**Comment by Crilum** [comment]
> I am having exact the same problems described as above on 2 different raspberry Pi's (Pi 400 and Pi 4) both using Ubuntu 20. The problems started after updating (sudo apt upgrade). First on my Pi 400 the issue started with blank window. Uninstalling/Removing pi-apps folder and re-installing didn't help. While on my Pi 4 it still works fine and I decided to do the same: just updating by 'sudo apt upgrade' and then the problem started there as well. Any idea?

Like @Botspot said: try running `~/pi-apps/preload yad` in your terminal, and see if there are any errors.
If there are any (error logs), could you post them here?

**Comment by astremler** [comment]
I got this log:

Timestamps match.
Reading list file for ''...
/home/pi/pi-apps/icons/categories/All Apps.png
All Apps
All Apps/
All Pi-Apps Applications in one long list.

/home/pi/pi-apps/icons/categories/Appearance.png
Appearance
Appearance/
Applications and Themes which modify the look and feel of your OS.

/home/pi/pi-apps/icons/categories/Creative Arts.png
Creative Arts
Creative Arts/
Drawing, Painting, and Photo and Movie Editors

/home/pi/pi-apps/icons/categories/Engineering.png
Engineering
Engineering/
3D Printing slicers, CAD/modeling, and general design software

/home/pi/pi-apps/icons/categories/Games.png
Games
Games/
Games and Emulators

/home/pi/pi-apps/icons/categories/Installed.png
Installed
Installed/
All Pi-Apps Apps that you have installed.

/home/pi/pi-apps/icons/categories/Internet.png
Internet
Internet/
Browsers, Chat Clients, Email Clients, and so much more.

/home/pi/pi-apps/icons/categories/Multimedia.png
Multimedia
Multimedia/
Video playback and creation, audio playback and creation, and streaming alternatives.

/home/pi/pi-apps/icons/categories/Office.png
Office
Office/
Office suites (document and slideshow editors), and other office tools.

/home/pi/pi-apps/icons/categories/Packages.png
Packages
Packages/
Simple Apps that install directly from APT repos.

/home/pi/pi-apps/icons/categories/Programming.png
Programming
Programming/
Code editors, IDEs, and other applications to help you write and make other programs.

/home/pi/pi-apps/icons/categories/System Management.png
System Management
System Management/
Apps that help you keep track of system resources and general system management.

/home/pi/pi-apps/icons/categories/Terminals.png
Terminals
Terminals/
Alternative terminal programs built for the modern age as well as to replicate your old vintage computer.

/home/pi/pi-apps/icons/categories/Tools.png
Tools
Tools/
An assortment of helpful programs that don't already fit into another category.

**Comment by Crilum** [comment]
@astremler That looks correct.. I'm not sure what's going on.

**Comment by theofficialgman** [comment]
@DaveDischord @PythonScratcher @astremler

since all of your appear to have similar issues (at least in regard to what is happening visualally) can you all please run pi-apps directly via the terminal
```
PS4='Line ${LINENO}: ' bash -x ~/pi-apps/gui
```

assuming you still are having issues, send all output from that terminal session here. this adds a bit of debug logging to at least show me where in the script you might have issues

**Comment by astremler** [comment]
@theofficialgman 

See the output below:

pi@Puerto-Pi400:~$ PS4='Line ${LINENO}: ' bash -x ~/pi-apps/gui
Line 8: command -v yad
Line 13: export GUI_FORMAT_VERSION=2
Line 13: GUI_FORMAT_VERSION=2
Line 16: '[' -z '' ']'
LLine 18: zcat /usr/share/doc/yad/NEWS.gz
LLine 18: head -n 1
LLine 18: tr -cd '0123456789\n'
Line 18: yad_version=0400
Line 19: '[' 0400 -lt 0400 ']'
Line 34: text_color=
Line 37: export text_color
Line 87: false
Line 95: '[' '!' -z '' ']'
LLLine 299: dirname /home/pi/pi-apps/gui
LLine 299: readlink -f /home/pi/pi-apps
Line 299: DIRECTORY=/home/pi/pi-apps
Line 301: set -a
Line 302: source /home/pi/pi-apps/api
LLine 2255: trap 'exit 1' INT
LLine 2257: cd /home/pi
LLine 2259: add_english
LLLine 97: cat /usr/share/i18n/SUPPORTED
LLLine 97: grep -o en_US.UTF-8
LLine 97: '[' en_US.UTF-8 == en_US.UTF-8 ']'
LLLine 98: locale -a
LLLine 98: grep -oF en_US.utf8
LLine 98: locale=en_US.utf8
LLine 99: '[' en_US.utf8 '!=' en_US.utf8 ']'
LLine 107: export LANG=en_US.UTF-8
LLine 107: LANG=en_US.UTF-8
LLine 108: export LANGUAGE=en_US.UTF-8
LLine 108: LANGUAGE=en_US.UTF-8
LLine 109: export LC_ALL=en_US.UTF-8
LLine 109: LC_ALL=en_US.UTF-8
LLLine 2262: cat '/home/pi/pi-apps/data/settings/App List Style'
LLine 2262: guimode=yad-default
LLine 2263: '[' yad-default == yad-dark ']'
LLine 2265: '[' yad-default == yad-light ']'
LLine 2267: '[' yad-default == yad-default ']'
LLine 2268: export GTK_THEME=
LLine 2268: GTK_THEME=
LLine 2278: yadflags=(--center --window-icon="${DIRECTORY}/icons/logo.png" --title="Pi-Apps" --separator='\n')
LLLLine 2281: readlink -f /sbin/init
LLLine 2281: od -An -t x1 -j 4 -N 1 /usr/lib/systemd/systemd
LLine 2281: '[' ' 02' = ' 02' ']'
LLine 2282: arch=64
LLine 2290: export GDK_BACKEND=x11
LLine 2290: GDK_BACKEND=x11
LLine 2293: [[ /home/pi/pi-apps/gui == */api ]]
LLine 2299: '[' -z /home/pi/pi-apps ']'
LLine 2299: '[' /home/pi/pi-apps == /home/pi ']'
LLine 2299: '[' '!' -d /home/pi/pi-apps ']'
LLine 2304: export DIRECTORY
Line 305: generate_logo
Line 35: blue='\e[38;5;21m'
Line 36: green='\e[38;5;46m'
Line 37: darkgreen='\e[38;5;34m'
Line 38: red='\e[38;5;197m'
Line 311: mkdir -p /home/pi/pi-apps/data/status /home/pi/pi-apps/data/update-status
LLine 41: grep VERSION_ID= /etc/os-release
LLine 41: tr -cd 0123456789.
Line 41: local version_id=20.04
Line 42: [[ 20.04 != *\.* ]]
Line 51: echo -e '\e[40m\e[97m    \e[38;5;46m▅\e[38;5;34m▅▅▅▅\e[38;5;46m▅\e[40m\e[97m
 \e[38;5;21m▂▂▂\e[38;5;46m█\e[38;5;21m▂▂▂▂\e[38;5;46m█\e[38;5;21m▂▂▂\e[40m\e[97m
 \e[107m\e[38;5;21m▌  \e[38;5;197m\e[40m▗▖▗▖▗▖\e[107m\e[38;5;21m  ▐\e[40m\e[97m   █▀▀▆ ▄
 \e[107m\e[38;5;21m▌  \e[38;5;197m\e[40m▗▖▗▖▗▖\e[107m\e[38;5;21m  ▐\e[40m\e[97m   █▄▄\e[7m▂\e[27m ▄ \e[38;5;21m▄▄\e[97m ▆▀▀█ █▀▀▆ █▀▀▆ ▆\e[7m━━━\e[27m
 \e[107m\e[38;5;21m▌  \e[38;5;197m\e[40m▗▖▗▖▗▖\e[107m\e[38;5;21m  ▐\e[40m\e[97m   █    █    \e[7m▂\e[27m▄▄█ █▄▄\e[7m▂\e[27m █▄▄\e[7m▂\e[27m ▄▄▄\e[7m▂\e[27m
 \e[38;5;21m\e[7m▂\e[27m\e[107m▃▃▃▃▃▃▃▃▃▃\e[40m\e[7m▂\e[27m\e[40m\e[40m\e[97m                  █    █
\e[0m\e[0m'
    ▅▅▅▅▅▅
 ▂▂▂█▂▂▂▂█▂▂▂
 ▌  ▗▖▗▖▗▖  ▐   █▀▀▆ ▄
 ▌  ▗▖▗▖▗▖  ▐   █▄▄▂ ▄ ▄▄ ▆▀▀█ █▀▀▆ █▀▀▆ ▆━━━
 ▌  ▗▖▗▖▗▖  ▐   █    █    ▂▄▄█ █▄▄▂ █▄▄▂ ▄▄▄▂
 ▂▃▃▃▃▃▃▃▃▃▃▂                  █    █

Line 313: trap 'kill 3775111 &>/dev/null' EXIT
Line 312: /home/pi/pi-apps/updater set-status
Line 317: sleep 10
LLine 506: cat '/home/pi/pi-apps/data/settings/App List Style'
Line 334: runonce
LLine 1750: cat /dev/stdin
Line 1750: script='  rm -rf  "${DIRECTORY}/data/preload"'
Line 506: guimode=yad-default
Line 507: '[' -z yad-default ']'
Line 621: get_positions
LLine 1752: sha1sum
LLine 1752: awk '{print $1}'
LLine 513: sed -n -e 's/^.*primary //p'
LLine 513: awk -F 'connected |\\+|\\(' '/ connected.*[0-9]+x[0-9]+\+/ && $2 {printf $2 ", "}'
LLine 513: tr x+ ' '
LLine 513: xrandr --nograb --current
LLine 513: tr ,+ ' '
Line 513: screen_dimensions='1920 1080  '
Line 514: '[' -z '1920 1080  ' ']'
Line 1752: runonce_hash=a61227109afaaf250c3eebb401608f8a4cc77f85
Line 1754: grep -qxF a61227109afaaf250c3eebb401608f8a4cc77f85 /home/pi/pi-apps/data/runonce_hashes
Line 1757: true
Line 339: runonce
LLine 519: awk '{print $1}'
LLine 1750: cat /dev/stdin
Line 1750: script='  if [ -f /usr/local/bin/twistver ] && command -v wine >/dev/null ;then
    echo '\''disabled'\'' > "${DIRECTORY}/data/status/Wine (x86)"
  fi
  if [ -f /usr/local/bin/twistver ] && command -v box86 >/dev/null ;then
    echo '\''disabled'\'' > "${DIRECTORY}/data/status/Box86"
  fi'
LLine 1752: sha1sum
LLine 1752: awk '{print $1}'
Line 519: screen_width=1920
LLine 520: awk '{print $2}'
Line 1752: runonce_hash=6934a09e1c6bb7dbbc8a61d87edc10e4e02ebdd9
Line 1754: grep -qxF 6934a09e1c6bb7dbbc8a61d87edc10e4e02ebdd9 /home/pi/pi-apps/data/runonce_hashes
Line 520: screen_height=1080
Line 521: unset screen_dimensions
Line 1757: true
Line 523: [[ yad-default == yad* ]]
Line 528: main_yad_window=
Line 529: '[' -n '' ']'
Line 349: runonce
Line 577: '[' 1920 -le 1000 ']'
Line 577: '[' 1080 -le 600 ']'
Line 588: height=600
Line 589: width=800
Line 592: width1=320
Line 594: width2=480
Line 597: yoffset=240
Line 600: xoffset1=560
Line 602: xoffset2=880
Line 605: geometry1=--geometry=320x600+560+240
Line 606: geometry2=--geometry=480x600+880+240
Line 624: [[ yad-default == xlunch* ]]
Line 682: '[' '!' -f /home/pi/pi-apps/data/announcements ']'
LLine 1750: cat /dev/stdin
LLine 682: find /home/pi/pi-apps/data/announcements -mtime +1 -print
Line 1750: script='if [ -f /usr/local/bin/twistver ] && [[ "$(twistver)" != '\''Twister OS version'\''* ]];then
  "${DIRECTORY}/install"
fi'
LLine 1752: awk '{print $1}'
Line 682: '[' '!' -z '' ']'
LLine 1752: sha1sum
Line 686: [[ yad-default == yad* ]]
LLine 689: mktemp -u
Line 1752: runonce_hash=1ecc4c03b401b5181b4090f1db79c7251667cf6e
Line 1754: grep -qxF 1ecc4c03b401b5181b4090f1db79c7251667cf6e /home/pi/pi-apps/data/runonce_hashes
Line 689: pipe=/tmp/tmp.6TQdYBwxcA
Line 690: mkfifo /tmp/tmp.6TQdYBwxcA
Line 1757: true
Line 356: runonce
LLine 1750: cat /dev/stdin
Line 691: trap 'rm /tmp/tmp.6TQdYBwxcA' EXIT
Line 692: echo pipe is /tmp/tmp.6TQdYBwxcA
pipe is /tmp/tmp.6TQdYBwxcA
Line 694: true
Line 696: echo -e '\f'
Line 1750: script='  #rework chromium downgrading apps to one single new app: '\''Downgrade Chromium'\''
  rm -rf "${DIRECTORY}/apps/Back to Chromium v86"
  rm -rf "${DIRECTORY}/apps/Back to Chromium v78"
  if [ "$(cat "${DIRECTORY}/data/status/Back to Chromium v78" 2>/dev/null)" == installed ] || [ "$(cat "${DIRECTORY}/data/status/Back to Chromium v86" 2>/dev/null)" == installed ];then
    echo "installed" > "${DIRECTORY}/data/status/Downgrade Chromium"
  fi
  
  #remove deprecated apps
  rm -rf "${DIRECTORY}/apps/FreeCAD (precompiled)"
  rm -rf "${DIRECTORY}/apps/Chromium Media Edition"
  rm -rf "${DIRECTORY}/apps/Cordless"
  rm -rf "${DIRECTORY}/apps/Retropie"
  rm -rf "${DIRECTORY}/apps/Raspi2png"
  rm -rf "${DIRECTORY}/apps/Falkon"
  rm -rf "${DIRECTORY}/apps/FreeCAD"
  rm -rf "${DIRECTORY}/apps/LinuxCNC"
  
  #remove TBOPlayer if it'\''s not already successfully installed
  if [ "$(app_status TBOPlayer)" != '\''installed'\'' ];then
    rm -rf "${DIRECTORY}/apps/TBOPlayer"
  fi
  
  #rename '\''Turbo Scratch'\'' app to '\''Turbowarp'\''
  rm -rf "${DIRECTORY}/apps/Turbo Scratch"
  mv -f "${DIRECTORY}/data/status/Turbo Scratch" "${DIRECTORY}/data/status/Turbowarp" 2>/dev/null
  
  #rename '\''Pi-Apps Terminal Plugin'\'' app to '\''Pi-Apps Terminal Plugin (python)'\''
  rm -rf "${DIRECTORY}/apps/Pi-Apps Terminal Plugin"
  mv -f "${DIRECTORY}/data/status/Pi-Apps Terminal Plugin" "${DIRECTORY}/data/status/Pi-Apps Terminal Plugin (python)" 2>/dev/null
  
  #rename '\''Whatsapp'\'' app to '\''WhatsApp'\''
  rm -rf "${DIRECTORY}/apps/Whatsapp"
  mv -f "${DIRECTORY}/data/status/Whatsapp" "${DIRECTORY}/data/status/WhatsApp" 2>/dev/null
  
  #rename '\''Sonic Pi 3.2'\'' to '\''Sonic Pi'\''
  rm -rf "${DIRECTORY}/apps/Sonic Pi 3.2"
  mv -f "${DIRECTORY}/data/status/Sonic Pi 3.2" "${DIRECTORY}/data/status/Sonic Pi" 2>/dev/null
  
  
  #rename '\''Min Browser'\'' to '\''Min'\''
  rm -rf "${DIRECTORY}/apps/Min Browser"
  mv -f "${DIRECTORY}/data/status/Min Browser" "${DIRECTORY}/data/status/Min" 2>/dev/null
  
  #rename '\''Pale Moon Browser'\'' to '\''Pale Moon'\''
  rm -rf "${DIRECTORY}/apps/Pale Moon Browser"
  mv -f "${DIRECTORY}/data/status/Pale Moon Browser" "${DIRECTORY}/data/status/Pale Moon" 2>/dev/null
  
  #rename '\''Puffin Browser Demo'\'' to '\''Puffin'\''
  rm -rf "${DIRECTORY}/apps/Puffin Browser Demo"
  mv -f "${DIRECTORY}/data/status/Puffin Browser Demo" "${DIRECTORY}/data/status/Puffin" 2>/dev/null
  
  #rename '\''Quartz Browser'\'' to '\''Quartz'\''
  rm -rf "${DIRECTORY}/apps/Quartz Browser"
  mv -f "${DIRECTORY}/data/status/Quartz Browser" "${DIRECTORY}/data/status/Quartz" 2>/dev/null
  
  #rename '\''Tor Browser'\'' to '\''Tor'\''
  rm -rf "${DIRECTORY}/apps/Tor Browser"
  mv -f "${DIRECTORY}/data/status/Tor Browser" "${DIRECTORY}/data/status/Tor" 2>/dev/null
  
  #rename '\''KeePassX'\'' to '\''KeePassXC'\''
  rm -rf "${DIRECTORY}/apps/KeePassX"
  mv -f "${DIRECTORY}/data/status/KeePassX" "${DIRECTORY}/data/status/KeePassXC" 2>/dev/null
  
  true'
LLine 701: shuf -n 1 /home/pi/pi-apps/data/announcements
LLine 1752: awk '{print $1}'
LLine 1752: sha1sum
Line 1752: runonce_hash=4bc97219543211749de8586e7fdcbdcd43b77b27
Line 1754: grep -qxF 4bc97219543211749de8586e7fdcbdcd43b77b27 /home/pi/pi-apps/data/runonce_hashes
Line 701: motd='Enable full <b>dark mode</b> in Chromium with the Better Chromium app.'
Line 705: tail -F /tmp/tmp.6TQdYBwxcA
Line 705: yad --center --title=Pi-Apps --image=/home/pi/pi-apps/icons/logo-64.png --image-on-top --text 'Enable full <b>dark mode</b> in Chromium with the Better Chromium app.' --list --no-headers --column=:IMG --column=Name --column=Sysname:HD --column=tip:HD --column=@fore@:HD '--separator=\n' --window-icon=/home/pi/pi-apps/icons/logo.png --tooltip-column=4 --dclick-action 'env pipe=/tmp/tmp.6TQdYBwxcA '\''/home/pi/pi-apps/gui'\''' --select-action 'env pipe=/tmp/tmp.6TQdYBwxcA '\''/home/pi/pi-apps/gui'\''' '--button=!/home/pi/pi-apps/icons/search.png!Search:env pipe=/tmp/tmp.6TQdYBwxcA '\''/home/pi/pi-apps/gui'\'' '\'''\'' '\'''\'' Search/ Search/' '--button=!/home/pi/pi-apps/icons/options.png!Settings:2' --geometry=320x600+560+240
Line 1757: true
Line 424: runonce
LLine 1750: cat /dev/stdin
Line 1750: script='  if [ "$(cat "${DIRECTORY}/data/settings/App List Style")" == xlunch ];then
    echo '\'
![screenshot](https://user-images.githubusercontent.com/5723122/171327188-07acd60a-70dd-40ef-a361-8ba7ab1a4a84.png)
'xlunch-dark'\'' > "${DIRECTORY}/data/settings/App List Style"
  fi'
LLine 1752: sha1sum
LLine 1752: awk '{print $1}'
Line 697: sleep 0.5
Line 1752: runonce_hash=df7ad95f0e073fd66c146647cba094e9c66b2dc0
Line 1754: grep -qxF df7ad95f0e073fd66c146647cba094e9c66b2dc0 /home/pi/pi-apps/data/runonce_hashes
Line 1757: true
Line 431: runonce
LLine 1750: cat /dev/stdin
Line 1750: script='  dependencies='\''yad curl wget aria2 lsb-release apt-utils imagemagick bc librsvg2-bin locales shellcheck git wmctrl xdotool x11-utils'\''
  # Install dependencies if necessary
  if ! dpkg -s $dependencies >/dev/null 2>&1; then
    sudo_popup apt install $dependencies -y -f --no-install-recommends
  fi'
LLine 1752: sha1sum
LLine 1752: awk '{print $1}'
Line 1752: runonce_hash=5587752ef11bc4f0e9534aff49f6eaf62d9e552e
Line 1754: grep -qxF 5587752ef11bc4f0e9534aff49f6eaf62d9e552e /home/pi/pi-apps/data/runonce_hashes
Line 1757: true
Line 440: runonce
LLine 1750: cat /dev/stdin
Line 1750: script='  if dpkg -l box86-no-binfmt-restart &>/dev/null ;then
    sudo_popup bash -c '\''dpkg --remove box86-no-binfmt-restart pi-apps-5f3374a7 && apt update && apt install box86 -y'\''
  fi
  
  #if box86 is supposedly installed, but box86 command not found, reinstall box86
  if [ "$(app_status Box86)" == '\''installed'\'' ] && ! command -v box86 >/dev/null;then
    rm -f "${DIRECTORY}/data/status/Box86"
    "${DIRECTORY}/manage" uninstall Box86
    "${DIRECTORY}/manage" install Box86
  fi
  true'
LLine 1752: sha1sum
LLine 1752: awk '{print $1}'
Line 1752: runonce_hash=098d329db1d610890e418e202abcae288d644ba1
Line 1754: grep -qxF 098d329db1d610890e418e202abcae288d644ba1 /home/pi/pi-apps/data/runonce_hashes
Line 1757: true
Line 455: runonce
LLine 1750: cat /dev/stdin
Line 1750: script='  rm -f "${DIRECTORY}/etc/bitlylink"
  rm -rf "${DIRECTORY}/data/categories"'
LLine 1752: sha1sum
LLine 1752: awk '{print $1}'
Line 1752: runonce_hash=88fea75739686e3bad8c5aa64f48bc913f188176
Line 1754: grep -qxF 88fea75739686e3bad8c5aa64f48bc913f188176 /home/pi/pi-apps/data/runonce_hashes
Line 1757: true
Line 461: runonce
LLine 1750: cat /dev/stdin
Line 1750: script='  IFS=$'\''\n'\''
  for app in $(list_apps package) ;do
    rm -f "${DIRECTORY}/data/status/${app}" || exit 1
  done
  
  refresh_all_pkgapp_status'
LLine 1752: sha1sum
LLine 1752: awk '{print $1}'
Line 1752: runonce_hash=4fc1fdfcc760e68d067f1bb9af22822393bfef0a
Line 1754: grep -qxF 4fc1fdfcc760e68d067f1bb9af22822393bfef0a /home/pi/pi-apps/data/runonce_hashes
Line 1757: true
Line 471: runonce
LLine 1750: cat /dev/stdin
Line 1750: script='  [ -a "$HOME/.local/share/applications/pi-apps-settings.desktop" ] && sed -i "s/logo.png/settings.png/g" "$HOME/.local/share/applications/pi-apps-settings.desktop" || true'
LLine 1752: sha1sum
LLine 1752: awk '{print $1}'
Line 1752: runonce_hash=e48bf347e7d32a0a3149c3214fe124ccf1b77543
Line 1754: grep -qxF e48bf347e7d32a0a3149c3214fe124ccf1b77543 /home/pi/pi-apps/data/runonce_hashes
Line 1757: true
Line 478: runonce
LLine 1750: cat /dev/stdin
Line 1750: script='  if [ -f /usr/bin/startlxde-pi ] && grep -q '\''/var/lib/menu-xdg"'\'' /usr/bin/startlxde-pi ;then
    sudo_popup sed -i '\''s;/var/lib/menu-xdg";/var/lib/menu-xdg${XDG_DATA_DIRS:+:$XDG_DATA_DIRS}";g'\'' /usr/bin/startlxde-pi
  fi'
LLine 1752: sha1sum
LLine 1752: awk '{print $1}'
Line 1752: runonce_hash=084bb057834363ce504ae6736c8abefaf82fa702
Line 1754: grep -qxF 084bb057834363ce504ae6736c8abefaf82fa702 /home/pi/pi-apps/data/runonce_hashes
Line 1757: true
Line 486: runonce
LLine 1750: cat /dev/stdin
Line 1750: script='  # Remove packages if necessary
  pkgToRemoveListFull="sdl2-image sdl2-mixer sdl2-ttf"
  pkgToRemoveList=""
  IFS='\'' '\''
  for pkgToRemove in $(echo $pkgToRemoveListFull); do
    $(dpkg --status $pkgToRemove &> /dev/null)
    if [[ $? -eq 0 ]]; then
      pkgToRemoveList="$pkgToRemoveList $pkgToRemove"
    fi
  done
  
  if [ ! -z "$pkgToRemoveList" ]; then
    sudo_popup apt-get --yes --purge remove $pkgToRemoveList || error "Could not remove packages"
  fi'
LLine 1752: sha1sum
LLine 1752: awk '{print $1}'
Line 1752: runonce_hash=7022b1f9ae6f7c75a8cc6c6fa62810a3dec45e03
Line 1754: grep -qxF 7022b1f9ae6f7c75a8cc6c6fa62810a3dec45e03 /home/pi/pi-apps/data/runonce_hashes
Line 1757: true
Line 698: /home/pi/pi-apps/preload yad ''
Timestamps match.
Reading list file for ''...
Line 318: command -v shellcheck
Line 323: sed 's/]31m//g'
Line 320: shellcheck /home/pi/pi-apps/updater --color=always
Line 320: grep '\[31m' --before 1
Line 328: sed 's/]31m//g'
Line 325: shellcheck /home/pi/pi-apps/api --color=always
Line 325: grep '\[31m' --before 1

I attached a screenshot but it came in the middle of the text.

**Comment by theofficialgman** [comment]
I have a feeling this is our culprit but can't reproduce...
https://github.com/Botspot/pi-apps/blob/6ed20c1b494e31743882f17ddf5e6fb635fd64a6/gui#L696-L699

@astremler 
if you feel comfortable, can you try manually increasing that sleep value to `sleep 5` and then running the `~/pi-apps/gui` again.

I just want to see if the pipe is the issue

**Comment by DaveDischord** [comment]
Sorry for the hiatus, its been a busy few weeks.  I've read over some of the posts and have attached 2 output files, one after running `PS4='Line ${LINENO}: ' bash -x ~/pi-apps/gui`  and the yad.txt output when I made the `sleep = 5` change and ran `~/pi-apps/gui`.  This is after a uninstall/reinstall of pi-apps.  On mine, I'm using a USB>NVMe for the OS storage, and BerryBoot in front, so I would hope my NVMe wasn't corrupted.  I haven't encountered any other issues elsewhere, but will keep an eye out
[piAppsOutput.txt](https://github.com/Botspot/pi-apps/files/8833984/piAppsOutput.txt)
[yad.txt](https://github.com/Botspot/pi-apps/files/8833985/yad.txt)
.

**Comment by theofficialgman** [comment]
@DaveDischord both your logs are the same and don't give any helpful output.

it appears that you have also run my command incorrect since I don't see any of the expected output. there should be output about the line number for each line of the bash script run
```
PS4='Line ${LINENO}: ' bash -x ~/pi-apps/gui
```

**Comment by DaveDischord** [comment]
[scriptResults.txt](https://github.com/Botspot/pi-apps/files/8856061/scriptResults.txt)

**Comment by Botspot** [comment]
@davedischord do you have Discord? I'd like message you to solve your problem by connecting to your Pi through AnyDesk.

**Comment by theofficialgman** [comment]
bug has been solved in the referenced commit
