### ISSUE TITLE
TiMidity++

### ISSUE THREAD

**Issue by faizu396** [Botspot/pi-apps#1845]
### What is the name of the app?

TiMidity++

### (Optional) Where is the app hosted?

[timidity.sourceforge.net](http://timidity.sourceforge.net)

### About the app

Midi player, can be run within terminal using timidity command or can be used via GUI

### Upload file or Add PR Link

[TiMidity++.zip](https://github.com/Botspot/pi-apps/files/8736930/TiMidity%2B%2B.zip)

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [x] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by theofficialgman** [comment]
I wouldn't suggest using the pacakge for timidity from debian. it is version 2.14 from 2012 (all debian versions).
timidity has been abandoned but it at least has a 2.15 release in source code from 2018

**Comment by faizu396** [comment]
Could adding a script to download it from the sourceforge servers be an option?

**Comment by faizu396** [comment]
And honestly, I don't really see what's wrong with 2.14

**Comment by theofficialgman** [comment]
> And honestly, I don't really see what's wrong with 2.14

I don't disagree. I just would rather issues be identified before using a very old version. If 2.14 works without major issues it can be used

**Comment by theofficialgman** [comment]
a modern maintained alternative is suggested for adding a midi player to pi-apps
