### ISSUE TITLE
Time for an app eligibility rubric!

### ISSUE THREAD

**Issue by Botspot** [Botspot/pi-apps#185]
It's time to write out what makes a good Pi-App.  
And, we need a standardized method of ranking app requests.

Here's my idea below:

1. 1-5 points: How many causal GUI users would find this app useful?
3. 1-5 points: How hard is it to install outside of Pi-Apps? (just one command? Or 20 commands?)
4. 1-5 points: The awesome factor. (5 is Kerbal Space program, 4 is an exotic browser, 1 is a slightly newer version of an antivirus)

Add up the points and see what you get. Below are some special cases where points don't matter - the app is disqualified:

- The app is already available on APT. 
- ~~The app requires paying for something.~~ Edit: What was I thinking? MC Java and MC Bedrock are already on here, and [KSP](https://github.com/Botspot/pi-apps/issues/139) is on the waiting list. I think they belong in Pi-Apps, despite costing money. This point is no longer valid.
- The app is illegal to distribute.

This issue is for **brainstorming**. Let's tally up the points for a few apps currently in Pi-Apps, and see which of them rank the highest.  
Do any apps seem unfairly judged too high or too low? Let me know!

**Comment by Botspot** [comment]
This really isn't an issue.

Closing. Something similar to this, minus the "points" system will be added to the README at some point.

**Comment by Botspot** [comment]
Note to self for future reference:

> Hey Botspot, you can view issues that can be closed due to inactivity, by clicking here: https://github.com/Botspot/pi-apps/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-asc
> (Open issue list sorted by least recent activity)

**Comment by srini-pro** [comment]
hey talktosrinivasn is open

**Comment by srini-pro** [comment]
is'nt talktosrinivasan is subbmited #talktosrinivasan

**Comment by Botspot** [comment]
> is'nt talktosrinivasan is subbmited #talktosrinivasan

@srini-pro STOP spamming this issue please.

**Comment by PGSCOM** [comment]
#1156
