### ISSUE TITLE
The Pi-Apps version of GParted is outdated.

### ISSUE THREAD

**Issue by Rak1ta** [Botspot/pi-apps#1852]
### Cool ideas?

Installed applications from Buster to Bulllseye and needed to format the flash drive in **exfat**. If you install GParted from the raspberry repository, then:
- Buster version = 0.32.0 [cannot](https://gparted.org/news.php?item=236) do this;
- Bullseye version = 1.2.0 offers (displays in the menu, but gives an error), but cannot without its own [package](https://gitlab.gnome.org/GNOME/gparted/-/issues/137), need to search and install

The latest version is [1.4.0](https://github.com/GNOME/gparted/tags)
Is it possible to get an up-to-date version for raspberry to make everything work?

**Comment by theofficialgman** [comment]
pi-apps uses a "package" app for gparted. this means it comes directly from debian/raspbian repos. as you have seen, buster repos have 0.32.0 and bullseye has 1.2.0.

this isn't a pi-apps issue but more of a limitation of newer gparted not being brought to old debian repos.
there is not a debianized version of gparted 1.4.0 available (1.3.0 is in sid already so it may be brought to buster/bullseye in the future)

**Comment by Botspot** [comment]
It would be easy enough to switch the app type to a script-app, but we'd need to ensure that the majority of users would care about the new features in 1.4.0.

**Comment by Crilum** [comment]
@Rak1ta Until this get resolved, you can install the exfat-utils package like this:
```
sudo apt install exfat-utils
```

GParted should work with exfat after that.

**Comment by theofficialgman** [comment]
> GParted should work with exfat after that.

only with bullseye. exfat partition creation  was not supported until version 1.2.0 using exfat-utils.
previous versions can only move partitions

**Comment by Botspot** [comment]
> @Rak1ta Until this get resolved, you can install the exfat-utils package like this:
> 
> ```
> sudo apt install exfat-utils
> ```

Or, in the case of Ubuntu, `sudo apt install exfatprogs`. [Source](https://github.com/Botspot/wor-flasher/issues/76)

**Comment by theofficialgman** [comment]
actually exfat-utils should not be used, that package does not contain exfatprogs on buster.
just install exfatprogs if its available (bullseye and up)

**Comment by Botspot** [comment]
> ```
> package_available exfatprogs
> if [[ $? == "0" ]]; then
>   install_packages exfatprogs || error "Failed to install dependencies"
> fi
> ```

Is there a particular advantage to using $?
I would have written it this way:
```
if package_available exfatprogs ; then
  install_packages exfatprogs || error "Failed to install dependencies"
fi
```

**Comment by theofficialgman** [comment]
> > ```
> > package_available exfatprogs
> > if [[ $? == "0" ]]; then
> >   install_packages exfatprogs || error "Failed to install dependencies"
> > fi
> > ```
> 
> Is there a particular advantage to using $? I would have written it this way:
> 
> ```
> if package_available exfatprogs ; then
>   install_packages exfatprogs || error "Failed to install dependencies"
> fi
> ```

there isn't any, its just the format I chose originally in other scripts and haven't changed

**Comment by Rak1ta** [comment]
> script-app

@Botspot I tried and something happened. I'm sure the setup is wrong, but it works (i.e. it is possible). 


Recommendation from the instructions and what was possible to put: g++, gettext, gnome-common, intltool, make, parted, yelp-tools
It took to install: libparted-dev, libgtkmm-3.0-dev


```
pi@raspberrypi:~ $ git clone https://github.com/GNOME/gparted
pi@raspberrypi:~ $ sudo mv ~/gparted /usr/local/
pi@raspberrypi:~ $ sudo su
root@raspberrypi:/home/pi# cd /usr/local/gparted
```

```
root@raspberrypi:/usr/local/gparted# 
(the instructions say to move to /usr/local)
autoreconf -i
intltoolize --force
./configure
make
make install
install -m 644 org.gnome.gparted.policy \
             /usr/share/polkit-1/actions/org.gnome.gparted.local.policy
```
It worked for me on Debian 10 32bit, but there were errors in the process, which I solved by searching on Google ([autoreconf -i](https://stackoverflow.com/questions/22603163/automake-error-ltmain-sh-not-found), [intltoolize --force](https://stackoverflow.com/questions/63201482/config-status-error-cannot-find-input-file-po-makefile-in-in))

Didn't work with exfatprogs. I already had an old version installed, but there is no such package from [GitHub](https://github.com/exfatprogs/exfatprogs) after installation according to the instructions
But the version [=1.1.3-1](http://raspbian.raspberrypi.org/raspbian/pool/main/e/exfatprogs/), intended for Bullseye, has earned
**{!}** _Some of your applications now require exfatprogs as a dependency_

**Comment by theofficialgman** [comment]
oh dear...  @Rak1ta you got really lost with how to properly compile and install software from source (in general). you should be cloning to a user owned folder, building the sofware in that folder (autoreconf, configure, make, etc), and then installing that with sudo make install...

I will note this is even detailed in the readme for gparted https://github.com/GNOME/gparted

when they say
```
   Briefly, build and install GParted into the default location of
   /usr/local using:
```
they DON'T mean to move the source code to that directory (like you have done)

**Comment by Rak1ta** [comment]
> they DON'T mean

Google translate says it's required. >_<

What about exfatprogs?  Is it acceptable to use deb from Bullseye?

**Comment by theofficialgman** [comment]
> Google translate says it's required. >_<

I am referring to your install (below) method... its very wrong

> pi@raspberrypi:~ $ git clone https://github.com/GNOME/gparted
> pi@raspberrypi:~ $ sudo mv ~/gparted /usr/local/
> pi@raspberrypi:~ $ sudo su
> root@raspberrypi:/home/pi# cd /usr/local/gparted
> root@raspberrypi:/usr/local/gparted# 
> (the instructions say to move to /usr/local)
> autoreconf -i
> intltoolize --force
> ./configure
> make
> make install
> install -m 644 org.gnome.gparted.policy \
>              /usr/share/polkit-1/actions/org.gnome.gparted.local.policy
>

**Comment by Rak1ta** [comment]
@theofficialgman thanks It works

```
sudo apt install g++ gettext gnome-common intltool make parted yelp-tools libparted-dev libgtkmm-3.0-dev
wget https://github.com/GNOME/gparted/archive/refs/tags/GPARTED_1_4_0.zip
unzip GPARTED_1_4_0.zip
cd gparted-GPARTED_1_4_0
intltoolize --force
autoreconf -i
./configure
make
sudo checkinstall
sudo install -m 644 org.gnome.gparted.policy \
             /usr/share/polkit-1/actions/org.gnome.gparted.local.policy
```
and [exfatprogs](http://raspbian.raspberrypi.org/raspbian/pool/main/e/exfatprogs/)=1.1.3-1

**Comment by Rak1ta** [comment]
@Botspot Is it possible to add (it works for me on Buster)  such variant (post above) of GParted to pi-apps?

**Comment by theofficialgman** [comment]
unsupported system (buster)
