### ISSUE TITLE
Geany Dark Mode not working as root

### ISSUE THREAD

**Issue by Rak1ta** [Botspot/pi-apps#1853]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)

### What happened?

Theme is not set to be used as root

### Description

Is it possible to make the theme install so that it works when using Geany as root?
For example, I edit config.txt

### What is your operating system?

RaspiOS 32bit Debian10/11

**Comment by theofficialgman** [comment]
> Is it possible to make the theme install so that it works when using Geany as root? For example, I edit config.txt

yes it is possible. @Botspot this would mean copying everything you currently do in ~/.config to the /root/.config
the theme and the config would need to exist in that /root/.config 

do we want to do this?

**Comment by Botspot** [comment]
There is a global location for default config. It is `/etc/xdg`. I'm not sure if all programs pay attention to it though, and in order for a global config file to take effect, the local one needs to be deleted.

It is a better option than searching for all home directories including root, and placing config files everywhere.

**Comment by theofficialgman** [comment]
> /etc/xdg

according to the geany manual it doesn't read that.  https://www.geany.org/manual/current/index.html#configuration-file-paths

it  only reads the install directory loction (/usr/share/geany) that will get overwritten by apt every time geany gets an update. and the $USER/.config/geany location

**Comment by theofficialgman** [comment]
actually there is no `/usr/share/geany/geany.conf` populated directly from the deb. so you can place a file here and it will apply for all users, I just tested it and it works @Botspot

**Comment by Botspot** [comment]
> actually there is no `/usr/share/geany/geany.conf` populated directly from the deb. so you can place a file here and it will apply for all users, I just tested it and it works @Botspot

That only works if that's a local config file does not already exist. I just tried running Geany without ~/.config/geany directory present. As soon as I closed Geany, a full geany.conf file was created in that directory.
This requires any script that changes the config, to make changes to every config file in the home folder and in `/usr/share/geany/geany.conf`. And that's assuming the user has not yet run geany as root, in which case we'd also have to edit /root/.config/geany/geany.conf

One thing I did notice:
```
$ dpkg -S /usr/share/geany/geany.conf
raspberrypi-ui-mods: /usr/share/geany/geany.conf
$ cat /usr/share/geany/geany.conf
[geany]
check_detect_indent=true
detect_indent_width=true
```
Also I found an Easter egg:
![2022-05-23-212051_1920x1080_scrot](https://user-images.githubusercontent.com/54716352/169935665-3480f2ca-58d7-4f90-ba02-9e9ec10d6ab3.png)

**Comment by theofficialgman** [comment]
> That only works if that's a local config file does not already exist. I just tried running Geany without ~/.config/geany directory present. As soon as I closed Geany, a full geany.conf file was created in that directory. This requires any script that changes the config, to make changes to every config file in the home folder and in `/usr/share/geany/geany.conf`. And that's assuming the user has not yet run geany as root, in which case we'd also have to edit /root/.config/geany/geany.conf

doesn't purging the app also remove its configs or not? if it doesn't, then your concerns are fair

> ```
> $ dpkg -S /usr/share/geany/geany.conf
> raspberrypi-ui-mods: /usr/share/geany/geany.conf
> $ cat /usr/share/geany/geany.conf
> [geany]
> check_detect_indent=true
> detect_indent_width=true
> ```

gosh dang it... why do they do this

**Comment by Botspot** [comment]
> doesn't purging the app also remove its configs or not? if it doesn't, then your concerns are fair

I've never seen an apt package remove its user config from $HOME. As a result, my year-old config folder consists of many folders that aren't even used by anything before as I uninstalled the apps long ago.

**Comment by theofficialgman** [comment]
> I've never seen an apt package remove its user config from $HOME. As a result, my year-old config folder consists of many folders that aren't even used by anything before as I uninstalled the apps long ago.

ah, I though purge removed the config files in the home directory. it removes them in everything but the ones in the home directory.
from the apt manpage:
```
Removing a package removes all packaged data, but leaves usually small (modified) user
configuration files behind, in case the remove was an accident. Just issuing an
installation request for the accidentally removed package will restore its function as
before in that case. On the other hand you can get rid of these leftovers by calling
purge even on already removed packages. Note that this does not affect any data or
configuration stored in your home directory.
```

**Comment by Crilum** [comment]
> Also I found an Easter egg: ![2022-05-23-212051_1920x1080_scrot](https://user-images.githubusercontent.com/54716352/169935665-3480f2ca-58d7-4f90-ba02-9e9ec10d6ab3.png)

Not sure why, I don't have that easter egg (:rofl:) :
![image](https://user-images.githubusercontent.com/91354257/169945975-aab8bde4-d879-46fb-9724-b64daf0b0710.png)

**Comment by Botspot** [comment]
![2022-05-23-231249_1920x1080_scrot](https://user-images.githubusercontent.com/54716352/169947447-e3713866-c868-4e28-a008-1d48aefe8e8e.png)
You are missing the other socket file too.

**Comment by theofficialgman** [comment]
@Botspot what is your final conclusion on the issue itself? leave it as a wontfix?
