### ISSUE TITLE
Abstraction of package installing

### ISSUE THREAD

**Issue by ralf1307** [Botspot/pi-apps#186]
pi-apps currently uses ex. apt for installing dependencies.
Because of this situation pi-apps is very dependent on an Debian-like systems.

[PackageKit](https://www.freedesktop.org/software/PackageKit/) sounds like the solution to achieve cross-platform compatibility.

**Comment by ralf1307** [comment]
https://blogs.gnome.org/hughsie/2019/02/14/packagekit-is-dead-long-live-well-something-else/
oh its deprecated. nevermind

**Comment by Botspot** [comment]
And on top of that, I've deliberately kept the app creation process as simple as possible. That way, beginners can easily make their own apps with zero prior knowledge.

So even if Packagekit was alive and well, I'd still have to decide if it was worth all the effort.
