### ISSUE TITLE
Snap Store is removed incorrectly (snapd package)

### ISSUE THREAD

**Issue by Rak1ta** [Botspot/pi-apps#1863]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)

### What happened?

"sudo apt purge snapd" fails

### Description

When deleting the Snap Store, it is suggested to delete completely by the command `sudo purge snapd`, но на моем RPi происходит вывод с ошибкой 
```
Removing snapd cache
rm: cannot remove '/var/cache/snapd/aux': Is a directory
dpkg: error processing package snapd (--purge):
 installed snapd package post-removal script subprocess returned error exit status 1
```
Based on this [message](https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1824234) thread, this error is corrected by the command
```
sudo rm -rf /var/cache/snapd/aux
sudo apt purge -y snapd
```
Is it possible to add a suggestion to the user whether he wants to remove the package, because this warning is displayed only for half a minute. And on Debian Buster (snapd-2.37.4-1) add these commands to complete the removal?

### What is your operating system?

RaspiOS 32bit Debian10

**Comment by theofficialgman** [comment]
snap store is just that, the store. its a rebranding of gnome-software and can install `debs` as well.

you should not be purging `snapd` as that will disabling the installation of snaps and remove all currently installed snaps

you can already see this is explained to you on uninstallation:
https://github.com/Botspot/pi-apps/blob/daf53a0f533ae38664f3c85838de12ef64cdbd36/apps/Snap%20Store/uninstall#L6-L8
