### ISSUE TITLE
PeaZip

### ISSUE THREAD

**Issue by ryanfortner** [Botspot/pi-apps#1865]
### What is the name of the app?

PeaZip

### (Optional) Where is the app hosted?

https://github.com/ryanfortner/peazip-arm/releases/download/8.6.0-fp2/peazip_8.6.0_fp1_arm64.deb

I'm opening an issue instead of a pr first because I would like for the package to be tested by more users than just me beforehand. Also, there is an option to use Flatpak for installing instead of a deb, if people would prefer that.

### About the app

PeaZip is a powerful free and open-source archive utility. It supports over 200 archive formats and counting. https://peazip.github.io/

![image](https://peazip.github.io/peazip.png)

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by theofficialgman** [comment]
```
Unpacking peazip (8.6.0~fp) ...
dpkg: error processing archive /tmp/apt-dpkg-install-gne6sK/5-peazip_8.6.0_fp_arm64.deb (--unpack):
 trying to overwrite '/usr/include/zdict.h', which is also in package libzstd-dev:arm64 1.3.3+dfsg-2ubuntu1.2
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
 /tmp/apt-dpkg-install-gne6sK/5-peazip_8.6.0_fp_arm64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

the package is improperly packaged with conflicting files. this can not be installed in pi-apps as it will cause issues on upgrade. please notify the upstream developers to fix their deb

**Comment by ryanfortner** [comment]
> ```
> Unpacking peazip (8.6.0~fp) ...
> dpkg: error processing archive /tmp/apt-dpkg-install-gne6sK/5-peazip_8.6.0_fp_arm64.deb (--unpack):
>  trying to overwrite '/usr/include/zdict.h', which is also in package libzstd-dev:arm64 1.3.3+dfsg-2ubuntu1.2
> dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
> Errors were encountered while processing:
>  /tmp/apt-dpkg-install-gne6sK/5-peazip_8.6.0_fp_arm64.deb
> E: Sub-process /usr/bin/dpkg returned an error code (1)
> ```
> the package is improperly packaged with conflicting files. this can not be installed in pi-apps as it will cause issues on upgrade and during installation. please notify the upstream developers to fix their deb

I’ll fix the deb as soon as I can.

 btw, there is no deb provided by the upstream developers. They only provide flatpaks. I’ve extracted the flatpak and packaged it into a deb.

**Comment by theofficialgman** [comment]
> btw, there is no deb provided by the upstream developers. They only provide flatpaks. I’ve extracted the flatpak and packaged it into a deb.

oh oops, I misread the url of the deb and thought it was from upstream. didn't realize it was your repo

**Comment by theofficialgman** [comment]
but they do have debs... just not arm64/armhf debs https://github.com/peazip/PeaZip/releases

**Comment by ryanfortner** [comment]
> but they do have debs... just not arm64/armhf debs https://github.com/peazip/PeaZip/releases

Yep I misspoke, sorry

**Comment by ryanfortner** [comment]
I just updated the link in my comment above, could you try again please @theofficialgman ?

**Comment by theofficialgman** [comment]
installs fine and the GUI runs, but most functions fail
like extracting a zip for example
```
Executable not found: "/usr/peazip/res/bin/7z/7z".
```

I went to this location and there are broken symbolic links
```
 file /usr/peazip/res/bin/7z/*
/usr/peazip/res/bin/7z/7z:        broken symbolic link to /app/bin/7z
/usr/peazip/res/bin/7z/7zCon.sfx: broken symbolic link to /app/bin/7zCon.sfx
```

**Comment by theofficialgman** [comment]
the flatpak itself works fine... might just be best to use that

**Comment by theofficialgman** [comment]
@ryanfortner since I have you though. can I pick your brain a bit. how do you directly download a .flatpak file from flathub?
I'm looking to download and edit one for another project... but the whole thing is convoluted to me

**Comment by ryanfortner** [comment]
> @ryanfortner since I have you though. can I pick your brain a bit. how do you directly download a .flatpak file from flathub?
> 
> I'm looking to download and edit one for another project... but the whole thing is convoluted to me

I looked for a while, but as far as I can see there is no way to download a flatpak without installing it. 

All data files from flatpak's are in /var/lib/flatpak and that's where I got the binaries.

**Comment by ryanfortner** [comment]
to keep things simple I think it's best if we just use the flatpak. I will make scripts later today.
