### ISSUE TITLE
Steam not working 

### ISSUE THREAD

**Issue by generalhindenburg** [Botspot/pi-apps#187]
When I try to run steam it gets stuck at processing vulkan shaders have I done something wrong I updated and complied the vulkan shaders from pi kiss downloaded box86 first then steam I also tried updating box86 and I'm still stuck at processing shaders. Any help would be appreciated. Great software by the way only problem I've had is with steam unfortunately. Also I am running raspberry pi os 32 bit. Is my problem just the os do I just need to run it on ubuntu?

**Comment by Botspot** [comment]
I'm not sure what to recommend.

Steam works for me! If it doesn't work for you, we have a tangle of stuff to fight through to get an answer.

- Is it a Pi-Apps problem? No.
- Is it a Box86 emulator problem? Maybe, but I asked @ptitSeb and he doesn't think so.
- So who can help? To be honest, I don't know.

**Comment by generalhindenburg** [comment]
So when I go to launch a game there's so reason it should get stuck on processing vulkan shaders because I believe half my problem is this. I even get a warning in the terminal (which never goes away) would taking a screenshot be of any help or do I just need to play with it some more ? I've tried looking through the old threads but I couldn't find a problem that matched mine.

**Comment by Botspot** [comment]
This issue is being closed now.

To recap: Steam is being **emulated**. Emulation can be spotty, and many Steam games are known to not work. Your Mileage May Vary.
