### ISSUE TITLE
Zoom getting an upgrade

### ISSUE THREAD

**Issue by Botspot** [Botspot/pi-apps#188]
I've been working on upgrading Zoom for a while now.

- It will fix pulseaudio problems:  
For years, Raspberry Pi OS has been notorious for glitching when **pulseaudio** is installed. Well, pulseaudio was necessary for Zoom to work. So, I made the install script install pulseaudio, and then disable it.  
Times have changed since then, and **RPiOS has switched to pulseaudio!** As soon as that happened, I removed the pulse-disabling code from the install script, but everyone who installed Zoom prior to that still has a broken Pulseaudio setup.  
So this new Zoom app version will undo those changes and fix everybody's system.
- Also, I'm switching Zoom to use [box86-updater](https://github.com/Botspot/box86-updater), instead of compiling box86. This saves a massive amount of time.
- As Zoom's official download website is back online thanks to [this bug report](https://devforum.zoom.us/t/cant-download-zoom-i686-tar-xz/38421), this script will download from there instead of from my [zoom_686_mirror](https://github.com/Botspot/zoom_686_mirror).

Slightly off-topic: There has been a super-popular [feature request on Zoom's developer forum site for them to release ARM builds for the Raspberry Pi](https://devforum.zoom.us/t/have-you-considered-building-zoom-for-the-raspberry-pi-4-linux-system/14257). It's seemed to me that Zoom Inc. has been ignoring it.  
UNTIL I happened to [mention it](https://devforum.zoom.us/t/cant-download-zoom-i686-tar-xz/38421/19) on the download-link-is-broken support thread. A Zoom staff member [saw it and says](https://devforum.zoom.us/t/cant-download-zoom-i686-tar-xz/38421/20) "Thanks @Botspot! :) We will evaluate the demand here."  
Cool. I may have just gotten the ball rolling for an official Zoom ARM build by writing that.

**Comment by Itai-Nelken** [comment]
@Botspot is it possible to make the install script try to download from the zoom website, and if it fails then download from your mirror?

**Comment by Botspot** [comment]
> @Botspot is it possible to make the install script try to download from the zoom website, and if it fails then download from your mirror?

Good idea.

**Comment by Botspot** [comment]
It turns out the latest version of Zoom 9686 is quite unstable! Out of five tries, it crashed upon joining a meeting three of those tries.

And, it's crashing 100% of the time when you click on Share Screen.

Because of this, the Zoom app will continue using my [zoom_686_mirror](https://github.com/Botspot/zoom_686_mirror). Yes the client is outdated, but it actually works.

**Comment by Botspot** [comment]
New Zoom App version uploaded with commit 6026e187b2ebee9342652548985cc671951d8f1f.

**Comment by fabianmendes** [comment]
I can't hear anything, should I install PulseAudio... right? The thing is that installiation Bluetooth headphones are a madness

**Comment by Botspot** [comment]
> I can't hear anything, should I install PulseAudio... right? The thing is that installation Bluetooth headphones is a madness

That probably wouldn't help. The Zoom app already installs pulseaudio already.

**Comment by fabianmendes** [comment]
Mhm, right. So what can I do or I suppose to do about the audio issue? Any
help?

 ~V. Fabian T· Mendes C.

**Comment by Botspot** [comment]
> So what can I do or I suppose to do about the audio issue? Any help?

No help. A lot pf people report the same thing, but nobody knows why. Audio problems started at about the same time Raspberry Pi OS switched to using pulseaudio.

**Comment by slaattnes** [comment]
I tried to install Zoom on a rpi4 running latest raspios and got this error message:

Setting up box86 (1:0.2.1+13cce1a4-1) ...
restarting systemd-binfmt...
Job for systemd-binfmt.service failed because the control process exited with error code.
See "systemctl status systemd-binfmt.service" and "journalctl -xe" for details.
dpkg: error processing package box86 (--configure):
 installed box86 package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 box86
E: Sub-process /usr/bin/dpkg returned an error code (1)
Failed to install the box86 package

Failed to install Box86 with install-32 script!
Box86 installation failed!

**Comment by Botspot** [comment]
@slaattnes Thank you for the bug report. To properly document your issue, I've created a new github issue for this.

Link: #471

**Comment by spinalbassoon10** [comment]
Hello , i have a joyaccsess webcam and in zoom the microphone dont work. itested it in some other apps and there the microphone works what can i do?

**Comment by Itai-Nelken** [comment]
@spinalbassoon10 that's a known issue, I think ptitseb (the developer of box86) said he thinks that pulseaudio isn't wrapped correctly. maybe linux x64 zoom will run better with box64 when its released.

**Comment by loudmusicpigeon** [comment]
has anyone gotten a mic to work on zoom?
which mics would you say will work best
i currently have a bluetooth mic and it doesn't work very well **only in zoom**

**Comment by Itai-Nelken** [comment]
Audio input doesn't work with Box86+zoom currently, it does work with box64 amd zoom.

**Comment by loudmusicpigeon** [comment]
> Audio input doesn't work with Box86+zoom currently, it does work with box64 amd zoom.

oh alright thanks
how do you downgrade to box64 then?

**Comment by Itai-Nelken** [comment]
> > Audio input doesn't work with Box86+zoom currently, it does work with box64 amd zoom.
> 
> oh alright thanks
> how do you downgrade to box64 then?

You can't downgrade, box64 is an x64 emulator for linux arm64.
To use it, install a 64bit OS and install zoom from pi-apps.

**Comment by shigerusz** [comment]
Hi,

I installed zoom x86-64 using pi-app.
The installation seems successful.
But it failed when running zoom:

Launching Zoom.
Dynarec for ARM64, with extension: ASIMD CRC32 PageSize:4096 Cores:4
Box64 with Dynarec v0.2.0 66686141 built on Nov 18 2022 06:47:14
Using default BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/
Using default BOX64_PATH: ./:bin/
Counted 52 Env var
Looking for zoom
Zoom detected, trying to use system libturbojpeg if possible
Rename process to "zoom"
Using emulated [libcef.so](http://libcef.so/)
Error loading needed lib [libffmpeg.so](http://libffmpeg.so/)
Error loading one of needed lib
Error: loading needed libs in elf /home/pi/zoom/zoom
Zoom exited. Close this terminal to exit

Please help me and give a hint.

Thanks and Regards,
