### ISSUE TITLE
cannot install any apps

### ISSUE THREAD

**Issue by matthewsalmon** [Botspot/pi-apps#1880]
Hi there, thanks for making this great app. Unfortunately, I cannot install anything at the moment. I am seeing the message "Failed to locate any terminal emulators!!!" on the command line when I click the "Install" button in the gui. Matt

**Comment by Botspot** [comment]
Thank you for reaching out and reporting this problem, @matthewsalmon.
The terminal-run script was recently updated to support the user's preference of `x-terminal-emulator`. I did briefly test these changes before I pushed them, but it's entirely possible something slipped through that only happens in certain scenarios.
You can see the recent changes to terminal-run [here.](https://github.com/Botspot/pi-apps/commit/a1d068075d7f4fe34be2eac994c0ee1b2cd64961)

**Comment by matthewsalmon** [comment]
Hi, this is the line that I have added to terminal-run:

elif [ "$choice" == lxterm ];then
  lxterm -T "$title" -e bash -c "$commands" &

Added at line 65. Matt

**Comment by Botspot** [comment]
> Hi, this is the line that I have added to terminal-run:
> 
> elif [ "$choice" == lxterm ];then lxterm -T "$title" -e bash -c "$commands" &
> 
> Added at line 65. Matt

Before you made those changes, did you see an error anywhere that said "Failed to locate any terminal emulators!!!"?

**Comment by matthewsalmon** [comment]
Hi @Botspot, yes, the error was "Failed to locate any terminal emulators!!!", around line 80 of terminal-run. In the elif I noticed that there was not a check for lxterm...

**Comment by Botspot** [comment]
> Hi @Botspot, yes, the error was "Failed to locate any terminal emulators!!!", around line 80 of terminal-run. In the elif I noticed that there was not a check for lxterm...

Previously, terminal-run had a final clause that would attempt running x-terminal-emulator directly, with the most generic way to run commands. This was removed in my recent change, but I am still confused about one thing.
You said:

>  I have lxterm, lxterminal, xterm and tabby installed.

Even if x-terminal-emulator points to an unsupported program (lxterm), it should have fallen back to other available options, which in this case would have been lxterminal. I don't understand why that did not work for you.

**Comment by theofficialgman** [comment]
> Update: I just found the issue. Changing `&&` to `||` on line 38 solves the problem. I will push an update to terminal-run in a moment, and that commit will close this issue.

line 38 of what? I don't see any && here https://github.com/Botspot/pi-apps/blob/78a47773a01115cf46a8b5a1a84b1f5afa6115d9/etc/terminal-run#L38

**Comment by theofficialgman** [comment]
the script works correctly for me as is... are you sure that is the problem?

**Comment by theofficialgman** [comment]
```
if [ ! -z "$terminal" ] && echo "$terminals" | grep -qF "$terminal" ;then
```
this reads as "if terminal contains a non-empty string and terminal is in the list of supported terminals" then "set it to choice"

**Comment by Botspot** [comment]
There, *now* it should be fixed. 🥲

**Comment by Botspot** [comment]
The actual problem was that `lxterm` is unsupported, but `lxterminal` is. Without the -x flag, grep found lxterm inside of lxterminal.
