### ISSUE TITLE
Dot Matrix

### ISSUE THREAD

**Issue by gtavio90** [Botspot/pi-apps#1882]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)

### What happened?

flatpak_install(): Could not install io.github.lainsce.DotMatrix because flatpak is not installed!

### Description

nstalled!

Failed to install Dot Matrix!
◢◣Need help? Copy the ENTIRE terminal output or take a screenshot.
Please ask on Github: https://github.com/Botspot/pi-apps/issues/new/choose
Or on DiscorRas

### What is your operating system?

rasapberry pi Debian GNU/Linux 11 (bullseye)

**Comment by Botspot** [comment]
@gtavio90, thank you for reporting this issue!
I have fixed it now in commit https://github.com/Botspot/pi-apps/commit/f4420636268d0072a3481b890a220b2c5e611c21.

It was a simple issue - for Dot Matrix we forgot to make sure flatpak was installed first.

**Comment by theofficialgman** [comment]
lol, looks like botspot got to it a few second before me.
fix has been pushed https://github.com/Botspot/pi-apps/commit/f4420636268d0072a3481b890a220b2c5e611c21

**Comment by Crilum** [comment]
Not sure how this got closed twice, lol:
![image](https://user-images.githubusercontent.com/91354257/170361076-b63b7251-c911-40f3-9e32-a8aa4329e6cc.png)

**Comment by theofficialgman** [comment]
> Not sure how this got closed twice

I had already typed into the closed message box before botspot closed it himself. Even after he closed it, I could still click the close button, so I did 😆
