### ISSUE TITLE
failed to install minecraft

### ISSUE THREAD

**Issue by premkubade** [Botspot/pi-apps#189]
when i try to install minecraft java it gives me a error that it failed to install minecraft java launcher

**Comment by premkubade** [comment]
Installing Minecraft Java with install-64 script
mkdir: cannot create directory ‘/home/pi/Minecraft’: File exists
Failed to install the launcher!

Failed to install Minecraft Java with install-64 script!

Close this window to exit.

**Comment by premkubade** [comment]
this was the issue while installing minecraft java through pi aaps

**Comment by premkubade** [comment]
Installing Minecraft Java with install-64 script
mkdir: cannot create directory ‘/home/pi/Minecraft’: File exists
Failed to install the launcher!

Failed to install Minecraft Java with install-64 script!

Close this window to exit.

**Comment by Botspot** [comment]
We'll continue using your original issue #173.
