### ISSUE TITLE
Sudoku

### ISSUE THREAD

**Issue by Rak1ta** [Botspot/pi-apps#1891]
### What is the name of the app?

Sudoku

### About the app

_This is an application for playing the popular sudoku logic puzzle game, in which one must fill a 9 by 9 square with the correct digits. It features automatic puzzle generation, saving and restoring games, annotations, trackers, and much more._

https://wiki.gnome.org/Apps/Sudoku
This is package-app.
[Sudoku.zip](https://github.com/Botspot/pi-apps/files/8784963/Sudoku.zip)

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by theofficialgman** [comment]
https://github.com/Botspot/pi-apps/issues/185#issue-776095524

see special package app rules here ^. Pi-apps does not have any other puzzle games unique to its platform. There is no reason to include this as it has no alternative in the store.
