### ISSUE TITLE
HandBrake

### ISSUE THREAD

**Issue by Rak1ta** [Botspot/pi-apps#1893]
### What is the name of the app?

HandBrake

### About the app

_HandBrake is a versatile, easy-to-use tool for converting DVDs and other videos into H.264, XViD, or Ogg formatted media.
It's particularly useful for making videos that are compatible with portable video devices such as the Apple iPod/iPhone or Sony PSP._

https://handbrake.fr/
This is package-app.
[HandBrake.zip](https://github.com/Botspot/pi-apps/files/8784997/HandBrake.zip)

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by theofficialgman** [comment]
package app rules: https://github.com/Botspot/pi-apps/issues/185
