### ISSUE TITLE
Xfburn

### ISSUE THREAD

**Issue by Rak1ta** [Botspot/pi-apps#1894]
### What is the name of the app?

Xfburn

### About the app

_Xfburn is a tool to help burning CDs and DVDs. It fits well in the Xfce Desktop Environment but can be used anywhere._

https://docs.xfce.org/apps/xfburn/start
I don't have an external drive at the moment, but there were no complaints on the rpi forum. This is package-app.
[Xfburn.zip](https://github.com/Botspot/pi-apps/files/8785000/Xfburn.zip)

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [ ] I have confirmed that this app can run on Raspberry Pi.

**Comment by ryanfortner** [comment]
I actually just used this the other day to burn an ISO to a cd drive, it worked perfectly. 

I haven’t tried it using rpios’ default desktop environment though. Are you sure xfburn can be installed without the entire xfce desktop suite along with it?

**Comment by Rak1ta** [comment]
@ryanfortner are you talking about dependencies?
![Безымянный](https://user-images.githubusercontent.com/88277343/171050613-a8431df6-ccd4-4a1c-a5b8-e77e7ca0a84e.png)

**Comment by Crilum** [comment]
```
$ sudo apt install xfburn
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  libburn4 libexo-2-0 libexo-common libisofs6 libjte2 libxfce4ui-2-0
  libxfce4ui-common
Suggested packages:
  devhelp
The following NEW packages will be installed:
  libburn4 libexo-2-0 libexo-common libisofs6 libjte2 libxfce4ui-2-0
  libxfce4ui-common xfburn
0 upgraded, 8 newly installed, 0 to remove and 5 not upgraded.
Need to get 1,947 kB of archives.
After this operation, 6,903 kB of additional disk space will be used.
Do you want to continue? [Y/n]
```

On RPiOS 11

**Comment by ryanfortner** [comment]
Thanks for confirming @Crilum and @Rak1ta , looks like it's safe to install on non-XFCE desktops. I have opened a pr, just waiting for botspot's approval. https://github.com/Botspot/pi-apps/pull/1916
