### ISSUE TITLE
TOS-Lite-Edu-Utils

### ISSUE THREAD

**Issue by DEVELOPER710** [Botspot/pi-apps#1895]
### **Name of APP is "TOS-Lite-Edu-Utils" by DEVELOPER710**

[TOS-Lite-Edu-Utils.zip](https://github.com/Botspot/pi-apps/files/8785842/TOS-Lite-Edu-Utils.zip)

**Comment by Crilum** [comment]
@DEVELOPER710 Did you mean to close this issue?
