### ISSUE TITLE
PyChess

### ISSUE THREAD

**Issue by Rak1ta** [Botspot/pi-apps#1898]
### What is the name of the app?

PyChess

### About the app

_PyChess is a gtk chess client, originally developed for GNOME, but running well under all other linux desktops. (Which we know of, at least). PyChess is 100% python code, from the top of the UI to the bottom of the chess engine, and all code is licensed under the GNU Public License.

The goal of PyChess is to provide an advanced chess client for linux following the GNOME Human Interface Guidelines. The client should be usable to those new to chess, who just want to play a short game and get back to their work, as well as those who wants to use the computer to further enhance their play._

https://pychess.github.io/
This is package-app.
[PyChess.zip](https://github.com/Botspot/pi-apps/files/8787072/PyChess.zip)

There is also a new release on GitHub which is workable (Debian 10/11 32bit). If you add this, you can take the deb from there.
https://github.com/pychess/pychess/releases/tag/1.0.3

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by Crilum** [comment]
@Rak1ta check out my [PR](https://github.com/Botspot/pi-apps/issues/1901), it installs the newer version from GitHub.

**Comment by Rak1ta** [comment]
@Crilum Yes, I wrote about her.  She worked for me on Buster/Bullseye 32bit.

**Comment by theofficialgman** [comment]
@Rak1ta we have app submissions as a issue template

> App Submission
> Submit/Upload an app to be added Pi Apps. For apps with a completed ZIP, install files, deb, or PR ONLY.

please use this format in the future for app submissions (such as this)

**Comment by theofficialgman** [comment]
https://github.com/Botspot/pi-apps/issues/185#issue-776095524

see special package app rules here ^. Pi-apps does not have any other puzzle games unique to its platform. There is no reason to include this as it has no alternative in the store. We aren't trying to make an apt alternative.

If we include some non-apt chess game and a great number of puzzle games in the future, then this can re-considered
