### ISSUE TITLE
[app request] Vivaldi Web browser thanks to @chunky-milk

### ISSUE THREAD

**Issue by Itai-Nelken** [Botspot/pi-apps#190]
[Vivaldi web browser.zip](https://github.com/Botspot/pi-apps/files/5761006/Vivaldi.web.browser.zip)
thanks to @chunky-milk https://discord.com/channels/770629697909424159/770629878319022090/795063789376503830

**Comment by Botspot** [comment]
Added to Pi-Apps with commit 581e3d2407aadea32672d971cb0bee69ae190ca9.

**Comment by fabianmendes** [comment]
Excuse me @Botspot, what screen video recorder do you use?

I didn't know where to ask you. I hope not bothering. Thanks

**Comment by Itai-Nelken** [comment]
> Excuse me @Botspot, what screen video recorder do you use?
> 
> I didn't know where to ask you. I hope not bothering. Thanks

I use SimpleScreenRecorder (`sudo apt install simplescreenrecorder`)

**Comment by Botspot** [comment]
> I didn't know where to ask you. I hope not bothering. Thanks

Oh you're fine. :)

> Excuse me @Botspot, what screen video recorder do you use?

I use `simplescreenrecorder` for videos, and use `raspi2png` for screenshots.

**Comment by fabianmendes** [comment]
Thanks! And what is the difference with the default Raspberry Pi Os'
screenshot?

 ~V. Fabian T· Mendes C.
