### ISSUE TITLE
Waveform Pro Free Trial

### ISSUE THREAD

**Issue by Crilum** [Botspot/pi-apps#1904]
### What is the name of the app?

Waveform Pro

### (Optional) Where is the app hosted?

https://www.tracktion.com/products/waveform-pro

### About the app

It's a trial of the Pro version of Waveform, of which we already have the Free version in Pi-Apps. Tracktion (the company who develops it) just released a new major version of Waveform Pro, and I wanted to make an app for the free trial, but since we already have Waveform Free, I wanted to ask if the free Trial of the Pro version would be added before I made the scripts.

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi. (Well, I'm not 100% sure, I haven't actually tried it, but since Waveform Free runs on the RPi, why not Waveform Pro?)

**Comment by Botspot** [comment]
I think it would be more optimal to include both versions under one app name, rather than having two apps on Pi-Apps.

**Comment by Crilum** [comment]
How would you do that? One is a trial, while the other is a full (albeit lesser) version.

**Comment by Botspot** [comment]
> How would you do that? One is a trial, while the other is a full (albeit lesser) version.

You could edit the existing app and either:
- Install both versions, or
- Ask the user which version they want to install

**Comment by Crilum** [comment]
> > How would you do that? One is a trial, while the other is a full (albeit lesser) version.
> 
> You could edit the existing app and either:

> * Install both versions, or

I don't think that would be a good solution.. It would take up a lot of extra space, and I don't think users would necessarily want both versions...
> * Ask the user which version they want to install

This would be better.. Maybe I'll look at changing the scripts.

**Comment by Crilum** [comment]
Closing for two reasons:

- I think Waveform (the non-Pro version) is fine, there's no need for the Pro version
- I just don't think I'll ever actually edit the scripts to include Waveform Pro
