### ISSUE TITLE
pi-apps is not responding

### ISSUE THREAD

**Issue by PGSCOM** [Botspot/pi-apps#1906]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [x] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)

### What happened?

The app cannot be opened

### Description

Today I tried to update pi-apps but when I clicked on the update tab before it loaded I gave configuration. Then the update tab appeared, it was closed, and the configuration tab was opened. I closed pi-apps and reopened it, and from that moment pi-apps was not responding. 

Then try to open it from the console but it did not emit anything, no error or warning. I put pi-apps in console and it was as if I just pressed enter.

My last attempt was to start the '/home/pi/pi-apps/updater' executable to update and it gave me this error.

### What is your operating system?

Twister OS in RPI4

### (Optional) Error log? Terminal output? Debug messages?

```bash
pi@raspberrypi:~/pi-apps $ '/home/pi/pi-apps/updater'
/home/pi/pi-apps/updater: línea 492: status: orden no encontrada
Checking for online changes... Done
/home/pi/pi-apps/updater: línea 172: list_apps: orden no encontrada
Scanning apps... Done
Scanning files... Done
/home/pi/pi-apps/updater: línea 629: status: orden no encontrada
pi@raspberrypi:~/pi-apps $
```

**Comment by PGSCOM** [comment]
Now I can't start pi-apps.

**Comment by Itai-Nelken** [comment]
It seems the `status` function is missing.

**Comment by theofficialgman** [comment]
```
/home/pi/pi-apps/updater: línea 172: list_apps: orden no encontrada
/home/pi/pi-apps/updater: línea 629: status: orden no encontrada
```
since you are missing two vital function from the api, my guess would be this is due to corruption of the api file or the sd card in general.

you best bet of restoring your install without uninstalling it to perform a forced 3-months update
```
rm -rf ~/pi-apps-forced-update
DIRECTORY=$HOME/pi-apps
git clone "$(cat "${DIRECTORY}/etc/git_url")" pi-apps-forced-update 1>&2 && \
cp -af "${DIRECTORY}/data" ~/pi-apps-forced-update && \
mv -f "$DIRECTORY" "${DIRECTORY}-3-months-old" && \
mv -f ~/pi-apps-forced-update "$DIRECTORY"
```
