### ISSUE TITLE
Is SteamLink available on arm64?

### ISSUE THREAD

**Issue by Rak1ta** [Botspot/pi-apps#1908]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)

### What happened?

SteamLink not installing on Raspberry Pi OS Debian 11 x64

### Description

When installing, it asks for dependencies, the usefulness of which I doubt. 32bit only?
![Безымянный](https://user-images.githubusercontent.com/88277343/170889735-7e1614b6-0752-44aa-8916-8527c7d94b17.png)

[install-fail-Steam Link.log](https://github.com/Botspot/pi-apps/files/8794213/install-fail-Steam.Link.log)

### What is your operating system?

RaspiOS 32bit Debian11 x64

**Comment by theofficialgman** [comment]
steam link is a proprietary build provided by steam (valve corporation) and is only available for armhf. they have not made a build for arm64

**Comment by Botspot** [comment]
Just for future reference...
Here was somebody's failed attempt to get steamlink running on pios 64-bit bookworm pi5.
https://forums.raspberrypi.com/viewtopic.php?p=2174716#p2174716
