### ISSUE TITLE
Adding Lightpad App To PiApps 

### ISSUE THREAD

**Issue by techcoder20** [Botspot/pi-apps#191]
[Lightpad.zip](https://github.com/Botspot/pi-apps/files/5761384/Lightpad.zip)

This zip file contains the install and uninstall scripts for the lightpad app.
Do I need to make a pull request ?

**Comment by Itai-Nelken** [comment]
>Do I need to make a pull request ?

@techcoder20 no, just wait for Botspot.

**Comment by Botspot** [comment]
Boy I wish I could stay up 24/7. ;)

ZIPs are better for me - they're easier to test out and collaborate on, I've found.

**Comment by Botspot** [comment]
> [Lightpad.zip](https://github.com/Botspot/pi-apps/files/5761384/Lightpad.zip)
> 
> This zip file contains the install and uninstall scripts for the lightpad app.

A couple tips:

- First, you shouldn't have to use `sudo` to remove a menu button from `~./local`. The script didn't use `sudo` to create the file, so it shouldn't need `sudo` to remove it.
- Next, I see that you're using an `armhf` deb file. Expect in a few limited cases, that means it will only work in 32-bit installations.  
So let's rename the installation script to `install-32`. @techcoder20 Do you know if Lightpad is installable on a 64-bit ARM OS? If so, let's create another file, `install-64`, to be used in such cases.

**Comment by Botspot** [comment]
[Lightpad.zip](https://github.com/Botspot/pi-apps/files/5762305/Lightpad.zip)  
@techcoder20 I haven't tested it yet, but here's a modified version of your zip that I went  ahead and made those changes for you.

**Comment by Botspot** [comment]
First bug:
```
Installing Lightpad with install-32 script
/home/pi/pi-apps/manage: line 135: /home/pi/pi-apps/apps/Lightpad/install-32: Permission denied

Failed to install Lightpad with install-32 script!
```
Looks like you forgot to make the install script executable! :)

**Comment by Itai-Nelken** [comment]
instead of installing the deb we can compile it, that way its also compatible with arm64,
[compile instructions](https://github.com/libredeb/lightpad#compilation)

**Comment by Botspot** [comment]
> instead of installing the deb we can compile it, that way its also compatible with arm64,
> [compile instructions](https://github.com/libredeb/lightpad#compilation)

Maybe for the 32-bit, we can use the deb file, and for the 64-bit we can compile it.

**Comment by Botspot** [comment]
> First bug:
> 
> ```
> Installing Lightpad with install-32 script
> /home/pi/pi-apps/manage: line 135: /home/pi/pi-apps/apps/Lightpad/install-32: Permission denied
> 
> Failed to install Lightpad with install-32 script!
> ```
> 
> Looks like you forgot to make the install script executable! :)

After making the script**s** executable, Lightpad works fine. I'll improve the description, then upload another zip.

**Comment by Itai-Nelken** [comment]
> > instead of installing the deb we can compile it, that way its also compatible with arm64,
> > [compile instructions](https://github.com/libredeb/lightpad#compilation)
> 
> Maybe for the 32-bit, we can use the deb file, and for the 64-bit we can compile it.

@Botspot create a arm64 deb, upload it to a repo, and use that.
### compilation instructions + package to deb:

```
sudo apt-get install meson ninja-build libgee-0.8-dev libgnome-menu-3-dev cdbs valac libvala-*-dev libglib2.0-dev libwnck-3-dev libgtk-3-dev xterm python3 python3-wheel python3-setuptools gnome-menus
```
```
git clone https://github.com/libredeb/lightpad.git
cd lightpad
meson build --prefix=/usr
cd build
ninja
```
package:
```
cd ..
dpkg-buildpackage -us -uc
```

**Comment by Botspot** [comment]
> @Botspot create a arm64 deb, upload it to a repo, and use that.

Sure I could, but it would be **one more thing to keep maintained**. Perhaps the Lightpad devs would be willing to add a ARM64 build to their releases? I'll ask.

**Comment by techcoder20** [comment]
I thought pi apps will make the scripts executable and run it. Sry

**Comment by techcoder20** [comment]
And for the arm 64 problem maybe we could make a script which compiles it until we have a proper Deb file ?

**Comment by Botspot** [comment]
Lightpad app added. Currently it's only 32-bit. This issue will stay open until a 64-bit **long-term solution** is worked out.

**Comment by Itai-Nelken** [comment]
@Botspot it needs to be added to the hidelist in TwisterOS as its already installed.

**Comment by techcoder20** [comment]
Maybe add a option for that in app builder

**Comment by Itai-Nelken** [comment]
> Maybe add a option for that in app builder

great idea! @Botspot is that possible?

**Comment by Botspot** [comment]
Turns out they do have a 64bit deb on the Ubuntu repository.

https://github.com/libredeb/lightpad/issues/15

**Comment by Itai-Nelken** [comment]
> Maybe add a option for that in app builder

@Botspot are you planning to do this? would be very useful in my opinion.

**Comment by techcoder20** [comment]
Gonna close this ticket as 64 bit lightpad has been added

**Comment by Botspot** [comment]
> > Maybe add a option for that in app builder
> 
> @Botspot are you planning to do this? would be very useful in my opinion.

@Itai-Nelken I'm working on a complete overhaul for Pi-Apps that includes a new hidelist mechanism. While it still probably won't be possible from the app creator to configure it, I figured you should know.
