### ISSUE TITLE
Gnome Builder (org.gnome.Builder) IDE

### ISSUE THREAD

**Issue by theofficialgman** [Botspot/pi-apps#1918]
### What is the name of the app?

org.gnome.Builder on flathub

### (Optional) Where is the app hosted?

https://flathub.org/apps/details/org.gnome.Builder

### About the app

I suggest installing via flatpak as this is the latest version using GTK4. You could install the version from apt but this is not the latest (uses ver 3.38 on bullseye and ver 3.30 on buster)

Do we think this is a good IDE to add to pi-apps would be the next question. I personally think its pretty nice and runs smooth.

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by Itai-Nelken** [comment]
It might have been a problem with the version of manjaro/kde I was running, but installing gnome builder from flatpak messed my fonts.

**Comment by Crilum** [comment]
I just installed it, and it works, and it hasn't mess up my fonts.

**Comment by Itai-Nelken** [comment]
It might have been a manjaro bug and it just happened to happen around the time I uninstalled it.
most likely not a bug with flatpak.
