### ISSUE TITLE
Wacup - Winamp Community Edition

### ISSUE THREAD

**Issue by ralf1307** [Botspot/pi-apps#192]
https://getwacup.com/

**Comment by Botspot** [comment]
Does this software run on Raspberry Pi?

**Comment by ralf1307** [comment]
It should be a x86 windows executable, so with box86 + wine: yes

**Comment by Botspot** [comment]
Wine + box86 can be hit-or-miss.

Has anyone actually tried it?

**Comment by Itai-Nelken** [comment]
I know real winamp runs fairly well. with box86+wine.

**Comment by Botspot** [comment]
OK, it worked fine for me.  
Let's wait for the WINE app to be added before making this app.

**Comment by techcoder20** [comment]
@Botspot I think we can add this app now that wine has been added

**Comment by Botspot** [comment]
I almost forgot about this. I made the app a while back.

Anyone want to try it?  
[WACUP (new WinAmp).zip](https://github.com/Botspot/pi-apps/files/6097986/WACUP.new.WinAmp.zip)

Also I'm not sure which category to put it in.

**Comment by Botspot** [comment]
Why wasn't this issue closed? Because I forgot about it.

WACUP has been on pi-apps for a while now with commit 5edd9ee7c747f0df8c4e409c57fb6d53f891d723.
