### ISSUE TITLE
 Wine64

### ISSUE THREAD

**Issue by ss8688** [Botspot/pi-apps#1921]
### What is the name of the app?

 Wine64

### (Optional) Where is the app hosted?

https://www.winehq.org/

### About the app

Wow64 on wine64 is working now，that means 32bit programs can work on wine64

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by Crilum** [comment]
There is already an issue for Wine64.. #807

**Comment by Crilum** [comment]
Also, you can just install Wine32 and Wine64, that's the way you're supposed to do it.
