### ISSUE TITLE
Can not install wine x86 on rasoberry pi os arm64

### ISSUE THREAD

**Issue by ss8688** [Botspot/pi-apps#1922]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)

### What happened?

No wine x86 in the app list

### Description

Wine64 5.x do not have Wow64, so wine x86 is need to run x86_32 progrom.
Box86 is working on arm64, So it could be possible to install wine x86 on arm64 systerm 

### What is your operating system?

rasoberry pi os arm64

**Comment by ss8688** [comment]
Another solution to run 32 bit code is updating wine64 to 7.0,which have Wow64.

**Comment by Crilum** [comment]
@Botspot why isn't Wine32 available for 64 bit systems? it works just fine. (I haven't tried installing Wine from Pi-Apps on 64-bit, but I have used 32 bit Wine on RPiOS 64-bit)

**Comment by ss8688** [comment]
> closing as duplicate #807
Not the same issue

**Comment by theofficialgman** [comment]
wine64 will include both x86 and x86_64 emulation. there is no need for a wine x86 on arm64

**Comment by Crilum** [comment]
@theofficialgman No, I don't think it does.. I installed it, and it said I needed to install Wine32..

**Comment by theofficialgman** [comment]
ah ok I thought that debians wine64 has a depend on wine32. regardless, these shouldn't be added as separate apps. wine32 and winde64 should be installed at once (and their versions matched)

I am used to winehq releases where winehq-stable does include both

**Comment by Crilum** [comment]
Yeah, I totaly agree.
