### ISSUE TITLE
Flow Browser

### ISSUE THREAD

**Issue by Botspot** [Botspot/pi-apps#193]
Interesting.  
https://www.raspberrypi.org/forums/viewtopic.php?f=62&t=296725  
https://www.theregister.com/2020/09/22/microsoft_edge_for_linux_october/  
https://support.ekioh.com/download/

**Comment by techcoder20** [comment]
Yes should we wait for a offical stable release or can we add the preview to pi apps ?

**Comment by Botspot** [comment]
After testing Flow and seeing that it fails to load many sites, I've decided it's too early to add it at this time.
