### ISSUE TITLE
Friday Night Funkin' Rewritten

### ISSUE THREAD

**Issue by AM7999** [Botspot/pi-apps#1934]
### What is the name of the app?

Friday Night Funkin' Rewritten

### (Optional) Where is the app hosted?

https://github.com/HTV04/funkin-rewritten

### About the app

Friday Night Funkin' Clone based on LÖVE 2d a 2d Game Engine

### Upload file or Add PR Link

[Friday Night Funkin' Rewritten.zip](https://github.com/Botspot/pi-apps/files/8818656/Friday.Night.Funkin.Rewritten.zip)

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by theofficialgman** [comment]
@AM7999 the uninstall is very dangerous
```
rm -rf ~/.love_games

rm -rf ~/.bin

rm ~/.local/share/applications/fnfr.desktop

rm -rf ~/.local/share/icons/FNFR
```
please only remove the FNFR files and nothing else. this will delete all programs in ~/.bin and ~/.love_games

**Comment by theofficialgman** [comment]
unable to run on bionic:
```
love $HOME/.love_games/friday_night_funkin_rewritten/funkin-rewritten.love
This game was made for a different version of LÖVE.
It may not be not be compatible with the running version (0.9.1).
Error: main.lua:76: attempt to call field 'getInfo' (a nil value)
stack traceback:
	(tail call): ?
	main.lua:76: in function 'load'
	[string "boot.lua"]:406: in function <[string "boot.lua"]:399>
	[C]: in function 'xpcall'
```
unable to run on bionic, which version of love is this application compatible with?

**Comment by theofficialgman** [comment]
also this concerns me...
```
Friday Night Funkin' Rewritten is licensed under the terms of the GNU General Public License v3, with the exception of most of the images, music, and sounds, which are proprietary. While FNF Rewritten's code is FOSS, use its assets at your own risk.
```

then I read this and was like, lol
```
Friday Night Funkin' is licensed under the [Apache License](https://en.wikipedia.org/wiki/Apache_License) 2.0, per the game's [license file](https://github.com/ninjamuffin99/Funkin/blob/master/LICENSE), and it is described as "fully open source" by its developers in the [readme file](https://github.com/ninjamuffin99/Funkin/blob/master/art/readme.txt) included with the game. However, the [repository's readme file](https://github.com/ninjamuffin99/Funkin/blob/master/README.md) states, "IF YOU MAKE A MOD AND DISTRIBUTE A MODIFIED / RECOMPILED VERSION, YOU MUST OPEN SOURCE YOUR MOD AS WELL", implying a [copyleft](https://en.wikipedia.org/wiki/Copyleft) requirement. From May to August 2021, the license file simply stated "if u make mods, open source them, lol!"; the Apache License 2.0 was used prior to May.
```

so I guess all is good and the rewrite in love by the community was just so that its easier to code in?

**Comment by theofficialgman** [comment]
anyway... once I built love 11.4 from source (it only took about 10 mintues), the game launches and works.

so I can edit your script in the future PR to include a building function if love 11.X is not available in the repos on a system

**Comment by AM7999** [comment]
Alright

**Comment by AM7999** [comment]
> @AM7999 the uninstall is very dangerous
> 
> ```
> rm -rf ~/.love_games
> 
> rm -rf ~/.bin
> 
> rm ~/.local/share/applications/fnfr.desktop
> 
> rm -rf ~/.local/share/icons/FNFR
> ```
> 
> please only remove the FNFR files and nothing else. this will delete all programs in ~/.bin and ~/.love_games

Ill try to fix this to make it not delete stuff there an just the files needed

**Comment by theofficialgman** [comment]
@AM7999 no need to do anything anymore. I've already covered it all in the PR referenced above

**Comment by AM7999** [comment]
Ah alright!
