### ISSUE TITLE
Krita - raster graphics editor

### ISSUE THREAD

**Issue by Rak1ta** [Botspot/pi-apps#1937]
### What is the name of the app?

Krita

### (Optional) Where is the app hosted?

https://krita.org/en/

Available on flathub: https://flathub.org/apps/details/org.kde.krita
`flatpak install flathub org.kde.krita`
Checked on: RaspiOS 32bit Debian10

**armhf** version 4.1.5: 11-10-2018
### About the app

Krita is a free and open-source raster graphics editor designed primarily for digital painting and 2D animation. The software runs on Windows, macOS, Linux, Android, and Chrome OS, and features an OpenGL-accelerated canvas, colour management support, an advanced brush engine, non-destructive layers and masks, group-based layer management, vector artwork support, and switchable customisation profiles.

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by ryanfortner** [comment]
Krita is already in the Debian repositories. Shouldn’t we just use that instead of the flatpak?

**Comment by Rak1ta** [comment]
@ryanfortner 
```
pi@raspberrypi:~ $ sudo apt install krita
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package krita is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'krita' has no installation candidate
```
http://raspbian.raspberrypi.org/raspbian/pool/main/k/krita/

**Comment by theofficialgman** [comment]
> @ryanfortner
> 
> ```
> pi@raspberrypi:~ $ sudo apt install krita
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> Package krita is not available, but is referred to by another package.
> This may mean that the package is missing, has been obsoleted, or
> is only available from another source
> 
> E: Package 'krita' has no installation candidate
> ```
> 
> http://raspbian.raspberrypi.org/raspbian/pool/main/k/krita/

its not in raspbian buster, bullseye, or stretch @Rak1ta you have linked to the main pool which includes all raspbian releases.

I'm not sure which raspbian release it is in, but its in none of those. it might even be just a broken package

it is in the debian official repos as ryanfortner pointed out BUT for ARM64 only, no armhf deb.

so this will probably say an ARM64 only app, whether that be through the deb or flatpak

**Comment by Rak1ta** [comment]
> ARM64 only app

> flatpak install flathub org.kde.krita
Checked on: RaspiOS 32bit Debian10

**Comment by theofficialgman** [comment]
flatpak is ARM64.. all flatpaks are now. there is no support for armhf in flatpak since about 1-2 years ago or so

**Comment by Crilum** [comment]
> flatpak is ARM64.. all flatpaks are now. there is no support for armhf in flatpak since about 1-2 years ago or so

Actually, I _believe_ (not totally sure) that Flatpak itself still supports arm32 packages, but Flathub stopped building them because the server costs were too high.

**Comment by theofficialgman** [comment]
> Actually, I _believe_ (not totally sure) that Flatpak itself still supports arm32 packages, but Flathub stopped building them because the server costs were too high.

flatpak, the format, is still arm32 compatible, yes. however, all the runtimes (gnome and everything based on it, and freedesktop and everything based on it) have decided to not build for arm32 anymore

**Comment by virat2010** [comment]
would love to see it.

**Comment by cruncher12** [comment]
I personally use Krita. I can confirm that a Flatpak installation of Krita does indeed work for me at least. Having Krita as part of pi-apps would be nice IMO.

**Comment by Rak1ta** [comment]
This proposal was implemented in https://github.com/Botspot/pi-apps/issues/2314 .
