### ISSUE TITLE
Kivy 

### ISSUE THREAD

**Issue by techcoder20** [Botspot/pi-apps#194]
Can we add [kivy](https://kivy.org/#home) to pi apps. I know its just a python library but installing it on RPi is kind of hard

**Comment by techcoder20** [comment]
```
#!/bin/bash

#Updating System
sudo apt update

#Installing Dependencies
sudo apt -y install python3-setuptools git-core python3-dev libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev pkg-config libgl1-mesa-dev libgles2-mesa-dev \
   libgstreamer1.0-dev \
   gstreamer1.0-plugins-{bad,base,good,ugly} \
   gstreamer1.0-{omx,alsa} libmtdev-dev \
   xclip xsel libjpeg-dev 


#Installing virtualenv with pip
python3 -m pip install --upgrade pip setuptools virtualenv

#Creating Virtual Environment
python3 -m virtualenv ~/kivy_venv

#Activating the virtual environment
source ~/kivy_venv/bin/activate

#Installing kivy with pip
python3 -m pip install kivy[base] kivy_examples

#Running example program
python3 ~/kivy_venv/share/kivy-examples/demo/showcase/main.py
```
These commands should  install it. If i get the approval I can make the script :)

**Comment by Botspot** [comment]
I'm afraid that not enough GUI users, like our "a guy", would be interested in this.

Tell you what: Make your app, and make a one-line command that adds your app to the user's local Pi-Apps folder.

**Comment by techcoder20** [comment]
Hmmm okay don't see the point of adding it to pi apps if the script is already there. Could just run the script. Anyways thx ☺️
