### ISSUE TITLE
Testdisk [CLI]

### ISSUE THREAD

**Issue by GYKgamer** [Botspot/pi-apps#1941]
### What is the name of the app?

Testdisk

### (Optional) Where is the app hosted?

Hosted in the god that is "apt"

### About the app

Helps you recover deleted files and is pretty easy. It is a cli based app.

### Upload file or Add PR Link

Sudo apt install Testdisk

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by GYKgamer** [comment]
Also here's a tutorial https://itsfoss.com/recover-deleted-files-linux/

**Comment by theofficialgman** [comment]
https://github.com/Botspot/pi-apps/issues/185#issue-776095524

see special package app rules here ^, as well as GUI "easy to use" as a priority.
