### ISSUE TITLE
Please add this to pi apps

### ISSUE THREAD

**Issue by MIT-Department-of-Security** [Botspot/pi-apps#1947]
### What is the name of the app?

Hackering

### (Optional) Where is the app hosted?

https://github.com/MIT-Department-of-Security/Hackering

### About the app

This app can be used by admins to discover weak passwords.

### Upload file or Add PR Link

[Hackering-Normal_release.zip](https://github.com/Botspot/pi-apps/files/8839668/Hackering-Normal_release.zip)

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by MIT-Department-of-Security** [comment]
you need to install wine first

**Comment by Crilum** [comment]
This is probably Malware:
![hackeringmalware](https://user-images.githubusercontent.com/91354257/172226297-e416035b-5e1e-4f56-9569-5cd6fd2f09ee.png)

**Comment by Botspot** [comment]
User @MIT-Department-of-Security has been blocked on all Botspot repos.

For future reference, I would not recommend trying to extract suspicious archives. It could have been a [zip bomb](https://en.wikipedia.org/wiki/Zip_bomb). Instead, find an online free extraction service and use that.
