### ISSUE TITLE
Please add this pro app to pi apps

### ISSUE THREAD

**Issue by MIT-Department-of-Security** [Botspot/pi-apps#1948]
### What is the name of the app?

S7ZIP

### (Optional) Where is the app hosted?

https://github.com/MIT-Department-of-Security/S7ZIP

### About the app

This is a modified version of 7zip. It's got new major compatibility updates. And new features are here such as lock the zip with Windows Hello. Or merge multiple ZIP files together.

NOTICE: The program is license free. You can modify it. But please don't use it in Enterprise. It took long time to code it. The program is also free of viruses

### Upload file or Add PR Link

[S7ZIP-main.zip](https://github.com/Botspot/pi-apps/files/8839723/S7ZIP-main.zip)

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by MIT-Department-of-Security** [comment]
You need to install wine first

**Comment by theofficialgman** [comment]
@MIT-Department-of-Security Hi, I am one of the maintainers of pi-apps. I'm not sure if I actually believe you are from MIT (I'm assuming that is the Massachusetts Institute of Technology).

Can you care to explain why you have just created this account (Joined 10 hours ago) as well as just made these repos.

Pi-Apps isn't software for anyone to upload their personal projects to without any benefit to normal GUI users https://github.com/Botspot/pi-apps/issues/185

that goes for this request as well as https://github.com/Botspot/pi-apps/issues/1947

**Comment by Crilum** [comment]
This also looks a little sus: `You can run this program in Windows easily, by running it as an admin.`
from the `!!README!!` file in https://github.com/MIT-Department-of-Security/S7ZIP/blob/main/S7ZIP-main.7z

Why do you need admin access just to compress and uncompress files?

**Comment by Crilum** [comment]
This is definintely Malware:
![s7zipmalware](https://user-images.githubusercontent.com/91354257/172226721-8f95d5e0-53f7-4619-a5e1-83e8b9123558.png)

**Comment by Itai-Nelken** [comment]
I have reported @MIT-Department-of-Security to github for trying to add malware to pi-apps.

**Comment by Botspot** [comment]
> This is definintely Malware: ![s7zipmalware](https://user-images.githubusercontent.com/91354257/172226721-8f95d5e0-53f7-4619-a5e1-83e8b9123558.png)

@Crilum Be sure to delete your Wine prefix after that. Setting the current directory will not change the default $WINEPREFIX, which is ~/.wine.

**Comment by Botspot** [comment]
User @MIT-Department-of-Security has been blocked on all Botspot repos.

For future reference, I would not recommend trying to extract suspicious archives. It could have been a [zip bomb](https://en.wikipedia.org/wiki/Zip_bomb). Instead, find an online free extraction service and use that.

**Comment by everypizza1** [comment]
This thread should be deleted.
![Screenshot_20230715-171912](https://github.com/Botspot/pi-apps/assets/82726593/083ae47b-c111-4f43-b32f-adf6283b2cd3)

**Comment by Crilum** [comment]
> This thread should be deleted.

Probably true. We have already proven that it's malware :joy:

**Comment by Botspot** [comment]
I think this is a fun piece of history on our repo that does not need to be deleted. Early on when I was building pi-apps from scratch, I thought of ways to evaluate its success, and one of those ways was to see it become a big enough target for someone to try to add malware to it. 🤣

**Comment by everypizza1** [comment]
Is there a way to report the malicious repository hosting the original?

**Comment by Botspot** [comment]
> Is there a way to report the malicious repository hosting the original?

Good idea. There is a "Report repository" button, so I've submitted the form now. It would probably not be necessary or useful for multiple people to all do it, so it's up to Github at this point.

**Comment by everypizza1** [comment]
Thanks.
