### ISSUE TITLE
Can't run pi apps x86

### ISSUE THREAD

**Issue by noars902** [Botspot/pi-apps#1949]
i can't run pi apps x86. it show this massage.

# Option “-x” is deprecated and might be removed in a later version of gnome-terminal.
# Use “-- ” to terminate the options and put the command line to execute after it.
./gui1: line 267: {DIRECTORY}/data/settings/App List Style: No such file or directory
xlunch failed to compile!

**Comment by Itai-Nelken** [comment]
Open this issue at the pi-apps x86 repo please.
This is the original arm version repo, we don't maintain the x86 version.
