### ISSUE TITLE
Q: How to (programmatically) see what apps are installed?

### ISSUE THREAD

**Issue by nikoloiz** [Botspot/pi-apps#1964]
Hi!
I have recently been experimenting with distro-hopping but am finding it frustrating having to individually re-install every app so I decided to write a script that:
1. Finds all the apps installed from pi-apps
2. Notes them into a file
3. When opened on another system, the file can be uploaded and the script uses Pi-Apps CLI to install them.

I remember a few months ago while exploring the ~/pi-apps folder, I saw an 'installed.txt' file for every app which said whether it was installed or not: but I can't find it anymore!

Can anybody help/is there any other way to find which apps are installed?

**Comment by Crilum** [comment]
Did you figure it out?
The `pi-apps` directory has a folder called `data`, which contains a status `folder`, which contains a file for every app installed, uninstalled, or corrupted:
![dataFlder](https://user-images.githubusercontent.com/91354257/173251125-94abc3ad-042c-47c2-9cfa-267e772308ab.png)

Note: Pi-Apps generates the `data` folder, so you won't find it until you run Pi-Apps once.

**Comment by Jai-JAP** [comment]
@nikoloiz running `grep "installed" ./*` in the pi-apps/data/status folder gives installed apps
replace `installed` with `uninstalled` or `corrupt` to list apps in the corresponding status
