### ISSUE TITLE
WeChat(Wine64 on arm64)

### ISSUE THREAD

**Issue by liulysunix** [Botspot/pi-apps#1968]
### What is the name of the app?

WeChat(Wine64)

### (Optional) Where is the app hosted?

github

### About the app

WeChat on My Wine64_86.https://github.com/Botspot/pi-apps/issues/1966

### Upload file or Add PR Link

[WeChat(Wine64).zip](https://github.com/Botspot/pi-apps/files/8885560/WeChat.Wine64.zip)
Use my Wine(x64)

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by liulysunix** [comment]
[WeChat(Wine64).zip](https://github.com/Botspot/pi-apps/files/8885663/WeChat.Wine64.zip)
new

**Comment by theofficialgman** [comment]
closing as this does not work at all and does not follow pi-apps coding standards. wechat can be access from browser as well and may be removed entirely

please create scripts in the install format and do not place arbitrary files in the app folder
