### ISSUE TITLE
Panther launcher

### ISSUE THREAD

**Issue by techcoder20** [Botspot/pi-apps#197]
Panther launcher is a cool alternative to the default applications menu in RPi OS. It looks like  

![screenshot](https://raw.githubusercontent.com/phoenixbyrd/panther_launcher/master/desktop3.png)

These are the installation commands:

```
#!/bin/bash 

sudo apt install -y libatk1.0-dev libglib2.0-dev libcairo2-dev libgtk-3-dev libpango1.0-dev libgdk-pixbuf2.0-dev libgee-0.8-dev libglib2.0-dev json-glib-tools libgnome-menu-3-dev libsoup2.4-dev libx11-dev cmake gettext pkg-config gcc make gnome-icon-theme valac-0.26 libjson-glib-dev libpanel-applet-dev libmate-panel-applet-dev


#Removing Repositoty if already cloned
sudo rm -r ~/panther_launcher

#Cloning Repository
git clone https://github.com/phoenixbyrd/panther_launcher.git ~/

#Changing Directory
cd ~/panther_launcher

#Removing Install directory if already created
sudo rm -r ~/install

#Creating Install Directory
mkdir install

#Changing Directory
cd install

#Building panther launcher
cmake .. -DCMAKE_INSTALL_PREFIX=/usr
make
sudo make install
```

The only one thing i am not sure how to do is how to add it to lxpanel. What I do is create a desktop shorcut and add it lxpanel with the applications launcher applet. To add this in the bash script I can either replace the lxpanel file but the problem with that is the users configurations will be gone. If we want to edit the config files with sed all the applets have a specific format so if i use the sed command to remove a specific applet it will remove all the applets. Any ideas on how to do that ?

**Comment by Botspot** [comment]
After having both Ulauncher AND Lightpad in Pi-Apps, is there still a use-case for Panther launcher?

**Comment by techcoder20** [comment]
hmmm your right :+1:
