### ISSUE TITLE
Install button broken

### ISSUE THREAD

**Issue by tedmakesstuff** [Botspot/pi-apps#1970]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [ ] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)

### What happened?

Install button doesn't work

### Description

If I press the install button on ANY app, it wont work.

### What is your operating system?

Raspberry Pi OS Bullseye armhf with KDE Plasma

**Comment by tedmakesstuff** [comment]
I should also mention I tried adding a map, and running the script also didn't work, so I'm unsure if my install scripts work. (I'm new to bash and stuff)

**Comment by theofficialgman** [comment]
if this is your first time running pi-apps, make sure that you actually properly installed it by running this script
https://github.com/Botspot/pi-apps#install-pi-apps

if you attempted to install via some other method, please list is here now

**Comment by tedmakesstuff** [comment]
I had it installed since I got my Pi, just recently I installed plasma (I was using  the default desktop before).

**Comment by tedmakesstuff** [comment]
Okay, I did a clean re-install of Pi Apps, and it still doesn't work. I ran it through the terminal, and when I tried to install an app, I got this:
![image](https://user-images.githubusercontent.com/66563283/173573917-6d3d6152-2f8c-4c74-8cdc-ef839751e12e.png)
(I pressed the button twice since it appeared twice since I clicked a bunch of times)

**Comment by cycool29** [comment]
What terminal are you using? Looks like pi-apps is unable to detect your terminal.

**Comment by Botspot** [comment]
> Okay, I did a clean re-install of Pi Apps, and it still doesn't work. I ran it through the terminal, and when I tried to install an app, I got this: ![image](https://user-images.githubusercontent.com/66563283/173573917-6d3d6152-2f8c-4c74-8cdc-ef839751e12e.png)

Perfect! That's what error messages are for.

@tedmakesstuff, let's find what terminal you have installed. To do that, please run this command:
```
readlink -f "$(command -v x-terminal-emulator)")"
```

**Comment by Botspot** [comment]
@tedmakesstuff, could you also run this command?
```
DEBUG=1 ~/pi-apps/etc/terminal-run
```
This will tell us which terminal the terminal-run script decided to use. On my system, the output is "`Using lxterminal from x-terminal-emulator`"

**Comment by tedmakesstuff** [comment]
I ran it, and it says no terminal detected, I'm assuming some bug in the code doesn't start a terminal at all, as nothing pops up.

**Comment by tedmakesstuff** [comment]
I also ran this, 
![image](https://user-images.githubusercontent.com/66563283/174138918-da84a03b-96e7-4593-bafa-95c347c45d34.png)
(i didnt see the comment above,)
and this
![image](https://user-images.githubusercontent.com/66563283/174139030-161389ad-230a-45c6-90a3-c139b4f05db8.png)

**Comment by theofficialgman** [comment]
@tedmakesstuff run these
```
which gnome-terminal
which gnome-terminal.wrapper
```

**Comment by tedmakesstuff** [comment]
@theofficialgman 
ok, here's the output
![image](https://user-images.githubusercontent.com/66563283/174139330-74e1b5d2-d8ec-48dd-b201-a861a9a73494.png)

**Comment by theofficialgman** [comment]
> @theofficialgman ok, here's the output ![image](https://user-images.githubusercontent.com/66563283/174139330-74e1b5d2-d8ec-48dd-b201-a861a9a73494.png) edit: btw I'm using LXTerminal (which I'm pretty sure is the terminal that comes with the pi)

doesn't matter. your default terminal is gnome-terminal.wrapper

```
gnome-terminal -x bash -c "echo 'this a test'; sleep 10"
```

**Comment by tedmakesstuff** [comment]
okay now I see. that terminal is broken, when pi apps tries to access it, it shows the same garbage that it showed when I ran that.
![image](https://user-images.githubusercontent.com/66563283/174139892-87a163ca-ff28-4ee1-a9c8-d5ee8a8348fc.png)
and a thing to note: my system & KDE Plasma is in Greek, so that changes terminal outputs a bit.

**Comment by theofficialgman** [comment]
set it to english temporarily for me and run it again
```
export LANG="en_US.UTF-8"
export LANGUAGE="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"
gnome-terminal -x bash -c "echo 'this a test'; sleep 10"
  ```

**Comment by tedmakesstuff** [comment]
okay, will do, also im pretty sure gnome terminal DOESN'T exist.. i think its supposed to be a folder, but i went to /usr/bin and found nothing

**Comment by tedmakesstuff** [comment]
i think i just need to change my default terminal

**Comment by theofficialgman** [comment]
no it looks like it exists
```
ls -l /usr/bin/gnome-terminal
```

**Comment by tedmakesstuff** [comment]
> set it to english temporarily for me and run it again
> 
> ```
> export LANG="en_US.UTF-8"
> export LANGUAGE="en_US.UTF-8"
> export LC_ALL="en_US.UTF-8"
> gnome-terminal -x bash -c "echo 'this a test'; sleep 10"
> ```
> 
> this isn't a pi-apps issue btw.. it appears that your gnome-terminal (your default selected terminal emulator) is broken or missing something

im new to linux, but i dont understand why they are called "Terminal Emulators" and not just "Terminal"

**Comment by tedmakesstuff** [comment]
I changed it through raspberry pi's menu. Now it makes a lot more sense, I'm assuming the Terminal wasn't property translated (at least the errors)
![image](https://user-images.githubusercontent.com/66563283/174141095-121003cb-8fc1-47e2-b710-4edb3d57fb66.png)

**Comment by tedmakesstuff** [comment]
![image](https://user-images.githubusercontent.com/66563283/174141698-53bb2a1b-7506-4c0f-8a32-b183a39b5680.png)
uhh...

**Comment by tedmakesstuff** [comment]
I don't know if any programs rely on gnome-terminal

**Comment by theofficialgman** [comment]
when you go to uninstall, you will see a list of programs that get uninstalled alongside it

**Comment by tedmakesstuff** [comment]
![image](https://user-images.githubusercontent.com/66563283/174142220-a4869aa0-ff25-40ca-9ab9-c0db7e7e83b2.png)
is this what it should output?

**Comment by theofficialgman** [comment]
yeah you uninstalled it, thats fine. now konsole is your default xterminal emulator. see it has been changed to that in the log

you can start up pi-apps normally now, it probably works

**Comment by tedmakesstuff** [comment]
works, it fell back to Konsole (which has rendering issues)

**Comment by tedmakesstuff** [comment]
btw, i will if i need to make a new issue, but why doesn't Minecraft pi edition modded not install? i says it cant write to
`/home/pi/.local/bin`

**Comment by theofficialgman** [comment]
you can always manually set the terminal emulator
```
sudo update-alternatives --config x-terminal-emulator
```
but rendering issue are outside of pi-apps control. I assuming you mean there are graphical issues

**Comment by tedmakesstuff** [comment]
@theofficialgman well what i meant is, when i press space it adds invis chars and makes the cursor go farther each time

**Comment by theofficialgman** [comment]
> btw, i will if i need to make a new issue, but why doesn't Minecraft pi edition modded not install? it says it cant write to `/home/pi/.local/bin`

a previous bug with PiKiss messed up permissions for users /home/pi/.local folder and made it root owned (which it should not be)

**Comment by tedmakesstuff** [comment]
how come i can access it then?

**Comment by theofficialgman** [comment]
> @theofficialgman well what i meant is, when i press space it adds invis chars and makes the cursor go farther each time

😆 thats literally what is supposed to happen....

**Comment by tedmakesstuff** [comment]
![image](https://user-images.githubusercontent.com/66563283/174143002-fdf56635-f1ba-4655-849e-1d77bab6ead6.png)

u cant see it but, even though the cursor is there, if i type it wont type it there,

**Comment by tedmakesstuff** [comment]
well, since pi apps is fixed, I'm closing the issue. thank you for helping me fix it.

**Comment by theofficialgman** [comment]
> ![image](https://user-images.githubusercontent.com/66563283/174143002-fdf56635-f1ba-4655-849e-1d77bab6ead6.png)
> 
> u cant see it but, even though the cursor is there, if i type it wont type it there,

ah I understand now... probably something to report to the piOS devs, or KDE devs
nothing you can do about it as a user.



> how come i can access it then?

its all root owned, you can read it, but not write it
https://github.com/Botspot/pi-apps/issues/1970#issuecomment-1158017119

we can't manually fix this issue
what are the contents of your folder:
```
ls -R ~/.local/
```
(if you have a lot of programs installed... this could be very long)

**Comment by tedmakesstuff** [comment]
it has bin, lib and share

**Comment by theofficialgman** [comment]
run the actual command and send the output

**Comment by tedmakesstuff** [comment]
well i had made a game that used love2d, so it wrote there on the share folder the high score

**Comment by tedmakesstuff** [comment]
its probably 5 million lines long, so i wont send the output.

**Comment by tedmakesstuff** [comment]
I'm assuming not... if so then something is wrong with my pi. my game actually saved a new high score (which is why i took long to respond)

**Comment by tedmakesstuff** [comment]
I JUST REALIZD WHATEVER PI APPS IS INSTALLING, ITS COMPILING STUFF SO IL RESPOND IN A BIT WHEN IT FNISHES

**Comment by tedmakesstuff** [comment]
things still compiling
everything BUT pikiss is root root, else is pi pi

**Comment by tedmakesstuff** [comment]
the bin folder says theres a pikiss-gui folder, with root root permissions
![image](https://user-images.githubusercontent.com/66563283/174147628-862bdf51-2c88-4ef8-ae53-e082eacf1c98.png)

**Comment by tedmakesstuff** [comment]
![image](https://user-images.githubusercontent.com/66563283/174147943-bed7236a-2104-4a0c-9fb3-b6470bb34576.png)

**Comment by theofficialgman** [comment]
share this result. the other files themselves look fine
```
ls -l ~/.local
```

**Comment by tedmakesstuff** [comment]
![Uploading image.png…]()
this says what i just said.

**Comment by theofficialgman** [comment]
ah there we go, so just the bin folder itself is messed up
easy fix
```
sudo chown $USER:$USER ~/.local/bin
```

**Comment by tedmakesstuff** [comment]
thank you! i ran the command again and it says pi pi now.

**Comment by tedmakesstuff** [comment]
i mean that 1 pi kiss gui file, was root ownerd

**Comment by tedmakesstuff** [comment]
ok i am able to launch it from terminal

**Comment by theofficialgman** [comment]
> ok now i cant open pi apps, it says i dont have permissions to do so

wdym? we didn't change anything to do with launching pi-apps

**Comment by theofficialgman** [comment]
> i mean that 1 pi kiss gui file, was root ownerd

yeah it shouldn't be either... but I'll leave that to pikiss to clean up

**Comment by theofficialgman** [comment]
> looking at the terminal, it makes sense why it wouldn't install, it tries to put an appimage to .local/bin/ also @theofficialgman its most likely to do with plasma, as i am able to run it from the terminal.

doubtful, you launch it how? via the desktop or via the apps list?

**Comment by tedmakesstuff** [comment]
both are broken. the desktop broke long before the app list though.

**Comment by theofficialgman** [comment]
what is the error? screenshot

**Comment by tedmakesstuff** [comment]
its a notification in greek
![image](https://user-images.githubusercontent.com/66563283/174149714-9b9c81c7-5628-4bf1-aa3f-3c07d092754a.png)

**Comment by theofficialgman** [comment]
```
ls -l $HOME/.local/share/applications/pi-apps.desktop
ls -l $HOME/Desktop/pi-apps.desktop
```

**Comment by tedmakesstuff** [comment]
it says that doesn't exist

**Comment by theofficialgman** [comment]
for which one? those are the locations of the .desktop files which correspond to the pi-apps icons

**Comment by tedmakesstuff** [comment]
i made a shortcut, btw theres no icon in the shortcut, or a name.
![image](https://user-images.githubusercontent.com/66563283/174150284-72700849-c86c-4903-ba9c-e01aa5a39f0d.png)

**Comment by tedmakesstuff** [comment]
btw that was the 2nd command
![image](https://user-images.githubusercontent.com/66563283/174150327-2cc80ea4-1496-4117-9d24-7cd928bc7861.png)

**Comment by theofficialgman** [comment]
I would say you probably broke the shortcut not pi-apps

just delete them and re-run the install command. it will skip installation but fix the icons

```
rm -f $HOME/.local/share/applications/pi-apps.desktop $HOME/Desktop/pi-apps.desktop
wget -qO- https://raw.githubusercontent.com/Botspot/pi-apps/master/install | bash
```

**Comment by tedmakesstuff** [comment]
the desktop shortcut still doesn't work, but i dont really care, though the app list icon is fixed.

**Comment by tedmakesstuff** [comment]
![image](https://user-images.githubusercontent.com/66563283/174150913-f1288e68-c40a-4a67-a6db-9beabeb7db96.png)
what the actual truck..
it says i dont have permissions for trash

**Comment by theofficialgman** [comment]
future users will now see a dialog prompt telling them that terminal-run has encountered a fatal error in addition to getting this in the hidden terminal log https://github.com/Botspot/pi-apps/issues/1970#issuecomment-1155100073

no other users will be left wondering why the install/uninstall buttons don't work if their terminal is broken

**Comment by Botspot** [comment]
> @Botspot looks like the pikiss error might have only caused the bin folder itself to be root owned, not the files in ~/.local/bin which is good. its perfectly safe to run this and change it back to the user ownership with a runonce

[Done.](https://github.com/Botspot/pi-apps/commit/c594d06adb036cf53a0352e8c4a7885958dcbf40)
