### ISSUE TITLE
Junk file in home directory

### ISSUE THREAD

**Issue by Rak1ta** [Botspot/pi-apps#1979]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)

### What happened?

Junk file in home directory

### Description

This is a text document. It began to appear when updating applications/and at the end of the update.
![Безымянный](https://user-images.githubusercontent.com/88277343/173932532-c0357c1c-e238-4c81-b7cf-1f527e89e034.png)

### What is your operating system?

RaspiOS 32bit Debian10

**Comment by theofficialgman** [comment]
@Botspot you know how you were impressed of the `2&>/dev/null` ?
turns out that doesn't work the way I thought 😆

**Comment by theofficialgman** [comment]
fixed, sorry about that. I accidentally recently introduced that.

after updating, you will not have that file generate anymore
