### ISSUE TITLE
Cawbird url for Buster is 404

### ISSUE THREAD

**Issue by Botspot** [Botspot/pi-apps#1985]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)

### What happened?

Cawbird url for Buster is 404

### Description

Thanks to @enemy88#5283 on the TwisterOS Discord server for reporting this.

### What is your operating system?

buster

### (Optional) Error log? Terminal output? Debug messages?

```bash
wget https://downloadcontent.opensuse.org/repositories/home:/IBBoard:/cawbird/Raspbian_10/armhf/repositories/home:/IBBoard:/cawbird/Raspbian_10/armhf/cawbird_1.5-1+3.11_armhf.deb
--2022-06-16 21:31:35--  https://downloadcontent.opensuse.org/repositories/home:/IBBoard:/cawbird/Raspbian_10/armhf/repositories/home:/IBBoard:/cawbird/Raspbian_10/armhf/cawbird_1.5-1+3.11_armhf.deb
Resolving downloadcontent.opensuse.org (downloadcontent.opensuse.org)... 2001:67c:2178:8::27, 195.135.221.157
Connecting to downloadcontent.opensuse.org (downloadcontent.opensuse.org)|2001:67c:2178:8::27|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-06-16 21:31:36 ERROR 404: Not Found.
```

**Comment by Botspot** [comment]
Pinging @theofficialgman due to commit https://github.com/Botspot/pi-apps/commit/50591953068b2d824db62c5f54541af293cb8f7c, and @cycool29 for opening the original pull request.

I'm not sure if this is a typo in the URL, or if opensuse took their old release down.

**Comment by theofficialgman** [comment]
the script is simple and it is impossible to get the URL you attempted to download with wget
```


#!/bin/bash

# buster version number
version=1.5-1+3.11
# bullseye version number
version2=1.5-1+3.5
# ubuntu focal version number
version3=1.5-1+3.1

if [[ $(get_codename) == "buster" ]]; then
  use_version="$version"
  release="Raspbian_10"
elif [[ $(get_codename) == "bullseye" ]]; then
  use_version="$version2"
  release="Debian_11"
elif [[ $(get_codename) == "focal" ]]; then
  use_version="$version3"
  release="xUbuntu_20.04"
else
  warning "OS unknown, defaulting to raspbian buster packages"
  use_version="$version"
  release="Raspbian_10"
fi

install_packages https://download.opensuse.org/repositories/home:/IBBoard:/cawbird/${release}/armhf/cawbird_${use_version}_armhf.deb gstreamer1.0-libav || exit 1
```
so what is the actual URL from their log?

**Comment by theofficialgman** [comment]
I see the post now... you made a bad copy of their URL

https://discord.com/channels/670543161525010442/773003751329103914/986342070597865502

it actually was
```
https://download.opensuse.org/repositories/home:/IBBoard:/cawbird/Raspbian_10/armhf/cawbird_1.5-1+3.11_armhf.deb
```
which downloads just fine

closing as no issue
