### ISSUE TITLE
Teamviewer Client and Host

### ISSUE THREAD

**Issue by GYKgamer** [Botspot/pi-apps#1988]
### What is the name of the app?

Teamviewer Client and Host

### (Optional) Where is the app hosted?

https://www.teamviewer.com/en/download/raspberry-pi/

### About the app

Teamviewer Host
![image](https://user-images.githubusercontent.com/41442793/174435218-e10c93c1-94af-43b3-880e-31cd782308ca.png)

Teamviewer (which is a hidden deb with both the host and client)
![image](https://user-images.githubusercontent.com/41442793/174435278-7f806b3c-ccb4-4840-9488-207ebcfd646d.png)

### Upload file or Add PR Link

https://download.teamviewer.com/download/linux/teamviewer_armhf.deb
https://download.teamviewer.com/download/linux/teamviewer_arm64.deb

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by theofficialgman** [comment]
@GYKgamer where is this deb from? the website is teamviewer host which is what our current script is

**Comment by GYKgamer** [comment]
> @GYKgamer where is this deb from? the website is teamviewer host version 14, the latest released version, which is what our current script is
The website, the current version is 14

**Comment by theofficialgman** [comment]
closing as the current deb for teamviewer host in pi-apps is the 15.30.3 version

```
Package: teamviewer-host
Maintainer: TeamViewer Germany GmbH <service@teamviewer.com>
Homepage: http://www.teamviewer.com
Version: 15.30.3
```

**Comment by GYKgamer** [comment]
Wait but Teamviewer Preview is different

**Comment by GYKgamer** [comment]
Host only lets you connect to the raspberry pi

**Comment by GYKgamer** [comment]
Preview lets you connect to and from the raspberry pi

**Comment by theofficialgman** [comment]
preview is the name given by the next version. when 14 was stable, 15 was called next. 15.30.3 has been released and is what the pi-apps script links to. it is not different.

**Comment by theofficialgman** [comment]
nevermind. I see what you are pointing to. there is a hidden link to teamviewer host and client for the pi.

we should migrate all users to this instead of teamviewer host @Botspot 
old link, host only:
```
https://download.teamviewer.com/download/linux/teamviewer-host_armhf.deb
```
new link, host and client:
```
https://download.teamviewer.com/download/linux/teamviewer_armhf.deb
```

**Comment by theofficialgman** [comment]
@GYKgamer I have edited your post. don't link to unofficial sources when there is an official source of the deb available

**Comment by theofficialgman** [comment]
the hidden deb is also available for arm64
```
https://download.teamviewer.com/download/linux/teamviewer_arm64.deb
```

**Comment by theofficialgman** [comment]
I'm amazed... it works on switch as well and with wayland. both directions
this is great

**Comment by Botspot** [comment]
Wow. This will be much easier than giving other people the credentials to my RealVNC account. 😂

**Comment by GYKgamer** [comment]
I'm lucky that @theofficialgman understood it after nearly stopping it fully

**Comment by theofficialgman** [comment]
> I'm lucky that @theofficialgman understood it after nearly stopping it fully

that was my bad, sorry. I was trying to figure out why you posted. I couldn't find the deb you linked on mediafire and then it hit me to check the control file and the name was different (teamviewer as opposed to teamviewer host)

**Comment by GYKgamer** [comment]
It's no problem

**Comment by theofficialgman** [comment]
the deb repo seems to have been added as part of the deb successfully as well
```
Get:43 https://linux.teamviewer.com/deb stable/main arm64 Packages [4,166 B]   
```
both teamviewer and teamviewer-host are available in the repo

**Comment by theofficialgman** [comment]
@Botspot I'll leave it up to you to decide if you want this to be a separate app or if you want to change the name and migrate all users to `Teamviewer`

**Comment by GYKgamer** [comment]
I would personally Migrate as it's the same app same concept just that now has the feature to connect to other devices

**Comment by Botspot** [comment]
Migration seems like the best choice here.

**Comment by Botspot** [comment]
I can try to find some time to work on this later. Right now I have a Windows 10 VM script to work on.

**Comment by Crilum** [comment]
> I can try to find some time to work on this later. Right now I have a Windows 10 VM script to work on.

For Raspberries?!

**Comment by theofficialgman** [comment]
> I can try to find some time to work on this later. Right now I have a Windows 10 VM script to work on.

kernel virtual machines aren't enabled by default on the pi kernel are they? I thought you had to build that in

**Comment by Botspot** [comment]
> For Raspberry Pies?! 👍

That's right!

> kernel virtual machines aren't enabled by default on the pi kernel are they? I thought you had to build that in

RPi 64-bit kernel has KVM enabled. So it's just a matter of setting up a chroot, compiling qemu, generating a windows image, and running it.

**Comment by GYKgamer** [comment]
[install.sh.zip](https://github.com/Botspot/pi-apps/files/8934169/install.sh.zip)
Well while you guys were amazed by BotSpot (I am aswell) I created a base that the code could use

**Comment by Botspot** [comment]
> we have a couple of users that patched the switch kernel with KVM support... but running windows (in their case they did 11) ran like crap 😆

For that, there are debloating scripts for turning off unnecessary features.
Stock windows will probably be slow, but I've seen it run quite well when optimized. (I ran RaspbianX and tested the vm)

**Comment by theofficialgman** [comment]
> RPi 64-bit kernel has KVM enabled. So it's just a matter of setting up a chroot, compiling qemu, generating a windows image, and running it.

are they enabled in all the kernel packages? armhf buster, arm64 buster, armhf bullseye, and arm64 bullseye? or just a subset of those options that pi-apps supports?

i guess they actually didn't have to do any porting on switch. they just had to enable the kernel models...
```
CONFIG_HAVE_KVM_IRQCHIP=y
CONFIG_HAVE_KVM_IRQFD=y
CONFIG_HAVE_KVM_IRQ_ROUTING=y
CONFIG_HAVE_KVM_EVENTFD=y
CONFIG_KVM_MMIO=y
CONFIG_HAVE_KVM_MSI=y
CONFIG_HAVE_KVM_CPU_RELAX_INTERCEPT=y
CONFIG_KVM_VFIO=y
CONFIG_HAVE_KVM_ARCH_TLB_FLUSH_ALL=y
CONFIG_KVM_GENERIC_DIRTYLOG_READ_PROTECT=y
CONFIG_KVM_COMPAT=y
CONFIG_VIRTUALIZATION=y
CONFIG_KVM_ARM_VGIC_V3_ITS=y
CONFIG_KVM=y
CONFIG_KVM_ARM_HOST=y
CONFIG_KVM_ARM_PMU=y
CONFIG_VHOST_NET=m
CONFIG_VHOST=m
CONFIG_VHOST_CROSS_ENDIAN_LEGACY=y
```

**Comment by Botspot** [comment]
> are they enabled in all the kernel packages? armhf buster, arm64 buster, armhf bullseye, and arm64 bullseye? or just a subset of those options that pi-apps supports?

The RPi 32-bit kernel does not have KVM enabled, but the RPi 64-bit kernel does have KVM.
Even if the 32-bit kernel had KVM, it would not matter, as we would need the 64-bit kernel to run qemu-system-aarch64.

**Comment by theofficialgman** [comment]
> qemu-system-aarch64. (and we need qemu-system-aarch64 to run Windows ARM64)

well windows 10 armv7l does exist... but its kinda trash and support is over.

**Comment by GYKgamer** [comment]
I just read back what @theofficialgman changed in my original app request and said that the download "is a hidden deb with both the host and client" yet the download is really easy to find and not hidden?

**Comment by theofficialgman** [comment]
> I just read back what @theofficialgman changed in my original app request and said that the download "is a hidden deb with both the host and client" yet the download is really easy to find and not hidden?

Where is the link visible on the website then? All links on the website are arm7l teamview host. There aren't any arm64 links and aren't any teamviewer links (just TeamViewer, which is the host and client)

**Comment by GYKgamer** [comment]
![image](https://user-images.githubusercontent.com/41442793/174455727-b5e04b67-069b-4147-9959-ad01712e50fc.png)
![image](https://user-images.githubusercontent.com/41442793/174455728-4102f88d-f69a-4260-97ae-f2482dc0d28a.png)

**Comment by theofficialgman** [comment]
What website is that on? Send the direct link. There is no preview button on any website I visit

**Comment by GYKgamer** [comment]
https://www.teamviewer.com/en/download/raspberry-pi/
This one right here that is shown on the app request
![image](https://user-images.githubusercontent.com/41442793/174455799-1d54c75c-a09a-4174-a114-6b036365cd4f.png)

**Comment by theofficialgman** [comment]
Those buttons don't exist on that website for me. Only the host button.
Does anyone else see the preview button?
Do you have an account or something?

**Comment by GYKgamer** [comment]
Uh no, I don't understand 
![image](https://user-images.githubusercontent.com/41442793/174455994-9301abda-98c2-48d6-b593-2e10acb33e0c.png)
This is what I see very top

**Comment by Botspot** [comment]
My page looks different.
![2022-06-18-153144_1920x1080_scrot](https://user-images.githubusercontent.com/54716352/174456252-6e95ed1f-44a6-4434-935a-c334d2dbde1a.png)
@GYKgamer must have a teamviewer account, or maybe a different browser user-agent, or maybe Teamviewer is only displaying this to some users as a trial run of some kind.

**Comment by GYKgamer** [comment]
Don't know, I'm not signed in, I even tried Brave and it shows the same result. It's possible that it's because its region based, I'm in the UK and i'm assuming you're all in the US.

**Comment by Botspot** [comment]
> Don't know, I'm not signed in, I even tried Brave and it shows the same result. It's possible that it's because its region based, I'm in the UK and i'm assuming you're all in the US.

That could be it. I checked the site's ipv6 address and the server is located on the US mainland. It's definitely possible that this was a recent change and Amazon web services has not synced servers yet.

**Comment by GYKgamer** [comment]
Checking through the screenshots does confirm it
![image](https://user-images.githubusercontent.com/41442793/174456863-d7099057-cc2f-4390-b999-213d53955b11.png)
![image](https://user-images.githubusercontent.com/41442793/174456864-1002d24a-5a36-4ee6-ac1c-43501ab3a06b.png)

**Comment by Crilum** [comment]
I have the same page as @Botspot, I'm also in the US, but, when I connect to a VPN in Germany, I get @GYKgamer's page:
![teamviewerGermany](https://user-images.githubusercontent.com/91354257/174456866-2c4b8f37-1c48-4ee5-8643-998bd710549c.png)

**Comment by GYKgamer** [comment]
So, probably any european country I guess

**Comment by theofficialgman** [comment]
alright well this makes more sense now... its still "hidden", just hidden from half the worlds population 😆
