### ISSUE TITLE
Teach them and they will learn.

### ISSUE THREAD

**Issue by IamKraZ** [Botspot/pi-apps#1990]
### Cool ideas?

An idea for making a tutorial to save us old farts from asking the same old questions and screwing the Pi-Apps program up, lol.

Just a quick way to let people see what they need to do to:

A: Uninstall Pi-Apps (correctly)
B: Reinstall Pi-Apps (correctly)
C: Install (for the first time) Pi-Apps (correctly)

Noobs and Pros alike tend to forget about certain aspects of the software when they assume it's working great. Or they haven't ran it in a while do to RL events and when coming back to it joggles their thinking. Yes, a quick jug over to the GitHub page helps, but sometimes a tutorial just refreshes the memory with out the embarrassment of feeling like a complete idiot, lol.

Just a suggestion.
Thanks for reading :)

**Comment by Crilum** [comment]
So, you want a `Help` sort of page, inside Pi-Apps?

**Comment by IamKraZ** [comment]
Or a video that teaches us noobs how to not screw up our Pis and Pi-Apps.

It doesn't have to be lengthy, just show us the correct way to install,
uninstall, and reinstall Pi-Apps.

3 simple short and correct videos. Nothing more. Heck, I'll do them if you
want a YouTube vid for it, lol. I just need to learn the "correct" way to
do those 3 things.

**Comment by CleanMachine1** [comment]
The readme is more than enough in my opinion, it provides everything to install and uninstall.

Everything [here](https://github.com/Botspot/pi-apps/blob/master/README.md#install-pi-apps) is how to uninstall and install. Although Pi-Apps IMO is aimed at beginners, I am sure most can open a terminal and paste a command
