### ISSUE TITLE
An attempt at getting VLC Media Player.

### ISSUE THREAD

**Issue by IamKraZ** [Botspot/pi-apps#1992]
### Cool ideas?

Ok, I have VLC Media Player on my home PC and Work PC, but not on my Pi.
Can we get it on the Pi from the greatest App store?

It's a great program and would be awesome.

Thanks for considering.

**Comment by IamKraZ** [comment]
Just Checked their GitHub and they support the Pi, but I noticed it was a different name called Easycap. Not sure if that's the video and audio version. 
But they support almost every format. well worth a look at.

**Comment by IamKraZ** [comment]
Check their Git.

https://github.com/videolan/vlc

**Comment by Botspot** [comment]
I'm not sure what OS you're using, but on Raspberry Pi OS, a custom hardware-accelerated version of VLC is preinstalled.
If you're using a different operating system, you might be able to compile it. Here's the github repo: https://github.com/RPi-Distro/vlc

**Comment by IamKraZ** [comment]
It's the old one unfortunately. I don't know the slightest thing about
compiling. I may need to just get the latest version of the Pi OS.

**Comment by Botspot** [comment]
> It's the old one unfortunately.

What do you mean? Have you tried running `vlc --version` to see what version it is?

> I may need to just get the latest version of the Pi OS.

What OS are you using now? If it's the Bullseye version and you keep it updated, then you should have the latest versions of everything. Well, "latest" in terms of the ultra-stable-but-outdated Debian updating model. :)

**Comment by IamKraZ** [comment]
No I actually didn't verify I even had it, but after checking I saw I did
not. I will try the command line code you posted to see if it works for
mine.

And I am using the "oldstable" version because it was a back up I made when
I first got my Pi.
I realize I need to upgrade the OS, but I just updated P-Apps because I was
limited on time.

I know I need to upgrade (especially since the new OS has VLC, lol).

**Comment by Botspot** [comment]
I'm fairly sure Raspberry Pi OS Buster (which is what your OS seems to be) also has VLC preinstalled. If you don't see it, then run `sudo apt install vlc`

> I know I need to upgrade (especially since the new OS has VLC, lol).
Well that answers your question.
