### ISSUE TITLE
Add shellcheck action

### ISSUE THREAD

**Issue by Itai-Nelken** [Botspot/pi-apps#1993]
### Cool ideas?

If bash reports an error, there most likely is a typo or some wrong code somewhere, and I think we should report those errors the same way we report app install/uninstall errors.
I found this: https://stackoverflow.com/a/13099228/14480208
I haven't really looked at how it works, but it seems we can register a error handler function that can report the error, where it happened, and a backtrace witch we can than ask the user to upload so we can debug it.

**Comment by theofficialgman** [comment]
we could easily turn it on so all errors are fatal, however, a lot of scripts are written in a way such that errors with the `|| exit 1` are known to be fine errors and non fatal.

making all non-zero exit codes fatal takes away the script writers decisions to make specific functions error and is fundamentally opposite of how pi-apps was written.

**Comment by Itai-Nelken** [comment]
tbh I didn't think of that. I was thinking of syntax errors which a eay better way of finding would be making a shellcheck action that runs on every commit/pr.

**Comment by Itai-Nelken** [comment]
I'll open a pr for a shellcheck action later.

**Comment by Itai-Nelken** [comment]
Turns out this is a bit tricky as app folders have spaces in them.
I'm not interested enough in adding this to find a way to do it.
