### ISSUE TITLE
Back button not working

### ISSUE THREAD

**Issue by mobilegmYT** [Botspot/pi-apps#2]
When you view the details of a project and click the "Back" button to go to the main screen, it closes and reopens the same page.

**Comment by Botspot** [comment]
This is still in development and not ready for any users but me. Only reason this Github repo is up here at all right now is so I could develop the app-updater. 

That being said, it doesn't hurt to have a few brave beta-users! I will fix it when I fix it.

**Comment by Botspot** [comment]
OK it's fixed now.
Will upload to the repo soon.

**Comment by Botspot** [comment]
Uploaded now.
