### ISSUE TITLE
Spotify

### ISSUE THREAD

**Issue by GYKgamer** [Botspot/pi-apps#2003]
### What is the name of the app?

Spotify

### (Optional) Where is the app hosted?

https://community.spotify.com/t5/Live-Ideas/Desktop-Developer-Spotify-for-Windows-on-Arm-Win32-Desktop-app/idi-p/4992167/page/4#M243280

### About the app

Spotify desktop application

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by GYKgamer** [comment]
There is one small problem however, it's arm64 and is a windows application. Which means you need wine and I don't think it's possible to install wine on arm64 (unless there is a way)

**Comment by Rak1ta** [comment]
Does it work on Linux?
https://www.spotify.com/us/download/linux/
https://snapcraft.io/spotify

And two unofficial projects.
https://github.com/dtcooper/raspotify
https://github.com/Spotifyd/spotifyd

**Comment by GYKgamer** [comment]
Also its windows arm64 version

**Comment by GYKgamer** [comment]
Tried using box64 and wine yet get an error saying "File not found" which is weird since the file is in the same folder and it does show when clicking tab. Do need help on this one

**Comment by 89paradox** [comment]
Are you typing the filename correctly??

**Comment by GYKgamer** [comment]
Yep, I even click "Tab" to auto fill the file name

**Comment by GYKgamer** [comment]
I just tried it again and it told me to get box86 now (didnt before) but i had to leave my house rn so i have to install box86 in a couple of hours

**Comment by GYKgamer** [comment]
those are most of the errors I get

**Comment by Crilum** [comment]
>   * [x]  I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.

#1108

**Comment by GYKgamer** [comment]
I do realise that it has been talked about before, but was never added due to piracy. I'm trying to get it working without exagear / not piracy

**Comment by Crilum** [comment]
> I do realise that it has been talked about before, but was never added due to piracy. I'm trying to get it working without exagear / not piracy

Well, I think you should discuss it in #1103. It's pretty much a discussion on Spotify on the Pi, not just with Exagear.

Also, FYI, you can't use Spotify with wine, because Spotify doesn't like being installed by Admin, which wine runs as.
I saw (some time ago) a thread on winehq about this, and there was something about using Wine Staging, which allows you to change the permissions of the current wine user (`runas.exe`).

**Comment by GYKgamer** [comment]
Tried to run this but sadly can't get it to work, closing.
