### ISSUE TITLE
Open Surge port

### ISSUE THREAD

**Issue by Stylix58** [Botspot/pi-apps#201]
[OpenSurgePiApps.zip](https://github.com/Botspot/pi-apps/files/5766916/OpenSurgePiApps.zip)
@Botspot

**Comment by robloxboy24** [comment]
What is this?

**Comment by techcoder20** [comment]
@Stylix58 It is not working. The script fails at `cmake ..` I even tested the snap package even that is not working :(

**Comment by Stylix58** [comment]
> I even tested the snap package even that is not working
https://snapcraft.io/install/opensurge/raspbian

**Comment by mobilegmYT** [comment]
> > I even tested the snap package even that is not working
> > https://snapcraft.io/install/opensurge/raspbian

Could you try making a new install zip using snap?

**Comment by Botspot** [comment]
Closing this issue for 3 reasons:

- Install script was obviously untested. There's no possible way it could have worked.
- As others have said, after fixing all the problems in the install script, `cmake` still failed.
- Inactivity in this issue.

In case anyone was interested, here's my finished install script:
```bash
#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

rm -rf ~/opensurge
git clone https://github.com/alemart/opensurge.git || #error 'Failed to clone Open Surge repository!'

# Get dependencies
sudo apt install -y build-essential cmake software-properties-common

# Build
cd opensurge && mkdir build && cd build && cmake .. && make && sudo make install || error 'Failed to build and install Open Surge!'
```

**Comment by tedmakesstuff** [comment]
>>>  I even tested the snap package even that is not working
>> https://snapcraft.io/install/opensurge/raspbian

> Could you try making a new install zip using snap?

The game has an issue, and snap having a read-only filesystem means it is UNFIXABLE, so the snap installation, as of now, is  broken, unless someone makes a script, the easiest way is by compiling it yourself.
