### ISSUE TITLE
Angry IP Scanner fails to launch

### ISSUE THREAD

**Issue by Sussy-OS** [Botspot/pi-apps#2014]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)

### What happened?

Angry IP Scanner gives errors while launching on RPIOS 11 32-bit

### Description

I launch Angry IP, and I get this window: 
![image](https://user-images.githubusercontent.com/98842253/176012026-8a2ae743-a049-4d3a-9c41-6be55fa35c97.png)
Presumably a Java error, but I do not know for certain.

### What is your operating system?

Raspberry Pi OS 32-bit aarch64 bit kernel

**Comment by theofficialgman** [comment]
Do not make duplicates,h ttps://github.com/Botspot/pi-apps/issues/1045 . Upstream Raspbian bullseye issue.
