### ISSUE TITLE
CUPS - Common Unix Printing Service

### ISSUE THREAD

**Issue by nolan-the-dev** [Botspot/pi-apps#2024]
### What is the name of the app?

CUPS

### About the app

CUPS is an Open Source Printing Service that lets you setup printer for your pi or network

### Upload file or Add PR Link

https://github.com/apple/cups

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by cycool29** [comment]
The CUPS used in Linux is https://github.com/OpenPrinting/cups/ instead of https://github.com/apple/cups.

**Comment by theofficialgman** [comment]
can someone elaborate and send picture of what this sofware does? as well as provide information/comparisons to the pre-installed print functionality in piOS

**Comment by Itai-Nelken** [comment]
As far as I know rpiOS comes preinstalled with CUPS and even a gui configuration app.

**Comment by theofficialgman** [comment]
I checked, and cups is installed in the piOS full image, but not the lite image (which makes sense since the lite version has no desktop).
specifically, these packages are installed in the full image (on bullseye, buster has slightly different versions):
```
ii  cups                                  2.3.3op2-3+deb11u1               arm64        Common UNIX Printing System(tm) - PPD/driver support, web interface
ii  cups-browsed                          1.28.7-1+deb11u1                 arm64        OpenPrinting CUPS Filters - cups-browsed
ii  cups-client                           2.3.3op2-3+deb11u1               arm64        Common UNIX Printing System(tm) - client programs (SysV)
ii  cups-common                           2.3.3op2-3+deb11u1               all          Common UNIX Printing System(tm) - common files
ii  cups-core-drivers                     2.3.3op2-3+deb11u1               arm64        Common UNIX Printing System(tm) - driverless printing
ii  cups-daemon                           2.3.3op2-3+deb11u1               arm64        Common UNIX Printing System(tm) - daemon
ii  cups-filters                          1.28.7-1+deb11u1                 arm64        OpenPrinting CUPS Filters - Main Package
ii  cups-filters-core-drivers             1.28.7-1+deb11u1                 arm64        OpenPrinting CUPS Filters - Driverless printing
ii  cups-ipp-utils                        2.3.3op2-3+deb11u1               arm64        Common UNIX Printing System(tm) - IPP developer/admin utilities
ii  cups-pk-helper                        0.2.6-1+rpi1                     arm64        PolicyKit helper to configure cups with fine-grained privileges
ii  cups-ppdc                             2.3.3op2-3+deb11u1               arm64        Common UNIX Printing System(tm) - PPD manipulation utilities
ii  cups-server-common                    2.3.3op2-3+deb11u1               all          Common UNIX Printing System(tm) - server common files
```

**Comment by Botspot** [comment]
Closing, as this is a commonly installed baseline package. It would be like asking Pi-Apps to install pulseaudio or sudo.
