### ISSUE TITLE
Vivaldi Browser

### ISSUE THREAD

**Issue by nolan-the-dev** [Botspot/pi-apps#2026]
### What is the name of the app?

Vivaldi Browser

### (Optional) Where is the app hosted?

Download Link

### About the app

Vivalid is a Browser

### Upload file or Add PR Link

https://downloads.vivaldi.com/stable/vivaldi-stable_5.3.2679.61-1_armhf.deb

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by Botspot** [comment]
> * [x]  I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.

Are you sure about that? ;)
