### ISSUE TITLE
Cairo Dock - Package Install

### ISSUE THREAD

**Issue by nolan-the-dev** [Botspot/pi-apps#2029]
### What is the name of the app?

Cairo Dock

### (Optional) Where is the app hosted?

ZIP File

### About the app

Cairo adds a mac like dock to the bottom of your screen

### Upload file or Add PR Link

[Cairo Dock.zip](https://github.com/Botspot/pi-apps/files/9048088/Cairo.Dock.zip)

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by theofficialgman** [comment]
I personally don't think cairo dock really fits in with the default DE on most pi installs.

also, based on the eligibility rubric https://github.com/Botspot/pi-apps/issues/185 this app not does compliment any other pre-existing script apps, and thus isn't eligible for inclusion. maybe someone could argue that Ulauncher is an alternative currently in pi-apps, but I wouldn't agree with that.
