### ISSUE TITLE
TrackMania Nations Forever (and a feature request)

### ISSUE THREAD

**Issue by Pythonic456** [Botspot/pi-apps#203]
Can you add TM Nations to the app list? I'm not sure what this would involve, but I can try and help :+1: 
And can you add an option to not attempt to rebuild or download box86, but rather trust that
the user has already installed it? Thanks :)

**Comment by Botspot** [comment]
> And can you add an option to not attempt to rebuild or download box86, but rather trust that
> the user has already installed it? Thanks :)

This is hard to keep everybody happy. Many people won't update box86 periodically, and that will cause problems.  
So, I chose to simply reinstall box86 in 30 seconds whenever an emulated app is updated/installed.

**Comment by Pythonic456** [comment]
Could you make it just ask the user if they want to update/install box86, but if there's
no input for 30 seconds it just does it anyway?

**Comment by Botspot** [comment]
Okay I tried installing Trackmania using an emulated WINE. It installed successfully, but when I launched it, it resized my screen to 480p, then froze my X server.

I had to kill all box86 process from the console to regain control on the desktop session.

**Comment by Botspot** [comment]
So to me, this looks like a no-go, unless someone takes the time to figure out if this is a WINE issue or a box86 one.

**Comment by Itai-Nelken** [comment]
> Okay I tried installing Trackmania using an emulated WINE. It installed successfully, but when I launched it, it resized my screen to 480p, then froze my X server.
> 
> I had to kill all box86 process from the console to regain control on the desktop session.

I have no idea how to do it, but you should make it launch inside wines virtual desktop, then the fuulscreen window will launch inside a window on your host OS. so it (hopefully) won't freeze.

**Comment by Botspot** [comment]
> I have no idea how to do it, but you should make it launch inside wines virtual desktop, then the fuulscreen window will launch inside a window on your host OS. so your OS (hopefully) won't freeze.

It's worth a shot!

**Comment by Botspot** [comment]
![2021-01-09-123712_1920x1080_scrot](https://user-images.githubusercontent.com/54716352/104105939-7a37df80-5277-11eb-98d3-d3b05f0d482a.png)  
So far it hasn't worked.

**Comment by Botspot** [comment]
I gave up. Nothing was happening.

**Comment by Pythonic456** [comment]
I waited about an hour and nothing happened. You could try using strace to see what it's doing, but strace stops pretty quickly for some reason.
