### ISSUE TITLE
Create an alert for pi-kiss

### ISSUE THREAD

**Issue by Rak1ta** [Botspot/pi-apps#2037]
### Cool ideas?

Is it possible to add a warning to the user when installing pi-kiss? The developer rarely fixes his applications (outdated links, installation errors); when updating, it creates a version only for Bullseye (does not support Buster and others), no old files remain (as an example: I updated dosbox - it didn’t work on Buster, but I can’t roll back).

Suggestion: warn the user to update applications in pi-kiss with care, if the program works, then it is better to leave it that way. And if you put something that changes in the system, make a backup copy.
Or indicate that there is no support for older systems, use with caution.

I always have a copy of the ssd image in case of a breakdown.

**Comment by Botspot** [comment]
Adding a warning to the `install` script would not be a good idea - that would force an unnecessary update and reinstall of PiKISS for everyone. While this would not affect applications installed by PiKISS, it would still be counterproductive.

Our best option is to add a note to the description. While I could try to do this, I'm not a PiKISS user. It may be better for you, @Rak1ta, to propose a revised description in a Pull Request.

**Comment by Rak1ta** [comment]
@Botspot english is not my main language, you will need to check spelling for errors after me. This is how I wanted to warn.


> ATTENTION! The pi-kiss maintainer only uses edge versions of software. This means that if you installed something and it works, it does not mean that it will work in the future. Currently only Bullseye is supported, operation on Buster and similar systems is not guaranteed. Do not rush to remove your programs, you may not be able to install them in the future.
