### ISSUE TITLE
CS:GO 1.6

### ISSUE THREAD

**Issue by GYKgamer** [Botspot/pi-apps#2038]
### What is the name of the app?

CS:GO 1.6

### (Optional) Where is the app hosted?

Many different sites, no real place to get it.

### About the app

It is a shooter game made by valve, is a 3d game and a windows based game.

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by GYKgamer** [comment]
Using Box86 and Wine I got it working in x64 raspberry pi, so I would guess running wine in x86 raspberry pi would do the same, One thing i'm not certain is if this is piracy or not.

**Comment by Rak1ta** [comment]
@GYKgamer The game Counter-Strike is currently on sale and is not free to distribute. In order for this not to be considered the distribution of illegal software, the player must use their licensed game files. There is no need to add everything that works in Wine. Who needs it, he will add.

**Comment by GYKgamer** [comment]
You are right, just realised there is more then 1 Counter Strike game, we could technically a way to add game files and verify. But if they don't have it is there any way for a demo version like they did with Doom?

**Comment by theofficialgman** [comment]
@GYKgamer we have multiple issue templates... PLEASE use the correct one for the issue: https://github.com/Botspot/pi-apps/issues/new/choose

you have not added a PR or ZIP so this is NOT an app submission.
this is an app suggestion.

**Comment by GYKgamer** [comment]
Ah, understand now. Thanks for the heads up.

**Comment by Rak1ta** [comment]
@GYKgamer Are you interested in the performance of CS1.6 in RaspiOS 32bit? Installed the game using Bullseye, used .exe installer.
![Безымянный](https://user-images.githubusercontent.com/88277343/178121245-af62f828-601e-44c5-9c3b-f16d0c4f1dab.png)

**Comment by GYKgamer** [comment]
> @GYKgamer Are you interested in the performance of CS1.6 in RaspiOS 32bit? Installed the game using Bullseye, used .exe installer. ![Безымянный](https://user-images.githubusercontent.com/88277343/178121245-af62f828-601e-44c5-9c3b-f16d0c4f1dab.png)

I tried 64 bit, I was getting usually 20 fps but got 30 fps in some places (mine showed the fps). I will like to know the performance on 32 bit since I emulated using box86 AND wine.

**Comment by Rak1ta** [comment]
@GYKgamer
RaspiOS Debian 10 Buster 32bit 1900mHz/750
Changing the screen resolution does not change anything. FPS sags often, unplayable. 

`1920*1080`13fps
with low quality graphics
with bots 10ea
de_dust2
`1920*1080` 7-12fps
with low quality graphics
server 15-15
de_dust2

**Comment by GYKgamer** [comment]
> @GYKgamer Changing the screen resolution does not change anything. FPS sags often, unplayable. RaspiOS Debian 10 Buster 32bit 1900mHz/750
> 
> `1920*1080`13fps with low quality graphics with bots 10ea de_dust2 `1920*1080` 7-12fps with low quality graphics server 15-15 de_dust2

That's weird, I played with medium settings 9 bots at 1920x1080 I don't know how you got such low performance

**Comment by theofficialgman** [comment]
I don't really see how this can remain as an issue on pi-apps
this is a paid game, does not have any free/demo version, and is available through other appstores

it is fine to discuss games running on arm through box86/64 in their discord server or as a discussion at the box86/64 github repos
