### ISSUE TITLE
Warnings during updates

### ISSUE THREAD

**Issue by Rak1ta** [Botspot/pi-apps#2043]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)

### What happened?

insserv: warning: script 'vmware-USBArbitrator' missing LSB tags

### Description

I'm not sure if this is a bug, but I wanted to ask you. When updating various packages, these warnings sometimes pop up. What's this? Not to pay attention?

### What is your operating system?

RaspiOS 32bit Debian10

### (Optional) Error log? Terminal output? Debug messages?

```bash
insserv: warning: script 'realtime' missing LSB tags
insserv: Default-Start undefined, assuming empty start runlevel(s) for script `realtime'
insserv: Default-Stop  undefined, assuming empty stop  runlevel(s) for script `realtime'
insserv: warning: script 'vmware-USBArbitrator' missing LSB tags
insserv: Default-Start undefined, assuming empty start runlevel(s) for script `vmware-USBArbitrator'
insserv: Default-Stop  undefined, assuming empty stop  runlevel(s) for script `vmware-USBArbitrator'
```

**Comment by theofficialgman** [comment]
what is this log from? what are you updating?
I don't understand what this "bug" is supposed to be reporting

**Comment by theofficialgman** [comment]
```
       insserv - boot sequence organizer using LSB init.d script dependency information
```
thats what I found on the package information

did you install the realtime kernel or something? as well as vmware?

**Comment by Rak1ta** [comment]
@theofficialgman 
Thanks! I had insserv installed with RetroPie and it displays these warnings for me. Everything is fine.
