### ISSUE TITLE
Error starting VMWare Horizon Client

### ISSUE THREAD

**Issue by Rak1ta** [Botspot/pi-apps#2044]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)

### What happened?

Packages need to be installed

### Description

If you try to run VMWare on a clean system, the application complains about missing files. Requires installation `libcairomm-1.0-1v5 libsigc++-2.0-0v5`.

### What is your operating system?

RaspiOS 32bit Debian10

**Comment by theofficialgman** [comment]
what is the actual error output of the app when starting (send log)? are these the only missing packages?

**Comment by theofficialgman** [comment]
closed with https://github.com/Botspot/pi-apps/commit/303fcf580ab7285f5f576edfe89dd47ac3cf99d2
