### ISSUE TITLE
Typo in /etc/apt/sources.list and /etc/apt/sources.list.d and I don't know what it is.

### ISSUE THREAD

**Issue by skeleton-mcpi** [Botspot/pi-apps#2057]
Whenever I install an app with PiApps, it fails and says there is a typo in /etc/apt/sources.list and /etc/apt/sources.list.d
I don't know what the typo is. I've had this problem before, but it randomly let me install Minecraft Pi Modded.

**Comment by Botspot** [comment]
The apt sources are only used when running `sudo apt update`, so could you paste the output of that command?

Also, Pi-Apps stores log files of all app-installations, so if you could upload one that would be great.

**Comment by skeleton-mcpi** [comment]
The output of running the command is:
E: Type '<!DOCTYPE' is not known on line 2 in source list /etc/apt/sources.list.d/mcpiscript.list
E: The list of sources could not be read.
If you need anthing else, I'll try to get on here later

**Comment by Botspot** [comment]
Yeah that definitely does not belong there.
Please run `cat  /etc/apt/sources.list.d/mcpiscript.list` and post the output so I can see the contents of the file.

**Comment by Jai-JAP** [comment]
Seems like its an html file. That surely doesn't belong there...
Random html file... :\

**Comment by Botspot** [comment]
I searched all of Github and found only one reference to "mcpiscript.list". It's in [this repo](https://github.com/mcpiscript/PPA) belonging to @leha-code. Presumably this is what @skeleton-mcpi used. 

The current [setup instructions](https://github.com/mcpiscript/PPA#installation) there say to download a file from mcpiscript.github.io to `/etc/apt/sources.list.d/mcpiscript.list`. I would speculate that at some point this page was down, so the 404 html page was written to the file.

@leha-code, you should avoid this issue by changing that line in your instructions to: `echo 'deb https://mcpiscript.github.io/PPA ./' | sudo tee /etc/apt/sources.list.d/mcpiscript.list` >/dev/null`

@skeleton-mcpi, you can solve your issue by deleting the /etc/apt/sources.list.d/mcpiscript.list file.

**Comment by skeleton-mcpi** [comment]
Thanks for the help @Botspot and @Jai-JAP. Will do that :)

**Comment by skeleton-mcpi** [comment]
@Botspot  it seems I'm unable to move mcpiscript.list to my trash. When I do, the output is: 
Unable to trash file /etc/apt/sources.list.d/mcpiscript.list: Permission denied

**Comment by Itai-Nelken** [comment]
> @Botspot  it seems I'm unable to move mcpiscript.list to my trash. When I do, the output is: 
> Unable to trash file /etc/apt/sources.list.d/mcpiscript.list: Permission denied

You need to do it as root. Open a terminao window and run `sudo rm /etc/apt/sources.list.d/mcpiscript.list`.
