### ISSUE TITLE
Connectivity issue in Linux-wifi-hotspot

### ISSUE THREAD

**Issue by abraha2** [Botspot/pi-apps#2060]
Hi, Botspot,  I have a problem with the Linux Wifi Hotspot app.
Pi-Apps automatically updated the Linux Wifi Hotspot app, and I also reset my Google Home Mini. Before that, it had been connected to the  hotspot that I set up on the pi. Now, the Google Home won't connect to the wifi network, at all. I have tried so many things. I even reset my Google Home three times, but to no avail.
  I would greatly appreciate help on this problem
I can't wait to get it fixed 

Here is my version information:
Raspberry Pi 3B+ running the official Raspberry Pi OS
```
~ $ uname -a           
Linux raspberrypi 5.15.32-v7+ #1538 SMP Thu Mar 31 19:38:48 BST 2022 armv7l GNU/Linux
```
P.S Don't click on the hashtag in the linux version info, it's just part of the terminal output.

**Comment by Botspot** [comment]
> P.S Don't click on the hashtag in the linux version info, it's just part of the terminal output.

I went ahead and put your `uname` output in code tags. Feel free to "edit" your post to see how I did it.

This app was last [changed](https://github.com/Botspot/pi-apps/commit/1d6c37c7a3026b1df8a78b0c79dbf57b43d9a028) 10 days ago, so you must have updated it between then and now.

Can you see the network from another device? Try to see if a smartphone or another computer can see, and connect to, the WiFi network.

**Comment by Botspot** [comment]
I just tested Linux WiFi Hotspot for myself again to make sure it still works. The first few tries, my second device could not seem to find the network, but that could have been my fault. The third time it worked.

**Comment by theofficialgman** [comment]
> This app was last [changed](https://github.com/Botspot/pi-apps/commit/1d6c37c7a3026b1df8a78b0c79dbf57b43d9a028) 10 days ago, so you must have updated it between then and now. I don't think the changes from 10 days ago could be causing your problem, but they did move a systemd service, so have you tried rebooting your Pi?

the changes can not have caused the issue. the service is not normally active, it is for users to manually enable if they would like to have the wifi network created automatically on boot. there also have note been any commits to linux wifi hostpot repo since april 30th (before it was even added to pi-apps)

the users issue here more likely just happened to correspond to a kernel/firmware update of the wifi chip in the pi3

**Comment by Botspot** [comment]
@abraha2, could you report back with any new findings?

**Comment by abraha2** [comment]
I have rebooted my Pi4B many times, and in none of those reboots, have I gotten it to work.
Also, no ,there are no new findings to report

**Comment by Botspot** [comment]
@abraha2, can you see the network from another device? Try to see if a smartphone or another computer can see, and connect to, the WiFi network.

**Comment by abraha2** [comment]
Sorry for the slow responses, I have a very hectic, and weird schedule.
Nonetheless I will answer as soon as I can.

**Comment by abraha2** [comment]
> I have rebooted my Pi4B many times, and in none of those reboots, have I gotten it to work. Also, no ,there are no new findings to report

Actually, I just got this mixed up with a different issue, so first off, I I'm not running it on a pi4B. It's actually a pi3B+.  With that in mind, then your answer is no. I have not tried rebooting my pi

**Comment by theofficialgman** [comment]
if you can connect via other devices, I think it is safe to assume that your google home mini reset applied a firmware/software update for that device which broke its wifi connection ability with some devices.

I suggest creating a support ticket with whatever resource you are supposed to go to for that device.

Since this isn't a pi-apps issue, I will close this

**Comment by abraha2** [comment]
What do you mean, a support ticket?

**Comment by Botspot** [comment]
> How do I make a support ticket, and what exactly am I making it for?

In other words, go find help for your google home mini, as that appears to be the problem here. The issue you are having is not the fault of Pi-Apps or Linux WiFi Hotspot, because you say that other devices can see the hotspot.
