### ISSUE TITLE
Minecraft Java Edition Is Becoming Unsuported!

### ISSUE THREAD

**Issue by KozmikNano** [Botspot/pi-apps#207]
I am pretty sure you guys have seen this before but Minecraft is switching over to Microsoft accounts. Due to this the legacy launcher is no longer supported. How can still play Minecraft?

**Comment by Botspot** [comment]
Yes, we know, and are keeping an eye on the situation on a daily basis.

You might notice there's an announcement about it on the main Pi-Apps window.

This issue it a duplicate. Please see #167.
