### ISSUE TITLE
RustDesk (Open source, Multiplatform, TeamViewer alternative)

### ISSUE THREAD

**Issue by theofficialgman** [Botspot/pi-apps#2083]
### What is the name of the app?

RustDesk

### (Optional) Where is the app hosted?

https://rustdesk.com/
https://github.com/rustdesk/rustdesk/releases/tag/1.1.9

video that I got in my recommended: https://www.youtube.com/watch?v=JIAdEGX_sIU

### About the app

> A remote desktop software, the open source TeamViewer alternative, works out of the box, no configuration required. You have full control of your data, with no concerns about security. You can use our public rendezvous/relay server, or [self-hosting](https://rustdesk.com/server), or write your own server.

they have a deb prebuilt already for armhf but building for arm64 should also be possible. there are build instructions in their README

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by Botspot** [comment]
Hooray, another Mental Outlaw fan! https://www.youtube.com/watch?v=JIAdEGX_sIU

**Comment by Botspot** [comment]
I found a recent github issue on arm64 support for RustDesk. In light of compilation errors, the main dev does not seem to consider it a high priority at this time.
https://github.com/rustdesk/rustdesk/issues/853

**Comment by Botspot** [comment]
I am pretty sure the reported installation size in the deb is wrong. The deb is 4.7MB, but apt said "`After this operation, 12.7 GB of additional disk space will be used.`" No other dependencies were pulled in either.

**Comment by theofficialgman** [comment]
> I found a recent github issue on arm64 support for RustDesk. In light of compilation errors, the main dev does not seem to consider it a high priority at this time. [rustdesk/rustdesk#853](https://github.com/rustdesk/rustdesk/issues/853)

yeah I see that
probably best to wait a while for their flutter rewrite. the sciter binaries aren't compatible with buster/bionic anyway `version 'GLIBC_2.29' not found`

**Comment by theofficialgman** [comment]
btw, a lot of work has been done for getting flutter on desktop on rustdesk. it was merged into the master branch in august, and there have been continual fixes since then.

I imagine a release with it will be coming out within a month or two

**Comment by theofficialgman** [comment]
alright looks like they have nightly builds setup for a bit now with rustdesk desktop flutter windows and linux (built on bionic).
their readme doesn't have build instructiosn for flutter yet but their CI can be used to get an idea
https://github.com/rustdesk/rustdesk/blob/a9eb2854255f6a93408d84b255af2e1dced05829/.github/workflows/flutter-nightly.yml#L103-L266

they use vcpkg for linux which is... a bit concerning since the armhf/arm64 support is generally pretty bad

**Comment by theofficialgman** [comment]
arm64 builds are available in the nightly branch
uses software decoding and encoding on arm64 and doesn't even use system ffmpeg so it probably will in the future as well

https://github.com/rustdesk/rustdesk/releases/tag/nightly

**Comment by theofficialgman** [comment]
I created a github issue requesting that rustdesk have an option for using the system ffmpeg and they moved it to a discussion. comment here if you would like this as well: https://github.com/rustdesk/rustdesk/discussions/2800

**Comment by theofficialgman** [comment]
rustdesk 1.2.0 with the flutter re-write just released. I don't think there were any changes regarding hardware acceleration via system ffmpeg but now it should be installable on ARM32/ARM64 (see release assets https://github.com/rustdesk/rustdesk/releases/tag/1.2.0 )

**Comment by Botspot** [comment]
After a bit of tinkering I got it working on PiOS Bookworm with wayland.
You have to install `xdg-desktop-portal-wlr` and then make a fix to its .service file as shown [here](https://forum.garudalinux.org/t/trouble-with-xdg-desktop-portal-and-screencasting/20090/4).

**Comment by theofficialgman** [comment]
> The XDG_CURRENT_DESKTOP variable was unset

I already reported that issue months ago to piOS I believe on the forum. It never got a response and is still unfixed https://forums.raspberrypi.com/viewtopic.php?p=2144462#p2144462

**Comment by Botspot** [comment]
Update on this: It seems that at some point Raspberry Pi OS now ships by setting `XDG_CURRENT_DESKTOP=wlroots` by default, and the systemd service file workaround is no longer necessary. This was tested today on a fresh install post labwc upgrade.

@theofficialgman, could you see any reason that RustDesk should not be added to Pi-Apps at this point? If not I'll take care of it.

**Comment by Botspot** [comment]
PR opened: https://github.com/Botspot/pi-apps/pull/2672

**Comment by theofficialgman** [comment]
> @theofficialgman, could you see any reason that RustDesk should not be added to Pi-Apps at this point? If not I'll take care of it.

No objections here.

**Comment by Botspot** [comment]
OK, I thought I half remembered you had some additional reason why it was unsuitable. But I'll merge it and if something comes up we can reassess.

**Comment by theofficialgman** [comment]
I'd still like the custom ffmpeg based decode support to be a feature as outlined in previous messages but it's not a blocker
