### ISSUE TITLE
How To Add A App To PiApps

### ISSUE THREAD

**Issue by RaspberryRBX** [Botspot/pi-apps#21]
How Do I Create A App On Piapps

**Comment by mobilegmYT** [comment]
Search for "Pi Apps Settings" in the application menu, open it and click "Create App".

**Comment by RaspberryRBX** [comment]
Ok

**Comment by Botspot** [comment]
On a Raspbian system, you won't have a search bar. You will find Pi-Apps Settings in Menu --> Preferences.
