### ISSUE TITLE
spotify

### ISSUE THREAD

**Issue by nolanh1** [Botspot/pi-apps#210]
i found a opensource github page with a rasbain version of spotify, could u maybe add it? link: https://github.com/dtcooper/raspotify

i think alot of people would love this, cause its spotify, i mean its spotify.

i think yes, u would need to get more in depth on the github page (link above)

i have the link to the github i can repost it again 

link: https://github.com/dtcooper/raspotify

**Comment by Itai-Nelken** [comment]
Its a spotify connect client for the pi, not spotify itself.

**Comment by Botspot** [comment]
First remark: Wow, raspotify has a lot of [issues](https://github.com/dtcooper/raspotify/issues), and does not look that well-maintained. And a lot of open issues look somewhat severe. (bugs, not enhancements)

Second, why not just play Spotify in the browser with Chromium Widevine?

**Comment by Botspot** [comment]
In addition, this has already been covered. #63 

If someone can convince me otherwise that Chromium Widevine (Media Edition) somehow isn't enough, we can re-open the issue.
