### ISSUE TITLE
Pale Moon cannot be installed

### ISSUE THREAD

**Issue by Rak1ta** [Botspot/pi-apps#2101]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)

### What happened?

Pale Moon cannot be installed

### Description

As I understand it, the program is located at a different [address](https://software.opensuse.org/download.html?project=home%3Astevenpusser&package=palemoon) and now there is a split on Debian 10/11.
[install-fail-Pale Moon.log](https://github.com/Botspot/pi-apps/files/9267869/install-fail-Pale.Moon.log)

### What is your operating system?

RaspiOS 32bit Debian10

**Comment by theofficialgman** [comment]
I think you are trying to say the correct thing but aren't explaining it well. the repo that pi-apps has for install-32 `http://download.opensuse.org/repositories/home:/stevenpusser/Raspbian_10` no longer contains `palemoon` at all

the debian 10 repo contains both armhf and arm64 palemoon so it we will switch to that

**Comment by theofficialgman** [comment]
@Rak1ta just to confirm, the fix has been pushed. please respond if pale moon installs and runs successfully on 32bit

**Comment by Rak1ta** [comment]
@theofficialgman the program works
