### ISSUE TITLE
improve it with nala instead of apt

### ISSUE THREAD

**Issue by j03ll0b0** [Botspot/pi-apps#2103]
### Cool ideas?

well there is more advanced features in nala, why not use it in pi-apps? it would be so cool though... and thanks for such a great tool

**Comment by Itai-Nelken** [comment]
> well there is more advanced features in nala [...]
Nala is just a wrapper around apt as far as I know. That means that apt can do everything nala does.

Nala is a more user-friendly interface for apt. That means that it has formatted output and omits data that might clutter the terminal, but that pi-apps needs.
Also pi-apps parses apts output, so having to filter through all the formatting nala adds will be slow and bug prone.

That said, if you have any ideas to where pi-apps could be improved, feel free to suggest them!

**Comment by Botspot** [comment]
@j03ll0b0, is there a particular feature nala has that you think Pi-apps could benefit from? For example, does it use concurrent downloads or a faster `apt update`?

**Comment by Itai-Nelken** [comment]
Turns out nala isn't simply a wrapper. It uses apt only to install/uninstall packages and update repos. It downloads and verifies packages concurrently and then passes them on to apt for installing.

**Comment by theofficialgman** [comment]
Nala also isn't compatible with buster/bionic libraries. So it can not be used. Sorry, closing.
Refer to https://gitlab.com/volian/nala/-/issues/19
