### ISSUE TITLE
Use of firejail in pi-apps

### ISSUE THREAD

**Issue by Bi-Doux** [Botspot/pi-apps#2104]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)

### What happened?

At each attemps installation or update, firejail returns an error and script is stopped

### Description

Sorry, I am not sure whether pi-apps uses firejail but each time I try to install a new app or update an existing one, I get the following error: "Error: too long environment variables, please use --rmenv" which originates from firejail.

As I don't now which environment variable of firejail has reached max size, I am just wondering whether there is a way to prevent pi-apps from calling firejail

### What is your operating system?

Raspberry Pi 4 under Bullseye 64bits

### (Optional) Error log? Terminal output? Debug messages?

```bash
🭊▅▅▅▅🬿
 🭈▂▂█▂▂▂▂█▂▂🬽
 ▌  ▗▖▗▖▗▖  ▐   █▀▀🭍 ▄
 ▌  ▗▖▗▖▗▖  ▐   █▄▄🭞 ▄ ▄▄ 🭂▀▀█ █▀▀🭍 █▀▀🭍 🭂🬰🬰🬰
 ▌  ▗▖▗▖▗▖  ▐   █    █    🭓▄▄█ █▄▄🭞 █▄▄🭞 ▄▄▄🭞
 🭓🬭🬭🬰🬰🬰🬰🬰🬰🬭🬭🭞                  █    █

i is q
i is O
using aria2c

Updater mode: set-status

Checking for online changes... Error: too long environment variables, please use --rmenv
pipe is /tmp/tmp.JvBTQz398I
Done
list file for  does not exist.
Generating list for ''...
Scanning apps... Done
Finished preload for ''
Scanning files... Done
Error: too long environment variables, please use --rmenv
Error: too long environment variables, please use --rmenv
Selection: All Apps/
Timestamps match.
Reading list file for 'All Apps'...
Selection: /
Timestamps match.
Reading list file for ''...
Selection: Tools/
Timestamps match.
Reading list file for 'Tools'...
Selection: Tools/More RAM
i is q
i is O
using aria2c
Error: too long environment variables, please use --rmenv
Selection: Tools/More RAM
i is q
i is O
using aria2c
Error: too long environment variables, please use --rmenv
Selection: /
Timestamps match.
Reading list file for ''...
Selection: Search/
search pattern: description -o -name website -o -name credits
Selection: /WPS Office
i is q
i is O
using aria2c
Error: too long environment variables, please use --rmenv
Selection: Installed/
Timestamps match.
Reading list file for 'Installed'...
Selection: Installed/WPS Office
i is q
i is O
using aria2c
Error: too long environment variables, please use --rmenv
Selection: Installed/WPS Office
i is q
i is O
using aria2c
Error: too long environment variables, please use --rmenv
Selection: Installed/WPS Office
i is q
i is O
using aria2c
Error: too long environment variables, please use --rmenv
```

**Comment by Botspot** [comment]
Pi-Apps does not run firejail. Either another command that is used by Pi-Apps is calling firejail, or perhaps another command is causing this error altogether.

**Comment by Botspot** [comment]
What OS are you using, @Bi-Doux?

Also, can you return the output of `env | wc -c`?
I have never used firejail, but from what I understand it can link itself to any command you want to isolate. Pi-Apps must be using one or more of these jailed commands, which runs firejail as a result.
@Bi-Doux, can you find a way to list all programs that are sandboxed with firejail?

**Comment by Bi-Doux** [comment]
Thanks for helping me trouble shooting this problem. env | wc -c returns 2892
My version is PiOS v5.15.32-v8+ (Bullseye)
The command firejail --list allows to list all applications running in sandbox and conky (installed via Pi-Apps) do as well as some other apps installed via Pi-Apps (e.g. firefox-esr, wps...etc) but it does not list applications bound to run in sandbox ???
No idea how firejail has automatically encapsulated most of my Pi-Apps but it may be linked with some command called in all installation scripts ?

**Comment by rusty-snake** [comment]
- To list all firecfg symlinks: `firecfg --list` (or `ls -l /usr/local/bin | grep /usr/bin/firejail`)
- Your log from OP says 'using aria2c', a symlink for `aria2c` is created by default.
  To remove it, remove the symlink (`sudo rm /usr/local/bin/aira2c`) and prevent future creation of it (`sudo sed -i "s/aria2c/#aria2c - breaks pi-apps/`).

**Comment by Botspot** [comment]
> and prevent future creation of it (`sudo sed -i "s/aria2c/#aria2c - breaks pi-apps/`).

@rusty-snake, you appear to have forgotten to specify which file `sed` should be editing. This command will not work in its current form.

**Comment by rusty-snake** [comment]
True. If using firejail 0.9.68 or newer `/etc/firejail/firecfg.config`.

```
sudo sed -i "s/aria2c/#aria2c - breaks pi-apps/" /etc/firejail/firecfg.config
```

For older releases it is somewhere under `/usr/lib??/*/firejail/firecfg.config`, just `find`/`locate` for it.

**Comment by Bi-Doux** [comment]
Firecfg --list returned 64 apps !! Finally firefcfg --clean did solved the Pi-Apps update problem (all my Pi-Apps are updating again) including by removing aria2c from sandbox.

Thank you all for the hints.

Bi-Doux

**Comment by Botspot** [comment]
> Firecfg --list returned 64 apps !! Finally firefcfg --clean did solved the Pi-Apps update problem (all my Pi-Apps are updating again) including by removing aria2c from sandbox.
> 
> Thank you all for the hints.
> 
> Bi-Doux

Out of curiosity, why was firejail installed on your system at all?

**Comment by Bi-Doux** [comment]
Not proactively by myself but certainly via a package dependency? When screening Github, I have noticed some installation scripts using firewall.
