### ISSUE TITLE
Raspberry Pi 4 Windows 11 Installation error

### ISSUE THREAD

**Issue by kichuu7115** [Botspot/pi-apps#2105]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)

### What happened?

WoR Flassher Error

### Description

I am unable to complete installation of Windows 11 on Raspberry pi 4. I get the following error messages:

An error has occurred:
get_uuid(): Failed to find a working Update ID for Windows 11. Please report this issue to Botspot.
Exiting now.

An error has occurred:
list_langs(): requires an argument for windows update ID. Example ID: db8ec987-d136-4421-afb8-2ef109396b00
Exiting now.

### What is your operating system?

Raspberry Pi

### (Optional) Error log? Terminal output? Debug messages?

```bash
pi@Ki:~ $ ~/wor-flasher/install-wor-gui.sh
DIRECTORY: /home/pi/wor-flasher
DL_DIR: /home/pi/wor-flasher-files
Checking for internet connection... Done
df: /home/pi/wor-flasher-files: No such file or directory
get_uuid(): Failed to find a working Update ID for Windows 11. Please report this issue to Botspot.
UUID: 
RPI_MODEL: 4
list_langs(): requires an argument for windows update ID. Example ID: db8ec987-d136-4421-afb8-2ef109396b00
pi@Ki:~ $
```

**Comment by Botspot** [comment]
Getting the list of languages and a build id is both dependent on https://uupdump.net. Please check if your  browser can reach that website from your network.

**Comment by kichuu7115** [comment]
> Getting the list of languages and a build id is both dependent on https://uupdump.net. Please check if your browser can reach that website from your network.

i have tried that - no luck:
502 Bad Gateway
nginx

any suggestions?

**Comment by theofficialgman** [comment]
Same here Botspot.
That website appears to be down or removed entirely

**Comment by theofficialgman** [comment]
website is back online.
likely a server issue on their end. closing

**Comment by Botspot** [comment]
I've improved WoR-Flasher to display a better error message the next time uupdump is down.
https://github.com/Botspot/wor-flasher/commit/d5de6cddde7f1fb6b722015bd164ff4192d163b6
