### ISSUE TITLE
Need help with installs shared libraries 

### ISSUE THREAD

**Issue by CMDR-Piboy314** [Botspot/pi-apps#2106]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)

### What happened?

Stunt Rally Installation has errors on 64-bit bullseye (RPi OS)

### Description

The installation simply errors out... This install is fresh (just from a few hours ago). I haven't tested this install script before so I don't know if it ever worked. NOTE: I had to put it on ubuntu pastebin because even with cutting massive chunks out it was too big for github.

### What is your operating system?

Raspberry Pi OS aarch64 (bullseye)

### (Optional) Error log? Terminal output? Debug messages?

```bash
https://pastebin.ubuntu.com/p/zm5bFbCjNv/
```

**Comment by CMDR-Piboy314** [comment]
dpkg certainly isn't happy 🤣, during --fix-broken install it breaks.
```
dpkg: error processing archive /var/cache/apt/archives/libglx-dev_1.3.2-1_arm64.
deb (--unpack):
 trying to overwrite shared '/usr/include/GL/glx.h', which is different from oth
er instances of package libglx-dev:arm64
Preparing to unpack .../libgl-dev_1.3.2-1_arm64.deb ...
Unpacking libgl-dev:arm64 (1.3.2-1) ...
dpkg: error processing archive /var/cache/apt/archives/libgl-dev_1.3.2-1_arm64.d
eb (--unpack):
 trying to overwrite shared '/usr/include/GL/gl.h', which is different from othe
r instances of package libgl-dev:arm64
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Preparing to unpack .../libegl-dev_1.3.2-1_arm64.deb ...
Unpacking libegl-dev:arm64 (1.3.2-1) ...
dpkg: error processing archive /var/cache/apt/archives/libegl-dev_1.3.2-1_arm64.
deb (--unpack):
 trying to overwrite shared '/usr/include/EGL/egl.h', which is different from ot
her instances of package libegl-dev:arm64
Preparing to unpack .../libgles-dev_1.3.2-1_arm64.deb ...
Unpacking libgles-dev:arm64 (1.3.2-1) ...
dpkg: error processing archive /var/cache/apt/archives/libgles-dev_1.3.2-1_arm64
.deb (--unpack):
 trying to overwrite shared '/usr/include/GLES2/gl2.h', which is different from 
other instances of package libgles-dev:arm64
Errors were encountered while processing:
 /var/cache/apt/archives/libglx-dev_1.3.2-1_arm64.deb
 /var/cache/apt/archives/libgl-dev_1.3.2-1_arm64.deb
 /var/cache/apt/archives/libegl-dev_1.3.2-1_arm64.deb
 /var/cache/apt/archives/libgles-dev_1.3.2-1_arm64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by theofficialgman** [comment]
The error is unrelated to stunt rally. Please check with your distro package maintainer for incompatible packages and make sure you haven't tried to install any custom mesa drivers
