### ISSUE TITLE
twitch

### ISSUE THREAD

**Issue by nolanh1** [Botspot/pi-apps#211]
this is only a thought i havent found anything on it, but would twitch work? like could u add it? or is linux not good for twitch.

**Comment by Botspot** [comment]
Quick question: are you hoping to **stream** to Twitch, or to **watch** Twitch on your RPi?

**Comment by fabianmendes** [comment]
> Quick question: are you hoping to **stream** to Twitch, or to **watch** Twitch on your RPi?

It would be good to stream

**Comment by nolanh1** [comment]
i was hoping to watch, sry for the late response. i was busy with school this week cause we switched to online.

**Comment by mobilegmYT** [comment]
Watch? Then can't you just use the web version?

**Comment by mobilegmYT** [comment]
@nolanh1 I don't think twitch desktop is available for linux, watching online is the only option. You could try use nativefier to make a "desktop app" and replicate the feeling of one.
