### ISSUE TITLE
does More Ram app work on radxa cm3/rk3566 soc with debian?

### ISSUE THREAD

**Issue by qNnOtTk** [Botspot/pi-apps#2111]
### Cool ideas?

I am buying a CM3 with only 2GB of ram and would like to know if this app is compatible with this board.
I can't buy a board with more ram because of price limit.

**Comment by Botspot** [comment]
More RAM is one of the few apps that does not actually download anything. Furthermore, it does not install any packages. It simply changes a few kernel settings to enable `zram`, along with other tweaks to maximize its effectiveness.

So as long as your kernel has a zram module, the More RAM app should work fine. You can have another Radxa user try running `sudo modprobe zram` to find out.

If this answered your question, feel free to close the issue @qNnOtTk.
