### ISSUE TITLE
Minecraft PaperMC Server Install based App

### ISSUE THREAD

**Issue by depthso** [Botspot/pi-apps#2112]
### What is the name of the app?

PaperMC

### (Optional) Where is the app hosted?

https://github.com/depthso/RaspberryPIMinecraft1.19.2-Server

### About the app

Automatic installer for creating a Minecraft server with PaperMC running 1.19.2.

Auto installs Java 17 for arm and the PaperMC server jar file.
 
Makes reinstalling and running easy using the `Install.sh` file that is located in the directory of the MInecraft server, and makes it easy to run the server at start up.

### Upload file or Add PR Link

[Minecraft PaperMC Server.zip](https://github.com/Botspot/pi-apps/files/9337503/Minecraft.PaperMC.Server.zip)

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by theofficialgman** [comment]
Closing. The already existing Minecraft java server app allows for automatic creation of Vanilla, Fabric, Forge, Paper, Bukkit, Spigot, Sponge, Purpur and Tuinity for all available versiond

Please use existing apps before creating duplicates
