### ISSUE TITLE
adding an app

### ISSUE THREAD

**Issue by wa1funky** [Botspot/pi-apps#2114]
### What is the name of the app?

Gengal

### (Optional) Where is the app hosted?

i reakky dont know i think if i remember i see it on emu movies but i do have acopy of the app if you need iy or would like a copy.

### About the app

it;s an xml genarator app the hekps you add extra xmk tags to your retropie xml lit. but it olnly runs on windows thank you for takimg your time to read this i hust really nre at giyhub and retropie my fisrt time in here you can reach me at 2010dbaby@gmailo.com thank you again

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by Sussy-OS** [comment]
Could you make an app folder for this app? Documentation here: https://github.com/Botspot/pi-apps/wiki/Creating-an-app

**Comment by theofficialgman** [comment]
Gegal is cute, but it doesn't really fit into pi-apps.
It has zero use to anyone who doesn't already have retropie installed (a software not even in pi-apps), and as you said, it is windows only software. Gengal also isn't maintained in any capacity, so we would have no place to send issues to even if it were compatible with linux and the pi.
