### ISSUE TITLE
No apps available on install

### ISSUE THREAD

**Issue by mikepaxton** [Botspot/pi-apps#2117]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)

### What happened?

Once installed there are no apps.

### Description

After installing Pi-Apps using both the wget and git options I start Pi-Apps but when the window comes up there are no application or categories to choose from.  Just and empty window.  I've tried doing an update using ~/pi-apps/updater cli but to no avail.  If I search for an application it will find it and allow me to install it.  

### What is your operating system?

Raspbian 64bit Bullseye 4/04/22 build

**Comment by theofficialgman** [comment]
@mikepaxton please join the discord server (linked in the post that github actions sent you) and ping @theofficialgman and @Botspot and state you need help with issue.

Over the years, there have been a couple of reports of this with no assistance from the users. This needs to be debugged on the system itself meaning that either botspot or myself with remotely access your pi through teamviewer to attempt to figure out what is wrong or different with your system.

**Comment by theofficialgman** [comment]
bug has been solved in the referenced commit
