### ISSUE TITLE
How do i fix my  apt repo --Sorrry i saw this once on this repo and i cant find it again sorry again--

### ISSUE THREAD

**Issue by rbcoder117** [Botspot/pi-apps#2121]
How do i fix my apt repo it is so out of date sorry i haven't been on recently ive been busy

**Comment by Botspot** [comment]
Your question could be interpreted in two ways:
1. You own an apt repo and you need help to "fix" it.
2. Your system is configured with an apt repo that no longer works. If this is the case, you can usually poke around in `/etc/apt/sources.list.d` and find the offending file to delete.
