### ISSUE TITLE
Better Chromium does not create rules for the snap version of the browser.

### ISSUE THREAD

**Issue by Rak1ta** [Botspot/pi-apps#2122]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)

### What happened?

Version from snap-store will not receive changes

### Description

As far as I understand, all settings should be [written here](https://github.com/Botspot/pi-apps/blob/ae1e75aebac321f932f15e62c22a56ff533aa3d6/apps/Better%20Chromium/install#L18), but I do not have such a folder.
![Безымянный](https://user-images.githubusercontent.com/88277343/187172407-5502b155-a441-40e3-8707-bcdfce1dc85a.png)
The browser itself is installed.
[install-success-Better Chromium.log](https://github.com/Botspot/pi-apps/files/9443500/install-success-Better.Chromium.log)
[uninstall-success-Better Chromium.log](https://github.com/Botspot/pi-apps/files/9443501/uninstall-success-Better.Chromium.log)

> On your system, neither of these directories exist. Please reach out to Botspot for this to be fixed.

@Botspot 

### What is your operating system?

RaspiOS 32bit Debian10

**Comment by Botspot** [comment]
Better Chromium should work with Snap's version of Chromium correctly.
Additionally, the logs seem to indicate that the Pi-Apps scripts are working as expected.

@Rak1ta, exactly what problem are you experiencing? Does Chromium seem to be ignoring your preferences?

**Comment by Rak1ta** [comment]
@Botspot The script does not create this folder `/etc/chromium.d` and there are no changes in the snap version.  And in the logs you can see that there is work with files only for `/etc/chromium-browser/customizations`. I hope I'm not mistaken, but it doesn't work for me.

**Comment by Botspot** [comment]
This is the code responsible for finding, choosing, and possibly *creating* the Chromium config directory:
```bash
#determine where the Chromium customizations folder is.
if [ -d /etc/chromium.d ];then
  folder=/etc/chromium.d
elif [ -d /etc/chromium-browser/customizations ];then
  folder=/etc/chromium-browser/customizations
elif [ -d /snap/chromium ] && [ -f /snap/bin/chromium ];then
  #if Snap Chromium is installed, make the customizations folder and later make a script to source its contents
  sudo mkdir -p /etc/chromium.d
  folder=/etc/chromium.d
  
else
  error "User error: Cannot find the directory where Chromium keeps its flags! Usually this would be /etc/chromium.d or /etc/chromium-browser/customizations. On your system, neither of these directories exist. Please reach out to Botspot for this to be fixed."
fi
```
@Rak1ta, it appears you encountered an unforeseen edge case: if /etc/chromium-browser/customizations exists, then the Snap-specific code won't run.

/etc/chromium-browser/customizations is the old location for Chromium configuration; this functionality has been moved to /etc/chromium.d in later Chromium versions.
Do you happen to know why this folder exists? Do you have an old deb version of Chromium installed too? It is also possible that rpi-chromium-mods created that folder.
Please run this command to see if dpkg thinks any packages "own" the directory, or if it is a remnant folder from long ago:
```
dpkg -S /etc/chromium-browser/customizations
```

**Comment by Rak1ta** [comment]
> old deb version

Last version for Debian Buster=92.0.4515.98

> if /etc/chromium-browser/customizations exists, then the Snap-specific code won't run

But Better Chromium doesn't create folders at all `/etc/chromium.d`, i thought it was because of this.


> run this command

```
pi@raspberrypi:~ $ dpkg -S /etc/chromium-browser/customizations
chromium-browser, rpi-chromium-mods: /etc/chromium-browser/customizations
```

**Comment by Botspot** [comment]
@Rak1ta, Better Chromium was not designed to handle systems with multiple versions of Chromium installed at the same time.

You have Snap Chromium and Debian Chromium installed at once. Better Chromium did not check if both were installed, so it proceeded to only use `/etc/chromium-browser/customizations`. I think that if you ran the non-snap Chromium, the changes would come through correctly.

@Rak1ta, I will let you decide: would you like to uninstall debian chromium which should fix this issue, or do you think this is enough of a problem for other people that I should change the script to accommodate such a scenario?

**Comment by Rak1ta** [comment]
> problem

Raspberry itself is not the fastest device and it seems to me stable chrome (in my case, version 92) works better than snap. For myself, I brought out some shortcuts through web-apps so that you can quickly log in without any problems and brakes through chromium-browser.
![Безымянный](https://user-images.githubusercontent.com/88277343/187493789-da878e8b-e934-4853-bbae-566ade910fda.png)

I do not know how big a problem this is, since it has not been written about before. I wanted to have a third-party up-to-date version next to the standard browser, which I could use on a PC. If it's not difficult, I hope you can tweak the code.

**Comment by Botspot** [comment]
This should now be fixed in commit https://github.com/Botspot/pi-apps/commit/8c784039ca68bd818aef9a4e0d1fd5e162ba1131.

**Comment by Rak1ta** [comment]
@Botspot And this is how it was conceived that in Video Decode such a setting is now?
![Безымянный](https://user-images.githubusercontent.com/88277343/189209192-b00c4046-31ac-4d4a-ba9f-736ddf0bf35d.png)

**Comment by Botspot** [comment]
> @Botspot And this is how it was conceived that in Video Decode such a setting is now? I don't remember how it was before. ![Безымянный](https://user-images.githubusercontent.com/88277343/189209192-b00c4046-31ac-4d4a-ba9f-736ddf0bf35d.png)

I don't remember either. You can try uninstalling Better Chromium and relaunching chromium to see if "Video Decode" is green.

**Comment by Itai-Nelken** [comment]
I don't think the pi has hardware video decode, so that looks normal.

**Comment by Rak1ta** [comment]
@Botspot Thanks for the fix, it's working. There is only one suggestion. Should customizations be supplemented with this `--enable-raw-draw` flag? It works in snap version of Chrome. 
And hardware acceleration did not work for me in the snap version. It [says](https://ubuntuhandbook.org/index.php/2022/07/chromium-snap-package-to-finally-get-back-vaapi-hardware-decoding/) here that another browser client is needed.

**Comment by Botspot** [comment]
> @Botspot Thanks for the fix, it's working.

Perfect!

> There is only one suggestion. Should customizations be supplemented with this `#enable-raw-draw` flag? It works in snap version of Chrome.

If you find that flag actually helps improves browsing performance, then I'll consider it. I have never found any practical difference with that enabled, other than more green color in chrome://flags. :)
