### ISSUE TITLE
MysteriumNetwork VPN

### ISSUE THREAD

**Issue by GYKgamer** [Botspot/pi-apps#2123]
### What is the name of the app?

MysteriumNetwork VPN

### (Optional) Where is the app hosted?

https://github.com/mysteriumnetwork/node
https://www.mysterium.network/

### About the app

VPN instead of ip's used from the company, users can use their devices as the vpn
(Does cost 1$ to use)

### Upload file or Add PR Link

[myst_linux_arm64.zip](https://github.com/Botspot/pi-apps/files/9448023/myst_linux_arm64.zip)

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by GYKgamer** [comment]
![image](https://user-images.githubusercontent.com/41442793/187302902-cffcfc2c-4e4f-4842-99b1-0a06a681057d.png)

**Comment by GYKgamer** [comment]
Any update if this is good enough for pi-apps or not?

**Comment by theofficialgman** [comment]
given that it is paid with a likely small userbase, I don't see it as beneficial to add to pi-apps
