### ISSUE TITLE
Add tlauncher so its free to play mc 

### ISSUE THREAD

**Issue by Malaska678** [Botspot/pi-apps#213]

**Comment by ilobilo** [comment]
I think its a good idea

**Comment by mobilegmYT** [comment]
@Malaska678 TLauncher is piracy, so it is illegal, which doesn't fit the eligibility rubric mentioned at https://github.com/Botspot/pi-apps/issues/185. It also doesn't work properly on Raspberry Pi. If you really can't afford Minecraft, try https://github.com/RaspberryPiNews/Cracked-Launcher

**Comment by Botspot** [comment]
Someone on discord said that tlauncher actually works with a Microsoft account, and is not piracy.

I'll try to find it...

**Comment by mobilegmYT** [comment]
It's called ATLauncher.

**Comment by lorecast162** [comment]
TLauncher seems awfully sketchy to me. Wouldn't really touch that

**Comment by chunky-milk** [comment]
Yeah i agree @lorecast162. There are also quite a lot of grammar mistakes on the website also...

**Comment by lorecast162** [comment]
I'd much rather advice you use GDLauncher. It's open source (everything on github), _requires_ you have a mojang account and you can use it to install a good lot of modpacks too. https://github.com/gorilla-devs/GDLauncher

**Comment by mobilegmYT** [comment]
> I'd much rather advice you use GDLauncher. It's open source (everything on github), _requires_ you have a mojang account and you can use it to install a good lot of modpacks too. https://github.com/gorilla-devs/GDLauncher

GDLauncher doesn't work on arm systems. ATLauncher does work.

**Comment by lorecast162** [comment]
Oh really? It's literally an electron app...

**Comment by mobilegmYT** [comment]
There arn't any arm linux builds, compiling also doesn't work :(

**Comment by lorecast162** [comment]
Fair enough. I'm lorecast162 on Discord and am into the PiLabs discord, can you contact me there so this issue doesn't go too offtopic?

**Comment by mobilegmYT** [comment]
Sure!

**Comment by mobilegmYT** [comment]
[ATLauncher](https://atlauncher.com/) works with MS accounts, and it's planned to be added to pi-apps. I'm just waiting for the dev to add native lwjgl linking.

**Comment by gl91306** [comment]
> @Malaska678 TLauncher is piracy, so it is illegal, which doesn't fit the eligibility rubric mentioned at #185. It also doesn't work properly on Raspberry Pi. If you really can't afford Minecraft, try https://github.com/RaspberryPiNews/Cracked-Launcher

it does work

**Comment by TheElephantCoder** [comment]
TLauncher is illegal because it has pirated versions of Minecraft.
