### ISSUE TITLE
mu-editor

### ISSUE THREAD

**Issue by digibitch** [Botspot/pi-apps#2130]
### What is the name of the app?

mu-Editor

### (Optional) Where is the app hosted?

https://codewith.mu/

### About the app

Mu is a very simple to use Python editor and IDE (integrated development environment) for beginners. It’s designed to be as user-friendly and helpful as possible for new Python programmers.

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by Botspot** [comment]
I have added Mu to Pi-Apps. Thanks for the suggestion!

**Comment by digibitch** [comment]
Oh cool, Botspot!! Thanks & Cheers! 🍺👍Greetz GordonAm 17.09.2022 7:46 nachm. schrieb Botspot ***@***.***>:
I have added Mu to Pi-Apps. Thanks for the suggestion!
