### ISSUE TITLE
Minecraft Java GDLauncher does not start

### ISSUE THREAD

**Issue by Rak1ta** [Botspot/pi-apps#2131]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)

### What happened?

Wrong launch command in shortcut Minecraft Java GDLauncher/Java error

### Description

The command in the shortcut is presented in this form. Should there also be an `env` command at the beginning?
`MESA_GL_VERSION_OVERRIDE=3.3 /opt/GDLauncher/gdlauncher %U`

And also this error in the screenshot. What can be done about it? More precisely, is it possible for the default x32 to write settings for the amount of memory for java? In the settings, such items can be changed manually.
![Безымянный](https://user-images.githubusercontent.com/88277343/190892526-5760c9f9-fdff-4287-9f03-b1a77e5e886a.png)

### What is your operating system?

RaspiOS 32bit Debian10

**Comment by theofficialgman** [comment]
This is a user error and tells you as such. 32bit applications can not be allocated 4GB of memory. For java, the max is roughly 2GB on arm32. Changing it through the in launcher settings is the only way to do it

Also no, it's not my intention to pass all user env variables to gdlauncher in the .desktop file

**Comment by theofficialgman** [comment]
however, I did find where GDLauncher hardcodes 4GB as the default option in code. I can change that and rebuild even on 64bit, allocating 4GB is not a good idea https://github.com/gorilla-devs/GDLauncher/blob/69a02964f4877f85271b5cdb09123e038c3bf9ec/src/app/desktop/utils/constants.js#L16

**Comment by Rak1ta** [comment]
@theofficialgman
```
Also no
```
In this form `MESA_GL_VERSION_OVERRIDE=3.3 /opt/GDLauncher/gdlauncher %U` I get  (something like this) "Invalid shortcut file name" on startup.

**Comment by theofficialgman** [comment]
oh? I wasn't aware of that (I have opengl 4.6 so don't need that case)
I will change it then
