### ISSUE TITLE
An idea to add to Wor-Flasher

### ISSUE THREAD

**Issue by GYKgamer** [Botspot/pi-apps#2133]
### Cool ideas?

So you know how you use uup-dump to download the file, well what if the user already has a windows 10 / 11 iso they want to use. An option to use an iso image would be another good option (or just the setup files)

**Comment by Itai-Nelken** [comment]
This is the pi-apps repo. The correct place for this feature request is in the [wor-flasher](https://github.com/Botspot/wor-flasher) repo.

**Comment by Botspot** [comment]
> ### Cool ideas?
> So you know how you use uup-dump to download the file, well what if the user already has a windows 10 / 11 iso they want to use. An option to use an iso image would be another good option (or just the setup files)

Itai is correct, but to answer your question, WoR-Flasher will let you use your own ISO if you move it to the `~/wor-flasher-files/uupdump` folder, creating folders as necessary. Also, make sure the ISO file you put there contains "ARM64" somewhere in the filename for detection to succeed.

The exact code used to detect a pre-existing ISO file is included below:
```
[ -f "$(pwd)/uupdump"/*ARM64*.ISO ]
```
