### ISSUE TITLE
User error: installation via unsupported method removed unintended files

### ISSUE THREAD

**Issue by DanaGoyette** [Botspot/pi-apps#2137]
I [don't trust piping curl into bash](https://0x46.net/thoughts/2019/04/27/piping-curl-to-shell/), so I downloaded the installer script and ran it from my Downloads directory, and the script rewarded me by nuking the whole thing!  The directory was full of many years worth of various downloads that I often went back to, including some things that I doubt I could find again.  It's a good thing I made a backup last month!

I'm guessing these lines in the installer script are to blame, but the installer should really prompt before nuking it, or else provide some other way to set the directory aside from whatever the parent directory is.  
```
DIRECTORY="$(readlink -f "$(dirname "$0")")"
if [ -z "$DIRECTORY" ] || [ "$DIRECTORY" == "$HOME" ] || [ "$DIRECTORY" == bash ];then
  DIRECTORY="$HOME/pi-apps"
fi
...
      cp -af "${DIRECTORY}/data" ~/pi-apps-forced-update
      cp -af "${DIRECTORY}/apps" ~/pi-apps-forced-update
      rm -rf "$DIRECTORY"
      mv -f ~/pi-apps-forced-update "$DIRECTORY"
```

```
dana@honeycomb:~$ wget -O Downloads/pi-apps.sh https://raw.githubusercontent.com/Botspot/pi-apps/master/install
--2022-09-23 14:10:55--  https://raw.githubusercontent.com/Botspot/pi-apps/master/install
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 2606:50c0:8001::154, 2606:50c0:8000::154, 2606:50c0:8003::154, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|2606:50c0:8001::154|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 6463 (6.3K) [text/plain]
Saving to: ‘Downloads/pi-apps.sh’

Downloads/pi-apps.sh                   100%[============================================================================>]   6.31K  --.-KB/s    in 0s      

2022-09-23 14:10:55 (17.7 MB/s) - ‘Downloads/pi-apps.sh’ saved [6463/6463]

dana@honeycomb:~$ chmod +x Downloads/pi-apps.sh 
dana@honeycomb:~$ ./Downloads/pi-apps.sh 

fatal: not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
Reinstalling Pi-Apps...
cp: cannot stat '/home/dana/Downloads/data': No such file or directory
cp: cannot stat '/home/dana/Downloads/apps': No such file or directory
 rm: cannot remove '/home/dana/Downloads/gpu-utils/rickslab_gpu_utils.egg-info/PKG-INFO': Permission denied
rm: cannot remove '/home/dana/Downloads/gpu-utils/rickslab_gpu_utils.egg-info/dependency_links.txt': Permission denied
rm: cannot remove '/home/dana/Downloads/gpu-utils/rickslab_gpu_utils.egg-info/requires.txt': Permission denied
rm: cannot remove '/home/dana/Downloads/gpu-utils/rickslab_gpu_utils.egg-info/top_level.txt': Permission denied
rm: cannot remove '/home/dana/Downloads/gpu-utils/rickslab_gpu_utils.egg-info/SOURCES.txt': Permission denied
rm: cannot remove '/home/dana/Downloads/gpu-utils/build/lib/GPUmodules/GPUgui.py': Permission denied
rm: cannot remove '/home/dana/Downloads/gpu-utils/build/lib/GPUmodules/__init__.py': Permission denied
rm: cannot remove '/home/dana/Downloads/gpu-utils/build/lib/GPUmodules/env.py': Permission denied
rm: cannot remove '/home/dana/Downloads/gpu-utils/build/lib/GPUmodules/GPUmodule.py': Permission denied
rm: cannot remove '/home/dana/Downloads/gpu-utils/build/bdist.linux-aarch64': Permission denied
rm: cannot remove '/home/dana/Downloads/gpu-utils/build/scripts-3.9/gpu-chk': Permission denied
rm: cannot remove '/home/dana/Downloads/gpu-utils/build/scripts-3.9/gpu-ls': Permission denied
rm: cannot remove '/home/dana/Downloads/gpu-utils/build/scripts-3.9/gpu-mon': Permission denied
rm: cannot remove '/home/dana/Downloads/gpu-utils/build/scripts-3.9/gpu-pac': Permission denied
rm: cannot remove '/home/dana/Downloads/gpu-utils/build/scripts-3.9/gpu-plot': Permission denied
rm: cannot remove '/home/dana/Downloads/gpu-utils/dist/rickslab_gpu_utils-3.6.2-py3.9.egg': Permission denied
rm: cannot remove '/home/dana/Downloads/tuya-convert/scripts/smartconfig/__pycache__/smartconfig.cpython-310.pyc': Permission denied
rm: cannot remove '/home/dana/Downloads/tuya-convert/scripts/smartconfig/__pycache__/broadcast.cpython-310.pyc': Permission denied
rm: cannot remove '/home/dana/Downloads/tuya-convert/scripts/smartconfig/__pycache__/crc.cpython-310.pyc': Permission denied
rm: cannot remove '/home/dana/Downloads/tuya-convert/scripts/smartconfig/__pycache__/multicast.cpython-310.pyc': Permission denied
 Preloading app list...
Installation complete. Pi-Apps can be launched from the start menu or by running the command 'pi-apps'.
```

**Comment by theofficialgman** [comment]
yeah this is entirely because you did what we said not to do
we have two ways to install, you can either run
```
wget -qO- https://raw.githubusercontent.com/Botspot/pi-apps/master/install | bash
```

OR you can clone the repo and run the script
```
git clone https://github.com/Botspot/pi-apps
~/pi-apps/install
```

what you did is NOT IN ANY WAY a supported install method. you basically disregarded what we told you to do and decided to install it with your own method. by downloading the install script manually and running inside of a directory, you told pi-apps that that current folder was the pi-apps folder. the install script saw that it was missing tons of pi-apps files so it deleted it.

be more careful next time before you try installing software via an unsupported method without understanding why it works the way it does
```

**Comment by theofficialgman** [comment]
also regarding all of the things mentioned in https://0x46.net/thoughts/2019/04/27/piping-curl-to-shell/ . You already confirmed that you are perfectly OK with running it via the pipe by that webpage logic:

- in the case of this install script:
https is used to TSL comes with that ✅ 
- this is an official script from the pi-apps developers, if you trust pi-apps, you should trust our install script (hidden text attacts guaranteed to not exist) ✅ 
- this script is on github, so user agent based attacks are not possible by us ✅ 
- you ran the script after you downloaded anyway without knowning what it would do, so this is no different than piping into bash because of the above ✅

**Comment by DanaGoyette** [comment]
It's not quite right to say that I did _what you said not to do_, because there's no "don't do this" section in the readme, but you're right that I didn't do either of the two things it *did* say to do.

You're also 100% right about how I ran the script without first checking what it would do, which is the entire point of saving it to disk in the first place.  That was rather silly of me!

At most, maybe just add a note to the readme as an official feature?  Save the script in some directory, and that directory will be deleted and recreated as the pi-apps directory.

**Comment by theofficialgman** [comment]
> At most, maybe just add a note to the readme as an official feature? Save the script in some directory, and that directory will be deleted and recreated as the pi-apps directory.

I'll let botspot decide what we want to add or not to the readme. My concern with adding anything like you suggest could lead to more people trying to install that way themselves and doing it incorrectly.

**Comment by Botspot** [comment]
Now with commit 882a6beb205406ffd2c95fcb7717ad851dc2a12c, the install script will look more closely at the directory it's running from, to ensure it really is a pi-apps directory, before overwriting it.
Specifically, before proceeding as if its parent directory is to be treated as the pi-apps repo folder, it verifies that the files `gui` and `api` exist.
