### ISSUE TITLE
Iconswitch - A github download project

### ISSUE THREAD

**Issue by MemeManMemes** [Botspot/pi-apps#2138]
### What is the name of the app?

Iconswitch

### (Optional) Where is the app hosted?

https://github.com/MemeManMemes/iconswitch

### About the app

This app replaces system icon files located in **/usr/share/icons/PiXflat** with one that the user provides.  After the command has been executed and the system has been rebooted, the new changes will appear.

### Upload file or Add PR Link

[iconswitch.zip](https://github.com/Botspot/pi-apps/files/9641091/iconswitch.zip)

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by theofficialgman** [comment]
I'm going to be honest, from looking at the github repo having this as C++ as oposed to as simple bash script makes it significantly worse. now your code is non-portable and you need to compile it per architecture. Every finename being hardcoded is not good.

This is also only useful for one theme (piOS PiXflat) and many users of pi-apps won't have that theme installed or even available (users using ubuntu or using other themes).

For those reasons, I am closing.

**Comment by MemeManMemes** [comment]
Interesting straight-forward reply.  I'm going to remake this as a bash
script and implement an automatic theme-checking system.
