### ISSUE TITLE
I want to know what happened to a lot of apps on the pi apps store,

### ISSUE THREAD

**Issue by cheesecat123** [Botspot/pi-apps#2141]
### Cool ideas?

I took a break from using my raspberry pi to get it serviced and when i got it back a lot of apps i had been using had become unsupported and some apps i accidentally deleted were missing like the wine installers that i needed for a project to do with roblox.

P.S. Speacking of roblox what the hell happened to grapejuice!

**Comment by theofficialgman** [comment]
you are probably not aware but there have been changes to piOS in the past year.
Previously, debian buster armhf was the only supported and default OS from the pi foundation. now the default is debian bullseye (a newer debian version). In addition, armhf (32bit arm) is not the default anymore, arm64 (64bit arm) is the default OS image.

You likely had an armhf image on your pi before and are now running an arm64 image. Refer to our app list for compatibility with our supported apps https://github.com/Botspot/pi-apps/wiki/Apps-List not all apps are both armhf and arm64 compatible (some are only one or the other). this is clearly shown in the app list at the link.

**Comment by theofficialgman** [comment]
in particular with wine. from pi-apps it is ARM32 only.
The current script is basically a total hackjob and I don't think anyone wants to or has the time to touch it. So in its current iteration it will stay as ARM32 only.
