### ISSUE TITLE
Visual bug in installation script

### ISSUE THREAD

**Issue by Rak1ta** [Botspot/pi-apps#2147]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)

### What happened?

Erroneous installation error display

### Description

I've noticed this before, but haven't figured out why. I noticed that if one of the applications was installed with an error (the link is not available, etc.), when installing subsequent applications in the queue, what is shown in the screenshot is displayed.
![Безымянный](https://user-images.githubusercontent.com/88277343/194771369-2aadbc1a-f16d-4811-b385-cd5a9633afa2.png)

### What is your operating system?

RaspiOS 32bit Debian10

**Comment by theofficialgman** [comment]
I have not noticed this ever.
was the uninstall of system monitoring center unsuccessful and then the install was succesful? do you have any more information to provide?

**Comment by Rak1ta** [comment]
@theofficialgman System monitoring center and other programs are installed successfully. Error notification - erroneous

**Comment by theofficialgman** [comment]
sorry I didn't get to this sooner. found the bug (variable was getting set and then never cleared). will fix shortly
