### ISSUE TITLE
Preliminary check of possibility of updating.

### ISSUE THREAD

**Issue by Rak1ta** [Botspot/pi-apps#2149]
### Cool ideas?

Is it possible for pi-apps to check if the install script can be executed when updating applications? For example, I update the Flow browser. Pi-apps checks the script for the successful completion of the package download command. Enter a separate file with links to sites from which the installation is performed. If the site is available, reinstallation is performed. As far as possible (for third-party sites).
```
Flow
https://support.ekioh.com/
```
```
Cawbird
http://download.opensuse.org/
```
```
Worldpainter
https://www.worldpainter.net/
```

**Comment by theofficialgman** [comment]
please re-explain in proper english. what is your goal here? pi-apps already checks these applications for updates on a weekly basis, this was decided on as the best way moving forward and will not be changed.

also, cawbird installs via an apt repository, so its updates are not handled by pi-apps anymore but instead the users apt install

**Comment by Rak1ta** [comment]
@theofficialgman I'll try to describe the use case. 
I want to install/update the Worldpainter application -> I press the "update" button -> pi-apps checks if the application is in the list * for verification -> checks the accessibility to the worldpainter site https://www.worldpainter.net/ -> if successful then the update script starts.

```
app "Flow"
link https://support.ekioh.com/
app "Worldpainter"
link https://www.worldpainter.net/
```

I propose to do so in order to exclude the situation when pi-apps deleted the application, but could not install it due to lack of access to the program website.

> pi-apps already checks these applications for updates on a weekly basis

It's not what I tried to explain :(

**Comment by theofficialgman** [comment]
oh you are concerned about online servers being down.
pretty much all of our applications have hosts with 99.9% uptime so this really isn't necessary.
we only very occasionally get errors due to online servers being offline.

this would really be redundant because we do want error reports incase a server is offline. so the current system is good for that in this case.
