### ISSUE TITLE
Application does not open after install

### ISSUE THREAD

**Issue by theparthway** [Botspot/pi-apps#2152]
Pi-apps does not execute after fresh installation, no matter where I try to open it from, desktop, terminal or installation location. I have a pi 4 8gb ram.

**Comment by cycool29** [comment]
Can you run `pi-apps` from the terminal and send the output here?

**Comment by Scoob1978** [comment]
I have the same issue. This is my error when I try to run theme converter. It's a fresh install.

bo@raspberrypi:~ $ themeconverter 
Traceback (most recent call last):
  File "/home/bo/.local/share/MacOSBigSurThemeConverter/gui.py", line 8, in <module>
    WindowIcon = PhotoImage(file = '/home/pi/.local/share/MacOSBigSurThemeConverter/assets/Icons/MacOSBigSurThemeConverterLogo.png')
  File "/usr/lib/python3.9/tkinter/__init__.py", line 4064, in __init__
    Image.__init__(self, 'photo', name, cnf, master, **kw)
  File "/usr/lib/python3.9/tkinter/__init__.py", line 4009, in __init__
    self.tk.call(('image', 'create', imgtype, name,) + options)
_tkinter.TclError: couldn't open "/home/pi/.local/share/MacOSBigSurThemeConverter/assets/Icons/MacOSBigSurThemeConverterLogo.png": no such file or directory
