### ISSUE TITLE
Minecraft Bedrock installer broken (at least on bullseye 64-bit)

### ISSUE THREAD

**Issue by bagong** [Botspot/pi-apps#2153]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)

### What happened?

App won't install, uses badly outdated install script, messes up 64-bit system

### Description

The Minecraft Bedrock launcher by now (and this has been so for quite some time!) uses an AppImage that requires no additional libs at all. Just download the AppImage and create an desktop icon. Currently 64-bit systems are unnecessarily contaminated with 32-bit libs, and on top of it the install breaks...

### What is your operating system?

RPI OS 64-bit bullseye

**Comment by bagong** [comment]
The only dependency required is fuse

**Comment by theofficialgman** [comment]
This is incorrect.
In order to play the older versions of Minecraft with were only arm32 on Android, the system still needs armhf multiarch which is why the script still has it included.

This has been confirmed functional on multiple fresh installs without any dependency conflicts.

**Comment by bagong** [comment]
Ah, okay, sorry, I didn't think of old versions! So likely my install crash is due to having compiled a more recent mesa driver for vulkan. Sorry for the noise. (I'll set up a fresh Pi OS and come back should I still get the same crash)
