### ISSUE TITLE
Minecraft Java Prism Launcher does not start

### ISSUE THREAD

**Issue by Rak1ta** [Botspot/pi-apps#2156]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)

### What happened?

Missing libraries error on startup

### Description

I thought that I did not have any of the packages installed, so I installed the one suggested by the Debian site, [libicu-dev](https://packages.debian.org/search?suite=buster&section=all&arch=any&searchon=contents&keywords=libicui18n.so) and [libmng-dev](https://packages.debian.org/search?suite=buster&section=all&arch=any&searchon=contents&keywords=libmng.so).  And more I do not understand what I can do, because I do not know.
 
![Безымянный](https://user-images.githubusercontent.com/88277343/196915290-d7521ce0-a2be-4125-9280-d0c253b8501a.png)

### What is your operating system?

RaspiOS 32bit Debian10

### (Optional) Error log? Terminal output? Debug messages?

```bash
pi@raspberrypi:~ $ env MESA_GL_VERSION_OVERRIDE=3.3 prismlauncher
Launcher Dir: /usr/share/prismlauncher
Error: The launcher is missing the following libraries that it needs to work correctly:
	libicui18n.so.60, libicuuc.so.60, libmng.so.2, 
Please install them from your distribution's package manager.

Hint (please apply common sense):
```

**Comment by theofficialgman** [comment]
was made aware in the discord a few hours ago. this specific issue (and other potential problems) should be solved as of
https://github.com/Botspot/pi-apps/commit/0a6509a118ed9f37531cc99f96e775d9f0f5b23c
https://github.com/Botspot/pi-apps/commit/2c960393705dd2bb6ae4fa5bce8e391453f7cf9d

**Comment by theofficialgman** [comment]
if there are more issues, I will re-open
