### ISSUE TITLE
Uninstall

### ISSUE THREAD

**Issue by Paranoi8972** [Botspot/pi-apps#2159]
I´m using the official PiOs 32 bit, everything is up to date. I installed some applications. I don´t need them anymore and want to uninstall them on the usual way but the terminal 
don´t open. Then I uninstalled and installed it but it doesn´t work now. Installing too.
Yours sincerely
Clemens aka. Paranoia8972

**Comment by theofficialgman** [comment]
please use the bug report issue template. your description lacks adequate information and clarity.
it may be better for you to recieve assistance via the discord server linked above as well
