### ISSUE TITLE
Notepad ++

### ISSUE THREAD

**Issue by techcoder20** [Botspot/pi-apps#216]
There is already sublime text running with box86 on pi apps so I thought why not add notepad ++ to pi apps.

**Comment by Itai-Nelken** [comment]
notepad ++ runs great under box86 + wine, so unless there is a Linux version I don't know about the wine"app" has to be finished first.

**Comment by nielsbaloe** [comment]
Actually, Notepad++ is not necessary because RaspberryPI-OS comes with an app that is nearly identical to Notepad++. It is called Geany. I switch between Notepad++ and Geany a few times a day and it is really really the same thing regarding editing textfiles and sourcecode (and similar as programming IDE).

**Comment by Botspot** [comment]
I think many people would still enjoy running Notepad ++ for the fun of it, even if Geany is perfectly sufficient.

@mobilegmYT, you sent me an "armhf version" of Notepad ++ in Discord. How to run that? Is it a Windows app? Would it require armhf WINE to run it? Or the x86 WINE app?

**Comment by mobilegmYT** [comment]
> I think many people would still enjoy running Notepad ++ for the fun of it, even if Geany is perfectly sufficient.
> 
> @mobilegmYT, you sent me an "armhf version" of Notepad ++ in Discord. How to run that? Is it a Windows app? Would it require armhf WINE to run it? Or the [x86 WINE app](https://github.com/Botspot/pi-apps/issues/151)?

It's a 32-bit windows app. You need wine to run it.

**Comment by mobilegmYT** [comment]
@Botspot You just need to download and run this with wine. https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v7.9.2/npp.7.9.2.portable.zip

**Comment by Botspot** [comment]
> It's a 32-bit windows app. You need wine to run it.

But you said it's **armhf**. That right there is unconventional. Most Windows apps are x86. So which is it, will an x86 WINE run what you sent me, or not?

**Comment by mobilegmYT** [comment]
Yes, x86 wine will run it, since it's 32-bit windows. Sorry for the bad communication about that.

**Comment by Botspot** [comment]
OK, it worked fine for me.
Let's wait for the WINE app to be added before making this app.

**Comment by techcoder20** [comment]
@Botspot can we add this now that wine had been added ?

**Comment by Itai-Nelken** [comment]
I'll write the scripts.

**Comment by Botspot** [comment]
> @Botspot can we add this now that wine had been added ?

@techcoder20 Yeah, let's do it. I already have WACUP ready-to-go, but would like to have three Windows apps ready to put in their own "Windows apps" category.

**Comment by techcoder20** [comment]
@Botspot I am done with the app :), sry for the delay 

[Notepad ++.zip](https://github.com/Botspot/pi-apps/files/6163586/Notepad.%2B%2B.zip)

**Comment by Itai-Nelken** [comment]
[Notepad ++.zip](https://github.com/Botspot/pi-apps/files/6163849/Notepad.%2B%2B.zip)
@techcoder20 I added the `-f` flag to the `rm` command in the start of the `install-32` script.
without that if the file and folder its trying to remove are not there which is most likely it will fail to install.

**Comment by techcoder20** [comment]
Thx 😁

**Comment by Botspot** [comment]
> To Run:  Menu -> Accessories -> Sublime Text

**Comment by Botspot** [comment]
Wow that installation was fast!

I'll fix the description and add it.

**Comment by Botspot** [comment]
Okay, it may take a while. I came across bug after bug. Each bug was unrelated to the last, but I've found 4 various ones so far.

Fixing them one by one... (and finding two more for each one I fix!)

**Comment by Botspot** [comment]
There. All bugs fixed, and Notepad++ has been added with commit e12ae48466c4943a35e9ccbe91edbe68a6235ffc
