### ISSUE TITLE
Some apps should/need to be updated

### ISSUE THREAD

**Issue by theofficialgman** [Botspot/pi-apps#2160]
This is a meta issue for applications that we are aware of that need/should be updated due to considerable addition of features and/or bugfixes from upstream:

- AntimicroX
  - New releases have been made upstream with support for Gyro/motion controls but require that a very recent version of SDL2 be bundled with the application
  - maybe we should consider using the flatpak instead
- Stunt Rally
  - needs to be re-built against static libboost so that the deb can work on multiple distros
  - version 2.7 was released recently https://github.com/stuntrally/stuntrally/releases/tag/2.7

**Comment by Rak1ta** [comment]
> Xsnow

The compiled version 3.5.3 works on Buster armhf, but I don't know which packages should be kept/removed as dependencies.

**Comment by theofficialgman** [comment]
the dependencies for the armhf package are as follows
```
Depends: libc6 (>= 2.29), libcairo2 (>= 1.14.0), libgcc-s1 (>= 3.5), libgdk-pixbuf-2.0-0 (>= 2.22.0), libglib2.0-0 (>= 2.28.0), libgsl25 (>= 2.6), libgtk-3-0 (>= 3.9.10), libstdc++6 (>= 5), libx11-6, libxext6, libxpm4
```
libc6 is 2.28 on buster. other packages may also be too new. I have not checked the binary itself to see if it is compatible

**Comment by theofficialgman** [comment]
turns out building OBS 28.X itself hasn't been too hard once I got QT6 installed. ffmpeg 4.X+ so far doesn't seem like a hard requirement. the problem comes when building the browser source CEF which now is built on the version where the ARM64 glibc reversion script was disabled in chromium. it STILL has not been re-enabled, I'm working on getting google chromium developers to do that upstream here: https://chromium-review.googlesource.com/c/chromium/src/+/3938615/2

**Comment by theofficialgman** [comment]
update, the patch was merged at chromium a few weeks ago and it has made its way to chromium 111

**Comment by everypizza1** [comment]
What about Godot? I think you can get 4.0 on the pi.

**Comment by theofficialgman** [comment]
> What about Godot? I think you can get 4.0 on the pi.

@everypizza1 Godot wasn't a candidate for an autoupdater due to this https://github.com/Botspot/pi-apps/pull/2182#issuecomment-1317911072 and the original person to add it to pi-apps hasn't submitted a PR for updating. It could be updated but one of those two things has to change (upstream needs to stabilize their packaging system or the @NoozSBC needs to keep it updated here)

**Comment by Renetrox** [comment]
sorry to intrude, but since we are dealing with this topic or suggestion, PPSSPP is not updated two years ago

**Comment by harmvuijk** [comment]
I'm not sure if this is the right place to ask, but MuseScore in pi-apps is at version 4.0.2 while the current version is 4.1.1 released July 26th. Any possibility to update to the latest version?

**Comment by theofficialgman** [comment]
> I'm not sure if this is the right place to ask, but MuseScore in pi-apps is at version 4.0.2 while the current version is 4.1.1 released July 26th. Any possibility to update to the latest version?

@harmvuijk Musescore is my porting project to ARM Linux. Unfortunately we were unable to build Musescore for ARM on Bionic CI due to a QEMU bug for the past few months. With Pi-Apps now dropping Buster/Bionic support that means I was able to upgrade the CI at Musescore to workaround a few more QEMU bugs. You can expect a newer version of Musescore to come to pi-apps in a day or so, just be patient as I am quite busy.

Future versions of Musescore should come out for ARMhf and ARM64 officially from Musescore if they choose the run the CI for it after this PR merges https://github.com/musescore/MuseScore/pull/18575

**Comment by theofficialgman** [comment]
> Any possibility to update to the latest version?

@harmvuijk it has now been updated. this was in no way affected by you asking btw. I had already solved all the issues yesterday and just needed time for slow internet to upload

**Comment by harmvuijk** [comment]
Great, thanks a lot!
