### ISSUE TITLE
Fix the search bar

### ISSUE THREAD

**Issue by GYKgamer** [Botspot/pi-apps#2161]
### Cool ideas?

The search only searches in the current directory, but to save time the search at the home screen
![image](https://user-images.githubusercontent.com/41442793/197387882-b5485232-7392-451e-b18a-154ac3f22bc3.png)
Could search through "All apps" as if you search in the start menu it only searches in the start menu (which has no apps)

**Comment by theofficialgman** [comment]
that is outside of our control. the menu you are looking at is generated by xlunch and we pass in the options as input to it. the searchbar is just functionality of xlunch and it just searches from the available listed options. 

https://xlunch.org/
