### ISSUE TITLE
32bit to 64bit

### ISSUE THREAD

**Issue by SudoAptonator** [Botspot/pi-apps#2163]
### Cool ideas?

I would like if you guys could please add the 32bit apps onto the 64bit pi-apps. I logged onto my 32bit Raspberry pi and downloaded Pi-Apps and I saw how There was a lot of apps on the 32bit Raspberry pi that the 64bit one did not have. Could you please suggest this? -SudoAptonator

**Comment by theofficialgman** [comment]
We are aware that not all applications are available on 64bit. you can find the list of all pi-apps applications here:
https://github.com/Botspot/pi-apps/wiki/Apps-List
Simply control+f and search for "arm32 only" and that will give you 20 apps. some of these apps are proprietary and only built for arm32 systems so cannot be brought over to native arm64 systems. Some apps just need a lot of work and developers don't have the hardware or time to port these apps over. There are also 8 apps that are arm64 only (for similar reasons). the vast majority of apps are supported on both arm32 and arm64 (150 apps plus an additional 36 package apps).

closing as this as a known suggestion.
