### ISSUE TITLE
The Battle for Wesnoth install script

### ISSUE THREAD

**Issue by alberic89** [Botspot/pi-apps#2167]
### What is the name of the app?

The Battle for Wesnoth

### (Optional) Where is the app hosted?

Sourceforge

### About the app

I have make a .deb package of The Battle for Wesnoth, and this script install it.

The Battle for Wesnoth is an [open source](https://opensource.org/faq#osd), turn-based strategy game with a high fantasy theme. It features both singleplayer and online/hotseat multiplayer combat.

Explore the world of Wesnoth and take part in its many adventures! Embark on a desperate quest to reclaim your rightful throne... Flee the Lich Lords to a new home across the sea... Delve into the darkest depths of the earth to craft a jewel of fire itself... Defend your kingdom against the ravaging hordes of a foul necromancer... Or lead a straggly band of survivors across the blazing sands to confront an unseen evil.

The choice is up to you...

### Upload file or Add PR Link

[The Battle for Wesnoth.zip](https://github.com/Botspot/pi-apps/files/9886576/The.Battle.for.Wesnoth.zip)

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by theofficialgman** [comment]
just wanted to post since you didn't add any website or link to the project. it has moved over to a fully github based source repository. sourceforge seems to only be a read only mirror https://github.com/wesnoth/wesnoth

**Comment by theofficialgman** [comment]
I took a lot at your debs. Unfortunatly, boost is one of the dreaded versioned libraries that a lot of applications depend on. buster/bionic/bullseye all have different libboost versions and this makes distributing one deb to work on all of those distros difficult.

see how your binary depends on libboost 1.74.0 and only that version
```
	libboost_iostreams.so.1.74.0 => not found
	libboost_program_options.so.1.74.0 => not found
	libboost_regex.so.1.74.0 => not found
	libboost_random.so.1.74.0 => not found
	libboost_locale.so.1.74.0 => not found
	libboost_filesystem.so.1.74.0 => not found
```

how long does it take to build wesnoth on your system (I assume a pi) because it may be better to have this as a buildscript.

there are also a few issues with your debs regardless. you are packaging the `var/run` folders.. those shouldn't be in a deb. you also don't need to specify the dependencies in the install script, your deb already includes them in its control file.
```
Depends: libboost-filesystem-dev (>= 1.66.0), libboost-locale-dev (>= 1.66.0), libboost-iostreams-dev (>= 1.66.0), libboost-random-dev (>= 1.66.0), libboost-regex-dev (>= 1.66.0), libboost-program-options-dev (>= 1.66.0), libboost-system-dev (>= 1.66.0), libboost-coroutine-dev (>=1.74.0), libsdl2-2.0-0, libsdl2-image-2.0-0, libsdl2-mixer-2.0-0, libfontconfig-dev, libcairo1.10-cil, libpango1.0-0, libvorbis-dev, libbz2-dev, libz3-dev, libcrypto++-dev, libssl-dev
```
this control file is also technically wrong. since it specifies a >= liboost version when as shown above your build only works with = 1.74.0

**Comment by theofficialgman** [comment]
also your binaries depend on glibc 2.35+ (can't run on buster/bionic/bullseye) you must be building on bookwork or jammy

**Comment by alberic89** [comment]
Thanks for all the feedback, I guess you figured it out, I'm new to packing.

(Excuse the mistakes and the maybe strange turns of phrase, I am French)

First of all, the Battle for Wesnoth project is a project developed by a team of volunteers, with the homepage at [wesnoth.org](wesnoth.org), the source code at [github.com/wesnoth/wesnoth](github.com/wesnoth/wesnoth), and the releases on [sourceforge](https://sourceforge.net/projects/wesnoth/). I created a small project that gets the source packages from sourceforge, compiles them for rspi and sends them to a project of mine that is also on [sourceforge](https://sourceforge.net/projects/battle-for-wesnoth-arm-build/), but separate from the official project. The pi-apps script installs the dependencies, downloads and installs one of my packages. I tested it, and it works normally for versions 1.16.8 and 1.17.9.

I've packaged everything with a clean version of Raspberry Pi OS, (with an R-pi 4B 4GB) fully updated on stable. Normally, the game should run on any Raspberry with the bullseye repositories (it doesn't even need an X server!)
Not wanting to dive too deep into the arcana of packaging, I used the checkinstall utility in a little script I made (and I'm attaching it, I had to rename .sh to .txt to make it go to github.).
[Wesnoth-1.16.6.txt](https://github.com/Botspot/pi-apps/files/9895668/Wesnoth-1.16.6.txt)
[Wesnoth-1.17.9.txt](https://github.com/Botspot/pi-apps/files/9895669/Wesnoth-1.17.9.txt)
I didn't know that checkinstall had included the dependencies in the package. For the libboost versions, I relied on what the INSTALL file said, but I installed the latest version to compile.

I didn't have any problem with glibc, which package did you test? (be careful, in the sourceforge project there is also a 1.0.2 package, which needs an advanced version of libstdc++6, I don't know why!)

**Comment by alberic89** [comment]
I apologize for my long absence.
I created an installation script instead, it takes about 15–30 minutes, depending on the internet connection and the responsiveness of the SD card.
The script starts by going to the /tmp folder, asks the user which version he wants to install, downloads the source code, extracts it, compiles it and installs it.
[The Battle for Wesnoth.zip](https://github.com/Botspot/pi-apps/files/10328749/The.Battle.for.Wesnoth.zip)

**Comment by theofficialgman** [comment]
I think at this point it might be best to use the official flatpak from the developer
its much easier that way even though it will only be for arm64

**Comment by alberic89** [comment]
As you wish.
Personally, I don't like Flatpak very much, especially on the Raspberry Pi because it takes a lot of space in “temporary” files, and is slower to start.
