### ISSUE TITLE
using a usb

### ISSUE THREAD

**Issue by scrapboy13** [Botspot/pi-apps#217]
if you a usb to boot with pi apps you can not in stall serton apps some work and some dont most dont

**Comment by Itai-Nelken** [comment]
I use usb boot and everything works perfectly fine.

**Comment by Botspot** [comment]
I also USB boot and all the apps work.

**Comment by scrapboy13** [comment]
i will try again but some worked and some did not i will try it again with a different usb

**Comment by scrapboy13** [comment]
it was something at the top saying directory does not exist and can not create one

**Comment by Itai-Nelken** [comment]
@scrapboy13 I'm not sure I understand, did the apps install but have a error on the top? was it this: `cat: /home/pi/pi-apps/data/status/Browsh: No such file or directory` but change `Browsh` with the app you are installing?
if yes thats normal.

**Comment by fabianmendes** [comment]
Otherwise, is that possible to install pi-apps on specific storage or partition??

**Comment by Botspot** [comment]
> Otherwise, is that possible to install pi-apps on specific storage or partition??

In theory, Pi-Apps should be installable anywhere, though it may fail to create menu buttons for you in some locations. Oh, and I think Pi-Apps won't work well if you `git clone` it into a directory structure containing a space ( ) character.

**Comment by Botspot** [comment]
I think this issue can be closed now. Right?

**Comment by fabianmendes** [comment]
> > Otherwise, is that possible to install pi-apps on specific storage or partition??
> 
> In theory, Pi-Apps should be installable anywhere, though it may fail to create menu buttons for you in some locations. Oh, and I think Pi-Apps won't work well if you `git clone` it into a directory structure containing a space ( ) character.

Where are the apps installed?



> I think this issue can be closed now. Right?

right

**Comment by Botspot** [comment]
> Where are the apps installed?

Anywhere really. Pi-Apps may be better described as a *catalog of recipes* for apps, not an app store.

**Comment by scrapboy13** [comment]
you could not use most of the apps  it did say cat: /home/pi/pi-apps/data/status/Browsh: No such file or directory but five or more times and at the end sead could not create or something like that
