### ISSUE TITLE
funktioniert nicht respbarry pi 4 FreeTube

### ISSUE THREAD

**Issue by odimmel** [Botspot/pi-apps#2171]
FreeTube nach neue update startet nicht nicht mehr

**Comment by theofficialgman** [comment]
please use english for creating issues, you can use a translater like https://translate.google.com/.
also use the bug report issues template for issues of this type.

you need to supply more information on your issue: refer to the bug report template https://github.com/Botspot/pi-apps/issues/new?assignees=&labels=bug&template=bug-report.yml

**Comment by theofficialgman** [comment]
I will close stale issues. please obey the issue form requests you have agreed to.

- [X] IMPORTANT: I promise to respond to comments on this issue and write a good bug report https://www.softwaretestinghelp.com/how-to-write-good-bug-report/
