### ISSUE TITLE
My Website

### ISSUE THREAD

**Issue by SudoAptonator** [Botspot/pi-apps#2175]
### My Website

I have a Website that has tutorials and stuff like that. And I was Wondering, is it ok if I can add Pi-Apps code on my Website? (Just making sure for copy right reasons)

**Comment by theofficialgman** [comment]
I took a look at your website as it is currently.
Are you asking if its ok for you to have the website as it is right now? where you have the install command for pi-apps.

or are you looking to add copy the code of pi-apps and use it for building your website?

or are you looking to do something else?

just give an example of what you plan to do, I think that will help with explaining.

**Comment by SudoAptonator** [comment]
"Are you asking if its ok for you to have the website as it is right now? where you have the install command for pi-apps."
Yes im wondering if its ok if i can have the pi-apps download in my website

**Comment by theofficialgman** [comment]
yes, it is fine to reference the install command for pi-apps on your website as you have done.
