### ISSUE TITLE
Pi-apps wont run YAD install issue?

### ISSUE THREAD

**Issue by helpmeprettyplease** [Botspot/pi-apps#2180]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)

### What happened?

Pi-apps wont run YAD install issue?

### Description

Pi-apps wont run. After Pi-apps install it wont run at all. When trying through terminal i get "YAD needs to be installed to run Pi-Apps." I'm a total noob so I don't know what that means and I can't find any answers online. HELP!

### What are your system specs (run the following command in your terminal)?

```bash
OS: Raspbian GNU/Linux 11 (bullseye)
OS architecture: 32-bit
Last updated Pi-Apps on: 11/12/2022
Latest Pi-Apps version: 11/12/2022
Kernel: armv7l 5.15.61-v7l+
Device model: Raspberry Pi 400 Rev 1.0 
Cpu name: Cortex-A72
Ram size: 3.83 GB
Raspberry Pi OS image version: 2022-09-22
Language: en_US.UTF-8
```

**Comment by theofficialgman** [comment]
Running the install command installs yad and all dependencies. What is the terminal output from
```
wget -qO- https://raw.githubusercontent.com/Botspot/pi-apps/master/install | bash
```

**Comment by theofficialgman** [comment]
closing due to lack of response.

if you need help, you need to respond to requests for information. if apt says that yad is installed and you still get this error, then your SD card is likely corrupt and you will need to re-flash your OS
