### ISSUE TITLE
Pixelorama

### ISSUE THREAD

**Issue by fmfarrand** [Botspot/pi-apps#2185]
### What is the name of the app?

Pixelorama

### (Optional) Where is the app hosted?

https://github.com/Orama-Interactive/Pixelorama/releases

### About the app

Pixelorama is a free and open source dedicated pixel art editor by Orama Interactive. Here are some of its advertised features:

- Animation support.
- Custom brushes, including random brushes.
- Create or import custom palettes.
- Import images and edit them inside Pixelorama. If you import multiple files, they will be added as individual animation frames. Importing spritesheets is also supported.
- Export as PNG, as a single file, a spritesheet or multiple files, or GIF file.
- Pixel perfect mode for perfect lines, for the pencil, eraser & lighten/darken tools.
- Autosave support, with data recovery in case of a software crash.
- Horizontal & vertical mirrored drawing.
- Tile Mode for pattern creation.
- Rectangular & isometric grid types.
- Scale, rotate and apply multiple image effects.
- Multi-language localization support!

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by theofficialgman** [comment]
I'll look into seeing if we can convince/implement 64bit ARM support upstream since it should be trivial. Pixelorama uses the Godot engine but only makes an armhf (arm32) package.

my guess is we will end up having to build godot ourselves for ARM64 since I imagine the developers at https://github.com/hiulit/Unofficial-Godot-Engine-Raspberry-Pi build their ARM64 releases on bullseye and we strive to support buster for ARM32 and ARM64 (with my personal goal of even older using ubuntu bionic)

**Comment by theofficialgman** [comment]
yup as I feared. binaries link to GLIBC 2.29
```
./godot_3.5.1-stable_rpi4_editor.arm64: /lib/aarch64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by ./godot_3.5.1-stable_rpi4_editor.arm64
```
we will need to build godot ourselves inorder to support this application and build pixelorama to use it

**Comment by fmfarrand** [comment]
Didn't realize it'd be that complicated. Thanks for looking into it, at least.

**Comment by theofficialgman** [comment]
this can stay open. I think there is still merit to the application even if its not as simple as first glance.

**Comment by theofficialgman** [comment]
@fmfarrand added in the above commit
I compiled godot from source on aarch64 and armv7l on ubuntu bionc and built pixelorama for both these platforms
