### ISSUE TITLE
zoom not working

### ISSUE THREAD

**Issue by gadido30** [Botspot/pi-apps#2186]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)
- [X] IMPORTANT: I promise to respond to comments on this issue and write a good bug report https://www.softwaretestinghelp.com/how-to-write-good-bug-report/

### What happened?

Error loading needed lib libffmpeg.so

### Description

Hi All

I have downloaded latest zoom client,
When I tired to run zoom client , it show an error: "libffmpeg.so" is missing, any idea?

The old zoom client work perfect

### What are your system specs (run the following command in your terminal)?

```bash
S: Ubuntu 22.04.1 LTS
OS architecture: 64-bit
Last updated Pi-Apps on: 11/16/2022
Latest Pi-Apps version: 11/17/2022
Kernel: aarch64 5.15.0-1017-raspi
Device model: Raspberry Pi 400 Rev 1.0 
Cpu name: Cortex-A72
Ram size: 3.78 GB
Language: en_US.UTF-8
```

### (Recommended) Error log? Terminal output? Debug messages?

```bash
Dynarec for ARM64, with extension: ASIMD CRC32 PageSize:4096 Cores:4
Box64 with Dynarec v0.1.9 c0d19de0 built on Nov 16 2022 06:48:09
Using default BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/
Using default BOX64_PATH: ./:bin/
Counted 52 Env var
Looking for ./zoom
Zoom detected, trying to use system libturbojpeg if possible
Rename process to "zoom"
Using emulated libcef.so
Error loading needed lib libffmpeg.so
Error loading one of needed lib
Error: loading needed libs in elf /home/user1/zoom/zoom
```

**Comment by theofficialgman** [comment]
I'll have to ping @ryanfortner for this.
I've never looked into zoom until just now. why does your zoom_x64_libs tarfile exist? the zoom tarfile has cef and other libraries in it already?

**Comment by theofficialgman** [comment]
I wasn't able to launch as-is. I needed to specify CEF in the BOX64_LD_LIBRARY_PATH, remove your libcef.so, and also specify for box64 to keep some libraries emulated (to avoid an error from gsettings)
`Error: PltResolver: Symbol g_settings_schema_source_get_default(ver 1: g_settings_schema_source_get_default) not found, cannot apply R_X86_64_JUMP_SLOT 0x7faa4dfc88 (0x7fa9dd4e86) in ./cef/libcef.so
`

so this is what I ran with your files extracted to another directory and libcef delted from your files:
```
BOX64_EMULATED_LIBS=libgobject-2.0.so.0:libgbm.so.1:libgio-2.0.so.0:libglib-2.0.so.0:libgthread-2.0.so.0 BOX64_LD_LIBRARY_PATH=./cef:../zoom_x64_libs box64 zoom --no-sandbox
```

**Comment by ryanfortner** [comment]
> I'll have to ping @ryanfortner for this.
> I've never looked into zoom until just now. why does your zoom_x64_libs tarfile exist? the zoom tarfile has cef and other libraries in it already.

If I remember correctly, if a native system library isn't "wrapped" by box64, the x64 version needs to be present. I packaged all these non-wrapped x64 libraries into one compressed archive. Some examples of missing libraries can be found in the box64/86 issues: [here](https://github.com/ptitSeb/box64/issues/17) is an example.

**Comment by rbcoder117** [comment]
Hi guys i wanted to check back and also zoom is extremely buggy last i checked. Also it crashes a lot back when i used to use it. If this is outdated sorry this was like 4-5 months ago.

**Comment by temporarium** [comment]
This particular issue is easily solved by creating the missing link:
`ln -s ~/zoom/cef/libffmpeg.so ~/zoom`

**Comment by Botspot** [comment]
Fixed with https://github.com/Botspot/pi-apps/commit/3a41b272167576b75bf9735fa283135438bbe28c
