### ISSUE TITLE
No catigories

### ISSUE THREAD

**Issue by KilixGT** [Botspot/pi-apps#2187]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [ ] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)
- [X] IMPORTANT: I promise to respond to comments on this issue and write a good bug report https://www.softwaretestinghelp.com/how-to-write-good-bug-report/

### What happened?

I install pi apps but i cannot see any catigories

### Description

when i install pi apps on Raspberry Pi Bullseye there is no catigories on app, so i can install any app!
![16687088920285266182540965906747](https://user-images.githubusercontent.com/88561149/202525333-34fc592b-50eb-4b58-9e7c-f7e5544a0f8f.jpg)

### What are your system specs (run the following command in your terminal)?

```bash
Raspbian OS Bullseye
Raspberry Pi 3 b+
Ram 1 gb
Boot: Berryboot
```

### (Recommended) Error log? Terminal output? Debug messages?

```bash
pipe is /tmp/tmp.oeLvXeoJlj

Updater mode: set-status

Checking for online changes... Timestamps don't match
Generating list for ''...
Done
Finished preload for ''
Scanning apps... Done
Scanning files... Done
cat: /home/pi/pi-apps/data/update-status/updatable-apps: No such file or directory
cat: /home/pi/pi-apps/data/update-status/updatable-files: No such file or directory
```

**Comment by theofficialgman** [comment]
bug has been solved in the referenced commit
