### ISSUE TITLE
Why can't I install apps

### ISSUE THREAD

**Issue by DavidLWB** [Botspot/pi-apps#2191]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [ ] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)
- [X] IMPORTANT: I promise to respond to comments on this issue and write a good bug report https://www.softwaretestinghelp.com/how-to-write-good-bug-report/

### What happened?

在安装应用程序时显示连接证书无法验证，导致无法安装。

### Description

在安装应用程序时显示连接证书无法验证，导致无法安装。What should I do？

### What are your system specs (run the following command in your terminal)?

```bash
OS: Kylin V10 SP1(基于Debian)
OS architecture: 64-bit
Last updated Pi-Apps on: 07/09/2022
date: option requires an argument -- 'd'
Try 'date --help' for more information.
Latest Pi-Apps version: 
Kernel: aarch64 5.4.18-35-generic
Device model: K681 F223 V1.0
Cpu name: Phytium,D2000/8
Ram size: 7.82 GB
Language: zh_CN.UTF-8
```

### (Recommended) Error log? Terminal output? Debug messages?

```bash
No internet connection! (github.com failed to respond)
Errors:
Spider mode enabled. Check if remote file exists.
--2022-12-06 12:05:29--  https://github.com/
Connecting to 0.0.0.0:26501... connected.
ERROR: cannot verify github.com's certificate, issued by ‘CN=SteamTools Certificate’:
  Unable to locally verify the issuer's authority.
To connect to github.com insecurely, use `--no-check-certificate'.
```

**Comment by theofficialgman** [comment]
we are well aware of the great chinese firewall. this is an issue without your country, there is nothing we can do to solve it.

VPNs should not cause any certificate issues, that is likely due to dns poisoning redirecting requests to github to some other site.

sorry you will have to solve your internet issues on your own
