### ISSUE TITLE
Zoom freezes

### ISSUE THREAD

**Issue by temporarium** [Botspot/pi-apps#2194]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)
- [X] IMPORTANT: I promise to respond to comments on this issue and write a good bug report https://www.softwaretestinghelp.com/how-to-write-good-bug-report/

### What happened?

Zoom freezes

### Description

Can't put my finger on it as to when this started, whether with an update to Zoom or Box64. It was working well before, and generally works well now - for 15 to 30 minutes and then freezeS completely.

Not sure either whether it has to do with screen-sharing being (en|dis)abled. Happens in full-screen mode and maximized. Just freezes on a frame.

JUST WANT TO KNOW IF ANYONE ELSE HAS EXPERIENCED SOMETHING SIMILAR WITH A RECENT UPDATE.

### What are your system specs (run the following command in your terminal)?

```bash
OS: Debian GNU/Linux 11 (bullseye)
OS architecture: 64-bit
Last updated Pi-Apps on: 12/07/2022
Latest Pi-Apps version: 12/07/2022
Kernel: aarch64 5.15.76-v8+
Device model: Raspberry Pi 4 Model B Rev 1.4 
Cpu name: Cortex-A72
Ram size: 3.74 GB
Raspberry Pi OS image version: 2022-01-28
Language: en_US.UTF-8
```

**Comment by temporarium** [comment]
Nevermind, found a work-around.

**Comment by Botspot** [comment]
How did you fix it?

**Comment by temporarium** [comment]
I didn't. I found a work-around: in my case, the web app (via firefox) works better than the current virtualized Zoom app.

And I didn't realize anyone else had this issue, since no one commented. ;-/
