### ISSUE TITLE
Twister OS - Icon Missing

### ISSUE THREAD

**Issue by ShortsKing** [Botspot/pi-apps#2196]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)
- [X] IMPORTANT: I promise to respond to comments on this issue and write a good bug report https://www.softwaretestinghelp.com/how-to-write-good-bug-report/

### What happened?

The taskbar/window frame icon was missing when i switched to Twister OS

### Description

When i transitioned operating systems from Raspberry Pi OS to Twister OS, i immediately installed pi apps and lost the window on the task bar (using windows 11 dark theme). At first i thought maybe this was the operating system, but apps i installed using pi apps did not have this problem.

### What are your system specs (run the following command in your terminal)?

```bash
OS: Raspbian GNU/Linux 10 (buster)
OS architecture: 32-bit
Last updated Pi-Apps on: 12/12/2022
Latest Pi-Apps version: 12/13/2022
Kernel: armv7l 5.10.17-v7l+
Device model: Raspberry Pi 400 Rev 1.0 
Cpu name: Cortex-A72
Ram size: 3.77 GB
Raspberry Pi OS image version: 2021-01-11
Language: en_US.UTF-8
```

**Comment by Botspot** [comment]
Could you attach a screenshot of the problem?

**Comment by ShortsKing** [comment]
![image](https://user-images.githubusercontent.com/82279627/207478627-f7fc9980-a49e-4a75-8b54-04288043a647.png)

**Comment by Botspot** [comment]
Try running this command:
```
yad --window-icon folder
```
This should open a YAD window with the "folder" icon. Let me know if that works for you, or if this also has a blank icon on your system.

**Comment by ShortsKing** [comment]
The command `yad --window-icon folder` produces a window with the defualt icon (icon missing)

**Comment by Botspot** [comment]
> The command `yad --window-icon folder` produces a window with the defualt icon (icon missing)

Interesting. When you ran that command in a terminal, did you see any error messages in the terminal?

**Comment by ShortsKing** [comment]
No. The terminal prompt did not appear until i closed the window, but at no point were there any error messages.

**Comment by ShortsKing** [comment]
Update: To clarify, i was incorrect in my original post. the icon on the task bar is missing, but the icon on the window border is not. this was also the case with the YAD test.
