### ISSUE TITLE
Tester wanted: to get steamlink running on PiOS Bullseye

### ISSUE THREAD

**Issue by Botspot** [Botspot/pi-apps#2198]
Steamlink runs fine on PiOS Buster, but on Bullseye it displays this error on launch:
![IMG_4137](https://user-images.githubusercontent.com/54716352/208020368-48dcf9c8-b61a-44aa-ac67-5a012871803f.jpg)
This is caused by a safety check in the `~/.local/share/SteamLink/steamlink.sh` script:
```bash
# Make sure we're not trying to display DRM frames on X11
if [ ! -f "$TOP/.ignore_x11" ] && [ "$DISPLAY" != "" ]; then
    OS_VERSION=$(fgrep VERSION_ID /etc/os-release | sed 's,.*"\([0-9]\+\)",\1,')
    if [ "$OS_VERSION" -gt 10 ]; then
        show_message --warning $"X11 is not supported on this version of Raspbian. You can run on the console or downgrade to Raspberry Pi Buster."
        exit 1
    fi
fi
```
While I can easily disable thus safety check to cause the fullscreen UI to load, this does nbot really prove anything. Reportedly, the problem with Bullseye only occurs when the game video stream starts. As I do not have immediate access to another computer on the network with Steam installed, I really have no way to test what graphical tweaks are necessary to make it fully work on PiOS Bullseye.

Tester requested! I want to see if switching to the FKMS GL driver allows the video stream to render, or if just running it in the console is enough. Additionally, I am interested in finding a way to run Steamlink from the graphical desktop, without any manual console-switching or changes to /boot/config.txt.
If this venture fails, then I see little point in continuing to carry Steamlink in Pi-Apps if it cannot run on the default OS going forward.

Those interested in workarounds can look to this tutorial: https://blog.iancolwell.ca/steamlink-aarch64

**Comment by Botspot** [comment]
The tester needs to have a Pi4 that is running PiOS Bullseye, with access to a PC that is running Steam.

**Comment by theofficialgman** [comment]
might be a good time to plug moonlight-qt (client software) and sunshine (an alterntive open source host software instead of nvidia geforce experience remote play) as steamlink alternatives.

there are specific debian repos of moonlight-qt for the pi (buster and bullseye 32/64bit) and nvidia jetson line (switch included) both with hardware accelerated decoding h264/hevc for fast and power efficient streaming

**Comment by Rak1ta** [comment]
@theofficialgman https://github.com/moonlight-stream/moonlight-docs/wiki/Installing-Moonlight-Qt-on-Raspberry-Pi-4

**Comment by theofficialgman** [comment]
Yes I'm well aware of the wiki. It's linked on the github releases page

**Comment by GYKgamer** [comment]
I will be happy to test

**Comment by Pi-Boy-314** [comment]
I'd be willing to test as well

**Comment by Botspot** [comment]
OK testers, first let's set some ground terms:

- "test" means to run the `steamlink` command, and see if it can play games without crashing. A successful program launch is not enough in this case.

First, the safety check for Debian Buster should be removed.
In the `~/.local/share/SteamLink/steamlink.sh` file, please change line 52 from:
```
	if [ "$OS_VERSION" -gt 10 ]; then
```
To:
```
	if false; then
```
This will allow steamlink to launch, but I need someone to actually **test** it. ;)
I'm expecting this to fail. Please verify, @Pi-Boy-314 @GYKgamer.

**Comment by Rak1ta** [comment]
@Botspot I could check in the next few days. I have a laptop nearby and the raspberry is connected to ethernet. Which Bullseye do you need?  32/64

**Comment by Botspot** [comment]
> @Botspot I could check in the next few days. I have a laptop nearby and the raspberry is connected to ethernet. Which Bullseye do you need? 32/64

I have no preference. Go with whichever one is more convenient for you. I will operate under the assumption that the solution for one will work on the other.

**Comment by GYKgamer** [comment]
Does the game need to take lots of system resources, or just any game?

**Comment by Botspot** [comment]
> Does the game need to take lots of system resources, or just any game?

Well ideally it would not be like 5fps, so I suppose that may rule out low-refresh games like tetris. But it doesn't have to be taxing either. The Pi just plays a video stream from another computer running Steam.

**Comment by GYKgamer** [comment]
https://user-images.githubusercontent.com/41442793/208224414-4a237b0a-5aa7-425f-8098-1e5f6f31b6c2.mp4

@Botspot Steam Link crashes when trying to join my pc

**Comment by Rak1ta** [comment]
@GYKgamer Are your PC and Pi connected to Wi-Fi?

**Comment by GYKgamer** [comment]
My pc is connected by ethernet and my pi is connected my wifi

**Comment by Botspot** [comment]
> 2022-12-17.04-14-34.mp4 
> @Botspot Steam Link crashes when trying to join my pc

That is to be expected. Steamlink was disabled on Bullseye for a reason! 😆 We are trying to find what tweaks will make it work again.
@GYKgamer, Please run steamlink in a terminal and post the output.

**Comment by GYKgamer** [comment]
pi@raspberrypi:~ $ steamlink
qt.qpa.xcb: QXcbConnection: XCB error: 148 (Unknown), sequence: 184, resource id: 0, major code: 140 (Unknown), minor code: 20
INFO: Connected to Remote Client service with session 740250188871379606
INFO: Starting Streaming
INFO: Received authorization proof request, responding with encrypted challenge
INFO: Received start streaming response k_ERemoteDeviceStreamingSuccess
INFO: Initializing player
INFO: Couldn't initialize SDL: No available displays
qt.qpa.xcb: QXcbConnection: XCB error: 148 (Unknown), sequence: 184, resource id: 0, major code: 140 (Unknown), minor code: 20
INFO: Connected to Remote Client service with session 6098393966422185598
Bad thread local
pi@raspberrypi:~ $

**Comment by Botspot** [comment]
@GYKgamer, now try running steamlink in a console on your Pi. You will need physical access to it, along with a real screen to do it.
Press Ctrl+Alt+F1 to get to the console. To return to the desktop press Ctrl+Alt+F7.
Try testing steamlink in the console. This ought to work, according to that tutorial website.

**Comment by GYKgamer** [comment]
This may be a bit of a problem, my micro-hdmi cable is broken. So I can't test it out (Yet). I'm probably going to buy one today. But it's 5am so the earliest I could do this is in about 6-ish hours.

**Comment by Botspot** [comment]
> This may be a bit of a problem, my micro-hdmi cable is broken. So I can't test it out (Yet). I'm probably going to buy one today. But it's 5am so the earliest I could do this is in about 6-ish hours.

In the meantime you could verify that switching to FKMS solves the problem.
Just add `dtoverlay=vc4-fkms-v3d` to /boot/config.txt, reboot, and now steamlink should work. (again, according to that website)
Having pi-apps users all switch to FKMS is not ideal, but this may give a clue as to another workaround that does not require permanent system changes. Please post the output of steamlink when fkms is enabled.

**Comment by GYKgamer** [comment]
![image](https://user-images.githubusercontent.com/41442793/208225630-6fde4479-486e-4d7b-8a2f-d99538b5d0e1.png)
well um. I have a slight issue. I tried ssh and turn on vnc again but putty hangs when I tell it to.

**Comment by GYKgamer** [comment]
> This may be a bit of a problem, my micro-hdmi cable is broken. So I can't test it out (Yet). I'm probably going to buy one today. But it's 5am so the earliest I could do this is in about 6-ish hours.

I lied, they're like £12 near me. I'm waiting for Christmas to get them for £3

**Comment by Pi-Boy-314** [comment]
It works for me just fine. A bit laggy, but that's to be expected. Doing it through WiFi on both the PC and the Pi. Both are plugged into monitors. Link to video showing it working.[It works! Wooo!](https://drive.google.com/file/d/1AuFta8pnjLix35n6JT0-zsFIduD8ZLXq/view?usp=sharing)

Also screenshot of neofetch to prove I'm using 64-bit bullseye
![image](https://user-images.githubusercontent.com/72768860/208269523-6f38bcb2-0aa3-4097-b80d-fa6c1ad6c4f6.png)

**Comment by GYKgamer** [comment]
After my 2 minutes worth of research I concluded (with my small knowledge) that the problem of steamlink not working is local to me for what i'm guessing is because of vnc.
Although terminal is giving me some nasty errors
/home/pi/.local/share/SteamLink/steamlink.sh: line 186: 27787 Segmentation fault      "streaming_client" "--settings" "/home/pi/.local/share/Valve Corporation/SteamLink/streaming_settings.bin" "--stats" "/home/pi/.local/share/Valve Corporation/SteamLink/streaming_stats.bin" "--sdr_config" "/home/pi/.local/share/Valve Corporation/SteamLink/sdr_config.txt" "--burst" "90000" "--captureres" "1920x1080" "--performance-icons" "--transport" "k_EStreamTransportUDP" "--steamid" "76561199427676272" "--server" "192.168.0.16:27031" "aa60ca1a1b28bd7e6cab4d6a868182da"
qt.qpa.xcb: QXcbConnection: XCB error: 148 (Unknown), sequence: 184, resource id: 0, major code: 140 (Unknown), minor code: 20

Here are both views of me trying steamlink.
https://user-images.githubusercontent.com/41442793/208270023-2f14ae81-efeb-417a-b24f-2182f09edfc1.mp4

**Comment by Pi-Boy-314** [comment]
I was using VNC Viewer to screen record. Not sure why it would cause issues for you. Maybe mine's a fluke or something. Are you using 32 bit or 64 big?

**Comment by GYKgamer** [comment]
First time was 32 bit, this time was 64 bit

**Comment by Botspot** [comment]
Does anyone here have their Pi displaying to an actual screen?

**Comment by Pi-Boy-314** [comment]
I did when testing it.

**Comment by libewa** [comment]
yeah my steamlink froze on the first launch screen when launching from the fullscreen terminal (64-bit bullseye)

**Comment by theofficialgman** [comment]
Closing as not planned.
If steamlink is to come to modern ARMhf/ARM64 debian/ubuntu versions, this needs to come from valve and not hacks to workaround the ancient binary that requires suitably ancient proprietary broadcom libraries not available on newer hardware.
