### ISSUE TITLE
64-bit Better Chromium DRM support doesn't work on e.g. Spotify

### ISSUE THREAD

**Issue by mobluse** [Botspot/pi-apps#2199]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)
- [X] IMPORTANT: I promise to respond to comments on this issue and write a good bug report https://www.softwaretestinghelp.com/how-to-write-good-bug-report/

### What happened?

64-bit Better Chromium DRM support doesn't work on e.g. Spotify

### Description

I installed Better Chromium in Debian 11 64-bit from Raspberry Pi using Pi-Apps, but I didn't get a checkbox about Enable Widevine for DRM and on e.g. Spotify and a tv channel (TV4 Play) DRM doesn't work. I think Widevine has not been installed since there wasn't a checkbox. It says in the description: "Widevine DRM support (for protected media like Netflix or Spotify)". It doesn't say that DRM doesn't work on 64-bit OS.

### What are your system specs (run the following command in your terminal)?

```bash
OS: Debian GNU/Linux 11 (bullseye)
OS architecture: 64-bit
Last updated Pi-Apps on: 12/15/2022
Latest Pi-Apps version: 12/15/2022
Kernel: aarch64 5.15.76-v8+
Device model: Raspberry Pi 4 Model B Rev 1.4 
Cpu name: Cortex-A72
Ram size: 7.81 GB
Raspberry Pi OS image version: 2022-09-22
Language: en_US.UTF-8
```

**Comment by Botspot** [comment]
The checkbox was hidden because Widevine does not work on 64-bit Chromium versions.
You have 3 options:

- Watch or listen to your media from alternative sources that do not have DRM
- Switch to PiOS 32-bit
- Install a 32-bit version of Chromium on your 64-bit OS, and then install Widevine, all with apt. See: https://forums.raspberrypi.com/viewtopic.php?t=340648

**Comment by mobluse** [comment]
I did the last point, so I now run the 32-bit version of Chromium in 64-bit OS. I found this on https://www.raspberrypi.com/news/raspberry-pi-os-64-bit/:
_The 64-bit version of Chromium, installed by default, has no version of the WidevineCDM library and therefore, it is not possible to play streaming media such as Netflix or Disney+.  To instead choose the 32-bit version just do the following within a terminal window:_

`sudo apt install chromium-browser:armhf libwidevinecdm0`

_To return to the 64-bit version_

`sudo apt install chromium-browser:arm64 libwidevinecdm0-`

I still think there should be some information about this problem in the description or that the DRM-checkbox should always be enabled, but if one activates it in 64-bit OS the 32-bit Chromium should be installed so that DRM works.
