### ISSUE TITLE
Add Visual Studio Code / vscode as an app

### ISSUE THREAD

**Issue by ryanbarlow1** [Botspot/pi-apps#22]
Visual Studio Code just barely added ARMv7 and ARM64 support [as of version 1.50](https://code.visualstudio.com/updates/v1_50#_linux-arm-builds).

The [base repository vscode](https://github.com/microsoft/vscode) has an MIT License, but the Visual Studio Code product is licensed under a Microsoft product license ([here's the differences between the vscode repo and Visual Studio Code](https://github.com/microsoft/vscode/wiki/Differences-between-the-repository-and-Visual-Studio-Code)). Because of the licensing, would this be eligible to be added to pi-apps?

If not, could [this community build by headmelted](http://code.headmelted.com) be added as an app?

Finally, thank you for creating this project! I just barely discovered it searching for a Zoom installer for Raspberry Pi. I just barely bought my first Raspberry Pi to use as a dev box and explore the hardware side of computing. I'm excited to see where this project goes!

**Comment by Botspot** [comment]
The nice thing about Pi-Apps is that it doesn't actually include any source code from any of the apps it installs.  
There is no way Pi-Apps could be involved in a lawsuit because it's not actually distributing any apps, but bash scripts that download an app when you click Install.  

I am not familiar with VS code, so if someone were to make an app that I could just add, that would be really nice.

**Comment by mobilegmYT** [comment]
Hmm. I do know pikiss has the new VScode...

**Comment by Botspot** [comment]
Yeah, but, Pi-Apps is better than PiKiss so we should add this regardless. ;)

OK I've tried out the headmelted thing and it seems to work well.  
I will also try the stock VS Studio Code and compare differences.

**Comment by ryanbarlow1** [comment]
>

**Comment by ryanbarlow1** [comment]
> The nice thing about Pi-Apps is that it doesn't actually include any source code from any of the apps it installs.
There is no way Pi-Apps could be involved in a lawsuit because it's not actually distributing any apps, but bash scripts that download an app when you click Install.

I wasn't meaning that there would be a lawsuit around installing Visual Studio code, I was wondering: Is pi-apps only for installing OSS apps? Because Visual Studio Code isn't open source, although the base repo vscode is.

**Comment by Botspot** [comment]
Oh, I see what you were asking, as the README mentions "open-source software". What I mean is: Pi-Apps is only for software that is not available in the RPi repositories.  
So if you can install it with `sudo apt install`, then it can't be added to Pi-Apps.

Yes, VS Code is eligible to be added. I don't like the headmelted version, so we'll go with Microsoft's release.  
As it's a deb file, this should be really easy.
```
wget https://aka.ms/linux-armhf-deb -O visual-studio.deb
sudo dpkg -i visual-studio.deb
rm visual-studio.deb
```
And then for `uninstall`:
```
sudo apt purge code
```

**Comment by mobilegmYT** [comment]
Actually, theres a armhf and a arm64 version of VScode. https://code.visualstudio.com/#alt-downloads. 
![image](https://user-images.githubusercontent.com/44128563/96389087-93def480-116a-11eb-8cf9-d9f2acae1992.png)

**Comment by ryanbarlow1** [comment]
> Oh, I see what you were asking, as the README mentions "open-source software". What I mean is: Pi-Apps is only for software that is not available in the RPi repositories.
So if you can install it with sudo apt install, then it can't be added to Pi-Apps.

Ah I see, thanks for clarifying. On another note, would you consider adding the Docker install to Pi-Apps as well, since the [recommended method is by script instead of by apt-get](https://docs.docker.com/engine/install/debian/)? If so I'll open another issue.

**Comment by mobilegmYT** [comment]
[Uploading Visual Studio Code.zip…]()

**Comment by Botspot** [comment]
> [Visual Studio Code.zip](https://github.com/Botspot/pi-apps/files/5398445/Visual.Studio.Code.zip)
@mobilegmYT 
Thanks. One question: why do you have it downloading a static deb file from mediafire?
Wouldn't it be better to download https://aka.ms/linux-armhf-deb or https://aka.ms/linux-arm64-deb directly from Microsoft?  
This way, VS will remain up-to-date. Every time MS uploads a new deb file, we don't have to change any links, as the links I suggested above will always point to the latest version.

**Comment by mobilegmYT** [comment]
Oh, wait Microsoft has direct download links to the files? I tried copying the link of the download buttons on the page but it didn't work out. You can just add the links in and commit it then.

**Comment by Botspot** [comment]
OK. VS Code has been added as of commit 03627d98ef3d811a544f7fc4eeff2d0bd09425e8
