### ISSUE TITLE
Veracrypt

### ISSUE THREAD

**Issue by nielsbaloe** [Botspot/pi-apps#220]
Hi,

I've been manually installing veracrypt ever since I have a Raspberry pi, so I thought: hej this would really be an app that people otherwise do not find.

You just can grab it from https://sourceforge.net/projects/veracrypt/files/ so there is not even a need to compile.
I did not check the latest versions, I happily stick with a great version 1.21 (which was really prepared for raspbian), however there are armf versions every new version.

And, so so many thanks for your recent small widevine fix, it works brilliantly. I looked in your script and placed the few files myself, works like a charm. Great! I've uninstalled Kodi, no need for that anymore.
And thanks for the zoom workaround and for tor-browser, I honestly did not know it existed untill I found pi-apps.
Thanks!!!!!!!!!!

Niels

**Comment by Botspot** [comment]
Added with commit b759d61160e880cf75eb6848ab83bf1c3bf177ab.

**Comment by Botspot** [comment]
Hello @nielsbaloe, could you try out something for me?
Try replacing veracrypt with a newer tool called zulucrypt.
Install:
```
sudo apt install -y zulucrypt
```
Then please run it and report back if you like it and if it does everything veracrypt can do.

**Comment by nielsbaloe** [comment]
Hi,

I tested Zulucrypt, and it works great.

The GUI layout is not properly spaced, and mounted volumes are not shown on the desktop (a feature that I love about Veracrypt).

So, yes it seems to work perfectly fine but the layout spacing is obviously never tested on Raspbian/RaspberryPiOS.

You can surely add it as alternative to your awesome pi-apps 😉. Veracrypt volumes itsself are still the most protective ones so I am personally sticking to Veracrypt volumes and to Veracrypt.

By the way, I had to use packagename zulucrypt-gui instead of zulucrypt.

Thanks for all your great work on pi-apps!!!!!!
NielsBaloe


________________________________
Van: Botspot ***@***.***>
Verzonden: vrijdag 31 maart 2023 06:16
Aan: Botspot/pi-apps ***@***.***>
CC: nielsbaloe ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [Botspot/pi-apps] Veracrypt (#220)


Hello @nielsbaloe<https://github.com/nielsbaloe>, could you try out something for me?
Try replacing veracrypt with a newer tool called zulucrypt.
Install:

sudo apt install -y zulucrypt


Then please run it and report back if you like it and if it does everything veracrypt can do.
