### ISSUE TITLE
cli-mg (command line minigames) - install based app

### ISSUE THREAD

**Issue by svgaming234** [Botspot/pi-apps#2203]
### What is the name of the app?

cli-mg

### (Optional) Where is the app hosted?

The app is hosted on my self-hosted service called GitForest, also I am sorry about any downtime it may have! [Link](http://person-stages.at.playit.gg:42126/SvGaming/cli-mg)

### About the app

A simple app containing simple command line minigames that pretty much run anywhere.

### Upload file or Add PR Link

[cli-mg_pi_apps.zip](https://github.com/Botspot/pi-apps/files/10252510/cli-mg_pi_apps.zip)

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by theofficialgman** [comment]
https://github.com/Botspot/pi-apps/issues/185
