### ISSUE TITLE
Launch after login ... pi-apps/apps/Zoom/install-64

### ISSUE THREAD

**Issue by cocobat40** [Botspot/pi-apps#2206]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)
- [X] IMPORTANT: I promise to respond to comments on this issue and write a good bug report https://www.softwaretestinghelp.com/how-to-write-good-bug-report/

### What happened?

Automatic launch after login does not work

### Description

Hello I try to run zoom64 via pi-apps once the user is logged in to PI-OS but it doesn't work. 
I tried several solutions but none work. 
I feel like something is missing. Can anyone help me? 
Thank you

### What are your system specs (run the following command in your terminal)?

```bash
OS: Debian GNU/Linux 11 (bullseye)
OS architecture: 64-bit
Last updated Pi-Apps on: 12/19/2022
Latest Pi-Apps version: 12/21/2022
Kernel: aarch64 5.15.76-v8+
Device model: Raspberry Pi 4 Model B Rev 1.5 
Cpu name: Cortex-A72
Ram size: 7.81 GB
Raspberry Pi OS image version: 2022-09-22
Language: en_US.UTF-8
```

### (Recommended) Error log? Terminal output? Debug messages?

```bash
sudo nano /etc/profile
. chemin_de_votre_script.sh

sudo nano /home/pi/.bashrc
. chemin_de_votre_script.sh
```

**Comment by Botspot** [comment]
Hello @cocobat40, thank you for asking for assistance. I suggest you take a look at the **Autostar** app on Pi-Apps. It will do exactly what you want it to.
I currently use Autostar to run Chromium and my bash IDE automatically on startup.

**Comment by Botspot** [comment]
The command you want Autostar to run is: `/home/pi/zoom/runzoom.sh`
(Be sure to replace "/home/pi" with the name of your home folder, if you chose a different username)

**Comment by cocobat40** [comment]
I know but this command was send after the login to Raspberry pi os (not
before), I don't know how to do this...
I must launch zoom automatically at startup.

Thanks very much for your help and for your job zoom64 work perfectly just
a lib mpeg miss but I create a file .lib with the same name and its ok !

**Comment by cocobat40** [comment]
Sorry but you don't have any idea ?
Thank you

**Comment by cocobat40** [comment]
Sorry I dont see your message I try Autostart and I'll be back thank you

**Comment by Botspot** [comment]
First, run Autostar, then click the "New" button.
![2023-01-03-082542_1920x1080_scrot](https://user-images.githubusercontent.com/54716352/210377076-3fe9e181-b5d2-409e-a7ab-39b04ab7a9d7.png)
Fill out the text fields with enough information to explain what you are doing. If your home folder is not /home/pi, be sure to change `/home/pi/zoom/runzoom.sh` to match.
![2023-01-03-082618_1920x1080_scrot](https://user-images.githubusercontent.com/54716352/210377217-99561468-80eb-4e8f-806a-b8fd2ed868b0.png)
This autostart method **will run** Zoom after login.
