### ISSUE TITLE
Package Cairo-dock

### ISSUE THREAD

**Issue by bobsquareeyes** [Botspot/pi-apps#2207]
### What is the name of the app?

cairo-dock

### About the app

Customisable dock on screen
To run: Menu/System Tools/Cairo-dock
Terminal: cairo-dock
To customise, right-click on dock, Cairo dock/configure.
Recommended to use autostar to autostart on boot.

### Upload file or Add PR Link

[Cairo Dock.zip](https://github.com/Botspot/pi-apps/files/10288099/Cairo.Dock.zip)

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [x] I have confirmed that this app can run on Raspberry Pi.

**Comment by theofficialgman** [comment]
While I personally use cairo dock on my budgie desktop environment. I don't think it fits very well and is even detremental/conflicting with some DEs. 

I think if the user wants this as part of their own DE customization they should be able to install it themselves just fine
