### ISSUE TITLE
Programs from JetBrains do not work correctly on 32bit

### ISSUE THREAD

**Issue by Rak1ta** [Botspot/pi-apps#2208]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)
- [X] IMPORTANT: I promise to respond to comments on this issue and write a good bug report https://www.softwaretestinghelp.com/how-to-write-good-bug-report/

### What happened?

Predictable startup errors

### Description

Version **v.2022.3** of these programs does not start.
Works from **v.2022.2.4** and below, many free memory errors in the console.
Version **v.2022.1.4** starts and does not crash.

Could this [affect](https://blog.jetbrains.com/idea/2021/04/end-of-support-for-32-bit-operating-systems-in-intellij-based-ides/) performance in armhf?

ver. 2022.3. [intellij-log.txt](https://github.com/Botspot/pi-apps/files/10285251/intellij-log.txt)
ver. 2022.3. [pucharm-log.txt](https://github.com/Botspot/pi-apps/files/10285252/pucharm-log.txt)

### What are your system specs (run the following command in your terminal)?

```bash
~/pi-apps/api get_device_info
OS: Raspbian GNU/Linux 10 (buster)
OS architecture: 32-bit
Last updated Pi-Apps on: 12/21/2022
Latest Pi-Apps version: 12/22/2022
Kernel: armv7l 5.10.103-v7l+
Device model: Raspberry Pi 4 Model B Rev 1.2 
Cpu name: Cortex-A72
Ram size: 3.65 GB
Raspberry Pi OS image version: 2021-05-07
Language: en_US.UTF-8
```

**Comment by theofficialgman** [comment]
alright its not work showing these on 32bit anymore then
its all memory errors due to jetbrains not caring about keeping the default memory allocation under 2GB

disabling on 32bit from now on
