### ISSUE TITLE
Armbian support

### ISSUE THREAD

**Issue by ririko5834** [Botspot/pi-apps#2209]
Does this work on single computers running armbian? I have Orange Pi 3 LTS

**Comment by theofficialgman** [comment]
Refer to the readme.

Most stuff will work. Some won't. In any case, you should be running a buster/bionic or newer derived debian distro.

**Comment by Botspot** [comment]
@ririko5834, I would also add that if something does not install or run successfully for you, feel free to reach out. It may be an easy fix.
