### ISSUE TITLE
i suggest you fix something

### ISSUE THREAD

**Issue by BunBao9557** [Botspot/pi-apps#221]
when i download steam on the pi apss thing i get this error message

W: Failed to fetch https://mirror.ox.ac.uk/sites/archive.raspbian.org/archive/raspbian/dists/stretch/InRelease  Could not connect to mirror.ox.ac.uk:443 (163.1.221.67). - connect (111: Connection refused) Could not connect to mirror.ox.ac.uk:443 (163.1.160.163). - connect (111: Connection refused)
W: Some index files failed to download. They have been ignored, or old ones used instead.

Please fix this

**Comment by Botspot** [comment]
This looks like an issue with your installation, not Pi-Apps.

Try running `sudo apt update` and see what it says.

**Comment by BunBao9557** [comment]
ok thx

**Comment by BunBao9557** [comment]
pi@raspberrypi:~ $ sudo apt update
Hit:1 https://dtcooper.github.io/raspotify raspotify InRelease
Hit:2 http://archive.raspberrypi.org/debian buster InRelease                   
Err:3 https://mirror.ox.ac.uk/sites/archive.raspbian.org/archive/raspbian stretch InRelease
  Could not connect to mirror.ox.ac.uk:443 (163.1.160.163). - connect (111: Connection refused) Could not connect to mirror.ox.ac.uk:443 (163.1.221.67). - connect (111: Connection refused)
Hit:4 http://raspbian.raspberrypi.org/raspbian buster InRelease        
Reading package lists... Done
Building dependency tree       
Reading state information... Done
1 package can be upgraded. Run 'apt list --upgradable' to see it.
W: Failed to fetch https://mirror.ox.ac.uk/sites/archive.raspbian.org/archive/raspbian/dists/stretch/InRelease  Could not connect to mirror.ox.ac.uk:443 (163.1.160.163). - connect (111: Connection refused) Could not connect to mirror.ox.ac.uk:443 (163.1.221.67). - connect (111: Connection refused)
W: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by BunBao9557** [comment]
thats what it says

**Comment by Botspot** [comment]
> thats what it says

Thanks for the output. This proves that Pi-Apps has nothing to do with the problem. Try asking on the Raspberry Pi forums. :)
