### ISSUE TITLE
Stacer

### ISSUE THREAD

**Issue by KolpixTV** [Botspot/pi-apps#2214]
### What is the name of the app?

Stacer

### (Optional) Where is the app hosted?

https://github.com/oguzhaninan/Stacer

### About the app

Stacer is an open source system optimizer and application monitor that helps users to manage entire system with different aspects, its an all in one system utility.

### Upload file or Add PR Link

[Stacer.zip](https://github.com/Botspot/pi-apps/files/10315946/Stacer.zip)

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [x] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by Botspot** [comment]
> * [x]  I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.

Actually it has been discussed before on two separate occasions. These can be found by going to the Issues tab and searching all issues for "stacer".
See #226 and #1033 for why we've decided to not add this to Pi-Apps.
