### ISSUE TITLE
PyCharm doesn't start

### ISSUE THREAD

**Issue by KolpixTV** [Botspot/pi-apps#2215]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)
- [X] IMPORTANT: I promise to respond to comments on this issue and write a good bug report https://www.softwaretestinghelp.com/how-to-write-good-bug-report/

### What happened?

PyCharm doesn't start, because "PathClassLoader" need Java 17

### Description

**Steps to reproduce:**

1. Install PyCharm CE
2. Try to run PyCharm CE

**The problem:**

I looked into the Issue and found out that "PathClassLoader" requires Java 17 (`java.lang.UnsupportedClassVersionError: com/intellij/util/lang/PathClassLoader has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0`).

**The fix:**

1. Install Java 17 (I downloaded it from [Adoptium](https://adoptium.net/de/temurin/releases/))
2. Change the start command from `bash -c "JAVA_HOME=/usr/lib/jvm/java-11-openjdk-arm64 PATH=/usr/lib/jvm/java-11-openjdk-arm64/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games /opt/pycharm-community/bin/pycharm.sh"` to `bash -c "JAVA_HOME=/usr/lib/jvm/jdk-17.0.5+8 PATH=/usr/lib/jvm/jdk-17.0.5+8/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games /opt/pycharm-community/bin/pycharm.sh"` (That obviously depends on the file name and the folder where you saved it)

And the install script installs java 11 so that's not needed anymore. It has to install java 17

### What are your system specs (run the following command in your terminal)?

```bash
OS: Debian GNU/Linux 11 (bullseye)
OS architecture: 64-bit
Last updated Pi-Apps on: 12/28/2022
Latest Pi-Apps version: 12/28/2022
Kernel: aarch64 5.15.61-v8+
Device model: Raspberry Pi 400 Rev 1.0 
Cpu name: Cortex-A72
Ram size: 3.79 GB
Raspberry Pi OS image version: 2022-09-22
Language: en_US.UTF-8
```

### (Recommended) Error log? Terminal output? Debug messages?

```bash
CompileCommand: exclude com/intellij/openapi/vfs/impl/FilePartNodeRoot.trieDescend
Error occurred during initialization of VM
java.lang.UnsupportedClassVersionError: com/intellij/util/lang/PathClassLoader has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
	at java.lang.ClassLoader.defineClass1(java.base@11.0.16/Native Method)
	at java.lang.ClassLoader.defineClass(java.base@11.0.16/ClassLoader.java:1017)
	at java.security.SecureClassLoader.defineClass(java.base@11.0.16/SecureClassLoader.java:174)
	at jdk.internal.loader.BuiltinClassLoader.defineClass(java.base@11.0.16/BuiltinClassLoader.java:800)
	at jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(java.base@11.0.16/BuiltinClassLoader.java:698)
	at jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(java.base@11.0.16/BuiltinClassLoader.java:621)
	at jdk.internal.loader.BuiltinClassLoader.loadClass(java.base@11.0.16/BuiltinClassLoader.java:579)
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(java.base@11.0.16/ClassLoaders.java:178)
	at java.lang.ClassLoader.loadClass(java.base@11.0.16/ClassLoader.java:522)
	at java.lang.Class.forName0(java.base@11.0.16/Native Method)
	at java.lang.Class.forName(java.base@11.0.16/Class.java:398)
	at java.lang.ClassLoader.initSystemClassLoader(java.base@11.0.16/ClassLoader.java:1976)
	at java.lang.System.initPhase3(java.base@11.0.16/System.java:2074)
```

**Comment by Botspot** [comment]
@theofficialgman is there any downside to using temurin-17-jdk as MultiMC does?

**Comment by theofficialgman** [comment]
oh pycharm requires java-17 now? it used to only require java 8 so this is news to me. I ran pycharm about a month ago with java 11 so this is a new change. pycharm usually ships with java-11 for x86_64 systems bundled in and the website says that is still the case

nothing wrong with using temurin-17-jdk, I can switch it to using that

**Comment by Rak1ta** [comment]
@theofficialgman
 ```
pi@raspberrypi:~ $ bash -c "JAVA_HOME=/usr/lib/jvm/temurin-17-jdk-armhf PATH=/usr/lib/jvm/temurin-17-jdk-armhf/bin/:/home/pi/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games:/snap/bin /opt/pycharm-community/bin/pycharm.sh"
OpenJDK Server VM warning: Archived non-system classes are disabled because the java.system.class.loader property is specified (value = "com.intellij.util.lang.PathClassLoader"). To use archived non-system classes, this property must not be set
Error: LinkageError occurred while loading main class com.intellij.idea.Main
	java.lang.ExceptionInInitializerError: null
pi@raspberrypi:~ $ bash -c "JAVA_HOME=/usr/lib/jvm/temurin-17-jdk-armhf PATH=/usr/lib/jvm/temurin-17-jdk-armhf/bin/:/home/pi/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games:/snap/bin /opt/ideaIC/bin/idea.sh"
OpenJDK Server VM warning: Archived non-system classes are disabled because the java.system.class.loader property is specified (value = "com.intellij.util.lang.PathClassLoader"). To use archived non-system classes, this property must not be set
Error: LinkageError occurred while loading main class com.intellij.idea.Main
	java.lang.ExceptionInInitializerError: null
```

**Comment by theofficialgman** [comment]
Oh I downgraded armhf at your request. I should make those continue to use java 11

**Comment by theofficialgman** [comment]
reverted armhf for pycharm and intellij java to continue to use java-11 since they are held at an old version (no 32bit support in newer versions)

https://github.com/Botspot/pi-apps/commit/75003f37a62671ea5e962ad8cd7437cd37addbcd
