### ISSUE TITLE
Add GLSL support on PinebookPro amd64 ubuntu 22.04

### ISSUE THREAD

**Issue by n8marti** [Botspot/pi-apps#2216]
### Cool ideas?

I get a GLSL version error when launching Minecraft via PrismLauncher ("GLSL 1.50 is not supported"). I resolved this by adding ```"MESA_GLSL_VERSION_OVERRIDE=330"``` to the ```Exec``` line in prismlauncher's .desktop file. I'm calling this a "suggestion" because I don't know if it would introduce other issues elsewhere.

**Comment by theofficialgman** [comment]
The panfrost Mali mesa drivers don't really support glsl 1.50 in the fullest. Geometry shader support is missing.
You are welcome to provide your own overrides in you main system environment file, the . desktop file, or when launching from terminal but I would rather not specify this override.

Panfrost will get there officially at some point.
