### ISSUE TITLE
Raspi-Info

### ISSUE THREAD

**Issue by mapi68** [Botspot/pi-apps#2217]
### What is the name of the app?

raspi-info

### (Optional) Where is the app hosted?

https://github.com/mapi68/raspi-info

### About the app

***RASPI-INFO is a tool to get a lot of infomations about your Raspberry Pi.***
Direct use from shell: raspi-info or raspi-info-light. Automatic use: when you login through SSH (only raspi-info-light). RASPI-INFO provides too more than 100 "shell tips" that can be useful to help you in bash! When a new update will be released you'll receive a message at the end of program.

**raspi-info** (main window, with many info)
**raspi-info-light** (light version, start by default when you make a SSH connection)
**raspi-info-check** (simple tool that check in real time load, temp, clock and volt)
**raspi-info-install** (install raspi-info)
**raspi-info-update** (update raspi-info)

**raspi-info-light
![raspi-info-light](https://github.com/mapi68/raspi-info/raw/master/images/raspi-info-light.png)
general-info
![general-info](https://github.com/mapi68/raspi-info/raw/master/images/general-info.png)
partition-info
![partition-info](https://github.com/mapi68/raspi-info/raw/master/images/partition-info.png)
folder-info
![folder-info](https://github.com/mapi68/raspi-info/raw/master/images/folder-info.png)
wireguard-info
![logo](https://github.com/mapi68/raspi-info/raw/master/images/wireguard-info.png)
raspi-info-check
![raspi-info-check](https://github.com/mapi68/raspi-info/raw/master/images/raspi-info-check.png)
raspi-info
![raspi-info](https://github.com/mapi68/raspi-info/raw/master/images/raspi-info.png)**

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by theofficialgman** [comment]
I don't really feel like this brings anything to the table for desktop GUI users.
These are simply wrapper commands for the likes of, lsblk, vcgencmd, cat /proc/cpuinfo, wiregaurd, etc.

I assume the use case for these terminal bash scripts would be for debugging in which case I think it's best that users get accustomed to the standard linux commands that are applicable across all devices.

**Comment by SebTNT** [comment]
I have made a zip installer and uninstaller at request #2223

**Comment by Botspot** [comment]
> I have made a zip installer and uninstaller at request #2223

https://github.com/Botspot/pi-apps/files/10344317/raspi-info.zip

**Comment by theofficialgman** [comment]
@SebTNT please review the "Creating an app" page on the wiki, particularly this section:
https://github.com/Botspot/pi-apps/wiki/Creating-an-app#other-things-to-be-aware-of

**Comment by craigevil** [comment]
It is in raspi-utils. Which is in the normal repos.
https://github.com/raspberrypi/utils

**Comment by Botspot** [comment]
> It is in raspi-utils. Which is in the normal repos. https://github.com/raspberrypi/utils

That does not appear to be correct, @craigevil. Where do you see this in raspi-utils??
![image](https://github.com/mapi68/raspi-info/raw/master/images/raspi-info.png)

**Comment by theofficialgman** [comment]
> > It is in raspi-utils. Which is in the normal repos. https://github.com/raspberrypi/utils
> 
> That does not appear to be correct, @craigevil. Where do you see this in raspi-utils??

It's a totally different script that happens to be named identical <https://github.com/raspberrypi/utils/tree/master/raspinfo> . Hence why I marked the comment as off-topic
