### ISSUE TITLE
Tor cant install or update

### ISSUE THREAD

**Issue by neil969** [Botspot/pi-apps#2221]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)
- [X] IMPORTANT: I promise to respond to comments on this issue and write a good bug report https://www.softwaretestinghelp.com/how-to-write-good-bug-report/

### What happened?

Tor wont install becaus the download link is wrong

### Description

I tried to do the update of TOR from the Pia Apps UI and it failed as it could not download , AFTER it had uninstalled the existing Tor application. This ..
No Tor installed :(  
The URI called does not exist

### What are your system specs (run the following command in your terminal)?

```bash
OS: Ubuntu 22.04.1 LTS
OS architecture: 32-bit
Last updated Pi-Apps on: 01/03/2023
Latest Pi-Apps version: 01/04/2023
Kernel: armv7l 5.15.0-1021-raspi
Device model: Raspberry Pi 4 Model B Rev 1.5 
Cpu name: Cortex-A72
Ram size: 3.83 GB
Language: en_US.UTF-8
```

### (Recommended) Error log? Terminal output? Debug messages?

```bash
OS: Ubuntu 22.04.1 LTS
OS architecture: 32-bit
Last updated Pi-Apps on: 01/03/2023
Latest Pi-Apps version: 01/04/2023
Kernel: armv7l 5.15.0-1021-raspi
Device model: Raspberry Pi 4 Model B Rev 1.5 
Cpu name: Cortex-A72
Ram size: 3.83 GB
Language: en_US.UTF-8

BEGINNING OF LOG FILE:
-----------------------

Downloading download to /home/pb-desktop3/tor.tar.xz... 
?25lK0B/0B 
01/04 08:33:30 [ERROR] CUID#7 - Download aborted. URI=https://sourceforge.net/projects/tor-browser-ports/files/12.0/tor-browser-linux-armhf-12.0_en-US.tar.xz/download
Exception: [AbstractCommand.cc:403] errorCode=4 URI=https://sourceforge.net/projects/tor-browser-ports/files/12.0/tor-browser-linux-armhf-12.0_en-US.tar.xz/download
  -> [RequestGroup.cc:1266] errorCode=4 Reached max-file-not-found count=5
ee7924|ERR |       0B/s|/home/pb-desktop3/tor.tar.xz
(ERR):error occurred.
aria2 will resume download if the transfer is restarted.
If there are any errors, then see the log file. See '-l' option in help/man page for details.
?25h
Failed to download: https://sourceforge.net/projects/tor-browser-ports/files/12.0/tor-browser-linux-armhf-12.0_en-US.tar.xz/download
Please review errors above.
Failed to download!

Failed to install Tor!
◢◣Need help? Copy the ENTIRE terminal output or take a screenshot.
Please ask on Github: https://github.com/Botspot/pi-apps/issues/new/choose
Or on Discord: https://discord.gg/RXSTvaUvuu
```

**Comment by SebTNT** [comment]
I looked on sourceforge, they have changed it to be ALL instead of en_US.
The new link is: https://sourceforge.net/projects/tor-browser-ports/files/12.0/tor-browser-linux-armhf-12.0_ALL.tar.xz/download
I will send a pull request through with the Tor fix

**Comment by SebTNT** [comment]
I have started a pull request on #2222

**Comment by neil969** [comment]
Thanks .. should I just edit my local script for now to let it install through PiApps?

**Comment by neil969** [comment]
> I have started a pull request on #2222

I noticed that it also extracts to a folder with a different name (~/tor-browser   - no "ALL" or "en_US ) so the script still fails to a) move the config & b) make a desktop entry, so those lines need to change too in the script
I manged to fiddle with the 32 bit script & make it work ( I have NO IDEA what I am doing BTW LOL) , but TOR still nags about needing to be upgraded :)

**Comment by SebTNT** [comment]
Hold on, im setting a PI up now.

**Comment by SebTNT** [comment]
I've fixed it and it should now also import your old browser data.

**Comment by neil969** [comment]
thanks :)

**Comment by SebTNT** [comment]
no problem - I barely know what I was doing.

**Comment by Botspot** [comment]
I've fixed it with this change: https://github.com/Botspot/pi-apps/commit/8bd6387b5f1fb811b2195e9db8a6c95608d972eb
