### ISSUE TITLE
steam error (OpenGL GLX extension not supported by display)

### ISSUE THREAD

**Issue by gamerboy80** [Botspot/pi-apps#223]
![image](https://user-images.githubusercontent.com/68038215/104048824-c06a4180-5198-11eb-82bd-cc5f00b69960.png)

**Comment by Botspot** [comment]
Is your operating system Raspberry Pi OS Buster? Did you disable the OpenGL FKMS driver?

Are you trying to run Steam inside vdesktop by any chance?

**Comment by gamerboy80** [comment]
yes im on buster, no i didnt disable the driver and im not running steam inside vdesktop

**Comment by Botspot** [comment]
Try updating box86.
```
wget -qO- https://raw.githubusercontent.com/Botspot/box86-updater/main/update-box86 | bash
```
And if that doesn't work, you'd probably be better off by opening an issue on the [box86 emulator's github page](https://github.com/ptitSeb/box86).
