### ISSUE TITLE
gcc-arm-none-eabi for arm7l

### ISSUE THREAD

**Issue by Ninoh-FOX** [Botspot/pi-apps#2230]
### Cool ideas?

Hi, I compiled gcc-arm-none-eabi 10.3 (in raspbian buster is v8) for systems 32bits, for is you like add this.

https://mega.nz/file/P05U3ApL#mcD32Ru_2CojMdupsGky1MmEEIgSoJeg2-Y0HJV_j0g

See you.

**Comment by Botspot** [comment]
Could you explain what this is and what makes it a good fit for Pi-Apps?

**Comment by theofficialgman** [comment]
its a build of the gcc-10 compiler, a later version than the one in buster (gcc-8). the target chosen was gcc-arm-none-eabi.

I don't see what good this does us... we could have compiled this compiler ourselves if we needed it for some reason

**Comment by Ninoh-FOX** [comment]
Well, this arch version no it is release in the source page, and the time compilation is about 14h, this is util if you like compiler and flash machines how game and watch.

**Comment by theofficialgman** [comment]
I don't really see any need for this.

If someone needs this specific toolchain version for their project and must compile from a host Linux armv7 system for a baremetal armv7 target, then they are going to have the knowledge already for how to compile the toolchain themselves.
