### ISSUE TITLE
EDIT ME Include the app name

### ISSUE THREAD

**Issue by iggymorr** [Botspot/pi-apps#2236]
### What is the name of the app?

Py game 

### (Optional) Where is the app hosted?

Not sure how to find it but I would like to get that so I can run the game I found git hub called stolen crown

### About the app

Py game for pi

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by Botspot** [comment]
It seems that you are asking us to add a game that even you cannot find. I briefly searched for it and did not see anything relevant. I am closing this issue now. @iggymorr, if you do find the game later please reply back.

**Comment by Botspot** [comment]
Let us know if you find it.

**Comment by Rak1ta** [comment]
@Itai-Nelken Can you run games through it?

**Comment by iggymorr** [comment]
Here’s the GitHub game I would like to play but it’s missing this pygame here’s the game and website 

https://github.com/justinmeister/The-Stolen-Crown-RPG 
https://www.pygame.org/news

**Comment by Itai-Nelken** [comment]
> @Itai-Nelken Can you run games through it? 

I remember there were example pygame games pre-installed in rpiOS, but I haven't used rpiOS in a long time. I assume they still run.

**Comment by iggymorr** [comment]
The new one doesn’t have tried to install it but it’s doesn’t work any more


Sent from Yahoo Mail for iPhone


On Sunday, January 22, 2023, 7:45 AM, Itai Nelken ***@***.***> wrote:





@Itai-Nelken Can you run games through it?


I remember there were example pygame games pre-installed in rpiOS, but I haven't used rpiOS in a long time. I assume they still run.
