### ISSUE TITLE
Minecraft Java Install Error

### ISSUE THREAD

**Issue by AmBruhIdot** [Botspot/pi-apps#224]
Pi 4 8GB-BerryBoot RPI OS (64bit)
Terminal: [https://pastebin.com/HP9HbdPf](url)

Before this installation when trying to install terminal something along the lines of installation failed because /home/pi/Minecraft already existed so I deleted that folder, pressed uninstall in pi apps, and tried installing again and got those errors in the Terminal. If there is anything you can help me with, please let me know!

**Comment by AmBruhIdot** [comment]
I have a Mojang account* forgot to add that

**Comment by mobilegmYT** [comment]
@AmBruhIdot Try again now.

**Comment by AmBruhIdot** [comment]
I'll try again when I get home, which will be about in 4 hours.

**Comment by Botspot** [comment]
Closed due to inactivity.

Reply back and I can re-open it.
