### ISSUE TITLE
The logo in the terminal is displayed incorrectly

### ISSUE THREAD

**Issue by Rak1ta** [Botspot/pi-apps#2243]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)
- [X] IMPORTANT: I promise to respond to comments on this issue and write a good bug report https://www.softwaretestinghelp.com/how-to-write-good-bug-report/

### What happened?

Unsupported characters in the logo

### Description

![Безымянный](https://user-images.githubusercontent.com/88277343/213741701-d630bc85-01e3-40ca-b936-d8f5e9b76ab5.png)

### What are your system specs (run the following command in your terminal)?

```bash
OS: Raspbian GNU/Linux 10 (buster)
OS architecture: 32-bit
Last updated Pi-Apps on: 01/19/2023
Latest Pi-Apps version: 01/19/2023
Kernel: armv7l 5.10.103-v7l+
Device model: Raspberry Pi 4 Model B Rev 1.2 
Cpu name: Cortex-A72
Ram size: 3.65 GB
Raspberry Pi OS image version: 2021-05-07
Language: en_US.UTF-8
```

**Comment by Botspot** [comment]
Fixed! Thanks for reporting. I forgot that I had messed with the fonts in my Buster VM, so I did not catch this until resetting it.
