### ISSUE TITLE
XSnow it works incorrectly

### ISSUE THREAD

**Issue by Rak1ta** [Botspot/pi-apps#2248]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)
- [X] IMPORTANT: I promise to respond to comments on this issue and write a good bug report https://www.softwaretestinghelp.com/how-to-write-good-bug-report/

### What happened?

XSnow is slow on default settings, etc.

### Description

а) XSnow is hidden for installation, you forgot to return "Appearance" in the [list of programs](https://github.com/Botspot/pi-apps/blob/0572e5a304273bc9980e86e4c4bbcaa9530d4424/etc/categories#L217).

б) In my case, the program is very slow and asks to lower the levels in the settings. But this does not happen quickly, as the program window freezes. **_.xsnowrc_** is created in /home/pi the first time the program is started. There are all the parameters for displaying snow. If you add these two commands to an empty file, they will be in place when you run xsnow and will be sorted with the rest of the parameters. It will not lag, you can already select the settings for yourself.
```
CpuLoad 20
Nbirds 20
```
в) And running xsnow hides shortcuts on the desktop

г) XSnow is displayed under the "Games" category. Wouldn't it make more sense to move it to "Utility"?

### What are your system specs (run the following command in your terminal)?

```bash
OS: Raspbian GNU/Linux 10 (buster)
OS architecture: 32-bit
Last updated Pi-Apps on: 01/21/2023
Latest Pi-Apps version: 01/21/2023
Kernel: armv7l 5.10.103-v7l+
Device model: Raspberry Pi 4 Model B Rev 1.2 
Cpu name: Cortex-A72
Ram size: 3.65 GB
Raspberry Pi OS image version: 2021-05-07
Language: en_US.UTF-8
```

### (Recommended) Error log? Terminal output? Debug messages?

```bash
pi@raspberrypi:~ $ xsnow
   *********************
   * xsnow 3.7.0~pre02 *
   *********************
December 14th 2001 by Rick Jansen 
December 2022 by Willem Vermin
Available languages are: de en es fi fr it nl pt
Detected desktop session: LXDE-pi
GTK version: 3.24.5
GSL version: 2.5
Cannot create transparent window
LXDE session found, using window 'pcmanfm'.
Using double buffer: 0x3200001. 1920x1080
Snowing in 0x1200003: pcmanfm 0+0 1920x1080
Using double buffer: 0x320004d. 1920x1080
```

**Comment by theofficialgman** [comment]
> а) XSnow is hidden for installation, you forgot to return "Appearance" in the [list of programs]

will correct this

> г) XSnow is displayed under the "Games" category. Wouldn't it make more sense to move it to "Utility"?

this uses the official xsnow source which includes installing a .desktop file. its exacly the same as the official deb. it is a game according to them 🤷🏻 
```
[Desktop Entry]
Name=xsnow
# xsnow-3.7.0~pre02
Comment=Snow, Santa and birds on your desktop
Exec=xsnow
Icon=xsnow
Type=Application
Categories=Game;
Terminal=false
Name[en_US]=xsnow
Keywords=christmas;santa;snow;xmas
Version=1.0
StartupNotify=true
Actions=start;nomenu;

[Desktop Action start]
Name=Start xsnow
Exec=xsnow

[Desktop Action nomenu]
Name=Start without menu
Exec=xsnow -hidemenu
```

> в) And running xsnow hides shortcuts on the desktop

that is simply how the program works. if you want to file it as an issue or need help setting it up, ask upstream

**Comment by Rak1ta** [comment]
@theofficialgman And according to the file .xsnowrc there is no sense to do a config in advance?  By analogy with programs from JetBrains.
