### ISSUE TITLE
Cannot install apps due to system error

### ISSUE THREAD

**Issue by JoeyAW** [Botspot/pi-apps#2250]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)
- [x] IMPORTANT: I promise to respond to comments on this issue and write a good bug report https://www.softwaretestinghelp.com/how-to-write-good-bug-report/

### What happened?

I cannot install any apps due to a system error that I do not know how to fix.

### Description

Whenever I try to download an app, such as Minecraft Pi (Modded) or Linerider, it fails to install giving me the message "[App Name] Failed to install because Pi-Apps encountered a system error." It then goes on to say:

APT reported a faulty repository, and you must fix it before Pi-Apps will work.

To delete the repository:
Remove the relevant line from /etc/apt/sources.list file or delete one file in
the /etc/apt/sources.list.d folder.

sources.list requires root permissions to edit: sudo mousepad /path/to/file
APT reported an unsigned repository. This has to be solved before APT or Pi-Apps, will work.

If you're not sure what to do, you can try to fix the problem by running this command in a terminal:
sudo apt update 2>&1 | sed -ne 's/.*NO_PUBKEY //p' | while read key; do if ! [[  =~ "" ]]; then sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys ""; keys+=(""); fi; done

I am not quite sure how to fix this as the commands are not working. It worked until I updated it tonight, but now it will not. Thank you in advance!

### What are your system specs (run the following command in your terminal)?

```bash
OS: Debian GNU/Linux 11 (bullseye)
OS architecture: 64-bit
Last updated Pi-Apps on: 01/21/2023
Latest Pi-Apps version: 01/21/2023
Kernel: aarch64 5.15.84-v8+
Device model: Raspberry Pi 3 Model B Plus Rev 1.3 
Cpu name: Cortex-A53
Ram size: .91 GB
Raspberry Pi OS image version: 2022-09-22
Language: en_US.UTF-8
```

### (Recommended) Error log? Terminal output? Debug messages?

```bash
🭊🬹🬹🬹🬿                                                          
 🭇🬭🬭🬎🬭🬭🬭🬎🬭🬭🬼                                                       
 🮉  ▄ ▄ ▄  ▋   █▀▀🭍 ▄                                              
 🮉  ▄ ▄ ▄  ▋   █▄▄🭞 ▄ ▄▄ 🭂▀▀█ █▀▀🭍 █▀▀🭍 🭂🬰🬰🬰                       
 🮉  ▄ ▄ ▄  ▋   █    █    🭓▄▄█ █▄▄🭞 █▄▄🭞 ▄▄▄🭞                       
 🭦🭏🬭🬭🬭🬭🬭🬭🬭🭄🭛                  █    █                               
                                                                   
                                                                   
tail: warning: --retry only effective for the initial open
Installing Minecraft Pi (Modded)...

Downloading minecraft-pi-reborn-client-2.4.6-arm64.AppImage to /home/joeyaw/.local/bin/com.thebrokenrail.MCPIRebornClient.AppImage... 
Done ———————————————————————————————————————————————————————————————————————————
Making executable: /home/joeyaw/.local/bin/com.thebrokenrail.MCPIRebornClient.AppImage
Will install these packages: fuse3 libfuse2 
Waiting until APT locks are released... Done
Creating an empty apt-package to install the necessary apt packages...
It will be named: pi-apps-8c0a342d
Depends: fuse3, libfuse2
Running sudo apt update...
Hit:1 http://security.debian.org/debian-security bullseye-security InRelease
Hit:2 http://deb.debian.org/debian bullseye InRelease
Hit:3 http://deb.debian.org/debian bullseye-updates InRelease
Hit:5 https://dl.winehq.org/wine-builds/debian bullseye InRelease
Hit:6 http://archive.raspberrypi.org/debian bullseye InRelease
Hit:4 https://box64.debian.ryanfortner.dev/debian ./ InRelease
Get:7 http://ppa.launchpad.net/openshot.developers/ppa/ubuntu lunar InRelease [17.6 kB]
Err:7 http://ppa.launchpad.net/openshot.developers/ppa/ubuntu lunar InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 52165BD6B9BA26FA
W: GPG error: http://ppa.launchpad.net/openshot.developers/ppa/ubuntu lunar InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 52165BD6B9BA26FA
E: The repository 'http://ppa.launchpad.net/openshot.developers/ppa/ubuntu lunar InRelease' is not signed.
apt update complete.
Failed to run sudo apt update!
APT reported these errors:
E: The repository 'http://ppa.launchpad.net/openshot.developers/ppa/ubuntu lunar InRelease' is not signed.
Hit:1 http://security.debian.org/debian-security bullseye-security InRelease
Hit:2 http://deb.debian.org/debian bullseye InRelease
Hit:3 http://deb.debian.org/debian bullseye-updates InRelease
Hit:5 https://dl.winehq.org/wine-builds/debian bullseye InRelease
Hit:6 http://archive.raspberrypi.org/debian bullseye InRelease
Hit:4 https://box64.debian.ryanfortner.dev/debian ./ InRelease
Get:7 http://ppa.launchpad.net/openshot.developers/ppa/ubuntu lunar InRelease [17.6 kB]
Err:7 http://ppa.launchpad.net/openshot.developers/ppa/ubuntu lunar InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 52165BD6B9BA26FA
W: GPG error: http://ppa.launchpad.net/openshot.developers/ppa/ubuntu lunar InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 52165BD6B9BA26FA
E: The repository 'http://ppa.launchpad.net/openshot.developers/ppa/ubuntu lunar InRelease' is not signed.

Failed to install Minecraft Pi (Modded)!
◢◣Need help? Copy the ENTIRE terminal output or take a screenshot.
Please ask on Github: https://github.com/Botspot/pi-apps/issues/new/choose
Or on Discord: https://discord.gg/RXSTvaUvuu
```

**Comment by Botspot** [comment]
It appears that you have added a repository to APT.
`http://ppa.launchpad.net/openshot.developers/ppa/ubuntu`
Do you remember doing this?

In any case, that site was down when you last ran `sudo apt update`, causing the whole command to fail. This is not a Pi-Apps issue, because Pi-Apps did not add this repository.
Were you trying to follow a tutorial that said to add that repository?

In any case, it is easy to remove. Please send me the output of running `grep -r . /etc/apt/sources.list*`.  You should be able to copy and paste from the terminal - no need to type all that output manually to Github here.
The output from this command will help me see where you installed that repository, so that it can be removed.

**Comment by JoeyAW** [comment]
I do not remember adding a repository, but I will try running that command.
The output said:

/etc/apt/sources.list:deb http://deb.debian.org/debian bullseye main contrib non-free
/etc/apt/sources.list:deb http://security.debian.org/debian-security bullseye-security main contrib non-free
/etc/apt/sources.list:deb http://deb.debian.org/debian bullseye-updates main contrib non-free
/etc/apt/sources.list:# Uncomment deb-src lines below then 'apt-get update' to enable 'apt-get source'
/etc/apt/sources.list:# deb-src http://deb.debian.org/debian bullseye main contrib non-free
/etc/apt/sources.list:# deb-src http://security.debian.org/debian-security bullseye-security main contrib non-free
/etc/apt/sources.list:# deb-src http://deb.debian.org/debian bullseye-updates main contrib non-free
/etc/apt/sources.list.d/raspi.list.save:deb http://archive.raspberrypi.org/debian/ bullseye main
/etc/apt/sources.list.d/raspi.list.save:# Uncomment line below then 'apt-get update' to enable 'apt-get source'
/etc/apt/sources.list.d/raspi.list.save:#deb-src http://archive.raspberrypi.org/debian/ bullseye main
/etc/apt/sources.list.d/box64.list:deb [signed-by=/usr/share/keyrings/box64-debs-archive-keyring.gpg] https://ryanfortner.github.io/box64-debs/debian ./
/etc/apt/sources.list.d/openshot_developers-ubuntu-ppa-lunar.list:deb http://ppa.launchpad.net/openshot.developers/ppa/ubuntu lunar main
/etc/apt/sources.list.d/openshot_developers-ubuntu-ppa-lunar.list:# deb-src http://ppa.launchpad.net/openshot.developers/ppa/ubuntu lunar main
/etc/apt/sources.list.d/raspi.list:deb http://archive.raspberrypi.org/debian/ bullseye main
/etc/apt/sources.list.d/raspi.list:# Uncomment line below then 'apt-get update' to enable 'apt-get source'
/etc/apt/sources.list.d/raspi.list:# deb-src http://archive.raspberrypi.org/debian/ bullseye main
/etc/apt/sources.list.d/winehq-bullseye.sources:Types: deb
/etc/apt/sources.list.d/winehq-bullseye.sources:URIs: https://dl.winehq.org/wine-builds/debian
/etc/apt/sources.list.d/winehq-bullseye.sources:Suites: bullseye
/etc/apt/sources.list.d/winehq-bullseye.sources:Components: main
/etc/apt/sources.list.d/winehq-bullseye.sources:Architectures: amd64 i386
/etc/apt/sources.list.d/winehq-bullseye.sources:Signed-By: /etc/apt/keyrings/winehq-archive.key
/etc/apt/sources.list.d/box64.list.save:deb [signed-by=/usr/share/keyrings/box64-debs-archive-keyring.gpg] https://ryanfortner.github.io/box64-debs/debian ./
/etc/apt/sources.list.save:deb http://deb.debian.org/debian bullseye main contrib non-free
/etc/apt/sources.list.save:deb http://security.debian.org/debian-security bullseye-security main contrib non-free
/etc/apt/sources.list.save:deb http://deb.debian.org/debian bullseye-updates main contrib non-free
/etc/apt/sources.list.save:# Uncomment deb-src lines below then 'apt-get update' to enable 'apt-get source'
/etc/apt/sources.list.save:#deb-src http://deb.debian.org/debian bullseye main contrib non-free
/etc/apt/sources.list.save:#deb-src http://security.debian.org/debian-security bullseye-security main contrib non-free
/etc/apt/sources.list.save:#deb-src http://deb.debian.org/debian bullseye-updates main contrib non-free

**Comment by JoeyAW** [comment]
I remember now! I installed openshot. That's probably why.

**Comment by JoeyAW** [comment]
It's fixed!
