### ISSUE TITLE
Won't update

### ISSUE THREAD

**Issue by Noob-Master-XD** [Botspot/pi-apps#2255]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)
- [X] IMPORTANT: I promise to respond to comments on this issue and write a good bug report https://www.softwaretestinghelp.com/how-to-write-good-bug-report/

### What happened?

Updating and it says that it's up to date

### Description

Updating and it says that it's up to date, but when i try to install a app it pops up an error and says that i have a older version.

### What are your system specs (run the following command in your terminal)?

```bash
OS: Debian GNU/Linux 11 (bullseye)
OS architecture: 64-bit
Last updated Pi-Apps on: 01/25/2023
Latest Pi-Apps version: 01/26/2023
Kernel: aarch64 5.15.84-v8+
Device model: Raspberry Pi 4 Model B Rev 1.5 
Cpu name: Cortex-A72
Ram size: 1.84 GB
```

**Comment by Botspot** [comment]
Could you capture a screenshot of the error that says you have an older version?

**Comment by Noob-Master-XD** [comment]
> Could you capture a screenshot of the error that says you have an older version?
Thank you for trying to help, but i managed to get it working. my raspberry pi just had some corrupted files so i coulden't update.
