### ISSUE TITLE
Fail to Download OBS for Rasberry PI 4

### ISSUE THREAD

**Issue by Lycronix** [Botspot/pi-apps#2256]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)
- [X] IMPORTANT: I promise to respond to comments on this issue and write a good bug report https://www.softwaretestinghelp.com/how-to-write-good-bug-report/

### What happened?

cant Download and Install Obs-Studio

### Description
```
Will install these packages: http://ftp.debian.org/debian/pool/non-free/f/fdk-aac/libfdk-aac2_2.0.1-1_armhf.deb http://ftp.debian.org/debian/pool/non-free/f/fdk-aac/libfdk-aac-dev_2.0.1-1_armhf.deb https://github.com/Pi-Apps-Coders/files/releases/download/large-files/obs-studio_27.2.0-beta3-40-g3ce12bc5e_armhf-buster.deb libmbedtls-dev libasound2-dev libavcodec-dev libavdevice-dev libavfilter-dev libavformat-dev libavutil-dev libcurl4-openssl-dev libfontconfig1-dev libfreetype6-dev libgl1-mesa-dev libjack-jackd2-dev libjansson-dev libluajit-5.1-dev libpulse-dev libqt5x11extras5-dev libspeexdsp-dev libswresample-dev libswscale-dev libudev-dev libv4l-dev libvlc-dev libx11-dev libx11-xcb1 libx11-xcb-dev libxcb-xinput0 libxcb-randr0 libxcb-shm0 libxcb-xfixes0 libxcb-xinerama0 libxcb1 libxcb-xinput-dev libxcb-damage0 libxcb-ewmh2 libxcb-xtest0 libxcb-composite0 libxdamage1 libx264-dev libxcomposite1 libxext6 libxfixes3 libxkbcommon0 libxrandr2 libxshmfence1 pkg-config python3-dev qtbase5-dev libqt5svg5-dev swig libxcb-util1 | libxcb-util0 
Downloading libfdk-aac2_2.0.1-1_armhf.deb... 
01/29 17:56:31 [ERROR] CUID#7 - Download aborted. URI=http://ftp.debian.org/debian/pool/non-free/f/fdk-aac/libfdk-aac2_2.0.1-1_armhf.deb
Exception: [AbstractCommand.cc:403] errorCode=15 URI=http://ftp.debian.org/debian/pool/non-free/f/fdk-aac/libfdk-aac2_2.0.1-1_armhf.deb
  -> [RequestGroup.cc:760] errorCode=15 Download aborted.
  -> [AbstractDiskWriter.cc:224] errNum=13 errorCode=15 Failed to open the file /home/pi/libfdk-aac2_2.0.1-1_armhf.deb, cause: Permission denied
0e2c0a|ERR |       0B/s|/home/pi/libfdk-aac2_2.0.1-1_armhf.deb
(ERR):error occurred.
aria2 will resume download if the transfer is restarted.
If there are any errors, then see the log file. See '-l' option in help/man page for details.
?25h
Failed to download: http://ftp.debian.org/debian/pool/non-free/f/fdk-aac/libfdk-aac2_2.0.1-1_armhf.deb
Please review errors above.

Failed to install OBS Studio!
◢◣Need help? Copy the ENTIRE terminal output or take a screenshot.
Please ask on Github: https://github.com/Botspot/pi-apps/issues/new/choose
Or on Discord: https://discord.gg/RXSTvaUvuu
```
### What are your system specs (run the following command in your terminal)?

```bash
OS: Raspbian GNU/Linux 10 (buster)
OS architecture: 32-bit
Last updated Pi-Apps on: 01/25/2023
Latest Pi-Apps version: 01/26/2023
Kernel: armv7l 5.10.103-v7l+
Device model: Raspberry Pi 4 Model B Rev 1.2 
Cpu name: Cortex-A72
Ram size: 3.83 GB
Raspberry Pi OS image version: 2019-09-26
Language: en_US.UTF-8
```

### (Recommended) Error log? Terminal output? Debug messages?

```bash
pi@raspberrypi:~ $ sudo apt-get install libfdk-aac2_2.0.1-1_armhf.deb
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libfdk-aac2_2.0.1-1_armhf.deb
E: Couldn't find any package by glob 'libfdk-aac2_2.0.1-1_armhf.deb'
E: Couldn't find any package by regex 'libfdk-aac2_2.0.1-1_armhf.deb'
pi@raspberrypi:~ $ dir
Bilder				    obs-studio
Desktop				    Öffentlich
Documents			    pi-apps
Dokumente			    PlayOnLinux's\ virtual\ drives
Downloads			    rpdiags.txt
libfdk-aac2_2.0.1-1_armhf.deb	    Scratch
libfdk-aac-dev_2.0.1-1_armhf.deb    test1
libfdk-aac-dev_2.0.1-1_armhf.deb.1  Videos
MagPi				    Vorlagen
Musik
pi@raspberrypi:~ $ sudo -s
root@raspberrypi:/home/pi# dir
Bilder				    obs-studio
Desktop				    Öffentlich
Documents			    pi-apps
Dokumente			    PlayOnLinux's\ virtual\ drives
Downloads			    rpdiags.txt
libfdk-aac2_2.0.1-1_armhf.deb	    Scratch
libfdk-aac-dev_2.0.1-1_armhf.deb    test1
libfdk-aac-dev_2.0.1-1_armhf.deb.1  Videos
MagPi				    Vorlagen
Musik
root@raspberrypi:/home/pi# sudo apt libfdk-aac2_2.0.1-1_armhf.deb
E: Invalid operation libfdk-aac2_2.0.1-1_armhf.deb
root@raspberrypi:/home/pi# sudo apt install libfdk-aac2_2.0.1-1_armhf.deb
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libfdk-aac2_2.0.1-1_armhf.deb
E: Couldn't find any package by glob 'libfdk-aac2_2.0.1-1_armhf.deb'
E: Couldn't find any package by regex 'libfdk-aac2_2.0.1-1_armhf.deb'
root@raspberrypi:/home/pi#
```

**Comment by theofficialgman** [comment]
it installs just fine: https://github.com/Botspot/pi-apps/actions/runs/4040311754

make sure that your internet isn't broken (blocking websites, etc), that you have space on your pi, and that your home folder isn't root owned

**Comment by Botspot** [comment]
@Lycronix, it looks like you either ran Pi-Apps as root, with `sudo`, or you ran a prior command that changed your entire /home/pi folder to be owned by the root user.

To confirm this, @Lycronix, could you run this command in your terminal?
```
ls -l /home
```

**Comment by theofficialgman** [comment]
> @Lycronix, it looks like you either ran Pi-Apps as root, with `sudo`

pi-apps can't be run as root since july of last year when I added this check https://github.com/Botspot/pi-apps/commit/2819c55e24c4412eb25fbdf089facf1e9c3dc1aa

**Comment by Botspot** [comment]
> @Botspot pi-apps can't be run as root since july of last year when I added this check [2819c55](https://github.com/Botspot/pi-apps/commit/2819c55e24c4412eb25fbdf089facf1e9c3dc1aa)

I know that, but it's still possible that this user ran individual pi-apps app scripts as root. I've seen people do that before. We won't know for sure until @Lycronix replies.

**Comment by theofficialgman** [comment]
> I know that, but it's still possible that this user ran individual pi-apps app scripts as root. I've seen people do that before. We won't know for sure until @Lycronix replies.

I'm sure its this:
> you ran a prior command that changed your entire /home/pi folder to be owned by the root user

considering that we see in their own additional logs that for some reason they are very comfortable with logging in as the root user and running commands as root in their own home folder
```
pi@raspberrypi:~ $ sudo -s
root@raspberrypi:/home/pi# dir
Bilder				    obs-studio
Desktop				    Öffentlich
Documents			    pi-apps
Dokumente			    PlayOnLinux's\ virtual\ drives
Downloads			    rpdiags.txt
libfdk-aac2_2.0.1-1_armhf.deb	    Scratch
libfdk-aac-dev_2.0.1-1_armhf.deb    test1
libfdk-aac-dev_2.0.1-1_armhf.deb.1  Videos
MagPi				    Vorlagen
Musik
root@raspberrypi:/home/pi# sudo apt libfdk-aac2_2.0.1-1_armhf.deb
```

**Comment by Lycronix** [comment]
> ```shell
> pi@raspberrypi:~ $ sudo apt-get install libfdk-aac2_2.0.1-1_armhf.deb
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> E: Unable to locate package libfdk-aac2_2.0.1-1_armhf.deb
> E: Couldn't find any package by glob 'libfdk-aac2_2.0.1-1_armhf.deb'
> E: Couldn't find any package by regex 'libfdk-aac2_2.0.1-1_armhf.deb'
> ```

pi@raspberrypi:~ $ sudo apt-get install libfdk-aac2_2.0.1-1_armhf.deb
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libfdk-aac2_2.0.1-1_armhf.deb
E: Couldn't find any package by glob 'libfdk-aac2_2.0.1-1_armhf.deb'
E: Couldn't find any package by regex 'libfdk-aac2_2.0.1-1_armhf.deb'



still in first i use it to install only in user, later i used in root

**Comment by theofficialgman** [comment]
I will close stale issues. please obey the issue form requests you have agreed to.

- [X] IMPORTANT: I promise to respond to comments on this issue and write a good bug report https://www.softwaretestinghelp.com/how-to-write-good-bug-report/
