### ISSUE TITLE
EDIT ME Include the app name and if it is a Package app or an Install based App

### ISSUE THREAD

**Issue by FabrizzioTroll** [Botspot/pi-apps#2258]
### What is the name of the app?

VS Code for Raspberry Pi

### About the app

It's VS Code for Raspberry Pi

### Upload file or Add PR Link

[VS Code for Raspberry Pi.zip](https://github.com/Botspot/pi-apps/files/10583539/VS.Code.for.Raspberry.Pi.zip)
This is the file, and thank you very much

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by theofficialgman** [comment]
```
This is VS Code (Visual Studio Code), is maked with love by Fabrizzio, if has some bugs, please report it to the email fmu.elmundodelosjuegos@gmail.com
```

```
#!/bin/bash


#Be sure to use the "error" function - it will display a message if a command fails to run. Example below:

git_clone https://example.com || error 'Failed to clone repository!'

# Install some packages that are necessary to run this app - no need for "error", as the install_packages function already handles errors.
install_packages package1 package2 package3 || exit 1
```

are you trolling? for one, as can be clearly seen you haven't even bothered to change the title of this issue or the contents of the install script. for two, vscode is already in pi-apps

**Comment by theofficialgman** [comment]
@Botspot I'm blind, read their username.

please block this user from the repository to teach them a lesson
