### ISSUE TITLE
Stacer

### ISSUE THREAD

**Issue by chunky-milk** [Botspot/pi-apps#226]
It can run smoothly on the Pi, i think it would be a nice addition to Pi-apps
[stacer.zip](https://github.com/Botspot/pi-apps/files/5791502/stacer.zip)

**Comment by fabianmendes** [comment]
Cool, which are the steps that go follow to install it??

**Comment by Botspot** [comment]
Last time I tried Stacer, it displayed a ridiculously large amount of RAM usage. Has that been sorted out yet?

Also, I found it to be somewhat unstable with a few segmentation faults.

**Comment by chunky-milk** [comment]
@Botspot I haven't had any segmentation faults, but the large amount of RAM has not been sorted out. The total amount of RAM being displayed is the only issue right now.

**Comment by chunky-milk** [comment]
@fabianmendes the installation script is inside the stacer.zip file

**Comment by chunky-milk** [comment]
Whoops, forgot to include ``description` file in the zip
here's the updated zipfile
[stacer.2.zip](https://github.com/Botspot/pi-apps/files/5791734/stacer.2.zip)

**Comment by Botspot** [comment]
> @Botspot I haven't had any segmentation faults, but the large amount of RAM has not been sorted out. The total amount of RAM being displayed is the only issue right now.

Let's try to get that fixed first please. After that, if it's sufficiently stable, I'll add it.

**Comment by Botspot** [comment]
Closing until those changes are made.

I suggest somebody opens an issue on Stacer's repo and try to sort things out. And maybe figure out how to compile it from source while you're at it. ;)
