### ISSUE TITLE
I added a broken ppa to my install

### ISSUE THREAD

**Issue by abhineet1992** [Botspot/pi-apps#2260]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)
- [X] IMPORTANT: I promise to respond to comments on this issue and write a good bug report https://www.softwaretestinghelp.com/how-to-write-good-bug-report/

### What happened?

Failed to install WhatsApp!

### Description

Will install these packages: https://github.com/cycool29/whatsapp-for-linux/releases/download/14.0/whatsapp_14.0_arm64.deb 
Waiting until APT locks are released... Done
Downloading whatsapp_14.0_arm64.deb to /tmp/whatsapp_14.0_arm64.deb... 
Done ———————————————————————————————————————————————————————————————————————————
Creating an empty apt-package to install the necessary apt packages...
It will be named: pi-apps-cce960d7
Depends: whatsapp
Running sudo apt update...
Get:1 file:/tmp/pi-apps-local-packages ./ InRelease
Ign:1 file:/tmp/pi-apps-local-packages ./ InRelease
Get:2 file:/tmp/pi-apps-local-packages ./ Release [847 B]
Get:2 file:/tmp/pi-apps-local-packages ./ Release [847 B]
Get:3 file:/tmp/pi-apps-local-packages ./ Release.gpg
Ign:3 file:/tmp/pi-apps-local-packages ./ Release.gpg
Get:4 file:/tmp/pi-apps-local-packages ./ Packages [572 B]
Hit:5 http://security.debian.org/debian-security bullseye-security InRelease
Ign:7 http://ppa.launchpad.net/alessandro-strada/ppa/ubuntu lunar InRelease
Hit:8 http://archive.raspberrypi.org/debian bullseye InRelease
Hit:9 http://deb.debian.org/debian bullseye InRelease
Hit:10 http://deb.debian.org/debian bullseye-updates InRelease
Err:11 http://ppa.launchpad.net/alessandro-strada/ppa/ubuntu lunar Release
  404  Not Found [IP: 2620:2d:4000:1::3e 80]
Hit:6 https://box64.debian.ryanfortner.dev/debian ./ InRelease
E: The repository 'http://ppa.launchpad.net/alessandro-strada/ppa/ubuntu lunar Release' does not have a Release file.
apt update complete.
Failed to run sudo apt update!
APT reported these errors:
E: The repository 'http://ppa.launchpad.net/alessandro-strada/ppa/ubuntu lunar Release' does not have a Release file.
Get:1 file:/tmp/pi-apps-local-packages ./ InRelease
Ign:1 file:/tmp/pi-apps-local-packages ./ InRelease
Get:2 file:/tmp/pi-apps-local-packages ./ Release [847 B]
Get:2 file:/tmp/pi-apps-local-packages ./ Release [847 B]
Get:3 file:/tmp/pi-apps-local-packages ./ Release.gpg
Ign:3 file:/tmp/pi-apps-local-packages ./ Release.gpg
Get:4 file:/tmp/pi-apps-local-packages ./ Packages [572 B]
Hit:5 http://security.debian.org/debian-security bullseye-security InRelease
Ign:7 http://ppa.launchpad.net/alessandro-strada/ppa/ubuntu lunar InRelease
Hit:8 http://archive.raspberrypi.org/debian bullseye InRelease
Hit:9 http://deb.debian.org/debian bullseye InRelease
Hit:10 http://deb.debian.org/debian bullseye-updates InRelease
Err:11 http://ppa.launchpad.net/alessandro-strada/ppa/ubuntu lunar Release
  404  Not Found [IP: 2620:2d:4000:1::3e 80]
Hit:6 https://box64.debian.ryanfortner.dev/debian ./ InRelease
E: The repository 'http://ppa.launchpad.net/alessandro-strada/ppa/ubuntu lunar Release' does not have a Release file.

Failed to install WhatsApp!
◢◣Need help? Copy the ENTIRE terminal output or take a screenshot.
Please ask on Github: https://github.com/Botspot/pi-apps/issues/new/choose
Or on Discord: https://discord.gg/RXSTvaUvuu

### What are your system specs (run the following command in your terminal)?

```bash
OS: Raspberry Pi
```

### (Recommended) Error log? Terminal output? Debug messages?

```bash
Will install these packages: https://github.com/cycool29/whatsapp-for-linux/releases/download/14.0/whatsapp_14.0_arm64.deb 
Waiting until APT locks are released... Done
Downloading whatsapp_14.0_arm64.deb to /tmp/whatsapp_14.0_arm64.deb... 
Done ———————————————————————————————————————————————————————————————————————————
Creating an empty apt-package to install the necessary apt packages...
It will be named: pi-apps-cce960d7
Depends: whatsapp
Running sudo apt update...
Get:1 file:/tmp/pi-apps-local-packages ./ InRelease
Ign:1 file:/tmp/pi-apps-local-packages ./ InRelease
Get:2 file:/tmp/pi-apps-local-packages ./ Release [847 B]
Get:2 file:/tmp/pi-apps-local-packages ./ Release [847 B]
Get:3 file:/tmp/pi-apps-local-packages ./ Release.gpg
Ign:3 file:/tmp/pi-apps-local-packages ./ Release.gpg
Get:4 file:/tmp/pi-apps-local-packages ./ Packages [572 B]
Hit:5 http://security.debian.org/debian-security bullseye-security InRelease
Ign:7 http://ppa.launchpad.net/alessandro-strada/ppa/ubuntu lunar InRelease
Hit:8 http://archive.raspberrypi.org/debian bullseye InRelease
Hit:9 http://deb.debian.org/debian bullseye InRelease
Hit:10 http://deb.debian.org/debian bullseye-updates InRelease
Err:11 http://ppa.launchpad.net/alessandro-strada/ppa/ubuntu lunar Release
  404  Not Found [IP: 2620:2d:4000:1::3e 80]
Hit:6 https://box64.debian.ryanfortner.dev/debian ./ InRelease
E: The repository 'http://ppa.launchpad.net/alessandro-strada/ppa/ubuntu lunar Release' does not have a Release file.
apt update complete.
Failed to run sudo apt update!
APT reported these errors:
E: The repository 'http://ppa.launchpad.net/alessandro-strada/ppa/ubuntu lunar Release' does not have a Release file.
Get:1 file:/tmp/pi-apps-local-packages ./ InRelease
Ign:1 file:/tmp/pi-apps-local-packages ./ InRelease
Get:2 file:/tmp/pi-apps-local-packages ./ Release [847 B]
Get:2 file:/tmp/pi-apps-local-packages ./ Release [847 B]
Get:3 file:/tmp/pi-apps-local-packages ./ Release.gpg
Ign:3 file:/tmp/pi-apps-local-packages ./ Release.gpg
Get:4 file:/tmp/pi-apps-local-packages ./ Packages [572 B]
Hit:5 http://security.debian.org/debian-security bullseye-security InRelease
Ign:7 http://ppa.launchpad.net/alessandro-strada/ppa/ubuntu lunar InRelease
Hit:8 http://archive.raspberrypi.org/debian bullseye InRelease
Hit:9 http://deb.debian.org/debian bullseye InRelease
Hit:10 http://deb.debian.org/debian bullseye-updates InRelease
Err:11 http://ppa.launchpad.net/alessandro-strada/ppa/ubuntu lunar Release
  404  Not Found [IP: 2620:2d:4000:1::3e 80]
Hit:6 https://box64.debian.ryanfortner.dev/debian ./ InRelease
E: The repository 'http://ppa.launchpad.net/alessandro-strada/ppa/ubuntu lunar Release' does not have a Release file.

Failed to install WhatsApp!
◢◣Need help? Copy the ENTIRE terminal output or take a screenshot.
Please ask on Github: https://github.com/Botspot/pi-apps/issues/new/choose
Or on Discord: https://discord.gg/RXSTvaUvuu
```

**Comment by theofficialgman** [comment]
```
Err:11 http://ppa.launchpad.net/alessandro-strada/ppa/ubuntu lunar Release
404 Not Found [IP: 2620:2d:4000:1::3e 80]
E: The repository 'http://ppa.launchpad.net/alessandro-strada/ppa/ubuntu lunar Release' does not have a Release file.
```
please remove or fix any apt repos are not working before running pi-apps. you will not be able to use apt properly without doing so

your ppa from alessandro-strada does not have lunar lobster as a dist target that you have added.
additionally, you should not be using ppas on a debian device without deeep knowledge of apt and dependencies between debian and ubuntu versions

**Comment by theofficialgman** [comment]
I will close stale issues. please obey the issue form requests you have agreed to.

- [X] IMPORTANT: I promise to respond to comments on this issue and write a good bug report https://www.softwaretestinghelp.com/how-to-write-good-bug-report/

**Comment by theofficialgman** [comment]
closing as stale
