### ISSUE TITLE
PI-APPS FOR ARMBIAN JAMMY FOR ORANGEPI3LTS

### ISSUE THREAD

**Issue by rfprof** [Botspot/pi-apps#2262]
### What is the name of the app?

PI-APPS FOR ORANGEPI3LTS

### About the app

I am using orangepi3lts with armbian jammy software
How can I install pi-apps on orangepi3lts

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by theofficialgman** [comment]
please refer to the readme regarding install instructions and supported systems
https://github.com/Botspot/pi-apps#install-pi-apps
