### ISSUE TITLE
UC37software app

### ISSUE THREAD

**Issue by Mrpi314tech** [Botspot/pi-apps#2266]
### What is the name of the app?

UC37software

### (Optional) Where is the app hosted?

https://github.com/Mrpi314tech/UC37software

### About the app

UC37 is a chatbot/task manager for your raspberry pi. UC37 is an artificial intelligence program/task manager that acts like a human. He can help out by doing things like turn on smart plugs and play music. He also keeps track of your system statistics, and end unwanted processes just with voice.

### Upload file or Add PR Link

[UC37software.zip](https://github.com/Botspot/pi-apps/files/10774755/UC37software.zip)

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by Botspot** [comment]
How long did it take you to make this? What voice recognition api are you using and is it cloud-based or onboard?

**Comment by Mrpi314tech** [comment]
I have been working on this for about a year and I am using this speech recognition software: [https://pypi.org/project/SpeechRecognition/](url). It is cloud based.

**Comment by theofficialgman** [comment]
closing stale issues
I don't think there is a desire to have cloud based applications in pi-apps either
