### ISSUE TITLE
Pi-apps isn't launching

### ISSUE THREAD

**Issue by Viktamfrver** [Botspot/pi-apps#2267]
when i try to open pi apps it doesnt respond. i try to open it using terminal but it says "YAD needs to be installed to run Pi-Apps."
i also tried uninstalling and installing. it asks if i also want to uninstall yad when i am uninstalling it. after reinstalling pi apps the same problem is reported

**Comment by Botspot** [comment]
How did you install pi apps?

Did you follow the installation directions found [here](https://github.com/Botspot/pi-apps#install-pi-apps), or did you do something else?

**Comment by Botspot** [comment]
@Viktamfrver, have you seen my last response? Could you answer my questions so I can help you fix pi-apps?

**Comment by Viktamfrver** [comment]
Uum sorry botspot,I've been offline for a long time and i haven't seen your comment. It seems that the problem was with the OS and there was something lacking in it and it always gave an error message.I have made a fresh install and pi-apps works just fine.
Thank you for trying to help me with my issue and for making such a wonderful app.
