### ISSUE TITLE
Installation size (app size, for its installation or after it)

### ISSUE THREAD

**Issue by fabianmendes** [Botspot/pi-apps#227]
Description or warning info. I would like to know how much space I will need or the pi-app expect to be before installation (downloading size would be good too because of mobile/internet Data usage).

Otherwise, The option to decide where to install the app (this one could be a little harder, a term-long proposal for this project? I'll create another issue for this one.

**Comment by Botspot** [comment]
This would probably involve creating a `metadata` file for each app. And that isn't a show-stopper, but let's see the big picture:

**Pi-Apps is designed to be as simple as possible**. This includes app creation.  
If I chose to force everybody to manually type in how much space their app took up and how big it was to download, this would both take longer, and be another added piece of frustration.

And what about the apps where size kind-of depends? What about all the other edge cases neither of us have thought about?

Most importantly, how many people would find this useful? 100%? Probably not. 50%? I don't think so. I think maybe 10% of users would really make decisions based app size. And that's not enough people in my opinion to increase the annoyance level for everyone else.
