### ISSUE TITLE
Update (script app/shortcut)

### ISSUE THREAD

**Issue by DarkAngel404** [Botspot/pi-apps#2270]
### What is the name of the app?

Update

### (Optional) Where is the app hosted?

Hosted on [Github](https://github.com/DarkAngel404/update_pi_apps_script.git)

### About the app

This is a shortcut that allows you to perform the update with a single click.

### Upload file or Add PR Link

README file : [README.md](https://github.com/Botspot/pi-apps/files/10844049/README.md)

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by theofficialgman** [comment]
we already have multiple good featured update helper scripts. this one won't even work for systems that don't have passwordless sudo

closing
