### ISSUE TITLE
I can't install anything!!!

### ISSUE THREAD

**Issue by augustZ123** [Botspot/pi-apps#2274]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)
- [X] IMPORTANT: I promise to respond to comments on this issue and write a good bug report https://www.softwaretestinghelp.com/how-to-write-good-bug-report/

### What happened?

I was installing winehq-stable and I added a repository then when I install some thing in pi apps it dosn't work

### Description

I found out that the repository is causing problems but I don't know how to fix it.

### What are your system specs (run the following command in your terminal)?

```bash
OS: Debian GNU/Linux 11 (bullseye)
OS architecture: 64-bit
Last updated Pi-Apps on: 03/01/2023
Latest Pi-Apps version: 03/02/2023
Kernel: aarch64 5.10.17-v8+
Device model: Raspberry Pi Compute Module 4 Rev 1.1 
Cpu name: Cortex-A72
Ram size: 3.79 GB
Raspberry Pi OS image version: 2022-04-04
Language: en_US.UTF-8
```

### (Recommended) Error log? Terminal output? Debug messages?

```bash
armhf arcitecture already added...
Will install these packages: libraspberrypi0:armhf libssh-gcrypt-4:armhf libgssapi-krb5-2:armhf libkrb5-3:armhf libssl1.1:armhf | libssl3:armhf libcups2:armhf libsdl1.2debian:armhf libopusfile0:armhf libc6:armhf libx11-6:armhf libgdk-pixbuf2.0-0:armhf libgtk2.0-0:armhf libstdc++6:armhf libsdl2-2.0-0:armhf mesa-va-drivers:armhf libsdl1.2-dev:armhf libsdl-mixer1.2:armhf libpng16-16:armhf libcal3d12v5:armhf libsdl2-net-2.0-0:armhf libopenal1:armhf libsdl2-image-2.0-0:armhf libvorbis-dev:armhf libcurl4:armhf osspd:armhf pulseaudio libjpeg62:armhf libudev1:armhf libgl1-mesa-dev:armhf libsnappy1v5:armhf libx11-dev:armhf libsmpeg0:armhf libboost-filesystem1.74.0:armhf libboost-program-options1.74.0:armhf libavcodec58:armhf libavformat58:armhf libswscale5:armhf libmyguiengine3debian1v5:armhf libboost-iostreams1.74.0:armhf libsdl2-mixer-2.0-0:armhf 
Creating an empty apt-package to install the necessary apt packages...
It will be named: pi-apps-5f3374a7
Depends: libavcodec58:armhf, libavformat58:armhf, libboost-filesystem1.74.0:armhf, libboost-iostreams1.74.0:armhf, libboost-program-options1.74.0:armhf, libc6:armhf, libcal3d12v5:armhf, libcups2:armhf, libcurl4:armhf, libgdk-pixbuf2.0-0:armhf, libgl1-mesa-dev:armhf, libgssapi-krb5-2:armhf, libgtk2.0-0:armhf, libjpeg62:armhf, libkrb5-3:armhf, libmyguiengine3debian1v5:armhf, libopenal1:armhf, libopusfile0:armhf, libpng16-16:armhf, libraspberrypi0:armhf, libsdl1.2debian:armhf, libsdl1.2-dev:armhf, libsdl2-2.0-0:armhf, libsdl2-image-2.0-0:armhf, libsdl2-mixer-2.0-0:armhf, libsdl2-net-2.0-0:armhf, libsdl-mixer1.2:armhf, libsmpeg0:armhf, libsnappy1v5:armhf, libssh-gcrypt-4:armhf, libssl1.1:armhf | libssl3:armhf, libstdc++6:armhf, libswscale5:armhf, libudev1:armhf, libvorbis-dev:armhf, libx11-6:armhf, libx11-dev:armhf, mesa-va-drivers:armhf, osspd:armhf, pulseaudio
Running sudo apt update...
Hit:1 http://security.debian.org/debian-security bullseye-security InRelease
Hit:2 http://deb.debian.org/debian bullseye InRelease
Hit:3 http://deb.debian.org/debian bullseye-updates InRelease
Hit:4 https://dl.yarnpkg.com/debian stable InRelease
Hit:5 https://dl.winehq.org/wine-builds/ubuntu impish InRelease
Get:6 https://raw.githubusercontent.com/clockworkpi/apt/main/debian stable InRelease [5,408 B]
Hit:7 https://deb.nodesource.com/node_16.x bullseye InRelease
Hit:8 http://archive.raspberrypi.org/debian bullseye InRelease
Ign:9 https://d.winehg.org/wine-builds/ubuntu impish InRelease
Err:10 https://d.winehg.org/wine-builds/ubuntu impish Release
  Redirection from https to 'http://ww16.d.winehg.org/wine-builds/ubuntu/dists/impish/Release?sub1=20230305-1040-54e5-a815-0796aceb829b' is forbidden [IP: 103.224.212.246 443]
E: The repository 'https://d.winehg.org/wine-builds/ubuntu impish Release' does not have a Release file.
apt update complete.
Failed to run sudo apt update!
APT reported these errors:
E: The repository 'https://d.winehg.org/wine-builds/ubuntu impish Release' does not have a Release file.
Hit:1 http://security.debian.org/debian-security bullseye-security InRelease
Hit:2 http://deb.debian.org/debian bullseye InRelease
Hit:3 http://deb.debian.org/debian bullseye-updates InRelease
Hit:4 https://dl.yarnpkg.com/debian stable InRelease
Hit:5 https://dl.winehq.org/wine-builds/ubuntu impish InRelease
Get:6 https://raw.githubusercontent.com/clockworkpi/apt/main/debian stable InRelease [5,408 B]
Hit:7 https://deb.nodesource.com/node_16.x bullseye InRelease
Hit:8 http://archive.raspberrypi.org/debian bullseye InRelease
Ign:9 https://d.winehg.org/wine-builds/ubuntu impish InRelease
Err:10 https://d.winehg.org/wine-builds/ubuntu impish Release
  Redirection from https to 'http://ww16.d.winehg.org/wine-builds/ubuntu/dists/impish/Release?sub1=20230305-1040-54e5-a815-0796aceb829b' is forbidden [IP: 103.224.212.246 443]
E: The repository 'https://d.winehg.org/wine-builds/ubuntu impish Release' does not have a Release file.

Failed to install Box86!
```

**Comment by Botspot** [comment]
You did not configure that repository correctly. As a result, `sudo apt install` does not work.
Pi-Apps relies on `sudo apt install` for most apps, so it is no surprise you are encountering problems.

I suggest you remove that repository. You could also try to fix it, but it would not be useful as x86 Wine builds from there won't run on a Pi anyway - at least, not without modifications and workarounds.

APT repositories are stored in the `/etc/apt` folder. You can look around this folder by going there in a file manager. However, you cannot make changes to it because the folder is root-owned. I suggest using the file-manager to locate the repository file, then using terminal commands as root to fix it.

The repository will be in one of two places in that folder. Either it will be its own ***file*** in `/etc/apt/sources.list.d`, or it will be a ***line*** in the `/etc/apt/sources.list` file. You need to look through both and see where `https://d.winehg.org/wine-builds/ubuntu` is mentioned, at which point you will need to remove it.

- To remove a file:
  `sudo rm /path/to/file`
- To remove a line in a file:
  `sudo nano /path/to/file`
  This opens the file in a terminal-based text editor. Use the keyboard to navigate to the line to remove, press Backspace to remove it, and then save your changes with Ctrl+S. To exit nano, press Ctrl+X.

**Comment by Botspot** [comment]
@augustZ123, have you seen my previous message? Were you able to try my instructions, and if so, did it work for you?

**Comment by augustZ123** [comment]
Thanks it worked.

**Comment by augustZ123** [comment]
@Botspot another question, when I install pi apps I can’t find wine in it can you tell me how to install it.

**Comment by Botspot** [comment]
> @Botspot another question, when I install pi apps I can’t find wine in it can you tell me how to install it.

Right now, Pi-Apps only has Wine available on 32-bit operating systems. That is why you could not find it. If you wait long enough, Wine will eventually become available on your 64-bit OS, or if you want to, you can install Raspberry Pi OS 32-bit to use Wine now.

Thanks for responding that the original issue was resolved. I will close the issue now. You are still able to reply, but if you encounter any more problems, please open a fresh issue so we can assist you best.
