### ISSUE TITLE
Decide where to install an app (which can be installed  wherels outside of the box/root)

### ISSUE THREAD

**Issue by fabianmendes** [Botspot/pi-apps#228]
As suggested in #227, if there are apps that can be installed without problem in another partition or storage, tell it to the Pi-apps on the installing app phase.

**Comment by Botspot** [comment]
Again, this will vary greatly based on the app. There will be many edge cases and unforseen scenarios that would need to be hammered out and bug tested.

In addition, I've made it a great effort to keep the app-creation process as simple as possible.  
How would most juvenile app creators fell if they had to ensure their app was portable, and would properly install anywhere?

Most app creators would probably give up. Which means, more work for me. And that's the exact opposite of what's needed.

More importantly, how many users would find this useful? I think 10% or less. What about the rest of users? They would not want to choose where apps go, and would find the process both annoying and confusing.

**Comment by fabianmendes** [comment]
Good!! Soorry for _waiste_ for a bit your time! Good to know!
