### ISSUE TITLE
Install option not showing 

### ISSUE THREAD

**Issue by 3301n** [Botspot/pi-apps#2280]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)
- [X] IMPORTANT: I promise to respond to comments on this issue and write a good bug report https://www.softwaretestinghelp.com/how-to-write-good-bug-report/

### What happened?

I can't find the menu to install the apps from Pi-apps.

### Description

When i open Pi-apps everything is fine. It shows the list of apps as normal but when i select an app to install the menu to install it not showing up .
![code](https://user-images.githubusercontent.com/69240615/226092848-430c0ff1-b991-435b-b53a-1f333b2227e6.png)

### What are your system specs (run the following command in your terminal)?

```bash
OS: Kali GNU/Linux Rolling
OS architecture: 64-bit
Last updated Pi-Apps on: 03/15/2023
Latest Pi-Apps version: 03/16/2023
Kernel: aarch64 4.19.127-Re4son-v8l+
Device model: Raspberry Pi 4 Model B Rev 1.1 
Cpu name: Cortex-A72
Ram size: 3.80 GB
Language: en_US.UTF-8
```

### (Recommended) Error log? Terminal output? Debug messages?

```bash
xrandr: Failed to get size of gamma for output default
xrandr: Failed to get size of gamma for output default
pipe is /tmp/tmp.qTFEXtFLCB
tail: warning: --retry only effective for the initial open

Updater mode: set-status

Checking for online changes... Timestamps match.
Reading list file for ''...
Done
Scanning apps... Done
Scanning files... Done
cat: /home/kali/pi-apps/data/update-status/updatable-files: No such file or directory
Selection: Terminals/
Timestamps match.
Reading list file for 'Terminals'...
Selection: Terminals/Hyper
Selection: Terminals/eDEX-UI
Selection: Terminals/Hyper
Selection: Terminals/Hyper
Selection: Terminals/Hyper
xrandr: Failed to get size of gamma for output default
xrandr: Failed to get size of gamma for output default
```

**Comment by theofficialgman** [comment]
Please use pi-apps on a supported debian/Ubuntu distro.
