### ISSUE TITLE
Installing Doom 3 after Box86 destroys Box86

### ISSUE THREAD

**Issue by mobluse** [Botspot/pi-apps#2281]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [ ] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)
- [X] IMPORTANT: I promise to respond to comments on this issue and write a good bug report https://www.softwaretestinghelp.com/how-to-write-good-bug-report/

### What happened?

Running x86 programs after installing Doom 3 and apt autormove doesn't work

### Description

First I installed Box86, and tested it with a program that uses SDL2, and then I installed Doom 3 and cleaned up using apt to save space:
```
sudo apt-get --yes autoremove > /dev/null
sudo apt-get --yes autoclean > /dev/null
sudo apt-get --yes clean
```

```
$ ./x16emu # An x86 Linux program that worked before I installed Doom 3 and cleaned 
bash: ./x16emu: No such file or directory
```

The problem is that Doom 3 install replaces armhf libraries with arm64. At least the armhf libraries are removed after the cleaning/autoremove above. I need to be able to use autoremove in order to save space. arm64 libraries seems not to be able to replace armhf. At least not the way Box86 is constructed now.

### What are your system specs (run the following command in your terminal)?

```bash
OS: Debian GNU/Linux 11 (bullseye)
OS architecture: 64-bit
Last updated Pi-Apps on: 03/19/2023
Latest Pi-Apps version: 03/19/2023
Kernel: aarch64 6.1.19-v8+
Device model: Raspberry Pi 4 Model B Rev 1.4 
Cpu name: Cortex-A72
Ram size: 7.81 GB
Raspberry Pi OS image version: 2022-09-22
Language: en_US.UTF-8
```

**Comment by theofficialgman** [comment]
Please uninstall box86 and doom3 in pi-apps and this install both of them and send the install logs for each one.

**Comment by theofficialgman** [comment]
I accidentially discovered the root of this issue

on newer distros (buster+ and focal+), `libsdl2-mixer-2.0-0` depends on `libopusfile0`. `libopusfile0` is NOT a multiarch compatible package as it places its binaries directly in `/usr/lib/` which is bad practice but still the case for some packages today

Doom 3 installs the `libsdl2-mixer-dev` package which depends on  `libsdl2-mixer-2.0-0`. Box86 currently has  `libsdl2-mixer-2.0-0:armhf` in the package list which will either result in the arm64 package of  `libsdl2-mixer-2.0-0` being removed (along with Doom 3) or a failed install.

I will remove  `libsdl2-mixer-2.0-0:armhf` from the Box86 64bit install script as it is not multiarch compatible on newer distros.
