### ISSUE TITLE
Steam doesn't launch

### ISSUE THREAD

**Issue by Kolpixx** [Botspot/pi-apps#2285]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)
- [X] IMPORTANT: I promise to respond to comments on this issue and write a good bug report https://www.softwaretestinghelp.com/how-to-write-good-bug-report/

### What happened?

Steam doesn't launch

### Description

Steps to reproduce:
1. Install Steam via pi-apps
2. Restart the Raspberry Pi
3. Try to launch it

I tried to install Steam with pi-apps, but when I try to start it. It gives me the error: "Fatal Error: Failed to load steamui.so". I already tried to uninstall and install it again.

### What are your system specs (run the following command in your terminal)?

```bash
OS: Debian GNU/Linux 11 (bullseye)
OS architecture: 64-bit
Last updated Pi-Apps on: 03/27/2023
Latest Pi-Apps version: 03/27/2023
Kernel: aarch64 6.1.19-v8+
Device model: Raspberry Pi 400 Rev 1.0 
Cpu name: Cortex-A72
Ram size: 3.79 GB
Raspberry Pi OS image version: 2022-09-22
Language: en_US.UTF-8
```

### (Recommended) Error log? Terminal output? Debug messages?

```bash
pi@raspberrypi:~ $ /usr/local/bin/steam %U
steam.sh[14615]: Running Steam on debian 11 64-bit
steam.sh[14615]: STEAM_RUNTIME is enabled by the user
setup.sh[14681]: Steam runtime environment up-to-date!
steam.sh[14615]: Steam client's requirements are satisfied
WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
[2023-03-27 10:12:11] Startup - updater built Mar 24 2023 17:19:53
[2023-03-27 10:12:11] Startup - Steam Client launched with: '/home/pi/.local/share/Steam/ubuntu12_32/steam' '-no-cef-sandbox' 'steam://open/minigameslist' '%U'
Installing breakpad exception handler for appid(steam)/version(1679680416)/tid(14721)
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[2023-03-27 10:12:11] Loading cached metrics from disk (/home/pi/.local/share/Steam/package/steam_client_metrics.bin)
[2023-03-27 10:12:11] Failed to load cached hosts file (File 'update_hosts_cached.vdf' not found), using defaults
[2023-03-27 10:12:11] Using the following download hosts for Public, Realm steamglobal
[2023-03-27 10:12:11] 1. http://media.steampowered.com, /client/, Realm 'steamglobal', weight was 1, source = 'baked in'
Installing breakpad exception handler for appid(steam)/version(1679680416)/tid(14722)
[2023-03-27 10:12:11] Checking for update on startup
[2023-03-27 10:12:11] Checking for available updates...
[2023-03-27 10:12:11] Downloading manifest: http://media.steampowered.com/client/steam_client_ubuntu12
[2023-03-27 10:12:11] Manifest download: send request
Installing breakpad exception handler for appid(steam)/version(1679680416)/tid(14723)
[2023-03-27 10:12:11] Manifest download: waiting for download to finish
[2023-03-27 10:12:11] Manifest download: finished
[2023-03-27 10:12:11] Download skipped: /client/steam_client_ubuntu12 version 1679680416, installed version 1679680416, existing pending version 0
[2023-03-27 10:12:11] Nothing to do
[2023-03-27 10:12:11] Verifying installation...
[2023-03-27 10:12:11] Performing checksum verification of executable files
Installing breakpad exception handler for appid(steam)/version(1679680416)/tid(14724)
Installing breakpad exception handler for appid(steam)/version(1679680416)/tid(14725)
[2023-03-27 10:12:15] Verification complete
Failed to load steamui.so - dlerror(): libGL.so.1: cannot open shared object file: No such file or directory
[2023-03-27 10:12:17] Shutdown
pi@raspberrypi:~ $
```

**Comment by theofficialgman** [comment]
libGL.so.1 is the vendor neutral GL dispatch library. if you don't have that present on your system then you likely have bigger issues as this is part of all linux distros with a GUI.

check for the presence of this library since you might have broken your system PATH variable if it can not be found

```
echo "Current system PATH is: $PATH
echo "File info for libGL.so.1:"
file /usr/lib/aarch64-linux-gnu/libGL.so.1
file /usr/lib/aarch64-linux-gnu/libGL.so.1.7.0
echo "Apt info for libgl1:"
apt -qq list libgl1
```

run all commands and send back the output here @Kolpixx

**Comment by theofficialgman** [comment]
@Kolpixx also, you appear to be missing box86 and/or box64 but you have told pi-apps to install them previously.
that means that you may have unintentionally purged them from your install.
Please use pi-apps to uninstall and then install box86 and box64 again.

**Comment by Kolpixx** [comment]
> libGL.so.1 is the vendor neutral GL dispatch library. if you don't have that present on your system then you likely have bigger issues as this is part of all linux distros with a GUI.
> 
> check for the presence of this library since you might have broken your system PATH variable if it can not be found
> 
> ```
> echo "Current system PATH is: $PATH
> echo "File info for libGL.so.1:"
> file /usr/lib/aarch64-linux-gnu/libGL.so.1
> file /usr/lib/aarch64-linux-gnu/libGL.so.1.7.0
> echo "Apt info for libgl1:"
> apt -qq list libgl1
> ```
> 
> run all commands and send back the output here @Kolpixx

```
Current system PATH is: /home/pi/.sdkman/candidates/java/current/bin:/home/pi/.local/bin:/home/pi/bin:/usr/lib/jvm/jdk8u352-b08/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games:/snap/bin:/usr/lib/jvm/jdk8u352-b08/bin
File info for libGL.so.1:
/usr/lib/aarch64-linux-gnu/libGL.so.1: symbolic link to libGL.so.1.7.0
/usr/lib/aarch64-linux-gnu/libGL.so.1.7.0: ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, BuildID[sha1]=6bd6f3d462e3db4dad7afab66a55d5c143cb28ca, stripped
Apt info for libgl1:
libgl1/stable,now 1.3.2-1 arm64  [Installiert,automatisch]
libgl1/stable,now 1.3.2-1 armhf  [Installiert,automatisch]

```

**Comment by theofficialgman** [comment]
@Kolpixx ok do what my previous message said then. box86/64 are not installed but marked in pi-apps as such

**Comment by Kolpixx** [comment]
Thanks. That worked!
