### ISSUE TITLE
netflix

### ISSUE THREAD

**Issue by lol-productions** [Botspot/pi-apps#229]
can you please add netflix to pi apps so people can use netflix on raspberry pi

**Comment by Botspot** [comment]
Take a look at Chromium Widevine.

**Comment by lol-productions** [comment]
i tried netflix still won't runon raspbian.

**Comment by lol-productions** [comment]
chromium widewine doesn't work i tried it and netflix didn't run on it.

**Comment by Botspot** [comment]
> chromium widewine doesn't work i tried it and netflix didn't run on it.


Well then something's wrong with your system. Try updating your OS to Raspberry Pi OS Buster, and run `sudo apt update ; sudo apt full-upgrade`, then try Netflix again.

**Comment by lol-productions** [comment]
i am using the latest version.
