### ISSUE TITLE
EDIT ME Include the app name and if it is a Package app or an Install based App

### ISSUE THREAD

**Issue by Torben0612** [Botspot/pi-apps#2291]
### What is the name of the app?

On Screen Keyboard

### About the app

its a app that lets you use a virtual keyboard for touch screen displays

### Upload file or Add PR Link

[on screen keyboard.zip](https://github.com/Botspot/pi-apps/files/11130822/on.screen.keyboard.zip)

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by theofficialgman** [comment]
https://github.com/Botspot/pi-apps/issues/185
