### ISSUE TITLE
OpenTTD

### ISSUE THREAD

**Issue by twinnnn** [Botspot/pi-apps#2293]
### What is the name of the app?

OpenTTD

### About the app

Its like simsity but older and free to play

### Upload file or Add PR Link

[OpenTTD.zip](https://github.com/Botspot/pi-apps/files/11138136/OpenTTD.zip)

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by theofficialgman** [comment]
Closing because it does not fit the app eligibility rubric https://github.com/Botspot/pi-apps/issues/185 . Please read the note about the use of package apps and compare that to the current game offerings in pi-apps https://github.com/Botspot/pi-apps/wiki/Apps-List#games
