### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by mobilegmYT** [Botspot/pi-apps#23]
[Docker.zip](https://github.com/Botspot/pi-apps/files/5398466/Docker.zip)

**Comment by Botspot** [comment]
I will have to decide if this is eligible.
Pi-Apps is mainly for graphical apps which do cool stuff out-of-the-box, while Docker is not graphical and requires you to do configure stuff for it to do anything.
Like an empty sandbox (docker), instead of a toy (app).

**Comment by Botspot** [comment]
OK I've decided not to add this. While it may be open-source, docker works fine installed from APT, and is intended for the professional developer who knows what he is doing.  
Pi-Apps on the other hand, is intended for standalone useful tools that do stuff out-of-the-box, for beginners.  

Docker does technically fit the criteria, but in this case I don't think it's a good fit for Pi-Apps.
