### ISSUE TITLE
Missing pubkey for box86-debs during apt update

### ISSUE THREAD

**Issue by bbrxr5** [Botspot/pi-apps#2301]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)
- [X] IMPORTANT: I promise to respond to comments on this issue and write a good bug report https://www.softwaretestinghelp.com/how-to-write-good-bug-report/

### What happened?

saying sudo apt update failed when i worked manually

### Description

it says that apt update wont work and i tried it manualy and it updateslike regular the one thing im confused on is box 86

### What are your system specs (run the following command in your terminal)?

```bash
OS: Debian GNU/Linux 11 (bullseye)
OS architecture: 64-bit
Last updated Pi-Apps on: 04/09/2023
Latest Pi-Apps version: 04/10/2023
Kernel: aarch64 6.1.21-v8+
Device model: Raspberry Pi 4 Model B Rev 1.1 
Cpu name: Cortex-A72
Ram size: 3.47 GB
Raspberry Pi OS image version: 2023-02-21
Language: en_US.UTF-8
```

### (Recommended) Error log? Terminal output? Debug messages?

```bash
Failed to run sudo apt update!
APT reported these errors:
E: The repository 'https://ryanfortner.github.io/box86-debs/debian ./ InRelease' is not signed.
Hit:1 http://security.debian.org/debian-security bullseye-security InRelease
Hit:4 http://archive.raspberrypi.org/debian bullseye InRelease
Get:3 https://box86.debian.ryanfortner.dev/debian ./ InRelease [2,115 B]
Hit:2 https://box64.debian.ryanfortner.dev/debian ./ InRelease
Err:3 https://box86.debian.ryanfortner.dev/debian ./ InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 23F03A72C8C4A15E
Hit:5 http://deb.debian.org/debian bullseye InRelease
Hit:6 http://deb.debian.org/debian bullseye-updates InRelease
W: GPG error: https://box86.debian.ryanfortner.dev/debian ./ InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 23F03A72C8C4A15E
E: The repository 'https://ryanfortner.github.io/box86-debs/debian ./ InRelease' is not signed.

Failed to install Box86!
```

**Comment by theofficialgman** [comment]
Please upload/attach all logs from the ~/pi-apps/logs that contain Steam, Box86, and Box64
