### ISSUE TITLE
need help uninstalling/disabling foreign architectures

### ISSUE THREAD

**Issue by Fresh-Squeezed-Lemonade** [Botspot/pi-apps#2304]
I don't know how it happened, but I log onto my Orange pi 5 one day and I try to open pi-apps and it never opens. I think to myself, "That's weird, I'll try opening it from terminal." When I open it from terminal, right as it starts running the command to run pi-apps, it just closes itself down. I have no idea what caused it. Please help. I've tried to reinstall it but it says that it can't because I have to "fix your apt package-management system."

**Comment by theofficialgman** [comment]
If you get a "fix your apt package-management system" error then that is because your APT is broken.

Run `sudo apt update` and report the output here.

Unfortunatly for you, the Orange PiOS is garbage and the developers there do not know what they are doing. So it is quite likely that they broke your OS in an update.

**Comment by Fresh-Squeezed-Lemonade** [comment]
N: Skipping acquire of configured file 'main/binary-amd6/Packages' as repository 'https://adoptium.jfrog.io/artifactory/deb jammy InRelease' doesn't support architecture 'amd6'
W: https://repo.huaweicloud.com/docker-ce/linux/ubuntu/dists/jammy/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
N: Skipping acquire of configured file 'main/binary-amd6/Packages' as repository 'http://repo.huaweicloud.com/ubuntu-ports jammy InRelease' doesn't support architecture 'amd6'
N: Skipping acquire of configured file 'universe/binary-amd6/Packages' as repository 'http://repo.huaweicloud.com/ubuntu-ports jammy InRelease' doesn't support architecture 'amd6'
N: Skipping acquire of configured file 'multiverse/binary-amd6/Packages' as repository 'http://repo.huaweicloud.com/ubuntu-ports jammy InRelease' doesn't support architecture 'amd6'
N: Skipping acquire of configured file 'restricted/binary-amd6/Packages' as repository 'http://repo.huaweicloud.com/ubuntu-ports jammy InRelease' doesn't support architecture 'amd6'
N: Skipping acquire of configured file 'restricted/binary-amd6/Packages' as repository 'http://repo.huaweicloud.com/ubuntu-ports jammy-security InRelease' doesn't support architecture 'amd6'
N: Skipping acquire of configured file 'main/binary-amd6/Packages' as repository 'http://repo.huaweicloud.com/ubuntu-ports jammy-security InRelease' doesn't support architecture 'amd6'
N: Skipping acquire of configured file 'multiverse/binary-amd6/Packages' as repository 'http://repo.huaweicloud.com/ubuntu-ports jammy-security InRelease' doesn't support architecture 'amd6'
N: Skipping acquire of configured file 'universe/binary-amd6/Packages' as repository 'http://repo.huaweicloud.com/ubuntu-ports jammy-security InRelease' doesn't support architecture 'amd6'
N: Skipping acquire of configured file 'universe/binary-amd6/Packages' as repository 'http://repo.huaweicloud.com/ubuntu-ports jammy-updates InRelease' doesn't support architecture 'amd6'
N: Skipping acquire of configured file 'multiverse/binary-amd6/Packages' as repository 'http://repo.huaweicloud.com/ubuntu-ports jammy-updates InRelease' doesn't support architecture 'amd6'
N: Skipping acquire of configured file 'restricted/binary-amd6/Packages' as repository 'http://repo.huaweicloud.com/ubuntu-ports jammy-updates InRelease' doesn't support architecture 'amd6'
N: Skipping acquire of configured file 'main/binary-amd6/Packages' as repository 'http://repo.huaweicloud.com/ubuntu-ports jammy-updates InRelease' doesn't support architecture 'amd6'
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://repo.huaweicloud.com/ubuntu-ports jammy-backports InRelease: Splitting up /var/lib/apt/lists/partial/repo.huaweicloud.com_ubuntu-ports_dists_jammy-backports_InRelease into data and signature failed
W: Failed to fetch http://repo.huaweicloud.com/ubuntu-ports/dists/jammy-backports/InRelease  Splitting up /var/lib/apt/lists/partial/repo.huaweicloud.com_ubuntu-ports_dists_jammy-backports_InRelease into data and signature failed
E: Failed to fetch http://repo.huaweicloud.com/ubuntu-ports/dists/jammy/multiverse/binary-amd64/Packages  404  Not Found [IP: 194.26.73.113 80]
E: Failed to fetch http://repo.huaweicloud.com/ubuntu-ports/dists/jammy-security/multiverse/binary-i386/Packages  404  Not Found [IP: 194.26.73.113 80]
E: Failed to fetch http://repo.huaweicloud.com/ubuntu-ports/dists/jammy-updates/main/binary-amd64/Packages  404  Not Found [IP: 194.26.73.113 80]
W: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by theofficialgman** [comment]
this is user error, not the distro
you added architectures amd64, i386, and maybe amd6 which I assume was you making a typo, lol.

don't add non-native architecture packages to your device. it is an arm64 device and can only natively run arm64 and armhf.

remove those broken architectures with dpkg

```
sudo dpkg --remove-architecture i386
sudo dpkg --remove-architecture amd64
sudo dpkg --remove-architecture amd6
```

**Comment by Fresh-Squeezed-Lemonade** [comment]
That didn't work
orangepi@orangepi5:~$ sudo dpkg --remove-architecture i386
[sudo] password for orangepi: 
Sorry, try again.
[sudo] password for orangepi: 
dpkg: error: cannot remove architecture 'i386' currently in use by the database
orangepi@orangepi5:~$ sudo dpkg --remove-architecture amd64
pkg-config-dpkghook: warning: Architecture amd6 not defined in architecture tables, ignored
orangepi@orangepi5:~$ sudo dpkg --remove-architucture amd6
dpkg: error: unknown option --remove-architucture

Type dpkg --help for help about installing and deinstalling packages [*];
Use 'apt' or 'aptitude' for user-friendly package management;
Type dpkg -Dhelp for a list of dpkg debug flag values;
Type dpkg --force-help for a list of forcing options;
Type dpkg-deb --help for help about manipulating *.deb files;

Options marked [*] produce a lot of output - pipe it through 'less' or 'more' !

**Comment by Fresh-Squeezed-Lemonade** [comment]
Reading package lists... Done
E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
E: Unable to lock directory /var/lib/apt/lists/
W: Problem unlinking the file /var/cache/apt/pkgcache.bin - RemoveCaches (13: Permission denied)
W: Problem unlinking the file /var/cache/apt/srcpkgcache.bin - RemoveCaches (13: Permission denied)

**Comment by theofficialgman** [comment]
@Fresh-Squeezed-Lemonade please use copy/paste instead of trying to write the commands out yourself. you made multiple typos which is why they did not work.

**Comment by Fresh-Squeezed-Lemonade** [comment]
I did copy and paste. It still isn't working

**Comment by theofficialgman** [comment]
well regarding this:
```
dpkg: error: cannot remove architecture 'i386' currently in use by the database
```
you need to uninstall any and all packages from i386 that are currently installed

and this like I said is a typo
```
sudo dpkg --remove-architucture amd6
```
architecture is misspelled. you would not have gotten that with a copy paste
