### ISSUE TITLE
Can't install pi apps on rpi os

### ISSUE THREAD

**Issue by Linkdash2019** [Botspot/pi-apps#2311]
my command output:

linkdash@raspberry:~ $ git clone https://github.com/Botspot/pi-apps
~/pi-apps/install
Cloning into 'pi-apps'...
remote: Enumerating objects: 23229, done.
remote: Counting objects: 100% (1546/1546), done.
remote: Compressing objects: 100% (130/130), done.
remote: Total 23229 (delta 1450), reused 1461 (delta 1416), pack-reused 21683
Receiving objects: 100% (23229/23229), 28.12 MiB | 12.19 MiB/s, done.
Resolving deltas: 100% (14962/14962), done.
Pi-Apps is not supported on non-ARM CPU architectures. We encourage you to use your distro's app store, like Gnome Software or Discover Software Center.

I am on a vm.. Is that the problem?

**Comment by theofficialgman** [comment]
You are on a VM of what operating system on what architecture? The "Raspberry Pi Desktop" which is an x86_64 OS is not a supported target for pi-apps.

Pi-Apps only supports ARMhf and ARM64 operating systems.
