### ISSUE TITLE
Tlauncher

### ISSUE THREAD

**Issue by cdkw2** [Botspot/pi-apps#2312]
### What is the name of the app?

Tlauncher

### (Optional) Where is the app hosted?

https://tlauncher.org/en/

### About the app

Minecraft launcher.

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by theofficialgman** [comment]
https://github.com/Botspot/pi-apps/issues/927
https://github.com/Botspot/pi-apps/issues/213
https://github.com/Botspot/pi-apps/issues/185
