### ISSUE TITLE
App sugestion: Krita

### ISSUE THREAD

**Issue by cdkw2** [Botspot/pi-apps#2314]
### What is the name of the app?

Krita

### (Optional) Where is the app hosted?

It's available on github I suppose and can be installed on RPi with snap store but I think that installing it with Piapps would be much more user friendly. 

### About the app

East photoshop like free a d opensource app.

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [x] I have confirmed that this app can run on Raspberry Pi.

**Comment by Botspot** [comment]
Version 4.4.2 can be installed with `sudo apt install krita`, but I can see that the snap store version is 5.1.5.

If a Pi-Apps maintainer has spare time and would like to find a way to add the latest version of Krita while avoiding Snap, I would be fine with adding it, as per the guidelines on our [App Eligibility Rubric](https://github.com/Botspot/pi-apps/issues/185).

**Comment by theofficialgman** [comment]
I would strongly avoid snap for the reasons I outlined before. I am not opposed to the flatpak version.
Krista is infeasible to install via any other method. Like other KDE apps it requires the latest QT version.

I personally use the flatpak and it works great

**Comment by cdkw2** [comment]
> I would strongly avoid snap for the reasons I outlined before. I am not opposed to the flatpak version (also the latest 5.1.5). Krista is infeasible to install via any other method. Like other KDE apps it requires the latest QT version.
> 
> I personally use the flatpak and it works great
Thank you for letting me know that there are better wayd o achieving it. 

^_^
