### ISSUE TITLE
GNOME Clock

### ISSUE THREAD

**Issue by cdkw2** [Botspot/pi-apps#2319]
### What is the name of the app?

Clock

### (Optional) Where is the app hosted?

https://gitlab.gnome.org/GNOME/gnome-clocks

### About the app

A simple clock application for GNOME. It includes world clocks, alarms, a stopwatch and a timer.

You can install this with ``` sudo apt install gnome-clocks ```

But I thin it would be easy to use you awesome app store!

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by Botspot** [comment]
Hello, we do not usually add apps if they are straight from `apt`. The idea is that if it is that easy to install, then Pi-apps is not necessary to install it. Please refer to our app eligibility rubric, available [here](https://github.com/Botspot/pi-apps/issues/185). Please pay particular attention to the bit about _package apps._

Can you think of any reasons that we should make an exception in this case?

**Comment by cdkw2** [comment]
> Hello, we do not usually add apps if they are straight from `apt`. The idea is that if it is that easy to install, then Pi-apps is not necessary to install it. Please refer to our app eligibility rubric, available [here](https://github.com/Botspot/pi-apps/issues/185). Please pay particular attention to the bit about _package apps._
> 
> Can you think of any reasons that we should make an exception in this case?

Oh ok I understand it now, I thought of recommending it because I read this line from the website.

![Screenshot_20230505-113207_Chrome.jpg](https://user-images.githubusercontent.com/67598073/236387024-feff612d-325e-44fb-bf1e-9d14b2eaf544.jpg)

**Comment by Rak1ta** [comment]
@Botspot Batch applications are easy to install.  It's hard to find such a package even available in this "Debian app store".
