### ISSUE TITLE
Minor Writing issue

### ISSUE THREAD

**Issue by cdkw2** [Botspot/pi-apps#2320]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)
- [X] IMPORTANT: I promise to respond to comments on this issue and write a good bug report https://www.softwaretestinghelp.com/how-to-write-good-bug-report/

### What happened?

Minor issue with the text

### Description

Hello awesome developers of pi-apps,
It's my first time writing a bug report so sorry if it's scuffed.

So I was opening your store and found that the random text that appears on the top has some issue.

The text says "Want to make a app? Click on Create App in settings!"

But when I actually click the setting button, there is no create app button. There is just "New app" button, which welcomes me to the Create App wizard. 

Not that big of a issue but I just felt like writing so that I could also help for once :)

Here, I have added the screenshot's too!

![error](https://user-images.githubusercontent.com/67598073/236517324-a8e5c96b-9b02-4afb-8a07-2a5ec586cedb.png)

![error2](https://user-images.githubusercontent.com/67598073/236517377-7d25b656-603e-455d-9ca4-cd9937de4902.png)

### What are your system specs (run the following command in your terminal)?

```bash
OS: Debian GNU/Linux 11 (bullseye)
OS architecture: 64-bit
Last updated Pi-Apps on: 05/04/2023
Latest Pi-Apps version: 05/05/2023
Kernel: aarch64 6.1.21-v8+
Device model: Raspberry Pi 4 Model B Rev 1.2 
Cpu name: Cortex-A72
Ram size: 3.79 GB
Raspberry Pi OS image version: 2023-02-21
Language: en_US.UTF-8
```

### (Recommended) Error log? Terminal output? Debug messages?

```bash
Nothing to write here :)
```

**Comment by Botspot** [comment]
Thank you for reporting. I have fixed it now.
https://github.com/Botspot/pi-apps-announcements/commit/7333fa1d83f4a497920ef0601af0dafb2a9cf881
