### ISSUE TITLE
StackEdit refuses to run; old build

### ISSUE THREAD

**Issue by ApricotFarm** [Botspot/pi-apps#2321]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)
- [X] IMPORTANT: I promise to respond to comments on this issue and write a good bug report https://www.softwaretestinghelp.com/how-to-write-good-bug-report/

### What happened?

StackEdit won't launch after install; "old build" notification

### Description

With brand new installation of Pi-apps (on a virgin, fully updated Pi OS installation), I installed StackEdit. When I try to run it, I get a message informing me that it's based on an old build, and refuses to run. 

![2023-05-06_15-19](https://user-images.githubusercontent.com/25875880/236643637-f8d4e702-051c-48d4-bf13-50203ce73db1.png)

### What are your system specs (run the following command in your terminal)?

```bash
OS: Raspbian GNU/Linux 11 (bullseye)
OS architecture: 32-bit
Last updated Pi-Apps on: 05/04/2023
Latest Pi-Apps version: 05/04/2023
Kernel: aarch64 6.1.21-v8+
Device model: Raspberry Pi 4 Model B Rev 1.4 
Cpu name: Cortex-A72
Ram size: 1.84 GB
Raspberry Pi OS image version: 2023-05-03
Language: en_US.UTF-8
```

**Comment by ApricotFarm** [comment]
I'm not really sure what that means, nor do I have the slightest idea of how I would go about running this app in a web browser. At any rate, I've tried running it again after another fresh installation (of 64-bit Pi OS) -- this time I still get the warning, but the app actually runs. 

Maybe it's a 32 vs 64-bit OS issue, but if the app is really going to be dropped, I suppose the issue is moot.

**Comment by Itai-Nelken** [comment]
> I'm not really sure what that means, nor do I have the slightest idea of how I would go about running this app in a web browser. [...]

Stackedit is a website which can be accessed here: https://stackedit.io/app

**Comment by ApricotFarm** [comment]
> Stackedit is a website which can be accessed here: https://stackedit.io/app

Ah, I see now...@theofficialgman is saying not to use the pi-apps installed app at all, but rather to use the webapp version that you linked to.

**Comment by ApricotFarm** [comment]
Annnd as of yesterday, @theofficialgman has hidden the app from the install menu (commit #ea3b528), so I guess they really don't want this app around. Question is moot.

**Comment by theofficialgman** [comment]
don't close, this is temporary until either it is actually removed or transitioned to a webapp
