### ISSUE TITLE
Can't click on apps

### ISSUE THREAD

**Issue by cdkw2** [Botspot/pi-apps#2324]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)
- [X] IMPORTANT: I promise to respond to comments on this issue and write a good bug report https://www.softwaretestinghelp.com/how-to-write-good-bug-report/

### What happened?

Can't open apps in Pi Apps

### Description

So I just wanted to install my favorite apps with pi apps but I wasn't able to install because I just wasn't able to click on the apps for some reason. Please tell me how to fix this? I have attached a video of me trying.

https://github.com/Botspot/pi-apps/assets/67598073/6118d1f8-c75a-430e-bf39-f3b6ac1acb89

### What are your system specs (run the following command in your terminal)?

```bash
OS: Debian GNU/Linux 11 (bullseye)
OS architecture: 64-bit
Last updated Pi-Apps on: 05/11/2023
Latest Pi-Apps version: 05/11/2023
Kernel: aarch64 6.1.21-v8+
Device model: Raspberry Pi 4 Model B Rev 1.2 
Cpu name: Cortex-A72
Ram size: 3.79 GB
Raspberry Pi OS image version: 2023-02-21
Language: en_US.UTF-8
```

**Comment by cdkw2** [comment]
Oh well

![image](https://github.com/Botspot/pi-apps/assets/67598073/fb39c86f-e598-4dd4-9571-22d2498c913a)

**Comment by cdkw2** [comment]
I am pretty sure, pi-apps in installed

**Comment by Botspot** [comment]
Run `~/pi-apps/install`

**Comment by theofficialgman** [comment]
if the `gio` command is hanging, then you likely have some corruption on your OS and that is very difficult to debug

I suggest re-installing your OS from scratch and make sure to always cleanly shutdown your system (ie: don't pull the plug on your pi)

**Comment by cdkw2** [comment]
hmm so I made up my mind to reinstall me os but is there a any to keep all my data and preference and all of my current raspberry pi on the new os I ill be installing?

**Comment by cdkw2** [comment]
@theofficialgman I think you would be able to help me here.

So I have reinstalled m OS THREE TIMES !!! but still this problem is happening.

When I type
``` wget -qO- https://raw.githubusercontent.com/Botspot/pi-apps/master/install | bash ```
The command just doesn't do anything and gets stuck. and if I try to manually install with 
``` git clone https://github.com/Botspot/pi-apps && ~/pi-apps/install ```
it gets stuck on the following console output.
``` cdkw2@raspberrypi:~ $ git clone https://github.com/Botspot/pi-apps
~/pi-apps/install
Cloning into 'pi-apps'...
remote: Enumerating objects: 23420, done.
remote: Counting objects: 100% (1636/1636), done.
remote: Compressing objects: 100% (234/234), done.
remote: Total 23420 (delta 1445), reused 1549 (delta 1400), pack-reused 21784
Receiving objects: 100% (23420/23420), 28.19 MiB | 3.22 MiB/s, done.
Resolving deltas: 100% (15054/15054), done.
Hit:1 http://security.debian.org/debian-security bullseye-security InRelease
Hit:2 http://archive.raspberrypi.org/debian bullseye InRelease                 
Hit:3 http://deb.debian.org/debian bullseye InRelease                          
Get:4 http://deb.debian.org/debian bullseye-updates InRelease [44.1 kB]        
Hit:5 https://apt.packages.shiftkey.dev/ubuntu any InRelease                   
Hit:6 https://mirror.mwt.me/shiftkey-desktop/deb any InRelease
Fetched 44.1 kB in 2s (25.7 kB/s)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.

Preloading app list...

```

It gets stuck like the wget command and just doesn't do anything for like hours. Any solutions because I am loosing my mind now, I just wanted to install GitHub desktop and I can't even do that now :sob:

**Comment by cdkw2** [comment]
And since I have reinstalled my os, all of the previous working pi-apps are also gone now.

**Comment by cdkw2** [comment]
And I have also noticed that when the output get's stuck, **the cpu usage goes down significantly** and when I tried 
``` wget -v https://raw.githubusercontent.com/Botspot/pi-apps/master/install ```
to see the log, It gets stuck on this:
``` cdkw2@raspberrypi:~ $ wget -v https://raw.githubusercontent.com/Botspot/pi-apps/master/install
--2023-05-14 14:40:42--  https://raw.githubusercontent.com/Botspot/pi-apps/master/install
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 2405:200:1607:2820:41::36, 49.44.79.236
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|2405:200:1607:2820:41::36|:443... failed: Connection timed out.
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|49.44.79.236|:443... 
```

Maybe this information could help you figure out the problem ¯\_(ツ)_/¯

**Comment by theofficialgman** [comment]
Your internet is bad though.
Are you in China or Russia or similar country that blocks major parts of the internet? raw.githubusercontent.com is being blocked and from my experience testing on a system in China the internet packets get forwarded randomly, timeout, or return in error which is causing the strange results.

**Comment by cdkw2** [comment]
> Your internet is bad though.
> Are you in China or Russia or similar country that blocks major parts of the internet? raw.githubusercontent.com is being blocked and from my experience testing on a system in China the [great firewall](https://en.m.wikipedia.org/wiki/Great_Firewall) causes internet packets get forwarded randomly, timeout, or return in error which is causing the strange results.

I am in India, and one of my friend uses raspberry pi too so I told him to try installing pi-apps with the steps I used and he was able to successfully run and use the app.

**Comment by theofficialgman** [comment]
I'm not sure what else to say other than use a VPN. You are experiencing internet blocking. Pi-apps simply can't run without access to github/githubrawusercontent.

**Comment by cdkw2** [comment]
What countryside VPN would be suitable?

**Comment by cdkw2** [comment]
What countryside VPN would be suitable?

**Comment by theofficialgman** [comment]
any country in the EU (european union) or the USA. pretty much anyone that doesn't block the internet

**Comment by cdkw2** [comment]
P

**Comment by Botspot** [comment]
> Phew, the issue is now resolved and I didn't even had to use a VPN!

What changed?

**Comment by nasyx-rakeeb** [comment]
Hi, i am facing the same issue, it gets stuck on "preloading apps list" and i also can't install it from wget it just gets stuck i installed by cloning github repository and running install script but now it has the same delay to open app details in the new window areound 7-9 minutes, is there a fix

**Comment by nasyx-rakeeb** [comment]
Ok i solved it, the issue was because my network was unable to access the raw.githubusercontent so i added the dns of cloudflare in my raspberry pi and it works now like a charm
