### ISSUE TITLE
pi-apps not open 

### ISSUE THREAD

**Issue by vpurushothamanpurushothaman** [Botspot/pi-apps#2326]
pi-apps not open in my latest version of raspberry pi os

**Comment by Botspot** [comment]
@vpurushothamanpurushothaman, thank you for asking for help.
You mentioned that pi-apps is not opening for you.

- How did you install pi-apps? Did you follow our instructions to install it, or did you use someone else's instructions which were different?
- Were there any errors when you were installing Pi-Apps?
- What kind of system are you using? Some people try to run pi-apps on their phone or PC computer - both of which take extra steps to get working.
- How did you run pi-apps? Could you try running it in a terminal? (Just open a terminal and run `pi-apps`)

**Comment by theofficialgman** [comment]
@vpurushothamanpurushothaman please use the bug report template that exists when submitting a bug report. this makes narrowing down your issue much easier and guides you into giving us the necessary information for solving your problem.

**Comment by theofficialgman** [comment]
closing as stale. we can't help you if you don't respond
