### ISSUE TITLE
please update Kodi version

### ISSUE THREAD

**Issue by tollkuehn82** [Botspot/pi-apps#2330]
### What is the name of the app?

Kodi version (20.1, Nexus)

### About the app

The current version 18 (Matrix) comes with outdated plugins like InputStreamAdaptive, which in turn does not support the new 64-bit version of widevine. Therefore Netflix is not possible on a 64-bit Rasperry Pi OS. In the newer Kodi this is all adapted and fixed... but this can only be installed with difficulty for laymen.

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have read the app eligibilty rubric https://github.com/Botspot/pi-apps/issues/185 and confirmed this app is suitable for addition in Pi-Apps.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi-Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by theofficialgman** [comment]
Kodi is a package app meaning it comes directly from apt.
It is much too complicated to install it from any other method. It will be updated as you update your distro (eg: move to a debian bookworm or Ubuntu lunar or newer)

I also suggest if you want to use Kodi frequently always on the latest version that you use the official libreelec distro https://libreelec.tv/downloads/

**Comment by tollkuehn82** [comment]
Thank you for the info. Just for understanding. If it comes from apt why is it then includet in pi-apps? (I thought only additional software is there).
