### ISSUE TITLE
Add Minetest 5.7.0

### ISSUE THREAD

**Issue by Thepotato2** [Botspot/pi-apps#2334]
### What is the name of the app?

Minetest 5.7.0

### About the app

Minetest is a game similar to Minecraft, however is has many differences from Minecraft, the main thing being that its made for modding and is programmed in lua, one of the easier programming language to learn, however i have tried to get it for my pi and while yes, i can get and old version, i cant seem to get the newest version. it would be nice to add this to Pi-Apps.

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have read the app eligibilty rubric https://github.com/Botspot/pi-apps/issues/185 and confirmed this app is suitable for addition in Pi-Apps.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi-Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by theofficialgman** [comment]
already been discussed here https://github.com/Botspot/pi-apps/issues/944 here https://github.com/Botspot/pi-apps/issues/575 and here https://github.com/Botspot/pi-apps/issues/546

the important reasons for closing are https://github.com/Botspot/pi-apps/issues/546#issuecomment-1120317474 and https://github.com/Botspot/pi-apps/issues/944#issuecomment-914852789

if you are able to build the latest version and confirm the performance issues are no longer an issue then the original app request can be re-opened but as it is this issue will be closed as a duplicate
