### ISSUE TITLE
Minecraft Server Forge installer broken

### ISSUE THREAD

**Issue by Botspot** [Botspot/pi-apps#2339]
Asking @theofficialgman to investigate line 70 in the Minecraft Java Server install script to see why it now returns nothing.
```
installer_version=$(curl -s https://files.minecraftforge.net/net/minecraftforge/forge/maven-metadata.json | jq -r '.'\"$server_version\"' | [last] | .[]')
```
I would do it but I don't understand jq syntax well yet.

**Comment by theofficialgman** [comment]
You sure anything there is wrong? Refer to https://discord.com/channels/770629697909424159/874656141475463229/1109237728358445056

**Comment by Botspot** [comment]
> You sure anything there is wrong?

Not anymore. I was looking at the wrong bit of script, which turns out to be much easier to do for scripts I did not write. 😆
Sorry for wasting your time.
