### ISSUE TITLE
Add Parler

### ISSUE THREAD

**Issue by blaze005** [Botspot/pi-apps#234]
This will run on the RPI-4. But I am unsure if parler is able to run on an ARM CPU currently.

**Comment by Botspot** [comment]
> This will run on the RPI-4. But I am unsure if parler is able to run on an ARM CPU currently.

The RPi-4 is an ARM CPU. So can Parler run on it or not?

**Comment by blaze005** [comment]
> > This will run on the RPI-4. But I am unsure if parler is able to run on an ARM CPU currently.
> 
> The RPi-4 is an ARM CPU. So can Parler run on it or not?

I am currently waiting for a response from the Parler Developers. As soon as I get info I will let you know ASAP

**Comment by mobilegmYT** [comment]
Which parler are you talking about? If it's the one thats been on the news lately, then I don't think it should exactly be on pi-apps.

**Comment by blaze005** [comment]
> Which parler are you talking about? If it's the one thats been on the news lately, then I don't think it should exactly be on pi-apps.

I understand your stance and your concerns. However the freedom of speech has been trampled upon for millions of people just because of a select few. I was on parler and I don’t ever recall a Capitol Storm being planned. I even followed the proud boys none of their posts on parler were “extremist”. I would also like to point out how come pedo groups are allowed on Twitter or MAP (minor attracted person). In my opinion it is an injustice and I hope you see and understand my concerns.
Thank You!

**Comment by mobilegmYT** [comment]
Hrm, also, can't you just use their website? I can't seem to find a parler desktop app anywhere.

**Comment by blaze005** [comment]
> Hrm, also, can't you just use their website? I can't seem to find a parler desktop app anywhere.

Parler was taken down by AWS (Amazon Web Services) How ever amazon broke the law, antitrust laws. Parler is suing amazon for this. Parler was also taken down by Apple and Google major app stores. So you can’t even access the site for now. This is why I am trying to get in contact with the developers so that they can possibly make a Linux desktop version when they get the site back up. Than your service would be one of the ways to download it. You do have the right to not accept my request. But I do want the consideration. 
Thank You.

**Comment by Botspot** [comment]
> > Which parler are you talking about? If it's the one thats been on the news lately, then I don't think it should exactly be on pi-apps.
> 
> I understand your stance and your concerns. However the freedom of speech has been trampled upon for millions of people just because of a select few. I was on parler and I don’t ever recall a Capitol Storm being planned. I even followed the proud boys none of their posts on parler were “extremist”. I would also like to point out how come pedo groups are allowed on Twitter or MAP (minor attracted person). In my opinion it is an injustice and I hope you see and understand my concerns.
> Thank You!

mobilegmYT does not decide which apps are eligible. I, Botspot, am the Pi-Apps developer. I'm the one who decides.  
If someone made an "app" that just opened parler.com in a browser, I'd probably not see the point. But, like you suggested, if there was some sort of secure portal that needed its own client, I'd be more than happy to add it.

**Comment by Botspot** [comment]
@blaze005 Would you mind if I close this issue now, and re-open it if Parler chooses to make a Linux-compatible portal app?

We try to keep issues open only if they are being actively worked on/
