### ISSUE TITLE
WPS Office no longer launches with firejail

### ISSUE THREAD

**Issue by theofficialgman** [Botspot/pi-apps#2345]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)
- [X] IMPORTANT: I promise to respond to comments on this issue and write a good bug report https://www.softwaretestinghelp.com/how-to-write-good-bug-report/

### What happened?

Run WPS office using the pi-apps edited .desktop files and it crashes

### Description

Running without firejail (eg: `/usr/bin/wps`) works normally.

If this could be tested on other distros to confirm it is not just an issue on bionic that would be great.

### What are your system specs (run the following command in your terminal)?

```bash
OS: Ubuntu 18.04.6 LTS
OS architecture: 64-bit
Last updated Pi-Apps on: 06/01/2023
Latest Pi-Apps version: 05/31/2023
Kernel: aarch64 4.9.140-l4t
Device model: Nintendo Switch (2017) tegra-x1
Cpu name: Cortex-A57
Ram size: 3.99 GB
Language: en_US.UTF-8
```

### (Recommended) Error log? Terminal output? Debug messages?

```bash
firejail /usr/bin/wps
Reading profile /etc/firejail/default.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Reading profile /etc/firejail/disable-programs.inc

** Note: you can use --noprofile to disable default.profile **

Parent pid 30407, child pid 30408
Error: proc 30407 cannot sync with peer: unexpected EOF
Peer 30408 unexpectedly killed (Bus error)
```
```

**Comment by Rak1ta** [comment]
On RPiOS Debian 11 Bullseye 64bit works.

```
pi@raspberrypi:~ $ firejail /usr/bin/wps
Reading profile /etc/firejail/default.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Reading profile /etc/firejail/disable-programs.inc
Warning: networking feature is disabled in Firejail configuration file

** Note: you can use --noprofile to disable default.profile **

Parent pid 18270, child pid 18271
Child process initialized in 209.57 ms

Parent is shutting down, bye...
```

**Comment by theofficialgman** [comment]
Can confirm it works on Ubuntu Focal as well.
Not really sure what this issue is. Maybe an old firejail bug that's been fixed in newer distros.

**Comment by theofficialgman** [comment]
solved with https://github.com/Botspot/pi-apps/commit/06545688a297bd79e1674eca8318d33cdd9193f6

**Comment by Botspot** [comment]
Fully solved with commit https://github.com/Botspot/pi-apps/commit/db8b2e05f31af09bb8fd0eb5d3b606a0551977ff.
