### ISSUE TITLE
Oh My Posh install script

### ISSUE THREAD

**Issue by libewa** [Botspot/pi-apps#2346]
### What is the name of the app?

Oh My Posh

### (Optional) Where is the app hosted?

https://github.com/jandedobbeleer/oh-my-posh
I download the official install script, which detects the architecture, from https://ohmyposh.dev.

### About the app

Oh My Posh adds customizable prompts to many shells, including bash, zsh, pwsh and fish.
Prompts are configured via json files and activated by adding a command to `~/.bashrc`

### Upload file or Add PR Link

~~[Oh My Posh.zip](https://github.com/Botspot/pi-apps/files/11627915/Oh.My.Posh.zip)~~
PR #2376

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by theofficialgman** [comment]
multiple issues with your install and uninstall scripts

I suggest you take a look at what the `https://ohmyposh.dev/install.sh` script actually does and integrate this into the install script in pi-apps itself. there is no reason to run their wrapper script which has no error checking. all it does is download the latest release binary and themes from the github releases and add them to the proper installation directory.

you should not leave orphaned files on the users install or execute extraneous commands either (eg: don't run purge_packages if you never ran install_packages)

also, please post a response with a picture of what your terminal looks like before and after installing this. I am having trouble understanding what it is for, what it does, and why you want it from the description and the website.

**Comment by libewa** [comment]
i also went on the omp discord for instructions on how to uninstall, and jan said to not use the install script on linux, but to use go install

**Comment by libewa** [comment]
[Oh My Posh.zip](https://github.com/Botspot/pi-apps/files/11635863/Oh.My.Posh.zip)
entirely new script using go install

**Comment by theofficialgman** [comment]
please refer to https://github.com/Botspot/pi-apps/issues/2346#issuecomment-1572636375
I do not want go install. pi-apps should manage the version of "oh my posh" by installing from github releases just like the https://ohmyposh.dev/install.sh does

also I still need the the last request there answered.

**Comment by libewa** [comment]
ah yeah

**Comment by libewa** [comment]
Screenshot: 
![image](https://github.com/Botspot/pi-apps/assets/67926131/c349708a-814c-4b01-abf6-2f9455c94731)
new zip:
[Oh My Posh.zip](https://github.com/Botspot/pi-apps/files/11642095/Oh.My.Posh.zip)
