### ISSUE TITLE
Stellarium

### ISSUE THREAD

**Issue by cdkw2** [Botspot/pi-apps#2347]
### What is the name of the app?

Stellarium

### (Optional) Where is the app hosted?

GIthub: https://github.com/Stellarium/stellarium

### About the app

Alright, so I have done my full research now, This app can indeed run on a raspberry pi and it is good for everyone. Like, watching the space is pretty cool. This app is opensource on GitHub and they even have a special page for Raspberry pi here: https://github.com/Stellarium/stellarium/wiki/Raspberry-Pi . 

So yeah, I hope I don't make any mistake yet again in submitting this app suggestion. I think it's perfect, so yeah please add it. No smiley this time because @theofficialgman doesn't like it.

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have read the app eligibilty rubric https://github.com/Botspot/pi-apps/issues/185 and confirmed this app is suitable for addition in Pi-Apps.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi-Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by theofficialgman** [comment]
I appreciate the research. However this is going to be a difficult app to add.
Stellarium is a QT toolkit based application and requires QT 5.14+ or QT 6. Neither of which are available in debian buster. Something like is done for PrismLauncher would need to be done -> https://github.com/Pi-Apps-Coders/files/blob/main/CompileCommands.md#prism-launcher

Also, if you read the raspberry pi install page you linked, you will see that compatibility is not very good any many pi versions/OS combos. This isn't really a fault of the software just a limitation of the rpi's poor desktop OpenGL drivers and hardware compatibility.

Regarding the app eligibility rubric, how is this sofware helpful for the everyday desktop GUI user? Its a neat software project but I don't really see it as helping anyone (we can all go outside and look at the sky) and given its difficult in porting I don't think it will be added by a pi-apps maintainer/developer.

**Comment by cdkw2** [comment]
I did open a issue on their repo but they told me that the app can be installed with ``` sudo apt install stellarium ``` but the version is outdated so my best bet would be building the app myself from source.

And yeah, probably the everyday Desktop user doesn't find this app useful but since I am a physics lover, I use this app a lot. I understand my opinion is biased so I won't argue with that. I understand the headache you guys would have to go through to get this app working so I wouldn't ask. Until then I would use the web app. Anyways, thanks for the reply.

**Comment by Rak1ta** [comment]
If anyone is interested, then Stellarium is also available on mobile devices. With a device that has an axellerometer, this is convenient.

https://stellarium-labs.com/stellarium-mobile-plus/

**Comment by cdkw2** [comment]
I know, I use the app too.
