### ISSUE TITLE
Download/Install script for Cascaydia Cove NF

### ISSUE THREAD

**Issue by libewa** [Botspot/pi-apps#2350]
### What is the name of the app?

Cascaydia Cove NF

### (Optional) Where is the app hosted?

https://www.nerdfonts.com/

### About the app

Cascaydia Cove is a version of Microsoft's Cascadia Code font with added symbols for apps like Oh My Posh and Oh My Fish.

### Upload file or Add PR Link

~~[Cascaydia Cove NF.zip](https://github.com/Botspot/pi-apps/files/11642018/Cascaydia.Cove.NF.zip)~~

PR #2375 

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by libewa** [comment]
[Cascaydia Cove NF.zip](https://github.com/Botspot/pi-apps/files/11642090/Cascaydia.Cove.NF.zip)
fixed a typo

**Comment by libewa** [comment]
i should stop making typos
[Cascaydia Cove NF.zip](https://github.com/Botspot/pi-apps/files/11642109/Cascaydia.Cove.NF.zip)

**Comment by theofficialgman** [comment]
there is an edit button under the `...` in the top right of each comment
no need to make a new comment with changes
