### ISSUE TITLE
Another minecraft launcher

### ISSUE THREAD

**Issue by Gracinplay1209** [Botspot/pi-apps#2351]
### What is the name of the app?

Official mc launcher 

### About the app

It is the official mc launcher that Microsoft made. I just want to try it out since I only on bedrock. the only bedrock launcher uses Google play to download it. I also don't have minecraft pe but bedrock on a Nintendo switch. It would be cool to see it on the raspberry pi.

I am a 13 year old raspberry pi 4 user with rpi os with the kde desktop on it. 

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have read the app eligibilty rubric https://github.com/Botspot/pi-apps/issues/185 and confirmed this app is suitable for addition in Pi-Apps.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi-Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by theofficialgman** [comment]
Official launcher is not compatible.
Sorry you aren't getting a more complete explanation than that.
Read the other issues please and don't lie in the checkboxes. 
https://github.com/Botspot/pi-apps/issues/2227
