### ISSUE TITLE
DKG FireFox Error Pi Apps Can't Install OBS

### ISSUE THREAD

**Issue by DashRock** [Botspot/pi-apps#2352]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)
- [X] IMPORTANT: I promise to respond to comments on this issue and write a good bug report https://www.softwaretestinghelp.com/how-to-write-good-bug-report/

### What happened?

Pi Apps can't install OBS

### Description

I believe it has something to do with Firefox, i have had the same issue before, i have uninstalled, deleted and installed Firefox multiple times, it comes up a dpkg error.

### What are your system specs (run the following command in your terminal)?

```bash
OS: Raspbian GNU/Linux 11 (bullseye)
OS architecture: 32-bit
Last updated Pi-Apps on: 06/04/2023
Latest Pi-Apps version: 06/04/2023
Kernel: aarch64 6.1.21-v8+
Device model: Raspberry Pi 4 Model B Rev 1.4 
Cpu name: Cortex-A72
Ram size: 7.81 GB
Raspberry Pi OS image version: 2023-02-21
Language: en_US.UTF-8
```

### (Recommended) Error log? Terminal output? Debug messages?

```bash
dpkg: error processing package firefox (--configure):
 installed firefox package post-installation script subprocess returned error exit status 2
Errors were encountered while processing:
 firefox
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by theofficialgman** [comment]
The CI passed with no issues.
What is the output when you run
```bash
sudo dpkg --configure -a
```

**Comment by Botspot** [comment]
Also, what is the output when you run this command in a terminal?
```
sudo apt purge firefox
```

**Comment by theofficialgman** [comment]
@DashRock this issue will be closed soon due to no response

**Comment by theofficialgman** [comment]
Closing due to no response.
