### ISSUE TITLE
Lego digital designer not starter after Box86 update

### ISSUE THREAD

**Issue by Rak1ta** [Botspot/pi-apps#2357]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)
- [X] IMPORTANT: I promise to respond to comments on this issue and write a good bug report https://www.softwaretestinghelp.com/how-to-write-good-bug-report/

### What happened?

Lego digital designer not starter after Box86 update

### Description

After updating the Box86, in my case, the version indicated below, LDD does not work and games hang with the desktop.
`Box86 with Dynarec v0.3.1 5cdc1b9f built on Jun  8 2023 07:13:26`

The problem is similar to the one indicated by the link, this was previously resolved. Wine 5.13 x86 is used.
https://github.com/Botspot/pi-apps/issues/1391

Checked on a clean OS installation.
I would like to confirm anything with Wine 8.10 but I have something broken (please wait, I have to double check).

![image](https://github.com/Botspot/pi-apps/assets/88277343/1364faa9-5ba5-4108-97cb-e384c8df8238)

### What are your system specs (run the following command in your terminal)?

```bash
OS: Raspbian GNU/Linux 10 (buster)
OS architecture: 32-bit
Last updated Pi-Apps on: 06/11/2023
Latest Pi-Apps version: 06/12/2023
Kernel: armv7l 5.10.103-v7l+
Device model: Raspberry Pi 4 Model B Rev 1.2 
Cpu name: Cortex-A72
Ram size: 3.66 GB
Raspberry Pi OS image version: 2021-05-07
Language: en_US.UTF-8
```

**Comment by Rak1ta** [comment]
With Wine 8.10, the program doesn't even open.
```
pi@raspberrypi:~/.wine/drive_c/Program Files/LEGO Company/LEGO Digital Designer $ BOX86_LOG=1 box86 wine LDD.exe
Debug level is 1
Dynarec for ARMv8, with extension: HALF FAST_MULT EDSP NEON VFPv4 IDIVA PageSize:4096 Running on Cortex-A72 with 4 Cores
Params database has 22 entries
Box86 with Dynarec v0.3.1 5cdc1b9f built on Jun  8 2023 07:13:26
BOX86: Wine detected, WINEPRELOADRESERVE=""
Using default BOX86_LD_LIBRARY_PATH: ./:lib/:lib32/:x86/:i686/
Using default BOX86_PATH: ./:bin/
Counted 46 Env var
Looking for wine
argv[1]="LDD.exe"
Not an ELF file (sign=#!/b)
Error: reading elf header of /usr/local/bin/wine, try to launch natively instead
Debug level is 1
Dynarec for ARMv8, with extension: HALF FAST_MULT EDSP NEON VFPv4 IDIVA PageSize:4096 Running on Cortex-A72 with 4 Cores
Params database has 22 entries
Box86 with Dynarec v0.3.1 5cdc1b9f built on Jun  8 2023 07:13:26
BOX86: Wine detected, WINEPRELOADRESERVE=""
Using default BOX86_LD_LIBRARY_PATH: ./:lib/:lib32/:x86/:i686/
Using default BOX86_PATH: ./:bin/
Counted 46 Env var
Looking for /opt/wine-8.10/bin/wine
argv[1]="LDD.exe"
Rename process to "wine"
Using native(wrapped) libdl.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux.so.2
Using native(wrapped) librt.so.1
Using emulated /opt/wine-8.10/bin/../lib/wine/i386-unix/ntdll.so
Debug level is 1
Dynarec for ARMv8, with extension: HALF FAST_MULT EDSP NEON VFPv4 IDIVA PageSize:4096 Running on Cortex-A72 with 4 Cores
Params database has 22 entries
Box86 with Dynarec v0.3.1 5cdc1b9f built on Jun  8 2023 07:13:26
BOX86: Wine detected, WINEPRELOADRESERVE=""
Using default BOX86_LD_LIBRARY_PATH: ./:lib/:lib32/:x86/:i686/
Using default BOX86_PATH: ./:bin/
Counted 48 Env var
Looking for /opt/wine-8.10/bin/wine
argv[1]="LDD.exe"
Rename process to "wine"
Using native(wrapped) libdl.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux.so.2
Using native(wrapped) librt.so.1
Using emulated /opt/wine-8.10/bin/../lib/wine/i386-unix/ntdll.so
Debug level is 1
Dynarec for ARMv8, with extension: HALF FAST_MULT EDSP NEON VFPv4 IDIVA PageSize:4096 Running on Cortex-A72 with 4 Cores
Params database has 22 entries
Box86 with Dynarec v0.3.1 5cdc1b9f built on Jun  8 2023 07:13:26
Using default BOX86_LD_LIBRARY_PATH: ./:lib/:lib32/:x86/:i686/
Using default BOX86_PATH: ./:bin/
Counted 48 Env var
Looking for /opt/wine-8.10/bin/wineserver
Rename process to "wineserver"
Using native(wrapped) libdl.so.2
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) librt.so.1
00a0:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
00a0:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
00a0:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
00a0:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
00a0:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
00a0:fixme:xinput:pdo_pnp IRP_MN_QUERY_ID type 5, not implemented!
00a0:fixme:xinput:pdo_pnp IRP_MN_QUERY_ID type 5, not implemented!
00a0:fixme:xinput:pdo_pnp IRP_MN_QUERY_ID type 5, not implemented!
00a0:fixme:xinput:pdo_pnp IRP_MN_QUERY_ID type 5, not implemented!
00e0:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
0050:err:ole:start_rpcss Failed to start RpcSs service
Debug level is 1
Dynarec for ARMv8, with extension: HALF FAST_MULT EDSP NEON VFPv4 IDIVA PageSize:4096 Running on Cortex-A72 with 4 Cores
Params database has 22 entries
Box86 with Dynarec v0.3.1 5cdc1b9f built on Jun  8 2023 07:13:26
BOX86: Wine detected, WINEPRELOADRESERVE="000400000-00047f000"
Using default BOX86_LD_LIBRARY_PATH: ./:lib/:lib32/:x86/:i686/
Using default BOX86_PATH: ./:bin/
Counted 50 Env var
Looking for /opt/wine-8.10/bin/wine
argv[1]="C:\windows\system32\conhost.exe"
argv[2]="--unix"
argv[3]="--width"
argv[4]="80"
argv[5]="--height"
argv[6]="45"
argv[7]="--server"
argv[8]="0x10"
Rename process to "wine"
Using native(wrapped) libdl.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux.so.2
Using native(wrapped) librt.so.1
Using emulated /opt/wine-8.10/bin/../lib/wine/i386-unix/ntdll.so
Using emulated /opt/wine-8.10/lib/wine/i386-unix/win32u.so
Using native(wrapped) libm.so.6
Using native(wrapped) libfreetype.so.6
Using native(wrapped) libfontconfig.so.1
Using emulated /opt/wine-8.10/lib/wine/i386-unix/win32u.so
Using native(wrapped) libm.so.6
Using native(wrapped) libfreetype.so.6
Using native(wrapped) libfontconfig.so.1
Using emulated /opt/wine-8.10/lib/wine/i386-unix/opengl32.so
Using emulated /opt/wine-8.10/lib/wine/i386-unix/winex11.so
Using native(wrapped) libXext.so.6
Using native(wrapped) libX11.so.6
Using native(wrapped) libxcb.so.1
Using native(wrapped) libXau.so.6
Using native(wrapped) libXdmcp.so.6
Using native(wrapped) libXinerama.so.1
Using native(wrapped) libXxf86vm.so.1
Using native(wrapped) libXrender.so.1
Using native(wrapped) libXrandr.so.2
Using native(wrapped) libXcomposite.so.1
Using native(wrapped) libXi.so.6
Using native(wrapped) libXcursor.so.1
Using emulated /opt/wine-8.10/lib/wine/i386-unix/winspool.so
Using native(wrapped) libcups.so.2
Using emulated /opt/wine-8.10/lib/wine/i386-unix/ws2_32.so
Using emulated /opt/wine-8.10/lib/wine/i386-unix/dnsapi.so
Using native(wrapped) libresolv.so.2
Using emulated /opt/wine-8.10/lib/wine/i386-unix/netapi32.so
Using native(wrapped) libGL.so.1
Using emulated /opt/wine-8.10/lib/wine/i386-unix/avicap32.so
Using emulated /opt/wine-8.10/lib/wine/i386-unix/winepulse.so
Using native(wrapped) libpulse.so.0
Using emulated /opt/wine-8.10/lib/wine/i386-unix/winealsa.so
Using native(wrapped) libasound.so.2
0024:err:winediag:MIDIMAP_drvOpen No software synthesizer midi port found, Midi sound output probably won't work.
Using emulated /opt/wine-8.10/lib/wine/i386-unix/winegstreamer.so
Using native(wrapped) libgstvideo-1.0.so.0
Using native(wrapped) libgstaudio-1.0.so.0
Using native(wrapped) libgsttag-1.0.so.0
Using native(wrapped) libgstreamer-1.0.so.0
Using native(wrapped) libgtk-3.so.0
Using native(wrapped) libgdk-3.so.0
Using native(wrapped) libgobject-2.0.so.0
Using native(wrapped) libglib-2.0.so.0
Using native(wrapped) libgio-2.0.so.0
Using native(wrapped) libgmodule-2.0.so.0
Using native(wrapped) libgdk_pixbuf-2.0.so.0
Using native(wrapped) libpangocairo-1.0.so.0
Using native(wrapped) libpango-1.0.so.0
00ec:fixme:service:QueryServiceConfig2W Level 6 not implemented
00ec:fixme:service:QueryServiceConfig2W Level 6 not implemented
Warning, GObject2 signal callback but no data found!Warning, GObject2 signal callback but no data found!Warning, GObject2 signal callback but no data found!Warning, GObject2 signal callback but no data found!Warning, GObject2 signal callback but no data found!Warning, GObject2 signal callback but no data found!FillBlock at (nil) triggered a segfault, cancelling
FillBlock at (nil) triggered a segfault, cancelling
1608|Ask to run at NULL, will segfault

```

**Comment by Rak1ta** [comment]
Если использовать Wine8.10:
`Box86 with Dynarec v0.2.9 5bb47315 built on Mar  5 2023 01:21:10`
[wine8.10_buster-32.txt](https://github.com/Botspot/pi-apps/files/11743611/wine8.10_buster-32.txt)
`Box86 with Dynarec v0.3.1 5cdc1b9f built on Jun  8 2023 07:13:26`
[wine8.10_buster-32-2.txt](https://github.com/Botspot/pi-apps/files/11743636/wine8.10_buster-32-2.txt)

**Comment by Rak1ta** [comment]
Multiple games that don't run (show the splash screen, but when games start, the screen freezes).

> `Box86 with Dynarec v0.3.1 5cdc1b9f built on Jun  8 2023 07:13:26`
> On Wine 5.13 installed 2023.14.06

[log-cs1.6.txt](https://github.com/Botspot/pi-apps/files/11745637/log-cs1.6.txt)
[log-psychonauts.txt](https://github.com/Botspot/pi-apps/files/11745638/log-psychonauts.txt)
[log-unreal-gold.txt](https://github.com/Botspot/pi-apps/files/11745639/log-unreal-gold.txt)

**Comment by Rak1ta** [comment]
Please help identify the issue with Wine and Box86. LDD I chose because it displays an error.

@theofficialgman  Wine installation question:
https://github.com/Botspot/pi-apps/commit/f7868d33703990a9d7db847b07090d737792c6ec - if the system is clean, then mesa-utils will not be installed? If mesa-utils are needed (i understand the script will not install it), you have the same thing in Wine 8.10 script.

@Botspot
https://github.com/Winetricks/winetricks/commit/be6d44613eed10e8f6757b8df9fc5af80103f5c1 -  I assume this commits (file) the last compatible with my installation. Why are you using this https://github.com/Botspot/pi-apps/commit/fc3181699bdbf2c0f228d259d47a945412615d93 option?

@ptitSeb i described the versions in which I found a problem.

Checked on Wine 5.13:
> `Box86 with Dynarec v0.3.1 5cdc1b9f built on Jun  8 2023 07:13:26` - OpenGL error
> `Box86 with Dynarec v0.3.1 1411d44b built on Apr 30 2023 07:06:50` - error starting the program window
> `Box86 with Dynarec v0.3.1 af67f69e built on Apr 24 2023 07:09:38` - OpenGL error
[buster-32_wine-5.13-error.txt](https://github.com/Botspot/pi-apps/files/11756972/buster-32_wine-5.13-error.txt)
> `Box86 with Dynarec v0.3.1 eb44fd62 built on Apr 20 2023 07:03:53` - long wait for the launch of the program
> `Box86 with Dynarec v0.3.1 1a0888ca built on Mar 23 2023 07:50:41` - works
[buster-32_wine-5.13.txt](https://github.com/Botspot/pi-apps/files/11756952/buster-32_wine-5.13.txt)

Checked on Wine 8.10:
> `Box86 with Dynarec v0.3.1 5cdc1b9f built on Jun  8 2023 07:13:26` - error starting the program window
[buster-32_wine-8.10-error2.txt](https://github.com/Botspot/pi-apps/files/11760528/buster-32_wine-8.10-error2.txt)
> `Box86 with Dynarec v0.3.1 af67f69e built on Apr 24 2023 07:09:38` - error starting the program window
[buster-32_wine-8.10-error1.txt](https://github.com/Botspot/pi-apps/files/11760515/buster-32_wine-8.10-error1.txt)
> `Box86 with Dynarec v0.3.1 eb44fd62 built on Apr 20 2023 07:03:53` - works, but there are many errors in the console
[buster-32_wine-8.10.txt](https://github.com/Botspot/pi-apps/files/11760514/buster-32_wine-8.10.txt)
[buster-32_wine-8.10-2.txt](https://github.com/Botspot/pi-apps/files/11760586/buster-32_wine-8.10-2.txt)
`Box86 with Dynarec v0.3.1 705414a3 built on Apr 16 2023 07:01:29` - error starting the program window
[buster-32_wine-8.10-error3.txt](https://github.com/Botspot/pi-apps/files/11760549/buster-32_wine-8.10-error3.txt)
`Box86 with Dynarec v0.3.1 1a0888ca built on Mar 23 2023 07:50:41` - start and error
[buster-32_wine-8.10-error4.txt](https://github.com/Botspot/pi-apps/files/11760576/buster-32_wine-8.10-error4.txt)







Sorry to i call everyone. I do not understand this.

**Comment by theofficialgman** [comment]
mesa is still not the default driver I belive on piOS. check `raspi-config` and try using full kms

**Comment by theofficialgman** [comment]
buster has been dropped. since this was the only platform where the issue was present by default, this will be closed
