### ISSUE TITLE
add DE detection

### ISSUE THREAD

**Issue by Itai-Nelken** [Botspot/pi-apps#236]
mainly for your win10 theme, it only works on lxde (right?).
here is a way to detect it:
```sh
#!/bin/bash

DE="`env | grep DESKTOP_SESSION`"

if [[ $DE == *"xfce"* ]]; then
	echo "xfce"
elif [[ $DE == *"lxde"* ]]; then
	echo "lxde"
elif [[ $DE == *"gnome"* ]]; then
        echo "gnome"
fi
```

source: https://askubuntu.com/questions/125062/how-can-i-find-which-desktop-enviroment-i-am-using#

**Comment by Botspot** [comment]
Yeah but, I'd have to make a whole new theme for xfce4!

Not that much from my existing theme could transfer over I'm afraid. In addition, if I made a xfce4-compatible theme, I'd have to account for varying window managers, wallpaper daemons, and pre-existing custom panel designs.

Making it compatible with all xfce4 systems sounds like a total pain to maintain.

**Comment by Itai-Nelken** [comment]
@Botspot I didn't mean to add this feature so it works on XFCE, the idea is that if you are running XFCE, the theme will be added to the hidelist.
sorry if I wasn't clear enough.

**Comment by Botspot** [comment]
> @Botspot I didn't mean to add this feature so it works on XFCE, the idea is that if you are running XFCE, the theme will be added to the hidelist.
> sorry if I wasn't clear enough.

Oh...  

No I did not understand it like *that*, but thanks for clarifying.

Yes, absolutely this tip will come in handy for hiding Win10 theme on xfce4. Thank you, @Itai-Nelken!
