### ISSUE TITLE
fish-shell [apt repo]

### ISSUE THREAD

**Issue by kkarhan** [Botspot/pi-apps#2362]
### What is the name of the app?

fish-shell

### (Optional) Where is the app hosted?

The App is distributed via OpenSuse  Build Service:
See https://software.opensuse.org/download.html?project=shells%3Afish%3Arelease%3A3&package=fish#manualDebian for details.

### About the app

The [Friendly Interactive Shell](https://fishshell.com/) is intended to be a user-friendly shell.

### Upload file or Add PR Link

https://github.com/Botspot/pi-apps/pull/2361

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by kkarhan** [comment]
Thanks for the [bot autoreply](https://github.com/Botspot/pi-apps/issues/2362#issuecomment-1595599999) but I can't use Discord due to it's unacceptable ToS.

**Comment by cdkw2** [comment]
> Thanks for the [bot autoreply](https://github.com/Botspot/pi-apps/issues/2362#issuecomment-1595599999) but I can't use Discord due to it's unacceptable ToS.

What is unacceptable in TOS?

**Comment by Botspot** [comment]
> What is unacceptable in TOS?

It could be a lot of things. I am not too fond of it either.

**Comment by Botspot** [comment]
Closing this issue to continue discussion in PR #2361.

**Comment by theofficialgman** [comment]
> > Thanks for the [bot autoreply](https://github.com/Botspot/pi-apps/issues/2362#issuecomment-1595599999) but I can't use Discord due to it's unacceptable ToS.
> 
> What is unacceptable in TOS?

Also interesting in knowning this @kkarhan . Getting to know our community is important and our Discord server is an important part of that. Please elaborate on what is "unacceptable" in the TOS. You can find the current TOS here https://discord.com/terms . Please respond with any/all copied clauses from the TOS that are unacceptable in your opinion.
