### ISSUE TITLE
There are no flatpak application icons

### ISSUE THREAD

**Issue by Rak1ta** [Botspot/pi-apps#2364]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)
- [X] IMPORTANT: I promise to respond to comments on this issue and write a good bug report https://www.softwaretestinghelp.com/how-to-write-good-bug-report/

### What happened?

No shortcuts

### Description

Dot Matrix, Telegram, LibrePCB (other programs are possible) - not found in the application menu.
[install-success-Dot Matrix.log](https://github.com/Botspot/pi-apps/files/11778655/install-success-Dot.Matrix.log)

![image](https://github.com/Botspot/pi-apps/assets/88277343/e5734b9d-2a64-4ec3-98bd-aea5316a5e10)

### What are your system specs (run the following command in your terminal)?

```bash
OS: Debian GNU/Linux 11 (bullseye)
OS architecture: 64-bit
Last updated Pi-Apps on: 06/11/2023
Latest Pi-Apps version: 06/17/2023
Kernel: aarch64 6.1.21-v8+
Device model: Raspberry Pi 4 Model B Rev 1.2 
Cpu name: Cortex-A72
Ram size: 3.61 GB
Raspberry Pi OS image version: 2023-02-21
Language: en_US.UTF-8
```

### (Recommended) Error log? Terminal output? Debug messages?

```bash
pi@raspberrypi:~ $ echo $XDG_DATA_DIRS
/usr/share/fkms:/usr/local/share:/usr/share/raspi-ui-overrides:/usr/share:/usr/share/gdm:/var/lib/menu-xdg:/home/pi/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share:/var/lib/snapd/desktop
```

**Comment by theofficialgman** [comment]
They should be there. As you just showed, XDG_DATA_DIRS has the filepath that contains the flatpak .desktop files. Have you tried rebooting once? Some DEs are bad and won't pick up on new applications until doing so.

**Comment by Rak1ta** [comment]
@theofficialgman reinstalled, rebooted. I have already checked this.

**Comment by theofficialgman** [comment]
Report this to piOS 64bit as a bug them. It is out of our control if they broke the DE to not respect XDG_DATA_DIRS. It used to work correctly. I will check myself

**Comment by theofficialgman** [comment]
Unable to reproduce. I am using a fresh piOS 64bit bullseye image
```
OS: Debian GNU/Linux 11 (bullseye)
OS architecture: 64-bit
Last updated Pi-Apps on: 06/14/2023
Latest Pi-Apps version: 06/16/2023
Kernel: aarch64 6.1.21-v8+
Device model: Raspberry Pi 3 Model B Rev 1.2 
Cpu name: Cortex-A53
Ram size: .90 GB
Raspberry Pi OS image version: 2023-05-03
Language: en_US.UTF-8
```

**Comment by Rak1ta** [comment]
I reinstalled pi-apps (I wanted to restart the api script). And the shortcuts were restored after reinstalling the programs.
