### ISSUE TITLE
Need help removing foreign apt repos

### ISSUE THREAD

**Issue by kbaraniak** [Botspot/pi-apps#2365]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)
- [X] IMPORTANT: I promise to respond to comments on this issue and write a good bug report https://www.softwaretestinghelp.com/how-to-write-good-bug-report/

### What happened?

InteliJ no works update after update Pi Apps

### Description

No work Update/install InteliJ after update Pi Apps, how to fix ?
I updated Raspbian to latest version Using (`sudo apt update && sudo apt dist-upgrade -y`)

### What are your system specs (run the following command in your terminal)?

```bash
OS: Debian GNU/Linux 11 (bullseye)
OS architecture: 64-bit
Last updated Pi-Apps on: 06/18/2023
Latest Pi-Apps version: 06/18/2023
Kernel: aarch64 6.1.21-v8+
Device model: Raspberry Pi 4 Model B Rev 1.5 
Cpu name: Cortex-A72
Ram size: 7.57 GB
Raspberry Pi OS image version: 2022-04-04
Language: en_US.UTF-8
```

### (Recommended) Error log? Terminal output? Debug messages?

```bash
Err:13 http://cz.archive.ubuntu.com/ubuntu bionic/main arm64 Packages
  404  Not Found [IP: 217.31.202.63 80]
Ign:14 http://cz.archive.ubuntu.com/ubuntu bionic/main armhf Packages
Ign:23 http://cz.archive.ubuntu.com/ubuntu bionic/universe arm64 Packages
Ign:24 http://cz.archive.ubuntu.com/ubuntu bionic/universe armhf Packages
Fetched 72.7 kB in 4s (16.4 kB/s)
E: Failed to fetch http://cz.archive.ubuntu.com/ubuntu/dists/bionic/main/binary-arm64/Packages  404  Not Found [IP: 217.31.202.63 80]
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by theofficialgman** [comment]
For one, you are not using raspbian. Raspbian is a armhf only distro. You are using Raspberry PiOS Bullseye ARM64.

Secondly, you have added incorrect Ubuntu Bionic repositories to your installation. Specifically a mirror of the archive.ubuntu.com repository which only contains i386 and amd64 architecture, neither of which are architecture supported by your raspberry pi.

You should check your `/etc/apt/sources.list.d/` folder and remove the `.list` file that contains the ubuntu repo in it.

What were you doing which prompted you to add this repository in the first place?

**Comment by kbaraniak** [comment]
From what I remember it was added automatically, I think from the Box86 installation before Pi-Apps

**Comment by theofficialgman** [comment]
> From what I remember it was added automatically, I think from the Box86 installation before Pi-Apps

not possible. pi-apps does not add any ubuntu repositories to users installs. that would be bad. you added this yourself (likely following some bad guide on the internet that told you to do so).

remove the repo following this https://github.com/Botspot/pi-apps/issues/2365#issuecomment-1599650757

**Comment by kbaraniak** [comment]
Thanks, I'm fixed my problem removing useless repos
