### ISSUE TITLE
PokeWilds

### ISSUE THREAD

**Issue by cdkw2** [Botspot/pi-apps#2369]
### What is the name of the app?

PokeWilds

### (Optional) Where is the app hosted?

https://github.com/SheerSt/pokewilds

### About the app

Simple game written in java. I want to confirm if it can be run with the Linux download or if we can use a wine layer to use the windows version. It won't let me issue this suggestion if I don't check that last button. I will remove it as soon as this is released, I just want to discuss if it is available. It's a good game for all. Sorry for bothering @theofficialgman in advance.

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have read the app eligibilty rubric https://github.com/Botspot/pi-apps/issues/185 and confirmed this app is suitable for addition in Pi-Apps.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi-Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by cdkw2** [comment]
Update: I got it to work!

https://github.com/SheerSt/pokewilds/issues/429

Now can you all add it?

**Comment by cdkw2** [comment]
@theofficialgman  Is this app still on the list of agendas or is the app discarded?

**Comment by theofficialgman** [comment]
I am not interested in implementing an installer for this at the moment. Given that they are using copyrighted assets ripped from the gamefreak games without requiring users to provide their own game dumps to extract the assets from at runtime, this is a violation of copyright. I don't want to support or promote that practice.

**Comment by cdkw2** [comment]
hmmmm I completely understand
