### ISSUE TITLE
add mcpil

### ISSUE THREAD

**Issue by pi-dev500** [Botspot/pi-apps#237]
a launcher for minecraft pi!

site of app: github.com/MCPI-devs/MCPIL

zipfile: 
[mcpil.zip](https://github.com/Botspot/pi-apps/files/5807678/mcpil.zip)

**Comment by Botspot** [comment]
Already working on it. https://github.com/Botspot/pi-apps/issues/144

**Comment by Botspot** [comment]
But, @pi-dev500, I like your install script!

Unlike the one from #144, it actually works. I'll credit you for contributing to the app.
