### ISSUE TITLE
Install script for official Discord Stable and PTB clients using box64

### ISSUE THREAD

**Issue by libewa** [Botspot/pi-apps#2374]
### What is the name of the app?

Discord Stable and Discord PTB

### (Optional) Where is the app hosted?

https://discord.com/download

### About the app

Discord is a chatting app similar to Slack and Guilded. We only have the third-party "Webcord" client, but some applications (like changing Rich Presence) need the official client. I noticed that the Steam client is also run using box64, and made this installer.

### Upload file or Add PR Link

#2373 

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by theofficialgman** [comment]
See PR
