### ISSUE TITLE
Somehow installed 64bit ONLY apps on 32bit OS

### ISSUE THREAD

**Issue by Joe-Lay** [Botspot/pi-apps#2379]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)
- [X] IMPORTANT: I promise to respond to comments on this issue and write a good bug report https://www.softwaretestinghelp.com/how-to-write-good-bug-report/

### What happened?

Wine attempts to run, but fails because ".wine" is a 32-bit installation

### Description

Priority: P5. I do not need the program.
When I run any program with wine, it fails and I receive this message at the end of the command line, "wine: '/home/pi/.wine' is a 32-bit installation, it cannot support 64-bit applications." I have done nothing to try to fix this because I know almost nothing about wine itself, and have no idea how to fix this.

How to Reproduce:
Simply launch any wine program, even winecfg or winemine, and you should receive a similar error if you do it from the command line. Try typing a command like "wine winecfg" and it should happen.
Thank you.

### What are your system specs (run the following command in your terminal)?

```bash
OS: Raspberry OS GNU/Linux 11 (Bullseye)
OS architechture: 64-bit
Last updated Pi-apps on: 6/2/2023
Kernel: 6.1.21-v8+
Device Model: Raspberry Pi 4 Model B Rev 1.1
Ram size: 3.7 GB
```

### (Recommended) Error log? Terminal output? Debug messages?

```bash
Dynarec for ARM64, with extension: ASIMD CRC32 PageSize:4096 Running on Cortex-A72 with 4 Cores
Params database has 24 entries
Box64 with Dynarec v0.2.3 3b977247 built on Jun 28 2023 07:45:48
BOX64: Wine64 detected, WINEPRELOADRESERVE=""
Using default BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/
Using default BOX64_PATH: ./:bin/
Counted 43 Env var
Looking for /usr/local/bin/wine
argv[1]="winecfg"
Rename process to "wine"
Using native(wrapped) libdl.so.2
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) libutil.so.1
Using native(wrapped) librt.so.1
Using emulated /opt/wine-8.11/bin/../lib/wine/x86_64-unix/ntdll.so
Using native(wrapped) libunwind.so.8
Dynarec for ARM64, with extension: ASIMD CRC32 PageSize:4096 Running on Cortex-A72 with 4 Cores
Params database has 24 entries
Box64 with Dynarec v0.2.3 3b977247 built on Jun 28 2023 07:45:48
BOX64: Wine preloader detected, loading "/opt/wine-8.11/bin/wine" directly
BOX64: Wine64 detected, WINEPRELOADRESERVE=""
Using default BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/
Using default BOX64_PATH: ./:bin/
Counted 45 Env var
Looking for /opt/wine-8.11/bin/wine
argv[1]="winecfg"
Rename process to "wine"
Using native(wrapped) libdl.so.2
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) libutil.so.1
Using native(wrapped) librt.so.1
Using emulated /opt/wine-8.11/bin/../lib/wine/x86_64-unix/ntdll.so
Using native(wrapped) libunwind.so.8
Dynarec for ARM64, with extension: ASIMD CRC32 PageSize:4096 Running on Cortex-A72 with 4 Cores
Params database has 24 entries
Box64 with Dynarec v0.2.3 3b977247 built on Jun 28 2023 07:45:48
Using default BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/
Using default BOX64_PATH: ./:bin/
Counted 45 Env var
Looking for /opt/wine-8.11/bin/wineserver
Rename process to "wineserver"
Using native(wrapped) libdl.so.2
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) libutil.so.1
Using native(wrapped) librt.so.1
wine: '/home/pi/.wine' is a 32-bit installation, it cannot support 64-bit applications.
```

**Comment by theofficialgman** [comment]
How were you able to install `Wine (x64)` and `Box64`? your OS is 32bit

> OS: Raspberry OS GNU/Linux 11 (Bullseye)
> OS architechture: 32-bit
> Last updated Pi-apps on: 6/2/2023
> Kernel: 6.1.21-v8+
> Device Model: Raspberry Pi 4 Model B Rev 1.1
> Ram size: 3.7 GB

**Comment by Joe-Lay** [comment]
Sorry, my mistake. I installed it on a 64-bit raspberry OS. I must have accidentally entered 32-bit when I should have said 64-bit
[logs.zip](https://github.com/Botspot/pi-apps/files/11938396/logs.zip) (my ~/pi-apps/logs directory)

**Comment by theofficialgman** [comment]
> Sorry, my mistake. I installed it on a 64-bit raspberry OS. I must have accidentally entered 32-bit when I should have said 64-bit [logs.zip](https://github.com/Botspot/pi-apps/files/11938396/logs.zip) (my ~/pi-apps/logs directory)

no, you don't enter that information. you run
`~/pi-apps/api get_device_info` in a terminal and then post the output. please run that command again and post the output again so I know what hardware/OS you are ACTUALLY using.

**Comment by theofficialgman** [comment]
I still consider this a user error but we can work around it.
for one, your internet is terrible. most of your logs have to do with failures in downloading.

but the actual issue is you had wine installed before via some other method that generated an inconpatible wine prefix in your ~/.wine folder. it needs to be fully cleared if detected. I can update the script to do that if the incompatible prefix is detected.

**Comment by theofficialgman** [comment]
closed with https://github.com/Botspot/pi-apps/commit/0f5b8cc8e92cb56e2c8585e8eeb8e06f912dd95e
