### ISSUE TITLE
Noto Color Emoji installed in $HOME/.fonts instead of /usr/local/share/fonts

### ISSUE THREAD

**Issue by libewa** [Botspot/pi-apps#2382]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)
- [X] IMPORTANT: I promise to respond to comments on this issue and write a good bug report https://www.softwaretestinghelp.com/how-to-write-good-bug-report/

### What happened?

Noto Color Emoji is being installed in $HOME/.fonts instead of /usr/local/share/fonts

### Description

This goes against https://github.com/Botspot/pi-apps/pull/2375#discussion_r1250145123

### What are your system specs (run the following command in your terminal)?

```bash
OS: Debian GNU/Linux 11 (bullseye)
OS architecture: 64-bit
Last updated Pi-Apps on: 07/04/2023
Latest Pi-Apps version: 07/04/2023
Kernel: aarch64 6.1.21-v8+
Device model: Raspberry Pi 4 Model B Rev 1.1 
Cpu name: Cortex-A72
Ram size: 3.79 GB
Raspberry Pi OS image version: 2023-05-03
Language: en_US.UTF-8
```

**Comment by Botspot** [comment]
I wrote this script a long time ago when I knew less about the benefits of system-wide installation.
Thank you for pointing it out; I will fix it.
