### ISSUE TITLE
Genshin Impact (Wine) 

### ISSUE THREAD

**Issue by everypizza1** [Botspot/pi-apps#2390]
### What is the name of the app?

Genshin Impact

### (Optional) Where is the app hosted?

https://genshin.hoyoverse.com/m/en

### About the app

Genshin Impact is a video game. (i am addicted to it)
We will need a warning saying that it is 119 GB. 

I have not tested it. 

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have read the app eligibilty rubric https://github.com/Botspot/pi-apps/issues/185 and confirmed this app is suitable for addition in Pi-Apps.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi-Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by cdkw2** [comment]
This will never get added

**Comment by everypizza1** [comment]
> This will never get added

What is your reasoning for that?

**Comment by everypizza1** [comment]
Update: We should not add this.
![Screenshot_20230715-114839](https://github.com/Botspot/pi-apps/assets/82726593/23670df9-e59e-42ee-b189-5a0f9a360b34)

**Comment by everypizza1** [comment]
Another update: DOOM is on Pi-apps, and is much more violent. Reopening.
![Screenshot_20230715-200210](https://github.com/Botspot/pi-apps/assets/82726593/ab3fc34b-d5b7-4ed2-8471-61ae43488b0c)

**Comment by cdkw2** [comment]
Bro I believe that any raspberry pi is not capable of running such a bulky game.

**Comment by cdkw2** [comment]
Also, explain this:

![image](https://github.com/Botspot/pi-apps/assets/67598073/47ac449f-8a00-4f3d-96ab-4058cba57108)

**Comment by everypizza1** [comment]
I saw a HoYoLAB post about it, confirming it is possible.

**Comment by everypizza1** [comment]
I think it was an overclocked pi 4  8gb. Closing again.
