### ISSUE TITLE
ArmCord - Version Mismatch

### ISSUE THREAD

**Issue by TheAlienDrew** [Botspot/pi-apps#2395]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)
- [X] IMPORTANT: I promise to respond to comments on this issue and write a good bug report https://www.softwaretestinghelp.com/how-to-write-good-bug-report/

### What happened?

After updating ArmCord to the latest version, for some strange reason that shows an older version even though it's updated.

### Description

If you install the latest version of ArmCord on a Raspberry Pi, launch it and sign in, then right click on the status icon... It shows version 3.1.3 instead of the newest version 3.2.1.

I originally reported this to ArmCord, thinking it was an issue with the app itself, but they say it's not them. https://github.com/ArmCord/ArmCord/issues/425

I did have an older version installed prior before installing the newer version so I'm not sure if that affects anything.

However, I also uninstalled and reinstalled ArmCord, but it still exhibited the same issue.

### What are your system specs (run the following command in your terminal)?

```bash
OS: Debian GNU/Linux 11 (bullseye)
OS architecture: 64-bit
Last updated Pi-Apps on: 07/18/2023
Latest Pi-Apps version: 07/19/2023
Kernel: aarch64 6.1.21-v8+
Device model: Raspberry Pi 4 Model B Rev 1.1 
Cpu name: Cortex-A72
Ram size: 3.79 GB
Raspberry Pi OS image version: 2022-09-22
Language: en_US.UTF-8
```

**Comment by theofficialgman** [comment]
I don't think it is use. our scripts are up to date
https://github.com/Botspot/pi-apps/blob/master/apps/ArmCord/install-32
https://github.com/Botspot/pi-apps/blob/master/apps/ArmCord/install-64

send all install/uninstall logs in `~/pi-apps/logs/` folder for armcord here

**Comment by TheAlienDrew** [comment]
> I don't think it is pi-apps. our scripts are up to date
> https://github.com/Botspot/pi-apps/blob/master/apps/ArmCord/install-32
> https://github.com/Botspot/pi-apps/blob/master/apps/ArmCord/install-64
> 
> send all install/uninstall logs in `~/pi-apps/logs/` folder for armcord here
> 

![logs.zip](https://github.com/Botspot/pi-apps/files/12114457/logs.zip)

**Comment by theofficialgman** [comment]
your armcord package is marked as manually install because as you said you manually installed it before.
this prevents pi-apps from uninstalling it in the first place since you manually installed it.

what version does apt report as installed? `apt list armcord`

**Comment by TheAlienDrew** [comment]
> your armcord package is marked as manually install because as you said you manually installed it before.
> this prevents pi-apps from uninstalling it in the first place since you manually installed it.
> 
> what version does apt report as installed? `apt list armcord`

Ah yeah, I see it shows the older version installed:

```bash
Listing... Done
armcord/now 3.1.3 arm64 [installed,local]
```

**Comment by TheAlienDrew** [comment]
Shouldn't there be a better warning or disclaimer when something like this is happening?

**Comment by theofficialgman** [comment]
@Botspot not sure what do to about this.
pin priorities are no help because those only affect the software if it is not currently installed.

the only solution I have is modifying the dummy deb to include a `>=` the version of any downloaded file

**Comment by Botspot** [comment]
`install_packages` or `purge_packages` could mark local debs as automatically installed.

**Comment by theofficialgman** [comment]
I've already explained why that would be bad multiple times before. thats not an option.

**Comment by Botspot** [comment]
> I've already explained why that would be bad multiple times before. thats not an option.

I could be mistaken, but in the past my bad suggestion was to mark *all* packages wanted by the dummy deb as `auto`, but this time I was suggesting to only mark locally downloaded packages as `auto`.

Potential caveats for changing dummy debs to require the latest version of a package:
1. It could break other areas in the api where details of the dummy deb are parsed. Namely, I'm thinking of the code that checks the dummy deb's current list of dependencies. That code would need to be tested in all cases to work with added version numbers.
2. It would prevent the user from manually installing an older version of the local package, to troubleshoot an issue. The dummy deb would first need to be uninstalled.

Maybe instead `install_packages` could detect this situation and during the time when the local apt repository is still set up, it could run `sudo apt upgrade armcord`.

**Comment by theofficialgman** [comment]
> 1. It could break other areas in the api where details of the dummy deb are parsed. Namely, I'm thinking of the code that checks the dummy deb's current list of dependencies. That code would need to be tested in all cases to work with added version numbers.

good point. `get_icon_from_package` will need to be updated to remove the version number when checking with dpkg-query for the icon

> 2. It would prevent the user from manually installing an older version of the local package, to troubleshoot an issue. The dummy deb would first need to be uninstalled.

sounds like a feature to me

> Maybe instead `install_packages` could detect this situation and during the time when the local apt repository is still set up, it could run `sudo apt upgrade armcord`.

I don't like that solution as much since we would need to first parse all depends then pass them it to `sudo apt install --upgrade-only` (`sudo apt upgrade armcord` is invalid syntax, upgrade does not take any package names as arguments, it just ignores them and does a regular upgrade)

**Comment by theofficialgman** [comment]
> > 1. It could break other areas in the api where details of the dummy deb are parsed. Namely, I'm thinking of the code that checks the dummy deb's current list of dependencies. That code would need to be tested in all cases to work with added version numbers.
> 
> good point. `get_icon_from_package` will need to be updated to remove the version number when checking with dpkg-query for the icon

nevermind, it is already good because of the `awk '{print $1}'` that is already included.
so no futher changes necessary

**Comment by Botspot** [comment]
> good point. get_icon_from_package will need to be updated to remove the version number when checking with dpkg-query for the icon

get_icon_from_package is not normally used on dummy debs...

> (sudo apt upgrade armcord is invalid syntax, upgrade does not take any package names as arguments, it just ignores them and does a regular upgrade)

Are you sure?
```
$ sudo apt upgrade chromium-browser
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
chromium-browser is already the newest version (113.0.5672.95-rpt1).
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

**Comment by theofficialgman** [comment]
yes, I just told my system to update bash `sudo apt update bash` and it updated google-chrome.....

**Comment by theofficialgman** [comment]
As a side affect of the PR, I think it is also nice to see the versions listed out to the user.
```
Allowing packages required by the ArmCord app to be uninstalled
These packages were: armcord (>= 3.2.1)
```

the `>=` system is widely used in debian in metapackages (what our dummy debs are), I see it as appropriate here.
