### ISSUE TITLE
Flashy - Run Adobe Flash Player content on the Raspberry Pi (.DEB package app)

### ISSUE THREAD

**Issue by Shock-OS** [Botspot/pi-apps#2397]
### What is the name of the app?

Flashy

### (Optional) Where is the app hosted?

[Flashy GitHub repo](https://github.com/Shock-OS/Flashy)

### About the app

Flashy is a front-end for running Adobe Flash Player games (SWF files). Using a simple, YAD powered GUI, Flashy makes it easy to run Flash content, install Flash content (create a .desktop file shortcut that automatically runs a SWF using Ruffle), and install/upgrade Ruffle! That's right - Flashy has a script that automatically compiles Ruffle on the Raspberry Pi. This can be very helpful as it automates a process that would otherwise be very hard and confusing for many. Flashy runs on pretty much any architecture, and has been tested on x86_64, and armhf and aarch64 on the Raspberry Pi 4B 8GB. On x86_64 machines, Flashy primarily utilizes the [Adobe Flash Player Standalone](https://flathub.org/apps/com.adobe.Flash-Player-Projector) runtime as it provides the best compatibility and performance (at least for now). But this runtime is unfortunately unavailable on non x86_64 machines (including the Raspberry Pi), so on these machines, Ruffle is used instead.

### Upload file or Add PR Link

NOTE: Flashy will likely be updated in the future, so if possible, please program the script to download the latest .DEB package from the GitHub releases page linked below. Thanks :)

[GitHub download (.DEB package)](https://github.com/Shock-OS/Flashy/releases)

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by Botspot** [comment]
Well done with the yad usage. I was genuinely impressed by some of the ways yad is being used in the scripts.

However, your scripts do not handle errors or failures very well. There are no error messages if anything goes wrong, and your scripts will continue even if a crucial step fails. This is particularly obvious in your [flashy-ruffle-installer](https://github.com/Shock-OS/Flashy/blob/fab7aad446f7e293f453ece3ec9f1cd78685a4e9/flashy-1.0-all/usr/bin/flashy-ruffle-installer) script. As a maintainer of a large app store, I have seen that pretty much any command can and will fail. So in all our app installation scripts, we are very careful to add messages like `|| error "this step failed"` to the end of nearly every line.

Also, your use of apt is not ideal as it does not remove the unnecessary build packages after compilation, instead leaving them installed. Adding an `apt purge` line may be tempting, but those packages may be necessary for other things. For this reason, I would recommend allowing pi-apps and its `install_packages` to handle compiling Ruffle. This will both keep Ruffle updated, and with the special way in which our `install_packages` function operates, it will correctly uninstall only which packages are safe to uninstall.
I recommend reading [our documentation](https://pi-apps.io/wiki/development/DOCUMENTATION/). While it is quite in-depth, I have tried to keep it easy to understand.

**Comment by Shock-OS** [comment]
Hey Botspot! I appreciate you pointing out these flawed areas, and I will get to work on making these improvements.

**Comment by theofficialgman** [comment]
Well actually @Botspot since @Shock-OS is making a deb of this. They shouldn't use install_packages/purge_packages. They should instead actually create their deb CONTROL file with the necessary dependencies listed

btw, I do think that a space after the `,` is a requirement by debian. I have certainly never seen an official package without them
```
Depends: yad,wget
```

you can have different control files per architecture if that is what you are concerned about (since only non-x86_64 needs ruffle with its dependencies). just don't make an _all deb and instead make per architecture debs.

**Comment by theofficialgman** [comment]
also you can run `flatpak` as part of a debian postinstall script. so there really is no need for `flashy-flashplayer-flapak-installer` at all either

**Comment by Shock-OS** [comment]
That is a good point @theofficialgman, I too realized that I couldn't use `install_packages` outside of Pi Apps. The `flashy-ruffle-installer` script will need to remain though, just without the line that installs the dependencies, as that will be done in the `postinst` script. That way Ruffle can be easily upgraded, which is very useful especially while it still only has nightly builds.

As for the dependencies, the syntax is correct. It may not be traditional formatting, as you pointed out, but I have build multiple .DEB packages before (all with that same syntax) and I can verify that it works just fine :)

However, I was not aware of the ability to make per-architecture control files. I will definitely look into that - thanks for the suggestion @theofficialgman.

**Comment by theofficialgman** [comment]
https://flathub.org/apps/com.adobe.Flash-Player-Projector is only available for x86_64 from flathub
sorry that I didn't notice this before.

given this project (flashy) seems abandoned and not being able to actually run on an ARM64 system, this will be closed.
