### ISSUE TITLE
Add conky rings twister theme, install script

### ISSUE THREAD

**Issue by SputnikRocket** [Botspot/pi-apps#2399]
### What is the name of the app?

Conky Rings Twister Theme

### (Optional) Where is the app hosted?

https://github.com/SputnikRocket/conky-rings-8core

### About the app

Conky rings theme heavily modified and redone for 8 core support, themed with twisterOS colors and style.
Created because of the rising usage of newer SBCs with 8 cores.
Installs a 4 core theme if 8 cores are not detected.

### Upload file or Add PR Link

[Conky Rings Twister Theme.zip](https://github.com/Botspot/pi-apps/files/12156817/Conky.Rings.Twister.Theme.zip)

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [x] I have confirmed that this app can run on Raspberry Pi.

**Comment by theofficialgman** [comment]
We are not interested in non-raspberry pi compatible apps currently. That is why all of the confirmation checkboxes are a requirement to submit an issue.

Regardless, please send a screenshot of the conky rings from this zip as well as the already existing conky rings from pi-apps.

If they overlap it would be much better to have the theme be generated programatically based on the number of cores on the users system and simply update the existing `Conkey Rings` app

**Comment by theofficialgman** [comment]
4 cores and 8 cores only cover a small number of potential systems. Please look into doing this at runtime. its a lua script, you can obtain the number of cores/threads in the script and make the number of "bars" based on that information.

**Comment by theofficialgman** [comment]
> As shown, my theme differs significantly from the original. Therefore, my theme can not be considered an "extension" of the original.

it looks the same to me with the main difference being the color pallet.

**Comment by Botspot** [comment]
> 4 cores and 8 cores only cover a small number of potential systems. Please look into doing this at runtime. its a lua script, you can obtain the number of cores/threads in the script and make the number of "bars" based on that information.

It might be harder than it seems to do that. This theme uses lua for the rings and the classic conkyrc for the text. Both files would need to detect the number of cores and adjust accordingly, all while maintaining alignment and picking the right colors, etc.

**Comment by theofficialgman** [comment]
see

> > 4 cores and 8 cores only cover a small number of potential systems. Please look into doing this at runtime. its a lua script, you can obtain the number of cores/threads in the script and make the number of "bars" based on that information.
> 
> It might be harder than it seems to do that. This theme uses lua for the rings and the classic conkyrc for the text. Both files would need to detect the number of cores and adjust accordingly, all while maintaining alignment and picking the right colors, etc.

see this project https://github.com/Aparicio99/conkyrc . It generates conkyrc files based on a supplied `jinja2` template. obtains the number of cpus, model, swap, disks, filesystems, and network interfaces so that the generated conkyrc can match the system.
also conkyrc can do conditional statements, so you could support the common core counts (2, 4, 6, 8, 12)

> Although I do agree, I think that the majority of "desktop" systems are either 4 core or 8 core. therefore, I think installing a 4 core or 8 core config would be sufficient for most scenarios.

looks at two 6 core systems on my desk (orin nano and my desktop PC)
