### ISSUE TITLE
FreeCad fail.

### ISSUE THREAD

**Issue by Ratteler** [Botspot/pi-apps#24]
Tried to install FreeCad on Twister OS 1.8.4 which is a Raspberry Pi OS fork with n XFCE front end themed to look like other various OS. I use in iRaspbien Dark.

[Freecad compile.txt](https://github.com/Botspot/pi-apps/files/5399274/Freecad.compile.txt)

**Comment by Botspot** [comment]
Hmm. Even if the terminal exits with an error, I think FreeCAD really was successfully installed.  
Does `/usr/local/share/applications/org.freecadweb.FreeCAD.desktop` exist?  
Try running this command in a terminal:

    FreeCAD

**Comment by Botspot** [comment]
@Ratteler Have you seen this yet?

**Comment by Botspot** [comment]
@Ratteler Unfortunately, I have to close this issue due to your inactivity.

**Comment by Ratteler** [comment]
> Hmm. Even if the terminal exits with an error, I think FreeCAD really was successfully installed.
> Does `/usr/local/share/applications/org.freecadweb.FreeCAD.desktop` exist?

yes

> Try running this command in a terminal:
> 
> ```
> FreeCAD
> ```
FreeCAD: error while loading shared libraries: libQtOpenGL.so.4: cannot open shared object file: No such file or directory

**Comment by Botspot** [comment]
OK I'm trying something - reinstall freecad please

**Comment by Ratteler** [comment]
I already tried the precompliled. It's running the complied version now.

**Comment by Botspot** [comment]
I just made a change to `FreeCAD` and `FreeCAD (precompiled)` 20 minutes ago which may solve your issue.  
Please try it again.

**Comment by Ratteler** [comment]
The build locked up. After a few hours of the mouse not moving, I restarted.
I started the build again, and long story short, FreeCAD is now up and running.
:-D

**Comment by Botspot** [comment]
> I started the build again, and long story short, FreeCAD is now up and running.
> :-D

Excellent! The change I made was to leave all the build packages installed. Some of those packages are (apparently) necessary for FreeCAD to launch, though most of them could be uninstalled without a problem.  
Better be safe than sorry I guess. Glad it's working for you.
