### ISSUE TITLE
MacOSBigSurThemeConverter

### ISSUE THREAD

**Issue by techcoder20** [Botspot/pi-apps#240]
[MacOSBigSurThemeConverter.zip](https://github.com/Botspot/pi-apps/files/5812491/MacOSBigSurThemeConverter.zip)

This zip file has the files for the MacOSBigSurThemeConverter app
Btw add it to the Eyecandy category and also add it to the hidelist in twister os
Website: https://github.com/techcoder20/MacOSBigSurThemeConverter

Here is a screenshot if your wondering how it looks
![screenshot](https://raw.githubusercontent.com/techcoder20/MacOSBigSurThemeConverter/main/Screenshots/MacOSBigSurLightScreenshot.png)

**Comment by Botspot** [comment]
Does this work on Raspberry Pi OS?

**Comment by Itai-Nelken** [comment]
@Botspot it's made for RPiOS, i tested it on RPiOS and works really well.

**Comment by Botspot** [comment]
Okay I tried it in vdesktop.

It worked well, though as soon as the installation terminal closed (after 30 seconds), the panel and window manager disappeared.

@techcoder20 I had the same problem, but found a way to keep those process running in the background with my windows 10 theme. Have a look. https://github.com/Botspot/pi-apps/commit/7ddcf3ed5d040064d38de5e05ac5e1d775ab8ac7

**Comment by techcoder20** [comment]
Okay I tried with the setsid command but i don't know why the terminal just closes sometimes randomly and pi apps thinks the installation is over and there were no problem. So what I did was separate the install script and theme converter script. So now after the installation is over the user has to launch the ThemeConverter app and from there they can apply the theme.

[MacOSBigSurThemeConverter.zip](https://github.com/Botspot/pi-apps/files/5823803/MacOSBigSurThemeConverter.zip)

**Comment by techcoder20** [comment]
[MacOSBigSurThemeConverter.zip](https://github.com/Botspot/pi-apps/files/5825949/MacOSBigSurThemeConverter.zip)

@Botspot Please take a look at this zip file :)

**Comment by techcoder20** [comment]
@Botspot I am done with the script. Please check it out when ur free :)

[MacOSBigSurThemeConverter.zip](https://github.com/Botspot/pi-apps/files/5850754/MacOSBigSurThemeConverter.zip)

**Comment by techcoder20** [comment]
@Botspot  I got a fix for the panel crashing after the terminal closing. I just added the refresh desktop part to the pi apps script and it worked 

[MacOSBigSurThemeConverter.zip](https://github.com/Botspot/pi-apps/files/5879799/MacOSBigSurThemeConverter.zip)

**Comment by techcoder20** [comment]
@Botspot were u able to try this out ⬆️

**Comment by techcoder20** [comment]
@Botspot is it working for u ?

**Comment by Botspot** [comment]
I'm trying it again right now, this time not in vdesktop.

Error message I happened to see while it installed:
```
Selecting previously unselected package ulauncher.
(Reading database ... 105428 files and directories currently installed.)
Preparing to unpack .../ulauncher_5.9.0_all.deb ...
Unpacking ulauncher (5.9.0) ...
dpkg: dependency problems prevent configuration of ulauncher:
 ulauncher depends on gir1.2-keybinder-3.0 (>= 0.3); however:
  Package gir1.2-keybinder-3.0 is not installed.
 ulauncher depends on python3-distutils-extra; however:
  Package python3-distutils-extra is not installed.
 ulauncher depends on python3-levenshtein; however:
  Package python3-levenshtein is not installed.
 ulauncher depends on python3-websocket; however:
  Package python3-websocket is not installed.

dpkg: error processing package ulauncher (--install):
 dependency problems - leaving unconfigured
Processing triggers for bamfdaemon (0.5.4-1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for gnome-menus (3.31.4-3) ...
Processing triggers for desktop-file-utils (0.23-4) ...
Processing triggers for mime-support (3.62) ...
Processing triggers for gnome-icon-theme (3.12.0-3) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Errors were encountered while processing:
 ulauncher
```

**Comment by Itai-Nelken** [comment]
> I'm trying it again right now, this time not in vdesktop.
> 
> Error message I happened to see while it installed:
> 
> ```
> Selecting previously unselected package ulauncher.
> (Reading database ... 105428 files and directories currently installed.)
> Preparing to unpack .../ulauncher_5.9.0_all.deb ...
> Unpacking ulauncher (5.9.0) ...
> dpkg: dependency problems prevent configuration of ulauncher:
>  ulauncher depends on gir1.2-keybinder-3.0 (>= 0.3); however:
>   Package gir1.2-keybinder-3.0 is not installed.
>  ulauncher depends on python3-distutils-extra; however:
>   Package python3-distutils-extra is not installed.
>  ulauncher depends on python3-levenshtein; however:
>   Package python3-levenshtein is not installed.
>  ulauncher depends on python3-websocket; however:
>   Package python3-websocket is not installed.
> 
> dpkg: error processing package ulauncher (--install):
>  dependency problems - leaving unconfigured
> Processing triggers for bamfdaemon (0.5.4-1) ...
> Rebuilding /usr/share/applications/bamf-2.index...
> Processing triggers for gnome-menus (3.31.4-3) ...
> Processing triggers for desktop-file-utils (0.23-4) ...
> Processing triggers for mime-support (3.62) ...
> Processing triggers for gnome-icon-theme (3.12.0-3) ...
> Processing triggers for hicolor-icon-theme (0.17-2) ...
> Errors were encountered while processing:
>  ulauncher
> ```

I think I also had that error, but ulauncher was still installed.
@techcoder20 maybe change the script so it installs ulauncher from pi-apps (after installing pi-apps) (`~/pi-apps/manage install Ulauncher)?

**Comment by Botspot** [comment]
Also this happened right towards the end:
```
cp: cannot create directory '/home/pi/.local/share/plank/themes/': No such file or directory
cp: cannot create directory '/home/pi/.local/share/plank/themes/': No such file or directory
rm: cannot remove '/home/pi/.config/plank': No such file or directory
```

**Comment by Botspot** [comment]
Aside from those errors, it seems to have installed fine for me.

One observation: The terminal never closed on its own. When I closed the terminal, Pi-Apps assumed the app installation existed with an error.

**Comment by Botspot** [comment]
Now I'm trying to uninstall it.

Immediate errors:
```
Uninstalling MacOSBigSurThemeConverter
cp: cannot stat '/home/pi/.local/share/MacOSBigSurThemeConverter/.config_backup/lxpanel': No such file or directory
cp: cannot stat '/home/pi/.local/share/MacOSBigSurThemeConverter/.config_backup/lxsession': No such file or directory
cp: cannot stat '/home/pi/.local/share/MacOSBigSurThemeConverter/.config_backup/lxterminal': No such file or directory
cp: cannot stat '/home/pi/.local/share/MacOSBigSurThemeConverter/.config_backup/pcmanfm': No such file or directory
rm: cannot remove '/home/pi/.local/share/plank/themes/mcOS-BS-Black-Stock/': No such file or directory
```

**Comment by Botspot** [comment]
That's not good. :(

```
Uninstalled MacOSBigSurThemeConverter successfully.

Closing in 30 seconds.
Removing lightpad (0.0.8~rev1) ...
Removing lolcat (42.0.99-1) ...
Removing nautilus (3.30.5-2+b1) ...
Removing network-manager-gnome (1.8.20-1.1) ...
Removing network-manager (1.14.6-2+deb10u1) ...
Removing panther-launcher (20210119-1) ...
Removing pavucontrol (3.0-4) ...
Removing plank (0.11.4-4) ...
Removing ulauncher (5.9.0) ...
Removing xfce4-appmenu-plugin (0.7.1+dfsg1-1) ...
Removing xfce4-panel (4.12.2-1) ...
Removing xfce4-panel-profiles (1.0.10-1) ...
dpkg: warning: while removing xfce4-panel-profiles, directory '/usr/local/share/applications' not empty so not removed
dpkg: warning: while removing xfce4-panel-profiles, directory '/usr/local/bin' not empty so not removed
Removing xfce4-pulseaudio-plugin:armhf (0.4.1-1) ...
Removing xfce4-settings (4.12.4-1) ...
Removing xfce4-statusnotifier-plugin (0.2.1-1) ...
Removing xfwm4 (4.12.5-1) ...
Processing triggers for desktop-file-utils (0.23-4) ...
Processing triggers for mime-support (3.62) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for gnome-menus (3.31.4-3) ...
Processing triggers for libglib2.0-0:armhf (2.58.3-2+deb10u2) ...
Processing triggers for libc-bin (2.28-10+rpi1) ...
Processing triggers for man-db (2.8.5-2) ...
Processing triggers for gnome-icon-theme (3.12.0-3) ...
Processing triggers for dbus (1.12.20-0+deb10u1) ...
Processing triggers for bamfdaemon (0.5.4-1) ...
Rebuilding /usr/share/applications/bamf-2.index...
(Reading database ... 112180 files and directories currently installed.)
Purging configuration files for plank (0.11.4-4) ...
Purging configuration files for network-manager-gnome (1.8.20-1.1) ...
Purging configuration files for network-manager (1.14.6-2+deb10u1) ...

Progress: [ 89%] [##################################################.......] 
```
The script was still doing stuff when the terminal closed.

**Comment by Botspot** [comment]
Another observation: After uninstalling, the window manager is not the same as before.  
![2021-02-08-115305_1920x1080_scrot](https://user-images.githubusercontent.com/54716352/107261020-66ad9f00-6a04-11eb-8315-75f5f7a07c1a.png)

Perhaps this was caused by the script exiting prematurely, or it was caused by something else.

**Comment by Itai-Nelken** [comment]
> Another observation: After uninstalling, the window manager is not the same as before.
> ![2021-02-08-115305_1920x1080_scrot](https://user-images.githubusercontent.com/54716352/107261020-66ad9f00-6a04-11eb-8315-75f5f7a07c1a.png)
> 
> Perhaps this was caused by the script exiting prematurely, or it was caused by something else.

actually I also happened to me, but I assumed something was wrong on my end.

**Comment by techcoder20** [comment]
> Another observation: After uninstalling, the window manager is not the same as before.
> ![2021-02-08-115305_1920x1080_scrot](https://user-images.githubusercontent.com/54716352/107261020-66ad9f00-6a04-11eb-8315-75f5f7a07c1a.png)
> 
> Perhaps this was caused by the script exiting prematurely, or it was caused by something else.

This was fixed for me after rebooting.

**Comment by techcoder20** [comment]
> That's not good. :(
> 
> ```
> Uninstalled MacOSBigSurThemeConverter successfully.
> 
> Closing in 30 seconds.
> Removing lightpad (0.0.8~rev1) ...
> Removing lolcat (42.0.99-1) ...
> Removing nautilus (3.30.5-2+b1) ...
> Removing network-manager-gnome (1.8.20-1.1) ...
> Removing network-manager (1.14.6-2+deb10u1) ...
> Removing panther-launcher (20210119-1) ...
> Removing pavucontrol (3.0-4) ...
> Removing plank (0.11.4-4) ...
> Removing ulauncher (5.9.0) ...
> Removing xfce4-appmenu-plugin (0.7.1+dfsg1-1) ...
> Removing xfce4-panel (4.12.2-1) ...
> Removing xfce4-panel-profiles (1.0.10-1) ...
> dpkg: warning: while removing xfce4-panel-profiles, directory '/usr/local/share/applications' not empty so not removed
> dpkg: warning: while removing xfce4-panel-profiles, directory '/usr/local/bin' not empty so not removed
> Removing xfce4-pulseaudio-plugin:armhf (0.4.1-1) ...
> Removing xfce4-settings (4.12.4-1) ...
> Removing xfce4-statusnotifier-plugin (0.2.1-1) ...
> Removing xfwm4 (4.12.5-1) ...
> Processing triggers for desktop-file-utils (0.23-4) ...
> Processing triggers for mime-support (3.62) ...
> Processing triggers for hicolor-icon-theme (0.17-2) ...
> Processing triggers for gnome-menus (3.31.4-3) ...
> Processing triggers for libglib2.0-0:armhf (2.58.3-2+deb10u2) ...
> Processing triggers for libc-bin (2.28-10+rpi1) ...
> Processing triggers for man-db (2.8.5-2) ...
> Processing triggers for gnome-icon-theme (3.12.0-3) ...
> Processing triggers for dbus (1.12.20-0+deb10u1) ...
> Processing triggers for bamfdaemon (0.5.4-1) ...
> Rebuilding /usr/share/applications/bamf-2.index...
> (Reading database ... 112180 files and directories currently installed.)
> Purging configuration files for plank (0.11.4-4) ...
> Purging configuration files for network-manager-gnome (1.8.20-1.1) ...
> Purging configuration files for network-manager (1.14.6-2+deb10u1) ...
> 
> Progress: [ 89%] [##################################################.......] 
> ```
> 
> The script was still doing stuff when the terminal closed.

This happens because it uses setsid. The same thing happens in the windows 10 theme so I thought it was fine.

**Comment by techcoder20** [comment]
> Also this happened right towards the end:
> 
> ```
> cp: cannot create directory '/home/pi/.local/share/plank/themes/': No such file or directory
> cp: cannot create directory '/home/pi/.local/share/plank/themes/': No such file or directory
> rm: cannot remove '/home/pi/.config/plank': No such file or directory
> ```

Thats fine that happens because plank has not been launched before due to which there is no config or themes folder. I will hide these errors

**Comment by techcoder20** [comment]
> Aside from those errors, it seems to have installed fine for me.
> 
> One observation: The terminal never closed on its own. When I closed the terminal, Pi-Apps assumed the app installation existed with an error.

Thats really strange. Any idea why that might have happened ?

**Comment by Botspot** [comment]
> > Aside from those errors, it seems to have installed fine for me.
> > One observation: The terminal never closed on its own. When I closed the terminal, Pi-Apps assumed the app installation existed with an error.
> 
> Thats really strange. Any idea why that might have happened ?

Yes. When I **closed** the **theme selection window**, then the terminal detected the script having exited.

> This happens because it uses setsid. The same thing happens in the windows 10 theme so I thought it was fine.

Setsid is used for running stuff in the background. Do you want an entire uninstallation script running in the background? No.

But, you may want setsid used to launch the panel and taskbar programs to keep them open after the terminal closes.

**Comment by techcoder20** [comment]
Okay I will send a updated zip soon

**Comment by techcoder20** [comment]
@Botspot I finally fixed the bugs. 

1. Ulauncher does show those packages not being installed but that is promptly fixed with the `sudo apt -y --fix-broken install`   command
2. I suppressed majority of the errors for `rm`and `cp` commands with either `-f` or `&>/dev/null`
3.  The reason we got the weird buttons was that i used the `openbox` command while I was supposed to be using `openbox-lxde-pi` command
4. And about the terminal not closing I was able to fix that by removing the setsid command in the pi apps installation script which i still dont fully understand how it worked.

So with the all this fixed bugs here is the final zip file:  
[MacOSBigSurThemeConverter.zip](https://github.com/Botspot/pi-apps/files/5965034/MacOSBigSurThemeConverter.zip)

**Comment by techcoder20** [comment]
@Botspot is it working for you ?

**Comment by Itai-Nelken** [comment]
I just installed it and it works perfectly fine.
I didn't try to uninstall though because I installed it on my main OS for now.

**Comment by Itai-Nelken** [comment]
I uninstalled it and it works perfectly fine.
@techcoder20 I would recommend to add `sudo apt autoremove -y` at the end of the uninstall script.

**Comment by Itai-Nelken** [comment]
also `compton` and `uxterm` aren't uninstalled (even after running apt autoremove)

**Comment by Itai-Nelken** [comment]
@techcoder20 also ~/MacOSBigSurThemeConverter isn't deleted when uninstalling

**Comment by techcoder20** [comment]
> @techcoder20 also ~/MacOSBigSurThemeConverter isn't deleted when uninstalling

Done it will remove folder now. Also did the installation script work properly for you ?

**Comment by techcoder20** [comment]
@Itai-Nelken Its fixed now :)

**Comment by techcoder20** [comment]
@Botspot is it working for you ?

**Comment by techcoder20** [comment]
@Botspot does this need any other changes ?

**Comment by Itai-Nelken** [comment]
in my opinion its as good as it can get.

**Comment by Botspot** [comment]
> @Itai-Nelken Its fixed now :)

@techcoder20, Is the zip you put [here](https://github.com/Botspot/pi-apps/issues/240#issuecomment-777401365) still the latest version?  
I'm ready to add this, but be aware that I won't be able to provide more than basic tech support for users who encounter problems.

**Comment by techcoder20** [comment]
This is the the latest and final: https://github.com/Botspot/pi-apps/files/5965034/MacOSBigSurThemeConverter.zip
and if anyone faces problems I am active in the pi-apps github and if I dont reply for some reason redirect them to the MacOSBigSurThemeConverter github page.

**Comment by Botspot** [comment]
One last thing: What should the app be called?

In my humble opinion, I think one long, mashed up word could be improved upon.

How about something simple: `Mac OS Theme`? (It would integrate well with the existing `Windows 10 Theme`)

**Comment by techcoder20** [comment]
Mac OS Theme Is good :)

**Comment by Botspot** [comment]
Added to Pi-Apps with commit 823e6e277c8de6e3c1b980bd1dcbd63a7cdff73c
