### ISSUE TITLE
GameMaker (beta) Install based

### ISSUE THREAD

**Issue by Liam1910** [Botspot/pi-apps#2407]
### What is the name of the app?

GameMaker (beta)

### (Optional) Where is the app hosted?

https://gamemaker.io/

### About the app

GameMaker is a free game Engine that uses a custom language to code (as an example Movement of certain objects) that has the .gml file Extension. GameMaker is very user friendly.

### Upload file or Add PR Link

[GameMaker (beta).zip](https://github.com/Botspot/pi-apps/files/12209827/GameMaker.beta.zip)

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by Liam1910** [comment]
I tested it on My 64-bit Raspbian Raspberry Pi and it worked very well, i hope it works for any of you testers too...

**Comment by Liam1910** [comment]
I tested it on My 64-bit Raspbian Raspberry Pi and it worked very well, i hope it works for any of you testers too...

**Comment by theofficialgman** [comment]
I won't comment on the app itself but only your scripts. please read our documentation as it is very clear based on how you have written the scripts you haven't read any of it https://pi-apps.io/wiki/development/Creating-an-app/

**Comment by theofficialgman** [comment]
also this deb is really horribly packaged... armv7l, aarch64, an x86_64 binaries all in on deb. thats just wasting a ton of space on the users install

also the "architecture" detection is broken. armv7l OS often run aarch64 kernel and the script will return the wrong value. you should report that upstream

```
#!/usr/bin/env bash

machine="$(uname -m)"
kernel="$(uname -s)"

cd "${0%/*}/$machine"

if [ "$kernel" = "Linux" ]; then
	# Deal with all the fun variants of "arm" that Linux will report (for now...)
	# See https://stackoverflow.com/a/45125525
	
	case "$machine" in
		aarch64*|armv8*)
			cd "${0%/*}/aarch64"
			;;
			
		arm*)
			cd "${0%/*}/armv7l"
			;;
		*)
			;;
	esac
elif [[ "$kernel" = "Darwin" ]]; then
	# Terminals and shell scripts in apps can be run in Rosetta! where you'll get x86_64 instead of arm64
	if [[ $(sysctl -in sysctl.proc_translated) = "1" ]]; then
		cd "${0%/*}/arm64"
	fi
fi
```

**Comment by theofficialgman** [comment]
upstream has not fixed these issues.

without those changes implemented this can never be added. I am not interested in reaching out as I have no use for this software.

If you reach out and have upstream fix their packaging I am happy to re-open in the future.
