### ISSUE TITLE
testing

### ISSUE THREAD

**Issue by theofficialgman** [Botspot/pi-apps#2415]
### What is the name of the app?

test

### (Optional) Where is the app hosted?

test

### About the app

test

### Upload file or Add PR Link

https://github.com/Botspot/pi-apps/files/11642018/Cascaydia.Cove.NF.zip

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by theofficialgman** [comment]
@Botspot thought something like this would be helpful ^

**Comment by Botspot** [comment]
Does this handle edits to the original body message or replies with their own new zip files?

**Comment by theofficialgman** [comment]
> Does this handle edits to the original body message or replies with their own new zip files?

No. The current implementation is minimum viable product. It only runs on the initial opening of an issue and only checks the body for zip urls in the `Upload file or Add PR Link` section.
It can be further built out later.

It's very very simple currently:
https://github.com/Botspot/pi-apps/blob/master/.github/workflows/zip-preview.yml

**Comment by theofficialgman** [comment]
[GameMaker (beta).zip](https://github.com/Botspot/pi-apps/files/12209827/GameMaker.beta.zip)

**Comment by theofficialgman** [comment]
hi

[GameMaker (beta).zip](https://github.com/Botspot/pi-apps/files/12209827/GameMaker.beta.zip)

**Comment by theofficialgman** [comment]
https://github.com/Crilum/stuff/blob/main/GroupMe-linux-armv7l.zip?raw=true
