### ISSUE TITLE
[Install based app request] Open-Typer App request

### ISSUE THREAD

**Issue by Sussy-OS** [Botspot/pi-apps#2422]
### What is the name of the app?

Open-Typer

### (Optional) Where is the app hosted?

https://github.com/Open-Typer/Open-Typer

### About the app

The Open-Typer app is an open sourced typing tutor created in Qt.

### Upload file or Add PR Link

#2421 

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi-Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by Botspot** [comment]
We don't need an issue open and a PR open. Closing.
