### ISSUE TITLE
[App Request] Jitsi Meet WPA (like Zoom)

### ISSUE THREAD

**Issue by hoasis2** [Botspot/pi-apps#2424]
### What is the name of the app?

Jitsi Meet  Web-App

### (Optional) Where is the app hosted?

Official
[https://meet.jits.si/](https://meet.jits.si/)
Community-instances
[https://jitsi.github.io/handbook/docs/community/community-instances/](https://jitsi.github.io/handbook/docs/community/community-instances/)

### About the app

[[https://en.wikipedia.org/wiki/Jitsi#Jitsi_Meet](https://en.wikipedia.org/wiki/Jitsi#Jitsi_Meet)]
Jitsi Meet is an open source JavaScript WebRTC application used primarily for video conferencing. In addition to audio and video, screen sharing is available, and new members can be invited via a generated link. The interface is accessible via web browser or with a mobile app.[38] The Jitsi Meet server software can be downloaded and installed on Linux-based computers.[39] Jitsi owner 8x8 maintains a free public-use server for up to 100 participants at meet.jit.si

The same procedure as for Zoom WPA.

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have read the app eligibilty rubric https://github.com/Botspot/pi-apps/issues/185 and confirmed this app is suitable for addition in Pi-Apps.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi-Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by theofficialgman** [comment]
We aren't interested in adding any new PWA, nativefier, or any similar apps. The distros default chromium browser should be used for these applications. If you wish to add your own icon for a particular website I encourage you to use the `Webapps` GUI application available in pi-apps to do so.

There is discussion in multiple issues but you can start reading here https://github.com/Botspot/pi-apps/issues/2321 . In addition, all existing nativefier apps are in the process of being converted to Web apps https://github.com/Botspot/pi-apps/pull/2333 .
