### ISSUE TITLE
Kdenlive Video Editor

### ISSUE THREAD

**Issue by xPi400** [Botspot/pi-apps#2427]
### What is the name of the app?

Kdenlive

### (Optional) Where is the app hosted?

kdenlive.org

### About the app

Kdenlive is a free and open-source video editor that can run on the Raspberry Pi (4gb of RAM or more for good performance)

### Upload file or Add PR Link

[Kdenlive.zip](https://github.com/Botspot/pi-apps/files/12365605/Kdenlive.zip)

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi-Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by Botspot** [comment]
Thank you for taking the time to submit this. I hope you found the process straightforward. If anything was confusing for you, please let us know.
Just as a reminder, Pi-Apps is not a GUI for apt. Other programs already do that nicely. So this is unlikely to be added unless there are other video editors already on pi-apps. I suggest reading the note about package apps on [the app eligibility rubric.](https://github.com/Botspot/pi-apps/issues/185)

If you find some way to make this version of kdenlive *better* than what can be found from APT, then we could probably add this. For example, if you can make it install from source or can find a newer version with more useful features, then we can make the case that adding it would have unique value.

**Comment by xPi400** [comment]
I am trying to find a way to have Kdenlive install with more features, and I would use a thing that would ask if you want to install the beta or the stable, but I don't think the beta runs on RPi without Wine or something.

**Comment by theofficialgman** [comment]
Botspot said it well. Pi-Apps does not have any other video editors. Kdenlive can be most easily installed with apt or via the flatpak (as is the case with almost all KDE official applications), both of which are handled well in other dedicated software stores.

**Comment by theofficialgman** [comment]
closed as not planned, not completed
