### ISSUE TITLE
EDIT ME Include the app name and if it is a Package app or an Install based App

### ISSUE THREAD

**Issue by BITIW** [Botspot/pi-apps#2430]
### What is the name of the app?

Playit.gg

### (Optional) Where is the app hosted?

Playit.gg

### About the app

playit.gg is a networking service that make it possible to host game servers at home that anyone across the world can join. We do this through our custom tunneling software. When you launch the playit program, the program will connect to our Anycast Network and assign you a static IP and port. You can then share your static IP and port with friends. When they connect, their connection information will go to the nearest tunnel server and be tunneled to the playit program running on your computer. By tunneling the connection, your friend is able to connect to the server running within your network.

### Upload file or Add PR Link

edit: gman re-upload as a zip
[Playit.zip](https://github.com/Botspot/pi-apps/files/12501068/Playit.zip)

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi-Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by Botspot** [comment]
Hello, thank you for taking the time to request this to be added to Pi-Apps. First, I recommend you tweak your github issue to get the title right. Of course I could do it, but it would get annoying if I did that for everyone.

I recommend reading through [our app submission documentation](https://pi-apps.io/wiki/development/Creating-an-app/). It includes some script-writing guidelines and specific allowed ways to install apt packages.
In your case, you should be using our `install_packages` function, and you should be removing the apt repo and GPG key on uninstall. You also missed some `|| error` lines.
Also your description should include usage information. Consider it a short manpage or `--help` menu. Users should be able to look at your description and get a good understanding on how and when to use the program, not a bunch of corporate-speak about 'our custom tunneling software'. Also, I can't tell if this is open source or not. You should probably make that clear. And you should make clear how this tunneling software is better than the competition. (And there is [a lot of competition](https://github.com/anderspitman/awesome-tunneling).)

**Comment by theofficialgman** [comment]
also don't lie about the compressed folder format. what you uploaded is not a zip file. it is a 7z file.
```
Playit.gg.zip: 7-zip archive data, version 0.4
```

**Comment by BITIW** [comment]
I’m sorry about that. My raspbian compressed into 7z, and i saw that needed
zip, so i renamed it (it didn’t broke archive)

Пт, 18 авг. 2023 г. в 22:39, theofficialgman ***@***.***>:

**Comment by theofficialgman** [comment]
> I’m sorry about that. My raspbian compressed into 7z, and i saw that needed zip, so i renamed it (it didn’t broke archive) 

thats where you are wrong. 7z and zip are totally different archival formats and are not compatible with one another. by renaming it to an incompatible format you did break the archive. it cannot be extracted by the `zip` cli tool.

**Comment by theofficialgman** [comment]
closing as stale as changes were requested over two weeks ago. This issue can be re-opened if changes are implemented.
