### ISSUE TITLE
Neverball- Tilt-controlled puzzle platformer. Roll the ball, navigate obstacles, collect coins, and conquer challenging levels--PACKAGE

### ISSUE THREAD

**Issue by SpyrosTheBoss** [Botspot/pi-apps#2431]
### What is the name of the app?

Neveball

### (Optional) Where is the app hosted?

https://neverball.org/index.php

https://github.com/Neverball

### About the app

Tilt, roll, and navigate puzzles. Collect coins, conquer levels in this open-source physics platformer

### Upload file or Add PR Link

[Neverball.zip](https://github.com/Botspot/pi-apps/files/12411965/Neverball.zip)

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi-Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by SpyrosTheBoss** [comment]
@Botspot  hello? Is anyone here? It's been like 2 days

**Comment by theofficialgman** [comment]
I'll copy/paste/paraphrase what Botspot responded to a similar app request:

Thank you for taking the time to submit this. I hope you found the process straightforward. If anything was confusing for you, please let us know.
Just as a reminder, Pi-Apps is not a GUI for apt. Other programs already do that nicely. So this is unlikely to be added unless there are other very similar puzzle/action games already on pi-apps. I suggest reading the note about package apps on [the app eligibility rubric.](https://github.com/Botspot/pi-apps/issues/185)

There are no other games in this genre on pi-apps currently (refer to above rubric) and none of the current pi-apps games are package apps.
