### ISSUE TITLE
app request: Minecraft Pi Server (fixed)

### ISSUE THREAD

**Issue by kidmakesreal** [Botspot/pi-apps#2434]
### What is the name of the app?

Minecraft Pi Server

### About the app

a simple minecraft pi server install (sorry i forgot to include the description last time)

### Upload file or Add PR Link

[Minecraft Pi Server.zip](https://github.com/Botspot/pi-apps/files/12438669/Minecraft.Pi.Server.zip)

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [ ] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi-Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by kidmakesreal** [comment]
Sorry use this file instead
[Minecraft Pi Server.zip](https://github.com/Botspot/pi-apps/files/12439378/Minecraft.Pi.Server.zip)

**Comment by kidmakesreal** [comment]
sorry if i did it wrong im new to github

**Comment by kidmakesreal** [comment]
Sorry use this file instead:
[Minecraft Pi Server.zip](https://github.com/Botspot/pi-apps/files/12440907/Minecraft.Pi.Server.zip)

**Comment by theofficialgman** [comment]
I suggest you look at the other scripts if you want to make a single install file that satisfies both architectures
```
#download server
if $(uname -m | grep '64'); then
```
this is very bad. here is an example of what I am talking about 
https://github.com/Botspot/pi-apps/blob/bd65fa664acd5390c67c38bb7a6d15a73776e806/apps/Boxy%20SVG/install#L24-L30

also, please read our wiki on creating an app as there are a multitude of issues in your scripts and I think reading our documentation will help you correct them: https://pi-apps.io/wiki/development/Creating-an-app/

**Comment by kidmakesreal** [comment]
> I suggest you look at the other scripts if you want to make a single install file that satisfies both architectures
> 
> ```
> #download server
> if $(uname -m | grep '64'); then
> ```
> 
> this is very bad. here is an example of what I am talking about
> 
> https://github.com/Botspot/pi-apps/blob/bd65fa664acd5390c67c38bb7a6d15a73776e806/apps/Boxy%20SVG/install#L24-L30
> 
> 
> also you don't seem to understand the concept of if/else statements. you placed the `fi` at the end of the file, meaning that only the "32bit" install would get the `.desktop` file
> also, please read our wiki on creating an app as there are a multitude of issues in your scripts and I think reading our documentation will help you correct them: https://pi-apps.io/wiki/development/Creating-an-app/

Sorry about that i did what you said here is the new file 
[Minecraft Pi Server.zip](https://github.com/Botspot/pi-apps/files/12445468/Minecraft.Pi.Server.zip)
