### ISSUE TITLE
whatsapp 

### ISSUE THREAD

**Issue by 0d0a** [Botspot/pi-apps#2439]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi-Apps and the issue is still not fixed. [How to update Pi-Apps?](https://pi-apps.io/wiki/getting-started/updating-pi-apps/)
- [X] IMPORTANT: I promise to respond to comments on this issue and write a good bug report https://www.softwaretestinghelp.com/how-to-write-good-bug-report/

### What happened?

whatsapp not launching after installation

### Description

Menu -> Internet -> Whatsapp Web greyad out.
/opt/WhatsApp/WhatsApp
bash: /opt/WhatsApp/WhatsApp: Permission denied

### What are your system specs (run the following command in your terminal)?

```bash
OS: Debian GNU/Linux 11 (bullseye)
OS architecture: 64-bit
Last updated Pi-Apps on: 09/03/2023
Latest Pi-Apps version: 09/05/2023
Kernel: aarch64 6.1.21-v8+
Device model: Raspberry Pi 3 Model B Plus Rev 1.3 
Cpu name: Cortex-A53
Ram size: .90 GB
Raspberry Pi OS image version: 2023-05-03
Language: en_US.UTF-8
```

### (Recommended) Error log? Terminal output? Debug messages?

```bash
bash: /opt/WhatsApp/WhatsApp: Permission denied
```

**Comment by 0d0a** [comment]
Solved by adding boot_delay=20 and boot_delay_ms=0 to /boot/config.txt.the white rider(Het leuke van ... is weten op reis te zijn; geboren te Vught, opgegroeid in Amsterdam en gezworven door Eurazië…)On 5 Sep 2023, at 17:13, theofficialgman ***@***.***> wrote:﻿
this is controlled by upstream @cycool29

**Comment by GTR2Fan** [comment]
That doesn't fix it for me. I guess I'll just have to wait for @cycool29 to come up with a fix.

**Comment by Rak1ta** [comment]
@cycool29 in version 21 there is something wrong with folder permissions.
![image](https://github.com/Botspot/pi-apps/assets/88277343/2cd1530c-011e-47cd-8c48-62913d727823)

**Comment by hyppyp** [comment]
Folder permissions: 
sudo chmod 777 -R /opt/WhatsApp
did the job for me
