### ISSUE TITLE
Adding a symbolic link for OpenSCAD

### ISSUE THREAD

**Issue by Joe-Lay** [Botspot/pi-apps#2441]
### Cool ideas?

I was wondering if it might be a good idea to add a line of code in the OpenSCAD install files that creates a symbolic link in /bin to the OpenSCAD appimage so that one may have a OpenSCAD executable. I find it much easier to type "openscad" than "/opt/OpenSCAD.AppImage" to launch the application. (And we all know speed is key ;) It also helps when using FreeCAD because freecad just looks inside /bin for the command, as far as I am aware of. At the very least, it doesn't detect the Pi-Apps install of OpenSCAD. But it does detect it when I run the command,
`sudo ln -s /opt/OpenSCAD.AppImage openscad`
And there lies the jist of my post. I think it could be useful if we added that one line of code to the install files.

**Comment by Botspot** [comment]
Thank you for the suggestion! Please feel free to suggest other small changes like this.

I've implemented your suggestion now with commit https://github.com/Botspot/pi-apps/commit/4eac0668ef632fa015ccb5b13ea62b3a0db894d1. After you update Pi-Apps, a `/usr/local/bin/openscad` command will be created.
