### ISSUE TITLE
Zoom Launch Fails

### ISSUE THREAD

**Issue by tazdon** [Botspot/pi-apps#2442]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi-Apps and the issue is still not fixed. [How to update Pi-Apps?](https://pi-apps.io/wiki/getting-started/updating-pi-apps/)
- [X] IMPORTANT: I promise to respond to comments on this issue and write a good bug report https://www.softwaretestinghelp.com/how-to-write-good-bug-report/

### What happened?

Zoom fails to lauch after Box86 uppdate

### Description
```
Launching Zoom.
Box86 with Dynarec v0.3.3 daef5cbd built on Sep  4 2023 06:36:24
zoom started.
Client: Breakpad is using Single Client Mode! client fd = -1
Error: PltResolver: Symbol XGetXCBConnection(ver 0: XGetXCBConnection) not found, cannot apply R_386_JMP_SLOT 0xebaa9738 (0xeb95f6c6) in libQt5XcbQpa.so.5
Zoom exited. Close this terminal to exit
```

### What are your system specs (run the following command in your terminal)?

```bash
pi@raspberrypi:~ $ ~/pi-apps/api get_device_info
OS: Raspbian GNU/Linux 11 (bullseye)
OS architecture: 32-bit
Last updated Pi-Apps on: 09/08/2023
Latest Pi-Apps version: 09/08/2023
Kernel: aarch64 6.1.45-v8+
Device model: Raspberry Pi 4 Model B Rev 1.1 
Cpu name: Cortex-A72
Ram size: 3.79 GB
Raspberry Pi OS image version: 2021-10-30
Language: en_US.UTF-8
```

**Comment by theofficialgman** [comment]
> Zoom fails to lauch after Box86 uppdate

if a box86 update broke zoom where it previously worked, report it upstream at box86 repo and not here

**Comment by Botspot** [comment]
Tagging @ptitseb

**Comment by ptitSeb** [comment]
That's a new symbol to wrap on box86. I'll do that soon-ish.

**Comment by ptitSeb** [comment]
Mmmm, this function is wrapped already, as part of the `libX11-xcb.so.1` wrapping (for many years). You should check if this library is correctly installed for the `armhf` architecture.

**Comment by le-doux** [comment]
just want to chime in to add that I'm also experiencing this issue

I just installed zoom from pi-apps today on a new raspberry pi OS install so afaik everything *should* be up-to-date

sorry if this is a basic question, but how would I go about checking if the xcb library is correctly installed on my system?

**Comment by tazdon** [comment]
I have reinstalled both box86 and zoom from pi-apps an, like le-doux, i assume everything is up-to-date.   I am still getting the following error when trying to launch Zoom:

Box86 with Dynarec v0.3.3 bc166ae3 built on Sep 27 2023 06:33:18
zoom started.
Client: Breakpad is using Single Client Mode! client fd = -1
Error: PltResolver: Symbol XGetXCBConnection(ver 0: XGetXCBConnection) not found, cannot apply R_386_JMP_SLOT 0xebc84738 (0xebb3a6c6) in libQt5XcbQpa.so.5
Zoom exited. Close this terminal to exit

**Comment by tazdon** [comment]
did not mean to close the issue

**Comment by Botspot** [comment]
@ptitSeb, would you be willing to test Zoom on PiOS 32-bit with your latest box86 version? I can try to test it myself at some point too.

**Comment by ptitSeb** [comment]
Ok, I'll check later. It's probably a missing dependancy in one of the wrapped lib.

**Comment by theofficialgman** [comment]
@tazdon can this issue be closed? I think it has long been resolved.
