### ISSUE TITLE
Add the open-source spreadsheet program Gnumeric

### ISSUE THREAD

**Issue by PeterGamma** [Botspot/pi-apps#2446]
### Cool ideas?

Hardly anyone uses LibreOffice on the PinePhone. Users recommended to use Abiword and Gnumeric instead. It is great for smaller 5 inch screens. Abiword is in th Pi-Apps store, but not Gnumeric. Add Gnumeric to make it complete

**Comment by theofficialgman** [comment]
This is an "app suggestion"
Please open a new issue with the proper template.
