### ISSUE TITLE
Gnumeric

### ISSUE THREAD

**Issue by PeterGamma** [Botspot/pi-apps#2447]
### What is the name of the app?

Gnumeric

### (Optional) Where is the app hosted?

http://www.gnumeric.org/

### About the app

For the Pinephone Abiword and Gnumeric is recommended instead of LibreOffice. Abword is in the Pi App list, but not Gnumeric. Gnumeric runs on the Raspberry Pi. It can be downloaded and installed in the leepspvideo KDE plasma build 4 discover store and works.

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have read the app eligibilty rubric https://github.com/Botspot/pi-apps/issues/185 and confirmed this app is suitable for addition in Pi-Apps.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi-Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by Botspot** [comment]
Thank you for your app suggestion! Don't feel bad about opening the wrong type of issue. Other people do it somewhat frequently too.

I have just added this app to Pi-Appa in such a way that installing it will simply install the `gnuplot` package. You can take a look at the changes here: https://github.com/Botspot/pi-apps/commit/01a94e6677199e5d601bab9c62ca1146dc7a0ae8

**Comment by PeterGamma** [comment]
Thank you very much, Botspot, this is great.

I recently struggeled to install LibreOffice on the PinePhone:

https://forum.pine64.org/showthread.php?tid=16614

Which was hard work, since I usually don’t code, as you can see on my GITHUB page. After I managed, alaraajavamma from the Pin64 suggested to use Abiword and Gnumeric instead of LibreOffice on the PinePhone, which works much better. Now we have Gnumeric and Abiword in the Pi-Apps store, which is great. 

I tried today to install the Pi-Apps store, Abiword & Gnumeric on a Raspberry Pi zero w2, but unfortunately I failed, which is documented here:

https://petergamma.org/issues-we-have-with-the-raspberry-pi-zero-2-w/

which might be due to the fact that I usually don’t code. Leepspvideo suggested to install the  Pi-Apps store on a Pi 4, and then use this SD card for the zero 2 w. I tried this, but unfortunately I failed also  with this command:

wget -qO- https://raw.githubusercontent.com/Botspot/pi-apps/master/install | bash

After hitting enter, my Pi’s paused for around 30 sec. , and the prompt comes back, but  Pi-Apps is not installed. What might be wrong?

**Comment by Botspot** [comment]
> I tried today to install the Pi-Apps store, Abiword & Gnumeric on a Raspberry Pi zero w2, but unfortunately I failed, which is documented here:
> 
> https://petergamma.org/issues-we-have-with-the-raspberry-pi-zero-2-w/
> 
> which might be due to the fact that I usually don’t code. Leepspvideo suggested to install the Pi-Apps store on a Pi 4, and then use this SD card for the zero 2 w. I tried this, but unfortunately I failed also with this command:

@PeterGamma, Thank you for the reply. I went ahead and reviewed your website, and something seems to be clearly wrong with your current Pi's setup. It's like you have no internet connection, or some other apt-based error. You mentioned several things "failing" to install, but never mentioned what the failure was. With Linux, it usually tells you EXACTLY what went wrong. But on your website and in this github issue, all you have said is "it failed". Please copy and paste all the output from running this command in a terminal on your raspberry pi:
```
sudo apt update
sudo apt install yad
```
To copy the text, just select it with your mouse, then right-click to select "Copy". then login to github.com on your Pi, navigate to this issue, and paste the output into here.
