### ISSUE TITLE
Spiral Knights on Raspberry Pi

### ISSUE THREAD

**Issue by SirDank** [Botspot/pi-apps#2448]
### What is the name of the app?

Spiral Knights

### (Optional) Where is the app hosted?

https://www.spiralknights.com/download.xhtml / http://store.steampowered.com/app/99900

### About the app

- Old game with a small community
- Can be further optimised by using [KnightLauncher](https://github.com/lucasluqui/KnightLauncher) with optimisation mods some of which are found [here](https://github.com/SirDank/Spiral-Knights-Modpack)

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have read the app eligibilty rubric https://github.com/Botspot/pi-apps/issues/185 and confirmed this app is suitable for addition in Pi-Apps.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi-Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by Botspot** [comment]
Have you specifically verified that this runs well on the Raspberry Pi platform?

**Comment by theofficialgman** [comment]
@SirDank how are you running this on arm32/arm64 Linux.

> I have confirmed that this app can run on Raspberry Pi.

By checking that box you have confirmed that it can be installed and runs. Please elaborate otherwise this will be closed. App requests are not porting requests.

**Comment by SirDank** [comment]
@Botspot @theofficialgman 

Yo mb, let me clarify. I have tested it on linux system but haven't gotten it to work and I'm sure that its probably me that's doing something wrong.

But I can verify that it runs on arm64 (Android/iOS [WIP]) via [PojavLauncher](https://github.com/PojavLauncherTeam/PojavLauncher) using the KnightInstaller.jar file found here [android](https://github.com/PojavLauncherTeam/KnightInstaller) / [ios](https://github.com/SirDank/KnightInstaller_iOS)

**Comment by Botspot** [comment]
Closing this issue until you can get it running on the raspberry pi, or until you can find a working tutorial that shows this game running on the raspberry pi.
