### ISSUE TITLE
FF Multi Converter does not create a shortcut

### ISSUE THREAD

**Issue by Rak1ta** [Botspot/pi-apps#2464]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi-Apps and the issue is still not fixed. [How to update Pi-Apps?](https://pi-apps.io/wiki/getting-started/updating-pi-apps/)
- [X] IMPORTANT: I promise to respond to comments on this issue and write a good bug report https://www.softwaretestinghelp.com/how-to-write-good-bug-report/

### What happened?

The script does not install the required files

### Description

The [script](https://github.com/ilstam/FF-Multi-Converter/blob/c47d47ab7f66a1973b1314ef531de2fb444c2fe6/setup.py#L7) does not install the necessary files in _/usr/local/share_

![image](https://github.com/Botspot/pi-apps/assets/88277343/50d42060-accc-4b65-b87d-1facbcb7b026)

I wanted to see if there were any errors during the installation, so I did it manually. But it didn’t become clearer to me.

### What are your system specs (run the following command in your terminal)?

```bash
OS: Debian GNU/Linux 12 (bookworm)
OS architecture: 64-bit
Last updated Pi-Apps on: 10/12/2023
Latest Pi-Apps version: 10/13/2023
Kernel: aarch64 6.1.0-rpi4-rpi-v8
Device model: Raspberry Pi 4 Model B Rev 1.2 
Cpu name: Cortex-A72
Ram size: 3.61 GB
Raspberry Pi OS image version: 2023-10-10
Language: en_US.UTF-8
```

### (Recommended) Error log? Terminal output? Debug messages?

```bash
pi@raspberrypi:~/FF-Multi-Converter $ sudo python3 setup.py install
/usr/lib/python3/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/usr/lib/python3/dist-packages/setuptools/command/easy_install.py:146: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/usr/lib/python3/dist-packages/setuptools/dist.py:159: UserWarning: newlines not allowed and will break in the future
  warnings.warn("newlines not allowed and will break in the future")
warning: no previously-included files found matching 'locale/*.qm'
warning: no previously-included files matching '*.pyc' found under directory 'ffmulticonverter'
zip_safe flag not set; analyzing archive contents...
ffmulticonverter.__pycache__.utils.cpython-311: module references __file__
```

**Comment by theofficialgman** [comment]
Does it show up after a reboot? The code you linked seems to indicate it does install a . desktop file.

**Comment by Rak1ta** [comment]
@theofficialgman yes, I gave a link to install .desktop file. The program works, but there is no shortcut. Rebooting doesn't affect anything for me.

**Comment by Botspot** [comment]
I just installed FF Multi Converter and it shows up in Office instead of Accessories as the pi-apps description claims. @Rak1ta, do you see it in Office on your system?

**Comment by Botspot** [comment]
I've gone ahead and updated the description to say it can be launched from Office. If @Rak1ta replies to say the menu launcher is absent from the Office category, then I can re-open the issue.

As usual, my deepest thanks goes to those involved in relentlessly weeding out all bugs from Pi-Apps. I cannot do this alone as a busy engineering college student.

**Comment by Rak1ta** [comment]
@Botspot I'm missing a shortcut. It is not available as a .desktop file either.

**Comment by Botspot** [comment]
@Rak1ta, please run this command:
```
file /usr/local/share/applications/ffmulticonverter.desktop
```

**Comment by Botspot** [comment]
And this:
```
file /usr/local/share/applications
```

**Comment by theofficialgman** [comment]
I can reproduce the issue.  For some reason the binary is installed (`/usr/local/bin/ffmulticonverter`) but the `.desktop` file is nowhere to be found. 
Tested on Bookworm ARM64
The folder `/usr/local/share/applications` already existed on my system even, so it isn't like it failed to place the file there because the folder did not previously exist.

I'm not super familiar with python distutils but it has to do with that <https://docs.python.org/3.11/distutils/setupscript.html#installing-additional-files>. Everything looks good to me so idk whats wrong.

**Comment by Botspot** [comment]
Seems like Bookworm is the difference here. I'm still on Bullseye.

**Comment by theofficialgman** [comment]
yeah this is a setuptools bug.... not sure who it needs to be reported to. it is simply ignoring the `data_files` entirely. We know setup.py is deprecated but its not supposed to be broken...

**Comment by theofficialgman** [comment]
can also confirm the issue on ubuntu mantic (also on python 3.11). so this definitely seems like a regression from 3.9 -> 3.11 regarding setuptools

**Comment by theofficialgman** [comment]
@Botspot found the change and found the fix
python changed to installing to egg `/usr/local/lib/python3.11/dist-packages/ffmulticonverter-1.8.0-py3.11.egg/`

now you have to pass `--old-and-unmanageable` to have the old expected results
```
sudo python3 setup.py install --old-and-unmanageable
```
does that run on bullseye without an error? because I will add it to the script if bullseye does not care even if it does not use it

**Comment by Botspot** [comment]
> @Botspot found the change and found the fix python changed to installing `data_files` to egg `/usr/local/lib/python3.11/dist-packages/ffmulticonverter-1.8.0-py3.11.egg/`
> 
> now you have to pass `--old-and-unmanageable` to have the old expected results https://packaging.python.org/en/latest/guides/distributing-packages-using-setuptools/#data-files
> 
> ```
> sudo python3 setup.py install --old-and-unmanageable
> ```
> 
> does that run on bullseye without an error? because I will add it to the script if bullseye does not care even if it does not use it

No it fails.
```
Errors:
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: option --old-and-unmanageable not recognized

```

**Comment by Botspot** [comment]
Just to be clear, I changed line 8 in the install script to include this:
```
sudo python3 setup.py install --old-and-unmanageable
```

**Comment by theofficialgman** [comment]
Alright cool.
I'll have to add a checks for the appropriate version when that flag was added. And only add it when necessary.
Thanks
