### ISSUE TITLE
App Request: Thorium (Chromium fork)

### ISSUE THREAD

**Issue by musicalskele** [Botspot/pi-apps#2467]
### What is the name of the app?

Thorium

### (Optional) Where is the app hosted?

main website is at https://thorium.rocks/
main repo is hosted at https://github.com/Alex313031/thorium
raspberry-pi builds hosted at https://github.com/Alex313031/Thorium-Raspi

### About the app

Thorium, a Chromium-based browser, claims to offer significant speed improvements ranging from 8% to 38% when compared to the standard Chromium browser. While I haven't conducted comprehensive testing, I have observed enhanced performance on my Raspberry Pi in _some_ areas. Perhaps it just needs tweaking.

One notable advantage of Thorium is the inclusion of several additional features not found in the regular Chromium browser. You can check these changes on the bottom of the this text which will have several links including a list of patches. 

I ran a benchmark test using the default Chromium application that comes with Raspberry Pi OS (64-bit) on my Raspberry Pi 4 Rev 1.1, which operates at 2.0GHz with 2 GB of memory and a 720p resolution over VNC. Here are the benchmark results:

![benchmark-chromium-summary](https://github.com/Botspot/pi-apps/assets/36569350/5fc028b4-dc52-4fad-b3eb-42f121cf3953)
![benchmarkchromium-detailed](https://github.com/Botspot/pi-apps/assets/36569350/c903f300-6589-4de0-8d2d-883acc30a842)

I repeated the same benchmark using Thorium on the same OS and device, and here are the results for Thorium:

![benchmark-thorium-summary](https://github.com/Botspot/pi-apps/assets/36569350/5ad56b74-cbde-4b04-a679-332b32e8008b)
![benchmark-thorium-detailed](https://github.com/Botspot/pi-apps/assets/36569350/dd3864ee-45ba-4774-99b2-5cf2b73ed42e)

A few things to note is the total memory usage was approximately 780MB on average with the default Chromium browser and averaged around 850MB with Thorium. Weirdly, Thorium had a quicker startup time and felt more responsive. It appeared to put less strain on the CPU, although I didn't measure this aspect.

While Thorium may have some areas where it performs slightly slower, I think it has some potential with the features it's got. As I have said perhaps the issue is that it hasn't been tweaked for the raspberry pi.

Unfortunately only supports arm64.
More details about the performance here:
https://thorium.rocks/performance
More details about the optimizations used here:
https://thorium.rocks/optimizations
List of all patches here:
https://github.com/Alex313031/Thorium/blob/main/infra/PATCHES.md

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have read the app eligibilty rubric https://github.com/Botspot/pi-apps/issues/185 and confirmed this app is suitable for addition in Pi-Apps.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi-Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by Botspot** [comment]
VNC could be messing up your results. Browsers in particular will care about displaying to a real screen.

**Comment by theofficialgman** [comment]
I had a pretty lengthy response written to this but then my computer crashed for the first time in forever so you are going to get the sparknotes of it now...

Thorium (chromium fork) and Mercury (firefox fork) are from the same devs.
The benchmarking they do is highly contrived and not reproducible by independent third parties https://www.phoronix.com/review/mercury-firefox-perf

I would consider these projects a cash grab at best and detrimental to the upstream projects at worst. Contributing patches that actually have meaningful improvements to performance is much more valuable than "oh lets turn on compiler optimizations, vroom vroom". Believe it or not google and mozilla do test for performance and have their own (usually very good and valid) reasons for using the optimization flags that they do use when they do use them.

Sorry but the kid that is behind those projects (just a one man show) is just 22 https://github.com/Alex313031 and they can't reasonably keep up with the security vulnerabilities that only increase in volume by the day.

TLDR: I'm opposed to this in pi-apps

**Comment by theofficialgman** [comment]
Brodie Robertson just make a video going over all of the concerns I brought up and more https://youtu.be/tR-dhc_SWBk
