### ISSUE TITLE
App Submission: OpenStream Music (Uses scripts to install)

### ISSUE THREAD

**Issue by techguy16** [Botspot/pi-apps#2469]
### What is the name of the app?

OpenStream Music

### (Optional) Where is the app hosted?

https://github.com/openstreamorg/openstreammusic/

### About the app

It is a free and open source music streaming service that has no ads or accounts. It uses its own database or YouTube Music's if it doesn't have the song.

### Upload file or Add PR Link

[OpenStream Music.zip](https://github.com/Botspot/pi-apps/files/13078400/OpenStream.Music.zip)

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi-Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by Botspot** [comment]
Are there openstream servers providing cached music, or does this use something like youtube-dl or yt-dlp as the backend?
The reason I ask is because I once wrote a software like this called PiTunes - it was never finished it but it was a very similar idea.

**Comment by techguy16** [comment]
It uses ytdl (a node frontend for YouTube-DL)

**Comment by techguy16** [comment]
You could contribute some features from PiTunes if you wanted?

**Comment by Botspot** [comment]
> You could contribute some features from PiTunes if you wanted?

PiTunes is all a bash script. Most of the code was to handle a playlist behavior with random ordering, editing, automatically splitting songs based on timestamps found in the description, and allowing manual trimming of each audio segment. It also had a simple scripting language for importing other people's playlists. I doubt any of that could transfer over to a project written in node.

**Comment by techguy16** [comment]
I was only meaning suggestions. Are you merging or closing?

**Comment by theofficialgman** [comment]
> It is a free and open source music streaming service that has no ads or accounts. It uses its own database or YouTube Music's if it doesn't have the song.

To me this sounds like a GUI frontend for piracy. You need to explain what is included in your database, where you steam those files from, and what license you have for that media where applicable.

**Comment by techguy16** [comment]
You cannot download anything.

**Comment by theofficialgman** [comment]
> You cannot download anything. They come directly from Google's servers.
> 
> What's your opinion on Youtubuddy then? It's the same concept.

You did not define what the "own database" is. That is what I was asking about.

Streaming from YouTube using their API is already proven legal (in the US at least) and there isn't any debate about that. I was not asking about that part though.

**Comment by techguy16** [comment]
It's a json file with links to some mp3s.

**Comment by Botspot** [comment]
It seems that user techguy16 is giving us minimal information. (spoonfeeding)
It's okay. You're welcome to go in depth. We can handle it. @techguy16, please explain the full flow of information - like how the user picks songs, how they are served up, how the audio is downloaded, and from where, and if you have thought through legal implications like the situation youtube-dl had to undergo.

**Comment by techguy16** [comment]
The user can choose from the "database" JSON that we have (set to be removed soon) on the homepage or search YouTube Music.
It then searches YouTube Music for that song. After that YTDL-Core gets the mp3 url and streams it if the song is clicked. The audio cannot be downloaded from YT Music, so you can only play it.

**Comment by theofficialgman** [comment]
One thing I notice quickly is the ancient version of electron used.
This is very dangerous given that your application loads images and is vulnerable to the webp CVE (and many others)
https://github.com/openstreamorg/openstreammusic/blob/b7a8a108e1d684cb2670da4162358f062539e5a5/desktop/package-lock.json#L4164-L4174

Please use one of the actively supported stable electron releases https://releases.electronjs.org/

**Comment by techguy16** [comment]
Hey @theofficialgman, in 1.3 I'm updating it to Electron 22 so I can still support Win7 but patch many bugs. 

And the bit about YouTube-DL and the legal stuff, it's not my problem. If the ytdl-core project dies, the Internet Archive it is.

**Comment by theofficialgman** [comment]
> Hey @theofficialgman, in 1.3 I'm updating it to Electron 22 so I can still support Win7 but patch many security issues. (Commit [f23ea5a](https://github.com/openstreamorg/openstreammusic/commit/f23ea5a38a8678c174bf6c8dc55359e78ea47bf0))

22 is also EOL as of 2+ weeks ago so that isn't enough. People have had years of extra time to move off of that platform. Sorry it's time to let that OS support die.

If you want to support windows 7, don't use a browser as your GUI toolkit.

**Comment by techguy16** [comment]
Supply a separate build for Win7?

**Comment by Botspot** [comment]
> Supply a separate build for Win7?

That is up to you, @techguy16.

**Comment by techguy16** [comment]
What I'm now doing:
- Windows 7&8 and 10&11 have a separate build (`npm run install-app-deps-win7` for Windows 7 and `npm run install-app-deps` for 10&11)
- Linux uses the latest Electron version.

Please wait until 1.3 is release before merging (only if you are).

**Comment by techguy16** [comment]
*Updated to Version 1.3*

**Comment by theofficialgman** [comment]
> 
> `OpenStream Music/website`
> 
> ```
> https://openstreamorg.github.io
> ```

the linked website does not exist/work

**Comment by techguy16** [comment]
@theofficialgman it's the homepage for OpenStream, the organization that "owns" OpenStream Music.

**Comment by theofficialgman** [comment]
it is a very good and descriptive homepage if it is working as intended
<img width="941" alt="image" src="https://github.com/Botspot/pi-apps/assets/28281419/e433ee82-9276-46a0-8747-cb9644722a65">

**Comment by Botspot** [comment]
The site is working for me.

**Comment by Sussy-OS** [comment]
> it is a very good and descriptive homepage if it is working as intended <img alt="image" width="941" src="https://user-images.githubusercontent.com/28281419/277455921-e433ee82-9276-46a0-8747-cb9644722a65.png">

It works for me as well.

**Comment by theofficialgman** [comment]
manually changed to http
got some info

<img width="768" alt="image" src="https://github.com/Botspot/pi-apps/assets/28281419/0c4ead58-4b53-4e1d-a4f0-d5cc6df8658f">

currently on university connection.... I doubt it was manually blocked. Something on their scraper must have found something phishy on the webpage. Was this domain owned before by something else maybe?

**Comment by Botspot** [comment]
@techguy16, I have given OpenStream a try. It looks good in some ways. As a test user, I found some issues and opened some support issues on your github. https://github.com/openstreamorg/openstreammusic/issues

After my review, I concluded that currently OpenStream seems to still be in alpha stage - with significant issues present. My recommendation is to get the app to a high level of "functional" before it is added to the largest ARM Linux app store.

**Comment by techguy16** [comment]
@Botspot, 2.0 is on the cards, which is a major revamp and fixes lots. 
It is designed for Pi 4's and up, even though it runs on my Pi 3B+. 
Thank you for your time and trying OpenStream Music. I see some of the issues are quick fixes, so I'll get onto them pretty soon.

**Comment by Botspot** [comment]
@techguy16, have you  dropped work on this?

**Comment by techguy16** [comment]
No, I've just got distracted with other random things 😀

**Comment by Botspot** [comment]
Should I just go ahead and close this issue then?

**Comment by techguy16** [comment]
For now, I'll get back eventually (hopefully...)
