### ISSUE TITLE
Discord right click context menu does not work

### ISSUE THREAD

**Issue by YodaLightsabr** [Botspot/pi-apps#247]
The right click context menu in Discord shows Copy, Paste, and Cut, rather than copy message link, copy ID, etc.

**Comment by Botspot** [comment]
Let's move this issue to the Discord App's repository.

https://github.com/SpacingBat3/electron-discord-webapp/issues/new

**Comment by YodaLightsabr** [comment]
> Let's move this issue to the Discord App's repository.
> 
> https://github.com/SpacingBat3/electron-discord-webapp/issues/new

But this isn't the official Discord client, is it?

**Comment by Botspot** [comment]
> > Let's move this issue to the Discord App's repository.
> > https://github.com/SpacingBat3/electron-discord-webapp/issues/new
> 
> But this isn't the official Discord client, is it?

The Pi-Apps version of Discord installs that Discord Electron app. No, it's not possible to install Discord's official desktop client.
