### ISSUE TITLE
pi-apps will not install apps with urxvt

### ISSUE THREAD

**Issue by Silent-Hunter** [Botspot/pi-apps#2471]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi-Apps and the issue is still not fixed. [How to update Pi-Apps?](https://pi-apps.io/wiki/getting-started/updating-pi-apps/)
- [X] IMPORTANT: I promise to respond to comments on this issue and write a good bug report https://www.softwaretestinghelp.com/how-to-write-good-bug-report/

### What happened?

pi-apps will not install apps with urxvt.

### Description

When I try to install any app, pi-apps opens a window containing the text below:
```Unable to open a terminal.
Debug output below.
Default x-terminal-emulator: urxvt
[91mFailed to locate any terminal emulators!!![39m
```

I was able to mitigate it by adding urxvt after line 37 of `terminal-run`, and then adding this after line 97:
```elif [ "$choice" == xterm ];then
  xterm -e bash -c "$commands" &
```

### What are your system specs (run the following command in your terminal)?

```bash
OS: Debian GNU/Linux 11 (bullseye)
OS architecture: 64-bit
Last updated Pi-Apps on: 10/22/2023
Latest Pi-Apps version: 10/22/2023
Kernel: aarch64 6.1.21-v8+
Device model: Raspberry Pi 4 Model B Rev 1.5 
Cpu name: Cortex-A72
Ram size: 7.63 GB
Raspberry Pi OS image version: 2022-09-22
Language: en_US.UTF-8
```

### (Recommended) Error log? Terminal output? Debug messages?

```bash
🭊🬹🬹🬹🬿                                                          
 🭇🬭🬭🬎🬭🬭🬭🬎🬭🬭🬼                                                       
 🮉  ▄ ▄ ▄  ▋   █▀▀🭍 ▄                                              
 🮉  ▄ ▄ ▄  ▋   █▄▄🭞 ▄ ▄▄ 🭂▀▀█ █▀▀🭍 █▀▀🭍 🭂🬰🬰🬰                       
 🮉  ▄ ▄ ▄  ▋   █    █    🭓▄▄█ █▄▄🭞 █▄▄🭞 ▄▄▄🭞                       
 🭦🭏🬭🬭🬭🬭🬭🬭🬭🭄🭛                  █    █                               
                                                                   
                                                                   
pipe is /tmp/tmp.FjuiClns4i
detailspid is /tmp/tmp.fizqJtilJZ
tail: warning: --retry only effective for the initial open

Updater mode: set-status

Checking for online changes... Done
Timestamps match.
Reading list file for ''...
Scanning apps... Done
Scanning files... Done
cat: /home/kavus/pi-apps/data/update-status/updatable-apps: No such file or directory
YAD_XID is 0x2800003
Timestamps match.
Reading list file for 'Games'...
YAD_XID is 0x2800003
Failed to locate any terminal emulators!!!
```

**Comment by Botspot** [comment]
Do you have any terminals other than urxvt installed?

**Comment by Silent-Hunter** [comment]
No I don't, it's the only one I use. I can install another to help test if need be.

**Comment by Botspot** [comment]
> I can install another to help test if need be.

The list of supported terminals in the `terminal-run` script are treated as a fallback: if your preferred terminal (as chosen by `x-terminal-emulator`) is not in the list, then terminal-run will check if any other supported terminal is installed.

In other words, you are encountering this problem because you have uninstalled all other terminal emulators. If you had a supported terminal emulator installed, then `terminal-run` would use that one.
I will look into adding urxvt to terminal-run properly.

**Comment by Botspot** [comment]
I have added urxvt to terminal-run in commit https://github.com/Botspot/pi-apps/commit/8e2f2bb3bc10a18cfc43616b717207468fc5c89a.

Please update pi-apps manually by running `~/pi-apps/updater cli-yes`. Then once that is done, you should be able to use pi-apps normally with your choice of terminal.

Thanks again for taking the time to reach out for help on this issue! Your issue report has made pi-apps just a little bit better for everyone. :)

**Comment by Sussy-OS** [comment]
> I have added urxvt to terminal-run in commit [8e2f2bb](https://github.com/Botspot/pi-apps/commit/8e2f2bb3bc10a18cfc43616b717207468fc5c89a).
> 
> Please update pi-apps manually by running `~/pi-apps/updater cli-yes`. Then once that is done, you should be able to use pi-apps normally with your choice of terminal.
> 
> Thanks again for taking the time to reach out for help on this issue! Your issue report has made pi-apps just a little bit better for everyone. :)

When updating via GUI, it provides an error. The error does not cause any problem, but it may throw some users off.

**Comment by Sussy-OS** [comment]
> > When updating via GUI, it provides an error. The error does not cause any problem, but it may throw some users off.
> 
> What do you mean? What error? Did you see an error when updating terminal-run on your system, @Sussy-OS?

Yes, I did. I'm not sure exactly what it said, but I'll downgrade pi-apps and try again so I can get the error.

**Comment by Sussy-OS** [comment]
Unable to open a terminal.
Debug output below.
Default x-terminal-emulator: lxterminal
Using lxterminal


![image](https://github.com/Botspot/pi-apps/assets/98842253/ad37e3c5-a16a-47bf-bd41-78d7ee9111ad)

**Comment by Sussy-OS** [comment]
Here is the actual issue: 

```
/home/james/pi-apps/etc/terminal-run: line 124: syntax error near unexpected token `do'
/home/james/pi-apps/etc/terminal-run: line 124: `/${terminalrun_pid} ];do'
```

**Comment by Sussy-OS** [comment]
I'm sure that line is intended, it's just causing an error for me.

**Comment by Silent-Hunter** [comment]
> Thanks again for taking the time to reach out for help on this issue! Your issue report has made pi-apps just a little bit better for everyone. :)

Thank _you_ for fixing the issue!

**Comment by Botspot** [comment]
> Here is the actual issue:
> 
> ```
> /home/james/pi-apps/etc/terminal-run: line 124: syntax error near unexpected token `do'
> /home/james/pi-apps/etc/terminal-run: line 124: `/${terminalrun_pid} ];do'
> ```

I know what happened. This can happen when a running script gets updated while it is running. Bash can lose track of where it was and get confused when the next lines of the file do not match what it was expecting. In the new commit https://github.com/Botspot/pi-apps/commit/f1b643bdabbd54a190d98738deac86195d2a1bb5, I have encased the entire terminal-run script in `{}` characters to force bash to read the whole file on startup. Even one-time errors are important. Thanks for reporting, @Sussy-OS.

**Comment by Sussy-OS** [comment]
> > Here is the actual issue:
> > ```
> > /home/james/pi-apps/etc/terminal-run: line 124: syntax error near unexpected token `do'
> > /home/james/pi-apps/etc/terminal-run: line 124: `/${terminalrun_pid} ];do'
> > ```
> 
> I know what happened. This can happen when a running script gets updated while it is running. Bash can lose track of where it was and get confused when the next lines of the file do not match what it was expecting. In the new commit [f1b643b](https://github.com/Botspot/pi-apps/commit/f1b643bdabbd54a190d98738deac86195d2a1bb5), I have encased the entire terminal-run script in `{}` characters to force bash to read the whole file on startup. Even one-time errors are important. Thanks for reporting, @Sussy-OS.

Oh, okay. No problem.
