### ISSUE TITLE
Error installing Box86

### ISSUE THREAD

**Issue by edbernard** [Botspot/pi-apps#2475]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi-Apps and the issue is still not fixed. [How to update Pi-Apps?](https://pi-apps.io/wiki/getting-started/updating-pi-apps/)
- [X] IMPORTANT: I promise to respond to comments on this issue and write a good bug report https://www.softwaretestinghelp.com/how-to-write-good-bug-report/

### What happened?

Box86 won't install

### Description

I simply clicked install on box86 and it immediately failed. I tried over and over, but it still did not work.

### What are your system specs (run the following command in your terminal)?

```bash
OS: Debian GNU/Linux 12 (bookworm)
OS architecture: 64-bit
Last updated Pi-Apps on: 10/29/2023
Latest Pi-Apps version: 10/29/2023
Kernel: aarch64 6.1.0-rpi4-rpi-2712
Device model: Raspberry Pi 5 Model B Rev 1.0
Cpu name: Cortex-A76
Ram size: 8.04 GB
Raspberry Pi OS image version: 2023-10-10
Language: en_US.UTF-8
```

### (Recommended) Error log? Terminal output? Debug messages?

```bash
🭊🬹🬹🬹🬿                                                          
 🭇🬭🬭🬎🬭🬭🬭🬎🬭🬭🬼                                                       
 🮉  ▄ ▄ ▄  ▋   █▀▀🭍 ▄                                              
 🮉  ▄ ▄ ▄  ▋   █▄▄🭞 ▄ ▄▄ 🭂▀▀█ █▀▀🭍 █▀▀🭍 🭂🬰🬰🬰                       
 🮉  ▄ ▄ ▄  ▋   █    █    🭓▄▄█ █▄▄🭞 █▄▄🭞 ▄▄▄🭞                       
 🭦🭏🬭🬭🬭🬭🬭🬭🬭🭄🭛                  █    █                               
                                                                   
                                                                   
tail: warning: --retry only effective for the initial open
Installing Box86...

User error (reporting allowed): 16K pagesize not supported on box86. Check if your system supports running 32bit ARM binaries and open an issue on Box86 GitHub if it can.

Failed to install Box86!
◢◣Need help? Copy the ENTIRE terminal output or take a screenshot.
Please ask on Github: https://github.com/Botspot/pi-apps/issues/new/choose
Or on Discord: https://discord.gg/RXSTvaUvuu
```

**Comment by theofficialgman** [comment]
> I simply clicked install on box86 and it immediately failed. I tried over and over, but it still did not work.

What part of the custom error message did you not understand? Trying over and over would never work. It informs you of the issue, and then suggests that you open an issue as the Box86 github.

Mind you this custom message was written before the Pi5 was announced and at that point the only known consumer devices using 16K PageSize kernels were Apple Silicon which cannot run 32bit binaries at all (hardware incompatible).

**Comment by edbernard** [comment]
Thank you for your help, I thought that the error meant that there was an issue with the app, and to fix it, I completely wiped the app and tried again. Thank you for your help, I found a work-around by manually building it myself.

**Comment by theofficialgman** [comment]
> Thank you for your help, I thought that the error meant that there was an issue with the app, and to fix it, I completely wiped the app and tried again. Thank you for your help, I found a work-around by manually building it myself.

Box86 will not function properly on 16K pagesize kernels. the dynarec and translation layers are not currently written for it
