### ISSUE TITLE
Your system is unsupported - SparkyLinux 7.1 RC1

### ISSUE THREAD

**Issue by RoonMoonlight** [Botspot/pi-apps#2479]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi-Apps and the issue is still not fixed. [How to update Pi-Apps?](https://pi-apps.io/wiki/getting-started/updating-pi-apps/)
- [X] IMPORTANT: I promise to respond to comments on this issue and write a good bug report https://www.softwaretestinghelp.com/how-to-write-good-bug-report/

### What happened?

Although it fully supports feature from Raspberry Pi OS, Pi-Apps thinks that the system is unsupported and displays warning message.

### Description

SparkyLinux recently added support for Raspberry Pi, based on Raspberry Pi OS with SparkyLinux's own features. The latest version is [7.1 RC1](https://sparkylinux.org/sparky-7-1-rc1-armhf-arm64/), based on Raspberry Pi OS Lite with Sparky feature installed. Although it completely supports feature that is used by Pi-Apps, the app things that the system is broken and displays warning that the system is unsupported on first run.

### What are your system specs (run the following command in your terminal)?

```bash
OS: SparkyLinux 7.1 (Orion-Belt)
OS architecture: 64-bit
Last updated Pi-Apps on: 11/12/2023
Latest Pi-Apps version: 11/12/2023
Kernel: aarch64 6.1.0-rpi6-rpi-v8
Device: Raspberry Pi 4 Model B Rev 1.5
SOC identifier: bcm2711
RAM size: 1.84 GB
Raspberry Pi OS image version:
Language: en_US.UTF-8
```

### (Recommended) Error log? Terminal output? Debug messages?

```bash
YOUR SYSTEM IS UNSUPPORTED:
Congratulations, Linux tinkerer, you broke your system. You have made your system a FrankenDebian.
This website explains your mistake in more detail: https://wiki.debian.org/DontBreakDebian
Your current reported release (N/a) should not be combined with other releases.
```

**Comment by theofficialgman** [comment]
You should go tell SparkyLinux that they need to fix their `lsb-release` package. it does not return any codename (see the "N/a" in your report. This is a requirement to query the information about a distribution.

Pi-Apps warning you of the problem and your distro should correct it.

**Comment by RoonMoonlight** [comment]
I got update from the SparkyLinux author Pawol Pavroo, they are not even going to fix it as well... What should I do now?

![Screenshot_20231114_220511_Telegram.jpg](https://github.com/Botspot/pi-apps/assets/25527589/b49ed635-ef32-406d-a4c6-a8d54c01a34c)

**Comment by theofficialgman** [comment]
> I got update from the SparkyLinux author Pawol Pavroo, they are not even going to fix it as well... What should I do now?
> 
> ![Screenshot_20231114_220511_Telegram.jpg](https://user-images.githubusercontent.com/25527589/282784221-b49ed635-ef32-406d-a4c6-a8d54c01a34c.jpg)

Copy paste and send them this or just link them this post.

SparkyLinux needs to fix their lsb-release package. it currently returns N/a for the codename. Please refer to https://github.com/Botspot/pi-apps/blob/08e864357a73654db1a91654e3e956b663ff1d30/api#L3252-L3305 for more information on expected output for distributions.

**Comment by theofficialgman** [comment]
Anyway the issue is very clear
They replace the `/usr/lib/os-release` file with their own contents but did not write in it the required output for lsb_release to parse. There is NO fix we can do for this on our end or want to do. This is a distro maintainer problem and they should fix it.

lsb_release code that obtains the info and returns the output:
```
if $show_codename ; then
	display_line "Codename" "${VERSION_CODENAME:-n/a}"
fi
```
sparky bad os-release info
```
PRETTY_NAME="SparkyLinux 7.1 (Orion-Belt)"
NAME="SparkyLinux"
VERSION_ID="7.1"
VERSION="7.1 (Orion-Belt)"
ID=sparky
ID_LIKE=debian
HOME_URL="https://sparkylinux.org/"
SUPPORT_URL="https://sparkylinux.org/forum/"
BUG_REPORT_URL="https://sourceforge.net/p/sparkylinux/tickets"
```
as you can clearly see, there is NO `VERSION_CODENAME` variable in their file, hence why the output is `n/a`


additionally, since sparky is modifying the ID from `debian` to `sparky` as well as the `VERSION_ID` from `12` to `7.1` they really should be putting `VERSION_CODENAME` as `Orion-Belt` (their "custom" name that they list already). The original distribution derived (bookworm) os-release file should then be provided in another location like is done in Pop!_OS or Linux Mint in either `/etc/upstream-release/lsb-release` or `/etc/lsb-release.diverted` file locations.
```
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Comment by Botspot** [comment]
@RoonMoonlight, maybe also try sending the link of this github issue to the author of SparkyLinux. If you have not already done this, it might help.

**Comment by pavroo** [comment]
updated sparky's base-file and added upstream's lsb-release 
will see...

**Comment by RoonMoonlight** [comment]
Thanks! Hope Pi-Apps should work better now...
