### ISSUE TITLE
I want to create app for piapps 

### ISSUE THREAD

**Issue by CoderLogy** [Botspot/pi-apps#248]
Pls let me create a notepads plus plus or password generator like app for Pi apps I want to contribute pls let me or I can make money sender something like that app that will help j to earn money or something like that or contributing to piapps

**Comment by Botspot** [comment]
You are more than welcome to look at all the issues and help with one or two.

Also, you can help test a beta app if the issue is labeled "Testers wanted"?

**Comment by CoderLogy** [comment]
Ok botspot but if there any thing I could do pls tell me I will help u in
Pi apps
