### ISSUE TITLE
Pi-apps starts empty and there's nothing to do

### ISSUE THREAD

**Issue by ojoshiro** [Botspot/pi-apps#2484]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi-Apps and the issue is still not fixed. [How to update Pi-Apps?](https://pi-apps.io/wiki/getting-started/updating-pi-apps/)
- [X] IMPORTANT: I promise to respond to comments on this issue and write a good bug report https://www.softwaretestinghelp.com/how-to-write-good-bug-report/

### What happened?

No apps ever load.
It  could be the search_ still works (lousy interface that, missing a GO button) but I never get any results.

### Description

When starting from 1942(CLI)  you get this helpful information.

Reading list file for ''...
Entry too long on line 9, maximum length is 255 characters!
Entry too long on line 9, maximum length is 255 characters!
Entry too long on line 11, maximum length is 255 characters!
Entry too long on line 13, maximum length is 255 characters!
Entry too long on line 8, maximum length is 255 characters!
Entry too long on line 11, maximum length is 255 characters!
Entry too long on line 11, maximum length is 255 characters!

According to Google I'm the only person in the world experiencing this... Figures.

Removing it and reinstalling it didn't change anything.
NB. I have seen it work, but even when the app did work you could only ever do one(1!) thing, after that the client locks up.

### What are your system specs (run the following command in your terminal)?

```bash

```

**Comment by Botspot** [comment]
Hello! And thank you for taking the time to report this issue.
We've seen similar issues before and solved them. Most of those were due to missing system folders, edge-case language preferences, weirdly outdated system packages, or unsupported systems.

Please run the commands below and then report the output:
```
~/pi-apps/api get_device_info
yad --version
```
Some people don't know this, but once you get the output back, there is no reason to have to manually type it all out on github.com. Just sign into github on the same system, then copy the output by selecting the output of those commands, then right-click -> copy.

**Comment by theofficialgman** [comment]
@ojoshiro Thanks for reporting your bug report. Please use the issue templates that repositories provide in the future. It prevents us from having to ask you for information manually.

I have edited your main post with the contents of the bug report issue template. Please fill it out. Botspot has asked for part of that information above already

**Comment by theofficialgman** [comment]
@ojoshiro we would love to help but cannot do anything without your response.

this issue will be closed in a few days as stale if no response is made

**Comment by theofficialgman** [comment]
Closing as stale. Will re-open if the information requested is provided.
