### ISSUE TITLE
PiGro 24.01 Release Preparation

### ISSUE THREAD

**Issue by actionschnitzel** [Botspot/pi-apps#2490]
Hi Pi-Apps Team,

I plan to release PiGro 24.01 in January.
Pi-Apps currently fetches PiGro from GitHub. Whenever I needed to make changes, I submitted a pull request to your repository. However, for the past six months, I have also been providing DEBIAN packages. What is more convenient for you?

This is not a critical issue. I just wanted to let you know in case you need to make major changes that take time.

**New Dependencies:**
- `git`
- `xterm`
- `python3-pil`
- `python3-pil.imagetk`
- `python3-psutil`
- `python3-distro`
- `python3-bs4`
- `python3-dev`
- `python3-requests`
- `mpg123`
- `lolcat`
- `wmctrl`
- `gdebi`
- `mousepad`

(Note: Git may not need to be installed via Pi-Apps)

**Link to Latest Release:**
[PiGro Latest Release](https://github.com/actionschnitzel/PiGro-Aid-/releases/latest)

**DEBIAN Package Download:**
As seen in your FreeTub installer:

```
version=23.04
https://github.com/actionschnitzel/PiGroAid-/releases/download/${version}/pigro_jci-${version%}_all.deb
```

**I would also like to submit updated icons:**
![icon-24](https://github.com/Botspot/pi-apps/assets/67635013/8c90d97e-0e15-48fc-8010-893ab16a10af)
![icon-64](https://github.com/Botspot/pi-apps/assets/67635013/35ada6e3-1a11-41eb-9fb5-cb899b184bb3)

Best regards
Timo

**Comment by Botspot** [comment]
Thanks for the heads-up. We're fine with switching to your deb release. Do you have your own apt repo? If not, that's fine.
This looks like a very simple change. Pi-Apps' main strength is its flexibility. It's a script, so any app can install by any means necessary.
While I could go ahead and make these changes myself, it would probably save us both time if you opened a pull request with the proposed changes. and yes, it looks like a copy of the FreeTube scripts would be a great starting point. This also gives you the chance to shoutout the new features in the description. If you can't tell, I think PiGro is pretty awesome especially for intermediate users who want to get stuff done quickly.

**Comment by actionschnitzel** [comment]
@theofficialgman Wow, good that you've taken a closer look. I am using a script that I found. Must fix this as soon as possible.

**Comment by actionschnitzel** [comment]
Update:
I fixed the ownership and permissions for `pigro-jci-23.04.deb` and also created a proper directory structure. I hope everything is now as it should be. If not, just let me know.

Thanks to both of you for your help and constructive criticism. It's appreciated.

Once everything is ready, I will create a pull request.

**Comment by theofficialgman** [comment]
> Update: I fixed the ownership and permissions for `pigro-jci-23.04.deb` and also created a proper directory structure. I hope everything is now as it should be. If not, just let me know.

Much better.

One thing to note about your .desktop file. You shouldn't need to specify the full path to the icon for it to work
`Icon=/usr/share/icons/hicolor/256x256/apps/pigro-logo.png`. Just the name of the icon should do `Icon=pigro-logo`. That lets users who have custom themed icons easily overwrite yours without having to edit the .desktop file manually. Additionally, if you have vectored versions of your logo that is generally a good thing to provide as well, they go under `/usr/share/icons/hicolor/scalable/apps` as an `.svg` file. Yes I realize that this icon only gets used briefly during launch of your application before the main python script tells tkinter  to use a specific hardcoded icon but it is still good practice. I will let you play around with the python code and see if you can get away with not specifying the full path and still have the icon load.

**Comment by actionschnitzel** [comment]
"It's always good to be nudged in the right direction :-) The `.svg` is now included. I replaced "`self.iconphoto(True, self.icon)`" (still needs to be completely removed) with "`__init__(className="PiGro")`". One less thing giving me a headache!

![20231130_12h44m19s_grim](https://github.com/Botspot/pi-apps/assets/67635013/aa077476-33a1-42be-a2e4-89ab28e59404)
![20231130_13h40m23s_grim](https://github.com/Botspot/pi-apps/assets/67635013/e54612da-c306-42b3-997c-2ee6a16a7b89)


I've packed v23.04 and a DEV-Preview of v24.01... Just in case there's interest."
240cb734c6fc)
[PIGRO-DEBS.tar.gz](https://github.com/Botspot/pi-apps/files/13513243/PIGRO-DEBS.tar.gz)

**Comment by theofficialgman** [comment]
> "It's always good to be nudged in the right direction :-) The `.svg` is now included. I replaced "`self.iconphoto(True, self.icon)`" (still needs to be completely removed) with "`__init__(className="PiGro")`". One less thing giving me a headache!

Right yeah, regarding the className variable, wayland base compositors actually can't set the window/titlebar icon through the old methods used in X11. what wayland compositors (like wayfire) do to get around this is check the `StartupWMClass` (and sometimes other environment variables) and see what .desktop files have a matching `StartupWMClass` or filename. the checks are different depending on the DE (eg: piOS wayfire, gnome, kde) and can be a little fuzzy so what works in one DE might not work in another (eg: some are case sensitive, others are not). I checked your deb and what you did looks good. That should work on everything since `StartupWMClass` is the most supported case.
