### ISSUE TITLE
V-Finder normal app no packages

### ISSUE THREAD

**Issue by solitary8** [Botspot/pi-apps#2494]
### What is the name of the app?

V-Finder

### (Optional) Where is the app hosted?

https://github.com/solitary8/v-finder.git

### About the app

This app permits users to scan devices to find vulnerabilities,it uses nmap but simplifies it.

### Upload file or Add PR Link

[V-Finder.zip](https://github.com/Botspot/pi-apps/files/13539531/V-Finder.zip)

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi-Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by theofficialgman** [comment]
See app eligibility rubric https://github.com/Botspot/pi-apps/issues/185 , simple wrappers around a single CLI program do not serve any purpose.

Also please read our creating an app documentation before making any app requests in the future https://pi-apps.io/wiki/development/Creating-an-app/
