### ISSUE TITLE
pi-apps won't run on raspberry pi 5 bookworm

### ISSUE THREAD

**Issue by quietCoder500** [Botspot/pi-apps#2500]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi-Apps and the issue is still not fixed. [How to update Pi-Apps?](https://pi-apps.io/wiki/getting-started/updating-pi-apps/)
- [X] IMPORTANT: I promise to respond to comments on this issue and write a good bug report https://www.softwaretestinghelp.com/how-to-write-good-bug-report/

### What happened?

pi-apps gui won't run

### Description

I got a fresh image of Bookworm on my Raspberry pi 5 and the first thing I tried to do was add pi-apps. It installed fine but when I click the menu or desktop icon nothing happens. I ran ~/pi-apps/gui but it told me `YAD needs to be installed to run Pi-Apps.`. YAD won't install either from apt-get or the manual .deb file. 

### What are your system specs (run the following command in your terminal)?

```bash
OS: Debian GNU/Linux 12 (bookworm)
OS architecture: 64-bit
Last updated Pi-Apps on: 12/18/2023
Latest Pi-Apps version: 12/18/2023
Kernel: aarch64 6.1.0-rpi7-rpi-2712
Device model: Raspberry Pi 5 Model B Rev 1.0
SOC identifier: bcm2712
Cpu name: Cortex-A76
Ram size: 4.04 GB
Raspberry Pi OS image version: 2023-12-05
Language: en_US.UTF-8
```

### (Recommended) Error log? Terminal output? Debug messages?

```bash
*****@homepi:~ $ /home/*****/pi-apps/gui
YAD needs to be installed to run Pi-Apps.
*****@homepi:~ $
```

**Comment by Botspot** [comment]
Hello and thank you for taking the time to ask us for help at the proper location.
How did you install pi-apps? Did you use the simple one-line install command, or did you follow some other tutorial for installing it?

Basically, I am trying to figure out why pi-apps did not install yad already. Yad can be installed with `sudo apt install yad`, but there are other things that should be installed too.

**Comment by Botspot** [comment]
> YAD won't install either from apt-get or the manual .deb file.

I saw this now. Please explain what happened when you tried. Please copy error messages from when you tried to install yad.

**Comment by Botspot** [comment]
For now I've gone ahead and improved the "yad missing" error to instruct users to please run the pi-apps install script. https://github.com/Botspot/pi-apps/commit/fa4690fce6a7861ddcbbc9030831ed9be010ee2a
It sounds like you have already tried this, but it should help others who try running pi-apps without installing dependencies first.

**Comment by quietCoder500** [comment]
I got YAD from [Source Forge](https://sourceforge.net/projects/yad-dialog/) (tar.gz format)
```quietCoder500@homepi:~ $ cd /home/quietCoder500/Downloads/yad-0.40.0
quietCoder500@homepi:~/Downloads/yad-0.40.0 $ ./configure && make && sudo make install
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking whether NLS is requested... yes
./configure: line 2979: intltool-update: command not found
checking for intltool >= 0.40.0...  found
configure: error: Your intltool is too old.  You need intltool 0.40.0 or later.
```
I tried to find out how to install [intltool.deb](http://http.us.debian.org/debian/pool/main/i/intltool/intltool_0.51.0-6_all.deb) but when I used Raspberry Pi package installer it simple told me it didn't work. So I tried with a tar.gz format that I found but nothing seemed to happen. But I just got YAD from [debian](https://packages.debian.org/sid/arm64/yad/download) and it installed with no errors. I opened Pi-Apps and was immediately told:
 ```
WARNING: YOUR SYSTEM IS UNSUPPORTED:
Congratulations, Linux tinkerer, you broke your system. The init package can not be found, which means you have removed the default debian sources from your system.
All apt based application installs will fail. Unless you have a backup of your /etc/apt/sources.list /etc/apt/sources.list.d you will need to reinstall your OS.
``` 
I pressed okay and Pi-Apps opened. Better Chromium and More Ram successfully installed with the same warning popping up each time. I don't know what has just happend.

**Comment by Botspot** [comment]
It looks like there has been something seriously wrong with your system this whole time, including the time before you tried installing Pi-Apps.
Please share the FULL output of the following commands:
```
sudo apt update
sudo apt install --reinstall yad -y
```
By the way I'm using Bookworm on a Pi5 and pi-apps runs great on it.

**Comment by quietCoder500** [comment]
Sorry, didn't see your first comment. I installed pi-apps with `wget -qO- https://raw.githubusercontent.com/Botspot/pi-apps/master/install | bash`, and I didn't try `sudo apt install yad`. I saw yad on pypi so I attempted `pip install yad` and `sudo apt install python3-yad` but neither worked.

**Comment by quietCoder500** [comment]
```
quietCoder500@homepi:~ $ sudo apt update
sudo apt install --reinstall yad -y
Hit:1 http://deb.debian.org/debian bookworm InRelease
Hit:2 http://deb.debian.org/debian-security bookworm-security InRelease
Hit:3 http://deb.debian.org/debian bookworm-updates InRelease
Hit:4 http://archive.raspberrypi.com/debian bookworm InRelease   
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
71 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
0 upgraded, 0 newly installed, 1 reinstalled, 0 to remove and 71 not upgraded.
Need to get 167 kB of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 http://deb.debian.org/debian bookworm/main arm64 yad arm64 0.40.0-1+b1 [167 kB]
Fetched 167 kB in 0s (648 kB/s)
debconf: unable to initialize frontend: Dialog
debconf: (Dialog frontend requires a screen at least 13 lines tall and 31 columns wide.)
debconf: falling back to frontend: Readline
(Reading database ... 126729 files and directories currently installed.)
Preparing to unpack .../yad_0.40.0-1+b1_arm64.deb ...
Unpacking yad (0.40.0-1+b1) over (0.40.0-1+b1) ...
Setting up yad (0.40.0-1+b1) ...
Processing triggers for desktop-file-utils (0.26-1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for gnome-menus (3.36.0-1.1) ...
Processing triggers for man-db (2.11.2-2) ...
Processing triggers for mailcap (3.70+nmu1) ...
```
I don't know what has happend. Do you thing I should reinstall the image on my sd card again?

**Comment by Botspot** [comment]
> I don't know what has happend. Do you thing I should reinstall the image on my sd card again?

Well that looks to be fine.

> I installed pi-apps with `wget -qO- https://raw.githubusercontent.com/Botspot/pi-apps/master/install | bash`

Well that should have installed yad when you ran it. Do you remember any errors? Do you still have the terminal open where you ran that?

**Comment by quietCoder500** [comment]
Yes, there were errors, no unfortunately I can't recreate them, but it said the install was successful.

**Comment by Botspot** [comment]
> Yes, there were errors, no unfortunately I can't recreate them, but it said the install was successful.

Please re-run the install script. `wget -qO- https://raw.githubusercontent.com/Botspot/pi-apps/master/install | bash`
Then please run this to check if pi-apps detects any other issues with your system: `~/pi-apps/api is_supported_system`

**Comment by quietCoder500** [comment]
Since my last comment I:
1. rebooted
2. successfully installed node.js as an apt test
3. opened pi-apps and recieved no warning
4. installed Cura from pi-apps with no warning
The result of `wget -qO- https://raw.githubusercontent.com/Botspot/pi-apps/master/install | bash` are:
```
quietCoder500@homepi:~ $ wget -qO- https://raw.githubusercontent.com/Botspot/pi-apps/master/install | bash
Hit:1 http://deb.debian.org/debian bookworm InRelease
Hit:2 http://deb.debian.org/debian-security bookworm-security InRelease        
Hit:3 http://deb.debian.org/debian bookworm-updates InRelease                  
Hit:4 http://archive.raspberrypi.com/debian bookworm InRelease                 
Hit:5 https://deb.nodesource.com/node_20.x nodistro InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
1 package can be upgraded. Run 'apt list --upgradable' to see it.

Reinstalling Pi-Apps...
Installation complete. Pi-Apps can be launched from the start menu or by running the command 'pi-apps'.
quietCoder500@homepi:~ $ 
```
Looks like the problems are resolved (I hope).

**Comment by Botspot** [comment]
No idea what the issue was, but if it happens again please reach out again.

**Comment by quietCoder500** [comment]
Okay, thanks for taking the time to help.
