### ISSUE TITLE
Rétroarch

### ISSUE THREAD

**Issue by Mama8315405924998525971827** [Botspot/pi-apps#2502]
### What is the name of the app?

Rétroarch 

### About the app

The application allows you to play retro games (like NES, N64, SNES, MEGADRIVE) and it would be cool to be able to have it on PI-APP. I hope it will be added :). Sincerely mama 

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have read the app eligibilty rubric https://github.com/Botspot/pi-apps/issues/185 and confirmed this app is suitable for addition in Pi-Apps.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi-Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by theofficialgman** [comment]
Retroarch does not build cores in their CI for arm64 Linux. Armhf only applications are not being considered. https://buildbot.libretro.com/nightly/linux/
Please make this request from retroarch developers.

Additionally, building cores manually is outside of pi-apps scope.
