### ISSUE TITLE
Pi-apps auto-updating

### ISSUE THREAD

**Issue by Sota4Ever** [Botspot/pi-apps#2504]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi-Apps and the issue is still not fixed. [How to update Pi-Apps?](https://pi-apps.io/wiki/getting-started/updating-pi-apps/)
- [X] IMPORTANT: I promise to respond to comments on this issue and write a good bug report https://www.softwaretestinghelp.com/how-to-write-good-bug-report/

### What happened?

Pi-apps keeps updating automatically several times and says that my Pi-Apps is an old version 

### Description

I recently installed pi-apps on..... kali linux... on my cell phone, I did it with git clone to be able to install pi-apps, it was installed correctly but when I wanted to install an app, it says that the version of pi-apps It is old and it keeps updating automatically and it is not resolved @
![Screenshot_20231225_193028_NetHunter KeX](https://github.com/Botspot/pi-apps/assets/151886690/94cf855c-36a8-4e44-84bf-9e5d8ac7e36f)

### What are your system specs (run the following command in your terminal)?

```bash
..............                                     kali@localhost 
            ..,;:ccc,.                             -------------- 
          ......''';lxO.                           OS: Kali GNU/Linux Rolling a 
.....''''..........,:ld;                           Kernel: 4.19.87-27231340 
           .';;;:::;,,.x,                          Uptime: 19717 days, 22 mins 
      ..'''.            0Xxoc:,.  ...              Packages: 2032 (dpkg) 
  ....                ,ONkc;,;cokOdc',.            Shell: bash 5.2.21 
 .                   OMo           ':ddo.          Resolution: 2312x1080 
                    dMc               :OO;         DE: Xfce 4.18 
                    0M.                 .:o.       WM: Xfwm4 
                    ;Wd                            WM Theme: Everblush-xfwm 
                     ;XO,                          Theme: Everblush [GTK2/3] 
                       ,d0Odlc;,..                 Icons: Nordzy-cyan-dark-MOD  
                           ..',;:cdOOd::,.         Terminal: xfce4-terminal 
                                    .:d;.':;.      Terminal Font: Monospace 12 
                                       'd,  .'     CPU: (8) 
                                         ;l   ..   Memory: 3937MiB / 5459MiB
```

### (Recommended) Error log? Terminal output? Debug messages?

```bash
57:20: '' is not a valid color name
C
(Pi-Apps:9394): Gtk-WARNING **: 00:29:54.003: Theme parsing error: gtk.css:20
is not a valid color name
58:16:
(Pi-Apps:9394): Gtk-WARNING **: 00:29:54.005: Theme parsing error: gtk.css:25
34:38: value 34 out of range. Must be from 0.0 to 1.0
(Pi-Apps:9394): Gtk-WARNING **: 00:29:54.012: Theme parsing error: gtk.css:49
93:38: value 34 out of range. Must be from 0.0 to 1.0
(Pi-Apps:9394): Gtk-WARNING **: 00:29:54.018: Theme parsing error: gtk.css:76
46:38: value 34 out of range. Must be from 0.0 to 1.0
(Pi-Apps:9394): Gtk-WARNING **: 00:29:54.018: Theme parsing error: gtk.css:77
85:51: value 34 out of range. Must be from 0.0 to 1.0
Cloning into 'pi-apps-forced-update
remote: Enumerating objects: 26767, done.
remote: Counting objeTts: 100% (63/63), done.
remote: Compressing objects: 100% (43/43), done
remote: Total 26767 (delta 22), reused 53 (delta 20), pack-reused 26704
Receiving objects: 100% (26767/26767), 28.93 MiB | 4.18 MiB/s, done.
Resolving deltas: 100% (17488/17488), done.
Updating files: 100% (1773/1773), done.
mv: cannot move '/home/kali/pi-apps' to '/home/kali/pi-apps-3-months-old/pi-a
pps': Directory not empty
fatal: bad object HEAD
```

**Comment by Botspot** [comment]
Hello and thank you for requesting help.
If I understand correctly, it seems that you saw a message saying "Your Pi-Apps installation is somehow 3 months out-of-date. Reinstalling Pi-Apps and saving the old version to /home/kali/pi-apps-3-months-old..."
If you saw this message ONCE, then it simply means pi-apps was not given the chance to update for 3 months. This behavior is normal.
But are you seeing the message repeatedly, over and over? That would not be normal.

**Comment by theofficialgman** [comment]
```
fatal: bad object HEAD
```
that is output from `git` (I believe the `git pull` in the update script) and is very concerning. What this appears to me is either:
A: corruption on the storage
B: errors caused by whatever emulation/translation/containerization method you are using to run kali on your phone

Please attempt to manually clone the repo and execute standard git operations on it in a testing folder. If any commands return in error then there is nothing we can do.
```bash
set -o xtrace
cd /tmp
git clone https://github.com/Botspot/pi-apps.git
cd pi-apps
git pull
git show -s --format=%ct
date +%s
```
attach the entire output as a comment

**Comment by theofficialgman** [comment]
Stale issues will be closed after a few days with no response. Still waiting on the OP's response.

**Comment by Botspot** [comment]
@Sota4Ever Please respond.

**Comment by Sota4Ever** [comment]
Well, I actually left it like that for a while until it updated automatically and then it worked, 2 hours for it to fix itself

**Comment by Botspot** [comment]
> Well, I actually left it like that for a while until it updated automatically and then it worked, 2 hours for it to fix itself

Let us know if this keeps happening, or if anything else seems to be unusual.
