### ISSUE TITLE
Trouble installing GRLevel3 in Wine x64

### ISSUE THREAD

**Issue by Twix094** [Botspot/pi-apps#2506]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi-Apps and the issue is still not fixed. [How to update Pi-Apps?](https://pi-apps.io/wiki/getting-started/updating-pi-apps/)
- [X] IMPORTANT: I promise to respond to comments on this issue and write a good bug report https://www.softwaretestinghelp.com/how-to-write-good-bug-report/

### What happened?

32-bit installer using Wine (x64) in default prefix fails to open. Gives error message 'Error creating window'

### Description

I installed wine (x64) through Pi-Apps in 64-bit Raspberry Pi OS on a Pi 4B and Pi 5. When attempting to install a 32-bit program (linked below) wine gives an error in a graphical window that says 'Error creating window' and fails to open the installer (Log posted below).
![WineRPiIssue](https://github.com/Botspot/pi-apps/assets/155034128/316f206c-fb6a-4fb6-8754-f3052e7a8119)
As a result, I am unable to install the software in the default prefix created during the Pi-Apps wine installation. I also tried creating a separate 32-bit prefix with`WINEARCH=win32 WINEPREFIX=~/wineapps/test1-32 winetricks`. This fails to fully create the prefix (see separate log file, [Log2_Prefix.txt](https://github.com/Botspot/pi-apps/files/13782755/Log2_Prefix.txt)). I am able to install this software successfully in 32-bit Raspberry Pi OS when installing wine (x32) through Pi-Apps. I was also able to successfully install this software in 64-bit Raspberry Pi OS about a month ago through Pi-Apps, but something has changed and it no longer works in a fresh install.

The software in question is GRLevel3, found here: https://grlevelx.com/grlevel3_2/

### What are your system specs (run the following command in your terminal)?

```bash
OS: Raspberry Pi OS (Debian 12 - bookworm)
OS architecture: 64-bit
Last updated Pi-Apps on: December 27, 2023
Kernel: 6.1.0-rpi7-rpi-v8
Device model: Raspberry Pi 4B and Raspberry Pi 5
CPU name: Cortex A72 and Cortex A76
Raspberry Pi OS image version: December 5, 2023
```

### (Recommended) Error log? Terminal output? Debug messages?

```bash
trpi@raspberrypi:~ $ wine ~/Downloads/gr2analyst_3_setup.exe
Dynarec for ARM64, with extension: ASIMD CRC32 PageSize:4096 Running on Cortex-A72 with 4 Cores
Params database has 44 entries
Box64 with Dynarec v0.2.7 cb63cdcd built on Dec 26 2023 06:27:58
BOX64: Wine64 detected, WINEPRELOADRESERVE=""
BOX64: Didn't detect 48bits of address space, considering it's 39bits
Counted 52 Env var
BOX64 LIB PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/:/lib/x86_64-linux-gnu/:/usr/lib/x86_64-linux-gnu/
BOX64 BIN PATH: ./:bin/:/usr/local/sbin/:/usr/local/bin/:/usr/sbin/:/usr/bin/:/sbin/:/bin/:/usr/local/games/:/usr/games/
Looking for /usr/local/bin/wine
Apply RC params for wine
Applying BOX64_MAXCPU=32
argv[1]="/home/trpi/Downloads/gr2analyst_3_setup.exe"
Rename process to "wine"
Using native(wrapped) libdl.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libutil.so.1
Using native(wrapped) librt.so.1
Using native(wrapped) libbsd.so.0
Using emulated /opt/wine-8.20/bin/../lib/wine/x86_64-unix/ntdll.so
Using emulated /lib/x86_64-linux-gnu/libunwind.so.8
Using native(wrapped) liblzma.so.5
Dynarec for ARM64, with extension: ASIMD CRC32 PageSize:4096 Running on Cortex-A72 with 4 Cores
Params database has 44 entries
Box64 with Dynarec v0.2.7 cb63cdcd built on Dec 26 2023 06:27:58
BOX64: Wine preloader detected, loading "/opt/wine-8.20/bin/wine" directly
BOX64: Wine64 detected, WINEPRELOADRESERVE=""
BOX64: Didn't detect 48bits of address space, considering it's 39bits
Counted 54 Env var
BOX64 LIB PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/:/lib/x86_64-linux-gnu/:/usr/lib/x86_64-linux-gnu/
BOX64 BIN PATH: ./:bin/:/usr/local/sbin/:/usr/local/bin/:/usr/sbin/:/usr/bin/:/sbin/:/bin/:/usr/local/games/:/usr/games/
Looking for /opt/wine-8.20/bin/wine
Apply RC params for wine
Applying BOX64_MAXCPU=32
argv[1]="/home/trpi/Downloads/gr2analyst_3_setup.exe"
Rename process to "wine"
Using native(wrapped) libdl.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libutil.so.1
Using native(wrapped) librt.so.1
Using native(wrapped) libbsd.so.0
Using emulated /opt/wine-8.20/bin/../lib/wine/x86_64-unix/ntdll.so
Using emulated /lib/x86_64-linux-gnu/libunwind.so.8
Using native(wrapped) liblzma.so.5
0120:err:environ:init_peb starting L"F:\\home\\trpi\\Downloads\\gr2analyst_3_setup.exe" in experimental wow64 mode
0120:err:virtual:map_fixed_area out of memory for 0x6fffffce0000-0x6fffffffd000
0120:err:virtual:try_map_free_area mmap() error Cannot allocate memory, range 0x7fffffcd0000-0x7ffffffed000, unix_prot 0x7.
Using emulated /opt/wine-8.20/lib/wine/x86_64-unix/win32u.so
Using native(wrapped) libm.so.6
Dynarec for ARM64, with extension: ASIMD CRC32 PageSize:4096 Running on Cortex-A72 with 4 Cores
Params database has 44 entries
Box64 with Dynarec v0.2.7 cb63cdcd built on Dec 26 2023 06:27:58
BOX64: Wine preloader detected, loading "/opt/wine-8.20/bin/wine" directly
BOX64: Wine64 detected, WINEPRELOADRESERVE="000400000-000496000"
BOX64: Didn't detect 48bits of address space, considering it's 39bits
Counted 56 Env var
BOX64 LIB PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/:/lib/x86_64-linux-gnu/:/usr/lib/x86_64-linux-gnu/
BOX64 BIN PATH: ./:bin/:/usr/local/sbin/:/usr/local/bin/:/usr/sbin/:/usr/bin/:/sbin/:/bin/:/usr/local/games/:/usr/games/
Looking for /opt/wine-8.20/bin/wine
Apply RC params for wine
Applying BOX64_MAXCPU=32
argv[1]="C:\windows\system32\conhost.exe"
argv[2]="--unix"
argv[3]="--width"
argv[4]="80"
argv[5]="--height"
argv[6]="24"
argv[7]="--server"
argv[8]="0x10"
Rename process to "wine"
Using native(wrapped) libdl.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libutil.so.1
Using native(wrapped) librt.so.1
Using native(wrapped) libbsd.so.0
Using emulated /opt/wine-8.20/bin/../lib/wine/x86_64-unix/ntdll.so
Using emulated /lib/x86_64-linux-gnu/libunwind.so.8
Using native(wrapped) liblzma.so.5
0128:err:virtual:map_fixed_area out of memory for 0x6fffffce0000-0x6fffffffd000
0128:err:virtual:try_map_free_area mmap() error Cannot allocate memory, range 0x7fffffcd0000-0x7ffffffed000, unix_prot 0x7.
0128:err:virtual:map_fixed_area out of memory for 0x6fffffb50000-0x6fffffcd9000
0128:err:virtual:try_map_free_area mmap() error Cannot allocate memory, range 0x7fffffe60000-0x7ffffffe9000, unix_prot 0x7.
0128:err:virtual:try_map_free_area mmap() error Cannot allocate memory, range 0x7fffffe60000-0x7ffffffe9000, unix_prot 0x7.
Using native(wrapped) libfreetype.so.6
Using native(wrapped) libfontconfig.so.1
Using native(wrapped) libexpat.so.1
0128:err:virtual:map_fixed_area out of memory for 0x6fffff5f0000-0x6fffffb4a000
0128:err:virtual:try_map_free_area mmap() error Cannot allocate memory, range 0x7fffffa90000-0x7ffffffea000, unix_prot 0x7.
0128:err:virtual:try_map_free_area mmap() error Cannot allocate memory, range 0x7fffffa90000-0x7ffffffea000, unix_prot 0x7.
Using emulated /opt/wine-8.20/lib/wine/x86_64-unix/win32u.so
Using native(wrapped) libm.so.6
Using native(wrapped) libfreetype.so.6
Using native(wrapped) libfontconfig.so.1
Using native(wrapped) libexpat.so.1
0130:err:virtual:map_fixed_area out of memory for 0x6fffffce0000-0x6fffffffd000
0130:err:virtual:try_map_free_area mmap() error Cannot allocate memory, range 0x7fffffcd0000-0x7ffffffed000, unix_prot 0x7.
0130:err:virtual:map_fixed_area out of memory for 0x6fffffb50000-0x6fffffcd9000
0130:err:virtual:try_map_free_area mmap() error Cannot allocate memory, range 0x7fffffe60000-0x7ffffffe9000, unix_prot 0x7.
0130:err:virtual:try_map_free_area mmap() error Cannot allocate memory, range 0x7fffffe60000-0x7ffffffe9000, unix_prot 0x7.
0130:err:virtual:map_fixed_area out of memory for 0x6fffff5f0000-0x6fffffb4a000
0130:err:virtual:try_map_free_area mmap() error Cannot allocate memory, range 0x7fffffa90000-0x7ffffffea000, unix_prot 0x7.
0130:err:virtual:try_map_free_area mmap() error Cannot allocate memory, range 0x7fffffa90000-0x7ffffffea000, unix_prot 0x7.
Using emulated /opt/wine-8.20/lib/wine/x86_64-unix/winex11.so
Using native(wrapped) libXext.so.6
Using native(wrapped) libX11.so.6
Using native(wrapped) libxcb.so.1
Using native(wrapped) libXau.so.6
Using native(wrapped) libXdmcp.so.6
Using native(wrapped) libXinerama.so.1
Using native(wrapped) libXxf86vm.so.1
Using native(wrapped) libXrender.so.1
Using native(wrapped) libXrandr.so.2
Using native(wrapped) libXcomposite.so.1
Using native(wrapped) libXi.so.6
Using native(wrapped) libXcursor.so.1
Dynarec for ARM64, with extension: ASIMD CRC32 PageSize:4096 Running on Cortex-A72 with 4 Cores
Params database has 44 entries
Box64 with Dynarec v0.2.7 cb63cdcd built on Dec 26 2023 06:27:58
BOX64: Wine preloader detected, loading "/opt/wine-8.20/bin/wine" directly
BOX64: Wine64 detected, WINEPRELOADRESERVE="000400000-0004bf000"
BOX64: Didn't detect 48bits of address space, considering it's 39bits
Counted 56 Env var
BOX64 LIB PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/:/lib/x86_64-linux-gnu/:/usr/lib/x86_64-linux-gnu/
BOX64 BIN PATH: ./:bin/:/usr/local/sbin/:/usr/local/bin/:/usr/sbin/:/usr/bin/:/sbin/:/bin/:/usr/local/games/:/usr/games/
Looking for /opt/wine-8.20/bin/wine
Apply RC params for wine
Applying BOX64_MAXCPU=32
argv[1]="C:\users\trpi\Temp\is-OROMJ.tmp\gr2analyst_3_setup.tmp"
argv[2]="/SL5=$2004A,20303645,58368,F:\home\trpi\Downloads\gr2analyst_3_setup.exe"
Rename process to "wine"
Using native(wrapped) libdl.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libutil.so.1
Using native(wrapped) librt.so.1
Using native(wrapped) libbsd.so.0
Using emulated /opt/wine-8.20/bin/../lib/wine/x86_64-unix/ntdll.so
Using emulated /lib/x86_64-linux-gnu/libunwind.so.8
Using native(wrapped) liblzma.so.5
0144:err:environ:init_peb starting L"C:\\users\\trpi\\Temp\\is-OROMJ.tmp\\gr2analyst_3_setup.tmp" in experimental wow64 mode
0144:err:virtual:map_fixed_area out of memory for 0x6fffffce0000-0x6fffffffd000
0144:err:virtual:try_map_free_area mmap() error Cannot allocate memory, range 0x7fffffcd0000-0x7ffffffed000, unix_prot 0x7.
Using emulated /opt/wine-8.20/lib/wine/x86_64-unix/win32u.so
Using native(wrapped) libm.so.6
Using native(wrapped) libfreetype.so.6
Using native(wrapped) libfontconfig.so.1
Using native(wrapped) libexpat.so.1
Using emulated /opt/wine-8.20/lib/wine/x86_64-unix/winex11.so
Using native(wrapped) libXext.so.6
Using native(wrapped) libX11.so.6
Using native(wrapped) libxcb.so.1
Using native(wrapped) libXau.so.6
Using native(wrapped) libXdmcp.so.6
Using native(wrapped) libXinerama.so.1
Using native(wrapped) libXxf86vm.so.1
Using native(wrapped) libXrender.so.1
Using native(wrapped) libXrandr.so.2
Using native(wrapped) libXcomposite.so.1
Using native(wrapped) libXi.so.6
Using native(wrapped) libXcursor.so.1
Using emulated /opt/wine-8.20/lib/wine/x86_64-unix/winspool.so
Using native(wrapped) libcups.so.2
0144:fixme:win:DisableProcessWindowsGhosting : stub
0144:fixme:graphics:ShutdownBlockReasonDestroy (00020060): stub
0144:fixme:graphics:ShutdownBlockReasonCreate (00020060, L"Installing"): stub
0144:fixme:rstrtmgr:RmStartSession 0049F3FC, 0, 0049F400 stub!
0144:fixme:graphics:ShutdownBlockReasonDestroy (00020060): stub
0144:fixme:graphics:ShutdownBlockReasonCreate (00020060, L"Installing GR2Analyst 3."): stub
0144:fixme:msg:ChangeWindowMessageFilterEx 0002009A c048 1 00000000
0144:fixme:msg:ChangeWindowMessageFilterEx 000200A2 c048 1 00000000
0144:fixme:rstrtmgr:RmEndSession 3735928559 stub!
0144:fixme:graphics:ShutdownBlockReasonDestroy (00020060): stub
```

**Comment by theofficialgman** [comment]
Since you have already confirmed that (old method) i386 Wine functions when using the `Wine (x86)` then this is a WOW64 Wine bug. Please report WOW64 Wine bugs upstream https://bugs.winehq.org/ as they are out of our control. Upstream Wine will want you to test on a real x86_64 linux computer and not emulated through box64, so I suggest downloading the WOW64 Wine build that pi-apps uses https://github.com/Pi-Apps-Coders/files/releases/download/large-files/wine-8.20.tar.gz on such a device, extracting that file, and running `wine` from within that archive.

**Comment by Twix094** [comment]
Thanks for your reply.
I just ran a test on an X86_64 system and the installer is functioning correctly in that system.

Here's the steps I followed:
On an Arch Linux system I downloaded the version of Wine linked in the previous post.
I extracted that file in my Documents folder.
I ran this command: `~/Documents/wine-8.20/bin/wine ~/Downloads/grlevel3_2_setup.exe`
It setup the default wine prefix in ~/.wine, the installer started, and I was able to successfully install and launch the software.

Assuming I performed all the steps correctly, it looks like it's not Wine causing the issue.

**Comment by theofficialgman** [comment]
Try following those same steps on your pi as well. Make sure to manually delete the wine prefix just to make sure it's not an issue with how pi-apps creates it's customized prefix with winetricks

**Comment by Twix094** [comment]
After deleting ~/.wine, ran the test on my Raspberry Pi as well and got the same result, 'Error creating window.'
Command I used: `~/Documents/wine-8.20/bin/wine ~/Downloads/grlevel3_2_setup.exe`

When I'm running this version of wine I downloaded from the github link, does it matter if the system already has wine installed?

I flashed a different SD card with a fresh install of Raspberry Pi OS 64-bit, installed only Box64 from Pi-Apps (not wine), and used the version of wine 8.20 that I downloaded from the github link. When running the same command seen above, it failed to make a prefix correctly and couldn't launch anything. This is the error it gave:
```wine: failed to start L"C:\\windows\\system32\\wineboot.exe"```
```0024:err:environ:run_wineboot failed to start wineboot c000007b```

**Comment by theofficialgman** [comment]
> After deleting ~/.wine, ran the test on my Raspberry Pi as well and got the same result, 'Error creating window.' Command I used: `~/Documents/wine-8.20/bin/wine ~/Downloads/grlevel3_2_setup.exe`

Try running with additional Box64 debug logging. The output that you have given does not point to any issues. This output will be large so you will probably want to upload it here as a file.

`BOX64_LOG=2 ~/Documents/wine-8.20/bin/wine ~/Downloads/grlevel3_2_setup.exe`

> When I'm running this version of wine I downloaded from the github link, does it matter if the system already has wine installed?

It does not. The default wine prefix will be shared (unless you override it) but you already deleted/cleared that. The wine from the github link I gave you is what the pi-apps script uses itself. 
https://github.com/Botspot/pi-apps/blob/master/apps/Wine%20(x64)/install-64#L53

**Comment by Twix094** [comment]
Thank you for taking the time to help me with this issue.

On my Pi 5, I updated Box64, deleted `~/.wine`, and ran the following command:
`BOX64_LOG=2 ~/Documents/wine-8.20/bin/wine ~/Downloads/grlevel3_2_setup.exe > Log_Box64_2024-01-01.txt`
The file is quite large for a text file, so I had to put it in a zip file and I've attached it here: [Log_Box64_2024-01-01.zip](https://github.com/Botspot/pi-apps/files/13805138/Log_Box64_2024-01-01.zip)

I also tried running the command without pointing it to a text file, like this: `BOX64_LOG=2 ~/Documents/wine-8.20/bin/wine ~/Downloads/grlevel3_2_setup.exe`
However, it was too many lines for the terminal and it just kept repeating error messages in the terminal until I clicked the 'OK' button in the error window that popped up.

**Comment by theofficialgman** [comment]
I am unable to troubleshoot further. Since this appears to be an issue with BOX64 emulation of Wine, please open an issue upstream https://github.com/ptitSeb/box64/issues with the above contents, explaining that you have tested the same Wine build on x86_64 and found no issues.
