### ISSUE TITLE
Not instaling

### ISSUE THREAD

**Issue by twirlscurt** [Botspot/pi-apps#2508]
### Confirmations

- [ ] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [ ] I tried updating Pi-Apps and the issue is still not fixed. [How to update Pi-Apps?](https://pi-apps.io/wiki/getting-started/updating-pi-apps/)
- [ ] IMPORTANT: I promise to respond to comments on this issue and write a good bug report https://www.softwaretestinghelp.com/how-to-write-good-bug-report/

### What happened?

When I click install on pi-apps it doesn’t open the installing windows

(Using Ubuntu on orange pi)

### What are your system specs (run the following command in your terminal)?
`~/pi-apps/api get_device_info`

```bash

```

**Comment by Botspot** [comment]
Hello @twirlscurt and thank you for reaching out.

Try running this and report what happens:
```
~/pi-apps/etc/terminal-run 'sudo apt update' 'running sudo apt update'
```
This should open a terminal and run `sudo apt update`. If the terminal does not open, then this is likely the issue.

**Comment by theofficialgman** [comment]
@twirlscurt please use issue templates when a repository provides them (such as this one) https://github.com/Botspot/pi-apps/issues/new/choose

I have edited your post to contain the contents of the issue template, please edit your post and fill it in.

**Comment by Botspot** [comment]
@twirlscurt Please respond.

**Comment by theofficialgman** [comment]
@twirlscurt stale issues will be closed with no response. We would like to help but cannot without a response.
