### ISSUE TITLE
Replace FF-Multi-Converter with FF-Converter fork

### ISSUE THREAD

**Issue by l-koehler** [Botspot/pi-apps#2513]
### What is the name of the app?

FF-Converter

### (Optional) Where is the app hosted?

https://github.com/l-koehler/FF-converter/

### About the app

The app is a fork of [lstam/FF-Multi-Converter](https://github.com/ilstam/FF-Multi-Converter), which is no longer being developed.
It can convert most common file formats into other formats.
It has the same features as the original, plus some extra functionality (pandoc and some other tools available for conversion, "All Formats" tab).
As far as I know, it should not have any major issues that aren't also present in the original, except that I did not translate all new features into each supported language (only english, german and french are complete).

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have read the app eligibilty rubric https://github.com/Botspot/pi-apps/issues/185 and confirmed this app is suitable for addition in Pi-Apps.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi-Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by theofficialgman** [comment]
regarding https://github.com/l-koehler/FF-converter?tab=readme-ov-file#troubleshooting that is a known issue with pipx, it doesn't have the ability to install .desktop files and was deemed "out of the project scope" (see https://github.com/pypa/pipx/issues/717)

it is easy to copy the file out of the installed directory though and place it in the proper location since it does reside in the pipx installed directory similar to what we do for Quartz https://github.com/Botspot/pi-apps/blob/afbca0bac81b6b49463660570e31059cbba71abf/apps/Quartz/install#L6-L9

**Comment by l-koehler** [comment]
thanks!
added that to the install instructions, as the previous workaround didn't work with the icon.

**Comment by theofficialgman** [comment]
@Botspot what are your thoughts on this? should we deprecate FF Multi Converter and instruct users in the popup to install FF Converter or should we simply change the scripts to install FF Converter while keeping the name?

**Comment by Botspot** [comment]
Let's transition them and keep the name the same.

**Comment by l-koehler** [comment]
@theofficialgman 
thanks for the update!
small problem: the [install script](https://github.com/Botspot/pi-apps/blob/master/apps/FF%20Multi%20Converter/install) is not automatically installing all optional dependencies.
the fork can also use ```pandoc```, ```ar```, ```zip``` and ```squashfs-tools```. (```tar``` too, but that should be preinstalled).
also, maybe it should only fail if ```python3``` or ```pyqt5``` fail to install, not if a optional dependency fails.
i would suggest to replace line 12 with
```sh
install_packages python3 python3-pyqt5 python3-distutils || exit 1
install_packages tar ar squashfs-tools pandoc ffmpeg imagemagick unoconv || echo "Could not install all optional dependencies"
```
(not sure about what pi-apps uses to show non-fatal errors, might need to replace the echo)

**Comment by theofficialgman** [comment]
@l-koehler we can install all packages that are available. there isn't any downside for having all the dependencies installed even if they are optional. with them installed the software has more features.

what is the `ar` that you are referring to? that isn't a package name and the binary under that name is from binutils and is the GNU assembler which I don't think you meant to write.

**Comment by l-koehler** [comment]
Part of [binutils](https://www.gnu.org/software/binutils/), shouldn't need install on most distributions.
> A utility for creating, modifying and extracting from archives.
Don't know why I included it, i guess it was missing for me once.

**Comment by theofficialgman** [comment]
The dependencies suggested have been added
