### ISSUE TITLE
Installer: Minecraft Pi Server

### ISSUE THREAD

**Issue by NoozAbooz** [Botspot/pi-apps#2514]
### What is the name of the app?

Minecraft Pi Server

### (Optional) Where is the app hosted?

https://github.com/NoozAbooz/mcpi-reborn-extended

### About the app

Dedicated server for MCPI. Continuation of #2437 since Botspot gave the go-ahead.

### Upload file or Add PR Link

[Minecraft Pi Server.zip](https://github.com/Botspot/pi-apps/files/13848441/Minecraft.Pi.Server.zip)

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [x] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi-Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by NoozAbooz** [comment]
This is currently untested FYI. I noticed in the OG pr that Botspot wanted to save files to /usr/share, but I decided to make the installer align with the formatting of the existing MCPI Client app.

**Comment by theofficialgman** [comment]
> I noticed in the OG pr that Botspot wanted to save files to /usr/share

Yes we would like that. We are slowly trying to migrate all install scripts to perform global installation.

**Comment by theofficialgman** [comment]
@NoozAbooz Please explain in clear terms what benefits your packages offer over TheBrokenRail's [minecraft-pi-reborn](https://gitea.thebrokenrail.com/minecraft-pi-reborn/minecraft-pi-reborn) . To an outsider (like me) all I see is that you package as a deb the work of TheBrokenRail that officially packages as an appimage.

**Comment by NoozAbooz** [comment]
> @NoozAbooz Please explain in clear terms what benefits your packages offer over TheBrokenRail's [minecraft-pi-reborn](https://gitea.thebrokenrail.com/minecraft-pi-reborn/minecraft-pi-reborn) . To an outsider (like me) all I see is that you package as a deb the work of TheBrokenRail that officially packages as an appimage and flatpak

There's a few QoL changes listed in the readme: https://github.com/NoozAbooz/mcpi-reborn-extended?tab=readme-ov-file#feature-list-in-order-of-awesomeness. For the server software, the only major change is that it fixes an issue with playing on older world files causing disappearing blocks: https://github.com/NoozAbooz/mcpi-reborn-extended/issues/39. 

I only kept the download link to my repo since the original author in #2437 used it. Let me know if you want it changed to TBR's server software.

**Comment by theofficialgman** [comment]
> There's a few QoL changes listed in the readme: https://github.com/NoozAbooz/mcpi-reborn-extended?tab=readme-ov-file#feature-list-in-order-of-awesomeness.

I have read the readme. It does not describe the changes that have been made in ADDITION to those already included in TheBrokenRail's software. I am not interested in the full list of changes in reference to the ORIGINAL Minecraft Pi Edition

**Comment by NoozAbooz** [comment]
> > There's a few QoL changes listed in the readme: https://github.com/NoozAbooz/mcpi-reborn-extended?tab=readme-ov-file#feature-list-in-order-of-awesomeness.
> 
> I have read the readme already. It does not describe the changes that have been made in ADDITION to those already included in TheBrokenRail's software. I am not interested in the full list of changes in reference to the ORIGINAL Minecraft Pi Edition

Sorry, I should have made some of them more detailed. All of these are additions on top of reborn.

Add [even more] missing items to creative inventory (full set of armour, all food types, etc)
Sprinting via Ctrl key
Optifine-like zoom feature via C key
Modern 1.14+ Jappa textures from [BasedSkeleton](https://basedskeleton.github.io/)

Longer chat message length limit (512 characters)
Longer username length limit (32 characters)
Add [more] item names to hidden items
Sneaking via both the Shift and Alt keys
A custom "[Cursed Chest](https://media.discordapp.net/attachments/761048906242981948/903080546182242344/2021-10-27_20.39.05.png)" block for debugging
Ability to look around via arrow keys instead of mouse (useful if mouse is glitched)

Ability to also use Vim keybindings for movement (hjkl)

Of course though, these are not relevant to the current submission since they are the client modifications. Here's a version of the installer downloading from TBR's version. The icon is the same as the MCPI app.
[Minecraft Pi Server.zip](https://github.com/Botspot/pi-apps/files/13850702/Minecraft.Pi.Server.zip)

**Comment by theofficialgman** [comment]
@NoozAbooz I am currently leaning towards TBR's version to match the current client available via pi-apps already.

In your personal opinion do you see any reason that a user would want to have both TBR's and your version installed? I am considering having both in pi-apps and am debating whether they should be separate apps or one app where a userinput prompt asks the user which one they would like to install. If we choose to do separate apps I think we need to rename the current application to better describe what it is. My current thinking of the following names to actually match the project names.

for the clients:
Minecraft Pi Reborn
Minecraft Pi Reborn Extended

for the servers:
Minecraft Pi Reborn Server
Minecraft Pi Reborn Extended Server

additionally I will add a subfolder `Games/Minecraft Pi` that these will reside in so it does not increase the length of the `Games` folder.

**Comment by TheBrokenRail** [comment]
In the upcoming MCPI-Reborn v3.0.0, the client and server builds have been unified. Running the dedicated server will only require running MCPI-Reborn with `--server`.

**Comment by theofficialgman** [comment]
closing as waiting for upstream release where support for this will be automatic
