### ISSUE TITLE
How do I uninstall pi-apps and all of the apps I installed with it

### ISSUE THREAD

**Issue by Kenfin7** [Botspot/pi-apps#2516]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [ ] I tried updating Pi-Apps and the issue is still not fixed. [How to update Pi-Apps?](https://pi-apps.io/wiki/getting-started/updating-pi-apps/)
- [X] IMPORTANT: I promise to respond to comments on this issue and write a good bug report https://www.softwaretestinghelp.com/how-to-write-good-bug-report/

### What happened?

I want to know how to uninstall pi apps

### Description

How do I uninstall pi-apps and all of the apps installed using it? I think the problem occured when I tried to turn it into xblunch 3d dark mode. It turned the app into a text file.

### What are your system specs (run the following command in your terminal)?

```bash
raspberry pi 4 os 64 Gigabite microsd card raspberry pi 4 model B
```

**Comment by Botspot** [comment]
You can turn off the xlucnh mode by going to the start menu -> Preferences -> Pi-Apps Settings.
Could you send a screenshot of the problem?

**Comment by theofficialgman** [comment]
@Kenfin7 We cannot help you further without an answer to the above question.

Please remember that stale issues where we are waiting on the users response will be closed after a period of time with no response.

**Comment by Kenfin7** [comment]
I'm sorry, but I already fixed it. Thanks for the help though!
