### ISSUE TITLE
DNS changer for raspberry pi

### ISSUE THREAD

**Issue by mohammade301** [Botspot/pi-apps#2519]
### What is the name of the app?

DNS changer

### (Optional) Where is the app hosted?

https://github.com/mrmoein/GUI-DNS-changer-for-linux

### About the app

this app scripted by mrmoein in github. 
easy and quick dns changer for linux.
tested on ubuntu,mint and raspbian

The program edits /etc/resolv.conf and at each boot (restart) this file is overwritten by the system and the software changes are removed (reset to default system dns).

### Upload file or Add PR Link

https://github.com/mrmoein/GUI-DNS-changer-for-linux

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi-Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by theofficialgman** [comment]
DNS should be set via the appropriate software tool associated with your DE. Modifying resolv.conf is NEVER supposed to be done manually.
```
# This is /run/systemd/resolve/stub-resolv.conf managed by man:systemd-resolved(8).
# Do not edit.
#
```
refer to the systemd-resolved manpage and other documentation for proper methods of setting the DNS which is what the other tools (eg: gnome settings, kde system settings, network-manager-applet, etc)

No plan to add this to pi-apps.

**Comment by theofficialgman** [comment]
@mohammade301 also please use the appropriate issue template, "App Suggestion", next time. there is no "completed ZIP, install files, deb, or PR ONLY" included in your issue which is required for an "App Submission".
