### ISSUE TITLE
Teamviewer seems to not connect nor accept any connection

### ISSUE THREAD

**Issue by GYKgamer** [Botspot/pi-apps#2523]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi-Apps and the issue is still not fixed. [How to update Pi-Apps?](https://pi-apps.io/wiki/getting-started/updating-pi-apps/)
- [X] IMPORTANT: I promise to respond to comments on this issue and write a good bug report https://www.softwaretestinghelp.com/how-to-write-good-bug-report/

### What happened?

When trying to connect to the raspberry pi via teamviewer, the teamviewer client is stuck on "Connecting" and after around 2 minutes just stops. When trying to connect you are required to log into an account, when trying to log in it just fails.

### Description

The Teamviewer client knows that the raspberry pi (server) exists, it doesn't error unlike if you turned the application off on your raspberry pi. If you try to connect using the raspberry pi to a pc it will just error asking to log in because of an "added security measure". When trying to log in it just errors at the fact that it found an incorrect username and password even though the app is asking for email. Also a small issue I found is once it errors it the program just spams **`** until you backspace, just a weird thing I found. I was able to reproduce this about 3 - 4 times. 
![image](https://github.com/Botspot/pi-apps/assets/41442793/d3aa3ba0-db02-47e3-b9b4-b4cc8e6c7cd1)
![image](https://github.com/Botspot/pi-apps/assets/41442793/ea631989-9789-4969-815c-3ce1245946d0)

### What are your system specs (run the following command in your terminal)?

```bash
OS: Debian GNU/Linux 12 (bookworm)
OS architecture: 64-bit
Last updated Pi-Apps on: 01/09/2024
Latest Pi-Apps version: 01/11/2024
Kernel: aarch64 6.1.0-rpi7-rpi-v8
Device model: Raspberry Pi 5 Model B Rev 1.0
SOC identifier: bcm2712
Cpu name: Cortex-A76
Ram size: 7.94 GB
Raspberry Pi OS image version: 2023-12-05
Language: en_US.UTF-8
```

### (Recommended) Error log? Terminal output? Debug messages?

```bash
pi@raspberrypi:~ $ teamviewer

Init...
CheckCPU: aarch64
Checking setup...
Launching TeamViewer ...
Launching TeamViewer GUI ...
```

**Comment by theofficialgman** [comment]
Teamviewer is a native application produced and packaged upstream by teamviewer themselves. If you are having trouble with it, open a support ticked through their own customer support system https://www.teamviewer.com/en-us/global/support/customer-support/

**Comment by theofficialgman** [comment]
I have confirmed the teamviewer upstream account email/login bug on both ARM64 and x86_64. Please open a ticket at teamviewer to have this issue fixed on their end. You can close this issue when they have fixed it.

**Comment by GYKgamer** [comment]
I see someone has already made a community post about this: https://community.teamviewer.com/English/discussion/132733/raspberry-pi-stuck-on-connecting
Apparently someone has found a fix where if you change from Wayland to Xorg is works

> Basically found the solution: Wayland -> Xorg.
See here:
https://community.teamviewer.com/English/discussion/122817/remote-control-is-currently-deactivated-on-the-device
https://www.omglinux.com/raspberry-pi-os-bookworm/
Good luck!

**Comment by theofficialgman** [comment]
@GYKgamer teamviewer appears to have fixed this server side.
I was able to attempt to signin, authorize my device via email, and then sign in again and it functions.

**Comment by Botspot** [comment]
Tried TeamViewer today with a user and it forever said "Connecting..." Maybe this is still an issue.

**Comment by theofficialgman** [comment]
They probably just broke it again. Last time I was able to reproduce the issue on arm64 and x86_64 and then a week later I tried again and it was resolved on both with no app updates.
