### ISSUE TITLE
pi-apps won't launch

### ISSUE THREAD

**Issue by gbrandt1** [Botspot/pi-apps#2525]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi-Apps and the issue is still not fixed. [How to update Pi-Apps?](https://pi-apps.io/wiki/getting-started/updating-pi-apps/)
- [X] IMPORTANT: I promise to respond to comments on this issue and write a good bug report https://www.softwaretestinghelp.com/how-to-write-good-bug-report/

### What happened?

after running pi-apps various errors appear and gui does not launch

### Description

various error messages at startup

### What are your system specs (run the following command in your terminal)?

```bash
OS: Debian GNU/Linux 12 (bookworm)
OS architecture: 64-bit
Last updated Pi-Apps on: 01/11/2024
Latest Pi-Apps version: 01/12/2024
Kernel: aarch64 6.1.0-rpi7-rpi-2712
Device model: Raspberry Pi 5 Model B Rev 1.0
SOC identifier: bcm2712
Cpu name: Cortex-A76
Ram size: 8.04 GB
Raspberry Pi OS image version: 2023-10-10
Language: en_US.UTF-8
```

### (Recommended) Error log? Terminal output? Debug messages?

```bash
🭊🬹🬹🬹🬿
 🭇🬭🬭🬎🬭🬭🬭🬎🬭🬭🬼
 🮉  ▄ ▄ ▄  ▋   █▀▀🭍 ▄
 🮉  ▄ ▄ ▄  ▋   █▄▄🭞 ▄ ▄▄ 🭂▀▀█ █▀▀🭍 █▀▀🭍 🭂🬰🬰🬰
 🮉  ▄ ▄ ▄  ▋   █    █    🭓▄▄█ █▄▄🭞 █▄▄🭞 ▄▄▄🭞
 🭦🭏🬭🬭🬭🬭🬭🬭🬭🭄🭛                  █    █


runonce(): '  dependencies='yad curl wget aria2 lsb-release software-properties-common apt-utils apt-transport-https gnupg imagemagick bc librsvg2-bin locales shellcheck git wmctrl xdotool x11-utils rsync unzip debsums'
  # Install dependencies if necessary
  if ! dpkg -s $dependencies >/dev/null 2>&1; then
    sudo_popup apt install $dependencies -y -f --no-install-recommends
  fi' succeeded. Added to list.
runonce(): '  if ! is_supported_system >/dev/null;then
    text="YOUR SYSTEM IS UNSUPPORTED:
$(is_supported_system)

Pi-Apps will disable the sending of any error reports until you have resolved the issue above.
Your mileage may vary with using Pi-Apps in this state. Expect the majority of apps to be broken."

    yadflags=(--class Pi-Apps --name "Pi-Apps" --window-icon="${DIRECTORY}/icons/logo.png" --title="Pi-Apps")
    userinput_func "$text" "Ok"
  fi
  true' succeeded. Added to list.
Can't open display
Can't open display
/home/gbrandt/pi-apps/gui: line 196: [: -le: unary operator expected
/home/gbrandt/pi-apps/gui: line 196: [: -le: unary operator expected
pipe is /tmp/tmp.VxcdiqIpED
detailspid is /tmp/tmp.uf0FbqxIGY
tail: warning: --retry only effective for the initial open

Updater mode: set-status

Checking for online changes...
(Pi-Apps:59006): Gtk-WARNING **: 21:32:33.741: cannot open display:
```

**Comment by Botspot** [comment]
Are you running this command in the console, or with ssh or something?
It looks like something with your display or screen is the cause of the problems.

**Comment by gbrandt1** [comment]
After installation I first tried to run from the Desktop using the launch icon.

When the GUI didn't come up, I started from the shell to see if any errors would appear, with the results posted above.

So while I agree the error points at display/screen there seems to be also unrelated shell parsing errors. 

I did try to set $DISPLAY=:0.0 manually to but it didn't help.

**Comment by Botspot** [comment]
Yeah you would get similar display-related errors from trying to run any GUI program in the shell.
Try opening a terminal within your desktop environment and run `pi-apps` in there. That should help show a bit more of what is going on here.

**Comment by gbrandt1** [comment]
that's what i did, i started pi-apps in a terminal within the desktop environment. i thought that's what you meant by shell.

i don't have any problems starting any other GUI application that way (i tried e.g. a webbrowser to check), only pi-apps.

**Comment by theofficialgman** [comment]
Please test on a fresh piOS image and report back (image dated December 11th 2023) https://www.raspberrypi.com/software/operating-systems/
Since your install is unable to run applications through xwayland it seems, you likely are missing critical packages in the OS or have corruption on your install.

**Comment by gbrandt1** [comment]
since the last pi-apps update it works. i didn't investigate further what changed. i didn't change anything in my system (no packages removed, added or updated)
thanks

**Comment by Botspot** [comment]
Let us know if the problem happens again.
