### ISSUE TITLE
Cant open Lunar client on Raspberry pi os bookworm

### ISSUE THREAD

**Issue by DatBoiG265** [Botspot/pi-apps#2531]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi-Apps and the issue is still not fixed. [How to update Pi-Apps?](https://pi-apps.io/wiki/getting-started/updating-pi-apps/)
- [X] IMPORTANT: I promise to respond to comments on this issue and write a good bug report https://www.softwaretestinghelp.com/how-to-write-good-bug-report/

### What happened?

Lunar client opening error

### Description

I went to open Lunar client and it gave me a popup message for an error so i tried to reinstall and it still showed the same error
![20240118_22h54m24s_grim](https://github.com/Botspot/pi-apps/assets/100205162/261a8cc7-2a76-4a6a-9663-ae9a13a67f34)

### What are your system specs (run the following command in your terminal)?

```bash
OS: Debian GNU/Linux 12 (bookworm)
OS architecture: 64-bit
Last updated Pi-Apps on: 01/16/2024
Latest Pi-Apps version: 01/17/2024
Kernel: aarch64 6.1.0-rpi7-rpi-v8
Device model: Raspberry Pi 4 Model B Rev 1.2
SOC identifier: bcm2711
Cpu name: Cortex-A72
Ram size: 3.79 GB
Raspberry Pi OS image version: 2023-12-05
Language: en_US.UTF-8
```

### (Recommended) Error log? Terminal output? Debug messages?

```bash
Failed to load launcher

TypeError: Cannot read property 'subversions' of undefined
```

**Comment by theofficialgman** [comment]
@gl91306 has previously asked that all lunar client issues be opened upstream at their repo https://github.com/gl91306/lunar

I suggest using one of the Open Source (not closed source like lunar client) launchers such as Prism Launcher

**Comment by DatBoiG265** [comment]
> @gl91306 has previously asked that all lunar client issues be opened upstream at their repo https://github.com/gl91306/lunar
> 
> I suggest using one of the Open Source (not closed source like lunar client) launchers such as Prism Launcher

Okay i will

**Comment by DatBoiG265** [comment]
The pi-apps version of lunar client is broken but here is the link for a working version of lunar client for raspberry pi.

https://github.com/gl91306/lunar
