### ISSUE TITLE
Lutris (Package app)

### ISSUE THREAD

**Issue by DatBoiG265** [Botspot/pi-apps#2532]
### What is the name of the app?

Lutris

### (Optional) Where is the app hosted?

https://lutris.net/
https://github.com/lutris/lutris

### About the app

Lutris is a free and open source game manager for Linux-based operating systems developed and maintained by Mathieu Comandon and the community

### Upload file or Add PR Link

[Lutris.zip](https://github.com/Botspot/pi-apps/files/13999435/Lutris.zip)

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi-Apps app list.
- [ ] I have confirmed that this app can run on Raspberry Pi.

**Comment by theofficialgman** [comment]
Third condition not met (cannot run on raspberry pi). Lutrus is for x86_64 linux PCs for running linux/windows PC games.

Not interesting in having an installer with box86/box64 for this as steam is already a nightmare in and of itself.
