### ISSUE TITLE
VICE Versatile Commodore Emulator

### ISSUE THREAD

**Issue by Centar2001** [Botspot/pi-apps#2534]
### What is the name of the app?

VICE

### (Optional) Where is the app hosted?

https://vice-emu.sourceforge.io/

### About the app

Popular Commodore emulator

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have read the app eligibilty rubric https://github.com/Botspot/pi-apps/issues/185 and confirmed this app is suitable for addition in Pi-Apps.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi-Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by theofficialgman** [comment]
>  I have confirmed that this app can run on Raspberry Pi.

Please explain how to run this on raspberry pi in detail

**Comment by theofficialgman** [comment]
stale issues will be closed. if you cannot explain how you have confirmed this can be run on raspberry pi, this issue will be closed.

**Comment by Botspot** [comment]
Closed because @Centar2001 failed to respond to comments on this issue.
