### ISSUE TITLE
AnyDesk

### ISSUE THREAD

**Issue by fabianmendes** [Botspot/pi-apps#254]
Hi, I've just created an AnyDesk app, to skip manual installation and I think it is not at aptitude. Anyways, like a deb package, it can be installed on any armfh architecture. [AnyDesk.zip](https://github.com/Botspot/pi-apps/files/5825655/AnyDesk.zip)

**Comment by Botspot** [comment]
Added! Commit 4376c584d63767451be978540887bfb8243768ff.
