### ISSUE TITLE
Soptfy

### ISSUE THREAD

**Issue by auguray** [Botspot/pi-apps#2546]
### What is the name of the app?

spotify

### About the app

Musik hören

### Upload file or Add PR Link

curl -sS https://download.spotify.com/debian/pubkey_6224F9941A8AA6D1.gpg | sudo gpg --dearmor --yes -o /etc/apt/trusted.gpg.d/spotify.gpg

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi-Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by Botspot** [comment]
Hello, have you actually tested this on a Raspberry Pi?

**Comment by theofficialgman** [comment]
no arm64 or armhf Packages file, thus, no support for armhf or arm64 from spotify apt http://repository.spotify.com/dists/stable/non-free/binary-arm64/Packages
http://repository.spotify.com/dists/stable/non-free/binary-armhf/Packages

only amd64 (and ancient unsupported i386)
http://repository.spotify.com/dists/stable/non-free/binary-amd64/Packages
http://repository.spotify.com/dists/stable/non-free/binary-i386/Packages

closing. @auguray please do not waste time and lie in the confirmation checkboxes. thanks
