### ISSUE TITLE
RetroPie

### ISSUE THREAD

**Issue by TheElephantCoder** [Botspot/pi-apps#2549]
### What is the name of the app?

RetroPie

### About the app

RetroPie is a Emulator that can run a lot of Engines and can play really smooth on a Raspberry Pi 3, 4, or 5. NOT OFFICIALLY FROM RETROPIE! Note: RetroPie does not include any games with it.

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have read the app eligibilty rubric https://github.com/Botspot/pi-apps/issues/185 and confirmed this app is suitable for addition in Pi-Apps.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi-Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by Botspot** [comment]
> * [x]  I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi-Apps app list.

Was this one confusing? You were supposed to search through our past issues to see if anyone had requested retropie before. RetroPie has been requested multiple times before by other people.

**Comment by Botspot** [comment]
https://github.com/Botspot/pi-apps/issues/1372
https://github.com/Botspot/pi-apps/issues/280
https://github.com/Botspot/pi-apps/issues/340
https://github.com/Botspot/pi-apps/issues/12

**Comment by TheElephantCoder** [comment]
oh sorry
