### ISSUE TITLE
Cura on Pi 5 Crash Fix

### ISSUE THREAD

**Issue by mikepaxton** [Botspot/pi-apps#2552]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi-Apps and the issue is still not fixed. [How to update Pi-Apps?](https://pi-apps.io/wiki/getting-started/updating-pi-apps/)
- [X] IMPORTANT: I promise to respond to comments on this issue and write a good bug report https://www.softwaretestinghelp.com/how-to-write-good-bug-report/

### What happened?

Installed Cura but crashed on Pi 5

### Description

After installing Cura on Raspberry Pi PiOS Bookworm it crashes immediately on startup.  I found that if I changed the install script to use the aarch64-16k  version (which Pi 5 is), then it installs and runs great.

### What are your system specs (run the following command in your terminal)?

```bash
OS: Debian GNU/Linux 12 (bookworm)
OS architecture: 64-bit
Last updated Pi-Apps on: 02/18/2024
Latest Pi-Apps version: 02/23/2024
Kernel: aarch64 6.1.0-rpi8-rpi-2712
Device model: Raspberry Pi 5 Model B Rev 1.0
SOC identifier: bcm2712
Cpu name: Cortex-A76
Ram size: 8.04 GB
Raspberry Pi OS image version: 2023-12-05
Language: en_US.UTF-8
```

**Comment by Botspot** [comment]
Interesting. I was under the impression that the cura build for 4k would work on 16k.
Was this incorrect, @smartavionics?

If so, I can update our script to select the right build based on the kernel version.

Potential complication:
I have actually been using the 4k kernel to get more apps to work. If somebody starts off with the 16k kernel, installs Cura, and then switches to 4k, then cura would probably fail to launch. I will need to decide if we need a system in place to detect this edge-case and warn the user.

**Comment by mikepaxton** [comment]
I believe the default RPiOS for Pi5 is a 16k kernel so i'm not sure it's an edge case, maybe i'm wrong though.

**Comment by smartavionics** [comment]
The 16k Cura build is built on a Pi5 running the default kernel. The other 64 bit Cura build is built on a Pi4 running buster (i.e. quite an old release). I haven't tried building on a Pi5 running the 4k kernel. I guess it is possible that such a build would also run when using the 16k kernel but then it wouldn't be usable on Pi4s running earlier systems which would be very confusing.

**Comment by theofficialgman** [comment]
@smartavionics what is the incompatibility with 16k kernel in cura that requires you to build on 16 kernel?

there aren't any known issues that don't have existing workarounds already.

**Comment by theofficialgman** [comment]
> The other 64 bit Cura build is built on a Pi4 running buster (i.e. quite an old release)

@smartavionics that will have issues on 16k pagesize kernels due to a bug in patchelf which was fixed in `0.12`. buster has `0.9`
see https://github.com/musescore/MuseScore/pull/20356 for more info

**Comment by theofficialgman** [comment]
> After installing Cura on Raspberry Pi PiOS Bookworm it crashes immediately on startup. I found that if I changed the install script to use the aarch64-16k version (which Pi 5 is), then it installs and runs great.

@smartavionics 
Tested `https://github.com/smartavionics/Cura/releases/download/4.20.17/Cura-4.20.17-mb-aarch64-16k.AppImage` on
```
OS: Ubuntu 22.04.4 LTS
OS architecture: 64-bit
Last updated Pi-Apps on: 02/24/2024
Latest Pi-Apps version: 02/24/2024
Kernel: aarch64 4.9.140-l4t
Device model: Nintendo Switch (2017)
SOC identifier: tegra-x1
Cpu name: Cortex-A57
Ram size: 3.99 GB
Language: en_US.UTF-8
```
so a 4K pagesize system

hangs when launching with `./Cura-4.20.17-mb-aarch64-16k.AppImage`
```
Found libGLESv2
<frozen zipimport>:259: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
```
works fine if 
```
./Cura-4.20.17-mb-aarch64-16k.AppImage --appimage-extract
./squashfs-root/AppRun
```

**Comment by theofficialgman** [comment]
no hang on launch with https://github.com/smartavionics/Cura/releases/download/4.20.17/Cura-4.20.17-mb-aarch64.AppImage
`./Cura-4.20.17-mb-aarch64.AppImage`

**Comment by theofficialgman** [comment]
marking as upstream bug. if @smartavionics builds on buster with patchelf 0.12+ then that build should be compatible with 4k, 16k, and 64k systems

**Comment by smartavionics** [comment]
I have now done as suggested and https://github.com/smartavionics/Cura/releases/download/4.20.17/Cura-4.20.17-mb-aarch64.AppImage should now be compatible with systems using either 4k or 16k pages.
