### ISSUE TITLE
PrusaSlicer no longer compatible with Pi4B or Pi5 OpenGL supported version

### ISSUE THREAD

**Issue by GTR2Fan** [Botspot/pi-apps#2560]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi-Apps and the issue is still not fixed. [How to update Pi-Apps?](https://pi-apps.io/wiki/getting-started/updating-pi-apps/)
- [X] IMPORTANT: I promise to respond to comments on this issue and write a good bug report https://www.softwaretestinghelp.com/how-to-write-good-bug-report/

### What happened?

App opens but with a warning of needing OpenGL 3.2 support.

### Description

Accepting the warning allows PrusaSlicer to proceed with all elements visible except for the contents of the view window which remains white.

Is this a recent update to version 2.7.2? Whatever version Pi-Apps offered a few weeks ago worked flawlessly on a Pi5 running Raspberry Pi OS (Bookworm).

Can we please have a rollback to the previously available version? Apologies for not knowing what version that was, but I take no notice of version numbers when things are working as expected.

### What are your system specs (run the following command in your terminal)?

```bash
OS: Debian GNU/Linux 12 (bookworm)
OS architecture: 64-bit
Last updated Pi-Apps on: 03/07/2024
Latest Pi-Apps version: 03/07/2024
Kernel: aarch64 6.1.0-rpi8-rpi-2712
Device model: Raspberry Pi 5 Model B Rev 1.0
SOC identifier: bcm2712
Cpu name: Cortex-A76
Ram size: 8.04 GB
Raspberry Pi OS image version: 2023-12-05
Language: en_US.UTF-8
```

**Comment by theofficialgman** [comment]
according to an upstream commit, Prusaslicer switch to a minimum requirement of OpenGL 3.2 https://github.com/prusa3d/PrusaSlicer/commit/1832c833a1747e5ff6ba5025d634182313737db7
according to that same commit it should fallback to a software renderer if that is not available (which is the case on all raspberry pi's that support a maximum of OpenGL 3.1 fully)

if there is an issue with the software renderer please report that upstream https://github.com/prusa3d/PrusaSlicer/issues

**Comment by Botspot** [comment]
@GTR2Fan, in addition to reporting the issue with the software rendering to prusaslicer, if you would like to help our development a little, try tricking PrusaSlicer into thinking that the OpenGL version actually is >= 3.2.

```
MESA_GL_VERSION_OVERRIDE=3.3 ~/PrusaSlicer.AppImage
```
I could do this myself, but if you are a heavy user of the app, then you would be more likely than I am to find an edge case.

**Comment by Botspot** [comment]
ok update: that override works fine during a brief test. It fixes the blank white area issue.
I have added the link to this issue on the prusaslicer issue, so hopefully they fix it.

For now I want to add this workaround to all pi-apps users but first I would like @GTR2Fan to try the workaround and report back that it is stable and does not crash during normal use.

**Comment by GTR2Fan** [comment]
I'm unable to get that fix to work. How are you implementing it?

**Comment by Botspot** [comment]
> MESA_GL_VERSION_OVERRIDE=3.3 /opt/PrusaSlicer.AppImage

Just close any running windows of prusaslicer, then run this command in a terminal:
```
MESA_GL_VERSION_OVERRIDE=3.3 /opt/PrusaSlicer.AppImage
```

**Comment by GTR2Fan** [comment]
It works!

I'll be using PrusaSlicer extensively over the next few days so will report back if I notice any problems.

Thank you.

**Comment by Botspot** [comment]
> It works!

Now I'm curious to know where you were trying to put that command in the first place when you said it did not work.

**Comment by GTR2Fan** [comment]
I've spent too long living in Windowsland so was attempting to add it to
the Desktop Entry launch settings via right-click Properties.

**Comment by Botspot** [comment]
> I've spent too long living in Windowsland so was attempting to add it to the Desktop Entry launch settings via right-click Properties.

Ah I see. Here is why that did not work: Only in a bash (or any) shell does `MESA_GL_VERSION_OVERRIDE=3.3` mean anything useful.
Outside of a bash shell, if you tried to run `MESA_GL_VERSION_OVERRIDE=3.3`, it would literally try to find and execute a program with that full name. Which obviously does not exist.

There is a way around this.
If you want to run PrusaSlicer and set this variable first, you cannot directly specify the variable. Instead you have to run another program first to set the variable, that then runs PrusaSlicer.
Here are 2 examples of ways to do that:
```
bash -c "MESA_GL_VERSION_OVERRIDE=3.3 /opt/PrusaSlicer.AppImage"
env MESA_GL_VERSION_OVERRIDE=3.3 /opt/PrusaSlicer.AppImage
```
Using `env` is simpler, more readible, and usually more preferable unless you need to do something more complicated directly in the desktop file.

Hopefully this info was interesting. :)

**Comment by GTR2Fan** [comment]
Very interesting and informative. Thank you.

PS I've been using PrusaSlicer 2.7.2 all day on the Pi5 without a hitch.

**Comment by Botspot** [comment]
Okay, I have added this fix to pi-apps.
See the changes here: https://github.com/Botspot/pi-apps/commit/73ff6f039a43478e6c3393f782f7041a6f1e0534

Closing this issue
