### ISSUE TITLE
Docker Engine - Install based app

### ISSUE THREAD

**Issue by FixeQyt** [Botspot/pi-apps#2561]
### What is the name of the app?

Docker Engine

### (Optional) Where is the app hosted?

https://docker.com

### About the app

Docker is a software platform that allows you to build, test, and deploy applications quickly. Docker packages software into standardized units called containers that have everything the software needs to run including libraries, system tools, code, and runtime. [(from)](https://aws.amazon.com/docker/)

### Upload file or Add PR Link

zip
[Docker Engine.zip](https://github.com/Botspot/pi-apps/files/14574411/Docker.Engine.zip)

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi-Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by theofficialgman** [comment]
please read the https://pi-apps.io/wiki/development/Creating-an-app/ documentation as well as refer to other applications in pi-apps for proper script writing.

Bullseye/Bookworm and Focal/Jammy support are required for pi-apps applications

see the app eligibility rubric https://github.com/Botspot/pi-apps/issues/185 . I do not believe docker engine falls under it.

closing this as there are so many things that have not been followed that an install script for docker engine would be an entire rewrite
