### ISSUE TITLE
Make Pycharm work faster by lowering version

### ISSUE THREAD

**Issue by szlovak** [Botspot/pi-apps#2563]
### Cool ideas?

Hi

Overall pi-apps is a great tool I hope it will be a standard solution to ease setup on RPi. When Pycharm is installed , the newest version is used which is a bad thing. It runs so unbearably slow on rpi4 even with all the plugins disabled. That’s in 64 bit since this is maintained. 32 bit version  is working much much better because it stuck on 2022.1.4 version or so. I don’t see any point to use new Pycharm on slow Rpi. Can you please make an option to choose version? I found out also that manually editing script and choosing 32bit, older version breaks dependencies, some Java issues arisen. It would be nice to be able to switch to 32bit versions. 

I guess other apps might have the very same problem of too high version installed, especially when producer clearly states that it isn’t meant to be installed on RPi like Pycharm does. 

Regards 
Adam

**Comment by theofficialgman** [comment]
I you have found regressions with performance at a particular pycharm version file those upstream with jetbrains. Such regressions affect all architectures and I have confirmed very high CPU utilization doing basic tasks on pycharm x86_64 (50%+ all core load on a modern 6 core Intel machine). I agree that is unacceptable and needs to be resolved upstream.

The version will not be lowered.

> especially when producer clearly states that it isn’t meant to be installed on RPi like Pycharm does.

There are no such claims made.
