### ISSUE TITLE
Add qFlipper?

### ISSUE THREAD

**Issue by AYEItzErik06** [Botspot/pi-apps#2564]
### What is the name of the app?

qFlipper

### Where is the app hosted?

Github, not sure how to work this app 😭 but I’ll leave a link to it.
https://github.com/flipperdevices/qFlipper

### About the app

It’s meant to help you manage a Flipper Zero via cable connection. It’s easy to use just not very user friendly to install on linux builds. My sincere apologies for this one I’m very new to this 😭.

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have read the app eligibilty rubric https://github.com/Botspot/pi-apps/issues/185 and confirmed this app is suitable for addition in Pi-Apps.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi-Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by theofficialgman** [comment]
This application is not useful for everyday raspberry pi users as it requires the user have a $170+ hardware meant for developers and hackers https://github.com/Botspot/pi-apps/issues/185 . These users are more than capable of following documentation for how to build the update software (if its not available as a prebuilt binary for their favorite platform).

> It’s easy to use just not very user friendly to install on linux builds.

its available prebuilt as an appimage for x86_64 (just download and run it) as well as a flatpak on flathub for x86_64 and aarch64 (just install through flatpak command line or your favorite graphical software store like GNOME software or KDE discover)
