### ISSUE TITLE
box64. The package hasn't been built since March 14

### ISSUE THREAD

**Issue by xboxones1** [Botspot/pi-apps#2566]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi-Apps and the issue is still not fixed. [How to update Pi-Apps?](https://pi-apps.io/wiki/getting-started/updating-pi-apps/)
- [X] IMPORTANT: I promise to respond to comments on this issue and write a good bug report https://www.softwaretestinghelp.com/how-to-write-good-bug-report/

### What happened?

https://github.com/Pi-Apps-Coders/box64-debs

### Description

The package has not been built in the [repository](https://github.com/Pi-Apps-Coders/box64-debs) since March 14

**Comment by Botspot** [comment]
Strange. You are right, but the unusual thing here is that it is still building the packages regularly. https://github.com/Pi-Apps-Coders/box64-debs/commits/master/

Asking @theofficialgman to look into this

**Comment by theofficialgman** [comment]
looking into it. the problem stems from this line https://github.com/Pi-Apps-Coders/box64-debs/blob/3767e264d835cc6e81dfb6a902663ec9b24a1238/create-deb.sh#L63 suddenly not functioning. so either a box64 change in the version output or qemu failures. will have to build box64 locally to see if the output has changed

**Comment by theofficialgman** [comment]
indeed the issue is likely caused by this commit https://github.com/ptitSeb/box64/commit/cd8bda7a29a2ef15d939890cacab02efb84e0158 where box64 can no longer be run without qemu
```
qemu-aarch64-static ./box64 -v
Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL SHA1 SHA2 PageSize:4096 Running on unknown aarch64 cpu with 4 Cores
qemu: uncaught target signal 4 (Illegal instruction) - core dumped
Illegal instruction (core dumped)
```
I'll change that function to instead parse this file [src/box64version.h](https://github.com/ptitSeb/box64/commit/986bff1c2211b1ab29118ed8c339ff92b95334f1#diff-4a1f91674c0a3c3623137f1a3b3caed237324f37d617e89a5eeef5dae368ce10)

**Comment by theofficialgman** [comment]
fixed https://github.com/Pi-Apps-Coders/box64-debs/commit/6583cb6ac1f4944b211f187081ba84b8b3e4e58b
