### ISSUE TITLE
Pi Apps fails to load correctly. No GUI Interface seen only the top menu !

### ISSUE THREAD

**Issue by Replicators2012** [Botspot/pi-apps#2567]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi-Apps and the issue is still not fixed. [How to update Pi-Apps?](https://pi-apps.io/wiki/getting-started/updating-pi-apps/)
- [X] IMPORTANT: I promise to respond to comments on this issue and write a good bug report https://www.softwaretestinghelp.com/how-to-write-good-bug-report/

### What happened?

After running the Update pi apps window will open but wont load the icons or graphics for the different sub menus or categories !

### Description

I have been running pi - apps for a while now. perhaps 2 years or maybe more. Been very  happy with it. I have not used my Rasp pi for quite a while though perhaps 3 months and its an old Pi 3 so its slow. Anyway i went to update pi apps after booting into the os and also ran the update apps from the top Task Bar at the same time. Well Pi apps seemed to get caught in a loop but after Update Apps finished uninstalling and reinstalling Libre Office then Pi apps completed successfully. However when i tried to use pi apps after the update the main gui/icons for subcategories are missing. I have a blank window. I tried rebooting but this did not work. I then tried to reinstall via terminal but it would not allow this either. So i uninstalled and reinstalled but the problem is the same ! :/ I then submitted this bug report as requested.

### What are your system specs (run the following command in your terminal)?

```bash
OS: Raspbian GNU/Linux 11 (bullseye)
OS architecture: 32-bit
Last updated Pi-Apps on: 03/23/2024
Latest Pi-Apps version: 03/24/2024
Kernel: armv7l 6.1.21-v7+
Device model: Raspberry Pi 3 Model B Rev 1.2
SOC identifier: bcm2837
Cpu name: Cortex-A53
Ram size: .92 GB
Raspberry Pi OS image version: 2023-02-21
Language: en_US.UTF-8
```

**Comment by Botspot** [comment]
Could you post a screenshot of the problem?
Could you run this command in a terminal and copy the terminal output here? `~/pi-apps/gui`

**Comment by Replicators2012** [comment]
Hi, Cant seem to copy or paste to this  webpage,nor click attach or drag n drop :/ ?
                                                           
pipe is /tmp/tmp.1QORxwnVTm
tail: warning: --retry only effective for the initial open

Updater mode: set-status

Checking for online changes... Timestamps match.
Reading list file for ''...
Entry too long on line 9, maximum length is 255 characters!
Entry too long on line 11, maximum length is 255 characters!
Entry too long on line 13, maximum length is 255 characters!
Entry too long on line 9, maximum length is 255 characters!
Entry too long on line 11, maximum length is 255 characters!
Entry too long on line 8, maximum length is 255 characters!
Done
Entry too long on line 9, maximum length is 255 characters!
Scanning apps... Done
Scanning files... Done

**Comment by Botspot** [comment]
From a terminal you can select text and then do `Ctrl Shift C`` to copy, and then on here to paste it just do a normal `Ctrl V`.
For screenshots, if drag and drop is not working, you can click the little paperclip button right above where you type text. That button lets you upload files.

**Comment by Botspot** [comment]
Also, I would rather fix any bugs, rather than just let you reinstall pi-apps to fix your problem. We don't want anyone else to encounter this problem in the future.

**Comment by Replicators2012** [comment]
I can copy paste from terminal OK but not for the jpg :/ Cant drag n drop it either and clicking on the paperclip does nothing :/ I'm probably doing something wrong as I'm very new on git hub in so much i never use it. At least I'm trying to highlight the bug and resolve the problem although I'm not a lot of help :/ I write this from my PC and the attach paperclip icon works with scroll over mouse tips working. This does not happen on my Raspberry Pi OS running the Puffin Browser as its the only browser that will run on my PI ! Will copy the jpg over to my PC via memory stick tomorrow and post it here. That should definitely work. Thanks for your assistance in this matter. Kind Regards.

**Comment by Botspot** [comment]
> I can copy paste from terminal OK but not for the jpg :/ Cant drag n drop it either and clicking on the paperclip does nothing :/ I'm probably doing something wrong as I'm very new on git hub in so much i never use it. At least I'm trying to highlight the bug and resolve the problem although I'm not a lot of help :/ I write this from my PC and the attach paperclip icon works with scroll over mouse tips working. This does not happen on my Raspberry Pi OS running the Puffin Browser as its the only browser that will run on my PI ! Will copy the jpg over to my PC via memory stick tomorrow and post it here. That should definitely work. Thanks for your assistance in this matter. Kind Regards.

Ah, Puffin Browser is very likely the problem. With puffion, basically you are remotely connecting to a server computer which loads the webpage, so file attachments would take extra work to get right as the server does not have access to your files.

Onboard browsing may be slow on the pi3 but could you try firefox?

**Comment by Replicators2012** [comment]
Yeup Seems FireFox works fine ! Picture Attached :)
![2024-03-24-213748_1440x900_scrot](https://github.com/Botspot/pi-apps/assets/2158979/f452e243-a6ad-4c4e-85f0-3d84f5370f00)

**Comment by Botspot** [comment]
ok, I would like to test your pi-apps install as it currently is. Now either I could set up a time with you to remote connect to your pi, using something like RustDesk, or you could send me your complete pi-apps folder so I could try to see for myself what went wrong.

If you are ok doing that, this command can be used to compress your pi-apps folder for easy attachment to github:
```
zip ~/pi-apps.zip ~/pi-apps -r
```
It will create a new file in your home directory called pi-apps.zip, which should be less than 25MB.

**Comment by Replicators2012** [comment]
[pi-apps.zip](https://github.com/Botspot/pi-apps/files/14746040/pi-apps.zip)

Pi-Apps.zip attached as requested :) Am i a linux super user yet ? :)

**Comment by Botspot** [comment]
OK, I have been able to reproduce this issue.
Now looking into potential fixes...

**Comment by Botspot** [comment]
For now it looks like going to pi-apps settings and switching the gui mode to one of the `yad` ones solves the problem.

**Comment by Botspot** [comment]
ok, I have fixed this now. View the fix here: https://github.com/Botspot/pi-apps/commit/8e3084d1ffc889f94540082288e7ac5bc93893d5

As far as I can tell, this has been an issue for over 9 months and nobody ever reported it.
That is hard to believe, but it looks like this was the last commit that interacted with this line of code: https://github.com/Botspot/pi-apps/commit/01cdee255afbb6d9e3ef25d3cf3b0038801bf349
And the bug was present before then, as that commit was a part of #2340 that moved the code to a different script. Not sure how long that bug was there before that.

**Comment by Replicators2012** [comment]
Thanks for the support  ! :) Problem fixed ! I went yad gui then tried dark gui again and its updated something and i can now see the gui again ! Simples :)
