### ISSUE TITLE
Need help with gnome-terminal not starting

### ISSUE THREAD

**Issue by sailnfool** [Botspot/pi-apps#2568]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [ ] I tried updating Pi-Apps and the issue is still not fixed. [How to update Pi-Apps?](https://pi-apps.io/wiki/getting-started/updating-pi-apps/)
- [X] IMPORTANT: I promise to respond to comments on this issue and write a good bug report https://www.softwaretestinghelp.com/how-to-write-good-bug-report/

### What happened?

Wine (x64) shows "Error occured when calling Terminal-run"

### Description

Popup window with error message in title bar: "Error occured when calling Terminal-run"
```
Unable to open a terminal.
Debug output below.
Default x-terminal-emulator: gnome-terminal.wrapper
Using gnome-terminal.wrapper
# Option “-x” is deprecated and might be removed in a later version of gnome-terminal.
# Use “-- ” to terminate the options and put the command line to execute after it.
[91mterminal-run: No terminal detected as it never created the pid file within 5 seconds.[39m
# Error constructing proxy for org.gnome.Terminal:/org/gnome/Terminal/Factory0: Error calling StartServiceByName for org.gnome.Terminal: Timeout was reached
```

### What are your system specs (run the following command in your terminal)?

```bash
OS: Debian GNU/Linux 12 (bookworm)
OS architecture: 64-bit
Last updated Pi-Apps on: 03/31/2024
Latest Pi-Apps version: 04/01/2024
Kernel: aarch64 6.6.20+rpt-rpi-v8
Device model: Raspberry Pi 4 Model B Rev 1.4
SOC identifier: bcm2711
Cpu name: Cortex-A72
Ram size: 7.81 GB
Raspberry Pi OS image version: 2024-03-15
Language: en_US.UTF-8
```

### (Recommended) Error log? Terminal output? Debug messages?

```bash
Unable to open a terminal.
Debug output below.
Default x-terminal-emulator: gnome-terminal.wrapper
Using gnome-terminal.wrapper
# Option “-x” is deprecated and might be removed in a later version of gnome-terminal.
# Use “-- ” to terminate the options and put the command line to execute after it.
[91mterminal-run: No terminal detected as it never created the pid file within 5 seconds.[39m
# Error constructing proxy for org.gnome.Terminal:/org/gnome/Terminal/Factory0: Error calling StartServiceByName for org.gnome.Terminal: Timeout was reached
```

**Comment by Botspot** [comment]
While in my tests, `gnome-terminal ` would display that warning about option "-x" being deprecated, it still seemed to work. Maybe your version is newer and no longer functions at all.

In commit https://github.com/Botspot/pi-apps/commit/209622cea1c14c57d75cda0c7cedb824bf62047f, I have changed the command slightly to avoid the warning. Please try again and reply if this change fixed your issue.

**Comment by sailnfool** [comment]
I uninstalled and re-installed pi-apps today.  As reported in #2569, I found the problem appears to be related to gnome-terminal in Raspberry PI OS 64.  Pi-apps ran flawlessly after I uninstalled the gnome-terminal with synaptic.  Alternatively the etc/terminal-wrap code could test for the 64-bit OS and use lxterminal instead of gnome-terminal

**Comment by sailnfool** [comment]
Sorry, I meant terminal-run not terminal-wrap

**Comment by Botspot** [comment]
Please run this in a terminal: `bash -x ~/pi-apps/etc/terminal-run 'sudo apt update'`
And send all output here.

**Comment by sailnfool** [comment]
$ bash -x ~/pi-apps/etc/terminal-run 'sudo apt update'
+ commands='sudo apt update'
+ title=
+ '[' -z '' ']'
+ DEBUG=0
+ export GTK_THEME=
+ GTK_THEME=
++ mktemp -u
+ temp_pid_file=/tmp/tmp.YX7KLRXLC3
+ commands='echo $$ > /tmp/tmp.YX7KLRXLC3
sudo apt update'
+ commands='echo -ne '\''\e]0;\a'\''
echo $$ > /tmp/tmp.YX7KLRXLC3
sudo apt update'
+ terminals='lxterminal
xfce4-terminal
mate-terminal
lxterm
uxterm
xterm
urxvt
konsole
terminator
gnome-terminal
gnome-terminal.wrapper
qterminal'
++++ command -v x-terminal-emulator
+++ readlink -f /usr/bin/x-terminal-emulator
++ basename /usr/bin/lxterminal
+ terminal=lxterminal
+ '[' 0 == 1 ']'
+ choice=
+ '[' '!' -z lxterminal ']'
+ echo 'lxterminal
xfce4-terminal
mate-terminal
lxterm
uxterm
xterm
urxvt
konsole
terminator
gnome-terminal
gnome-terminal.wrapper
qterminal'
+ grep -qFx lxterminal
+ choice=lxterminal
+ '[' 0 == 1 ']'
+ '[' -z lxterminal ']'
+ '[' lxterminal == lxterminal ']'
+ '[' '!' -z /tmp/tmp.YX7KLRXLC3 ']'
+ attempts=0
+ lxterminal -e bash -c 'echo -ne '\''\e]0;\a'\''
echo $$ > /tmp/tmp.YX7KLRXLC3
+ '[' '!' -f /tmp/tmp.YX7KLRXLC3 ']'
sudo apt update'
+ '[' 0 -gt 10 ']'
+ sleep 1
+ attempts=1
+ '[' '!' -f /tmp/tmp.YX7KLRXLC3 ']'
+ '[' 1 -gt 10 ']'
+ sleep 1
+ attempts=2
+ '[' '!' -f /tmp/tmp.YX7KLRXLC3 ']'
+ '[' 2 -gt 10 ']'
+ sleep 1
+ attempts=3
+ '[' '!' -f /tmp/tmp.YX7KLRXLC3 ']'
+ '[' 3 -gt 10 ']'
+ sleep 1
+ attempts=4
+ '[' '!' -f /tmp/tmp.YX7KLRXLC3 ']'
+ '[' 4 -gt 10 ']'
+ sleep 1
+ attempts=5
+ '[' '!' -f /tmp/tmp.YX7KLRXLC3 ']'
+ '[' 5 -gt 10 ']'
+ sleep 1
+ attempts=6
+ '[' '!' -f /tmp/tmp.YX7KLRXLC3 ']'
+ '[' 6 -gt 10 ']'
+ sleep 1
+ attempts=7
+ '[' '!' -f /tmp/tmp.YX7KLRXLC3 ']'
+ '[' 7 -gt 10 ']'
+ sleep 1
+ attempts=8
+ '[' '!' -f /tmp/tmp.YX7KLRXLC3 ']'
+ '[' 8 -gt 10 ']'
+ sleep 1
+ attempts=9
+ '[' '!' -f /tmp/tmp.YX7KLRXLC3 ']'
+ '[' 9 -gt 10 ']'
+ sleep 1
+ attempts=10
+ '[' '!' -f /tmp/tmp.YX7KLRXLC3 ']'
+ '[' 10 -gt 10 ']'
+ sleep 1
+ attempts=11
+ '[' '!' -f /tmp/tmp.YX7KLRXLC3 ']'
+ '[' 11 -gt 10 ']'
+ error 'terminal-run: No terminal detected as it never created the pid
file within 5 seconds.'
+ echo -e '\e[91mterminal-run: No terminal detected as it never created the
pid file within 5 seconds.\e[39m'
terminal-run: No terminal detected as it never created the pid file within
5 seconds.
+ exit 1

The "sudo apt update" window closed with no messages and no updates made.

Robert E. Novak
***@***.***
Philippines Cell +63 968 896 8851
USA Cell: +1 (408) 333-5488
Skype: sailnfool.ren
WhatsApp +639688968851
Linkedin: https://www.linkedin.com/in/sailnfool
Github: https://www.github.com/sailnfool

**Comment by Botspot** [comment]
How can you be certain that this issue is caused by gnome-terminal when from your command output, it looked like `terminal-run` chose to go with `lxterminal`?

**Comment by Botspot** [comment]
> The "sudo apt update" window closed with no messages and no updates made.

Please clarify. Did it open and then immediately close thereafter?

**Comment by Botspot** [comment]
I have made a couple of changes to the `terminal-run` script that handle some error cases with the /tmp folder. It is possible that is the problem here.

No need to reinstall pi-apps. To get the latest updates with a non-working terminal-run script, use this command: `~/pi-apps/updater cli-yes`

**Comment by sailnfool** [comment]
I uninstalled gnome-terminal to get a successful run.  Just running
terminal run stand-alone, it would fail.

"etc/terminal-run" would fail with gnome-terminal installed.

./terminal-run ls "ls"

Would fail.  I added:
Terminal=""
Right after:
#Try to honor the preference of update-alternatives x-terminal-emulator
terminal="$(basename "$(readlink -f "$(command -v x-terminal-emulator)")")"
terminal=""

In order to get terminal-run to even work, then I uninstalled
gnome-terminal and "pi-apps" ran fine for me.

I just re-installed gnome-terminal with "sudo synaptic" and then ran:
$ ./terminal-run ls "ls"
terminal-run: No terminal detected as it never created the pid file within
5 seconds.
[1]+  Done                    sudo synaptic
***@***.***<19:20:52>:[~/mygithub/pi-apps/etc* master]
$ # Error constructing proxy for
org.gnome.Terminal:/org/gnome/Terminal/Factory0: Error calling
StartServiceByName for org.gnome.Terminal: Timeout was reached

And saw the failing behavior above.  If I uninstall gnome-terminal,
everything works fine.

**Comment by theofficialgman** [comment]
```
# Error constructing proxy for org.gnome.Terminal:/org/gnome/Terminal/Factory0: Error calling StartServiceByName for org.gnome.Terminal: Timeout was reached
```
@sailnfool this error is outside of pi-apps control. gnome-terminal seems unable to start.
try running with `gnome-terminal` in another terminal and see if it is able to start. I expect it not to be able to.

it is worth running `tail -f /var/log/syslog` in another terminal before attempting to start gnome-terminal as well to see if there are any additional logs about your broken system

**Comment by sailnfool** [comment]
***@***.***<19:15:17>:[~/mygithub/pi-apps/etc* master]
$ DEBUG=1 ./terminal-run "cat /etc/hosts" hosts
Default x-terminal-emulator: gnome-terminal.wrapper
Using gnome-terminal.wrapper
terminal-run: No terminal detected as it never created the pid file within
5 seconds.
***@***.***<05:04:48>:[~/mygithub/pi-apps/etc* master]
$ # Error constructing proxy for
org.gnome.Terminal:/org/gnome/Terminal/Factory0: Error calling
StartServiceByName for org.gnome.Terminal: Timeout was reached

From /var/log/syslog
2024-04-03T05:04:59.696229+08:00 RP04-01 ntpd[4042]: DNS: dns_take_status:
3.debian.pool.ntp.org=>good, 8
2024-04-03T05:05:12.679417+08:00 RP04-01 ntpd[4042]: PROTO: 222.127.1.18
unlink local addr 10.0.4.14 -> <null>
2024-04-03T05:05:17.679417+08:00 RP04-01 ntpd[4042]: PROTO: 222.127.1.24
unlink local addr 10.0.4.14 -> <null>

***** After running "sudo synaptic" and removing Gnome-terminal
$ sudo synaptic &
[1] 91239
***@***.***<05:09:48>:[~/mygithub/pi-apps/etc* master]
$ ./terminal-run ls "ls"
[1]+  Done                    sudo synaptic
***@***.***<05:12:47>:[~/mygithub/pi-apps/etc* master]
/var/log/syslog
2024-04-03T05:11:34.679408+08:00 RP04-01 ntpd[4042]: PROTO: 222.127.1.26
unlink local addr 10.0.4.14 -> <null>
2024-04-03T05:12:02.426222+08:00 RP04-01 dbus-daemon[1795]: Unable to set
up transient service directory: XDG_RUNTIME_DIR "/run/user/1000" can be
written by others (mode 040770)
2024-04-03T05:12:02.462381+08:00 RP04-01 dbus-daemon[37014]: [session uid=0
pid=37012] Reloaded configuration
2024-04-03T05:12:02.475004+08:00 RP04-01 dbus-daemon[1795]: [session
uid=1000 pid=1795] Reloaded configuration
2024-04-03T05:12:17.396446+08:00 RP04-01 dbus-daemon[563]: [system]
Activating via systemd: service name='org.freedesktop.PackageKit'
unit='packagekit.service' requested by ':1.265' (uid=0 pid=91889
comm="/usr/bin/gdbus call --system --dest org.freedeskto")
2024-04-03T05:12:17.426115+08:00 RP04-01 systemd[1]: Starting
packagekit.service - PackageKit Daemon...
2024-04-03T05:12:17.444776+08:00 RP04-01 PackageKit: daemon start
2024-04-03T05:12:17.529739+08:00 RP04-01 dbus-daemon[563]: [system]
Successfully activated service 'org.freedesktop.PackageKit'
2024-04-03T05:12:17.531430+08:00 RP04-01 systemd[1]: Started
packagekit.service - PackageKit Daemon.
2024-04-03T05:13:28.679349+08:00 RP04-01 ntpd[4042]: DNS: dns_probe:
0.debian.pool.ntp.org, cast_flags:8, flags:101
Robert E. Novak
***@***.***
Philippines Cell +63 968 896 8851
USA Cell: +1 (408) 333-5488
Skype: sailnfool.ren
WhatsApp +639688968851
Linkedin: https://www.linkedin.com/in/sailnfool
Github: https://www.github.com/sailnfool

**Comment by theofficialgman** [comment]
I can't tell what you are intended to test there at all
Please use github to formulate further responses with code blocks
Follow this https://github.com/Botspot/pi-apps/issues/2568#issuecomment-2032198350 . All I asked was that you run `gnome-terminal` and tell me if it launches. If it doesn't, then it is something on your system that is broken. You can debug the issue by running `tail -f /var/log/syslog` in another terminal before attempting to start `gnome-terminal` to get additional logs

**Comment by sailnfool** [comment]
Sorry for not being clear.  I simply ran terminal-run, both with gnome-terminal uninstalled and then with gnome-terminal installed with synaptic.  With gnome-terminal installed on my system, terminal-run fails.  When gnome-terminal is uninstalled, terminal-run works fine since it invoked lxterminal.  There were no messages in /var/log/syslog in either case indicating that anything was amiss.

**Comment by Botspot** [comment]
> If I uninstall gnome-terminal, everything works fine.

But in [one of your earlier comments](https://github.com/Botspot/pi-apps/issues/2568#issuecomment-2031086233), it seemed that terminal-run chose to use lxterminal, and it still failed. Any ideas for why that happened? I thought only gnome-terminal was affected by your non-standard locale setting.

**Comment by theofficialgman** [comment]
@sailnfool in the future please don't fully change the contents of a post like that with an edit. it makes the conversation impossible to read without viewing the previous edits in context

**Comment by theofficialgman** [comment]
> But in [one of your earlier comments](https://github.com/Botspot/pi-apps/issues/2568#issuecomment-2031086233), it seemed that terminal-run chose to use lxterminal, and it still failed. Any ideas for why that happened? I thought you were saying that only gnome-terminal was affected by your non-standard locale setting.

I think its likely that lxterminal also requires UTF-8 locale, causing the same failure. I hope that this bug hasn't been re-introduced in the latest piOS image https://github.com/raspberrypi/bookworm-feedback/issues/123

**Comment by theofficialgman** [comment]
Can this issue but closed? I don't think there is anything we can do about users default terminal being non-functional due to poor user locale choices.

**Comment by sailnfool** [comment]
lxterminal did work correctly even with the incorrect locale setting.  Now
that I have fixed the locale and reinstalled gnome-terminal.  Everything
works just fine.  Sorry for the wild-goose chase, but it is good to know
that if anyone else encounters a similar issue, that you can look at their
locale issues and that there are no inherent issues in pi-apps.

On a separate note, I had used cloudbuddy as a way to access my dropbox.  I
was running some large scripts to move files around in dropbox to eliminate
many of the duplications that were found by fdupes.  The only reason that I
mention this is that in the meantime I had gotten my NFS mount of Dropbox
on an x86 machine running.  The scripts that were moving the files around
ran significantly FASTER on the NFS mount than on the cloudbuddy.  This is
NOT a critique.  I am very impressed with Cloudbuddy.  It is significantly
less user work to install a Dropbox with cloudbuddy than in setting up the
NFS mounting.  I just noted that due to the implementation (probably due to
the Dropbox APIs) that moving files around was significantly slower.  That
said, I was VERY impressed that being able to mount Dropbox without
consuming local storage on the Raspberry PI was terrific for casual use and
a simple installation step.

For over 6 years I have been writing to Dropbox customer support that it
would be nice if their proprietary application was ported to the ARM
architecture, not just to x86 architectures, but they have seen no value in
this, despite the VERY large number of Raspberry PIs that have been
installed worldwide.

On a second note, I have been running Ubuntu on the Raspberry PI 4 with 8GB
of RAM for about 5 years.  The way that I got this to work was by
installing ZRAM to increase the amount of virtual memory on my Raspberry PI
by compressing the physical memory as swap space.  This allowed Ubuntu to
actually run on a 64-bit architecture ARM with Reasonable performance
(albeit about 4-5X slower than on my Dell laptop).  For most tasks of
writing and building software, this has been more than adequate.  If you
are curious, there is an implementation (I only made minor changes to
someone else's script) that you can find at:
https://github.com/sailnfool/systemd-zram

I have abandoned Ubuntu to go to Linux Mint on my x86 boxes and Raspberry
PI OS now that there is native 64-bit support.  I found that the use of
SNAP significantly slowed all of my machines.  In addition, their new
memory management configuration caused Ubuntu to aggressively kill running
tasks while there was still plenty of memory available in Swap.  I have not
encountered those problems with Linux Mint or Raspberry PI OS.

Apologies for the long note.  I REALLY appreciate your work with PI-Apps.

Robert E. Novak
***@***.***
Philippines Cell +63 968 896 8851
USA Cell: +1 (408) 333-5488
Skype: sailnfool.ren
WhatsApp +639688968851
Linkedin: https://www.linkedin.com/in/sailnfool
Github: https://www.github.com/sailnfool

**Comment by Botspot** [comment]
> lxterminal did work correctly even with the incorrect locale setting.  Now
> that I have fixed the locale and reinstalled gnome-terminal.  Everything
> works just fine.  Sorry for the wild-goose chase, but it is good to know
> that if anyone else encounters a similar issue, that you can look at their
> locale issues and that there are no inherent issues in pi-apps.

Well it sure looks like lxterminal was the chosen terminal from your post here: https://github.com/Botspot/pi-apps/issues/2568#issuecomment-2031086233
It works now, which is what matters. Just wanted to clarify what I said earlier. Maybe lxterminal was still the chosen default, even when gnome-terminal was installed. ¯\_(ツ)_/¯

> On a separate note, I had used cloudbuddy as a way to access my dropbox.  I
> was running some large scripts to move files around in dropbox to eliminate
> many of the duplications that were found by fdupes.  The only reason that I
> mention this is that in the meantime I had gotten my NFS mount of Dropbox
> on an x86 machine running.  The scripts that were moving the files around
> ran significantly FASTER on the NFS mount than on the cloudbuddy.  This is
> NOT a critique.  I am very impressed with Cloudbuddy.  It is significantly
> less user work to install a Dropbox with cloudbuddy than in setting up the
> NFS mounting.  I just noted that due to the implementation (probably due to
> the Dropbox APIs) that moving files around was significantly slower.  That
> said, I was VERY impressed that being able to mount Dropbox without
> consuming local storage on the Raspberry PI was terrific for casual use and
> a simple installation step.

CloudBuddy uses the `rclone` project. I think that for many cloud providers, if you set up an API key and configure rclone to use it, then speeds will be higher. At least for Gdrive, rclone uses a rate-limited api key from Google, and that rate limit is applied to all rclone users who share the api key. You are on your own or that.
An easier way to get higher speeds: use rclone's built-in copy commands instead of mounting the drive. With my CloudBuddy tool, this can be done with the "browse drive" button. In that mode, there is an option to download groups of files or upload files. This is much faster, and less failure-prone.

> Apologies for the long note.

No worries. I hope my response here is helpful.

> I REALLY appreciate your work with PI-Apps.

Yeah, definitely credits to those involved. I can say that if it were just me working on the project without help from devs like @theofficialgman and the support from people like you, I would have lost interest years ago.
