### ISSUE TITLE
I cant update or install anything

### ISSUE THREAD

**Issue by t-rex131** [Botspot/pi-apps#2572]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [ ] I tried updating Pi-Apps and the issue is still not fixed. [How to update Pi-Apps?](https://pi-apps.io/wiki/getting-started/updating-pi-apps/)
- [X] IMPORTANT: I promise to respond to comments on this issue and write a good bug report https://www.softwaretestinghelp.com/how-to-write-good-bug-report/

### What happened?

whenever i try to install something using pie apps i get an error

### Description

I tried to install pie apps a little wile ago on my raspberry pi 4 model b but nothing is working i get the same error message every time i try to update or install anything also by the way i don't have access to discord to look on the server 

### What are your system specs (run the following command in your terminal)?

```bash
OS: Debian GNU/Linux 12 (bookworm)
OS architecture: 64-bit
Last updated Pi-Apps on: 04/02/2024
Latest Pi-Apps version: 04/02/2024
Kernel: aarch64 6.1.0-rpi7-rpi-v8
Device model: Raspberry Pi 4 Model B Rev 1.5
SOC identifier: bcm2711
Cpu name: Cortex-A72
Ram size: 7.81 GB
Raspberry Pi OS image version: 2023-12-05
Language: en_US.UTF-8
```

### (Recommended) Error log? Terminal output? Debug messages?

```bash
Unable to open a terminal.
Debug output below.
Default x-terminal-emulator: lxterm
Using lxterm
Usage:
  lxterminal [Options...] - LXTerminal is a terminal emulator

Options:
  -e, --command=STRING             Execute the argument to this option inside the terminal
  --geometry=COLUMNSxROWS          Set the terminal's size
  -l, --loginshell                 Execute login shell
  -t, -T, --title=,
    --tabs=NAME[,NAME[,NAME[...]]] Set the terminal's title
  --working-directory=DIRECTORY    Set the terminal's working directory
  --no-remote                      Do not accept or send remote commands
  -v, --version                    Version information

[91mterminal-run: No terminal detected as it never created the pid file within 10 seconds.[39m
```

**Comment by Botspot** [comment]
This is strange. Thank you for reporting the issue.

Did you manually mess with your terminal setup? Did you rename any files related to `lxterm`, or create a symlink to always launch lxterminal? If you do not know what these words mean, the probably not.

Please run these commands one at a time and send back the output. (copy text from a terminal with ctrl+shift+C, then paste to github.com with the usual ctrl+V)
```
readlink -f "$(command -v x-terminal-emulator)"
file /usr/bin/lxterminal
```

**Comment by Botspot** [comment]
> I don't think I did any of that i just copy and pasted the install command into the terminal
> 
> here is what i got from those commands
> 
> ```
> /usr/bin/lxterminal: ELF 64-bit LSB pie executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, BuildID[sha1]=89a686e35a54188e2a0195440c17159d86ce3ecd, for GNU/Linux 3.7.0, stripped 
> ```

That is what you got from the *second* command, how about the first one?

**Comment by Botspot** [comment]
@t-rex131 please respond.

**Comment by theofficialgman** [comment]
closing as stale.
there is no way to end up in this situation using standard configs and apt packages. The only way would be for the user to deliberately overwrite lxterm with the binary of lxterminal or change lxterm to be a symlink to lxterminal. Dangerous user modification of system controlled files is not supported.
