### ISSUE TITLE
Pi Power Tools Shrink shows error at zerofree

### ISSUE THREAD

**Issue by NoPlayBack** [Botspot/pi-apps#2574]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [ ] I tried updating Pi-Apps and the issue is still not fixed. [How to update Pi-Apps?](https://pi-apps.io/wiki/getting-started/updating-pi-apps/)
- [X] IMPORTANT: I promise to respond to comments on this issue and write a good bug report https://www.softwaretestinghelp.com/how-to-write-good-bug-report/

### What happened?

Pi Power Tools Shrink shows error at zerofree

### Description

Was using Shrink on Raspian Bullseye... reinstalled Raspian complete new as version Bookworm and 64bit.
Installed Pi-Apps & Pi Power Tools without seeing any problem.
Using shrink as usual... but this time, at the very end of the work i see the message:

Command succeeded. Now running zerofree:
sudo: unable to execute /home/pi/Pi-Power-Tools/functions/zerofree: No such file or directory

The images i wanted to shrink is definitely smaller as original.

Does this errormessage has a big impact?
Can i fix that?

### What are your system specs (run the following command in your terminal)?

```bash
OS: Debian GNU/Linux 12 (bookworm)
OS architecture: 64-bit
fatal: not a git repository (or any of the parent directories): .git
date: option requires an argument -- 'd'
Try 'date --help' for more information.
Last updated Pi-Apps on:
Kernel: aarch64 6.6.20+rpt-rpi-v8
Device model: Raspberry Pi 4 Model B Rev 1.5
SOC identifier: bcm2711
Cpu name: Cortex-A72
Ram size: 7.80 GB
Raspberry Pi OS image version: 2024-03-15
Language: en_US.UTF-8
```

### (Recommended) Error log? Terminal output? Debug messages?

```bash
Command succeeded. Now running zerofree:
sudo: unable to execute /home/pi/Pi-Power-Tools/functions/zerofree: No such file or directory
```

**Comment by Botspot** [comment]
Pi-Power-Tools is not well maintained. Not sure about the zerofree error, but yeah that is a final step and with its failure you should still be fine. Zerofree only usually shrinks an IMG by a few percentage points.

**Comment by Botspot** [comment]
Open a new issue on the https://github.com/Botspot/Pi-Power-Tools repo if you need anything else.
