### ISSUE TITLE
Steam from Pi-Apps does not use Wine installed from Pi-Apps.

### ISSUE THREAD

**Issue by ninjakitty844** [Botspot/pi-apps#2579]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi-Apps and the issue is still not fixed. [How to update Pi-Apps?](https://pi-apps.io/wiki/getting-started/updating-pi-apps/)
- [X] IMPORTANT: I promise to respond to comments on this issue and write a good bug report https://www.softwaretestinghelp.com/how-to-write-good-bug-report/

### What happened?

Steam installed from Pi-Apps uses Proton only. Even if you installed Wine and Box86/64 from Pi-Apps, it does not use Wine.

### Description

When you install Steam from Pi-Apps, it will not use Wine that you installed from Pi-Apps. It tries to instead use Proton, which in my experience never successfully runs any Windows games on Pi (is it possible that Proton just doesn't work at all on Pi?)

### What are your system specs (run the following command in your terminal)?

```bash
OS: Debian GNU/Linux 12 (bookworm)
OS architecture: 64-bit
Last updated Pi-Apps on: 04/19/2024
Latest Pi-Apps version: 04/18/2024
Kernel: aarch64 6.6.26-v8+
Device model: Raspberry Pi 5 Model B Rev 1.0
SOC identifier: bcm2712
Cpu name: Cortex-A76
Ram size: 7.94 GB
Raspberry Pi OS image version: 2024-03-15
Language: en_US.UTF-8
```

**Comment by theofficialgman** [comment]
This is not a bug.

Steam does not use system Wine. It uses proton. Proton functions for many windows applications. Keep in mind that many windows games are DX11-12 and this requires a vulkan driver to be installed on your system (apt package `mesa-vulkan-drivers`) for the DX to vulkan translation layer
