### ISSUE TITLE
FreeTube

### ISSUE THREAD

**Issue by techcoder20** [Botspot/pi-apps#258]
@Botspot This is a must add app. Its so cool. https://freetubeapp.io/  FreeTube is a YouTube client for Windows, Mac, and Linux built around using YouTube more privately. You can enjoy your favorite content and creators without your habits being tracked. All of your user data is stored locally and never sent or published to the internet. FreeTube grabs data by scraping the information it needs (with either local methods or by optionally utilizing the Invidious API). With many features similar to YouTube, FreeTube has become one of the best methods to watch YouTube privately on desktop. 

[FreeTube.zip](https://github.com/Botspot/pi-apps/files/5830999/FreeTube.zip)

**Comment by Itai-Nelken** [comment]
you can also subscribe to channels, see comments, set video resolution, share the video, download it, and probably more.
though I still prefer youtubuddy for most of my needs.

**Comment by Itai-Nelken** [comment]
also I think the developer of FreeTube is going to add "official" armhf debs to the releases.

**Comment by techcoder20** [comment]
> also I think the developer of FreeTube is going to add "official" armhf debs to the releases.

Maybe, I have used the archive.org link for now

**Comment by Botspot** [comment]
I'm more concerned about performance - does it play videos well?

I'd doubt the player it uses would be as efficient as VLC.

**Comment by Botspot** [comment]
> I'm more concerned about performance - does it play videos well?
> 
> I'd doubt the player it uses would be as efficient as VLC.

Just what I was worried about - video playback is choppy, frequently pauses to load, and uses 100% CPU.  
Compare that to VLC used in YouTubuddy, which usually stays below 30% at 1080p 60fps.

Is there a way around this?

**Comment by Itai-Nelken** [comment]
> I'm more concerned about performance - does it play videos well?
> 
> I'd doubt the player it uses would be as efficient as VLC.

yes, it plays them as good as vlc

**Comment by Itai-Nelken** [comment]
>Just what I was worried about - video playback is choppy, frequently pauses to load, and uses 100% CPU. At 720p.
Compare that to VLC used in YouTubuddy, which usually stays below 30% at 1080p 60fps.

weired, for me it plays smoothly without using to much cpu at 1080p.

**Comment by Itai-Nelken** [comment]
here is a video of a 1080p30 video playing perfectly fine without using more cpu than vlc (when in fullscreen and using ulauncher to make the "dock" appear it uses the sam amount of cpu):

https://user-images.githubusercontent.com/70802936/104951775-d8796680-59cb-11eb-8eb5-8461e92ede2a.mp4

I do prefer the download feature of youtubuddy, it works way better (this one only opens a web browser with the video (not the youtube website) and then you need to right click and "save as...")

**Comment by Botspot** [comment]
Here's what I see:  
https://user-images.githubusercontent.com/54716352/104965452-5fb2e400-59a4-11eb-906a-93e26dbc7c0b.mp4

Notice the solid 100% CPU usage, and the extremely choppy video.

**Comment by Itai-Nelken** [comment]
@Botspot maybe its a 60fps video? try this one: https://www.youtube.com/watch?v=JDyRV0IMANY its the one I used and its 1080p30.
then we'll now if 60fps video is whats causing it.

**Comment by Itai-Nelken** [comment]
I just checked with a 1080p60 video and it was verry stutery and used all cpu, but when playing anything up to 1080p30 it works great.

**Comment by Itai-Nelken** [comment]
@Botspot I just thought about something:

I don't think freetube needs to be a replacment for youtubuddy - that is **the best** way to watch youtube on a pi - but an alternative to the youtube website (both perform the same), so if all you want is to subscribe to channels, read comments etc but don't want to use the youtube website and/or a google account (because of privacy), freetube is the best. if you want to watch youtube in the smoothest and best way, youtubuddy+vlc are the best.

I think there are a lot of people that will prefer privacy over performance while still being able to subscribe to channels, read the comments etc.

**Comment by Botspot** [comment]
> @Botspot I just thought about something:
> 
> I don't think freetube needs to be a "replacment" for youtubuddy - youtubuddy _is **the best**_ way to watch youtube on a pi - but an alternative to the _youtube website_ (both perform the same), so if all you want is to subscribe to channels, read comments etc but don't want to use the youtube website and/or a google account (because of privacy), freetube is the best. if you want to watch youtube in the smoothest and best way, youtubuddy+vlc are the best.
> 
> I think there are a lot of people that will prefer privacy over performance while still being able to subscribe to channels, read comments etc.

I agree that many people prefer the familiar layout of YouTube. But, as far as I can tell, FreeTube has much worse performance than the real YouTube website!  
That needs to be worked on.

**Comment by techcoder20** [comment]
Should I close this ?

**Comment by Botspot** [comment]
> Should I close this then ?

No, we should try to figure out why the video performance is worse, and see what can be done to improve it.

As I recall, RPi's Chromium uses the h264ify Chrome Extension to force YouTube to use a certain hardware accelerated codec.  
My guess is that FreeTube is not using this codec.

So we need to find out how to change the codec.

PS. This morning I discovered FreeTube is basically an Electron App!

**Comment by Itai-Nelken** [comment]
>As I recall, RPi's Chromium uses the h264ify Chrome Extension to force YouTube to use a certain hardware accelerated codec.

@Botspot h264ify simply forces youtube to play the video in 30fps, and freetube is capable of playing 1080p30 but uses all cpu, youtube website performs a bit worse, but uses less cpu.

**Comment by Botspot** [comment]
> > As I recall, RPi's Chromium uses the h264ify Chrome Extension to force YouTube to use a certain hardware accelerated codec.
> 
> @Botspot h264ify simply forces youtube to play the video in 30fps, and freetube is capable of playing 1080p30 but uses all cpu, youtube website performs a bit worse, but uses less cpu.

No, I think there is more to it. Not only can you tell h264ify to allow 60fps videos, the term "h264" refers to a certain video codec.  
Time for some research!

**Comment by Itai-Nelken** [comment]
you are right, it forces youtube to use the h264 codec instead of vp8/vp9.
here is the description from the chrome web store:
```
Makes YouTube stream H.264 videos instead of VP8/VP9 videos
Try h264ify if YouTube videos stutter, take up too much CPU, eat battery life, or make your laptop hot.

By default, YouTube streams VP8/VP9 encoded video. However, this can cause problems with less powerful machines because VP8/VP9 is not typically hardware accelerated.

In contrast, H.264 is commonly hardware accelerated by GPUs, which usually means smoother video playback and reduced CPU usage. h264ify makes YouTube stream H.264 videos instead of VP8/VP9 videos.

Github: https://github.com/erkserkserks/h264ify
```

**Comment by mobilegmYT** [comment]
> > @Botspot I just thought about something:
> > I don't think freetube needs to be a "replacment" for youtubuddy - youtubuddy _is **the best**_ way to watch youtube on a pi - but an alternative to the _youtube website_ (both perform the same), so if all you want is to subscribe to channels, read comments etc but don't want to use the youtube website and/or a google account (because of privacy), freetube is the best. if you want to watch youtube in the smoothest and best way, youtubuddy+vlc are the best.
> > I think there are a lot of people that will prefer privacy over performance while still being able to subscribe to channels, read comments etc.
> 
> I agree that many people prefer the familiar layout of YouTube. But, as far as I can tell, FreeTube has much worse performance than the real YouTube website!
> That needs to be worked on.

For me, it runs quite fast.

**Comment by Itai-Nelken** [comment]
> For me, it runs quite fast.

it runs well for anything 30fps, it can't handle 60fps 720 or 1080 on the pi.

**Comment by Botspot** [comment]
Too bad you can't disable 60fps in the settings.

**Comment by chunky-milk** [comment]
> > also I think the developer of FreeTube is going to add "official" armhf debs to the releases.
> 
> Maybe, I have used the archive.org link for now

@techcoder20 where can i find the armhf .deb files?

**Comment by techcoder20** [comment]
@chunky-milk https://archive.org/download/freetube_0.11.1_armv7l/freetube_0.11.1_armv7l.deb

**Comment by Botspot** [comment]
I just figured out: Disabling the compositor makes 60fps videos work a lot better with less CPU usage.  
This discovery will be mentioned in the description and now I'm fine with adding it.

One thing though: FreeTube is announcing that there is a later version available. Can it be updated before I add it to the store?

**Comment by Itai-Nelken** [comment]
> I just figured out: Disabling the compositor makes 60fps videos work a lot better with less CPU usage.
> This discovery will be mentioned in the description and now I'm fine with adding it.
> 
> One thing though: FreeTube is announcing that there is a later version available. Can it be updated before I add it to the store?

I'll compile a newer version.

**Comment by Itai-Nelken** [comment]
[FreeTube.zip](https://github.com/Botspot/pi-apps/files/5945827/FreeTube.zip)
here.
I also updated the 64bit version to use the lates arm64 build (same as mine, 0.12.2).

**Comment by Botspot** [comment]
Added to Pi-Apps with commit 73fa70005dcc1e78cc78df1ab5932c6d28f03b22.
