### ISSUE TITLE
Add script install app Qalculate! to Pi-Apps 

### ISSUE THREAD

**Issue by PyProgrammer1** [Botspot/pi-apps#2582]
### What is the name of the app?

Qalculate!

### Where is the app hosted?

Website

### About the app

Qalculate! is a lightweight calculator. It can graph, solve math problems, and much more.

### Upload file or Add PR Link

[Qalculate!.zip](https://github.com/Botspot/pi-apps/files/15075412/Qalculate.zip)

### Confirmations

- [x] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi-Apps app list.
- [X] I have read and followed the [creating an app for Pi-Apps documentation](https://pi-apps.io/wiki/development/Creating-an-app/).
- [X] I have confirmed that this app can run on all [Pi-Apps supported systems](https://pi-apps.io/install/).

**Comment by Botspot** [comment]
Your zip file is empty. :(

**Comment by PyProgrammer1** [comment]
[Qalculate!.zip](https://github.com/Botspot/pi-apps/files/15076362/Qalculate.zip)

**Comment by theofficialgman** [comment]
Closing as invalid. Please read the documentation as linked in the issue template. We do not support snap based installs and definitely cannot assume that snap is installed and available.
