### ISSUE TITLE
Suggestion enchantment add box86wine to RetroPie 

### ISSUE THREAD

**Issue by actraiser30** [Botspot/pi-apps#2587]
### Cool ideas?

Is it possible to add an option to ask on Installing to add box86/wine to RetroPie installation if it exist of course??

Thanks

**Comment by theofficialgman** [comment]
Ask the retropie developers to implement your suggestion of previewing wine applications

**Comment by actraiser30** [comment]
I doupt they care to do it,they don't do anything useful 

Thanks anyway
