### ISSUE TITLE
maybe found a bug with snap-store uninstall

### ISSUE THREAD

**Issue by Itai-Nelken** [Botspot/pi-apps#259]
when uninstalling the snap store, purging `snapd` will give a error that it can't remove `/var/cache/snapd/aux`
I fixed it by running `sudo rm -rf /var/cache/snapd/aux` and then `sudo apt purge snapd -y`

**Comment by Itai-Nelken** [comment]
also remove the question label please.

**Comment by techcoder20** [comment]
Hmm I dont remember uninstalling snapd in the uninstall script. We decided not to uninstall snapd as some of the packages which were installed with snap might get messed up. Will have to check again.

**Comment by Itai-Nelken** [comment]
think @Botspot added it, so closing this issue
