### ISSUE TITLE
GDL Launcher: Error: Uncaught Fatal Exception; code: 1

### ISSUE THREAD

**Issue by Ertzuita** [Botspot/pi-apps#2599]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [ ] I tried updating Pi-Apps and the issue is still not fixed. [How to update Pi-Apps?](https://pi-apps.io/wiki/getting-started/updating-pi-apps/)
- [X] IMPORTANT: I promise to respond to comments on this issue and write a good bug report https://www.softwaretestinghelp.com/how-to-write-good-bug-report/

### What happened?

GDL Launcher: Error: Uncaught Fatal Exception; code: 1

### Description

There stands that i have Java Runtime  file version 65, but it only recognizes files up to 61. What should I do?

### What are your system specs (run the following command in your terminal)?

```bash
OS: Ubuntu 23.10
OS architecture: 64-bit
Last updated Pi-Apps on: 05/30/2024
Latest Pi-Apps version: 05/30/2024
Kernel: aarch64 6.5.0-1017-raspi
Device model: Raspberry Pi 5 Model B Rev 1.0
SOC identifier: bcm2712
Cpu name: Cortex-A76
Ram size: 7.93 GB
Language: en_US.UTF-8
```

### (Recommended) Error log? Terminal output? Debug messages?

```bash
(node:8572) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 13)
```

**Comment by theofficialgman** [comment]
It is GDLauncher. Not GDL Launcher.

Can you please paste the full error log when launching from terminal as well as describe what you are doing when you encounter this error (ie: is it when starting the launcher or starting a particular version of Minecraft via the launcher)?

**Comment by theofficialgman** [comment]
Closing as user error. For minecraft versions greater than or equal to 1.21 you need to provide java 21 and select it manually in the instance settings. 

https://github.com/gorilla-devs/GDLauncher/issues/1613#issuecomment-2104136498

this version of GDLauncher (the last remaining open source version) has been discontinued by upstream prior to minecraft 1.21 and java 21
