### ISSUE TITLE
Possible Admin Issue on some installs.

### ISSUE THREAD

**Issue by Oldbenone** [Botspot/pi-apps#26]
Hi, I have the same issues, in my install of PI-Apps it seems to be a Admin (Super User) problem. Cant figure out how to make it run as super user I'm just a Noob, same errors but says no privileges to create or have access to etc errors. 
It does download packages and installs most of them in the terminal window. Example .. Arduino installed ...while installing in terminal creating shortcuts, access was denied to some folders (although I could see desktop icon being created on desktop) it then deleted the icons on desktop and in start-menu. I think the problem is just admin rights on terminal window side of Program.
I did run Main Program as sudo command in terminal but gave me the same errors. The Program seems to open terminal as normal user.
I hope this info is helpful.

**Comment by Botspot** [comment]
Wow you're posting this everywhere! XD  
I replied to you [here](https://www.youtube.com/watch?v=zxyWQ3FV98I&lc=UgwfzxxN23ayMZ7Tcih4AaABAg.9EyxgOvf4789F-ZydFnrD-), but I don't mind repeating myself. ;)  

With the Arduino app, I have it run the arduino install script twice - once as root, and once as user pi.
Try launching arduino by running /home/pi/arduino-1.8.13/arduino in a terminal.

**Comment by Oldbenone** [comment]
Hi sorry for the double posting just thought it would help you and others.
The apps themselves do run. if i open start menu and type the program exactly it shows run XX you can then click on it and it opens up and works
just the icons seems to be missing in my instance.

**Comment by Botspot** [comment]
> just the icons seems to be missing in my instance.

Do you mean the arduino icon is missing? Which icons?

**Comment by Oldbenone** [comment]
Hi I will try and explain.
When i run your program and install lets say arduino it opens A terminal and  runs a install script while running i can see it tries to create/access folders with reply "home/pi/pi-apps/data/settings/debug mode': No such file or directory" multiple times.
While still running script i can see Arduino icon appear on desktop and when script finish the icon disappear again.
i would asume the same goes for the shortcuts/icons in start menu.
Although i can run the program from start menu search (if i type it exactly as your installer describes it) it works fine.

i do not know much about linux systems so sorry for the low quality of my response.
Thanks for the aplications like this that can help all of us (windows users) to move away from Windows.

**Comment by mobilegmYT** [comment]
I know many other people have had issues with debug mode. I think its because it has a space in its name.

**Comment by Botspot** [comment]
> I know many other people have had issues with debug mode. I think its because it has a space in its name.

I've seen many reports as well. Looking into it right now.

**Comment by Oldbenone** [comment]
While installing Commander pi
Running pkg-install...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
output: Reading package lists...
Building dependency tree...
Reading state information...
python3-pil is already the newest version (5.4.1-2+deb10u2).
python3-pil.imagetk is already the newest version (5.4.1-2+deb10u2).
python3-tk is already the newest version (3.7.3-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
No new packages to install. Nothing to do!
fatal: destination path 'CommanderPi' already exists and is not an empty directory.
failed to download repository!

Command failed!
Close this window to exit.
it displayed other errors the first time that I ran the insaller.
i did uninstall and reinstall now with this error.
and corrupted next to icon in program.
My problems are probably only on my machine/operating system anyway.
Thank you. i will check back tomorrow.

**Comment by Botspot** [comment]
Well, looks like you tried to install CommanderPi once before.
Are you sure CommanderPi is not installed already?

**Comment by Botspot** [comment]
@Oldbenone any updates? I'd like to see this issue solved.

**Comment by Oldbenone** [comment]
Hi, I will close the issue as I don't have time till the weekend to look into this Quark.
Thanks again for the feedback, and i will definitely make use of this great peace of software.

**Comment by Botspot** [comment]
I was not meaning to rush you. Until your problem is solved, I have nothing against leaving the issue open.

**Comment by Oldbenone** [comment]
Ok will keep you updated closer to the weekend, Thanks.

**Comment by Oldbenone** [comment]
PS is there a way to temporarily disable the automatic closing of the terminal window? So that i can capture the data it displays for you.

**Comment by Botspot** [comment]
> PS is there a way to temporarily disable the automatic closing of the terminal window? So that i can capture the data it displays for you.

Easy: change line 49 of the `manage` script to "sleep infinity".

**Comment by Oldbenone** [comment]
Hi I tried to edit the Manage script, also no permission when saving, although i opened with sudo su command (with red banner warning and all). So i think this is just my install being difficult with me. 
This is not the first time that i have Admin permission problems with my build, I just don't know how to fix it.
Do you per chance know how to always be Super User from login. Personally I don't care about hacking i won't store important files on my Raspberry anyway. 
I will Install a fresh Raspberry OS on Another card and let you know the results.. My Guess is it will run 100%

**Comment by Botspot** [comment]
> Hi I tried to edit the Manage script, also no permission when saving, although i opened with sudo su command (with red banner warning and all). So i think this is just my install being difficult with me.

I agree, that does not sound normal.  
No matter how hard I try, I mess up my OS up past the point of no return about once a year. And that is despite frequent backups. So I keep a record of everything I install/uninstall, to make it easier to redo my OS.

> I will Install a fresh Raspberry OS on Another card and let you know the results.. My Guess is it will run 100%

Hopefully it will. Keep me updated.

**Comment by Oldbenone** [comment]
This is one of the errors i got opening Pi Apps after reboot the Pi Apps desktop icon also disappeared so i used this to open in terminal. Just lots of weirdness. (this specific error seems to relate somewhat to internet access) the missing folders i get on almost all programs i install from Pi Apps.
 
pi@raspberrypi:~ $ sudo ./pi-apps/gui
Timestamps match.
Reading list file...
error: RPC failed; curl 56 GnuTLS recv error (-9): Error decoding the received TLS packet.
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
/home/pi/pi-apps/updater: line 70: cd: /home/pi/pi-apps/update/pi-apps: No such file or directory
Button: 252
pi@raspberrypi:~ $

PS how do I uninstall Pi Apps completely to reinstall, it might be  worth trying? I did with terminal sudo apt remove .. but returns no such file or directory. (also obviously, i think, not listed in ad remove programs.

**Comment by Botspot** [comment]
Is yad installed? Are you connected to the internet?

**Comment by Botspot** [comment]
> PS how do I uninstall Pi Apps completely to reinstall, it might be worth trying? I did with terminal sudo apt remove .. but returns no such file or directory. (also obviously, i think, not listed in ad remove programs.

You can uninstall Pi-Apps with: `/home/pi/pi-apps/uninstall`

**Comment by Oldbenone** [comment]
Ok Thanks. 
Fresh install of rasp. on slow class 4 sd
same/similar error with Arduino
--2020-10-23 18:29:20--  https://downloads.arduino.cc/arduino-1.8.13-linuxarm.tar.xz
Resolving downloads.arduino.cc (downloads.arduino.cc)... 172.67.5.5, 104.22.49.75, 104.22.48.75, ...
Connecting to downloads.arduino.cc (downloads.arduino.cc)|172.67.5.5|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 96485196 (92M) [binary/octet-stream]
Saving to: ‘arduino-1.8.13-linuxarm.tar.xz’

arduino-1.8.13-linu 100%[===================>]  92.01M   491KB/s    in 3m 17s  

2020-10-23 18:32:38 (478 KB/s) - ‘arduino-1.8.13-linuxarm.tar.xz’ saved [96485196/96485196]


Adding desktop shortcut, menu item and file associations for Arduino IDE...touch: cannot touch '/home/pi/.local/share/icons/hicolor/.xdg-icon-resource-dummy': No such file or directory
touch: cannot touch '/home/pi/.local/share/icons/hicolor/.xdg-icon-resource-dummy': No such file or directory
touch: cannot touch '/home/pi/.local/share/icons/hicolor/.xdg-icon-resource-dummy': No such file or directory
touch: cannot touch '/home/pi/.local/share/icons/hicolor/.xdg-icon-resource-dummy': No such file or directory
touch: cannot touch '/home/pi/.local/share/icons/hicolor/.xdg-icon-resource-dummy': No such file or directory
touch: cannot touch '/home/pi/.local/share/icons/hicolor/.xdg-icon-resource-dummy': No such file or directory
touch: cannot touch '/home/pi/.local/share/icons/hicolor/.xdg-icon-resource-dummy': No such file or directory
touch: cannot touch '/home/pi/.local/share/icons/hicolor/.xdg-icon-resource-dummy': No such file or directory
touch: cannot touch '/home/pi/.local/share/icons/hicolor/.xdg-icon-resource-dummy': No such file or directory
touch: cannot touch '/home/pi/.local/share/icons/hicolor/.xdg-icon-resource-dummy': No such file or directory
touch: cannot touch '/home/pi/.local/share/icons/hicolor/.xdg-icon-resource-dummy': No such file or directory
touch: cannot touch '/home/pi/.local/share/icons/hicolor/.xdg-icon-resource-dummy': No such file or directory
touch: cannot touch '/home/pi/.local/share/icons/hicolor/.xdg-icon-resource-dummy': No such file or directory
touch: cannot touch '/home/pi/.local/share/icons/hicolor/.xdg-icon-resource-dummy': No such file or directory
touch: cannot touch '/home/pi/.local/share/icons/hicolor/.xdg-icon-resource-dummy': No such file or directory
touch: cannot touch '/home/pi/.local/share/icons/hicolor/.xdg-icon-resource-dummy': No such file or directory
touch: cannot touch '/home/pi/.local/share/icons/hicolor/.xdg-icon-resource-dummy': No such file or directory
touch: cannot touch '/home/pi/.local/share/icons/hicolor/.xdg-icon-resource-dummy': No such file or directory



ln: failed to create symbolic link '/usr/local/bin/arduino': Permission denied
Adding symlink failed. Hope that's OK. If not then rerun as root with sudo.
 done!
Adding desktop shortcut, menu item and file associations for Arduino IDE...  

Could not get the last part, still can not edit Mange script.
the desktop icon of arduino was created i could see it, and then after installer closed the icon disappeared from desktop.
i Have a 2gig raspberry pi4. if this makes any difference.

**Comment by Oldbenone** [comment]
pi kiss installed 
First try with network error.
Second try installed with menu icon and working as intended.
My pi is connected with Ethernet to my rooter. i do not use WiFi.

**Comment by Oldbenone** [comment]
Eathernet is on 4meg line. so slow internet.

**Comment by mobilegmYT** [comment]
Hmm. I do know that pikiss has an issue saying it can't connect to the internet. Just edit the desktop file and add -ni to the end of it

**Comment by Oldbenone** [comment]
It is not a problem for me it is working now, i just mentioned it so it could point to a possible cause of the problems that I am experiencing, and solution maybe.

**Comment by Botspot** [comment]
> Could not get the last part, still can not edit Mange script.

Please try running this:

```
sudo nano ~/pi-apps/manage
```

> the desktop icon of arduino was created i could see it, and then after installer closed the icon disappeared from desktop.

That is normal. I made the install script [delete the desktop launcher](https://github.com/Botspot/pi-apps/blob/master/apps/Arduino/install#L17). This is just my personal preference, as I prefer launching Arduino from Menu -> Programming -> Arduino.

**Comment by Oldbenone** [comment]
DOH, I completely forgot about nano, worked Thanks.
Intel inside - idiot outside
AMD inside - Idiot outside
ARM inside - still idiot outside

**Comment by Botspot** [comment]
> OK so for the most part Pi-Apps seems to work on fresh install then, except for my slow internet, which could in some cases cause some Aps that rely on internet to misbehave. Am i right in my assumption?
> (Like i had with Pi-Kiss)

I would think so. Yes. Good to know your issues have been solved.
