### ISSUE TITLE
Doom 3 - video card / driver combo doesn't support necessary features

### ISSUE THREAD

**Issue by Brandoskey** [Botspot/pi-apps#260]
After installing from pi-apps and attempting to run the game I get this error

This is on a fresh install of rasbian with everything updated

> ----- Initializing OpenGL -----
> 
> Initializing OpenGL subsystem
> Using 8 color bits, 24 depth, 8 stencil display
> OpenGL vendor: Broadcom
> OpenGL renderer: V3D 4.2
> OpenGL version: OpenGL ES 3.1 Mesa 19.3.2
> X..GL_ARB_multitexture not found
> X..GL_ARB_texture_env_combine not found
> X..GL_ARB_texture_cube_map not found
> X..GL_ARB_texture_env_dot3 not found
> X..GL_ARB_texture_env_add not found
> X..GL_ARB_texture_non_power_of_two not found
> X..GL_ARB_texture_compression not found
> X..GL_EXT_texture_filter_anisotropic not found
> X..GL_EXT_texture_lod not found
> X..GL_1.4_texture_lod_bias not found
> X..GL_EXT_shared_texture_palette not found
> X..GL_EXT_texture3D not found
> X..GL_EXT_stencil_wrap not found
> X..GL_EXT_stencil_two_side not found
> ... don't have GL2.0+ glStencilOpSeparate()
> X..GL_ARB_vertex_buffer_object not found
> X..GL_ARB_vertex_program not found
> X..GL_ARB_fragment_program not found
> TODO: Sys_SetClipboardData
> ********************
> ERROR: The current video card / driver combination does not support the necessary features.
> ********************
> Sys_Error: Error during initialization
> shutdown terminal support
> Looks like dhewm3 1.5.1rc2 crashed with signal SIGSEGV (11) - sorry!
> 
> Backtrace:
>   ./dhewm3() [0x1da5e8]
>   /lib/arm-linux-gnueabihf/libc.so.6(__default_sa_restorer+0) [0xb6953120]
>   ./dhewm3() [0x24d36c]
>   ./dhewm3() [0xed0dc]
> 
> Segmentation fault

**Comment by Botspot** [comment]
What operating system are you using?

**Comment by Brandoskey** [comment]
Old habits, raspberry pi os Jan 11th release

**Comment by Botspot** [comment]
Someone on the Botspot Discord server says they think it's due to RPiOS recently downgrading Mesa. Interesting.

**Comment by Brandoskey** [comment]
That was my first thought, but I was able to update mesa to the proper version using pi KISS' mesa upgrade script. Doom3 now shows the proper mesa version after failing to run, but all the other errors from my initial post are still there

**Comment by Botspot** [comment]
> That was my first thought, but I was able to update mesa to the proper version using pi KISS' mesa upgrade script. Doom3 now shows the proper mesa version after failing to run, but all the other errors from my initial post are still there

That is strange.  
Perhaps someone on the Raspberry Pi Forums knows?

**Comment by mobilegmYT** [comment]
> That was my first thought, but I was able to update mesa to the proper version using pi KISS' mesa upgrade script. Doom3 now shows the proper mesa version after failing to run, but all the other errors from my initial post are still there

You seem to be using a old version, I think a recent apt update downgraded mesa. Run this to go back up to mesa 20.3: `wget https://twisteros.com/Mesa-v20-3-RPi4.run && chmod +x Mesa-v20-3-RPi4.run && ./Mesa-v20-3-RPi4.run && sudo rm Mesa-v20-3-RPi4.run`.

**Comment by Brandoskey** [comment]
In my last reply I mention I updated mesa to, same issue.

The twister updater doesn't seem to work on raspberry pi is, had to use the upgrade script in pi kiss

**Comment by Botspot** [comment]
Doom 3 seems to be working fine again.

Nobody on the team knows what caused it to break, or what's caused it to work again now. But since it's working reliably again, I've un-hid it.
