### ISSUE TITLE
Web cloning you may have security problems on your official Raspberry PI App installation

### ISSUE THREAD

**Issue by PrincessJanniot** [Botspot/pi-apps#2601]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi-Apps and the issue is still not fixed. [How to update Pi-Apps?](https://pi-apps.io/wiki/getting-started/updating-pi-apps/)
- [X] IMPORTANT: I promise to respond to comments on this issue and write a good bug report https://www.softwaretestinghelp.com/how-to-write-good-bug-report/

### What happened?

App suppository was empty

### Description

The Application appendage was empty

### What are your system specs (run the following command in your terminal)?

```bash
Raspberry PI 3 vi.2
running lastest OS
```

### (Recommended) Error log? Terminal output? Debug messages?

```bash
Unfortunately my LX Terminal was closed automatically
```

**Comment by theofficialgman** [comment]
closing as invalid issue. no comprehensible issue is presented.

Please follow our official installation instructions and make sure there are no error messages during install.
