### ISSUE TITLE
Freetube does not show up in bookworm 32 bit

### ISSUE THREAD

**Issue by archisman-panigrahi** [Botspot/pi-apps#2602]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi-Apps and the issue is still not fixed. [How to update Pi-Apps?](https://pi-apps.io/wiki/getting-started/updating-pi-apps/)
- [X] IMPORTANT: I promise to respond to comments on this issue and write a good bug report https://www.softwaretestinghelp.com/how-to-write-good-bug-report/

### What happened?

FreeTube does not show up and when I try to install freetube by searching it says it is not compatible with bookworm 32 bit

### Description

Debian installer for Freetube for armhf is available on its website and it works just fine. But pi-apps says it is not compatible, which is probably a bug.

### What are your system specs (run the following command in your terminal)?

```bash
OS: Raspbian GNU/Linux 12 (bookworm)
OS architecture: 32-bit
Last updated Pi-Apps on: 06/01/2024
Latest Pi-Apps version: 05/31/2024
Kernel: armv7l 6.4.0-rc6-next-20230616-g032fe376bdff-dirty
Device model: Surface with Windows RT PV
SOC identifier: jetson-unknown
Cpu name: Cortex-A9
Ram size: 1.95 GB
Raspberry Pi OS image version: 2024-03-15
Language: en_US.UTF-8
```

### (Recommended) Error log? Terminal output? Debug messages?
![Screenshot from 2024-06-01 09-19-06](https://github.com/Botspot/pi-apps/assets/3063132/caa5698c-c253-45a7-87f2-cd90e43ece94)

Note: I am using Raspberry Pi OS Bookworm on a Surface RT. It is the official image with a custom kernel.

**Comment by theofficialgman** [comment]
This is not a but

FreeTube is intentionally hidden on jetson devices as playback within it is typically not hardware accelerated (on our most popular jetson devices) and would lead to a poor experience

https://github.com/Botspot/pi-apps/blob/master/etc/category-overrides-jetson-generic

**Comment by archisman-panigrahi** [comment]
But, does not freetube work well in Raspberry Pi? Maybe it does not work on
Jetson, but it works in surface rt. Does Pi-Apps assume all non-pi devices
as jetson?

**Comment by theofficialgman** [comment]
No, your device is detected as a "jetson" because it is a nvidia tegra based device.

**Comment by theofficialgman** [comment]
if you can post the output of 

```
cat /proc/device-tree/compatible
```
and
```
cat /sys/devices/soc0/family
```
that would be helpful so I can identify the device further (instead of jetson-unknown)

**Comment by archisman-panigrahi** [comment]
NVidia does not necessarily mean jetson.

```
 $ cat /proc/device-tree/compatible
microsoft,surface-rt-efimicrosoft,surface-rtnvidia,tegra30
```

```
$ cat /sys/devices/soc0/family
Tegra
```

**Comment by theofficialgman** [comment]
You are running a tegra-3 based device. Nvidia's official boards based on tegra's go under the brand name "jetson". 
There is no discussion to be had about that. This is simply an identification of your device as a "tegra" based device. We have particular applications [hidden](https://github.com/Botspot/pi-apps/blob/master/etc/category-overrides-jetson-generic) on these devices that are known not to work well (or at all) based on the majority of such devices.
