### ISSUE TITLE
Vulkan Drivers! (Install based app)

### ISSUE THREAD

**Issue by Pro42good** [Botspot/pi-apps#2603]
### What is the name of the app?

Vulkan Drivers

### Where is the app hosted?

Github Repo
https://github.com/KhronosGroup/Vulkan-Tools
Mesa:
https://packages.debian.org/buster/mesa-vulkan-drivers
https://archlinuxarm.org/packages/aarch64/mesa-utils

### About the app

Its vulkan drivers for the raspberry pi graphics card, I know it might fall under the headless category, but it would be nice to just have vulkan driver on Pi-Apps that lets someone just install vulkan drivers to play a game instead of looking on the internet for a while asking for vulkan on Raspberry Pi, its a nice quality of life thing for the average user, to just be able to click install for vulkan and get it over with.

### Upload file or Add PR Link

[Vulkan Drivers.zip](https://github.com/user-attachments/files/15755541/Vulkan.Drivers.zip)

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi-Apps app list.
- [X] I have read and followed the [creating an app for Pi-Apps documentation](https://pi-apps.io/wiki/development/Creating-an-app/).
- [X] I have confirmed that this app can run on all [Pi-Apps supported systems](https://pi-apps.io/install/).

**Comment by Botspot** [comment]
What advantage does this have over a simple `sudo apt install vulkan-tools mesa-vulkan-drivers`?

**Comment by theofficialgman** [comment]
zip is empty. vulkan drivers are shipped preinstalled on all default debian based distros (ubuntu, debian, even piOS now as of the March 15th 2024 images, etc)

closing as not our problem and unnecessary

**Comment by Pro42good** [comment]
oh ok, i thought it was worth a shot though  :(

**Comment by Botspot** [comment]
No worries! Thanks for reaching out. If you have any other ideas, I hope you return to suggest them.
The worst we can say is no, and through the process you might just learn something new about linux.
