### ISSUE TITLE
Roblox 

### ISSUE THREAD

**Issue by akudzwemachikiche** [Botspot/pi-apps#2607]
### What is the name of the app?

Roblox.com

### Where is the app hosted?

https://www.roblox.com/home

### About the app

What is Roblox's Main Purpose?
Roblox's main purpose is to provide a platform where users can design, create, and play games created by other users. It aims to foster creativity, encourage social interaction, and offer an engaging environment for both game development and gameplay.

How Does Roblox Work?
Game Creation:

Roblox Studio: Users create games and experiences using Roblox Studio, a development environment that utilizes the Lua programming language. This tool allows for the creation of diverse and complex games.
User-Generated Content: Users can design characters, environments, and game mechanics, sharing their creations with the Roblox community.
Gameplay:

Player Interaction: Users can play games created by others, interact with friends, and participate in various multiplayer experiences.
Cross-Platform Play: Roblox supports multiple platforms, allowing users to play and interact across different devices.
Virtual Economy:

Robux: Roblox has its own virtual currency, Robux, which players can use to buy in-game items, avatar accessories, and more. Developers can earn Robux through their games and exchange it for real money via the Developer Exchange program (DevEx).
Social Features:

Friends and Groups: Players can add friends, join groups, and chat with other users.
Community Engagement: Roblox fosters a sense of community through social interactions, events, and user-created content.
How Does Roblox Fit Our App Eligibility Rubric?
Educational Value:

Creativity and Learning: Roblox encourages users to learn programming, game design, and problem-solving skills through its game creation tools.
Resources for Educators: Roblox provides educational resources and supports initiatives that integrate game development into learning environments.
User Engagement:

Active User Base: Roblox has a large and active user base, with millions of daily active users engaging in various games and social activities.
Interactive Features: The platform includes social features like messaging, friends lists, and groups, which enhance user engagement and retention.
Safety and Moderation:

Parental Controls: Roblox offers robust parental controls to manage children’s accounts, limit interactions, and control spending.
Content Moderation: The platform employs automated systems and human moderators to ensure content complies with community guidelines, providing a safer environment for younger users.
Monetization and Revenue Potential:

Developer Opportunities: Roblox offers monetization opportunities for developers through the sale of in-game items and the Developer Exchange program, encouraging high-quality game creation.
Virtual Economy: The use of Robux promotes an in-app economy that supports continued engagement and revenue generation.
Cross-Platform Compatibility:

Accessibility: Roblox is available on multiple platforms, including Windows, macOS, iOS, Android, and Xbox One, making it widely accessible to users on different devices.
By meeting these criteria, Roblox demonstrates its value as an educational, engaging, and socially responsible platform that aligns well with app eligibility standards.

Grapejuice: This is a popular tool that helps you run Roblox through Wine, a compatibility layer for running Windows programs on Linux. You can find instructions and the Grapejuice repository on GitLab [grapejuice roblox ON GitLab gitlab.com].
Roblox on Linux Forum Thread: This thread on the Roblox developer forum discusses various methods for installing Roblox on Linux, including using Grapejuice.  https://www.roblox.com/home
Remember, using unofficial methods like Wine may not be as stable or supported as using the official Roblox client for other operating systems.

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi-Apps app list.
- [X] I have read and followed the [creating an app for Pi-Apps documentation](https://pi-apps.io/wiki/development/Creating-an-app/).
- [ ] I have confirmed that this app can run on all [Pi-Apps supported systems](https://pi-apps.io/install/).

**Comment by theofficialgman** [comment]
See app eligibility rubric https://github.com/Botspot/pi-apps/issues/185

Also we do not take porting requests since you have not proven to run this application on all pi-apps supported systems and provided a list of steps for how to do so.
