### ISSUE TITLE
More RAM Installation over CLI

### ISSUE THREAD

**Issue by mlinko6** [Botspot/pi-apps#2609]
### Cool ideas?

Dear all,

I'm apparently to dum to install the app "More RAM" over the cli with the commad:

~/pi-apps/manage install More RAM

as there are 2 separate words the installer doesn't find the program.

Thank you!

KR
Rok

**Comment by Botspot** [comment]
You were close. Do this:
```
~/pi-apps/manage install "More RAM"
```

**Comment by mlinko6** [comment]
Found it - I'm an idiot:

'More RAM'

**Comment by mlinko6** [comment]
Thx!

**Comment by Botspot** [comment]
No worries!
