### ISSUE TITLE
Auto_Backup install based app

### ISSUE THREAD

**Issue by solitary8** [Botspot/pi-apps#2611]
### What is the name of the app?

Auto_Backup

### Where is the app hosted?

https://github.com/solitary8/Auto_Backup

### About the app

This GUI app was created to back up files and folders from a source directory or file to a destination in an easy and fast way,both the source and destination are chosen by the user before the files are backed up.

### Upload file or Add PR Link

[Auto_Backup.zip](https://github.com/user-attachments/files/15936318/Auto_Backup.zip)

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi-Apps app list.
- [X] I have read and followed the [creating an app for Pi-Apps documentation](https://pi-apps.io/wiki/development/Creating-an-app/).
- [X] I have confirmed that this app can run on all [Pi-Apps supported systems](https://pi-apps.io/install/).

**Comment by solitary8** [comment]
I must warn you I have finished the first version of this app a few days ago and that I made it in shell using zenity but in the future I might switch to python for the GUI and use customtkinter.

**Comment by theofficialgman** [comment]
Zip is empty

**Comment by solitary8** [comment]
I'm sorry I compressed the folders not the files in it I will properly compress once I get back home

**Comment by theofficialgman** [comment]
I will say looking at the script https://github.com/solitary8/Auto_Backup/blob/main/auto_backup_main.sh I don't think it really has any merit for pi-apps.

A wrapper around something that users can already do in any file manager in a easier graphical way (copy a folder) is not something we need added.

Don't let this denial deter your scripting

**Comment by solitary8** [comment]
I understand. Thank you for your time,
have a good day.
