### ISSUE TITLE
SkEditor - Install based app

### ISSUE THREAD

**Issue by FixeQyt** [Botspot/pi-apps#2612]
### What is the name of the app?

SkEditor

### Where is the app hosted?

https://github.com/SkEditorTeam/SkEditor

### About the app

SkEditor is an app for editing Skript files

### Upload file or Add PR Link

[SkEditor.zip](https://github.com/user-attachments/files/15954368/SkEditor.zip)

### Confirmations

- [x] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi-Apps app list.
- [X] I have confirmed that this app is legal and not piracy.
- [X] I have read and followed the [creating an app for Pi-Apps documentation](https://pi-apps.io/wiki/development/Creating-an-app/).
- [X] I have confirmed that this app can run on all [Pi-Apps supported systems](https://pi-apps.io/install/).

**Comment by Botspot** [comment]
Please work on the description a bit.
- How to run from menu?
- What is a skript file?
- Why would raspberry pi users want this, and what is it used for?

Also, your install script is very overcomplicated. In a pi-apps script I could get it all done with less than 20 lines.
No promises we will agree to add this, but at the very least we would need you to avoid using `apt` directly. You need to use our `install_packages` function, which is safer than apt and takes deb url arguments.
```bash
install_packages 'https://nightly.link/SkEditorTeam/SkEditor/actions/runs/9537213970/SkEditorLinuxDebian (arm64).zip'
```
Please take a look at https://pi-apps.io/wiki/development/Creating-an-app/ for more tips

**Comment by FixeQyt** [comment]
ok I change

**Comment by theofficialgman** [comment]
this is extremely needlessly complex
please refer to many other pi-apps install scripts that download github actions artifacts and install debs

I see you are the upstream contributor that added debian packaging to github actions artifacts. Please request that upstream include those in standard github releases so that real users can download them (without needing a github account and searching through actions logs)
