### ISSUE TITLE
Puffin Install Fails

### ISSUE THREAD

**Issue by connorjacem** [Botspot/pi-apps#2618]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi-Apps and the issue is still not fixed. [How to update Pi-Apps?](https://pi-apps.io/wiki/getting-started/updating-pi-apps/)
- [X] IMPORTANT: I promise to respond to comments on this issue and write a good bug report https://www.softwaretestinghelp.com/how-to-write-good-bug-report/

### What happened?

Puffin Installation stops partway

### Description

I have attempted to install Puffin a few times and it also causes the entire OS to freeze once it reaches a specific line in the installation. The installation does not pass that point even with 30 minutes+ in that state. That line is: 

Get: 2 /tmp/pi-apps-7d27a60f.deb pi-apps-7d27a60f all 1.0 [772 B]

I’ve tried installing other apps to see if there might have been a problem there, but it’s only with Puffin that I have this issue.

### What are your system specs (run the following command in your terminal)?

```bash
OS: Debian GNU/Linux 11 (bullseye)
OS architecture: 64-bit
Last updated Pi-Apps on: 7/12/2024
Latest Pi-Apps version: 7/12/2024
Kernel: aarch64 6.1.21-v8+
Device model: Raspberry Pi 3 Model A Plus Rev 1.1
SOC indentifier: bcm2837
CPU name: Cortex-A53
Ram size: .41 GB
Raspberry Pi OS image version: 2024-07-04
```

**Comment by Botspot** [comment]
Please send the full error log. There is not much we can do with just one line from the error log.

**Comment by Botspot** [comment]
It could be RAM-related. Try keeping an eye on htop's reported RAM usage to see if it reaches 100% then freezes. If that happens, a ZRAM setup such as the excellent implementation in our More RAM app may help.

**Comment by connorjacem** [comment]
Sorry, I’m rather new to Linux/raspberry pi so I’m not entirely sure how to access the error log. That line provided was the last line executed in the installation terminal. Until then, I’ll try you’re more ram app and see if that works

**Comment by Botspot** [comment]
Just copy everything in the terminal. If the terminal closed already, then please go to Pi-Apps settings, click the Logs button, and then you can view every past app installation log from there.

**Comment by connorjacem** [comment]
Sorry I can’t get chrome to open properly on the Pi so I’m going to submit pictures of the logs. I didn’t include the full percentage update just to keep it cleaner.
![IMG_2757](https://github.com/user-attachments/assets/c8003a07-6a5a-40bd-8604-ca562be98d08)

![IMG_2755](https://github.com/user-attachments/assets/35fda130-8bbe-4c20-9c09-d80e0c14dd26)
![IMG_2756](https://github.com/user-attachments/assets/a64133d7-0c1f-4cff-9f5b-d04624f63b0d)

**Comment by Botspot** [comment]
Yeah try installing Puffin again, but this time watch HTOP for total usage of CPU or RAM.
Don't be surprised if installing More RAM solves the issue.

**Comment by connorjacem** [comment]
I didn’t have HTOP installed previously so I installed that and monitored it like you said, and interestingly enough there was no issue and the program installed. Not sure what was different from the dozen or so other times I tried but glad to see it worked. Thank you for your help.
