### ISSUE TITLE
Need help with device out of space

### ISSUE THREAD

**Issue by baboeska** [Botspot/pi-apps#2619]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi-Apps and the issue is still not fixed. [How to update Pi-Apps?](https://pi-apps.io/wiki/getting-started/updating-pi-apps/)
- [X] IMPORTANT: I promise to respond to comments on this issue and write a good bug report https://www.softwaretestinghelp.com/how-to-write-good-bug-report/

### What happened?

Cannot uninstall 

### Description

Monitor progress reads:
1 Will
Done

Pi-apps reports "Failed to install app for unknown reason" while attempting to uninstall ppsspp.
When using pi-apps to install ppsspp, I get issue where github says insufficient space on drive, cannot build.

### What are your system specs (run the following command in your terminal)?

```bash
OS: Armbian 24.5.1 jammy
Armbian 24.5.1 jammy
OS architecture: 64-bit
Last updated Pi-Apps on: 07/13/2024
Latest Pi-Apps version: 07/15/2024
Kernel: aarch64 6.6.31-current-bcm2711
Device model: Raspberry Pi 4 Model B Rev 1.5
SOC identifier: bcm2711
Cpu name: Cortex-A72
Ram size: 3.49 GB
Language: en_US.UTF-8
```

### (Recommended) Error log? Terminal output? Debug messages?

```bash
From uninstalliing:

tac: /tmp/tacKb6fTZ: write error: No space left on device
You need to specify an operation, and in most cases, which app to operate on.

(Pi-Apps:31423): GLib-GObject-CRITICAL **: 01:39:03.326: g_value_type_compatible: assertion 'src_type' failed

(Pi-Apps:31423): Gtk-WARNING **: 01:39:03.329: ../../../../gtk/gtkliststore.c:1039: invalid object type '

(Pi-Apps:31423): GLib-GObject-CRITICAL **: 01:39:03.329: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
cat: '': No such file or directory
cat: '': No such file or directory
```

**Comment by baboeska** [comment]
Over 15gb of free space on /

**Comment by Botspot** [comment]
Could you run this command to check free space in /tmp?
```
df -h /tmp
```

**Comment by baboeska** [comment]
df -h /tmp
Filesystem      Size  Used Avail Use% Mounted on
tmpfs           1.8G  4.0K  1.8G   1% /tmp

**Comment by baboeska** [comment]
Filesystem      Size  Used Avail Use% Mounted on
tmpfs           1.8G  1.8G     0 100% /tmp


error: unable to write file tests/ref/vsynth/vsynth_lena-h263p
error: unable to write file tests/ref/vsynth/vsynth_lena-huffyuv
error: unable to write file tests/ref/vsynth/vsynth_lena-huffyuvbgr24
error: unable to write file tests/ref/vsynth/vsynth_lena-huffyuvbgra
error: unable to write file tests/ref/vsynth/vsynth_lena-jpeg2000
error: unable to write file tests/ref/vsynth/vsynth_lena-jpeg2000-97
error: unable to write file tests/ref/vsynth/vsynth_lena-jpegls
error: unable to write file tests/ref/vsynth/vsynth_lena-ljpeg
error: unable to write file tests/ref/vsynth/vsynth_lena-mjpeg
error: unable to write file tests/ref/vsynth/vsynth_lena-mjpeg-422
error: unable to write file tests/ref/vsynth/vsynth_lena-mjpeg-444
error: unable to write file tests/ref/vsynth/vsynth_lena-mjpeg-trell
error: unable to write file tests/ref/vsynth/vsynth_lena-mov-bgr24
error: unable to write file tests/ref/vsynth/vsynth_lena-mov-bpp15
error: unable to write file tests/ref/vsynth/vsynth_lena-mov-bpp16
error: unable to write file tests/ref/vsynth/vsynth_lena-mpeg1
error: unable to write file tests/ref/vsynth/vsynth_lena-mpeg1b
error: unable to write file tests/ref/vsynth/vsynth_lena-mpeg2
error: unable to write file tests/ref/vsynth/vsynth_lena-mpeg2-422
error: unable to write file tests/ref/vsynth/vsynth_lena-mpeg2-idct-int
error: unable to write file tests/ref/vsynth/vsynth_lena-mpeg2-ilace
error: unable to write file tests/ref/vsynth/vsynth_lena-mpeg2-ivlc-qprd
error: unable to write file tests/ref/vsynth/vsynth_lena-mpeg2-thread
error: unable to write file tests/ref/vsynth/vsynth_lena-mpeg2-thread-ivlc
error: unable to write file tests/ref/vsynth/vsynth_lena-mpeg4
error: unable to write file tests/ref/vsynth/vsynth_lena-mpeg4-adap
error: unable to write file tests/ref/vsynth/vsynth_lena-mpeg4-adv
error: unable to write file tests/ref/vsynth/vsynth_lena-mpeg4-error
error: unable to write file tests/ref/vsynth/vsynth_lena-mpeg4-nr
error: unable to write file tests/ref/vsynth/vsynth_lena-mpeg4-nsse
error: unable to write file tests/ref/vsynth/vsynth_lena-mpeg4-qpel
error: unable to write file tests/ref/vsynth/vsynth_lena-mpeg4-qprd
error: unable to write file tests/ref/vsynth/vsynth_lena-mpeg4-rc
error: unable to write file tests/ref/vsynth/vsynth_lena-mpeg4-thread
error: unable to write file tests/ref/vsynth/vsynth_lena-mpng
error: unable to write file tests/ref/vsynth/vsynth_lena-msmpeg4
error: unable to write file tests/ref/vsynth/vsynth_lena-msmpeg4v2
error: unable to write file tests/ref/vsynth/vsynth_lena-msvideo1
error: unable to write file tests/ref/vsynth/vsynth_lena-prores
error: unable to write file tests/ref/vsynth/vsynth_lena-prores_ks
error: unable to write file tests/ref/vsynth/vsynth_lena-qtrle
error: unable to write file tests/ref/vsynth/vsynth_lena-qtrlegray
error: unable to write file tests/ref/vsynth/vsynth_lena-r210
error: unable to write file tests/ref/vsynth/vsynth_lena-rgb
error: unable to write file tests/ref/vsynth/vsynth_lena-roqvideo
error: unable to write file tests/ref/vsynth/vsynth_lena-rv10
error: unable to write file tests/ref/vsynth/vsynth_lena-rv20
error: unable to write file tests/ref/vsynth/vsynth_lena-snow
error: unable to write file tests/ref/vsynth/vsynth_lena-snow-hpel
error: unable to write file tests/ref/vsynth/vsynth_lena-snow-ll
error: unable to write file tests/ref/vsynth/vsynth_lena-svq1
error: unable to write file tests/ref/vsynth/vsynth_lena-v210
error: unable to write file tests/ref/vsynth/vsynth_lena-v210-10
error: unable to write file tests/ref/vsynth/vsynth_lena-v308
error: unable to write file tests/ref/vsynth/vsynth_lena-v408
error: unable to write file tests/ref/vsynth/vsynth_lena-wmv1
error: unable to write file tests/ref/vsynth/vsynth_lena-wmv2
error: unable to write file tests/ref/vsynth/vsynth_lena-xface
error: unable to write file tests/ref/vsynth/vsynth_lena-y41p
error: unable to write file tests/ref/vsynth/vsynth_lena-yuv
error: unable to write file tests/ref/vsynth/vsynth_lena-yuv4
error: unable to write file tests/ref/vsynth/vsynth_lena-zlib
error: unable to write file tests/ref/vsynth/vsynth_lena-zmbv
error: unable to write file tests/ref/vsynth1/cljr
error: unable to write file tests/ref/vsynth1/yuv
error: unable to write file tests/ref/vsynth_lena/cljr
error: unable to write file tests/ref/vsynth_lena/huffyuv
error: unable to write file tests/ref/vsynth_lena/yuv
error: unable to write file tests/reference.pnm
error: unable to write file tests/regression-funcs.sh
error: unable to write file tests/rotozoom.c
error: unable to write file tests/simple1.ffconcat
error: unable to write file tests/simple2.ffconcat
error: unable to write file tests/test.ffmeta
error: unable to write file tests/tiny_psnr.c
error: unable to write file tests/tiny_ssim.c
error: unable to write file tests/utils.c
error: unable to write file tests/videogen.c
error: unable to write file tools/aviocat.c
error: unable to write file tools/bisect-create
error: unable to write file tools/bookmarklets.html
error: unable to write file tools/clean-diff
error: unable to write file tools/coverity.c
error: unable to write file tools/crypto_bench.c
error: unable to write file tools/cws2fws.c
error: unable to write file tools/dvd2concat
error: unable to write file tools/enum_options.c
error: unable to write file tools/ffescape.c
error: unable to write file tools/ffeval.c
error: unable to write file tools/ffhash.c
error: unable to write file tools/fourcc2pixfmt.c
error: unable to write file tools/gen-rc
error: unable to write file tools/graph2dot.c
error: unable to write file tools/ismindex.c
error: unable to write file tools/make_chlayout_test
error: unable to write file tools/missing_codec_desc
error: unable to write file tools/normalize.py
error: unable to write file tools/patcheck
error: unable to write file tools/pktdumper.c
error: unable to write file tools/plotframes
error: unable to write file tools/probetest.c
error: unable to write file tools/qt-faststart.c
error: unable to write file tools/seek_print.c
error: unable to write file tools/sidxindex.c
error: unable to write file tools/trasher.c
error: unable to write file tools/uncoded_frame.c
error: unable to write file tools/unwrap-diff
error: unable to write file tools/yuvcmp.c
error: unable to write file tools/zmqsend.c
error: unable to write file tools/zmqshell.py
error: unable to write file tvos-build.sh
error: unable to write file tvos/arm64/include/libavcodec/avcodec.h
error: unable to write file tvos/arm64/include/libavcodec/avdct.h
error: unable to write file tvos/arm64/include/libavcodec/avfft.h
error: unable to write file tvos/arm64/include/libavcodec/d3d11va.h
error: unable to write file tvos/arm64/include/libavcodec/dirac.h
error: unable to write file tvos/arm64/include/libavcodec/dv_profile.h
error: unable to write file tvos/arm64/include/libavcodec/dxva2.h
error: unable to write file tvos/arm64/include/libavcodec/qsv.h
error: unable to write file tvos/arm64/include/libavcodec/vaapi.h
error: unable to write file tvos/arm64/include/libavcodec/vda.h
error: unable to write file tvos/arm64/include/libavcodec/vdpau.h
error: unable to write file tvos/arm64/include/libavcodec/version.h
error: unable to write file tvos/arm64/include/libavcodec/videotoolbox.h
error: unable to write file tvos/arm64/include/libavcodec/vorbis_parser.h
error: unable to write file tvos/arm64/include/libavcodec/xvmc.h
error: unable to write file tvos/arm64/include/libavdevice/avdevice.h
error: unable to write file tvos/arm64/include/libavdevice/version.h
error: unable to write file tvos/arm64/include/libavformat/avformat.h
error: unable to write file tvos/arm64/include/libavformat/avio.h
error: unable to write file tvos/arm64/include/libavformat/version.h
error: unable to write file tvos/arm64/include/libavutil/adler32.h
error: unable to write file tvos/arm64/include/libavutil/aes.h
error: unable to write file tvos/arm64/include/libavutil/aes_ctr.h
error: unable to write file tvos/arm64/include/libavutil/attributes.h
error: unable to write file tvos/arm64/include/libavutil/audio_fifo.h
error: unable to write file tvos/arm64/include/libavutil/avassert.h
error: unable to write file tvos/arm64/include/libavutil/avconfig.h
error: unable to write file tvos/arm64/include/libavutil/avstring.h
error: unable to write file tvos/arm64/include/libavutil/avutil.h
error: unable to write file tvos/arm64/include/libavutil/base64.h
error: unable to write file tvos/arm64/include/libavutil/blowfish.h
error: unable to write file tvos/arm64/include/libavutil/bprint.h
error: unable to write file tvos/arm64/include/libavutil/bswap.h
error: unable to write file tvos/arm64/include/libavutil/buffer.h
error: unable to write file tvos/arm64/include/libavutil/camellia.h
error: unable to write file tvos/arm64/include/libavutil/cast5.h
error: unable to write file tvos/arm64/include/libavutil/channel_layout.h
error: unable to write file tvos/arm64/include/libavutil/common.h
error: unable to write file tvos/arm64/include/libavutil/cpu.h
error: unable to write file tvos/arm64/include/libavutil/crc.h
error: unable to write file tvos/arm64/include/libavutil/des.h
error: unable to write file tvos/arm64/include/libavutil/dict.h
error: unable to write file tvos/arm64/include/libavutil/display.h
error: unable to write file tvos/arm64/include/libavutil/downmix_info.h
error: unable to write file tvos/arm64/include/libavutil/error.h
error: unable to write file tvos/arm64/include/libavutil/eval.h
error: unable to write file tvos/arm64/include/libavutil/ffversion.h
error: unable to write file tvos/arm64/include/libavutil/fifo.h
error: unable to write file tvos/arm64/include/libavutil/file.h
error: unable to write file tvos/arm64/include/libavutil/frame.h
error: unable to write file tvos/arm64/include/libavutil/hash.h
error: unable to write file tvos/arm64/include/libavutil/hmac.h
error: unable to write file tvos/arm64/include/libavutil/imgutils.h
error: unable to write file tvos/arm64/include/libavutil/intfloat.h
error: unable to write file tvos/arm64/include/libavutil/intreadwrite.h
error: unable to write file tvos/arm64/include/libavutil/lfg.h
error: unable to write file tvos/arm64/include/libavutil/log.h
error: unable to write file tvos/arm64/include/libavutil/macros.h
error: unable to write file tvos/arm64/include/libavutil/mastering_display_metadata.h
error: unable to write file tvos/arm64/include/libavutil/mathematics.h
error: unable to write file tvos/arm64/include/libavutil/md5.h
error: unable to write file tvos/arm64/include/libavutil/mem.h
error: unable to write file tvos/arm64/include/libavutil/motion_vector.h
error: unable to write file tvos/arm64/include/libavutil/murmur3.h
error: unable to write file tvos/arm64/include/libavutil/opt.h
error: unable to write file tvos/arm64/include/libavutil/parseutils.h
error: unable to write file tvos/arm64/include/libavutil/pixdesc.h
error: unable to write file tvos/arm64/include/libavutil/pixelutils.h
error: unable to write file tvos/arm64/include/libavutil/pixfmt.h
error: unable to write file tvos/arm64/include/libavutil/random_seed.h
error: unable to write file tvos/arm64/include/libavutil/rational.h
error: unable to write file tvos/arm64/include/libavutil/rc4.h
error: unable to write file tvos/arm64/include/libavutil/replaygain.h
error: unable to write file tvos/arm64/include/libavutil/ripemd.h
error: unable to write file tvos/arm64/include/libavutil/samplefmt.h
error: unable to write file tvos/arm64/include/libavutil/sha.h
error: unable to write file tvos/arm64/include/libavutil/sha512.h
error: unable to write file tvos/arm64/include/libavutil/stereo3d.h
error: unable to write file tvos/arm64/include/libavutil/tea.h
error: unable to write file tvos/arm64/include/libavutil/threadmessage.h
error: unable to write file tvos/arm64/include/libavutil/time.h
error: unable to write file tvos/arm64/include/libavutil/timecode.h
error: unable to write file tvos/arm64/include/libavutil/timestamp.h
error: unable to write file tvos/arm64/include/libavutil/tree.h
error: unable to write file tvos/arm64/include/libavutil/twofish.h
error: unable to write file tvos/arm64/include/libavutil/version.h
error: unable to write file tvos/arm64/include/libavutil/xtea.h
error: unable to write file tvos/arm64/include/libswresample/swresample.h
error: unable to write file tvos/arm64/include/libswresample/version.h
error: unable to write file tvos/arm64/include/libswscale/swscale.h
error: unable to write file tvos/arm64/include/libswscale/version.h
error: unable to write file tvos/arm64/lib/libavcodec.a
error: unable to write file tvos/arm64/lib/libavdevice.a
error: unable to write file tvos/arm64/lib/libavformat.a
error: unable to write file tvos/arm64/lib/libavutil.a
error: unable to write file tvos/arm64/lib/libswresample.a
error: unable to write file tvos/arm64/lib/libswscale.a
error: unable to write file uwp_ARM-build.sh
error: unable to write file uwp_ARM64-build.sh
error: unable to write file uwp_x64-build.sh
error: unable to write file uwp_x86-build.sh
error: unable to write file version.sh
error: unable to write file wiiu.sh
error: unable to write file wiiu/include/libavcodec/avcodec.h
error: unable to write file wiiu/include/libavcodec/avdct.h
error: unable to write file wiiu/include/libavcodec/avfft.h
error: unable to write file wiiu/include/libavcodec/d3d11va.h
error: unable to write file wiiu/include/libavcodec/dirac.h
error: unable to write file wiiu/include/libavcodec/dv_profile.h
error: unable to write file wiiu/include/libavcodec/dxva2.h
error: unable to write file wiiu/include/libavcodec/qsv.h
error: unable to write file wiiu/include/libavcodec/vaapi.h
error: unable to write file wiiu/include/libavcodec/vda.h
error: unable to write file wiiu/include/libavcodec/vdpau.h
error: unable to write file wiiu/include/libavcodec/version.h
error: unable to write file wiiu/include/libavcodec/videotoolbox.h
error: unable to write file wiiu/include/libavcodec/vorbis_parser.h
error: unable to write file wiiu/include/libavcodec/xvmc.h
error: unable to write file wiiu/include/libavformat/avformat.h
error: unable to write file wiiu/include/libavformat/avio.h
error: unable to write file wiiu/include/libavformat/version.h
error: unable to write file wiiu/include/libavutil/adler32.h
error: unable to write file wiiu/include/libavutil/aes.h
error: unable to write file wiiu/include/libavutil/aes_ctr.h
error: unable to write file wiiu/include/libavutil/attributes.h
error: unable to write file wiiu/include/libavutil/audio_fifo.h
error: unable to write file wiiu/include/libavutil/avassert.h
error: unable to write file wiiu/include/libavutil/avconfig.h
error: unable to write file wiiu/include/libavutil/avstring.h
error: unable to write file wiiu/include/libavutil/avutil.h
error: unable to write file wiiu/include/libavutil/base64.h
error: unable to write file wiiu/include/libavutil/blowfish.h
error: unable to write file wiiu/include/libavutil/bprint.h
error: unable to write file wiiu/include/libavutil/bswap.h
error: unable to write file wiiu/include/libavutil/buffer.h
error: unable to write file wiiu/include/libavutil/camellia.h
error: unable to write file wiiu/include/libavutil/cast5.h
error: unable to write file wiiu/include/libavutil/channel_layout.h
error: unable to write file wiiu/include/libavutil/common.h
error: unable to write file wiiu/include/libavutil/cpu.h
error: unable to write file wiiu/include/libavutil/crc.h
error: unable to write file wiiu/include/libavutil/des.h
error: unable to write file wiiu/include/libavutil/dict.h
error: unable to write file wiiu/include/libavutil/display.h
error: unable to write file wiiu/include/libavutil/downmix_info.h
error: unable to write file wiiu/include/libavutil/error.h
error: unable to write file wiiu/include/libavutil/eval.h
error: unable to write file wiiu/include/libavutil/ffversion.h
error: unable to write file wiiu/include/libavutil/fifo.h
error: unable to write file wiiu/include/libavutil/file.h
error: unable to write file wiiu/include/libavutil/frame.h
error: unable to write file wiiu/include/libavutil/hash.h
error: unable to write file wiiu/include/libavutil/hmac.h
error: unable to write file wiiu/include/libavutil/imgutils.h
error: unable to write file wiiu/include/libavutil/intfloat.h
error: unable to write file wiiu/include/libavutil/intreadwrite.h
error: unable to write file wiiu/include/libavutil/lfg.h
error: unable to write file wiiu/include/libavutil/log.h
error: unable to write file wiiu/include/libavutil/macros.h
error: unable to write file wiiu/include/libavutil/mastering_display_metadata.h
error: unable to write file wiiu/include/libavutil/mathematics.h
error: unable to write file wiiu/include/libavutil/md5.h
error: unable to write file wiiu/include/libavutil/mem.h
error: unable to write file wiiu/include/libavutil/motion_vector.h
error: unable to write file wiiu/include/libavutil/murmur3.h
error: unable to write file wiiu/include/libavutil/opt.h
error: unable to write file wiiu/include/libavutil/parseutils.h
error: unable to write file wiiu/include/libavutil/pixdesc.h
error: unable to write file wiiu/include/libavutil/pixelutils.h
error: unable to write file wiiu/include/libavutil/pixfmt.h
error: unable to write file wiiu/include/libavutil/random_seed.h
error: unable to write file wiiu/include/libavutil/rational.h
error: unable to write file wiiu/include/libavutil/rc4.h
error: unable to write file wiiu/include/libavutil/replaygain.h
error: unable to write file wiiu/include/libavutil/ripemd.h
error: unable to write file wiiu/include/libavutil/samplefmt.h
error: unable to write file wiiu/include/libavutil/sha.h
error: unable to write file wiiu/include/libavutil/sha512.h
error: unable to write file wiiu/include/libavutil/stereo3d.h
error: unable to write file wiiu/include/libavutil/tea.h
error: unable to write file wiiu/include/libavutil/threadmessage.h
error: unable to write file wiiu/include/libavutil/time.h
error: unable to write file wiiu/include/libavutil/timecode.h
error: unable to write file wiiu/include/libavutil/timestamp.h
error: unable to write file wiiu/include/libavutil/tree.h
error: unable to write file wiiu/include/libavutil/twofish.h
error: unable to write file wiiu/include/libavutil/version.h
error: unable to write file wiiu/include/libavutil/xtea.h
error: unable to write file wiiu/include/libswresample/swresample.h
error: unable to write file wiiu/include/libswresample/version.h
error: unable to write file wiiu/include/libswscale/swscale.h
error: unable to write file wiiu/include/libswscale/version.h
error: unable to write file wiiu/lib/libavcodec.a
error: unable to write file wiiu/lib/libavformat.a
error: unable to write file wiiu/lib/libavutil.a
error: unable to write file wiiu/lib/libswresample.a
error: unable to write file wiiu/lib/libswscale.a
error: unable to write file windows_arm-build.sh
error: unable to write file windows_arm64-build.sh
error: unable to write file windows_x64-build.sh
error: unable to write file windows_x86-build.sh
fatal: sha1 file '/tmp/ppsspp/.git/modules/ffmpeg/index.lock' write error. Out of diskspace
error: failed to write new configuration file /tmp/ppsspp/.git/modules/libretro/libretro-common/config.lock
fatal: could not set 'core.worktree' to '../../../../libretro/libretro-common'
Failed to clone the repo

**Comment by baboeska** [comment]
Okay, so do I need to make my tmp fs 5gb+ for ppsspp script to work?
Is that easy/doable on an already mostly full sd-card with a fair few gbs of free space?

**Comment by baboeska** [comment]
After closing installer.
Note, I ran firefox-esr during install of ppsspp to update bug report.

df -h
Filesystem      Size  Used Avail Use% Mounted on
tmpfs           350M   11M  339M   3% /run
/dev/mmcblk0p2  469G  450G   15G  97% /
tmpfs           1.8G     0  1.8G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           1.8G     0  1.8G   0% /run/qemu
tmpfs           1.8G  1.8G     0 100% /tmp
/dev/mmcblk0p1  253M  134M  120M  53% /boot/firmware
/dev/zram1       47M  1.7M   42M   4% /var/log
tmpfs           350M   84K  350M   1% /run/user/1000
overlaid        350M   84K  350M   1% /run/user/1000/xs-chromium

**Comment by baboeska** [comment]
???

mount -o remount,size=5G /tmp/

???
would that work?

**Comment by Botspot** [comment]
I am not sure. This is something that you will need to resolve on your own, as we here are not familiar with Armbian.
