### ISSUE TITLE
[Add app to list] NGGYUNGLYD: A Useful App 

### ISSUE THREAD

**Issue by Aerospace35** [Botspot/pi-apps#262]
here is the zip file... very useful indeed *wink

The description is the useful part

MAKE SURE TO WATCH THE TUTORIAL

check it out here!

https://youtu.be/dQw4w9WgXcQ

[NGGYUNGLYD.zip](https://github.com/Botspot/pi-apps/files/5845896/NGGYUNGLYD.zip)

**Comment by Botspot** [comment]
Unfortunately, your ZIP file was not formatted correctly.

Be sure to follow the App Creator's instructions, and then we'll see if the NGGYUNGLYD app can be added to Pi-Apps! ;)
