### ISSUE TITLE
BomberMan3D Install based app

### ISSUE THREAD

**Issue by Robostep21** [Botspot/pi-apps#2621]
### What is the name of the app?

BomberMan3D

### Where is the app hosted?

https://github.com/Robostep21/BomberMan3D

### About the app

Retro game in 3D, with multiplayer! Maked on Godot.

HOW TO RUN: from menu.

CONTROLS:
   Walk: arrows.
   Place bomb: space.

### Upload file or Add PR Link

[BomberMan3D.zip](https://github.com/user-attachments/files/16283126/BomberMan3D.zip)

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi-Apps app list.
- [X] I have read and followed the [creating an app for Pi-Apps documentation](https://pi-apps.io/wiki/development/Creating-an-app/).
- [ ] I have confirmed that this app can run on all [Pi-Apps supported systems](https://pi-apps.io/install/).

**Comment by Botspot** [comment]
This is currently your install script:
```
#!/bin/bash


#Be sure to use the "error" function - it will display a message if a command fails to run. Example below:

git_clone https://github.com/Robostep21/BomberMan3D.git || error 'Failed to clone repository!'

unzip /home/admin/BomberMan3D/BM3D.zip
```
How is this supposed to work? what if I am using /home/pi instead of /home/admin?
Do any apt packages need to be installed?

Also your description mentions something.

> HOW TO RUN: from menu.

How is this menu button created? I don't see anything creating a menu launcher in your script, or in your zip file hosted on your github.

**Comment by Botspot** [comment]
Also this is a x86_64 binary - it won't run on Raspberry Pi.
So why did you check this box in your original post?

> * [x]  I have confirmed that this app can run on all [Pi-Apps supported systems](https://pi-apps.io/install/).

**Comment by Robostep21** [comment]
Sorry. My error. I need to fix it.

**Comment by theofficialgman** [comment]
The ability to run on all pi-apps supported systems is a requirement.

Due to the low quality of this issue and the requirement for porting (which we do not take requests for) this will be closed.

**Comment by Botspot** [comment]
@Robostep21 feel free to comment here if you get everything working, and we can reopen the issue.

**Comment by theofficialgman** [comment]
The source of the application is not clear either. Is this paid software (is: you want us to facilitate piracy) or is this software you have developed which the source just isn't available?
