### ISSUE TITLE
EDIT ME Include the app name and if it is a Package app or an Install based App

### ISSUE THREAD

**Issue by StateSource** [Botspot/pi-apps#2623]
### What is the name of the app?

VM Manager

### Where is the app hosted?

https://virt-manager.org

### About the app

the app can manage the installed virtual machine for create / delete / ajust / and run virtual machines this supports all platforms and architectures to create ; x64_86 , aarch64 , arm64 , amd64 , and more!

### Upload file or Add PR Link

[VM Manager.zip](https://github.com/user-attachments/files/16325419/VM.Manager.zip)

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi-Apps app list.
- [X] I have read and followed the [creating an app for Pi-Apps documentation](https://pi-apps.io/wiki/development/Creating-an-app/).
- [X] I have confirmed that this app can run on all [Pi-Apps supported systems](https://pi-apps.io/install/).

**Comment by StateSource** [comment]
ok

**Comment by Botspot** [comment]
I apologize for asking, but is this a joke?
Why are there terminal commands in the `description`, `website` and `credits` files? Normal text belongs in those files, not shell commands.
