### ISSUE TITLE
Unable to install Anydesk on Raspberry Pi 5

### ISSUE THREAD

**Issue by StanTsai** [Botspot/pi-apps#2624]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [ ] I tried updating Pi-Apps and the issue is still not fixed. [How to update Pi-Apps?](https://pi-apps.io/wiki/getting-started/updating-pi-apps/)
- [X] IMPORTANT: I promise to respond to comments on this issue and write a good bug report https://www.softwaretestinghelp.com/how-to-write-good-bug-report/

### What happened?

Unable to install Anydesk on Raspberry Pi 5

### Description

After following the procedure to install anydesk, it doesn't work. It shows Active: failed.

### What are your system specs (run the following command in your terminal)?

```bash
OS: Raspbian GNU/Linux 12 (bookworm)
OS architecture: 32-bit
Last updated Pi-Apps on: 07/24/2024
Latest Pi-Apps version: 07/23/2024
Kernel: aarch64 6.6.31+rpt-rpi-v8
SOC identifier: bcm2712
Cpu name: Cortex-A76
Ram size: 7.94 GB
Raspberry Pi OS image version: 2024-07-04
Language: en_US.UTF-8
```

### (Recommended) Error log? Terminal output? Debug messages?

```bash
gbcadmin@raspberrypi:~ $ sudo systemctl status anydesk.service
× anydesk.service - AnyDesk
     Loaded: loaded (/etc/systemd/system/anydesk.service; enabled; preset: enabled)
     Active: failed (Result: exit-code) since Wed 2024-07-24 15:37:06 EDT; 1min 8s ago
   Duration: 3ms
    Process: 12597 ExecStart=/usr/bin/anydesk --service (code=exited, status=127)
   Main PID: 12597 (code=exited, status=127)
        CPU: 2ms

Jul 24 15:37:06 raspberrypi systemd[1]: Started anydesk.service - AnyDesk.
Jul 24 15:37:06 raspberrypi anydesk[12597]: /usr/bin/anydesk: error while loading shared libraries: libbcm_host.so: cannot open shared o>
Jul 24 15:37:06 raspberrypi systemd[1]: anydesk.service: Main process exited, code=exited, status=127/n/a
Jul 24 15:37:06 raspberrypi systemd[1]: anydesk.service: Failed with result 'exit-code'.
```

**Comment by theofficialgman** [comment]
Already known upstream anydesk issue.https://github.com/Botspot/pi-apps/pull/2455#issuecomment-1984800997

Anydesk upstream has not maintained the pi port for years.

Thanks for the reminder. At this point it needs to be removed from pi-apps.

@Botspot thoughts?

**Comment by Botspot** [comment]
AnyDesk has been removed from Pi-Apps.
