### ISSUE TITLE
EDIT ME Include the app name and if it is a Package app or an Install based App

### ISSUE THREAD

**Issue by zaelyy** [Botspot/pi-apps#2627]
### What is the name of the app?

vscode

### Where is the app hosted?

pi apps

### About the app

app installer

### Upload file or Add PR Link

none

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi-Apps app list.
- [X] I have read and followed the [creating an app for Pi-Apps documentation](https://pi-apps.io/wiki/development/Creating-an-app/).
- [X] I have confirmed that this app can run on all [Pi-Apps supported systems](https://pi-apps.io/install/).

**Comment by Botspot** [comment]
Please explain yourself.
We already have Visual Studio Code and VSCodium.
![20240727_18h33m41s_grim](https://github.com/user-attachments/assets/b302cd8f-28ac-489a-a789-ad54204d336e)
