### ISSUE TITLE
obsstudio

### ISSUE THREAD

**Issue by 0d0a** [Botspot/pi-apps#2628]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi-Apps and the issue is still not fixed. [How to update Pi-Apps?](https://pi-apps.io/wiki/getting-started/updating-pi-apps/)
- [X] IMPORTANT: I promise to respond to comments on this issue and write a good bug report https://www.softwaretestinghelp.com/how-to-write-good-bug-report/

### What happened?

app obsstudio problem failed to update

### Description

emoving pi-apps-2fe85b57 (1.0) ...

Removing obs-studio (30.2.2-1) ...

Removing libfdk-aac2:arm64 (2.0.2-1) ...

Removing libmbedtls14:arm64 (2.28.3-1) ...

Removing libmbedx509-1:arm64 (2.28.3-1) ...

Removing libqrcodegencpp1:arm64 (1.8.0-1.1) ...

Removing libqt6svg6:arm64 (6.4.2-2) ...

Removing old xtrx-0.0.1+git20190320.5ae3a3e-3.2 DKMS files...

/usr/sbin/dkms: line 2497: echo: write error: Broken pipe

Deleting module xtrx-0.0.1+git20190320.5ae3a3e-3.2 completely from the DKMS tree.

Loading new xtrx-0.0.1+git20190320.5ae3a3e-3.2 DKMS files...

/usr/sbin/dkms: line 2497: echo: write error: Broken pipe

Building for 6.6.31+rpt-rpi-2712 6.6.31+rpt-rpi-v8

/usr/sbin/dkms: line 2497: echo: write error: Broken pipe

Building initial module for 6.6.31+rpt-rpi-2712

/usr/sbin/dkms: line 2497: echo: write error: Broken pipe

Error! Bad return status for module build on kernel: 6.6.31+rpt-rpi-2712 (aarch64)

Consult /var/lib/dkms/xtrx/0.0.1+git20190320.5ae3a3e-3.2/build/make.log for more information.

dpkg: error processing package xtrx-dkms (--configure):

 installed xtrx-dkms package post-installation script subprocess returned error exit status 10

Errors were encountered while processing:

 xtrx-dkms

E: Sub-process /usr/bin/dpkg returned an error code (1)

### What are your system specs (run the following command in your terminal)?

```bash
OS: Debian GNU/Linux 12 (bookworm)
OS architecture: 64-bit
Last updated Pi-Apps on: 07/31/2024
Latest Pi-Apps version: 07/31/2024
Kernel: aarch64 6.6.31+rpt-rpi-2712
Device model: Raspberry Pi 5 Model B Rev 1.0
SOC identifier: bcm2712
Cpu name: Cortex-A76
Ram size: 4.04 GB
Raspberry Pi OS image version: 2024-03-15
Language: en_US.UTF-8
```

### (Recommended) Error log? Terminal output? Debug messages?

```bash
emoving pi-apps-2fe85b57 (1.0) ...

Removing obs-studio (30.2.2-1) ...

Removing libfdk-aac2:arm64 (2.0.2-1) ...

Removing libmbedtls14:arm64 (2.28.3-1) ...

Removing libmbedx509-1:arm64 (2.28.3-1) ...

Removing libqrcodegencpp1:arm64 (1.8.0-1.1) ...

Removing libqt6svg6:arm64 (6.4.2-2) ...

Removing old xtrx-0.0.1+git20190320.5ae3a3e-3.2 DKMS files...

/usr/sbin/dkms: line 2497: echo: write error: Broken pipe

Deleting module xtrx-0.0.1+git20190320.5ae3a3e-3.2 completely from the DKMS tree.

Loading new xtrx-0.0.1+git20190320.5ae3a3e-3.2 DKMS files...

/usr/sbin/dkms: line 2497: echo: write error: Broken pipe

Building for 6.6.31+rpt-rpi-2712 6.6.31+rpt-rpi-v8

/usr/sbin/dkms: line 2497: echo: write error: Broken pipe

Building initial module for 6.6.31+rpt-rpi-2712

/usr/sbin/dkms: line 2497: echo: write error: Broken pipe

Error! Bad return status for module build on kernel: 6.6.31+rpt-rpi-2712 (aarch64)

Consult /var/lib/dkms/xtrx/0.0.1+git20190320.5ae3a3e-3.2/build/make.log for more information.

dpkg: error processing package xtrx-dkms (--configure):

 installed xtrx-dkms package post-installation script subprocess returned error exit status 10

Errors were encountered while processing:

 xtrx-dkms

E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by theofficialgman** [comment]
this has nothing to do with OBS Studio updates.

this is the same user error as experienced by another user https://github.com/Botspot/pi-apps/issues/2626

Please go to that issue if you have further questions.
