### ISSUE TITLE
Py-autoclicker - install based app

### ISSUE THREAD

**Issue by douxxu** [Botspot/pi-apps#2629]
### What is the name of the app?

Py-autoclicker

### Where is the app hosted?

Github: [repo base](https://github.com/douxxu/Py-autoclicker/)

### About the app

- Py-autoclicker is a python based autoclicker with a simple and intuitive GUI, similar to the one of opautoclicker.com. It can by used for multiple purposes.
- It uses the python module 'keyboard' to listen to your keyboard, and detect if you press the activation/stop key. It also use pyautogui to interact with your mouse.
- App eligibility:
1. The app needs to be useful for people who use their Raspberry Pi as an everyday, desktop computer:
- This app can be useful while, e.g. if you want to afk while gaming on your rpi.
- This app include a gui.
2. The app needs to be legal to download and use:
- Is an opensource app. [Github repo](https://github.com/douxxu/Py-autoclicker/)
3. The app should be appropriate for all ages:
- There is no nsfw or explicit content in this app.
4. Applications that support both ARM32 and ARM64:
- Both are supported.
5. The app may not have any malicious content:
- This app hasn't any viruses (e.g. stealers or trojans).

### Upload file or Add PR Link

[Py-autoclicker.zip](https://github.com/user-attachments/files/16472954/Py-autoclicker.zip)

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi-Apps app list.
- [X] I have read and followed the [creating an app for Pi-Apps documentation](https://pi-apps.io/wiki/development/Creating-an-app/).
- [X] I have confirmed that this app can run on all [Pi-Apps supported systems](https://pi-apps.io/install/).

**Comment by Botspot** [comment]
Does this work on both Wayland and X11?

**Comment by Botspot** [comment]
Also, if you are installing the menu launcher to all home directories, why not instead install it to a global location like `/usr/share/applications/py-autoclicker.desktop`

**Comment by douxxu** [comment]
> Does this work on both Wayland and X11?

I used it in both kde x11 and kde wayland, seems to works fine

**Comment by douxxu** [comment]
> Also, if you are installing the menu launcher to all home directories, why not instead install it to a global location like `/usr/share/applications/py-autoclicker.desktop`

Oh yeah, I didn't though about it, i'll soon update it, but I'll need to modify the uninstall script too. Can we do it one published or must we wait ? I'm not hurry anyways

**Comment by Botspot** [comment]
> Can we do it one published or must we wait ? I'm not hurry anyways

I do not completely understand what you are asking here, but feel free to update your github repo, and then upload a new zip file to this issue once you have changed the uninstall script.

**Comment by douxxu** [comment]
> > Can we do it one published or must we wait ? I'm not hurry anyways
> 
> I do not completely understand what you are asking here, but feel free to update your github repo, and then upload a new zip file to this issue once you have changed the uninstall script.

Ok no problem

**Comment by douxxu** [comment]
Hey, just modified the code, here is the new zip:

[Py-autoclicker.zip](https://github.com/user-attachments/files/16479353/Py-autoclicker.zip)

**Comment by Botspot** [comment]
Where is this app actually installing itself to? Is it just staying downloaded in /tmp?
I don't see any directories being removed in the `uninstall` script.

**Comment by douxxu** [comment]
> Where is this app actually installing itself to? Is it just staying downloaded in /tmp? 

Actually, the installer (`installer.py`) ask you to install the auto clicker necessary files into a custom directory you choose, and deletes himself and the GitHub repo. But the uninstall can't actually uninstall the chosen directory.. maybe I have to ask to input manually the path ?

**Comment by Botspot** [comment]
> > Where is this app actually installing itself to? Is it just staying downloaded in /tmp?
> 
> Actually, the installer (`installer.py`) ask you to install the auto clicker necessary files into a custom directory you choose, and deletes himself and the GitHub repo. But the uninstall can't actually uninstall the chosen directory.. maybe I have to ask to input manually the path ?

None of the other apps in pi-apps ask the user to specify an installation directory... why would anyone want that for an autoclicker? Just throw it in /opt or something

**Comment by Botspot** [comment]
Otherwise, any time this updates, it will get stuck and wait for the user to specify an installation directory, and that is assuming they even remember where they put it the first time.

**Comment by douxxu** [comment]
Yeah right, I'll modify it and make a simpler installer without gui in bash for pi apps, i'll

**Comment by douxxu** [comment]
Damn I missclicked.. so I was saying that I'll upload the zip when I finished it

**Comment by theofficialgman** [comment]
Regardless of the applications intended functionality, I do not trust or suggest advertising a single maintainer untrusted 3rd party keystroke generator.

It is not safe for us to advertise as you could maliciously update the application to execute keystrokes without our knowledge once the application has a large enough install base to execute an attack.

I would only be comfortable with an application with such functionality being advertised if it came from the official debian repos which have requirements and maintainers that vet applications for malicious intent before updating.

**Comment by Botspot** [comment]
> Regardless of the applications intended functionality, I do not trust or suggest advertising a single maintainer untrusted 3rd party keystroke generator.
> 
> It is not safe for us to advertise as you could maliciously update the application to execute keystrokes without our knowledge once the application has a large enough install base to execute an attack.
> 
> I would only be comfortable with an application with such functionality being advertised if it came from the official debian repos which have requirements and maintainers that vet applications for malicious intent before updating.

The same could be said for any 3rd-party application run by a single maintainer. Currently it only does mouse clicks, not keystrokes. If we adopt a standard against single maintainers, and apply it fairly, then many pre-existing apps would need review and potential removal. From a codebase perspective, I see nothing uniquely dangerous here - any python script could be maliciously updated to add new functionality unrelated to its original stated purpose.
@theofficialgman, if you are concerned about a malicious update for this app in particular, then ensuring it cannot auto-update for existing users would seem like a simple solution.

> Regardless of the applications intended functionality

To my understanding, autoclickers are useful for certain websites and games

**Comment by theofficialgman** [comment]
> The same could be said for any 3rd-party application run by a single maintainer. Currently it only does mouse clicks, not keystrokes.

Clicks are keystrokes. There is no difference between the two.

> If we adopt a standard against single maintainers, and apply it fairly, then many pre-existing apps would need review and potential removal.

This isn't the problem. See below.

> From a codebase perspective, I see nothing uniquely dangerous here - any python script could be maliciously updated to add new functionality unrelated to its original stated purpose.

The applications original purpose is a keystroke injector. It would be trivial for it to be edited to inject a number of malicious commands (eg: `rm -rf /`). Other applications are not keystroke injectors originally and would require additional work (and permissions) to add such functionality. 

The application has root privileges which is something no other application that is part of pi-apps has https://github.com/douxxu/Py-autoclicker/blob/5dca26db662fdb28f331178d422fa68eaaa80e5f/src/Py-autoclicker.py#L207 

> @theofficialgman, if you are concerned about a malicious update for this app in particular, then ensuring it cannot auto-update for existing users would seem like a simple solution.

I do not want the application period for the reasons above.

**Comment by theofficialgman** [comment]
> To my understanding, autoclickers are useful for certain websites and games

imho, the applications value is vastly outweighed by its risk. users can accept that risk themselves by seeking it out on their own but I do not want to promote such and application and take that risk on myself.

**Comment by Botspot** [comment]
Very well then.
