### ISSUE TITLE
Bino3d

### ISSUE THREAD

**Issue by hubertmeier** [Botspot/pi-apps#2630]
### What is the name of the app?

Bino3d

### Where is the app hosted?

https://github.com/marlam/bino

### About the app

**It's the only availbale 3D-Videoplayer ... and it works fine on windows and linux systems**, but sadly not on the raspian os. You will find an issue from me and the nice communication with the author. The actual version requires qt6.6 which is not available and with the previous version i have trouble with compiling, but there a people with more knowledges than me.

You will find the issue here:

https://github.com/marlam/bino/issues

I had to click "I have confirmed that this app can run on Raspberry Pi" ... The author suggested that this app should run on the Raspi. Thank you

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have read the app eligibilty rubric https://github.com/Botspot/pi-apps/issues/185 and confirmed this app is suitable for addition in Pi-Apps.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi-Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by Botspot** [comment]
I see the issue. https://github.com/marlam/bino/issues/27
How are we at Pi-Apps supposed to help with this? I am not sure what you were hoping for when you opened this issue requesting an app that does not run on the Pi yet.

**Comment by hubertmeier** [comment]
I thought, you have much more experience in compiling software than me... Ok, if the author finds a solution an we get it to work I will post a comment here.

**Comment by Botspot** [comment]
Feel free to comment back here if anything changes. For now I think it's best to close this issue, but that does not prevent you from leaving further updates. We can reopen it if the recompilation is successful.

@theofficialgman I vaguely recall you having some QT6 tips and tricks somewhere... if you feel they are relevant then consider sharing it either here or in the issue on the bino repo.

**Comment by theofficialgman** [comment]
Seems to simply be an upstream issue and they are resolving it slowly.

If QT6.6+ is required its best to use a flatpak as they are already doing or use a distribution where QT6.6+ is already available (eg: KDE Neon). You can build your own flatpak packages for testing, it is not too difficult and every package on flathub has public information for doing so.

**Comment by hubertmeier** [comment]
Marlam built a new version which is available as a flatpak package at bino3d.org which works now on rpi5
