### ISSUE TITLE
terminal not showing on manage install/uninstall/updates

### ISSUE THREAD

**Issue by Nitivity90CODER** [Botspot/pi-apps#2631]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi-Apps and the issue is still not fixed. [How to update Pi-Apps?](https://pi-apps.io/wiki/getting-started/updating-pi-apps/)
- [X] IMPORTANT: I promise to respond to comments on this issue and write a good bug report https://www.softwaretestinghelp.com/how-to-write-good-bug-report/

### What happened?

'Apps' technically ..... won't install... 

### Description

When I click on an app to install it, it just doesn't install. No terminal is opening, no apps opening, not even Pi-Apps is showing anything about it installing. I asked chat-gpt why it is'nt working but the code chat-gpt game wasn't working. Plz fix this problem as soon as possible. I really need to use Pi-Apps for my raspberry pi 4!

Thanks,
Nitivity90BRO

PI APPS looks different from now...

### What are your system specs (run the following command in your terminal)?

```bash
OS: Raspberry pi os or 'Raspberrien' Idk how to spell it
OS architecture: ARMv8-A architecture
Last updated Pi-Apps: 8/4/2
Latest PI-Apps version: Up to date
IDK WHAT KERNEL IS
Device model: Raspberry Pi 4
IDK WHAT SOC IDENTIFIER IS
CPU name: Broadcom BCM2711
RAM Size:OS: Raspberry pi os or 'Raspberrien' Idk how to spell it
OS architecture: ARMv8-A architecture
Last updated Pi-Apps: 8/4/2
Latest PI-Apps version: Up to date
IDK WHAT KERNEL IS
Device model: Raspberry Pi 4
IDK WHAT SOC IDENTIFIER IS
CPU name: Broadcom BCM2711
Ram size: 3.7
IDK WHAT IS THE Raspberry pi 4 os image version
Language: English
```

### (Recommended) Error log? Terminal output? Debug messages?

```bash
If no terminal popped up then why this
```

**Comment by Nitivity90CODER** [comment]
Also, make sure to email me at nitivitybro@gmail.com or message on imessage at nitivitybro@gmail.com

**Comment by Botspot** [comment]
When there are replies here, it should email you. You might want to delete that comment with your contact information so you don't get spammed by bots who find your message.

Please send a screenshot or a video of what you see.

```
OS: Raspberry pi os or 'Raspberrien' Idk how to spell it
OS architecture: ARMv8-A architecture
Last updated Pi-Apps: 8/4/2
Latest PI-Apps version: Up to date
IDK WHAT KERNEL IS
Device model: Raspberry Pi 4
IDK WHAT SOC IDENTIFIER IS
CPU name: Broadcom BCM2711
RAM Size:OS: Raspberry pi os or 'Raspberrien' Idk how to spell it
OS architecture: ARMv8-A architecture
Last updated Pi-Apps: 8/4/2
Latest PI-Apps version: Up to date
IDK WHAT KERNEL IS
Device model: Raspberry Pi 4
IDK WHAT SOC IDENTIFIER IS
CPU name: Broadcom BCM2711
Ram size: 3.7
IDK WHAT IS THE Raspberry pi 4 os image version
Language: English
```
You filled that out manually?? Ouch. Pi-Apps is supposed to give you all that information. We don't ask that you find it yourself.
Just open a terminal and run `~/pi-apps/api get_device_info`
It should look like this:
![20240804_22h04m17s_grim](https://github.com/user-attachments/assets/60c81b21-c5cd-416c-b07a-5a14e69bff9c)
Then, go to github.com on your pi if you are not already, and copy the output from the terminal to the web. You should not need to manually type it all out.

**Comment by Nitivity90CODER** [comment]
Leave it...... It already got fixed after starting fresh on my Raspberry Pi
4

**Comment by Botspot** [comment]
ok
