### ISSUE TITLE
Bisq - P2P open source bitcoin exchange

### ISSUE THREAD

**Issue by Combustion-is-fun** [Botspot/pi-apps#2632]
### What is the name of the app?

Bisq

### Where is the app hosted?

Github mostly but there is an official website if you want to build from there zip file.  I would recommend using the work of someone who has already tried this.
The Github page [Running Bisq on Raspberry Pi](https://gist.github.com/tmakerman/ee53a94c3cfc8362192ad9df20709547) is the process to build a version that works on the Raspberry Pi. 
This is the official website: https://bisq.network/

### About the app

This is a way to exchange bitcoin for fiat or other crypto including Monero for your Monero GUI app.
The link I am providing you leads to the GUI app has been configured to work on a Raspberry Pi so it should work. The reason for me providing you with this information is that it would increase the value of the Monero GUI app to the average user but I am too busy to build it myself. 

# The following extract has been taken from the official website

### How is Bisq different from other decentralized exchanges?
Bisq is a peer-to-peer trading network, not a website or "app"  or other centralized service. It's software you run on your own hardware, which connects to other people running the Bisq software to facilitate trades. It's open-source and community-driven.

And you can trade bitcoin for fiat currencies with it!

The difference between Bisq and other so-called decentralized exchanges is as stark as the difference between owning your own home and renting someone else's—in the former case you have full control over the property, and in the latter you're always subject to the landlord's whims and demands (no matter how nice the landlord may seem to be).

With Bisq you're always the owner—not just owner of your bitcoin, but also owner of your data.

Bisq does not hold any bitcoin. All bitcoin used for trading is held in 2-of-2 multisignature addresses controlled solely by the trading peers themselves.
* Bisq does not hold any national currency. National currency is transferred directly from one trader to the other using traditional banking and payment services.
* All Bisq data is transferred over its own secure peer-to-peer network, which is built on top of the Tor network—no central servers. This means there are no data honeypots, rendering large-scale hacks of customer information databases impossible.
* Bisq does not know anything about traders who use its network, and no data is stored on who trades with whom.
* Bisq does not require registration, so your privacy is protected, and you can begin trading instantly.
* Bisq is code, not a company. It is an open-source project organized as a [decentralized autonomous organization (DAO)](https://bisq.wiki/Decentralized_autonomous_organization) built on top of Bitcoin.

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have read the app eligibilty rubric https://github.com/Botspot/pi-apps/issues/185 and confirmed this app is suitable for addition in Pi-Apps.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi-Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by Botspot** [comment]
> ### Where is the app hosted?
> Github mostly but there is an official website if you want to build from there zip file. I would recommend using the work of someone who has already tried this. The Github page [Running Bisq on Raspberry Pi](https://gist.github.com/tmakerman/ee53a94c3cfc8362192ad9df20709547) is the process to build a version that works on the Raspberry Pi.

Ironically, I had this link open in a tab for months waiting to try this, then my browser config got corrupted and I cleared it out and forgot what was open.
So thanks for the reminder. The install process given in that tutorial is fairly long and could probably be shortened. I could try to simplify it, but I would prefer to be doing that alongside someone familiar with using Bisq to confirm everything works.

I checked back at those instructions and see two main areas for improvement:
- For example, restarting in the middle of installation is a problem. That would need to be eliminated somehow.
- Hopefully it turns out that installing one specific JDK11 is unnecessary.

**Comment by Combustion-is-fun** [comment]
# Someone smarter than me...
I do not know how to use Bisq at all it seemed like the only possible way to use Monero <-->Fiat (via Bitcoin) on a Raspberry Pi. I have a mental list of software that I am trying to get on Pi apps to turn the RPI into a privacy-secure desktop. (I am enjoying Brave, Tor, Signal and ProtonVPN) Bisq helps only by making easy transactions of common cryptocurrency.

**Comment by theofficialgman** [comment]
We are not interested in porting projects at this time. As upstream bisq does not have aarch64/armv7l linux support please PR support for that upstream first so that it can be built and run without using a year out of date fork that is unmaintained (eg: at minimum a security risk)
