### ISSUE TITLE
How to control pi-apps via ansible?

### ISSUE THREAD

**Issue by Lonerider2010** [Botspot/pi-apps#2634]
### Cool ideas?

Does anyone have any experience with controlling pi-apps via ansible?

**Comment by Botspot** [comment]
There should be no need to automate pi-apps in this way. Check out our `manage` and `api` scripts - they should do more than you could ever need.
If you need to automate something specifically, please let us know and we can help point you in the right direction.

Read the Wiki and you should be good to go. https://pi-apps.io/wiki/

**Comment by theofficialgman** [comment]
Closing as unactionable.
