### ISSUE TITLE
Bambu Studio failed to install on RPi - 5

### ISSUE THREAD

**Issue by tomsmeyer** [Botspot/pi-apps#2635]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi-Apps and the issue is still not fixed. [How to update Pi-Apps?](https://pi-apps.io/wiki/getting-started/updating-pi-apps/)
- [X] IMPORTANT: I promise to respond to comments on this issue and write a good bug report https://www.softwaretestinghelp.com/how-to-write-good-bug-report/

### What happened?

Bambu Labs app won't install

### Description

Bambu Labs Studio will not install. It appears to be failing to get files from peer on com.bambulab.BambuStudio.
I just installed Pi-Apps, so it is a new release. I also did an apt-get update and upgrade prior to installation.

### What are your system specs (run the following command in your terminal)?

```bash
OS: Debian GNU/Linux 12 (bookworm)
OS architecture: 64-bit
Last updated Pi-Apps on: 08/18/2024
Latest Pi-Apps version: 08/17/2024
Kernel: aarch64 6.6.31+rpt-rpi-2712
Device model: Raspberry Pi 5 Model B Rev 1.0
SOC identifier: bcm2712
Cpu name: Cortex-A76
Ram size: 8.05 GB
Raspberry Pi OS image version: 2024-03-15
Language: en_US.UTF-8
```

### (Recommended) Error log? Terminal output? Debug messages?

```bash
OS: Debian GNU/Linux 12 (bookworm)
OS architecture: 64-bit
Last updated Pi-Apps on: 08/18/2024
Latest Pi-Apps version: 08/17/2024
Kernel: aarch64 6.6.31+rpt-rpi-2712
Device model: Raspberry Pi 5 Model B Rev 1.0
SOC identifier: bcm2712
Cpu name: Cortex-A76
Ram size: 8.05 GB
Raspberry Pi OS image version: 2024-03-15
Language: en_US.UTF-8

BEGINNING OF LOG FILE:
-----------------------

Will install these packages: flatpak 
Creating an empty apt-package to install the necessary apt packages...
It will be named: pi-apps-67e75edb
Depends: flatpak
Running sudo apt update...
Hit:1 http://deb.debian.org/debian bookworm InRelease
Hit:2 http://deb.debian.org/debian-security bookworm-security InRelease
Hit:3 http://deb.debian.org/debian bookworm-updates InRelease
Hit:4 http://archive.raspberrypi.com/debian bookworm InRelease
All packages are up to date.
apt update complete.
Installing the pi-apps-67e75edb package...
The following additional packages will be installed:
  flatpak libmalcontent-0-0 libostree-1-1
Suggested packages:
  malcontent-gui
The following NEW packages will be installed:
  flatpak libmalcontent-0-0 libostree-1-1 pi-apps-67e75edb
0 upgraded, 4 newly installed, 0 to remove and 0 not upgraded.
After this operation, 8,681 kB of additional disk space will be used.
Get:1 /tmp/pi-apps-67e75edb.deb pi-apps-67e75edb all 1.0 [748 B]
Get:2 http://deb.debian.org/debian bookworm/main arm64 libmalcontent-0-0 arm64 0.11.0-4 [20.4 kB]
Get:3 http://deb.debian.org/debian bookworm/main arm64 libostree-1-1 arm64 2022.7-2 [284 kB]
Get:4 http://deb.debian.org/debian-security bookworm-security/main arm64 flatpak arm64 1.14.10-1~deb12u1 [1,325 kB]
Fetched 1,629 kB in 0s (4,826 kB/s)
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 188208 files and directories currently installed.)

Unpacking libmalcontent-0-0:arm64 (0.11.0-4) ...

Unpacking libostree-1-1:arm64 (2022.7-2) ...

Unpacking flatpak (1.14.10-1~deb12u1) ...

Unpacking pi-apps-67e75edb (1.0) ...

Apt finished.
Package installation complete.
Flatpak: Adding flathub remote... Done
Flatpak: installing com.bambulab.BambuStudio... Error: While pulling app/com.bambulab.BambuStudio/aarch64/stable from remote flathub: While fetching https://dl.flathub.org/repo/deltas/cU/e65PrO9m6BH1v9sTcQ6pJd11gk1zYzC2J9P8pxy_4/1: [56] Failure when receiving data from the peer
error: Failed to install com.bambulab.BambuStudio: While pulling app/com.bambulab.BambuStudio/aarch64/stable from remote flathub: While fetching https://dl.flathub.org/repo/deltas/cU/e65PrO9m6BH1v9sTcQ6pJd11gk1zYzC2J9P8pxy_4/1: [56] Failure when receiving data from the peer
Error: While pulling app/com.bambulab.BambuStudio/aarch64/stable from remote flathub: While fetching https://dl.flathub.org/repo/objects/3d/297ffbe65b9105a884de033d95ab0c847d0737c3acf0ff8a38a440efe38516.filez: [56] Failure when receiving data from the peer
error: Failed to install com.bambulab.BambuStudio: While pulling app/com.bambulab.BambuStudio/aarch64/stable from remote flathub: While fetching https://dl.flathub.org/repo/objects/3d/297ffbe65b9105a884de033d95ab0c847d0737c3acf0ff8a38a440efe38516.filez: [56] Failure when receiving data from the peer
Flatpak failed to install com.bambulab.BambuStudio!

Running purge_packages...
Allowing packages required by the Bambu Studio app to be uninstalled
These packages were: flatpak
Purging the pi-apps-67e75edb package...
The following packages will be REMOVED:
  flatpak* libmalcontent-0-0* libostree-1-1* pi-apps-67e75edb*
0 upgraded, 0 newly installed, 4 to remove and 0 not upgraded.
After this operation, 8,681 kB disk space will be freed.
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 188349 files and directories currently installed.)

Removing pi-apps-67e75edb (1.0) ...

Removing flatpak (1.14.10-1~deb12u1) ...

Removing libmalcontent-0-0:arm64 (0.11.0-4) ...

Removing libostree-1-1:arm64 (2022.7-2) ...

(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 188210 files and directories currently installed.)

Purging configuration files for flatpak (1.14.10-1~deb12u1) ...

Apt finished.
All packages have been purged successfully.

Failed to install Bambu Studio!
◢◣Need help? Copy the ENTIRE terminal output or take a screenshot.
Please ask on Github: https://github.com/Botspot/pi-apps/issues/new/choose
Or on Discord: https://discord.gg/RXSTvaUvuu
```

**Comment by Botspot** [comment]
This looks like a symptom of an unreliable internet connection.
Have you tried installing Bambu Studio several times, and was the error the same each time?

**Comment by tomsmeyer** [comment]
First, thanks for your response.

Yes, and yes. I have no problems doing Raspian updates and upgrades. I also
installed other software today without issue.

Thanks,
Tom

Tom Meyer
***@***.***

**Comment by Botspot** [comment]
Let's check if the site is blocked.
Can you try downloading the URL mentioned in the error?
First, on your Pi go to this link in your web browser: https://dl.flathub.org/repo/objects/3d/297ffbe65b9105a884de033d95ab0c847d0737c3acf0ff8a38a440efe38516.filez
See if it loads, or displays an error.
Also, try downloading it with this command:
```
wget -O /dev/null https://dl.flathub.org/repo/objects/3d/297ffbe65b9105a884de033d95ab0c847d0737c3acf0ff8a38a440efe38516.filez
```
Note that we only really care about the progress bar. This command does not actually save the file to disk.
I just checked and on my machine, this `wget` command succeeds.

**Comment by tomsmeyer** [comment]
The link downloaded, and the wget also worked. Both downloaded a 68.8 MB
file.


Tom Meyer
***@***.***

**Comment by Botspot** [comment]
At this point, I suggest you ask for help from Flatpak for why wget can download the file but flatpak cannot.
We from Pi-Apps can help you no further.

**Comment by tomsmeyer** [comment]
Thanks anyway.

**Comment by tomsmeyer** [comment]
One last request. I visited the Flatpack page on GitHub but did not find a way to ask a question. Can you point me to the appropriate discussion?

Thanks again,
Tom

**Comment by tomsmeyer** [comment]
One more question. Is there a way to install Bambu Studio without Pi-Apps? Simple command line?

Thanks again,
Tom

**Comment by Botspot** [comment]
Maybe https://github.com/flatpak/flatpak/issues

**Comment by Botspot** [comment]
> One more question. Is there a way to install Bambu Studio without Pi-Apps? Simple command line?
> 
> Thanks again, Tom

the only practical way I know of to get Bambu Studio installed on ARM64 is through flatpak. Nothing is stopping you from using the `flatpak` command directly, though I doubt that would make any difference as Pi-Apps is using the `fpatpak` command in the script already.

**Comment by tomsmeyer** [comment]
I sent word to Flatpack, where I outlined the problem, and included the
error messages from Pi-Apps.  This was their reply.
Hubert Figuière ***@***.***>4:58 PM (6 hours ago)

to flatpak/flatpak, me, Author

No idea what Pi-Apps is and what it is doing. But unless you are using
flatpak directly, then you should be talking to Pi-Apps.

End of reply

Please advise,
Tom Meyer
***@***.***

**Comment by Botspot** [comment]
> I sent word to Flatpack, where I outlined the problem, and included the error messages from Pi-Apps. This was their reply. Hubert Figuière ***@***.***>4:58 PM (6 hours ago) to flatpak/flatpak, me, Author No idea what Pi-Apps is and what it is doing. But unless you are using flatpak directly, then you should be talking to Pi-Apps. End of reply Please advise, Tom 

This is a fair response. I suggest you keep make it clear that pi-apps is just using flatpak directly, or better yet, leave pi-apps out of it completely.

This is the Bambu Studio install-64 script in the pi-apps folder:
```bash
#!/bin/bash

install_packages flatpak || exit 1

flatpak_install com.bambulab.BambuStudio || exit 1
```
So in normal commands that can be translated as:
```
sudo apt install flatpak -y
sudo flatpak install flathub com.bambulab.BambuStudio -y
```
Go ahead and run that command.
- If it fails, then now you can clarify on your help request that pi-apps is not involved in the error, and you can reproduce the error by using flatpak directly.
- If it succeeds, let us know. This would be very strange if it led back to a bug in pi-apps, but useful to know.
