### ISSUE TITLE
Several Pi-Apps work pretty well in the virtual machines on the Lenovo Duet 3 Aarch64 Chromebook OS!

### ISSUE THREAD

**Issue by SugarRayLua** [Botspot/pi-apps#2637]
### Cool ideas?

Hi, Pi-App developers.

I know the Pi-Apps website states that it is unlikely that Pi-Apps will work on Chrome OS, but I recently purchased an new Aarch64 Chromebook OS and another person on GitHub from the FydeOS community suggesting I try Pi-Apps and wanted to report back that it works great in the virtual machines on my Chrome OS!

I installed the following Pi-Apps that work great on my ChromeOS:
Signal (couldn't get the default to work from Debian repository in my Debian virtual machine but the Pi-Apps version works great!)
Box86
Box64
Wine

I installed the last few to see if I could get Wine working well on the virtual machine in my ChromeOS to see if I could play any of the newer Windows games and to my pleasant surprise all of those 3 apps worked perfectly! (Since on ChromeOS you can't use privileged containers without disabling some of ChromeOS's security, I did need to run an additional Bash script from the box86 developer to get it to work in addition to needing to install DXVK since the game uses Direct X 11) 

As a novice Linux and Chrome OS virtual machine user where I can find a standard repository solution for my Aarch64 virtual machines needs, I'll again first look in Pi-Apps and recommend it to other ChromeOS virtual machines users.

Fyi,
Have a good week :-)

**Comment by Botspot** [comment]
It is my understanding that without binfmt, wine won't work. What script from the box86 developer are you referring to?

**Comment by theofficialgman** [comment]
Thanks for the information. However our stance on support is unchanged as chromeOS containers cannot install binfmt https://issues.chromium.org/issues/40175258 and is missing many other standard linux feature support
