### ISSUE TITLE
(bug) Minecraft Bedrock will not download and it says failed this happened on the new update

### ISSUE THREAD

**Issue by Th4tM4t** [Botspot/pi-apps#264]

**Comment by Th4tM4t** [comment]
I dont use github so how do i lable it bug

**Comment by Botspot** [comment]
You need to give more information than that. :(

How can I help you with what you've given me?

**Comment by mobilegmYT** [comment]
@Th4tM4t Issue has been fixed with a new commit, please update and try again :)
