### ISSUE TITLE
APP Request: Bino3d

### ISSUE THREAD

**Issue by hubertmeier** [Botspot/pi-apps#2645]
### What is the name of the app?

Bino3d

### Where is the app hosted?

https://github.com/marlam/bino

### About the app

This is one of the rare ( i dont know any other) 3D-Player Apps, it reqires Qt6 and the author has made it work for the raspberry (many thanks to marlam). It would be great to have this installation easy by pi-apps.
It's important to know that after compiling and installation the app must be startet with the parameter

**bino --opengles**

because raspberry os has OpenGL ES built in. Without this parameter there is only a black window.

**_The recipe to build it should be:_**

git clone https://github.com/marlam/bino.git
cd bino
mkdir build
cd build
cmake ..
make
sudo make install

Here is the link to the issue at marlams repo: https://github.com/marlam/bino/issues/27

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have read the app eligibilty rubric https://github.com/Botspot/pi-apps/issues/185 and confirmed this app is suitable for addition in Pi-Apps.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi-Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by theofficialgman** [comment]
Closing as unable to support. QT6.6 is not available in the default repositories for any of the distros we support.

The flatpak package is available but cannot be used due to the following issue that affects all versions of the application: If upstream fixes their software to automatically use the appropriate GL/GLES renderer based on what the drivers report as available this can be reopened. As it is now, the application does not work out of the box.

**Comment by hubertmeier** [comment]
Hi,

Marlam as owner from bino3d.org has solved all problems with rpi5, there is now a working Flathub package.

Is this interesting for pi-apps?

**Comment by hubertmeier** [comment]
Hi, would you give bino3d a new try? I got it to work on a fresh raspberry os Trixie with the steps from the recipe on the website ... 

The only exception is the last step which requires sudo.

Thank you
