### ISSUE TITLE
remove deprecated and unnecessary `--ignore-gpu-blacklist` flag in Better Chromium

### ISSUE THREAD

**Issue by glanduin** [Botspot/pi-apps#2647]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi-Apps and the issue is still not fixed. [How to update Pi-Apps?](https://pi-apps.io/wiki/getting-started/updating-pi-apps/)
- [X] IMPORTANT: I promise to respond to comments on this issue and write a good bug report https://www.softwaretestinghelp.com/how-to-write-good-bug-report/

### What happened?

Not much. It is just a typo in the code i assume.

### Description

In the installation script of Better Chromium, there is this line (501)

`  flags="--ignore-gpu-blacklist --enable-checker-imaging --cc-scroll-animation-duration-in-seconds=0.6 --disable-quic --enable-tcp-fast-open --enable-experimental-canvas-features --enable-scroll-prediction --enable-simple-cache-backend --max-tiles-for-interest-area=512 --num-raster-threads=4 --default-tile-height=512 --enable-features=VaapiVideoDecoder,VaapiVideoEncoder,ParallelDownloading --disable-features=UseChromeOSDirectVideoDecoder --enable-accelerated-video-decode --enable-low-res-tiling --process-per-site"`

I think the "ignore-gpu-blacklist" should be "ignore-gpu-blocklist" instead, to be correct. To go to that particular flag in Chromium you need to type:

chrome://flags/#ignore-gpu-blocklist

### What are your system specs (run the following command in your terminal)?

```bash
OS: Debian GNU/Linux 12 (bookworm)
OS architecture: 64-bit
Last updated Pi-Apps on: 09/16/2024
Latest Pi-Apps version: 09/16/2024
Kernel: aarch64 6.6.47+rpt-rpi-2712
Device model: Raspberry Pi 5 Model B Rev 1.0
SOC identifier: bcm2712
Cpu name: Cortex-A76
Ram size: 4.04 GB
Raspberry Pi OS image version: 2024-03-15
Language: en_US.UTF-8
```

**Comment by theofficialgman** [comment]
> I think the "ignore-gpu-blacklist" should be "ignore-gpu-blocklist" instead, to be correct

Its not a typo. That used to be the command but they renamed it mid 2020 (https://chromium-review.googlesource.com/c/chromium/src/+/2289414) and then removed compatibility with the original in late 2020 (https://chromium-review.googlesource.com/c/chromium/src/+/2540668).

This doesn't necessitate an immediate change as it isn't required to have hardware acceleration.

**Comment by Botspot** [comment]
I think the name change was due to some people thinking "blacklist" is a racist term.
