### ISSUE TITLE
no working

### ISSUE THREAD

**Issue by srini-pro** [Botspot/pi-apps#265]
Failed to run sudo apt update!
APT reported these errors:
W: Target Packages (contrib/binary-all/Packages) is configured multiple times in /etc/apt/sources.list:4 and /etc/apt/sources.list.d/virtualbox.list:1
W: Target Translations (contrib/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list:4 and /etc/apt/sources.list.d/virtualbox.list:1
W: Target Packages (contrib/binary-all/Packages) is configured multiple times in /etc/apt/sources.list:4 and /etc/apt/sources.list.d/virtualbox.list:1
W: Target Translations (contrib/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list:4 and /etc/apt/sources.list.d/virtualbox.list:1

**Comment by Itai-Nelken** [comment]
when did that happen?

**Comment by Botspot** [comment]
@srini-pro Pi-Apps had nothing to do with this.  
It looks like you were playing around with Virtualbox. Try this: run `sudo apt update` in a terminal and see errors.

**Comment by srini-pro** [comment]
ok thanks for help i acctuallly needed help

**Comment by srini-pro** [comment]
no this is not the system pi apps couldnt  update
