### ISSUE TITLE
Cant find Steam on 64-bit device

### ISSUE THREAD

**Issue by 06NinjaKid06** [Botspot/pi-apps#2650]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi-Apps and the issue is still not fixed. [How to update Pi-Apps?](https://pi-apps.io/wiki/getting-started/updating-pi-apps/)
- [X] IMPORTANT: I promise to respond to comments on this issue and write a good bug report https://www.softwaretestinghelp.com/how-to-write-good-bug-report/

### What happened?

I can't find steam in the Games section on aarch64.

### Description

I'm on my nintendo switch and i see an article that tells me to use piapps to install steam on arm. I install piapps, search it, but it's not there.
![20240928_204614](https://github.com/user-attachments/assets/541ea7ab-74b9-49ae-9ae4-fcdbf1caffa8)

### What are your system specs (run the following command in your terminal)?

```bash
OS: Ubuntu 24.04.1 LTS
OS architecture: 64-bit
Last updated Pi-Apps on: 09/28/2024
Latest Pi-Apps version: 09/28/2024
Device model: Nintendo Switch (2017)
SOC identifier: tegra-x1
Machine-id (hashed): [I'm using my phone to type this id rather not type this]
Serial-number (hashed): [same as above]
Cpu name: Cortex-A57
Ram size: 3.99 GB
Language: en_us.UTF-8
```

### (Recommended) Error log? Terminal output? Debug messages?

```bash
No output
```

**Comment by SagarChandra07** [comment]
maybe this will help
https://bit.ly/47P0Nvo
Pass: changeme
If you don't have the c compliator, install it.(gcc or clang)

**Comment by 06NinjaKid06** [comment]
that is so sketchy bro nah I'm good, give me commands to run instead.

**Comment by 06NinjaKid06** [comment]
I fixed it myself, but keeping this open incase someone else has this problem. ( for me the fix was just don't use pi-apps )

**Comment by theofficialgman** [comment]
Working as intended. Steam is hidden on (Nvidia) tegra devices as they cannot natively run 32bit arm graphical applications due to not having 32bit arm GPU drivers from Nvidia.

Install steam from the L4T-Megascript which contains compatibility layers to allow Steam 32bit processes to use the 64bit graphics drivers (with a heavy performance penalty but there are no other options currently until Box32).
