### ISSUE TITLE
It says Pi-Apps is not designed to be installed as root! Please try again as a regular user.

### ISSUE THREAD

**Issue by MaxFlame123** [Botspot/pi-apps#2656]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [ ] I tried updating Pi-Apps and the issue is still not fixed. [How to update Pi-Apps?](https://pi-apps.io/wiki/getting-started/updating-pi-apps/)
- [X] IMPORTANT: I promise to respond to comments on this issue and write a good bug report https://www.softwaretestinghelp.com/how-to-write-good-bug-report/

### What happened?

Can't install pi apps

### Description

Haven't fixed it it says that the pi apps isn't rooted and need to be a regular user

### What are your system specs (run the following command in your terminal)?

```bash
Os Linux
Architecture O
```

### (Recommended) Error log? Terminal output? Debug messages?

```bash
Pi-Apps is not designed to be installed as root! Please try again as a regular user.
```

**Comment by Botspot** [comment]
Could you describe your operating system and device that you are trying to install Pi-Apps on? Does your operating system have a normal user account that is not the `root` account?

**Comment by MaxFlame123** [comment]
I am using a android fire hd 8 tablet and it doesn't have a not rooted account

On October 9, 2024, at 1:35 PM, Botspot ***@***.***> wrote:

Could you describe your operating system and device that you are trying to install Pi-Apps on? Does your operating system have a normal user account that is not the root account?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.￼Message ID: ***@***.***>

[ { ***@***.***": "<a href="http://schema.org">http://schema.org</a>", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "<a href="https://github.com/Botspot/pi-apps/issues/2656#issuecomment-2402201155">https://github.com/Botspot/pi-apps/issues/2656#issuecomment-2402201155</a>", "url": "<a href="https://github.com/Botspot/pi-apps/issues/2656#issuecomment-2402201155">https://github.com/Botspot/pi-apps/issues/2656#issuecomment-2402201155</a>", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "<a href="https://github.com">https://github.com</a>" } } ]

**Comment by theofficialgman** [comment]
This is working as intended. Pi-Apps and many applications that can be installed in it are designed to be run as uuid 1000 (user level) and not uuid 0 (root level). This check is intentional and will not be adjusted.

If you want to use pi-apps (still unsupported for you since you are not using [supported hardware](https://pi-apps.io/install/#supported-systems:)) and the applications that can be installed with it you will need to create and operate pi-apps and its applications as a uuid 1000 (user level) user account.

**Comment by MaxFlame123** [comment]
Can you tell me how to make it a uuid 1000 (user level) user account

**Comment by Botspot** [comment]
> Can you tell me how to make it a uuid 1000 (user level) user account

That is a good question for chatgpt. https://talkai.info/chat/
