### ISSUE TITLE
App Suggestion: untis-py

### ISSUE THREAD

**Issue by l-koehler** [Botspot/pi-apps#2657]
### What is the name of the app?

untis-py

### Where is the app hosted?

https://github.com/l-koehler/untis-py

### About the app

The App is a alternative to the WebUntis website, which is frequently used at German/Austrian schools and universities as a digital timetable.
It requires far less performance and data than using a web browser, and also stores timetables locally.
Devices without Internet access can also check the timetable, provided that week was viewed at least once before.
It is written in python, so it should work just fine on the Raspberry Pi with installing the requirements.txt, then using the provided install.sh.

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have read the app eligibilty rubric https://github.com/Botspot/pi-apps/issues/185 and confirmed this app is suitable for addition in Pi-Apps.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi-Apps app list.
- [ ] I have confirmed that this app can run on Raspberry Pi.

**Comment by theofficialgman** [comment]
We do not take porting requests. We cannot support applications that do not run on ALL our diverse range of supported systems and distributions <https://pi-apps.io/install/#supported-systems:>
This application requires a very specific version of QT6 (not available on any of our supported systems) https://github.com/l-koehler/untis-py/blob/da9839ba5ba8b8e40a29d4229c9b2149d906031a/requirements.txt#L2
If you work with upstream to provide a more portable version of the application (eg: flatpak or appimage with all libraries contained) they there is a possibility this could be considered. Even if that is done we may still refuse to include the application as neither myself nor the other maintainer have any way of testing the application.

**Comment by l-koehler** [comment]
PyQt6 is not strictly required, the app can work with PyQt5 too ([which is supported](https://www.pythonguis.com/installation/install-pyqt5-raspberry-pi/)). This is just not reflected in the requirements.txt because the format doesn't allow specifying any-of-several packages as needed.
I use the app on a PinePhone, so ARM devices are tested (not on a raspberry, but still).
