### ISSUE TITLE
ArmCord rebranded to Legcord

### ISSUE THREAD

**Issue by Andrew-J-Larson** [Botspot/pi-apps#2659]
Still functionally the same, they just had to do a name change because of a cease and desist from Arm (the corporation).

More info about the name change is on their Discord: https://discord.com/channels/820732039253852171/821385577194717194/1294353795647668306

https://github.com/Legcord/Legcord

**Comment by Botspot** [comment]
Yeah I saw it. I have all necessary changes ready to push, but at the moment I have been having some trouble getting LegCord to launch.

**Comment by Botspot** [comment]
Lead dev of legcord has confirmed a launch bug and plans to fix it tomorrow.

**Comment by theofficialgman** [comment]
@Andrew-J-Larson just an fyi, I would classify this as a "Suggestion" based on our current descriptions as this is not a new application to pi-apps

![image](https://github.com/user-attachments/assets/5b71230c-0d24-41fd-834d-5cf9237807f8)

let us know if we can provide any further clarification regarding our issue template descriptions.

**Comment by theofficialgman** [comment]
> at the moment I have been having some trouble getting LegCord to launch.
> Lead dev of legcord has confirmed a launch bug and plans to fix it tomorrow.

Any mention of that publicly? A quick scan of the discord and github didn't bring me any results.

**Comment by Botspot** [comment]
He says https://github.com/Legcord/Legcord/releases/tag/v1.0.1 should work.

**Comment by theofficialgman** [comment]
> I have all necessary changes ready to push

Regarding this, I am not sure what your plan was for this but I would prefer and recommend that the system standardized with our latest transition (Geekbench to Geekbench 5) be used here and the runonce be made just like that for Armcord -> Legcord.

**Comment by theofficialgman** [comment]
@Botspot it seems my recommendation was ignored https://github.com/Botspot/pi-apps/commit/f593c97e225fb37be96371ee462fe42213292279#diff-7035412399e0395e1ed812fc1f3f1eb906b9b33e5149c2c2ab2916c1cc78c22bR175-R177

this won't work for users that have Armcord installed. They will be left with Armcord and will not update to Legcord until the next release after they have had this runonce executed.

The method I suggested avoids that issue.

**Comment by Botspot** [comment]
I apologize. I only saw your message after making the commit. Will fix.

**Comment by theofficialgman** [comment]
@Botspot I think branding is wrong here
It is Legcord not LegCord

**Comment by theofficialgman** [comment]
handled with https://github.com/Botspot/pi-apps/commit/3a60909666ac02fe6479ed8764b7bbae5b16d595 (see commit message)
