### ISSUE TITLE
Conky Manager Installed with Conky

### ISSUE THREAD

**Issue by techcoder20** [Botspot/pi-apps#266]
Configure conky app to install both conky and conky manager

Installation Commands by Chunky Milk:
```
wget https://github.com/chunky-milk/pi-bashscripts-files/raw/main/conky-manager/realpath_8.25-2ubuntu3_16.04_all.deb
wget https://github.com/chunky-milk/pi-bashscripts-files/raw/main/conky-manager/conky-manager_2.4_136_ubuntu16.04.1_armhf.deb
sudo dpkg -i realpath_8.25-2ubuntu3_16.04_all.deb && sudo dpkg -i conky-manager_2.4_136_ubuntu16.04.1_armhf.deb
rm conky-manager_2.4_136_ubuntu16.04.1_armhf.deb && rm realpath_8.25-2ubuntu3_16.04_all.deb
```

**Comment by techcoder20** [comment]
@Botspot what do you think ? Should conky manager be a separate app ?

**Comment by Botspot** [comment]
> @Botspot what do you think ? Should conky manager be a separate app ?

No, I think it would be better included with the existing Conky app.

@techcoder20 @chunky-milk Could the Conky Manager app get a proper icon in the Start Menu?  
Right now it's just the generic "application" icon. (On my system at least)

**Comment by chunky-milk** [comment]
i'm getting an icon. but then again, i'm using ```papirus-icon-theme```

**Comment by chunky-milk** [comment]
@Botspot ^

**Comment by techcoder20** [comment]
> i'm getting an icon. but then again, i'm using `papirus-icon-theme`

Same here but we could download the icon if required

**Comment by Itai-Nelken** [comment]
any updates?

**Comment by techcoder20** [comment]
The app works and we can add the icon, We need @Botspot 's opinion...

**Comment by theofficialgman** [comment]
closing as unactionable. https://github.com/Botspot/pi-apps/issues/266#issuecomment-769214349 asked for the application to be added to the existing Conky app. Please open a PR for that if interested in continuing this.
