### ISSUE TITLE
installation not possible on Pi3b / Stretch

### ISSUE THREAD

**Issue by dsyleixa** [Botspot/pi-apps#2665]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi-Apps and the issue is still not fixed. [How to update Pi-Apps?](https://pi-apps.io/wiki/getting-started/updating-pi-apps/)
- [X] IMPORTANT: I promise to respond to comments on this issue and write a good bug report https://www.softwaretestinghelp.com/how-to-write-good-bug-report/

### What happened?

installation not possible

### Description

can't install pi-apps on my pi3B with Stretch

E: The repository 'http://raspbian.raspberrypi.org/raspbian stretch Release' does no longer have a Release file.

how to fix that?

[code]
```
wget -qO- https://raw.githubusercontent.com/Botspot/pi-apps/master/install | bash
Holen:1 http://deb.nodesource.com/node_9.x stretch InRelease [4.623 B]
Ign:2 http://raspbian.raspberrypi.org/raspbian stretch InRelease               
Fehl:3 http://raspbian.raspberrypi.org/raspbian stretch Release                
  404  Not Found [IP: 2a00:1098:0:80:1000:75:0:3 80]
OK:4 http://archive.raspberrypi.org/debian stretch InRelease
Paketlisten werden gelesen... Fertig
E: The repository 'http://raspbian.raspberrypi.org/raspbian stretch Release' does no longer have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
The command 'sudo apt update' failed. Before Pi-Apps will work, you must fix you
```
[/code]

### What are your system specs (run the following command in your terminal)?

```bash
OS: Stretch
Pi3B
```

### (Recommended) Error log? Terminal output? Debug messages?

```bash
wget -qO- https://raw.githubusercontent.com/Botspot/pi-apps/master/install | bash
Holen:1 http://deb.nodesource.com/node_9.x stretch InRelease [4.623 B]
Ign:2 http://raspbian.raspberrypi.org/raspbian stretch InRelease               
Fehl:3 http://raspbian.raspberrypi.org/raspbian stretch Release                
  404  Not Found [IP: 2a00:1098:0:80:1000:75:0:3 80]
OK:4 http://archive.raspberrypi.org/debian stretch InRelease
Paketlisten werden gelesen... Fertig
E: The repository 'http://raspbian.raspberrypi.org/raspbian stretch Release' does no longer have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
The command 'sudo apt update' failed. Before Pi-Apps will work, you must fix you
```
```

**Comment by theofficialgman** [comment]
stretch has been removed from raspbian repos (http://raspbian.raspberrypi.org/raspbian/dists/stretch/). there is no fix and you must install a newer version of the operating system (bookworm) https://www.raspberrypi.com/software/

**Comment by dsyleixa** [comment]
a pity, I have to stay with my Stretch because of too many apps and settings have been installed and configured which once took almost a half lifetime.
Migration and new installation of all and everything not possible.

**Comment by theofficialgman** [comment]
Sorry but its not an issue that we or anyone else can fix. Your operating system receives no updates for 4 years and has had its remote repositories DELETED. New installation of software is not possible. You will need to install a new distro in order to install anything of value.
