### ISSUE TITLE
Box64 Installation Fails with Timeout Error

### ISSUE THREAD

**Issue by anodyne99** [Botspot/pi-apps#2667]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi-Apps and the issue is still not fixed. [How to update Pi-Apps?](https://pi-apps.io/wiki/getting-started/updating-pi-apps/)
- [X] IMPORTANT: I promise to respond to comments on this issue and write a good bug report https://www.softwaretestinghelp.com/how-to-write-good-bug-report/

### What happened?

Any app that tries to install Box64 fails

### Description

When attempting to install Notepad++, the installation hangs up on box64 installation with a connection time out error in the terminal. I'm not sure if it's the git url in the install script and if it is, I have no idea what to change it to. I have also tried installing Box64 through pi-apps by itself with the same results.

### What are your system specs (run the following command in your terminal)?

```bash
OS: Debian GNU/Linux 12 (bookworm)
OS architecture: 64-bit
Last updated Pi-Apps on: 10/22/2024
Latest Pi-Apps version: 10/21/2024
Kernel: aarch64 6.6.31+rpt-rpi-v8
Device model: Raspberry Pi 400 Rev 1.1
SOC identifier: bcm2711
Cpu name: Cortex-A72
Ram size: 3.79 GB
```

### (Recommended) Error log? Terminal output? Debug messages?

```bash
Installing Box64...

add_external_repo: checking 3rd party pubkeyurl validity
Downloading KEY.gpg... 
Spider mode enabled. Check if remote file exists.
--2024-10-22 00:19:46--  https://pi-apps-coders.github.io/box64-debs/KEY.gpg
Resolving pi-apps-coders.github.io (pi-apps-coders.github.io)... 2606:50c0:8000::153, 2606:50c0:8001::153, 2606:50c0:8002::153, ...
Connecting to pi-apps-coders.github.io (pi-apps-coders.github.io)|2606:50c0:8000::153|:443... failed: Connection timed out.
Connecting to pi-apps-coders.github.io (pi-apps-coders.github.io)|2606:50c0:8001::153|:443... 
failed: Connection timed out.
```

**Comment by theofficialgman** [comment]
This is an internet error that could indicate an issue with your local internet connection or a temporary issue at the server (github). If you try again and still have issues then its your local internet connection and we cannot do anything to resolve that.

**Comment by anodyne99** [comment]
Thank you. I double checked my internet settings and it was indeed my router not handling ipv6 addresses properly. After some tweaking with the settings the install worked flawlessly.
