### ISSUE TITLE
EDIT ME Include the app name and if it is a Package app or an Install based App

### ISSUE THREAD

**Issue by chdhidjdjdjdj** [Botspot/pi-apps#2671]
### What is the name of the app?

Sksks

### Where is the app hosted?

WARNING: YOUR SYSTEM IS UNSUPPORTED:
Pi-Apps is not supported on Android. Some apps will work, but others won't.
The ability to send error reports has been disabled.
Waiting 10 seconds... (To cancel, press Ctrl+C or close this terminal)
Installing Better Chromium...

User error: Chromium is not installed! Failed to find either a 'chromium' command or 'chromium-browser' command. If you are sure Chromium is installed, please reach out to Botspot for this to be fixed.

Failed to install Better Chromium!
◢◣Need help? Copy the ENTIRE terminal output or take a screenshot.
Please ask on Github: https://github.com/Botspot/pi-apps/issues/new/choose
Or on Discord: https://discord.gg/RXSTvaUvuu

### About the app

WARNING: YOUR SYSTEM IS UNSUPPORTED:
Pi-Apps is not supported on Android. Some apps will work, but others won't.
The ability to send error reports has been disabled.
Waiting 10 seconds... (To cancel, press Ctrl+C or close this terminal)
Installing Better Chromium...

User error: Chromium is not installed! Failed to find either a 'chromium' command or 'chromium-browser' command. If you are sure Chromium is installed, please reach out to Botspot for this to be fixed.

Failed to install Better Chromium!
◢◣Need help? Copy the ENTIRE terminal output or take a screenshot.
Please ask on Github: https://github.com/Botspot/pi-apps/issues/new/choose
Or on Discord: https://discord.gg/RXSTvaUvuu

### Upload file or Add PR Link

WARNING: YOUR SYSTEM IS UNSUPPORTED:
Pi-Apps is not supported on Android. Some apps will work, but others won't.
The ability to send error reports has been disabled.
Waiting 10 seconds... (To cancel, press Ctrl+C or close this terminal)
Installing Better Chromium...

User error: Chromium is not installed! Failed to find either a 'chromium' command or 'chromium-browser' command. If you are sure Chromium is installed, please reach out to Botspot for this to be fixed.

Failed to install Better Chromium!
◢◣Need help? Copy the ENTIRE terminal output or take a screenshot.
Please ask on Github: https://github.com/Botspot/pi-apps/issues/new/choose
Or on Discord: https://discord.gg/RXSTvaUvuu

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi-Apps app list.
- [X] I have read and followed the [creating an app for Pi-Apps documentation](https://pi-apps.io/wiki/development/Creating-an-app/).
- [X] I have confirmed that this app can run on all [Pi-Apps supported systems](https://pi-apps.io/install/).

**Comment by chdhidjdjdjdj** [comment]
WARNING: YOUR SYSTEM IS UNSUPPORTED:
Pi-Apps is not supported on Android. Some apps will work, but others won't.
The ability to send error reports has been disabled.
Waiting 10 seconds... (To cancel, press Ctrl+C or close this terminal)
Installing Better Chromium...

User error: Chromium is not installed! Failed to find either a 'chromium' command or 'chromium-browser' command. If you are sure Chromium is installed, please reach out to Botspot for this to be fixed.

Failed to install Better Chromium!
◢◣Need help? Copy the ENTIRE terminal output or take a screenshot.
Please ask on Github: https://github.com/Botspot/pi-apps/issues/new/choose
Or on Discord: https://discord.gg/RXSTvaUvuu

**Comment by Botspot** [comment]
Hello, It is strange to me why you used the "app submission" issue type instead of the "bug report" format.
I need a lot more information from you to properly work on this, and instead of asking for it, I am going to give you the opportunity to provide it yourself.

Please use THIS link to open an issue. https://github.com/Botspot/pi-apps/issues/new?assignees=&labels=bug&projects=&template=bug-report.yml
And please give the information it asks for. It's important.
