### ISSUE TITLE
Steam fails to launch after it auto-updated today

### ISSUE THREAD

**Issue by geerlingguy** [Botspot/pi-apps#2676]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi-Apps and the issue is still not fixed. [How to update Pi-Apps?](https://pi-apps.io/wiki/getting-started/updating-pi-apps/)
- [X] IMPORTANT: I promise to respond to comments on this issue and write a good bug report https://www.softwaretestinghelp.com/how-to-write-good-bug-report/

### What happened?

Steam auto-updated this morning and now it won't launch.

### Description

I see a dialog "Fatal Error: Failed to load steamui.so".

When I launch steam with Terminal `/usr/local/bin/steam` I get the following errors:

```
Error initializing native libbz2.so.1 (last dlerror is libbz2.so.1: wrong ELF class: ELFCLASS64)
Using emulated /home/pi/.local/share/Steam/ubuntu12_32/steam-runtime/lib/i386-linux-gnu/libbz2.so.1.0
Warning: Weak Symbol _ZGTtnaj not found, cannot apply R_386_JMP_SLOT 0x695bc7f0 (0x3b1e6)
Error loading one of needed lib
Error initializing needed lib steamui.so
Warning: Cannot dlopen("steamui.so"/0x65ab7cd8, 2)
dlmopen steamui.so failed: Cannot dlopen("steamui.so"/0x65ab7cd8, 2)

Failed to load steamui.so - dlerror(): (null)
[2024-11-11 10:09:12] Shutdown
```

### What are your system specs (run the following command in your terminal)?

```bash
OS: Debian GNU/Linux 12 (bookworm)
OS architecture: 64-bit
Last updated Pi-Apps on: 11/11/2024
Latest Pi-Apps version: 11/11/2024
Kernel: aarch64 6.6.58-v8-16k+
Device model: Raspberry Pi 5 Model B Rev 1.0
SOC identifier: bcm2712
Machine-id (hashed): b718e451fc7689e94966bc4c92e49936c49d6aec
Serial-number (hashed): 2fed9f8845dfbcc357edfec13515d5388acccee3
Cpu name: Cortex-A76
Ram size: 7.94 GB
Raspberry Pi OS image version: 2024-07-04
Language: en_US.UTF-8
```

**Comment by geerlingguy** [comment]
Note: The kernel says 16k+, but it's actually 4KB page size:

```
$ getconf PAGESIZE
4096
```

**Comment by geerlingguy** [comment]
Wanted to open this issue to track my own debugging...

After restarting and re-launching Steam on the CLI, I'm seeing:

```
Apply RC params for steam-runtime-launcher-service
Applying BOX64_NOGTK=1
Applying BOX64_EXIT=1
Steam Runtime Launch Service: steam-runtime-launcher-service pid 2824 exited
Steam Runtime Launch Service: steam-runtime-launcher-service keeps crashing on startup, disabling
Using emulated /home/pi/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu/gtk-2.0/2.10.0/engines/libpixmap.so
Error loading needed lib libunity.so.9
Warning: Cannot dlopen("libunity.so.9"/0x64ad1bbf, 1)
Using native(wrapped) libXss.so.1
Using emulated /home/pi/.local/share/Steam/ubuntu12_32/friendsui.so
Warning: Weak Symbol _ZGTtnaj not found, cannot apply R_386_JMP_SLOT 0x6d676b38 (0x77ee6)
Using native(wrapped) libXss.so.1
Desktop state changed: desktop: { pos:    0,   0 size: 3840,2160 } primary: { pos:    0,   0 size: 3840,2160 }
Caching cursor image for , size 21x32, serial 2, cache size = 0
[2024-11-11 10:44:51] Background update loop checking for update. . .
[2024-11-11 10:44:51] Checking for available updates...
[2024-11-11 10:44:51] Downloading manifest: https://client-update.fastly.steamstatic.com/steam_client_ubuntu12
[2024-11-11 10:44:51] Manifest download: send request
[2024-11-11 10:44:51] Manifest download: waiting for download to finish
[2024-11-11 10:44:52] Manifest download: finished
[2024-11-11 10:44:52] Download skipped by HTTP 304 Not Modified
[2024-11-11 10:44:52] Nothing to do
```

Then it seems to hang with Steam hitting one core 100% for many minutes (15 so far).

**Comment by Botspot** [comment]
I can reproduce this on the 4k kernel. I have not yet tried rebooting.
For steam launch regressions, we usually ask that users open an issue on the box64 repo. You would get better help there from @ptitseb.

**Comment by ptitSeb** [comment]
I have updated box86 and box64 last week for steam. There is already a ticket about that on box86 repo: https://github.com/ptitSeb/box86/issues/1012

**Comment by Botspot** [comment]
Steam now launches successfully on my system after an apt upgrade and reboot. In the upgrade I saw both box86 and box64 get updated from [our repos](https://github.com/Pi-Apps-Coders/box64-debs) with daily builds.

@geerlingguy make sure you are getting our latest Box86/64 build from out apt repo. For example my installed box64-generic-arm package now shows this version: `0.3.1+20241111T062542.cf5b94d-1`

**Comment by geerlingguy** [comment]
Just ran a full-upgrade and will reinstall box64/86 and Steam and try again!

**Comment by geerlingguy** [comment]
@Botspot weird, I still can't get steam to launch.

```
pi@pi5-pcie:~ $ sudo apt list box64-generic-arm
Listing... Done
box64-generic-arm/unknown,now 0.3.1+20241111T062542.cf5b94d-1 arm64 [installed,automatic]
N: There are 3 additional versions. Please use the '-a' switch to see them.
```

And steam is failing on libcurl.so now:

```
Rename process to "steamerrorreporter"
Using native(wrapped) libdl.so.2
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) librt.so.1
Using native(wrapped) libbsd.so.0
/share/Steam/linux32/steamerrorreporter[9747]: Uploading dump (out-of-process)
/tmp/dumps/assert_20241111134347_3.dmp
Error loading needed lib libcurl.so
Warning: Cannot dlopen("libcurl.so"/0x30017013, 2)
```

(This is after a fresh install and reboot)

**Comment by Botspot** [comment]
Try switching to the 4k kernel if you have not tried that already.

**Comment by geerlingguy** [comment]
I've only been testing on the 4K kernel—the kernel is reporting as 16k in `uname` but only because I haven't changed the name on my custom kernel. Page size is `4096`.

**Comment by geerlingguy** [comment]
`amdgpu_top` took a while to compile, but now I see a lot more details than either `radeontop` or `nvtop` give. I like it!

<img width="1280" alt="Screenshot 2024-11-11 at 2 34 35 PM" src="https://github.com/user-attachments/assets/1f076c89-0aaf-4f1c-9333-38a1dbaab3e0">

And it's fun watching the Pi 5 struggle mightily to even get 1 fps recording with x264 in OBS. GPU seems to handle it a tiny bit better but I think there are some massive CPU bottlenecks there.

If I scale down to 720p in OBS, I can record smooth as butter using x264. No artifacts whatsoever:

https://github.com/user-attachments/assets/5947808b-3fcc-4c16-807e-67392ee0ec70

This was with the screen at 4K, with PipeWire capture, and scaled to 720p in the 'Video' settings. @Coreforge if you try OBS, are you still seeing artifacts when encoding?

I also had to triple-check the GPU was being used... in OBS I see 60%+ GFX usage by OBS when using VAAPI, whereas if I have x264, it is between 10-15%.

![Untitled-1](https://github.com/user-attachments/assets/ed5ab64c-e4f1-41ae-960d-97ba052e5a4e)

I thought 'Media' would indicate the encoder activity, and maybe it does... It was at 2% when doing my 4K stress test, and 0% when I switched to CPU.

**Comment by Botspot** [comment]
@geerlingguy pretty sure you posted that in the wrong issue...

**Comment by geerlingguy** [comment]
@Botspot oops! Will remove here lol.

**Comment by geerlingguy** [comment]
I've re-installed everything (short of Pi-Apps itself) 3 times and still just getting that `Warning: Cannot dlopen("libcurl.so"/0x30017013, 2)` warning before a crash:

```
Using native(wrapped) libcurl.so.4
/share/Steam/linux32/steamerrorreporter[9313]: Finished uploading minidump (out-of-process): success = yes
/share/Steam/linux32/steamerrorreporter[9313]: response: CrashID=bp-4f861eaf-e023-402a-8fca-b264e2241111
/share/Steam/linux32/steamerrorreporter[9313]: file ''/tmp/dumps/assert_20241111153046_3.dmp'', upload yes: ''CrashID=bp-4f861eaf-e023-402a-8fca-b264e2241111''
```

**Comment by geerlingguy** [comment]
I'll try to reproduce on a fresh Pi OS install later. Maybe something else is broken here.

**Comment by geerlingguy** [comment]
Moving over to https://github.com/ptitSeb/box64/issues/2021 — I think I can close this issue as it's not related to the Pi-Apps install.

**Comment by Botspot** [comment]
Fixed in https://github.com/Botspot/pi-apps/commit/391b49105727a13ed2b8b1ee4b693b10f30ac941
