### ISSUE TITLE
pi apps no pubkeys wont install apps.

### ISSUE THREAD

**Issue by gregoryaul** [Botspot/pi-apps#2678]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi-Apps and the issue is still not fixed. [How to update Pi-Apps?](https://pi-apps.io/wiki/getting-started/updating-pi-apps/)
- [X] IMPORTANT: I promise to respond to comments on this issue and write a good bug report https://www.softwaretestinghelp.com/how-to-write-good-bug-report/

### What happened?

pi apps wont install and pi app store wont update

### Description

wont install any apps not sure how to fix it myself.
for now i uninstalled pi apps.

### What are your system specs (run the following command in your terminal)?

```bash
OS: Debian GNU/Linux 11 (bullseye)
OS architecture: 64-bit
Last updated Pi-Apps on: 11/13/2024
Latest Pi-Apps version: 11/13/2024
Kernel: aarch64 6.1.21-v8+
Device model: Raspberry Pi 4 Model B Rev 1.4
SOC identifier: bcm2711
Machine-id (hashed): fc2da10210016904609350780ec9f0d3ed2f84a2
Serial-number (hashed): b0cccc61aba44845fc2130b58c615775e487e27d
Cpu name: Cortex-A72
Ram size: 7.81 GB
Raspberry Pi OS image version: 2022-04-04
Language: en_US.UTF-8
```

### (Recommended) Error log? Terminal output? Debug messages?

```bash
i@raspberrypi:~ $ wget -qO- https://raw.githubusercontent.com/Botspot/pi-apps/master/install | bash
Hit:1 http://deb.debian.org/debian bullseye InRelease
Hit:2 http://security.debian.org/debian-security bullseye-security InRelease   
Hit:3 http://deb.debian.org/debian bullseye-updates InRelease                  
Hit:4 http://archive.raspberrypi.org/debian bullseye InRelease                 
Ign:5 http://ppa.launchpad.net/cappelikan/ppa/ubuntu plucky InRelease          
Get:6 https://packages.mozilla.org/apt mozilla InRelease [1,522 B]             
Err:7 http://ppa.launchpad.net/cappelikan/ppa/ubuntu plucky Release            
  404  Not Found [IP: 2620:2d:4000:1::81 80]
Hit:8 https://ppa.launchpadcontent.net/mozillateam/ppa/ubuntu focal InRelease  
Err:6 https://packages.mozilla.org/apt mozilla InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY C0BA5CE6DC6315A3
Reading package lists... Done
E: The repository 'http://ppa.launchpad.net/cappelikan/ppa/ubuntu plucky Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: https://packages.mozilla.org/apt mozilla InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY C0BA5CE6DC6315A3
E: The repository 'https://packages.mozilla.org/apt mozilla InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
The command 'sudo apt update' failed. Before Pi-Apps will work, you must fix your apt package-management system.
pi@raspberrypi:~ $ git clone https://github.com/Botspot/pi-apps && ~/pi-apps/install
fatal: destination path 'pi-apps' already exists and is not an empty directory.
pi@raspberrypi:~ $ ~/pi-apps/uninstall
Removing menu button...
Removing terminal command...
Uninstallation complete. Only /home/pi/pi-apps still remains.
If Pi-apps didn't work for you, PLEASE consider submitting a bug report!
--> https://github.com/Botspot/pi-apps/issues/new
pi@raspberrypi:~ $
```

**Comment by Botspot** [comment]
There are two errors here.
1. `Err:7 http://ppa.launchpad.net/cappelikan/ppa/ubuntu plucky Release`
2. `Err:6 https://packages.mozilla.org/apt mozilla InRelease  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY C0BA5CE6DC6315A3`

Both of these are your own doing. You added these repositories at some time in the past.
Go run `sudo pcmanfm`, and look around in this folder: /etc/apt/sources.list.d
Open the files in there until you find the one for https://packages.mozilla.org/apt and delete it. Also find the file pertaining to http://ppa.launchpad.net/cappelikan/ppa/ubuntu and delete that too.

Then Pi-Apps should work.
Note: deleting all of the files will break updates for your operating system, so use caution.

**Comment by theofficialgman** [comment]
I will also note in the majority of cases ubuntu ppa's should not be added to a debian install (there are edge cases where it is safe to do so when done properly like for mozilla firefox's ppa but these are edge cases and not the norm).

**Comment by theofficialgman** [comment]
Stale issues are closed after no response. Please comment if our help was not enough to help you resolve your issue.

**Comment by armand03000** [comment]
L'erreur qui s'affiche sur mon raspberry pi 4 sur ubuntu 24.10 est : error of GPG  https://proget.makedeb.org prebuilt-mpr Release : Les signatures suivantes n'ont pas pu être vérifiées car la clé publique n'est pas disponible : NO_PUBKEY 4FE9F2C43D9428A0 . Pls help !!!!! tor not run in forge version,spotify not run!!! S.O.S!!!!!
![Capture d’écran du 2025-01-01 20-05-51](https://github.com/user-attachments/assets/249e1b32-cea3-4619-9875-256d9671d134)
