### ISSUE TITLE
VSCodium

### ISSUE THREAD

**Issue by chunky-milk** [Botspot/pi-apps#268]
these are open source builds of VSCode without the telemetry and tracking
[vscodium.zip](https://github.com/Botspot/pi-apps/files/5856197/vscodium.zip)

@Botspot

**Comment by Botspot** [comment]
Okay I've tested it and fixed the icon.

One question: Would it be possible to install both VSCode and VSCodium at the same time?  
By looking at the Menu button, how can I know if that's launching VSCode or VSCodium?

**Comment by Itai-Nelken** [comment]
@Botspot
> One question: Would it be possible to install both VSCode and VSCodium at the same time?

I can confirm that's possible, I have both VS code and VSCodium installed on my pi.
> By looking at the Menu button, how can I know if that's launching VSCode or VSCodium?

they have a different icon and name, so you won't get confused.

**Comment by chunky-milk** [comment]
@Botspot yes, you can install both, it does not interfere with other packages.

**Comment by Botspot** [comment]
Oh. Looks like it didn't actually install anything.

@chunky-milk which of the below lines actually installs something?
```
wget -qO - https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg | gpg --dearmor | sudo dd of=/etc/apt/trusted.gpg.d/vscodium.gpg 
echo 'deb https://paulcarroty.gitlab.io/vscodium-deb-rpm-repo/debs/ vscodium main' | sudo tee --append /etc/apt/sources.list.d/vscodium.list 
sudo apt-get update
```

**Comment by Itai-Nelken** [comment]
> Oh. Looks like it didn't actually install anything.
> 
> @chunky-milk which of the below lines actually installs something?
> 
> ```
> wget -qO - https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg | gpg --dearmor | sudo dd of=/etc/apt/trusted.gpg.d/vscodium.gpg 
> echo 'deb https://paulcarroty.gitlab.io/vscodium-deb-rpm-repo/debs/ vscodium main' | sudo tee --append /etc/apt/sources.list.d/vscodium.list 
> sudo apt-get update
> ```

`sudo apt install vscodium` has to be run after `sudo apt update`

**Comment by chunky-milk** [comment]
> Oh. Looks like it didn't actually install anything.
> 
> 
> 
> @chunky-milk which of the below lines actually installs something?
> 
> ```
> 
> wget -qO - https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg | gpg --dearmor | sudo dd of=/etc/apt/trusted.gpg.d/vscodium.gpg 
> 
> echo 'deb https://paulcarroty.gitlab.io/vscodium-deb-rpm-repo/debs/ vscodium main' | sudo tee --append /etc/apt/sources.list.d/vscodium.list 
> 
> sudo apt-get update
> 
> ```

whoops, forgot to include sudo apt install codium.

**Comment by chunky-milk** [comment]
@Botspot here's the updated .zip
[VSCodium.zip](https://github.com/Botspot/pi-apps/files/5887295/VSCodium.zip)

**Comment by Botspot** [comment]
Added to Pi-Apps with commit 127858695e9366a75a0e0cce401b219b513e9281.

**Comment by Botspot** [comment]
@chunky-milk It looks like you used the wrong icon.

I'm going to update it to this:  
![vscodium](https://user-images.githubusercontent.com/54716352/106187367-29772080-616b-11eb-879b-4954476b323e.png)

**Comment by chunky-milk** [comment]
> @chunky-milk It looks like you used the wrong icon.
> 
> I'm going to update it to this:
> ![vscodium](https://user-images.githubusercontent.com/54716352/106187367-29772080-616b-11eb-879b-4954476b323e.png)

oh no! ok that sounds good.

**Comment by Botspot** [comment]
@chunky-milk, any ideas? The package seems to have vanished from the repository. We've received an error log and I've been able to reproduce it.

## Procedure:
```
wget -qO - https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg | gpg --dearmor | sudo dd of=/etc/apt/trusted.gpg.d/vscodium.gpg
sudo bash -c "echo 'deb https://paulcarroty.gitlab.io/vscodium-deb-rpm-repo/debs/ vscodium main' > /etc/apt/sources.list.d/vscodium.list"
sudo apt update
sudo apt install -y codium
```
## Expected result:
Codium package installs.

## Actual result:
```
E: Unable to locate package codium
```

**Comment by chunky-milk** [comment]
I'm also having the same issue. Maybe have the install scripts download the latest deb from here and install it? https://github.com/VSCodium/vscodium/releases/tag/1.60.1

**Comment by Botspot** [comment]
> I'm also having the same issue. Maybe have the install scripts download the latest deb from here and install it? https://github.com/VSCodium/vscodium/releases/tag/1.60.1

Looks good except that your program icon is the old version. It should be that green "swoosh".
