### ISSUE TITLE
zenstudio

### ISSUE THREAD

**Issue by abu-hanyball** [Botspot/pi-apps#2694]
### What is the name of the app?

zenstudio

### Where is the app hosted?

www;cronus.com

### About the app

connecter  toute les manette et clavier ,souri sur n import quel support

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have read the app eligibilty rubric https://github.com/Botspot/pi-apps/issues/185 and confirmed this app is suitable for addition in Pi-Apps.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi-Apps app list.
- [X] I have confirmed that this app can run on all [Pi-Apps supported systems](https://pi-apps.io/install/).

**Comment by Botspot** [comment]
Closing until you can:

1. Actually link to a valid website.
2. Prove the app runs on Raspberry Pi
3. Write in English
