### ISSUE TITLE
Unmet Dependensies

### ISSUE THREAD

**Issue by Adam6545** [Botspot/pi-apps#2696]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi-Apps and the issue is still not fixed. [How to update Pi-Apps?](https://pi-apps.io/wiki/getting-started/updating-pi-apps/)
- [X] IMPORTANT: I promise to respond to comments on this issue and write a good bug report https://www.softwaretestinghelp.com/how-to-write-good-bug-report/

### What happened?

App wont install

### Description

I put it in the line of code i found in the pi-apps console and was met with a message saying ;" Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
Pi-Apps dependencies failed to install and so the Pi-Apps install has been aborted. Before Pi-Apps can be installed you must solve any errors above."
I am new to my Rasberry Pi so i was not sure what to do. I searched it up online and found nothing relevant. 

### What are your system specs (run the following command in your terminal)?

```bash
OS: Debian GNU/Linux 12 (bookworm)
OS architecture: 64-bit
Last updated Pi-Apps on: 12/18/2024
Latest Pi-Apps version: 12/18/2024
Kernel: I wont be providing this information
Device model: Raspberry Pi 5 Model B Rev 1.0
SOC identifier: I wont be providing this information
Machine-id (hashed): I wont be providing this information
Serial-number (hashed): I wont be providing this information
Cpu name: I wont be providing this information
Ram size: 4.04 GB
Raspberry Pi OS image version: 2024-11-19
Language: en_US.UTF-8
```

### (Recommended) Error log? Terminal output? Debug messages?

```bash
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
Pi-Apps dependencies failed to install and so the Pi-Apps install has been aborted. Before Pi-Apps can be installed you must solve any errors above.
```

**Comment by Botspot** [comment]
As you can see, it says "`Before Pi-Apps can be installed you must solve any errors above.`"
You did not provide those errors above, so I cannot help you. Please provide more information.

**Comment by Adam6545** [comment]
Thank you for your help, the error dissapeared and I'm not sure how it happened but next time i will provide more informtation
