### ISSUE TITLE
How can I install an app from Pi Apps onto an external hard drive (HDD)

### ISSUE THREAD

**Issue by cooldev68** [Botspot/pi-apps#2698]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [ ] I tried updating Pi-Apps and the issue is still not fixed. [How to update Pi-Apps?](https://pi-apps.io/wiki/getting-started/updating-pi-apps/)
- [X] IMPORTANT: I promise to respond to comments on this issue and write a good bug report https://www.softwaretestinghelp.com/how-to-write-good-bug-report/

### What happened?

Trying to install apps onto an external hard drive (HDD)

### Description

**I have ran out of space so I connected an external hard drive but I do not know how to change the installation directory of apps so that any new Pi Apps may be installed on the HDD. Any suggestions?**

_**Note: The output below is what I receive on my microSD, I am trying to find a way to install it onto my external hard drive**_

### What are your system specs (run the following command in your terminal)?

```bash
OS: Debian GNU/Linux 12 (bookworm)
OS architecture: 64-bit
Last updated Pi-Apps on: 12/22/2024
Latest Pi-Apps version: 12/22/2024
Kernel: aarch64 6.6.62+rpt-rpi-v8
Device model: Raspberry Pi 400 Rev 1.0
SOC identifier: bcm2711
Machine-id (hashed): fbee12f52a2a847d65ab4e0b4d3ca37bc61e880d
Serial-number (hashed): 9e00925304ea069408620ffaf3970e32ed19a55c
Cpu name: Cortex-A72
Ram size: 3.79 GB
Raspberry Pi OS image version: 2023-10-10
Language: en_US.UTF-8
```

### (Recommended) Error log? Terminal output? Debug messages?

```bash
◣ WARNING: YOUR SYSTEM IS UNSUPPORTED:
Your system drive has less than 500MB of free space. Watch out for "disk full" errors.
The ability to send error reports has been disabled.
Waiting 10 seconds... (To cancel, press Ctrl+C or close this terminal)
```

**Comment by Botspot** [comment]
Most apps do not use that much space. Also, they all will install differently. Pi-Apps does not have a unified packaging format, or singular installation directory that could be changed ton an external drive.

My recommendation is to move large personal files (such as pictures or videos) to the HDD, leaving software installation on the sd card. Alternatively, check online for ways to move your $HOME folder to an external drive. This is a fairly standard operation.

**Comment by cooldev68** [comment]
Would it be safe then to install the raspberry os onto the HDD in order for
the apps to be installed straight there? If not, then is it possible to
move the apps once they are installed onto the HDD?

**Comment by Botspot** [comment]
> Would it be safe then to install the raspberry os onto the HDD in order for the apps to be installed straight there?

You can do this. I have. It was very slow.

> If not, then is it possible to move the apps once they are installed onto the HDD?

That's not how apps work. You can move files. You could look at the install scripts for the apps you are interested in, to try to get some of an idea for what files they install, but again, most apps don't take up much space.

I would suggest using the Disk Usage Analyzer on Pi-Apps to see what is using the most of your storage.

**Comment by cooldev68** [comment]
Alright I will try that, thanks for your time. Merry Christmas!
