### ISSUE TITLE
simplescreenrecorder

### ISSUE THREAD

**Issue by Itai-Nelken** [Botspot/pi-apps#27]
[SimpleScreenRecorder.zip](https://github.com/Botspot/pi-apps/files/5403495/SimpleScreenRecorder.zip)

**Comment by Botspot** [comment]
I'm sorry, but I will not be able to add this app. :(  
Pi-Apps is exclusively for programs that cannot be installed with `sudo apt install`.

As your App does exactly that, it cannot be added to Pi-Apps.

**Comment by Itai-Nelken** [comment]
Ok

**Comment by Botspot** [comment]
In the future, I may decide to add a separate category to Pi-Apps, suited for this type of repository app.
