### ISSUE TITLE
Snap shows twice on menu

### ISSUE THREAD

**Issue by Chulamin** [Botspot/pi-apps#272]
Hi. I tried a couple of times to add and delete Snap with Pi-Apps but it always creates two menu items under system using Twister OS.

**Comment by Botspot** [comment]
I had to make a workaround for Raspberry Pi OS, for the menu buttons to show up at all.

That workaround wasn't needed on TwisterOS, as Snap works out-of-the box there apparently.  
Thanks for letting me know!

**Comment by techcoder20** [comment]
@Botspot I proposed a fix here https://github.com/Botspot/pi-apps/pull/273

**Comment by Botspot** [comment]
@Chulamin Could you send a screenshot of your menu that contains two Snap Store menu icons?

I haven't been able to repeat what you're reporting.

**Comment by Chulamin** [comment]
________________________________

**Comment by Botspot** [comment]
> ________________________________ From: Botspot <notifications@github.com> Sent: Wednesday, January 27, 2021 9:09:16 PM To: Botspot/pi-apps <pi-apps@noreply.github.com> Cc: Chulamin <chulamin@hotmail.com>; Mention <mention@noreply.github.com> Subject: Re: [Botspot/pi-apps] Snap shows twice on menu (#272) @Chulamin<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FChulamin&data=04%7C01%7C%7C8422ec28ecac4840dcfa08d8c3427aef%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637474037580613093%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=c1NSuO6b6N7CM70i4HOS%2FPwJWjgxToMoXtQc7EtwLqo%3D&reserved=0> Could you send a screenshot of your menu that contains two Snap Store menu icons? I haven't been able to repeat what you're reporting. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FBotspot%2Fpi-apps%2Fissues%2F272%23issuecomment-768785983&data=04%7C01%7C%7C8422ec28ecac4840dcfa08d8c3427aef%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637474037580623093%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=fb%2FkQGfcTnxIadOmKub08%2F3OZ53F8PuA5569Mj6BFUE%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FARHWP6IVT36GSOIZN6ZLPI3S4DPOZANCNFSM4WQ3EM3A&data=04%7C01%7C%7C8422ec28ecac4840dcfa08d8c3427aef%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637474037580633089%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=PYvxnTVnwRrrXCjSnJmv%2FfXRT5%2F2jaNHdBTUUli6Gf0%3D&reserved=0>. [Image] There it is.

@Chulamin You can't attach images to an email like that. I don't see anything. Please attach an image on the github issue.

**Comment by Chulamin** [comment]
![20210127_212533.jpg](https://user-images.githubusercontent.com/72312825/106091531-e0cb5300-60e9-11eb-8f47-8678d512f8fc.jpg)

**Comment by Chulamin** [comment]
I just performed a complete reinstall of Pi-Apps and then Snap and there is only one menu item now. I Don't know if you made a change or if there was some other issue but it is fine now. Thanks.

**Comment by Botspot** [comment]
Strange.

I wonder if **rebooting** would cause the second menu entry to show up again.

**Comment by Chulamin** [comment]
You were right...second entry is back. It's not a big deal but I guess it should be happening.

**Comment by Botspot** [comment]
Okay I've been able to repeat this.  
![2021-01-28-181215_1920x1080_scrot](https://user-images.githubusercontent.com/54716352/106214451-6a375f80-6194-11eb-94ab-20ab631d121c.png)

**Comment by Itai-Nelken** [comment]
is this still an issue?

**Comment by Chulamin** [comment]
Everything looks good now. Thanks for the follow up.

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by Itai-Nelken** [comment]
Good!
