### ISSUE TITLE
[App submission] Spaceflight Simulator

### ISSUE THREAD

**Issue by mobilegmYT** [Botspot/pi-apps#274]
Here's the download for anyone wanting to test. Run it with box86 and wine: https://mega.nz/#!IqgSDa7J!zIx_u_xmE-qlw7_YY8UMzjSOlM7vOOmXArIO4PSSc00

From my testing, you can build rockets but it froze pressing the launch button

**Comment by Itai-Nelken** [comment]
I have the same results as @mobilegmYT.
this is what happens when clicking on launch:
![image](https://i.imgur.com/7viuJMD.png)
I inluded the crash log in the zip bellow
[SFS-crash.zip](https://github.com/Botspot/pi-apps/files/5868795/SFS-crash.zip)

**Comment by CoderLogy** [comment]
With twister os I think this could work by downloading in Google play store or run as apk
As linux  have less support or not work for unity
But there could be thing if u download latest version from seeing photo I see that u are working on outdated update or version of game try new version

**Comment by CoderLogy** [comment]
And botspot pls join CodersHub pls

**Comment by mobilegmYT** [comment]
> With twister os I think this could work by downloading in Google play store or run as apk
> As linux have less support or not work for unity
> But there could be thing if u download latest version from seeing photo I see that u are working on outdated update or version of game try new version

APK's don't run a TwisterOS.

**Comment by CoderLogy** [comment]
Ok then u can use android os on rpi work on android lollipop

**Comment by CoderLogy** [comment]
But I have read somewhere twister os can work with apk

**Comment by techcoder20** [comment]
> But I have read somewhere twister os can work with apk

Some people have been trying to get anbox running

**Comment by CoderLogy** [comment]
Ok but u got my point space flight simulator u  use is outdated version and
linux have less suport for unity on arm ok good that is why do it on
android os on raspberry Pi

**Comment by techcoder20** [comment]
@CoderLogy your correct that the game will run properly on Lineage os or omni rom but we want it added to pi apps so they are figuring out how to run it on RPi os

**Comment by CoderLogy** [comment]
Ok but I have better idea use a apk player called emulator on rpi the app
will work or better not use windows version of game and turn it with box 86
and wine I hope it will work

**Comment by Itai-Nelken** [comment]
>or better not use windows version of game and turn it with box 86 and wine I hope it will work

box86+wine is what's being used right now, but the game crashes when trying to launch a rocket.

**Comment by Botspot** [comment]
> And botspot pls join CodersHub pls

What is that and why do you think I should join it?

**Comment by Botspot** [comment]
> Ok but I have better idea use a apk player called emulator on rpi the app will work

That would be a game changer! However, I'm not aware of an emulator that would work suitably fast.

**Comment by CoderLogy** [comment]
Ok

> > And botspot pls join CodersHub pls
> 
> What is that and why do you think I should join it?

U should join it because it's a hub for coder and new generation of coders who are good enough to make apps and website or even use bash script to create anything everytype of programming language here supported even
Mobilegmyt one of your countributor joined it u should too
We can also make a emulator for apk and much more but we need u botspot and not only contribute to open-source but. Private source too 
Pls join it I am redefining coders hub pls share this message to other countributor ofnpiaaps or people u know

**Comment by CoderLogy** [comment]
This could work botspot https://github.com/EKA2L1/EKA2L1
A sysbian emulator it supports arm I think so

**Comment by CoderLogy** [comment]
I have one idea too use lutris it could also work

**Comment by CoderLogy** [comment]
Mitch Carrol space simulator could work add it to piapps too 
https://github.com/MitchCarroll/spacesim
It's like space flight simulator but a clone of it made by him I think it is good I had not tried but could work

**Comment by CoderLogy** [comment]
Pls anyone tell something does this solution work

**Comment by CoderLogy** [comment]
Pls anyone tell something that this solution work

**Comment by mobilegmYT** [comment]
> Mitch Carrol space simulator could work add it to piapps too
> https://github.com/MitchCarroll/spacesim
> It's like space flight simulator but a clone of it made by him I think it is good I had not tried but could work

This issue is for Spaceflight Simulator, though you can make a new issue for that if you'd like it to be added.

**Comment by Botspot** [comment]
This issue will be re-opened if someone actually gets Spaceflight Simulator **working** well on RPi.
