### ISSUE TITLE
Microphone not working on Pi400 using Zoom

### ISSUE THREAD

**Issue by mjtorre** [Botspot/pi-apps#275]
Hello,

I am using an Pi400, TwisterOS 1.9.7, a usb camera with integrated microphone. I can see and hear the Zoom session perfectly :-).
When I try to use the microphone all looks good, but others cannot hear me.
Any advice?

**Comment by Itai-Nelken** [comment]
this is a known issue, and doesn't have anything to do with pi-apps.
issue on box86 repo: https://github.com/ptitSeb/box86/issues/193

**Comment by mjtorre** [comment]
Thanks for the information.
