### ISSUE TITLE
Puffin doesnot work

### ISSUE THREAD

**Issue by CoderLogy** [Botspot/pi-apps#277]
I tried puffin it doesn't work  pls help me I have installed and updated. When update come to it but now it doesnot work for around 5 days
It doesn't open when clicked but the mouse shows something like puffin is loading and going to open but not worked pls help

**Comment by Botspot** [comment]
This tip will come in handy for a lot of things so pay attention.

- In the start menu, right-click on the Puffin Browser button.
- Select Properties. Click Desktop Entry.
- Look at the **command:** field.
- Copy that command (ctrl+c) and paste it into a terminal (ctrl+shift+v).
- Press Enter to execute the command.

Most likely, the terminal will display everything we need to know to solve the problem.

**Comment by CoderLogy** [comment]
Ok I will do it

**Comment by CoderLogy** [comment]
I found issue it was with something called vc as my system was not sharing library with raspberry Pi because in/opt/vc vc was deleted
