### ISSUE TITLE
RetroPie

### ISSUE THREAD

**Issue by Pythonic456** [Botspot/pi-apps#280]
How do I use retropie?

**Comment by Wizard451345** [comment]
🅱...

**Comment by Botspot** [comment]
> How do I use retropie?

it should work f you type `emulationstation` in the terminal.

**Comment by Pythonic456** [comment]
Thanks! And do you know where I can get ROMs to use with RetroPie?

**Comment by lorecast162** [comment]
Oh no

**Comment by Pythonic456** [comment]
No, not illegally, but I just wondered if there's any games that will run with RetroPie, that are old enough to be free?

**Comment by Jonson26** [comment]
I don't think any video games are old enough these days, as copyright lasts a million years and then some. You might find some that have been released to the Public Domain, but it's unlikely. You might also try to search for homebrew titles, as these are generally freeware (or at least shareware).

**Comment by lorecast162** [comment]
There are some cool homebrew games out there
