### ISSUE TITLE
Pls add any type of game engine

### ISSUE THREAD

**Issue by CoderLogy** [Botspot/pi-apps#282]
Pls add any type of game engine pls for game programmers

**Comment by techcoder20** [comment]
Anything specific that works on RPi ?

**Comment by CoderLogy** [comment]
Yes that works with raspberry Pi not high end like unreal or unity but good
one that could work and produce event graphics one is Godot(most
recommended), löve(most stable),pygame and panda3d(most suitable)etc
There are many game engine pls add any that can do 3d or do 2d no matter
but it's should be good pls do it I would appreciate

**Comment by CoderLogy** [comment]
Pls reply

**Comment by techcoder20** [comment]
@CoderLogy Guess what I got working on RPi
![Screenshot_2021-01-27_05-30-04](https://user-images.githubusercontent.com/68472305/105985220-cc8f4380-6060-11eb-8f00-d8382c6f0ee0.png)

**Comment by Botspot** [comment]
This issue is way too broad, and is not really an app request or a suggestion.

Pi-Apps makes it easier to install **things that already install** on RPi.  
Nobody here is doing the development on new apps from the ground-up.

**Comment by CoderLogy** [comment]
U can use panda3d I didnot for sure said to use only Godot pls hear
