### ISSUE TITLE
Pls add game engine to raspberry Pi it needs it for many coders pls

### ISSUE THREAD

**Issue by CoderLogy** [Botspot/pi-apps#283]

**Comment by CoderLogy** [comment]
löve(most stable),pygame and panda3d(most suitable)etc
There are many game engine pls add any that can do 3d or do 2d no matter
but it's should be good pls do it I would appreciate

**Comment by Botspot** [comment]
This type of issue is outside the scope of Pi-Apps.

https://github.com/Botspot/pi-apps/issues/282#issuecomment-768384629

Please do not open another issue that asks for an indefinite number of apps of a certain type. Each issue needs to be more specific than that and limited to one app.  
Also, for an app request, you should know if it's possible to run the app on RPi first. **Pi-Apps isn't magic.** An app needs to work on the Pi first, then Pi-Apps can simplify the installation process.

**Comment by CoderLogy** [comment]
I say u panda3d  or löve SDK could work belive me pls do it

**Comment by mobilegmYT** [comment]
> I say u panda3d or löve SDK could work belive me pls do it

If you can get it working on your RPI, then you could just send us the commands you used.

**Comment by CoderLogy** [comment]
Ok
