### ISSUE TITLE
Add among us on raspberry Pi

### ISSUE THREAD

**Issue by CoderLogy** [Botspot/pi-apps#289]
Add among us on raspberry Pi even rpi coder aka mobilegmyt your contributor has also did it

**Comment by chunky-milk** [comment]
@CoderLogy the only way to run among us is through Windows on Raspberry Pi

**Comment by Itai-Nelken** [comment]
> @CoderLogy the only way to run among us is through Windows on Raspberry Pi

or Android 10/11 konstakang or FydeOS (chrome OS, has the play store).

**Comment by slashtechno** [comment]
> > @CoderLogy the only way to run among us is through Windows on Raspberry Pi
> 
> or Android 10/11 konstakang or FydeOS (chrome OS, has the play store).

I have never got this working but [ARChon Runtime](https://archon-runtime.github.io/) has support for ARM and can run Android apps.

**Comment by mobilegmYT** [comment]
> Add among us on raspberry Pi even rpi coder aka mobilegmyt your contributor has also did it

I never got among us working? Among Us simply won't work on raspbian, so there is nothing pi-apps can do about it. Please open new app requests only if you know it has arm support, or you've gotten it working yourself.

**Comment by CoderLogy** [comment]
Thank you sorry mobilegmyt if you think I had a wrong and rude allegation on you
