### ISSUE TITLE
Processing Java

### ISSUE THREAD

**Issue by pi-dev500** [Botspot/pi-apps#290]
A simple IDE for learning javascript.
Can you add this app ?
It works perfectly on my PI4.
[Processing javascript.zip](https://github.com/Botspot/pi-apps/files/5886455/Processing.javascript.zip)
I found a special release for processing made for raspberry pi: [here](https://github.com/processing/processing/releases/tag/processing-0268-3.5.2)
screenshot:
![screenshot](https://user-images.githubusercontent.com/77228126/106139138-562c3780-616d-11eb-8e3b-30a38f5148bb.png)

**Comment by chunky-milk** [comment]
@Botspot  i tested it and it works, 
[Processing.zip](https://github.com/Botspot/pi-apps/files/5887841/Processing.zip)

**Comment by CoderLogy** [comment]
Instead of zip you can also use sudo apt install processing or wget install or ever using tar

**Comment by Botspot** [comment]
> Instead of zip you can also use `sudo apt install processing` or wget install or ever using tar

Umm, @CoderLogy, does that work on your system? On my Raspberry Pi OS, I try to install Processing the way you suggested and it didn't work.
```
pi@raspberrypi:~ $ sudo apt install processing
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package processing
```

**Comment by CoderLogy** [comment]
I remember when I installed processing I installed it like this you can
google and check how to do that

**Comment by Botspot** [comment]
> @Botspot i tested it and it works,
> [Processing.zip](https://github.com/Botspot/pi-apps/files/5887841/Processing.zip)

Yes it works flawlessly for me too. However, I'm a bit skeptical as to how many people would use it.

**Comment by pi-dev500** [comment]
This is an app for beiginners in JavaScript , python and and others langages. We can programm an Arduino to send some data to the raspberry pi and receive the data with a simple processing graphical interface.

**Comment by techcoder20** [comment]
> We can programm an Arduino to send some data to the raspberry pi and receive the data with a simple processing graphical interface.
Dont we have the official IDE for that ?

**Comment by CoderLogy** [comment]
We have officiall ide but this thing is much better it supports java which
is good to make good interface for them like there is Eric sudo apt install
Eric ,eric is used for qt5 python gui and so does processing is used to
make interface like tkinter in python,the processing is like tkinter and
eric is interface like nexiton so I also make final thought include
nexiton,eric and processing to pi-apps pls

**Comment by Botspot** [comment]
I've finally decided to add this.

Changes:

- It'll be renamed to `Processing IDE`.
- Its description needs to be expanded please. I don't know enough about Processing IDE to write a good description.
Description suggestions are welcome to be directly posted in this issue, as opposed to a zip.

**Comment by CoderLogy** [comment]
I will add description

**Comment by CoderLogy** [comment]
Description follows here-
Add Processing Ide to your Raspberry Pi  and enjoy making of graphic design and serial commands using this ide with java  and other supported languages that you are known of.
Download it now from pi-apps.
For further more you can download from your terminal:
`curl https://processing.org/download/install-arm.sh | sudo sh`

**Comment by pi-dev500** [comment]
I have finished the zipfile:
[Processing IDE.zip](https://github.com/Botspot/pi-apps/files/6009496/Processing.IDE.zip)

**Comment by pi-dev500** [comment]
@Botspot, it can be added 

- [X] Renamed it into Processing IDE

- [X]  Changed the description

**Comment by Itai-Nelken** [comment]
@pi-dev500 I think `install-64` isn't executable.

**Comment by pi-dev500** [comment]
Ok, I have edited my zipfile

**Comment by Botspot** [comment]
The description needs work.

- This is quite long:  
> Add Processing Ide to your Raspberry Pi and enjoy making of graphic design and serial commands using this ide with java and other supported languages that you are known of.

The first line should be short because this is the text that appears when you hover your mouse over the app in the list.

- This line seems unnecessary and authoratative:  
> Download it now from pi-apps.

- This portion should be removed:  
> ~$ curl https://processing.org/download/install-arm.sh | sudo sh

Nobody wants manual installation commands when there is an install button right there.

**Comment by CoderLogy** [comment]
Ok new description here I added manual download for that you can add it in
its install script:

Processing IDE a new intelligent way of writing graphical code in Raspberry
Pi.

**Comment by Botspot** [comment]
> Processing IDE a new intelligent way of writing graphical code in Raspberry Pi.

Can we lengthen that? Maybe mention *how* it's "new" and "intelligent"?  
Also I'd like to see the "to-run" stuff. `To run: Menu -> ...`, and, `To run in a terminal: command-name`

**Comment by CoderLogy** [comment]
You told me to make it small so I made it now you want long why 😭❔
You can edit to long no problem I will make new description in some time 😃

**Comment by Botspot** [comment]
> You told me to make it small so I made it now you want long why

Simple reason: your first sentence was uncomfortably long. That's all. And the rest of your description was, well, not really what I think users would find to be helpful.

> You can edit to long no problem I will make new description in some time 

I wish I could, but, I don't know enough details about Processing to do a good job writing it.

**Comment by Dell-Glitch** [comment]
> > Instead of zip you can also use `sudo apt install processing` or wget install or ever using tar
> 
> Umm, @CoderLogy, does that work on your system? On my Raspberry Pi OS, I try to install Processing the way you suggested and it didn't work.
> 
> ```
> pi@raspberrypi:~ $ sudo apt install processing
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> E: Unable to locate package processing
> ```

well you got to compile it because it would only apt-get install for x86 not arm

**Comment by CoderLogy** [comment]
Dell apt doesn't work try this would definitely work run this in terminal
below command.

 curl https://processing.org/download/install-arm.sh | sudo sh

**Comment by Dell-Glitch** [comment]
Forgot about curl

**Comment by CoderLogy** [comment]
Why robot curl it good one if you download processing you can goto their
website in my case curl worked only so you should also try

**Comment by CleanMachine1** [comment]
To start this isn't JavaScript, its more like Java but simple

Comparing Java to Javascript is like a Car to Carpet.
Anyway here's my description

Processing is an IDE + Programming Language used for Visual Arts.
It is an Open-Source and Free Software (FOSS) which is built from Java and is used to create graphics.


Don't know what more to add because I really don't know what this is apart from what a video said and the wiki..

**Comment by CleanMachine1** [comment]
@Botspot Enjoy.

**Comment by Botspot** [comment]
> @Botspot Enjoy.

Thank you. It's better than I could have done.

**Comment by CoderLogy** [comment]
We can also add it supports python and other languages too
