### ISSUE TITLE
PiKiss Uninstall

### ISSUE THREAD

**Issue by slashtechno** [Botspot/pi-apps#291]
So I am not sure but doesn't PiKiss use install/uninstall scripts to manage apps? Is it possible to make it so when PiKiss is uninstalled **through Pi-Apps** all PiKiss apps are uninstalled with it? Sorry if I should be making this issue on the PiKiss Repo

**Comment by mobilegmYT** [comment]
Yea, probably ask on the pikiss repo. As said in the readme, when a app is uninstalled, all data it stored must be kept.

**Comment by Botspot** [comment]
I asked the PiKISS dev and he told me that there is no way to do this, and that adding this feature would be very hard to implement.
