### ISSUE TITLE
Firefox

### ISSUE THREAD

**Issue by slashtechno** [Botspot/pi-apps#292]
Firefox can be installed on Raspberry Pi with `sudo apt-get install firefox-esr` 
This is Firefox-ESR but it is basically the same as normal Firefox (I could not find anything different) **but** the user-agent string needs to be overrode since the **default user-agent is a mobile device**. I use an extension but I think it can be **overrode through a config file as well.**

**Comment by mobilegmYT** [comment]
> Firefox can be installed on Raspberry Pi with `sudo apt-get install firefox-esr`
> This is Firefox-ESR but it is basically the same as normal Firefox (I could not find anything different) **but** the user-agent string needs to be overrode since the **default user-agent is a mobile device**. I use an extension but I think it can be **overrode through a config file as well.**

Firebox can be installed with apt, which violates the criteria for pi-apps apps.

**Comment by Botspot** [comment]
While it would be nice if FireFox didn't mention arm32 in its user-agent, I don't think that reason alone is enough to add such an app to Pi-Apps.

As @mobilegmYT said, Pi-Apps specializes in hard-to-install stuff. (so, not available via `apt-get` for example) I don't think FireFox fits the bill well enough.
