### ISSUE TITLE
Need a shell or HTML or even python coder

### ISSUE THREAD

**Issue by CoderLogy** [Botspot/pi-apps#295]
Pls anyone who can do this tel me here I would invite you to my organization thnks

**Comment by mobilegmYT** [comment]
@CoderLogy Please stop making off topic issues, this isn't a place for you to advertise.

**Comment by Botspot** [comment]
No, please don't open an issue that asks for people to volunteer their time to work on your project(s).  
That is not pi-apps related.

An appropriate place to ask it is in the [Pi Labs discord server](https://discord.gg/Fh8sjmu), or in the [Botspot Discord server](https://discord.gg/RXSTvaUvuu). Not here.

**Comment by CoderLogy** [comment]
Thnks sorry my mistake
