### ISSUE TITLE
Wine with box86

### ISSUE THREAD

**Issue by SuperPi911** [Botspot/pi-apps#299]
[Wine.zip](https://github.com/Botspot/pi-apps/files/5893740/Wine.zip)

**Comment by Itai-Nelken** [comment]
there already is a box86+wine issue: #151

**Comment by SuperPi911** [comment]
But on mine the uninstaller is working 100% and I don't have any problem with it

**Comment by Botspot** [comment]
> But on mine the uninstaller is working 100% and I don't have any problem with it

Yeah I'm afraid we already have a WINE issue open. That one works well, and we've even made a few improvements to make WINE run better.  
What we're waiting on now is Raspberry Pi 3 support.

**Comment by SuperPi911** [comment]
But I tested on rpi3 and si working well because I don't have th pi4

**Comment by Botspot** [comment]
> But I tested on rpi3 and si working well because I don't have th pi4

How did you manage that? Is this a custom WINE build for a 2G/2G kernel, or did you make a custom 3G/1G kernel for the Pi3?

**Comment by SuperPi911** [comment]
With a custom kernel

**Comment by Botspot** [comment]
> With a custom kernel

Okay that's what I thought. If I were to try your WINE pi-app on my non-modified Pi3, would it work? (Does your WINE app install the custom kernel necessary?)

**Comment by SuperPi911** [comment]
Yes

**Comment by Botspot** [comment]
> Yes

Really?  
Okay, which line in your `install-32` script is responsible for installing the custom kernel:
```
#!/bin/bash

wget https://dl.winehq.org/wine-builds/debian/dists/buster/main/binary-i386/wine-devel-i386_5.21~buster_i386.deb


wget https://dl.winehq.org/wine-builds/debian/dists/buster/main/binary-i386/wine-devel_5.21~buster_i386.deb


dpkg-deb -xv wine-devel-i386_5.21~buster_i386.deb wine-installer

dpkg-deb -xv wine-devel_5.21~buster_i386.deb wine-installer

sudo mv wine-installer/opt/wine-devel ~/wine
sudo ln -s ~/wine/bin/wine /usr/local/bin/wine
sudo ln -s ~/wine/bin/winecfg /usr/local/bin/winecfg
sudo ln -s ~/wine/bin/wineserver /usr/local/bin/wineserver

sudo rm wine-devel-i386_5.21~buster_i386.deb

sudo rm wine-devel_5.21~buster_i386.deb

sudo rm -r wine-installer
```

**Comment by SuperPi911** [comment]
I think is working without it (on my pi3)

**Comment by Botspot** [comment]
> I think is working without it (on my pi3)

Okay I'll do some testing on your WINE version and our WINE version on my Pi3.

**Comment by SuperPi911** [comment]
Ok

**Comment by Botspot** [comment]
@SuperPi911 When trying to run your version of WINE on my Pi3, it gives me this error:
```
pi@raspberrypi:~ $ wine ~/wine/bin/wineboot
Box86 with Dynarec v0.1.3 7713bd04 built on Oct  8 2020 12:31:54
err:module:check_vmsplit Warning: memory above 0x80000000 doesn't seem to be accessible.
Wine requires a 3G/1G user/kernel memory split to work properly.
Box86 with Dynarec v0.1.3 7713bd04 built on Oct  8 2020 12:31:54
err:virtual:virtual_alloc_first_teb wine: failed to map the shared user data: c0000018
pi@raspberrypi:~ $ 
```
