### ISSUE TITLE
createapp errors

### ISSUE THREAD

**Issue by mobilegmYT** [Botspot/pi-apps#3]
When I run the createapps program, I get this error `/home/pi/pi-apps/binaries/xdotool: error while loading shared libraries: libxdo.so.3: cannot open shared object file: No such file or directory
`

**Comment by Botspot** [comment]
Yeah I'm making so many changes, and so fast, that things like that will happen frequently until initial development is completed.
The latest version doesn't use xdotool, I took it out.

**Comment by Botspot** [comment]
OK I updated the repo. Xdotool has been removed from the script.

**Comment by mobilegmYT** [comment]
Hope it gets fixed soon! Have a lotta things I wanna add lol.

**Comment by Botspot** [comment]
It is fixed.
To update your local version of Pi-Apps, run:

    /home/pi/pi-apps/updater

**Comment by mobilegmYT** [comment]
I know I just updated the code. When I launch the app creator it justs straight to step 6 and doesn't really do anything

**Comment by Botspot** [comment]
Oh oops.
Fixed it now - update again.

**Comment by Botspot** [comment]
Please keep in mind I literally just finished writing `createapp` like 1 minute ago.

**Comment by Botspot** [comment]
I'm going to bed now.

**Comment by mobilegmYT** [comment]
Yea probably should. Also it now says "Unknown step"

**Comment by Botspot** [comment]
OK it should be fixed now.
