### ISSUE TITLE
add app: system-tools

### ISSUE THREAD

**Issue by Itai-Nelken** [Botspot/pi-apps#30]
[system-tools.zip](https://github.com/Botspot/pi-apps/files/5408481/system-tools.zip)

**Comment by mobilegmYT** [comment]
May I ask what the purpose of this is?

**Comment by Botspot** [comment]
Not sure to be honest. Looks really simple though.  
![image 1](https://github.com/Itai-Nelken/system-tools/blob/main/screenshots/system-tools-1.png?raw=true)  
![image 2](https://github.com/Itai-Nelken/system-tools/blob/main/screenshots/system-tools-2.png?raw=true)

**Comment by Itai-Nelken** [comment]
it's more for beginners to the pi and Linux, it just executes apt commands (apt update, apt install etc.) without having to know or remember the exact commands.

**Comment by Itai-Nelken** [comment]
it's the first version, it's sort of still in "beta".
I plan to add more apps and other things.
the whole idea of the app is to be simple

**Comment by Botspot** [comment]
> it's the first version, it's sort of still in "beta".
> I plan to add more apps and other things.
> the whole idea of the app is to be simple

I think it would be best if we wait until your 'system-tools' has more features. It's a really good concept, but I think adding it to Pi-Apps now would be too early, and would be harmful in the long run.

**Comment by Itai-Nelken** [comment]
ok, do you have any ideas of things I could add?

**Comment by Botspot** [comment]
@Itai-Nelken I don't know, just polish it up, maybe post it on the Raspberry Pi forums and you will get plenty of suggestions/improvement ideas.  

One thing in particular that I think could be improved: After installing `gparted`, I had to press Enter 3 times. And then the terminal closed. Do we really need to press Enter 3 times just for the terminal to disappear? That seems a bit silly to me.

**Comment by Itai-Nelken** [comment]
@Botspot I know, I'm removing unnecessary steps and `sleep` and `echo` commands and instead of everything being one long script I'm braking it into smaller scripts.
I included the version I'm working on now if you wan't to look at it (it's just the scripts, and most apps don't have install scripts yet)
anyway thanks for the suggestions.

[system-tools-beta.zip](https://github.com/Botspot/pi-apps/files/5409599/system-tools-beta.zip)

**Comment by Itai-Nelken** [comment]
also do you know how can I make the script return to the first screen after for example installing an app (or changing the password etc.)

**Comment by Botspot** [comment]
> also do you know how can I make the script return to the first screen after for example installing an app (or changing the password etc.)

Easy: a while loop and case statement. Below, I wrote a little program for you:
```
#!/bin/bash
pkg_list="gparted
blender
inkscape
chromium-browser
firefox-esr"

#make another list, this one with line numbers in front of each line
num_list="$(echo "$pkg_list" | awk '{print NR  ") " $s}')"

max_num="$(echo "$pkg_list" | wc -l)"
while true;do
  re='^[0-9]+$'
  while [[ ! $number =~ $re ]];do
    #this loop will not exit until a number is selected
    echo -e "You can install this stuff:
  ${num_list}
  Enter a number [1-${max_num}]"
    read number
  done
  #past this point, a number is selected.

  #take that number and convert it to the package name in the list
  pkg="$(echo "$pkg_list" | sed -n "${number}p")"
  echo "This command would be run: sudo apt install -y $pkg"
done
```

**Comment by Itai-Nelken** [comment]
@Botspot  Thanks

**Comment by Botspot** [comment]
@Itai-Nelken Also, you should change the name of this to something more unique.
System-Tools is very generic, and on my system it's even a menu category.
![snapshot](https://user-images.githubusercontent.com/54716352/97019624-2807dd80-1516-11eb-8c55-bc658e0e7784.png)

**Comment by Botspot** [comment]
Closing this issue for now. @Itai-Nelken Please reply back to this thread when your tool has been overhauled and had its name changed.

Thank you.

**Comment by Itai-Nelken** [comment]
@Botspot would you add the ["app"](https://github.com/Itai-Nelken/Pi-Assistant) now?
it still isn't a final realease, but if I don't find any bugs in the next few weeks then it will be final.
