### ISSUE TITLE
BUG: Cannot install Minecraft Pi

### ISSUE THREAD

**Issue by Joshy-2010** [Botspot/pi-apps#302]
I cannot install the fairly new App: "Minecraft Pi"

Here's the terminals output: (sorry if there is a prettier way to insert code I'm kinda new here; plus: How can i add `labels?)`

`Installing Minecraft Pi with install script
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
E: Paket minecraft-pi-native kann nicht gefunden werden.
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
Paket »docker.io« ist nicht installiert, wird also auch nicht entfernt.
0 aktualisiert, 0 neu installiert, 0 zu entfernen und 101 nicht aktualisiert.
Will not apply HSTS. The HSTS database must be a regular and non-world-writable file.
ERROR: could not open HSTS store at '/home/pi/.wget-hsts'. HSTS will be disabled.
Warnung: Joker-Zeichen werden bei HTTP nicht unterstützt.
--2021-01-30 21:52:23--  https://jenkins.thebrokenrail.com/job/minecraft-pi-reborn/job/master/lastSuccessfulBuild/artifact/out/deb/*zip*/deb.zip
Auflösen des Hostnamens jenkins.thebrokenrail.com (jenkins.thebrokenrail.com)... 2601:40a:8280:ce20::1, 68.43.64.50
Verbindungsaufbau zu jenkins.thebrokenrail.com (jenkins.thebrokenrail.com)|2601:40a:8280:ce20::1|:443 ... verbunden.
HTTP-Anforderung gesendet, auf Antwort wird gewartet ... 200 OK
Länge: nicht spezifiziert [application/zip]
Wird in »/home/pi/Programme/pi-apps/apps/Minecraft Pi/mcpi-reborn/deb.zip« gespeichert.

/home/pi/Programme/     [         <=>        ]  15,57M   233KB/s    in 65s     

2021-01-30 21:53:35 (243 KB/s) - »/home/pi/Programme/pi-apps/apps/Minecraft Pi/mcpi-reborn/deb.zip« gespeichert [16330088]

Archive:  /home/pi/Programme/pi-apps/apps/Minecraft Pi/mcpi-reborn/deb.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /home/pi/Programme/pi-apps/apps/Minecraft Pi/mcpi-reborn/deb.zip or
        /home/pi/Programme/pi-apps/apps/Minecraft Pi/mcpi-reborn/deb.zip.zip, and cannot find /home/pi/Programme/pi-apps/apps/Minecraft Pi/mcpi-reborn/deb.zip.ZIP, period.
Unable to extract deb.zip!

Failed to install Minecraft Pi with install script!

Close this window to exit.`

**Comment by Botspot** [comment]
Minecraft Pi is not ready. It doesn't work.

**Comment by Botspot** [comment]
It was supposed to be hidden on everyone's system, by the way.
