### ISSUE TITLE
[App submission] remarkable (markdown editor)

### ISSUE THREAD

**Issue by Itai-Nelken** [Botspot/pi-apps#305]
[remarkable.zip](https://github.com/Botspot/pi-apps/files/5899509/remarkable.zip)

**Comment by Itai-Nelken** [comment]
@Botspot can it be added?
I tested the scripts and they work perfectly fine.

**Comment by Itai-Nelken** [comment]
@Botspot is something wrong with this app? or you just didn't have time to test it?
It's completly ready, only thing left is for you to approve it and add it (or not).

**Comment by Botspot** [comment]
Actually I was able to briefly test this yesterday.  
It's not as good as stackedit.io, but I still think it's useful for offline usage.

I'll add it.

**Comment by Itai-Nelken** [comment]
> Actually I was able to briefly test this yesterday.
> It's not as good as stackedit.io, but I still think it's useful for offline usage.
> 
> I'll add it.

I can make a stackedit nativefier webapp if you want.

**Comment by Botspot** [comment]
Remarkable app added with commit c299f9dbad5a53a085f75f443720f7c0bc8e0be6.

**Comment by Botspot** [comment]
> I can make a stackedit nativefier webapp if you want.

Could you get it to run offline by any chance?

**Comment by Itai-Nelken** [comment]
> > I can make a stackedit nativefier webapp if you want.
> 
> Could you get it to run offline by any chance?

I could try to get all the html code, but I doubt It will work.

**Comment by Itai-Nelken** [comment]
@Botspot there is a chrome app that runs offline: https://chrome.google.com/webstore/detail/stackedit/iiooodelglhkcpgbajoejffhijaclcdg
