### ISSUE TITLE
Change Visual Studio Code

### ISSUE THREAD

**Issue by CleanMachine1** [Botspot/pi-apps#308]
Raspberry Pi  have added a microsoft repo into apt which allows VSCode to be installed with a `sudo apt install code`

**Comment by techcoder20** [comment]
Hmmm this might result in vscode being removed because apps which can be installed by apt have not been welcome in pi apps.

**Comment by CleanMachine1** [comment]
It doesn't matter, I am pretty sure the .deb are coming from the same repo from apt and pi-apps download are both coming. Just a suggestion and also consider that many people may still want it and as in the apt repo its called "code", people may not be able to find it.
Up to you but seems like a easy thing to change :)

**Comment by techcoder20** [comment]
Hmmm looks like it's up to @Botspot now

**Comment by Botspot** [comment]
> Raspberry Pi have added a microsoft repo into apt which allows VSCode to be installed with a `sudo apt install code`

Could you send me a link to their announcement? I'd be very surprised if this was truly the case.

**Comment by CleanMachine1** [comment]
> > Raspberry Pi have added a microsoft repo into apt which allows VSCode to be installed with a `sudo apt install code`
> 
> 
> 
> Could you send me a link to their announcement? I'd be very surprised if this was truly the case.

https://www.raspberrypi.org/forums/viewtopic.php?f=63&t=301011&p=1810197&hilit=Vscode#p1810197

Read the post to find the engineers say that added the repo after the new pi pico, as something to do with it is recommended to do with VSCode

Just to prove, run a sudo apt update and you will see the repo

**Comment by mobilegmYT** [comment]
I think the VSCode repo is automatically added when you install it.

**Comment by CleanMachine1** [comment]
I previously had installed VSCode to my pi using the official arm build from Microsoft and the same repo was added to my apt update

This idea of making the installer simplistic doesn't fix anything, just makes it most likely more reliable

**Comment by Itai-Nelken** [comment]
I just ran `apt update` and `apt upgrade` and it told me its adding the vscode repo, then it said it already exists (because I already have it installed).
so I'm pretty sure they did add it.

**Comment by Itai-Nelken** [comment]
I think pi-apps should install vscode the same way, because if it uses apt it won't work on other OS's that don't have the microsoft repo.

**Comment by CleanMachine1** [comment]
You make a valid point but remember that the repo that raspberry pi has used will probably work a little better than just using the current Pi-Apps method

But this is just my speculation

**Comment by Itai-Nelken** [comment]
> You make a valid point but remember that the repo that raspberry pi has used will probably work a little better than just using the current Pi-Apps method
> 
> But this is just my speculation

why work better? the current pi-apps vscode is downloaded from Microsoft's website and apt installs it, why would that be worse then downloading the same deb but from the repo?

**Comment by Botspot** [comment]
Unless Pi-Apps's version somehow breaks Raspberry Pi OS, I plan to leave Visual Studio Code as-is.

Other OS'es don't have Microsoft's repository, so in this case I think it's best to leave the app here.
