### ISSUE TITLE
Retro pi application not working 

### ISSUE THREAD

**Issue by shade024** [Botspot/pi-apps#315]
It won’t finish the installation

**Comment by Itai-Nelken** [comment]
that isn't enough information, can you send a screenshot of the error?

**Comment by Botspot** [comment]
> It won’t finish the installation

Yeah... can't help you there.  
I don't have enough money to buy a crystal ball.

> Mind reading not supported. ;-)

**Comment by Botspot** [comment]
I think it's safe to close this issue now.

@shade024 can reply back with details or error messages and the issue can be re-opened.
