### ISSUE TITLE
Anything using the headmelted repository doesn't work

### ISSUE THREAD

**Issue by JMVRy** [Botspot/pi-apps#316]
Any time I try to install an app that uses headmelted's repository, it says "APT reported these errors:
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://packagecloud.io/headmelted/codebuilds/debian stretch InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 0CC3FD642696BFC8
W: Failed to fetch https://packagecloud.io/headmelted/codebuilds/debian/dists/stretch/InRelease  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 0CC3FD642696BFC8
W: Some index files failed to download. They have been ignored, or old ones used instead."

I have no idea why these errors occur. Can anyone tell me how I can get this to work? This problem is keeping me from installing Wine (x86), Snap Store, Email Checker, Windows 10 theme, and possibly more apps I haven't tried installing yet.

![2021-02-02-162949_1920x1080_scrot](https://user-images.githubusercontent.com/77213524/106672390-9593c300-6575-11eb-905f-cf38afcf7352.png)

**Comment by Botspot** [comment]
> Any time I try to install an app that uses headmelted's repository, it says "APT reported these errors:

Correction: Any app that runs **`sudo apt update`** fails, because you messed around with your Pi. This is not a Pi-Apps problem.

Try to undo whatever you did to add the headmelted repository from your `/etc/apt/sources.list` and try again.

**Comment by JMVRy** [comment]
I did not add the headmelted repository in sources.list. The file is the same as it always was, and I still get the error.

**Comment by JMVRy** [comment]
Apparently, when I got VSCode from headmelted a while ago, it added "headmelted_vscode.list" to /etc/apt/sources.list.d. After I deleted this file (since I deleted their version of VSCode in exchange for your version), it worked fine.
