### ISSUE TITLE
Node JS

### ISSUE THREAD

**Issue by techcoder20** [Botspot/pi-apps#317]
Many people new to RPI always wonder how to install node js to compile a package or host a discord bot or something and in the process might mess something up so I think it would be a good idea to add it to pi apps .

**Comment by ilobilo** [comment]
I don't know if it will work.
[nodejs.zip](https://github.com/Botspot/pi-apps/files/5918815/nodejs.zip)

**Comment by Itai-Nelken** [comment]
> I don't know if it will work.
> [nodejs.zip](https://github.com/Botspot/pi-apps/files/5918815/nodejs.zip)

[nodejs.zip](https://github.com/Botspot/pi-apps/files/5918936/nodejs.zip)
@ilobilo I improved the script and added a missing `"`, it now also removes the repo from `/etc/apt/sources.list.d/nodesource.list`

**Comment by techcoder20** [comment]
@ilobilo I think @Botspot will prefer checking if curl is installed with pi apps package install functions

**Comment by Itai-Nelken** [comment]
> @ilobilo I think @Botspot will prefer checking if curl is installed with pi apps package install functions

[nodejs.zip](https://github.com/Botspot/pi-apps/files/5919108/nodejs.zip)
I added it, now it uses `pkg-install` and `purge-installed`.

**Comment by techcoder20** [comment]
Nice.

**Comment by Botspot** [comment]
This app will be added.

I'm thinking it should go in the Internet category. Any objections?

**Comment by Itai-Nelken** [comment]
> This app will be added.
> 
> I'm thinking it should go in the Internet category. Any objections?

no.
here is the latest zip: [nodejs.zip](https://github.com/Botspot/pi-apps/files/5919108/nodejs.zip) (same as in https://github.com/Botspot/pi-apps/issues/317#issuecomment-772554213)

**Comment by Botspot** [comment]
> > This app will be added.
> > I'm thinking it should go in the Internet category. Any objections?
> 
> no.
> here is the latest zip: [nodejs.zip](https://github.com/Botspot/pi-apps/files/5919108/nodejs.zip) (same as in [#317 (comment)](https://github.com/Botspot/pi-apps/issues/317#issuecomment-772554213))

I know, that's the zip I used and it worked perfectly.

What are you saying "no" about?

**Comment by Itai-Nelken** [comment]
> > > This app will be added.
> > > I'm thinking it should go in the Internet category. Any objections?
> > 
> > 
> > no.
> > here is the latest zip: [nodejs.zip](https://github.com/Botspot/pi-apps/files/5919108/nodejs.zip) (same as in [#317 (comment)](https://github.com/Botspot/pi-apps/issues/317#issuecomment-772554213))
> 
> I know, that's the zip I used and it worked perfectly.
> 
> What are you saying "no" about?

I'm saying I have no objection to put it under the Internet category.

**Comment by techcoder20** [comment]
> I'm thinking it should go in the Internet category. Any objections?

No 😀

**Comment by Botspot** [comment]
Only thing I have left before adding it is to tweak the 24x24 icon.

Right now, the text is unreadable. Solution: remove the text!

**Comment by Botspot** [comment]
What should it be called?

- Node JS
- nodejs
- Node.js
- Node.JS

**Comment by techcoder20** [comment]
The Wikipedia page says Node.js so...

**Comment by Botspot** [comment]
Added to pi-apps with commit c0948e8da8b0a527a44315a58e5dba256a3ab829.

**Comment by Botspot** [comment]
@ilobilo I had a lot of issues with this recently.

Could you remind me again why we didn't just do `sudo apt install nodejs npm`? That <-- command worked, while this app did not. It kept having weird issues. (See #498)

**Comment by Itai-Nelken** [comment]
> @ilobilo I had a lot of issues with this recently.
> 
> Could you remind me again why we didn't just do `sudo apt install nodejs npm`? That <-- command worked, while this app did not. This app kept having weird issues. (See #498)

@Botspot the version in apt breaks permissions on the system and makes it unusable.

**Comment by Botspot** [comment]
> > @ilobilo I had a lot of issues with this recently.
> > Could you remind me again why we didn't just do `sudo apt install nodejs npm`? That <-- command worked, while this app did not. This app kept having weird issues. (See #498)
> 
> @Botspot the version in apt breaks permissions on the system and makes it unusable.

Okay I've uninstalled node and npm via apt.

Same problem as before:  
```
pi@raspberrypi:~/edex-ui $ npm run install-linux
/usr/bin/env: `node`: No such file or directory
```

**Comment by ilobilo** [comment]
> @ilobilo I had a lot of issues with this recently.
> 
> Could you remind me again why we didn't just do `sudo apt install nodejs npm`? That <-- command worked, while this app did not. This app kept having weird issues. (See #498)

In original script I used `sudo apt-get install -y nodejs'

**Comment by ilobilo** [comment]
> > @ilobilo I had a lot of issues with this recently.
> > Could you remind me again why we didn't just do `sudo apt install nodejs npm`? That <-- command worked, while this app did not. This app kept having weird issues. (See #498)
> 
> In original script I used `sudo apt-get install -y nodejs`

I have not changed it

**Comment by Botspot** [comment]
> > @ilobilo I had a lot of issues with this recently.
> > Could you remind me again why we didn't just do `sudo apt install nodejs npm`? That <-- command worked, while this app did not. This app kept having weird issues. (See #498)
> 
> In original script I used `sudo apt-get install -y nodejs`
> I have not changed it

Oh you're right! https://github.com/Botspot/pi-apps/commit/c0948e8da8b0a527a44315a58e5dba256a3ab829#diff-739047f5ede4109ac5d3f61ec9dcd856812d5c57f245c14c94f1faacfce332b0

**Comment by ilobilo** [comment]
👍

**Comment by Botspot** [comment]
@Itai-Nelken I'm minded to revert back to @ilobilo's original NodeJS script, as it actually works.

Would you like to try to fix the existing script first?

**Comment by Itai-Nelken** [comment]
I'll try to fix it.
