### ISSUE TITLE
Doom

### ISSUE THREAD

**Issue by slashtechno** [Botspot/pi-apps#318]
What happened to Doom?

**Comment by Itai-Nelken** [comment]
I think something is wrong with it, so it was hidden untill it will be fixed.

**Comment by techcoder20** [comment]
Yes. We suspect it's because mesa got downgraded but it's a work in progress.

**Comment by Itai-Nelken** [comment]
> Yes. We suspect it's because mesa got downgraded but it's a work in progress.

did you try to update mesa?
becasue if the mesa downgrade really is the problem you can use the Mesa upgraders from the TwisterOS website (https://twisteros.com/faq.html).
and make the launcher script for doom to check the mesa version and update it if needed.

**Comment by slashtechno** [comment]
Oh Okay.
