### ISSUE TITLE
Pull Request or Issue

### ISSUE THREAD

**Issue by slashtechno** [Botspot/pi-apps#324]
If you have a completed app do you make an app submission or do you pull request?

**Comment by Itai-Nelken** [comment]
> If you have a completed app do you make an app submission or do you pull request?

you open a issue.
if you used the pi-apps app creator to create the scripts and icons etc. you zip the app folder (located in `~/pi-apps/apps/`) and upload it as well.

**Comment by Botspot** [comment]
I've found that app submissions are most efficient, when packaged in a zip file and uploaded to a new issue.

A pull request is harder to download, remix, and test.
