### ISSUE TITLE
bug/suggestion about nodejs

### ISSUE THREAD

**Issue by Itai-Nelken** [Botspot/pi-apps#325]
I have nodejs installed on my pi, but for some rason when I try to run `sudo apt update`  apt shows this error:
```bash
The following signatures were invalid: EXPKEYSIG 23E7166788B63E1E Yarn Packaging <yarn@dan.cx>
```
then exits with this error:
```bash
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://dl.yarnpkg.com/debian stable InRelease: The following signatures were invalid: EXPKEYSIG 23E7166788B63E1E Yarn Packaging <yarn@dan.cx>
W: Failed to fetch https://dl.yarnpkg.com/debian/dists/stable/InRelease  The following signatures were invalid: EXPKEYSIG 23E7166788B63E1E Yarn Packaging <yarn@dan.cx>
W: Some index files failed to download. They have been ignored, or old ones used instead.
```

while most people won't have this error I think it would be good to make the install script run this command:
```bash
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
```
if apt update exits with the error above.
there probably is a better way to do itt, but thats what I used and it fixed it.

**Comment by Botspot** [comment]
Thanks for the bug report.

This zip ought to work, could someone test it?  
[Node.js.zip](https://github.com/Botspot/pi-apps/files/5933560/Node.js.zip)

**Comment by Itai-Nelken** [comment]
it works fine.
something else I noticed, the part that adds the nodesource repo uses `curl` so its needed as a dependency
[Node.js.zip](https://github.com/Botspot/pi-apps/files/5933721/Node.js.zip)
here is a updated zip that install curl with pkg-install.

**Comment by Botspot** [comment]
This has been fixed with commit dd65c94e9b6facfd9edca06599ce8ca30bf8e140.

**Comment by fabianmendes** [comment]
Hi, excuse me. I've tried to install RetroPi
and got this code because of Nodejs conflict (rpm)

**Comment by Botspot** [comment]
> Hi, excuse me. I've tried to install RetroPi
> and got this code because of Nodejs conflict (rpm)

How did you even install RetroPie? I thought it was hidden for everyone as it's had too many problems.

**Comment by fabianmendes** [comment]
It is just there.. Idk, bro seriously I didn't anything to it appeared

On Feb 15, 2021 9:38 PM, "Botspot" <notifications@github.com> wrote:

Hi, excuse me. I've tried to install RetroPi
and got this code because of Nodejs conflict (rpm)

How did you even install RetroPie? I thought it was hidden for everyone as
it's had too many problems.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/Botspot/pi-apps/issues/325#issuecomment-779528148>, or
unsubscribe
