### ISSUE TITLE
StackEdit (nativefier webapp, runs offline)

### ISSUE THREAD

**Issue by Itai-Nelken** [Botspot/pi-apps#327]
[StackEdit.zip](https://github.com/Botspot/pi-apps/files/5936724/StackEdit.zip)
nativefier webapp, runs (and loads) offline after first start.

**Comment by Itai-Nelken** [comment]
[StackEdit.zip](https://github.com/Botspot/pi-apps/files/5937230/StackEdit.zip)
forgot to remove the tar.xz.

**Comment by Botspot** [comment]
Added with commit e2bfd67239cf935eeb909c722593c6c1722d6542.
