### ISSUE TITLE
Minecraft Bedrock frame rate

### ISSUE THREAD

**Issue by Pythonic456** [Botspot/pi-apps#328]
How can I get a decent frame rate (30-60 FPS) in Minecraft Bedrock from Pi-Apps? I am using a Pi 4B with 4G of RAM.
Help is appreciated!

**Comment by mobilegmYT** [comment]
> How can I get a decent frame rate (30-60 FPS) in Minecraft Bedrock from Pi-Apps? I am using a Pi 4B with 4G of RAM.
> Help is appreciated!

Turn every single setting to minimum?

**Comment by Pythonic456** [comment]
I have already :-| The lowest for the view distance is 6 chunks, how can I set this lower?
Thanks!

**Comment by mobilegmYT** [comment]
Try using the bedrocktimize addon to maybe set other settings lower?

**Comment by Pythonic456** [comment]
I added the bedrocktimize addon, and optimized the settings as much as I could, although I couldn't find the particle render distance setting. It made it from ~5fps to ~10fps, but is there a way to increase this even more?
Thanks for your help!

**Comment by phoenixbyrd** [comment]
If you're running on an SD performance is going to generally be junk, I recommend an SSD if you expect close to PC like performance off a little under powered SBC with a crap GPU. Bedrock edition you should be able to average 30 fps with ease.

**Comment by mobilegmYT** [comment]
Also the people who develop the launcher told me that versions like 1.16.40 and 1.16.20 run better as the new versions added a lot of things that decreased performance.

**Comment by Pythonic456** [comment]
@phoenixbyrd Why would running on an SD or an SSD affect the fps of Minecraft?

**Comment by mobilegmYT** [comment]
> @phoenixbyrd Why would running on an SD or an SSD affect the fps of Minecraft?
 Well SSDs are bigger and more expensive, so they offer higher read a write speeds, so the game writes and reads to the game buffers quicker.
