### ISSUE TITLE
Minecraft Java Launcher Cracked

### ISSUE THREAD

**Issue by RaspberryRBX** [Botspot/pi-apps#33]
[MinecraftJavaCracked.zip](https://github.com/Botspot/pi-apps/files/5420602/MinecraftJavaCracked.zip)

**Comment by Botspot** [comment]
I have been considering adding this for a while, but eventually decided it was not worth the legal risk.  
If somebody wants cracked Minecraft Java, first they have to install Minecraft Java, then run these two commands:

    sudo mv /usr/share/minecraftjava/launcher.jar /usr/share/minecraftjava/oldlauncher.jar
    sudo wget https://github.com/boomerangos/Cracked-Launcher/blob/master/crackedlauncherVer1.1.jar?raw=true -O /usr/share/minecraftjava/launcher.jar

**Comment by RaspberryRBX** [comment]
Ok
