### ISSUE TITLE
Problems Installing Pi Apps

### ISSUE THREAD

**Issue by ReallyFunnyGuyGabe** [Botspot/pi-apps#333]
I’ve been experimenting with Pi OS lately, and then used the correct commands to download this app. It seemed that it couldn’t install this app. Any fixes to squash that bug?

**Comment by ReallyFunnyGuyGabe** [comment]
Never mind, my internet connection wasn’t configured. SILLY ME!
There is no bug to squash here. Sorry for such an interruption.

**Comment by Botspot** [comment]
I'm glad you were able to fix it.

In the future though, I may be able to help you better (and sooner) if error reports were more specific than "it _couldn't_ install _this_ app".
