### ISSUE TITLE
Katoolin

### ISSUE THREAD

**Issue by slashtechno** [Botspot/pi-apps#334]
Is it possible to add [Katoolin](https://github.com/LionSec/katoolin)? This is a way to install tools found on Kali Linux on an Linux distro.

**Is there a way to individually add install scripts from Katoolin and/or add a way to uninstall Katoolin tools?**

**Comment by Botspot** [comment]
> Is it possible to add [Katoolin](https://github.com/LionSec/katoolin)?

If it runs on a Raspberry Pi, then there is a possibility it can be added to the app store.

On first glance, this says it's will "Automatically install all Kali linux tools". Is this a tool that would only be useful on Kali Linux?

**Comment by techcoder20** [comment]
@Botspot I went through the katoolin script and it installs most of the tools with apt commands so I think it's better to add the one katoolin script which gives us menu instead of adding individual apps

**Comment by slashtechno** [comment]
>  Is this a tool that would only be useful on Kali Linux?

This installs all Kali Linux tools on **any Ubuntu/Debian based OS**,
 

> it installs most of the tools with apt commands

Before you can install tools using Katoolin you have to use Katoolin to add Kali Linux repositories to sources.list.

I have run it on Raspberry Pi before. The only thing I do not like about it is that there is no uninstall feature.

**Comment by Botspot** [comment]
> Before you can install tools using Katoolin you have to use Katoolin to add Kali Linux repositories to sources.list.

You're right.  
Using Katoolin, I added the Kali repositories. Now, apt says **over 2000 packages** can be upgraded. Wow.

> I have run it on Raspberry Pi before. The only thing I do not like about it is that there is no uninstall feature.

I noticed that. Also, when trying to see what packages were upgradable, this happened:
```
pi@raspberrypi:~ $ sudo apt full-upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Error!
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libc6-dev : Breaks: libgcc-8-dev (< 8.4.0-2~) but 8.3.0-6+rpi1 is to be installed
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
```
APT errors. Fun.

**Comment by slashtechno** [comment]
> APT errors. Fun.

According to Katoolin you are supposed to remove Kali Linux repositories before updating your system. 
You can see that warning [here](https://github.com/LionSec/katoolin#warning)

**Comment by Botspot** [comment]
> > APT errors. Fun.
> 
> According to Katoolin you are supposed to remove Kali Linux repositories before updating your system.
> You can see that warning [here](https://github.com/LionSec/katoolin#warning).

Oh I think I get it now. So to install Kali tools, you'd add the Kali repositories, install stuff, then remove the Kali repositories immediately to avoid issues. Is that statement accurate?

**Comment by slashtechno** [comment]
> Oh I think I get it now. So to install Kali tools, you'd add the Kali repositories, install stuff, then remove the Kali repositories immediately to avoid issues. Is that statement accurate?

I believe so.

**Comment by Botspot** [comment]
> > Oh I think I get it now. So to install Kali tools, you'd add the Kali repositories, install stuff, then remove the Kali repositories immediately to avoid issues. Is that statement accurate?
> 
> I believe so.

Oh man...  
I'm afraid if this was added, **noob users** would fail to do that and mess up their systems badly. Perhaps we could automate the repository adding/removing part? Maybe a script would be the wrapper for katoolin, and it would add the kali repo first, run katoolin, then when the user exits, comment out the line in sources.list.

That might be too slow though, as it would have to run `sudo apt update` before and after.

**Comment by slashtechno** [comment]
Why would you need to run `apt update` after? Also Katoolin has a built in feature to remove Kali repositories.  
I would love to help make the script but I am not good at making scripts.

**Comment by Botspot** [comment]
> Why would you need to run `apt update` after?

To refresh which repositories existed. (And which were removed)

> Also Katoolin has a built in feature to remove Kali repositories.

I know. But how many beginner users would always remember to do that when they're done?

**Comment by slashtechno** [comment]
True...

**Comment by Botspot** [comment]
> I would love to help make the script but I am not good at making scripts.

There's only one way to change that...

Step 1: figure out what terminal command would be necessary to do with you want. Google searches are your friend, like: "bash change line in text file".
Step 2: put each command in a text file, one on each line. That's it - you just made a bash script!

**Comment by Itai-Nelken** [comment]
>text file

with the `.sh` file extension.

**Comment by Botspot** [comment]
> > text file
> 
> with the `.sh` file extension.

If you want to. But it's not mandatory. (Look at pi-apps - nothing ends in .sh!)  
But each text file (bash script) does begin with `#!/bin/bash` for good form.

**Comment by slashtechno** [comment]
Thank you for the tips. Will I need to reverse-engineer Katoolin? Also, would this work: making a script that add Kali repos updates then tells the user to install whatever they want then press enter. Once they press enter it removes repos and updates again.

**Comment by slashtechno** [comment]
I tried figuring out how to add multiple lines of text to a file but I could not. I was trying to make a bash script write to blank text file called kalirepo.py and then run it. I have attached the python script (it does everything needed with the sources.list)

**Comment by Botspot** [comment]
@slashtechno I've converted your python script into a bash script:
```
#!/bin/bash
sudo apt-key adv --keyserver pool.sks-keyservers.net --recv-keys ED444FF07D8D0BF6

#write to file as sudo user. The tee command is a necessary workaround. 
echo 'deb http://http.kali.org/kali kali-rolling main contrib non-free'| sudo tee /etc/apt/sources.list >/dev/null

#wait until user presses Enter.
read -p 'Press enter when you have installed needed tools'

#remove the line from sources.list
sudo sed -i '/deb http://http.kali.org/kali kali-rolling main contrib non-free\n/d' /etc/apt/sources.list

echo -e "\033[1;31m\nAll kali linux repositories have been deleted!\n\033[1;m"
```

**Comment by slashtechno** [comment]
Thank you @Botspot. Is this script done then for Katoolin?

**Comment by slashtechno** [comment]
@Botspot [This](https://github.com/s-h-3-l-l/katoolin3) is a port of Katoolin with improvements such as automatically dealing with repositories and uninstalling tools as well as other fixes.

**Comment by Botspot** [comment]
> @Botspot [This](https://github.com/s-h-3-l-l/katoolin3) is a port of Katoolin with improvements such as automatically dealing with repositories and uninstalling tools as well as other fixes.

Wow that looks very promising. Any idea why that port is now archived?

**Comment by slashtechno** [comment]
> > @Botspot [This](https://github.com/s-h-3-l-l/katoolin3) is a port of Katoolin with improvements such as automatically dealing with repositories and uninstalling tools as well as other fixes.
> 
> Wow that looks very promising. Any idea why that repository is now archived?

@Botspot Sorry for the late reply. I do not know why it is archived.

**Comment by Itai-Nelken** [comment]
any updates?

**Comment by theofficialgman** [comment]
given all the posts here with the original intention of creating a franken debian, as well as the new tool which has been archived, I'm going to close this for all of our sanity. we do NOT need users doing this https://github.com/Botspot/pi-apps/issues/334#issuecomment-775998234 its super dangerous and is just 100% going to cause issues in the long run.

if someone wants to make an maintain these kali tools in a piOS buster+ compatible package without updating system dependencies, then it can be added, but there is no way it will be added like this
