### ISSUE TITLE
Wine still detecting an invalid kernel after compiling a new one or installing either of the kernels provided on pi 3

### ISSUE THREAD

**Issue by Hampoon** [Botspot/pi-apps#338]
Hi, I have a raspberry pi 3 (still) and I just recently found Pi-Apps and I saw that it has Wine. I attempted to install it but it alerted me that the kernel that was installed would not work for Wine. I picked the first option, to switch to the 64-bit kernel which promptly stopped my Pi from booting and instead made it get stuck on the rainbow bootscreen. I had to reinstall. I tried again and I picked the third option to install a precompiled kernel which appeared to do nothing so I decided to do the second one. After waiting two and a half hours, it had the same result as the third option - nothing happened.

**Comment by Hampoon** [comment]
Update, I sudo apt get install'd wine and I do get the error that I don't have a proper kernel

**Comment by Itai-Nelken** [comment]
You need to reboot after installing the kernel (2nd or 3rd option) and install wine again, read what it tells you.

**Comment by Itai-Nelken** [comment]
after using the precompiled 3g/1g kernel you will get a message like this one in the terminal window:
```
It appears the precompiled 3G/1G kernel has been installed successfully.
Please reboot and install the Wine app again.
```
and after compiling the kernel:
```
It appears the 3G/1G kernel has been built and installed successfully.
Please reboot and install the Wine app again.
```

it won't do anything after showing this message.

**Comment by Itai-Nelken** [comment]
>I sudo apt get install'd wine

**DON'T DO THAT!** run `sudo apt purge wine`!
the wine pi-apps has is the x86 version running with box86, and installing wine from `apt` will conflict!

try this:
`sudo apt purge wine -y`
now install wine again from pi-apps.
if it aks you to select a option, select the option for the precompiled kernel.
wait for it to finish downloading and installing.
reboot
install wine again.

**Comment by Itai-Nelken** [comment]
>I picked the first option, to switch to the 64-bit kernel which promptly stopped my Pi from booting and instead made it get stuck on the rainbow bootscreen

@Botspot  maybe add a warning that switching to a 64bit kernel might stop the OS from booting?

**Comment by Botspot** [comment]
> > I picked the first option, to switch to the 64-bit kernel which promptly stopped my Pi from booting and instead made it get stuck on the rainbow bootscreen
> 
> @Botspot maybe add a warning that switching to a 64bit kernel might stop the OS from booting?

OS'es should not do that. And by the way, @Hampoon could have inserted his SD card into any computer available and edited the config.txt file to remove the `arm_64bit=1` line.

I'd like to know why a 64-bit kernel would do that. All my Pi3s use the 64bit kernel without issue. So for another person's Pi3 to not boot after switching, perplexes me.  
@Hampoon, have you always kept your OS up to date? Are/were you on the latest Raspberry Pi OS **Buster**?

**Comment by Hampoon** [comment]
Update #2, I tried the first option again and it just added a line to /boot/config.txt and nothing happened soooo...?
I should also note that I am running BerryBoot
Yes, I have kept it up to date. I put the latest version from the website on it like last week.

> 
> 
> > I sudo apt get install'd wine
> 
> **DON'T DO THAT IF THE WINE IN PI-APPS IS INSTALLED/YOU WANT TO INSTALL IT!!!**
> the wine pi-apps has is the x86 version running with box86, and installing wine from `apt` will conflict with it!
> 
> try this:
> 
>     1. run `sudo apt purge wine -y` in terminal.
> 
>     2. now install wine again from pi-apps.
> 
>     3. if it aks you to select a option, select the option for the precompiled kernel.
>        wait for it to finish downloading and installing.
> 
>     4. reboot
> 
>     5. install wine again.

Did this and I still get the incompatible kernel, also tried the first option again

**Comment by Itai-Nelken** [comment]
>I tried the first option again and it just added a line to /boot/config.txt and nothing happened soooo...?

you mean you selected the first option (change to 64bit kernel) and nothing happened other than the new line in the config.txt file?
if yes, you should reboot after it adds the line and install wine again as it tells you.

**Comment by Hampoon** [comment]
> 
> 
> > I tried the first option again and it just added a line to /boot/config.txt and nothing happened soooo...?
> 
> you mean you selected the first option (change to 64bit kernel) and nothing happened other than the new line in the config.txt file?
> if yes, you should reboot after it adds the line and install wine again as it tells you.

Yes, I know that I need to restart it.
I meant nothing happened as in it still gives me the error
I went ahead and manually added that line to config.txt and it is back to getting stuck on the rainbow screen, this time I will just remove it with a different computer

**Comment by Botspot** [comment]
> I went ahead and manually added that line to config.txt and it is back to getting stuck on the rainbow screen, this time I will just remove it with a different computer

@Hampoon, could you ask about that on the [Raspberry Pi Forums](https://www.raspberrypi.org/forums)?  
I've never heard of a Pi3 that refused to boot on the 64-bit kernel, and it would be fascinating to figure out what the underlying cause is for that.

**Comment by Hampoon** [comment]
> 
> 
> > I went ahead and manually added that line to config.txt and it is back to getting stuck on the rainbow screen, this time I will just remove it with a different computer
> 
> @Hampoon, could you ask about that on the [Raspberry Pi Forums](https://www.raspberrypi.org/forums)?
> I've never heard of a Pi3 that refused to boot on the 64-bit kernel, and it would be fascinating to figure out what the underlying cause is for that.

Possibly because I use BerryBoot, before I do that I'll just burn Raspberry Pi OS to a different SD card. 
If you are unaware, BerryBoot allows you to multiboot your pi

**Comment by Botspot** [comment]
> Possibly because I use BerryBoot

Maybe. I don't know.

**Comment by Botspot** [comment]
> > Possibly because I use BerryBoot
> 
> Maybe. I don't know.

Yeah that would be my guess.
