### ISSUE TITLE
When cloning repos use  "git clone depth=1 <repo-url>" instead of "git clone <repo-url>"

### ISSUE THREAD

**Issue by geraskalnas** [Botspot/pi-apps#339]
Hi. I have an suggestion.
Since pi-apps use git to download apps, "git clone" clones full repository, though for app installation full repository not required.
So my suggestion is to use  "git clone depth=1 <repo-url>" (it clones only current tree) instead of "git clone <repo-url>". 
Features: installation faster, less bandwidth.

**Comment by Botspot** [comment]
Thanks for the tip.

I've seen `--depth=1` used on other repositories before, but never realized it would make downloading faster.

With this discovery, I've chosen to make a standalone Pi-Apps installation script that applies what you've taught me. Thanks! :)
