### ISSUE TITLE
Box86

### ISSUE THREAD

**Issue by RaspberryRBX** [Botspot/pi-apps#34]
[Box86.zip](https://github.com/Botspot/pi-apps/files/5425263/Box86.zip)

**Comment by Botspot** [comment]
Good app suggestion, but there are a few problems with your submission:

- You need to fill out the description field.
- You need to include an icon.
- Unless your dropbox link is regularly updated, Box86 needs to be compiled from source to stay up-to-date.
- You need to use the error() function after every command, for both the `install` and `uninstall` scripts.

**Comment by mobilegmYT** [comment]
There's a person on the Pi Labs discord who does daily compiles of box86 at https://archive.org/details/box86.7z_20200928. He also made a script to automatically download and install his compiles. I think we can just mod the script he wrote. 
[box86_archive_insall.zip](https://github.com/Botspot/pi-apps/files/5426034/box86_archive_insall.zip)

**Comment by RaspberryRBX** [comment]
Botspot I Used Te Sonic Download Install Script And Changed It And Filled Out Everything And I Used The Box86 Installer From Novatech

**Comment by RaspberryRBX** [comment]
[Box86.zip](https://github.com/Botspot/pi-apps/files/5429990/Box86.zip)
Ive Update It And Add A Update Way And It Works

**Comment by RaspberryRBX** [comment]
[Box86.zip](https://github.com/Botspot/pi-apps/files/5430004/Box86.zip)
Fixed It And Add A Icon And A Update Tool For Terminal I Could'nt Get Icon To Work

**Comment by Botspot** [comment]
This is way more complicated than it needs to be.

 - The app's install script clones https://github.com/RaspberryRBX/Raspi-Box86-InstallScript, then runs `Raspi-Box86-InstallScript/FullInstallBox86.sh`
   - FullInstallBox86.sh clones https://github.com/DeadRasBoi12/Box86-Pilabs, then runs `Box86-Pilabs/install_box86.sh` and `Box86-Pilabs/Box86Updater.sh`.
     - `install_box86.sh` clones https://github.com/ptitSeb/box86, then compiles box86 from source.
     - `Box86Updater.sh` pulls the latest box86 and compiles it again!

**Comment by RaspberryRBX** [comment]
Well It's An Old Script I Pulled From My Github

**Comment by RaspberryRBX** [comment]
But It Should Work

**Comment by Botspot** [comment]
> But It Should Work

And if/when it doesn't work for someone's install, we would have to slog through all those layers of complexity to locate the problem.

Box86 will be added as an app, but the `install` script should compile box86 directly, **not** download a repository, that downloads a repository, that downloads a repository, to install box86.

**Comment by RaspberryRBX** [comment]
ok

**Comment by RaspberryRBX** [comment]
@Botspot I've  Made A Easy Updater For It And It Not Complex It Should Work Now And It Doesn't Have All Them Git clones still no image working
[Box86.zip](https://github.com/Botspot/pi-apps/files/5430750/Box86.zip)

**Comment by Botspot** [comment]
Box86 will be added to Pi-Apps. This issue will remain open until until it's added.

**Comment by Botspot** [comment]
@RaspberryRBX In case you're wondering why it's taking so long, it's because:

- Your script needs some changes, and I haven't been able to finish making those changes yet because:
- I am busy with developing vdesktop, PPT, and all the other app requests.

**Comment by Botspot** [comment]
> There's a person on the Pi Labs discord who does daily compiles of box86 at https://archive.org/details/box86.7z_20200928. He also made a script to automatically download and install his compiles. I think we can just mod the script he wrote.
> [box86_archive_insall.zip](https://github.com/Botspot/pi-apps/files/5426034/box86_archive_insall.zip)

@mobilegmYT Getting that to work is taking more effort than I imagined.  
As compiling box86 only takes a couple minutes on a Pi4, it doesn't seem like a big deal to do exactly that - have each Pi compile box86 locally instead of downloading a precompiled release.

**Comment by mobilegmYT** [comment]
Yea that seems a bit easier.

**Comment by Botspot** [comment]
Box86 has been added just now with commit 1c91abcbb71da4ff102eb49a8f7d781153aeb345.

**Comment by RaspberryRBX** [comment]
Add Cmake install to box86 installer

**Comment by Botspot** [comment]
> @Botspot Add Cmake install to box86 installer

Mind telling me why that's necessary? On my system, box86 installs just fine without executing `cmake install`.  
Also, the [official Box86 compilation guide](https://github.com/ptitSeb/box86/blob/master/COMPILE.md#for-raspberrypi) doesn't mention having to run `cmake install` either.

**Comment by RaspberryRBX** [comment]
In The Compiling U Need Cmake
also i meant sudo apt install cmake

**Comment by RaspberryRBX** [comment]
Not Cmake Install

**Comment by RaspberryRBX** [comment]
So Can U Add sudo apt install cmake on the box86 installer

**Comment by Botspot** [comment]
Oh! @RaspberryRBX thank you so much for pointing that out!

I had forgotten that cmake does not come installed on default Raspbian.

**Comment by Botspot** [comment]
OK. There we go. 3c7c17d3bd43ff4165af7d0d941b276a3a8fa92b

**Comment by RaspberryRBX** [comment]
OK
