### ISSUE TITLE
Discord App installs fine, does not open.

### ISSUE THREAD

**Issue by FlyingFaller** [Botspot/pi-apps#342]
Using RPI 0 W with Pi-Apps. I can install Discord through the PI Apps GUI without issue (pi-apps does not report corruption) but when I launch it, the hourglass thinks for a bit and nothing opens. Does not appear to be running in task manager either. Other apps install and open correctly. New to linux and RPI so if there is additional info I can provide that would be helpful please let me know. Thanks.

**Comment by Itai-Nelken** [comment]
I don't think the discord app is compatible with pi0, all the apps on pi-apps will work well on a pi4, most of them will work well on pi3 and I don't know how much will work on pi0.

the pi0's CPU is armv6 while the pi4' for example is arm64 (but most people use it with a armv7l OS).

you can try to build it from source (https://github.com/SpacingBat3/electron-discord-webapp) but I'm not sure it will work on pi0 at all.

**Comment by Botspot** [comment]
> also I don't think electron works with armv6 CPU's.

You hit it right on the nail.

In addition to reasons like that, you will find problems with some apps on your Pi Zero simply because I _don't have_ a Pi Zero to test stuff on.

@FlyingFaller Please continue reporting every app you find that doesn't work. Thank you.

**Comment by Itai-Nelken** [comment]
>I don't have a Pi Zero to test stuff on.

@Botspot I have a pi0, I'll test all apps on pi-apps on it sometime.
