### ISSUE TITLE
pi apps and raspberry pi arm64

### ISSUE THREAD

**Issue by timonrus** [Botspot/pi-apps#343]
After installing raspberry pi arm64, applications such as steam, wine, box86 and inelliJ IDEA are no longer available in pi apps. How to solve this problem?

**Comment by techcoder20** [comment]
> After installing raspberry pi arm64, applications such as steam, wine, box86 and inelliJ IDEA are no longer available in pi apps. How to solve this problem?

The reason for this is that those apps are not 64 bit compatibile so the only solution is to either compile it for 64 bit or find w 64 bit version

**Comment by timonrus** [comment]
> > After installing raspberry pi arm64, applications such as steam, wine, box86 and inelliJ IDEA are no longer available in pi apps. How to solve this problem?
> 
> The reason for this is that those apps are not 64 bit compatibile so the only solution is to either compile it for 64 bit or find a 64 bit version app

If I add architecture using the "sudo dpkg --add-architecture armhf" command, can I somehow achieve the display of application data?

**Comment by mobilegmYT** [comment]
> > > After installing raspberry pi arm64, applications such as steam, wine, box86 and inelliJ IDEA are no longer available in pi apps. How to solve this problem?
> > 
> > 
> > The reason for this is that those apps are not 64 bit compatibile so the only solution is to either compile it for 64 bit or find a 64 bit version app
> 
> If I add architecture using the "sudo dpkg --add-architecture armhf" command, can I somehow achieve the display of application data?

It wouldn't work. Unless you use a 32-bit OS, they don't work. You could try using vdesktop to boot a 32-bit VM.

**Comment by mobilegmYT** [comment]
@timonrus Could you close this issue please?

**Comment by timonrus** [comment]
> > > > After installing raspberry pi arm64, applications such as steam, wine, box86 and inelliJ IDEA are no longer available in pi apps. How to solve this problem?
> > > 
> > > 
> > > The reason for this is that those apps are not 64 bit compatibile so the only solution is to either compile it for 64 bit or find a 64 bit version app
> > 
> > 
> > If I add architecture using the "sudo dpkg --add-architecture armhf" command, can I somehow achieve the display of application data?
> 
> It wouldn't work. Unless you use a 32-bit OS, they don't work. You could try using vdesktop to boot a 32-bit VM.

I found this manual https://forum.armbian.com/topic/16584-install-box86-on-arm64/.
Is it possible to add this functionality to pi apps?

**Comment by mobilegmYT** [comment]
> > > > > After installing raspberry pi arm64, applications such as steam, wine, box86 and inelliJ IDEA are no longer available in pi apps. How to solve this problem?
> > > > 
> > > > 
> > > > The reason for this is that those apps are not 64 bit compatibile so the only solution is to either compile it for 64 bit or find a 64 bit version app
> > > 
> > > 
> > > If I add architecture using the "sudo dpkg --add-architecture armhf" command, can I somehow achieve the display of application data?
> > 
> > 
> > It wouldn't work. Unless you use a 32-bit OS, they don't work. You could try using vdesktop to boot a 32-bit VM.
> 
> I found this manual https://forum.armbian.com/topic/16584-install-box86-on-arm64/.
> Is it possible to add this functionality to pi apps?

It certainly is, though someone would need to turn all that code there into a bash script. Feel free to use the app creator if you'd like(run `~/pi-apps/createapp`) to try and make a bash script that does everything mentioned on the page.

**Comment by slashtechno** [comment]
> Also if you believe this manual https://thewayeye.net/posts/installing-raspotify-arm64/ then you don't necessarily need vdesktop to run.

This may be able to help with #320 (RealVNC on 64 bit) as well.
