### ISSUE TITLE
Minecraft Bedrock not downloading on Pi Apps

### ISSUE THREAD

**Issue by PB0819** [Botspot/pi-apps#344]
Ive tried several times to download pi apps, talking to people on discord and searching the web and still found no way to do so. My pi apps thinks im on a 64 bit system but I have 32 bit and when I tried downloading the 32 bit it still wouldnt work: 
Failed to check which packages whould be installed!
APT reported these errors:
E: Unable to locate package libcom-err2:armhf

Failed to install Minecraft Bedrock with install-64 script!
Ive made sure everything is up to date and still nothing worked. Can anyone help?

**Comment by Botspot** [comment]
> My pi apps thinks im on a 64 bit system but I have 32 bit

All Pi-Apps scripts use this code to detect which OS CPU-bit you're using:
```
#determine if host system is 64 bit arm64 or 32 bit armhf
if [ ! -z "$(file "$(readlink -f "/sbin/init")" | grep 64)" ];then
  arch=64
elif [ ! -z "$(file "$(readlink -f "/sbin/init")" | grep 32)" ];then
  arch=32
else
  error "Failed to detect OS CPU architecture! Something is very wrong."
fi
```
Let's modify the code to **tell** us which OS you're using, instead of setting it to a variable.
```
if [ ! -z "$(file "$(readlink -f "/sbin/init")" | grep 64)" ];then
  echo "64 bit"
elif [ ! -z "$(file "$(readlink -f "/sbin/init")" | grep 32)" ];then
  echo "32 bit"
fi
```
That above code, please copy it all and paste it into a terminal. Let's see what it says.

**Comment by PB0819** [comment]
Im using Raspian OS 32 bit (RPI #B+) @Botspot

**Comment by PB0819** [comment]
3 not #

**Comment by PB0819** [comment]
Everytime I download it from Pi-Apps it downloads the 64 bit but I checked my system it says im using a 32

**Comment by PB0819** [comment]
k maybe it is 64 bit

**Comment by PB0819** [comment]
but the pi apps still wont work

**Comment by Botspot** [comment]
> but I checked my system it says im using a 32

How did you check your system?

> but I still cant figure out why then it wont install properly

64-bit support is not as good as 32-bit support. Pi-Apps has many more apps for 32-bit, and you are less prone to seeing bugs than when you use the 64-bit version of Raspberry Pi OS.  
Unless you have a good reason to stay, I encourage you to switch to the 32-bit stable Raspberry Pi OS.
