### ISSUE TITLE
hide whatsapp web, it doesn't work, nativefier issue.

### ISSUE THREAD

**Issue by Itai-Nelken** [Botspot/pi-apps#345]
I remember seeing someone somwhere say that the whatsapp web webapp is saying it needs a newer version of chrome after asking to update, so I tested it and it does happen.
so @Botspot can you hide whatsapp web?
![image](https://i.imgur.com/2pTHUXJ.png)

**Comment by Itai-Nelken** [comment]
[whatsappweb.sh.zip](https://github.com/Botspot/pi-apps/files/5956695/whatsappweb.sh.zip)
@Botspot is it ok if I change the nativefier app with a simple chromium webapp like the one in the script above (its a slightly modified version of phoenixbyrd's webapps) until nativefier fix this issue?

**Comment by Itai-Nelken** [comment]
[Whatsapp.zip](https://github.com/Botspot/pi-apps/files/5956931/Whatsapp.zip)
@Botspot I modified the install & uninstall scripts to make a chromium webapp.

**Comment by Itai-Nelken** [comment]
oh, and I forgot the old scripts in the zip.

**Comment by Botspot** [comment]
@Itai-Nelken Could the nativefier app just get a proper user agent to fix the problem??

**Comment by Itai-Nelken** [comment]
@Botspot probably yes, but I don't know how.
I opened a issue in the nativefier repo: https://github.com/nativefier/nativefier/issues/1112
also this chrome app webapp is only a temprary solution so people can keep using whatsapp web.

**Comment by Botspot** [comment]
Looks like there already is an issue for that. It specifically mentions WhatsApp.

https://github.com/nativefier/nativefier/issues/51

**Comment by Itai-Nelken** [comment]
I tried that with the user agent of chrome 88 on my mac, but it still gives the same error.

**Comment by Itai-Nelken** [comment]
this is the user agent nativefier uses: `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36`
I also tried using this one: `Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36`
but same issue.
so @Botspot could you add the temporary webapp untill the nativefier issue is fixed?

**Comment by Botspot** [comment]
> so @Botspot could you add the temporary webapp untill the nativefier issue is fixed?

There I did it.

**Comment by Itai-Nelken** [comment]
Thanks

**Comment by Itai-Nelken** [comment]
I'll try to package a new nativefier version using the following user agents (they aren't chrome/chromium ones).
### user agents taken from a intel MBP running MacOS Big Sur 11.2.1:
**from Safari 14:** `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Safari/605.1.15`<br>
**from Firefox 85.0.2:** `Mozilla/5.0 (Macintosh; Intel Mac OS X 10.16; rv:85.0) Gecko/20100101 Firefox/85.0`<br>
**from MS Edge 88:** `Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36 Edg/88.0.705.68`<br>
### user agents taken from a ElementaryOS 5.1.7 (x64):
**GNOME Web (epiphany):** `Mozilla/5.0 (X11; Ubuntu; Linux x86_64) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0 Safari/605.1.15 Epiphany/605.1.15`<br>


I'll try some Windows onesas well if the ones above don't work.

**Comment by Itai-Nelken** [comment]
I made a whatsapp web nativefier webapp for MacOS and it does work, so I think its something wrong with the Linux versions as all bug reports reporting this issue in the nativefier repo that I read where about Linux.

**Comment by Itai-Nelken** [comment]
@Botspot good news! I packaged the nativefier webapp for the pi on my mac and it does work, maybe nativefiers user agent option is broken because I tried using the user agent from the mac but compiling on the pi and it didn't work.

**Comment by Botspot** [comment]
> @Botspot good news! I packaged the nativefier webapp for the pi on my mac and it does work, maybe nativefiers user agent option is broken because I tried using the user agent from the mac but compiling on the pi and it didn't work.

Have Nativefier go to a user agent displaying website to verify if the RPi version is indeed broken.

**Comment by Itai-Nelken** [comment]
I can't, my install died again...
if you can, heres how:
install node.js
run `npm install -g nativefier` (if it fails, run it as root).
run: `nativefier --arch=armv7l https://www.whatismybrowser.com/detect/what-is-my-user-agent` and see what user agent it says, then run this: `nativefier --arch=armv7l --user-agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36" https://www.whatismybrowser.com/detect/what-is-my-user-agent`
