### ISSUE TITLE
Minecraft Java

### ISSUE THREAD

**Issue by cjcool18** [Botspot/pi-apps#347]
i only can play not full version can you fix it

**Comment by mobilegmYT** [comment]
> i only can play not full version can you fix it

What do you mean?

**Comment by cjcool18** [comment]
Microsoft account

**Comment by cjcool18** [comment]
I not have mojang account

**Comment by mobilegmYT** [comment]
> Microsoft account

Microsoft account support is in the works. We're just finishing some code to make it work.

**Comment by cjcool18** [comment]
I have Microsoft account

**Comment by cjcool18** [comment]
When

**Comment by mobilegmYT** [comment]
> When

I can't give an exact estimate, but about 1-2 weeks.

**Comment by cjcool18** [comment]
I done

**Comment by cjcool18** [comment]
Ok
