### ISSUE TITLE
Pi Apps for Terminal

### ISSUE THREAD

**Issue by techcoder20** [Botspot/pi-apps#350]
@Botspot  I have made a terminal version for pi apps. I have tried to make it similar to apt. It has `install`, `uninstall`, `update`, `list-all`, `list-installed`, `search`

Commands To Test It out:
First Download the file
`wget https://raw.githubusercontent.com/techcoder20/PiAppsPackageManagerTerminal/main/papm.py`
Move it to pi-apps directory
`mv papm.py ~/pi-apps`
Create a alias
`alias papm="python3 ~/pi-apps/papm.py"`
Run the help command to get the list of commands
`papm help`

Hope you like it 🙂
Btw if ur wondering what papm is it stands for pi apps package manager

**Comment by Itai-Nelken** [comment]
I just tested it and it works really well, I especially like the list all command, it prints all apps in a easy to read way with the description for each app.

**Comment by Botspot** [comment]
Okay, let's add this.

It won't be included on all installs (because I want to be able to say Pi-Apps is truly 100% bash), but I will allow it to be its own app under the Tools category that people can install if they choose to.

**Comment by techcoder20** [comment]
> Okay, let's add this.
> 
> It won't be included on all installs (because I want to be able to say Pi-Apps is truly 100% bash), but I will allow it to be its own app under the Tools category that people can install if they choose to.

I don't see a problem with having a little python but okay a seperate app might be good. Do u want me to make a install script for pi apps ?

**Comment by Botspot** [comment]
> Do u want me to make a install script for pi apps ?

Yes please. It shouldn't take long.

Here's the icons I made for it:  
![logo-24](https://user-images.githubusercontent.com/54716352/109534011-7e66c900-7a80-11eb-9be2-5286d0efae6f.png)
![logo-64](https://user-images.githubusercontent.com/54716352/109534015-7eff5f80-7a80-11eb-8b7e-928dbf807752.png)

**Comment by Itai-Nelken** [comment]
>Here's the icons I made for it:
![icon-24](https://user-images.githubusercontent.com/54716352/109535228-ee298380-7a81-11eb-86d5-6f40a0a8361c.png)
![icon-64](https://user-images.githubusercontent.com/54716352/109535226-ed90ed00-7a81-11eb-9b26-915cfb18eb75.png)

nice icons.

**Comment by slashtechno** [comment]
One thing, can the command to use it be `pi-apps` instead of `papm`?

Also those icons are amazing. How did you make them?

**Comment by techcoder20** [comment]
> One thing, can the command to use it be `pi-apps` instead of `papm`?
> 
> Also those icons are amazing. How did you make them?

U just need to change the alias to pi-apps. @Botspot which one do u want ?

**Comment by Botspot** [comment]
> > One thing, can the command to use it be `pi-apps` instead of `papm`?
> > Also those icons are amazing. How did you make them?
> 
> U just need to change the alias to pi-apps. @Botspot which one do u want ?

My preferred method would be to replace Pi-Apps's default terminal command. `/usr/local/bin/pi-apps`  
The code responsible for creating it can be found in the Pi-Apps `install` script:
```bash
#pi-apps terminal command
if [ ! -f /usr/local/bin/pi-apps ] || ! grep -q /usr/local/bin/pi-apps "${DIRECTORY}/gui";then
  rm /usr/local/bin/pi-apps
  echo "#!/bin/bash
${DIRECTORY}/gui" | sudo tee /usr/local/bin/pi-apps >/dev/null
  sudo chmod +x /usr/local/bin/pi-apps
  echo "You can now run pi-apps in a terminal, just by running 'pi-apps'"
fi
```
Notice something: If `grep` doesn't find that file containing `${DIRECTORY}/gui` (translates to `/home/pi/pi-apps gui` by default), then it will replace the file. This is to prevent any issues with non-standard/corrupted files.  
So, when you create the file that will overwrite that one, be sure to include a commented-out mention of `${DIRECTORY}/gui` to prevent it from being overwritten.

**Comment by Botspot** [comment]
> Also those icons are amazing. How did you make them?

Well, in this case, I just changed the colors of the existing Pi-Apps icon. The Pi-Apps logo, in vector format, can be found at `/home/pi/pi-apps/icons/logo.svg`.  
My favorite SVG image editor is Boxy SVG. It's available on Pi-Apps.

**Comment by techcoder20** [comment]
I have finished the install script. I am sorry but i was unable to understand how you are checking  for corrupted files so I was unable to add it. Also the name has been changed to PiAppsTerminalAdvanced cause I felt it made more sense.

[PiAppsTerminalAdvanced.zip](https://github.com/Botspot/pi-apps/files/6067979/PiAppsTerminalAdvanced.zip)

**Comment by Botspot** [comment]
> I am sorry but i was unable to understand how you are checking for corrupted files so I was unable to add it.

In order to not be overwritten, the file must contain `${DIRECTORY}/gui` (`/home/pi/pi-apps/gui`) somewhere. If not, then the file will be overwritten.  
Here's what my file looks like:
```
pi@raspberrypi:~ $ cat /usr/local/bin/pi-apps
#!/bin/bash
/home/pi/pi-apps/gui
```
So, your file will also have to contain `/home/pi/pi-apps/gui`, in order to not be overwritten. How? Easy:
```
#!/bin/bash
#just comment it out
#/home/pi/pi-apps/gui
#put your script stuff below this
```

**Comment by techcoder20** [comment]
I am not creating a binary file. I am creating a alias so I just remove the file in /usr/local/bin. If you want I can take the path used in the default binary store it in some file and use it whenever the python script is running

**Comment by Botspot** [comment]
> I am not creating a binary file. I am creating a alias so I just remove the file in /usr/local/bin. If you want I can take the path used in the default binary store it in some file and use it whenever the python script is running

To avoid issues, I want your installation script to overwrite `/usr/local/bin/pi-apps`.  
And no, it's not a "binary file", it's a two-line bash script.

**Comment by techcoder20** [comment]
I am not overwriting the file. When I tried placing the python script in `/usr/local/bin` it was not working and I am not sure how to get it to work, so I am making a alias.

**Comment by Botspot** [comment]
Can we get a better description?

For example, when I run `pi-apps`, it just opens the GUI window for some reason. The description doesn't explain, at all, how to use your program.

**Comment by techcoder20** [comment]
Oh ya sry about that will send one with updated description soon.

**Comment by Botspot** [comment]
Here's my version, that seems to work fine, that uses `/usr/local/bin/pi-apps`.
[PiAppsTerminalAdvanced.zip](https://github.com/Botspot/pi-apps/files/6069888/PiAppsTerminalAdvanced.zip)

Advantages of using a bash script in `/usr/local/bin` are:
- There's only one file responsible. If you used bashrc and Pi-Apps used `/usr/local/bin/pi-apps`, then we'd have one more place to look if there were errors. And I'm not sure what would happen if both existed at once. (Which one would override the other?)
- It works immediately. No need to source bashrc.
- It's easier to undo.
- It works for all users, globally.

**Comment by techcoder20** [comment]
Okay what about instead of translating the whole thing to bash I make a bash script that takes the arguments and executes the python script accordingly

**Comment by Botspot** [comment]
> Okay what about instead of translating the whole thing to bash I make a bash script that takes the arguments and executes the python script accordingly

That's actually exactly what I did.

After running my install script, the `/usr/local/bin/pi-apps` text file contains:
```
#!/bin/bash
#/home/pi/pi-apps/gui
python3 /home/pi/pi-apps/PiAppsTerminalAdvanced.py $@
```

**Comment by techcoder20** [comment]
@Botspot I have added a list of arguments in the description and added a \ in the echo command to ignore the $ sign
[PiAppsTerminalAdvanced.zip](https://github.com/Botspot/pi-apps/files/6073492/PiAppsTerminalAdvanced.zip)

**Comment by Itai-Nelken** [comment]
I tried the latest zip (https://github.com/Botspot/pi-apps/issues/350#issuecomment-789409114) and there is something wrong with the python script: it launches pi-apps only, same as what was before.
I checked and `/usr/local/bin/pi-apps` is what is should be. I launched the python script and got the same result: pi-apps starts regularly.

**Comment by Itai-Nelken** [comment]
I just tested it and it works great.
maybe add to the description that if you don't supply any arguments it starts pi-apps regularly.

**Comment by Botspot** [comment]
Added to Pi-Apps with commit c16f703c05ac9aee86ec9027fda88b8a67927e25
