### ISSUE TITLE
Pi-safe app request

### ISSUE THREAD

**Issue by RichardMidnight** [Botspot/pi-apps#351]
Love that you did this.  I was thinking of starting a more basic pi-app-store... again, glad you did it.

I wrote pi-safe.  A menu driven tool to create shrunk, compressed raspberry pi image files.  It can also restore them.

https://github.com/RichardMidnight/pi-safe

Best wishes,  Richard

**Comment by Botspot** [comment]
Fascinating. How does it compare to Pi Power Tools?

**Comment by RichardMidnight** [comment]
I think pi-safe is simpler (but I may be biased).  It is like Raspberry Pi Imager if they added a "create image" button.  I only put a simple gui on it, so it is not as fancy, but pretty easy to use.  There is a Backup option to create an image file from an sd card and a Restore option to write the image file back to an sd card.

**Comment by RichardMidnight** [comment]
There is a screen shot of the front menu here:  https://github.com/RichardMidnight/pi-safe/blob/main/snapshot.png

**Comment by RichardMidnight** [comment]
What is entailed in making a pi-apps app?

**Comment by Botspot** [comment]
> What is entailed in making a pi-apps app?

First of all, I apologize for leaving this issue silent. There's just so many of them and I can't keep up with all of them.

Making your own app is pretty easy. Check out [our wiki](https://github.com/Botspot/pi-apps/wiki).

**Comment by Botspot** [comment]
> What is entailed in making a pi-apps app?

First of all, I apologize for leaving this issue silent. There's just so many of them and I can't keep up with all of them.

Making your own app is pretty easy. Check out [our wiki](https://github.com/Botspot/pi-apps/wiki).

**Comment by RichardMidnight** [comment]
No problem.  I will take a look at creating the script.

**Comment by RichardMidnight** [comment]
attempt number 1
not too sure about the icon...
[PiSafe.zip](https://github.com/Botspot/pi-apps/files/6395616/PiSafe.zip)

**Comment by Botspot** [comment]
I've not tried your zip yet, but looking in your uninstall script, there doesn't seem to be any commands that remove a folder.
Does PiSafe really not keep any folders anywhere?

**Comment by Botspot** [comment]
Okay, installation was successful.

One thing I noticed about the desktop file: it's being run in two nested terminals. So first, the desktop manager runs the command in a terminal, because your desktop file contains `Terminal=true`.
*Then*, your desktop file's `Exec=` *also* launches a terminal.
Consequently, when I click your menu launcher, two terminals appear, then one disappears shortly thereafter.

By the way, not all RPi operating systems will have `lxterminal` installed. How will your program handle such systems?

**Comment by Botspot** [comment]
In your uninstall script, this line contains two problems:
```
sudo rm "~/.local/share/applications/$PRODUCTNAME.desktop"
```
First, it should not be necessary to remove a local user-generated file, with sudo. It's bad practice and should be avoided if at all possible.
Second, when you put `~/` inside quotes, it's not expanded. As a result, the `rm` command is going to search for a file _literally_ named `~/.local/share/applications/PiSafe.desktop`, which, obviously doesn't exist.
Solution(s):

- Move the `~/` out of quotation marks:
`rm ~/".local/share/applications/$PRODUCTNAME.desktop"`
- Use the environment variable instead:
`rm "$HOME/.local/share/applications/$PRODUCTNAME.desktop"`

**Comment by RichardMidnight** [comment]
Let me think... it is just the script file, a config file and the menu entries... unless I forgot something.

**Comment by RichardMidnight** [comment]
Thanks for the feedback, I will take a look.  There is an install and uninstall in the pisafe menu itself.

**Comment by Botspot** [comment]
> There is an install and uninstall in the pisafe menu itself.

I noticed that. For Pi-Apps only, could your install script *not* ask the user for confirmation if they really want to install PiSafe? (user-interaction within install scripts is frowned upon)

**Comment by RichardMidnight** [comment]
[pisafe-piapps.zip](https://github.com/Botspot/pi-apps/files/6406712/pisafe-piapps.zip)

OK, how is this?  I modified PiSafe to allow a silent install and uninstall.  I modified the pi-apps scripts.  Hopefully I got it all right.
By the way, I don't know what do do about the lxterminal call in the .desktop file.  Do you have any suggestions?

**Comment by Botspot** [comment]
> OK, how is this? I modified PiSafe to allow a silent install and uninstall. I modified the pi-apps scripts. Hopefully I got it all right.

It worked fine for me.

> By the way, I don't know what do do about the lxterminal call in the .desktop file. Do you have any suggestions?

Well, first it doesn't need `Terminal=true`. Second, I'd suggest you create a terminal-run script that will accommodate various terminals.
Pi-Apps had this exact same problem early on. To solve it, I created the `terminal-run` script. On a normal pi-apps installation, this script is located at `~/pi-apps/etc/terminal-run`.

My terminal-run script doesn't set the terminal _size_ though, so this is something you'd have to work through, one terminal at a time.

**Comment by RichardMidnight** [comment]
Thanks, I will look into the terminal-run later.  I did set terminal to false.  If the scripts work for you, you can include in pi-apps.

**Comment by Botspot** [comment]
> Thanks, I will look into the terminal-run later. I did set terminal to false. If the scripts work for you, you can include in pi-apps.

If Pi-safe was added to the app store now, it would fail to work on Ubuntu, Manjaro, and all other linux systems that don't have lxterminal installed.
Are you sure it's ready to add?

**Comment by RichardMidnight** [comment]
1) Good point.  I appreciate your advice.  Do you also have a routine that will put an app in the active desktop that is running?  
2) My primary scope was students and builders working with the RaspberryPi-OS desktop (LXDE?).  So the current menu-front-end installs into the LXDE desktop.
3) With the CLI, it probably runs on most Debian distros,
4) If there is not an easy way to insert it into various popular desktop environments, I may just document the scope to be RaspberryPiOS and let it go.
What are your thoughts?

**Comment by RichardMidnight** [comment]
Hmm, I just looked up MATE and xfce and it looks like the .desktop file is the same and put in the same folder.  Looks like this is a standard.

**Comment by RichardMidnight** [comment]
OK, I updated PiSafe ver 1.0.4 to use an available terminal (thanks for the code).  As above, I think the menu works on most Desktop Environments.  The pi-apps scripts I sent last should still work.  I think it is ready to be put into Pi-Apps.
Thanks.

**Comment by Botspot** [comment]
> Hmm, I just looked up MATE and xfce and it looks like the .desktop file is the same and put in the same folder. Looks like this is a standard.

What I mean is: Those operating systems **do not** use lxterminal. So if your app *depends* on lxterminal only, then it'll only work on the OS'es that have it installed.

What I recommend: accommodate _several_ terminals like Pi-Apps does with its `terminal-run` script.
For your convenience, here is Pi-Apps' terminal-run script. It can be found at `~/pi-apps/etc/terminal-run`
```
#!/bin/bash

#$1 is the command to be run.
#$2 is the title.

if [ -f /usr/bin/lxterminal ];then
  lxterminal --title="$2" -e bash -c "$1"
elif [ -f /usr/bin/xfce4-terminal ];then
  xfce4-terminal --title="$2" -x bash -c "$1"
elif [ -f /usr/bin/mate-terminal ];then
  #mate-terminal --title="$2" -e "bash -c "\""$1"\"""
  mate-terminal --title="$2" -x bash -c "$1"
elif [ -f /usr/bin/xterm ];then
  xterm -T "$2" -e bash -c "$1"
elif [ -f /usr/bin/konsole ];then
  konsole -p tabtitle="$2" -e bash <(echo "$1")
elif [ -f /usr/bin/terminator ];then
  terminator -T "$2" -x bash -c "$1"
elif [ -f /usr/bin/gnome-terminal ];then
  gnome-terminal --title "$2" -x bash -c "$1"
elif [ -f /usr/bin/x-terminal-emulator ];then
  $(readlink -f /usr/bin/x-terminal-emulator) -e bash -c "$1"
else
  echo "Failed to locate any terminal emulators!!!"
  exit 1
fi
```

**Comment by RichardMidnight** [comment]
Yes, thank you.  I did that.  I used your code as a model.  It customizes the .desktop file depending on the terminal found.  It works on Ubuntu and LMDE.
