### ISSUE TITLE
Jgrasp installation fail

### ISSUE THREAD

**Issue by chunky-milk** [Botspot/pi-apps#354]
I am on Twister OS and i got this error when installing JGrasp. ![image](https://user-images.githubusercontent.com/71036629/107880942-df52a680-6eaf-11eb-8a31-aa09dcdfef9c.jpeg)

**Comment by Itai-Nelken** [comment]
weird! there is no line 40!
<img width="1197" alt="Screen Shot 2021-02-14 at 5 37 19 PM" src="https://user-images.githubusercontent.com/70802936/107881090-52c5d980-6eeb-11eb-8939-b1f6554ee506.png">

**Comment by Botspot** [comment]
Oh wow. Missing quotation mark.  
Yes it happens to everyone. Even Botspot. :(

Fixed with commit 13c6937a26ca0374e7da39423643427c06c1dae5.
