### ISSUE TITLE
Choose to update box86 automatically

### ISSUE THREAD

**Issue by Pythonic456** [Botspot/pi-apps#355]
It would be a nice feature if you could turn off automatic box86 compile/install when you install a box86 app, it doesn't even have to be an obvious thing, it could be some option in a text file or bash script or similar.
Thanks!

**Comment by Itai-Nelken** [comment]
box86 doesn't update at all, it just uses box86 updater's script to install box86.

**Comment by Botspot** [comment]
> It would be a nice feature if you could turn off automatic box86 compile/install when you install a box86 app, it doesn't even have to be an obvious thing, it could be some option in a text file or bash script or similar.
> Thanks!

@Pythonic456 This is a good idea. In fact, barely any effort would be needed to do it as I've already done it. See: https://github.com/Botspot/box86-updater

Box86-updater has these three options:

- Just install box86 once and don't leave anything behind. (Current approach with pi-apps)
- Install box86 and display a notification whenever an update is available.
- Install box86 and automatically update without asking.

Some people won't want notifications. Others don't want auto-update. And others (like you and me) would prefer box86 to not easily go out of date.

I've not found a way to satisfy everybody. Any ideas?

**Comment by Pythonic456** [comment]
@Botspot I would also like an option to _not_ update/compile box86 automatically, for instance if I already had box86 installed. Simply put: A way to disable automatic update/compile of box86.

**Comment by Itai-Nelken** [comment]
@Pythonic456 pi-apps does **not** update box86 automatically.

**Comment by Itai-Nelken** [comment]
@Botspot's box86 updater has a script that simply installs box86 using pales automatic builds, so the pi-apps install script simply uses that script.
<img width="759" alt="Screen Shot 2021-02-15 at 3 58 16 PM" src="https://user-images.githubusercontent.com/70802936/107955637-aea16880-6fa6-11eb-997f-c1f2354026ba.png">
^ thats the line the pi-apps script uses, the screenshot is from the [box86 updater github repo](https://github.com/botspot/box86-updater).

**Comment by Pythonic456** [comment]
I think I need to make it clear exactly what I mean. I think there should be a choice when you try and install an app that would use box86, to compile box86 or not.

**Comment by Itai-Nelken** [comment]
> I think I need to make it clear exactly what I mean. I think there should be a choice when you try and install an app that would use box86, to compile box86 or not.

oh, I didn't understand until now.
yes I think that is a good idea, as @Pythonic456 maybe a setting in pi-apps settings.

**Comment by Botspot** [comment]
Itai is developing a repository that hosts box86 deb packages.  
This will have many advantages, including easier installation on RPiOS, and a built-in updating capability.

This is very exciting news IMHO.

**Comment by Itai-Nelken** [comment]
its actually sort of done, you can install box86 and update it when new version is uploaded by my script, but at this stage use it at your own risk, it might be down a few times while I'm working on it snd cause some apt errors.
https://itai-nelken.github.io/weekly-box86-debs/

**Comment by Botspot** [comment]
>but at this stage use it at your own risk, it might be down a few times while I'm working on it snd cause some apt errors.

Yeah, I don't know. It would be a shame to increase the number of bug reports, just because your repo is offline. Let me know when it's equally reliable to the existing box86 installation method.

**Comment by Itai-Nelken** [comment]
the repo is up, I won't be changing anything in the way its set up, so no apt errors.
I might migrate it to a better format in the future, but I'll do it in a way that won't cause any errors (I'm thinking about something like the code that added the vscode repo to rpiOS).

**Comment by Botspot** [comment]
@Pythonic456 The Box86 app now uses Itai's box86 apt package.

Upgrading happens whenever you run `sudo apt upgrade box86`
