### ISSUE TITLE
Snapdrop

### ISSUE THREAD

**Issue by chunky-milk** [Botspot/pi-apps#356]
https://github.com/RobinLinus/snapdrop
[Snapdrop.zip](https://github.com/Botspot/pi-apps/files/5978642/Snapdrop.zip)

**Comment by chunky-milk** [comment]
@Botspot

**Comment by Itai-Nelken** [comment]
its a really useful app, and the speeds aren't to bad either.

**Comment by Itai-Nelken** [comment]
@chunky-milk its a nativefier webapp, right?

**Comment by chunky-milk** [comment]
Yes.

**Comment by chunky-milk** [comment]
@Botspot @Itai-Nelken added 64bit also, 
[snapdrop.zip](https://github.com/Botspot/pi-apps/files/5982440/snapdrop.zip)

**Comment by Itai-Nelken** [comment]
[Snapdrop.zip](https://github.com/Botspot/pi-apps/files/5982555/Snapdrop.zip)
@chunky-milk the install-32 was installing the 64bit version and the install-64 the 32bit one.
fixed it.

**Comment by chunky-milk** [comment]
> [Snapdrop.zip](https://github.com/Botspot/pi-apps/files/5982555/Snapdrop.zip)
> @chunky-milk the install-32 was installing the 64bit version and the install-64 the 32bit one.
> fixed it.
Oh no! Thanks!

**Comment by chunky-milk** [comment]
@Botspot

**Comment by Botspot** [comment]
The icons need work.

Both icons in @Itai-Nelken's zip are too large (96x96 and _512x512_) and don't match each other.  
Which one should be used?  
![2021-03-07-152836_1920x1080_scrot](https://user-images.githubusercontent.com/54716352/110255549-f5f19800-7f59-11eb-8453-358fbb0c7d61.png)

**Comment by Itai-Nelken** [comment]
> The icons need work.
> 
> Both icons in @Itai-Nelken's zip are too large (96x96 and _512x512_) and don't match each other.
> Which one should be used?
> ![2021-03-07-152836_1920x1080_scrot](https://user-images.githubusercontent.com/54716352/110255549-f5f19800-7f59-11eb-8453-358fbb0c7d61.png)

the `icon-32`.

**Comment by Botspot** [comment]
Okay, done. I ended up using another icon, similar to the icon-32, but without a drop shadow. This scaled down to 24x24 a lot easier.

@Itai-Nelken, is this an accurate description?

> Share files with nearby devices on the local network. Inspired by Apple's Airdrop.
> To run: Menu -> Internet -> Snapdrop
> To use: Open a web browser on the other computer/smartphone and go to snapdrop.net
> Now drag and drop files to the website, and the other device will see the files and download them.

**Comment by Itai-Nelken** [comment]
>@Itai-Nelken, is this an accurate description?

Share files with nearby devices on the local network. Inspired by Apple's Airdrop.
To run: Menu -> Internet -> Snapdrop
To use: Open a web browser on the other computer/smartphone and go to snapdrop.net
Now drag and drop files to the website, and the other device will see the files and download them.

in my opinion yes.
here is the github repo for it: https://github.com/RobinLinus/snapdrop

**Comment by Botspot** [comment]
Added with commit f0d5b96935f198399b6adb3743e1c1ad216d14c4

**Comment by robert5974** [comment]
Raspberry Pi complains when Snapdrop is ran.  It warns that Nativefier needs to be updated and the app should be rebuilt.  I tried to use it regardless of the message but using the Android app for snapdrop, every upload failed.

**Comment by cycool29** [comment]
> Raspberry Pi complains when Snapdrop is ran. It warns that Nativefier needs to be updated and the app should be rebuilt. I tried to use it regardless of the message but using the Android app for snapdrop, every upload failed.

@ryanfortner

**Comment by Itai-Nelken** [comment]
Should be fixed
