### ISSUE TITLE
USB Microphone not working with Zoom

### ISSUE THREAD

**Issue by joaojcorreia** [Botspot/pi-apps#357]
I've installed pi-apps in my daughters Raspberry pi 400, and successfully installed Zoom. Everything works fine, we are able to connect to meeting, the video works fine, there is a little lag, but nothing that wouldn't make impossible to use. The only exception is the input sound. The Rapsberry pi 400 has no sound jack, so we are using a USB camera with integrated mic. The mic works fine elsewhere, both in a mic test within Raspberry pi 400, and on a PC, but on Zoom it doesn't work properly. For the initial seconds it works fine, but after that it only really registers loud sounds and even those not properly. For example if one claps, the other side will only hear light "tick tick". I've also tried with a bluetooth head set and it is the same thing. Am I missing installing something? Thank you for your help.

**Comment by Itai-Nelken** [comment]
that is a known issue unfortunately.
see this issue on the box 86 github: https://github.com/ptitSeb/box86/issues/193

**Comment by joaojcorreia** [comment]
@Itai-Nelken thank you for your quick reply. Hopefully this gets sorted out soon. With children having to connect to zoom for school, being able to do so in an 100€ setup is a game changer.

**Comment by gopalakrishnapuvvada** [comment]
Respected 

> I've installed pi-apps in my daughters Raspberry pi 400, and successfully installed Zoom. Everything works fine, we are able to connect to meeting, the video works fine, there is a little lag, but nothing that wouldn't make impossible to use. The only exception is the input sound. The Rapsberry pi 400 has no sound jack, so we are using a USB camera with integrated mic. The mic works fine elsewhere, both in a mic test within Raspberry pi 400, and on a PC, but on Zoom it doesn't work properly. For the initial seconds it works fine, but after that it only really registers loud sounds and even those not properly. For example if one claps, the other side will only hear light "tick tick". I've also tried with a bluetooth head set and it is the same thing. Am I missing installing something? Thank you for your help.

Respected sir 
I also faced issues about microphone in zoom app. I think you fixed the problem . So please tell me how to fix the problem. I am waiting for your response

**Comment by joaojcorreia** [comment]
I didn't manage to solve it. I resorted to using the web version of Zoom, it worked well enough for my daughter to attend classes. Occasionally the system will disable the microphone, and you have to go to alsamixer to manually increase the input volume.

**Comment by FullSoundBox** [comment]
I've installed Zoom on Raspberry Pi OS 64 bits, Bullseye release and with a Box64 compilaton and PiApps installation, my microphone is working. I'm using a generic 1080p camera, Logitech H390 headphones and a Raspberry Pi 4B of 4GB.
