### ISSUE TITLE
SDR apps?

### ISSUE THREAD

**Issue by LucidEye** [Botspot/pi-apps#358]
It would be really useful to a lot of people in the SDR community if we could have an easier way to run Software Defined Radio apps that normally only run in Windoze.

Specifically... 
SDR# (SDR Sharp)
Linrad (linux version does not build correctly on latest RPiOS for Rpi4... would be nice to run the Windoze version on the Pi)
PowerSDR (windoze only app)

Can this app run on RPi? If so, please provide a link to a tutorial if applicable.  
Is this app something many GUI users would find useful?  
Is this app installable with `sudo apt install`?  

If you've created a zip file for this app, upload it here.

**Comment by Botspot** [comment]
Unfortunately, I don't have the time to lay down the groundwork for apps like this.

While such things like this would be *awesome*, I have no clue where to start, and would have to learn about SDR, basically from square one. (or from square zero, as I don't use Windows)

If you, or someone else, can get "SDR" working on RPi (on Raspberry Pi OS, that is), then I can consider adding it. But there's no way I could invest the time needed to sort out other people's problems for them in this manner. That would be superhuman, and I'm not there yet. ;)

One tip: there's a group of people who have gotten Windows running very well on Raspberry Pi! Using WoR (Windows on Raspberry), most EXEs work, albeit slowly under emulation. Maybe that's your best hope at getting something like this working on the Pi.
