### ISSUE TITLE
cannot uninstalled app

### ISSUE THREAD

**Issue by TheGipset** [Botspot/pi-apps#359]
These packages will be purged: 
All packages were purged succesfully.
/home/pi/pi-apps/purge-installed: line 66: gio: command not found

Failed to uninstall Mission Planner!

**Comment by Itai-Nelken** [comment]
on what OS are you?

**Comment by TheGipset** [comment]
> on what OS are you?

Raspbian

**Comment by Itai-Nelken** [comment]
Raspbian or RaspberryPiOS?

**Comment by TheGipset** [comment]
.

> Raspbian or RaspberryPiOS?

RaspberryPiOS buster

**Comment by Itai-Nelken** [comment]
try this:
open terminal and type: `touch test` this will create a file called test.
now type: `gio trash test` this will try to move test to trash.
send the full output.

**Comment by TheGipset** [comment]
> try this:
> open terminal and type: `touch test` this will create a file called test.
> now type: `gio trash test` this will try to move test to trash.
> send the full output.

bash: gio: command not found

**Comment by Itai-Nelken** [comment]
that is very weird, the gio command should work in RPiOS.
btw you can delete the test file: `rm test`

**Comment by TheGipset** [comment]
> that is very weird, the gio command should work in RPiOS.
> btw you can delete the test file: `rm test`
i dont know what should i do now
this thing is very weird

**Comment by Itai-Nelken** [comment]
@TheGipset wait for @Botspot or someone else that knows how to fix it.

**Comment by TheGipset** [comment]
> @TheGipset wait for @Botspot or someone else that knows how to fix it.

Okay

**Comment by pi-dev500** [comment]
Try  ```sudo apt install --reinstall gvfs```

**Comment by TheGipset** [comment]
> Try `sudo apt install --reinstall gvfs`

Still doesnt work

**Comment by Botspot** [comment]
According to the apt package file finder:
```
dpkg -S /usr/bin/gio
```
It determined that the `libglib2.0-bin` package is responaible for installing the `gio` command.

@TheGipset Please install `libglib2.0-bin` and try that `gio trash test` thing again.

And thank you @pi-dev500 for helping this guy while I was asleep. :)

**Comment by TheGipset** [comment]
> According to the apt package file finder:
> 
> ```
> dpkg -S /usr/bin/gio
> ```
> 
> It determined that the `libglib2.0-bin` package is responaible for installing the `gio` command.
> 
> @TheGipset Please install `libglib2.0-bin` and try that `gio trash test` thing again.
> 
> And thank you @pi-dev500 for helping this guy while I was asleep. :)

That work perfectly. Thank you!

**Comment by Botspot** [comment]
Excellent! My guess is that you accidentally removed that package. Good to know it works for you now.
