### ISSUE TITLE
Steam

### ISSUE THREAD

**Issue by SwiftSki** [Botspot/pi-apps#36]
Please add steam support

**Comment by Crazily** [comment]
I know this is a lot to ask especially because you need to jump through hoops to install box86 **Especially on a 64 bit OS** but I really would love to see this be as easy as all the other apps. Thank you.

**Comment by Botspot** [comment]
Yes, we've been discussing it.

So far, nobody's figured out yet why it fails to work at all on Raspbian. I have no idea what's causing the issue, but I haven't forgotten about this!

**Comment by mobilegmYT** [comment]
So far, the only place I have seen is TwisterOS but the wizards on the dev team are quite secretive...

**Comment by Botspot** [comment]
Thanks to ptitseb, I just got steam working!

It shouldn't be long before it's in Pi-Apps.

**Comment by Botspot** [comment]
Okay, who volunteers to try it?  
Extract the below zip file to `~/pi-apps/apps`.  
[Steam.zip](https://github.com/Botspot/pi-apps/files/5592791/Steam.zip)

**Comment by robloxboy24** [comment]
> Okay, who volunteers to try it?
> Extract the below zip file to `~/pi-apps/apps` and then it will appear in the app list.
> [Steam.zip](https://github.com/Botspot/pi-apps/files/5593060/Steam.zip)

I will do it later today! I hope it works!

**Comment by Botspot** [comment]
I've added Steam to Pi-Apps as of now. Commit 7c54fb875dacf9bc720db120e2584305bd420b9b
