### ISSUE TITLE
Add forge and fabric support to MineCraft

### ISSUE THREAD

**Issue by ScorpioStorm** [Botspot/pi-apps#363]
You can java- jar (file name) and install it, then navigate to the mods folder, add the mods, and then do it, I mean, it is not that hard, but most people don't know how to do it, maybe at least create a tutorial or something idk

**Comment by mobilegmYT** [comment]
> You can java- jar (file name) and install it, then navigate to the mods folder, add the mods, and then do it, I mean, it is not that hard, but most people don't know how to do it, maybe at least create a tutorial or something idk

I guess I could add a small thing to the installer. Though, we are preparing for the move to atlauncher very very soon so I don't think it's needed.

**Comment by ItCameFr0mMars** [comment]
@ScorpioStorm What forge version and settings are you using? I can't get forge to work for me...

**Comment by mobilegmYT** [comment]
Join discord server and go to https://discord.com/channels/770629697909424159/770629878319022090/804433480774844416
