### ISSUE TITLE
nativefier whatsapp web (works, see last comment in #345)

### ISSUE THREAD

**Issue by Itai-Nelken** [Botspot/pi-apps#364]
https://github.com/Botspot/pi-apps/issues/345#issuecomment-779962185
[Whatsapp.zip](https://github.com/Botspot/pi-apps/files/5990669/Whatsapp.zip)

**Comment by Botspot** [comment]
The way I read your comment, it sounds like the user-agent setting is not working on RPi, but is working on your Mac. Is this a correct interpretation?

**Comment by Itai-Nelken** [comment]
> The way I read your comment, it sounds like the user-agent setting is not working on RPi, but is working on your Mac. Is this a correct interpretation?

aort of, I think the user agent option isn't working at all, but I don't know if its only on the pi.
I mean that packaging the app on the pi makes it not work (it complains it needs a newer chrome version)
but packaging it **for the pi** on my mac and running it on the pi it does work.

I find that weird because using the option to use a different user agent I tried to use the user agent from chrome on my mac and it didn't work.

simplified:
packaging on the pi **for** the pi = doesn't work
packaging on the mac **for the pi** = it does work (on the pi).

**Comment by Botspot** [comment]
```
#for backwards compatibility with the chromium version
rm -rf ~/WhatsappWeb > /dev/null/

rm -rf ~/WhatsAppWeb
```
The above code confuses me. Also you use `/dev/null`, not `/dev/null/`.

**Comment by Itai-Nelken** [comment]
I messed up the dev/null, it should be `rm -rf ~/WhatsappWeb` that works and doesn't output any errors even if the folder doesn't exist.

**Comment by Botspot** [comment]
> I messed up the dev/null, it should be `rm -rf ~/WhatsappWeb` that works and doesn't output any errors even if the folder doesn't exist.

Why do you have two rm commands then? Why is one "for backwards compatibility"?

**Comment by Itai-Nelken** [comment]
because the chromium version folder was named "**W**hatsapp**W**eb" and the nativefier one is called "**W**hats**A**pp**W**eb"

**Comment by Botspot** [comment]
> because the chromium version folder was named "**W**hatsapp**W**eb" and the nativefier one is called "**W**hats**A**pp**W**eb"

Wow I didn't even see that!  
After I fix the `/dev/null` thing, is this ready to be pushed to the repo?

**Comment by Itai-Nelken** [comment]
yes.

**Comment by Botspot** [comment]
Whoa cool. Apparently mentioning an open issue in a commit, will close the issue, and automatically mention the commit ID!

**Comment by Itai-Nelken** [comment]
neat!
