### ISSUE TITLE
wine installer continues before wineboot finishes

### ISSUE THREAD

**Issue by Itai-Nelken** [Botspot/pi-apps#366]
I have no idea how to fix this, but the install script continues to the 2nd wineboot (`wine wineboot -u`) before it finishes installing the wine mono and gecko.

**Comment by Botspot** [comment]
What was the second wineboot for? (Would removing it solve the problem?)

**Comment by Itai-Nelken** [comment]
the 2nd wineboot is there to fix a problem that sometimes causes wine to not detect its "C drive" and that makes apps no install and run correctly.
I don't think removing it will solve the problem, its probably the first wineboot exiting but still running (if that makes sense). I have seen wine exit in terminal while still running actually.
maybe make a yad pop-up window asking the user to press continue when wine exits.

**Comment by Itai-Nelken** [comment]
someone else had this problem: https://discord.com/channels/770629697909424159/770629697909424162/812538263054843904
the same person also had the 'adobeair corrupt' winetricks error: https://discord.com/channels/770629697909424159/770629697909424162/812585776256385104

**Comment by Itai-Nelken** [comment]
the last commit fixed this issue.

**Comment by Botspot** [comment]
Closing the issue, as this problem has been fixed.
