### ISSUE TITLE
Cura 404 error (again)

### ISSUE THREAD

**Issue by chunky-milk** [Botspot/pi-apps#368]
Cura fails to download with a 404 error. It seems the link may have changed... again?
@Botspot

**Comment by Botspot** [comment]
The Cura dev doesn't leave older releases up for long.  
It's a big game of cat and mouse. Thanks for reporting - I hadn't noticed it yet.

Fixed with commit 8763c8596cac64361808aacca0897021a008f0c9.

**Comment by Itai-Nelken** [comment]
@Botspot why not use something similar to this: https://github.com/Botspot/pi-apps/pull/369#issuecomment-780624939 if the download fails? that way every time a new release you can bump the version and trigger a update for everyone that has it installed, but until you change the download, people will still be able to install cura.

**Comment by Botspot** [comment]
> @Botspot why not use something similar to this: [#369 (comment)](https://github.com/Botspot/pi-apps/pull/369#issuecomment-780624939) if the download fails? that way every time a new release you can bump the version and trigger a update for everyone that has it installed, but until you change the download, people will still be able to install cura.

While such a move would both reduce our workload and improve reliability, it comes at a great expense:  
Updates.

During an update, Pi-Apps will reinstall an app, only if its install script is modified. So if the Cura app's install script never needed changing, then everyone who installed Cura prior to the update, will never receive another update again.

BTW I've asked Cura's developer to help prevent this from happening again. https://github.com/smartavionics/Cura/issues/95

**Comment by Itai-Nelken** [comment]
that is why I said to run that download latest release code **only** if the main download fails, that way cura is downloaded from the link that gets updated every new release so people get the cura updates.
but **if the download fails**, run the get latest release code so the installation doesn't fail even if the old release is deleted.
