### ISSUE TITLE
Pls add code blocks to Pi apps

### ISSUE THREAD

**Issue by CoderLogy** [Botspot/pi-apps#372]
Pls add Code::Blocks to Pi apps

**Comment by chunky-milk** [comment]
> Pls add Code::Blocks to Pi apps

@CoderLogy i see that there are 32 and 64bit linux binaries [here](https://www.codeblocks.org/downloads/binaries/), but have you found any ARM binaries?

**Comment by Botspot** [comment]
Would this work?
```
sudo apt-get install codeblocks
```

**Comment by CoderLogy** [comment]
Doesn't work when coding Arduino I tried to code Arduino it shows me to
tell where is gnu gcc age compiler and I have downloaded it using sudo but
can't tell where it's is so a wget thing or GitHub thing Pi apps to do to
install is better pls add to Pi apps

**Comment by Botspot** [comment]
> Doesn't work when coding Arduino I tried to code Arduino it shows me to tell where is gnu gcc age compiler and I have downloaded it using sudo but can't tell where it's is so a wget thing or GitHub thing Pi apps to do to install is better pls add to Pi apps

Why are you trying to code Arduino using a non-conventional IDE? What's wrong with Arduino IDE?

**Comment by CoderLogy** [comment]
Code blocks is ide which supports better version of Arduino and it really
is it does auto complete have supported to make other projects than rather
coding Arduino but it's there always mess when you code it for Arduino soni
wanted you to fix  this mess when using sudo apt install or add new version
of code blocks to Pi apps so easy installation as new installation I think
fixed up mess pls add it

**Comment by Botspot** [comment]
I'm closing this issue because codeblocks is already is already on `apt`, and therefore, "too easy" to install compared to other things like Steam.

But, if someone wants it to be Arduino-compatible, and they want the **pi-app added badly enough to put the work in**, I'd probably add it once somebody got it working first.
