### ISSUE TITLE
updater not working, saying that installer-32 could not be found or does not exist

### ISSUE THREAD

**Issue by aidanrfraser** [Botspot/pi-apps#375]
after running sudo apt-get autoremove on my system, i'm running into an issue where nothing is updating (and discord is not installing) due to "installer-32 could not be found or does not exist". I have tried uninstalling and reinstalling pi-apps and that did not fix the problem.

**Comment by aidanrfraser** [comment]
update-reinstalling did fix

**Comment by Botspot** [comment]
I'm not familiar with the "installer-32 could not be found or does not exist" error.

Could you reply back with the full error you saw? (hint: to copy from a terminal, use Ctrl+**Shift**+C)

**Comment by aidanrfraser** [comment]
> I'm not familiar with the "installer-32 could not be found or does not exist" error.
> 
> Could you reply back with the full error you saw? (hint: to copy from a terminal, use Ctrl+**Shift**+C)

i absolutely would but i seem to have eliminated the issue entirely. let me try to explain it better.
Upon trying to update apps, each apps update would end in a failure that stated `~/pi-apps/apps/<app-name>/install-32` did not exist or could not be found. I can only assume this was because running `sudo apt-get autoremove` deleted it. upon reinstalling i can go into each app's folder and locate the install-32 file. I was not smart enough to try and see if they were there before reinstalling. i believe autoremove decided that the install-32 files were unnecessary and simply removed them.

**Comment by Botspot** [comment]
Maybe if I saw the error _in context_, I would understand what really happened.

I can't imagine `apt autoremove` having anything to do with it, but can't think of anything else that would systematically delete your files either.

Let me know if it happens again.

**Comment by Itai-Nelken** [comment]
@aidanrfraser apt **can't** remove pi-apps files.
apt can only remove whatever it installs, and it doesn't install pi-apps.
