### ISSUE TITLE
Failed to load steamui.so - dlerror(): Cannot dlopen("steamui.so"/0x6524a538, 2).

### ISSUE THREAD

**Issue by heavygabriel** [Botspot/pi-apps#383]
So I can't open steam because of the error "Failed to load steamui.so - dlerror(): Cannot dlopen("steamui.so"/0x6524a538, 2)".

I also used a fair bit of workarounds to launch steam and maybe that could be because of that?
I recorded the steps that I did, here is the file: https://drive.google.com/file/d/12NfHuCAaJI7wD_UBzKkFcbgws0fhGE0s/view?usp=sharing

This happens on a "clean" (I just installed thunar, chromium, git, build-essentials and xfce4) Raspberry Pi OS and I have not yet found a way to resolve this issue.

**Comment by Botspot** [comment]
Could you try reinstalling box86 and then reinstalling steam?

With recent improvements in box86, Steam seems more stable.

**Comment by heavygabriel** [comment]
Tried reinstalling and reinstalling box86 and steam, nothing has changed (no new errors, no new things in the console's output, etc.)

**Comment by heavygabriel** [comment]
Nevermind, found the issue.

It looks like `systemd-binfmt` doesn't get restarted when box86 gets installed (required for box86 to work).

A restart should fix the issue, but that's precisely why I couldn't solve it: I didn't reboot to confirm my findings.

#481 should fix this.
