### ISSUE TITLE
Run installation actions with `nice`

### ISSUE THREAD

**Issue by dimag0g** [Botspot/pi-apps#384]
Currently, when Pi-apps is installing an application, the whole system becomes sluggish. It would be better if time-consuming actions such as installation scripts or `sudo apt` calls were executed with `nice`, to keep the system responsive even when the installation is ongoing. On the contrary, calls to the interface functions such as `yad` should still run with default priority, to ensure the user interface remains responsive.

**Comment by Itai-Nelken** [comment]
you are probably using a slow sd/usb/ssd, I never had any problem with the system being slugish when installing apps from pi-apps, but I had similar sluggishness problems when running apt commands, downloading and extracting files, moving files etc. on slow sd cards.

**Comment by Botspot** [comment]
As Itai mentioned, such operations like `sudo apt update` will only slow down your Pi if the SD Card is sub-par.

But, I'd like to ask you, @dimag0g, how hard do you think this would be to implement? Are you hoping for *all* disk-heavy commands to be run `nice`ly? Or just apt ones?

**Comment by dimag0g** [comment]
I would test just running install/uninstall scripts with `nice` for a start.

**Comment by Botspot** [comment]
> I don't think it makes much sense for you to test this if your system is not affected.

Exactly.

> I would just test how running the entire install/uninstall scripts with `nice` changes things for a start. If I get my hands on the code and the performance will improve, I'll ping you with a PR.

I'm not familiar with how `nice` works, but I'd imagine that adding it to pi-apps's `manage` script would be the best approach.  

Try this: Change line 134 of `manage` from this:
```
  if "$installscript" ; then
```
To this:
```
  if "nice $installscript" ; then
```
Let me know how it goes.

**Comment by Botspot** [comment]
Closing this issue now. Will re-open it if @dimag0g replies back.

**Comment by dimag0g** [comment]
@Botspot Thanks for the hint. I added `nice` in front of install/uninstall scripts in `manage`, and IMO it's an improvement. My system stays more responsive during installs/uninstalls now. It's up to you if you want to put this change upstream.

**Comment by dimag0g** [comment]
@Botspot Are you keeping this open because you work on the topic, or do you wait for me to do something (like a pull request)?

**Comment by Botspot** [comment]
> @Botspot Are you keeping this open because you work on the topic, or do you wait for me to do something (like a pull request)?

No, I plan to implement it, and didn't want the issue to disappear in the lake of closed issues. Hopefully that makes sense.

**Comment by Botspot** [comment]
There, finished. Commit c04cf9174675f3041e761c9e663ca677aea3dcf5
