### ISSUE TITLE
Non-Debian OSs (Arch Linux, OpenSUSE, Fedora)

### ISSUE THREAD

**Issue by slashtechno** [Botspot/pi-apps#388]
Is it possible to make Pi-Apps work on other OSs that are not based on Debian?

**Comment by Botspot** [comment]
No, but technically yes.

Pi-Apps's user interface could probably run on almost anything. But the apps would be an entirely different story.

If your favorite OS is not debian-based, you are more than welcome to test each app and propose fixes for those that don't. But, for me, I don't have time to try out Pi-Apps on every OS conceivable.

It's hard enough to keep it going on RPiOS and TwisterOS.

**Comment by slashtechno** [comment]
> I don't have time to try out Pi-Apps on every OS conceivable.
> 
> It's hard enough to keep it going on RPiOS and TwisterOS.

Just like for ARM64 Pi-Apps accepts `install-32` and `install-64` separately, can Pi-Apps start accepting `archinstall`?  That way **people who find a way to install a useful app** on another distro can submit an app request. That way no one needs to convert **every** app.

**Comment by Botspot** [comment]
> > I don't have time to try out Pi-Apps on every OS conceivable.
> > It's hard enough to keep it going on RPiOS and TwisterOS.
> 
> Just like for ARM64 Pi-Apps accepts `install-32` and `install-64` separately, can Pi-Apps start accepting `archinstall`? That way **people who find a way to install a useful app** on another distro can submit an app request. That way no one needs to convert **every** app.

I'm afraid such a feature would take more effort than it's worth.

If you are brave enough to try arch, then you are probably good enough at a terminal to install your apps manually. (And not likely a noob user. Pi-Apps targets noob users)

**Comment by slashtechno** [comment]
Thank you for considering it @Botspot.
