### ISSUE TITLE
Unity3D game engine on RPi

### ISSUE THREAD

**Issue by Bonekiller99** [Botspot/pi-apps#389]
Can this app run on RPi? If so, please provide a link to a tutorial if applicable.  
I've tried getting unity on Ubuntu, it didn't work. I tried it on Raspberry Pi OS through Wine and also FlatHub. My next attempt would be to get Windows 10. Is there a way it can be added to Pi-Apps?

**Comment by Itai-Nelken** [comment]
pi-apps isn't magic, only apps that already run on the pi can be added.
if you know of a way to add it (which you don't according to your question) then you can make the scripts or say how to install it.

again pi-apps isn't magic, all the apps on pi-apps already run on the pi and pi-apps only has some bash scripts that run the commands to download and install them.

**Comment by Botspot** [comment]
Well said, @Itai-Nelken.

@Bonekiller99, if you find a way to get Unity3D running on the Pi (Specifically, running on Raspberry Pi OS), let us know. Until then, I've closed this issue.
