### ISSUE TITLE
Snap with Box86

### ISSUE THREAD

**Issue by slashtechno** [Botspot/pi-apps#390]
If it is possible to run [Snap](https://snapcraft.io) with Box86? That would allow for a ton of apps. This includes [Brave](https://snapcraft.io/install/brave/debian), [Spotify](https://snapcraft.io/spotify) and many more apps. 

Is this possible?

**Comment by Itai-Nelken** [comment]
snap is already in pi-apps, and it natively works with arm.
on pi-apps is comes with the snap store.

**Comment by techcoder20** [comment]
> If it is possible to run [Snap](https://snapcraft.io) with Box86? That would allow for a ton of apps. This includes [Brave](https://snapcraft.io/install/brave/debian), [Spotify](https://snapcraft.io/spotify) and many more apps.
> 
> Is this possible?

I was unable to get brave working with box86 so don't really think it will work when using snap

**Comment by Itai-Nelken** [comment]
even if brave or spotify did work with box86, performance would probably be terrible.

**Comment by slashtechno** [comment]
Okay.
