### ISSUE TITLE
Problems with running pi-apps on RPI 3B v1.2

### ISSUE THREAD

**Issue by IlFANGlI** [Botspot/pi-apps#391]
Im getting the error "/usr/local/bin/pi-apps: line 2: /home/pi/pi-apps/gui: No such file or directory" when I run pi-apps in terminal. I do have iRaspbian installed(custom skin for Raspbian)
![Screenshot_2021-02-24_18-08-33](https://user-images.githubusercontent.com/73181796/109083335-5a476880-76cb-11eb-81e1-9b59b7d24edd.png)
, so maybe that's an issue?

**Comment by slashtechno** [comment]
I think reinstalling should help...

**Comment by IlFANGlI** [comment]
@slashtechno Nope, flat out won't let me install the program. Maybe it's an issue with iRaspbian, because I could install it fine on regular Raspbian.

**Comment by IlFANGlI** [comment]
Nevermind, thanks @slashtechno for the help. Got it working with a manual install!
![Screenshot_2021-02-25_20-02-34](https://user-images.githubusercontent.com/73181796/109239953-8256ca80-77a4-11eb-9755-782e507b7b2b.png)

**Comment by slashtechno** [comment]
@IlFANGlI You're welcome. Have a good day or night (depending on where you live).

**Comment by Botspot** [comment]
> Nevermind, thanks @slashtechno for the help. Got it working with a manual install!

Did you determine what the problem was?

**Comment by IlFANGlI** [comment]
> > Nevermind, thanks @slashtechno for the help. Got it working with a manual install!
> 
> Did you determine what the problem was?

No, I thought it was an issue with permissions, but I ran sudo su (superuser command) and then ran it but still didn't work. Im gonna work it out.

**Comment by Botspot** [comment]
My guess is that the automated install script failed to download the repo.
