### ISSUE TITLE
Wine returning Syntax Error

### ISSUE THREAD

**Issue by slashtechno** [Botspot/pi-apps#393]
When I try to run Wine I get this error:
`/home/pi/wine/bin/wine: 1: /home/pi/wine/bin/wine: Syntax error: "(" unexpected
`

**Comment by Botspot** [comment]
Try running `cat /usr/local/bin/wine`  
And `shasum /home/pi/wine/bin/wine`

**Comment by slashtechno** [comment]
@Botspot I did not do anything but it seems to be working now. Interesting...
