### ISSUE TITLE
Google Drive

### ISSUE THREAD

**Issue by slashtechno** [Botspot/pi-apps#396]
I found a tutorial to mount Google Drive to Raspberry Pi. The tutorial is [here](https://www.raspberrypi.org/forums/viewtopic.php?p=801697). I believe this would be helpful to people who are coming from Windows and used to have Drive mounted.

**Comment by fabianmendes** [comment]
May you please try to make an Install script?
See: Pi-apps' Tool for app creation

**Comment by slashtechno** [comment]
Okay. I should be done with the script by Monday

**Comment by Botspot** [comment]
As-is, beginners will find it quite difficult to use rclone effectively.  
This isn't a self-contained GUI application. Instead, it's an expansive terminal command that requires learning.

We have two options:
- Make a GUI app. I've considered doing it for years, but it's still on the to-do list.
- Make an [incredibly detailed](https://www.raspberrypi.org/forums/viewtopic.php?p=1594806#p1594806) `description` file that covers everything a beginner could want to do.

**Comment by slashtechno** [comment]
I was having a hard time finding any tutorial that **does not** need to you to go into Google Developer Console and get an API token. I could not really figure our rclone either. What if we use Wine with Box86 to run something?

**Comment by Botspot** [comment]
> I was having a hard time finding any tutorial that **does not** need to you to go into Google Developer Console and get an API token. I could not really figure our rclone either. What if we use Wine with Box86 to run something?

Huh? For me, rclone has always worked fine when using its automated setup tool.
```
rclone config
```
During the authentication step, rclone will take you to a web browser for you to sign into Google. It's that easy.

**Comment by slashtechno** [comment]
@Botspot I was following a tutorial that made it over-complicated I think. Anyway I found [this](https://github.com/thejinx0r/DriveFS) project that allows you to mount Google Drive

**Comment by srini-pro** [comment]
"Installing google-drive-ocamlfuse on Ubuntu or Linux Mint, you can use its official PPA as follows." ,might say  but that usually x86

**Comment by slashtechno** [comment]
> > I was having a hard time finding any tutorial that **does not** need to you to go into Google Developer Console and get an API token. I could not really figure our rclone either. What if we use Wine with Box86 to run something?
> 
> Huh? For me, rclone has always worked fine when using its automated setup tool.
> 
> ```
> rclone config
> ```
> 
> During the authentication step, rclone will take you to a web browser for you to sign into Google. It's that easy.

I was following [this](https://medium.com/@artur.klauser/mounting-google-drive-on-raspberry-pi-f5002c7095c2) tutorial and it claimed that
 `This means that by using the rclone default client_id you’re competing against all other users of rclone, globally, for operation bandwidth to Google Drive.`

**Comment by slashtechno** [comment]
I have made a repository with a detailed tutorial for setting up rclone and a script that makes it run in the background at boot.
You can find it [here](https://github.com/slashtechno/gdriveMounter)

**Comment by open-sorcerer64** [comment]
@Botspot, Please close this issue as it is fixed by **CloudBuddy**
