### ISSUE TITLE
Discord Screensharing

### ISSUE THREAD

**Issue by slashtechno** [Botspot/pi-apps#398]
Discord screen sharing does not work for some reason.

**Comment by Itai-Nelken** [comment]
thats a known issue, and it was fixed (see https://github.com/SpacingBat3/electron-discord-webapp/issues/12) it will be added to pi-apps when my pr (#361) is approved and merged.

**Comment by slashtechno** [comment]
Oh okay, sorry I did not know that was a known issue.

**Comment by SpacingBat3** [comment]
> Discord screen sharing does not work for some reason.

...because I forgot to enable it in the production builds. But I'm going right now to release `v1.1.1` patch that will fix that.

**Comment by Botspot** [comment]
May this issue be closed?

**Comment by slashtechno** [comment]
Did the most recent commit fix it?

**Comment by Itai-Nelken** [comment]
> Did the most recent commit fix it?

yes.
