### ISSUE TITLE
update freetube 0.11.2 --> 0.11.3

### ISSUE THREAD

**Issue by Itai-Nelken** [Botspot/pi-apps#403]
**armhf:** https://archive.org/download/freetube_0.11.2_armv7l/freetube_0.11.3_armv7l.deb
**arm64:** https://github.com/FreeTubeApp/FreeTube/releases/download/v0.11.3-beta/freetube_0.11.3_arm64.deb

I don't wan't to open a pr right now because my fork is sort of messed up, once the edex-ui pr's are merged/closed I will be able to delete it.

**Comment by Botspot** [comment]
> I don't wan't to open a pr right now because my fork is sort of messed up, once the edex-ui pr's are merged/closed I will be able to delete it.

zip.

**Comment by Itai-Nelken** [comment]
nvm, I already did this, forgot. sorry.
