### ISSUE TITLE
Discord Notificiations 

### ISSUE THREAD

**Issue by slashtechno** [Botspot/pi-apps#404]
Sorry if this is a duplicate issue but does Discord have push notifications?

**Comment by Botspot** [comment]
The panel indicator will display a red dot if you have unread messages.

In the future, consider opening an issue on the [Discord app's repository](https://github.com/SpacingBat3/electron-discord-webapp) instead.

**Comment by slashtechno** [comment]
@Botspot Oh sorry. Thank you for telling me though.

**Comment by Botspot** [comment]
> @Botspot Oh sorry. Thank you for telling me though.

You're fine. I told you that for your own good, as you are more likely to get an accurate answer from there than from here. (Maybe @spacingbat3's Discord actually does push notifications, and I just accidentally misinformed you!)
