### ISSUE TITLE
Blank terminal

### ISSUE THREAD

**Issue by kcat36** [Botspot/pi-apps#41]
Pi apps was installed but i cant install anything from it, when i click install on an app the terminal shows up but is just blank and nothing happens. Im on raspberry pi Os and on a Pi3b.

**Comment by Botspot** [comment]
Recently I have redone the installation process by adding multiple `install` scripts whose names change depending on which app you're installing.
Exactly what app were you trying to install?

**Comment by Botspot** [comment]
Okay, I believe I found the problem - a bug in `manage update` that wouldn't update an app even if the filenames have been changed from `install` to `install-32`.  
Now that that's fixed, it should work flawlessly now.

@kcat36 , could you confirm that it's working for you now?

**Comment by kcat36** [comment]
Its working now it seems

**Comment by Botspot** [comment]
Good! Thank you.
