### ISSUE TITLE
This wine shortcut creation line might need fixing, but I haven't actually tested it 

### ISSUE THREAD

**Issue by WheezyE** [Botspot/pi-apps#410]
https://github.com/Botspot/pi-apps/blob/4a48ba62b157420c6e33666e7d050ee3ce21ab0b/apps/Wine%20(x86)/install-32#L165

Hey! I was just making a draft of a wine installation readme for the box86 github page.  I noticed this line I think makes an extra " mark and no `"$@"`

The script that's created should be this I think:
```
#!/bin/bash
setarch linux32 -L /home/pi/wine/bin/wine "$@"
```
source: https://discord.com/channels/670543161525010442/736736690932285481/793373458096324629

I might propose these commands
```
# Install wine (move wine folder into place, make launcher, & make symlinks. Credits: grayduck, Botspot)
sudo mv wine-installer/opt/wine-devel ~/wine
echo -e '#!/bin/bash\nsetarch linux32 -L $HOME/wine/bin/wine "$@"' | sudo tee -a /usr/local/bin/wine >/dev/null # Silently create a script in /usr/local/bin to launch wine programs as 32bit only
sudo ln -s ~/wine/bin/wineserver /usr/local/bin/wineserver
sudo ln -s ~/wine/bin/wineboot /usr/local/bin/wineboot
sudo ln -s ~/wine/bin/winecfg /usr/local/bin/winecfg
sudo chmod +x /usr/local/bin/wine /usr/local/bin/wineboot /usr/local/bin/wineserver /usr/local/bin/winecfg
rm -rf wine-installer # clean up
```

I'm kind of new to linux though and wanted to run it by you

**Comment by Botspot** [comment]
Excellent question.

Yes, the script generated by that echo command should be this:
```
#!/bin/bash
setarch linux32 -L /home/pi/wine/bin/wine "$@"
```
Now, notice something. The above script should contain literal double-quotes and a literal shell variable. (`"$@"`) Okay.  
But in the same script creation, it *is* supposed to expand a shell variable. (`$HOME/wine/bin/wine`)

So in one command, we have to tell the script that "this variable should be expanded, but this other one next to it should not.

To do that, we use single-quotes (`'`) to keep shell variables literal, and double-quotes (`"`) to expand the variable. As you can see below, my script-creation `echo` command makes use of both, one portion is using double-quotes, but the other portion uses single-quotes.
```
echo "#!/bin/bash
setarch linux32 -L $HOME/wine/bin/wine"' "$@"' | sudo tee /usr/local/bin/wine >/dev/null
# --------double-quotes---------------|single|
```
Bash programming is _awesome_.

**Comment by Botspot** [comment]
Thanks for asking, by the way.
