### ISSUE TITLE
Scrcpy

### ISSUE THREAD

**Issue by Dell-Glitch** [Botspot/pi-apps#413]
1.17 doesn't work

**Comment by Botspot** [comment]
> 1.17 doesn't work

What failed?

Did it install okay? Did it launch okay? Something else?

**Comment by Dell-Glitch** [comment]
it installed ok but couldn't execute right it wasn't because of sudo it's
was a missing file or some sort it just couldn't launched

**Comment by Botspot** [comment]
I figured it out. For some reason, the new version's tar.gz archive does not contain as many files as the version 1.13 archive.

Looks like we'll have to revert back to 1.13...

**Comment by Dell-Glitch** [comment]
ok
