### ISSUE TITLE
HexChat

### ISSUE THREAD

**Issue by Dell-Glitch** [Botspot/pi-apps#417]
I want you to add HexChat?
**32bit**- http://ftp.br.debian.org/debian/pool/main/h/hexchat/hexchat_2.14.2-4_armhf.deb
**64bit**- http://ftp.br.debian.org/debian/pool/main/h/hexchat/hexchat_2.14.2-4_arm64.deb

**Comment by Dell-Glitch** [comment]
![2021-03-04-220850_1280x1024_scrot](https://user-images.githubusercontent.com/73069007/110061838-3e307080-7d36-11eb-9b58-8e0ecab28796.png)

**Comment by techcoder20** [comment]
I was able to install it with apt so I dont think it can be added

**Comment by Dell-Glitch** [comment]
i know about the apt but still

**Comment by Dell-Glitch** [comment]
nvm

**Comment by Dell-Glitch** [comment]
well we can use apt to install hexchat, yes i know it's so simple you just
need to type **sudo apt-get install hexchat** but pi-apps use for
installing things with ease but typing sudo apt-get install hexchat is easy
too... idk were im going with this but still

**Comment by Botspot** [comment]
> well we can use apt to install hexchat, yes i know it's so simple you just need to type **sudo apt-get install hexchat** but pi-apps use for installing things with ease but typing sudo apt-get install hexchat is easy too... idk were im going with this but still

Exactly...

**Comment by Dell-Glitch** [comment]
ok

**Comment by Rak1ta** [comment]
@Botspot From what I understand, you are now adding applications from the package manager.
[HexChat.zip](https://github.com/Botspot/pi-apps/files/8784705/HexChat.zip)
