### ISSUE TITLE
Simplenote

### ISSUE THREAD

**Issue by Itai-Nelken** [Botspot/pi-apps#418]
[Simplenote.zip](https://github.com/Botspot/pi-apps/files/6090650/Simplenote.zip)
tested install-32 and uninstall scripts, havent tested install-64, but followed each step it does and I'm 99% sure it will work.

**Comment by Botspot** [comment]
How many people do you think would use this? I noticed it requires a login.

**Comment by Itai-Nelken** [comment]
>I noticed it requires a login.

its a free account, no extra payed services.
>How many people do you think would use this?

I don't know, but a few, its lighter than using the website in chromium though. I just made the install scripts for https://github.com/Botspot/pi-apps/issues/88 and made myself a account on the wasy to test if the app works correctly. I find it very useful as it runs well on all platforms: Windows. MacOS, and Linux (arm and x86).

**Comment by Botspot** [comment]
> > I noticed it requires a login.
> 
> its a free account, no extra payed services.
> 
> > How many people do you think would use this?
> 
> I don't know, but a few, its lighter than using the website in chromium though. I just made the install scripts for #88 and made myself a account on the wasy to test if the app works correctly. I find it very useful as it runs well on all platforms: Windows. MacOS, and Linux (arm and x86).

Okay. How does it compare to the other GTK-based note takers? Specifically nixnote2? (for Evernote)

**Comment by Itai-Nelken** [comment]
> > > I noticed it requires a login.
> > 
> > 
> > its a free account, no extra payed services.
> > > How many people do you think would use this?
> > 
> > 
> > I don't know, but a few, its lighter than using the website in chromium though. I just made the install scripts for #88 and made myself a account on the wasy to test if the app works correctly. I find it very useful as it runs well on all platforms: Windows. MacOS, and Linux (arm and x86).
> 
> Okay. How does it compare to the other GTK-based note takers? Specifically nixnote2? (for Evernote)

I don't know, I never used any other note taking app. but if they are GTK based they will probably be way faster and use less resources, simplenote is a electron app.

**Comment by Itai-Nelken** [comment]
nixnote2 looks like a very powerful app, but the fact that its unofficial (nothing wrong with that, but some people might not like that) and doesn't look very user friendly for less professional users makes me think simplenote should be added.

**Comment by Botspot** [comment]
@Itai-Nelken, I have two concerns about this:

1. There are many note-taking apps and websites. If one goes into Pi-Apps, others may follow suit and stage a takeover! :)
2. Out of all the note-taking apps, Simplenote may not be the best one, as it requires creating an account.

Now, neither of those above concerns are official or set in stone. But they are things we'll have to watch out for.

So, @Itai-Nelken, I'll give you the choice: Put Simplenote on Pi-Apps, or not? Whatever you decide, I'll go with it.

**Comment by Itai-Nelken** [comment]
@Botspot hard choice: your ponits are true, and simplenote isn't the best note taking app, but its the only one I know of that is cross platform (its available for Linux (x86 and arm), mac, android, os, and windows) and its decent.
but after all the app is just a electron app displaying their website.
so I don't know if its really worth adding to pi-apps.

do whatever you think is good, I say add it (but I'm biased because I use it).

**Comment by Botspot** [comment]
> but after all the app is just a electron app displaying their website.

Mmm good point. I guess in this case we could consider this app to be "too easy to install already", like an apt package.

**Comment by Botspot** [comment]
The simplenote.com website is equally good as the electron app? Are there any differences at all between the two?

**Comment by Itai-Nelken** [comment]
> The simplenote.com website is **equally good** as the electron app, right? Are there any differences at all between the two?

not that I'm aware of.
![image](https://i.imgur.com/e70yUK4.png)
