### ISSUE TITLE
Scrcpy

### ISSUE THREAD

**Issue by RaspberryRBX** [Botspot/pi-apps#42]
[Scrcpy.zip](https://github.com/Botspot/pi-apps/files/5461626/Scrcpy.zip)

**Comment by RaspberryRBX** [comment]
Icon Don't Work

**Comment by Botspot** [comment]
I'm going to have to ask  the PiKISS dev he's OK with his scripts being ripped straight out of PiKISS and being put into Pi-Apps.

**Comment by RaspberryRBX** [comment]
Ok

**Comment by RaspberryRBX** [comment]
@Botspot Ive Got Permission By PiKISS Dev

**Comment by RaspberryRBX** [comment]
https://i.imgur.com/GE8Uhbk.png

**Comment by RaspberryRBX** [comment]
[Scrcpy.zip](https://github.com/Botspot/pi-apps/files/5467626/Scrcpy.zip)
updated uninstalled

**Comment by Botspot** [comment]
Hey @RaspberryRBX , have you tried adding the icon in Create App using this button?  
![snapshot](https://user-images.githubusercontent.com/54716352/97760977-81ea4380-1ad2-11eb-9eb1-8e1c7c3e6318.png)

**Comment by RaspberryRBX** [comment]
Yes

**Comment by RaspberryRBX** [comment]
[Scrcpy.zip](https://github.com/Botspot/pi-apps/files/5469191/Scrcpy.zip)

**Comment by Botspot** [comment]
I have eited the `install` script to adhere to the Pi-Apps standards, and also removed nearly everything PiKISS-related like `helpers.sh`.

@RaspberryRBX , I don't have an Android device nearby to test it out, so could you test it for me? Thanks.
[Scrcpy.zip](https://github.com/Botspot/pi-apps/files/5469314/Scrcpy.zip)

**Comment by RaspberryRBX** [comment]
Ok

**Comment by RaspberryRBX** [comment]
Works

**Comment by Botspot** [comment]
> Works

Thanks. I've now added Scrcpy as of commit 0264b229b99a842f624e1887376add92f3d43ebd.

**Comment by RaspberryRBX** [comment]
Ok
