### ISSUE TITLE
Stunt Rally

### ISSUE THREAD

**Issue by Itai-Nelken** [Botspot/pi-apps#424]
[Stunt rally.zip](https://github.com/Botspot/pi-apps/files/6093675/Stunt.rally.zip)

**Comment by Itai-Nelken** [comment]
[Stunt rally.zip](https://github.com/Botspot/pi-apps/files/6093678/Stunt.rally.zip)
fixed a typo.

**Comment by techcoder20** [comment]
@Itai-Nelken you are installing the dependencies in install-64 but not in install-32. Also maybe add a warning that you need atleast 2gb free space

**Comment by Itai-Nelken** [comment]
[Stunt rally.zip](https://github.com/Botspot/pi-apps/files/6102253/Stunt.rally.zip)
here, I added the warning to the description and the dependencies are now installed for 32bit.
thanks @techcoder20

**Comment by Botspot** [comment]
@Itai-Nelken What you did here was brilliant! :)

```
#install dependencies
if ! command -v aria2c >/dev/null ; then
  sudo apt install aria2 -y
  ARIA2=1
fi

#rest of script

#clean up
if [[ "$ARIA2" == 1 ]]; then
  sudo apt purge -y aria2
fi
```

**Comment by Itai-Nelken** [comment]
> @Itai-Nelken What you did here was brilliant! :)

thanks!

**Comment by Botspot** [comment]
Okay I briefly tried Stunt Rally - it's laggy. Maybe 7 fps.

What do we do?

**Comment by Itai-Nelken** [comment]
@Botspot I think I added a note to the description on how to make it perform better, but here it is:
in the games options set the graphics to 'lowest' and the resolution to 800x600. then it performs pretty good adn is playable. I would say around 20fps.

**Comment by Itai-Nelken** [comment]
https://user-images.githubusercontent.com/70802936/110373610-58c95900-8058-11eb-832e-78b7024a8aa0.mp4

as you see in the screen recording its really smooth even while recording  (and my really bad game skills). I also show my settings.
thats running on a pi4 4gb no overclock.

**Comment by Itai-Nelken** [comment]
@Botspot I did add the note on how to improve performance to the description:
![description](https://i.imgur.com/44fAEzf.png)
and I fixed a typo: [Stunt rally.zip](https://github.com/Botspot/pi-apps/files/6103817/Stunt.rally.zip)

**Comment by Botspot** [comment]
The menu icons aren't working for me.

**Comment by Botspot** [comment]
> and I fixed a typo: [Stunt rally.zip](https://github.com/Botspot/pi-apps/files/6103817/Stunt.rally.zip)

To save me some time, did you fix a typo in the description? Or in one of the other files? (I've made major changes to the description, that's why)

**Comment by Botspot** [comment]
Also, I think we could automate the turning-down of settings by creating a custom config file.

It appears to be located at:
```
/home/pi/.config/stuntrally/game.cfg
```

**Comment by Botspot** [comment]
Here's my zip with a couple bug fixes and an improved description:
[Stunt Rally.zip](https://github.com/Botspot/pi-apps/files/6104082/Stunt.Rally.zip)

**Comment by Itai-Nelken** [comment]
> > and I fixed a typo: [Stunt rally.zip](https://github.com/Botspot/pi-apps/files/6103817/Stunt.rally.zip)
> 
> To save me some time, did you fix a typo in the description? Or in one of the other files? (I've made major changes to the description, that's why)

description only `retsart` instead of `restart`.

**Comment by Pythonic456** [comment]
I think this would be a good app to add. Upvote +1

**Comment by Botspot** [comment]
> but I'm pretty sure `~/.config/stuntrally` is created when running the game for the first time

I was thinking something like:
```
mkdir -p ~/.config/stuntrally
echo 'bla bla' > ~/.config/stuntrally/game.cfg
```

**Comment by Itai-Nelken** [comment]
ok ,I did that and it works! the game starts using the correct settings for best performance (but the install scripts are around 450 lines).
will make it later.

**Comment by Botspot** [comment]
> ok ,I did that and it works! the game starts using the correct settings for best performance (but the install scripts are around 450 lines).

Oh wow. Well if it's that long, then maybe it would be better if you uploaded the file to github gist and pulled it down with wget.

**Comment by Itai-Nelken** [comment]
> Oh wow. Well if it's that long, then maybe it would be better if you uploaded the file to github gist and pulled it down with wget.

is it that bad that the file is so long?

**Comment by Botspot** [comment]
> > Oh wow. Well if it's that long, then maybe it would be better if you uploaded the file to github gist and pulled it down with wget.
> 
> is it that bad that the script is so long?

Not necessarily. I was just mentioning an alternative, possibly cleaner but more complicated way of doing it.

**Comment by Itai-Nelken** [comment]
> Not at all. (See the zoom script! :) ) I was just mentioning an alternative, possibly cleaner but more complicated way of doing it, if you'd prefer to do it that way.

I prefer it this way, no need to download extra things that might arouse the suspicions of some and make the script fail if for some reason the gist is deleted or something happens to it.

I'll upload the zip later.

**Comment by Itai-Nelken** [comment]
[Stunt rally.zip](https://github.com/Botspot/pi-apps/files/6137560/Stunt.rally.zip)
here.

**Comment by Itai-Nelken** [comment]
I forgot to remove the performance part in the description, I'm going to replace it with something like this:
<b>
pi-apps automatically sets the game's settings for best performance, feel free to experiment and find the best settings for you.
</b>

**Comment by Botspot** [comment]
I changed the description beforehand, here it is:

> Racing game with rally style driving, mostly on gravel.
> WARNING: at least 2GB of free disk space is needed!
> 
> To improve performance, go into options in the games main menu>screen tab and set the graphics preset to lowest and the resolution to 800x600. Then restart the game.
> 
> Stunt Rally features a rich variety of 172 tracks in 34 sceneries also on other planets.
> Track difficulty ranges from short and easy, to very difficult stunt tracks including jumps, skewed loops, pipes winding in 3D, obstacles, or all of the above.
> Vehicle options: 20 cars, 1 motorbike, 3 hovering spaceships and 1 bouncing sphere.
> The latter provide a fast and easier gameplay on flat tracks.
> Game modes include:
> Single Race, Tutorials, Championships, Challenges, Multiplayer and Split Screen.
> Also Replays and Ghost drive are present.
> The Track Editor allows creating and modifying tracks. It uses a 3D spline generated road.
> 
> To run: Menu -> Games -> Stunt Rally
> To run in terminal: stuntrally
> 
> To run track editor: Menu -> Games -> Stunt Rally Track Editor
> To run in terminal: sr-editor

**Comment by Itai-Nelken** [comment]
[Stunt rally.zip](https://github.com/Botspot/pi-apps/files/6137599/Stunt.rally.zip)
oops, sorry, forgot to add your description. added it in this zip.

**Comment by Botspot** [comment]
Added. Commit 2a4c828ca0feaa13c0188de3d39e51fc872d254d
