### ISSUE TITLE
Mac OS Theme Uninstall Changes

### ISSUE THREAD

**Issue by slashtechno** [Botspot/pi-apps#425]
Could the uninstall for the Mac OS Theme please also remove the programs it added. For example it adds a volume controller, this makes it so normal users will not know whether to use the volume controller in the system tray, or the one it adds. Also Panther Launcher is added. As well as Lightpad, Compton and Plank. I think that the the uninstall script should either **uninstall all of these** or **ask the user if it should remove these**. Another option is adding a full uninstall button to Pi-Apps.

**EDIT: Did this just get updated? It did not uninstall before but now it does**

**Comment by Itai-Nelken** [comment]
the MacOS theme should uninstall all those packages.
[lines 40-42 of its uninstall script:](https://github.com/techcoder20/MacOSBigSurThemeConverter/blob/8a2ae4dc228ebaa22fdb28b3cc6bfaef387546d3/uninstall.sh#L40-L42)
```bash
#Removing Ulauncher, xfce4-panel-profiles, lightpad, and panther launcher
sudo apt -y purge ulauncher xfce4-panel-profiles xterm lightpad panther-launcher plank xfwm4 xfce4-settings nautilus xfce4-panel xfce4-appmenu-plugin xfce4-statusnotifier-plugin xfce4-pulseaudio-plugin blueman network-manager figlet lolcat pavucontrol compton 
sudo apt -y autoremove
```

**Comment by Botspot** [comment]
> **EDIT: Did this just get updated? It did not uninstall before but now it does**

Yes it did update, to fix your earlier issue. #419
