### ISSUE TITLE
Lightpad Uninstall not Working

### ISSUE THREAD

**Issue by slashtechno** [Botspot/pi-apps#431]
I tried to uninstall Lightpad but when I press control+space the search bar still shows up.

Also for the issue templates can bug be an option?

**Comment by Botspot** [comment]
> Also for the issue templates can bug be an option?

Good idea. Just did it with commit fea8f5e2e6f856d273216575f45a86708aa66e27.

> I tried to uninstall Lightpad but when I press control+space the search bar still shows up.

Let me try to replicate the issue.

**Comment by Botspot** [comment]
@slashtechno, what happens when you run this command?
```
sudo apt -y purge lightpad
```

**Comment by techcoder20** [comment]
@slashtechno I think you are talking about ulauncher

**Comment by slashtechno** [comment]
I think a reboot fixed it.
