### ISSUE TITLE
Installation Failure For AndroidBuddy

### ISSUE THREAD

**Issue by techtipsforteens** [Botspot/pi-apps#432]
Hi,

I was trying to install AndroidBuddy from Pi-Apps, and I got an error. It reads...
`Failed to run sudo apt update!
APT reported these errors:
W: GPG error: http://deb.debian.org/debian buster-backports InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 04EE7237B7D453EC NO_PUBKEY 648ACFD622F3D138
E: The repository 'http://deb.debian.org/debian buster-backports InRelease' is not signed.
`
Thanks

**Comment by Botspot** [comment]
Looks like your `apt` setup was messed up, prior to installing Androidbuddy.

Do you remember adding the `http://deb.debian.org/debian buster-backports` repository to your system?  
If not, then maybe another Pi-App did it. The `Minecraft Pi (Modded)` app does add the buster-backports repository.

**Comment by Botspot** [comment]
@techtipsforteens, were you able to troubleshoot?

Is there anything else you still need help with? If not, then this issue should be closed.

**Comment by techtipsforteens** [comment]
After reformatting my SD card, everything works fine. Thanks.
