### ISSUE TITLE
Terminal Fix For PyCharm

### ISSUE THREAD

**Issue by techcoder20** [Botspot/pi-apps#434]
The local terminal in pycharm does not work by default. Here is a modified install script of pycharm with a fix for that.

[install.zip](https://github.com/Botspot/pi-apps/files/6098615/install.zip)

**Comment by fabianmendes** [comment]
Just be aware with 32 and 64 bit target versions, mate!

**Comment by techcoder20** [comment]
Yes It was working for 64 bit without the fix but 32 bit does require the fix.

**Comment by fabianmendes** [comment]
Coool

**Comment by techcoder20** [comment]
Fixed with #461, Thx @Botspot :)
