### ISSUE TITLE
Done Installing

### ISSUE THREAD

**Issue by Dell-Glitch** [Botspot/pi-apps#436]
can you change the Closing in 30 secs to 10 secs?

**Comment by Itai-Nelken** [comment]
> can you change the Closing in 30 secs to 10 secs?

I'm pretty sure it already closes in 10seconds, and even if no, what is preventing you from manually closing the window? sometime that extra 20seconds are needed to copy output.

**Comment by Dell-Glitch** [comment]
i can still exited out

**Comment by Botspot** [comment]
> can you change the Closing in 30 secs to 10 secs?

No. Those 30 seconds are necessary to check for errors and to copy terminal output. Ten seconds was too short in the beginning.

You are more than welcome to close the terminal early, by pressing Enter, or Alt+F4, or by clicking the window-close button.

**Comment by Dell-Glitch** [comment]
Makes sense
