### ISSUE TITLE
Initial pi-apps installation does not work when running bash script from Downloads folder

### ISSUE THREAD

**Issue by ryanbarlow1** [Botspot/pi-apps#439]
### Steps to replicate issue:
Fresh instance of Raspberry Pi OS (32-bit, latest)
Logged in as default (pi) user
cd to Downloads folder
Try to install pi-apps via wget bash script

### Result:
Installation is messed up. The pi-apps.desktop and pi-apps-settings.desktop files both don't work.

### Solution:
Either the script needs to cd to the correct location, or the README needs to specify where this command should be run.

**Comment by Botspot** [comment]
Thank you. It should be fixed now.

**Comment by Botspot** [comment]
> Used install script, still had a issue:
> 
> ```
>  wget -qO- https://raw.githubusercontent.com/Botspot/pi-apps/master/install | bash
> Get:1 http://raspbian.raspberrypi.org/raspbian buster InRelease [15.0 kB]
> Hit:2 http://download.opensuse.org/repositories/home:/kozec/Debian_10  InRelease
> Hit:3 https://download.docker.com/linux/raspbian buster InRelease              
> Hit:4 http://archive.raspberrypi.org/debian buster InRelease                   
> Get:5 https://apt.syncthing.net syncthing InRelease [15.1 kB]                  
> Fetched 30.1 kB in 3s (11.7 kB/s)                  
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> All packages are up to date.
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> The following NEW packages will be installed:
>   yad
> 0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
> Need to get 162 kB of archives.
> After this operation, 512 kB of additional disk space will be used.
> Get:1 http://mirror.dkm.cz/raspbian/raspbian buster/main armhf yad armhf 0.40.0-1 [162 kB]
> Fetched 162 kB in 0s (340 kB/s)
> Selecting previously unselected package yad.
> (Reading database ... 114647 files and directories currently installed.)
> Preparing to unpack .../yad_0.40.0-1_armhf.deb ...
> Unpacking yad (0.40.0-1) ...
> Setting up yad (0.40.0-1) ...
> Processing triggers for mime-support (3.62) ...
> Processing triggers for hicolor-icon-theme (0.17-2) ...
> Processing triggers for gnome-menus (3.31.4-3) ...
> Processing triggers for man-db (2.8.5-2) ...
> Processing triggers for desktop-file-utils (0.23-4) ...
> Creating menu button...
> Adding Desktop shortcut...
> Creating Settings menu button...
> Creating autostarted updater...
> bash: line 122: /home/pi/Downloads/etc/categoryedit: No such file or directory
> You can now launch pi-apps from a terminal, just by running 'pi-apps'
> Generating default settings...
> bash: line 159: /home/pi/Downloads/settings: No such file or directory
> Preloading app list...
> Installation complete.
> pi@fourb:~/Downloads $ pi-apps
> /usr/local/bin/pi-apps: line 2: /home/pi/Downloads/gui: No such file or directory
> ```

Okay, *now* it should be fixed.
