### ISSUE TITLE
Updates reset all data.

### ISSUE THREAD

**Issue by MTCK123** [Botspot/pi-apps#44]
Any update (on pi apps) requires uninstallation of application causing all data for (eg: worlds on Minecraft java) to de deleted.

**Comment by Botspot** [comment]
For some of the apps, I made sure that uninstalling apps does not delete their config. For other apps, I forgot to make sure this happened.
Sorry about that - we'll fix it.

**Comment by MTCK123** [comment]
So is that including Minecraft java saves?

**Comment by MTCK123** [comment]
Ok cool. I will close problem now! Thanks for fixing!

**Comment by Botspot** [comment]
> Ok cool. I will close problem now! Thanks for fixing!

No problem. If you find any other apps causing the same issue, please let me know. Thank you as well.

**Comment by CircuitTear** [comment]
> worlds on Minecraft java) to de deleted.

oof i would be pissed if that happened
