### ISSUE TITLE
Snapdrop Failed to Install

### ISSUE THREAD

**Issue by GabeCoder** [Botspot/pi-apps#442]
While connected to the internet on a 2GB RPi4, I found this new app, Snapdrop, that was added to the Pi App Store, so I decided to install it for an easier way to transfer files. However, it failed to install on my computer. I'm sure the bug will be patched soon, but I just want to make sure you are aware of this bug.

**Comment by Botspot** [comment]
Maybe try again?

Snapdrop's "developer" just had me update the app with a [bug fix](https://github.com/Botspot/pi-apps/pull/441) relating to a broken URL.

Strangely, it worked fine for me during testing, so I don't know what happened. But try installing it again.

**Comment by chunky-milk** [comment]
Yep, it should be fixed now @GabeCoder. Try running `~/pi-apps/updater` in a terminal, then reinstall the app.

**Comment by GabeCoder** [comment]
Yeah, it works now. Thanks for the fix!
