### ISSUE TITLE
Latest Zoom Version

### ISSUE THREAD

**Issue by troyster101** [Botspot/pi-apps#444]
Hi - I'm using the Zoom app within Pi-Apps and it works fine. My only issue is that I need to be able to move participants around in the Gallery view. This is possible in the last official version of Zoom, but not in the Pi-Apps version.

Do you have plans to update this and make this feature accessible in the Pi-Apps version?

Thanks - all the best

**Comment by Itai-Nelken** [comment]
the newest version is very unstable with box86, someone in the discord is testing the newest version to see if it works now.

**Comment by Itai-Nelken** [comment]
see https://github.com/Botspot/pi-apps/issues/188#issuecomment-753675056

**Comment by troyster101** [comment]
> Actually, we were testing the latest Zoom version just yesterday, and it seems to be working fine.
> 
> Want to try it?
> 
> 1. Download this: https://zoom.us/client/5.4.53391.1108/zoom_i686.tar.xz
> 2. Extract it.
> 3. To run:
> 
> ```
> cd /home/pi/Downloads/zoom
> box86 /home/pi/Downloads/zoom/zoom
> ```

Brilliant. Thank you

**Comment by Itai-Nelken** [comment]
@troyster101 did the latest zoom version work?

**Comment by Botspot** [comment]
Done. Commit 5677cc7f37238f73f425b554c3d9c722f408d26b

**Comment by Itai-Nelken** [comment]
@Botspot the script will fail I think. it checks for the box86 binary in `/usr/local/bin` but my deb installs it to `/usr/bin`.

**Comment by Botspot** [comment]
> @Botspot the script will fail I think. it checks for the box86 binary in `/usr/local/bin` but my deb installs it to `/usr/bin`.

Should be [fixed](ce204accb7f15a46d4e057f9db7873cc64aa25ae) now.

**Comment by Itai-Nelken** [comment]
great!
(the link you sent is broken, ...**/issues/**... instead of ...**/commit/**...)

**Comment by Botspot** [comment]
> (the link you sent is broken, ...**/issues/**... instead of ...**/commit/**...)

Wha...?

I copied that link straight from the address bar. I think I just came across a once-in-a-lifetime occurrence. (The URL changing mid-paste)

**Comment by Itai-Nelken** [comment]
weird!
