### ISSUE TITLE
PPSSPP

### ISSUE THREAD

**Issue by chunky-milk** [Botspot/pi-apps#445]
@Botspot this is a PSP emulator, could it be added to pi-apps?
It's not available on APT.

[PPSSPP.zip](https://github.com/Botspot/pi-apps/files/6116078/PPSSPP.zip)

**Comment by Botspot** [comment]
Does it need any kind of BIOS, or is it self-contained and ready-to-use?

Also, would you like to name it something a bit more universally recognizable, like "PSP emulator"?

**Comment by chunky-milk** [comment]
> Does it need any kind of BIOS, or is it self-contained and ready-to-use?
No, it doesn't need a bios, it's ready to use.

> Also, would you like to name it something a bit more universally recognizable, like "PSP emulator"?
Sure, maybe "PPSSPP (PSP emulator)" or would that be too long?

**Comment by Botspot** [comment]
> PPSSPP (PSP emulator)

Fine with me.

**Comment by Botspot** [comment]
Done. commit 1d955f91c5166b47d30475f9dac3f768a05b27ba
