### ISSUE TITLE
box86 update to use my apt repo

### ISSUE THREAD

**Issue by Itai-Nelken** [Botspot/pi-apps#446]
[Box86.zip](https://github.com/Botspot/pi-apps/files/6117153/Box86.zip)
I didn't test it yet, and because I created the zip on my mac the files inside might be a bit weird.

**Comment by Itai-Nelken** [comment]
[Box86.zip](https://github.com/Botspot/pi-apps/files/6117289/Box86.zip)
updated the scripts to try and remove `box86.list` before adding it again just in case

**Comment by Itai-Nelken** [comment]
just needs to be tested one last time, I have to download a new RPiOS image for that, so it will take some time. also someone needs to test it on arm64.

**Comment by Itai-Nelken** [comment]
> > [Box86.zip](https://github.com/Botspot/pi-apps/files/6117334/Box86.zip)
> > removed all weird MacOS stuff.
> 
> The scripts have .sh extensions, those might need to be removed and made executable

oops, here fixed it:
[Box86.zip](https://github.com/Botspot/pi-apps/files/6117482/Box86.zip)

**Comment by Botspot** [comment]
Slight formatting changes. Still untested by me.
[Box86.zip](https://github.com/Botspot/pi-apps/files/6117571/Box86.zip)

@Itai-Nelken What would happen on a system that had already added armhf dpkg architecture beforehand? Would the uninstall script mess up the system, or would it leave the armhf architecture alone?

**Comment by Itai-Nelken** [comment]
> Slight formatting changes. Still untested by me.
> [Box86.zip](https://github.com/Botspot/pi-apps/files/6117571/Box86.zip)
> 
> @Itai-Nelken What would happen on a system that had already added armhf dpkg architecture beforehand? Would the uninstall script mess up the system, or would it leave the armhf architecture alone?

`dpkg` doesn't allow you to remove the armhf architecture if a installed package needs it, thats why instead of using the `error` function I created and use the `warning` function that prints the text in yellow and doesn't exit.

**Comment by Itai-Nelken** [comment]
[Box86.zip](https://github.com/Botspot/pi-apps/files/6117671/Box86.zip)
thats important! good thing you catched that @Botspot, otherwise it would always fail to remove the armhf architecture!

**Comment by Itai-Nelken** [comment]
[Box86.zip](https://github.com/Botspot/pi-apps/files/6117745/Box86.zip)
`purge-installed` was being run twice.

**Comment by Botspot** [comment]
64-bit is going to be tricky.
```
Installing Box86 with install-64 script
armhf arcitecture already added...
Running pkg-install...
Waiting until APT locks are released... Done
Some packages can be upgraded. Please consider running sudo apt full-upgrade -y.
output: Reading package lists...
Building dependency tree...
Reading state information...
libc6:armhf is already the newest version (2.28-10).
libc6:armhf set to manually installed.
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libavcodec58:armhf : Depends: libraspberrypi0:armhf but it is not going to be installed
 libavformat58:armhf : Depends: libssh-gcrypt-4:armhf (>= 0.8.0) but it is not going to be installed
                       Depends: libraspberrypi0:armhf but it is not going to be installed
 libcurl4:armhf : Depends: libgssapi-krb5-2:armhf (>= 1.17) but it is not going to be installed
                  Depends: libkrb5-3:armhf (>= 1.6.dfsg.2) but it is not going to be installed
                  Depends: libssl1.1:armhf (>= 1.1.1) but it is not going to be installed
 libgtk2.0-0:armhf : Depends: libcups2:armhf (>= 1.6.0) but it is not going to be installed
 libsdl-mixer1.2:armhf : Depends: libsdl1.2debian:armhf (>= 1.2.11) but it is not going to be installed
 libsdl1.2-dev:armhf : Depends: libsdl1.2debian:armhf (= 1.2.15+dfsg2-4+rpt2) but it is not going to be installed
 libsdl2-mixer-2.0-0:armhf : Depends: libopusfile0:armhf (>= 0.5) but it is not going to be installed
 libsmpeg0:armhf : Depends: libsdl1.2debian:armhf (>= 1.2.11) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
Failed to check which packages whould be installed!
APT reported these errors:
E: Unable to correct problems, you have held broken packages.

Failed to install Box86 with install-64 script!

Close this window to exit.
```

**Comment by Itai-Nelken** [comment]
oof... I tested it on a fresh debian arm64 VM (on my mac using [UTM](https://mac.getutm.app/) (QEMU)) and it worked perfectly fine...
I say you add the 32bit script and keep working on the arm64 script (hope we don't end up in dependency hell).

also after reading the errors again its saying it won't install the dependencies even though they are probably available meaning all thats needed hopefully is to install all those packages.
```
libraspberrypi0:armhf libssh-gcrypt-4:armhf libgssapi-krb5-2:armhf libkrb5-3:armhf libssl1.1:armhf libcups2:armhf libsdl1.2debian:armhf libopusfile0:armhf 
```
also those `pkg-install` use the `-f` (`--fix-broken`) flag for apt? because if yes it should install all those dependencies because it seems that they are available.

**Comment by Botspot** [comment]
> I say you add the 32bit script and keep working on the arm64 script (hope we don't end up in dependency hell).

Done. Commit 05a183970743c59a1e6c6df2dc1686297d057d28

**Comment by Botspot** [comment]
Let's close this issue and create a new issue that addresses 64-bit box86.
