### ISSUE TITLE
Apps

### ISSUE THREAD

**Issue by Dell-Glitch** [Botspot/pi-apps#448]
![2021-03-10-203907_1280x1024_scrot](https://user-images.githubusercontent.com/73069007/110722677-aec90880-81e0-11eb-8d2b-27e001283f36.png)

**Comment by Botspot** [comment]
Oops. I edited the categories to put PPSSPP in the Games category, and then I renamed PPSSPP to "PPSSPP (PSP emulator)".

And I forgot to update the category. It is fixed now. To apply the fix, open the Category editor (in Pi-Apps Settings), find the PPSSPP line, and click Delete. Then click Save.

Next time Pi-Apps is launched, PPSSPP will be placed in the new default location, which is the Games category.

**Comment by Dell-Glitch** [comment]
Did someone say pss pss pss?!

Also it worked
