### ISSUE TITLE
Is minecraft free in there

### ISSUE THREAD

**Issue by CoderLogy** [Botspot/pi-apps#45]

**Comment by RaspberryRBX** [comment]
Minecraft Cracked Aint In PiApps But U Can Get It

**Comment by Botspot** [comment]
> Is minecraft free in there

No, it's not. The Minecraft Java requires a login (however there is a cracked version you can get, if you can find the link), and the Minecraft Bedrock requires a Google Play Store login to get the .apk file. (And yes, that too has a free workaround, but considering it's illegal, no links to cracked versions are allowed here.)

**Comment by RaspberryRBX** [comment]
@Botspot  On Minecraft Bedrock I Cat Use Google Play Store

**Comment by mobilegmYT** [comment]
If this issue is resolved, please close it.

**Comment by mobilegmYT** [comment]
While I cannot get you the direct download link, http://mcpe-monster.com/ is a good place to look for apks for MCPE and https://www.youtube.com/watch?v=pEhutXW-ZJU for cracked mc java.

**Comment by Botspot** [comment]
I'm closing this since the original question has been answered.

**Comment by CoderLogy** [comment]
Thnks
