### ISSUE TITLE
Minecraft Importer

### ISSUE THREAD

**Issue by GabeCoder** [Botspot/pi-apps#450]
Imagine this one Minecraft player who just wants an easy way to import worlds and mods. Well luckily for him, Minecraft Importer exists now! Its user-friendly interface will help them install their favorite texture packs and backups into their game, especially the Mobile Export resource pack.

Can this app run on RPi? If so, please provide a link to a tutorial if applicable.
Yes, it is made on an RPi and verified on an RPi!

Is this app something many GUI users would find useful?  
Yes, since it automatically installs the worlds and packs.

Is this app installable with `sudo apt install`?  
No, you'll need to install it with at least three commands.
```
git clone https://github.com/GabeCoder/mc-importer
chmod +x import.sh
desktop-file-install --dir=$HOME/.local/share/applications $HOME/mc-importer/mc-importer.desktop
```

If you've created a zip file for this app, upload it here.

[Minecraft Importer.zip](https://github.com/Botspot/pi-apps/files/6121147/Minecraft.Importer.zip)
Have fun!

**Comment by Botspot** [comment]
Is this intended for Minecraft Bedrock, Java, or Pi?

**Comment by GabeCoder** [comment]
> Is this intended for Minecraft Bedrock, Java, or Pi?

As I have legally acquired Minecraft Bedrock Edition, this app is intended for Bedrock. More editions of the app will come soon if possible.

**Comment by GabeCoder** [comment]
Oh, and there are some requirements for this app.
YAD (installed with pi apps)
Zenity
Unzip
Minecraft Bedrock Edition
etc.

**Comment by GabeCoder** [comment]
Due to my terrible coding, this idea has been scrapped.

**Comment by GabeCoder** [comment]
Re-opening

**Comment by GabeCoder** [comment]
So I updated the app with bug fixes that caused resource and behavior packs not being able to import. I also accidentally tested this with a corrupted addon, so I’ll keep you updated.

**Comment by GabeCoder** [comment]
Update: Importing worlds and packs were successful.
Add-on imports are still a **feature of the future**, so they will be implemented when possible.

**Comment by mobilegmYT** [comment]
Oh this is pretty nice! Would be nice to java support, though you mentioned that you don't have a copy of Java. From what I know, for java support it just needs to take a .zip resourcepack and move it to ~/.minecraft/resourcepacks.

**Comment by gl91306** [comment]
yes but java resources are kind of different from bedrock, and the mod and world files are different

**Comment by Botspot** [comment]
#505
