### ISSUE TITLE
Failed to build dhewm3

### ISSUE THREAD

**Issue by akhilleusuggo** [Botspot/pi-apps#453]
Hello , 

I'm trying to install Doom 3 , but having an issue during install .

```
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Setting -DD3_ARCH="aarch64" -DD3_SIZEOFPTR=4 -DD3_OSTYPE="linux" 
CMake Error at CMakeLists.txt:118 (message):
  CMake thinks sizeof(void*) == 4, but the target CPU looks like a 64bit CPU!


CMake Error at CMakeLists.txt:119 (message):
  If you're building in a 32bit chroot on a 64bit host, switch to it with
  'linux32 chroot' or at least call cmake with linux32 (or your OSs
  equivalent)!


-- Configuring incomplete, errors occurred!
See also "/home/pi/RPIDoom3Installer/dhewm3/neo/build/CMakeFiles/CMakeOutput.log".
Failed to build dhewm3
Failed to run install script :(

Failed to install Doom 3 with install-32 script!
```

I've checked the log file at : `/home/pi/RPIDoom3Installer/dhewm3/neo/build/CMakeFiles/CMakeOutput.log` , but I don't see error .

**Comment by akhilleusuggo** [comment]
Works !

Just in case someone has this issue , removing / commenting the `arm_64bit=1` solves it

**Comment by Itai-Nelken** [comment]
> Works !
> 
> Just in case someone has this issue , removing / commenting the `arm_64bit=1` solves it

@Botspot maybe make the doom3 install-32 check what arch you are on using `uname -m` and fail if it says 64bit.

**Comment by Botspot** [comment]
> > Works !
> > Just in case someone has this issue , removing / commenting the `arm_64bit=1` solves it
> 
> @Botspot maybe make the doom3 install-32 check what arch you are on using `uname -m` and fail if it says 64bit.

We _could_, or we could take `cmake`'s suggestion:

> `or at least call cmake with linux32 (or your OSs
  equivalent)!`

Untested, but maybe this would work? `setarch linux32 cmake ...` (Just remember seeing the setarch trick used for the Wine app)

**Comment by Itai-Nelken** [comment]
>...or we could take cmake's suggestion:

or at least call cmake with linux32 (or your OSs equivalent)!

Untested, but maybe this would work? setarch linux32 cmake ... (Just remember seeing the setarch trick used for the Wine app)

maybe, if yes thats a better idea.
