### ISSUE TITLE
Minecraft Pi

### ISSUE THREAD

**Issue by MrBrain295** [Botspot/pi-apps#457]
I can't see minecraft pi on the app list. I am using Ubuntu groovy gorilla and the xlunch app style.

**Comment by slashtechno** [comment]
@MrBrain295 Make sure you are in the "Games" Category. If it does not  appear(and you did not change the app list), try running this command, 
To install: `~/pi-apps/apps/Minecraft Pi (Modded)/install`
To uninstall `~/pi-apps/apps/Minecraft Pi (Modded)/uninstall`

**Comment by mobilegmYT** [comment]
> I can't see minecraft pi on the app list. I am using Ubuntu groovy gorilla and the xlunch app style.

The desktop shortcut is called `MCPIL`. You can also launch it in terminal with `mcpil`.

**Comment by Botspot** [comment]
@MrBrain295, were you able to find it and solve the problem? Is there anything else we can help you with?

If not, then this issue should be closed.
