### ISSUE TITLE
[App Request] Wechat

### ISSUE THREAD

**Issue by mobilegmYT** [Botspot/pi-apps#458]
Can this app run on RPi? If so, please provide a link to a tutorial if applicable.  
I tested it

Is this app something many GUI users would find useful?  
Yes

Is this app installable with `sudo apt install`?  
Nope

If you've created a zip file for this app, upload it here.
[Wechat.zip](https://github.com/Botspot/pi-apps/files/6135017/Wechat.zip)

**Comment by Botspot** [comment]
It appears that you have to do a lot of workarounds + a manual step to get Chinese to render properly.

What if I didn't care about Chinese? Could the script be simplified? If so, let's ask the user if they care about Chinese characters or not.

**Comment by mobilegmYT** [comment]
> It appears that you have to do a lot of workarounds + a manual step to get Chinese to render properly.
> 
> What if I didn't care about Chinese? Could the script be simplified? If so, let's ask the user if they care about Chinese characters or not.

I mean considering wechat is a chinese app, and that you need their mobile app which is chinese only to use it, I think it should be added.

**Comment by Botspot** [comment]
> I mean considering wechat is a chinese app

Are you implying that WeChat will only interest Chinese users? In that case, my next question is "How many people would use this?"

**Comment by mobilegmYT** [comment]
> > I mean considering wechat is a chinese app
> 
> Are you implying that WeChat will only interest Chinese users? In that case, my next question is "How many people would use this?"

I mean there is a modest Chinese RPI community so 🤷‍♂️, but if you don't think anyone will use it then you don't need to add it.

**Comment by Botspot** [comment]
> I mean there is a modest Chinese RPI community so 🤷‍♂️, but if you don't think anyone will use it then you don't need to add it.

Okay, after [searching](https://www.raspberrypi.org/forums/search.php?keywords=wechat) the RPi forum to gauge interest, I've decided to add it.

Could you clarify in the tooltip that Wechat is mainly intended for Chinese users?

**Comment by mobilegmYT** [comment]
[Uploading Wechat.zip…]()

**Comment by mobilegmYT** [comment]
[Wechat.zip](https://github.com/Botspot/pi-apps/files/6152006/Wechat.zip)

**Comment by Botspot** [comment]
I think it may be possible to automatically make that change to the registry.

I've concluded this after noticing that winetricks is making changes. It was kind enough to list all commands being run.  
Example:
```
Executing wine regedit C:\windows\Temp\_register-font.reg
Executing cp /home/pi/.wine/dosdevices/c:/windows/temp/_register-font.reg /tmp/winetricks.xNSCXvgN/_reg_d7f60a67_31292.reg
```

**Comment by Botspot** [comment]
So it looks like `wine regedit` can take an argument.  
Let's try it.
```
pi@raspberrypi:~ $ wine regedit ~/Downloads/chn_fonts.reg
Box86 with Dynarec v0.2.1 be82ccbf built on Mar 15 2021 00:03:16
Box86 with Dynarec v0.2.1 be82ccbf built on Mar 15 2021 00:03:16
Box86 with Dynarec v0.2.1 be82ccbf built on Mar 15 2021 00:03:16
```
I think it worked!! No window opened at least, and it briefly used 200MB of RAM.

**Comment by Botspot** [comment]
I'm not sure how to read this:

> pi-apps will now install wechat. Just click continue to all the prompts **and do not enable and extra settings.**

**Comment by Botspot** [comment]
Well that's an interesting typo.  
I can just see the bug reports: "Why does uninstalling Wechat actually uninstall Minecraft?"  
Here's your uninstall script:
```
#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

rm -f ~/.local/share/applications/minecraft.desktop
sudo rm -rf ~/Minecraft
sudo rm -rf ~/lwjgl2arm32
sudo rm -rf ~/lwjgl3arm32
sudo rm -rf ~/lwjgl3arm64
sudo rm -rf ~/lwjgl2arm64
sudo rm -rf /usr/share/minecraftjava/
```

**Comment by mobilegmYT** [comment]
> I'm not sure how to read this:
> 
> > pi-apps will now install wechat. Just click continue to all the prompts **and do not enable and extra settings.**

Basically it's saying don't change install location or anything when it runs the setup.exe

**Comment by Botspot** [comment]
In any case, here's the app that I made changes to.
[Wechat.zip](https://github.com/Botspot/pi-apps/files/6176559/Wechat.zip)
I changed the second `and` to `any`. It makes sense that way.

**Comment by mobilegmYT** [comment]
> I can just imagine the bug reports: "Why does uninstalling Wechat actually uninstall Minecraft?"
> Here's your uninstall script...
> 
> ```
> #!/bin/bash
> 
> DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"
> 
> function error {
>   echo -e "\\e[91m$1\\e[39m"
>   exit 1
> }
> 
> rm -f ~/.local/share/applications/minecraft.desktop
> sudo rm -rf ~/Minecraft
> sudo rm -rf ~/lwjgl2arm32
> sudo rm -rf ~/lwjgl3arm32
> sudo rm -rf ~/lwjgl3arm64
> sudo rm -rf ~/lwjgl2arm64
> sudo rm -rf /usr/share/minecraftjava/
> ```

True, lemme fix

**Comment by mobilegmYT** [comment]
[Wechat.zip](https://github.com/Botspot/pi-apps/files/6254873/Wechat.zip)

Install to different wine prefix

**Comment by hmsjy2017** [comment]
There is an arm64 version here, I am not sure if it will work properly and what is the difference with the x86 version.
https://drive.google.com/file/d/1HYUci776F5576cCqgkymHqrwG_UDjqe9/view?usp=sharing

**Comment by mobilegmYT** [comment]
> There is an arm64 version here, I am not sure if it will work properly and what is the difference with the x86 version.
> https://drive.google.com/file/d/1HYUci776F5576cCqgkymHqrwG_UDjqe9/view?usp=sharing

![image](https://user-images.githubusercontent.com/44128563/113515460-e69e4400-9531-11eb-900e-0831704543e1.png)

**Comment by hmsjy2017** [comment]
I have changed the access permissions, is it okay now?

**Comment by Botspot** [comment]
Wechat 32-bit added to the app store with commit d40b5a7a72cb54de7bc1d7872bf5dd992e60ebd1.

Are we still interested in 64bit, or should I close this issue?

**Comment by mobilegmYT** [comment]
> Wechat 32-bit added to the app store with commit [d40b5a7](https://github.com/Botspot/pi-apps/commit/d40b5a7a72cb54de7bc1d7872bf5dd992e60ebd1).
> 
> Are we still interested in 64bit, or should I close this issue?

I mean since box86 has a 64-bit install, we might be able to just rename the install script.

**Comment by hmsjy2017** [comment]
> Wechat 32-bit added to the app store with commit [d40b5a7](https://github.com/Botspot/pi-apps/commit/d40b5a7a72cb54de7bc1d7872bf5dd992e60ebd1).
> 
> Are we still interested in 64bit, or should I close this issue?

But this is an arm64 version, maybe we can install it directly without box86.

**Comment by Botspot** [comment]
On an arm64 virtual machine, I installed the arm64 wechat.deb without incident.
But when trying to run in the terminal, it gave me this error:
```
pi@raspberrypi:~ $ /usr/bin/wechat-uos
bwrap: capset failed: Operation not permitted
```

**Comment by Botspot** [comment]
@mobilegmYT On an armhf virtual machine, I tried installing wechat from Pi-Apps. It never launches.
```
pi@raspberrypi:~ $ env WINEPREFIX="/home/pi/.config/wechat-prefix" wine C:\\\\windows\\\\command\\\\start.exe /Unix /home/pi/.config/wechat-prefix/dosdevices/c:/users/Public/Desktop/WeChat.lnk
Box86 with Dynarec v0.2.1 b588709a built on May 23 2021 00:03:17
Box86 with Dynarec v0.2.1 b588709a built on May 23 2021 00:03:17
Box86 with Dynarec v0.2.1 b588709a built on May 23 2021 00:03:17
0024:fixme:exec:SHELL_execute flags ignored: 0x00000100
0024:fixme:exec:SHELL_execute flags ignored: 0x00004100
00b8:fixme:process:SetProcessDEPPolicy (3): stub
00b8:err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
00c0:fixme:ver:GetCurrentPackageId (0530FF0C 00000000): stub
00c0:fixme:sync:SetWaitableTimerEx (000000B8, 0530FDBC, 0, 00000000, 00000000, 00000000, 1499) semi-stub
00f0:err:ntdll:RtlpWaitForCriticalSection section 7BCC55C0 "loader.c: loader_section" wait timed out in thread 00f0, blocked by 00b8, retrying (60 sec)
00e8:err:ntdll:RtlpWaitForCriticalSection section 7BCC55C0 "loader.c: loader_section" wait timed out in thread 00e8, blocked by 00b8, retrying (60 sec)
00d8:err:ntdll:RtlpWaitForCriticalSection section 7BCC55C0 "loader.c: loader_section" wait timed out in thread 00d8, blocked by 00b8, retrying (60 sec)
00d0:err:ntdll:RtlpWaitForCriticalSection section 7BCC55C0 "loader.c: loader_section" wait timed out in thread 00d0, blocked by 00b8, retrying (60 sec)
00c
```
@mobilegmYT Have you had this same problem?

**Comment by mobilegmYT** [comment]
> @mobilegmYT On an armhf virtual machine, I tried installing wechat from Pi-Apps. It never launches.
> 
> ```
> pi@raspberrypi:~ $ env WINEPREFIX="/home/pi/.config/wechat-prefix" wine C:\\\\windows\\\\command\\\\start.exe /Unix /home/pi/.config/wechat-prefix/dosdevices/c:/users/Public/Desktop/WeChat.lnk
> Box86 with Dynarec v0.2.1 b588709a built on May 23 2021 00:03:17
> Box86 with Dynarec v0.2.1 b588709a built on May 23 2021 00:03:17
> Box86 with Dynarec v0.2.1 b588709a built on May 23 2021 00:03:17
> 0024:fixme:exec:SHELL_execute flags ignored: 0x00000100
> 0024:fixme:exec:SHELL_execute flags ignored: 0x00004100
> 00b8:fixme:process:SetProcessDEPPolicy (3): stub
> 00b8:err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
> 00c0:fixme:ver:GetCurrentPackageId (0530FF0C 00000000): stub
> 00c0:fixme:sync:SetWaitableTimerEx (000000B8, 0530FDBC, 0, 00000000, 00000000, 00000000, 1499) semi-stub
> 00f0:err:ntdll:RtlpWaitForCriticalSection section 7BCC55C0 "loader.c: loader_section" wait timed out in thread 00f0, blocked by 00b8, retrying (60 sec)
> 00e8:err:ntdll:RtlpWaitForCriticalSection section 7BCC55C0 "loader.c: loader_section" wait timed out in thread 00e8, blocked by 00b8, retrying (60 sec)
> 00d8:err:ntdll:RtlpWaitForCriticalSection section 7BCC55C0 "loader.c: loader_section" wait timed out in thread 00d8, blocked by 00b8, retrying (60 sec)
> 00d0:err:ntdll:RtlpWaitForCriticalSection section 7BCC55C0 "loader.c: loader_section" wait timed out in thread 00d0, blocked by 00b8, retrying (60 sec)
> 00c
> ```
> 
> @mobilegmYT Have you had this same problem?

Yea about that, ptitseb said he doesn't know what the issue there is.

**Comment by Botspot** [comment]
It appears one discord user is also [having the same problem](https://discord.com/channels/770629697909424159/770629878319022090/846277167297724437).

Should WeChat be pulled from Pi-Apps then?

**Comment by mobilegmYT** [comment]
> It appears one discord user is also [having the same problem](https://discord.com/channels/770629697909424159/770629878319022090/846277167297724437).
> 
> Should WeChat be pulled from Pi-Apps then?

Sure, maybe we could remove install-32 and add install-64 with the deb.

**Comment by Botspot** [comment]
> Sure, maybe we could remove install-32 and add install-64 with the deb.

Before that happens, we need someone to successfully get the arm64 deb working.

**Comment by mobilegmYT** [comment]
> > Sure, maybe we could remove install-32 and add install-64 with the deb.
> 
> Before that happens, we need someone to successfully get the arm64 deb working.

Erm true, IG we can pull it for now then.

**Comment by Botspot** [comment]
> > On an arm64 virtual machine, I installed the arm64 wechat.deb without incident.
> > But when trying to run in the terminal, it gave me this error:
> > ```
> > pi@raspberrypi:~ $ /usr/bin/wechat-uos
> > bwrap: capset failed: Operation not permitted
> > ```
> 
> However, I can successfully install it on Raspberry Pi OS (arm64). It can be used normally. But armhf is not supported by the app.

Interesting!

**Comment by Itai-Nelken** [comment]
closing as wechat is already added.
