### ISSUE TITLE
eDEX-UI 3.0.0

### ISSUE THREAD

**Issue by slashtechno** [Botspot/pi-apps#460]
eDEX-UI 3.0.0 does not start for me, I tried `sudo modprobe fuse` after looking at issue #72 but it still does not start.

**Comment by Botspot** [comment]
What happens when you run eDEX-UI in the terminal? It ought to display the error.

**Comment by slashtechno** [comment]
```
Cannot mount AppImage, please check your FUSE setup.
You might still be able to extract the contents of this AppImage 
if you run it with the --appimage-extract option. 
See https://github.com/AppImage/AppImageKit/wiki/FUSE 
for more information

```

I did `sudo modprobe fuse`.

**Comment by Itai-Nelken** [comment]
> ```
> Cannot mount AppImage, please check your FUSE setup.
> You might still be able to extract the contents of this AppImage 
> if you run it with the --appimage-extract option. 
> See https://github.com/AppImage/AppImageKit/wiki/FUSE 
> for more information
> ```
> 
> I did `sudo modprobe fuse`.

reboot, it fixed the issue multiple times for me.
