### ISSUE TITLE
[App Request] KeePassX

### ISSUE THREAD

**Issue by chunky-milk** [Botspot/pi-apps#468]
This is an open-source password/secure information vault. You can store your passwords, attachments, urls, and more in one secure database. 

**Can this app run on RPi? If so, please provide a link to a tutorial if applicable.**  
Yes, it can run on Raspberry Pi, I tested it.

**Is this app something many GUI users would find useful?**  
Yes, it has a GUI itself.

**Is this app installable with `sudo apt install`?**  
Yes, but the version in the repositories is outdated.

**If you've created a zip file for this app, upload it here.**
I don't have a zip, but I do have a compiled deb [here](https://github.com/chunky-milk/keepassx-rpi/releases/download/2.0.3/keepassx_2.0.3-1_armhf.deb), and when installing the deb, dependencies are automatically installed.

**Comment by mobilegmYT** [comment]
@chunky-milk To ensure your app gets added sooner, please use the app creation tool in pi-apps to make a zip installer so it's quicker for botspot to add in.

**Comment by chunky-milk** [comment]
> @chunky-milk To ensure your app gets added sooner, please use the app creation tool in pi-apps to make a zip installer so it's quicker for botspot to add in.

I know. 🙂

**Comment by Botspot** [comment]
What can I say? It works fine, but needs a description, icons, a website, in addition to install and uninstall scripts.

**Comment by Botspot** [comment]
Here's what I suggest, @chunky-milk:  
Take a similar existing app and edit it. Looks like VeraCrypt is very similar and you will only have to change a few minor things.  
If you have Pi-Apps installed in the default location, you will fine VeraCrypt located at: `/home/pi/pi-apps/apps/VeraCrypt`

**Comment by Botspot** [comment]
@chunky-milk How did I not notice the obvious before?

KeePassX is already on the repositories.  
On a fresh RPiOS system, you can install keepassx with this command:
```
sudo apt install keepassx
```
And that's `2.0.3-2`, instead of `2.0.3-1`. (your version )

**Comment by chunky-milk** [comment]
> @chunky-milk How did I not notice the obvious before?
> 
> 
> 
> KeePassX is already on the repositories.  
> 
> On a fresh RPiOS system, you can install keepassx with this command:
> 
> ```
> 
> sudo apt install keepassx
> 
> ```
> 
> And that's `2.0.3-2`, instead of `2.0.3-1`. (your version )

Oh no!!! Sorry 😆
