### ISSUE TITLE
Raspi2png install error

### ISSUE THREAD

**Issue by mobilegmYT** [Botspot/pi-apps#47]
Just got an update on pi-apps for this and I got this
![image](https://user-images.githubusercontent.com/44128563/97741514-78e47c80-1aa8-11eb-8af8-bd91f038c8f9.png)

**Comment by Botspot** [comment]
Wait, seriously? Looks like APT has a typo! "Failed to check which packages **whould** be installed!"

This issue was caused by me fixing raspi2png to run on arm64. I'm going to make it only install libpng-dev, and you please let me know if that works.

**Comment by Botspot** [comment]
There - please try it again. 1b62bd3482ba3a40a957b1a3a6d3d6dc1e8d539f

**Comment by mobilegmYT** [comment]
Ayy it worked!
