### ISSUE TITLE
Failed to install NodeJS after update.

### ISSUE THREAD

**Issue by scamdotnet** [Botspot/pi-apps#472]
I recently updated Pi-Apps, and one of the updates was NodeJS, so it uninstalled the app as normal, but when reinstalling it encountered an error. Sadly I do not have a copy of the original error message, but when trying to install it via the normal install process, it gives the following error

```
 Installing Node.js with install script
   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                  Dload  Upload   Total   Spent    Left  Speed
 100 13527  100 13527    0     0   150k      0 --:--:-- --:--:-- --:--:--  150k
 => nvm is already installed in /home/pi/.config/nvm, trying to update using git
 => => Compressing and cleaning up git repository
 
 => nvm source string already in /home/pi/.bashrc
 => bash_completion source string already in /home/pi/.bashrc
 => Close and reopen your terminal to start using nvm or run the following to use it now:
 
 export NVM_DIR="$HOME/.config/nvm"
 [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
 [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
 /home/pi/pi-apps/apps/Node.js/install: line 30: nvm: command not found
 
 Failed to install Node.js with install script!

 
Close this window to exit.
```
Does anyone have any ideas of what is going on here?

**Comment by Itai-Nelken** [comment]
> I recently updated Pi-Apps, and one of the updates was NodeJS, so it uninstalled the app as normal, but when reinstalling it encountered an error. Sadly I do not have a copy of the original error message, but when trying to install it via the normal install process, it gives the following error
> 
> ```
>  Installing Node.js with install script
>    % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                   Dload  Upload   Total   Spent    Left  Speed
>  100 13527  100 13527    0     0   150k      0 --:--:-- --:--:-- --:--:--  150k
>  => nvm is already installed in /home/pi/.config/nvm, trying to update using git
>  => => Compressing and cleaning up git repository
>  
>  => nvm source string already in /home/pi/.bashrc
>  => bash_completion source string already in /home/pi/.bashrc
>  => Close and reopen your terminal to start using nvm or run the following to use it now:
>  
>  export NVM_DIR="$HOME/.config/nvm"
>  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
>  [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
>  /home/pi/pi-apps/apps/Node.js/install: line 30: nvm: command not found
>  
>  Failed to install Node.js with install script!
> ```
>  
> Close this window to exit.
> 
> Does anyone have any ideas of what is going on here?

Weird, that was fixed in https://github.com/Botspot/pi-apps/commit/4e9a7f0b5ac37468393747446fae777fead8f5e0

**Comment by scamdotnet** [comment]
Closed due to this being fixed.
