### ISSUE TITLE
Failed to install Snap Store

### ISSUE THREAD

**Issue by scamdotnet** [Botspot/pi-apps#473]
I have been having this issue for a while, but whenever I try to install the Snap Store using Pi-Apps, I get the following error:
```
Installing Snap Store with install script
Running pkg-install...
Waiting until APT locks are released... Done
Some packages can be upgraded. Please consider running sudo apt full-upgrade -y.
output: Reading package lists...
Building dependency tree...
Reading state information...
snapd is already the newest version (2.37.4-1+rpi1).
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
No new packages to install. Nothing to do!
snap "core" is already installed, see 'snap help refresh'
error: cannot perform the following tasks:
- Mount snap "snap-store" (503) (mkdir /snap: file exists)
Unable to install snap store

Failed to install Snap Store with install script!

Close this window to exit.

```

Anyone have an explanation for this?

**Comment by Botspot** [comment]
I had the same issue yesterday.

Completely reinstalling snapd worked.  
```
sudo rm -r /snap
sudo apt purge -y snapd
sudo apt install snapd
```

**Comment by scamdotnet** [comment]
> I had the same issue yesterday.
> 
> Completely reinstalling snapd worked.
> 
> ```
> sudo rm -r /snap
> sudo apt purge -y snapd
> sudo apt install snapd
> ```

For me, that second command (sudo apt purge -y snapd) doesn't work, it fails with the following:
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following package was automatically installed and is no longer required:
  squashfs-tools
Use 'sudo apt autoremove' to remove it.
The following packages will be REMOVED:
  snapd*
0 upgraded, 0 newly installed, 1 to remove and 3 not upgraded.
After this operation, 48.3 MB disk space will be freed.
(Reading database ... 263785 files and directories currently installed.)
Removing snapd (2.37.4-1+rpi1) ...
Processing triggers for desktop-file-utils (0.23-4) ...
Processing triggers for mime-support (3.62) ...
Processing triggers for gnome-menus (3.31.4-3) ...
Processing triggers for man-db (2.8.5-2) ...
Processing triggers for bamfdaemon (0.5.4-1) ...
Rebuilding /usr/share/applications/bamf-2.index...
(Reading database ... 263733 files and directories currently installed.)
Purging configuration files for snapd (2.37.4-1+rpi1) ...
Final directory cleanup
Discarding preserved snap namespaces
Removing extra snap-confine apparmor rules
Removing snapd cache
rm: cannot remove '/var/cache/snapd/aux': Is a directory
dpkg: error processing package snapd (--purge):
 installed snapd package post-removal script subprocess returned error exit status 1
Errors were encountered while processing:
 snapd
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by Botspot** [comment]
> > I had the same issue yesterday.
> > Completely reinstalling snapd worked.
> > ```
> > sudo rm -r /snap
> > sudo apt purge -y snapd
> > sudo apt install snapd
> > ```
> 
> For me, that second command (sudo apt purge -y snapd) doesn't work, it fails with the following:
> 
> ```
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> The following package was automatically installed and is no longer required:
>   squashfs-tools
> Use 'sudo apt autoremove' to remove it.
> The following packages will be REMOVED:
>   snapd*
> 0 upgraded, 0 newly installed, 1 to remove and 3 not upgraded.
> After this operation, 48.3 MB disk space will be freed.
> (Reading database ... 263785 files and directories currently installed.)
> Removing snapd (2.37.4-1+rpi1) ...
> Processing triggers for desktop-file-utils (0.23-4) ...
> Processing triggers for mime-support (3.62) ...
> Processing triggers for gnome-menus (3.31.4-3) ...
> Processing triggers for man-db (2.8.5-2) ...
> Processing triggers for bamfdaemon (0.5.4-1) ...
> Rebuilding /usr/share/applications/bamf-2.index...
> (Reading database ... 263733 files and directories currently installed.)
> Purging configuration files for snapd (2.37.4-1+rpi1) ...
> Final directory cleanup
> Discarding preserved snap namespaces
> Removing extra snap-confine apparmor rules
> Removing snapd cache
> rm: cannot remove '/var/cache/snapd/aux': Is a directory
> dpkg: error processing package snapd (--purge):
>  installed snapd package post-removal script subprocess returned error exit status 1
> Errors were encountered while processing:
>  snapd
> E: Sub-process /usr/bin/dpkg returned an error code (1)
> ```

Oh yeah, that too. `sudo rm -r /var/cache/snapd/aux`

**Comment by scamdotnet** [comment]
should that code be added to the uninstall script? I know it says that the uninstall script doesn't remove snapd itself.

**Comment by scamdotnet** [comment]
I got it working, but there are some weird visual bugs, but I believe that's a bug with the snap store itself, not with Pi-Apps.

**Comment by Botspot** [comment]
> I got it working, but there are some weird visual bugs, but I believe that's a bug with the snap store itself, not with Pi-Apps.

Same here. Rebooting partially helped me.

**Comment by scamdotnet** [comment]
> > I got it working, but there are some weird visual bugs, but I believe that's a bug with the snap store itself, not with Pi-Apps.
> 
> Same here. Rebooting partially helped me.

Same, but the main explore page is pretty broken, all I can see is half of the telegram logo (after a reboot).

**Comment by Itai-Nelken** [comment]
Snapcraft are having issues, yesterday most of their services were down.
You can see the status of their services [here](https://status.snapcraft.io/).
Maybe thats the cause?
