### ISSUE TITLE
Pi-Apps Install issues - Would not install

### ISSUE THREAD

**Issue by vmoutsop** [Botspot/pi-apps#476]
03/18/21 - I copied and pasted the install script and it didn't work. I tried a couple of different ways that I looked up but neither worked.

**Comment by Itai-Nelken** [comment]
@vmoutsop that isn'r enough information.
here are a few questions that will help us help you:
- what OS are you on?
- what pi are you using?
- what is the terminal output when copying the line?
- what are the different ways you tried?

**Comment by fabianmendes** [comment]
I got this intalling Pycharm 
![2021-03-18-223230_800x480_scrot](https://user-images.githubusercontent.com/31230743/111726845-1403a600-8840-11eb-977d-90ae19d2d125.png)

**Comment by Botspot** [comment]
Oh. This was due to the recent pull request. I forgot that github pull requests by default don't **mark scripts as executable**.

Fixed now.
