### ISSUE TITLE
Adding more terminal emulators

### ISSUE THREAD

**Issue by CleanMachine1** [Botspot/pi-apps#477]
Although the /etc/terminal-run file has plenty of terminals, it may be a simple addition to others such as:
terminator
gnome-terminator
guake

Thanks

**Comment by Botspot** [comment]
Terminator: Done. (locally on my system, not yet uploaded)  
Gnome-terminator: `E: Unable to locate package gnome-terminator` Any ideas?  
Guake: Doesn't appear to be possible.

**Comment by CleanMachine1** [comment]
must have been thinking of my favourite emulator terminator 

The correct package is gnome-terminal

**Comment by Botspot** [comment]
Done. Commit 8c2034cfc9d196bc51496906b46421f1995bcc61.

**Comment by CleanMachine1** [comment]
What?  [8c2034c](https://github.com/Botspot/pi-apps/commit/8c2034cfc9d196bc51496906b46421f1995bcc61) references nothing to do with terminals, its about pycharm and having an empty file..

**Comment by CleanMachine1** [comment]
Ah nevermind, you must have grabbed the wrong link! 

Checked commits list and its this [7ca71cd](https://github.com/Botspot/pi-apps/commit/7ca71cd4b939784691a49257ea064614b28cc48c)
