### ISSUE TITLE
Remove VSCode 

### ISSUE THREAD

**Issue by CleanMachine1** [Botspot/pi-apps#478]
Since RPi Foundation/Trading removed the VSCode repo and instead added to their repo this is no longer necessary, also I am pretty sure that using the install method currently used doesn't keep it up-to-date 

[http://archive.raspberrypi.org/debian/pool/main/c/code/](http://archive.raspberrypi.org/debian/pool/main/c/code/)

**Comment by Itai-Nelken** [comment]
Yes it is neccesary because pi-apps isn't made just for RPiOS, so if for example you are on Ubuntu using apt won't work because its not in the Ubuntu repos as far as I know.

**Comment by Itai-Nelken** [comment]
so you say to download the deb from there?
I don" see how downloading VSCode from the rpi repo is better than downloading it from the website if you aren't on RPiOS.

**Comment by CleanMachine1** [comment]
On raspberry pi OS, a few weeks back they added "code" to their repos which can be installed with a simple `sudo apt install code`

**Comment by Itai-Nelken** [comment]
> On raspberry pi OS, a few weeks back they added "code" to their repos which can be installed with a simple `sudo apt install code`

I know, but what if you are using pi-apps on Ubuntu for example? Ubuntu doesn't have VSCode in its repos.
The current way will work on any debian system.

**Comment by CleanMachine1** [comment]
suits me, makes sense however I may add a pull request to change something about vscode
