### ISSUE TITLE
missing screenshot 'create-app.png' in readme

### ISSUE THREAD

**Issue by Itai-Nelken** [Botspot/pi-apps#484]
https://github.com/botspot/pi-apps/#directory-tree

**Comment by Botspot** [comment]
I am aware of this and did it intentionally. Yesterday I took all new screenshots, but forgot this one.

To prevent myself from forgetting to update the `create app.png`, I intentionally deleted it from the repo. That way, if I forgot, someone else would notice and tell me.

Thanks! :)  
(Screenshot done this morning)
