### ISSUE TITLE
RPi-Play app suggestion

### ISSUE THREAD

**Issue by CleanMachine1** [Botspot/pi-apps#486]
Hi,
here is a link to the github repo [RPiPlay](https://github.com/FD-/RPiPlay)

It allows IOS devices to connect to the pi and allow screen sharing,
I have compiled it before with these commands `sudo apt-get install cmake
sudo apt-get install libavahi-compat-libdnssd-dev
sudo apt-get install libplist-dev
sudo apt-get install libssl-dev
mkdir build
cd build
cmake ..
make
sudo make install`
and it worked well however some may find it useful to not have to compile something 

Seems like something that could be done easily.
You may also want to consider having it default to using -a hdmi so sound defaults to hdmi rather than analog

One problem you may have, it has a different dependencies depending on OS

Overall this project seems like something people would like and use

Regards,
CleanMachine1

**Comment by Botspot** [comment]
So it's basically scrcpy or androidbuddy, but for iOS?

**Comment by CleanMachine1** [comment]
Unfortunately iOS airplay (what it uses) doesn't support touch control, only mirrors the screen and sound

However think of it as scrcpy, without control

**Comment by chunky-milk** [comment]
debfile [here](https://github.com/chunky-milk/raspbian_repository/blob/master/debian/pool/rpiplay_20210320-1_armhf.deb)

**Comment by CleanMachine1** [comment]
I personally don't like just running random .deb however gdebi package manager reports this

`Package: rpiplay
Priority: extra
Section: checkinstall
Installed-Size: 1424
Maintainer: root@twister-desktop
Architecture: armhf
Version: 20210320-1
Depends: libavahi-compat-libdnssd-dev,libplist-dev,libssl-dev
Provides: rpiplay
Description: Package created with checkinstall 1.6.3
` which seems pretty safe to me

However, I fear this wont work on something like ubuntu due to different dependencies

**Comment by chunky-milk** [comment]
> I personally don't like just running random .deb however gdebi package manager reports this
> 
> `Package: rpiplay Priority: extra Section: checkinstall Installed-Size: 1424 Maintainer: root@twister-desktop Architecture: armhf Version: 20210320-1 Depends: libavahi-compat-libdnssd-dev,libplist-dev,libssl-dev Provides: rpiplay Description: Package created with checkinstall 1.6.3 ` which seems pretty safe to me
> 
> However, I fear this wont work on something like ubuntu due to different dependencies

Did you try installing those dependencies on Ubuntu?

**Comment by CleanMachine1** [comment]
I don't use ubuntu on my raspberry pis', so no.

However I do have a suggestion

If we look at /etc/os-release we can get some data about the OS, check which package should be installed and install it

**Comment by CleanMachine1** [comment]
test=$(hostnamectl | grep Operating)
here is a better command for getting the output to a variable

**Comment by CleanMachine1** [comment]
OK, I am going to try and make a app script which compiles from source RPi-Play
before I try its probably going to take me a few days and also I have a few questions:
which OS should I try and support?
What command can I use to find the users OS for the install script?

**Comment by Botspot** [comment]
> OK, I am going to try and make a app script which compiles from source RPi-Play
> before I try its probably going to take me a few days and also I have a few questions:
> which OS should I try and support?
> What command can I use to find the users OS for the install script?

Raspberry Pi OS is the only officially supported OS. You can choose to only support 32-bit, 64-bit, or both.  
For installing a local package, this command should install all necessary dependencies. (So therefore your script shouldn't need to detect OS version)
```
sudo apt install -y --fix-broken /path/to/local.deb
```
The `--fix-broken` flag ~~will~~ _should_ automatically install all dependencies. Be sure to use the `|| error` function in case stuff fails. Have you read through the Pi-Apps "Creating an app" section? https://github.com/Botspot/pi-apps#to-do

**Comment by CleanMachine1** [comment]
I have published code in the pull PR, this issue is now irrelevant
