### ISSUE TITLE
Kodi

### ISSUE THREAD

**Issue by RaspberryRBX** [Botspot/pi-apps#49]
[Kodi.zip](https://github.com/Botspot/pi-apps/files/5469265/Kodi.zip)

**Comment by Botspot** [comment]
As you know, Pi-Apps is only for those apps that are not available on the repositories.

How is this Kodi version different from simply installing it with `sudo apt install kodi`?

**Comment by RaspberryRBX** [comment]
Its Setup Automatically Live TV Game Controllers

**Comment by RaspberryRBX** [comment]
Works

**Comment by Botspot** [comment]
Sorry, I can't add this. Kodi is already installable via `apt-get`.

In addition, that's basically all your script does. (yes I saw it added some other stuff, but that too is stuff from the repos.)

Later on, I may add a second section to Pi-Apps that does install repository-hosted apps, but for now, this type of app is not allowed.
