### ISSUE TITLE
How to get beta  Minecraft Java 

### ISSUE THREAD

**Issue by cjcool18** [Botspot/pi-apps#490]
How to get a Minecraft Java beta on raspberry pi on pi app

**Comment by oxmc** [comment]
> How to get a Minecraft Java beta on raspberry pi on pi app

Are you saying it like an app suggestion or just like a hey how about this?

**Comment by mobilegmYT** [comment]
> How to get a Minecraft Java beta on raspberry pi on pi app

If you don't even know how to unzip a file and read the instructions, it's better off to wait for the public release.

**Comment by cjcool18** [comment]
When it go public release

**Comment by cjcool18** [comment]
What file

**Comment by cjcool18** [comment]
I know how to unzip a file

**Comment by Itai-Nelken** [comment]
> I know how to unzip a file

well, then download the latest zip from #483 and follow the instructions in the first comment there.

**Comment by Itai-Nelken** [comment]
> When it go public release

when its working reliably.
