### ISSUE TITLE
set reinstall after update no,why this time update uninstall wine app.

### ISSUE THREAD

**Issue by try1995** [Botspot/pi-apps#492]
today i update pi-apps, i found it uninsall wine app. i dont want unintall any apps after update,because i will lost my data.what should i do

**Comment by Itai-Nelken** [comment]
pi-apps always uninstalls the app its updating, and if you set it to not install after a update it won't install it again.

**Comment by Itai-Nelken** [comment]
also pi-apps doesn't delete any user data

**Comment by Itai-Nelken** [comment]
@try1995 set pi-apps to reinstall after update and install wine again, you should have all your wine programs installed.

**Comment by Botspot** [comment]
> also pi-apps doesn't delete any user data

pi-apps ~~doesn't~~ _shouldn't_ delete any user data.
