### ISSUE TITLE
app creation

### ISSUE THREAD

**Issue by akhilleusuggo** [Botspot/pi-apps#495]
I'm not a developer , but wanted to experiment and try to create an app for myself/needs by executing multiple command lines ( like a shortcut ) .

The issue happens when I get to step 3 ( execute and test script ) . On the app and wiki , it's clearly stated : 

> Simply write down all those commands in a file Pi-Apps _**opens for you**_.

But nothing opens . Is this related to the text editor ? Witch one should be used to open the file script ?

**Comment by akhilleusuggo** [comment]
Ok, the default one `Geany` does open .

**Comment by Botspot** [comment]
> Ok, the default one `Geany` does open .

Interesting. What OS are you using? Geany is installed by default on Raspberry Pi OS.

**Comment by akhilleusuggo** [comment]
@Botspot Rasbian OS ( the official one ), or Raspberry Pi OS ( same thing ) .

Yes , I have just edited the editor to nano ( one that the app does feature! ) . I though would open a command line prompt or a text editor , but nothing happened . 

I use bluefish , since atom not available .

Maybe a pull request would be to have the ability to add new editors to the list ( customize , point to the app users does use ) .

**Comment by Botspot** [comment]
> @Botspot Rasbian OS ( the official one ), or Raspberry Pi OS ( same thing ) .

Huh. Maybe you uninstalled geany.

I'll see what's going on with `nano`.

**Comment by Botspot** [comment]
> Maybe a pull request would be to have the ability to add new editors to the list ( customize , point to the app users does use ) .

@akhilleusuggo  
What I don't want happening is Pi-Apps listing a bunch of nonexistent text editors that aren't true options unless you install them.  
Currently I can just use a file to contain the list of all available text editors. If I added more specialty editors that aren't installed by default, that would then require logic to detect and hide incompatible editors. That would add complexity.

I've just now fixed the nano implementation with commit bf7956d2a3ffc7828196721edeb204e65b93bb3d.  
If you want to use a custom text editor, you can simply edit the settings file to anything you want: `~/pi-apps/data/settings/Preferred text editor`.

**Comment by akhilleusuggo** [comment]
Thank you Sr !
