### ISSUE TITLE
Offset color of Pi-Apps logo text for use in dark mode.

### ISSUE THREAD

**Issue by necro-nemesis** [Botspot/pi-apps#496]
![image](https://user-images.githubusercontent.com/29291956/111964243-c9e22500-8aca-11eb-8099-ae6cbd52e564.png)

I run github in dark mode. As you can see the text color doesn't have very good contrast against the background color of github in dark mode. Suggest tuning it slightly to provide some additional contrast for those running in dark mode.

**Comment by CleanMachine1** [comment]
![blackonwhite](https://user-images.githubusercontent.com/78213164/112012536-30922d80-8b21-11eb-9102-7cef28fe1beb.png)

**Comment by Botspot** [comment]
There, I added a discrete white outline.

In dark mode:  
![2021-03-22-104308_1920x1080_scrot](https://user-images.githubusercontent.com/54716352/112017523-b307f680-8afb-11eb-903a-014f1a67f803.png)  
In light mode:  
![2021-03-22-104312_1920x1080_scrot](https://user-images.githubusercontent.com/54716352/112017524-b3a08d00-8afb-11eb-9abc-afe5b964b1ad.png)

**Comment by Botspot** [comment]
Completed with commit 240b9f609e9872cbb0de9bb912df373c280e7ba4

**Comment by necro-nemesis** [comment]
![image](https://user-images.githubusercontent.com/29291956/112021222-704c1b80-8b07-11eb-8a97-8f222458f0f0.png)
Nice. Up top on README.md could use it too.

**Comment by CleanMachine1** [comment]
PS Happy Pi closed issues! (314 Closed issues)
