### ISSUE TITLE
[App request] Discord

### ISSUE THREAD

**Issue by mobilegmYT** [Botspot/pi-apps#5]
The app maker works! Made this quickly with SpacingBat3's discord natifier.
[Discord.zip](https://github.com/Botspot/pi-apps/files/5319058/Discord.zip)

**Comment by Botspot** [comment]
The desktop shortcut and menu button don't work.
Check the contents of /home/pi/Desktop/discord.desktop - mine contains an entire HTML document in it!

**Comment by mobilegmYT** [comment]
oop

**Comment by mobilegmYT** [comment]
Hmm. what if you just run the command `wget http://download941.mediafire.com/nyhl1h8xxcog/18ux1pdfc714tim/discord.desktop -P /usr/bin/discord-linux-armv7l/`?

**Comment by Botspot** [comment]
That command creates a file at `/usr/bin/discord-linux-armv7l/discord.desktop`, but it's 43KB of HTML code.

**Comment by Botspot** [comment]
This article may be helpful: https://superuser.com/questions/312305/downloading-a-rar-file-from-mediafire-using-wget

**Comment by Botspot** [comment]
Probably the best option is for you to create your own GitHub repository and host discord.desktop and discord.svg yourself.
Or, you could be creative and reuse `icon-64.png` for the .desktop file, and then hardcode discord.desktop creation within the install script.

**Comment by mobilegmYT** [comment]
was just about to do that

**Comment by mobilegmYT** [comment]
try dis: 
[Discord.zip](https://github.com/Botspot/pi-apps/files/5319391/Discord.zip)

**Comment by mobilegmYT** [comment]
Updated the desktop files too

**Comment by Botspot** [comment]
Works for me. Though it would be more streamlined if you were to do something like this for `install`:
```
#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$(dirname "$0")")")"
function error {
  echo -e "\e[31m$1\e[39m"
  exit 1
}

cd ~/Downloads
#Download from github
wget https://github.com/SpacingBat3/nativefier-discord-arm/raw/master/assets/discord-linux-armv7l.tar.gz || error 'Failed to download files!'
#Delete tar.gz and move to /usr/bin
tar -xf discord-linux-armv7l.tar.gz || error 'Failed to extract program!'
rm discord-linux-armv7l.tar.gz
sudo mv discord-linux-armv7l /usr/bin/ || error 'Failed to move folder!'

#Move desktop shortcuts

echo "[Desktop Entry]
Version=1.0
Terminal=false
Type=Application
Name=Discord
Exec=/usr/bin/discord-linux-armv7l/discord
Icon="${DIRECTORY}/icon-64.png
Categories=Network;Chat;VideoConference;WebApp;Internet
Comment=Your place to talk!
Comment[pl]=Twoje miejsce do rozmów!
GenericName=Network Messenger
GenericName[pl]=Kommunikator internetowy" > /usr/bin/discord-linux-armv7l/discord.desktop

sudo chmod +x /usr/bin/discord-linux-armv7l/discord.desktop

#menu button
sudo cp -a /usr/bin/discord-linux-armv7l/discord.desktop /usr/share/applications

#desktop shortcut
sudo cp -a /usr/bin/discord-linux-armv7l/discord.desktop ~/Desktop/
```

**Comment by mobilegmYT** [comment]
[Discord.zip](https://github.com/Botspot/pi-apps/files/5319421/Discord.zip)

**Comment by mobilegmYT** [comment]
That was a lot more work than anticipated

**Comment by Botspot** [comment]
Don't worry, you will get the hang of it.
If there's anything I can do to streamline the app creation process, please let me know.
I will add Discord to the official repo soon.

**Comment by mobilegmYT** [comment]
Thx bro

**Comment by mobilegmYT** [comment]
https://github.com/Botspot/pi-apps/issues/1 
![image](https://user-images.githubusercontent.com/44128563/94952453-404e8480-04a3-11eb-8990-686bf7aff453.png)

**Comment by mobilegmYT** [comment]
oop i think its broken again

**Comment by Botspot** [comment]
No don't worry, I'm fixing it all up and trying various scenarios on it to make it BULLETPROOF. :)

**Comment by mobilegmYT** [comment]
Your version of install.sh is slightly broken I think.

**Comment by mobilegmYT** [comment]
tried installing and the program folder didnt even get moved, the icon doesn't show up for the shortcuts, and the menu bar shortcut isn't even there lol

**Comment by Botspot** [comment]
I know. Don't worry.

**Comment by Botspot** [comment]
OK it's been added to the repo.

**Comment by mobilegmYT** [comment]
I updated the repo and it auto started installing discord. Is that supposed to happen?

**Comment by mobilegmYT** [comment]
Also, the reason I didn't want to use the icon for discord in /apps/discord is that the middle is transparent.
![image](https://user-images.githubusercontent.com/44128563/94954044-b9e77200-04a5-11eb-8b85-4bc1f6d8cd43.png)

**Comment by Botspot** [comment]
Yes. Pi-Apps remembers that Discord was installed prior to the update.
When it updates, it uninstalls, copies the new files in, and then reinstalls.

If Discord had been uninstalled prior to updating, Pi-Apps wouldn't have installed it. APT does the same thing.

**Comment by mobilegmYT** [comment]
Probably should fix up the icon tho.

**Comment by Botspot** [comment]
I noticed the bad transparency in the image. As that transparency is undesirable in all cases, I will fix the icons.

**Comment by Botspot** [comment]
icons fixed.

**Comment by mobilegmYT** [comment]
https://github.com/Botspot/pi-apps/issues/6
