### ISSUE TITLE
Updater

### ISSUE THREAD

**Issue by RaspberryRBX** [Botspot/pi-apps#50]
@Botspot The Updater Wont Update PiApps

**Comment by RaspberryRBX** [comment]
@Botspot The Updater Wont Update

**Comment by RaspberryRBX** [comment]
@Botspot Can U Fix It

**Comment by Botspot** [comment]
Yes, something is wrong. I'm fixing it at the moment.

**Comment by Botspot** [comment]
Okay, I believe it's now fixed as of commit 036e9765d0322c22f95b4f2ffd597ddb2db3c7ba  
First, allow Pi-Apps to check for updates. Next, run this command:

    cp ~/pi-apps/update/pi-apps/updater ~/pi-apps/updater
