### ISSUE TITLE
the new icons are good but the status icons are..

### ISSUE THREAD

**Issue by srini-pro** [Botspot/pi-apps#501]
the icons are so small that  the instaled status icons look little bit gross icrease the size are revert to otiginal  other wise a amazing update

**Comment by Botspot** [comment]
Are you saying that these icons are too small for you to make out?  
![installed](https://user-images.githubusercontent.com/54716352/112087137-6c49e900-8b5b-11eb-9efc-cbb6018e00f2.png)  ![corrupted](https://user-images.githubusercontent.com/54716352/112087183-7d92f580-8b5b-11eb-9267-a526f57561fa.png)  ![none](https://user-images.githubusercontent.com/54716352/112087184-7d92f580-8b5b-11eb-84f7-ecf5a395ded6.png)  ![uninstalled](https://user-images.githubusercontent.com/54716352/112087185-7d92f580-8b5b-11eb-9629-90dd88b0e9e1.png)

**Comment by srini-pro** [comment]
yaa and kinda indistingiuable in my monitor

**Comment by srini-pro** [comment]
![image](https://user-images.githubusercontent.com/75109032/112246708-10758200-8c79-11eb-9b41-ea8f22272272.png)

**Comment by Botspot** [comment]
> yaa and kinda indistinguishable in my monitor

How do you suggest I improve them?

**Comment by srini-pro** [comment]
the  before update icons? i guess but with cittle bit of colour

**Comment by Botspot** [comment]
> The icons from before the update? i guess but with little bit of colour.

The problem with those was that they looked too much like checkboxes. Nearly all youtubers first attempted to "check" the box.  
To prevent that from happening and to clarify the status icons' meaning, I had to make them not look like checkboxes.

Any ideas for how I can make the status icons more distinguishable, but not look like checkboxes?

**Comment by srini-pro** [comment]
other side of  the icon  write installed or corrupted and unistalled  it the same coulours 
installed = green , unistalled=red ,courupted=yellow?

**Comment by Botspot** [comment]
> other side of the icon write installed or corrupted and unistalled it the same coulours
> installed = green , unistalled=red ,courupted=yellow?

Like this?  
![2021-03-29-092124_1920x1080_scrot](https://user-images.githubusercontent.com/54716352/112851073-397a8600-9070-11eb-9bb5-ec60d168092e.png)

**Comment by Itai-Nelken** [comment]
maybe a option to change between text and icons be added to the settings?
is that possible?
maybe rename all the icons, so when the icon ones are used, the text ones are called `<icon-name>-text.png` and when the text ones are in use, the icon ones are called `<icon-name>-icon.png`. that way there is no need to change the scrips.

**Comment by srini-pro** [comment]
yep   after the name  and icon

**Comment by srini-pro** [comment]
> maybe a option to change between text and icons be added to the settings?
> is that possible?
> maybe rename all the icons, so when the icon ones are used, the text ones are called `<icon-name>-text.png` and when the text ones are in use, the icon ones are called `<icon-name>-icon.png`. that way there is no need to change the scrips.

yes  the default willl be the usuall

**Comment by techcoder20** [comment]
Speaking of icons can you give the text a white outline like you did in youtubuddy, u cant the see the text i ur using a dark theme
![pi-apps](https://user-images.githubusercontent.com/68472305/112964355-e3880a00-9165-11eb-8500-5abfb7ea07f8.png)

**Comment by Botspot** [comment]
> Speaking of icons can you give the text a white outline like you did in youtubuddy, u cant the see the text i ur using a dark theme
> ![pi-apps](https://user-images.githubusercontent.com/68472305/112964355-e3880a00-9165-11eb-8500-5abfb7ea07f8.png)

Good idea. Better now?

**Comment by srini-pro** [comment]
gr8
