### ISSUE TITLE
make it easy to download apps from snap and apt 

### ISSUE THREAD

**Issue by srini-pro** [Botspot/pi-apps#502]
even rpm

**Comment by CleanMachine1** [comment]
Regarding apt

You may not know that pi-apps tends to stay away from things in the repos unless its a dependency? 
Most people that can use pi-apps will be able to search the built in GUI apt thingy for their program

Regarding npm read this [Link to RPi-Forum](https://www.raspberrypi.org/forums/viewtopic.php?t=163006)

**Comment by Botspot** [comment]
Closing, as the request within this issue is broad and vague.

**Comment by srini-pro** [comment]
meant like  type the app  and it will install it?

**Comment by srini-pro** [comment]
maybe like pi-gro
