### ISSUE TITLE
Add VSCode to settings app maker editors

### ISSUE THREAD

**Issue by CleanMachine1** [Botspot/pi-apps#504]
It pretty nice to be able to edit my files using VSCode as I like using all my extensions.

This is a follow up to your most recent commit 

https://github.com/Botspot/pi-apps/commit/bf7956d2a3ffc7828196721edeb204e65b93bb3d

**Comment by Botspot** [comment]
Great idea, but the problem with automatically including more text editors is that Pi-Apps would then have to detect which editors were installed, and hide those that were not.

While that doesn't sound so hard, it is. It would require code changes in multiple scripts and break the currently elegant settings implementation. And for most people, Geany is sufficient.

There is a workaround though: https://github.com/Botspot/pi-apps/issues/495#issuecomment-805977360

**Comment by CleanMachine1** [comment]
Okay that works, for future the future this will be helpful
