### ISSUE TITLE
Minecraft Importer (Updated)

### ISSUE THREAD

**Issue by ghost** [Botspot/pi-apps#505]
Can this app run on RPi? If so, please provide a link to a tutorial if applicable.  
Yes, this app has been developed on a Raspberry Pi, tested on a Raspberry Pi, and has worked on a Raspberry Pi!
Is this app something many GUI users would find useful?  
Yes, since it decreases difficulty in importing packages to Minecraft Bedrock Edition.
Is this app installable with `sudo apt install`?  
No, you'll need to install this app with Pi Apps.
If you've created a zip file for this app, upload it here.
[Minecraft Importer.tar.gz](https://github.com/Botspot/pi-apps/files/6381084/Minecraft.Importer.tar.gz)

The category is "Games".

**Comment by Botspot** [comment]
To be honest this was the first time I tried it.  
I am slightly confused what this program does or how to use it.

The description merely says:

> Import worlds and packs straight to Minecraft Bedrock Edition for you to access and use. (Only designed for Linux.)
> With only a few clicks, you'll be able to install your favorite backups with no sweat.

Okay... But how to do that?  
I launched Minecraft Importer from the menu and clicked OK. A file selection window appeared. Now what? What am I looking for?

And is this simply a file copier? What's it doing behind the scenes?

**Comment by GabeCoder** [comment]
> To be honest this was the first time I tried it.
> I am slightly confused what this program does or how to use it.
> 
> The description merely says:
> 
> > Import worlds and packs straight to Minecraft Bedrock Edition for you to access and use. (Only designed for Linux.)
> > With only a few clicks, you'll be able to install your favorite backups with no sweat.
> 
> Okay... But how to do that?
> I launched Minecraft Importer from the menu and clicked OK. A file selection window appeared. Now what? What am I looking for?
> 
> And is this simply a file copier? What's it doing behind the scenes?

There are 2 file types you can import.
Minecraft Worlds: .mcworld
Minecraft Resource/Behavior Packs: .mcpack
Minecraft Addons are coming soon!

**Comment by Botspot** [comment]
> There are 2 file types you can import.
> Minecraft Worlds: .mcworld
> Minecraft Resource/Behavior Packs: .mcpack
> Minecraft Addons are coming soon!
> 
> .mcworld and .mcpack are simply archives. The importer will extract the files from the archives to a folder in the game’s directory, which will hold the contents of the imported package. That is how the importer imports backups and mods.

Excellent. I suggest you add that information to the description.

**Comment by Botspot** [comment]
> Excellent. I suggest you add that information to the description.

And is there any chance this could expand to do interesting stuff for Minecraft Java and for Minecraft Pi as well?

**Comment by GabeCoder** [comment]
> > Excellent. I suggest you add that information to the description.
> 
> And is there any chance this could expand to do interesting stuff for Minecraft Java and for Minecraft Pi as well?

Although I have installed both Java and Pi, I don’t really know about modding the Pi Edition and need to purchase the Java Edition, so as long as I find out about Pi mods and pay $25 for MCJava, versions for those will come out too.

**Comment by GabeCoder** [comment]
I have updated the Minecraft Importer package and repository for Pi Apps. The three main updated elements of this package are the description, credits, and mostly the icon. The new package was uploaded on my edited issue. If you have no idea what I'm talking about, I'll lend you the new package here.
[Minecraft Importer.tar.gz](https://github.com/Botspot/pi-apps/files/6381092/Minecraft.Importer.tar.gz)

**Comment by theofficialgman** [comment]
@ghost whats the status on this? shouldn't this be added as a builtin option to the minecraft bedrock script instead of a separate thing? after all its pretty much useless unless you have bedrock edition installed

importing worlds into java edition is hassle free, you either just copy them to the correct folder, or you add them via the GUI in multimc, so I don't see a need for an importer in java edition (as was previously suggested)

**Comment by theofficialgman** [comment]
oh I see ghost isn't an actual user, lol. this whole time on github I though they were an actual user, not a deleted user.
no wonder I see ghost around all over the place.

@Botspot  it looks like the user, GabeCoder, has deleted their entire profile, so this will have to be closed as their github repo is non-existant and this will never be able to be installed.
