### ISSUE TITLE
Password Manager

### ISSUE THREAD

**Issue by GabeCoder** [Botspot/pi-apps#508]
Can this app run on RPi? If so, please provide a link to a tutorial if applicable.  
Yes, this app has been developed in, tested in, and works in a Raspberry Pi.
Is this app something many GUI users would find useful?  
Yes, this app requires no commands to be run.
Is this app installable with `sudo apt install`?  
No, you'll need to run a few commands or use its provided installer to install it without Pi Apps.
If you've created a zip file for this app, upload it here.
[Password Manager.tar.gz](https://github.com/Botspot/pi-apps/files/6208619/Password.Manager.tar.gz)
The category for this app is "Tools".

**Comment by Botspot** [comment]
Wow, who wrote `password-manager.sh`? It's simple and well-thought-out.  
Minus the fact that the windows don't appear in the center of the screen, and minus the fact that the passwords aren't encrypted.

I'm not bashing the app per se, but aren't there already plenty of password managers that *do* have encryption, *do* have a way to import passwords from browsers and .csv files, and *do* allow you have multiple entries that start with the same username?

**Comment by GabeCoder** [comment]
> Wow, who wrote `password-manager.sh`? It's simple and well-thought-out.
> Minus the fact that the windows don't appear in the center of the screen, and minus the fact that the passwords aren't encrypted.
> 
> I'm not bashing the app per se, but aren't there already plenty of password managers that _do_ have encryption, _do_ have a way to import passwords from browsers and .csv files, and _do_ allow you have multiple entries that start with the same username?

Yes, I understand this a lot. I tried hard to find a way to force users to enter their password to access the manager. Plus, the password managers you suggested seem better to use.
To explain my manager, I just made this so I could store all my passwords in a hidden folder without anybody else seeing. This was also made to store a Pi-Hole admin password I wanted to keep secret. Feel free to reject this if you want to, though the manager will still remain available to install with an installer on the README.md of the GitHub repository.

**Comment by Botspot** [comment]
@GabeCoder, Let's compare your app to [the KeePassX app request](https://github.com/Botspot/pi-apps/issues/468). Right now KeePassX seems to be more user-friendly & more secure.

I think most Pi-Apps users would agree with me that they'd rather have their usernames, passwords and other random text stored in an _encrypted_ vault, than in an unprotected directory containing files of plain text.

Either your app will have to _drastically_ improve in flexibility and security, or else I'm afraid it wouldn't be a good match for Pi-Apps. Maybe you'd rather help create the app files for KeePassX? :)

**Comment by Botspot** [comment]
> Oh, and I wrote the entirety of the script.

Well done! I congratulate you. :)

**Comment by GabeCoder** [comment]
> @GabeCoder, Let's compare your app to [the KeePassX app request](https://github.com/Botspot/pi-apps/issues/468). Right now KeePassX seems to be more user-friendly & more secure.
> 
> I think most Pi-Apps users would agree with me that they'd rather have their usernames, passwords and other random text stored in an _encrypted_ vault, than in an unprotected directory containing files of plain text.
> 
> Either your app will have to _drastically_ improve in flexibility and security, or else I'm afraid it wouldn't be a good match for Pi-Apps. Maybe you'd rather help create the app files for KeePassX? :)

Actually, I’d rather work on KeePassX. Surely it’ll help many users secure their passwords.

**Comment by Botspot** [comment]
> Actually, I’d rather work on KeePassX. Surely it’ll help many users secure their passwords.

Thank you for understanding, @GabeCoder. :)
