### ISSUE TITLE
Failed to install yad.

### ISSUE THREAD

**Issue by seaniedan** [Botspot/pi-apps#509]
Yad does not install.  Using a Raspberry pi4, 8Gb:

pi@pi4:~ $ wget -qO- https://raw.githubusercontent.com/Botspot/pi-apps/master/install | bash
Get:1 http://archive.raspberrypi.org/debian buster InRelease [32.9 kB]
Get:2 http://raspbian.raspberrypi.org/raspbian buster InRelease [15.0 kB]   
Get:3 http://archive.raspberrypi.org/debian buster/main armhf Packages [372 kB]
Get:4 http://raspbian.raspberrypi.org/raspbian buster/main armhf Packages [13.0 MB]
Get:5 http://raspbian.raspberrypi.org/raspbian buster/non-free armhf Packages [104 kB]
Fetched 13.5 MB in 12s (1,090 kB/s)                                            
Reading package lists... Done
Building dependency tree       
Reading state information... Done
107 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 mcpil : Depends: minecraft-pi-reborn-virgl but it is not installable or
                  minecraft-pi-reborn-native but it is not installable
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
Failed to install yad.

**Comment by Itai-Nelken** [comment]
first of all run `sudo apt update; sudo apt full-upgrade -y`.
you tried to install minecraft pi modded from pi-apps and it failed so you are trying to reinstall pi-apps, right?
anyway run `sudo apt purge mcpil -y` and `sudo apt clean; sudo apt autoremove -y; sudo apt autoclean`
then try to install pi-apps again.

**Comment by seaniedan** [comment]
Ah, I did:
```
sudo apt update; sudo apt full-upgrade -y
sudo apt --fix-broken install
sudo apt purge mcpil -y and sudo apt clean; sudo apt autoremove -y; sudo apt autoclean
```
..then installed and all working. Thank you for your help!
