### ISSUE TITLE
Cannot Install Any App

### ISSUE THREAD

**Issue by Alextrapixel** [Botspot/pi-apps#51]
well I cannot install app from Pi-Apps. I'm using latest Raspberry Pi OS 32bit. And custom desktop environtment (MATE desktop). Bellow the screenshot after click install of any app
![Screenshot at 2020-11-01 12-51-37](https://user-images.githubusercontent.com/59244353/97796196-723d3d00-1c41-11eb-9f0d-09081486df84.png)

**Comment by Botspot** [comment]
This is interesting. There's been almost zero testing on other desktop environments, so once we fix this you can be sure Pi-Apps will be more _bulletproof_ than it is now. :) 

> well I cannot install app from Pi-Apps. I'm using latest Raspberry Pi OS 32bit. And custom desktop environtment (MATE desktop). Bellow the screenshot after click install of any app

So it sounds like Pi-Apps itself installed okay, but you're saying that no apps will install. This seems very similar to issue #41, but I thought I fixed it 2 days ago. Could you try updating Pi-Apps?

**Comment by Botspot** [comment]
After two others had the same issue on my Discord server, I connected the dots and determined: this is a problem with the terminal.
Removing the `cd` line seems to have solved the problem with commit 65a593a756d4d7988905a5f47c6e4061de393120. Please try updating.

**Comment by Alextrapixel** [comment]
After updating, the warning almost similar with screenshot above, but it say :
 `Failed to execute child process “if” (No such file or directory)`
 😅

**Comment by Botspot** [comment]
What terminal are you using?

**Comment by Alextrapixel** [comment]
Mate Terminal

**Comment by Botspot** [comment]
> Mate Terminal

Thank you. I will install `mate-terminal` and try to fix the problem for you.

**Comment by Botspot** [comment]
Okay, I think it's fixed now with commit 5a153d21da8af94bb25f64be286101c59a3f0d19. For some reason, `mate-terminal` didn't know it was supposed to run `bash`.  
So once I explicitly told it to run `bash`, it worked.

**Comment by Alextrapixel** [comment]
> Okay, I think it's fixed now with commit [5a153d2](https://github.com/Botspot/pi-apps/commit/5a153d21da8af94bb25f64be286101c59a3f0d19). For some reason, `mate-terminal` didn't know it was supposed to run `bash`.
> So once I explicitly told it to run `bash`, it worked.

It works now... cool. Great fix... 👍
Thank you for the hard works.
