### ISSUE TITLE
ARCon Runtime

### ISSUE THREAD

**Issue by ilobilo** [Botspot/pi-apps#510]
Description:
Run android apps on Linux from chromium browser!

Can this app run on RPi? If so, please provide a link to a tutorial if applicable.  
It can run on arm CPU.

Is this app something many GUI users would find useful?  
Yes.

Is this app installable with `sudo apt install`?  
No

Website: https://archon-runtime.github.io/
Helpful links: 
Install extensions from command line:
https://askubuntu.com/questions/1063331/how-to-install-google-chrome-extensions-though-terminal

**Comment by Botspot** [comment]
This did not successfully install in my Chromium-browser. Did you get it working?

**Comment by ilobilo** [comment]
As I already said I don't have raspberry pi (I'm 13 year old kid and don't have money for it). My main Linux system, where I do everything is my android phone with termux. I just like rpi and your project, so I want to help you by giving you ideas and helping with scripts.

Sorry for bad english.

**Comment by Botspot** [comment]
> As I already said I don't have raspberry pi (I'm 13 year old kid and don't have money for it). My main Linux system, where I do everything is my android phone with termux. I just like rpi and your project, so I want to help you by giving you ideas and helping with scripts.

In that case, thank you! Too bad it doesn't work though.
