### ISSUE TITLE
wish list

### ISSUE THREAD

**Issue by srini-pro** [Botspot/pi-apps#514]
i was browsing pi-apps when i saw a cool app i didnt have the space to download it but i knew i could download it later i know  i can make doc and then search..

**Comment by Botspot** [comment]
Upon reading your suggestion, I'm unsure exactly what new feature you are requesting, or what the problem is that you want solved. Could you help explain?

**Comment by srini-pro** [comment]
sure  lets i want qemu but  i have tto do something else now later i will forget that app reight so if there was a button or a folder open then iwill see the  and think if i acttually need it so if i do  it installs it if  now i've change my mind i would  remove from my wish list

**Comment by techcoder20** [comment]
I think he is suggesting something similar to a watchlater list, link in youtubuddy. Would be easy to implement but in my opinion there is no need for it :)

**Comment by Botspot** [comment]
> sure lets i want qemu but i have tto do something else now later i will forget that app reight so if there was a button or a folder open then iwill see the and think if i acttually need it so if i do it installs it if now i've change my mind i would remove from my wish list

Oh I get it. Like a "remind your future self" kind of thing. A wishlist perhaps.  
While it's a good idea and @techcoder20's right - it would be easy to implement, I am not convinced enough people would make use of the feature. And in the meantime, there would be one more button everywhere, making the Pi-Apps window even longer than it already is.

Solution:  
@srini-pro, while there isn't a watch-later feature in Pi-Apps, you could easily implement one using Pi-Apps categories.  
Launch the category editor (from Pi-Apps Settings), and find your desired app. Simply rename the category to "Install later".

Now, that app will be located in the "Install later" category. To revert, launch the category editor again, and change the category back.

**Comment by srini-pro** [comment]
definitely an option a feature

**Comment by srini-pro** [comment]
oh never new that
