### ISSUE TITLE
Google Chrome

### ISSUE THREAD

**Issue by Pythonic456** [Botspot/pi-apps#515]
Google Chromium cannot sync anymore, as Google strikes again.
But maybe we could use 32-bit Chrome and box86 or make a petition.

Thanks in advance :)

**Comment by techcoder20** [comment]
Even if we were able to get chrome working on box86, at this stage I dont think it will be very smooth and wont really be that usable.

**Comment by Botspot** [comment]
> Google Chromium cannot sync anymore, as Google strikes again.

I had expected there to be some sort of syncing problem, but so far haven't. Google is still syncing fine with my system's Chromium v88. Has Google's decision not affected Pi users yet or something?

> But maybe we could use 32-bit Chrome and box86 or make a petition.

Interesting idea. I actually got 32-bit Chrome .exe to launch using Wine. But all pages crashed with Aw, Snap!

**Comment by Itai-Nelken** [comment]
maybe the newest version will run with box64 when its released.

**Comment by locness3** [comment]
> Has Google's decision not affected Pi users yet

I would think they decided to update the code instead of restricting API access. The raspbian repos are hardly ever up-to-date, so if they actually do that then we can wait a while.

But why would you need to sync?

**Comment by techcoder20** [comment]
> But why would you need to sync?

When ur distro hopping which can happen a lot if ur using a Raspberry Pi, it will become easy for us to move our browser data from one os to another. One alternative is to backup the `~/.config/chromium` folder

**Comment by Itai-Nelken** [comment]
Or if you are using multiple devices.

**Comment by Botspot** [comment]
> That is the reason I want sync.

Has anyone actually *reported* having syncing problems yet? It's still working fine for me.

**Comment by Pythonic456** [comment]
Yes, just a couple of days ago, sync stopped working for me. And just yesterday it signed me out of my Google account.

**Comment by srini-pro** [comment]
From: Pythonic456Sent: Saturday, April 3, 2021 1:45 PMTo: Botspot/pi-appsCc: SubscribedSubject: Re: [Botspot/pi-apps] Google Chrome (#515) ok—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Botspot** [comment]
> Yes, just a couple of days ago, sync stopped working for me. And just yesterday it signed me out of my Google account.

Huh. I wonder why I haven't been affected yet...

**Comment by Itai-Nelken** [comment]
> Huh. I wonder why I haven't been affected yet...

I haven't been affected either..

**Comment by Botspot** [comment]
I am going to close this issue.

Currently there is no known way to run a recent version of Google Chrome on RPi. Chrome v33 or something similarly old running under Wine or ExaGear doesn't count.

**Comment by Botspot** [comment]
Google Chrome has been added to pi-apps https://github.com/Botspot/pi-apps/commit/392d265fabb3043f1141f219dc963550c024a637
