### ISSUE TITLE
[app] github-cli

### ISSUE THREAD

**Issue by Itai-Nelken** [Botspot/pi-apps#518]
[Github-CLI.zip](https://github.com/Botspot/pi-apps/files/6232522/Github-CLI.zip)

**Comment by Itai-Nelken** [comment]
its a really cool and useful utility.
![image](https://i.imgur.com/IozILtn.png)

**Comment by Itai-Nelken** [comment]
this comment is from github-cli.﻿

**Comment by Botspot** [comment]
Done. Commit 7ae1715485f47796e5c3899ded4beb293133a35e
