### ISSUE TITLE
Not able to download any app from it enev clicked intalled

### ISSUE THREAD

**Issue by CoderLogy** [Botspot/pi-apps#52]

**Comment by Botspot** [comment]
Do any errors show up when you click install?

Also, is your Pi-Apps fully up-to-date?

**Comment by mobilegmYT** [comment]
I suggest you run pi-apps.uninstall and follow the install procedures again.

**Comment by CoderLogy** [comment]
No when I click install the apps donot get install

**Comment by CoderLogy** [comment]
They eventually get refresh just not installed

**Comment by Botspot** [comment]
> No when I click install the apps donot get install

Your version of Pi-Apps is probably out of date. Please uninstall Pi-Apps, and then install Pi-Apps.

**Comment by CoderLogy** [comment]
I have done but not at any result new version even installed I am using
Raspberry Pi 3a+ please tell if I click install the page refresh nothing
installs

**Comment by Botspot** [comment]
@CoderLogy What OS are you running? Is it Raspberry Pi OS Buster?

**Comment by CoderLogy** [comment]
I am using Raspberry Pi OS Buster
It's new and updated pls check why not working the os is officiall os made
by Raspberry Pi

**Comment by Botspot** [comment]
> I am using Raspberry Pi OS Buster It's new and updated pls check why not working the os is officiall os made by Raspberry Pi

Okay, now please run this command in a terminal:
```
/home/pi/pi-apps/gui
```
That will run Pi-Apps as normal, but now the terminal will catch any errors.  
Please copy out the full terminal output and post it here.

**Comment by Botspot** [comment]
@CoderLogy Any updates?

**Comment by CoderLogy** [comment]
Yes when did that what you told but there was error shown that no data
found in terminal so pls help me in this

**Comment by Botspot** [comment]
> Yes when did that what you told but there was error shown that no data found in terminal so pls help me in this

Sorry, I need more details than that. Could you send me a screenshot of the error?

**Comment by CoderLogy** [comment]
Ok I will send it

**Comment by gilesn** [comment]
Hello, Same here, nothing is installed (using latest RP OS, Linux raspberrypi4 5.4.77-v8+) 

I get this output:

```
xterm: bad command line option "--title=Installing Chromium Widevine"

usage:  xterm [-/+132] [-C] [-Sccn] [-T string] [-/+ah] [-/+ai] [-/+aw]
    [-b number] [-baudrate rate] [-/+bc] [-bcf milliseconds]
    [-bcn milliseconds] [-bd color] [-/+bdc] [-bg color] [-bw number] [-/+cb]
    [-cc classrange] [-/+cjk_width] [-class string] [-/+cm] [-/+cn] [-cr color]
    [-/+cu] [-/+dc] [-display displayname] [-e command args ...] [-fa pattern]
    [-fb fontname] [-/+fbb] [-/+fbx] [-fd pattern] [-fg color] [-fi fontname]
    [-fn fontname] [-fs size] [-/+fullscreen] [-fw fontname] [-fwb fontname]
    [-fx fontname] [%geom] [#geom] [-geometry geom] [-help] [-/+hm] [-/+hold]
    [-iconic] [-/+ie] [-/+im] [-into windowId] [-/+itc] [-/+j] [-/+k8]
    [-kt keyboardtype] [-/+l] [-/+lc] [-lcc path] [-leftbar] [-lf filename]
    [-/+ls] [-/+maximized] [-/+mb] [-mc milliseconds] [-/+mesg] [-/+mk_width]
    [-ms color] [-n string] [-name string] [-nb number] [-/+nul] [-/+pc]
    [-/+pob] [-report-charclass] [-report-colors] [-report-fonts] [-rightbar]
    [-/+rv] [-/+rvc] [-/+rw] [-/+s] [-/+samename] [-/+sb] [-selbg color]
    [-selfg color] [-/+sf] [-sh number] [-/+si] [-/+sk] [-sl number] [-/+sm]
    [-/+sp] [-/+t] [-ti termid] [-title string] [-tm string] [-tn name] [-/+u8]
    [-/+uc] [-/+ulc] [-/+ulit] [-/+ut] [-/+vb] [-version] [-/+wc] [-/+wf]
    [-xrm resourcestring] [-ziconbeep percent]

Type xterm -help for a full description.
```

**Comment by Botspot** [comment]
@gilesn That is a very useful error output! Thanks for sharing.

Basically, whenever Pi-Apps wants to open a terminal, it uses a command called `x-terminal-emulator`. This command launches the default terminal emulator for the OS.  
Raspbian has `lxterminal` as default.  
TwisterOS uses `xfce4-terminal`.  
Other OS'es use `mate-terminal`.  
Apparently your OS uses `xterm`.

Looks like `xterm` doesn't know what to do with the `--title` flag. Interesting.  
Looks like I'll have to revisit the terminal-running code, and have it change the command based on which terminal `x-terminal-emulator` chooses to use.

In the meantime @gilesn , you can set `lxtermin`l back to being the default terminal by running this:

    sudo apt install --reinstall lxterminal

**Comment by Botspot** [comment]
Turns out #90 was caused by this same issue.

The OP in that issue report has `lxterm` as their default terminal.

**Comment by Botspot** [comment]
Okay, I think I've fixed this issue as of commit a28ec27c733c536a72506feb7bfde62eff48551f.

**Comment by gilesn** [comment]
> Okay, I think I've fixed this issue as of commit [a28ec27](https://github.com/Botspot/pi-apps/commit/a28ec27c733c536a72506feb7bfde62eff48551f).

Great, it's working so I'll leave my default terminal as-is.

**Comment by Botspot** [comment]
Glad it worked for you @gilesn , and as for @CoderLogy , could you paste the error message? Or maybe a screenshot?

**Comment by fabianmendes** [comment]
I was trying to install an app, any from Pi-apps list, and it says:

Using LXterminal:
`cat: /home/pi/Downloads/git/pi-apps/data/status/Zoom: Directory or folder doesn't exist.`

And running XTerm terminal instead:
`Timestamp match.`
`Reading list file...`

Of course, doesn't happen. Any app wasn't installing. Should I reinstall the Pi-app? How can I do that??

**Comment by Botspot** [comment]
> I was trying to install an app, any from Pi-apps list, and it says:
> 
> Using LXterminal:
> `cat: /home/pi/Downloads/git/pi-apps/data/status/Zoom: Directory or folder doesn't exist.`
> 
> And running XTerm terminal instead:
> `Timestamp match.`
> `Reading list file...`
> 
> Of course, doesn't happen. Any app wasn't installing. Should I reinstall the Pi-app? How can I do that??

Unfortunately, neither of those error messages is particularly helpful.  
@fabianmendes Could you try installing Pi-Apps using the official install instructions?
```
git clone https://github.com/Botspot/pi-apps
~/pi-apps/install
```

**Comment by fabianmendes** [comment]
Sure, I will. Thanks for replying so fast!! Otherwise, I've just edited my last comment. May you please look forward to it?

I'll run that code.:
> > I was trying to install an app, any from Pi-apps list, and it says:
> > Using LXterminal:
> > `cat: /home/pi/Downloads/git/pi-apps/data/status/Zoom: Directory or folder doesn't exist.`
> > And running XTerm terminal instead:
> > `Timestamp match.`
> > `Reading list file...`
> > Of course, doesn't happen. Any app wasn't installing. Should I reinstall the Pi-app? How can I do that??
> 
> Unfortunately, neither of those error messages is particularly helpful.
> @fabianmendes Could you try installing Pi-Apps using the official install instructions?
> 
> ```
> git clone https://github.com/Botspot/pi-apps
> ~/pi-apps/install
> ```

**Comment by fabianmendes** [comment]
should I reinstall the already installed apps? (They appear on the GUI Pi-Apps as they aren't installed)

**Comment by Botspot** [comment]
> should I reinstall the already installed apps? (They appear on the GUI Pi-Apps as they aren't installed)

No, they are actually installed, but Pi-Apps doesn't know better.

Simply copy over your old data directory from your old location to the new one.
Something like this:
```
gio trash /home/pi/pi-apps/data
cp -a /home/pi/Downloads/git/pi-apps/data /home/pi/pi-apps
```

**Comment by fabianmendes** [comment]
![2020-11-25-225735_800x480_scrot](https://user-images.githubusercontent.com/31230743/100302930-bc2fef00-2f71-11eb-8661-d712cda1fae5.png)

It's happening the same thing :L
And at first, I've tried to install TBOplayer, and on the very first try it said  _Permisson Denied_, then I've run Pi-apps GUI from the terminal using _sudo_, and then try out to install TBOplaye again but it gave me the next same message:
`cat: /home/pi/Downloads/git/pi-apps/data/status/TBOPlaye: Directory or folder doesn't exist.`
(I'm trying to install ZOOM and TBOPlayer)

|
Ok, sure:

> > should I reinstall the already installed apps? (They appear on the GUI Pi-Apps as they aren't installed)
> 
> No, they are actually installed, but Pi-Apps doesn't know better.
> 
> Simply copy over your old data directory from your old location to the new one.
> Something like this:
> 
> ```
> gio trash /home/pi/pi-apps/data/status
> cp -a /home/pi/Downloads/git/pi-apps/data/status /home/pi/pi-apps/data
> ```
> 
> The first command moves the empty data directory to Trash, and the command command copies the new version.

**Comment by fabianmendes** [comment]
Nevermind! Seems to be an Internet Connection problem!!

It's installing now, thank you @Botspot !

**Comment by Botspot** [comment]
> cat: /home/pi/Downloads/git/pi-apps/data/status/TBOPlaye: Directory or folder doesn't exist.

That's strange. Did you select TBOPlayer from the Pi-Apps list, and then click the Install button?

**Comment by fabianmendes** [comment]
Sorry, where should I see Zoom after installing it? There is not in any category from my Raspberry Pi menu :$

**Comment by Botspot** [comment]
> Sorry, excuse me. Where should I see Zoom after installing it? There is not in any category from my Raspberry Pi menu :$

Maybe it didn't install correctly. Please open a new issue for that.

**Comment by CoderLogy** [comment]
My problem I am able to download but problem is I have downloaded libreelec
it doesn't show on screen after install and also it cosnsumed lot of space
even after I have deleted it

**Comment by Botspot** [comment]
> My problem I am able to download but problem is I have downloaded libreelec it doesn't show on screen after install and also it cosnsumed lot of space even after I have deleted it

Sounds like you are talking about libreelec os.  
How is this related to Pi-Apps?

**Comment by CoderLogy** [comment]
It's not libreelec os I am talking about libreelec pcb pls solve my problem

**Comment by Botspot** [comment]
I haven't found anybody who understands what @CoderLogy is talking about, so I'm closing this issue for now.

@CoderLogy if you're still having a problem with Pi-Apps, please open a new issue and explain exactly what is going on for you.

**Comment by CoderLogy** [comment]
Ok

**Comment by CoderLogy** [comment]
Close it my problem solved
