### ISSUE TITLE
talktosrinivasan its done

### ISSUE THREAD

**Issue by srini-pro** [Botspot/pi-apps#521]
[talktosrinivasan.zip](https://github.com/Botspot/pi-apps/files/6240823/talktosrinivasan.zip)
better thaan redirecting link

**Comment by srini-pro** [comment]
heloo didnt people got hyped for ths?

**Comment by Itai-Nelken** [comment]
A few problems I found:
- the `install-32` script is blank, it does nothing and will fail.
- the `install-64` script needs a lot of work:     It has to move the desktop shortcut by itself.
It needs to have the pi-apps stuff at the top and its very recommended to use the error function included there.
- the description needs some work.

**Comment by Itai-Nelken** [comment]
Also the only file in the repo you are cloning is a invalid .desktop file (it looks like a bash script).

**Comment by Botspot** [comment]
> Also the only file in the repo you are cloning is a invalid .desktop file (it looks like a bash script).

I noticed that too. The script that you run, creates a desktop file, and inside the desktop file, is the same script you just ran! :O  
I've not seen anything like this before. The script seems to be like paradox almost. Very similar to the ["freepage" issue](https://github.com/Botspot/pi-apps/issues/523) by @srini-pro as well.

**Comment by CleanMachine1** [comment]
I have looked at it as well, all of this does absolutely nothing other than install some junk scripts that install themselves
I feel this guy is just trying to be a contributor  

Personally, I would close this issue as its just spam.

**Comment by CleanMachine1** [comment]
Code isn't templates of things 

If you are going to make a program to use facebook, don't just make some directories and download a git repo to nothing

**Comment by Botspot** [comment]
> Personally, I would close this issue as its just spam.

Unfortunately, I would have to agree - looks like spam to me.

**Comment by srini-pro** [comment]
spam?

**Comment by srini-pro** [comment]
ohh code is beta

**Comment by CleanMachine1** [comment]
Difference between beta and nothing,,,

Anyone can write 5 lines of pointless bash script which uses C:/ on linux.....
