### ISSUE TITLE
'

### ISSUE THREAD

**Issue by thanick49** [Botspot/pi-apps#522]
i just unstall pi-app 
and can't reinstall
 404  Not Found [IP: 2001:67c:1360:8001::24 80]
sorry for my bad english

**Comment by thanick49** [comment]
> i just unstall pi-app
> and can't reinstall
> 404 Not Found [IP: 2001:67c:1360:8001::24 80]
> sorry for my bad english

**Comment by Itai-Nelken** [comment]
Are you dure you are connected to the internet?
Also why did you close this issue?
