### ISSUE TITLE
free web

### ISSUE THREAD

**Issue by srini-pro** [Botspot/pi-apps#523]
https://github.com/free-page/freepage

**Comment by Botspot** [comment]
Wow, the readme is very unhelpful. It's only a link to itself. What is "freepage"?

And wow, the `freepage.sh` script seems poorly written and is paradoxical. It clones its own git repository, but only contains an installation script that installs itself.  
What is this supposed to do?

**Comment by CleanMachine1** [comment]
What are you trying to achieve other than wasting time...

**Comment by CleanMachine1** [comment]
Batch scripts on linux isn't a thing to my knowledge

**Comment by srini-pro** [comment]
updated it

**Comment by CleanMachine1** [comment]
It does NOTHING

**Comment by CleanMachine1** [comment]
May I ask, what does that mean exactly. Can you ban users from repos'.

Having a look at his profile,  it shows loads of repos' with similar scripts that do nothing like scripts with misspelled commands.

**Comment by Botspot** [comment]
> Having a look at his profile, it shows loads of repos' with similar scripts that do nothing like scripts with misspelled commands.

Yes, I noticed that too.

> May I ask, what does that mean exactly? Can you ban users from repos?

I banned him Botspot-wide using Github's ["Block users" page](https://github.com/settings/blocked_users).  
> ![2021-04-05-104619_1920x1080_scrot](https://user-images.githubusercontent.com/54716352/113593703-57119780-95fc-11eb-94ab-7fe6081fe332.png)
