### ISSUE TITLE
xlunch looks noice!

### ISSUE THREAD

**Issue by GabeCoder** [Botspot/pi-apps#524]
Since there isn’t a discussions tab in this repo, I’m just gonna say that, WOW! XLUNCH LOOKS AMAZING!

**Comment by Botspot** [comment]
> Since there isn’t a discussions tab in this repo, I’m just gonna say that, WOW! XLUNCH LOOKS AMAZING!

Thanks! :)

I think it's especially useful when you delete all the categories and can search for all apps.  
Issues like this one are always welcome. ;)

> Since there isn’t a discussions tab in this repo

Do you use [Discord](https://discord.gg/RXSTvaUvuu)? [That](https://discord.gg/RXSTvaUvuu) is currently the only discussion forum for Pi-Apps, Pi Power Tools, vdesktop, youtubuddy, and other RPi-related stuff.
