### ISSUE TITLE
Pi compatibly show for apps

### ISSUE THREAD

**Issue by 0Dragonmoon** [Botspot/pi-apps#525]
Not every app on pi apps is compatible with every pi, I think it would be good idea to list supported pis for the app you click on. For example wine with box86 doesn’t work on pi 1 b+ but pi apps installs it.
Good luck and cheers.

**Comment by CleanMachine1** [comment]
Easy enough to do, if someone makes a list of everything that works I'll add it to all of the descriptions.

**Comment by Itai-Nelken** [comment]
It would be better to just hide the apps as almost no one reads the description.
You can get the rpi model name ftom /proc/cpuinfo.
The code that does that can be added to the `gui` script and run only once uwing the `runonce` function.

**Comment by CleanMachine1** [comment]
That is a better solution.

Yet it will probably be a bit of work, and I cannot help with that as I wouldn't know where to start 

Best solution I can think of is using the mentioned gui file as well as making a new file in every app with a file called cpu to mark them.

**Comment by Botspot** [comment]
Some problems I have with automatically hiding apps on Pi Zero and Pi1:

- It would take significant effort, testing each app at a time. (and testing all new apps from now on)
- It would mean another file added to each app, and yet another option you must choose in the App Maker.
- I don't have any armv6 devices, and so would have to ask others to test new apps on their Pi Zero.
- Making such a move may only open the door for more requests to dynamically hide apps. Where do we draw the line? Other example requests include:
  - "You should hide Chinese apps if users choose a different language."
  - "You should hide themes that don't work on XFCE."
  - "You should hide apps that are too big to fit on the sd card."
  - "Your apps should be able to individually choose when to be visible."
  - "Your apps should hide themselves if the the Pi model is too slow to run the game."

Each of those features would mean more files added to each app folder. And how many people would benefit from Pi Zero app-hiding? Few. Pi-Apps is intended for desktop users. Nearly all of them use Pi3s or Pi4s. Not many apps would run well on a Pi Zero I think.

**Comment by CleanMachine1** [comment]
Also I just have just realised, who really is using desktop on a low powered pi?
I retract the need for this, and as you have mentioned it just an annoyance not worth the time.
