### ISSUE TITLE
KDiskMark

### ISSUE THREAD

**Issue by hmsjy2017** [Botspot/pi-apps#526]
https://github.com/JonMagon/KDiskMark
It can test the disk speed and display it intuitively. It is difficult to find similar tools that support ARM Linux. It is similar to CrystalDiskMark on the Windows platform.
I think that it is really useful.
![5CE161F5-FA52-48D3-8114-BBB866884EF1](https://user-images.githubusercontent.com/42692274/113489980-f437d780-94f9-11eb-92f6-4d4cdc0972cd.png)
This software can be installed via PPA.
https://launchpad.net/~jonmagon/+archive/ubuntu/kdiskmark
It provides both armhf and arm64 packages.

**Comment by Botspot** [comment]
```
pi@raspberrypi:~ $ sudo add-apt-repository ppa:jonmagon/kdiskmark
Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 95, in <module>
    sp = SoftwareProperties(options=options)
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 109, in __init__
    self.reload_sourceslist()
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 599, in reload_sourceslist
    self.distro.get_sources(self.sourceslist)    
  File "/usr/lib/python3/dist-packages/aptsources/distro.py", line 93, in get_sources
    (self.id, self.codename))
aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for Raspbian/buster
```

**Comment by hmsjy2017** [comment]
Installing directly from the binary file may be a better option.
https://launchpad.net/~jonmagon/+archive/ubuntu/kdiskmark/+files/kdiskmark_2.2.0-3_arm64.deb
https://launchpad.net/~jonmagon/+archive/ubuntu/kdiskmark/+files/kdiskmark_2.2.0-3_armhf.deb

**Comment by Botspot** [comment]
> Installing directly from the binary file may be a better option.
> https://launchpad.net/~jonmagon/+archive/ubuntu/kdiskmark/+files/kdiskmark_2.2.0-3_arm64.deb
> https://launchpad.net/~jonmagon/+archive/ubuntu/kdiskmark/+files/kdiskmark_2.2.0-3_armhf.deb

Any ideas?
```
Note, selecting 'kdiskmark' instead of '/home/pi/kdiskmark.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 kdiskmark : Depends: libkf5authcore5 (>= 5.56.0) but it is not installable
             Depends: libqt5core5a (>= 5.14.1) but 5.11.3+dfsg1-1+rpi1+deb10u4 is to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by hmsjy2017** [comment]
This may be because the packages that KDiskMark depends on are not in the Raspbian source, you can try to install these two packages manually:
http://ftp.hk.debian.org/debian/pool/main/k/kauth/libkf5authcore5_5.78.0-2_armhf.deb
http://ftp.hk.debian.org/debian/pool/main/q/qtbase-opensource-src/libqt5core5a_5.15.2+dfsg-5_armhf.deb

**Comment by Botspot** [comment]
> This may be because the packages that KDiskMark depends on are not in the Raspbian source, you can try to install these two packages manually

Hmm...
```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libkf5authcore5 : Depends: libkf5auth-data (= 5.78.0-2) but 5.54.0-2 is to be installed
                   Depends: libkf5coreaddons5 (>= 5.78.0~) but 5.54.0-1 is to be installed
                   Depends: libpolkit-qt5-1-1 (>= 0.113.0) but it is not going to be installed
                   Depends: libqt5dbus5 (>= 5.14.0~) but it is not going to be installed
                   Depends: libqt5widgets5 (>= 5.14.0~) but it is not going to be installed
 libqt5core5a : Depends: libc6 (>= 2.29) but 2.28-10+rpi1 is to be installed
                Depends: libdouble-conversion3 (>= 2.0.0) but it is not installable
                Depends: libicu67 (>= 67.1-1~) but it is not installable
                Depends: libstdc++6 (>= 10) but 8.3.0-6+rpi1 is to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by Itai-Nelken** [comment]
now if you download the debs for those dependencies you will need to download the debs for the dependencies of the dependencies and so on until something will break or you give up or you end up with a super long list of packages that might conflict on some systems, in other words dependency hell...

**Comment by hmsjy2017** [comment]
@Botspot The developer of this software suggested that we compile it ourselves, which might solve the dependency problem.

**Comment by chunky-milk** [comment]
> now if you download the debs for those dependencies you will need to download the debs for the dependencies of the dependencies and so on until something will break or you give up or you end up with a super long list of packages that might conflict on some systems, in other words dependency hell...

@Itai-Nelken don't get me started on the dependencies of libc6...

**Comment by CleanMachine1** [comment]
You would still need the libraries to install, are they in the repo or are they the same dependencies that we are missing.

Also, although it is not as good a benchmark by a long shot, using dd to make a 1gb file is good enough since dd tells you write speed, then to get a read speed you can read the file into /dev/null (Remember to clear the dd cache thing overwise the results wont be accurate to the disk

**Comment by mobilegmYT** [comment]
@hmsjy2017 You mentioned crystaldiskmark before. Why don't we just run that with wine? I've done that before and it runs fine.

**Comment by hmsjy2017** [comment]
@mobilegmYT Although it is possible to do this, I am worried that there may be a performance loss when running through wine, which will make the test results inaccurate.

**Comment by CleanMachine1** [comment]
I wouldn't have thought so, however will it run at all.

Does wine feed /dev/sda and others to the application layer, or does it give it virtual harddrives

**Comment by hmsjy2017** [comment]
@Botspot I built it successfully.
![E7C583C9-A290-489D-B31F-9FA00A3ED6E4](https://user-images.githubusercontent.com/42692274/118359749-8c27e700-b5b7-11eb-8433-e403a602c880.png)

**Comment by CleanMachine1** [comment]
Does it work?

**Comment by hmsjy2017** [comment]
@CleanMachine1 These are some problems.
![18CA16BA-7EFC-48CA-8D7A-E6A130952E30](https://user-images.githubusercontent.com/42692274/118362954-9dc3bb80-b5c4-11eb-883f-4e3736e5e927.png)

**Comment by hmsjy2017** [comment]
@CleanMachine1 There is the compiled file:[KDiskMark.zip](https://github.com/Botspot/pi-apps/files/6487558/KDiskMark.zip)

**Comment by theofficialgman** [comment]
closing as I don't think this software can be trusted on ARM systems with low single threaded performance
I have an issue at the repo that has stood for a year where all `fio` threads spawn on the same core, leading to significantly worse benchmark performance than just testing with `fio` itself. this is a blocking issue

https://github.com/JonMagon/KDiskMark/issues/50

if this issue is fixed, this can be re-opened and a buildscript or debs can be made as the software otherwise is very nice
