### ISSUE TITLE
Drawing

### ISSUE THREAD

**Issue by hmsjy2017** [Botspot/pi-apps#528]
https://github.com/maoschanz/drawing
A drawing application for the GNOME desktop. It is similar to Microsoft Paint.
![7A11B813-95C8-45A2-B9E3-3F1A964D0A79](https://user-images.githubusercontent.com/42692274/113490527-357db680-94fd-11eb-9c6a-3f9bcf084283.png)
It can run normally.
You can install it via PPA (armhf and arm64).
https://launchpad.net/~cartes/+archive/ubuntu/drawing/
It seems to be available from FlatHub, but I haven't tested it.
https://flathub.org/apps/details/com.github.maoschanz.drawing

**Comment by Botspot** [comment]
```
pi@raspberrypi:~ $ sudo add-apt-repository ppa:cartes/drawing
Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 95, in <module>
    sp = SoftwareProperties(options=options)
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 109, in __init__
    self.reload_sourceslist()
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 599, in reload_sourceslist
    self.distro.get_sources(self.sourceslist)    
  File "/usr/lib/python3/dist-packages/aptsources/distro.py", line 93, in get_sources
    (self.id, self.codename))
aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for Raspbian/buster
```

**Comment by Itai-Nelken** [comment]
I think a better idea would be to just download the deb from that ppa.

**Comment by Botspot** [comment]
> I think a better idea would be to just download the deb from that ppa.

I wonder if PPAs are broken on RPi?

**Comment by hmsjy2017** [comment]
You can download deb packages directly.
https://launchpad.net/~cartes/+archive/ubuntu/drawing/+files/drawing_0.6.5-0ubuntu1~groovy_armhf.deb
https://launchpad.net/~cartes/+archive/ubuntu/drawing/+files/drawing_0.6.5-0ubuntu1~groovy_arm64.deb

**Comment by hmsjy2017** [comment]
> > I think a better idea would be to just download the deb from that ppa.
> 
> I wonder if _all_ PPAs are broken on RPi?

The problem that Raspberry/stable cannot be found is because add-apt-repository will extract the ID and version model of the current linux system. As a result, when the Raspberry Pi model name does not match the address name in the mirror source, the download cannot be automatically added. source. So it needs to be added manually.

**Comment by Itai-Nelken** [comment]
ppa's are just simple apt repos I think.

**Comment by Botspot** [comment]
I was able to get it to work by running this:
```bash
wget https://launchpad.net/~cartes/+archive/ubuntu/drawing/+files/drawing_0.6.5-0ubuntu1~groovy_armhf.deb -O drawing.deb && sudo apt install -fy ~/drawing.deb
```
@hmsjy2017 I have no problem adding this, but I do have several questions about it.
- Is this something that a lot of people would prefer to use, *over* Kolourpaint? (IMO, Kolourpaint is much closer to MS Paint, and has more features.)
- Does this app have a more specific name than "Drawing"?
- Does this app have an icon? (I noticed it didn't have an icon, both in the menu and in the task bar.)

**Comment by hmsjy2017** [comment]
- I think adding a similar software can provide users with more choices. Kolourpaint does have more features than Drawing and is more like MS Paint. But I think that the interface of Drawing is more concise, it takes up less disk space, and it is constantly being improved. For me, the function of Painting is also sufficient.
- No.
- This may be a bug.

**Comment by Botspot** [comment]
> * This may be a bug. But when I installed it, there was an icon in the menu, but not in the taskbar. **This question has been submitted to _the official_.**

What was the end result of your efforts?

**Comment by Botspot** [comment]
@hmsjy2017 Could you please reply back?

**Comment by hmsjy2017** [comment]
@Botspot Sorry, I haven't seen your reply before.
Developers have added support for LXDE. Maybe the problem of missing icons has been resolved.
https://github.com/maoschanz/drawing/issues/358

**Comment by Botspot** [comment]
> @Botspot Sorry, I haven't seen your reply before.
> Developers have added support for LXDE. Maybe the problem of missing icons has been resolved.

Thanks for replying. :)
It works well!
```
wget https://launchpadlibrarian.net/535392140/drawing_0.8.0-0ubuntu1~focal_armhf.deb
sudo apt install -yf ~/drawing_0.8.0-0ubuntu1_focal_armhf.deb
```

**Comment by Botspot** [comment]
App has been added.
