### ISSUE TITLE
add: USBImager

### ISSUE THREAD

**Issue by Itai-Nelken** [Botspot/pi-apps#53]
[USBImager.zip](https://github.com/Botspot/pi-apps/files/5475509/USBImager.zip)
there is a arm64 version, but I couldn't find out how to install it.

**Comment by Itai-Nelken** [comment]
I figured out how to compile it, I'll try compiling the arm64 version tomorrow

**Comment by Botspot** [comment]
Are you sure that's necessary? For USBImager, it has an arm64 release that you simply extract to /usr/.

**Comment by mobilegmYT** [comment]
BalenaEtcher does the exact same things as this and it's already in pi-apps.

**Comment by Botspot** [comment]
> BalenaEtcher does the exact same things as this and it's already in pi-apps.

@mobilegmYT If you start using that logic, wasn't Pi-Power-Tools here long before either Etcher or USBImager? (Pi-Power-Tools has a fully-functional flasher built-in)

**Comment by Itai-Nelken** [comment]
> Are you sure that's necessary? For USBImager, it has an arm64 release that you simply extract to /usr/.

yes, but it didn't work for me

**Comment by Itai-Nelken** [comment]
[USBImager.zip](https://github.com/Botspot/pi-apps/files/5480590/USBImager.zip)

@Botspot I wrote a install script for the 64bit version, but the uninstall script has to be modified to remove the _share_ and _bin_ directories and the menu shortcut from _/usr/share/applications/usbimager.desktop_

**Comment by Itai-Nelken** [comment]
[USBImager.zip](https://github.com/Botspot/pi-apps/files/5486343/USBImager.zip)
I decided to compile and package to a .deb file the 64bit version so that they can be removed with the same script.
I'm sure there is a different way of doing it, but I couldn't think of anything else I can do.

**Comment by Botspot** [comment]
Very good! Only issue I could find was your `install-64` script was not executable. After fixing that, it works great!

**Comment by Botspot** [comment]
Added with commit 3d61f713573ba591aba50c32dd95c9df2f845b37.

**Comment by Itai-Nelken** [comment]
great
