### ISSUE TITLE
Etcher

### ISSUE THREAD

**Issue by hmsjy2017** [Botspot/pi-apps#530]
https://www.raspberrypi.org/forums/viewtopic.php?f=62&t=255205&start=25&sid=772abfdc391c9c0270b30873a4c80ec8
GitHub: https://github.com/futurejones/balena-etcher-arm
![D0D008A3-A188-49D6-A651-FA3A921AB361](https://user-images.githubusercontent.com/42692274/113491137-05381700-9501-11eb-9ece-de5c5c49a24e.png)
Install package is available.
https://github.com/futurejones/balena-etcher-arm/releases/tag/v1.5.63
Or install  via PackageCloud.
https://packagecloud.io/swift-arm/etcher
But they are not the latest version. The latest version needs to be compiled by yourself.
The build  instructions are here.
https://github.com/futurejones/balena-etcher-arm/blob/master/etcher-build/README.md

**Comment by Itai-Nelken** [comment]
Etcher is already on pi-apps, and its the newest version.
