### ISSUE TITLE
Issue with categories on Twister OS Lite

### ISSUE THREAD

**Issue by mobilegmYT** [Botspot/pi-apps#534]
Recently after a new update, I saw that hidden apps on Twister Lite were made visable. Issue is that the apps dont go in categories. This is still happens after reinstalling pi-apps

![image](https://user-images.githubusercontent.com/44128563/113514107-003b8d80-952a-11eb-96c4-9ef9c852768e.png)

**Comment by mobilegmYT** [comment]
Fixed in https://github.com/Botspot/pi-apps/commit/cb0367e36f6829846bf46a95b701a5727c63d29f

**Comment by Botspot** [comment]
Should be fixed now. cb0367e36f6829846bf46a95b701a5727c63d29f

I've added a new functionality to `categoryedit`: the `--delete` flag.  
Using `--delete`, you can remove an app entirely from the category file. Then the app will be reset to its original online-default category next time Pi-Apps launches.
