### ISSUE TITLE
Provide the I18n translations

### ISSUE THREAD

**Issue by hmsjy2017** [Botspot/pi-apps#535]
Pi-Apps is a good software, it makes it easy for people to install commonly used software. However, this software is in English, which may not be convenient for non-native English speakers to use. So I think localizing this software might be a good choice.😄

**Comment by CleanMachine1** [comment]
basically impossible, also this isn't a problem with Pi-Apps, its a problem with standards with applications E.G. VSCode which provides language packs while other applications might not

**Comment by Botspot** [comment]
> Pi-Apps is a good software, it makes it easy for people to install commonly used software. However, this software is in English, which may not be convenient for non-native English speakers to use. So I think localizing this software might be a good choice.😄

I've been dreading the day someone would ask for this. :(

While such a feature would benefit a good number of users, it would be very hard & tedious to do. Every piece of text within all the scripts would have to be put within a long string of if/then statements. How do other programs do it? It sounds like a nightmare to implement.

**Comment by hmsjy2017** [comment]
Is it possible to make language packs like VS Code does, and let users install them by themselves?

**Comment by CleanMachine1** [comment]
Depends on the app

**Comment by Botspot** [comment]
> Is it possible to make language packs like VS Code does, and let users install them by themselves?

Now it's a bit unclear what @hmsjy2017 is asking for.  
@hmsjy2017, are you asking for the Pi-Apps interface to support multiple languages? To that, I say "Very hard to do, and very hard to maintain."  
Or are you asking if Pi-Apps can install individual apps and let you choose a language pack for each app?

**Comment by hmsjy2017** [comment]
I am asking about the former.

**Comment by hmsjy2017** [comment]
I think it may be a good choice to create a localized branch for each language. Each branch is maintained separately, which may solve the problem of difficult maintenance.

**Comment by Botspot** [comment]
> I am asking about the former.

Okay then. To do that, I'd have to go through *every single* Pi-Apps script, and translate all text strings into the desired language. (All the text strings are hard-coded directly in the scripts, there's no such thing as a language pack)
Furthermore, if you wanted to easily switch languages, I'd have to create hundreds of `if/then` statements throughout the scripts for every piece of text found anywhere.

In addition to changing all the scripts, I'd also have to create another repo for the Pi-Apps "message of the day", the donate message, the README + wiki, and create different install/uninstall icons that have been translated. This would be a tremendous undertaking.

**Comment by CleanMachine1** [comment]
Maybe a simpler approach would be adding a list of major languages supported by the app

And maybe a link for the user to find out how to change the language of that particular app

**Comment by CleanMachine1** [comment]
Making work as only apps that would have this list would be ones with built in features such as VsCOde

**Comment by hmsjy2017** [comment]
OK. But I think it shouldn’t be difficult to just translate the README and Wiki. These can be done by me.

**Comment by Botspot** [comment]
> OK. But I think it shouldn’t be difficult to just translate the README and Wiki. These can be done by me.

Sure you can do that. But how do you suggest both READMEs be stored in the same pi-apps repo?

**Comment by CleanMachine1** [comment]
More if statements!

**Comment by hmsjy2017** [comment]
I think it's easy, you can create a README-zh_CN.md for Simplified Chinese.

**Comment by CleanMachine1** [comment]
Give me a minute and I'll create a repo with an english README and a chinese with just hello

**Comment by hmsjy2017** [comment]
I think you can put the name of the language on the project homepage, like this:
![A366DEC8-8723-4684-BE1A-5C8683A7898B](https://user-images.githubusercontent.com/42692274/113742578-529cca00-9735-11eb-8c1f-aa4706b0df3b.jpeg)

**Comment by CleanMachine1** [comment]
thats a better idea, however could you tell me if you see hello in chinese or english!
https://github.com/CleanMachine1/readmelangtest

**Comment by hmsjy2017** [comment]
In Chinese.

**Comment by CleanMachine1** [comment]
On the main page or when you click on the chinese one?
Sorry for having to ask this, I wasn't clear in my original question!

**Comment by hmsjy2017** [comment]
When I click on the Chinese one.

**Comment by CleanMachine1** [comment]
Ok thanks for the assistance!

I dont have any control of this repo, however I am sure botspot would be willing to have the option to just click a button to load a README in a different language

**Comment by Botspot** [comment]
> Ok thanks for the assistance!
> 
> I dont have any control of this repo, however I am sure botspot would be willing to have the option to just click a button to load a README in a different language

That sounds reasonable to me. A button in the English readme to go to a translated readme sounds fine.

**Comment by CleanMachine1** [comment]
@Botspot do you have any friends or maintainers that speak different languages or even your self?

I am sure now this issue has been raised that we could get some documentation in different languages.

**Comment by Botspot** [comment]
> @Botspot do you have any friends or maintainers that speak different languages or even your self?

I have no idea. Maybe @mobilegmYT knows?

**Comment by mobilegmYT** [comment]
I know chinese.

**Comment by Itai-Nelken** [comment]
I know spanish, but am really bad at writing in it...

**Comment by mobilegmYT** [comment]
> I know spanish, but am really bad at writing in it...

Google translate it and make sure the grammar sounds right

**Comment by CleanMachine1** [comment]
Google translate is far from perfect.

It doesn't cut it, we need 2-3 speakers of each to review it all

**Comment by Itai-Nelken** [comment]
I can translate it with help from Gtranslate to spanish and then we can ask someone who knows better to fix anything thats wrong.
but TBH I prefer not to translate it as it will take me a ton of time that I don't have.

**Comment by CleanMachine1** [comment]
Could we ask the maker of PiKISS for spanish?

I understand its a little rude to ask but hes a fluent speaker to my knowledge 

We should work on covering:
Spanish
French (maybe)
Chinese

**Comment by CleanMachine1** [comment]
@hmsjy2017 Do you plan on doing the Chinese?

**Comment by hmsjy2017** [comment]
@CleanMachine1 Yes, I plan to translate it when I have free time.

**Comment by CleanMachine1** [comment]
Ok

**Comment by Botspot** [comment]
https://github.com/Botspot/pi-apps/pull/583
