### ISSUE TITLE
BlockPi

### ISSUE THREAD

**Issue by hmsjy2017** [Botspot/pi-apps#536]
Open source Raspberry Pi graphical programming platform
https://github.com/alienzhangyw/BlockPi
![10DB38BD-C57E-4810-A27B-7C7769BEC696](https://user-images.githubusercontent.com/42692274/113515369-afb64580-95a6-11eb-947e-07d0734043b5.png)
arm64: https://github.com/alienzhangyw/BlockPi/releases/download/v1.1.5/blockpi_1.1.5_arm64.deb
armhf: https://github.com/alienzhangyw/BlockPi/releases/download/v1.1.5/blockpi_1.1.5_armv7l.deb

**Comment by Itai-Nelken** [comment]
I think scratch looks better

**Comment by Botspot** [comment]
> I think scratch looks better

At first glance, this looks like it may contain features not found in Scratch.

**Comment by Itai-Nelken** [comment]
I didn't mean its worse, I meant I personally like the l9ok of scratch better.

**Comment by Botspot** [comment]
This has been added to pi-apps with commit 4002c0e8796ac917e83bbaaaffbe5201a28fb639
