### ISSUE TITLE
sudo apt update fails due to unsigned buster-backports repo

### ISSUE THREAD

**Issue by MasterLink151** [Botspot/pi-apps#537]
After an update through Pi-Apps, Minecraft bedrock would not boot up. It said through Pi-apps that it was not installed. I then tried to reinstall it but it would not install. It said "failed to run sudo apt update". I tried to install other apps and some of them installed like FreeTube but other apps had the same error such as Steam. If you could fix this I would really appreciate it. Thanks.

**Comment by mobilegmYT** [comment]
> After an update through Pi-Apps, Minecraft bedrock would not boot up. It said through Pi-apps that it was not installed. I then tried to reinstall it but it would not install. It said "failed to run sudo apt update". I tried to install other apps and some of them installed like FreeTube but other apps had the same error such as Steam. If you could fix this I would really appreciate it. Thanks.

Please send a screenshot of the error

**Comment by MasterLink151** [comment]
![2021-04-04-184623_1360x768_scrot](https://user-images.githubusercontent.com/81928420/113523603-854c9400-9576-11eb-9d48-bc2890f06361.png)

**Comment by Botspot** [comment]
It appears Minecraft Bedrock was not fully installed the last time you tried to install it.

Uninstall Minecraft Bedrock. At this point, if you run `sudo apt update`, it should work.  
Then install Minecraft Bedrock again. Report back the results, and thank you for using Pi-Apps! :)

**Comment by MasterLink151** [comment]
It still gives the same results.

**Comment by GabeCoder** [comment]
```sudo apt``` may be broken, so you'll want to run ```sudo apt --fix-broken install``` in order to fix it. I've tried it on an RPi and it managed to fix everything. Once you do that, APT should function properly again.

**Comment by Itai-Nelken** [comment]
@MasterLink151 run `cat /etc/apt/sources.list`

**Comment by Botspot** [comment]
Wait a second, I was mixing two things up!  
Minecraft **_Pi_** uses buster-backports, not Minecraft Bedrock.

@MasterLink151, we think Minecraft Pi was not fully installed. Please uninstall Minecraft Pi and then run `sudo apt update`.

**Comment by MasterLink151** [comment]
Wait, so what do I do for Minecraft Bedrock then?

**Comment by Botspot** [comment]
> Wait, so what do I do for Minecraft Bedrock then?

Leave it for now. It's almost certain that Minecraft Pi was causing you issues, and the issue simply interfered with Minecraft Bedrock.  
Once your Minecraft Pi install is fixed, I expect Minecraft Bedrock to install without issue.

**Comment by mobilegmYT** [comment]
> Wait a second, I was mixing two things up!
> Minecraft **_Pi_** uses buster-backports, not Minecraft Bedrock.
> 
> @MasterLink151, we think Minecraft Pi was not fully installed. Please uninstall Minecraft Pi and then run `sudo apt update`.

MCPI uninstall doesn't remove backports.

@MasterLink151 Run `sudo apt update 2>&1 1>/dev/null | sed -ne 's/.*NO_PUBKEY //p' | while read key; do if ! [[ ${keys[*]} =~ "$key" ]]; then sudo apt-key adv --keyserver hkp://pool.sks-keyservers.net:80 --recv-keys "$key"; keys+=("$key"); fi; done` to fix the install error for bedrock.

**Comment by MasterLink151** [comment]
I got Minecraft Bedrock to work. Thank you everyone for the help. I greatly appreciate it. :)
