### ISSUE TITLE
[Request] TurboWarp

### ISSUE THREAD

**Issue by mobilegmYT** [Botspot/pi-apps#539]
Basically scratch desktop, but it's way faster since it compiles code to javascript, has a dark mode, and also incorporates the scratch addons chrome extension features. 

https://github.com/TurboWarp/desktop/releases/download/v0.3.1/TurboWarp-linux-armv7l-0.3.1.deb

**Comment by mobilegmYT** [comment]
@Botspot 
[TurboWarp.zip](https://github.com/Botspot/pi-apps/files/6259142/TurboWarp.zip)

**Comment by Botspot** [comment]
Thanks! I was just trying this and it is much faster and original Scratch.

I was wondering how long it would take someone to make something like this...

**Comment by Botspot** [comment]
Original Scratch Desktop is in Programming. I suggest TurboWarp should go there too.

Also, I think many, many more people would try it out if the app was renamed to TurboScratch. What do you think? Right now, as-is, I think few Scratch users would recognize the app by its logo and title alone.

**Comment by mobilegmYT** [comment]
> Original Scratch Desktop is in Programming. I suggest TurboWarp should go there too.
> 
> Also, I think many, many more people would try it out if the app was renamed to TurboScratch. What do you think? Right now, as-is, I think few Scratch users would recognize the app by its logo and title alone.

I mean it is a deb, so not sure if its possible to rename it. There is a tooltip when you hover over that does say it's a scratch mod and also the logo is very similiar to scratch...

**Comment by Botspot** [comment]
> I mean it is a deb, so not sure if its possible to rename it.

We can always pull a `sed` move on the desktop file.

**Comment by mobilegmYT** [comment]
> > I mean it is a deb, so not sure if its possible to rename it.
> 
> We can always pull a `sed` move on the desktop file.

Well having a name different to app's actual name might cause confusion when people launch it.

**Comment by Botspot** [comment]
> > > I mean it is a deb, so not sure if its possible to rename it.
> > 
> > 
> > We can always pull a `sed` move on the desktop file.
> 
> Well having a name different to app's actual name might cause confusion when people launch it.

You could make a similar argument for Discord. Will people go looking for "WebCord"? No. Will they look for "Discord"? Yes. So it will continue to be called Discord, because that's what everyone comes looking for. Then we can explain in the description.   
IMHO, it's better for Pi-Apps to understand what you _intended_ to look for, than for what you actually looked for.

**Comment by mobilegmYT** [comment]
True, i'll see if I can change the desktop shortcut.

**Comment by Botspot** [comment]
> True, i'll see if I can change the desktop shortcut.

/usr/share/applications/turbowarp-desktop.desktop

**Comment by Botspot** [comment]
I'll do it.

**Comment by Botspot** [comment]
Done. Commit 4731804d221fec795f5eb2d66b64ac481dc24e16

**Comment by Botspot** [comment]
This app was impressive enough that I wrote about it on the RPi forums.

https://www.raspberrypi.org/forums/viewtopic.php?f=63&t=308834
