### ISSUE TITLE
use newer version of etcher

### ISSUE THREAD

**Issue by Itai-Nelken** [Botspot/pi-apps#54]
[BalenaEtcher.zip](https://github.com/Botspot/pi-apps/files/5476253/BalenaEtcher.zip)

I modified the scripts to use v1.5.109 (32bit & 64bit) that I compiled instead of 1.5.36.
v1.5.109 has features that I find more useful like 'flash from URL' and 'clone drive'

**Comment by Botspot** [comment]
Whoa nice!

**Comment by Botspot** [comment]
Where did you get these debs from - did you compile them yourself, or did you find them from somewhere?

**Comment by Itai-Nelken** [comment]
I compiled them using the instructions found [here](https://github.com/futurejones/balena-etcher-arm/blob/master/etcher-build/BUILD.md) on twisterOS for the 32bit and RaspberryPi OS for the 64bit

**Comment by Botspot** [comment]
```
wget wget https://github.com/Itai-Nelken/Etcher-arm-32-64/raw/main/etcher_1.5.109_armhf.deb || error "Failed to download!"
```
Fixed that for you.

**Comment by Itai-Nelken** [comment]
thanks

**Comment by Botspot** [comment]
App added with commit 4a2a3021cbc87fef8144eb1a7d1832c6ee222bb6.
