### ISSUE TITLE
Gamer's Soundboard

### ISSUE THREAD

**Issue by GabeCoder** [Botspot/pi-apps#540]
Can this app run on RPi? If so, please provide a link to a tutorial if applicable.  
Yes, this app is capable of running on a Raspberry Pi, and possibly more Linux distros.
Is this app something many GUI users would find useful?  
Yes, since it automatically runs commands without the user having to enter the commands.
Is this app installable with `sudo apt install`?  
No, you'll need to use a few commands to install it. An easier way is to simply download "Gamer's Soundboard.tar.gz", as it will bring up a graphical installer that will automatically install the application for you.
If you've created a zip file for this app, upload it here.
[Gamer's Soundboard.tar.gz](https://github.com/Botspot/pi-apps/files/6256714/Gamer.s.Soundboard.tar.gz)
The ZIP file posted above contains the Pi Apps details, not the installer. Oh yeah, and the category for this app is: Tools.

**All the cool kids are using soundboards right now!**
kewl.

**Comment by GabeCoder** [comment]
Boop beep bop
Mr. Felix says that he isn’t using a soundboard.
Lol

**Comment by Botspot** [comment]
Sorry for the month-long delay! :(

> **All the cool kids are using soundboards right now!** kewl.

Umm, so this is a simplistic audio player? Is there anything unique to it, when compared to VLC or WACUP?

**Comment by mobilegmYT** [comment]
> Sorry for the month-long delay! :(
> 
> > **All the cool kids are using soundboards right now!** kewl.
> 
> Umm, so this is a simplistic audio player? Is there anything unique to it, when compared to VLC or WACUP?

It let's you import sounds and play them AFAIK.

**Comment by Botspot** [comment]
> There’s an updated package at #620.

Okay we'll close #620. No need for duplicate issues.
Below is your download link from issue 6209, for convenience:
[Gamer's Soundboard.tar.gz](https://github.com/Botspot/pi-apps/files/6437583/Gamer.s.Soundboard.tar.gz)

**Comment by Botspot** [comment]
I consider this app to be too simple  and too generic for many people to want.

People who want to play sounds can do so in the browser, omxplayer, mpv, aplay, vlc, wacup, etc.

**Comment by GabeCoder** [comment]
> I consider this app to be too simple and too generic for many people to want.
Well, it isn’t too exciting anyway, to be honest.
> People who want to play sounds can do so in the browser, omxplayer, mpv, aplay, vlc, wacup, etc.
That’s true. Some websites actually serve as soundboards.
I’d still not recommend using browsers as soundboards because they use a lot of resources.

Anyway, the Gamer’s Soundboard will still remain available for installation at https://github.com/GabeCoder/gamers-soundboard in the README.md document.
