### ISSUE TITLE
Bongo Cam

### ISSUE THREAD

**Issue by Botspot** [Botspot/pi-apps#542]
@mobilegmYT Please reply back with your latest zip folder for the bongo cam app.

**Comment by mobilegmYT** [comment]
[Bongo Cam.zip](https://github.com/Botspot/pi-apps/files/6259683/Bongo.Cam.zip)

**Comment by Botspot** [comment]
> [Bongo Cam.zip](https://github.com/Botspot/pi-apps/files/6259683/Bongo.Cam.zip)

Thanks.  
Could you elaborate in the description what the default keyboard shortcuts? And how do I switch "modes"?

**Comment by mobilegmYT** [comment]
> > [Bongo Cam.zip](https://github.com/Botspot/pi-apps/files/6259683/Bongo.Cam.zip)
> 
> Thanks.
> Could you elaborate in the description what the default keyboard shortcuts are? And how do I switch "modes"?

I mean the github wiki has info on usage and stuff, it's probably better if people checked it then me to badly paraphrase it.

**Comment by mobilegmYT** [comment]
(This is some weird OSU stuff, so not sure about shortcuts or the modes actually)

**Comment by mobilegmYT** [comment]
@Botspot Close now maybe?

**Comment by Botspot** [comment]
> @Botspot Close now maybe?

Yes. Bongo Cam was [added](https://github.com/Botspot/pi-apps/commit/2621212e8570605bc93d092afc20c77535fb4627) a while ago.

**Comment by Botspot** [comment]
> @Botspot Close now maybe?

Yes. Bongo Cam was [added](https://github.com/Botspot/pi-apps/commit/2621212e8570605bc93d092afc20c77535fb4627) a while ago.
