### ISSUE TITLE
Pi-Apps only shows installed.

### ISSUE THREAD

**Issue by IamKraZ** [Botspot/pi-apps#543]
Hi I'm running a pi4 and before I updated and upgraded  apt the Pi-Apps worked fine. Then after it only shows the programs I installed. The original list is no longer there. Even after the program asked if I wanted to update. It shows everything that could be installed so I hit "update all" and it only just shows installed. 
Not sure if this is a bug, error, or me not doing something right, lol.

If it's a bug, when can it be fixed?
If it's an error, is it fixable? 
If it's me not doing something right, please help, lol.

I assume it's the later, but just incase it's one of the other 2 and it hasn't been brought to your attention, I hope it can be fixed soon. There were a few I'd like to install, lol.

Thanks for a great program regardless of this little bug, error, or my stupidity, lol. I love what you have done to help Raspberry Pis.

**Comment by Itai-Nelken** [comment]
I'm not sure I understand you. after the update only the 'installed' category shows?

**Comment by Botspot** [comment]
> I'm not sure I understand you. after the update only the 'installed' category shows?

That's how I took it.

@IamKraZ What operating system are you using? How did you install Pi-Apps?  
And, please **don't reinstall pi-apps.** You are the second person who's reported this, and I'd prefer to find the problem and *fix it*, than to have the problem vanish again.

**Comment by IamKraZ** [comment]
I'm running Noobs on a pi4. Rasbian I think. 

And I had a second SDcard with a previous copy. One before the update. 

After choosing "Update Now" all I get is thec2 programs I installed. No other program shows in the categories.

**Comment by IamKraZ** [comment]
How did you install Pi-Apps? It came with my Noobs 32gig flash sdcard.

It won't let me re-install (did it on my other flash drive, lol). The one I just tried (different card, exact same setup) worked great until I hit the Update Now button.

**Comment by IamKraZ** [comment]
> I'm not sure I understand you. after the update only the 'installed' category shows?

Yes, on both of my copies

**Comment by Botspot** [comment]
> I'm running Noobs on a pi4. Rasbian I think.
> 
> And I had a second SDcard with a previous copy. One before the update.
> 
> After choosing "Update Now" all I get is thec2 programs I installed. No other program shows in the categories.

Okay let's see if some of the apps are missing for some reason:
```
ls ~/pi-apps/apps
```
And I'm curious which files the `preload` script created:
```
ls ~/pi-apps/data/preload
```
And finally, what is the output of these commands?
```
~/pi-apps/preload yad
~/pi-apps/preload yad 'Tools'
```

**Comment by IamKraZ** [comment]
> Okay let's see if some of the apps are missing for some reason:
> 
> ```
> ls ~/pi-apps/apps
> ```

One sec, I got to boot it up.

**Comment by IamKraZ** [comment]
> And I'm curious which files the `preload` script created:
> 
> ```
> ls ~/pi-apps/data/preload
> ```

Ok, this just shows "LIST LIST- LIST-INSTALLED timestamps timestamps- timestamps-installed""

**Comment by IamKraZ** [comment]
> And finally, what is the output of these commands?
> 
> ```
> ~/pi-apps/preload yad
> ~/pi-apps/preload yad 'Tools'
> ```

![Uploading 16176574568938617512375910196362.jpg…]()

**Comment by IamKraZ** [comment]
![16176575847036846324576298984080](https://user-images.githubusercontent.com/31492582/113628620-c30af480-962a-11eb-9ca6-778a26544d90.jpg)

This is what it shows for tools

**Comment by IamKraZ** [comment]
Sorry for some reason the first picture didn't go through so I had to restart type the command and retake the picture, lol.

**Comment by Botspot** [comment]
Thanks for the screenshot. I was able to determine that your problems were caused by a missing folder. How did it get deleted? I have no idea.

But to fix it, run this:
```
mkdir ~/pi-apps/data/categories
```

**Comment by IamKraZ** [comment]
> mkdir ~/pi-apps/data/categories

![16176580554361698314992711437941](https://user-images.githubusercontent.com/31492582/113629301-dbc7da00-962b-11eb-9e65-98dbad0ef4f7.jpg)
 
It won't let me.

**Comment by IamKraZ** [comment]
Ok directory made.

**Comment by Botspot** [comment]
> > How did you install Pi-Apps?
> It came with my Noobs 32gig flash sdcard.

What? Pi-Apps was pre-installed on your sd card? You didn't install Pi-Apps?

> Ok directory made.

Now try launching Pi-Apps.

**Comment by IamKraZ** [comment]
![16176582177793023885336311969564](https://user-images.githubusercontent.com/31492582/113629575-3b25ea00-962c-11eb-807b-76d334e3a71b.jpg)
 Same issue.

**Comment by IamKraZ** [comment]
> What? Pi-Apps was pre-installed on your sd card? You didn't install Pi-Apps?

Yepper, I never installed it. I thought it was cool Rasbian had a good Pi app organizer, lol.

**Comment by Botspot** [comment]
> > What? Pi-Apps was pre-installed on your sd card? You didn't install Pi-Apps?
> 
> Yepper, I never installed it. I thought it was cool Rasbian had a good Pi app organizer, lol.

Wow. I'm not sure what to think of that. _Last time I checked ;)_, Pi-Apps is unofficial. So I wonder who chose to put it on an image and distribute it.

Question: did your _SD Card_ come preinstalled with Pi-Apps, or did you use NOOBS to install Raspbian?

BTW, to fix the "same issue", try deleting the preloaded app list by running this:
```
rm -rf ~/pi-apps/data/preload
```

**Comment by IamKraZ** [comment]
![16176585224418925741681497206052](https://user-images.githubusercontent.com/31492582/113630078-f2226580-962c-11eb-9219-a2c6385a0406.jpg)

I also get this when I double click it on the desktop.

**Comment by Botspot** [comment]
> I also get this when I double click it on the desktop.

That's normal and to be expected. It's caused by a program outside of Pi-App's control. (pcmanfm)  
Because of that, my preferred way to launch Pi-Apps is by going to the Start Menu -> Accessories. You could also permanently add it to your taskbar.

**Comment by IamKraZ** [comment]
> Question: did your _SD Card_ come preinstalled with Pi-Apps, or did you use _NOOBS_ to install Raspbian, and Pi-Apps was on there already?

The SD Card came pre-installed with it. It was there when I first booted it up.

**Comment by Botspot** [comment]
> The SD Card came pre-installed with Pi-Apps. It was there when I first booted it up.

Wow. Where did you buy your Pi from?

**Comment by IamKraZ** [comment]
> rm -rf ~/pi-apps/data/preload

This won't mess up the 2 programs will it?

**Comment by IamKraZ** [comment]
> Wow. Where did you buy your Pi from?

Amazon as a complete package lol. I got the Pu4, a case, the Noops SD Card, power supply, etc.

**Comment by IamKraZ** [comment]
> rm -rf ~/pi-apps/data/preload

Ok, now what?

**Comment by IamKraZ** [comment]
BTW, do you guys have a discord server? I'm on Discord all the time, lol. 

One of the apps I installed from Pi-Apps, lol.

**Comment by Botspot** [comment]
> BTW, do you guys have a discord server? I'm on Discord all the time, lol.

Sure do! It's on the main readme page. Don't feel bad, several people have missed it recently. If you can think of any ways I could make it harder to miss, let me know.

**Comment by Botspot** [comment]
> > rm -rf ~/pi-apps/data/preload
> 
> Ok, now what?

Launch Pi-Apps and see how it looks.

**Comment by IamKraZ** [comment]
> If you can think of any ways I could make it harder to miss, let me know.

_**BIG BOLD LETTERS**_, lol.

**Comment by IamKraZ** [comment]
> Launch Pi-Apps and see how it looks.

No change. Same "Installed" folder and nothing else.

**Comment by Botspot** [comment]
> No change. Same "Installed" folder and nothing else.

Okay, at this point I'd like to inspect your Pi-Apps folder directly.  
Please open your file manager and locate the pi-apps folder. (should be `/home/pi/pi-apps`)  
Right-click on the Pi-Apps folder and select "Compress...". Save the file as a .zip.  
Upload the zip to this issue.

**Comment by IamKraZ** [comment]
> Upload the zip to this issue.

How, from my Pi? I can if I email it to myself maybe.

**Comment by Botspot** [comment]
> > Upload the zip to this issue.
> 
> How, from my Pi? I can if I email it to myself maybe.

The Pi has a browser. Go to github.com, login, and navigate to this issue. Then simply drag-n-drop the zip to the message box.

**Comment by IamKraZ** [comment]
[pi-apps.zip](https://github.com/Botspot/pi-apps/files/6260933/pi-apps.zip)

Yay, finally able to send it, lol.

**Comment by Itai-Nelken** [comment]
I'm not sure, but will downloading the [category](https://github.com/Botspot/pi-apps/blob/master/data/categories/structure) 'structure' file to 'pi-apps/data/categories/' fix the issue (as its missing) @Botspot?

**Comment by Botspot** [comment]
> I'm not sure, but will downloading the [category](https://github.com/Botspot/pi-apps/blob/master/data/categories/structure) 'structure' file to 'pi-apps/data/categories/' fix the issue (as its missing) @Botspot?

That file ought to be recreated upon next launch. But the folder was not being recreated.

**Comment by IamKraZ** [comment]
ping me if it can be fixed or if there is anything I can do further, atm it's dinner time and I'm hungry, lol.

**Comment by Botspot** [comment]
> > mkdir ~/pi-apps/data/categories
> Typo, one sec.

Looks like that wasn't your only typo. In your zip I noticed there's a folder called cat**a**gories, not cat**e**gories.

**Comment by IamKraZ** [comment]
Ahhh, ok. I'll redo it, should I just rename it?

**Comment by Botspot** [comment]
> Ahhh, ok. I'll redo it, should I just rename it?

Sure. Just be sure to delete the `preload` folder again.

**Comment by IamKraZ** [comment]
Where is the "preload" folder again?

**Comment by IamKraZ** [comment]
Same issue, only installed folder.

**Comment by Botspot** [comment]
> Same issue, only installed folder.

And did you delete the preload folder?

Let's see what the issue is this time so tun Pi-Apps in a terminal:
```
~/pi-apps/gui
```

**Comment by Botspot** [comment]
> Where is the "preload" folder again?

Well maybe you already deleted it.  
Anyway, run this to remove it:
```
rm -rf ~/pi-apps/data/preload
```

**Comment by IamKraZ** [comment]
> rm -rf ~/pi-apps/data/preload

Did that already, running 

~/pi-apps/gui seemed to bring it all back. It prompted for and update again. I did so. waiting on update to complete.

**Comment by IamKraZ** [comment]
Ok, so everything came back, but once again when I updated it.... poof, Installed only shows up.

**Comment by IamKraZ** [comment]
Now, if I use ~/pi-apps/gui again it brings up all the categories and plus some. not just installed.

**Comment by IamKraZ** [comment]
Note: I am using the Windows 10 theme from the pi-app.

**Comment by Botspot** [comment]
> Ok, so everything came back, but once again when I updated it.... poof, Installed only shows up.

Weird! Okay I'll install your pi-apps folder in a virtual machine and go through the updating process.

**Comment by IamKraZ** [comment]
Ok, thanks. Hope you get that bug.

**Comment by Botspot** [comment]
> Ok, thanks. Hope you get that bug.

I was not able to repeat the issue, but I think I know what happened: your Pi-Apps install was so old that it had trouble migrating to the latest version.

I pushed some changes that should create the categories folder automatically upon next run and this should solve your issue. Try updating again.

**Comment by IamKraZ** [comment]
> Try updating again.

I will definitely do that as soon as I get off work this evening. Thanks again for all your hard work. You've built a great program 😀

**Comment by IamKraZ** [comment]
![MyPiWithPi-App](https://user-images.githubusercontent.com/31492582/113795477-a0eca180-9712-11eb-8052-131f9c9d3d60.jpg)

Yay, it's working Thanks Botspot. You guys rock!!!

**Comment by Botspot** [comment]
Good to know! Thanks for opening the issue, and I'm glad it's been solved for you.
