### ISSUE TITLE
mint-webapps

### ISSUE THREAD

**Issue by Itai-Nelken** [Botspot/pi-apps#544]
https://github.com/phoenixbyrd/Linux_Mint_Webapps
this is a reminder for me to add it.
if someone wants to add it, feel free to do so.

**Comment by Botspot** [comment]
[Web Apps.zip](https://github.com/Botspot/pi-apps/files/6268535/Web.Apps.zip)

**Comment by Itai-Nelken** [comment]
it fails to uninstall as it doesn't find the package `webapp-manager` which is really weird as I checked the deb's control file and the package name _is_ `webapp-manager`.

**Comment by Itai-Nelken** [comment]
It did get uninstalled, weird!

**Comment by Itai-Nelken** [comment]
I found the issue: `purge-installed` removed the package.
the weird thing is that `pkg-install` isn't used to install it, so probably `apt` trying to fix dependency problems.
I fixed it by first uninstalling `webapp-manager`, and then running `purge-installed` to uninstall all the dependencies.
[Web Apps.zip](https://github.com/Botspot/pi-apps/files/6278406/Web.Apps.zip)

**Comment by Itai-Nelken** [comment]
needs testing.
works for me.

**Comment by Itai-Nelken** [comment]
@Botspot its ready to be added in my opinion.

**Comment by Botspot** [comment]
> @Botspot its ready to be added in my opinion.

Okay I've added it with commit 77f7d5b733d21d9979ea5809b15ec427e5de7272.

Before closing this issue, could we improve the description?  
It currently says "Linux Mint's official Web Apps program."

**Comment by Itai-Nelken** [comment]
Linux Mint's official Web Apps program: convert Any Website into Desktop Application.

**Comment by Itai-Nelken** [comment]
or:
Linux Mint's official Web Apps program: add a menu shortcut to any website.

**Comment by Itai-Nelken** [comment]
@Botspot should I change the description to one of my suggestions?
personaly I prefer the 2nd one.

**Comment by Botspot** [comment]
> @Botspot should I change the description to one of my suggestions?
> personaly I prefer the 2nd one.

Let's use the second one, and then add the customary to run stuff.

**Comment by Botspot** [comment]
How about: Linux Mint's official Web Apps program: Run any website as a standalone app.

**Comment by CleanMachine1** [comment]
I use Mint and the official description is
"Run websites as if they were apps"

I propose 

Have a website you want to use standalone, such as Microsoft Teams or Pi-Hole Admin or Discord Web?
Linux Mint's Official Web apps program can make this possible!
mint-webapps treats every website as a standalone application so you can achieve this!

**Comment by CleanMachine1** [comment]
PS: I really wanted to add this app a few days ago, but tried compiling it and couldn't.
