### ISSUE TITLE
Lutris (waiting for solution to vulkan error)

### ISSUE THREAD

**Issue by NoozSBC** [Botspot/pi-apps#545]
Can this app run on RPi? If so, please provide a link to a tutorial if applicable. 
Yes

Is this app something many GUI users would find useful?  
Yes

Is this app installable with `sudo apt install`?  
No(technically)

If you've created a zip file for this app, upload it here.
I will upload a zip soon

Install lutris with deb
https://download.opensuse.org/repositories/home:/strycore/Raspbian_10/all/lutris_0.5.8.3_all.deb

or with apt repo
```
echo 'deb http://download.opensuse.org/repositories/home:/strycore/Raspbian_10/ /' | sudo tee /etc/apt/sources.list.d/home:strycore.list
curl -fsSL https://download.opensuse.org/repositories/home:strycore/Raspbian_10/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/home_strycore.gpg > /dev/null
sudo apt update
sudo apt install lutris
```

**Comment by mobilegmYT** [comment]
@Botspot [Lutris.zip](https://github.com/Botspot/pi-apps/files/6274251/Lutris.zip) 

Note that this installs wine, so we need Wine to first get a install-64 so this will work for 64-bit.

**Comment by Botspot** [comment]
About this:
```
~/pi-apps manage install Box86
~/pi-apps manage install Wine
```
First, that command doesn't work at all. `bash: /home/pi/pi-apps: Is a directory`
Second, installing wine already installs box86. So we don't need to explicitly install box86.  
Third, we don't need to install wine, if it's already been installed.
Fourth, there is no app named "`Wine`". It's "`Wine (x86)`".
I've changed the above code to:
```
"${DIRECTORY}/manage" install-if-not-installed 'Wine (x86)'
```

**Comment by Botspot** [comment]
Upon a successful installation and subsequently launching Lutris, this dialog window appeared:  
![2021-04-12-201626_1920x1080_scrot](https://user-images.githubusercontent.com/54716352/114482337-0be32000-9bcc-11eb-809d-fad93d8762ed.png)  
Is my system messed up? If this is to be expected, then maybe an addition to the description would be a good idea.

**Comment by Itai-Nelken** [comment]
I installed that deb on TwisterOS and I didn't get that error.

**Comment by mobilegmYT** [comment]
> Upon a successful installation and subsequently launching Lutris, this dialog window appeared:
> ![2021-04-12-201626_1920x1080_scrot](https://user-images.githubusercontent.com/54716352/114482337-0be32000-9bcc-11eb-809d-fad93d8762ed.png)
> Is my system messed up? If this is to be expected, then maybe an addition to the description would be a good idea.

I think you can ignore that

**Comment by chunky-milk** [comment]
> > Upon a successful installation and subsequently launching Lutris, this dialog window appeared:
> 
> > ![2021-04-12-201626_1920x1080_scrot](https://user-images.githubusercontent.com/54716352/114482337-0be32000-9bcc-11eb-809d-fad93d8762ed.png)
> 
> > Is my system messed up? If this is to be expected, then maybe an addition to the description would be a good idea.
> 
> 
> 
> I think you can ignore that

No, you probably shouldn't ignore that, as some games won't run through Lutris without proper Vulkan support. You don't get that error on TwisterOS because all the libraries are already installed for Vulkan. 

Solution: Have the script compile the **latest** Vulkan driver, then continue to install Lutris.

**Comment by Botspot** [comment]
> Solution: Have the script compile the **latest** Vulkan driver, then continue to install Lutris.

How do we do that? Is Mesa a synonym for Vulkan?

**Comment by mobilegmYT** [comment]
Does vulkan even work yet?

**Comment by mobilegmYT** [comment]
[Lutris.zip](https://github.com/Botspot/pi-apps/files/6571521/Lutris.zip)
Also fixed stuff

**Comment by Itai-Nelken** [comment]
> Does vulkan even work yet?

I don't think so

**Comment by Painadath** [comment]
@chunky-milk @mobilegmYT i have doubt that there is already script or pre buit versions of vulkan which bundles with web-apps can we just use it?

**Comment by theofficialgman** [comment]
same probllem as https://github.com/Botspot/pi-apps/issues/1395#issuecomment-1374358074
