### ISSUE TITLE
Krop

### ISSUE THREAD

**Issue by hmsjy2017** [Botspot/pi-apps#547]
> Krop is a simple graphical tool to crop the pages of PDF files. It is written in Python and relies on PyQT, python-poppler-qt4 and pyPDF for its functionality. A unique feature of krop is its ability to automatically split pages into subpages to fit the limited screen size of devices such as eReaders. This is particularly useful, if your eReader does not support convenient scrolling.

![5E04360B-99B8-4640-9945-AE94A1CDE86D](https://user-images.githubusercontent.com/42692274/113741480-47956a00-9734-11eb-9958-46c8b1c87a26.png)

https://github.com/gocarlos/krop
Terminal: sudo snap install krop
Both armhf and arm64 are supported.

**Comment by Botspot** [comment]
```
pi@raspberrypi:~ $ sudo snap install krop
error: cannot perform the following tasks:
- Ensure prerequisites for "krop" are available (cannot install prerequisite "kde-frameworks-5-core18": no snap revision available as specified)
```

**Comment by CleanMachine1** [comment]
I personally have never used it, but I have heard that LibreOffice Draw is a good tool for editing PDFs' 
why not just use that rather than wasteful snaps

**Comment by Itai-Nelken** [comment]
krop is in the apt repos `sudo apt install krop`

**Comment by Botspot** [comment]
> krop is in the apt repos `sudo apt install krop`

Sure enough. Apps that are already in `apt` are not allowed in Pi-Apps: this app store specializes in hard-to-install stuff.
