### ISSUE TITLE
I can not install any app

### ISSUE THREAD

**Issue by 65564654** [Botspot/pi-apps#548]
I pulled the newest update for pi apps on twister os and it looks like below
![Screenshot_2021-04-06_14-52-39](https://user-images.githubusercontent.com/72508925/113763570-d039e900-96e7-11eb-832b-f85990926f9a.png)
I can not install or uninstall apps but all apps that I installed through pi-apps still work.
I have tried uninstalling and reinstalling. It did not work. I may have done that wrong.
I did these steps to uninstall and install.
1. delete the entire pi-apps folder.
2. run in the home folder so /home/pi
`git clone https://github.com/Botspot/pi-apps`
3. and then ran
`./pi-apps/install`
4. It installed successfully and gave no error messages or anything but it was still broken.

**Comment by Botspot** [comment]
Oops. Careless mistake. I was playing around with the code yesterday, then made some important fixes this morning. Then I accidentally pushed the whole thing, including those unwanted changes.

It should be fixed now. Update again and you should be all good. Thanks for reporting the issue! :)
