### ISSUE TITLE
Not displaying apps

### ISSUE THREAD

**Issue by adriantse136** [Botspot/pi-apps#550]
I am not able to install any apps, it does not display any apps. 
![863A91C3-72C1-4ADD-A035-234A9C783463](https://user-images.githubusercontent.com/54153247/113782313-a12b7380-96f7-11eb-905c-dabf056f3460.png)

If I click on “App folder”, it tries to open folder.png (the icon file) as if it is a folder, which is not the right file or directory.
![42C1E450-C19F-44C9-9AEA-C51180AF85BD](https://user-images.githubusercontent.com/54153247/113782476-de900100-96f7-11eb-9ce5-0f51465ca4ba.png)

however, the apps are here.
![3CF2742D-58C9-4628-90F1-F866D57F3A85](https://user-images.githubusercontent.com/54153247/113782526-f49dc180-96f7-11eb-9148-86700028d1b2.png)

**Comment by Botspot** [comment]
Sorry about that. I take full responsibility for my mistake.

Update and you should be good to go! (See https://github.com/Botspot/pi-apps/issues/548)
