### ISSUE TITLE
pi-apps reinstall problem

### ISSUE THREAD

**Issue by centershot** [Botspot/pi-apps#552]
my  pi-app app got correpted during a recent update.
i unistalled
i reinstalled it
works fine however
it doesent now the installed apps anmore
? is there a way for pi-apps to rediscover with pi apps it has installed on my system

**Comment by Botspot** [comment]
Unfortunately there's nothing I can do about that. :(
Pi-Apps remembers which apps are installed, by using some files within this folder: `/home/pi/pi-apps/data/status`.

If you deleted your old Pi-Apps install, then that data is gone. Fortunately, it's somewhat easy to manually recreate that data.  
For example, if you wanted to make Pi-Apps think that Windows 10 Theme was installed, you'd create this file:
```
/home/pi/pi-apps/data/status/Windows 10 Theme
```
Once you create the file, open it in a text editor. Simply write this to the file:
```
installed
```
If Pi-Apps sees this file contains 'installed', then it will treat Windows 10 Theme as if it was installed.
