### ISSUE TITLE
App submission: OpenSCAD

### ISSUE THREAD

**Issue by koendv** [Botspot/pi-apps#556]
[OpenSCAD.zip](https://github.com/Botspot/pi-apps/files/6277057/OpenSCAD.zip)

This is OpenSCAD, the 3D CAD program, as an AppImage. 
The 64-bit version is from http://www.openscad.org
The 32-bit version is from https://github.com/koendv/openscad-raspberrypi

**Comment by Botspot** [comment]
Done. Thank you very much for providing a zip!

The scripts were well-done. Good job. Only change I made was removing the `purge-installed` line from the `uninstall` script - as your install scripts didn't install anything, then there will never be a situation when uninstalling OpenSCAD should uninstall anything either.

**Comment by koendv** [comment]
You can extract the .desktop file from an AppImage:
```
~/bin/OpenSCAD-2021.04.04-aarch64.AppImage --appimage-extract '*.desktop'
```
or you can extract all files:
```
~/bin/OpenSCAD-2021.04.04-aarch64.AppImage --appimage-extract
```
I'm saying this because this way you could automate adding an app-image to pi-apps.
