### ISSUE TITLE
My pi-apps broke after update

### ISSUE THREAD

**Issue by CEONediak** [Botspot/pi-apps#558]
### Hello again
Pi-apps has broke and cant install a single program after updating and says Microsoft account and minecraft 

OS:Ubuntu 20.10 arm
64 bit maybe? also cant find minecraft beta either

**Comment by Botspot** [comment]
> ### Hello again
> Pi-apps has broke and cant install a single program after updating and says Microsoft account and minecraft

What errors do you see?  
BTW, please be patient. Pi-Apps just went through a semi-massive overhaul about a minute ago. It ought to run much faster now, but problems can sometimes pop up.

**Comment by CEONediak** [comment]
Sos just wanted to install wine found away to install it on 64 bit pi apps. i will. EXITED! It just does not show app list apart from my pocketmine-mp app

**Comment by Botspot** [comment]
> Sos just wanted to install wine found away to install it on 64 bit pi apps. i will. EXITED!

I don't understand how you managed to install Wine, on 64-bit, THROUGH Pi-Apps. Pi-Apps has no such script to do that.

> It just does not show app list apart from my pocketmine-mp app

Could you send me a screenshot?

**Comment by CEONediak** [comment]
![Screenshot from 2021-04-08 18-02-51](https://user-images.githubusercontent.com/62204723/114069922-69f3c880-9897-11eb-9cc1-d2a0f3b2f8bc.png)
I added the armf arcitecture *safe to do this Then deleted arm64 *never do this i had a backup and then installed and added back arm64 and worked fine BEFORE THE UPDATE. Agian i will be patient

**Comment by Botspot** [comment]
> ![Screenshot from 2021-04-08 18-02-51](https://user-images.githubusercontent.com/62204723/114069922-69f3c880-9897-11eb-9cc1-d2a0f3b2f8bc.png)
> I added the armf arcitecture *safe to do this Then deleted arm64 *never do this i had a backup and then installed and added back arm64 and worked fine BEFORE THE UPDATE. Agian i will be patient

Huh. I don't understand how that's possible, but I'll assume for now that installing Wine had nothing to do with the app list going blank like that.

@CEONediak, what's the output of this command, when you run it in the terminal?
```
pi-apps
```

**Comment by CEONediak** [comment]
![Screenshot from 2021-04-08 18-33-16](https://user-images.githubusercontent.com/62204723/114071377-f3f06100-9898-11eb-9bd0-747f202c9e2e.png)
Same thing, sadly.

**Comment by CEONediak** [comment]
Reinstalled and still not fixed.

**Comment by Itai-Nelken** [comment]
can you run `ls ~/pi-apps`? I think a few things got deleted there.

**Comment by CEONediak** [comment]
Shows a list of apps

**Comment by CEONediak** [comment]
> can you run `ls ~/pi-apps`? I think a few things got deleted there.

Also really like your Ubuntu on too fixes tutorial helped me lot of time when reinstalling Ubuntu

**Comment by Botspot** [comment]
Fixed.

The preload script was pointing to `/home/pi`, when it should have been flexible for systems that don't use /home/pi, like yours.

**Comment by CEONediak** [comment]
Should i reinstall?

**Comment by Botspot** [comment]
> Should i reinstall?

You shouldn't have to. Updating should work.

**Comment by CEONediak** [comment]
Thank you pi god!

**Comment by Botspot** [comment]
> ![Screenshot from 2021-04-08 18-33-16](https://user-images.githubusercontent.com/62204723/114071377-f3f06100-9898-11eb-9bd0-747f202c9e2e.png)

PS: Your Conky is bothering me. It shouldn't look like that. Sometimes the same thing happens to me. To fix:  
```
conky
```
