### ISSUE TITLE
add: speedtest-cli

### ISSUE THREAD

**Issue by Itai-Nelken** [Botspot/pi-apps#56]
[SpeedTest-CLI.zip](https://github.com/Botspot/pi-apps/files/5478444/SpeedTest-CLI.zip)

**Comment by Botspot** [comment]
Are you aware that speedtest-cli is available for install via `apt-get`?  
Is this a later version or something?

**Comment by mobilegmYT** [comment]
I think most people would just use a web browser for a speed test.

**Comment by Botspot** [comment]
> I think most people would just use a web browser for a speed test.

1. If they know about it.
2. The speedtest.net site will render wildly worse results than using `speedtest-cli`. (due to all the bottlenecks associated with a web-browser and non-native javascript)  
On my install, `speedtest-cli` gets **230** Mb/s down & 12 Mb/s up. But speedtest.net reports only **86** Mb/s down and 11Mb/s up. That's a big difference.

**Comment by Itai-Nelken** [comment]
> Are you aware that speedtest-cli is available for install via `apt-get`?
> Is this a later version or something?

I didn't no, but I just tested the `apt-get` version, and I think this one is better.

**Comment by Itai-Nelken** [comment]
it can be create easily, but the `apt-get` version has no menu shortcut and in my opinion less user friendly

**Comment by Botspot** [comment]
Oh wow, it is quite different. I like this new version better.

@Itai-Nelken A couple things though:

- Shouldn't the menu shortcut go in the Internet category? On my install, it's in Other. :/ 
- Shouldn't the terminal stay open after the speedtest has finished? Currently, the terminal disappears as soon as it finishes, so you never get a chance to see the final upload speed value.

**Comment by Itai-Nelken** [comment]
[SpeedTest-CLI.zip](https://github.com/Botspot/pi-apps/files/5482903/SpeedTest-CLI.zip)
@Botspot I made a script that runs when you open the program, it runs the program, and then waits for 5 seconds.
but the menu shortcut disappeared from my main menu when I tried to add it to the internet category, I can still find it using a application finder, but it won't appear in the main menu.

**Comment by Itai-Nelken** [comment]
I found the shortcut, it is in a duplicate of the _Other_ category and it doesn't appear in the main menu.

**Comment by Botspot** [comment]
Okay, I think I've fixed it for you:  
[SpeedTest-CLI.zip](https://github.com/Botspot/pi-apps/files/5483004/SpeedTest-CLI.zip)

**Comment by Itai-Nelken** [comment]
[SpeedTest-CLI.zip](https://github.com/Botspot/pi-apps/files/5483040/SpeedTest-CLI.zip)
I fixed the uninstall script, it was still trying to remove _/usr/share/applications/speedtest.desktop_

**Comment by Itai-Nelken** [comment]
I think it's ready, I tested it a few times and it works great every time.

**Comment by Botspot** [comment]
> I think it's ready, I tested it a few times and it works great every time. (the install script and the program itself itself)

Agreed. I worked on the description and now it's been added. Commit da6c8adba9b8b7611bd69e23a070dbc1034f0e46

**Comment by Itai-Nelken** [comment]
Great!
