### ISSUE TITLE
Does pi-apps work on ubuntu?

### ISSUE THREAD

**Issue by The-Sapphire-Starship** [Botspot/pi-apps#563]
Does pi-apps work on ubuntu 20.10 desktop? If not could you please make it compatible :)

**Comment by Painadath** [comment]
When runny ng on Ubuntu mate 18.04 it says we only support buster

**Comment by Botspot** [comment]
> Does pi-apps work on ubuntu 20.10 desktop? If not could you please make it compatible :)

Yes, it should work. If you encounter specific problems with specific apps, let me know.  
And in general, be aware that 64-bit support on Pi-Apps is not as good as 32-bit support (armhf). If you want a larger (and more reliable) selection of apps to choose from, consider switching to a 32-bit OS like [Raspberry Pi OS](https://www.raspberrypi.org/software/).

**Comment by The-Sapphire-Starship** [comment]
> > Does pi-apps work on ubuntu 20.10 desktop? If not could you please make it compatible :)
> 
> Yes, it should work. If you encounter specific problems with specific apps, let me know.
> And in general, be aware that 64-bit support on Pi-Apps is not as good as 32-bit support (armhf). If you want a larger (and more reliable) selection of apps to choose from, consider switching to a 32-bit OS like [Raspberry Pi OS](https://www.raspberrypi.org/software/).

I might end up doing that, i switched to ubuntu because im trying to compile  the godot game engine and i thought i needed a 64-bit os, im realizing now that i might need it and that there are somethings that are harder to do in ubuntu, i may and up switching back

**Comment by The-Sapphire-Starship** [comment]
> Yes, it should work. If you encounter specific problems with specific apps, let me know.
> And in general, be aware that 64-bit support on Pi-Apps is not as good as 32-bit support (armhf). If you want a larger (and more reliable) selection of apps to choose from, consider switching to a 32-bit OS like [Raspberry Pi OS](https://www.raspberrypi.org/software/).

Does it work witht he twister OS (and would you recommend the twister OS) (im asking because im want to make sure it will before changing OS again, i was taken for a ride when changing to ubuntu, there were several issues and it was a big headack, i just want to make sure that things should work on it before changing), i believe twister OS is a 32-bit OS

**Comment by The-Sapphire-Starship** [comment]
^^^
nvm, i just found the spot on their website where they specificly mention pi-apps, ill probly try out twister

**Comment by Botspot** [comment]
> > Yes, it should work. If you encounter specific problems with specific apps, let me know.
> > And in general, be aware that 64-bit support on Pi-Apps is not as good as 32-bit support (armhf). If you want a larger (and more reliable) selection of apps to choose from, consider switching to a 32-bit OS like [Raspberry Pi OS](https://www.raspberrypi.org/software/).
> 
> Does it work witht he twister OS (and would you recommend the twister OS) (im asking because im want to make sure it will before changing OS again, i was taken for a ride when changing to ubuntu, there were several issues and it was a big headack, i just want to make sure that things should work on it before changing), i believe twister OS is a 32-bit OS

Sorry for the delay - I was making an app.  
Twister OS is just modified Raspberry Pi OS. It uses a different desktop system that takes more resources. Twister OS has the ability to switch themes, and is designed for emulation and gaming.

I personally prefer RPiOS. It's smaller and lighter-weight. Also I prefer the LXDE desktop environment over XFCE. So if I was forced to use Twister OS, I'd uninstall the gaming stuff, switch to LXDE, and get rid of the theme switcher.  In other words I'd use RPi OS and then install my custom-made Windows 10 Theme app from Pi-Apps.

**Comment by The-Sapphire-Starship** [comment]
> Sorry for the delay - I was making an app.
> Twister OS is just modified Raspberry Pi OS. It uses a different desktop system that takes more resources. Twister OS has the ability to switch themes, and is designed for emulation and gaming.
> 
> I personally prefer RPiOS. It's smaller and lighter-weight. Also I prefer the LXDE desktop environment over XFCE. So if I was forced to use Twister OS, I'd uninstall the gaming stuff, switch to LXDE, and get rid of the theme switcher. In other words I'd use RPi OS and then install my custom-made Windows 10 Theme app from Pi-Apps.

I may end up doing that but ill just stick with this for now, ive done 2 os changes in 2 days and the first was a pain to get working right, is there any good guide on how to the switch over without having to completely reflash the sd card?

**Comment by Botspot** [comment]
> > Sorry for the delay - I was making an app.
> > Twister OS is just modified Raspberry Pi OS. It uses a different desktop system that takes more resources. Twister OS has the ability to switch themes, and is designed for emulation and gaming.
> > I personally prefer RPiOS. It's smaller and lighter-weight. Also I prefer the LXDE desktop environment over XFCE. So if I was forced to use Twister OS, I'd uninstall the gaming stuff, switch to LXDE, and get rid of the theme switcher. In other words I'd use RPi OS and then install my custom-made Windows 10 Theme app from Pi-Apps.
> 
> I may end up doing that but ill just stick with this for now, ive done 2 os changes in 2 days and the first was a pain to get working right, is there any good guide on how to the switch over without having to completely reflash the sd card?

I'm not aware of a way to easily switch from TwisterOS to RPiOS without reflashing.  
Maybe it would be easier for you if you had two sd cards? (That way you can take regular backups, which is highly recommended)

**Comment by The-Sapphire-Starship** [comment]
> I'm not aware of a way to easily switch from TwisterOS to RPiOS without reflashing.
> Maybe it would be easier for you if you had two sd cards? (That way you can take regular backups, which is highly recommended)

I ended up flashing Raspberry pi os back onto the sd, ill 
probly be getting your windows 10 theme to see how it looks :)

I'm already planning a project to do in the near future that will us another Raspberry pi and some external hard sides to create a backup system, transferring the files through eternity, I'm planning on writing all the code myself :)

**Comment by The-Sapphire-Starship** [comment]
Thanks for making the pi-apps program, I can't imagine no having it now. Your windows 10 theme is a lot closed to the actuall thing then the twister one
