### ISSUE TITLE
FlameShot

### ISSUE THREAD

**Issue by CleanMachine1** [Botspot/pi-apps#564]
Hi, I have been using Flameshot since I started using Linux, its a great tool for taking screenshots and its easy for someone to use coming from Windows 10's snipping tool.

The version in the repos is old, I don't think its too old but still old

It can easily be compiled from source but takes a while, I couldn't get it work with checkinstall however it does easily compile from source
its repo can be found here along with instructions to build 
Building takes around 4 mins on a Raspberry Pi 4B 
https://github.com/flameshot-org/flameshot 

It does need a lot of -dev dependencies to compile however source code builds are always better than just debs

**Comment by CleanMachine1** [comment]
Just checked official RPi Repo and it has version 0.6.0-11 while the newest is 0.9.1
but the repo provides an unused 0.9.0.deb

**Comment by Itai-Nelken** [comment]
they have official arm releases (see https://github.com/flameshot-org/flameshot/issues/1444#issuecomment-798465911)

**Comment by Botspot** [comment]
> they have official arm releases (see [flameshot-org/flameshot#1444 (comment)](https://github.com/flameshot-org/flameshot/issues/1444#issuecomment-798465911))

How do you actually download them?

**Comment by CleanMachine1** [comment]
Exactly what I was thinking after looking at it.

**Comment by Itai-Nelken** [comment]
using this link: https://github.com/flameshot-org/flameshot/suites/2457831109/artifacts/52759918 there still isn't a new release though.
(that link downloads all the linux debs and appimages, thats why its so big (127mb).

**Comment by CleanMachine1** [comment]
No new releases?
So compiling from source is still a better idea?

**Comment by Itai-Nelken** [comment]
use that file I lined, it contains the newest debs.

**Comment by Itai-Nelken** [comment]
[flameshot-arm.zip](https://github.com/Botspot/pi-apps/files/6290345/flameshot-arm.zip)
I made a zip containing the armhf and arm64 debs from here: https://github.com/flameshot-org/flameshot/suites/2457831109/artifacts/52759918

**Comment by CleanMachine1** [comment]
Well I still think source code is better however it would probably be easier to use the download. If we download the the .deb on its own and host it in a different repo and keep it updated it would be better.

PS: will using an external .deb clash with the repo .deb?

**Comment by Itai-Nelken** [comment]
>PS: will using an external .deb clash with the repo .deb?

@CleanMachine1 no, I'm using those debs since they started existing.

**Comment by Itai-Nelken** [comment]
>Well I still think source code is better however it would probably be easier to use the download. If we download the the .deb on its own and host it in a different repo and keep it updated it would be better.

why? those debs are the automated builds that end up in the releases, I see no reason not to use them.

**Comment by CleanMachine1** [comment]
Okay, well I will maintain when with PR if required @Itai-Nelken if I remember :smile:

**Comment by CleanMachine1** [comment]
Source builds result in better performance to my knowledge

**Comment by Itai-Nelken** [comment]
I think

> Okay, well I will maintain when with PR if required @Itai-Nelken if I remember 😄

I didn't understand what you mean.

**Comment by Itai-Nelken** [comment]
> Source builds result in better performance to my knowledge

whats the difference between building natively and building natively but on QEMU (what flameshot's automated arm builds use)?

**Comment by CleanMachine1** [comment]
Where are we hosting the deb

**Comment by Itai-Nelken** [comment]
and flameshot isn't a program where performance matters.

**Comment by Itai-Nelken** [comment]
> Where are we hosting the deb

here is the armhf deb: https://we.tl/t-mYh4WJ10IQ
and the arm64 one: https://we.tl/t-cHENaJBoWc
(the links are taken from the automated builds and are official)

**Comment by CleanMachine1** [comment]
Thats not appropriate, how about my RPi-Stuff repo

**Comment by CleanMachine1** [comment]
We transfer links expire

**Comment by Itai-Nelken** [comment]
I have a idea, @chunky-milk can upload it to his rpi-addons apt repo and we can download it from there.

**Comment by chunky-milk** [comment]
> I have a idea, @chunky-milk can upload it to his rpi-addons apt repo and we can download it from there.

great idea :)

**Comment by CleanMachine1** [comment]
Sure

**Comment by chunky-milk** [comment]
> Sure

Uploading now

**Comment by chunky-milk** [comment]
The deb files are here:

https://github.com/chunky-milk/raspbian-addons/raw/master/debian/pool/main/f/flameshot/flameshot_0.9.0-1_arm64.deb

https://github.com/chunky-milk/raspbian-addons/raw/master/debian/pool/main/f/flameshot/flameshot_0.9.0-1_armhf.deb

**Comment by Itai-Nelken** [comment]
I'll make the scrips, is that ok with everyone?

**Comment by CleanMachine1** [comment]
I'd like to make them personally.

**Comment by Itai-Nelken** [comment]
> I'd like to make them personally.

@CleanMachine1 ok

**Comment by Itai-Nelken** [comment]
good luck

**Comment by CleanMachine1** [comment]
What are the dependencies of the script?

**Comment by chunky-milk** [comment]
> What are the dependencies of the script?

They are automatically installed, when the deb is installed. `sudo apt install -yf ./deb-filename-here.deb`

**Comment by Itai-Nelken** [comment]
> What are the dependencies of the script?

@CleanMachine1 what @chunky-milk said

**Comment by CleanMachine1** [comment]
can I ignore the dependencies line then.

**Comment by CleanMachine1** [comment]
[Flameshot.zip](https://github.com/Botspot/pi-apps/files/6290547/Flameshot.zip)
Well heres my second time making an app and I haven't tested it since I haven't got my Raspberry Pi readily available right now however it seemed to pass the shellcheck without giving errors other than the directory blah blah blah with the error

**Comment by chunky-milk** [comment]
> [Flameshot.zip](https://github.com/Botspot/pi-apps/files/6290547/Flameshot.zip)
> Well heres my second time making an app and I haven't tested it since I haven't got my Raspberry Pi readily available right now however it seemed to pass the shellcheck without giving errors other than the directory blah blah blah with the error scheme

Looks good to me. @Botspot ?

**Comment by Itai-Nelken** [comment]
@CleanMachine1 I would use `rm -f` in the `uninstall` script so it doesn't give a error if it fails to delete the deb for some reason.

**Comment by CleanMachine1** [comment]
The error thingy should take effect if it can't delete it, right?

**Comment by Itai-Nelken** [comment]
> The error thingy should take effect if it can't delete it, right?

@CleanMachine1 yes, but we don't want that because it doesn't matter if it fails to delete it, it still installed successfully.

**Comment by Botspot** [comment]
Any reason in particular why we have `sudo apt clean` at the end of the `install-32` script?

**Comment by CleanMachine1** [comment]
Thought I had it in the uninstall, if not then I am sorry, small error

**Comment by Botspot** [comment]
Done with commit 49553f542fa02e8e7e8060a9e44d397e1a17e9fb.

PS we're still waiting for someone to write a good description for Processing IDE. https://github.com/Botspot/pi-apps/issues/290

**Comment by CleanMachine1** [comment]
What are you trying to say

You want me to write it up because for some reason I like to fix and write documentation??? :eyes: :eyes: 
_or are you just saying_

**Comment by Botspot** [comment]
> What are you trying to say
> 
> You want me to write it up because for some reason I like to fix and write documentation??? 👀 👀
> _or are you just saying_

No, I'm not saying anything in particular, or _to_ any_one_ in particular. ;)

Just saying that Processing is an easy app to add next. It's all ready to go except that it needs a good description. Now, what you choose to *do* with that information is entirely up to you. If you choose to do nothing with that info, it's fine with me.

**Comment by CleanMachine1** [comment]
I'll write it but I've never used JS or the tool in question.

**Comment by CleanMachine1** [comment]
What language is it even for??
https://en.wikipedia.org/wiki/Processing_(programming_language)
is this it?
Is it an IDE and language?

**Comment by CleanMachine1** [comment]
@Botspot ?

**Comment by Botspot** [comment]
> Is it an IDE and language?

I really don't know. :(

**Comment by ZetaoYang** [comment]
@CleanMachine1 flameshot released 0.10.1 with arm64 and armhf
https://github.com/flameshot-org/flameshot/releases/download/v0.10.1/flameshot-0.10.1-1.debian-10.armhf.deb
https://github.com/flameshot-org/flameshot/releases/download/v0.10.1/flameshot-0.10.1-1.debian-10.arm64.deb

So I think the download links mentioned in https://github.com/Botspot/pi-apps/commit/49553f542fa02e8e7e8060a9e44d397e1a17e9fb could be updated.
