### ISSUE TITLE
Astomence

### ISSUE THREAD

**Issue by Painadath** [Botspot/pi-apps#565]
Astromenace is hard core alien ship shooter created with c++
https://github.com/viewizard/astromenace
i have created a app to install it
[AstroMenace.zip](https://github.com/Botspot/pi-apps/files/6291797/AstroMenace.zip)
@Botspot please check it out

**Comment by Botspot** [comment]
This crashed my 4GB Pi4 twice.

It used up all my RAM. To solve this, I've changed `make -j`expr $c - 1` to `make`.

**Comment by Botspot** [comment]
Done. AstroMenace has been added to Pi-Apps.

**Comment by Painadath** [comment]
@Botspot if simply you use make it will takke a long time

**Comment by Painadath** [comment]
@Botspot add to the games list please
