### ISSUE TITLE
Typora (waiting for box86 fixes)

### ISSUE THREAD

**Issue by hmsjy2017** [Botspot/pi-apps#567]
https://typora.io/
Typora is the best Markdown editor I have ever used. But it does not support ARM, which is a pity.
![4EDDB1C1-5944-4139-99B1-6D856B64C420](https://user-images.githubusercontent.com/42692274/114309792-0b3e8100-9b1b-11eb-865e-f97d838b5e05.png)

Maybe it can be run through Box86 or wine.
https://typora.io/#windows
https://typora.io/linux/typora_0.9.98_amd64.deb
https://typora.io/linux/Typora-linux-x64.tar.gz
https://typora.io/linux/Typora-linux-ia32.tar.gz

**Comment by Botspot** [comment]
Progress report:

Trying to run this with box86 resulted in a missing library error: `Error loading needed lib: "libatk-bridge-2.0.so.0"`
@ptitseb says he will wrap the library within box86, then we'll continue from there.

**Comment by CleanMachine1** [comment]
I write every I do in VSCode and it works fine, there are some nice extensions you can add, such as markdownlint and spell check 

also the keyboard shortcut Ctrl+Shift+V gives you a pull preview of it! 
Heres a photo of it 
![VS](https://user-images.githubusercontent.com/78213164/115264458-3a15b200-a12e-11eb-8fc0-fa1f64f586da.png)

**Comment by hmsjy2017** [comment]
@CleanMachine1 But Typora has some unique functions, such as exporting files to other types, uploading pictures to the picture bed and inserting them into articles.

**Comment by CleanMachine1** [comment]
Interesting, might have a look at it my self

**Comment by CleanMachine1** [comment]
VSCode has its own extension with it!

Problem solved :laughing:

**Comment by Itai-Nelken** [comment]
I tried to run it with box86, and after finding all the x86libs it needed (here: read the readme inside, put them inside the typora folder [deps_box86.zip](https://github.com/Botspot/pi-apps/files/6345030/deps_box86.zip)) box86 gives this error:
```
pi@TwisterPi4:~/Downloads/Typora-linux-ia32 $ ./Typora 
Box86 with Dynarec v0.2.1 4a8d19da built on Apr 20 2021 10:40:54
Error: Global Symbol gtk_paper_size_free not found, cannot apply R_386_GLOB_DAT @0x509cd78 ((nil)) in ./Typora
21089|SIGSEGV @(nil) (???((nil))) (x86pc=0x6301402b/???:"???", esp=0xb6291b88, stack=0xb5a93000:0xb6293000 own=(nil) fp=0x800), for accessing (nil) (code=1/prot=0), db=(nil)((nil):(nil)/(nil):(nil)/???:clean, hash:0/0)
Segmentation fault
pi@TwisterPi4:~/Downloads/Typora-linux-ia32 $ 
```
I'll open a issue in the box86 repo later.

**Comment by Botspot** [comment]
> I tried to run it with box86, and after finding all the x86libs it needed (here: read the readme inside, put them inside the typora folder [deps_box86.zip](https://github.com/Botspot/pi-apps/files/6345030/deps_box86.zip)) box86 gives this error:
> 
> ```
> pi@TwisterPi4:~/Downloads/Typora-linux-ia32 $ ./Typora 
> Box86 with Dynarec v0.2.1 4a8d19da built on Apr 20 2021 10:40:54
> Error: Global Symbol gtk_paper_size_free not found, cannot apply R_386_GLOB_DAT @0x509cd78 ((nil)) in ./Typora
> 21089|SIGSEGV @(nil) (???((nil))) (x86pc=0x6301402b/???:"???", esp=0xb6291b88, stack=0xb5a93000:0xb6293000 own=(nil) fp=0x800), for accessing (nil) (code=1/prot=0), db=(nil)((nil):(nil)/(nil):(nil)/???:clean, hash:0/0)
> Segmentation fault
> pi@TwisterPi4:~/Downloads/Typora-linux-ia32 $ 
> ```
> 
> I'll open a issue in the box86 repo later.

Great job, @Itai-Nelken!

**Comment by CleanMachine1** [comment]
Looks like another dependency issue to me. It knows what GTK is but not what "paper" is

**Comment by Itai-Nelken** [comment]
https://github.com/ptitSeb/box86/issues/378

**Comment by Itai-Nelken** [comment]
I haven't tested it yet, but it might work?
also https://github.com/ptitSeb/box86/issues/400

**Comment by hmsjy2017** [comment]
Good news! Typora now supports Linux ARM64. There is a pre build for testing.
https://download.typora.io/linux/typora_0.11.18_arm64.deb
https://github.com/typora/typora-issues/issues/4282#issuecomment-972987534

**Comment by hmsjy2017** [comment]
@Itai-Nelken @Botspot

**Comment by theofficialgman** [comment]
since this issue has gone stale, might I suggest using vscode (or vscodium) with the builtin markdown previews or the many extensions that do a very good job of this.

typora is now a paid app as well with only a 15 day trial period. they appear to have abandoned distributing arm64 debs as well (only a tar.gz remains)

**Comment by Itai-Nelken** [comment]
> since this issue has gone stale, might I suggest using vscode (or vscodium) with the builtin markdown previews or the many extensions that do a very good job of this.
> 
> typora is now a paid app as well with only a 15 day trial period. they appear to have abandoned distributing arm64 debs as well (only a tar.gz remains)

If it's pajd now I guess we can't add it..
Closing
