### ISSUE TITLE
HFS

### ISSUE THREAD

**Issue by hmsjy2017** [Botspot/pi-apps#568]
http://www.rejetto.com/hfs/

"HFS" stands for "Http file server". This software has a GUI that makes sharing files easy and fast. It has been tested to run on Linux through wine.
https://appdb.winehq.org/objectManager.php?sClass=application&iId=5751
![E12B4E2B-15F0-4D5A-BC4D-2CCA75C8D92C](https://user-images.githubusercontent.com/42692274/114312001-ab000d00-9b23-11eb-8df7-a97d8f4b8053.png)

More screenshots can be found here:
http://www.rejetto.com/hfs/?f=ss

**Comment by CleanMachine1** [comment]
Never seen or used this, but who is using a http file server?
Most are using ftp and stfp

**Comment by Botspot** [comment]
How to download this?
The wine test's download link doesn't work.

**Comment by hmsjy2017** [comment]
@Botspot Use this link: http://www.rejetto.com/hfs/download

**Comment by Botspot** [comment]
> @Botspot Use this link: http://www.rejetto.com/hfs/download

This works well! How does it differ from something like Snapdrop?

**Comment by hmsjy2017** [comment]
@Botspot It has an interface like a resource manager, which makes it easier to manage files.It is extremely compatible and can even run normally on Windows 98.

**Comment by Botspot** [comment]
I have made the app!
[Https File Server.zip](https://github.com/Botspot/pi-apps/files/6722832/Https.File.Server.zip)
@hmsjy2017, please try it out and let me know if everything looks and works fine or if something needs tweaking.

**Comment by Botspot** [comment]
This app has been added to pi-apps with commit 18a3d0007d89a72f2c0b1b385487bc029b73ac95.
