### ISSUE TITLE
Zoom - Sign-in?

### ISSUE THREAD

**Issue by npgoalkeeper** [Botspot/pi-apps#57]
Hi! I recently stumbled upon this in a forum post, and thought it was great. However, when I tried to sign into Zoom via Google, I was unable to do so as Zoom would open a browser page then ask to open Zoom. Is there something I'm missing?

**Comment by Botspot** [comment]
Yea, I have heard that this has been an issue, with both Google sign-ins and SSO.  
I think it's related either vto Zoom's emulation layer, or to a missing library for xdg-open through the browser.

Either of the above option, I have no idea how to fix. I suggest you ask around on the [box86 Zoom thread](https://github.com/ptitSeb/box86/issues/193), and maybe also consider using the Zoom Chrome App via ChromeOS on RPi.

**Comment by npgoalkeeper** [comment]
Thank you for your response.
