### ISSUE TITLE
Add Minetest

### ISSUE THREAD

**Issue by TechDudie** [Botspot/pi-apps#575]
Can this app run on RPi? If so, please provide a link to a tutorial if applicable.

* Yes, it can.

Is this app something many GUI users would find useful?

* Yes, it’s a free Minecraft clone, and it is very fun.

Is this app installable with `sudo apt install`?

* No. 0.4.17.1 is installable with `sudo apt install minetest`, but to install Minetest the latest version, you have to build from source.

If you've created a zip file for this app, upload it here.

* Meh, the link is at:
  * https://github.com/minetest/minetest/releases/tag/5.4.1
  * https://minetest.net

**Comment by Botspot** [comment]
> Can this app run on RPi? If so, please provide a link to a tutorial if applicable.
> 
> * Yes, it can.

Are you sure about that? The [link](https://github.com/minetest/minetest/releases/tag/5.4.1) you provided points to an x86 Windows application.

RPis are neither x86, nor Windows. Do you know or not if this can run on RPi via Wine or not?

**Comment by TechDudie** [comment]
Yes - er no I’ve never heard of Wine. I just mean that’s the latest version, you have to go to that tag, wget it, and build from source (it can take about an hour from my experience)

**Comment by Botspot** [comment]
Update: I tried running the Minetest exe on my Pi4 using box86 + Wine. Surprisingly, it worked quite well on OpenGL, until I moved. Whenever you try to move, it becomes very laggy - around 3 fps.

**Comment by TechDudie** [comment]
Yeah, build from source. Wine dosent work very well with it apparently.

**Comment by TechDudie** [comment]
Oh, maybe should mention that as of 5.4.1, you have to build a special irrlicht (is the name correct?) because the minetest team forked the engine and edited it for Minetest themselves, also should mention that the long dependency install command is missing irrlicht-dev or something (for 5.4.0) and lib-bz2 I think.

**Comment by TechDudie** [comment]
The source code for 5.4.0 (the max u can use with the original irrlicht) is at

https://github.com/minetest/minetest/tree/5.4.0

**Comment by Painadath** [comment]
@TechDudie @Botspot i have also created a issue for minetest and mineclone 2 i build it 
https://github.com/Painadath/Minetest-raspi-builds/
look at the release page

**Comment by Painadath** [comment]
see #546

**Comment by Painadath** [comment]
with this i got about 20-50 FPS

**Comment by Painadath** [comment]
you have to install the game to /usr/local/share/minetest/

**Comment by Painadath** [comment]
#546  includes the zip for pi-apps app

**Comment by TechDudie** [comment]
Hmm... I think building from source is a good idea - wait I think no building needed, just build with the -DRUN_IN_PLACE flag on and it’ll build portable Minetest that can be copied onto *any* Raspberry Pi @Botspot @Painadath

**Comment by TechDudie** [comment]
Also, I recommend a place in pi-apps to install MineClone2 and EliasFleckenstein03s texture pack. Both require no installation, and the dev version has extra features atm such as swimming animations and elytra.

**Comment by Painadath** [comment]
@TechDudie that will take a lot of time and diskspace from building from source .that's why i packed it as a deb you can now install the games and textures to /usr/local/games/minetest/games/
PS: it takes about %)MB of space while building from source and takes about 5minutes and can fail any time whiel the deb is only 7MB

**Comment by Painadath** [comment]
@TechDudie @Botspot please try this app 
extarct it put it on pi-apps/apps folder and install it
[minetest_mineclone2.zip](https://github.com/Botspot/pi-apps/files/6340818/minetest_mineclone2.zip)

**Comment by Painadath** [comment]
@Botspot @TechDudie 
use this latest zip
https://github.com/Botspot/pi-apps/files/6343287/minetest_mineclone2.zip

**Comment by Botspot** [comment]
Why do we have two issues open for this?

#575
#546

**Comment by Painadath** [comment]
of course you can close one @Botspot 
but please test it

**Comment by Botspot** [comment]
Okay we'll keep #546 open.
