### ISSUE TITLE
Add Smashy Road Wanted 2

### ISSUE THREAD

**Issue by Pythonic456** [Botspot/pi-apps#579]
As this is only on the Play Store and iOS, I was wondering if you could do it the same way you have done Minecraft Bedrock.

[Smashy Road Wanted 2 - Google Play](https://play.google.com/store/apps/details?id=com.rkgames.basisgame&hl=en_GB&gl=US)

Thanks!

**Comment by Botspot** [comment]
Highly unlikely.

@mobilegmYT

**Comment by mobilegmYT** [comment]
> Highly unlikely.
> 
> @mobilegmYT

I feel *pinged*.

Unless we get anbox working, this won't run.

**Comment by Pythonic456** [comment]
Ok sure. Thanks for considering it anyway!
