### ISSUE TITLE
App Reviews, Ratings, Screenshots, and Preview Videos

### ISSUE THREAD

**Issue by GabeCoder** [Botspot/pi-apps#585]
Pi Apps is already one of the perfect app stores to install your favorite applications from since it is easy to use.
I have some suggestions for Pi Apps to make it similar to the Apple App Store and the Microsoft Windows Store.

There should come a new feature, **App Reviews**. Reviews on the Pi Apps store are important for users to understand how people think of an app. If most reviews are positive, then the user will most likely install it. If most reviews are negative, then the user will most likely look for another app. Reviews will be located in the information box of an application. To create a review can be submitted in the **Issues** section of the Pi Apps repository. Otherwise, a simple web server can be set up to collect reviews from users who install an application. This web server can be curled by the computer using the Pi Apps store to collect reviews. It can also be utilized to collect **ratings** from users, as this helps out even more.

If adding reviews and ratings is too hard, there's always an easy feature to add, which are **screenshots**. Users can preview the app and how it does what it does before installing it. This makes it easier for them to understand the app. In the app wizard, there can be an option to add screenshots or **videos** to the app's information.

**Comment by Botspot** [comment]
> I have some suggestions for Pi Apps to make it similar to the Apple App Store and the Microsoft Windows Store.

That's an issue right there: I'm not envisioning Pi-Apps to be like an conventional app store. It's more meant to be a simple software catalog.

> There should come a new feature, **App Reviews**.
> It can also be utilized to collect **ratings** from users, as this helps out even more.

Those two would require more moderation and oversight. And I already have a busy schedule with the app backlog. Where will this new time come from?

Not to mention the technical difficulties.

**Comment by CleanMachine1** [comment]
As mentioned, just more pointless work, if someone wants to leave feedback they will post an issue here.
However Botspot could probably add a new tag for the issues section then add a hyperlink to the Github issues 

Then again, I am not Botspot :rofl:
Just giving my idea

**Comment by GabeCoder** [comment]
What about screenshots? I actually am wondering how to add screenshots to a YAD dialog. Since you're an expert, you probably will be able to find out how to add screenshots.

**Comment by CleanMachine1** [comment]
I assume you are talking to Botspot since I don't know a thing about using yad.

why would you want to add screenshots? 
For the user to see before using?

I guess it could be done pretty easily, adding a new folder for each app called Screenshots, then a picture

**Comment by Botspot** [comment]
> What about screenshots? I actually am wondering how to add screenshots to a YAD dialog.

It's pretty easy. See the yad tutorial here: http://smokey01.com/yad/  
In this case, you'd be interested in yad's `--image=` flag. Example:
```
yad --image /root/iow2.jpg
```
Limitations:
- Only one image can be displayed at a time.
- The image will not be scaled to fit the window.

**Comment by CleanMachine1** [comment]
We can merge photos to one if required.
Is this the sort of "screenshot" you are looking for?

**Comment by CleanMachine1** [comment]
![vscode](https://user-images.githubusercontent.com/78213164/115429793-a7434900-a1fb-11eb-8fa3-109691f56f9a.png)
ignore flameshot being annoying

**Comment by Botspot** [comment]
A picture is worth a thousand words. Adding screenshots to each app seems like a good idea, but I don't think it's the top priority.

For now, this idea will sit on the shelf. **If someone else wants to take screenshots of everything,** then we can implement this feature sooner rather than later.

**Comment by GabeCoder** [comment]
> A picture is worth a thousand words. Adding screenshots to each app seems like a good idea, but I don't think it's the top priority.
> 
> For now, this idea will sit on the shelf. **If someone else wants to take screenshots of everything,** then we can implement this feature sooner rather than later.

I’d be willing to screenshot my apps, but you know what they say. A picture is worth a thousand words.
I still need to add more to my vocabulary.
