### ISSUE TITLE
HalfLife

### ISSUE THREAD

**Issue by RaspberryRBX** [Botspot/pi-apps#59]
[HalfLife.zip](https://github.com/Botspot/pi-apps/files/5484443/HalfLife.zip)

**Comment by Botspot** [comment]
When I try to run Half life it says ```
pi@raspberrypi:~ $ /home/pi/games/half-life/half-life.sh
Copy your valve directory before start. I'll do the rest :)
```

**Comment by mobilegmYT** [comment]
Well, you need the actually have the game files for halflife. Otherwise, that's just piracy.

**Comment by Botspot** [comment]
I've decided to close this issue.  
I think many Pi-Apps users won't have the game files on hand, and if this were added, 99% of people would walk away disappointed.
