### ISSUE TITLE
Zoom microphone

### ISSUE THREAD

**Issue by SuperPi911** [Botspot/pi-apps#590]
My usb mic isn't working with zoom

**Comment by mobilegmYT** [comment]
> My usb mic isn't working with zoom

Well does it work with other apps?

**Comment by SuperPi911** [comment]
Yes

**Comment by Itai-Nelken** [comment]
its a known issue, I think ptitseb (the creator of box86) thinks its a problem with how pulseaudio is wrapped.
see https://github.com/ptitSeb/box86/issues/193 for more details.
