### ISSUE TITLE
New version of GH-CLI 

### ISSUE THREAD

**Issue by CleanMachine1** [Botspot/pi-apps#591]
A new release is available
This may interest you @Itai-Nelken

**Comment by Itai-Nelken** [comment]
pi-apps has the latest release as of #580

**Comment by CleanMachine1** [comment]
https://github.com/cli/cli/releases/tag/v1.9.2

**Comment by Itai-Nelken** [comment]
oh, its only a tag, no release. I'll ad 1.9.2 when they release it with the binaries (probably very soon if the tag already exists).
thanks for opening this issue anyway.

**Comment by CleanMachine1** [comment]
Ok, didn't know, you're welcome though

**Comment by CleanMachine1** [comment]
The binaries are now available!

Just received an update with apt

**Comment by Itai-Nelken** [comment]
done #592 
thanks @CleanMachine1!
