### ISSUE TITLE
Spotify, but its probably not possible

### ISSUE THREAD

**Issue by MichalAsik** [Botspot/pi-apps#594]
Can this app run on RPi? If so, please provide a link to a tutorial if applicable.  
Is this app something many GUI users would find useful?  
Is this app installable with `sudo apt install`?  

If you've created a zip file for this app, upload it here.

**Comment by mobilegmYT** [comment]
> Can this app run on RPi? If so, please provide a link to a tutorial if applicable.
> Is this app something many GUI users would find useful?
> Is this app installable with `sudo apt install`?
> 
> If you've created a zip file for this app, upload it here.

I believe the spotify desktop client won't run in Wine.

**Comment by Botspot** [comment]
@MichalAsik, are you looking to _play_ Spotify on your Pi?

If so, [use Chromium Widevine](https://www.raspberrypi.org/forums/viewtopic.php?f=63&t=290443).

**Comment by CleanMachine1** [comment]
On X86, there is a full linux version
Heres a link to the repo which apt would use to keep it updated

https://repository-origin.spotify.com/pool/non-free/s/spotify-client/

I think it would probably work with BOX86

**Comment by Botspot** [comment]
> On X86, there is a full linux version
> Heres a link to the repo which apt would use to keep it updated
> 
> https://repository-origin.spotify.com/pool/non-free/s/spotify-client/
> 
> I think it would probably work with BOX86

Interesting. Just for fun, I installed box86 inside a RPi virtual machine and then installed the i386 Spotify deb.  
Trying to run it with box86 resulted in this error:
```
Error loading needed lib: "libnss3.so"
Error loading needed lib: "libcef.so"
```

All commands necessary to install it:
```
#install box86 FIRST!
wget -O ~/spotify-client.deb https://repository-origin.spotify.com/pool/non-free/s/spotify-client/spotify-client_1.0.72.117.g6bd7cc73-35_i386.deb #I had a ton of network errors, but it finally finished downloading.
sudo dpkg --force-all -i ~/spotify-client.deb
```
The command I used to run it and to see the library errors:
```
BOX86_LOG=1 spotify
```

**Comment by CleanMachine1** [comment]
>  I installed box86 inside a RPi virtual machine and then installed the i386 Spotify deb.

Don't act like you said nothing! 
How do I get a ARM32 VM?
Are you on a pi in a pi like your vdesktop or on a X86 Machine?

**Comment by mobilegmYT** [comment]
> > I installed box86 inside a RPi virtual machine and then installed the i386 Spotify deb.
> 
> Don't act like you said nothing!
> How do I get a ARM32 VM?
> Are you on a pi in a pi like your vdesktop or on a X86 Machine?

He's using desktop for the VM, box86 can install x86 debs.

**Comment by CleanMachine1** [comment]
I am unaware how Box86 works with dependencies, however libnss3 is in the official apt repos but I don't know about the other one

**Comment by Itai-Nelken** [comment]
libnss3 isn't wrapped by box86, I have a copy of it in the zip I uploaded to the typora issue (https://github.com/Botspot/pi-apps/issues/567#issuecomment-823409525), just put it in the same folder as the spotify executable.
***
also the spotify client for linux is super heavy and slow, so I doubt it will run well on the pi, especially if its being emulated.

**Comment by Botspot** [comment]
> > I installed box86 inside a RPi virtual machine and then installed the i386 Spotify deb.
> 
> Don't act like you said nothing!
> How do I get a ARM32 VM?

It's a armhf vm running on my Pi. No emulation necessary, just a container.

The only reason I used a VM was because it's a clean slate I can work off of, and I don't care if the OS gets trashed. Installing x86 debs using scary-sounding flags like `--force-all` sometimes ends in [scary results](https://github.com/Botspot/pi-apps/issues/128).

**Comment by Botspot** [comment]
Closing this issue for these reasons:

- Spotify can already be played using Chromium Widevine.
- It doesn't successfully install.
- Even if it did, it would [likely run too slowly](https://github.com/Botspot/pi-apps/issues/594#issuecomment-825821328) to be of any use.
