### ISSUE TITLE
Dolphin Emulator App Request

### ISSUE THREAD

**Issue by ghost** [Botspot/pi-apps#595]
Can this app run on RPi? If so, please provide a link to a tutorial if applicable.   It runs only on arm64 and will run on raspberry pi 4
Is this app something many GUI users would find useful? yes 
Is this app installable with `sudo apt install`?  yeah and old outdated one on ubuntu only

Bash Script to Install
```
bash <( curl https://raw.githubusercontent.com/cobalt2727/L4T-Megascript/master/helper.sh ) "scripts/games_and_emulators/dolphin/main.sh"
```
link edited by theofficialgman

This is only for arm64 oses on Raspberry Pi
This is a replacement for the 6-7 year old port of dolphin on PiKiss for Raspberry Pi
The version on Pi Kiss is so out of date it shouldn't be used
The script here installs a recent version of Dolphin Emulator that is a beta build whch is much newer.

This newer version of dolphin has vulkan support and could be configured in the future with the pi 4's vulkan drivers and future pi's

**Comment by Vasslepulver** [comment]
The Raspberry Pi isn't currently powerful enough to run the Dolphin emulator in any of it's configurations. It's a great emulator though and well worth checking out on a faster machine. It even runs Wii titles with the ability to use Wiimotes and Gamecube controllers natively with zero input lag.So i dont think its a good idea to add this to Pi Apps sorry :)

**Comment by theofficialgman** [comment]
was browsing through here, yeah sorry I changed the location for that file on the github
regardless, you should not be directly running a file from the megascript since the megascript functions will not be loaded and the script will have many errors

the only supported way of installing megascript apps from cli is using our helper script to do so
```
bash <( curl https://raw.githubusercontent.com/cobalt2727/L4T-Megascript/master/helper.sh ) "games_and_emulators/dolphin/main.sh"
```
