### ISSUE TITLE
fail install wechat

### ISSUE THREAD

**Issue by huangguiniab** [Botspot/pi-apps#597]
I live in China. When I tried to install it, I found that he tried to visit *.archive.org, but for some strange reason, my country blocked this website, so I couldn’t install this application.
And it is illegal to use VPN in my country. Is there any other way to install this software?

**Comment by Botspot** [comment]
Strangely enough, [Wechat's installation script](https://github.com/Botspot/pi-apps/blob/master/apps/Wechat/install-32) doesn't mention archive.org anywhere.

**Comment by CleanMachine1** [comment]
I recently learnt that raw.githubusercontent is also banned, that's probably your issue rather than archive . org

**Comment by mobilegmYT** [comment]
> Strangely enough, [Wechat's installation script](https://github.com/Botspot/pi-apps/blob/master/apps/Wechat/install-32) doesn't mention archive.org anywhere.

Well when winetricks installed everything, it downloaded the packages from archive.org where they were hosted. It would be a pain in the butt to find each package winetricks uses and then make pi-apps manually install them.

**Comment by huangguiniab** [comment]
[a.log](https://github.com/Botspot/pi-apps/files/6368798/a.log)

**Comment by huangguiniab** [comment]
I agree that it is winetricks' problem, because archive.org is indeed not seen in the installation script, but when I installed it, 
https://web.archive.org/web/20060720160141/https://download.microsoft.  com/download/WindowsInstaller/Install/2.0/W9XMe/EN-US/InstMsiA.exe
, please help me download it for me?  Upload to github.

**Comment by mobilegmYT** [comment]
> I agree that it is winetricks' problem, because archive.org is indeed not seen in the installation script, but when I installed it,
> https://web.archive.org/web/20060720160141/https://download.microsoft.com/download/WindowsInstaller/Install/2.0/W9XMe/EN-US/InstMsiA.exe
> , please help me download it for me? Upload to github.


[instmsiA.zip](https://github.com/Botspot/pi-apps/files/6368803/instmsiA.zip)

**Comment by huangguiniab** [comment]
> > I agree that it is winetricks' problem, because archive.org is indeed not seen in the installation script, but when I installed it,
> > https://web.archive.org/web/20060720160141/https://download.microsoft.com/download/WindowsInstaller/Install/2.0/W9XMe/EN-US/InstMsiA.exe
> > , please help me download it for me? Upload to github.
> 
> [instmsiA.zip](https://github.com/Botspot/pi-apps/files/6368803/instmsiA.zip)

Thank you very much for replying to me so quickly, but even though I manually executed this file in wine, winetrick will still try to download it from the Internet.

**Comment by mobilegmYT** [comment]
> > > I agree that it is winetricks' problem, because archive.org is indeed not seen in the installation script, but when I installed it,
> > > https://web.archive.org/web/20060720160141/https://download.microsoft.com/download/WindowsInstaller/Install/2.0/W9XMe/EN-US/InstMsiA.exe
> > > , please help me download it for me? Upload to github.
> > 
> > 
> > [instmsiA.zip](https://github.com/Botspot/pi-apps/files/6368803/instmsiA.zip)
> 
> Thank you very much for replying to me so quickly, but even though I manually executed this file in wine, winetrick will still try to download it from the Internet.

well you need to edit winetricks and change the code to install exe and not download from internet.

**Comment by huangguiniab** [comment]
Indeed, winetrack is actually a bash script. I believe that by modifying some parts of it, this restriction can be lifted, I have read for an afternoon, but i cant understand all it.
And this problem has nothing to do with this project, because the problem lies with wine, not this project, I think this issue can be closed.
