### ISSUE TITLE
Add checksum to apps

### ISSUE THREAD

**Issue by CleanMachine1** [Botspot/pi-apps#598]
There should be a feature added to automatically checksum all new additions to pi-apps and slowly work on older ones

This feature would only really be efficient on apps where the checksum won't change often such as timeshift

This feature should be thing as newbs won't ever checksum since they don't know what it is

Adding a checksum to new apps should be done by adding a new page on the app creator and making the maker add a checksum, although I feel some would not understand what this is

**Comment by CleanMachine1** [comment]
SHA256 is the standard and in the app installer it would need to be run on the machine then compare to the already written SHA256sum.txt file

**Comment by Botspot** [comment]
> There should be a feature added to automatically checksum all new additions to pi-apps

And the point of this would be...?

**Comment by CleanMachine1** [comment]
Stopping different types of attacks such as Man in the middle.

It just makes sure the software being installed is what left the developer and hasn't been edited

**Comment by Botspot** [comment]
> Stopping different types of attacks such as Man in the middle.
> 
> It just makes sure the software being installed is what left the developer and hasn't been edited

Are you envisioning the _apps themselves_ being checksummed, or do you envision that everything an app _downloads_ be checksummed?

**Comment by CleanMachine1** [comment]
The Deb files that are being downloaded should be checked

I understand some programs wont have the checksums listed however it should be a question in the app creator, also @chunky-milk could/should checksum the programs in his repo, big task but could be done over time as each app receives an update, and just have a big .txt file with all the checksums

**Comment by chunky-milk** [comment]
> The Deb files that are being downloaded should be checked
> 
> I understand some programs wont have the checksums listed however it should be a question in the app creator, also @chunky-milk could/should checksum the programs in his repo, big task but could be done over time as each app receives an update, and just have a big .txt file with all the checksums 

Hmm. Sounds like a lot of work that'll take up time I don't have.

**Comment by Botspot** [comment]
> The Deb files that are being downloaded should be checked

Have you considered all the edge cases for that?

- An app that installs multiple deb files
- An app that installs different deb files depending on the situation
- An app that downloads some other form of archive instead

Also, how would an ordinary app creator know how to checksum their app properly?

**Comment by CleanMachine1** [comment]
> > The Deb files that are being downloaded should be checked
> > 
> > I understand some programs wont have the checksums listed however it should be a question in the app creator, also @chunky-milk could/should checksum the programs in his repo, big task but could be done over time as each app receives an update, and just have a big .txt file with all the checksums 
> 
> Hmm. Sounds like a lot of work that'll take up time I don't have. 

Well it could be something you could automate with a shell script

**Comment by CleanMachine1** [comment]
> > The Deb files that are being downloaded should be checked
> 
> 
> 
> Have you considered all the edge cases for that?
> 
> 
> 
> - An app that installs multiple deb files
> 
> - An app that installs different deb files depending on the situation
> 
> - An app that downloads some other form of archive instead
> 
> 
> 
> Also, how would an ordinary app creator know how to checksum their app properly?

Keep it as an optional step, not all know what a checksum is

**Comment by Botspot** [comment]
> > Also, how would an ordinary app creator know how to checksum their app properly?
> Well it could be something you could automate with a shell script

I don't want to go down the road of having pi-apps automatically detect things within bash scripts. Going down such a path would just be begging for endless edge cases and annoying situations.

**Comment by CleanMachine1** [comment]
True but checksums should be a standard part of installing applications, everything I download such as ISOs and .deb I checksum

**Comment by CleanMachine1** [comment]
Even if 10 apps have checksum, its still better than 0

**Comment by Botspot** [comment]
> True but checksums should be a standard part of installing applications, everything I download such as ISOs and .deb I checksum

I understand, but having an automated script make decisions based on the content of a user-generated bash script is just _begging_ for a large number of bugs.

> Even if 10 apps have checksum, its still better than 0

It's the job of the scriptwriter to implement this. It's not pi-apps' job to detect downloaded debs and automatically checksum them with a hash in a text file.
@CleanMachine1, if you want to submit PRs for all the deb-downloading apps for improved security, go ahead. Just be aware that it will require an extra step when updating app deb versions. (rather than change the version number in the URL, we'd now have to download it and change the hash too)

I don't have the time or patience to implement this.

**Comment by CleanMachine1** [comment]
I'll do a few

**Comment by Itai-Nelken** [comment]
@CleanMachine1 @chunky-milk's debs arfrom h8s apt repo, so every package has a md5sum and a sha256sum as well I think.

**Comment by CleanMachine1** [comment]
Who is h8s?

**Comment by Itai-Nelken** [comment]
> @CleanMachine1 @chunky-milk's debs from his apt repo, so every package has a md5sum and a sha256sum as well I think.

**Comment by Itai-Nelken** [comment]
> Who is h8s?

@CleanMachine1 a typo, I fixed it.

**Comment by CleanMachine1** [comment]
I just checked the repo and each app does have a SHA256Sum attached under dist

**Comment by Itai-Nelken** [comment]
The sha256sums will change each time @chunky-milk updates the app, so I don't think its a good idea.

**Comment by chunky-milk** [comment]
> The sha256sums will change each time @chunky-milk updates the app, so I don't think its a good idea. 

Yes, and the old deb files are deleted to make way for a new one every time I update it.

**Comment by CleanMachine1** [comment]
2 solutions 


Only checksum non frequent updated programs 

Let the user just pass a warning that the checksums isn't the same and tell them to report it here

**Comment by chunky-milk** [comment]
> Let the user just pass a warning that the checksums isn't the same and tell them to report it here

Sounds like a lot of work...

And also, if we give a warning to the user, they might think pi apps is insecure, and stop using it. I'm sure @Botspot wont like that. 

Please don't think I'm trying to shoot down your idea, I would like to help find possible solutions.

**Comment by CleanMachine1** [comment]
Well implementing the optional warning would be easy, just using the read command then match it against something like y or n 

To be honest, this is the second time that pi-apps has come before peoples personal security, I don't feel that is right.
I understand that a newb might be turned off but you could make the warning message something like


"The checksum for this download doesn't match what the developer has provided
This most likely means a maintainer (CleanMachine1) hasn't kept the checksum up to date, however it is worth leaving a message at pi-apps Issue section, just in case the download has been hacked!"

**Comment by Itai-Nelken** [comment]
> "The checksum for this download doesn't match what the developer has provided
This most likely means a maintainer (CleanMachine1) hasn't kept the checksum up to date, however it is worth leaving a message at pi-apps Issue section, just in case the download has been hacked!"

If I was  newb and saw that message, I would probably delete pi-apps immediately.

**Comment by CleanMachine1** [comment]
What would you write then?
Because thats the best I have

**Comment by Itai-Nelken** [comment]
Maybe something without 'hacked' in it, something like this maybe (your suffestion, but edited a but);
"The checksum for this download doesn't match what the developer has provided
This most likely means a maintainer (CleanMachine1) hasn't kept the checksum up to date, however it is worth leaving a message at pi-apps Issue - section, because its less secure!"

I don't think it's better than your suggestion @CleanMachine1, but it wouldn't make me want to uninstall pi-apps.

**Comment by CleanMachine1** [comment]
Well someone has to tell them!

Also checksuming takes between a few seconds and and 20 seconds depending on the size of the download.

I don't like the "its less secure", if a download is being hacked and malformed, I would want the user to take it seriously rather than it being less secure

We could attach a website URL to something which explains what the checksum is, such as an issue here (locked)

However we could add at the top

===Authenticity of download===
===Most likely nothing but please submit a issue to the Github!===
Please copy this and supply the app you intended to install
