### ISSUE TITLE
APT Cleaner

### ISSUE THREAD

**Issue by GabeCoder** [Botspot/pi-apps#599]
APT Cleaner is a Debian tool for cleaning your operating system by removing bloatware from your disk. As simple as it is, it only takes one click to start the cleanup process. Plus, APT Cleaner cleans your disk once you log in.
Here is the archive for the app.
[APT Cleaner.tar.gz](https://github.com/Botspot/pi-apps/files/6372076/APT.Cleaner.tar.gz)

**Comment by CleanMachine1** [comment]
First of all, it assumes that the user has lxterminal installed. I don't for example.
Second, it doesn't do really anything other than sudo apt autoremove -y...
I have added a PR to make it a little better (Not Actually Submitted yet)
However, overall this is a really simple script that almost does _nothing_.

**Comment by mobilegmYT** [comment]
Maybe you could research how bleachbit and stacer clean out the apt repos more, and try to implement them in your script.

**Comment by CleanMachine1** [comment]
Yes exactly, what tends to be the biggest usage of data space is locales and languages, EG if you have libreoffice installed, deleting all the languages help pages can save up to 1G!

**Comment by GabeCoder** [comment]
> First of all, it assumes that the user has lxterminal installed. I don't for example.
> Second, it doesn't do really anything other than sudo apt autoremove -y...
> I have added a PR to make it a little better (Not Actually Submitted yet)
> However, overall this is a really simple script that almost does _nothing_.

#roasted

**Comment by CleanMachine1** [comment]
Sorry to have to insult you and your product but it doesn't really "clean" a machine

**Comment by GabeCoder** [comment]
> Sorry to have to insult you and your product but it doesn't really "clean" a machine

Actually, it’s not supposed to clean your hardware. It’s “clean” name is meant for freeing up space from your software.

**Comment by CleanMachine1** [comment]
I call instances of OS's, machines, sorry for the confusion

if you accept my PR on your github, the software would already be better

**Comment by GabeCoder** [comment]
> I call instances of OS's, machines, sorry for the confusion
> 
> if you accept my PR on your github, the software would already be better

yes sir

**Comment by CleanMachine1** [comment]
Thank you, sir :tophat:

**Comment by GabeCoder** [comment]
I actually just realized, the terminal doesn’t open if more than one command is run in the script, even with proper quotation.

**Comment by CleanMachine1** [comment]
Also I wouldn't want it to purge everything so often, I have had it a few times when I have nearly broken an install because apt thought it would be a great idea to purge something like my entire desktop :facepalm: however because an automatic script didn't do it for me, I managed to save it with blacklisting removing certain parts

I run sudo apt autoremove after removing a program, however I would never use it with -y

**Comment by CleanMachine1** [comment]
>I actually just realized, the terminal doesn’t open if more than one command is run in the script, even with proper quotation.

turn the command into a script then do the lxterminal -e "script.sh"

I will get on writing the documentation, its my favourite thing :eyes:

**Comment by GabeCoder** [comment]
> Also I wouldn't want it to purge everything so often, I have had it a few times when I have nearly broken an install because apt thought it would be a great idea to purge something like my entire desktop 🤦 however because an automatic script didn't do it for me, I managed to save it with blacklisting removing certain parts
> 
> I run sudo apt autoremove after removing a program, however I would never use it with -y

Updating some scripts...

**Comment by GabeCoder** [comment]
Here is an updated archive with an edited install script. There are some new lines including the enabling of the main script.
[APT Cleaner.tar.gz](https://github.com/Botspot/pi-apps/files/6370066/APT.Cleaner.tar.gz)

**Comment by CleanMachine1** [comment]
Unaware if you have seen but I have submitted a PR on your repo fixing some documentation!

**Comment by GabeCoder** [comment]
I just updated the credits by adding @CleanMachine1 to the scripting.
[APT Cleaner.tar.gz](https://github.com/Botspot/pi-apps/files/6370076/APT.Cleaner.tar.gz)

**Comment by Botspot** [comment]
> I actually just realized, the terminal doesn’t open if more than one command is run in the script, even with proper quotation.

Pi-Apps had the same problem. Eventually I found a way to make most major terminals run multi-line commands, by using pi-apps's `pkg-install script`. Maybe that would help you?

**Comment by mobilegmYT** [comment]
> > I actually just realized, the terminal doesn’t open if more than one command is run in the script, even with proper quotation.
> 
> Pi-Apps had the same problem. Eventually I found a way to make most major terminals run multi-line commands, by using pi-apps's `pkg-install script`. Maybe that would help you?

Isn't it terminal-run?

**Comment by Botspot** [comment]
> Isn't it terminal-run?

Yes. :(

**Comment by GabeCoder** [comment]
Here is the new package.
[APT Cleaner.tar.gz](https://github.com/Botspot/pi-apps/files/6372035/APT.Cleaner.tar.gz)

**Comment by GabeCoder** [comment]
Here is a stable package.
[APT Cleaner.tar.gz](https://github.com/Botspot/pi-apps/files/6372074/APT.Cleaner.tar.gz)

**Comment by zachthecoder14** [comment]
I’d very much like to see this on Pi Apps :)

**Comment by donnerkebab1730** [comment]
same:)

**Comment by CleanMachine1** [comment]
`sudo apt update && sudo apt autoremove`
done..

**Comment by donnerkebab1730** [comment]
wait its on pi apps

**Comment by donnerkebab1730** [comment]
have i missed something?

**Comment by CleanMachine1** [comment]
All this does is run 3 commands.

**Comment by donnerkebab1730** [comment]
ik but it would be nice to see this on pi apps

**Comment by CleanMachine1** [comment]
Why.

**Comment by donnerkebab1730** [comment]
Well not even is going to see this but it would be nice for them to able to do this

**Comment by CleanMachine1** [comment]
Sorry if I am wrong but you must be new to Linux. The best way to learn Linux is doing, not running scripts from other people

**Comment by GabeCoder** [comment]
> Sorry if I am wrong but you must be new to Linux. The best way to learn Linux is doing, not running scripts from other people

So technically, you shouldn’t be running Pi-Apps, which is a set of scripts from Botspot.

**Comment by CleanMachine1** [comment]
I don't and never have!
I prefer source builds and fixing my own errors.
I just like to contribute, however I have moved on a little and starting to maintain tldr-pages/tldr

**Comment by CleanMachine1** [comment]
If a user is running Pi-Apps I hope they take the time to at least read the scripts and understand what they do. Linux maybe secure but its not perfect, you can still get malware.
And considering Pi-Apps can run sudo commands since the raspberry Pi is a NOPASSWD OS, whats stopping botspot from running a dd of my entire drive, not that he would since that would ruin all the hard work he has put here

**Comment by CleanMachine1** [comment]
Plus I don't really use the pi any more apart from server usage. Switched over to Arch X86

**Comment by donnerkebab1730** [comment]
> Sorry if I am wrong but you must be new to Linux. The best way to learn Linux is doing, not running scripts from other people

- [ ] Ye I am fairly new but I think using projects from others to make your own is very good. Also I'm to lazy to make it .myself...

**Comment by CleanMachine1** [comment]
Learning Bash is a pretty big deal in Linux, you will be able to make automation scripts.

My newest bash script gives a button on my laptop the function to print a terminal with loads of useful information to me

**Comment by donnerkebab1730** [comment]
Ik it's just I've been putting it off for other things ( though I know a tiny bit)

**Comment by mobilegmYT** [comment]
> I just like to contribute, however I have moved on a little and starting to maintain tldr-pages/tldr

~~Add pi-apps to tldr~~

And just to throw in my chips here, pi-apps is for complex or install or unknown apps which desktop users would want. I mean it's fine if a user doesn't know how to compile a game, but like... you gotta force them to learn the basics of bash and apt... it would be harder to open start menu, find this thing, and run it instead of just running `sudo apt update` and `sudo apt upgrade` or learning how to make a bash alias.

**Comment by CleanMachine1** [comment]
Has Pi-Apps got a command line parameters. Heres a prime example of a tldr page, 

$ tldr upower (my first page I did)

upower
System utility to provide power and battery information and statistics.More information: https://upower.freedesktop.org/docs/upower.1.html.

 - Display power and battery information:
   upower --dump

 - List all power devices:
   upower --enumerate

 - Watch for and print power status changes:
   upower --monitor

 - Watch for and print detailed power status changes:
   upower --monitor-detail

 - Display version:
   upower --version

**Comment by mobilegmYT** [comment]
> Has Pi-Apps got a command line parameters. Heres a prime example of a tldr page,
> 
> $ tldr upower (my first page I did)
> 
> upower
> System utility to provide power and battery information and statistics.More information: https://upower.freedesktop.org/docs/upower.1.html.
> 
> * Display power and battery information:
>   upower --dump
> * List all power devices:
>   upower --enumerate
> * Watch for and print power status changes:
>   upower --monitor
> * Watch for and print detailed power status changes:
>   upower --monitor-detail
> * Display version:
>   upower --version

Ohhh yea,,, I forgot vanilla pi-apps only opened the GUI. I thought botspot made it also use the api script when arguments was passed though.

**Comment by Itai-Nelken** [comment]
there are 3 pi-apps terminal programs that make pi-apps usable from the terminal only:
1) @techcoder20's script (python): https://github.com/techcoder20/PiAppsTerminalAdvanced/
2) my script (bash): https://github.com/Itai-Nelken/PiApps-terminal_bash-edition
3) my C program (private repo, not finished yet).

**Comment by Botspot** [comment]
> And considering Pi-Apps can run sudo commands since the raspberry Pi is a NOPASSWD OS, whats stopping botspot from running a dd of my entire drive, not that he would since that would ruin all the hard work he has put here

That is a valid concern. But you could potentially say the same thing for _any_ app installer or program. _Anything_ being run as root could maliciously wipe your drive. Including apt-get.
Remember, whenever you run `sudo apt install `, you are literally running a bash script contained in that deb file, as the `root` user. What's the difference? There is no difference - apt could destroy your system just as easily as pi-apps could, if a bad actor injected a line of destructive code.

It comes down to this: Just like you have to trust the package maintainers to not ship damaging code, you have to trust me to not ship malicious code either. (And of course, feel free to inspect the scripts - that's what the new "Scripts" button in Pi-Apps is for.)

**Comment by CleanMachine1** [comment]
No, apt is maintained by trusted individuals who approval each update and change

**Comment by Botspot** [comment]
> No, apt is maintained by trusted individuals who approval each update and change

This all still boils down to trust. In both cases, _people_ are in control of root-run bash scripts that are fully capable of wiping your system drive. You may trust the repository maintainers more than you trust me, and maybe rightfully so since it's less likely for the entire group of them to agree to do something malicious.

But from a _technical_ standpoint, it's equally easy for a repository maintainer to ship you destructo-ware, as it is for a Pi-Apps maintainer to ship you destructo-ware.

How did this conversation even start anyway? :)

**Comment by GabeCoder** [comment]
APT Cleaner doesn’t have to be approved for Pi-Apps, but I’d still recommend this helpful tool.

**Comment by GabeCoder** [comment]
So far, nobody else has commented on this. @Botspot, what do you think? Should this “useful” tool be added to Pi-Apps, or should you reject it?

**Comment by GabeCoder** [comment]
I have updated the APT Cleaner package with minorly edited scripts.
[APT Cleaner.tar.gz](https://github.com/Botspot/pi-apps/files/6786434/APT.Cleaner.tar.gz)

**Comment by Botspot** [comment]
Hey @GabeCoder, do you think you could get APT cleaner to detect if a repository has been **configured twice**, and to automatically (or ask to) correct the problem?

**Comment by CleanMachine1** [comment]
What do you mean by "configured"

**Comment by Botspot** [comment]
> What do you mean by "configured"

It's easier to demonstrate than to explain.
Edit `/etc/apt/sources.list` and copy one of the uncommented lines. Then paste the line again so there are two duplicate lines.
Save the file and run `sudo apt update`. APT will complain that you have sources configured twice.
I think a bash script can detect this and automatically get rid of duplicate lines from that file.
If we wanted to be thorough, it should also check the files in `/etc/apt/sources.list.d` and ensure that there are no duplicate lines between any of them and sources.list, but that would be complicated and the chances of someone configuring a source twice in one of those subfiles is very slim.

**Comment by CleanMachine1** [comment]
Ah, I forgot that the apt entries are repos, I consider them as mirrors (which they aren't) and repos for Git

**Comment by Itai-Nelken** [comment]
Here is a way to fix duplicates:
```
sudo rm -f ~/sources.list /etc/apt/sources.list.bak
#the part that actually deletes the dupicates
awk '/^$/ {print; next} {if ($1 in a) next; a[$1]=$0; print}' /etc/apt/sources.list > ~/sources.list
sudo mv /etc/apt/sources.list /etc/apt/sources.list.bak
sudo mv ~/sources.list /etc/apt/sources.list 
```

I'm not sure how reliable it is, but it worked when I tested it

It also creates a backup just in case.

**Comment by CleanMachine1** [comment]
might want to update the package cache after doing that

**Comment by Botspot** [comment]
I think it makes most sense to add this to the "All Is Well" app, instead of making a separate app.

And Pi-Apps [now diagnoses](https://github.com/Botspot/pi-apps/blob/335dbbb8b3686db5a71e07dca2dabee549b0958b/pkg-install#L33-L194) apt errors.
