### ISSUE TITLE
[App request] piKiss

### ISSUE THREAD

**Issue by mobilegmYT** [Botspot/pi-apps#6]
[piKiss.zip](https://github.com/Botspot/pi-apps/files/5319551/piKiss.zip)
Also, you probably should add an update button in the main screen GUI instead of running the command every time.

**Comment by mobilegmYT** [comment]
nvm

**Comment by Botspot** [comment]
Pi-Apps automatically checks for updates once a day.
I'm working to add a Settings window, which will tie up a bunch of loose ends like this one.

**Comment by Botspot** [comment]
PS. For future apps, I would prefer if you open an issue and attach a .zip.
Doing a Pull Request took me a lot longer, as I had to create a new directory, `git checkout`, `git pull`, then some cp commands to move it to my main pi-apps folder.

**Comment by mobilegmYT** [comment]
Oh I thought it was easier because you could just use the website and click "Merge"

**Comment by Botspot** [comment]
Well sure, but before I merge it, I have to download the files and make sure the code follows specs, works reliably, doesn't contain malware, will update properly, you name it.
So if it's a long process to download your code for testing, then other ways (like a zip file) would be preferable.

**Comment by mobilegmYT** [comment]
Ahh I see

**Comment by mobilegmYT** [comment]
Certainly makes it harder to make edits though.

**Comment by Botspot** [comment]
Very true.
If we could work with PRs it would certainly have some advantages.
But for now, I think .zip files are just a simpler way to do it. And if any edits need to be made I can make them myself before uploading changes.

If you have any other ides for streamlining the process, I'd like to hear them though.
