### ISSUE TITLE
available on pi apps graphic

### ISSUE THREAD

**Issue by Itai-Nelken** [Botspot/pi-apps#60]
![available_on_pi-apps](https://user-images.githubusercontent.com/70802936/98048890-471c3e80-1e37-11eb-9c05-30df87c336e6.png)
I created this as a test (and it is by no means ready), I think it might be a good idea to add it sometime, even if not now.

**Comment by Botspot** [comment]
What would this graphic be used for?

**Comment by Botspot** [comment]
Are you thinking this would be a kind of "badge" that goes on other websites, that say it's available on Pi-Apps?

**Comment by Botspot** [comment]
Oh, something like this?  
![app-store-google-play-icons-color-icons-app-store-google-play-colors-vector-illustration-145688828](https://user-images.githubusercontent.com/54716352/98049725-e587b000-1df5-11eb-8ee4-78673aaba380.jpg)

**Comment by mobilegmYT** [comment]
For example, you could place it on SpacingBat's Discord Github repo.

**Comment by Itai-Nelken** [comment]
yes, exactly

**Comment by Botspot** [comment]
> yes, exactly

Very good idea! I'll crack open Boxy SVG and have a go at it.

**Comment by Itai-Nelken** [comment]
![available_on_pi-apps2](https://user-images.githubusercontent.com/70802936/98051017-9ebca900-1e3b-11eb-9c77-9f26121b43b4.png)

**Comment by Itai-Nelken** [comment]
![Uploading available_on_pi-apps3.png…]()
one more

**Comment by Itai-Nelken** [comment]
![available_on_pi-apps3](https://user-images.githubusercontent.com/70802936/98051304-3a4e1980-1e3c-11eb-9d14-46e729dd2d50.png)
one more

**Comment by Itai-Nelken** [comment]
![get_it_on_pi-apps4 svg](https://user-images.githubusercontent.com/70802936/98051621-ed1e7780-1e3c-11eb-8f39-6a588191aafb.png)
another one

**Comment by Itai-Nelken** [comment]
![get_it_on_pi-apps4 1 svg](https://user-images.githubusercontent.com/70802936/98051707-1ccd7f80-1e3d-11eb-9535-27bde67a9806.png)
improved

**Comment by Itai-Nelken** [comment]
![get_it_on_pi-apps5](https://user-images.githubusercontent.com/70802936/98052405-d547f300-1e3e-11eb-9f40-d32d64e3769b.png)
another one

**Comment by Itai-Nelken** [comment]
[available on pi-apps.zip](https://github.com/Botspot/pi-apps/files/5484697/available.on.pi-apps.zip)
all of them (almost) with the svg files for all of them but the first and the last (the last being created in snappa, so no svg).

**Comment by Botspot** [comment]
I think this looks good:
![badge](https://user-images.githubusercontent.com/54716352/98055464-220dd880-1e03-11eb-92ce-cbbde2688ff8.png)

**Comment by Itai-Nelken** [comment]
It looks great!

**Comment by Itai-Nelken** [comment]
@Botspot I'll add it to the github repository where I uploaded the etcher .deb files

**Comment by Botspot** [comment]
> @Botspot I'll add it to the github repository where I uploaded the etcher .deb files

I would rather host it myself in the icons directory of this repository. Also I will make a copy-n-paste embed code that anyone can add to their own README.

**Comment by Itai-Nelken** [comment]
let me know when you Finnish the embed code, I could try creating it also if you want.

**Comment by Botspot** [comment]
OK here it is:
```
[![badge](https://github.com/Botspot/pi-apps/blob/master/icons/badge.png?raw=true)](https://github.com/Botspot/pi-apps)
```

**Comment by Botspot** [comment]
It has been added to the README.

**Comment by Itai-Nelken** [comment]
great!
