### ISSUE TITLE
pkg-install doesn't delete dummy deb folder

### ISSUE THREAD

**Issue by Itai-Nelken** [Botspot/pi-apps#600]
it leaves the folder that was used to create the de, the unpacked deb.

**Comment by Itai-Nelken** [comment]
never mind, apt failed, so I think that was the cause

**Comment by Botspot** [comment]
> never mind, apt failed, so I think that was the cause

Yes.

**Comment by Botspot** [comment]
Happy 600th issue, by the way! ;)

**Comment by mobilegmYT** [comment]
> Happy 600th issue, by the way! ;)

👀
