### ISSUE TITLE
eDEX-UI isn't starting

### ISSUE THREAD

**Issue by Samaliel** [Botspot/pi-apps#603]
I run eDEX-UI and nothing happens

**Comment by Samaliel** [comment]
All the installation in my raspberry pi 4, of the Pi APps and eDEX, they have gone perfectly. I installed it on my pixel from the RetroPie.
When I run it, the hourglass comes out for a few seconds and then nothing happens.
from the terminal with
cd ~ / eDEX-UI-RPi /
sudo chmod + x eDEX-UI-Linux-armv7l_2.2.7.AppImage
./eDEX-UI-Linux-armv7l_2.2.7.AppImage
the last command gives me bus error

**Comment by Samaliel** [comment]
I also tried another image with pixel installed from retropie.
And the same thing happens to me, nothing happens when I run eDEX. I'm afraid it might be a problem to run eDEX from PIxel-retropie?

**Comment by Itai-Nelken** [comment]
what error does running `./eDEX-UI-RPi/ ./eDEX-UI-Linux-armv7l_2.2.7.AppImage` give?
try running `sudo modprobe fuse` and if it still doesn't work, reboot and try again.

**Comment by Samaliel** [comment]
Thanks for answering.
Nothing happens.
the result : bus error  :(

**Comment by Samaliel** [comment]
I am afraid that the problem so that eDEX does not run, may be that I am running it from a PI Boy?

**Comment by Itai-Nelken** [comment]
> Thanks for answering.
> Nothing happens.
> the result : bus error :(

can you send the full output please?

**Comment by Samaliel** [comment]
pi@retropie:~ $ $HOME/eDEX-UI-RPi/eDEX-UI-Linux-armv7l_2.2.7.AppImage
Bus error
pi@retropie:~ $ sudo modprobe fuse
pi@retropie:~ $ $HOME/eDEX-UI-RPi/eDEX-UI-Linux-armv7l_2.2.7.AppImage
Bus error
pi@retropie:~ $ ./eDEX-UI-RPi/eDEX-UI-Linux-armv7l_2.2.7.AppImage
Bus error

**Comment by Samaliel** [comment]
pi@retropie:~ $ ls
Desktop    Downloads    Music  pi-apps   piKiss  RetroPie        Templates
Documents  eDEX-UI-RPi  osd    Pictures  Public  RetroPie-Setup  Videos
pi@retropie:~ $ cd ~/eDEX-UI-RPi/
pi@retropie:~/eDEX-UI-RPi $ sudo chmod +x eDEX-UI-Linux-armv7l_2.2.7.AppImage
pi@retropie:~/eDEX-UI-RPi $ ./eDEX-UI-Linux-armv7l_2.2.7.AppImage
Bus error
pi@retropie:~/eDEX-UI-RPi $

**Comment by Itai-Nelken** [comment]
weird!

**Comment by Botspot** [comment]
> All the installation in my raspberry pi 4, of the Pi APps and eDEX, they have gone perfectly. I installed it on my **_pixel_** from the RetroPie.

So it works fine everywhere for you, except on your pixel? I assume "pixel" means a smartphone? Maybe you'll find your answer somewhere else because I have no idea how to help you for a non-Pi device/OS.

**Comment by techcoder20** [comment]
The raspberry pi desktop was previously known as the pixel desktop https://www.raspberrypi.org/blog/introducing-pixel/

**Comment by Botspot** [comment]
> The raspberry pi desktop was previously known as the pixel desktop https://www.raspberrypi.org/blog/introducing-pixel/

That could be what @Samaliel was referring to, but I'm not sure. @Samaliel says "I installed it on my pixel..."

**Comment by Samaliel** [comment]
Yes that's how it is.
I have one of my raspberrys pi 4 inside a PIBoy from Experimental PI. This has on the micro sd, retropie installed. From retropie you can install raspberry OS (called pixel among the community).

**Comment by Samaliel** [comment]
I have thought that perhaps the software that consists of a loadable kernel module to interact with the Piboy controls, the executable called OSD, and the Dispmanx for the on-screen display that also incorporates some of the safe shutdown codes, are responsible. not finish running eDex.
Thanks to everyone

**Comment by Botspot** [comment]
I'm afraid we have to conclude that the issue is caused by something outside Pi-Apps's control.

Most likely, there is something wrong with your system. It may [indicate](https://www.quora.com/What-does-Bus-error-mean-in-Linux-command-line) SD card corruption, or it may not.

**Comment by Samaliel** [comment]
I understand.
But I tried the installation on two sds.
I was thinking that maybe I can't run on a 3.5 "screen

**Comment by Botspot** [comment]
> But I tried the installation on two sds.

Then maybe it's an issue with the operating system you are using.

> I was thinking that maybe I can't run on a 3.5 "screen

I'd advise you not attempt to run on a 3.5" screen. Use a treadmill instead - it has handlebars. ;)

**Comment by Samaliel** [comment]
XD
Thanks!
