### ISSUE TITLE
Complete Old Scool Runescape 

### ISSUE THREAD

**Issue by Vasslepulver** [Botspot/pi-apps#611]
Hello! :) 

I trying to fix Old Scool Runesape to Pi Apps Servers. I have fix everyhing but i cant fix the unistall script.
Can someone here fix this for me so we can uppload it to the Pi Apps so more people can enjoy this game ? and i have only test this on 32 bit system and that works fine
[Old Scool Runescape.zip](https://github.com/Botspot/pi-apps/files/6371746/Old.Scool.Runescape.zip)

**Comment by Itai-Nelken** [comment]
Sorry, accidentally reopened
