### ISSUE TITLE
Yad failed to install

### ISSUE THREAD

**Issue by Havelex** [Botspot/pi-apps#616]
I tried to intall pi-apps (manually) and the first command worked fine, but  the second command '~/pi-apps/install' gave me an error message: 

_The following packages have unmet dependencies:
 libgl1-mesa-dev : Depends: libgl-dev
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
Failed to install yad._

So I uninstalled pi-apps and yad and deleted everything. I tried to install it again twice manually and automatic, but it didn't work either.
I don't know what to do, pls send help.

**Comment by Itai-Nelken** [comment]
This isn't a pi-apps issue, your apt is messed up.
Try runnig what apt told you: `sudo apt -f install`.

**Comment by CleanMachine1** [comment]
I have a feeling that pi-apps has nothing to do with it as well, however have you installed any other prior to getting this error
