### ISSUE TITLE
Atom on RPI

### ISSUE THREAD

**Issue by ghost** [Botspot/pi-apps#617]
This Might Help You: https://github.com/atom/atom/issues/7822

**Comment by Itai-Nelken** [comment]
I have tried compiling atom on the rpi multiple times with ni success...

**Comment by Decotron99** [comment]
oh ok

**Comment by oxmc** [comment]
From what i see ```Linux
Atom is only available for 64-bit Linux systems.```

**Comment by Itai-Nelken** [comment]
right, but it does build on arm. unfortunately it doesn't work.

@Botspot I think this issue can be closed. there is nothing we can do until the atom team add support for arm (hopefully they will)

**Comment by slashtechno** [comment]
@Botspot  Can this issue be reopened because of WINE with Box86?

**Comment by Itai-Nelken** [comment]
> @Botspot  Can this issue be reopened because of WINE with Box86?

@slashtechno box86 doesn't support chromium (atom is written with electron that is chromium under the hood).
