### ISSUE TITLE
New Minecraft Importer

### ISSUE THREAD

**Issue by ghost** [Botspot/pi-apps#619]
Minecraft Importer for Minecraft Bedrock Edition has been updated with a new icon and a description with a list of packages compatible with the app. Unfortunately, the addon importing feature was canceled due to the difficulty of having it properly work. Here is the new archive with all the updated files. The repository for the app itself doesn't need to come included with the app packaging.
[Minecraft Importer.tar.gz](https://github.com/Botspot/pi-apps/files/6401408/Minecraft.Importer.tar.gz)

**Comment by GabeCoder** [comment]
Sorry for adding too many app requests to your repository. I do realize how much a developer has to work for this. Hopefully, a donation can come with the exact same respect.
I will donate when I’m old enough.

**Comment by GabeCoder** [comment]
And yes, I’d be in debt.

**Comment by Botspot** [comment]
> I will donate when I’m old enough.

For your information, donations are not accepted at this time. (PayPal account got locked)

**Comment by GabeCoder** [comment]
In my opinion, Minecraft Importer saves a lot of time when importing your favorite packages with only a few clicks.

**Comment by mobilegmYT** [comment]
> In my opinion, Minecraft Importer saves a lot of time when importing your favorite packages with only a few clicks.

That is true. I suggest you:

1. Make a pi-apps installer for your app so it's more likely it'll be added
2. Make it edit MIME types, so when you double click any Minecraft world file in file manager it'll automatically run the import script.

**Comment by GabeCoder** [comment]
> > In my opinion, Minecraft Importer saves a lot of time when importing your favorite packages with only a few clicks.
> 
> That is true. I suggest you:
> 
> 1. Make a pi-apps installer for your app so it's more likely it'll be added

Does the Pi-Apps installer typically mean the actual installer for Pi-Apps or the installation script of this app that is contained in apps/Minecraft Importer?

> 2. Make it edit MIME types, so when you double click any Minecraft world file in file manager it'll automatically run the import script.

That’s actually a good idea. I’ll look up how to do that.

**Comment by mobilegmYT** [comment]
> > > In my opinion, Minecraft Importer saves a lot of time when importing your favorite packages with only a few clicks.
> > 
> > 
> > That is true. I suggest you:
> > 
> > 1. Make a pi-apps installer for your app so it's more likely it'll be added
> 
> Does the Pi-Apps installer typically mean the actual installer for Pi-Apps or the installation script of this app that is contained in apps/Minecraft Importer?
 
As in a installer which can be added to pi-apps, basically a folder with the install scripts used by pi-apps and such. You can run `~/pi-apps/createapp` to start a wizard which will help you with this.

**Comment by GabeCoder** [comment]
> > > > In my opinion, Minecraft Importer saves a lot of time when importing your favorite packages with only a few clicks.
> > > 
> > > 
> > > That is true. I suggest you:
> > > 
> > > 1. Make a pi-apps installer for your app so it's more likely it'll be added
> > 
> > 
> > Does the Pi-Apps installer typically mean the actual installer for Pi-Apps or the installation script of this app that is contained in apps/Minecraft Importer?
> 
> As in a installer which can be added to pi-apps, basically a folder with the install scripts used by pi-apps and such. You can run `~/pi-apps/createapp` to start a wizard which will help you with this.

Actually, you can simply just extract the package contents to ˜/pi-apps/apps

**Comment by mobilegmYT** [comment]
> > > > > In my opinion, Minecraft Importer saves a lot of time when importing your favorite packages with only a few clicks.
> > > > 
> > > > 
> > > > That is true. I suggest you:
> > > > 
> > > > 1. Make a pi-apps installer for your app so it's more likely it'll be added
> > > 
> > > 
> > > Does the Pi-Apps installer typically mean the actual installer for Pi-Apps or the installation script of this app that is contained in apps/Minecraft Importer?
> > 
> > 
> > As in a installer which can be added to pi-apps, basically a folder with the install scripts used by pi-apps and such. You can run `~/pi-apps/createapp` to start a wizard which will help you with this.
> 
> Actually, you can simply just extract the package contents to ˜/pi-apps/apps

Nevermind, i'm a idiot lol.

**Comment by GabeCoder** [comment]
> > > > > > In my opinion, Minecraft Importer saves a lot of time when importing your favorite packages with only a few clicks.
> > > > > 
> > > > > 
> > > > > That is true. I suggest you:
> > > > > 
> > > > > 1. Make a pi-apps installer for your app so it's more likely it'll be added
> > > > 
> > > > 
> > > > Does the Pi-Apps installer typically mean the actual installer for Pi-Apps or the installation script of this app that is contained in apps/Minecraft Importer?
> > > 
> > > 
> > > As in a installer which can be added to pi-apps, basically a folder with the install scripts used by pi-apps and such. You can run `~/pi-apps/createapp` to start a wizard which will help you with this.
> > 
> > 
> > Actually, you can simply just extract the package contents to ˜/pi-apps/apps
> 
> Nevermind, i'm a idiot lol.

lmao no ur not

**Comment by donnerkebab1730** [comment]
> For your information, donations are not accepted at this time. (PayPal account got locked)

oof is it still locked?

**Comment by GabeCoder** [comment]
What do you think of the importer? I’ve been using it and it became so much easier to import my backups to Minecraft.

**Comment by GabeCoder** [comment]
So far, nobody else has commented on this app. @Botspot, do you think this useful tool can be added to Pi-Apps?

**Comment by theofficialgman** [comment]
closing as the github user GabeCoder has been deleted along with all their repos (which this dependend on)
