### ISSUE TITLE
New Gamer's Soundboard

### ISSUE THREAD

**Issue by GabeCoder** [Botspot/pi-apps#620]
Minor updates were applied to Gamer's Soundboard with a new comment and description.
[Gamer's Soundboard.tar.gz](https://github.com/Botspot/pi-apps/files/6437583/Gamer.s.Soundboard.tar.gz)

**Comment by Botspot** [comment]
Closing duplicate issue.
See: https://github.com/Botspot/pi-apps/issues/540#issuecomment-834603736
