### ISSUE TITLE
Deltarune

### ISSUE THREAD

**Issue by gl91306** [Botspot/pi-apps#621]
Can this app run on RPi? If so, please provide a link to a tutorial if applicable.

yes. https://github.com/Kneesnap/deltarune-circuit-sword/ is the og link exept you replace the runner with a pi-4 one

Is this app something many GUI users would find useful?

yes

Is this app installable with `sudo apt install`?

no lol

If you've created a zip file for this app, upload it here.

[Deltarune.zip](https://github.com/Botspot/pi-apps/files/6409086/Deltarune.zip)

**Comment by oxmc** [comment]
@gl91306 we fixed the install correct?

**Comment by gl91306** [comment]
yea but they havent added this in like a year so i close it
