### ISSUE TITLE
Host all .debs and downloaded files at a trusted place

### ISSUE THREAD

**Issue by CleanMachine1** [Botspot/pi-apps#624]
All debs and executed scripts should be hosted somewhere specific such as a Botspot repo or chunky milk.

Any other download needs/should be moved!

This is because, what if the script name is kept the same so it doesn't break pi-apps install however the attacker decides to make the script run malicious code or commands such as (DONT RUN) sudo rm / (NOT CORRECT COMMAND)

Just a suggestion

**Comment by Botspot** [comment]
Better question is: Why would you trust me? Even if you did trust Botspot, an attacker could easily sneak an infected deb onto "The official pi-apps deb server" without me noticing.

Raspberry Pi9 Forum users had a good talk about this. See: https://www.raspberrypi.org/forums/viewtopic.php?f=63&t=268455&p=1750604&hilit=trust+pi+apps#p1750595 and continue reading down.

**Comment by CleanMachine1** [comment]
Personally I actually don't use pi-apps, like at all. I have never actually downloaded anything... I just like to help

If I need software, I am not a total noob, I source it myself 

However I am sure anyone willing to run pi-apps is willing to trust the software from a botspot repo

Whats stopping you from running malware in the original install script? Nothing!

People clearly have trust in you, but I am sure not all would want software coming from another users repo

PS: sorry for all the security topics I create, its just security is what I like!

**Comment by CleanMachine1** [comment]
Me not running any software from Pi-Apps isn't because I trust you, I just like to build from source

**Comment by CleanMachine1** [comment]
Also about the bit where you mention an attack acting as you, thats where GPG signing becomes useful and its probably something you should have done a while back creating an app store 

Look at my personal readme and find a link to a tutorial 


GPG signed commits are only from computers you have setup, an attacker needs access to your github to then add a GPG key to your account (this will send emails and every other notification)

If you look at some of my repos and view the commits, you will see that they are all signed, so you know its me

**Comment by chunky-milk** [comment]
> Better question is: Why would you trust me? Even if you did trust Botspot, an attacker could easily sneak an infected deb onto "The official pi-apps deb server" without me noticing.
> 
> 
> 
> Raspberry Pi Forum users had a good talk about Pi-Apps security. See: https://www.raspberrypi.org/forums/viewtopic.php?f=63&t=268455&p=1750604&hilit=trust+pi+apps#p1750595 and read down from there.

I've got an APT repository [here](https://github.com/chunky-milk/raspbian-addons), which I maintain and commit to very frequently. It contains all the apps from Pi Apps and even some more. 

Also, the debs are automatically checksummed when uploaded to the repo, which can come in handy when trying to verify the integrity of a deb.

I think this would be a very good place to store debs for Pi Apps to download.

**Comment by Botspot** [comment]
> I think this would be a very good place to store debs for Pi Apps to download.

I think you're missing the point. By design, an app store that uses bash scripts to download third-party debs and install them is inherently insecure.
There's a limit to how much security can be bolted onto an insecure system.

And besides, even if there was a "Botspot official secure repository", what would stop me, or another bad actor from distributing a compromised deb through it?
As I see it, the whole concept of security is an illusion: it involves trusting somebody. You have to trust me, the app's developer, the one who created the source code, the one who compiled the deb, the website that hosts the deb, etc.

**Comment by CleanMachine1** [comment]
Im sure botspot knows 😆

**Comment by CleanMachine1** [comment]
Well a lot of people trust you and if they didn't they wouldn't even have pi apps installed 

I call for a GPG signing of all debs from at least @Botspot @chunky-milk for all debs or deb updates since it is the only way to show that the account hasn't been hacked or similar

**Comment by CleanMachine1** [comment]
^ gpg signging the commits where the deb is uploaded

**Comment by CleanMachine1** [comment]
> > I think this would be a very good place to store debs for Pi Apps to download.
> 
> 
> 
> I think you're missing the point. By design, an app store that uses bash scripts to download third-party debs and install them is inherently insecure.
> 
> There's a limit to how much security can be bolted onto an insecure system.
> 
> 
> 
> And besides, even if there was a "Botspot official secure repository", what would stop me, or another bad actor from distributing a compromised deb through it?
> 
> As I see it, the whole concept of security is an illusion: it involves trusting somebody. You have to trust me, the app's developer, the one who created the source code, the one who compiled the deb, the website that hosts the deb, etc.



What... file integrity and gpg siggning products completely goes against your last statement


If you visit linux mint for example you will find integrity of files and gpg signing to prove that the checksum.txt isn't edited

**Comment by Itai-Nelken** [comment]
sigining commits is pretty easy:

create a gpg key:
```bash
sudo apt install gnupg
gpg --full-gen-key
```
select option `1`
enter: `4096`
enter: `0`
enter: `y`
enter your name
enter your email address
press ENTER
enter: `o`

then export it: `gpg --export-secret-keys "${EMAIL}" > my-private-key.asc` (change `${EMAIL}` with the email you used to create the key) and back it up.

add the gpg key to your github account:
run `gpg --list-secret-keys --keyid-format LONG` and copy the numbers and letters in the 2nd line under `sec`, for example:
```
/home/pi/.gnupg/pubring.kbx
---------------------------
sec   rsa4096/E65F4R2C487B0EFV 2021-04-06 [SC]
      **TT420F4C7GTTFF76E0DD33F376DE45E4E2C367B8AE6**
uid                 [ unknown] your name <email@example.com>
ssb   rsa4096/CGG84205BD43F05D 2021-04-06 [E]
```
the line between the **'s

then run `gpg --armor --export <key-id>` but change `<key-id> with the line you copied in the last step.

copy the output, and follow [github's official tutorial](https://docs.github.com/en/github/authenticating-to-github/adding-a-new-gpg-key-to-your-github-account).

**Comment by CleanMachine1** [comment]
Personally I would follow the full official guide, it explains more

**Comment by Botspot** [comment]
> All debs and executed scripts should be hosted somewhere specific such as a Botspot repo or chunky milk.
> 
> Any other download needs/should be moved!

This proposal, while logical, is not practical.

Few authors would want their debs and scripts being stored somewhere that they don't control. What if I was an app developer, found a bug in my deb, fixed it, and wanted to re-upload it? Now I'd have to ask _somebody else_ to re-upload _my_ deb, in order for my users to receive the changes. I, as a developer would be frustrated by the **red tape**.

I (Botspot) would probably end up being the "gatekeeper" to the secure repository. As a result, I'd have less time to work on other, more practical, things. For example I'd have less time to deal with bug reports, create new apps, or improve the user experience.

To conclude: This idea makes sense. It has good intentions. But for (mostly) one unpaid developer who does this in his free-time, it's too burdensome an idea.

**Comment by CleanMachine1** [comment]
You already approve PR requests for apps being updated,  is their much of a difference

**Comment by Botspot** [comment]
> You already approve PR requests for apps being updated, is their much of a difference

It's one thing to approve a url change within github.com.
It's quite another to assume responsibility maintaining all debs. For every deb in the safe repository, I'd have to download it from one place, then upload it. I would be a significant bottleneck.
That's a lot more hoops to jump through, and at the current size of Pi-Apps development team, I just don't see how it would be practical.

**Comment by CleanMachine1** [comment]
Ok, well I haven't got any examples however I have one last thing about this topic, some applications from shady websites and places should be declined, considering that so many people use Pi-Apps.

Safety should ALWAYS be the priority with something like pi-apps, people trust this program like they would with the apt repo
