### ISSUE TITLE
Opera

### ISSUE THREAD

**Issue by leha-code** [Botspot/pi-apps#628]
Can this app run on RPi? If so, please provide a link to a tutorial if applicable.]
I don't know

Is this app something many GUI users would find useful?
Yeah
Is this app installable with `sudo apt install`?
No

**Comment by mobilegmYT** [comment]
> Can this app run on RPi? If so, please provide a link to a tutorial if applicable.]
> I don't know
> 
> Is this app something many GUI users would find useful?
> Yeah
> Is this app installable with `sudo apt install`?
> No

1. Opera is not open source so it can't be compiled
2. This means there's no way to get it to work unless box64 comes out, and even running on box64 it'll be somewhat slow.

**Comment by Botspot** [comment]
> Can this app run on RPi? If so, please provide a link to a tutorial if applicable.]
> I don't know

Could you do us developers a favor and find out if it's possible to install first, before opening an issue?
Google: "Install opera browser on raspberry pi"

**Comment by CleanMachine1** [comment]
Considering what opera have done in recent years, I wouldn't want this program added regardless of if it was possible

**Comment by Itai-Nelken** [comment]
Whay did they do @CleanMachine1?

**Comment by CleanMachine1** [comment]
https://www.androidpolice.com/2020/01/21/opera-predatory-loans/

There is more, let me find some

**Comment by CleanMachine1** [comment]
Also its Chinese company, and while I don't have anything against the Chinese people, I do like my privacy, and would prefer my data private and secure with something like chromium and even better firefox

**Comment by CleanMachine1** [comment]
Overall, questionable security and scamming people in poor countries in need of loans

**Comment by leha-code** [comment]
Vote for opera! Chromium sends stats to google. ((((.

**Comment by leha-code** [comment]
Also it is a company from Norway

sent from not an computer

**Comment by CleanMachine1** [comment]
Use firefox for an opensource non google experience

**Comment by Botspot** [comment]
> Vote for opera! Chromium sends stats to google. ((((.

Well it doesn't matter. Opera doesn't run on Raspberry Pi, so it doesn't matter how badly we want it.
