### ISSUE TITLE
Doki Doki Literature Club (app request)

### ISSUE THREAD

**Issue by Aradionov366** [Botspot/pi-apps#631]
so i created zip for this game, Botspot, pls check it out
[Doki Doki Literature Club.zip](https://github.com/Botspot/pi-apps/files/6419134/Doki.Doki.Literature.Club.zip)

**Comment by mobilegmYT** [comment]
> so i created zip for this game, Botspot, pls check it out
> [Doki Doki Literature Club.zip](https://github.com/Botspot/pi-apps/files/6419134/Doki.Doki.Literature.Club.zip)

It looks here you have 3 install scripts. Does this app need seprate install code for 32 and 64-bit apps or does it only need 1 script?

**Comment by Aradionov366** [comment]
[Doki Doki Literature Club.zip](https://github.com/Botspot/pi-apps/files/6425589/Doki.Doki.Literature.Club.zip)
do some bugfixes and delete extra install scripts

**Comment by oxmc** [comment]
This:
```
wget https://www.renpy.org/dl/7.4.4/renpy-7.4.4-sdk.tar.bz2 || error "Failed to clone renpy files"
tar -xf renpy-7.4.4-sdk.tar.bz2
rm -rf renpy-7.4.4-sdk.tar.bz2
cd renpy-7.4.4-sdk
cd lib
wget https://www.renpy.org/dl/7.4.4/renpy-7.4.4-raspi.tar.bz2 || error "Failed to clone rpi renpy support files"
tar -xf renpy-7.4.4-raspi.tar.bz2
rm -rf renpy-7.4.4-raspi.tar.bz2
```
Is not needed, you can install renpy from 'pkg-install' Example: `"${DIRECTORY}/pkg-install" "renpy" "$(dirname "$0")" || error "Unable to install renpy, this is needed to run the launcher!"`

**Comment by oxmc** [comment]
Here is a small install script:
```
#!/bin/bash

#Variables
DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

#Functions
function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

#Main
#CD into users home directory, usually /home/pi
cd $HOME

#Install dependencies required to run DDLC
"${DIRECTORY}/pkg-install" "renpy" "$(dirname "$0")" || exit 1

#Make the main directory
if [ -d "~/DDLC" ]; then
  #DDLC folder exists, delete it and re-download it
  echo "The DDLC folder already exists, I will re-download it for you..."
  sudo rm -rf ~/DDLC
  mkdir DDLC
  #Cd into DDLC folder
  cd ~/DDLC
  #Download game
  wget https://archive.org/download/ddlcgame.tar/ddlcgame.tar.bz2 
  tar -xf ddlcgame.tar.bz2 
  rm -rf ddlcgame.tar.bz2
  #Download launcher
  wget https://raw.githubusercontent.com/Aradionov366/DDLC/main/launch.sh || error 'Failed to clone launcher!'
  #Make menu button shortcut
  echo "[Desktop Entry]
Name=Doki Doki Literature Club
GenericName=DDLC
Comment=Doki Doki Literature Club is a visual novel with horror elements
Exec=bash -c '~/DDLC/launch.sh'
Icon=$(dirname $0)/icon-64.png
Terminal=false
Type=Application
Categories=Game;Application;
Keywords=Game;
StartupNotify=true" > ~/usr/share/applications/DDLC.desktop
else
  #DDLC folder does not exist, download it
  echo "The DDLC folder does not exist, I will download it for you..."
  mkdir DDLC
  #Cd into DDLC folder
  cd ~/DDLC
  #Download game
  wget https://archive.org/download/ddlcgame.tar/ddlcgame.tar.bz2 
  tar -xf ddlcgame.tar.bz2 
  rm -rf ddlcgame.tar.bz2
  #Download launcher
  wget https://raw.githubusercontent.com/Aradionov366/DDLC/main/launch.sh || error 'Failed to clone launcher!'
  #Make menu button shortcut
  echo "[Desktop Entry]
Name=Doki Doki Literature Club
GenericName=DDLC
Comment=Doki Doki Literature Club is a visual novel with horror elements
Exec=bash -c '~/DDLC/launch.sh'
Icon=$(dirname $0)/icon-64.png
Terminal=false
Type=Application
Categories=Game;Application;
Keywords=Game;
StartupNotify=true" > ~/usr/share/applications/DDLC.desktop
fi
#If no errors accured, exit the script with exitcode 0
exit 0
```

**Comment by mobilegmYT** [comment]
@Aradionov366 ^

**Comment by coolcatsuperhero** [comment]
This is my favorite game!!!!!!

**Comment by mobilegmYT** [comment]
*bump
Changes oxmc made:
*[Doki.Doki.Literature.Club.zip](https://github.com/Botspot/pi-apps/files/6594596/Doki.Doki.Literature.Club.zip)

**Comment by mobilegmYT** [comment]
@Botspot @Itai-Nelken Improved version. I added some trigger warnings in description. 
[Doki Doki Literature Club.zip](https://github.com/Botspot/pi-apps/files/6744642/Doki.Doki.Literature.Club.zip)

**Comment by Itai-Nelken** [comment]
no need to install `git`, if pi-apps is installed, git is also installed.
uninstall script line 11 character 33: extra " (is this tested? because if yes you would get a syntax error when uninstalling.

other than that, looks good.

**Comment by mobilegmYT** [comment]
> no need to install `git`, if pi-apps is installed, git is also installed.
> uninstall script line 11 character 33: extra " (is this tested? because if yes you would get a syntax error when uninstalling.
> 
> other than that, looks good.

Now fully tested: https://transfer.sh/OtM/Doki.zip
Also check out #877 while your at it?
![unknown](https://user-images.githubusercontent.com/44128563/129599921-f12e7095-f923-412b-8bb7-acf9e40574ea.png)

**Comment by Itai-Nelken** [comment]
[Doki.zip](https://github.com/Botspot/pi-apps/files/6994171/Doki.zip) (same file that @mobilegmYT just uploaded)
@Botspot I guess its ready to be added

**Comment by Botspot** [comment]
As the prime maintainer of the app store, it is my responsiblity to make sure that the store's content is suitable for all ages. It's common knowledge: Raspberry Pi computers are marketed for **young children** and the behavior of our users seems to conform that notion. (with Minecraft being the #1 most popular app)
After reading the unsettling description, I decided to wait on this app until I had a chance to research it thoroughly. I have now had a chance to research it, and agree with the description it would be inappropriate for some ages. Furthermore, I believe that adding it *at all* would be irresponsible to the parents who entrust their kids with a Pi.
Perhaps one day, when Pi-Apps requires account logins, knows everyone's ages, and supports parental controls, we can add this app. (just kidding, that's never going to happen)
It's my duty, it's *our* duty to keep the apps clean and family-friendly.
Will this decision hinder Pi-Apps's growth? Probably. Will some people be disappointed in this decision and call me a tyrant? Perhaps. Nevertheless, I see this as the right thing to do.

**Comment by Botspot** [comment]
NOW, just because this app isn't headed to the *official* Pi-Apps repository, *doesn't* mean that a third-party can't create their own repository, with this app in it, and an easy way to add it to Pi-Apps. That would not bother me one bit.
In fact, the more I think about this, the more I like the idea. Since day one, Pi-Apps allowed local apps to remain in the app-folder, untouched by updates. Maybe this is the next step in Pi-Apps's evolution: for unofficial, additional collections of apps to be created and curated by other github users, each with a single-line command to drop in the new apps.

Now... who will be the first to make such a proposed third-party pi-apps repository? :)

**Comment by mobilegmYT** [comment]
~~Time to cut out the NSFW parts and make everything just dialog with thicc anime girls~~
