### ISSUE TITLE
app creator creating 2 install scripts

### ISSUE THREAD

**Issue by Itai-Nelken** [Botspot/pi-apps#633]
The app creator has been creating 3 install scripts, install-<32|64> and install, I though it maybe was a bug I was playing around with the app creator script, but after updating it it still happens, and its seems that the same thing happened to @Aradionov366 in #631

**Comment by Botspot** [comment]
I've been meaning to track this down. It's hard though because I haven't been able to pin down exactly what circumstances cause it.
