### ISSUE TITLE
LibreCAD

### ISSUE THREAD

**Issue by Jai-JAP** [Botspot/pi-apps#639]
LibreCAD is a free Open Source CAD application for Windows, Apple and Linux. Support and documentation are free from our large, dedicated community of users, contributors and developers.

Here is the zip file for the installer I created for installing LibreCAD on RPi.
[LibreCAD.zip](https://github.com/Botspot/pi-apps/files/6432614/LibreCAD.zip)

**Comment by Jai-JAP** [comment]
[LibreCAD website](https://librecad.org)
[LibreCAD wiki](https://wiki.librecad.org)

**Comment by Botspot** [comment]
Pi-Apps specializes in hard-to-install software.
Librecad is not hard to install on Raspberry Pi, it's easy.
```
sudo apt install librecad
```
