### ISSUE TITLE
Buttons look wrong on Twister OS

### ISSUE THREAD

**Issue by mobilegmYT** [Botspot/pi-apps#640]
I'm using the win10 dark mode theme on Twister OS. Only the Install and Uninstall button's text has this squishing sort of problem, all other buttons don't.

![image](https://user-images.githubusercontent.com/44128563/117319450-8c521500-ae48-11eb-963d-52a24e9d140c.png)

![image](https://user-images.githubusercontent.com/44128563/117319527-9c69f480-ae48-11eb-8acd-64c3d0e11326.png)

![image](https://user-images.githubusercontent.com/44128563/117319546-a25fd580-ae48-11eb-9f5e-5e4b48a3b6eb.png)

**Comment by Botspot** [comment]
None of those button images look right. @mobilegmYT Did you shrink your screenshots before posting them?

**Comment by mobilegmYT** [comment]
> None of those button images look right. @mobilegmYT Did you shrink your screenshots before posting them?

None of them??? I didn't shrink, these are screenshots I captured natively.

**Comment by mobilegmYT** [comment]
(Should clarify they were captured with a AnyDesk remote connection, since this is posted from my windows pc but on my pi's monitor they look the same)

**Comment by Botspot** [comment]
> None of them??? I didn't shrink, these are screenshots I captured natively.

Then something on your end is shrinking them and making them look bad.
Check your DPI settings and ensure AnyDesk isn't scaling your screen.

**Comment by mobilegmYT** [comment]
> > None of them??? I didn't shrink, these are screenshots I captured natively.
> 
> Then something on your end is shrinking them and making them look bad.
> Check your DPI settings and ensure AnyDesk isn't scaling your screen.

They do also look that way on my monitor connected to the pi.

**Comment by Botspot** [comment]
> They do also look that way on my monitor connected to the pi.

The icons should not look like that. Something is wrong with your system. Perhaps your GTK theme is shrinking the icons?

**Comment by mobilegmYT** [comment]
> > They do also look that way on my monitor connected to the pi.
> 
> The icons should not look like that. Something is wrong with your system. Perhaps your GTK theme is shrinking the icons?

I mean maybe?? IDK

**Comment by Botspot** [comment]
> I mean maybe?? IDK

Have they always looked like this on your system?

**Comment by mobilegmYT** [comment]
> > I mean maybe?? IDK
> 
> Have they always looked like this on your system?

Yes.

**Comment by mobilegmYT** [comment]
But all the other icons don't have the text issue.

**Comment by Botspot** [comment]
> But all the other icons don't have the text issue.

That's because these buttons have text that's *built-in* to the images.
@mobilegmYT You should find out why your icons are being shrunk. Once that's fixed, everything will be fine.
Maybe switching Twister themes would make a difference?

**Comment by Jai-JAP** [comment]
I too have the same issue even on fresh install of Twister OS and also on Twister OS Lite

**Comment by leha-code** [comment]
I had the same on twister, until it got kernel panic from skifree

**Comment by Itai-Nelken** [comment]
I also have this problem on TwisterOS, but tbh I don't care that much (especially as I use my pi-apps terminal script most of the time, and I don't use pi-apps much after the initial setup of my OS).

**Comment by Botspot** [comment]
This issue is being closed because there is nothing I can do from the Pi-Apps end. As this problem is _caused_ by your GTK theme, it is only _fixable_ by your GTK theme.

Anyone interested enough to fix this can pester Grayduck into locating the issue within the GTK theme and solving it.

**Comment by mobilegmYT** [comment]
I think I've found the issue botspot. It looks like this error happens on
all dark themes because there's some white stuff you forgot you delete
surrounding the icon text? If you bring it into pixlr you can see it since
it has a dark background.

**Comment by Botspot** [comment]
> I think I've found the issue botspot. It looks like this error happens on all dark themes because there's some white stuff you forgot you delete surrounding the icon text? If you bring it into pixlr you can see it since it has a dark background.

No, the problem  is that your GTK theme is shrinking the button icons. This shrinking action does not occur on my GTK theme, but it does occur on yours. As a result of the image scaling, the button icons look blurry on your system, but crisp on mine.

The only way to solve this issue is to prevent the GTK theme from scaling button icons.
