### ISSUE TITLE
Theme Saver

### ISSUE THREAD

**Issue by techcoder20** [Botspot/pi-apps#644]
Can this app run on RPi? If so, please provide a link to a tutorial if applicable.
Yes This App Can Run on the RPi Link: https://github.com/techcoder20/themesaver

Is this app something many GUI users would find useful?
Yes

Is this app installable with `sudo apt install`?
No

If you've created a zip file for this app, upload it here.
[Theme Saver.zip](https://github.com/Botspot/pi-apps/files/6439764/Theme.Saver.zip)

**Comment by techcoder20** [comment]
It does need to care for desktop environment as this app only works on lxde and xfce. I did use the pkg-install before running my script so that it installs the dependencies. All the other changes have been made. Run the install script once again to fix that error :)

**Comment by Botspot** [comment]
> It does need to care for desktop environment as this app only works on lxde and xfce.

But why? Is this a built-in limitation to Python? In any case, this app ought to run on non-`lxde-pi` desktop environments.

**Comment by techcoder20** [comment]
No its a builtin limitation of my script. I wanted to make the app apply the theme changes without reboot due to which I have to tailor it for every desktop environment. I am currently done with lxde and xfce. More will be coming :)

**Comment by Itai-Nelken** [comment]
looks good to me, I think it can be added. I'll test it one last time and then I'll add it.

**Comment by Botspot** [comment]
> looks good to me, I think it can be added. I'll test it one last time and then I'll add it.

I haven't had time to look at this recently, but what would happen if someone tried to install this app on a non-sup[ported desktop system? Would the script detect this and fail?

**Comment by Itai-Nelken** [comment]
Yes

**Comment by Itai-Nelken** [comment]
```Installing dummy deb...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 pi-apps-2bab2d84 : Depends: python-pyqt5 but it is not installable
E: Unable to correct problems, you have held broken packages.

Apt finished.
Failed to install the packages!
APT reported these errors:
E: Unable to correct problems, you have held broken packages.

Failed to install Theme Saver with install script!
```
@techcoder20 the package name in debian is `python3-pyqt5`. also your [install script](https://github.com/techcoder20/ThemeSaver/blob/main/install.sh) installs dependencies using `apt`. maybe change it to check if the package is installed before installing it? that way pi-apps can handle installing and uninstalling the dependencies with `pkg-install` and `-purge-installed`.

**Comment by techcoder20** [comment]
Sorry for the late reply. I had to change the zip as I had changed the install script to a python script. 
[Theme Saver.zip](https://github.com/Botspot/pi-apps/files/6886281/Theme.Saver.zip)

> @techcoder20 the package name in debian is `python3-pyqt5`

Fixed :)


> also your [install script](https://github.com/techcoder20/ThemeSaver/blob/main/install.sh) installs dependencies using `apt`. maybe change it to check if the package is installed before installing it? that way pi-apps can handle installing and uninstalling the dependencies with `pkg-install` and `purge-installed`.

That just seems like unnecessary work. Its apt's job to check if the dependencies are installed and how to manage them but if you feel its really necessary I will add them :)

**Comment by Itai-Nelken** [comment]
looks good to me. are the scripts tested?

**Comment by techcoder20** [comment]
Yes :)

**Comment by Itai-Nelken** [comment]
A few problems: I'm on xfce but don't have `wmctrl` install so theme saver's install script fails to detect my desktop environment -> it fails but with a return value of 0 -> pi-apps thinks it installed succesfully.
so I suggest you make the install script exit with a non-zero return value if it failed.

**Comment by Itai-Nelken** [comment]
@techcoder20

**Comment by techcoder20** [comment]
Hmm I added the `wmctrl` stuff because when only using a window manager you dont have the `$DESKTOP_SESSION` variable. Xfce should have that variable. I will take a look :)

**Comment by Itai-Nelken** [comment]
any updates @techcoder20?

**Comment by techcoder20** [comment]
No sry I forgot about this. I will try to fix it by tommorow :)

**Comment by Itai-Nelken** [comment]
@techcoder20

**Comment by techcoder20** [comment]
Sorry it took a little while to make it work with mutter
[Theme Saver.zip](https://github.com/Botspot/pi-apps/files/7938640/Theme.Saver.zip)

**Comment by Crilum** [comment]
@techcoder20 um, any reason you don't install `wmctrl` with install packages?

**Comment by techcoder20** [comment]
No, just forgot about it. Updated the zip

**Comment by Crilum** [comment]
> Sorry it took a little while to make it work with mutter [Theme Saver.zip](https://github.com/Botspot/pi-apps/files/7940114/Theme.Saver.zip)

That comment?

**Comment by techcoder20** [comment]
Yes

**Comment by Crilum** [comment]
@techcoder20 The app works, but in the install script, apt is still being called multiple times.. maybe create a no-apt version of your python install script for Pi-Apps?

**Comment by techcoder20** [comment]
I can but I dont see the need. Pi Apps already installs all the dependencies so I dont see how it can break anyting. Is there any specific reason ?

**Comment by Crilum** [comment]
Just becuase it takes, lik, an extra ten seconds... I'll try to make a no-apt version for you, if you want.

**Comment by Crilum** [comment]
Here is a version that doesn't use apt. 
I just removed all the package installing lines - apt and pacman.

[install.py.txt](https://github.com/Botspot/pi-apps/files/7962627/install.py.txt)

Just rename the file to `install.py`, I just changed the name so Github would accept it...

**Comment by techcoder20** [comment]
Well I know it saves time but I am not sure if its worth it.  Also if I add a seperate file it will be kind of annoying to maintain both of them. If this is really necessary I  could add a flag such as `--no-depends` that could be used when using the pi-apps script.

**Comment by Itai-Nelken** [comment]
> [...] If this is really necessary I  could add a flag such as `--no-depends` that could be used when using the pi-apps script.

That would be great!

**Comment by techcoder20** [comment]
Ok I have finished adding the `-nd` flag and I have also updated the pi apps install script. Here is the updated zip
[Theme Saver.tar.gz](https://github.com/Botspot/pi-apps/files/7965193/Theme.Saver.tar.gz)

**Comment by Crilum** [comment]
>Ok I have finished adding the -nd flag and I have also updated the pi apps install script. Here is the updated zip
Theme Saver.tar.gz

zip or tar?

**Comment by theofficialgman** [comment]
closing as really too complicated and prone to breakage for us to support. also lacks support for piOS wayfire. also installation method not supported on recent debian/ubuntu versions
