### ISSUE TITLE
Chiaki

### ISSUE THREAD

**Issue by Markieautarkie** [Botspot/pi-apps#645]
**What is Chiaki?**
Chiaki is a free and open source software client which enables PlayStation 4/5 remote play on various platforms.
This fork allows users to stream and play directly from a Raspberry Pi!
_Demo:_ https://www.youtube.com/watch?v=9TIIiuy_Hxk

**Can this app run on RPi? If so, please provide a link to a tutorial if applicable.**
Yes, the Raspberry Pi fork of the project (including tutorial) can be found here: https://github.com/Fredrum/chiaki/wiki/Chiaki-for-the-Raspberry-Pi

**Is this app something many GUI users would find useful?**
Yes! The application is completely GUI based and makes streaming your favorite PlayStation titles as easy as... Pi.

**Is this app installable with `sudo apt install`?**
No, the application consists out of many dependencies, the project is cloned and needs to be build with CMake.

**If you've created a zip file for this app, upload it here.**
[Chiaki.zip](https://github.com/Botspot/pi-apps/files/6441838/Chiaki.zip)

**Comment by Botspot** [comment]
First off, excellent job creating your app! The script syntax is very clean, and it installed successfully for me on the first try.

Question: Why did you choose to use the https://github.com/Fredrum/chiaki repository? That looks like a fork. Is the fork repo better than the [original author's repo](https://git.sr.ht/~thestr4ng3r/chiaki)?

**Comment by Markieautarkie** [comment]
> First off, excellent job creating your app! The script syntax is very clean, and it installed successfully for me on the first try.
> 
> Question: Why did you choose to use the https://github.com/Fredrum/chiaki repository? That looks like a fork. Is the fork repo better than the [original author's repo](https://git.sr.ht/~thestr4ng3r/chiaki)?

Thank you! And yes, although the original repo supports many platforms, Raspberry Pi isn't one of them. The fork simply adds a decoder for the Raspberry Pi.

**Comment by Botspot** [comment]
> Thank you! And yes, although the original repo supports many platforms, Raspberry Pi isn't one of them. The fork simply adds a decoder for the Raspberry Pi.

That makes sense.
Chiaki has been added with commit 957920a5d6a314f0f9830f1bdf5d28db07e4eddf.
