### ISSUE TITLE
VSDC Free Video Editor

### ISSUE THREAD

**Issue by Botspot** [Botspot/pi-apps#646]
In theory, this can run with wine.

Links for future reference:
- Tutorial that seems to work with recent VSDC version. Includes registry and DLL fixes.
  - https://pclosmag.com/html/Issues/201610/page07.html
- VSDC download site - mentions that version 6.4.2 is the last version to run on Windows XP.
  - http://www.videosoftdev.com/free-video-editor/download
- WineHQ test results
  - https://appdb.winehq.org/objectManager.php?sClass=application&iId=18595

**Comment by mobilegmYT** [comment]
You know, it would probably be better to add Windows Movie Maker instead of this thing which I've never heard of. I'll go make a issue for it I guess.

**Comment by Botspot** [comment]
> You know, it would probably be better to add Windows Movie Maker instead of this thing which I've never heard of. I'll go make a issue for it I guess.

I've had extensive experience with VSDC and like it.
Movie Maker doesn't seem possible according to WineHQ.

**Comment by mobilegmYT** [comment]
> Movie Maker doesn't seem possible according to WineHQ.

I read the WineDB page wrong, I thought it said Gold since it was yellow and not brown 🤦‍♂️

**Comment by Botspot** [comment]
Various useful commands for my future reference:
```
export WINEPREFIX=~/.config/vsdc-wine
setarch linux32 -L box86 wine wineboot
setarch linux32 -L wine wineboot
wget http://downloads.videosoftdev.com/video_tools/video_editor_x32_xp.exe && wine ~/video_editor_x32_xp.exe
wine 'C:\Program Files\FlashIntegro\VideoEditor\VideoEditor.exe'
rm -rf $WINEPREFIX
```

**Comment by Botspot** [comment]
Closing as I never got this to run reliably. It always crashes.
