### ISSUE TITLE
update-exclusion failing

### ISSUE THREAD

**Issue by mobilegmYT** [Botspot/pi-apps#649]
I'm on Twister OS.

update-exclusion has this:
```
apps/Wine (x86)/
apps/Steam
```

I recently noticed that Wine got an update even when it's not supposed to. I tested this with manually triggering a reinstall with the update system, and it still reinstalled wine even though it's not supposed to.

**Comment by Botspot** [comment]
> I'm on Twister OS.
> 
> update-exclusion has this:
> 
> ```
> apps/Wine (x86)/
> apps/Steam
> ```
> 
> I recently noticed that Wine got an update even when it's not supposed to.

That's not good. Thank you very much for letting me know. (last thing we need is another round of *that*.)
What happens if update-exclusion is changed to this?
```
apps/Wine (x86)
apps/Steam
```

**Comment by Itai-Nelken** [comment]
maybe 
```
apps/Wine\ (x86)
apps/Steam
```
@mobilegmYT

**Comment by mobilegmYT** [comment]
> maybe
> 
> ```
> apps/Wine\ (x86)
> apps/Steam
> ```
> 
> @mobilegmYT

Ayy it worked now!

**Comment by mobilegmYT** [comment]
> > > maybe
> > > ```
> > > apps/Wine\ (x86)
> > > apps/Steam
> > > ```
> > > 
> > > 
> > >   
> > >     
> > >     
> > >   
> > > 
> > > 
> > > @mobilegmYT
> > 
> > 
> > Ayy it worked now! @Botspot Just change whatever pi-apps does to add Wine to the list, to the stuff above ^
> 
> Hmm. It shouldn't need that slash. It means something isn't being quoted properly.

Pretty sure even if bash does quote it, it still needs more quotes for it to work. Hence why I have to do `~/pi-apps/manage install Wine\ (x86)` and not `~/pi-apps/manage install Wine (x86)`

**Comment by Itai-Nelken** [comment]
@mobilegmYT commits https://github.com/Botspot/pi-apps/compare/765275e38170...cdfe0ebd8f1d should fix it, Update and try again.

**Comment by Botspot** [comment]
@mobilegmYT update-exclusion only applies to individual files, not apps.
The new way Wine is prevented from being installed on TwisterOS is by [marking it as `disabled`](https://github.com/Botspot/pi-apps/blob/ad71a5e9b0f5e49fe4433e86811fb75c03df916d/gui#L34-L42).
