### ISSUE TITLE
Cannot Update from MATE Desktop Env

### ISSUE THREAD

**Issue by Alextrapixel** [Botspot/pi-apps#65]
Similar with my last issue maybe ( #51 )
Happened when first time on boot or on opening Pi-Apps (when updater is triggered).

 - OS : Raspberry Pi OS 32bit (latest)
 - DE : Mate Desktop Env
 - Terminal : Mate Terminal
Here is the screenshot
![Screenshot at 2020-11-05 10-35-57](https://user-images.githubusercontent.com/59244353/98195106-86d84880-1f53-11eb-863a-509491411f4b.png)

**Comment by Botspot** [comment]
I thought I fixed this a week ago...

Try manually copying the new updater script:
```
cp -f /home/pi/pi-apps/update/pi-apps/updater /home/pi/pi-apps/updater
```

**Comment by Botspot** [comment]
Yes, this problem was very similar to #51 , basically identical actually.

I had fixed the `install` script so mate terminal would work, but didn't realize the exact problem was in the `updater` script.

**Comment by Botspot** [comment]
Identical to #55 .

**Comment by Alextrapixel** [comment]
yup... it works now... why reopen issue by the way?

**Comment by Botspot** [comment]
I didn't mean to close it. 😄

Well **now** that it works for you, **now** I will close it.￼ On purpose this time.
