### ISSUE TITLE
App icons not showing up properly

### ISSUE THREAD

**Issue by Jai-JAP** [Botspot/pi-apps#654]
On Twister OS Windows 10 Dark (Nighthawk) theme some app icons do not show up properly

## Windows 10  
![Windows-10](https://user-images.githubusercontent.com/78354625/117786048-c2d1ca80-b262-11eb-9241-d0508b8771ca.png)

## PiSafe  
![PiSafe](https://user-images.githubusercontent.com/78354625/117786050-c36a6100-b262-11eb-81a8-38e95f5aa1c4.png)

## Github-CLI  
![Github-CLI](https://user-images.githubusercontent.com/78354625/117786053-c402f780-b262-11eb-86fb-90f7ad4ad102.png)

## AndroidBuddy  
![AndroidBuddy](https://user-images.githubusercontent.com/78354625/117786055-c402f780-b262-11eb-8a41-0c38ccf2b72e.png)

Also Youtubuddy icon-64 is not a square icon

## Youtubuddy  
![Youtubuddy](https://user-images.githubusercontent.com/78354625/117786042-c1a09d80-b262-11eb-8070-e0facdc22d36.png)

**Comment by Jai-JAP** [comment]
[pi-apps.zip](https://github.com/Botspot/pi-apps/files/6457800/pi-apps.zip)

This is a zip file consisting of modified icons. Hope it helps.

Extract it to your home folder and allow to replace or overwrite files if asked.

**Comment by Jai-JAP** [comment]
After applying this patch the icons are as below

## Windows 10
![Windows-10](https://user-images.githubusercontent.com/78354625/117789871-67094080-b266-11eb-9496-fd44c9f54caf.png)

## PiSafe
![PiSafe](https://user-images.githubusercontent.com/78354625/117789919-75eff300-b266-11eb-9f78-b778b1656bf6.png)

## Github-CLI
![Pi-Apps-Github-CLI](https://user-images.githubusercontent.com/78354625/117790090-a3d53780-b266-11eb-973b-3f1823344573.png)

## AndroidBuddy
![AndroidBuddy](https://user-images.githubusercontent.com/78354625/117790135-b0599000-b266-11eb-9053-b259acc3f2d8.png)

## YouTubuddy
![Youtubuddy](https://user-images.githubusercontent.com/78354625/117790181-be0f1580-b266-11eb-911e-4f204dd82e94.png)

**Comment by leha-code** [comment]
I have the same issue with xlunch on LEHA OS pi

**Comment by Botspot** [comment]
Finally! I had time to get to this. :) Thank you @Jai-jap for tweaking some of the icons. I used some of yours, and for others I re-did them for crisper pixels.
