### ISSUE TITLE
request anki flashcard app

### ISSUE THREAD

**Issue by sakagsakag** [Botspot/pi-apps#657]
can't install anki on raspi now.

**Comment by Itai-Nelken** [comment]
This app won't run on the pi, even with box86 as its a 64bit x86 app... it might run when box64 is released.

**Comment by Itai-Nelken** [comment]
@sakagsakag it turns out that anki is in the apt repositories. simply run `sudo apt update` and then `sudo apt install anki`.

**Comment by Itai-Nelken** [comment]
the one in the apt repos doesn't work unfortunately....

**Comment by Itai-Nelken** [comment]
this might work: https://www.raspberrypi.org/forums/viewtopic.php?t=294640#p1778988
@sakagsakag can you test that method? do it at your own risk though as it downgrades some packages I think and it might break other stuff.

**Comment by sakagsakag** [comment]
i tried this but can't.
considering other software risk, so i gave it up.
thanks your advices.

**Comment by Itai-Nelken** [comment]
[anki-2.1.15-1-any.pkg.zip](https://github.com/Botspot/pi-apps/files/6516606/anki-2.1.15-1-any.pkg.zip)
here is the anki arm64 package from the manjaro repos. inside of it are 2 hidden files containing the information about the package.

Right now I don't have the time or interest to work on this, so anyone who can, please do it!

**Comment by donnerkebab1730** [comment]
i might try but im probably not going to be able to do so

**Comment by CleanMachine1** [comment]
That seems to have a KDE dependency, and also a beautiful soup which I have tried and never seemed to work. However you might get different results
