### ISSUE TITLE
Problem with ClamAV installer

### ISSUE THREAD

**Issue by Itai-Nelken** [Botspot/pi-apps#66]
there is a problem with the Clam Antivirus installer, I think I fixed it, but the uninstaller has to be modified as well.

[install.zip](https://github.com/Botspot/pi-apps/files/5496628/install.zip)

**Comment by Itai-Nelken** [comment]
[uninstall.zip](https://github.com/Botspot/pi-apps/files/5496678/uninstall.zip)

here is the uninstall script

**Comment by Botspot** [comment]
Oh it looks like I never copied the finished (fixed) version of clamav to the pi-apps folder before uploading to the repository yesterday.

Okay, try it now.

**Comment by Itai-Nelken** [comment]
I'm trying it out, but it will take a lot of time because my internet decided to slow down today, it's like 2mbits download and upload.

**Comment by Botspot** [comment]
> I'm trying it out, but it will take a lot of time because my internet decided to slow down today, it's like 2mbits download and upload.

I know it's a long shot, but sometimes if my internet slows down considerably, running `sudo dhclient` helps. Maybe it would help you too.

**Comment by Itai-Nelken** [comment]
I'll try, what does it do?

**Comment by Botspot** [comment]
> I'll try, what does it do?

TBH, I really don't know. Just came across the command on a Linux forum a few years back and sometimes it works.

**Comment by Itai-Nelken** [comment]
ok, I don't think it will work it's my router I think.

**Comment by Itai-Nelken** [comment]
anyway ClamAV installs ok

**Comment by Itai-Nelken** [comment]
but the uninstaller doesn't

**Comment by Botspot** [comment]
> but the uninstaller doesn't

Hey I just made an edit to the uninstaller that should fix it. What's the contents of the `uninstall` file?

**Comment by Itai-Nelken** [comment]
#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$(dirname "$0")")")"
function error {
  echo -e "\\e[31m$1\\e[39m"
  exit 1
}

#if your app installs any packages, keep this command here so those packages will be removed.
"${DIRECTORY}/purge-installed" "$(dirname "$0")" || exit 1

if [ -f /usr/bin/thunar ];then
  sudo apt purge thunar-sendto-clamtk -y
fi

exit 0

**Comment by Botspot** [comment]
Okay, and what doesn't work for the uninstaller?

**Comment by Itai-Nelken** [comment]
it doesn't uninstall anything, here is the terminal output:
Uninstalling Clam Antivirus
Running purge-installed...
cat: '/home/pi/pi-apps/data/installed-packages/Clam Antivirus': No such file or directory
Does /home/pi/pi-apps/data/installed-packages/Clam Antivirus exist?

Uninstalled Clam Antivirus successfully.
Closing in 30 seconds.

**Comment by Botspot** [comment]
Oh I know what happened: `clamtk` and `clamav` were already installed before installing this app most recently. So during uninstall, Pi-Apps didn't think ClamAV installed anything.

Try purging `clamtk` and `clamav` manually, and from now on the ClamAV app will uninstall fully on your system.

**Comment by Itai-Nelken** [comment]
still doesn't work, same error

**Comment by Itai-Nelken** [comment]
it doesn't solve the problem, i still get the same error

**Comment by Botspot** [comment]
Please run:
```
sudo apt purge clamtk clamav
```
Then try installing 'Clam Antivirus' from Pi-Apps.  
Then try uninstalling Clam Antivirus.

**Comment by Itai-Nelken** [comment]
that's exactly what i did

**Comment by mobilegmYT** [comment]
I dont think `clamscan` works...

**Comment by Botspot** [comment]
> that's exactly what i did

If so, then maybe `pkg-install` didn't create an `installed-packages` file?
Please manually purge `clamtk` & `clamav`, then post the full terminal output when installing ClamAV via Pi-Apps.

**Comment by Botspot** [comment]
@Itai-Nelken What's your locale?

**Comment by Botspot** [comment]
@Itai-Nelken I just found the problem: the `pkg-install` line was commented out for some reason.

I changed

   # "${DIRECTORY}/pkg-install" "clamav clamtk" "$(dirname "$0")" || exit 1

to

   "${DIRECTORY}/pkg-install" "clamav clamtk" "$(dirname "$0")" || exit 1

and it works now!

Commit e0ff995395cdb060059b66f59e3099366934cad6

**Comment by Itai-Nelken** [comment]
great!
