### ISSUE TITLE
Possibility to download the available apps with pi-apps with another OS

### ISSUE THREAD

**Issue by orangina-mc** [Botspot/pi-apps#660]
Hello, I have a RPI4 on **Manjaro**, and I suggest adding the compatibility with other OS than Raspbian.
Or if it's not possible, adding an option to downloads with a simple command line a software available on the store.

**Comment by mobilegmYT** [comment]
> Hello, I have a RPI4 on **Manjaro**, and I suggest adding the compatibility with other OS than Raspbian.
> Or if it's not possible, adding an option to downloads with a simple command line a software available on the store.

It would be very hard to add multi-os support to every single app, when the userbase pi-apps is made for is mostly debian users. You could copy the install script for a app you'd like to install though, and run it in terminal. Some apps use apt though, which you'll need to change to pacman instead. 

E.G if you want to install colour emoji font:

Copy everything below this segment
![image](https://user-images.githubusercontent.com/44128563/118312857-3ec05280-b4af-11eb-9891-ea1426710053.png)

then run it in terminal.

**Comment by orangina-mc** [comment]
Ok, thank you
