### ISSUE TITLE
Updater syntax errors

### ISSUE THREAD

**Issue by Itai-Nelken** [Botspot/pi-apps#664]
```bash
/home/pi/pi-apps/updater: line 216: $'m\ndone\nIFS=': command not found
/home/pi/pi-apps/updater: line 220: 
    for i in 
    do
      /home/pi/pi-apps/manage update updater nofetch
      echo -e e[92mupdater: No such file or directory
/home/pi/pi-apps/updater: line 240: unexpected EOF while looking for matching `"'
/home/pi/pi-apps/updater: line 242: syntax error: unexpected end of file
```

**Comment by Botspot** [comment]
> ```shell
> /home/pi/pi-apps/updater: line 216: $'m\ndone\nIFS=': command not found
> /home/pi/pi-apps/updater: line 220: 
>     for i in 
>     do
>       /home/pi/pi-apps/manage update updater nofetch
>       echo -e e[92mupdater: No such file or directory
> /home/pi/pi-apps/updater: line 240: unexpected EOF while looking for matching `"'
> /home/pi/pi-apps/updater: line 242: syntax error: unexpected end of file
> ```

This is what happens when a bash script updates itself while running.
Run `updater` again and it'll work fine this time.
