### ISSUE TITLE
Thunder

### ISSUE THREAD

**Issue by hmsjy2017** [Botspot/pi-apps#666]
A P2P download software that supports BT.
I have successfully installed it on a 64-bit Raspberry Pi OS. The only drawback is that there is no icon.

It only supports ARM64.
https://raw.githubusercontent.com/hmsjy2017/debian-pi-aarch64-apps/master/apps/thunder/com.xunlei.download_1.0.0.1_arm64.deb
For the convenience of downloading, I have imported it into GitHub.

**Comment by Botspot** [comment]
In your opinion, would people prefer using this instead of Snapdrop for any reason?

**Comment by hmsjy2017** [comment]
@Botspot Thunder is different from Snapdrop. Thunder is a downloader, and Snapdrop is a file sharing tool. So Snapdrop cannot replace Thunder.

**Comment by fabianmendes** [comment]
Cool

**Comment by Botspot** [comment]
> A P2P download software that supports BT.
> I have successfully installed it on a 64-bit Raspberry Pi OS. The only drawback is that there is no icon.
> 
> It only supports ARM64.

Well that's another drawback, as most RPi users are still on armhf.

Today I got Thunder running in a 64-bit [vdesktop](https://github.com/Botspot/vdesktop).
It launched fine, but how do I change the language? If this is a Chinese-only app, then all of our English users will be disappointed when installing this.
Screenshot:
![2021-07-10-205047_1366x768_scrot](https://user-images.githubusercontent.com/54716352/125180552-e5c81e80-e1c0-11eb-825c-149e1f7483dc.png)

**Comment by Botspot** [comment]
Closing this issue because nobody answered my question:

> but how do I change the language?

**Comment by hmsjy2017** [comment]
@Botspot It seems that there is no option to switch languages.
