### ISSUE TITLE
github CLI

### ISSUE THREAD

**Issue by CleanMachine1** [Botspot/pi-apps#667]
The current version will be out of date probably in a few hours or maybe a day

Keep an eye on it 

https://github.com/cli/cli/releases/tag/v1.10.0-pre.4

**Comment by CleanMachine1** [comment]
https://github.com/cli/cli/releases/tag/v1.10.0

**Comment by CleanMachine1** [comment]
https://github.com/cli/cli/releases/tag/v1.10.1

**Comment by CleanMachine1** [comment]
I'll keep you update to date with this since I have it installed I see when APT get it

**Comment by Itai-Nelken** [comment]
thanks a lot!

**Comment by Itai-Nelken** [comment]
Updated to 1.10.1 in commit 7d3044b32a2886fca3356c6b33ad2dbf127ea5ce

**Comment by Itai-Nelken** [comment]
...
I will wait for 1.10.3 before updating again...

**Comment by CleanMachine1** [comment]
lol

**Comment by Itai-Nelken** [comment]
(didn't realize this issue was already closed...)

**Comment by CleanMachine1** [comment]
its updated to 3

**Comment by CleanMachine1** [comment]
@Itai-Nelken Could you upgrade it again

**Comment by Itai-Nelken** [comment]
done in commit e17bc06b7dee961d0c3e2b3f534dd0f905a97665

**Comment by CleanMachine1** [comment]
gh/unknown 1.11.0 amd64 [upgradable from: 1.10.3]
