### ISSUE TITLE
Install Pi-apps for non-sudoers

### ISSUE THREAD

**Issue by breeegz** [Botspot/pi-apps#672]
I tried your script today, installed perfectly for me, but when I went to check a kid's account it wasn't there.  Obviously, it was because pi-apps installed in my home directory.

The work around that I used was to promote kid1 to a sudoers, and install his own version.  Then I took admin rights away.  Without digging too deep, it looks like you are hard coded to the home directory.  I'd rather not do that for all 4 kids at my house.

Maybe if it was installing @ the root directory (/pi-apps) and make permissions such that it's easy to control who has access.  Or pick a home directory during install; pick mine as default, but let me edit it to point to /home/kid1.

I'll leave it up to you, since you're a better coder than I, and you know what your code is doing.

**Comment by mobilegmYT** [comment]
> Maybe if it was installing @ the root directory (/pi-apps) and make permissions such that it's easy to control who has access.

It's generally bad practice to install code to root directory/run an app as root, especially for pi-apps since it'll bork up install of other apps. Pi-apps is meant for beginners, and as such for debugging and convenience features it's put in the home directory. Most of pi-apps isn't designed for multi-person usage though so you might have to just manually install it on each account. Of course, manual install scripts for each app are available on GitHub if you go into the `apps` folder and find your app, then the install script, which you can copy the contents of and run in terminal.

**Comment by breeegz** [comment]
the trouble is that if you aren't a sudoer, then you can't install Minecraft Java, for instance.  if I "su myuser" so I can install it, them it goes to my home directory and not the directory that I'm in.  maybe my second suggestion would work better, have a confirmation where you have the opportunity to install it for someone else.  

it doesn't matter what you want to do for my own use case, I might stand alone.  And my workaround isn't horrible, just not very convenient.  And I'll look at the apps folder, maybe that will work for me.

**Comment by Itai-Nelken** [comment]
If you aren't a sudoer you can't install almost anything, not having root access makes pi-apps almost useless.
you can try to install pi-apps to your root directory and change the permissions of the folder, but you will have to change some of the scripts, and you won't be able to use the install script, you will have to manually move the files.

**Comment by breeegz** [comment]
> If you aren't a sudoer you can't install almost anything, not having root access makes pi-apps almost useless.
> you can try to install pi-apps to your root directory and change the permissions of the folder, but you will have to change some of the scripts, and you won't be able to use the install script, you will have to manually move the files.

I get it, but I think I'm looking at it like a Systems Admin, and you are looking at it from a different point of view.  Non-Sudoers need Sudoers to install things for them.  Please keep in mind that I am not saying anything is broken, I just wanted to make a suggestion...  (hence the tag)  in case you and your collaborators didn't think of it from this angle.  I might be the only person looking to install Minecraft Java on a Raspberry Pi 4 for his kids, and I'm not too keen on giving kids sudo access on any computer I administrate.  However, I doubt that I'm the only one looking at this particular conflict and challenge.

I'm not a coder, but I don't think my suggestion would be that difficult to implement, just let the installer pick the location of the install.  There might be more to it than I realize, but it's not like it's a "must-have".  Again, I have the expertise to be able to get this to work for me, others might not be so lucky.

Again, this isn't a trouble ticket, nor is it a bug report.  This is a suggestion for the direction of a really great resource for Raspberry Pi's and the Dad's that build them.

**Comment by Itai-Nelken** [comment]
I think I understand what you mean: you want to be able to install pi-apps to the root directory so you can for example install minecraft from your user (that has root access) but other users can still use it. is that correct @breeegz?
I didn't write pi-apps, thats @Botspot so I don't know exactly how everything works and how easy it could be to implement. but my guess is it will be changing a lot of paths.
Is there anything else that would have to be changed for that @Botspot?

**Comment by Botspot** [comment]
> I tried your script today, installed perfectly for me, but when I went to check a kid's account it wasn't there. Obviously, it was because pi-apps installed in my home directory.


Like any software installer, Pi-Apps is no different. In order to install certain system components or files, **it's necessary to gain root permissions**. There is no way to get around this fact. (If there was, we'd have to worry about unprivileged users installing stuff! That would be a security nightmare.)

But _unlike_ some other software installers, Pi-Apps also installs files to the current user's directory in some cases. Sometimes it copies configuration files around, while other times it installs the whole application to your home directory. This varies on an app-by-app basis.

My suggestions:
Configure each child account to ask for a root password whenever `sudo` is run. Only you should know the password.
Then install Pi-Apps on every child account and install the same app on each. Hopefully the script will successfully reinstall the system-wide files each time, and properly generate user-specific files each time. If all goes well, each child account will have the app installed correctly.

**Comment by CleanMachine1** [comment]
I understand that root is a privilege but let your kid experiment, if he breaks the current install, lesson learnt, wont make the same mistake

**Comment by CleanMachine1** [comment]
Whoops actually no probably not, 4 kids is a little too much if 1 kid breaks the entire thing.. Ignore me but teach the kids how to use sudo and when to use it and when not to

**Comment by breeegz** [comment]
> Configure each child account to ask for a root password whenever sudo is run. Only you should know the password.
> Then install Pi-Apps on every child account and install the same app on each.

I looked into having a different password for login and sudo.  I'm probably not going to reconfigure my sudo just for this.  

> root is a privilege but let your kid experiment

yes, root is a privilege.  I've started teaching them about sudo/root, about the CLI and getting them used to running commands without pointy/clicky.  Eventually they will _earn_ root/sudo, but not before.

>`#Download java and launcher
>mkdir ~/Minecraft && cd ~/Minecraft && wget https://github.com/mikehooper/Minecraft/raw/main/setupMC.sh && chmod +x >setupMC.sh && ./setupMC.sh || error 'Failed to install the launcher!'

This portion of the script is hard coded to go to my home directory, then it deletes it later.  Only the person that installs Minecraft needs sudo, the following can be done by any user, or it could be done for all users at time of install.

>' #Create desktop shortcut
> cd ~/.local/share/applications/
> echo "[Desktop Entry]
> Version=1.0
> Type=Application
> Name=Minecraft Launcher
> Comment=3D block based sandbox game
> Icon=$(dirname "$0")/icon-64.png
> Exec=env MESA_GL_VERSION_OVERRIDE=3.3 java -jar /usr/share/minecraftjava/launcher.jar
> Categories=Game;" > minecraft.desktop
> chmod +x minecraft.desktop
> cd
> 
> mkdir -p ~/.minecraft
> echo '{
>   "profiles": {
>     "(Default)": {
>       "name": "(Default)",
>       "javaDir": "/opt/jdk/jdk1.8.0_251/bin/java",
>       "javaArgs": "-Dorg.lwjgl.librarypath='$HOME'/lwjgl3arm64 -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M"
>     }
>   },
>   "selectedProfile": "(Default)",
>   "clientToken": "c4a6f915-4d47-47bf-a8f4-746090e7e576",
>   "authenticationDatabase": {},
>   "launcherVersion": {
>     "name": "1.6.93",
>     "format": 21,
>     "profilesFormat": 1
>   }
> }' > $HOME/.minecraft/launcher_profiles.json`

I understand that I picked one example out of the hundred or so available install scripts.

**Comment by Botspot** [comment]
> This portion of the script is hard coded to go to my home directory, then it deletes it later.

*No*, it's "hard coded" to go to whichever home directory you're currently using.
For example, if you switch to one of your kid's accounts and run the script, it will now use *that* home directory.

> I understand that I picked one example out of the hundred or so available install scripts, but I'm not wrong that the install script is hard coded to home directories. And I not wrong that in a multi-user system, _like Linux_, that you should limit privileged accounts to an account-by-account basis.
> 
> With all that said, this project belongs to @Botspot and if they don't want to make a change like this, then they don't have to. This was merely a suggestion.

At the moment, I'm unable to comprehend how a script could achieve what you are looking to do. Even if there was a clear way to go about this, I would have to decide if the number of users this would benefit, would be worth modifying and testing over 240 scripts.
