### ISSUE TITLE
danganronpa app request

### ISSUE THREAD

**Issue by coolcatsuperhero** [Botspot/pi-apps#673]
Does anyone know how to get one of the danganronpas on to pi apps?

and if no one does can someone find out how to?

**Comment by donnerkebab1730** [comment]
ill look into it, but im not sure if ill find anything

**Comment by coolcatsuperhero** [comment]
:)

**Comment by donnerkebab1730** [comment]
after a couple mins looking into it i think the best option would be to emulate an old version of one of the games.

i think theres an emulator compatible with psvita on pi apps so here is the download link to the rom

https://romsforever.co/roms/ps-vita/danganronpa.html

idk if it is a working rom as i havent tested but this was the best i could find

**Comment by coolcatsuperhero** [comment]
So would I put that into new app?

**Comment by donnerkebab1730** [comment]
i have no idea but from what i an see its the only way to get it to work on pi

**Comment by coolcatsuperhero** [comment]
So I’m basically brand new to it so could you sorta help me with installation?

**Comment by donnerkebab1730** [comment]
_So I’m basically brand new to it so could you sorta help me with _installation?_

same

i am currently on laptop so i cant help atm however i will be able to write down how to install in about 45 min

**Comment by coolcatsuperhero** [comment]
Nice

**Comment by donnerkebab1730** [comment]
nvm i might have to write it tomorrow sry

**Comment by coolcatsuperhero** [comment]
It’s fine, you can take all the time in the world

**Comment by CleanMachine1** [comment]
If you can get PS Vita on a Pi, (I don't know if you can) then you may be able to however it depending on the graphical requirements of the game, it will probably run terribly

**Comment by donnerkebab1730** [comment]
> If you can get PS Vita on a Pi, (I don't know if you can) then you may be able to however it depending on the graphical requirements of the game, it will probably run terribly 

I've tried before and I think it's really just a case of do.yiu have anything running in the background and what pi you have

**Comment by CleanMachine1** [comment]
I dont emulate games.. and I don't use a pi

**Comment by donnerkebab1730** [comment]
its really a case of now can i find a rom that works because there are absoloutley no results anywhere ive spent a while looking, and ill try some more but i dont think it will work

**Comment by Botspot** [comment]
> Does anyone know how to get one of the danganronpas on to pi apps?
> 
> and if no one does can someone find out how to?

It needs to run on Raspberry Pi first, before it could be added to this popular app installer.
The people who roam around here probably won't be of much help, because currently there is no known way to run danganronpa on Raspberry Pi.

@coolcatsuperhero, I suggest you ask about this on the [Raspberry Pi Forums](https://www.raspberrypi.org/forums/). Not here.

**Comment by donnerkebab1730** [comment]
i was about to say it appears i found no way of emulating it, however maby when the rpi 5 releases (ages away) it could work using retropi

**Comment by CleanMachine1** [comment]
And whys that

**Comment by coolcatsuperhero** [comment]
When is ages away?

**Comment by CleanMachine1** [comment]
The pi 5 will probably be available in 1-2 years time and I wouldnt be suprised if the SOC was the same

**Comment by coolcatsuperhero** [comment]
By that time I’ll be married and have kids

**Comment by CleanMachine1** [comment]
I assume your new to the pi and Linux, personally I started 2 years back.

However Debian Bullseye will be released soon so there is at least that to look forward to, that bring a lot of packages to modern standards... rather than something from the last decade

**Comment by donnerkebab1730** [comment]
> And whys that

 nobody can emulate it as they require too much power even on the newest raspi. but i think next time when retropi and retroarch update you will be able to play it, maybe.

**Comment by coolcatsuperhero** [comment]
Darn, well then thanks!

**Comment by donnerkebab1730** [comment]
your sort of welcome i guess though i didnt manage to do anything, if i see anything pop up ill let you know.

**Comment by CleanMachine1** [comment]
Very much doubt that. A pi will always be extremely lacklustre when it comes to performance, however consider its a sub-50 pc.

Don't expect to run slightly demanding games on a pi at higher than 20fps. A pis graphic chip is made nothing but Desktop and slight rendering of things, not for games

**Comment by donnerkebab1730** [comment]
its an old game though and there are already roms i can get so i think it will happen some time just not now

**Comment by coolcatsuperhero** [comment]
That’s great

**Comment by mobilegmYT** [comment]
Well not for like really new games... but old games run quite well.

**Comment by mobilegmYT** [comment]
> Very much doubt that. A pi will always be extremely lacklustre when it comes to performance, however consider its a sub-50 pc.
> 
> Don't expect to run slightly demanding games on a pi at higher than 20fps. A pis graphic chip is made nothing but Desktop and slight rendering of things, not for games

Well not for like really new games... but old games run quite well.
