### ISSUE TITLE
Flashpoint

### ISSUE THREAD

**Issue by fabianmendes** [Botspot/pi-apps#682]
Is that possible to create a _BlueMaxima's_ **Flashpoint** for Raspberry pi? It seems to be amd64 only, but I think it could be possible because it is for web page-based games and they required Flash plugin, most of them are Java related.

https://bluemaxima.org/flashpoint/downloads

**Comment by Itai-Nelken** [comment]
I tried to get it to run once (https://github.com/FlashpointProject/launcher/issues/179), and while I somehow got it to compile correctly, I never got the data part to work, so its basically useless on the pi so far.

**Comment by Botspot** [comment]
We can re-open this issue if this software runs on Raspberry Pi.
