### ISSUE TITLE
[DOCS] add  the new screenshot of piapps updater

### ISSUE THREAD

**Issue by leha-code** [Botspot/pi-apps#689]

**Comment by mobilegmYT** [comment]
You could have PRed it in...

**Comment by leha-code** [comment]
No. I don't want more bad relationships and you callingmme a dummy

**Comment by mobilegmYT** [comment]
> No. I don't want more bad relationships and you callingmme a dummy

... Just saying Botspot is extremely busy, he doesn't have the time to really do anything except add a few apps and merge PRs. You could help him out by taking a screenshot or 2 and adding them in a PR.

**Comment by leha-code** [comment]
I'm on mobile, lol! You can take the screen from discord though

**Comment by Botspot** [comment]
> No. I don't want more bad relationships and you callingmme a dummy

Whoa whoa, what?

About this request, yes I know about it. But it involves booting an image with vdesktop and I haven't had time to do that yet. Over 50 emails in the inbox, just for today. :(

**Comment by Botspot** [comment]
Done with commit a2d0520261b155656c1f15f890f4a408016a365d.
