### ISSUE TITLE
Wine - Box86 - Among Us

### ISSUE THREAD

**Issue by Pythonic456** [Botspot/pi-apps#690]
I am trying to run Among Us on a RPi 4B. However I am having trouble (as expected). Here is the error when running `Among Us.exe` (which I have acquired straight from Steam).

```
pi@raspberrypi4b:~/Downloads $ wine Among\ Us.exe 
Box86 with Dynarec v0.2.1 b588709a built on May 23 2021 00:03:17
Box86 with Dynarec v0.2.1 b588709a built on May 23 2021 00:03:17
Box86 with Dynarec v0.2.1 b588709a built on May 23 2021 00:03:17
0024:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
0024:fixme:imm:ImmReleaseContext (0001004A, 087B5B58): stub
0024:fixme:kernelbase:AppPolicyGetProcessTerminationMethod FFFFFFFA, 0030FC24
pi@raspberrypi4b:~/Downloads $ 00b8:fixme:file:CancelSynchronousIo (00000080): stub
00b8:fixme:kernelbase:AppPolicyGetProcessTerminationMethod FFFFFFFA, 0031FE4C
011c:fixme:kernelbase:AppPolicyGetProcessTerminationMethod FFFFFFFA, 0031FE4C
```

![2021-05-25-190006_1920x1200_scrot](https://user-images.githubusercontent.com/56113118/119546756-2e03bc80-bd8c-11eb-977b-52e6d5cc2aa9.png)

Running the latest version of Box86 and the newest Wine version from Pi-Apps (which may not be the latest wine version).

Thanks!

**Comment by mobilegmYT** [comment]
> I am trying to run Among Us on a RPi 4B. However I am having trouble (as expected). Here is the error when running `Among Us.exe` (which I have acquired straight from Steam).
> 
> ```
> pi@raspberrypi4b:~/Downloads $ wine Among\ Us.exe 
> Box86 with Dynarec v0.2.1 b588709a built on May 23 2021 00:03:17
> Box86 with Dynarec v0.2.1 b588709a built on May 23 2021 00:03:17
> Box86 with Dynarec v0.2.1 b588709a built on May 23 2021 00:03:17
> 0024:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
> 0024:fixme:imm:ImmReleaseContext (0001004A, 087B5B58): stub
> 0024:fixme:kernelbase:AppPolicyGetProcessTerminationMethod FFFFFFFA, 0030FC24
> pi@raspberrypi4b:~/Downloads $ 00b8:fixme:file:CancelSynchronousIo (00000080): stub
> 00b8:fixme:kernelbase:AppPolicyGetProcessTerminationMethod FFFFFFFA, 0031FE4C
> 011c:fixme:kernelbase:AppPolicyGetProcessTerminationMethod FFFFFFFA, 0031FE4C
> ```
> 
> ![2021-05-25-190006_1920x1200_scrot](https://user-images.githubusercontent.com/56113118/119546756-2e03bc80-bd8c-11eb-977b-52e6d5cc2aa9.png)
> 
> Running the latest version of Box86 and the newest Wine version from Pi-Apps (which may not be the latest wine version).
> 
> Thanks!

See https://www.youtube.com/watch?v=ZJ74jKixHa8

**Comment by Pythonic456** [comment]
Thanks for your quick response! But nope. Still doesn't work. Running the command `env GALLIUM_HUD=simple,fps env LIBGL_ALWAYS_SOFTWARE=1 wine "Among Us.exe"` gives the same errors.

**Comment by mobilegmYT** [comment]
> LIBGL_ALWAYS_SOFTWARE=1 wine "Among Us.exe"

Try `LIBGL_ALWAYS_SOFTWARE=1 wine "Among Us.exe"`

**Comment by Pythonic456** [comment]
Same thing happens.

**Comment by mobilegmYT** [comment]
> Same thing happens.

Never seen that... the libgl flag should force it to run in gl than dx. Perhaps ask in pi labs.

**Comment by Pythonic456** [comment]
https://user-images.githubusercontent.com/56113118/119550879-d6b41b00-bd90-11eb-9d68-90700bf3f7cc.mp4

I run the command, then wait for a while, then get an error, then show that no wine processes are still running (wine usually keeps running after you ^C or exit the terminal).

**Comment by Botspot** [comment]
Closing this issue, as it is not related to an error in Pi-Apps.
