### ISSUE TITLE
Xfce

### ISSUE THREAD

**Issue by leha-code** [Botspot/pi-apps#691]
Can this app run on RPi? If so, please provide a link to a tutorial if applicable.
Yes, lol, Google xfce on raspberry pi
Is this app something many GUI users would find useful?
It is the best desktop!
Is this app installable with `sudo apt install`?
Yes, lol
If you've created a zip file for this app, upload it here.
I will this evening if I will be able to

**Comment by Botspot** [comment]
@techcoder20 made the Mac OS theme. That theme switches you to XFCE. With his permission, you could probably use that as a starting point.

**Comment by techcoder20** [comment]
> @techcoder20 made the Mac OS theme. That theme switches you to XFCE. With his permission, you could probably use that as a starting point.

It doesnt install xfce, It just installs a few components of the xfce desktop. If you do want to install the xfce desktop just use `tasksel`

**Comment by slashtechno** [comment]
I do not think Raspberry Pi OS can switch desktop environments from the login screen like Ubuntu for example. If the script installed XFCE with Taskel and then switched to it, then it might work.

**Comment by The-Sapphire-Starship** [comment]
Using tasksel does work switch your desktop environment on the raspberry pi to xfce, if did it a couple of days ago

**Comment by mobilegmYT** [comment]
Pretty easy to use tasksel or apt to do it, I think this can be closed maybe @Botspot

**Comment by leha-code** [comment]
Apt version is outdated.

**Comment by Itai-Nelken** [comment]
XFCE depends on a lot of packages, and if we want a newer version we will need newer versions of all packages which has a high risk of breaking the OS.

**Comment by Botspot** [comment]
I think this would take too much maintenance and it would harm too many people's systems.
Remember the RetroPie app? It was so complicated that we had to pull it from pi-apps as it was the most failure-prone app.
