### ISSUE TITLE
I installed the windows theme, worked well, unistalled, fast destroyed openbox

### ISSUE THREAD

**Issue by PanDabStudios** [Botspot/pi-apps#693]
thats it, all my previous config, anything I had done was lost, really for pi desktop its crap.

**Comment by Botspot** [comment]
I wonder what happened! [The Windows 10 theme](https://github.com/Botspot/Windows-10) was carefully designed to backup every file it overwrote, and stores all config to restore it when uninstalling.

**Comment by Botspot** [comment]
> really for pi desktop its crap.

Windows 10 theme was _specifically designed_ to work on Raspberry Pi OS desktop and it's been extensively tested to restore backup configs under varying conditions.

**Comment by PanDabStudios** [comment]
hey, I didn't saw any errors, and I had To re-install raspbian to make Drop box work again, I really hope U can make it work, all in all the ap is really good

**Comment by Botspot** [comment]
> hey, I didn't saw any errors, and I had To re-install raspbian to make openbox work again, I really hope U can make it work, all in all the ap is really good

Unfortunately, there is no way I can even attempt to fix this, given the information you gave me. Software is complicated. When it breaks, complete and exact steps and errors are necessary for me to be able to work with. If exact error messages are not available, then I need complete and exact steps for how to repeat the error.

Without that, none of us are able to help you, no matter how much we want to.
