### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by Kirill2006183** [Botspot/pi-apps#694]
/root/ pi-apps/ api: line 15: file: command not found
/root/ pi-apps/ api: line 17: file: command not found 
how to fix it

**Comment by mobilegmYT** [comment]
> /root/ pi-apps/ api: line 15: file: command not found
> /root/ pi-apps/ api: line 17: file: command not found
> how to fix it

Please do not use root to install/run pi-apps.

**Comment by Botspot** [comment]
> /root/ pi-apps/ api: line 15: file: command not found
> /root/ pi-apps/ api: line 17: file: command not found
> how to fix it

I see two problems.

1. First, there has been absolutely zero testing for running Pi-Apps as the root user. Proceed at your own risk and brace yourself for endless permission errors.
2. Whatever system you are using does not include the `file` command. I've not seen this problem before, though I have known it's theoretically possible as the `file` command is not POSIX-compliant.

**Comment by Kirill2006183** [comment]
> > /root/ pi-apps/ api: line 15: file: command not found
> > /root/ pi-apps/ api: line 17: file: command not found
> > how to fix it
> 
> Please do not use root to install/run pi-apps.

Now access is denied /root/pi-apps/gui I did without root

**Comment by Botspot** [comment]
> > > /root/ pi-apps/ api: line 15: file: command not found
> > > /root/ pi-apps/ api: line 17: file: command not found
> > > how to fix it
> > 
> > 
> > Please do not use root to install/run pi-apps.
> 
> Now access is denied /root/pi-apps/gui I did without root

Exactly. If you use root even once with pi-apps, it changes the permissions for some files and breaks its usage for non-root usage.
To solve, I suggest you delete the whole pi-apps folder and start over.

Also, @Kirill2006183, what operating system are you using that doesn't include the `file` command?

**Comment by Kirill2006183** [comment]
> > > > / root / pi-apps / api: строка 15: файл: команда не найдена 
> > > > / root / pi-apps / api: строка 17: файл: команда не найдена, 
> > > > как это исправить
> > > 
> > > 
> > > Пожалуйста, не используйте root для установки / запуска pi-приложений.
> > 
> > 
> > Теперь доступ запрещен / root / pi-apps / gui Я сделал без рута
> 
> Точно. Если вы используете root даже один раз с pi-приложениями, это изменяет разрешения для некоторых файлов и нарушает его использование для использования без полномочий root.
> Чтобы решить эту проблему, я предлагаю вам удалить всю папку pi-apps и начать заново.
> 
> Кроме того, @ Kirill2006183 , какую операционную систему вы используете, в которой нет этой `file`команды?

Well I'm still using ubuntu system

**Comment by Kirill2006183** [comment]
Solved this error you need to download this program file sudo apt install file only without root

**Comment by Kirill2006183** [comment]
Solved this error you need to download this program file sudo apt install file only without root

**Comment by Kirill2006183** [comment]
Solved this error you need to download this program file sudo apt install file only without root
