### ISSUE TITLE
tor-browser

### ISSUE THREAD

**Issue by glefter** [Botspot/pi-apps#697]
Can this app run on RPi? If so, please provide a link to a tutorial if applicable.

Is this app something many GUI users would find useful?

Is this app installable with `sudo apt install`?

If you've created a zip file for this app, upload it here.

**Comment by mobilegmYT** [comment]
> Can this app run on RPi? If so, please provide a link to a tutorial if applicable.
> 
> Is this app something many GUI users would find useful?
> 
> Is this app installable with `sudo apt install`?
> 
> If you've created a zip file for this app, upload it here.

Tor is already on pi-apps, just run `~/pi-apps/updater` to update pi-apps and get it.
