### ISSUE TITLE
Failed to install Tor Browser with install-32 script!

### ISSUE THREAD

**Issue by glefter** [Botspot/pi-apps#698]
Can this app run on RPi? If so, please provide a link to a tutorial if applicable.

Is this app something many GUI users would find useful?

Is this app installable with `sudo apt install`?

If you've created a zip file for this app, upload it here.

**Comment by mobilegmYT** [comment]
@glefter Send screenshot

**Comment by Itai-Nelken** [comment]
@glefter why did you close?
