### ISSUE TITLE
Pi-Apps terminal - bash edition

### ISSUE THREAD

**Issue by Itai-Nelken** [Botspot/pi-apps#699]
https://github.com/Itai-Nelken/PiApps-terminal_bash-edition

[Pi-Apps terminal.zip](https://github.com/Botspot/pi-apps/files/6562956/Pi-Apps.terminal.zip)

I have no icon for it.
There is a problem, @techcoder20's pi-apps terminal is already in pi-apps. should both be in pi-apps? or only one? and if only one, which one?
@techcoder20 and @Botspot and anyone else that happens to come by, what is your opinion?

**Comment by techcoder20** [comment]
Well @Botspot added the pi-apps terminal advanced as an app because it was written in python. What about removing the pi apps terminal advanced app and integrating the bash version so that, Pi Apps is 100 % bash

**Comment by Itai-Nelken** [comment]
good idea, what do you say @Botspot?

**Comment by Botspot** [comment]
> Well @Botspot added the pi-apps terminal advanced as an app because it was written in python.

Correct. Let me explain:
Part of what makes Pi-Apps so unique is the choice of programming language. I believe that bash-GUI scripts have great potential for certain tasks. So to demonstrate the power of bash, I want Pi-Apps to be pure-bred so that the statement "pi-apps is 100% bash" to be completely true, and without exceptions.

> What about removing the pi apps terminal advanced app

I hesitate to remove an app from the store just because there's a "better" alternative. Besides, making such a move would likely anger a few die-hard users who (for whatever reason) prefer the python terminal client instead of the bash one.

> and integrating the bash version so that, Pi Apps is 100% bash

Fine with me, in the long run. But before this is pushed to 100% of pi-apps installs, it may be smarter to distribute this to a smaller number of users at first. This approach should weed out any remaining bugs, as well as generate feedback to its further improvement.

Once the bash-based pi-apps terminal client is deemed to be stable and appreciated by its users, then at that point I think it would be ready to ship in all pi-apps installs.

**Comment by Itai-Nelken** [comment]
>I hesitate to remove an app from the store just because there's a "better" alternative. Besides, making such a move would likely anger a few die-hard users who (for whatever reason) prefer the python terminal client instead of the bash one.

Maybe make a general app called 'Pi-Apps Terminal' that when installed opens a menu like the 'Downgrade Chromium' app that asks you what edition you want with a tooltip for each edition showing its strength's and weakness's.

Then while the bash edition is in 'beta' it can be there (maybe make a announcement in the discord server and in the pi-apps announcements) and then when/if its added it can be removed and the name can be changed to 'Pi-Apps terminal - Python edition'. then if a new pi-apps terminal is created, it can be renamed back to 'Pi-Apps terminal' and have the selection menu again. 
That way the Python version isn't removed, and if/when there will be other editions they can be added so the user can install whatever version they prefer (The uninstall scripts will have to restore the bash one).

**Comment by Itai-Nelken** [comment]
>Fine with me, in the long run. But before this is pushed to 100% of pi-apps installs, it may be smarter to distribute this to a smaller number of users at first. This approach should weed out any remaining bugs, as well as generate feedback to its further improvement.

how would we do that? maybe a pop up that can be told to never come back asking the users to help test it? or just an announcement in the top banner of the main window? maybe add some code that will generate a random number, and if it matches one of a list of numbers, then the pop up is shown (with a button to install it, to dismiss it, and to make it never show again)?

something like this maybe:
```bash
function pop_up() {
	# code to create the pop up
}

# change the value of UPTO to change the maximum number that can be generated.
# for example: if UPTO=10, a random number between 1 and 10 will be generated. if UPTO=20, a random number between 1 and 20 will be generated.
UPTO=20
num="$((1+$RANDOM%$UPTO))"
case num in
	1|3|5|10|20|6|9|8|4)
		pop_up
	;;
esac
```

**Comment by Itai-Nelken** [comment]
I tested every feature of the bash edition multiple times including with invalid options to generate a error, but unexpected bugs always appear...

**Comment by Botspot** [comment]
> > Fine with me, in the long run. But before this is pushed to 100% of pi-apps installs, it may be smarter to distribute this to a smaller number of users at first. This approach should weed out any remaining bugs, as well as generate feedback to its further improvement.
> 
> how would we do that? maybe a pop up that can be told to never come back asking the users to help test it?

How about adding this as an app that anyone can choose to install. Then point to it using discord and maybe the pi-apps announcements.

If it's well-accepted, then in the future it can be installed by default on all pi-apps installs.

**Comment by Itai-Nelken** [comment]
that sounds good

**Comment by Botspot** [comment]
Added with commit 1f7d0de1034970e530dcb4ea996903d5cae299db
