### ISSUE TITLE
install-32 always failing

### ISSUE THREAD

**Issue by Pechu317** [Botspot/pi-apps#702]
I'm using Raspbian OS, and whenever I try to install something that would use Box86 or Box86 itself, I always get the same error: `Failed to install Box86 with install-32 script!`

Also, not sure if this is related, but the line right above that says `Failed to run sudo apt update`.

Below is the copy/pasted output of what happens when I try to install something that would use Box86 or Box86 itself.
[box86error.txt](https://github.com/Botspot/pi-apps/files/6567278/box86error.txt)

**Comment by Pechu317** [comment]
Actually, with further testing, this seems to be a problem with install-32, not Box86. Updating title

**Comment by mobilegmYT** [comment]
> I'm using Raspbian OS, and whenever I try to install something that would use Box86 or Box86 itself, I always get the same error: `Failed to install Box86 with install-32 script!`
> 
> Also, not sure if this is related, but the line right above that says `Failed to run sudo apt update`.
> 
> Below is the copy/pasted output of what happens when I try to install something that would use Box86 or Box86 itself.
> [box86error.txt](https://github.com/Botspot/pi-apps/files/6567278/box86error.txt)

Try `wget -qO- https://itai-nelken.github.io/weekly-box86-debs/debian/KEY.gpg | sudo apt-key add -`, then reinstall it in pi-apps.

**Comment by Pechu317** [comment]
> > I'm using Raspbian OS, and whenever I try to install something that would use Box86 or Box86 itself, I always get the same error: `Failed to install Box86 with install-32 script!`
> > Also, not sure if this is related, but the line right above that says `Failed to run sudo apt update`.
> > Below is the copy/pasted output of what happens when I try to install something that would use Box86 or Box86 itself.
> > [box86error.txt](https://github.com/Botspot/pi-apps/files/6567278/box86error.txt)
> 
> Try `wget -qO- https://itai-nelken.github.io/weekly-box86-debs/debian/KEY.gpg | sudo apt-key add -`, then reinstall it in pi-apps.

I just tried that, same result. Like I mentioned before, I do believe this is an issue with install-32 rather than Box86.

**Comment by mobilegmYT** [comment]
> > > I'm using Raspbian OS, and whenever I try to install something that would use Box86 or Box86 itself, I always get the same error: `Failed to install Box86 with install-32 script!`
> > > Also, not sure if this is related, but the line right above that says `Failed to run sudo apt update`.
> > > Below is the copy/pasted output of what happens when I try to install something that would use Box86 or Box86 itself.
> > > [box86error.txt](https://github.com/Botspot/pi-apps/files/6567278/box86error.txt)
> > 
> > 
> > Try `wget -qO- https://itai-nelken.github.io/weekly-box86-debs/debian/KEY.gpg | sudo apt-key add -`, then reinstall it in pi-apps.
> 
> I just tried that, same result. Like I mentioned before, I do believe this is an issue with install-32 rather than Box86.

I don't have a particular fix for the pi-apps issue, that's @Itai-Nelken's stuff. The following will help manually install b86 tho.

```
sudo apt-get install cmake -y
 
cd ~/Downloads
git clone https://github.com/ptitSeb/box86
cd box86
mkdir build; cd build; cmake .. -DRPI4=1 -DCMAKE_BUILD_TYPE=RelWithDebInfo
make -j4
sudo make install
sudo systemctl restart systemd-binfmt
cd ~/Downloads
rm -rf box86 # clean up
```

**Comment by Botspot** [comment]
> I'm using Raspbian OS, and whenever I try to install something that would use Box86 or Box86 itself, I always get the same error: `Failed to install Box86 with install-32 script!`
> 
> Also, not sure if this is related, but the line right above that says `Failed to run sudo apt update`.

Yes it's related. That "Failed to install Box86 with install-32 script!" message is just a generic overview. It tells me nothing about what the problem actually is.

Please copy the terminal output and paste it here, or attach a screenshot.

**Comment by Itai-Nelken** [comment]
The problem is the vivaldi repository.
Try to uninstall vivaldi and see if it fixes the error.

**Comment by Itai-Nelken** [comment]
Output from the fike @Pechu317 included:
```
Installing Box86 with install-32 script
adding box86 repo...
--2021-05-30 21:30:23--  https://itai-nelken.github.io/weekly-box86-debs/debian/box86.list
Resolving itai-nelken.github.io (itai-nelken.github.io)... 185.199.111.153, 185.199.108.153, 185.199.109.153, ...
Connecting to itai-nelken.github.io (itai-nelken.github.io)|185.199.111.153|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 62 [text/plain]
Saving to: ‘/etc/apt/sources.list.d/box86.list’

/etc/apt/sources.li 100%[===================>]      62  --.-KB/s    in 0s      

2021-05-30 21:30:23 (1.30 MB/s) - ‘/etc/apt/sources.list.d/box86.list’ saved [62/62]

adding key...
OK
running 'sudo apt update'...
Hit:1 https://itai-nelken.github.io/weekly-box86-debs/debian  InRelease
Hit:2 http://archive.raspberrypi.org/debian buster InRelease                   
Ign:3 http://repo.vivaldi.com/stable/deb stable InRelease                      
Hit:4 http://raspbian.raspberrypi.org/raspbian buster InRelease
Get:5 http://repo.vivaldi.com/stable/deb stable Release [3,831 B]
Get:6 http://repo.vivaldi.com/stable/deb stable Release.gpg [833 B]
Ign:6 http://repo.vivaldi.com/stable/deb stable Release.gpg
Reading package lists... Done
W: GPG error: http://repo.vivaldi.com/stable/deb stable Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 793FEB8BB69735B2
E: The repository 'http://repo.vivaldi.com/stable/deb stable Release' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
Failed to run sudo apt update

Failed to install Box86 with install-32 script!
▲ Need help? Copy the above error output or take a screenshot.
Please ask on Github: https://github.com/Botspot/pi-apps/issues/new/choose
Or on Discord: https://discord.gg/RXSTvaUvuu

Close this window to exit
```

**Comment by Itai-Nelken** [comment]
@Pechu317 run this:
`https://repo.vivaldi.com/archive/linux_signing_key.pub | sudo apt-key add -`
Then try to install box86 again.
Tge problem you have is the vivaldi repo key.

**Comment by Pechu317** [comment]
> @Pechu317 run this:
> `https://repo.vivaldi.com/archive/linux_signing_key.pub | sudo apt-key add -`
> Then try to install box86 again.
> Tge problem you have is the vivaldi repo key.

i get this error: `-bash: https://repo.vivaldi.com/archive/linux_signing_key.pub: No such file or directory
gpg: no valid OpenPGP data found.`

**Comment by Itai-Nelken** [comment]
@Pechu317 try this:
`wget -qO- https://repo.vivaldi.com/archive/linux_signing_key.pub | sudo apt-key add -`

**Comment by Itai-Nelken** [comment]
Then install box86 again

**Comment by Botspot** [comment]
I think it's safe to say the problem has been identified and that the original poster's system is up and running well now.
In addition, this issue has been stale for a week.

As a result, I'm closing this issue.
