### ISSUE TITLE
Anyone some help?

### ISSUE THREAD

**Issue by Skilowi** [Botspot/pi-apps#712]
Sooooooooo,

I tried to contact TheBrokenRail team but didnt found anything

As ya know pi-apps offers to install Minecraft-pi launcher with classic MCPI, MCPI modded and MCPE. All of those versions have build-in minecraft server. But that server is in miserable state: laggy, cannot do anything but breaking blocks coz picking up anything is impossible (the entire world is covered in lying blocks and items (ill link ss))
![2021-06-04-001927_1920x1080_scrot](https://user-images.githubusercontent.com/76708049/120722282-cce89100-c4cf-11eb-8431-2360177b23e0.png)
Now imagine the entire world is like that: wherever you see: lying block of dirt, cobblestone sand and other trash, and u cant pick em up

Do anyone have contact wit TheBrokenRail team? Do they know what is going on with server? Do they plan anything about it? Are pancakes strongest weapon in universe? 

sorry but i dont have where to ask

yes - that issue is completly not related with pi-apps

**Comment by chunky-milk** [comment]
@Skilowi Do you have Discord?

I know that MCPI has a discord server in which they provide support: https://discord.gg/sq6hKKQXDU

**Comment by mobilegmYT** [comment]
> Sooooooooo,
> 
> I tried to contact TheBrokenRail team but didnt found anything
> 
> As ya know pi-apps offers to install Minecraft-pi launcher with classic MCPI, MCPI modded and MCPE. All of those versions have build-in minecraft server. But that server is in miserable state: laggy, cannot do anything but breaking blocks coz picking up anything is impossible (the entire world is covered in lying blocks and items (ill link ss))
> ![2021-06-04-001927_1920x1080_scrot](https://user-images.githubusercontent.com/76708049/120722282-cce89100-c4cf-11eb-8431-2360177b23e0.png)
> Now imagine the entire world is like that: wherever you see: lying block of dirt, cobblestone sand and other trash, and u cant pick em up
> 
> Do anyone have contact wit TheBrokenRail team? Do they know what is going on with server? Do they plan anything about it? Are pancakes strongest weapon in universe?
> 
> sorry but i dont have where to ask
> 
> yes - that issue is completly not related with pi-apps

MCPI Modded itself does not contain any supported/reccomended server software. https://mcpirevival.tk/servers.html might be what your searching for

**Comment by Itai-Nelken** [comment]
I'm closing this as it's not related to pi-apps, but feel free to keep discussing the issue here.
