### ISSUE TITLE
apps listed

### ISSUE THREAD

**Issue by akhilleusuggo** [Botspot/pi-apps#713]
What is the factors that in some of my devices some apps are shown, and others are not?

**Comment by mobilegmYT** [comment]
> What is the factors that in some of my devices some apps are shown, and others are not?

The big thing is if you are on 32-bit or 64-bit, and if you are using Twister OS.

**Comment by akhilleusuggo** [comment]
I see, thank you for the answer.
When you say 64-bit are you referring to OS based 64-bits, or from the boot config file?

**Comment by akhilleusuggo** [comment]
Thank you for the quick answer.
I'm closing.
