### ISSUE TITLE
64bit eDEX-UI desktop entry is wrong

### ISSUE THREAD

**Issue by TamaTamaGoGo** [Botspot/pi-apps#715]
I am 64bit user.

I tried to install eDEX-UI, and when I pushed eDEX-UI at application launcher, it didn’t response.
I copied command what the code written at menu’s profile, and I got output like the AppImage isn’t found.

I found wrong setting at desktop entry.

`Exec=bash -c "\""sudo modprobe fuse; $HOME/eDEX-UI-RPi/eDEX-UI-Linux-armv7l_2.2.7.AppImage"\"" %U`

This might be
`Exec=bash -c "\""sudo modprobe fuse; $HOME/eDEX-UI-RPi/eDEX-UI-Linux-arm64_2.2.7.AppImage"\"" %U`

That’s important bug.
If you have a time, fix it please🙏

**Comment by Itai-Nelken** [comment]
Fixed, thanks for the noticing!
