### ISSUE TITLE
apt update

### ISSUE THREAD

**Issue by MadCoder2601** [Botspot/pi-apps#716]
Some apps give me the following error when doing sudo apt update command

```
"Running pkg-install...
Waiting until APT locks are released... Done
Running sudo apt update...
Some packages can be upgraded. Please consider running sudo apt full-upgrade.
pkg-install failed to run sudo apt update!
APT reported these errors:
W: Target Packages (main/binary-armhf/Packages) is configured multiple times in /etc/apt/sources.list:4 and /etc/apt/sources.list:5
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list:4 and /etc/apt/sources.list:5
W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list:4 and /etc/apt/sources.list:5
W: Target Packages (main/binary-armhf/Packages) is configured multiple times in /etc/apt/sources.list:4 and /etc/apt/sources.list:5
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list:4 and /etc/apt/sources.list:5
W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list:4 and /etc/apt/sources.list:5

Failed to install Email Checker with install script!"
```

Can I have help fixing this?

**Comment by Itai-Nelken** [comment]
This isn't a pi-apps problem, your apt sources are messed up.

Can you run the following and comment the output please:
`cat /etc/apt/sources.list`
`ls /etc/apt/sources.list.d`

**Comment by MadCoder2601** [comment]
Output:

pi@raspberrypi:~ $ cat /etc/apt/sources.list
deb http://raspbian.raspberrypi.org/raspbian/ buster main contrib non-free rpi
# Uncomment line below then 'apt-get update' to enable 'apt-get source'
#deb-src http://raspbian.raspberrypi.org/raspbian/ buster main contrib non-free rpi
deb http://deb.debian.org/debian buster-backports main
deb http://deb.debian.org/debian buster-backports main
pi@raspberrypi:~ $ ls /etc/apt/sources.list.d
docker.list  raspi.list  vscode.list
pi@raspberrypi:~ $

**Comment by Itai-Nelken** [comment]
run `sudo mousepad /etc/apt/sources.list` and delete the last line (that will be a duplicated line, `
deb http://deb.debian.org/debian buster-backports main`, delete only the 2nd time it appears).
then run `sudo apt update`, if you don't get any errors the problem is fixed.

**Comment by MadCoder2601** [comment]
sudo apt update output:

Get:1 http://deb.debian.org/debian buster-backports InRelease [46.7 kB]
Hit:2 https://download.docker.com/linux/raspbian buster InRelease              
Hit:3 http://archive.raspberrypi.org/debian buster InRelease                   
Get:4 http://raspbian.raspberrypi.org/raspbian buster InRelease [15.0 kB]      
Hit:5 https://packages.microsoft.com/repos/code stable InRelease               
Fetched 61.7 kB in 2s (34.3 kB/s)                        
Reading package lists... Done
Building dependency tree       
Reading state information... Done
14 packages can be upgraded. Run 'apt list --upgradable' to see them.

Does This Mean That The Problem Is Fixed?

**Comment by MadCoder2601** [comment]
Thanks! The Issue Is Fixed!
