### ISSUE TITLE
eDex-UI not starting

### ISSUE THREAD

**Issue by Itai-Nelken** [Botspot/pi-apps#72]
I tried to run i from terminal and I got this error: 
pi@raspberrypi:~/eDEX-UI-RPi $ ./eDEX-UI_Linux_armv7l_2.2.2.AppImage 
fuse: device not found, try 'modprobe fuse' first

Cannot mount AppImage, please check your FUSE setup.
You might still be able to extract the contents of this AppImage 
if you run it with the --appimage-extract option. 
See https://github.com/AppImage/AppImageKit/wiki/FUSE 
for more information
open dir error: No such file or directory
pi@raspberrypi:~/eDEX-UI-RPi $

**Comment by Botspot** [comment]
`sudo mobprobe fuse`
After you run that, it should work.

**Comment by Itai-Nelken** [comment]
works, thanks! 
btw you typed `sudo **mobprobe** fuse` instead of `modprobe`

**Comment by Botspot** [comment]
> btw you typed `sudo **mobprobe** fuse` instead of `modprobe`

AARGH! haha, well at least you got it working.
