### ISSUE TITLE
please add more gui

### ISSUE THREAD

**Issue by marv-nerd** [Botspot/pi-apps#721]
i wish you could add more graphical user interface so it would look better, also, whens the version of minecraft with microsoft support going to release

**Comment by Itai-Nelken** [comment]
The minercrft with ms account support will release when its done.
what do you mean by more gui? the current gui covers everything I can think of. what do you want more?

**Comment by mobilegmYT** [comment]
1. It's not possible without rewriting the entire app to use another GUI, and yad+bash was cbksed for native support without any other programming language interpreters.

2. Soon, were looking for launchers to add lwjgl linking by default.

**Comment by marv-nerd** [comment]
what i mean is that i dont think it looks good if you make it look like file manager or something, im really good at english

**Comment by marv-nerd** [comment]
![2021-06-09-124841_1920x1080_scrot](https://user-images.githubusercontent.com/85557553/121295109-16e2d400-c921-11eb-95c0-78a8b2879418.png)
help

**Comment by Itai-Nelken** [comment]
@marv-nerd run `chmod +x ~/pi-apps/apps/ATLuncher/*` then try again

**Comment by mobilegmYT** [comment]
> what i mean is that i dont think it looks good if you make it look like file manager or something, im not really good at english

We can't change what it looks like using yad.
