### ISSUE TITLE
Snap store not installing

### ISSUE THREAD

**Issue by Astechlab** [Botspot/pi-apps#725]
![Screenshot_2021-06-10_14-47-40](https://user-images.githubusercontent.com/85675705/121499234-d2c40200-c9fa-11eb-9c47-bb115b640576.png)

**Comment by Botspot** [comment]
What operating system are you using?
Did you have _any_ snap-related stuff installed, prior to installing this?

**Comment by Itai-Nelken** [comment]
according to [here](https://unix.stackexchange.com/questions/308009/cant-delete-from-sd-card-read-only-file-system) that means that your filesystem is corrupted. you should backup your data and re flash the OS.

**Comment by Astechlab** [comment]
> What operating system are you using?
> Did you have _any_ snap-related stuff installed, prior to installing this?

Twister os

**Comment by Astechlab** [comment]
> according to [here](https://unix.stackexchange.com/questions/308009/cant-delete-from-sd-card-read-only-file-system) that means that your filesystem is corrupted. you should backup your data and re flash the OS.

but all other apps are installing

**Comment by Itai-Nelken** [comment]
Then maybe the permissions are messed up. A lot of the apps place files in your home folder, but the snap store also puts files in /snap. That may mean that your permissions are messed up. 

Could you create a vdeaktop vm with pi power tools, install pi-apps in the VM, and try to install the snap store? That way we will now if the problem is the script.

**Comment by stguen1** [comment]
I had a similar problem upon reinstalling snap store using PI Apps. The following message appeared. I don't know what to do to correct the situation. Any suggestions ? 
**"snap "core" is already installed, see 'snap help refresh'
error: cannot perform the following tasks:
- Mount snap "snap-store" (546) (snap "snap-store" assumes unsupported features: snapd2.43 (try to update snapd and refresh the core snap))
Unable to install snap store"**

**Comment by Itai-Nelken** [comment]
@stguen1 try running `sudo apt update && sudo apt upgrade` then `sudo snap refresh core`. then try installing the snap-store again.

**Comment by stguen1** [comment]
Thank you Itai-Nelken for your suggestion, which I tried. Unfortunately, I still cannot reinstall snap store. Pi Apps shows the application as corrupted. Any final suggestion ? 
P.S. A few weeks ago, I used BleachBit to clean-up my system. Could this have removed a file that has an effect on my ability to reinstall snap store ?

**Comment by Itai-Nelken** [comment]
@stguen1 maybe.
Could you try installing the snap store in a clean rpiOS image in vdesktop and see if it works?
Use Pi Power Tools

**Comment by Astechlab** [comment]
I have used this command for installing snap store 'sudo snap install snap-store'
