### ISSUE TITLE
Decentralized email

### ISSUE THREAD

**Issue by Dell-Glitch** [Botspot/pi-apps#726]
**https://github.com/DevanaLabs/lemon.email-dApp**

Is this app something many GUI users would find useful?
**Yes, like for privacy and security. It's decentralized so there is no main server so it's spread out across the globe and can't be tampered with because you sign the email with your digital signature and any copies would be deleted.**

Is this app installable with `sudo apt install`?
**No, That I know of**

**Comment by Itai-Nelken** [comment]
Have you tried running it on rpi?

**Comment by Dell-Glitch** [comment]
Well I tried and got error but I barely know how to use npm so I'm probably missing something or doing something wrong

**Comment by Botspot** [comment]
> Well I tried and got error but I barely know how to use npm so I'm probably missing something or doing something wrong

In that case, this issue will probably sit around dormant for a while or forever. I don't think the core pi-apps developers are in the position to lay groundwork for apps.

**Comment by citizensanction** [comment]
> Well I tried and got error but I barely know how to use npm so I'm probably missing something or doing something wrong

You do realize that npm refers to Node Package Manager.. therefore it cannot be installed with sudo apt install... you can instlal it using the command npm install -g but the requirement is that you must have node.js installed on your device. that comes bundled with NPM node package manager

**Comment by mobilegmYT** [comment]
> > Well I tried and got error but I barely know how to use npm so I'm probably missing something or doing something wrong
> 
> You do realize that npm refers to Node Package Manager.. therefore it cannot be installed with sudo apt install... you can instlal it using the command npm install -g but the requirement is that you must have node.js installed on your device. that comes bundled with NPM node package manager

node.js is in pi-apps

**Comment by Dell-Glitch** [comment]
> node.js is in pi-apps

One time I tried installing node.js in pi-apps but it failed to install

**Comment by Botspot** [comment]
> > node.js is in pi-apps
> 
> One time I tried installing node.js in pi-apps but it failed to install so idk if it would work again?

I just re-did the Node.js app, basically from scratch because it had so many problems. This was in commit e9de2f14c2b306a526fc25a81cf95ebad5054e3e.
@Dell-Glitch, would you be able to try installing node.js again?

**Comment by Botspot** [comment]
When I read this, I feel as though not that many Pi-Apps users would go to the effort to ask for some cryptocurrency in order to use an app.
![2021-07-10-204437_1366x768_scrot](https://user-images.githubusercontent.com/54716352/125180447-d98f9180-e1bf-11eb-8a64-817b2a812715.png)
Did I misunderstand [their readme](https://github.com/DevanaLabs/lemon.email-dApp/blob/master/README.md)?

**Comment by Dell-Glitch** [comment]
> Did I misunderstand their readme?

Nope... and Node.js installed successfully

**Comment by Botspot** [comment]
> and Node.js installed successfully

Good!

> > Did I misunderstand their readme?
> 
> Nope...

What a shame. As long as this app requires you to obtain some cryptocurrency to use it, I don't see how very many people would succeed to get this working. Too many would give up in frustration to justify adding this to Pi-Apps.
