### ISSUE TITLE
error in installing 

### ISSUE THREAD

**Issue by picomputer** [Botspot/pi-apps#728]
![2021-06-13-182322_1920x1080_scrot](https://user-images.githubusercontent.com/85831246/121808156-e67a9d00-cc74-11eb-8ec5-f54ca7c1369a.png)

**Comment by picomputer** [comment]
please help

**Comment by slashtechno** [comment]
@picomputer try doing `rm ~/youtubuddy` in terminal and reinstall.

**Comment by Itai-Nelken** [comment]
@picomputer uninstall youtubuddy and try again.

**Comment by Botspot** [comment]
@Itai-Nelken's advice is correct. Uninstall Youtubuddy, then try again.
