### ISSUE TITLE
nymea.io

### ISSUE THREAD

**Issue by simonseres** [Botspot/pi-apps#73]
Would be nice if you add our easy-to-use Smart Home Controller. :)
www.nymea.io
www.github.com/nymea/nymea

**Comment by Botspot** [comment]
I don't have the time to research your product for myself, so I'm going to ask you these questions and we'll see if this a good fir for Pi-Apps:

- Is this suitable for beginners who shy away from the command-line?
- Is it free?
- Is this something that many users would want, or is it for a tiny niche market?
- Pi-Apps is suited for people who use their RPi as an everyday desktop PC. Is your app intended to work on headless, embedded applications only?

Also, keep in mind that I (Botspot) can choose to break the above guidelines whenever I feel like it. So it really comes down to me.

Note that if I don't decide to add this app to the official repo, you could simply distribute your own app folder in the form of a ,zip file and have users extract it to `/home/pi/pi-apps/apps`.

**Comment by Botspot** [comment]
@simonseres Closing due to your inactivity.
