### ISSUE TITLE
file not installed on DietPi

### ISSUE THREAD

**Issue by TamaTamaGoGo** [Botspot/pi-apps#730]
Sorry for my weak English.
### Error at initializing on running

Using DietPi OS.
Can't use file command.

```
/root/pi-apps/api: line 15: file: command not found
/root/pi-apps/api: line 17: file: command not found
Failed to detect OS CPU architecture! Something is very wrong.
```

When I tried to run this command - `file "$(readlink -f "/sbin/init")"`, terminal returned that file command is unavailable.
So, I installed file by apt and I got this.
```
/lib/systemd/systemd: ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, BuildID[sha1]=18ce50ef03a7482735416b991ab1dd7a5fc93997, stripped
```

So, I suggest to install file command by apt at installing for the user who can't use file command.
Thank you.

**Comment by Itai-Nelken** [comment]
First of all DON'T install pi-apps as root.
`file` is included in most distributions, but I guess it won't hurt to make the install script check if it's installed.

**Comment by Botspot** [comment]
1. If you use the root account with pi-apps even once, some files may change ownership to root and this prevents you from using a unprivelaged account again. Also, be aware that Pi-Apps was never intended to be run as root, so if you encounter problems, you are on your own.
2. Pi-Apps has never been tested on DietPi OS. Expect problems.

As always, feel free to report problems. But on uncommon setups like this, you can expect to see errors.

Assuming DietPi is an `apt`-based OS, you can install the `file` command with `sudo apt install file`.
If DietPi is not an `apt`-based system, then Pi-Apps will not work at all.
