### ISSUE TITLE
Failed to install app

### ISSUE THREAD

**Issue by ElMaggus** [Botspot/pi-apps#731]
Good day.

When I want to download something,there is this error: Failed to install BlockPi with install 32 script. Of course it has something to do with the 32 and 64 system but I don't know what to.

**Comment by Itai-Nelken** [comment]
we need the full output to know what is wrong, 'Failed to install APP with install 32 script' means that you tried to install APP (BlockPi in your case) and that you are using a 32bit OS.
can you please send the full output when trying to install the app?

**Comment by ElMaggus** [comment]
![IMG_20210614_172154.jpg](https://user-images.githubusercontent.com/84408106/121917131-15584800-cd35-11eb-934c-1b00bd1fe225.jpg)

It's German... But one line says that problems can't get corrected. You have defect packages

**Comment by Itai-Nelken** [comment]
never mind, I used google translate. can you run in terminal `sudo apt update` and send the output please?

**Comment by ElMaggus** [comment]
OK: 1 http://deb.debian.org/debian buster-backports InRelease
OK: 2 http://ftp.debian.org/debian buster InRelease
OK: 3 http://ftp.debian.org/debian buster-updates InRelease
OK: 4 http://security.debian.org buster / updates InRelease
OK: 5 http://dl.google.com/linux/chrome/deb stable InRelease
OK: 6 http://archive.raspberrypi.org/debian buster InRelease
OK: 7 http://repository.spotify.com stable InRelease
OK: 8 https://download.docker.com/linux/debian buster InRelease
OK: 9 https://itai-nelken.github.io/weekly-box86-debs/debian InRelease
Package lists are being read ... Done
The dependency tree is built.
Status information is read in .... Done
All packages are up to date.
N: The loading of the configured file »stable / binary-i386 / Packages« is skipped because the depot »https://download.docker.com/linux/debian buster InRelease« does not support the architecture »i386«.

**Comment by Itai-Nelken** [comment]
Can you run `uname -m` please?

**Comment by ElMaggus** [comment]
X86_64

**Comment by Itai-Nelken** [comment]
Oh, you are not on a raspberry pi, right?

**Comment by ElMaggus** [comment]
I use an old laptop from 2010. But I installed Raspberry Pi on it. Now it works smooth. All applications work but the raspberry store seems to be not working because of 64bit I guess..

**Comment by ElMaggus** [comment]
> I use an old laptop from 2010. But I installed Raspberry Pi on it. Now it works smooth. All applications work but the raspberry store seems to be not working because of 64bit I guess.. 
The laptop was windows

**Comment by Itai-Nelken** [comment]
> > I use an old laptop from 2010. But I installed Raspberry Pi on it. Now it works smooth. All applications work but the raspberry store seems to be not working because of 64bit I guess.. 

The laptop was windows

**Comment by Itai-Nelken** [comment]
Then that is the problem. While you installed the rpi desktop, the laptop is still x64. Pi-Apps is made for arm only.
The error is pi-apps trying to install a arm deb on a x64 system.

**Comment by ElMaggus** [comment]
thx for your help. At the end it is not possible to do this? Any emulator who can run those apps? Greeting and have a good day.

**Comment by Itai-Nelken** [comment]
Most of the apps can run natively. What apps do you want to install?

**Comment by ElMaggus** [comment]
the basics like goggle chrome( dont know what chromium is)/ Spotify and Netflix

**Comment by Itai-Nelken** [comment]
chromium is the open source version of chrome made by google. to make chrome, google take the chromium source code and add their branding and stuff.
### to install Spotify:
**Add the official repository:**
```bash
curl -sS https://download.spotify.com/debian/pubkey_0D811D58.gpg | sudo apt-key add - 
echo "deb http://repository.spotify.com stable non-free" | sudo tee /etc/apt/sources.l
```
**Update the repository lists:**
```bash
sudo apt update
```
**Install spotify:**
```bash
sudo apt install spotify-client
```
### Chrome:
1) click on download on the google webpage for chrome: https://www.google.com/chrome/
2) open terminal and run `cd Downloads`
and
`sudo apt -f install *chrome*.deb`
if the line above doesn't work, run `sudo apt install <chrome.deb>` but replace `<chrome.deb> with the file that you downloaded in step 1.

I don't know if netflix has a desktop app, but you can watch netflix in chrome.
