### ISSUE TITLE
Modded minecraft pi

### ISSUE THREAD

**Issue by aaron-is-the-best2114** [Botspot/pi-apps#733]
Every time I open the Minecraft pi launcher and try to launch minecraft pi modded I get an error page and it says, "Minecraft pi edition has crashed! Exit Code 1"  any Ideas of how to fix it.  I installed pi-apps on a fresh install of raspberry pi os and a clean install of the modded version of minecraft.  Please help?

**Comment by mobilegmYT** [comment]
It is an issue with how the game is loaded. A patch will be pushed out within the next month to fix this.

**Comment by Botspot** [comment]
@aaron-is-the-best2114 Can you confirm that this minecraft issue was fixed for you?

**Comment by aaron-is-the-best2114** [comment]
Yes, the issue has been resolved for me.
