### ISSUE TITLE
Line Chat

### ISSUE THREAD

**Issue by AFOEK** [Botspot/pi-apps#735]
Can this app run on RPi? If so, please provide a link to a tutorial if applicable.
- From i know there can run on android and Ubuntu using wine. [Link](https://askubuntu.com/a/517944) Use the first walk around.

Is this app something many GUI users would find useful?
- Yes, especially ASIA user

Is this app installable with `sudo apt install`?
- emulate using wine -> I use Line on Ubuntu, I must install it using wine

**Comment by mobilegmYT** [comment]
@AFOEK I suggest trying using Wine/Box86 app on pi-apps to try and test if it works correctly.

**Comment by AFOEK** [comment]
> 
> 
> @AFOEK I suggest trying using Wine/Box86 app on pi-apps to try and test if it works correctly.

Ok I'll try it if i got any problem i i'll post it thanks

**Comment by AFOEK** [comment]
![image](https://user-images.githubusercontent.com/52521676/122707329-049f5900-d284-11eb-8787-b96a51116a78.png)
apparently it cannot run, it's just can install to my raspberry pi

**Comment by Botspot** [comment]
> apparently it cannot run

We can re-open this issue if someone can get it running.
