### ISSUE TITLE
minecraft java install fails

### ISSUE THREAD

**Issue by imyetihearmeroar** [Botspot/pi-apps#74]
Here is the error

Installing Minecraft Java with install-32 script
--2020-11-08 21:57:56--  https://www.dropbox.com/s/2602i5d0h4kteex/setupMC.sh
Resolving www.dropbox.com (www.dropbox.com)... 162.125.6.1, 2620:100:601c:1::a27d:601
Connecting to www.dropbox.com (www.dropbox.com)|162.125.6.1|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: /s/raw/2602i5d0h4kteex/setupMC.sh [following]
--2020-11-08 21:57:56--  https://www.dropbox.com/s/raw/2602i5d0h4kteex/setupMC.sh
Reusing existing connection to www.dropbox.com:443.
HTTP request sent, awaiting response... 404 Not Found
2020-11-08 21:57:56 ERROR 404: Not Found.

Failed to install the launcher!

**Comment by mobilegmYT** [comment]
@imyetihearmeroar About that... the script host went down recently. As all the install stuff is made by another individual, I have no control over it. Until it is fixed, I cannot do anything about this.

**Comment by mikehooper** [comment]
Thats my script. My Dropbox got blocked due to too many downloads. Moved to GitHub https://github.com/mikehooper/Minecraft/raw/main/setupMC.sh

**Comment by imyetihearmeroar** [comment]
> https://github.com/mikehooper/Minecraft/raw/main/setupMC.sh

what do I do with this link? do I just run the script in it? Im not very good with linux, sorry.

**Comment by mobilegmYT** [comment]
If I could,I would PR the new link in but botspot hasn't been online in a few days.

**Comment by Botspot** [comment]
> botspot hasn't been online in a few days.

Yeah, sorry. I'm back now. Feel free to open a PR.

**Comment by Botspot** [comment]
It should work now, as of commit 876829e1e6950f5eaa3300ae5be9074c3bc87f84.
