### ISSUE TITLE
Box64 + Lunar Client

### ISSUE THREAD

**Issue by Pythonic456** [Botspot/pi-apps#741]
When Box64 is released (and I am not expecting it to be any time soon), I suppose it will be added to Pi-Apps.
But my question (as I do not know where else to ask this yet) is will Lunar Client have a chance of running with box64?
Maybe @ptitSeb will be able to answer this.

Thanks in advance!

**Comment by chunky-milk** [comment]
@Pythonic456 try this. https://github.com/gl91306/lunar

**Comment by Botspot** [comment]
If this question is directed at @ptitseb on box86, then maybe it would be better if the question was asked on [the box86 repository](https://github.com/ptitSeb/box86).
