### ISSUE TITLE
Hyper

### ISSUE THREAD

**Issue by slashtechno** [Botspot/pi-apps#744]
[Hyper](https://hyper.is/) is an electron based terminal. It can run on Linux but doe not seem to be able to run on the Raspberry Pi.
 
I think users who use the CLI will find this app useful. 

The Github repo is [here](https://github.com/vercel/hyper/tree/3.0.2)

**Comment by Itai-Nelken** [comment]
I tried to compile it, but it failed

**Comment by Botspot** [comment]
My current progress on armhf:

Install Yarn:
```
npm install --global yarn
```
Install dependencies: (In a pi-apps script we'd use `pkg-install`)
```
sudo apt install graphicsmagick icnsutils xz-utils
```
Install:
```
git clone https://github.com/vercel/hyper
cd hyper
yarn
yarn run dist
```

**Comment by Botspot** [comment]
`yarn run dist` failed.
Furthermore, I was unable to run `yarn run app` successfully, until I ran [this fix](https://github.com/vercel/hyper/#error-building-node-pty). After that, Hyper successfully launched.

Now I'm trying to build it again.

**Comment by slashtechno** [comment]
I ran it successfully, however, the `hyper` command does not seem to work.

**Comment by Botspot** [comment]
> I ran it successfully

@slashtechno, did you get it to install successfully?

**Comment by slashtechno** [comment]
> > I ran it successfully
> 
> @slashtechno, did you get it to install successfully?

Yes, but the `hyper` command (used to install plugins and themes) does not work

**Comment by Itai-Nelken** [comment]
probably because the app isn't installed yet, `yarn run dist` should produce binaries in dist/, check there.

**Comment by Botspot** [comment]
> probably because the app isn't installed yet, `yarn run dist` should produce binaries in dist/, check there.

Has anyone gotten `yarn run dist` to succeed? I haven't.

**Comment by slashtechno** [comment]
@Botspot For me, only `yarn run app` works.

**Comment by Gowtham2003** [comment]
I have Successfully Compiled Hyper For Raspberry Pi 

I'll Submit the app to pi apps soon 😄

**Comment by Gowtham2003** [comment]
> I have Successfully Compiled Hyper For Raspberry Pi
> 
> I'll Submit the app to pi apps soon

After Compilation it worked fine , but when run hyper in freshly installed rpi os it's throwing error :sad:

**Comment by Gowtham2003** [comment]
> I have Successfully Compiled Hyper For Raspberry Pi
> 
> I'll Submit the app to pi apps soon

After Compilation it worked fine , but when run hyper in freshly installed rpi os it's throwing error :sad:

**Comment by oxmc** [comment]
@Gowtham2003 @Botspot @Itai-Nelken I got a successful build for armv7l.

**Comment by Gowtham2003** [comment]
> @Gowtham2003 @Botspot @Itai-Nelken I got a successful build for armv7l.
> 
> It's an appimage.

But did you tried executing appimage on fresh install ?

I compiled for both armv7l and arm64 it's working great but when i execute in fresh install it's throwing errors related to asar file 

I'll attach the error soon

**Comment by oxmc** [comment]
> > @Gowtham2003 @Botspot @Itai-Nelken I got a successful build for armv7l.
> > It's an appimage.
> 
> But did you tried executing appimage on fresh install ?
> 
> I compiled for both armv7l and arm64 it's working great but when i execute in fresh install it's throwing errors related to asar file
> 
> I'll attach the error soon

Oh? I have not had any error like that, and yes, i have tested it on a fresh rpios installation.

**Comment by Gowtham2003** [comment]
> > > @Gowtham2003 @Botspot @Itai-Nelken I got a successful build for armv7l.
> > > It's an appimage.
> > 
> > 
> > But did you tried executing appimage on fresh install ?
> > I compiled for both armv7l and arm64 it's working great but when i execute in fresh install it's throwing errors related to asar file
> > I'll attach the error soon
> 
> Oh? I have not had any error like that, and yes, i have tested it on a fresh rpios installation.

Can you provide the link to the appimage ? 

I'll test it once

**Comment by oxmc** [comment]
> > > > @Gowtham2003 @Botspot @Itai-Nelken I got a successful build for armv7l.
> > > > It's an appimage.
> > > 
> > > 
> > > But did you tried executing appimage on fresh install ?
> > > I compiled for both armv7l and arm64 it's working great but when i execute in fresh install it's throwing errors related to asar file
> > > I'll attach the error soon
> > 
> > 
> > Oh? I have not had any error like that, and yes, i have tested it on a fresh rpios installation.
> 
> Can you provide the link to the appimage ?
> 
> I'll test it once

Sure, let me upload it real quick.

**Comment by oxmc** [comment]
[AppImage download](http://os-detect.ml/Hyper-3.1.0-canary.6-armv7l.AppImage)

**Comment by slashtechno** [comment]
> [AppImage download](http://os-detect.ml/Hyper-3.1.0-canary.6-armv7l.AppImage)

I tried to run the appimage and it did launch Hyper, however, the `hyper` command does not work, the error I receive is:
`bash: hyper: command not found`

**Comment by Botspot** [comment]
> [AppImage download](http://os-detect.ml/Hyper-3.1.0-canary.6-armv7l.AppImage)

@oxmc, your download link does not seem to be working. :(

**Comment by slashtechno** [comment]
@Botspot Interesting, I downloaded it recently and the download link worked. Should I upload the file I downloaded?

**Comment by Botspot** [comment]
> @Botspot Interesting, I downloaded it recently and the download link worked. Should I upload the file I downloaded?

That would be great. Thank you.

**Comment by slashtechno** [comment]
> > @Botspot Interesting, I downloaded it recently and the download link worked. Should I upload the file I downloaded?
> 
> That would be great. Thank you.

Sorry, may not be able to upload the file at this moment, may have the opportunity later.

**Comment by slashtechno** [comment]
What is a good service I could use to host the file so I can upload to a Github issue?

**Comment by Botspot** [comment]
> What is a good service I could use to host the file so I can upload to a Github issue?

https://transfer.sh/

**Comment by slashtechno** [comment]
@Botspot Thanks
[Here](https://transfer.sh/njXQgC/Hyper-3.1.0-canary.6-armv7l.AppImage) is the link to the file.

**Comment by Jai-JAP** [comment]
https://github.com/vercel/hyper/pull/6370

**Comment by Crilum** [comment]
I made scripts to install Hyper, with armv7l from @Jai-JAP's repo, and arm64 from the offial repo. It works on my Raspberry Pi, but the builds aren't perfect yet, (https://github.com/vercel/hyper/pull/6370) so it probably shouldn't be added to Pi-Apps:
[Hyper.zip](https://github.com/Botspot/pi-apps/files/8248828/Hyper.zip)

**Comment by Jai-JAP** [comment]
Dont use arm64 from official repo its broken (see https://github.com/vercel/hyper/issues/6380)
I am gonna publish arm64 debs soon

**Comment by Jai-JAP** [comment]
> Wow, @Jai-JAP! clap
> 
> I made scripts to install Hyper, with armv7l from your repo, and arm64 from the offial repo.
> 
> It works on my Raspberry Pi, but the builds aren't perfect yet, ([vercel/hyper#6370](https://github.com/vercel/hyper/pull/6370)) so it probably shouldn't be added to Pi-Apps: [Hyper.zip](https://github.com/Botspot/pi-apps/files/8248828/Hyper.zip)
> 
> EDIT: Definitely don't add this yet! 32-bit works, but 64-bit is broken.

Posted the fixed arm64 deb here 
https://github.com/Jai-JAP/hyper-arm-builds/releases/download/v3.2.0/hyper_3.2.0_arm64.deb
Tested working on RPiOS buster and up

**Comment by Jai-JAP** [comment]
[Hyper.zip](https://github.com/Botspot/pi-apps/files/8322748/Hyper.zip)
Here's the new zip with the fixed arm64 build

**Comment by Jai-JAP** [comment]
Also we have to remove all other arches (x64, arm64) & add armv7l to arch in electron-buulder.yml

**Comment by LabhanshAgrawal** [comment]
@Botspot I've fixed the arm64 builds and added armv7l to Hyper. You can check out the recent release https://github.com/vercel/hyper/releases/tag/v4.0.0-canary.4
It's a canary release, there's still some time for v4. Maybe you can use it till then.
