### ISSUE TITLE
Winetricks failed to run

### ISSUE THREAD

**Issue by AFOEK** [Botspot/pi-apps#748]
I try to install Line apps using wine but I got these error :
![image](https://user-images.githubusercontent.com/52521676/122706273-c012be00-d281-11eb-9046-65a7566d2cfe.png)
any fixes or suggestion ? btw I'm not familiar with Box86

**Comment by mobilegmYT** [comment]
> I try to install Line apps using wine but I got these error :
> ![image](https://user-images.githubusercontent.com/52521676/122706273-c012be00-d281-11eb-9046-65a7566d2cfe.png)
> any fixes or suggestion ? btw I'm not familiar with Box86

This isn't on pi-apps yet so I suggest asking stuff in your original issue. Just put `BOX86_NOBANNER=1 ` in front of the winetricks command.

**Comment by AFOEK** [comment]
Thanks
