### ISSUE TITLE
quake 3

### ISSUE THREAD

**Issue by donnerkebab1730** [Botspot/pi-apps#749]
Can this app run on RPi? If so, please provide a link to a tutorial if applicable.

yes , https://pimylifeup.com/raspberry-pi-quake-3/

Is this app something many GUI users would find useful?

yes i think people would probably be intrested in downloading this

Is this app installable with `sudo apt install`?

yes

im not sure if it would be worth adding since its only a few terminal lines however it would make it easier for people using pi as a basic desktop and are unsure of how to use the terminal 

also as i dont know much about bash i can put all the commands here however i wont really be able to compile them to something that is very functional

**Comment by donnerkebab1730** [comment]
the commands to installing are:

sudo apt update
sudo apt full-upgrade
sudo apt install quake3
game-data-packager quake3 -i --gain-root-command sudo

as i was saying its very basic.

or you can get q3 lite:

sudo apt update
sudo apt full-upgrade
sudo apt install git libasound2-dev libudev-dev libibus-1.0-dev libevdev-dev libdbus-1-dev libcurl4-openssl-dev fcitx-libs-dev libgbm-dev libsamplerate0-dev xinput
git clone https://github.com/cdev-tux/q3lite.git
cd ~/q3lite
sudo ./make-raspberrypi.sh
sudo ./make-raspberrypi.sh install
ls -l /usr/local/games/quake3/baseq3/

i have not tested q3 lite however it is optimized for pi

**Comment by donnerkebab1730** [comment]
please note these are not my bash scripts (if you could call them that even) and are taken from the tutorial above i just think it would be a good app for pi apps, please also note that i am a beginner at making bash scripts and still learning so i probably wont be able to compile these into bash scripts and make them fully ready for pi apps.

**Comment by Itai-Nelken** [comment]
Quake 3 probably can't be in pi-apps as its in apt, bu I'll wait for @Botspot to make the decision.
About q3 lite I think it can be added especially as its optimized for the pi.

**Comment by donnerkebab1730** [comment]
> Quake 3 probably can't be in pi-apps as its in apt, but I'll wait for @Botspot to make the decision.
> About q3 lite I think it can be added especially as its optimized for the pi.


i was just about to say that as i found the eligibility post.....

**Comment by donnerkebab1730** [comment]
just checked and you can distribute under their license (https://github.com/cdev-tux/q3lite/blob/dev/COPYING.txt)

**Comment by Itai-Nelken** [comment]
@Botspot what do you say?

**Comment by donnerkebab1730** [comment]
I checked and the install appears to not be functional for some reason I'll keep working on it though

**Comment by Botspot** [comment]
> just checked and you can distribute under their license (https://github.com/cdev-tux/q3lite/blob/dev/COPYING.txt)

Now is a good time to remind everyone here that Pi-Apps does not distribute software. Instead, Pi-Apps is a collection of bash scripts that tell your computer to download things from elsewhere. Think of it as an automation tool - it installs things on your behalf so you don't have to follow a tutorial. In a way, Pi-Apps is just a bunch of RPi tutorials, but with a "run" button!

Quake 3 is disqualified from being added to Pi-Apps because it's on the official RPi repositories.
Q3lite sounds interesting. @donnerkebab1730, how many people do you think would be interested in a lite version instead of the original? Does the normal Quake 3 run with poor framerate?

**Comment by donnerkebab1730** [comment]
@Botspot Quake 3 lite is an optimized version that allows you to have better server software for hosting and other things, however when I resently reinstalled it it wasn't working but I'm unsure if that's my pi being bad as it normally is but I'll have to keep trying to get it working

**Comment by Botspot** [comment]
> but I'll have to keep trying to get it working

Interesting. As long as this is free and self-contained (not requiring you to obtain game files from somewhere), I am interested in adding this to Pi-Apps.

**Comment by donnerkebab1730** [comment]
That's the weird bit, it worked before without external stuff and then, for some reason it doesn't now

**Comment by donnerkebab1730** [comment]
I'm gonna close this because I think it is not going to work anymore.

**Comment by donnerkebab1730** [comment]
I'll try if I can get it to work.
