### ISSUE TITLE
Latest WINE version

### ISSUE THREAD

**Issue by Pythonic456** [Botspot/pi-apps#750]
Build the latest wine version with this: https://github.com/ptitSeb/box86/blob/master/docs/X86WINE.md and https://dl.winehq.org/wine-builds/debian/dists/buster/main/binary-i386/wine-stable_6.0.1~buster-1_i386.deb

It would replace the old WINE version when you install it.
Installing the old WINE version would uninstall the latest one and install the old one.
They replace each other when you install them.

Thanks!

**Comment by Itai-Nelken** [comment]
there is also this: https://github.com/Kron4ek/Wine-Builds
I think that something like the 'downgrade chromium' selection UI can be used to select the version you want.

**Comment by Itai-Nelken** [comment]
what do you say @Botspot?

**Comment by derryktutt** [comment]
seems good, would like wine 7.0

**Comment by Pythonic456** [comment]
+1

**Comment by Painadath** [comment]
> there is also this: https://github.com/Kron4ek/Wine-Builds I think that something like the 'downgrade chromium' selection UI can be used to select the version you want.

i am trying it

**Comment by theofficialgman** [comment]
closing in favor of https://github.com/Botspot/pi-apps/issues/2160
a meta-issue for tracking any/all apps that really need updating in pi-apps
