### ISSUE TITLE
Rpi686

### ISSUE THREAD

**Issue by Pythonic456** [Botspot/pi-apps#751]
https://github.com/SkywalkerSW5/Rpi686/wiki/How-to-download-Rpi686-3.0-BETA-1

I do not know a lot about this yet, seems to be a neat tool to run chroots.
I personally would use it a lot.

Thanks!

**Comment by Itai-Nelken** [comment]
rpi686 is disconinued: https://github.com/SkywalkerSW5/Rpi686#rpi686-is-discontinued

**Comment by Botspot** [comment]
I like the idea of RPi686 abd would gladly add it, but someone needs to maintain it.

Interestingly, RPi686's maker [claimed](https://www.raspberrypi.org/forums/viewtopic.php?f=63&t=251107&p=1532973&hilit=virtualbox#p1532973) that he was able to run x86 Virtualbox on it!
I asked the author why he discontinued rpi686, and [this](https://github.com/SkywalkerSW5/Rpi686/issues/4) was his answer.
