### ISSUE TITLE
Failure to get Deb.zip

### ISSUE THREAD

**Issue by MrTKusa** [Botspot/pi-apps#754]

**Comment by MrTKusa** [comment]
Installing Minecraft Pi (Modded) with install script
Docker is installed at /usr/bin/docker
Warning: wildcards not supported in HTTP.
--2021-06-22 07:20:09--  https://jenkins.thebrokenrail.com/job/minecraft-pi-reborn/job/master/lastSuccessfulBuild/artifact/out/deb/*zip*/deb.zip
Resolving jenkins.thebrokenrail.com (jenkins.thebrokenrail.com)... 68.43.64.50, 2601:40a:8280:ce20::1
Connecting to jenkins.thebrokenrail.com (jenkins.thebrokenrail.com)|68.43.64.50|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-06-22 07:20:09 ERROR 404: Not Found.

Unable To Download deb.zip! Check your internet connection and try again.

Failed to install Minecraft Pi (Modded) with install script!
\u25b2 Need help? Copy the above error output or take a screenshot.
Please ask on Github: https://github.com/Botspot/pi-apps/issues/new/choose
Or on Discord: https://discord.gg/RXSTvaUvuu

Close this window to exit.

**Comment by Itai-Nelken** [comment]
Update pi-apps and try again.

**Comment by Itai-Nelken** [comment]
This was fixed in #683
