### ISSUE TITLE
Pi apps using install-64 script on Raspberry pi os (32 bit)

### ISSUE THREAD

**Issue by ghost** [Botspot/pi-apps#760]
Pi apps using install-64 when i tried to install balena etcher or anything else ,fix this!

**Comment by Itai-Nelken** [comment]
Can you run `uname -m` in terminal and send the output please?
That will tell us if your kernel is 32 or 64bit.

**Comment by JeromTWin10Lyt** [comment]
The kernel is 32-bit

**Comment by Itai-Nelken** [comment]
the person asking deleted his account, so I'm closing this issue.
I have a suspect that its spam.

**Comment by Botspot** [comment]
> The kernel is 32-bit

That's simply not possible.
