### ISSUE TITLE
cura

### ISSUE THREAD

**Issue by Zeek2103** [Botspot/pi-apps#764]
Installing PrusaSlicer with install-32 script
Running pkg-install...
Waiting until APT locks are released... Done
Running sudo apt update...
pkg-install failed to run sudo apt update!
APT reported these errors:
E: Unable to parse package file /var/lib/apt/lists/partial/mcpirevival.tk_mcpi-packages_dists_buster_Release (1)

Failed to install PrusaSlicer with install-32 script!
\u25b2 Need help? Copy the above error output or take a screenshot.
Please ask on Github: https://github.com/Botspot/pi-apps/issues/new/choose
Or on Discord: https://discord.gg/RXSTvaUvuu

Close this window to exit.

**Comment by mobilegmYT** [comment]
> Installing PrusaSlicer with install-32 script
> Running pkg-install...
> Waiting until APT locks are released... Done
> Running sudo apt update...
> pkg-install failed to run sudo apt update!
> APT reported these errors:
> E: Unable to parse package file /var/lib/apt/lists/partial/mcpirevival.tk_mcpi-packages_dists_buster_Release (1)
> 
> Failed to install PrusaSlicer with install-32 script!
> \u25b2 Need help? Copy the above error output or take a screenshot.
> Please ask on Github: https://github.com/Botspot/pi-apps/issues/new/choose
> Or on Discord: https://discord.gg/RXSTvaUvuu
> 
> Close this window to exit.

You can try uninstalling MCPI modded for now, you can reinstall it after you see it gets a update in pi-apps.

**Comment by Alvarito050506** [comment]
Sorry for the inconvenient, this should be fixed once #763 is merged.

**Comment by Alvarito050506** [comment]
This should be fixed now, you can try reinstalling both MCPI and Cura and it should work.

**Comment by Itai-Nelken** [comment]
Closing as #763 was merged
