### ISSUE TITLE
latest and official minecraft launcher

### ISSUE THREAD

**Issue by marv-nerd** [Botspot/pi-apps#766]
i wanted to get minecraft working with microsoft support, i followed the tutorials for https://github.com/Botspot/pi-apps/issues/483 but it didnt work, so can you plz use the linux .deb from official minecraft website and make it support arm cpu

**Comment by Itai-Nelken** [comment]
We aren't magicians.
If it hasn't been done yet, then its impossible or really hard.
@mobilegmYT is there even a small chance of running the official launcher on the pi?
>i followed the tutorials for #483 but it didnt work

@marv-nerd ask for help in that issue then, don't give up immediately.

**Comment by Itai-Nelken** [comment]
Closing because as far as I know its impossible to run the latest official launcher on the pi. if I'm wrong, I'll be happy to reopen.

**Comment by mobilegmYT** [comment]
No, mojang themselves need to support it. We should close the atlauncher
issue ATM and use the lunar launcher issue since that's the most
promising solution we have rn.
