### ISSUE TITLE
MCPI GPG error: NO_PUBKEY

### ISSUE THREAD

**Issue by MofumofuKii** [Botspot/pi-apps#767]
pkg-install failed to run sudo apt update!
APT reported these errors:
W: GPG error: https://mcpirevival.tk/mcpi-packages buster InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 1C9B63619855132D

**Comment by Itai-Nelken** [comment]
1) uninstall minecraft oi (modded)
2) update pi-apps
3) install whatever you are tryong to install again
you can install minecraft pi again.

**Comment by CleanMachine1** [comment]
You need to add the public key for the apt repo. And you should do it quick because otherwise you can't update your system at all since you will always get that flagged.

Your options are add the key, remove the minecraft or remove the apt repo entry


try running these commands to add the key

```

wget -q -O - https://mcpirevival.tk/mcpi-packages/KEY.gpg | sudo apt-key add -
echo "deb [trusted=yes] https://mcpirevival.tk/mcpi-packages ${SUITE} main" | sudo tee /etc/apt/sources.list.d/mcpi-revival.list
```

This will serve the public key requirement, and tell apt to use it

**Comment by CleanMachine1** [comment]
Also try to use more useful titles
@Itai-Nelken Change it to `GPG Error - No public key for minecraft`

**Comment by mobilegmYT** [comment]
> You need to add the public key for the apt repo. And you should do it quick because otherwise you can't update your system at all since you will always get that flagged.
> 
> Your options are add the key, remove the minecraft or remove the apt repo entry
> 
> try running these commands to add the key
> 
> ```
> 
> wget -q -O - https://mcpirevival.tk/mcpi-packages/KEY.gpg | sudo apt-key add -
> echo "deb [trusted=yes] https://mcpirevival.tk/mcpi-packages ${SUITE} main" | sudo tee /etc/apt/sources.list.d/mcpi-revival.list
> ```
> 
> This will serve the public key requirement, and tell apt to use it

We've removed the GPG to use something else. Reinstalling it from pi-apps will fix.

**Comment by CleanMachine1** [comment]
Whats being used then. I am sure I could research but asking since you know the answer will be easier

**Comment by mobilegmYT** [comment]
> Whats being used then. I am sure I could research but asking since you know the answer will be easier

I have no idea because the big brain devs worked on that section during the revamp.

**Comment by CleanMachine1** [comment]
Not using GPG just seems like a long winded way to do it, since from what I have seen, external repos normally just have GPG for verification of software

**Comment by mobilegmYT** [comment]
> Not using GPG just seems like a long winded way to do it, since from what I have seen, external repos normally just have GPG for verification of software

I think it still uses GPG but just a different way, IDK, don't ask me.

**Comment by CleanMachine1** [comment]
Well the install.sh script uses what I copied and pasted, so you might want to look into fixing it if it is using an outdated invalid method

**Comment by Itai-Nelken** [comment]
> Also try to use more useful titles
> @Itai-Nelken Change it to `GPG Error - No public key for minecraft`

I can't control that error, its from apt.

**Comment by Itai-Nelken** [comment]
Oh, never mind. I misunderstood

**Comment by mobilegmYT** [comment]
I think this can be closed since it got resolved in update.

**Comment by Itai-Nelken** [comment]
@MofumofuKii can you please confirm that it works for you now?

**Comment by MofumofuKii** [comment]
thank you!

**Comment by MofumofuKii** [comment]
So sorry I'm late.

**Comment by Itai-Nelken** [comment]
Thanks
