### ISSUE TITLE
Minecraft Java Worlds

### ISSUE THREAD

**Issue by That-Name-Is-Taken3** [Botspot/pi-apps#770]
Is there a way to import world files in Minecraft java? I can't find a way to do it but then again I am very bad with Linux.
Keep up the great work!

**Comment by mobilegmYT** [comment]
~/.minecraft/worlds or somewhere in the .minecraft folder

**Comment by That-Name-Is-Taken3** [comment]
Thanks!

**Comment by mobilegmYT** [comment]
Can you close issue if it's resolved? Thanks
