### ISSUE TITLE
TwisterOS web apps

### ISSUE THREAD

**Issue by aaron-is-the-best2114** [Botspot/pi-apps#771]
@Botspot I run Twister OS 2.0.0 on my raspberry pi 3 model b and there's this application where ther's a bunch of online games and multimedia software.  It's called Twister OS webapps, and thought it would be cool if I was able to download it on any linux operating system that run's on the raspberry pi.  I thought, hey why not put it on pi-apps for easy downloadability.  Herer is the original github page I built for it, https://github.com/aaron-is-the-best2114/Twister-OS-webapps , if you want to try it out you can download the zip file and it will be in your downloads folder or you can use the git clone command to put it into your home directory.  Is it okay to put it on pi-apps for easy use, if peopl don't have large enough SD cards to fit ther versions of Twister OS with Twister OS webapps.  I linked the zip file below for download.  I have taken care for everything, it has an install script for 32 and 64-bit operating systems and an uninstall script. 
[Twister-OS-Webapps.zip](https://github.com/Botspot/pi-apps/files/6742632/Twister-OS-Webapps.zip)

**Comment by fabianmendes** [comment]
What happened?
 ~V. Fabian T· Mendes C.

**Comment by Itai-Nelken** [comment]
Why did you close this issue @aaron-is-the-best2114?

**Comment by Botspot** [comment]
Most likely this issue was mistakenly closed. Reopening.

**Comment by Botspot** [comment]
> I thought, hey why not put it on pi-apps for easy downloadability. Herer is the original github page I built for it, https://github.com/aaron-is-the-best2114/Twister-OS-webapps

Here is the _true_ original github page for TwisterOS-webapps: https://github.com/phoenixbyrd/webapps

**Comment by Itai-Nelken** [comment]
as @phoenixbyrd didn't give permission to add this app (https://github.com/phoenixbyrd/webapps/issues/4#issuecomment-873392895), I'm closing this issue.
