### ISSUE TITLE
New app?

### ISSUE THREAD

**Issue by aaron-is-the-best2114** [Botspot/pi-apps#772]
@Botspot I run Twister OS 2.0.0 on my raspberry pi 3 model b and there's this application where ther's a bunch of online games and multimedia software. It's called Twister OS webapps, and thought it would be cool if I was able to download it on any linux operating system that run's on the raspberry pi. I thought, hey why not put it on pi-apps for easy downloadability. Herer is the original github page I built for it, https://github.com/aaron-is-the-best2114/Twister-OS-webapps , if you want to try it out you can download the zip file and it will be in your downloads folder or you can use the git clone command to put it into your home directory. Is it okay to put it on pi-apps for easy use, if peopl don't have large enough SD cards to fit ther versions of Twister OS with Twister OS webapps. I linked the zip file below for download. I have taken care for everything, it has an install script for 32 and 64-bit operating systems and an uninstall script.
[Twister-OS-Webapps.zip](https://github.com/Botspot/pi-apps/files/6742632/Twister-OS-Webapps.zip)

**Comment by mobilegmYT** [comment]
> @Botspot I run Twister OS 2.0.0 on my raspberry pi 3 model b and there's this application where ther's a bunch of online games and multimedia software. It's called Twister OS webapps, and thought it would be cool if I was able to download it on any linux operating system that run's on the raspberry pi. I thought, hey why not put it on pi-apps for easy downloadability. Herer is the original github page I built for it, https://github.com/aaron-is-the-best2114/Twister-OS-webapps , if you want to try it out you can download the zip file and it will be in your downloads folder or you can use the git clone command to put it into your home directory. Is it okay to put it on pi-apps for easy use, if peopl don't have large enough SD cards to fit ther versions of Twister OS with Twister OS webapps. I linked the zip file below for download. I have taken care for everything, it has an install script for 32 and 64-bit operating systems and an uninstall script.
> [Twister-OS-Webapps.zip](https://github.com/Botspot/pi-apps/files/6742632/Twister-OS-Webapps.zip)

Permission should first be received from the creator @phoenixbyrd. The app is Twister OS centric so it'll need some fixes to remove all the logos and text. IMO, the Web Apps app already exists so if someone needs a webapp they can use that.

**Comment by aaron-is-the-best2114** [comment]
I'll reopen this when I get full permission.
