### ISSUE TITLE
IGdm (Instagram DMs)

### ISSUE THREAD

**Issue by fabianmendes** [Botspot/pi-apps#777]
Would be possible to install it?

https://appimage.github.io/IGdm/

https://github.com/igdmapps/igdm/

(there is a ".zip", and I am wondering thanks to its source code may be able to install it on raspberry pi)

**Comment by techcoder20** [comment]
Install Node js from pi apps and try running these commands

```
git clone https://github.com/ifedapoolarewaju/igdm.git
cd igdm
npm install
npm start
```

**Comment by fabianmendes** [comment]
I got an error installing Node.js
```
Installing Node.js with install-32 script
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 13527  100 13527    0     0  43918      0 --:--:-- --:--:-- --:--:-- 43918
=> nvm is already installed in /home/pi/.config/nvm, trying to update using git
=> => Compressing and cleaning up git repository

=> nvm source string already in /home/pi/.bashrc
=> bash_completion source string already in /home/pi/.bashrc
=> Close and reopen your terminal to start using nvm or run the following to use it now:

export NVM_DIR="$HOME/.config/nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
sed: no se puede leer /home/pi/.nvm/nvm.sh: No existe el fichero o el directorio
/home/pi/pi-apps/apps/Node.js/install-32: l\u00ednea 32: nvm: orden no encontrada

```

**Comment by fabianmendes** [comment]
thanks @techcoder20 it worked! The only thing is that gets a lot of CPU or idk it's just kind of crazy. Did you test it as well?

**Comment by Botspot** [comment]
> thanks @techcoder20 it worked! The only thing is that gets a lot of CPU or idk it's just kind of crazy. Did you test it as well?

If "it worked", then why was this issue closed?

**Comment by fabianmendes** [comment]
Because seems to no be good enough to add it, did you test it? It worked
but gets down my raspberry pi - I mean, once it's running, all gets slow
and unusable, barely you can even move the mouse; seems to be unsuitable.
What do you think?
 ~V. Fabian T· Mendes C.

**Comment by Botspot** [comment]
> Because seems to no be good enough to add it, did you test it? It worked but gets down my raspberry pi - I mean, once it's running, all gets slow and unusable

Does that occur for you *before* logging in, or _after_?

**Comment by fabianmendes** [comment]
after loggin of course
 ~V. Fabian T· Mendes C.
