### ISSUE TITLE
update to install-64 for etcher

### ISSUE THREAD

**Issue by Itai-Nelken** [Botspot/pi-apps#78]
[BalenaEtcher.zip](https://github.com/Botspot/pi-apps/files/5512205/BalenaEtcher.zip)

issue: https://github.com/Itai-Nelken/Etcher-arm-32-64/issues/2
I compiled a bit newer version (v1.5.110) and it fixed the issue. I tested it on Ubuntu 20.10 on rpi and it worked great.

**Comment by Botspot** [comment]
Fixed with commit 9b8abea057fb975afbd0ce8fa76cade68312f4b4
