### ISSUE TITLE
The Discord App for my Rasberry Pi will not install.

### ISSUE THREAD

**Issue by MyPocketComputer** [Botspot/pi-apps#780]
The Discord App for my Rasberry Pi is for some reason a broken package and fails to install correctly, even after it's done it said that the errors can not be corrected I don't know if I have made a mistake. But I downloaded the app from Pi Apps. Please help if you can. Thank you.

**Comment by Itai-Nelken** [comment]
we need the full output of the script.
@Botspot added logs a few hours ago, so:
1) update pi-apps by running `echo u | ~/pi-apps/updater` in terminal
2) open pi-apps settings
3) click on the 'logs' option
4) click on the Discord install log
5) send its output here

**Comment by Itai-Nelken** [comment]
@MyPocketComputer ^

**Comment by Botspot** [comment]
Due to @MyPocketComputer's lack of response, we can only assume that this is working fine now.

@MyPocketComputer, if this is not the case, please reply back and we can re-open the issue.
