### ISSUE TITLE
FL Studio

### ISSUE THREAD

**Issue by JF5-RPi** [Botspot/pi-apps#782]
Can this app run on RPi? If so, please provide a link to a tutorial if applicable.
No
Is this app something many GUI users would find useful?
Yes
Is this app installable with `sudo apt install`?
No
If you've created a zip file for this app, upload it here.
N/A

**Comment by Itai-Nelken** [comment]
If this app cant run on the RPi, how can we add it?

**Comment by Itai-Nelken** [comment]
I don't think its even available for linux or windows x86 (then we can try to run it with box86+wine). as box64 doesn't fully support wine yet, I think this issue should be closed as even if we could run it with box64+wine it would perform really bad.

**Comment by gl91306** [comment]
its also a paid app

**Comment by Itai-Nelken** [comment]
I think this app doesn't qualify.

**Comment by Itai-Nelken** [comment]
what do you say @Botspot?

**Comment by Botspot** [comment]
> what do you say @Botspot?

We can reopen the issue if someone succeeds to get this working on a Pi.
