### ISSUE TITLE
Minecraft Pi Modded Install Fail

### ISSUE THREAD

**Issue by JF5-RPi** [Botspot/pi-apps#783]
![2021-07-04-080221_1024x600_scrot](https://user-images.githubusercontent.com/66373203/124389955-55f51280-dc9e-11eb-933e-93036dfd6709.png)
Image of issue

**Comment by mobilegmYT** [comment]
Wait for https://github.com/Botspot/pi-apps/pull/784 to be merged and
update pi-apps, then try installing it again.

>

**Comment by Itai-Nelken** [comment]
I merged #784.
@JF5-RPi Update pi-apps and try again.
If it still fails, (I'm pretty sure it will) send a screenshot of the problem again please.

**Comment by Itai-Nelken** [comment]
@JF5-RPi ^

**Comment by Botspot** [comment]
Due to @JF5-RPi's lack of response, we can only assume that this is working fine now.

@JF5-RPi, _**if this is not the case**_, please reply back and we can re-open the issue.
