### ISSUE TITLE
Minecraft: Pi edition installing in root

### ISSUE THREAD

**Issue by MeowPi** [Botspot/pi-apps#787]
I- I don't even know what to say. 
WHY ON EARTH WOULD IT SAVE IN ROOT!?

**Comment by Itai-Nelken** [comment]
did you install/run pi-apps as root? if yes that's the cause

**Comment by Itai-Nelken** [comment]
mcpi installs just fine for me

**Comment by MeowPi** [comment]
im not running pi-apps as root.

**Comment by Itai-Nelken** [comment]
can you send the output of the following command please:
```
echo $USER
echo $HOME
file ~/pi-apps
```

**Comment by mobilegmYT** [comment]
@MeowPi

**Comment by mobilegmYT** [comment]
Do you mean it saves the game itself in root? Like the game binary and libraries are stored in /opt? That's intended.

**Comment by Botspot** [comment]
Due to @MeowPi's lack of response, we can only assume that this is working fine now.

@MeowPi, if this is not the case, please reply back and we can re-open the issue.
