### ISSUE TITLE
unable to install Node.js

### ISSUE THREAD

**Issue by vardhan-cyber** [Botspot/pi-apps#789]
```
Installing Node.js with install-32 script
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 13527  100 13527    0     0   142k      0 --:--:-- --:--:-- --:--:--  142k
=> Downloading nvm from git to '/home/pi/.config/nvm'
=> Cloning into '/home/pi/.config/nvm'...
=> Compressing and cleaning up git repository

=> Appending nvm source string to /home/pi/.bashrc
=> Appending bash_completion source string to /home/pi/.bashrc
npm WARN npm npm does not support Node.js v10.24.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/
=> Close and reopen your terminal to start using nvm or run the following to use it now:

export NVM_DIR="$HOME/.config/nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
sed: can't read /home/pi/.nvm/nvm.sh: No such file or directory
/home/pi/pi-apps/apps/Node.js/install-32: line 32: nvm: command not found
```

it is showing like this

**Comment by Itai-Nelken** [comment]
This is a known issue, it will be fixed when #708 is merged.

**Comment by Itai-Nelken** [comment]
@vardhan-cyber update pi-apps and try again.
can you confirm it works after updating please?

**Comment by vardhan-cyber** [comment]
Installing Node.js with install script
=> nvm is already installed in /home/pi/.config/nvm, trying to update using
git
=> => Compressing and cleaning up git repository

=> nvm source string already in /home/pi/.bashrc
=> bash_completion source string already in /home/pi/.bashrc
npm WARN npm npm does not support Node.js v10.24.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6,
7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/
=> Close and reopen your terminal to start using nvm or run the following
to use it now:

export NVM_DIR="$HOME/.config/nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This
loads nvm bash_completion
/home/pi/pi-apps/apps/Node.js/install: line 15: nvm: command not found
failed to install node.js! trying again with different NVM_DIR...
/home/pi/pi-apps/apps/Node.js/install: line 15: nvm: command not found
Failed to install Node.js using nvm!

Failed to install Node.js with install script!
\u25b2 Need help? Copy the above error output or take a screenshot.
Please ask on Github: https://github.com/Botspot/pi-apps/issues/new/choose
Or on Discord: https://discord.gg/RXSTvaUvuu

Close this window to exit.



still i am unable to install

**Comment by Itai-Nelken** [comment]
I just tested the scri[t again and it works perfectly fine, this is really weird!

**Comment by Botspot** [comment]
I had the exact same problem, and more, when I tried to get Node.js working today. Two hours later, I had found four problematic edge cases and 5+ bugs in the Node.js scripts. [I fixed them all.](https://github.com/Botspot/pi-apps/commit/e9de2f14c2b306a526fc25a81cf95ebad5054e3e)

@vardhan-cyber, could you try installing Node.js again? Please uninstall it first to clear up two of the edge cases I mentioned above.

**Comment by Botspot** [comment]
Due to @vardhan-cyber's lack of response, we can only assume that this is working fine now.

@vardhan-cyber, if this is not the case, please reply back and we can re-open the issue.
