### ISSUE TITLE
Min Browser

### ISSUE THREAD

**Issue by chunky-milk** [Botspot/pi-apps#790]
https://minbrowser.org/

 A fast, minimal browser that protects your privacy.

[min.zip](https://github.com/Botspot/pi-apps/files/6777618/min.zip)

**Comment by slashtechno** [comment]
It seems it has a prebuilt release for ARM64 and [supports Raspberry Pi](https://github.com/minbrowser/min/tree/v1.20.0#building-binaries) as long as it is built from source.

**Comment by Itai-Nelken** [comment]
It's better to use `rm -f` when removing the deb, that way we don't get a error if it fails as it doesn't matter that much.
also why is `apt-get` being used to update, but `apt` to uninstall? just use `apt`, it's the same thing (I think it actually calls `apt-get`).
other than that, everything looks good to me.

**Comment by Botspot** [comment]
> other than that, everything looks good to me.

Same here. I like this browser. Its WebGL performance is about the same as the optimized RPi Chromium, and websites tend to load faster - about as fast as Vivaldi.
