### ISSUE TITLE
No Longer Installing

### ISSUE THREAD

**Issue by Zipperoos** [Botspot/pi-apps#791]
Hey, so I have been using piapps for a while now, never found any problems with the app. Then I was trying to install FreeCAD, and as luck would have it, the power cut. When I reconnected the power  and tried to install FreeCAD again, it gave me the error show in the screenshot. I tried installing something else; same error.
    It is really frustrating and I love piapps so PLEASE help me be able to use it again. I don't want to have to reset my pi with all the progress I've made on it.
    Thanks for seeing this! ~Zipperoos
![ERROR](https://user-images.githubusercontent.com/85034797/124836073-587e9300-df50-11eb-9186-a1dc3ab461ce.png)

**Comment by mobilegmYT** [comment]
> Hey, so I have been using piapps for a while now, never found any problems with the app. Then I was trying to install FreeCAD, and as luck would have it, the power cut. When I reconnected the power and tried to install FreeCAD again, it gave me the error show in the screenshot. I tried installing something else; same error.
> It is really frustrating and I love piapps so PLEASE help me be able to use it again. I don't want to have to reset my pi with all the progress I've made on it.
> Thanks for seeing this! ~Zipperoos
> ![ERROR](https://user-images.githubusercontent.com/85034797/124836073-587e9300-df50-11eb-9186-a1dc3ab461ce.png)

Try removing freecad and install it again.

**Comment by Zipperoos** [comment]
It happens when I hit "Uninstall" on any app too.

**Comment by mobilegmYT** [comment]
Hmm... try to remove freecab in apt or run sudo apt install -f?

**Comment by Botspot** [comment]
This problem was caused by your power outage.
The error "`E: The package freecad needs to be reinstalled, but I can't find an archive for it.`" seems to indicate your power outage occurred while the freecad package was being installed.

Try this:
`sudo apt purge freecad`

**Comment by Zipperoos** [comment]
ARRGGGGGG still nothing, same error msg EVERYTHING I do with apt

**Comment by Itai-Nelken** [comment]
Try this: https://www.programmersought.com/article/29105789912/

**Comment by Zipperoos** [comment]
OH MY GOSH TYSM!!!! I had to adapt them slightly for debian-based
Linux, but I entered the status file, deleted the entry for freecad
that said "half installed", and it WORKED!!!!!!
Thanks for your great support and perseverance!

**Comment by Itai-Nelken** [comment]
The instructions were dor debian, ubuntu more irnless is debian with extra repositories.
