### ISSUE TITLE
BlockBench

### ISSUE THREAD

**Issue by Zipperoos** [Botspot/pi-apps#792]
Hey, I am a avid Minecrafter, and I would like to be able to use BlockBench (https://blockbench.net/) on the pi, as the webapp is very slow on a pi. Could you please consider trying to figure this out? 
Thx! ~Zipperoos

**Comment by mobilegmYT** [comment]
> Hey, I am a avid Minecrafter, and I would like to be able to use BlockBench (https://blockbench.net/) on the pi, as the webapp is very slow on a pi. Could you please consider trying to figure this out?
> Thx! ~Zipperoos

According to https://github.com/JannisX11/blockbench if you install the nodeJS app on pi-apps you can run from source.

**Comment by chunky-milk** [comment]
I've compiled it into a deb, both for arm 32 and 64 bit.

32 bit: http://transfer.sh/w/Blockbench_3.9.2.deb
64 bit: https://transfer.sh/1OfPK3t/Blockbench_3.9.2.deb

**Comment by Zipperoos** [comment]
Thanks so much!
~Zipperoos

**Comment by chunky-milk** [comment]
> Thanks so much!
> ~Zipperoos

You're welcome. 
The only issue I had on RPiOS is that no program icon shows up.

**Comment by chunky-milk** [comment]
Also please note that the links I provided are only valid for 14 days so if you are creating scripts make sure to not use those links.

**Comment by Itai-Nelken** [comment]
is someone planning to write the scripts?

**Comment by Zipperoos** [comment]
Ummmm I mean I could try, but I have no clue how to upload the script
to Pi-Apps for everyone.
~Zipperoos

**Comment by Itai-Nelken** [comment]
make a zip archive and upload it here @Zipperoos.

**Comment by Zipperoos** [comment]
I see that all the scripts use some sort of online file storage
service to get the stuff from. What should I use for the .deb file?
(BTW someone else created the Deb I just am creating a script for it.)

**Comment by Itai-Nelken** [comment]
could you upload the deb and send it here please?

**Comment by Zipperoos** [comment]
Ok there we go I finally figured out the zip command lol here it is.

**Comment by Zipperoos** [comment]
Apparently I am a 13 year old **IDIOT** because it will _not_ upload the zip. I will send you a link to a GoogleDrive with it.

**Comment by Zipperoos** [comment]
[](https://drive.google.com/file/d/1by6FOQXBPAtTNYgutYIDAwfP3zUTr9Hp/view?usp=sharing)  Here it is.

**Comment by Zipperoos** [comment]
usp=sharing[https://drive.google.com/file/d/1by6FOQXBPAtTNYgutYIDAwfP3zUTr9Hp/view?usp=sharing](url)

**Comment by Itai-Nelken** [comment]
thanks! @chunky-milk can you upload it to your repo please?

**Comment by Botspot** [comment]
@ryanfortner, how is progress going?

**Comment by ryanfortner** [comment]
> @ryanfortner, how is progress going?

I'll upload debs to my repository later today. Sorry for the delay.

**Comment by Botspot** [comment]
> could I get someone to test this deb for me please?

Sure, I just tested it with vdesktop in a fresh arm64 image and it installed fine.
One thing I noticed: the menu launcher is in the "Other" category and doesn't have an icon. Can this be improved?
Also, when running, the program has no icon on the taskbar. This is Electron, so there should be a built-in way to do that.

**Comment by ryanfortner** [comment]
> Sure. I just tested your deb in a fresh arm64 image with [vdesktop](https://github.com/Botspot/vdesktop). The deb installed and ran fine. One thing I noticed: the menu launcher is in the "Other" category and doesn't have an icon. Can this be improved? Also, when running, the program has no icon on the taskbar. This is Electron, so there should be a built-in way to do that.

I should just be able to modify the .desktop file in the deb and repackage it. I'll get to work :)
