### ISSUE TITLE
PiApps installed FreeCAD 0.19 error 'Cannot load workbench'

### ISSUE THREAD

**Issue by gartlana** [Botspot/pi-apps#793]
Problem Scenario: 
PiApps Installed FreeCAD cannot load Workbench in new, pristine Twister-OS, PiApps & FreeCAD builds. To recreate simply create a new Twister build, use Pi-Apps to install FreeCAD and then attempt to invoke the Path workbench.

Diagnostics:
FreeCAD Message Box extract: "Cannot Load Workbench"

FreeCAD Report view window message:
```
"07:38:50  Traceback (most recent call last):
  File "<string>", line 1, in <module>
<class 'Base.FreeCADError'>: PathWorkbench: PythonCommand::getResource(): Method GetResources() of the Python command object returns a dictionary which holds not only strings"
```
Platform: 
Hardware Pi400, 
OS New/unaltered Twister OS 2.1.0 installed to micro-SD via Pi Imager and patch updated on 8th July 2021
Application(s): Pre-installed Pi-Apps and then Pi-Apps installed FreeCAD  0.19.

The supplied version of Java supplied with this build follows:
```
pi@raspberrypi:~ $ python
Python 2.7.16 (default, Oct 10 2019, 22:02:15) 
[GCC 8.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
```
N.B.: Hi, I'm new to Pi, Linux & FreeCAD but will do my best to report this bug and help with resolution and testing. 
I tried to compile FreeCAD from source using tips from http://scruss.com/blog/2020/02/16/freecad-on-raspberry-pi-4/ but the same bug occurred in new/separate/pristine builds for FreeCAD 0.19.1 and 0.19.2  on Twister-OS 2.1.0 (32 bit). 
My aim is to run Universal G-Code Sender (UGC) and FreeCAD on the Pi400 for a home CNC build. UGC can run on this platform. FreeCAD 0.18.4 can run on this platform (with workarounds).

**Comment by Botspot** [comment]
@gartlana, thank you for opening an issue on the Pi-Apps page. I can tell that you put some serious time and thought into this.

But I'm afraid I can't help you. This problem may be due to the fact that FreeCAD is still using Python2, or maybe this is a bug with Freecad, or with RPi.
Have you Googled that error and found anything? I found [this](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=237987), but think it's most likely unrelated.

**Comment by gartlana** [comment]
Thanks Botspot for your comments.
The older version you found a hit on works fine in these builds and the details differ as best I can determine (I am not C++ or Python or GITHUB literate at this stage really ... ).

I will try a FreeCAD specific path within GITHUB next based on your input thanks:)

Andrew
