### ISSUE TITLE
Box64

### ISSUE THREAD

**Issue by Tejas-Singh-py** [Botspot/pi-apps#794]
Hi @Botspot !

Looks like @ptitSeb has finally released box64.

I have created scripts for it, and it would be great if you can see them and check that they are correct
I haven't make a install-32 script because it makes no sense... 

Q. Is this app installable with `sudo apt install`?
Ans. Not Yet

If you've created a zip file for this app, upload it here.
[Box64.tar.gz](https://github.com/Botspot/pi-apps/files/6790442/Box64.tar.gz)

Unfortunately, for some reason I couldn't create a `.zip` so i hope `tar.gz` works for you

**Comment by Itai-Nelken** [comment]
why this line? `# Get dependencies
"${DIRECTORY}/pkg-install" "sudo systemctl restart systemd-binfmt" "$(dirname "$0")" || exit 1`
`pkg-install` is for installing dependencies. replace that line with `sudo systemctl restart systemd-binfmt`

how will this work (in the uninstall script): `sudo apt purge box64 -y || error "Failed to uninstall box64!"`? you didn't install box64 as a apt package, so doing this won't work.
the uninstall script should be something like this:
```
#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

cd ~/box64/build || error "Failed to enter ~/box64/build!"
sudo make uninstall || error "Failed to uninstall box64!"
cd "$HOME" || error "Failed to enter $HOME!"
rm -rf box64

```

**Comment by Tejas-Singh-py** [comment]
> why this line? `# Get dependencies "${DIRECTORY}/pkg-install" "sudo systemctl restart systemd-binfmt" "$(dirname "$0")" || exit 1`
> `pkg-install` is for installing dependencies. replace that line with `sudo systemctl restart systemd-binfmt`

@Itai-Nelken 
Oh! got it. I am gonna update it.

**Comment by Tejas-Singh-py** [comment]
Hi, @Itai-Nelken and @Botspot !
I have fixed the` scripts`
[Box64.tar.gz](https://github.com/Botspot/pi-apps/files/6794607/Box64.tar.gz)
You should check it out now


By The Way, should I open another issue, for this to be added to pi-apps

**Comment by Itai-Nelken** [comment]
no need to open a new issue or pr.
I improved the errors and split the cmake line to 3 different lines.
[Box64.tar.gz](https://github.com/Botspot/pi-apps/files/6794744/Box64.tar.gz)

**Comment by Botspot** [comment]
> Hi, @Itai-Nelken and @Botspot !
> I have fixed the` scripts`
> [Box64.tar.gz](https://github.com/Botspot/pi-apps/files/6794607/Box64.tar.gz)
> You should check it out now
> 
> By The Way, should I open another issue or do a PR, for this to be added to pi-apps

It is easiest to stick with this issue and to share zip files back and forth. When the app is ready, I'll upload it to Github, so no need for a pull request.

**Comment by Botspot** [comment]
Box64 has been added to Pi-Apps with commit 83fff45fddb02ba7891a325b37a8918efa01e6e4.
