### ISSUE TITLE
i am unable to get audio output from raspiberry pi 4

### ISSUE THREAD

**Issue by vardhan-cyber** [Botspot/pi-apps#795]
Can this app run on RPi? If so, please provide a link to a tutorial if applicable.

Is this app something many GUI users would find useful?

Is this app installable with `sudo apt install`?

If you've created a zip file for this app, upload it here.

**Comment by vardhan-cyber** [comment]
i am unable to get audio output from raspberry pi 4

**Comment by Itai-Nelken** [comment]
What app? Is this related to pi-apps?

**Comment by Botspot** [comment]
Closing this issue. The problem @vardhan-cyber is having, does not seem to be related to the Pi-Apps Raspberry Pi **app store**.

@vardhan-cyber, I suggest you ask for help for issues like this on [the Raspberry Pi official Forums](https://www.raspberrypi.org/forums/).

If this issue ***is*** related related to an app in Pi-Apps, we can re-open your issue.
