### ISSUE TITLE
Added GTA 3 & GTA VC

### ISSUE THREAD

**Issue by Jai-JAP** [Botspot/pi-apps#799]
Can this app run on RPi? If so, please provide a link to a tutorial if applicable.
Yes. https://github.com/laomingOfficial/RaspberryPi-re3
A quick google translate will translate to English

There are some errors in the tutorial scripts to it will not work Out-of-the-box

Is this app something many GUI users would find useful?
Yes. Who doesn't want to play GTA on RPi 

Is this app installable with `sudo apt install`?
No.

If you've created a zip file for this app, upload it here.
go to PR #798

**Comment by Jai-JAP** [comment]
I have compiled the re3 and reVC for both arm and arm64. They can be found [here](https://github.com/Jai-JAP/RPi-GTA-re) 

Note: This is only the engine. To play the game, you must provide/copy ALL the folders of your copy of the game inside the install path.
      Any kind of pirated gamedata is not supported.


Testers are welcome.

**Comment by Jai-JAP** [comment]
Has anyone tested this successfully

**Comment by Jai-JAP** [comment]
Anyone tested this?

**Comment by theofficialgman** [comment]
closing as I also closed the related PR
