### ISSUE TITLE
Opera

### ISSUE THREAD

**Issue by leha-code** [Botspot/pi-apps#802]
Can this app run on RPi? If so, please provide a link to a tutorial if applicable.
Nope it cant. But we might get it running with boxx86, i guess.... Opera does not make ARM releases

Is this app something many GUI users would find useful?
of course

Is this app installable with `sudo apt install`?
no
If you've created a zip file for this app, upload it here.

**Comment by chunky-milk** [comment]
Have you had any success running Opera with Box86 or Box64?

**Comment by Botspot** [comment]
#628

**Comment by leha-code** [comment]
I cannot try, my pies connector is broken
