### ISSUE TITLE
Box86 glibc_2.29 not found / required

### ISSUE THREAD

**Issue by Manolosun** [Botspot/pi-apps#803]
after installing box86 i become request that glibc_2.29 not found is required for box86.
if i download and compile box86 manually all is working. pls fix it.

**Comment by Itai-Nelken** [comment]
Known issue, I'll fix it as soon as I have time.

**Comment by Itai-Nelken** [comment]
@Manolosun if you run `sudo apt purge box86 -y; sudo apt update; sudo apt install box86 -y`

**Comment by Itai-Nelken** [comment]
The problem is fixed
