### ISSUE TITLE
error output for stunt rally

### ISSUE THREAD

**Issue by joshHoover279** [Botspot/pi-apps#808]
Failed to install Stunt Rally with install-64 script!

**Comment by Itai-Nelken** [comment]
Full output please

**Comment by Itai-Nelken** [comment]
@joshHoover279 ^

**Comment by Botspot** [comment]
Due to @joshHoover279's lack of response, we can only assume that this is working fine now.

@joshHoover279, if this is not the case, please reply back and we can re-open the issue.
