### ISSUE TITLE
VSCode Server

### ISSUE THREAD

**Issue by ryanfortner** [Botspot/pi-apps#809]
VSCode in a browser!

I'll create scripts later, here is the project repository..,

https://github.com/cdr/code-server

**Comment by Botspot** [comment]
> VSCode in a browser!

What advantages does this have over an offline, local installation?

**Comment by chunky-milk** [comment]
> What advantages does this have over an offline, local installation?

Since it's accessible via a web browser you can access it anywhere, without having local access. It has all the features of VSCode.

**Comment by open-sorcerer64** [comment]
> > What advantages does this have over an offline, local installation?
> 
> Since it's accessible via a web browser you can access it anywhere, without having local access. It has all the features of VSCode.

can't you do it with replit?

**Comment by chunky-milk** [comment]
> can't you do it with replit?

Yes, and you can also self-host it.

**Comment by Botspot** [comment]
> > can't you do it with replit?
> 
> Yes, you can host it using Heroku, Linode, AWS, and many other cloud providers, or using your own hardware.

Pi-Apps is intended for people who use their Raspberry Pies as a desktop PC. I'm not sure how adding a web-server for a certain type of software would benefit many people.
From my understanding, VSCode Server only makes sense, if your Pi is the server and another computer is the client. Ignoring the question of "Why not just run VSCode directly on the other computer?", we still have to face the fact that in this usage scenario, the Pi would not be used as a Desktop PC, but as a headless machine.

And if you're messing with headless machines, it makes more sense to do the installation from the terminal, than from a graphical app-store.
Perhaps it would be better to add a note to VSCode's description, saying that you can make your Pi the server, with a link pointing to the relevant repository.

**Comment by open-sorcerer64** [comment]
This makes less sense after GitHub Codespaces

**Comment by ryanfortner** [comment]
> Pi-Apps is intended for people who use their Raspberry Pies as a desktop PC. I'm not sure how adding a web-server for a certain type of software would benefit many people. From my understanding, VSCode Server only makes sense, if your Pi is the server and another computer is the client. Ignoring the question of "Why not just run VSCode directly on the other computer?", we still have to face the fact that in this usage scenario, the Pi would not be used as a Desktop PC, but as a headless machine.

Yeah, that does make sense, especially because on headless machines people most likely won't be using Pi-apps...

> And if you're messing with headless machines, it makes more sense to do the installation from the terminal, than from a graphical app-store. Perhaps it would be better to add a note to VSCode's description, saying that you can make your Pi the server, with a link pointing to the relevant repository.

I'm alright with not adding it. Just a suggestion though: maybe create a category for headless server applications, such as webservers and file servers? I'm sure this will benefit many people.

**Comment by theofficialgman** [comment]
I think this can be closed. Official support for vs-code in the browser already exists and is here -> <https://vscode.dev/>

I this pi-apps should be for software that people want to run on a pi, code-server would only be useful running on another system (think about a more powerful headless server you would run it on) which you would then remotely access via your pi.
