### ISSUE TITLE
Pls add Kdelvine or any video editor to pi-apps

### ISSUE THREAD

**Issue by CoderLogy** [Botspot/pi-apps#812]

**Comment by Itai-Nelken** [comment]
Kdenlive is in apt

**Comment by Tejas-Singh-py** [comment]
Okay, making scripts but I am not sure if @Botspot will add them to Pi-Apps. BTW @Itai-Nelken is correct all video editors that can run on the Pi are present in apt repo

**Comment by Itai-Nelken** [comment]
Mist of them.
Anyway apps that are on apt aren't allowed unless its a newer version that is way better.

**Comment by CoderLogy** [comment]
so pls add it to pi-apps as we need a minimum of one video editor for pi-apps

**Comment by Itai-Nelken** [comment]
kdenlive isn't allowed as its in APT.
@CoderLogy if you find a video editor that runs well on the pi and isn't in APT, we can add it.
flowblade is a nice video editor that runs well on the pi and is in APT: `sudo apt install flowblade`.
closing this issue for now.

**Comment by Rak1ta** [comment]
@Botspot From what I understand, you are now adding applications from the package manager.
[Kdelvine.zip](https://github.com/Botspot/pi-apps/files/8784704/Kdelvine.zip)
