### ISSUE TITLE
Pls add laverna or simple note to pi

### ISSUE THREAD

**Issue by CoderLogy** [Botspot/pi-apps#815]

**Comment by Itai-Nelken** [comment]
for simplenote see #88 and #418.
for laverna: is it available for arm linux?

**Comment by CoderLogy** [comment]
For Laverna we can use box86 to convert windows to work on arm or wine 86 but add it

**Comment by Itai-Nelken** [comment]
Can you try running it with Box86 b and wine?

**Comment by CoderLogy** [comment]
I have rpi 3A+ with only running 328mb of ram so u can think I cannot do
right now any emulation on that even when I run chromium my pi stops and
also it cannot run youtube without cloud browser
