### ISSUE TITLE
Balena-etcher-electron blank 

### ISSUE THREAD

**Issue by akhilleusuggo** [Botspot/pi-apps#817]
Hello,

After updating the balena-etcher-electron stopped working. All I'm getting is a blank window

![image](https://user-images.githubusercontent.com/52116577/126374879-8936212d-7339-461f-84b6-f837801bc852.png)

By terminal; Same result, no logs. Where can I check the logs ?

```
~ $ /opt/balenaEtcher/balena-etcher-electron
ready-to-show: 1.036s
```

**Comment by chunky-milk** [comment]
Also what is your system's architecture? (32 or 64 bit)

**Comment by akhilleusuggo** [comment]
@Itai-Nelken I can't even open it to flash anything or try to do anything. The screen you see is what I get when I execute the software.
@chunky-milk 
```
~ $ uname -a
Linux raspberrypi 5.10.17-v8+ #1421 SMP PREEMPT Thu May 27 14:01:37 BST 2021 aarch64 GNU/Linux
```

**Comment by chunky-milk** [comment]
I'll try to recompile it in a bit

**Comment by akhilleusuggo** [comment]
The only thing I can say during the install is 

`chmod: cannot access '/opt/balena-etcher-electron/chrome-sandbox': No such file or directory`

**Comment by Itai-Nelken** [comment]
That is a known electron issue. It doesn't affect anything though

**Comment by akhilleusuggo** [comment]
Just to close this issue. Does the Balena-etcher works for you ?

**Comment by chunky-milk** [comment]
Works perfectly fine for me.

**Comment by akhilleusuggo** [comment]
@chunky-milk countless times reinstalled, and about terminal, already posted;

> By terminal; Same result, no logs. Where can I check the logs ?
~ $ /opt/balenaEtcher/balena-etcher-electron
ready-to-show: 1.036s

**Comment by Rak1ta** [comment]
@chunky-milk I have a similar problem with a white screen. Installing a previous version fixes the error.
https://github.com/Botspot/pi-apps/pull/806/commits/f91a9c746e03496f6f9e5924db6210c567181a9e

**Comment by Botspot** [comment]
> @chunky-milk I have a similar problem with a white screen. Installing a previous version fixes the error.
> [f91a9c7](https://github.com/Botspot/pi-apps/commit/f91a9c746e03496f6f9e5924db6210c567181a9e)

That's an interesting data point.
To everyone who is having trouble with balenaEtcher, could you send me your system configuration by running this command?
```
~/pi-apps/api get_device_info
```

**Comment by Rak1ta** [comment]
@Botspot 

> pi@raspberrypi:~ $ ~/pi-apps/api get_device_info
> OS: Raspbian GNU/Linux 10 (buster)
> OS architecture: 32-bit
> Kernel: armv7l 5.10.52-v7l+
> Device model: Raspberry Pi 4 Model B Rev 1.2
> Raspberry Pi OS image version: 2021-05-07
> Language: ru_RU.UTF-8
> Pi-Apps gui script datestamp: \u0421\u0440 \u0430\u0432\u0433 11 21:22:28 MSK 2021

**Comment by Botspot** [comment]
Today I reinstalled balenaEtcher and I was able to reproduce the problem. Because of this, the BalenaEtcher app has been downgraded to v1.5.120 with commit 5f736d39fdaf9e261516f5a670165d1fbe728bd6.

**Comment by chunky-milk** [comment]
I'll work on re-compiling it next time I get the chance.

**Comment by chunky-milk** [comment]
Could I get someone to test this deb please?

I haven't gotten the chance to compile it for arm64 yet, but here are the armhf binaries

https://github.com/Itai-Nelken/Etcher-arm-32-64/releases/tag/v1.5.121

**Comment by Rak1ta** [comment]
@chunky-milk `balena-etcher-electron_1.5.121+8b3f3710_armv7l.deb` starts correctly

**Comment by chunky-milk** [comment]
> @chunky-milk `balena-etcher-electron_1.5.121+8b3f3710_armv7l.deb` starts correctly.

Great, I'll let you know when I compile arm64
