### ISSUE TITLE
Adding support to install apps in termux

### ISSUE THREAD

**Issue by DevAgentA** [Botspot/pi-apps#820]
Is it possible to install this on termux? 
What's termux? 
>Termux provides Linux environment on Android without root.

More? 
Google it

**Comment by Itai-Nelken** [comment]
Some apps will install.
But unless someone ports it to termux, I don't think it will happen.

**Comment by CoderLogy** [comment]
No, It would happen termux , I think it works on FreeBSD as BSD uses pkg command so free BSD is a type of Linux and Unix mix so these apps can work

**Comment by Itai-Nelken** [comment]
Termux uses apt but also has the `pkg` command that is a wrapper for apt.

**Comment by Botspot** [comment]
I do find this application fascinating - installing Pi-Apps on your smartphone and using it to install apps in the linux environment.

But before we can even consider officially supporting Pi-Apps running on Termux, two things need to happen:
1. We need a way to run and interact with Termux for app testing purposes. I'm not aware of a way to do that on a Raspberry Pi running Raspberry Pi OS. (And a Raspberry Pi is all I have to work with. No smartphone.)
2. We would need to take on additional, enthusiastic developers to bear the resulting larger workload.

As long as we have few developers working on Pi-Apps in their spare time, requests to support Pi-Apps on new platforms like Windows or x86 Linux or smartphones are not likely to go anywhere.

**Comment by Botspot** [comment]
Today I just came across a video where someone successfully installs Minecraft on their Android phone using Termux.
https://www.youtube.com/watch?v=ICd7tOTW3LQ
It is fascinating to watch.
