### ISSUE TITLE
Trying to install Notepad++ and not working

### ISSUE THREAD

**Issue by AlecYoungie** [Botspot/pi-apps#822]
it says "Failed to install Box86 with install-32 script!"
Please help

**Comment by Itai-Nelken** [comment]
Full output please

**Comment by Botspot** [comment]
> it says "Failed to install Box86 with install-32 script!"
> Please help

That "error" does not help us at all. You need to send us the FULL OUTPUT - everything you saw in the terminal program.
And while we're at it, what operating system are you using? Is it 64-bit? (It's rare for box86 to fail to install.)

**Comment by Botspot** [comment]
This issue is being closed due to inactivity.
