### ISSUE TITLE
USBImager Installer

### ISSUE THREAD

**Issue by u038265** [Botspot/pi-apps#827]
Hi, when I install USBImager via PIApps on Raspberry PI4B+ I get a compile time error:

"H -Wvla -Wformat = 2 -Winit--Wfloat self-equal -Wwrite-strings -Wredundant-decls -Wmissing-prototypes -wc ++ - compat -DHUF_FORCE_DECOMPRESS_X1 -DZSTD_FORCE_DECOMPRESS_SHORT -DZSTD_NO_INLINE -DZSTD_STRIP_ERROR_STRINGS -DXXH_NAMESPACE = ZSTD_ -DZSTD_LEGACY_SUPPORT = 0 -c -o decompress / zstd_decompress_block.o decompress / zstd_decompress_block.c
compiling static library
make [1]: exit from directory "/ home / pi / usbimager / src / zstd"
Package gtk + -3.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gtk + -3.0.pc '
to the PKG_CONFIG_PATH environment variable
No package 'gtk + -3.0' found
gcc -pthread -o usbimager stream.o lang.o main_libui.o disks_linux.o zlib / libz.a bzip2 / libbz2.a xz / libxz.a zstd / libzstd.a libui / raspios.a
gcc: error: libui / raspios.a: File or directory does not exist
make: *** [Makefile: 173: usbimager] Error 1
Failed to compile usbimager!

Failed to install USBImager with install-64 script!
▲ Need help? Copy the above error output or take a screenshot.
Please ask on Github: https://github.com/Botspot/pi-apps/issues/new/choose
Or on Discord: https://discord.gg/RXSTvaUvuu "

You can help me.

Thanks so much.

**Comment by Itai-Nelken** [comment]
You are on 64bit, right?

**Comment by u038265** [comment]
Yes

Il Gio 22 Lug 2021, 10:42 Itai Nelken ***@***.***> ha scritto:

**Comment by Itai-Nelken** [comment]
That's a problem eith libui (the gui toolkit that is used). For now remove `USE_LIBUI=yes` from the usbimager install-64 script to compile with the X11 gui.

**Comment by u038265** [comment]
Ok, thank you so much.

Best regards

Il Gio 22 Lug 2021, 11:40 Itai Nelken ***@***.***> ha scritto:

**Comment by Botspot** [comment]
> Ok, thank you so much. Best regards 

@u038265, is USBImager working for you?

**Comment by u038265** [comment]
Yes

Il Dom 25 Lug 2021, 23:37 Botspot ***@***.***> ha scritto:

**Comment by Botspot** [comment]
To eliminate installation failures, Pi-Apps [now uses](https://github.com/Botspot/pi-apps/commit/734380230be303572f953845552d229597084135) USBImager's precompiled releases.

**Comment by Itai-Nelken** [comment]
@Botspot did you test this on arm64? Because as far as I know there are no arm64 binaries.

**Comment by Botspot** [comment]
> @Botspot did you test this on arm64? Because as far as I know there are no arm64 binaries.

Unless I'm mistaken, [this](https://github.com/Botspot/pi-apps/commit/734380230be303572f953845552d229597084135#diff-6894c7989ecd8bfd56bd0aabe0fc72882bbcbb873e1d85b876012509353a9352R18) is a valid USBImager aarch64 release: https://gitlab.com/bztsrc/usbimager/raw/binaries/usbimager_1.0.7-aarch64-linux-x11.zip

**Comment by Itai-Nelken** [comment]
Oh, uts the X11 version. That one works on almost everything.

**Comment by u038265** [comment]
Ok, thank you so much.

Il Ven 13 Ago 2021, 16:18 Itai Nelken ***@***.***> ha scritto:
