### ISSUE TITLE
tldr: edit installation

### ISSUE THREAD

**Issue by CleanMachine1** [Botspot/pi-apps#828]
Already exists, but who knows what the binary points to?

I guess its the C client, but I don't run random binaries on my computer.

Please change to the python client or the node js client, since they are the most updated, most featured and official clients.

**Comment by Itai-Nelken** [comment]
I noticed that the python client doesn't work offline for some reason, is it supposed to be like that? because if yes I think we should go with the C one. I want to avoid the nodejs one as nodejs cli programs feel slow on the pi.

**Comment by CleanMachine1** [comment]
Take a look at the client list on the repo, and se if any fit what you think

Ps tealdeer is the fastest i think

**Comment by Itai-Nelken** [comment]
just tested python one and it works fine. so I'll change to it as the C version is broken anyway (it fails to update the cache, so it is online only...).
I'll change the install script to the pi-apps equivalent of
```
sudo apt install python3-pip
pip3 install tldr
```
and maybe add ~/.local/bin to PATH

**Comment by Itai-Nelken** [comment]
is that ok @CleanMachine1?

**Comment by CleanMachine1** [comment]
yes

**Comment by CleanMachine1** [comment]
> I noticed that the python client doesn't work offline for some reason, is it supposed to be like that? because if yes I think we should go with the C one. I want to avoid the nodejs one as nodejs cli programs feel slow on the pi.

it probably doesn't work since it needs to set a cache after installing.

Maybe run the command `tldr -u`after it installs to download a cache for the pages.

**Comment by Itai-Nelken** [comment]
I know, the C version fails to do that, and I mixed it up with the python version that does work and is the best I have used so far.
I'll edit the installation script later.

**Comment by CleanMachine1** [comment]
Ah, ok.

Its a simple change for the file as you know since it doesn't have many dependencies and pip will take care of any if there are.

**Comment by mobilegmYT** [comment]
> Already exists, but who knows what the binary points to?
> 
> I guess its the C client, but I don't run random binaries on my computer.
> 
> Please change to the python client or the node js client, since they are the most updated, most featured and official clients.

I believe it does currently use tealdeer

**Comment by CleanMachine1** [comment]
Can you provide any proof?

**Comment by mobilegmYT** [comment]
> Can you provide any proof?

~If you really are worried about malware just install antivirus~ Back when I made the install script I didn't know that tealdeer had a ARM version, and I saw this arm binary posted in Pi Labs (the download link in the script matches up with pi labs server ID too). If you are worried this guy who has been a mod in Pi Labs for a year is spreading malware, I could change it to the official download link from tealdeer.
![image](https://user-images.githubusercontent.com/44128563/129281484-ee72ee4f-2a4c-4d02-b603-6317f341ce16.png)

**Comment by CleanMachine1** [comment]
I have no idea where a binary comes from, I cannot see the user and I cannot see anything.

I feel that it is better to be open about as much as possible and from looking at tealdeer, they provide arm versions. So why not download from there rather than a random unknown _potentially malicious_ binary without any context.

Official sources should be prioritised. What it is effectively happening here is the rule to never run random commands you see.

You don't know whether it prints a nice happy message or bricks your system

**Comment by CleanMachine1** [comment]
echo "MVRWQ3ZANBSWY3DPFQQGQYLWMUQGCIDONFRWKIDEMF4QU===" | base32 --decode  | bash


Is a prime example.

All it does is decode that base32 string which turns into `echo hello, have a nice day` then executes it.

**Comment by mobilegmYT** [comment]
Alright alright, I'll go change it to official sources after I figure out which binary is for which arch. All the names are confusing as heck for a guy like me who knows nothing about cpu architectures

https://github.com/dbrgn/tealdeer/releases/tag/v1.4.1

**Comment by CleanMachine1** [comment]
arm-musleabihf looks to be correct, ARMhf. I'd still recommend using the python client since it is the easiest and most official (node is a huge installation cost if you don't have all the dependencies pre-installed

**Comment by mobilegmYT** [comment]
Python client does seem good but tealdeer is faster and I always prefer a easy to distribute binary over needing to use python and pip.

**Comment by CleanMachine1** [comment]
Its a shame we don't support Arch. There is a PKGBUILD and it is in the official repos.

But for the purposes of Pi-Apps, a compiled version is preferable

**Comment by Botspot** [comment]
#899
