### ISSUE TITLE
update to install-32 for etcher so 32bit version will be the same as 64bit

### ISSUE THREAD

**Issue by Itai-Nelken** [Botspot/pi-apps#83]
[BalenaEtcher.zip](https://github.com/Botspot/pi-apps/files/5515740/BalenaEtcher.zip)

update to install-32 for etcher so the 64bit and 32bit versions will be the same (v1.5.110)

**Comment by Botspot** [comment]
Thanks. Commit e4788f1222bd81d93175418e2d2f3aa706dc65fe
