### ISSUE TITLE
Sublime Text

### ISSUE THREAD

**Issue by akhilleusuggo** [Botspot/pi-apps#830]
First I want to say that, one of the things I like about pi-apps is that makes find similar software that works on other platforms and I was looking for something similar that works on Rpi.

I would like to ask to change the default location from `Menu -> Accessories -> Sublime Text` to `Menu -> Programming -> Sublime Text`

This should be the right place.

**Comment by open-sorcerer64** [comment]
That is not Pi-Apps' issue. It is because RPi OS thinks it isn't for programming, because technically it is a text editor only

**Comment by Itai-Nelken** [comment]
It is a pi-apps issue as pi-apps creates the menu shortcut. I'll see what is the correct category for programming.

**Comment by Itai-Nelken** [comment]
I think I have done it. @akhilleusuggo can you confirm it is in the `Menu -> Programming/Development`?

**Comment by akhilleusuggo** [comment]
@Itai-Nelken Thank you. Yes it does appear under `Menu -> Programming`

**Comment by akhilleusuggo** [comment]
@Itai-Nelken On the code, for some reason you left Utility too. But it doesn't bother me, I'll just remove it manually.

**Comment by Itai-Nelken** [comment]
> @Itai-Nelken On the code, for some reason you left Utility too. But it doesn't bother me, I'll just remove it manually.

@akhilleusuggo I know, I did that so people don't suddenly "loose" the app. do you think its better to remove it from there?
