### ISSUE TITLE
pi-apps error

### ISSUE THREAD

**Issue by mlohdael** [Botspot/pi-apps#834]
```
Installing Heroes 2 with install-32 script
Running pkg-install...
Waiting until APT locks are released... Done
Running sudo apt update...

Creating dummy deb...
dpkg-deb: building package 'pi-apps-30fe4a24' in '/home/pi/pi-apps-30fe4a24.deb'.

Installing dummy deb...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 pi-apps-30fe4a24 : Depends: libsdl2-mixer-2.0 but it is not installable
                    Depends: libsdl2-ttf-2.0 but it is not installable
E: Unable to correct problems, you have held broken packages.

Apt finished.
Failed to install the packages!
APT reported these errors:
E: Unable to correct problems, you have held broken packages.

Failed to install Heroes 2 with install-32 script!
▲ Need help? Copy the above error output or take a screenshot.
Please ask on Github: https://github.com/Botspot/pi-apps/issues/new/choose
Or on Discord: https://discord.gg/RXSTvaUvuu

Close this window to exit.
```

**Comment by marv-nerd** [comment]
hmm

**Comment by Itai-Nelken** [comment]
@mlohdael try to run
`sudo apt install libsdl2-mixer-2.0`
and
`libsdl2-ttf-2.0`

**Comment by mlohdael** [comment]
Hey, all. Im not exactly now what steps I did to produce that , as I was just scrolling through and installing a lot of pi-apps packages/programs without rebooting. When I got those 2 errors I posted, I quickly posted each and after that uninstalled what it could through the pi-apps gui as it said ‘corrupted’. I eventually rebooted, went through the list again, and well… no issue. Something glitchy on my end. Everything is fixed now, it was just me being dumb and not rebooting enough. That’s all. Operator error. Problem between keyboard and chair… ------------------------------------------------------------------------------------------------------Christopher ***@***.*** From: Itai NelkenSent: Saturday, July 24, 2021 03:09To: Botspot/pi-appsCc: Christopher Leadholm; MentionSubject: Re: [Botspot/pi-apps] pi-apps error ***@***.*** try to runsudo apt install libsdl2-mixer-2.0andlibsdl2-ttf-2.0—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Botspot** [comment]
> Hey, all. I'm not exactly now what steps I did to produce that , as I was just scrolling through and installing a lot of pi-apps packages/programs without rebooting.
> Something glitchy on my end.

In theory, very few apps on Pi-Apps require a reboot after installing. But in practice, there always seems to be some edge case that involves your particular system and the combination/order of apps you installed. Basically, problems like this that are not reproducible, are really hard to track down and identify the cause.
But I think it's safe to say this was not caused by a bug in Pi-Apps. It could be one of those unrepeatable system issues (I've had my fair share of them myself), or operator error like you suggested.

Anyway, it's good to know that Pi-Apps is working well for you now. :)
