### ISSUE TITLE
Firefox Rapid Release (continuation of #810)

### ISSUE THREAD

**Issue by Itai-Nelken** [Botspot/pi-apps#835]
@open-sorcerer64.
here is a zip with some fixes:
- new icons with no white background
- added error handling to uninstall script
- fix typos

[Mozilla_Firefox_RR.zip](https://github.com/Botspot/pi-apps/files/6872039/Mozilla_Firefox_RR.zip)

**Comment by open-sorcerer64** [comment]
Looks good to me. I really wanted a contributor badge next to my name, but I think scripts are also good enough. Let's see what @Botspot thinks

**Comment by CleanMachine1** [comment]
Whats the thoughts of letting an empty commit be allowed?

Work shouldn't be represented by a file no-one views.

**Comment by CleanMachine1** [comment]
Although it would require a lot of setup from your end using git.

From what it seems you don't use it.

**Comment by Botspot** [comment]
> I really wanted a contributor badge next to my name, but I think scripts are also good enough.

We find that using zip files for app development is easier and more reliable. Unfortunately, this approach does mean that the original app-submitter will not be considered a contributor by Github. For this reason, we added the `credits` file. @open-sorcerer64, is your name in it?

Also @open-sorcerer64, if you want to be considered a "contributor" by Github, then try finding something here that could be solved best by a pull request. Examples: grammar improvements to the README, updating a download URL in a pre-existing app, or improving an app's description.

**Comment by Botspot** [comment]
I hesitate to add a repository to people's systems that may end up updating other packages.

Can this repo be added so that it is disabled by default unless you specifically request to install from it? (Just like buster-backports)

**Comment by Itai-Nelken** [comment]
The 99bionic-updates file puts it as the lowest repo I thonk meaning that apt will use it only if it doesn't find the package anywhere else.
I have added the repo and I didn't get any updates. But it is a risk.

**Comment by Botspot** [comment]
> The 99bionic-updates file puts it as the lowest repo I thonk meaning that apt will use it only if it doesn't find the package anywhere else.

In that case, what would happen if another repo contains an older version of the `firefox` package? In that case this app wouldn't function properly. Would there be a way to force-specify the repo to install from?
Like this:
```
sudo apt install -t bionic-updates firefox
```

**Comment by Itai-Nelken** [comment]
I don't know. but on RPiOS the only version of firefox is `firefox-esr`, so it doesn't matter much as most users are on RPiOS I guess.
maybe we can install the specific version we want with `sudo apt install firefox=<VERSION>`.
