### ISSUE TITLE
Update Buddy waits 12 hours?

### ISSUE THREAD

**Issue by chunky-milk** [Botspot/pi-apps#843]
For some reason the `onboot.sh` script that is run when installing Update Buddy waits 12 hours...
![image](https://user-images.githubusercontent.com/71036629/126911240-983b62a2-9e4a-4704-ad35-347820c93c6f.png)

**Comment by Botspot** [comment]
That is a misleading message in this context. Let me explain:
Basically, Update Buddy will check for updates on boot. If no updates are found, it will check _again_ in 12 hours. This feature is useful for those of us who leave our Raspberry Pies on indefinitely.
To prevent requiring a reboot, Pi-Apps will start Update Buddy during the installation process.

These two factors will result in a misleading and confusing terminal output, which seems to indicate that something is waiting 12 hours. And while something *is* waiting 12 hours, it's not what you would expect.

To fix this, I've [just disabled](https://github.com/Botspot/update-buddy) the `echo` command that previously displayed "`Waiting 12 hours`" message from update-buddy.

**Comment by chunky-milk** [comment]
Thanks for explaining.
