### ISSUE TITLE
speedtest-cli fails to install

### ISSUE THREAD

**Issue by Botspot** [Botspot/pi-apps#844]
```
Installing SpeedTest-CLI with install-32 script
/home/pi/pi-apps/apps/SpeedTest-CLI/install-32: line 12: wgethttps://install.speedtest.net/app/cli/ookla-speedtest-1.0.0-armhf-linux.tgz: No such file or directory
Failed to download!

Failed to install SpeedTest-CLI with install-32 script!
```
This problem was caused by @Itai-Nelken's commit 5f9242c0dde6bfd8e4ca7c152a85d942f76e67e7.

**Comment by Itai-Nelken** [comment]
284a1c4aa1f0d7580ad897aa730cab812522f067 fixes the missing space. I'm not sure about the `mkdir` error.

**Comment by Botspot** [comment]
> [284a1c4](https://github.com/Botspot/pi-apps/commit/284a1c4aa1f0d7580ad897aa730cab812522f067) fixes the missing space.

Thank you. :)
