### ISSUE TITLE
Update Minecraft java launcher to the inofficial continuation of the old launcher

### ISSUE THREAD

**Issue by iAmInActions** [Botspot/pi-apps#847]
This guy (https://github.com/mclaunch/) decompiled and improved the old minecraft launcher (thats the one that is also being used for java edition on the pi). He fixed some bugs and made the title screen show the newer versions changes instead of being stuck on the 1.11 release. Would be nice if it got added.

The repo is https://github.com/mclaunch/mclaunch/
The latest release download is https://github.com/mclaunch/mclaunch/releases/latest/download/mclaunch.jar

Its 100% compatible and works with the pi library string added.

**Comment by mobilegmYT** [comment]
Ello mate, dev of MC Java install script here. This does look promising, but currently the dev team is working on replacing the legacy launcher with Lunar Launcher and ATLauncher to provide MS account support, so adding this in wouldn't be very useful since it'll get replaced anyways in a few weeks.

**Comment by iAmInActions** [comment]
Maybe it could be split into two apps: Minecraft Java edition modded launcher and Minecraft Java edition classic laucher.

**Comment by iAmInActions** [comment]
Btw, im gonna ask the mclaunch guys if they gonna add microsoft account verification.

**Comment by timof121** [comment]
> Ello mate, dev of MC Java install script here. This does look promising, but currently the dev team is working on replacing the legacy launcher with Lunar Launcher and ATLauncher to provide MS account support, so adding this in wouldn't be very useful since it'll get replaced anyways in a few weeks.

i thought atlauncher for arm got abandoned

**Comment by mobilegmYT** [comment]
Eh yea it did, I forgot

**Comment by Botspot** [comment]
Minecraft Java now supports Microsoft accounts!
We've switched to a fork of Lunar Launcher to make this work.
https://github.com/Botspot/pi-apps/commit/178b9dac1fabe9042b95a33e0c33edbdbd61ba78
