### ISSUE TITLE
What file type do i need to create my app for pi-apps

### ISSUE THREAD

**Issue by leodev12345** [Botspot/pi-apps#85]
Hello i just wanted to know what file type does pi-installer need to put your own app on the store. I have my python game and can i use a python file thats attribute is changed to executable and than put it on pi-apps?

**Comment by leodev12345** [comment]
I mean can i make my own game and put it on py-apps?

**Comment by Botspot** [comment]
Contrary to popular belief, Pi-Apps is only a bunch of install/uninstall scripts. It does not actually distribute any programs at all, but scripts that download the apps from elsewhere.

Most install scripts clone a github repository, run `chmod +x` on a file, and create a menu button.

**Comment by leodev12345** [comment]
Yes but if i make my game file executable can it work?

**Comment by Botspot** [comment]
For a python script, simply work out **which terminal commands** are necessary.

Those terminal commands are really `bash` commands. Just put those commands in the `install` script, and you're good to go.

BTW: do you know how to create an app? It's a wizard that guides you through the process, and can be found in Pi-Apps Settings.

**Comment by leodev12345** [comment]
I think i know what you mean i should make a bash script that clones the project from github with wget or something right?

**Comment by Botspot** [comment]
> I think i know what you mean i should make a bash script that clones the project from github with wget or something right?

Yep. `git clone` would probably work well enough.

**Comment by leodev12345** [comment]
Yea but what about users that dont have git installed?

**Comment by Botspot** [comment]
> Yea but what about users that dont have git installed?

Oh they will. ;) (To install Pi-Apps, they've already run `git clone`.)

**Comment by leodev12345** [comment]
lol i forgot and do i need to add something extra in the install file other than downloading file?

**Comment by Botspot** [comment]
> lol i forgot and do i need to add something extra in the install file other than downloading file?

Well, how will it be run? Preferably using a menu button.

**Comment by leodev12345** [comment]
I got it to script i will add a command that downloads it and a command that makes a desktop shortcut and maybe a menu shortcut thank you
