### ISSUE TITLE
any app wont install

### ISSUE THREAD

**Issue by kiki96max** [Botspot/pi-apps#852]
ive tried to install wine, minecraft modded, minecraft jva , and minecraft bedrock , but they all say app corrupted. any help!?
the error output:

pkg-install failed to run sudo apt update!
APT reported these errors:
E: The repository 'http://mirrordirector.raspbian.org/raspbian wheezy Release' does not have a Release file.

Failed to install Zoom with install-32 script!
\u25b2 Need help? Copy the above error output or take a screenshot.
Please ask on Github: https://github.com/Botspot/pi-apps/issues/new/choose
Or on Discord: https://discord.gg/RXSTvaUvuu

**Comment by marv-nerd** [comment]
huh, weird

**Comment by Itai-Nelken** [comment]
@kiki96max can you send the output of `cat /etc/os-release` please?

**Comment by Botspot** [comment]
> ```
> E: The repository 'http://mirrordirector.raspbian.org/raspbian wheezy Release' does not have a Release file.
> ```

That says enough. @kiki96max, it appears you are running a very old version of Raspberry Pi OS. The last version of Raspbian Wheezy was released in **2015**. This operating system is unsupported, mostly broken at this point, and has never been tested for running Pi-Apps.
@kiki96max, if your operating system is truly Raspbian Wheezy, you should re-flash your Raspberry Pi's SD card with the latest Raspberry Pi OS. [Here are the official instructions.](https://www.raspberrypi.org/software/operating-systems/)
