### ISSUE TITLE
Editing an app with a single script for 32 and 64 bit creates install-32 and install-64

### ISSUE THREAD

**Issue by scamdotnet** [Botspot/pi-apps#854]
Editing an app with a single script for 32 and 64 bit creates install-32 and install-64 instead of opening the single script as expected.

Steps to recreate:

1. Make an app using Pi Apps' utilities (making sure to select 64bit and 32bit as the compatibility): 
![TestApp](https://user-images.githubusercontent.com/43154292/127672469-98b57631-01d5-4e97-ae81-7ead32901d9a.png)
2. On the next page select 1 script:
![TestApp2](https://user-images.githubusercontent.com/43154292/127673119-12646470-5929-4907-9d3d-c6322df619d2.png)
3. Press next until you reach the done screen, and close the create app wizard
4. Open Pi-Apps and find your app. Open the details screen and click on "Edit" (you need to enable editing of apps in settings)
5. On the following window, press next and two text editors will open up with "install-64" and "install-32"

Expected Behavior:
On step 5 the text editor should open "install" and not create an "install-64" and an "install-32"

**Comment by Botspot** [comment]
Fixed. Thanks for reporting.
