### ISSUE TITLE
Move update log to pi-apps folder

### ISSUE THREAD

**Issue by mobilegmYT** [Botspot/pi-apps#859]
Currently when I run the updater, a list of updated files get written into ~/output.log. I think it would be less clutter to rename it something like update.log and write it to the logs folder.

**Comment by Botspot** [comment]
I noticed this file being created on a couple of my systems, but wasn't sure what was causing it.
Thanks for the lead - it's in the `updater` script.

**Comment by Botspot** [comment]
Wow, this line of code been around since May 24 2021 when I made the updater allow individual items to be unselected!
https://github.com/Botspot/pi-apps/commit/aa60e839d3df6eb0840b8a7143028764c4ade2f5#diff-196c23750e800642e7c008dc0416536449f295069c8161c23283c86334f8d251R225

**Comment by mobilegmYT** [comment]
bruh

**Comment by Botspot** [comment]
Fixed with commit https://github.com/Botspot/pi-apps/commit/a1fbfd5029f55aba789c9e974c276f5b85a840fe
