### ISSUE TITLE
Hey 

### ISSUE THREAD

**Issue by Jacklobl84** [Botspot/pi-apps#86]
i install the api-app 
but for some reason it didnt install the YAD 
how can i install it or remove it and install again ? 👍 thanks

**Comment by mobilegmYT** [comment]
Hmm. Try running `sudo apt install yad -y` in terminal.

**Comment by Botspot** [comment]
When you ran the main Pi-Apps `install` script, that should have installed yad for you.

If it didn't, then maybe there was an error?

**Comment by Jacklobl84** [comment]
all good thanks 
it did install it.
but when i ran the app its runing fine , but when i chose to install it or an app .
it goes to the app i want but the INSTALL dosent clickbale (not working...
Thanks for the quick Answer !<3

**Comment by Botspot** [comment]
> all good thanks
> it did install it.
> but when i ran the app its runing fine , but when i chose to install it or an app .
> it goes to the app i want but the INSTALL dosent clickbale (not working... just going back to Deatils of ... )
> Thanks for the quick Answer !<3

You have to select an app first, then click install. Does that help?

**Comment by Jacklobl84** [comment]
Hey , 
yes i can pick an app.
but when i click install it just quit and go back to the app install..
just if i click the link i can install it by myself...

**Comment by Botspot** [comment]
@Jacklobl84 
What operating system are you running?

What happens when you run `x-terminal-emulator`?

**Comment by Jacklobl84** [comment]
Warring: locale not supported by Xlib, locale set to C

**Comment by Botspot** [comment]
Hmm, that's likely the issue. I'm sorry, but I don't know how to help you.

Maybe try setting your locale, or otherwise use Raspberry Pi OS.
