### ISSUE TITLE
Failed to install Heroes 2

### ISSUE THREAD

**Issue by Rak1ta** [Botspot/pi-apps#860]
Hello. There was a need to reinstall the system and when trying to get back Heroes 2, an error occurs. But Doom3Demo and other games associated with these packages are installed without errors. 
`Some packages cannot be installed. `
`Perhaps what you ask for is
not feasible, or you are using an unstable version of the distribution where
the packages you requested have not yet been created or have been removed from Incoming.`
`The following information may help you:`
`The following packages have unmet dependencies:`
`pi-apps-30fe4a24 : Depends: libsdl2-mixer-2.0 but it cannot be installed`
`pi-apps-30fe4a24 : Depends: libsdl2-ttf-2.0 but it cannot be installed`
`E: Unable to fix bugs: you have broken packages.`
There are no problems installing separately as a package.
`Already installed package libsdl2-mixer-2.0-0 the newest version (2.0.4+dfsg1-1).`
`Already installed package libsdl2-ttf-2.0-0 the newest version (2.0.15+dfsg1-1).`
 I do not understand this, I hope someone knows the solution to the problem (could not find it myself).

![Безымянный](https://user-images.githubusercontent.com/88277343/127772378-850b9578-3175-4a53-9b73-ccf8974c9c82.png)
![Безымянный2](https://user-images.githubusercontent.com/88277343/127772514-cb4f04c9-9004-49ad-bccb-8f1c8edcdd67.png)

**Comment by Rak1ta** [comment]
I drew attention to this issue that this issue is solvable. But I also tried installing on a clean system, the same error occurs. But through PiKISS, the game is installed correctly. Then, it seems to me, something in the Pi Apps itself.
[pi-apps error #834](https://github.com/Botspot/pi-apps/issues/834)
@Botspot Is there an option, what could it be? I would like to send the logs where the error occurs, but there is nothing to send.
![Безымянный](https://user-images.githubusercontent.com/88277343/127973594-ab750438-bf32-4878-abde-ba4f42dd397d.png)

**Comment by Itai-Nelken** [comment]
there are logs of every install/uninstall, check pi-apps settings to view them. they are located in ~/pi-apps/logs

**Comment by Rak1ta** [comment]
@Botspot Hi. I have a guess as to why it didn't work for me. The pi-Apps script for Heroes 2 specifies the packages to install:
`"${DIRECTORY}/pkg-install" "libsdl2-mixer-2.0 libsdl2-ttf-2.0" "$(dirname "$0")" || exit 1`
In PiKISS, the libsdl2 package is fully named with -0 at the end.
`readonly PACKAGES=(fluidr3mono-gm-soundfont fluid-soundfont-gm libsdl2-mixer-2.0-0 libsdl2-image-2.0-0 libsdl2-ttf-2.0-0)
readonly PACKAGES_DEV=(libsdl2-dev libsdl2-ttf-dev libsdl2-mixer-dev libsdl2-image-dev gettext)`
Only I did not pay attention to this, because everything is OK through the console.
![image](https://user-images.githubusercontent.com/88277343/128365968-c1c26ece-7f02-4a7c-9182-ba1841814a6e.png)
As a result, the game was installed. But I don’t know from whose side the mistake was. Thanks for this wonderful software installation tool.

**Comment by e-faz** [comment]
Hi,

Similar problem on new install of Noobs:

```
Installing dummy deb...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 pi-apps-30fe4a24 : Depends: libsdl2-mixer-2.0 but it is not installable
                    Depends: libsdl2-ttf-2.0 but it is not installable
E: Unable to correct problems, you have held broken packages.

Apt finished.
Failed to install the packages!
APT reported these errors:
E: Unable to correct problems, you have held broken packages.

Failed to install Heroes 2 with install-32 script!
\u25b2 Need help? Copy the ENTIRE terminal output or take a screenshot.
Please ask on Github: https://github.com/Botspot/pi-apps/issues/new/choose
Or on Discord: https://discord.gg/RXSTvaUvuu
```

As it says, the dependencies are not installable (as the fix above sugests)?

Any help gratefully received?

Thanks,

A

**Comment by Botspot** [comment]
> @Botspot Hi. I have a guess as to why it didn't work for me. The pi-Apps script for Heroes 2 specifies the packages to install:
> `"${DIRECTORY}/pkg-install" "libsdl2-mixer-2.0 libsdl2-ttf-2.0" "$(dirname "$0")" || exit 1`
> In PiKISS, the libsdl2 package is fully named with -0 at the end.

Thank you for finding that out. I believe I have determined why this issue was not caught in the original app testing. It's because with `apt-get`, the `"-0`" part is **optional**.
```
$ sudo apt install libsdl2-mixer-2.0 libsdl2-ttf-2.0
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'libsdl2-mixer-2.0-0' for regex 'libsdl2-mixer-2.0'
Note, selecting 'libsdl2-ttf-2.0-0' for regex 'libsdl2-ttf-2.0'
```
The Pi-Apps `pkg-install` script **used to use an `apt-get install` command**. But we've switched it to build a deb package that lists an app's necessary dependencies. This technique has countless advantages and completely prevents any chance that a necessary package will be accidentally be uninstalled when an app is uninstalled.

But apparently, this dummy-deb technique **does not** like us omitting the "`-0`" part. So I've added it in and Heroes 2 should work again.
