### ISSUE TITLE
Scrcpy Not Working

### ISSUE THREAD

**Issue by techcoder20** [Botspot/pi-apps#863]
I just tested scrcpy and I could not get it working. The error I was getting:
```
adb:error:failed to get feature set: insufficient permission for device:user in plugdevgroup; are your udev rules wrong ?
```
The solution I found was adding `sudo ./adb start-server` to the android.sh file. Is this happening to anyone else ?

**Comment by mobilegmYT** [comment]
Doesnt seem to happen for me

**Comment by techcoder20** [comment]
Oh okay then I will close it then if anyone else has this problem they can find the solution here :)
