### ISSUE TITLE
Update now button

### ISSUE THREAD

**Issue by Audvikhp737** [Botspot/pi-apps#865]
It will be handy if pi-apps had a update button.

**Comment by techcoder20** [comment]
Just run `~/pi-apps/updater`

**Comment by chunky-milk** [comment]
I think this would be a handy feature, also I'd like to suggest a reinstall button

**Comment by Botspot** [comment]
> It will be handy if pi-apps had a update button.

It will automatically display its update "button" when updates are available. This "button" comes in the form of a notification.
![2021-08-02-210539_1366x768_scrot](https://user-images.githubusercontent.com/54716352/127946274-f433412b-2a2a-4bbe-8a97-8febb36428f9.png)
@Audvikhp737, have you ever seen that notification? It should appear when you turn your Pi on.

**Comment by Audvikhp737** [comment]
yes i have got thst notification

**Comment by Audvikhp737** [comment]
but somw times i just slowdown pi with updating 
in between clases

**Comment by Audvikhp737** [comment]
it does't apper always

**Comment by Audvikhp737** [comment]
can you just telll me if there is  away to update pi-apps with a command or something

**Comment by Itai-Nelken** [comment]
you can set the update interval to 'always' or run the updater directly with `~/pi-apps/updater` and to skip any prompts before the update notification `echo u | ~/pi-apps/updater`.

**Comment by Audvikhp737** [comment]
Ok thanks
