### ISSUE TITLE
New apps added not on my  pi-apps

### ISSUE THREAD

**Issue by MTCK123** [Botspot/pi-apps#87]
I checked the change-logs just curios because I have not seen any new apps. Anyway I find that there are a bunch of new apps but I haven't got them on my app list. I still get updates for the apps (that are on my list) but I don't the new apps.

**Comment by Botspot** [comment]
How old is your Pi-Apps?  About two weeks ago, I found some issues with the updater (and how it calculates hashes). It should be fixed by now.

**Comment by MTCK123** [comment]
Yep 👍. Its fixed now
