### ISSUE TITLE
I can't install any apps via Pi-Apps

### ISSUE THREAD

**Issue by SDWaps** [Botspot/pi-apps#870]
Whenever i try to use pi-apps to install apps i get this error:
```
Installing Wine (x86) with install-32 script
Your system is using a 3G/1G kernel. Continuing...
/usr/local/bin/box86
Running pkg-install...
Waiting until APT locks are released... Done
Running sudo apt update...
pkg-install failed to run sudo apt update!
APT reported these errors:
E: The repository 'https://packagecloud.io/AllToMP3/alltomp3/raspbian buster Release' does not have a Release file.

Failed to install Wine (x86) with install-32 script!
\u25b2 Need help? Copy the ENTIRE terminal output or take a screenshot.
Please ask on Github: https://github.com/Botspot/pi-apps/issues/new/choose
Or on Discord: https://discord.gg/RXSTvaUvuu

Close this window to exit.
```

Any help is much loved.
-SamDev

**Comment by Jai-JAP** [comment]
Try ` rm /etc/apt/sources.list.d/AllToMP3_alltomp3.list `

After that ` curl -s https://packagecloud.io/install/repositories/AllToMP3/alltomp3/script.deb.sh | sudo bash `

I too had the same issue previously,  this solved it for me

**Comment by Botspot** [comment]
Closing this issue as the problem was not **caused** by Pi-Apps.

Pi-Apps has simply detected a problem that already existed on your system, and for safety it won't proceed until the repository is fixed.
