### ISSUE TITLE
feature request: support for other package managers

### ISSUE THREAD

**Issue by Kuratius** [Botspot/pi-apps#875]
In this particular case I tried minecraft java on manjaro, but this should affect all games that use apt.

I was able to install pi-apps itself without issues by installing YAD with the corresponding pacman command in advance.

**Comment by chunky-milk** [comment]
Unfortunately, for now Pi Apps can only be fully supported on Debian-based operating systems, such as RPiOS and Ubuntu, which use APT. While it would be a great addition in the future, pi apps does not support other package managers for the time being.

**Comment by chunky-milk** [comment]
Unfortunately, for now Pi Apps can only be fully supported on Debian-based operating systems, such as RPiOS and Ubuntu, which use APT. While it would be a great addition in the future, pi apps does not support other package managers for the time being.

**Comment by chunky-milk** [comment]
Unfortunately, for now Pi Apps can only be fully supported on Debian-based operating systems, such as RPiOS and Ubuntu, which use APT. While it would be a great addition in the future, pi apps does not support other package managers for the time being.

**Comment by Itai-Nelken** [comment]
The main problem isn't changing the scripts to use a different package manager if apt isn't available, it is that a lot of apps come packaged in .debs or use apt repos. so to add support for other package managers we will have to implement new `install-32`, `install-64`, (or `install`), and `uninstall` scripts for each package manager and write the new scripts for all 100+ apps and we don't have enough time to handle issues/app requests let alone adding new features... anyway most pi-apps users are on Debian based OS's.
so if someone can make this work, great! but we probably won't be doing this.

**Comment by Botspot** [comment]
Well said, @Itai-Nelken
