### ISSUE TITLE
Can't install TurboWarp: script permission denied

### ISSUE THREAD

**Issue by Audvikhp737** [Botspot/pi-apps#876]
![tuooooooo](https://user-images.githubusercontent.com/88205594/128623337-95aa6c75-0c29-435c-a7d6-481347960b19.png)

fail to install with 32-spcipt 
whatever that thing is 
and my pi apps is up to date

**Comment by Audvikhp737** [comment]
@Botspot 

tuooooooo
fail to install with 32-spcipt
whatever that thing is
and my pi apps is up to date

**Comment by Audvikhp737** [comment]
@Botspot 

fail to install with 32-spcipt
whatever that thing is
and my pi apps is up to date
permision got denied
don't know why

**Comment by Itai-Nelken** [comment]
Run `chmod +x ~/pi-apps/apps/Turbowarp/install-32` and try installing again.

**Comment by Botspot** [comment]
> ![tuooooooo](https://user-images.githubusercontent.com/88205594/128623337-95aa6c75-0c29-435c-a7d6-481347960b19.png)

It looks like your installation of Pi-Apps was completed incorrectly somehow.
Under normal circumstances, the `git` command will change file-attributes to make all of the scripts **executable**. But for some reason your Pi-Apps installation did not do that.
@Audvikhp737, how did you install Pi-Apps? Do other apps also have this "Permission denied" error?

**Comment by Audvikhp737** [comment]
no apps i have install is showing this eorrr exect this

**Comment by mobilegmYT** [comment]
For now you can run `chmod +x ~/pi-apps/apps/Turbowarp/install-32 && chmod +x ~/pi-apps/apps/Turbowarp/uninstall` to fix it

**Comment by Botspot** [comment]
> No apps have shown this error except this app.

If this is the only app that had trouble with script permissions, then I have no plausible explanation for it.
In any case, I've made a change to our `manage` script to automatically mark the script as executable, so this problem should be fixed from now on.

**Comment by Audvikhp737** [comment]
ok let me try

**Comment by Audvikhp737** [comment]
that work thanks
