### ISSUE TITLE
Add Box64 on aarch64 installations

### ISSUE THREAD

**Issue by iAmInActions** [Botspot/pi-apps#878]
Can this app run on RPi? If so, please provide a link to a tutorial if applicable.
https://github.com/ptitSeb/box64

Is this app something many GUI users would find useful?
Absolutely. It provides an x86_64 environment for apps meaning that wine64 can be installed and many new applications and games will be able to run on the pi.

Is this app installable with `sudo apt install`?
Not yet, may be changed in the future though.

If you've created a zip file for this app, upload it here.
I haven't yet, but I probably will do so in the future and upload the zip then.

**Comment by Botspot** [comment]
Box64 is already on Pi-Apps. https://github.com/Botspot/pi-apps/tree/master/apps/Box64
On 32-bit installations, Pi-Apps will hide Box64. On 64-bit installations, Box64 will be visible.
