### ISSUE TITLE
Search Feature

### ISSUE THREAD

**Issue by Rex-Arnab** [Botspot/pi-apps#879]
Its great that pi-apps is getting huge so I think its a right time to add a search feature to it like any other software store out there :D

**Comment by Itai-Nelken** [comment]
There already is one if you use one ofvthe xlunch themes.
But I guessnitbwould be nice to have better search, what do you say @Botspot?

**Comment by mobilegmYT** [comment]
With the normal theme though, AFAIK it's impossible to add one in directly to the app due to YAD limitations, but it might be possible to add a button which then opens a new window with a search bar.

**Comment by Botspot** [comment]
A search feature has been added in commit eac1369ec8e1e741417dc4d3a75431795167be04.
