### ISSUE TITLE
Simplenote - App Request

### ISSUE THREAD

**Issue by rekab72** [Botspot/pi-apps#88]
Please consider adding Simplenote electron app. https://github.com/Automattic/simplenote-electron
Version 2.1 has been updated to build both 32 & 64 bit ARM versions. Once the release candidate is stable could you add it.
@SpacingBat3 who created the Discord electron app included in pi-apps assisted fixing the ARM builds for simplenote-electron.

**Comment by Botspot** [comment]
As you well know, Pi-Apps does not allow software that's already on the repositories.

This does not look like it's on the repositories, so we look good to go!

One question though @rekab72: how would you compare this electron app to the `nvpy` apt package?

**Comment by rekab72** [comment]
@Botspot The nvpy apt package I just search for seems like last update 2011. Do you have a different repository? Simplenote is simple, not secure. It serves me well with trying so many differenct Pi images. I can always launch the browser and access my notes for how to's, mod's, scripts, etc. If I save locally every time I wipe a sd, ssd, or usb with a new image I have start over.

**Comment by SpacingBat3** [comment]
@Botspot @rekab72 I believe the devs might compile the app for the ARM target, so you might want to just wait for the future releases (2.1.0+). The current "beta" pre-release existed before my PR were there merged, but "beta3" pre-release or "2.1.0" release might contain the ARM package files.

**Comment by Botspot** [comment]
@rekab72 Are you okay if I close this issue until Simplenote releases official ARM targets?

**Comment by rekab72** [comment]
> @rekab72 Are you okay if I close this issue until Simplenote releases official ARM targets?

Yes, thank you their RC are working but wait until official. Thanks for your work.

**Comment by Itai-Nelken** [comment]
@Botspot there are official arm debs and appimages now, will make the zip.

**Comment by Itai-Nelken** [comment]
@Botspot #418
