### ISSUE TITLE
Better Blender?

### ISSUE THREAD

**Issue by Zipperoos** [Botspot/pi-apps#881]
Hey, so I have been interested in using blender for minecraft animations for a long time now. However, most of the ones I can find are for blender 2.9 and not the current installable version of blender for RPi.
If you could create a script to download a later version, I would be extremely grateful!
~Zipperoos
PS: I have already been VERY bothersome to the Pi-Apps github, and this isn't urgent, so don't bother if it will be too troublesome for you guys.
PPS: If there are any tutorials out there or some info on learning how to do the stuff you guys do for this, I would be very glad to try and help you guys out! Pls note i have very little programming/Linux experience, but I am happy to learn!

**Comment by Itai-Nelken** [comment]
Unfortunately its impossible to install the latest version of blender on the pi as it requires a newer version of opengl that isn't available (and if I remember correctly the gpu doesn't even support it).

**Comment by Zipperoos** [comment]
Ok, good to know. I have found some older tutorials, but I just
thought I'd ask. Thanks for letting me know, as I have no knowledge
whatsoever about the inner workings of the Pi.
~ Zipperoos
