### ISSUE TITLE
Webcord Update

### ISSUE THREAD

**Issue by open-sorcerer64** [Botspot/pi-apps#885]
### Hi, There

I just noticed that there is a new Webcord version 1.6.0, so it will be great if you guys can update the script

**Comment by Botspot** [comment]
@spacingbat3, is it ready or is our WebCord outdated for a reason?

**Comment by SpacingBat3** [comment]
Yes, [WebCord v1.6.0] has been recently released and is available to download.

**Comment by open-sorcerer64** [comment]
Closing this issue as it was fixed in https://github.com/Botspot/pi-apps/commit/2bc6f8424fcc25dea4a083c7280de71fe837fc04
