### ISSUE TITLE
The link to the git repo is not found (the one you git clone)

### ISSUE THREAD

**Issue by Zephymyra** [Botspot/pi-apps#89]

**Comment by Botspot** [comment]
How can I help you, I don't tknow. Make sure you spelled it correctly.

    git clone https://github.com/Botspot/pi-apps

**Comment by Itai-Nelken** [comment]
the link works. maybe your internet is slow, I had issues with cloning repositories with a slow internet

**Comment by Botspot** [comment]
Yeah. The link works fine.

If you have any issues with it then something is wrong on your end. (either a typo, locale issue, or internet issue)
