### ISSUE TITLE
Pi apps not supported on x86 systems!

### ISSUE THREAD

**Issue by abraha2** [Botspot/pi-apps#892]
I tried running Pi apps on Raspberry Pi desktop (raspberry pi OS for intel based computers), 
and it came back with this error  "Pi-Apps is not not supported on x86 processors."
I really hope you can fix this problem, till then, thanks in advance!

**Comment by Botspot** [comment]
> I tried running Pi apps on Raspberry Pi desktop (raspberry pi OS for intel based computers),
> and it came back with this error "Pi-Apps is not not supported on x86 processors."
> I really hope you can fix this problem, till then, thanks in advance!

Pi-Apps is supported **only** on ARM-cpu devices, specifically the Raspberry Pi platform.
Your computer is not arm, it's x86. Because of that, nearly all of the apps on pi-apps won't work on your system.

**Comment by abraha2** [comment]
but it worked beforeI updated Pi apps, today

**Comment by Botspot** [comment]
> but it worked before I updated Pi apps, today

*Pi-Apps* may have worked, but nearly all of the apps won't.
And we added that detection today because people kept sending us installation error reports from x86 devices.

Is there a particular app on Pi-Apps that _did_ work?

**Comment by abraha2** [comment]
Pi Apps apps that worked:
mac os theme
Discord
Ulauncher
that's it

**Comment by abraha2** [comment]
Oh, I missed the part where you added detection
is there any way you can easly disable that?

**Comment by Botspot** [comment]
> Oh, I missed the part where you added detection
> is there any way you can easily disable that?

Yes - lines 32, 33, and 34 in the `manage` script. Erasing those should regain your ability to use Pi-Apps.
And for convenience, you can view all changes we make to Pi-Apps, [here](https://github.com/Botspot/pi-apps/commits).

Be aware that editing files in pi-apps will make <the file you edited> show up in the update box. You will have to uncheck it each time, or add the file to the updating blacklist whose details are explained in [the directory tree](https://github.com/Botspot/pi-apps/wiki/Directory-tree).

**Comment by abraha2** [comment]
Thank you very much, for your time, and that is all.
bye!
