### ISSUE TITLE
ZOOM CANT INSTALL

### ISSUE THREAD

**Issue by sudeepbpr** [Botspot/pi-apps#896]
OS: Raspbian GNU/Linux 10 (buster)
OS architecture: 32-bit
Kernel: armv7l 5.10.17-v7l+
Device model: Raspberry Pi 400 Rev 1.0
Raspberry Pi OS image version: 2021-05-07
Language: en_US.UTF-8
Pi-Apps gui script datestamp: Thu 12 Aug 2021 09:29:00 PM IST

BEGINNING OF ERROR LOG:
-----------------------

Installing zoom with install-32 script
Cloning into 'example.com'...
fatal: repository 'https://example.com/' not found
Failed to clone example.com repository!

Failed to install zoom with install-32 script!
\u25b2 Need help? Copy the ENTIRE terminal output or take a screenshot.
Please ask on Github: https://github.com/Botspot/pi-apps/issues/new/choose
Or on Discord: https://discord.gg/RXSTvaUvuu

**Comment by sudeepbpr** [comment]
OS: Raspbian GNU/Linux 10 (buster)
OS architecture: 32-bit
Kernel: armv7l 5.10.17-v7l+
Device model: Raspberry Pi 400 Rev 1.0
Raspberry Pi OS image version: 2021-05-07
Language: en_US.UTF-8
Pi-Apps gui script datestamp: Thu 12 Aug 2021 09:29:00 PM IST

BEGINNING OF ERROR LOG:
-----------------------

Installing zoom with install-32 script
Cloning into 'example.com'...
fatal: repository 'https://example.com/' not found
Failed to clone example.com repository!

Failed to install zoom with install-32 script!
\u25b2 Need help? Copy the ENTIRE terminal output or take a screenshot.
Please ask on Github: https://github.com/Botspot/pi-apps/issues/new/choose
Or on Discord: https://discord.gg/RXSTvaUvuu

**Comment by Botspot** [comment]
You appear to be using some 3rd-party app. There is no "zoom" app. (lowercase)
