### ISSUE TITLE
[App suggestion] Minecraft Java

### ISSUE THREAD

**Issue by mobilegmYT** [Botspot/pi-apps#9]
[Minecraft.zip](https://github.com/Botspot/pi-apps/files/5320908/Minecraft.zip)

**Comment by Botspot** [comment]
This requires you to have a Minecraft account, right?
Well I don't have one.

**Comment by mobilegmYT** [comment]
If you wanna test it, I can lend you mine, or I could give you the download to a cracked version

**Comment by Botspot** [comment]
One issue: The menu button's icon isn't displaying. I checked the .desktop file and it contains some rogue characters. Several of these: `\`

**Comment by mobilegmYT** [comment]
Hmm.

**Comment by mobilegmYT** [comment]
Well, let me just upload the file instead. In the meantime, take a look at this vid from me and replace the links in ur launcher with the cracked one. https://www.youtube.com/watch?v=pEhutXW-ZJU

**Comment by mobilegmYT** [comment]
[Minecraft.zip](https://github.com/Botspot/pi-apps/files/5320926/Minecraft.zip)
Updated version

**Comment by Botspot** [comment]
Your updated version looks much better.

**Comment by Botspot** [comment]
OK I've uploaded a ton of updates, including Minecraft and a new settings program that's in progress.
Have fun! (while I sleep)

**Comment by Botspot** [comment]
I've followed your crack installation instructions and it seems to work, but upon clicking Play Minecraft comes back with a crash report:
```
---- Minecraft Crash Report ----
// Oops.

Time: 10/3/20 10:38 AM
Description: Initializing game

java.lang.ExceptionInInitializerError
	at dka.<init>(SourceFile:143)
	at djw.<init>(SourceFile:426)
	at net.minecraft.client.main.Main.main(SourceFile:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at info.mineshafter.GameStarter.main(GameStarter.java:61)
Caused by: java.lang.RuntimeException: java.lang.UnsatisfiedLinkError: Failed to locate library: liblwjgl32.so
	at del.<clinit>(SourceFile:46)
	... 8 more
Caused by: java.lang.UnsatisfiedLinkError: Failed to locate library: liblwjgl32.so
	at org.lwjgl.system.Library.loadSystem(Library.java:147)
	at org.lwjgl.system.Library.loadSystem(Library.java:67)
	at org.lwjgl.system.Library.<clinit>(Library.java:50)
	at org.lwjgl.system.MemoryAccessJNI.<clinit>(MemoryAccessJNI.java:13)
	at org.lwjgl.system.Pointer.<clinit>(Pointer.java:28)
	at org.lwjgl.system.Platform.mapLibraryNameBundled(Platform.java:80)
	at org.lwjgl.glfw.GLFW.<clinit>(GLFW.java:674)
	at sun.misc.Unsafe.ensureClassInitialized(Native Method)
	at java.lang.invoke.DirectMethodHandle$EnsureInitialized.computeValue(DirectMethodHandle.java:330)
	at java.lang.invoke.DirectMethodHandle$EnsureInitialized.computeValue(DirectMethodHandle.java:327)
	at java.lang.ClassValue.getFromHashMap(ClassValue.java:227)
	at java.lang.ClassValue.getFromBackup(ClassValue.java:209)
	at java.lang.ClassValue.get(ClassValue.java:115)
	at java.lang.invoke.DirectMethodHandle.checkInitialized(DirectMethodHandle.java:351)
	at java.lang.invoke.DirectMethodHandle.ensureInitialized(DirectMethodHandle.java:341)
	at java.lang.invoke.DirectMethodHandle.ensureInitialized(DirectMethodHandle.java:373)
	at del.<clinit>(SourceFile:43)
	... 8 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at dka.<init>(SourceFile:143)
	at djw.<init>(SourceFile:426)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at info.mineshafter.GameStarter.main(GameStarter.java:61)

-- System Details --
Details:
	Minecraft Version: 1.16.3
	Minecraft Version ID: 1.16.3
	Operating System: Linux (arm) version 5.4.51-v7l+
	Java Version: 1.8.0_251, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Server VM (mixed mode), Oracle Corporation
	Memory: 139542056 bytes (133 MB) / 302395392 bytes (288 MB) up to 523501568 bytes (499 MB)
	CPUs: 4
	JVM Flags: 5 total; -Xmx512M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	Launched Version: 1.16.3
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: ~~ERROR~~ NoClassDefFoundError: Could not initialize class org.lwjgl.glfw.GLFW
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Probably not. Jar signature remains and client brand is untouched.
	Type: Client (map_client.txt)
	CPU: <unknown>
```
what am I doing wrong? (running latest RaspiOS 32bit Buster)

**Comment by mobilegmYT** [comment]
There's something in the instructions.

**Comment by mobilegmYT** [comment]
Please log in to the launcher with your MC account and follow the instructions at https://www.noxxtech.tk/minecraft-install#h.fpnon3xvmuoz

**Comment by mobilegmYT** [comment]
Didn't read the instructions in the script eh?

**Comment by Botspot** [comment]
No I didn't. Was not expecting to have to make changes to the game in order for installation to finish.
Would it be at all possible for your install script to make those changes automatically? I'd think it's just a matter of finding the right config file.
If that is not possible, then we need the description to say "after you install this from Pi-Apps, you need to follow this website's instructions to make Minecraft install the rest of the way."

**Comment by mobilegmYT** [comment]
Yep lol. I dont think theres a way to do it without giving people access to my mc account. I guess you could automate it with sed or awk. The file that stores the configs for the java arguments is ~/.minecraft/launcher_profiles.json.

**Comment by mobilegmYT** [comment]
Small update to the part asking to edit JVM settings
[Minecraft.zip](https://github.com/Botspot/pi-apps/files/5322083/Minecraft.zip)

**Comment by mobilegmYT** [comment]
let me edit the description too

**Comment by mobilegmYT** [comment]
[Minecraft.zip](https://github.com/Botspot/pi-apps/files/5322087/Minecraft.zip)
Also I think you could make the colour of URLs lighter since they are pretty dark.
![image](https://user-images.githubusercontent.com/44128563/94998532-9ab51700-056f-11eb-8962-71a64209d676.png)

**Comment by mobilegmYT** [comment]
[Minecraft.zip](https://github.com/Botspot/pi-apps/files/5322123/Minecraft.zip)
Yeet

**Comment by Botspot** [comment]
Are you using a dark mode? Default Raspbian is a grey-ish light mode, and URLs are much easier to read.
BTW I'm making progress reverse-engineering `launcher_profiles.json` to ship with the right settings, while not leaking any username information.

**Comment by mobilegmYT** [comment]
Totally forgot I was using TwisterOS nighthawk. Kinda just used to it lol.

**Comment by Botspot** [comment]
OK, it appears these two commands will make the necessary changes to `launcher_profiles.json` for Minecraft to install successfully: (after logging in of course)

    sed -i -e 4's/$/, &/' /home/pi/.minecraft/launcher_profiles.json
    sed -n -i 'p;4a\      "javaArgs": "-Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M -Dorg.lwjgl.librarypath=/home/pi/lwjgl3arm32"' /home/pi/.minecraft/launcher_profiles.json

But now, those commands will have to be run automatically after somebody logs in, but before they click Play.
I'm going to see if I can find the default javaArgs location and modify that directly to fix this second issue.

**Comment by mobilegmYT** [comment]
Also probably should tweak it to 
`sed -n -i 'p;4a\      "javaArgs": "-Dorg.lwjgl.librarypath=/home/pi/lwjgl3arm32 -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M"' /home/pi/.minecraft/launcher_profiles.json`

**Comment by Botspot** [comment]
OK I got it to work before logging in!
Please try it:
[Minecraft.zip](https://github.com/Botspot/pi-apps/files/5323431/Minecraft.zip)

**Comment by mobilegmYT** [comment]
`sed: can't read /home/pi/.minecraft/launcher_profiles.json: No such file or directory
sed: can't read /home/pi/.minecraft/launcher_profiles.json: No such file or directory
`

**Comment by Botspot** [comment]
Will look into it.

**Comment by mobilegmYT** [comment]
Quick update so the install completes without errors. 
[Minecraft.zip](https://github.com/Botspot/pi-apps/files/5324686/Minecraft.zip)

**Comment by Botspot** [comment]
> Quick update so the install completes without errors.
> [Minecraft.zip](https://github.com/Botspot/pi-apps/files/5324686/Minecraft.zip)

OK, will do. I see you moved ./setupMC.sh down to a new line. I went a step further and broke the commands out more.

**Comment by mobilegmYT** [comment]
Yea. Had some install problems testing it because update-alternatives had problems

**Comment by mobilegmYT** [comment]
Kept on getting `update-alternatives: error: alternative /usr/lib/jvm/java-11-openjdk-arm64/bin/java for java not registered; not setting` but I dont think it affects anything.

**Comment by Botspot** [comment]
No clue whatsoever.
Is your TwisterOS 64-bit?

**Comment by mobilegmYT** [comment]
Well I'm using the 64-bit kernel thing

**Comment by Botspot** [comment]
OK, was just curious. If you want that error investigated, I'd go ask the guy who made this java Minecraft installation possible.

**Comment by mobilegmYT** [comment]
Ehh not my biggest issue.

**Comment by Botspot** [comment]
For future reference, these 2 commands will install the cracked launcher. Much simpler than that video tutorial!
```
sudo mv /usr/share/minecraftjava/launcher.jar /usr/share/minecraftjava/oldlauncher.jar
sudo wget https://github.com/boomerangos/Cracked-Launcher/blob/master/crackedlauncherVer1.1.jar?raw=true -O /usr/share/minecraftjava/launcher.jar
```

**Comment by Botspot** [comment]
OK, here's an improved version of that automatic Minecraft installer I've been working on:
[Minecraft.zip](https://github.com/Botspot/pi-apps/files/5324927/Minecraft.zip)
I've tested it multiple times, and it has worked each time. Awaiting testing from you.

**Comment by mobilegmYT** [comment]
Also theres this better icon I found for the launcher made by https://www.youtube.com/channel/UCojEXrCBzO-cP2N5YlRcrWw
[minecraft3d.svg.zip](https://github.com/Botspot/pi-apps/files/5324948/minecraft3d.svg.zip)

**Comment by mobilegmYT** [comment]
Also the install got stuck here.
![image](https://user-images.githubusercontent.com/44128563/95035878-91b56a00-0683-11eb-8867-9fa34155b087.png)

**Comment by Botspot** [comment]
Oh cool... do you want me to put that as icon-64.png and icon-24.png?

**Comment by Botspot** [comment]
Oh, just hit Enter.
That gives me a chance to install the cracked launcher. The real Minecraft app won't stop like that.

**Comment by mobilegmYT** [comment]
> Oh cool... do you want me to put that as icon-64.png and icon-24.png?

Sure. And he launcher nvm arguments worked! That's a lotta big brain code you did in install.sh lol.

**Comment by Botspot** [comment]
Good to know.
What I ended up doing was to create the .minecraft folder beforehand, then create a modified version of ~/.minecraft/launcher_profiles.json.
Then after that file is created, Minecraft Launcher is started for the first time. Pretty simple really, but I agree with you that the code to do it looks pretty wacky.

**Comment by Botspot** [comment]
OK, I've uploaded the new Minecraft to the repo. Thanks for your testing & help!

**Comment by mobilegmYT** [comment]
Even more quick edits
[Minecraft.zip](https://github.com/Botspot/pi-apps/files/5325041/Minecraft.zip)

**Comment by mobilegmYT** [comment]
[Minecraft.zip](https://github.com/Botspot/pi-apps/files/5325178/Minecraft.zip)

**Comment by mobilegmYT** [comment]
Another update to change the website to the original place.
[Minecraft.zip](https://github.com/Botspot/pi-apps/files/5325201/Minecraft.zip)

**Comment by Botspot** [comment]
When we `wget` the desktop launcher, in the event that fails, do we want the script to exit with an error? (I noticed you didn't put a `|| error ''` there)

**Comment by mobilegmYT** [comment]
Yes

**Comment by mobilegmYT** [comment]
Now if only we could get it to also set the version to the latest on the first launch...

**Comment by Botspot** [comment]
> Now if only we could get it to also set the version to the latest on the first launch...

It already does AFAIK.
If you were to force a specific Minecraft version, then `launcher_profiles.json` would include this line:
```
"lastVersionId": "1.16.3",
```

**Comment by mobilegmYT** [comment]
Quick update to do some update-alternatives magic.
[Minecraft.zip](https://github.com/Botspot/pi-apps/files/5337952/Minecraft.zip)

**Comment by mobilegmYT** [comment]
Also, if a profile is using version 1.12 or older, it needs to change the jvm to `-Dorg.lwjgl.librarypath=/home/pi/lwjgl2arm32`

**Comment by Botspot** [comment]
> Also, if a profile is using version 1.12 or older, it needs to change the jvm to `-Dorg.lwjgl.librarypath=/home/pi/lwjgl2arm32`

Yeah, speaking of that, do you know if anyone out there would deliberately want to run an older version of Minecraft?

**Comment by mobilegmYT** [comment]
I know a lot of people who play older version because they run faster than the 10-20fps normal mc has, or have old mods.

**Comment by Botspot** [comment]
Interesting. That makes perfect sense.  
I don't think the script can do anything about that. Here's the two options:

- During install, have the script ask the user what version they want. If the requested version is less than 1.12, then generate one `launcher_profiles.json`, but if the requested version is greater than 1.12, then generate a different `launcher_profiles.json`. 
  - Pros: Simple, easy to get working.
  - Cons: What if the user wants to change the version? I guess they could uninstall the Minecraft App and then reinstall it again.
- Have the script automatically detect the requested MC version by reading the `launcher_profiles.json` file on a regular basis. It would then change `librarypath` as necessary.
  - Pros: more automatic
  - Cons: Won't work right away, extremely complicated, may corrupt `launcher_profiles.json` if other settings are modified, etc.

**Comment by mobilegmYT** [comment]
I'm thinking we do both... but its really up to your choice.

**Comment by Botspot** [comment]
Yeah, I think we'll do option 1 and put the info in the description.

**Comment by mobilegmYT** [comment]
Also, the description should say:
"NOTE: If you have any trouble with running Minecraft(not the launcher), then please directly follow this guide: https://www.noxxtech.tk/minecraft-install"

I actually had a problem with launching Minecraft when I installed it with pi-apps, and I couldn't seem to find the issue.
