### ISSUE TITLE
Better Banner

### ISSUE THREAD

**Issue by open-sorcerer64** [Botspot/pi-apps#900]
### Hi, @Botspot 

Today, I noticed that you added a `Pi Apps` banner, i.e, 
![2021-08-13_10-25](https://user-images.githubusercontent.com/78641958/129307986-357228d8-edcf-4e02-9b64-444509b64529.png)

But the text is a little wonky, so here are some suggestions

[maysuggest.txt](https://github.com/Botspot/pi-apps/files/6980054/maysuggest.txt)

**Comment by Botspot** [comment]
I agree that the pi-apps text has room for improvement, but enlarging it the way you suggest is not an option. I want the Pi-Apps text to stay the same size.

**Comment by Botspot** [comment]
What do you think of this?
![2021-08-13-073414_1920x1080_scrot](https://user-images.githubusercontent.com/54716352/129357868-6a20ae4d-9ec7-4cc1-979d-f128e13b8bae.png)

**Comment by Botspot** [comment]
Or this?
![2021-08-13-073728_1920x1080_scrot](https://user-images.githubusercontent.com/54716352/129358194-52cf02ec-0b41-4dff-80f8-88ed0d6cfb3d.png)

**Comment by mobilegmYT** [comment]
> Or this?
> ![2021-08-13-073728_1920x1080_scrot](https://user-images.githubusercontent.com/54716352/129358194-52cf02ec-0b41-4dff-80f8-88ed0d6cfb3d.png)

Looks good

**Comment by open-sorcerer64** [comment]
> Or this?
> ![2021-08-13-073728_1920x1080_scrot](https://user-images.githubusercontent.com/54716352/129358194-52cf02ec-0b41-4dff-80f8-88ed0d6cfb3d.png)

Looks good, but can you make the **p** a little shorter

**Comment by Botspot** [comment]
> > Or this?
> > ![2021-08-13-073728_1920x1080_scrot](https://user-images.githubusercontent.com/54716352/129358194-52cf02ec-0b41-4dff-80f8-88ed0d6cfb3d.png)
> 
> Looks good, but can you make the **p** a little shorter

I don't think there is a Unicode character for that.

**Comment by open-sorcerer64** [comment]
> > > Or this?
> > > ![2021-08-13-073728_1920x1080_scrot](https://user-images.githubusercontent.com/54716352/129358194-52cf02ec-0b41-4dff-80f8-88ed0d6cfb3d.png)
> > 
> > 
> > Looks good, but can you make the **p** a little shorter
> 
> I don't think there is a Unicode character for that.

Oh, but this one also looks good
