### ISSUE TITLE
Snipping Tool

### ISSUE THREAD

**Issue by P-EO** [Botspot/pi-apps#902]
Microsoft Snip tool with more features

WARNING:BE CAREFULL WHEN YOU DOWNLOAD 
THE APP/IF YOU ARE DONE WITH THE APP AND YOU WANT TO DELETE IT , IT WILL ALSO DELETE *BOX86*
ON SPOT SO BEFORE YOU DOWNLOAD AND INSTALL FIRST MAKE UP YOUR MIND.

**Comment by Botspot** [comment]
Did you intend to upload an app zip file for us to review?

**Comment by Botspot** [comment]
Closing this issue as @P-EO never replied back. We can re-open the issue if @P-EO replies back later.
