### ISSUE TITLE
(question) Is the bounty for the new minecraft launcher still up?

### ISSUE THREAD

**Issue by iAmInActions** [Botspot/pi-apps#905]
I had read that there was a bounty for getting the new minecraft launcher to work on the pi. Is that still the case or has someone already done that?

**Comment by marv-nerd** [comment]
where did u here that from?

**Comment by iAmInActions** [comment]
on the raspberry pi forum. someone offered $100 for the person who makes it work. but i cant remember the URL of the post.

**Comment by Botspot** [comment]
> on the raspberry pi forum. someone offered $100 for the person who makes it work. but i cant remember the URL of the post.

I think you are mistaken. The only $100 bounty I'm aware of is this one: https://www.raspberrypi.org/forums/viewtopic.php?f=63&t=308303&p=1844479&hilit=$100#p1844479 (For somebody to recompile chromium-browser with the classic trapezoid tabs)

**Comment by oxmc** [comment]
@Botspot Is this still open or?

**Comment by Botspot** [comment]
> @Botspot Is this still open or?

I never offered a bounty of $100 for Minecraft.
Tell you what though: Starting now, a $15 bounty is available for making a Minecraft app that fulfills these requirements:

- Legal and cordial - using the Lunar launcher from Pi-Ware without their approval does not count. A pirating launcher would not count either.
- Allows Microsoft sign-in.
- Runs smoothly on a Pi4. (Turning settings down is okay - but it needs to be considered "playable")
- Will install on armhf and arm64 Buster operating systems.

If multiple people send me different Minecraft solutions, I will choose the option that would serve our users best. In other words, the bounty will not necessarily go to the **_first_** person to fulfill the above requirements!

**Comment by oxmc** [comment]
> using the Lunar launcher from Pi-Ware without their approval does not count. A pirating launcher would not count either.

What do you mean by this?
You mean asking gl91306 for permission to use it? or not copy from pi-ware?

**Comment by Botspot** [comment]
> > using the Lunar launcher from Pi-Ware without their approval does not count. A pirating launcher would not count either.
> 
> What do you mean by this?
> You mean asking gl91306 for permission to use it? or not copy from pi-ware?

I mean that nobody should expect to be awarded the bounty for gl91306's Lunar Launcher project, because I wouldn't be able to use it. (I'm honoring gl91306's request to **not** put his Lunar Launcher build on Pi-Apps)

**Comment by oxmc** [comment]
Oh, i thought gl91306 was okay with this, let me check...

**Comment by oxmc** [comment]
![Screen Shot 2021-09-20 at 11 11 16 AM](https://user-images.githubusercontent.com/67136658/134052806-ce78d111-77e7-40ed-85ac-6778ce06efe0.png)

**Comment by Botspot** [comment]
> Oh, i thought gl91306 was okay with this, let me check...

Rpinews told me something similar today - that gl91306 is now allowing Lunar Launcher to go on Pi-Apps.
Maybe that's why [he uploaded](https://github.com/Botspot/pi-apps/issues/483#issuecomment-922574021) a new zip for Lunar today that included an attribution message at the end of the script.
I plan to make extensive changes to the script for reliability and aesthetics.

As far as the bounty, I'm not sure who deserves it most. RPiNews? gl91306? Someone else?
This situation is tricky because I intended for the $15 bounty to go to someone to do work. However, the Lunar project has been in a "finished" state for months.

**Comment by oxmc** [comment]
True.

**Comment by oxmc** [comment]
@Botspot I believe that it's only fair you keep the money, as we haven't done that much. We just made it public.

**Comment by oxmc** [comment]
@Botspot Do you want to close this or?

**Comment by gl91306** [comment]
wait how have i not seen this before?

**Comment by gl91306** [comment]
> @Botspot I believe that it's only fair you keep the money, as we haven't done that much. We just made it public.

What do you mean we havent dont that much? I litterally spent a year on making this work D:<
