### ISSUE TITLE
Using a ".pi-apps" folder

### ISSUE THREAD

**Issue by open-sorcerer64** [Botspot/pi-apps#907]
### Hello 
So, I was thinking to rename the `pi-apps`  folder to `.pi-apps` to make the file manager look neat, and also it won't look bloated. Just renaming the folder won't do it so we'll have to rename every single instance from `/home/pi/pi-apps` to `/home/pi/.pi-apps`. What are your views on this @Botspot?

P.S - This issue isn't for functionality or stuff, but completely for looks.

**Comment by Botspot** [comment]
From a programming perspective, this would be super easy as all Pi-Apps scripts don't use a hard-coded folder name. They all use the DIRECTORY variable that is dynamically determined by the script.

For this reason, pi-apps can be installed anywhere on your filesystem.
Renaming the folder would be easy, but I see a major downside: **manual file-editing**.
Pi-Apps welcomes and encourages its users to poke around and learn how it works. To this end, I wrote out an [explanation](https://github.com/Botspot/pi-apps/wiki/Directory-tree) for every single file in the Pi-Apps folder.

I want people to manually edit apps, to open the core scripts and learn how they work, and to make their own changes. Some actions, like using the `data/update-exclusion` file, require manual file-viewing.
Also, many users prefer updating manually: `~/pi-apps/updater`

So if the pi-apps folder was renamed, users would have to _show hidden files_ to browse Pi-Apps files. They would have to change all pi-apps terminal commands they've grown used to, and have to jump through more hoops to learn how Pi-Apps works.

I think making such a change makes some sense, but the downsides for doing it outweigh the improved looks of the file manager.
