### ISSUE TITLE
Github.com won't reply to pings

### ISSUE THREAD

**Issue by nicejs-is-cool** [Botspot/pi-apps#913]
I was trying to install minecraft bedrock on my Raspberry Pi 4
But got this error instead:
```
No internet connection!
github.com failed to respond
Errors: PING github.com (20.201.20.151) 56(84) bytes of data.

--- github.com ping statistics ---
1 packets transmitted, 0 received, 100% packet loss, time 0ms

Close this window to exit.
```
I can confirm that i do have a internet connection, and github does work fine when accessed via the browser i tried to ping it manually with the ping command but it did not work i also tried to ping github.com using my laptop and it also didn't work.
So my theory is github is not replying to pings, So is there any way for me to skip that ping check?
(And yes, rebooting both my router and my Pi didn't work. any other website except github replies to pings correctly)

**Comment by Botspot** [comment]
This is most likely a firewall issue. Someone on our Discord had the same issue until they disabled their router's Firewall.
@nicejs-is-cool, does this command work for you?

```
wget --spider github.com && echo "Succeeded"
```

**Comment by nicejs-is-cool** [comment]
Yes.

**Comment by Botspot** [comment]
> Yes.

Thanks for getting back with me. After trying it myself, I went ahead and [made this change](https://github.com/Botspot/pi-apps/commit/ada99f4258668eb13b845248f766e593628c2667#diff-181229424893bb65d94a74c2132b8b9e5adfe851464fdb5cb9f49e8a8204be7bR24) already.
@nicejs-is-cool, if you haven't updated Pi-Apps, please do so now for the fix to be applied.
