### ISSUE TITLE
Wine says it is disabled

### ISSUE THREAD

**Issue by MrTKusa** [Botspot/pi-apps#914]
You are doing great work, I really appreciate it.  I do have a problem installing "Windows Screensavers". 
 I do not know enough to figure it out.  Please help me.  Thank you so much for your time and kind consideration.

**_My Summary of  environment:_**

[Box86 with Dynarec v0.2.1 aa7b620d built on Apr  7 2021 17:38:04]

          GL4ES found
          Binfmt-magic present: Yes
          interpreter /usr/local/bin/box86
          Latest commit:ea9e9da829b1661f0acf1efc9ab8d025b6fdcf70
          Box86 is out of date. If you are having issues,
          consider updating Box86 using: Menu > Games > UPDATE BOX86

[OpenGL version string: 2.1 Mesa 19.3.2]

          OpenGL vendor string: Broadcom
          direct rendering: Yes
          Linked to libGL.so.1.2.0

[Raspberry Pi 4 Model B Rev 1.4]

          You are on Twister OS version 2.1.2
          Kernel:5.10.17-v7l+ armv7l
          It has 5.8G of free ram.

[wine-5.13]

          linked with: /usr/local/bin/wine
          linktype=> Bourne-Again ASCII text executable
          Prefix:PE32 executable (GUI) Intel 80386, for MS Windows
          Found mono-2.0
          Found Winetricks 20210206

                                                                                                                        

**_Uninstall:_**
***************************************************
API script thinks directory is /home/pi/pi-apps
   \u250f\u2501\u2501\u2501\u2513
\u250f\u2501\u2501\u253b\u2501\u2501\u2501\u253b\u2501\u2501\u2513
\u2503  \u2b1b\u2b1b\u2b1b \u2503  \u2595\u1450 \u2022 \u2581  \u028c
\u2503  \u2b1b\u2b1b\u2b1b \u2503  \u2595  \u2502   \u2571\u203e\u2572\u2595\u1450 \u2595\u1450 \uff33
\u2503  \u2b1b\u2b1b\u2b1b \u2503            \u2595  \u2595
\u2570\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u256f

API script thinks directory is /home/pi/pi-apps
API script thinks directory is /home/pi/pi-apps
Uninstalling Windows Screensavers...

Running purge-installed...
API script thinks directory is /home/pi/pi-apps
Waiting until APT locks are released... Done
Waiting until APT locks are released... Done

Removing dummy deb for Windows Screensavers...

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Reading package lists...
Building dependency tree...
Reading state information...
The following package was automatically installed and is no longer required:
  xprintidle
Use 'sudo apt autoremove' to remove it.
The following packages will be REMOVED:
  pi-apps-4f08f6e7*
0 upgraded, 0 newly installed, 1 to remove and 1 not upgraded.
                                                              After this operation, 0 B of additional disk space will be used.
(Reading database ... 157977 files and directories currently installed.). 
Removing pi-apps-4f08f6e7 (1.0) ...

Autoremoving packages...

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Reading package lists...
Building dependency tree...
Reading state information...
The following packages will be REMOVED:
  xprintidle
0 upgraded, 0 newly installed, 1 to remove and 1 not upgraded.
                                                              After this operation, 21.5 kB disk space will be freed.
(Reading database ... 157977 files and directories currently installed.)
Removing xprintidle (0.2-10) ...
Processing triggers for man-db (2.8.5-2) ...
All packages have been purged succesfully.
Removing directories...
Reloading systemd daemon...

Uninstalled Windows Screensavers successfully.

Closing in 30 seconds.

***************************************************
**_Install:_**
***************************************************
API script thinks directory is /home/pi/pi-apps
   \u250f\u2501\u2501\u2501\u2513
\u250f\u2501\u2501\u253b\u2501\u2501\u2501\u253b\u2501\u2501\u2513
\u2503  \u2b1b\u2b1b\u2b1b \u2503  \u2595\u1450 \u2022 \u2581  \u028c
\u2503  \u2b1b\u2b1b\u2b1b \u2503  \u2595  \u2502   \u2571\u203e\u2572\u2595\u145API script thinks directory is /home/pi/pi-apps
   \u250f\u2501\u2501\u2501\u2513
\u250f\u2501\u2501\u253b\u2501\u2501\u2501\u253b\u2501\u2501\u2513
\u2503  \u2b1b\u2b1b\u2b1b \u2503  \u2595\u1450 \u2022 \u2581  \u028c
\u2503  \u2b1b\u2b1b\u2b1b \u2503  \u2595  \u2502   \u2571\u203e\u2572\u2595\u1450 \u2595\u1450 \uff33
\u2503  \u2b1b\u2b1b\u2b1b \u2503            \u2595  \u2595
\u2570\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u256f

API script thinks directory is /home/pi/pi-apps
API script thinks directory is /home/pi/pi-apps
Installing Windows Screensavers...
API script thinks directory is /home/pi/pi-apps
API script thinks directory is /home/pi/pi-apps
Not installing the Wine (x86) app. IT IS DISABLED.
Running pkg-install...
API script thinks directory is /home/pi/pi-apps
Waiting until APT locks are released... Done
Running sudo apt update...

Creating dummy deb...
Waiting until APT locks are released... Done

Installing dummy deb...
The following additional packages will be installed:
  xprintidle
The following NEW packages will be installed:
  pi-apps-4f08f6e7 xprintidle
0 upgraded, 2 newly installed, 0 to remove and 1 not upgraded.
(Reading database ... 157970 files and directories currently installed.)

Apt finished.
Cloning into 'Screensavers'...
Checking out files: 100% (94/94), done.

Installed Windows Screensavers successfully.

Closing in 30 seconds.
0 \u2595\u1450 \uff33
\u2503  \u2b1b\u2b1b\u2b1b \u2503            \u2595  \u2595
\u2570\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u256f

API script thinks directory is /home/pi/pi-apps
API script thinks directory is /home/pi/pi-apps
Installing Windows Screensavers...
API script thinks directory is /home/pi/pi-apps
API script thinks directory is /home/pi/pi-apps
Not installing the Wine (x86) app. IT IS DISABLED.
Running pkg-install...
API script thinks directory is /home/pi/pi-apps
Waiting until APT locks are released... Done
Running sudo apt update...

Creating dummy deb...
Waiting until APT locks are released... Done

Installing dummy deb...
The following additional packages will be installed:
  xprintidle
The following NEW packages will be installed:
  pi-apps-4f08f6e7 xprintidle
0 upgraded, 2 newly installed, 0 to remove and 1 not upgraded.
(Reading database ... 157970 files and directories currently installed.)

Apt finished.
Cloning into 'Screensavers'...
Checking out files: 100% (94/94), done.

Installed Windows Screensavers successfully.

Closing in 30 seconds.
***********************************************************

**Comment by Itai-Nelken** [comment]
Wine is disabled on TwisterOS as its preinstalled (box86/64 are also disabled).
It does install just fine as your logs show (because box86 and wine are preinstalled).

thanks for asking!
