### ISSUE TITLE
WorldPainter

### ISSUE THREAD

**Issue by irtexo** [Botspot/pi-apps#919]
This app can run on Rpi 4 if Java 7+ is installed

It's an map editor for Minecraft Java

https://www.mediafire.com/file/il3y9yel6jqa6cs/WorldPainter.tar/file

I could not upload a zip cause my xarchiver is broken and github don't accept .tar files

**Comment by Itai-Nelken** [comment]
Sorry it took so much time to review this.

1) the scripts are ok, but while they work the install script should install dependencies (using pi-apps's `pkg-install` script), and the uninstall script should remove them (with pi-apps's `purge-installed`). take a look at [Autostar's install and uninstall scripts](https://github.com/Botspot/pi-apps/tree/master/apps/Autostar) for examples of using `pkg-install` and `purge-installed`
2) in the credits file I think there should be a newline between `Credits to the persons who created pi-apps` and `https://www.worldpainter.net/trac/wiki/Credits`
3) in the description there is no need to mention java 7+ as a dependency as the install script needs to take care of that (1).

**Comment by irtexo** [comment]
1 Sorry i didn't understand how the pkg-install work,but anyways i now the script also install java 11
2 The credits should be good now
3 The description should also be good

[WorldPainter.zip](https://github.com/Botspot/pi-apps/files/7039068/WorldPainter.zip)

**Comment by techcoder20** [comment]
Fixed the install scripts. The [Ulauncher App](https://github.com/Botspot/pi-apps/tree/master/apps/Ulauncher) is a great reference for creating scripts where you just need to download a deb :)
Fixed Zip: [WorldPainter.zip](https://github.com/Botspot/pi-apps/files/7040233/WorldPainter.zip)

**Comment by Botspot** [comment]
How to run this? No menu button is created and there does not appear to be any terminal command used to launch it.

**Comment by irtexo** [comment]
Should be fixed: [WorldPainter.zip](https://github.com/Botspot/pi-apps/files/7046944/WorldPainter.zip)

By the way the command is cd /opt/worldpainter ./worldpainter

**Comment by Botspot** [comment]
> Should be fixed: [WorldPainter.zip](https://github.com/Botspot/pi-apps/files/7046944/WorldPainter.zip)

Looks like your install script tries to create a menu button, but it does not write that text to any file. Therefore, no menu launcher file is created.
