### ISSUE TITLE
Zoom installation fails

### ISSUE THREAD

**Issue by Itai-Nelken** [Botspot/pi-apps#92]
`wget` can't download zoom and exits with `error 403 forbidden`

**Comment by Itai-Nelken** [comment]
it appears to be a bug in the zoom website.
when trying to download from the website, I get this error:
`This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>464F36AE7189B513</RequestId>
<HostId>tzRrNLJ4IVZY6KCvkiJuf0ryZonQg8cDV7Y32GOBofYxIbZHF6Ji+OrkEXenNYDpsA5JnE5Zd7o=</HostId>
</Error>`

**Comment by Itai-Nelken** [comment]
only the linux 32bit downloads are broken, 64 bit works

**Comment by Itai-Nelken** [comment]
installing zoom from pikiss does work

**Comment by Botspot** [comment]
Wow you're right - Zoom's 32bit Linux download link is broken.

I'll have to find someone with an offline copy of it and upload it to an alternative file-hosting service.

Thank you for letting me know.

**Comment by sumanalla** [comment]
i am also facing the same issue.

-Suman.

**Comment by Itai-Nelken** [comment]
@Botspot I have a copy if you need, you need

**Comment by Botspot** [comment]
> @Botspot I have a copy

Thanks for the offer. Turns out I had a local copy too, so it;s almost ready. It's hosted at https://github.com/Botspot/zoom_686_mirror

**Comment by Itai-Nelken** [comment]
![zoom-icon](https://user-images.githubusercontent.com/70802936/99415782-d548f800-2900-11eb-93ec-0a9df2f78f03.png)

taling about zoom, here is the newer icon. personally I think it looks better

**Comment by Botspot** [comment]
Good idea.

**Comment by Itai-Nelken** [comment]
pikiss does install zoom successfully, but I couldn't find from where it downloads zoom

**Comment by Botspot** [comment]
> pikiss does install zoom successfully, but I couldn't find from where it downloads zoom

It downloads it from the zoom website, but from a different URL which still works for the time being. I don't trust the Zoom website anymore, so I've chosen to host it [here](https://github.com/Botspot/zoom_686_mirror) instead.

**Comment by Botspot** [comment]
Okay I've updated Zoom. It should work now.

**Comment by Botspot** [comment]
Can I get a positive confirmation from anybody in order to close the issue?

**Comment by Itai-Nelken** [comment]
just a second, I'm starting vdesktop to check it

**Comment by Botspot** [comment]
> just a second, I'm starting vdesktop to check it

Okay. I'd expect webcam input to fail inside vdesktop. Forewarning.

**Comment by Itai-Nelken** [comment]
oh that's ok, I will only see if it starts and can get into a meeting, I won't be using the camera

**Comment by Botspot** [comment]
> oh that's ok, I will only see if it starts and can get into a meeting, I won't be using the camera

Not sure if/how that will work either inside vdesktop. But as long as it installs okay, it's a success.

**Comment by Itai-Nelken** [comment]
vdesktop isn't working with my usb sd card reader, so I'm booting my other pi, and that might take a bit longer as Ihave to install pi-apps on it

**Comment by Itai-Nelken** [comment]
ok. it downloaded zoom ok, and now is comiling box86

**Comment by Botspot** [comment]
Excellent! I consider that a success.

**Comment by Itai-Nelken** [comment]
zoom starts

**Comment by Itai-Nelken** [comment]
and joining a meeting works
