### ISSUE TITLE
Add rctc

### ISSUE THREAD

**Issue by Khhs167** [Botspot/pi-apps#921]
Can this app run on RPi? If so, please provide a link to a tutorial if applicable.
No tutorial yet...

Is this app something many GUI users would find useful?
Yesnt, it isnt a GUI app, but it is missing a way to install, and i believe GUI would make it easiest

Is this app installable with `sudo apt install`?
no

If you've created a zip file for this app, upload it here.
[rctc-piapps.zip](https://github.com/Botspot/pi-apps/files/7009749/rctc-piapps.zip)

**Comment by Itai-Nelken** [comment]
is this tested?
a few problems: there is no need to clone a repo as root.
the script should install any needed dependencies

**Comment by theofficialgman** [comment]
I'm going to consider this too niche:
```
ReCT (Redcubes epic Compiler Thingy) is a compiler written in C# that compiles a language that is also called ReCT. Development started on the 30th of July 2020.
```
and not very useful for everyday GUI users:
https://github.com/Botspot/pi-apps/issues/185
