### ISSUE TITLE
Add s3tc libraries into x86_32bit bootstrap

### ISSUE THREAD

**Issue by Zenitur** [Botspot/pi-apps#922]
I could start Awesomenauts game using Steam x86_32bit client. I see only splash screen and no texture on "Loading..." picture. After 10-15 seconds, game crashes. It seems like that Mesa hasn't the s3tc support. This is shared lib from the `libtxc-dxtn-s2tc` package.

**Comment by Itai-Nelken** [comment]
This isn't a pi-apps problem. steam is unstable, and there isn't a lot to do. you could try asking in the TwisterOS discord or open a issue in the box86 github.
