### ISSUE TITLE
Update Pycharm

### ISSUE THREAD

**Issue by hmsjy2017** [Botspot/pi-apps#926]
The latest release is `2021.2`.
https://download.jetbrains.com/python/pycharm-community-2021.2.tar.gz

**Comment by Botspot** [comment]
> The latest release is `2021.2`.
> https://download.jetbrains.com/python/pycharm-community-2021.2.tar.gz

You are welcome to edit the download link for your local script and try it out.
If my memory serves me well, I think we had to use an outdated version of Pycharm, in order for it to successfully launch on a Raspberry Pi.

**Comment by hmsjy2017** [comment]
@hmsjy2017 I have tested that the latest version can start normally. But the prerequisite is that Java 11 or higher is installed.

**Comment by Botspot** [comment]
Beta app available for testing:
[Pycharm CE.zip](https://github.com/Botspot/pi-apps/files/7024575/Pycharm.CE.zip)

**Comment by Botspot** [comment]
Pycharm has been updated. https://github.com/Botspot/pi-apps/commit/1bc0d07b3cca604ffccbcc29d217c75655bf2cbe
