### ISSUE TITLE
please make tlauncher (minecraft if you dont have official account)

### ISSUE THREAD

**Issue by xerix123456** [Botspot/pi-apps#927]
when i try to start it it gaves error

**Comment by InternalAardvark** [comment]
im gonna have to agree with ya on this

**Comment by chunky-milk** [comment]
Using Minecraft without an account by using cracked launchers such as tlauncher is illegal... and probably won't be added to pi apps

**Comment by CleanMachine1** [comment]
:+1: Cracked software, software which breaks EULA or Licenses are prohibited most likely here.

1. It looks bad if someone disagree with pirating
2. If the software being cracked devs/minecraft see that promoting pirating, I am sure pi-apps would be deleted pretty quick
