### ISSUE TITLE
obs error

### ISSUE THREAD

**Issue by vince12345678** [Botspot/pi-apps#929]

**Comment by vince12345678** [comment]
OS: Raspbian GNU/Linux 10 (buster)
OS architecture: 32-bit
Pi-Apps local commit ID: 6d8fc50c73896cda20a9ade3a5ace77976afad52
Kernel: armv7l 5.10.52-v7l+
Device model: Raspberry Pi 4 Model B Rev 1.4
Raspberry Pi OS image version: 2021-01-11
Language: en_US.UTF-8

BEGINNING OF LOG FILE:
-----------------------

Uninstalling OBS Studio...

Running purge-installed...
Waiting until APT locks are released... Done
purge-installed: Neither dummy deb nor installed-packages file detected. Nothing to do!
All packages have been purged succesfully.

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Reading package lists...
Building dependency tree...
Reading state information...
Package 'obs' is not installed, so not removed
E: Unable to locate package libfdk-aac2
E: Unable to locate package libfdk-aac-dev
APT failed to purge OBS!

**Comment by Itai-Nelken** [comment]
Is obs installed?

**Comment by vince12345678** [comment]
No

**Comment by Itai-Nelken** [comment]
Then why are you trying to uninstall it?

**Comment by vince12345678** [comment]
It's show corrupted

**Comment by Itai-Nelken** [comment]
Try installing it again.

**Comment by vince12345678** [comment]
Ok, I'll check it out.

**Comment by Botspot** [comment]
> Pi-Apps local commit ID: [6d8fc50](https://github.com/Botspot/pi-apps/commit/6d8fc50c73896cda20a9ade3a5ace77976afad52)

That's the problem right there - your pi-apps installation is 2 weeks out of date!
Additional evidence of this is that your OBS apps `uninstall` script is trying to purge the `obs` package. This behavior [was changed](https://github.com/Botspot/pi-apps/commit/a8c3ce736f8e821170825faf78ed3bca6ab97ecc) 9 days ago.

**Comment by vince12345678** [comment]
Thanks, I'll check it out.
