### ISSUE TITLE
browsh

### ISSUE THREAD

**Issue by Itai-Nelken** [Botspot/pi-apps#93]
[Browsh.zip](https://github.com/Botspot/pi-apps/files/5554419/Browsh.zip)

**Comment by Botspot** [comment]
Awesome! I heard about this browser 2 years ago, but forgot the name and never found it again.

**Comment by mobilegmYT** [comment]
[Browsh.zip](https://github.com/Botspot/pi-apps/files/5557649/Browsh.zip)

**Comment by Botspot** [comment]
Added. Commit acf0193cce6f1df3cbc4e3a70fa4fc81b1fc8ef2

**Comment by Itai-Nelken** [comment]
Great!
