### ISSUE TITLE
Cannot install mac os theme after updating pi apps.

### ISSUE THREAD

**Issue by kerem700916** [Botspot/pi-apps#930]
# The error code
```
This script is made by RPICoder  
Special thanks to Botspot for helping me with the script  
This script will make raspberry pi os look similar to MacOSBigSur 
I am not responsible if anything wrong happens 
Please note that I have not made any of the themes or icons 
Theme made by vinceliuice 
Find the theme at https://github.com/vinceliuice/WhiteSur-gtk-theme.git 
Icons made by yeyushengfan258 
Find the icons at https://github.com/yeyushengfan258/BigSur-icon-theme.git 
Cursors and plank theme made by Macintosh98 
Find the cursors at https://github.com/BigSur-Originals-Cursor.git 
Plank theme and wallpaper make by FKORPSVART
Find the plank theme and wallpapers at https://www.pling.com/p/1399398/ 

Press any key to continue
WARNING! It appears there is already a backup at ~/.local/share/MacOSBigSurThemeConverter/.config_backup. Do you want to overwrite ? [Y/n] y
mkdir: cannot create directory ‘/home/pi/.local/share/MacOSBigSurThemeConverter/.config_backup’: File exists

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Hit:1 http://archive.raspberrypi.org/debian buster InRelease
Hit:2 http://repository.spotify.com stable InRelease
Hit:3 https://itai-nelken.github.io/weekly-box86-debs/debian  InRelease
Get:4 http://raspbian.raspberrypi.org/raspbian buster InRelease [15.0 kB]
Reading package lists...
E: Repository 'http://raspbian.raspberrypi.org/raspbian buster InRelease' changed its 'Suite' value from 'stable' to 'oldstable'
Failed to update apt packages
Failed to run install script

Failed to install Mac OS Theme with install-32 script!
▲ Need help? Copy the ENTIRE terminal output or take a screenshot.
Please ask on Github: https://github.com/Botspot/pi-apps/issues/new/choose
Or on Discord: https://discord.gg/RXSTvaUvuu

Close this window to exit.
```
# Thanks for your time :)

**Comment by Itai-Nelken** [comment]
run `sudo apt update --allow-releaseinfo-change` ([source[(https://www.raspberrypi.org/forums/viewtopic.php?t=245073))
@Botspot maybe make pkg-install do that if it detects that error?

**Comment by kerem700916** [comment]
> run `sudo apt update --allow-releaseinfo-change` ([source](https://www.raspberrypi.org/forums/viewtopic.php?t=245073))
> 
> @Botspot maybe make pkg-install do that if it detects that error?

**Comment by kerem700916** [comment]
Again the same error...

**Comment by Botspot** [comment]
> run `sudo apt update --allow-releaseinfo-change` ([source](https://www.raspberrypi.org/forums/viewtopic.php?t=245073))
> @Botspot maybe make pkg-install do that if it detects that error?

Great job finding that, @Itai-Nelken! This fix has been pushed in commit 949ec131c6fd93e5ff0351becca6935cf2d9c79d.
@kerem700916, Pi-Apps ought to work for you now, and for many others as well.

**Comment by kerem700916** [comment]
Again the same error.

**Comment by Itai-Nelken** [comment]
You updated pi-apps, right?

**Comment by Botspot** [comment]
> Again the same error.

If you haven't updated pi-apps yet, then the recent changes have not taken effect yet.

**Comment by kerem700916** [comment]
@Botspot @Itai-Nelken yes, I updated

**Comment by kerem700916** [comment]
Now I fixed it.
Thanks for your time @Botspot @Itai-Nelken

**Comment by Botspot** [comment]
> I am not sure but I am assuming that this happening due to the migration to debian bullseye.

It is. All systems that use a Raspbian repository receive this error the first time they run `sudo apt update`. As a result, we've received a spike in "error" reports in the past few days. Hopefully the apt flag Itai found will alleviate this for everyone.
