### ISSUE TITLE
Add Atom text editor

### ISSUE THREAD

**Issue by kerem700916** [Botspot/pi-apps#932]

**Comment by Itai-Nelken** [comment]
Duplicate of #617

**Comment by Itai-Nelken** [comment]
@kerem700916 it isn't possible to install atom on the rpi, at least currently.

**Comment by Itai-Nelken** [comment]
Tou could try to compile it if you want, maybe it works now.

**Comment by kerem700916** [comment]
Oh!
My bad

**Comment by kerem700916** [comment]
By the way I'm trying to changing the some apps icon with sudo nano <app pat>. But I can't find the apps path that I downloaded via pi-apps. Can you tell me the apps default directory?

**Comment by Botspot** [comment]
> By the way I'm trying to changing the some apps icon with sudo nano **app path**. But I can't find the apps path that I downloaded via pi-apps. Can you tell me the apps default directory?

~/pi-apps/apps
Learn all about each file in the pi-apps folder [here](https://github.com/Botspot/pi-apps/wiki/Directory-tree).

**Comment by kerem700916** [comment]
Thanks @Botspot @Itai-Nelken

**Comment by ryanfortner** [comment]
I just came across this repository: https://github.com/bcurnow/atom-arm64-pi

I'm not sure if it works but I'll try in a bit.

**Comment by Crilum** [comment]
It appears to me that this doeesn't work:

<i>From the README:</i>
>Wouldn't it be nice if this worked?
