### ISSUE TITLE
Add (if it does not exist) cli based update capabilty...

### ISSUE THREAD

**Issue by CTinMich** [Botspot/pi-apps#938]
Hey Guys,

I would love for you to add (or tell us how) we can run updates strictly from cli.  I use a small utility (RaspController) to launch custom maint commands from my Cell Phone when to lazy to vnc into my raspberry pi.  There seems to be frequent updates on pi-apps and would like to streamline the update process a little bit please :)

**Comment by Itai-Nelken** [comment]
You can run `~/pi-apps/updater` if you want to skip the updater not updating because of the update interval you can either set it to always or run `echo u | ~/pi-apps/updater` (u is just a random character, any will work).
You can also install one of the pi-apps terminal plugins available in pi-apps and then run `pi-apps update`

**Comment by CTinMich** [comment]
Thanks Itai-Nelken, but that does not seem to accomplish my goal.  Trying to do an "un-attended" upgrade.  The command you gave just seems to check for updated files and launches a gui which you have to run to get the actual upgrades started.

**Comment by Itai-Nelken** [comment]
@Botspot can you add a CLI only flag to the updater?

**Comment by Botspot** [comment]
> @Botspot can you add a CLI only flag to the updater?

I've been meaning to do this for a while.

**Comment by Botspot** [comment]
Making steady progress...

**Comment by Botspot** [comment]
I've [re-written](https://github.com/Botspot/pi-apps/commit/c71624b440b6ae87f7b0835ab59a7c3ab5c08097#diff-196c23750e800642e7c008dc0416536449f295069c8161c23283c86334f8d251) the `updater` script. Now it checks for updates 8 times faster, integrates itself in the Pi-Apps main GUI, and supports multiple running-modes.

Updater supports these modes: autostarted, get-status, set-status, gui, gui-yes, cli, cli-yes
The OP of this issue would likely be interested in the `cli` and `cli-yes` modes.

This will list available updates and ask permission to update:
```
~/pi-apps/updater cli
```
This will automatically update without asking permission.
```
~/pi-apps/updater cli-yes
```
Both of these `cli` modes do not launch any dialog boxes, and so should work fine with ssh or in the console.
