### ISSUE TITLE
Dosn't display on FydeOS

### ISSUE THREAD

**Issue by pranavr2003** [Botspot/pi-apps#940]
Pi-Apps doesn't display at all on [FydeOS](https://github.com/FydeOS/chromium_os-raspberry_pi/releases/tag/r92). It just shows a somewhat-something outline and a bunch on no-sense pixels instead. The best part is that it doesn't even come up on a screenshot.

Here's a picture of what it looks like:
![IMG_20210831_105648](https://user-images.githubusercontent.com/54716352/131507737-d35c543b-33ed-4ae9-a409-ad951daf1038.jpg)

Making life difficult cuz Pi-Apps has spoilt me.

Just saw #923. This has more info to reproduce/rectify

**Comment by mobilegmYT** [comment]
Perhaps using CLI for now? `~/pi-apps/manage install "app name goes here"`
