### ISSUE TITLE
Chromium Widevine not playing Widevine?

### ISSUE THREAD

**Issue by pranavr2003** [Botspot/pi-apps#941]
I installed Chromium Widevine via Pi-Apps on a fresh install of RPi-OS.

It's always worked before. It isn't now, for some reason.

![image](https://user-images.githubusercontent.com/56883253/131974142-5a28c12a-4a11-47fc-b88d-14036949cda2.png)

I did a DRM test, but it seems to have a license issue (?)

![image](https://user-images.githubusercontent.com/56883253/131980427-dc4cac4e-a5a7-460d-8bbf-ff1643a52607.png)

**Comment by Botspot** [comment]
What version of Chromium are you using?
```
chromium-browser --version
```
What is the user-agent when browsing websites? (Go to the `chrome://version` page and copy the **User Agent** field)

**Comment by Botspot** [comment]
Okay, never mind. I got the same error too. Investigating.

**Comment by Botspot** [comment]
Looks like this was broken by yesterday's kernel update. :(
https://www.raspberrypi.org/forums/viewtopic.php?f=28&t=318928

**Comment by Botspot** [comment]
Maybe try setting an older Chromium version using my "Downgrade Chromium" app? I do know that Chromium versions lower than **v84** tend to play DRM videos in higher quality.

**Comment by pranavr2003** [comment]
> Maybe try setting an older Chromium version using my "Downgrade Chromium" app? I do know that Chromium versions lower than **v84** tend to play DRM videos in higher quality.

Yeah, I'll try that

**Comment by pranavr2003** [comment]
@Botspot So I try v84 and lower, or lower than v84?

**Comment by pranavr2003** [comment]
@Botspot Doesn't work one bit. It can't go past the Play button.

**Comment by Botspot** [comment]
I tried most of the Chromium versions in a virtual machine. None worked.
A Raspberry Pi moderator/developer says he knows what happened and is trying to fix it. https://www.raspberrypi.org/forums/viewtopic.php?f=63&t=318893&p=1909287#p1909287

**Comment by pranavr2003** [comment]
@Botspot Yeah, you're right. v84 AND below don't work. Same goes for 86 and 88.

**Comment by Botspot** [comment]
This person sums up the situation nicely: https://www.raspberrypi.org/forums/viewtopic.php?p=1909302#p1909340

**Comment by pranavr2003** [comment]
@Botspot Yeah. As of now, [this](https://github.com/HenningThiemann/docker-chromium-armhf) is the best fix I've found.

**Comment by Botspot** [comment]
Do these instructions fix the problem?
https://www.raspberrypi.org/forums/viewtopic.php?p=1910100#p1910100
(Untested and possibly unsafe)

**Comment by pranavr2003** [comment]
@Botspot Yeah I'll test it. Did you try too? Someone says it works, if you move down the thread.

**Comment by pranavr2003** [comment]
@Botspot That actually works without a hitch. Finally, a (temporary, but perfect) Widevine solution is found. Thanks for that mate
