### ISSUE TITLE
[App Request] Minetest

### ISSUE THREAD

**Issue by MegaTKC** [Botspot/pi-apps#944]
Can this app run on RPi? If so, please provide a link to a tutorial if applicable.
Yes. [https://www.minetest.net/downloads/](Minetest.net)
Is this app something many GUI users would find useful?
Not really, I would say it is a game. But, if people would like to play an open source version of Minecraft it is there for you to do so.
There are many features and it is still updated to this day.
Is this app installable with `sudo apt install`?
Yes, it is, but I don't think that it is the latest version of the game though.
If you've created a zip file for this app, upload it here.

**Comment by Botspot** [comment]
#546

**Comment by Botspot** [comment]
The issue I had with minetest was that the frame-rate was too slow on the Pi4 to really be usable.
