### ISSUE TITLE
Request for vdesktop files

### ISSUE THREAD

**Issue by C-EO** [Botspot/pi-apps#945]
Hi Botspot!
I was wondering if you would help send me the [vdesktop](github.com/Botspot/vdesktop) files.
I would like to add it to my version of pi-apps located [here](github.com/C-EO/AppPlay).
I am only asking because:
- I want to add it to my version pi-apps.
- I don't have any install scripts for it.
- I don't have its logo files.
I would appreciate if you send it very soon.
You can open an [issue](github.com/C-EO/AppPlay/issues/new/choose) and attacht the .zip file onto the app/feature request template.

Thanks,
C-EO

**Comment by oxmc** [comment]
I'm confused, what do you mean by files? Do you mean the install and
uninstall scripts vdesktop?

**Comment by Botspot** [comment]
Vdesktop does not have a logo.

Pi-Power-Tools includes vdesktop, and can be considered a gui frontend for vdesktop. (See my biography)

**Comment by C-EO** [comment]
Thanks for the help.
