### ISSUE TITLE
Sysmon

### ISSUE THREAD

**Issue by chunky-milk** [Botspot/pi-apps#951]
https://github.com/t0xic0der/sysmon

System monitoring accessible via a web browser.

Guide to installing: https://github.com/chunky-milk/sysmon-rpi

I'll write scripts when I have time.

**Comment by chunky-milk** [comment]
Install scripts: 
[Sysmon.zip](https://github.com/Botspot/pi-apps/files/7179779/Sysmon.zip)

**Comment by Botspot** [comment]
> there is no icon for the software.

In the browser, there appears to be some sort of icon.
![2021-09-19-231343_1920x1080_scrot](https://user-images.githubusercontent.com/54716352/133956613-9f593397-70c1-4ba6-a644-2f9d1b0ae0fd.png)

**Comment by Botspot** [comment]
Found it. http://localhost:6969/static/imgs/sysmon.svg

**Comment by Botspot** [comment]
This app has been added to Pi-Apps.
Commit: https://github.com/Botspot/pi-apps/commit/9a6ef6473b64ccb1bf44415f72b178fe6333caff
