### ISSUE TITLE
Simplify scripts for all apps

### ISSUE THREAD

**Issue by Jai-JAP** [Botspot/pi-apps#952]
https://github.com/Botspot/pi-apps/blob/15c6037244281c6aa8d17b2aeccd9413c134075a/manage#L17-L18

as per above snip now pi-apps `manage` script makes all functions in `api` available to all the install and uninstall scripts
and the api script has the error function as below

https://github.com/Botspot/pi-apps/blob/15c6037244281c6aa8d17b2aeccd9413c134075a/api#L3-L6

so it will be good to remove the below part from all the scripts

https://github.com/Botspot/pi-apps/blob/15c6037244281c6aa8d17b2aeccd9413c134075a/apps/template/install#L5-L8

**Comment by Botspot** [comment]
That makes sense, but I still intend for the apps to be able to be run standalone.

For example, my [rpi-flashplayer](https://github.com/Botspot/rpi-flashplayer) project [runs](https://github.com/Botspot/rpi-flashplayer/blob/main/install.sh#L9) a pi-apps script without ever downloading pi-apps.

**Comment by Botspot** [comment]
The only reason I've made the `api`'s functions available to the apps is for the `wget` function (which translates wget command-syntax to `aria2c` syntax)
