### ISSUE TITLE
Rust app

### ISSUE THREAD

**Issue by Zuygui** [Botspot/pi-apps#956]
Hello i want to post my rust language support for pi-apps.

[Rust.zip](https://github.com/Botspot/pi-apps/files/7186714/Rust.zip)

**Comment by Botspot** [comment]
Thank you for your app-submission.
I found a few ways your `install` script could be improved. Below is the script after I changed it to be pi-apps-compliant.
```
#!/bin/bash

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

# instructions
echo "Select second option,
  default host triple: armv7-unknown-linux-gnueabihf
  default toolchain: stable (default)
  profile: default\n
  modify PATH variable: yes"

wget -qO- https://sh.rustup.rs | sh || error "rust installation script failed!"
```
Unfortunately, your `uninstall` script does nothing. It does not uninstall Rust. Could this be improved?

**Comment by Zuygui** [comment]
Sorry I am french développer and i not make an uninstall script because an 
apt purge résolve this problem

**Comment by Zuygui** [comment]
For uninstall: the script is here:

```
sudo apt purge rust

**Comment by cycool29** [comment]
> We'll re-open this issue if a way to **uninstall** rust becomes available.

```
rustup self uninstall
```

[Source](https://stackoverflow.com/questions/52045966/how-to-uninstall-rust-that-was-installed-via-rustup).

**Comment by Zuygui** [comment]
Yes

**Comment by Itai-Nelken** [comment]
Rust isn't something most GUI users will find useful which is a requirement for apps in pi-apps.
because of that I don't think it can be added.
