### ISSUE TITLE
Pi-Apps is not not supported on non-arm processor architectures like amd64 and i386.

### ISSUE THREAD

**Issue by ImiTheDev** [Botspot/pi-apps#957]
Hi,
I am using my old laptop and installed Debian Buster with Raspberry Pi Desktop (Release date: January 11th 2021) on it. While installing Pi Apps, the installation process stopped with the below error message so I uninstalled and deleted anything related to Pi Apps. I take it it's the OS that is not compatible however, would be great to have this fixed if possible so I can use the great apps in the future. Thanks!

```
pi@raspberry:~ $ ~/pi-apps/install
Pi-Apps is not not supported on non-arm processor architectures like amd64 and i386. You may be interested in Pi-Apps x86, a unofficial fork of Pi-Apps for x64 and x86 systems: https://github.com/Pi-Apps-Recreates/pi-apps-x86
pi@raspberry:~ $ ^C
pi@raspberry:~ $ git clone https://github.com/Botspot/pi-apps
fatal: destination path 'pi-apps' already exists and is not an empty directory.
pi@raspberry:~ $ ~/pi-apps/install
Pi-Apps is not not supported on non-arm processor architectures like amd64 and i386. You may be interested in Pi-Apps x86, a unofficial fork of Pi-Apps for x64 and x86 systems: https://github.com/Pi-Apps-Recreates/pi-apps-x86
pi@raspberry:~ $ ~/pi-apps/uninstall
Removing menu button...
Removing terminal command...
Uninstallation complete. Only /home/pi/pi-apps still remains.
If Pi-apps didn't work for you, PLEASE consider submitting a bug report!
--> https://github.com/Botspot/pi-apps/issues/new
```

**Comment by Itai-Nelken** [comment]
This part of the error:
> You may be interested in Pi-Apps x86, a unofficial fork of Pi-Apps for x64 and x86 systems: https://github.com/Pi-Apps-Recreates/pi-apps-x86

**Comment by Itai-Nelken** [comment]
Its not the OS that is incompatible, its your CPU. Pi-apps is made for the raspberry pi and specifically the model 4. The rpi has a ARM cpu, and your laptop has a i386 or amd64 CPU. Most of the software on pi-apps is available natively for x86 and is easily installable.

**Comment by Itai-Nelken** [comment]
Closing as pi-apps won't be ported officially to x86 for now. you can use Pi-Apps x86 if you want pi-apps on your laptop.
