### ISSUE TITLE
T-Launcher (Custom Minecraft Launcher with Microsoft Migration)

### ISSUE THREAD

**Issue by KolpixTV** [Botspot/pi-apps#958]
TLauncher is very known because it support cracked Minecraft Players but also it support Microsoft Migrated Accounts and normal Mojang Accounts and some more Types of Accounts.
I did not get Minecraft Versions over 1.12.2 work if someone can do it please say how. Also i don't tested it on a fresh installation of Raspberry Pi OS it would be nice if someone can test it.

Is this app installable with `sudo apt install`?

No it's not.

If you've created a zip file for this app, upload it here.
[Minecraft (TLauncher).zip](https://github.com/Botspot/pi-apps/files/7190392/Minecraft.TLauncher.zip)

**Comment by mobilegmYT** [comment]
We are in the final stages of deploying a new launcher, and tlauncher is illegal no matter what :p

**Comment by Botspot** [comment]
@KolpixTV, This issue is being closed because we require everything on Pi-Apps to be legal.

If you can prove that Tlauncher is indeed legal, the issue can be re-opened.

**Comment by KolpixTV** [comment]
TLauncher is not illegal provided that you have purchased Minecraft Java Edition on Mojang's website. If you are using TLauncher to play Minecraft for free, you are committing piracy, which is illegal in most parts of the world.

**Comment by mobilegmYT** [comment]
But the thing is, tlauncher itself still CAN be used to commit piracy,
which is illegal

**Comment by KolpixTV** [comment]
Oh okay.
