### ISSUE TITLE
Ask before removing dependencies

### ISSUE THREAD

**Issue by Itai-Nelken** [Botspot/pi-apps#96]
example:
lets say someone uses Firefox-esr as his main browser on his pi, and he uninstalls browsh and that removes firefox. he won't understand where firefox, and that can be annoying.

**Comment by Botspot** [comment]
Actually, that's exactly what Pi-Apps does!

In the case of Browsh, you can see that I'm not using `apt` to install firefox-esr, I'm using `pkg-install` on [line 11](https://github.com/Botspot/pi-apps/blob/master/apps/Browsh/install-32#L11).  
`Pkg-install` remembers which packages each app installs, so when you [uninstall](https://github.com/Botspot/pi-apps/blob/master/apps/Browsh/uninstall#L14) that app, Pi-Apps will only uninstall the packages that app originally installed.

So if you installed firefox-esr prior to installing Browsh, then when uninstalling Browsh, it should have left firefox-esr intact.

Make sense?

**Comment by Itai-Nelken** [comment]
actually yes, I didn't understand that part of the code.
