### ISSUE TITLE
Unable to run Zoom

### ISSUE THREAD

**Issue by cycool29** [Botspot/pi-apps#962]
![zoom](https://user-images.githubusercontent.com/88134003/134132419-f4a81de5-c7e0-474a-9122-a9f33b988b9f.png)

When I launch Zoom from menu bar, it stucks here and I have been waiting for 30 minutes, remain same screen.

Tried:
- Reinstalling Zoom and Box86
- Uninstall Zoom PWA 
- `sudo rm -rf ~/.config/*zoom* *Zoom*`
- Reboot
- Build Box86 manually
- `sudo apt purge box86 -y && sudo apt install box86`

**Comment by Botspot** [comment]
- What operating system are you using?
- Does this command succeed?
`sudo systemctl restart systemd-binfmt`
- Try running this: `cd ${HOME}/zoom ; box86 zoom`
- If that doesn't work, try adding "`./`" to the beginning of the word "zoom" and see if that changes anything.

**Comment by OishiiCha** [comment]
I am also having the same issue, it just hangs like that.

Running RPI4 8GB

> - What operating system are you using?
Raspbian 10

> - Does this command succeed?
> `sudo systemctl restart systemd-binfmt`
Systemd-binfmt not found

> - Try running this: `cd ~/zoom ; box86 zoom`
Just hangs with the text in the original image

> - If that doesn't work, try this: `cd ~/zoom ; box86 ./zoom`
> 
Same as above

**Comment by Botspot** [comment]
> > * Does this command succeed?
> >   `sudo systemctl restart systemd-binfmt`
> 
> Systemd-binfmt not found

Now that's interesting. When was the last time you updated?
What happens when you install binfmt?
```
sudo apt install binfmt-support
```

**Comment by Botspot** [comment]
> > What happens when you install binfmt?
> > ```
> > sudo apt install binfmt-support
> > ```
> 
> Installed it

Strange. I'm guessing either you removed the package earlier, or you started with Raspberry Pi OS Lite.

> however the message was still the same when opening the zoom application

Try reinstalling Box86.

**Comment by OishiiCha** [comment]
Tried to reinstall box86, issue persists

**Comment by Botspot** [comment]
> Tried to reinstall box86, issue persists

Please run these commands and reply back with the full output:
```
cd ~/zoom
BOX86_LOG=1 box86 ./zoom
```

**Comment by Botspot** [comment]
Update: I just tried my own suggestion and have been able to reproduce the issue.

Downgrading Box86 appears to fix it:
```
sudo apt install box86-no-binfmt-restart=0.2.3+20210917.9190a20c-1
```

**Comment by cycool29** [comment]
> * What operating system are you using?

Latest Raspbian 32bit

> * Does this command succeed?
`sudo systemctl restart systemd-binfmt`

Yes, and `sudo systemctl status systemd-binfmt` shows `active`

> * Try running this: `cd ~/zoom ; box86 zoom`
> * If that doesn't work, try this: `cd ~/zoom ; box86 ./zoom`

Both just hang with the text



> > Tried to reinstall box86, issue persists
> 
> Please run these commands and reply back with the full output:
> 
> ```
> cd ~/zoom
> BOX86_LOG=1 box86 ./zoom
> ```

Output for the command:
```
Debug level is 1
Dynarec for ARM, with extension: HALF FAST_MULT EDSP NEON VFPv4 IDIVA PageSize:4096
Box86 with Dynarec v0.2.3 6afddae6 built on Sep 19 2021 12:24:29
Using default BOX86_LD_LIBRARY_PATH: ./:lib/:lib32/:x86/
Using default BOX86_PATH: ./:bin/
Counted 57 Env var
Looking for ./zoom
Zoom detected, trying to use system libturbojpeg if possible
Using native(wrapped) libdl.so.2
Using native(wrapped) libX11.so.6
Using native(wrapped) librt.so.1
Using native(wrapped) libxcb.so.1
Using native(wrapped) libXext.so.6
Using native(wrapped) libXau.so.6
Using native(wrapped) libXdmcp.so.6
Using native(wrapped) libxcb-xfixes.so.0
Using native(wrapped) libxcb-shape.so.0
Using native(wrapped) libxcb-shm.so.0
Using native(wrapped) libxcb-randr.so.0
Using native(wrapped) libxcb-image.so.0
Using native(wrapped) libxcb-keysyms.so.1
Using native(wrapped) libxcb-xtest.so.0
Using native(wrapped) libXfixes.so.3
Using native(wrapped) libXtst.so.6
Using native(wrapped) libglib-2.0.so.0
Using native(wrapped) libdbus-1.so.3
Using emulated libQt5Quick.so.5
Using emulated libQt5Widgets.so.5
Using emulated libQt5Gui.so.5
Using emulated libQt5Qml.so.5
Using emulated libQt5Network.so.5
Using emulated libQt5Script.so.5
Using emulated libQt5DBus.so.5
Using emulated libQt5Core.so.5
Using native(wrapped) libGL.so.1
Using native(wrapped) libpthread.so.0
Using emulated /lib/i386-linux-gnu/libstdc++.so.6
Using native(wrapped) libm.so.6
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux.so.2
Using emulated /lib/i386-linux-gnu/libgcc_s.so.1
Using emulated libicui18n.so.54
Using emulated libicuuc.so.54
Using emulated libicudata.so.54
Using native(wrapped) libgthread-2.0.so.0
Using global g_threads_got_initialized for gthread2 (0xbedd7c5c:0x62eafed0)
Using native(wrapped) libgobject-2.0.so.0
```
Then it just hang here.

**Comment by Botspot** [comment]
> Then it just hang here.

@cycool29 As I said above, downgrading box86 seems to fix the problem.
This command will do that for you:
```
sudo apt install box86-no-binfmt-restart=0.2.3+20210917.9190a20c-1
```

**Comment by cycool29** [comment]
> > Then it just hang here.
> 
> @cycool29 As I said above, downgrading box86 seems to fix the problem.
> This command will do that for you:
> 
> ```
> sudo apt install box86-no-binfmt-restart=0.2.3+20210917.9190a20c-1
> ```
> 
> I am actively communicating with the developers to try to fix the problem.

Thanks, this fixed the issue! So it is the problem of box86.

**Comment by cycool29** [comment]
@Botspot The box86 dev updated the repo and now the issue fixed.
@Itai-Nelken Please compile box86 again and update your apt repo.

**Comment by cycool29** [comment]
@Itai-Nelken

**Comment by Itai-Nelken** [comment]
I know, but I'm not near the pi that builds so I can't trigger a build. the next automatic one is on sunday.

**Comment by cycool29** [comment]
[Itai's repo](https://github.com/Itai-Nelken/weekly-box86-debs) has compiled and updated the box86, works for me. 
As this, closing.
