### ISSUE TITLE
Node.js Current Version

### ISSUE THREAD

**Issue by 1Spinne** [Botspot/pi-apps#964]
I made an app, that installs the current version of Node.js not the recommended.
[Node.js Current.zip](https://github.com/Botspot/pi-apps/files/7211417/Node.js.Current.zip)

**Comment by Botspot** [comment]
It appears the only change you made is by changing `nvm install --lts` to `nvm install node`.
Could you explain how this change makes a newer version of Node.js install?

**Comment by Botspot** [comment]
I just ran `nvm --help` and the content seems to answer my question:

>   nvm install node                      Install the latest available version
  nvm use node                          Use the latest version
  nvm install --lts                     Install the latest LTS version
  nvm use --lts                         Use the latest LTS version

**Comment by Botspot** [comment]
This change has been uploaded in https://github.com/Botspot/pi-apps/commit/f2a740f3920d1ea63f2d3bebe79e8513e923b4b5
