### ISSUE TITLE
pycharm

### ISSUE THREAD

**Issue by azza25** [Botspot/pi-apps#967]
Can this app run on RPi? If so, please provide a link to a tutorial if applicable.

Is this app something many GUI users would find useful?

Is this app installable with `sudo apt install`?

If you've created a zip file for this app, upload it here.

**Comment by cycool29** [comment]
What is your question? 
You can install PyCharm in pi-apps, did you face any trouble when you installing it?

**Comment by Itai-Nelken** [comment]
If this is a app request - pycharm is already on pi-apps as `PyCharm CE` (the free community edition).\

**Comment by cycool29** [comment]
I think this can be closed since there is no response from the author.
