### ISSUE TITLE
Minecraft crashes

### ISSUE THREAD

**Issue by Crazily** [Botspot/pi-apps#97]
Hi. On Ubuntu Minecraft crashes if the PI is overclocked by more than ~ 100mhz or so. Even though it runs perfectly fine in retropi like that. Thanks.

**Comment by Botspot** [comment]
So if you don't overclock your Pi, it works fine? Then don't overclock your Pi!

As for why it works fine on Retropie but not here: Retropie's version of Minecraft may be different or does't tax the CPU as much. Many factors could cause it.
