### ISSUE TITLE
Notepad++ failing to install

### ISSUE THREAD

**Issue by khadij-hasan86** [Botspot/pi-apps#970]
i'm facing issues in installing apps on my RPI 4
![2021-09-24_15-43](https://user-images.githubusercontent.com/91321724/134664954-ef5211a0-ff89-4e9a-af3f-95439bdf19d0.png)

**Comment by Botspot** [comment]
This is an issue with your Raspberry Pi's configuration. Pi-Apps did not cause this error.

In this case, I suggest you ask for help on [the Raspberry Pi Forums](https://www.raspberrypi.org/forums/).
