### ISSUE TITLE
Submiting Godot updated+64 bits support

### ISSUE THREAD

**Issue by irtexo** [Botspot/pi-apps#972]
Updated Godot Rpi support 1.5 and Godot version to 3.3.3
Also changed the install-32 to install since this version supports 32 and 64 bit

https://github.com/Botspot/pi-apps/files/7231729/Godot_1.5.0-3.3.3_64b.zip

**Comment by Botspot** [comment]
Thanks! :)

**Comment by Ratteler** [comment]
64 Bit installed, but doesn't seem to start?

**Comment by theofficialgman** [comment]
@irtexo @Botspot looks like nobody actually fact checked this
this is very much still a arm 32bit binary and should be disabled on arm64
```
ELF 32-bit LSB executable, ARM, EABI5 version 1 (GNU/Linux), dynamically linked, interpreter /lib/ld-linux-armhf.so.3, for GNU/Linux 5.9.0, stripped
```
I have disabled it
