### ISSUE TITLE
Wor flasher error triggering bios screen

### ISSUE THREAD

**Issue by SnarkyDeveloper** [Botspot/pi-apps#975]
This is what I got when running after successful  installation environment.

![Pi Issue #4-092621](https://user-images.githubusercontent.com/91441703/134832057-6959ffc7-c86f-4bf3-b119-bdf3680f7d7d.jpeg)
![Pi Issue #3-092621](https://user-images.githubusercontent.com/91441703/134832058-e6db993f-b143-4e2a-9d8d-dc9686ef6b3c.jpeg)

**Comment by cycool29** [comment]
From the error code `0xc00005`:
> 0xc0000005 as Windows installation error. This error can be caused due to your RAM or your hard drive being defective. You can use the chkdsk utility to fix the error and delete all partitions already existing on the hard drive.  

`INACCESSIBLE_BOOT_DEVICE`
> INACCESSIBLE BOOT DEVICE BSOD reflects some kind of issue with a Windows installation’s designated boot device. When this error occurs, it means that the Windows file system tried to read the boot device and failed. Most often, this means the boot device failed to initialize. 

Seems that is your boot device problem.

Did you try reinstalling WoR?
Where did you installed it? (SD card, USB, etc)

**Comment by Botspot** [comment]
What bootloader version is your Pi using? What version of Windows is this?

**Comment by rbcoder117** [comment]
> From the error code `0xc00005`:
> 
> > 0xc0000005 as Windows installation error. This error can be caused due to your RAM or your hard drive being defective. You can use the chkdsk utility to fix the error and delete all partitions already existing on the hard drive.
> 
> `INACCESSIBLE_BOOT_DEVICE`
> 
> > INACCESSIBLE BOOT DEVICE BSOD reflects some kind of issue with a Windows installation’s designated boot device. When this error occurs, it means that the Windows file system tried to read the boot device and failed. Most often, this means the boot device failed to initialize.
> 
> Seems that is your boot device problem.
> 
> Did you try reinstalling WoR?
> Where did you installed it? (SD card, USB, etc)

Thanks! I’ll see if reinstalling WoR works.
I installed it on a 1.8T external hard drive

**Comment by rbcoder117** [comment]
> What bootloader version is your Pi using? What version of Windows is this?

I’m using the newest version of Debian lite and it is Windows 11

**Comment by Botspot** [comment]
> > What bootloader version is your Pi using? What version of Windows is this?
> 
> I’m using the newest version of Debian lite and it is Windows 11

Please run this command on your Pi4 to check if the bootloader is up to date:
```
sudo rpi-eeprom-update
```

**Comment by rbcoder117** [comment]
Ok

**Comment by rbcoder117** [comment]
> > > What bootloader version is your Pi using? What version of Windows is this?
> > 
> > 
> > I’m using the newest version of Debian lite and it is Windows 11
> 
> Please run this command on your Pi4 to check if the bootloader is up to date:
> 
> ```
> sudo rpi-eeprom-update
> ```

I ran this and it was up to date. I updated my packages and ran a full test and it didn’t work

**Comment by rbcoder117** [comment]
It gave me the error code “[WARNING] Ignoring extended attributes of 1 file(use -unix-data mode to extract these)” when boot.wim was downloading in the install script.

**Comment by rbcoder117** [comment]
plz reply to error https://github.com/Botspot/pi-apps/issues/975 @Botspot

**Comment by Botspot** [comment]
@rbcoder117 What SD card are you using and how fast is it? Windows is especially picky about disk speed and performance, much more picky than Linux is.
We have multiple documented cases where someone's SD card was too slow, causing a variety of random boot errors and blue screens.
