### ISSUE TITLE
broken repository on ubuntu-mate

### ISSUE THREAD

**Issue by nilmarsh555** [Botspot/pi-apps#977]
pi-apps not installing on ubuntu-mate 64 bit.
Error:
```
$ ~/pi-apps/install
Hit:1 http://ppa.launchpad.net/lah7/ubuntu-mate-colours/ubuntu focal InRelease 
Hit:2 http://ports.ubuntu.com/ubuntu-ports focal InRelease                     
Hit:3 http://ppa.launchpad.net/ubuntu-pi-flavour-makers/ppa/ubuntu focal InRelease
Hit:4 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease
Hit:5 http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease
Ign:6 http://ppa.launchpad.net/webupd8team/atom/ubuntu focal InRelease
Err:7 http://ppa.launchpad.net/webupd8team/atom/ubuntu focal Release
  404  Not Found [IP: 91.189.95.85 80]
Reading package lists... Done
E: The repository 'http://ppa.launchpad.net/webupd8team/atom/ubuntu focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
The command 'sudo apt update' failed. Before Pi-Apps will work, you must fix your apt package-management system.
```

**Comment by cycool29** [comment]
1. I think that is your `sources.list` problem, as the last line of error said, `The command 'sudo apt update' failed. Before Pi-Apps will work, you must fix your apt package-management system.` The error should be at the `atom` PPA as the `sudo apt update` just ignored it. [Here](https://askubuntu.com/questions/866901/what-can-i-do-if-a-repository-ppa-does-not-have-a-release-file) is the Ask Ubuntu post to solve the PPA problem.

2. `pi-apps not installing on ubuntu-mate 64 bit.` Are you installing pi-apps on x64 system? Do you mean `arm64` or `aarch64`? Pi-Apps is designed for ARM devices only.

**Comment by nilmarsh555** [comment]
arm64

**Comment by Botspot** [comment]
> ```
> The command 'sudo apt update' failed. Before Pi-Apps will work, you must fix your apt package-management system.
> ```

That final error message makes the problem pretty clear. Basically, your operating system is not configured correctly and it's not Pi-Apps's fault.
In this case, your system appears to have a broken software repository: `http://ppa.launchpad.net/webupd8team/atom/ubuntu`
Either you can try to fix it (use Google), or you can remove the repository.

## To remove the repository:
APT repositories are located in two places:

- A single **line** in the text **file** located at `/etc/apt/sources.list`
- A single **file** in the **folder** located at `/etc/apt/sources.list.d`

Be careful. Try to look through sources.list first and look for any lines that mention "`webupd8team/atom/ubuntu`". If you don't see any, look inside all the files in sources.list.d and see if any of them mention "`webupd8team/atom/ubuntu`".
When you find the right line, delete it and then save the file.
Alternatively, if the entire file _only_ contains stuff for "`webupd8team/atom/ubuntu`", you could delete the whole file if you wanted to.

*Note: Modifing files in the /etc directory require root privileges. This can be accomplished by using `sudo`.

**Comment by cycool29** [comment]
Hmm @nilmarsh555 is this issue solved?

**Comment by cycool29** [comment]
You may close the issue now :)
