### ISSUE TITLE
Roblox (Its ok if its glitchy and this is a app request)

### ISSUE THREAD

**Issue by robloxboy24** [Botspot/pi-apps#98]
I would like roblox because I can only play games after school and my comupter is only for school so I need roblox to be on my raspberry pi

**Comment by mobilegmYT** [comment]
This is quite impossible because Roblox doesn't compile their client for armv7l.

**Comment by Botspot** [comment]
Remember: Pi-Apps is just a convenient app installer. That's it.

So before an app can be put on Pi-Apps, it has to work by itself, without Pi-Apps. So, if you can find a way to run "roblox" on your Pi, and it works well and isn't illegal, then I may consider adding it to Pi-Apps.
