### ISSUE TITLE
Can't Install pi-apps

### ISSUE THREAD

**Issue by RockZombie123** [Botspot/pi-apps#981]
So I've recently tried to install pi-apps using:

`git clone https://github.com/Botspot/pi-apps`
and it cloned, but when I used:

` /home/pi/pi-apps/install`
it gave me this error:

`The command 'sudo apt update' failed. Before Pi-Apps will work, you must fix your apt package-management system.`
And I even tried manually updating using:

`wget http://archive.raspbian.org/raspbian/pool/main/n/nettle/libnettle6_3.4.1-1_armhf.deb`
but that gave me a 404 not found error!

and of course if I used:

` sudo dpkg -i libnettle6_3.4.1-1_armhf.deb`
It would obviously give me an error:

`dpkg: error: cannot access archive 'libnettle6_3.4.1-1_armhf.deb': No such file or directory`
I hope someone can help me or Botspot could fix this...

**Comment by Botspot** [comment]
> I hope someone can help me or Botspot could fix this...

This is not the kind of thing I can fix - it's a problem with your system that was there before you installed Pi-Apps.

What is the full output of `sudo apt update`?

**Comment by RockZombie123** [comment]
The full output of sudo apt update was:

```
Get:1 http://archive.raspberrypi.org/debian buster InRelease [32.6 kB]
Get:2 http://raspbian.raspberrypi.org/raspbian buster InRelease [15.0 kB]
Ign:3 http://mirrordirector.raspbian.org/raspbian wheezy InRelease
Err:4 http://mirrordirector.raspbian.org/raspbian wheezy Release
 404 Not Found [IP: 2a00:1098:0:80:1000:75:0:3 80]
Hit:5 http://www.deb-multimedia.org stable InRelease
Reading package lists... Done
E: Release file for http://raspbian.raspberrypi.org/raspbian/dists/buster/InRelease is not valid yet (invalid for another 1h 1min 30s). Updates for this repository will not be applied.
E: The repository 'http://mirrordirector.raspbian.org/raspbian wheezy Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
E: Release file for http://archive.raspberrypi.org/debian/dists/buster/InRelease is not valid yet (invalid for another 3h 48min 41s). Updates for this repository will not be applied.

```

**Comment by cycool29** [comment]
Again, that is your source list problem.
Why you are using both `buster` and `wheezy` mirror?
Try `sudo apt edit-sources` and delete `http://mirrordirector.raspbian.org/raspbian wheezy InRelease` and `http://mirrordirector.raspbian.org/raspbian wheezy Release` . 
If you can't find them there, check in `/etc/apt/sources.list.d` .

> The full output of `sudo apt update` was:
> 
> ```
> Get:1 http://archive.raspberrypi.org/debian buster InRelease [32.6 kB]
> Get:2 http://raspbian.raspberrypi.org/raspbian buster InRelease [15.0 kB]
> Ign:3 http://mirrordirector.raspbian.org/raspbian wheezy InRelease
> Err:4 http://mirrordirector.raspbian.org/raspbian wheezy Release
>  404 Not Found [IP: 2a00:1098:0:80:1000:75:0:3 80]
> Hit:5 http://www.deb-multimedia.org stable InRelease
> Reading package lists... Done
> E: Release file for http://raspbian.raspberrypi.org/raspbian/dists/buster/InRelease is not valid yet (invalid for another 1h 1min 30s). Updates for this repository will not be applied.
> E: The repository 'http://mirrordirector.raspbian.org/raspbian wheezy Release' does not have a Release file.
> N: Updating from such a repository can't be done securely, and is therefore disabled by default.
> E: Release file for http://archive.raspberrypi.org/debian/dists/buster/InRelease is not valid yet (invalid for another 3h 48min 41s). Updates for this repository will not be applied.
> ```

**Comment by cycool29** [comment]
> The full output of `sudo apt update` was:
> 
> ```
> Get:1 http://archive.raspberrypi.org/debian buster InRelease [32.6 kB]
> Get:2 http://raspbian.raspberrypi.org/raspbian buster InRelease [15.0 kB]
> Ign:3 http://mirrordirector.raspbian.org/raspbian wheezy InRelease
> Err:4 http://mirrordirector.raspbian.org/raspbian wheezy Release
>  404 Not Found [IP: 2a00:1098:0:80:1000:75:0:3 80]
> Hit:5 http://www.deb-multimedia.org stable InRelease
> Reading package lists... Done
> E: Release file for http://raspbian.raspberrypi.org/raspbian/dists/buster/InRelease is not valid yet (invalid for another 1h 1min 30s). Updates for this repository will not be applied.
> E: The repository 'http://mirrordirector.raspbian.org/raspbian wheezy Release' does not have a Release file.
> N: Updating from such a repository can't be done securely, and is therefore disabled by default.
> E: Release file for http://archive.raspberrypi.org/debian/dists/buster/InRelease is not valid yet (invalid for another 3h 48min 41s). Updates for this repository will not be applied.
> ```

Again, that is your source list problem.
Why you are using both `buster` and `wheezy` mirror?
Try `sudo apt edit-sources` and delete http://mirrordirector.raspbian.org/raspbian wheezy InRelease and http://mirrordirector.raspbian.org/raspbian wheezy Release .
If you can't find them there, check in /etc/apt/sources.list.d .

**Comment by RockZombie123** [comment]
@cycool29 Thanks! I think I'm going to try out that command!

**Comment by RockZombie123** [comment]
When I tried: `sudo apt edit-sources`, it didn't give me an error, but it didn't show http://mirrordirector.raspbian.org/raspbian wheezy Release. 

This is what it showed instead:

```
deb http://raspbian.raspberrypi.org/raspbian/ buster main contrib non-free rpi
#Uncomment the line below then 'apt-get update' to enable 'apt-get source'
#deb-src http://raspbian.raspberrypi.org/raspbian/ buster main contrib non-free rpi
deb http://www.deb-multimedia.org stable main
```

**Comment by cycool29** [comment]
What about `cd /etc/apt/sources.list.d && ls` ?

**Comment by RockZombie123** [comment]
@cycool29 It changed my directory...

**Comment by cycool29** [comment]
What is the output of `cat /etc/apt/sources.list.d/raspbian-src.list`?

**Comment by RockZombie123** [comment]
`deb-src http://mirrordirector.raspbian.org/raspbian/ wheezy main contrib non-free rpi`

**Comment by cycool29** [comment]
> `deb-src http://mirrordirector.raspbian.org/raspbian/ wheezy main contrib non-free rpi`


This file should be the problem. Try `sudo rm -f /etc/apt/sources.list.d/raspbian-src.list` and run `sudo apt update` again.

**Comment by RockZombie123** [comment]
It gives me an error saying that `Release file for http://raspbian.raspberrypi.org/raspbian/dists/buster/InRelease is not valid yet (invalid for another 7h 3min 38s). Updates for this repository will not be applied.`

**Comment by cycool29** [comment]
`raspbian.raspberrypi.org` often broken. Use `archive.raspberrypi.org` instead.
```
echo "deb http://archive.raspberrypi.org/debian/ buster main
# Uncomment line below then 'apt-get update' to enable 'apt-get source'
deb-src http://archive.raspberrypi.org/debian/ buster main" > /etc/apt/sources.list.d/raspi.list
```

And run `sudo apt update` again.

**Comment by RockZombie123** [comment]
> `raspbian.raspberrypi.org` often broken. Use `archive.raspberrypi.org` instead.
> 
> ```
> echo "deb http://archive.raspberrypi.org/debian/ buster main
> # Uncomment line below then 'apt-get update' to enable 'apt-get source'
> deb-src http://archive.raspberrypi.org/debian/ buster main" > /etc/apt/sources.list.d/raspi.list
> ```
> 
> And run `sudo apt update` again.

You mean do that in `sudo apt edit-resources`?

**Comment by cycool29** [comment]
> > `raspbian.raspberrypi.org` often broken. Use `archive.raspberrypi.org` instead.
> > ```
> > echo "deb http://archive.raspberrypi.org/debian/ buster main
> > # Uncomment line below then 'apt-get update' to enable 'apt-get source'
> > deb-src http://archive.raspberrypi.org/debian/ buster main" > /etc/apt/sources.list.d/raspi.list
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And run `sudo apt update` again.
> 
> You mean do that in `sudo apt edit-resources`?

No, just paste it in terminal and enter.

**Comment by RockZombie123** [comment]
Oh! ok.

**Comment by cycool29** [comment]
How is the progress now? @RockZombie123

**Comment by RockZombie123** [comment]
It gives me the same error: Release file for http://raspbian.raspberrypi.org/raspbian/dists/buster/InRelease is not valid yet (invalid for another 6h 3min 38s). Updates for this repository will not be applied.

**Comment by RockZombie123** [comment]
sorry about the trouble :(

**Comment by cycool29** [comment]
> It gives me the same error: `Release file for http://raspbian.raspberrypi.org/raspbian/dists/buster/InRelease is not valid yet (invalid for another 6h 3min 38s). Updates for this repository will not be applied. `


Weird.
Try `sudo apt edit-sources`, delete `deb http://www.deb-multimedia.org stable main` . Run `sudo apt update again`.

**Comment by RockZombie123** [comment]
@cycool29 ok, I really hope that works...

**Comment by RockZombie123** [comment]
btw, am I supposed to go as root?

**Comment by cycool29** [comment]
> btw, am I supposed to go as root?

What do you mean 'go as root' ? Using `sudo` should make you as root when running commands.

**Comment by RockZombie123** [comment]
`E: Release file for http://raspbian.raspberrypi.org/raspbian/dists/buster/InRelease is not valid yet (invalid for another 6h 22min 39s). Updates for this repository will not be applied.
`

**Comment by RockZombie123** [comment]
:(

**Comment by cycool29** [comment]
That is really weird.
After googling, try `sudo hwclock --hctosys` and `sudo apt update` again.

**Comment by Botspot** [comment]
I think the raspbian repository is not in `raspi.list`, but in `sources.list`. At least on my system it is.

@RockZombie123, if the clock-fix doesn't work, try editing `/etc/apt/sources.list` and comment out a line mentioning "`deb http://raspbian.raspberrypi.org/raspbian/ buster main contrib non-free rpi`".

**Comment by cycool29** [comment]
> I think the raspbian repository is not in `raspi.list`, but in `sources.list`. At least on my system it is.
> 
> @RockZombie123, if the clock-fix doesn't work, try editing `/etc/apt/sources.list` and comment out a line mentioning "`deb http://raspbian.raspberrypi.org/raspbian/ buster main contrib non-free rpi`".

`sudo apt edit-sources` already did that.

**Comment by RockZombie123** [comment]
> That is really weird. After googling, try `sudo hwclock --hctosys` and `sudo apt update` again.
> 
> This command is to synchronize the time between your system and real-world.

Synchronizing clock didn't work, but I have a different way of changing the time & date on my raspberry pi.

**Comment by RockZombie123** [comment]
> /etc/apt/sources.list

I already did that.

**Comment by cycool29** [comment]
> but I have a different way of changing the time & date on my raspberry pi. 

That is not about changing time on your pi, but **synchronize** the time.
If that command won't work, try this:
```
sudo timedatectl set-local-rtc 1
```

**Comment by cycool29** [comment]
You can also try solutions [here](https://www.how2shout.com/linux/fix-inrelease-is-not-valid-yet-invalid-for-another-h-min-s-updates-for-this-repository-will-not-be-applied/). @RockZombie123

**Comment by cycool29** [comment]
How is the progress now? @RockZombie123

**Comment by RockZombie123** [comment]
Sorry, I gotta go, it's night for me, so I will come back tomorrow.

**Comment by RockZombie123** [comment]
btw, I tried syncing time, I think it should work, but should it change the time on my clock?
also, sudo apt update still failed. I'll talk to you tomorrow.

**Comment by cycool29** [comment]
> Sorry, I gotta go, it's night for me, so I will come back tomorrow.

OK, that's fine. it's just afternoon for me lol. Goodnight to you.

**Comment by RockZombie123** [comment]
@cycool29 good morning! at least for me it is lol

**Comment by RockZombie123** [comment]
can ANYONE help me with this?

**Comment by RockZombie123** [comment]
I just found what I wanted to download from pi-apps on flathub.

**Comment by cycool29** [comment]
> I just found what I wanted to download from pi-apps on flathub.

Hey, I just woke up here. So did you solve your apt?
