### ISSUE TITLE
Pycharm Community Edition by JetBrains (both 32-bit & 64-bit respectively)

### ISSUE THREAD

**Issue by fabianmendes** [Botspot/pi-apps#99]
[for 32-bit only (version from 2018.3.7) & 64-bit updatable versions]]

Hi, again @Botspot. I want to open an app request, but mostly I would like to help to integrate it, or at least do the "dirty work" of coding, and then you could write the _easiest_ parts, I don't know. It seems to be very easy to install, there is not any problem to do so manually; but what about doing it faster and _automatic_ alongside the others Pi-apps.

**App request.** As I said, it is pretty easy to install manually, just download the version, unzip, and run _./pycharm.sh_ once.* 
Source: https://www.element14.com/community/community/raspberry-pi/blog/2019/09/12/installing-pycharm-on-raspberry-pi (really thanks to this guy). I've even already memorized the process, **also, it is not necessary to move the folder into the _/opt/_ as it says either**.

Just let me know how can I help, @Botspot. Should I create a fork or something??

Otherwise, and most important: due to having two versions for the Community Edition: the _..-2018.3.7_ version it's the only recent release available for 32-bits OS. Should I create an `install-32 | install-64` option respectively, right?

What may I do to help you for adding it to the Pi-apps?

* as you may see on the link, we only just may check that _pip_, _pip3_, and _openjdk-11-jdk_ are installed.

**Comment by Botspot** [comment]
Pi-Apps uses `bash` scripts to install and uninstall its apps.

A bash script is really just a text file full of **terminal commands**.

So if you know the terminal commands necessary to install your app, then simply paste all the commands into a text file and that's about it.

Pi-Apps has an automated App maker wizard. Launch it by going to Menu -> Preferences -> Pi-Apps Settings. Then click Create app.  
As I said, the wizard should guide you through the whole process, and saves your work as you go.

Once the app is in it's early stages, feel free to send it to me by compressing the relevant folder in `~/pi-apps/apps` as a .ZIP file, then attach that file to this message box.

We'll work together to make the app, and when it's done, I think we'll add it to the official Pi-Apps repository.

**Comment by fabianmendes** [comment]
how can I verify on a system if it's 32-bit or 64-bit? so, then if it is 32-bit do the next process, or if it is 64-bit do this thing. Because I have to specify which bit is the system to download a file or another from JetBrain's website page.

**Comment by Botspot** [comment]
> how can I verify on a system if it's 32-bit or 64-bit? so, then if it is 32-bit do the next process, or if it is 64-bit do this thing. Because I have to specify which bit is the system to download a file or another from JetBrain's website page.

Pi-Apps takes care of OS detection for you. On a 64bit system, Pi-Apps will execute the `install-64` script. On a 32bit system, Pi-Apps will use the `install-32` script.

**Comment by fabianmendes** [comment]
Here is the zip file.
[pycharm_ce.zip](https://github.com/Botspot/pi-apps/files/5604936/pycharm_ce.zip)

**Comment by fabianmendes** [comment]
It's ok! Just let me know anything I should know to learn!

**Comment by Botspot** [comment]
@fabianmendes 
lol
```
mv pycharm-community-2018.3.7 pycharm-community || "Failed to rename pycharm folder "
```

**Comment by Botspot** [comment]
@fabianmendes I don't think putting trademark information into descriptions or credits is necessary or desired.
```
Blender has been registered as a trademark by Blender Foundation in USA and EU. It has been used by Blender Foundation since 2002
```
Keep in mind that Pi-Apps does not distribute any apps at all, but only provides a set of scripts to download & install them from elsewhere. Therefore, we don't have to worry about copyright issues.

**Comment by fabianmendes** [comment]
> @fabianmendes
> haha, look at line 16: (missing `error` command)
> 
> ```
> mv pycharm-community-2018.3.7 pycharm-community || "Failed to rename pycharm folder "
> ```
> 
> And line 22: (Discord electron?)
> 
> ```
> cd /opt/pycharm-community || error "Failed to enter discord-electron folder!"
> ```

Sorry I had copied scripts from Discord like a template and just modify the main stuff.

**Comment by fabianmendes** [comment]
> @fabianmendes I don't think putting trademark information into descriptions or credits is necessary or desired.
> 
> ```
> Blender has been registered as a trademark by Blender Foundation in USA and EU. It has been used by Blender Foundation since 2002
> ```
> 
> Keep in mind that Pi-Apps does not distribute any apps at all, but only provides a set of scripts to download & install them from elsewhere. Therefore, we don't have to worry about copyright issues.

sure, thanks!

**Comment by Botspot** [comment]
@fabianmendes 
Hmm. The `pip` and `pip3` packages do not exist on the repositories. Did you mean `python-pip` and `python3-pip`?

**Comment by fabianmendes** [comment]
Yes I think

**Comment by Botspot** [comment]
> Sorry I had copied scripts from Discord like a template and just modify the main stuff.

Sure you can do that, but are you aware of Pi-Apps' built-in App maker wizard? It guides you through the whole process. Now, you did a really good job with the syntax, but just wanted to make sure you were of the Create App button in Pi-Apps Settings.

**Comment by fabianmendes** [comment]
Yes I did, I've Just did it as an easy way  to write all essentual things properly. Also, thanks again - to you @Botspot

**Comment by Botspot** [comment]
@fabianmendes How is the menu button supposed to be created?

After changing your script, I got it to install correctly, but there's no menu entry in Programming.

**Comment by fabianmendes** [comment]
That's a bit weird, I think it should create automátic after first Run but
you're right, I'm Just  remembering nos that it wont create the entry until
first use. But, it is posible to create an Entry desktop File to put
there.. Sorry about it!

**Comment by fabianmendes** [comment]
I'm trying to share with you the script of the menu applications

**Comment by fabianmendes** [comment]
name: "/home/pi/.local/share/applications/**jetbrains-pycharm-ce.desktop**"

```

[Desktop Entry]
Version=1.0
Type=Application
Name=PyCharm Community Edition
Icon=/opt/pycharm-community/bin/pycharm.svg
Exec="/opt/pycharm-community/bin/pycharm.sh" %f
Comment=Python IDE for Professional Developers
Categories=Development;IDE;
Terminal=false
StartupWMClass=jetbrains-pycharm-ce

```

**Comment by Botspot** [comment]
Perfect. We can run this command to create the desktop file during install:
```
echo "[Desktop Entry]
Version=1.0
Type=Application
Name=PyCharm Community Edition
Icon=/opt/pycharm-community/bin/pycharm.svg
Exec=/opt/pycharm-community/bin/pycharm.sh %f
Comment=Python IDE for Professional Developers
Categories=Development;IDE;
Terminal=false
StartupWMClass=jetbrains-pycharm-ce" > ~/.local/share/applications/jetbrains-pycharm-ce.desktop
```

**Comment by fabianmendes** [comment]
Good, all right!

**Comment by Botspot** [comment]
@fabianmendes Do you think you could find an armhf release of Pycharm from 2020?  
2018 is rather old.

**Comment by fabianmendes** [comment]
The 2018 is only for 32-bit, there is not new realease for 32bit and wont
be any more. Anyways, for 64bits, The newest pycharm versions do! At no n
the script (wget..) should be the current lastest version

**Comment by Botspot** [comment]
One more thing: If we shortened the name to "Pycharm", would that be okay?

**Comment by fabianmendes** [comment]
Just to "Pycharm Community", or "Pycharm CE". Because there is another (and
purchable) profesional versión!

**Comment by Botspot** [comment]
Okay I've now added Pycharm CE to Pi-Apps as of commit 157e1ba1ccd8a07df4bd3a6c7d750f7344a68d58.

**Comment by Botspot** [comment]
@fabianmendes, do you have any suggestions for the issue one of our users is having?

https://github.com/Botspot/pi-apps/issues/924
